/**
 * Trafik işaretleri kataloğu (Program 1 · Görsel Dönüşüm Bölüm 1). ÖZGÜN eğitimsel sunum.
 * Standart şekil/renk (serbest) kullanılır; çizim dili kendimize aittir (telif-güvenli).
 * Her işaret: resmî anlam + hafıza tekniği + sınav önemi + sık hata + ilgili ders.
 */

export type SignCategory =
  'tehlike' | 'yasak' | 'mecburiyet' | 'bilgi' | 'park' | 'otoyol' | 'gecici' | 'oncelik';

export type SignShape =
  | 'triangle'
  | 'inv-triangle'
  | 'ring'
  | 'disc'
  | 'rect-blue'
  | 'rect-green'
  | 'octagon'
  | 'diamond';

export const CATEGORY_LABEL: Record<SignCategory, string> = {
  tehlike: 'Tehlike Uyarı',
  yasak: 'Yasaklayıcı / Kısıtlayıcı',
  mecburiyet: 'Mecburiyet',
  bilgi: 'Bilgi',
  park: 'Duraklama & Park',
  otoyol: 'Otoyol & Yönlendirme',
  gecici: 'Geçici / Çalışma',
  oncelik: 'Öncelik (DUR / Yol Ver)',
};

export type ExamImportance = 'çok yüksek' | 'yüksek' | 'orta';

export interface TrafficSign {
  id: string;
  category: SignCategory;
  name: string;
  shape: SignShape;
  glyph?: string;
  glyphText?: string;
  meaning: string;
  memoryTip: string;
  examImportance: ExamImportance;
  commonMistake?: string;
  relatedLessonSlug?: string;
  keywords: string[];
}

export const SIGNS: TrafficSign[] = [
  // ——— TEHLİKE UYARI (üçgen, kırmızı kenar) ———
  {
    id: 'kaygan-yol',
    category: 'tehlike',
    name: 'Kaygan Yol',
    shape: 'triangle',
    glyph: 'slippery',
    meaning: 'İleride zemin kaygandır; kaymaya karşı hız düşürülür ve ani manevradan kaçınılır.',
    memoryTip: 'Üçgen = dikkat; kayan araç sembolü = zemin kaygan.',
    examImportance: 'yüksek',
    commonMistake: 'Kuru havada da olsa hızı korumak.',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['kaygan', 'buz', 'yagmur', 'kayma'],
  },
  {
    id: 'tehlikeli-viraj-sol',
    category: 'tehlike',
    name: 'Sola Tehlikeli Viraj',
    shape: 'triangle',
    glyph: 'curveLeft',
    meaning: 'İleride sola keskin viraj vardır; hız düşürülür.',
    memoryTip: 'Okun büküldüğü yön = virajın yönü.',
    examImportance: 'yüksek',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['viraj', 'sol', 'donemec'],
  },
  {
    id: 'tehlikeli-viraj-sag',
    category: 'tehlike',
    name: 'Sağa Tehlikeli Viraj',
    shape: 'triangle',
    glyph: 'curveRight',
    meaning: 'İleride sağa keskin viraj vardır; hız düşürülür.',
    memoryTip: 'Okun büküldüğü yön = virajın yönü.',
    examImportance: 'yüksek',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['viraj', 'sag', 'donemec'],
  },
  {
    id: 'devamli-viraj',
    category: 'tehlike',
    name: 'Devamlı Virajlar',
    shape: 'triangle',
    glyph: 'sCurve',
    meaning: 'Birbirini izleyen virajlar vardır; sürekli dikkat ve düşük hız gerekir.',
    memoryTip: 'S çizgisi = arka arkaya viraj.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['viraj', 'devamli', 's'],
  },
  {
    id: 'tumsek',
    category: 'tehlike',
    name: 'Tümsek',
    shape: 'triangle',
    glyph: 'bump',
    meaning: 'Yol yüzeyinde tümsek vardır; hız düşürülür.',
    memoryTip: 'Kambur çizgi = yol kabarması.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['tumsek', 'kasis'],
  },
  {
    id: 'yaya-geciti-tehlike',
    category: 'tehlike',
    name: 'Yaya Geçidi (yaklaşım)',
    shape: 'triangle',
    glyph: 'pedestrian',
    meaning: 'İleride yaya geçidi vardır; yavaşla, yayaya öncelik ver.',
    memoryTip: 'Üçgen içinde yürüyen figür = geçit yaklaşıyor.',
    examImportance: 'çok yüksek',
    commonMistake: 'Yaya geçidinde yayaya yol vermemek.',
    relatedLessonSlug: 'yaya-gecidi',
    keywords: ['yaya', 'gecit', 'oncelik'],
  },
  {
    id: 'okul-gecidi',
    category: 'tehlike',
    name: 'Okul Geçidi / Çocuklar',
    shape: 'triangle',
    glyph: 'children',
    meaning: 'İleride okul/çocukların bulunduğu bölge vardır; çok yavaş ve dikkatli sürülür.',
    memoryTip: 'İki çocuk figürü = okul bölgesi.',
    examImportance: 'yüksek',
    relatedLessonSlug: 'yaya-gecidi',
    keywords: ['okul', 'cocuk'],
  },
  {
    id: 'ehli-hayvan',
    category: 'tehlike',
    name: 'Ehli Hayvan Çıkabilir',
    shape: 'triangle',
    glyph: 'animal',
    meaning: 'Yola evcil/çiftlik hayvanı çıkabilir; hız düşürülür.',
    memoryTip: 'Hayvan silüeti = ani çıkış riski.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['hayvan', 'ciftlik'],
  },
  {
    id: 'donel-kavsak-yaklasim',
    category: 'tehlike',
    name: 'Dönel Kavşak (yaklaşım)',
    shape: 'triangle',
    glyph: 'roundabout',
    meaning: 'İleride dönel kavşak vardır; yavaşla, içerideki araca yol ver.',
    memoryTip: 'Dairesel oklar = ada etrafında dönüş.',
    examImportance: 'yüksek',
    relatedLessonSlug: 'kavsak-uygulama',
    keywords: ['donel', 'kavsak', 'ada'],
  },
  {
    id: 'yol-daralmasi',
    category: 'tehlike',
    name: 'Yol Daralması',
    shape: 'triangle',
    glyph: 'narrow',
    meaning: 'Yol ileride daralır; hız ayarlanır, karşıdan gelene dikkat edilir.',
    memoryTip: 'İçe kapanan çizgiler = daralma.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['daralma', 'dar'],
  },
  {
    id: 'iki-yonlu-trafik',
    category: 'tehlike',
    name: 'İki Yönlü Trafik',
    shape: 'triangle',
    glyph: 'twoway',
    meaning: 'İleride karşılıklı iki yönlü trafik başlar; sollama ve mesafede dikkat.',
    memoryTip: 'Zıt iki ok = karşılıklı akış.',
    examImportance: 'orta',
    relatedLessonSlug: 'sollama-serit',
    keywords: ['iki-yonlu', 'karsi'],
  },
  {
    id: 'isikli-isaret-yaklasim',
    category: 'tehlike',
    name: 'Işıklı İşaret Cihazı',
    shape: 'triangle',
    glyph: 'light',
    meaning: 'İleride trafik ışıkları vardır; yaklaşırken hazır ol.',
    memoryTip: 'Üç renkli kutu = trafik lambası.',
    examImportance: 'yüksek',
    relatedLessonSlug: 'kavsak-oncelik',
    keywords: ['isik', 'lamba', 'trafik-isigi'],
  },
  {
    id: 'egimli-inis',
    category: 'tehlike',
    name: 'Tehlikeli Eğim (iniş)',
    shape: 'triangle',
    glyph: 'hillDown',
    meaning: 'Dik iniş vardır; motor freninden yararlan, hızı kontrol et.',
    memoryTip: 'Aşağı inen yokuş = iniş eğimi.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['egim', 'inis', 'yokus'],
  },
  {
    id: 'hemzemin-gecit',
    category: 'tehlike',
    name: 'Demiryolu Hemzemin Geçit',
    shape: 'triangle',
    glyph: 'levelCross',
    meaning: 'Bariyersiz/bariyerli tren geçidi yaklaşır; dur-bak-dinle, tren varsa geçme.',
    memoryTip: 'Ray + bariyer çizgisi = tren geçidi.',
    examImportance: 'yüksek',
    commonMistake: 'Bariyer inerken geçmeye çalışmak.',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['tren', 'demiryolu', 'hemzemin', 'bariyer'],
  },

  // ——— YASAKLAYICI / KISITLAYICI (kırmızı çember) ———
  {
    id: 'azami-hiz-20',
    category: 'yasak',
    name: 'Azami Hız 20',
    shape: 'ring',
    glyphText: '20',
    meaning: 'Bu kesimde en yüksek hız 20 km/saattir.',
    memoryTip: 'Kırmızı çember + rakam = üst hız sınırı.',
    examImportance: 'çok yüksek',
    relatedLessonSlug: 'hiz-takip',
    keywords: ['hiz', 'azami', '20'],
  },
  {
    id: 'azami-hiz-30',
    category: 'yasak',
    name: 'Azami Hız 30',
    shape: 'ring',
    glyphText: '30',
    meaning: 'Bu kesimde en yüksek hız 30 km/saattir (genelde okul/yerleşim içi).',
    memoryTip: 'Kırmızı çember + rakam = üst hız sınırı.',
    examImportance: 'çok yüksek',
    relatedLessonSlug: 'hiz-takip',
    keywords: ['hiz', 'azami', '30', 'okul'],
  },
  {
    id: 'azami-hiz-50',
    category: 'yasak',
    name: 'Azami Hız 50',
    shape: 'ring',
    glyphText: '50',
    meaning: 'Bu kesimde en yüksek hız 50 km/saattir (yerleşim içi genel sınır).',
    memoryTip: 'Levha varsa levha, yoksa yerleşim içi 50.',
    examImportance: 'çok yüksek',
    commonMistake: 'Levha değeri ile genel sınırı karıştırmak.',
    relatedLessonSlug: 'hiz-takip',
    keywords: ['hiz', 'azami', '50', 'sehir'],
  },
  {
    id: 'azami-hiz-70',
    category: 'yasak',
    name: 'Azami Hız 70',
    shape: 'ring',
    glyphText: '70',
    meaning: 'Bu kesimde en yüksek hız 70 km/saattir.',
    memoryTip: 'Kırmızı çember + rakam = üst hız sınırı.',
    examImportance: 'yüksek',
    relatedLessonSlug: 'hiz-takip',
    keywords: ['hiz', 'azami', '70'],
  },
  {
    id: 'sollama-yasak',
    category: 'yasak',
    name: 'Sollama Yasağı',
    shape: 'ring',
    glyph: 'twoCars',
    meaning: 'Bu kesimde öndeki aracı sollamak yasaktır.',
    memoryTip: 'İki araç + kırmızı = geçme yok.',
    examImportance: 'çok yüksek',
    commonMistake: 'Yasağın bittiği yeri gözden kaçırmak.',
    relatedLessonSlug: 'sollama-serit',
    keywords: ['sollama', 'gecme', 'yasak'],
  },
  {
    id: 'donus-yasak-sol',
    category: 'yasak',
    name: 'Sola Dönülmez',
    shape: 'ring',
    glyph: 'arrowLeft',
    meaning: 'Bu kavşakta sola dönüş yasaktır.',
    memoryTip: 'Kırmızı çember + sol ok = sola dönme.',
    examImportance: 'yüksek',
    relatedLessonSlug: 'kavsak-oncelik',
    keywords: ['donus', 'sol', 'yasak'],
  },
  {
    id: 'donus-yasak-sag',
    category: 'yasak',
    name: 'Sağa Dönülmez',
    shape: 'ring',
    glyph: 'arrowRight',
    meaning: 'Bu kavşakta sağa dönüş yasaktır.',
    memoryTip: 'Kırmızı çember + sağ ok = sağa dönme.',
    examImportance: 'yüksek',
    relatedLessonSlug: 'kavsak-oncelik',
    keywords: ['donus', 'sag', 'yasak'],
  },
  {
    id: 'tasit-giremez',
    category: 'yasak',
    name: 'Taşıt Trafiğine Kapalı',
    shape: 'ring',
    glyph: 'noStop',
    meaning: 'Bu yola taşıt giremez.',
    memoryTip: 'Boş kırmızı çember = araç girişi kapalı.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['giremez', 'kapali', 'tasit'],
  },
  {
    id: 'bisiklet-giremez',
    category: 'yasak',
    name: 'Bisiklet Giremez',
    shape: 'ring',
    glyph: 'bike',
    meaning: 'Bu yola bisiklet giremez.',
    memoryTip: 'Bisiklet + kırmızı = giriş yok.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['bisiklet', 'giremez'],
  },
  {
    id: 'otomobil-giremez',
    category: 'yasak',
    name: 'Otomobil Giremez',
    shape: 'ring',
    glyph: 'car',
    meaning: 'Bu yola otomobil giremez.',
    memoryTip: 'Otomobil + kırmızı = giriş yok.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['otomobil', 'giremez'],
  },

  // ——— MECBURİYET (mavi daire) ———
  {
    id: 'ileri-mecburi',
    category: 'mecburiyet',
    name: 'İleri Mecburi Yön',
    shape: 'disc',
    glyph: 'arrowStraight',
    meaning: 'Sadece ileri gidilebilir.',
    memoryTip: 'Mavi daire + ok = zorunlu yön.',
    examImportance: 'yüksek',
    commonMistake: 'Mavi (zorunlu) ile kırmızıyı (yasak) karıştırmak.',
    relatedLessonSlug: 'kavsak-oncelik',
    keywords: ['mecburi', 'ileri', 'yon'],
  },
  {
    id: 'saga-mecburi',
    category: 'mecburiyet',
    name: 'Sağa Mecburi Yön',
    shape: 'disc',
    glyph: 'arrowRight',
    meaning: 'Sadece sağa dönülebilir.',
    memoryTip: 'Mavi daire + sağ ok = zorunlu sağ.',
    examImportance: 'yüksek',
    relatedLessonSlug: 'kavsak-oncelik',
    keywords: ['mecburi', 'sag', 'yon'],
  },
  {
    id: 'sola-mecburi',
    category: 'mecburiyet',
    name: 'Sola Mecburi Yön',
    shape: 'disc',
    glyph: 'arrowLeft',
    meaning: 'Sadece sola dönülebilir.',
    memoryTip: 'Mavi daire + sol ok = zorunlu sol.',
    examImportance: 'yüksek',
    relatedLessonSlug: 'kavsak-oncelik',
    keywords: ['mecburi', 'sol', 'yon'],
  },
  {
    id: 'donel-mecburi',
    category: 'mecburiyet',
    name: 'Ada Etrafında Dönünüz',
    shape: 'disc',
    glyph: 'roundabout',
    meaning: 'Dönel kavşakta ada etrafında belirtilen yönde dönülür.',
    memoryTip: 'Mavi daire + dönme okları = ada etrafı.',
    examImportance: 'yüksek',
    relatedLessonSlug: 'kavsak-uygulama',
    keywords: ['donel', 'ada', 'mecburi'],
  },
  {
    id: 'bisiklet-yolu',
    category: 'mecburiyet',
    name: 'Bisiklet Yolu',
    shape: 'disc',
    glyph: 'bike',
    meaning: 'Bu yol bisikletlilere ayrılmıştır.',
    memoryTip: 'Mavi daire + bisiklet = bisiklet yolu.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['bisiklet', 'yol'],
  },

  // ——— BİLGİ (mavi dikdörtgen) ———
  {
    id: 'hastane',
    category: 'bilgi',
    name: 'Hastane',
    shape: 'rect-blue',
    glyph: 'hospital',
    meaning: 'Yakında hastane vardır; gürültüden kaçın, dikkatli sür.',
    memoryTip: 'Mavi zemin + artı = sağlık/hastane.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['hastane', 'saglik'],
  },
  {
    id: 'yaya-gecidi-bilgi',
    category: 'bilgi',
    name: 'Yaya Geçidi (bilgi)',
    shape: 'rect-blue',
    glyph: 'pedestrian',
    meaning: 'Burada yaya geçidi bulunur; yayaya öncelik ver.',
    memoryTip: 'Mavi kare + yürüyen = geçit yeri.',
    examImportance: 'yüksek',
    relatedLessonSlug: 'yaya-gecidi',
    keywords: ['yaya', 'gecit', 'bilgi'],
  },
  {
    id: 'park-yeri-bilgi',
    category: 'bilgi',
    name: 'Park Yeri',
    shape: 'rect-blue',
    glyph: 'parkingP',
    meaning: 'Burada park etmek serbesttir.',
    memoryTip: 'Mavi + P = park izni.',
    examImportance: 'orta',
    relatedLessonSlug: 'park-manevra',
    keywords: ['park', 'p', 'yer'],
  },

  // ——— DURAKLAMA & PARK ———
  {
    id: 'park-serbest',
    category: 'park',
    name: 'Park Serbest (P)',
    shape: 'rect-blue',
    glyph: 'parkingP',
    meaning: 'Belirtilen alanda park etmek serbesttir.',
    memoryTip: 'Mavi P = izin.',
    examImportance: 'yüksek',
    relatedLessonSlug: 'park-manevra',
    keywords: ['park', 'serbest', 'p'],
  },
  {
    id: 'park-yasak',
    category: 'park',
    name: 'Parketmek Yasaktır',
    shape: 'ring',
    glyph: 'parkingP',
    meaning: 'Bu kesimde park etmek yasaktır (duraklama olabilir).',
    memoryTip: 'Kırmızı çember + P = park yasak.',
    examImportance: 'yüksek',
    commonMistake: 'Park ile duraklama yasağını karıştırmak.',
    relatedLessonSlug: 'park-manevra',
    keywords: ['park', 'yasak'],
  },
  {
    id: 'duraklama-yasak',
    category: 'park',
    name: 'Duraklamak Yasaktır',
    shape: 'ring',
    glyph: 'cross',
    meaning: 'Bu kesimde duraklamak da park etmek de yasaktır.',
    memoryTip: 'Çapraz X = hiç durma.',
    examImportance: 'yüksek',
    relatedLessonSlug: 'park-manevra',
    keywords: ['duraklama', 'yasak'],
  },

  // ——— OTOYOL & YÖNLENDİRME ———
  {
    id: 'otoyol-baslangic',
    category: 'otoyol',
    name: 'Otoyol Başlangıcı',
    shape: 'rect-green',
    glyph: 'arrowStraight',
    meaning: 'Otoyol başlar; asgari/azami hız ve otoyol kuralları geçerli olur.',
    memoryTip: 'Yeşil zemin = otoyol.',
    examImportance: 'orta',
    relatedLessonSlug: 'hiz-takip',
    keywords: ['otoyol', 'yesil'],
  },
  {
    id: 'devlet-yolu',
    category: 'otoyol',
    name: 'Devlet Yolu Yönlendirme',
    shape: 'rect-blue',
    glyph: 'arrowStraight',
    meaning: 'Devlet yolu yön/mesafe bilgisi verir.',
    memoryTip: 'Mavi zemin = devlet yolu yönlendirme.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['devlet-yolu', 'yon', 'mavi'],
  },

  // ——— GEÇİCİ / ÇALIŞMA (sarı zemin — burada üçgen ile stilize) ———
  {
    id: 'yol-calismasi',
    category: 'gecici',
    name: 'Yolda Çalışma',
    shape: 'triangle',
    glyph: 'digger',
    meaning:
      'İleride yol çalışması vardır (gerçek levha sarı zeminlidir); yavaşla, işçilere dikkat.',
    memoryTip: 'Sarı zemin = geçici durum; kürek/iş makinesi = çalışma.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['calisma', 'yol', 'gecici', 'sari'],
  },
  {
    id: 'gevsek-malzeme',
    category: 'gecici',
    name: 'Gevşek Malzeme',
    shape: 'triangle',
    glyph: 'exclam',
    meaning: 'Yolda gevşek mıcır/malzeme vardır; hız düşür, takip mesafesini artır.',
    memoryTip: 'Geçici uyarı = dikkat + yavaşla.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['gevsek', 'micir', 'malzeme'],
  },

  // ——— ÖNCELİK (özel şekiller) ———
  {
    id: 'dur',
    category: 'oncelik',
    name: 'DUR',
    shape: 'octagon',
    meaning: 'Araç durma çizgisinden önce TAM durur ve geçiş üstünlüğü olana yol verir.',
    memoryTip: 'Sekizgen = sadece DUR bu şekle sahiptir.',
    examImportance: 'çok yüksek',
    commonMistake: 'Yavaşlayıp durmadan geçmek.',
    relatedLessonSlug: 'kavsak-oncelik',
    keywords: ['dur', 'stop', 'tam-dur'],
  },
  {
    id: 'yol-ver',
    category: 'oncelik',
    name: 'Yol Ver',
    shape: 'inv-triangle',
    meaning: 'Geçiş üstünlüğü olan trafiğe yol verilir; gerekirse durulur.',
    memoryTip: 'Ters üçgen = yol ver (benzersiz şekil).',
    examImportance: 'çok yüksek',
    relatedLessonSlug: 'kavsak-oncelik',
    keywords: ['yol-ver', 'oncelik'],
  },
  {
    id: 'ana-yol',
    category: 'oncelik',
    name: 'Ana Yol',
    shape: 'diamond',
    meaning: 'Bulunduğun yol ana yoldur; tali yoldan çıkanlar sana yol verir.',
    memoryTip: 'Sarı eşkenar dörtgen = ana yol.',
    examImportance: 'yüksek',
    relatedLessonSlug: 'kavsak-oncelik',
    keywords: ['ana-yol', 'oncelik', 'tali'],
  },

  // ——— EK: TEHLİKE UYARI (üçgen) ———
  {
    id: 'dikkat',
    category: 'tehlike',
    name: 'Dikkat',
    shape: 'triangle',
    glyph: 'exclam',
    meaning:
      'Diğer levhalarla ayrıca belirtilmeyen bir tehlike vardır; hız düşürülür ve çevre dikkatle izlenir.',
    memoryTip: 'Ünlem = adı konmamış tehlike; ne olduğunu göremiyorsan önce yavaşla.',
    examImportance: 'yüksek',
    commonMistake: 'Somut bir tehlike görünmediği için hızı hiç azaltmamak.',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['dikkat', 'unlem', 'genel-tehlike'],
  },
  {
    id: 'dik-cikis',
    category: 'tehlike',
    name: 'Tehlikeli Eğim (çıkış)',
    shape: 'triangle',
    glyph: 'hillUp',
    meaning:
      'İleride dik yokuş çıkışı vardır; uygun vites seçilir, öndeki yavaş araçlara dikkat edilir.',
    memoryTip: 'Yukarı tırmanan rampa = çıkış; iniş levhasının aynadaki kardeşi.',
    examImportance: 'orta',
    commonMistake: 'Yüksek viteste rampaya girip aracı boğmak.',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['egim', 'cikis', 'rampa', 'yokus'],
  },
  {
    id: 'sagdan-daralma',
    category: 'tehlike',
    name: 'Sağdan Daralan Kaplama',
    shape: 'triangle',
    glyph: 'narrowRight',
    meaning:
      'Yol ileride sağ taraftan daralır; sağdaki kenar ve engellere dikkat edilerek hız ayarlanır.',
    memoryTip: 'Hangi çizgi içe kırılıyorsa daralma o taraftadır: sağ çizgi içeride = sağdan.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['daralma', 'sag', 'kaplama'],
  },
  {
    id: 'soldan-daralma',
    category: 'tehlike',
    name: 'Soldan Daralan Kaplama',
    shape: 'triangle',
    glyph: 'narrowLeft',
    meaning:
      'Yol ileride sol taraftan daralır; karşı yönden gelenlere ve sol kenara dikkat edilir.',
    memoryTip: 'İçe kırılan sol çizgi = daralma solda.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['daralma', 'sol', 'kaplama'],
  },
  {
    id: 'kasisli-yol',
    category: 'tehlike',
    name: 'Kasisli Yol',
    shape: 'triangle',
    glyph: 'bump',
    meaning:
      'Yol yüzeyi ileride bozuk, çukurlu veya kasislidir; hız düşürülür, ani manevradan kaçınılır.',
    memoryTip: 'Tümsek tek kabarmadır; kasis art arda bozuk zemin demektir.',
    examImportance: 'orta',
    commonMistake: 'Tümsek levhası ile karıştırmak; kasiste kesim boyunca yavaş gitmek gerekir.',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['kasis', 'bozuk', 'cukur'],
  },
  {
    id: 'yandan-ruzgar',
    category: 'tehlike',
    name: 'Yandan Rüzgâr',
    shape: 'triangle',
    glyph: 'wind',
    meaning:
      'Bu kesimde şiddetli yan rüzgâr esebilir; araç savrulabilir, direksiyon iki elle kavranır ve hız düşürülür.',
    memoryTip: 'Şişen tulum, rüzgârın estiği yönü ve şiddetini gösterir.',
    examImportance: 'orta',
    commonMistake: 'Köprü ve viyadük çıkışlarındaki ani rüzgârı hesaba katmamak.',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['ruzgar', 'yan', 'savrulma', 'tulum'],
  },
  {
    id: 'dusen-kaya',
    category: 'tehlike',
    name: 'Düşen Kaya',
    shape: 'triangle',
    glyph: 'rocks',
    meaning:
      'Yamaçtan yola kaya veya taş düşebilir; yol üzerinde düşmüş parçalar olabilir, yavaş ve dikkatli geçilir.',
    memoryTip: 'Yamaçtan yuvarlanan taşlar = hem yukarıya hem yola bak.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['kaya', 'heyelan', 'tas'],
  },
  {
    id: 'deniz-kiyisi',
    category: 'tehlike',
    name: 'Deniz veya Nehir Kıyısında Biten Yol',
    shape: 'triangle',
    glyph: 'quay',
    meaning:
      'Yol ileride iskele, rıhtım veya kıyıda biter; suya düşme tehlikesine karşı çok yavaş yaklaşılır.',
    memoryTip: 'Suya doğru kayan araç silüeti = yolun sonunda su var, fren payı bırak.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['kiyi', 'iskele', 'rihtim', 'su'],
  },
  {
    id: 'alcak-ucus',
    category: 'tehlike',
    name: 'Alçak Uçuş Bölgesi',
    shape: 'triangle',
    glyph: 'airplane',
    meaning:
      'Havaalanı yakınıdır; alçaktan geçen uçağın ani gürültüsü sürücüyü irkiltebilir, direksiyon hâkimiyeti korunur.',
    memoryTip: 'Uçak silüeti = gürültüye hazırlıklı ol, panik yapma.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['ucak', 'havaalani', 'gurultu'],
  },
  {
    id: 'tramvay-hatti',
    category: 'tehlike',
    name: 'Tramvay Hattı ile Kesişme',
    shape: 'triangle',
    glyph: 'tram',
    meaning:
      'İleride yol tramvay hattı ile kesişir; raylı taşıt yönünü değiştiremez ve geç durur, geçiş üstünlüğü tramvaya bırakılır.',
    memoryTip: 'Raydaki sana yol veremez; yolu sen ver.',
    examImportance: 'yüksek',
    commonMistake: 'Tramvayın kısa mesafede durabileceğini sanmak.',
    relatedLessonSlug: 'kavsak-oncelik',
    keywords: ['tramvay', 'ray', 'kesisme'],
  },
  {
    id: 'vahsi-hayvan',
    category: 'tehlike',
    name: 'Vahşi Hayvanlar Geçebilir',
    shape: 'triangle',
    glyph: 'deer',
    meaning:
      'Yola yaban hayvanı çıkabilir; özellikle gece ve alacakaranlıkta hız düşürülür, ani şerit değişiminden kaçınılır.',
    memoryTip: 'Geyik silüeti = orman kesimi; en riskli saatler gün batımı ve şafak.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['vahsi', 'geyik', 'orman', 'hayvan'],
  },
  {
    id: 'kontrolsuz-kavsak',
    category: 'tehlike',
    name: 'Kontrolsüz Kavşak',
    shape: 'triangle',
    glyph: 'cross',
    meaning:
      'İleride ışık veya işaretle düzenlenmemiş kavşak vardır; genel kural gereği sağdan gelen araca yol verilir.',
    memoryTip: 'Işık yoksa kural var: sağdaki kazanır.',
    examImportance: 'çok yüksek',
    commonMistake: 'Kendi yolunu ana yol sanıp sağdan gelene yol vermemek.',
    relatedLessonSlug: 'kavsak-oncelik',
    keywords: ['kavsak', 'kontrolsuz', 'sagdan-gelen'],
  },
  {
    id: 'anayol-tali-kavsak',
    category: 'tehlike',
    name: 'Ana Yol - Tali Yol Kavşağı',
    shape: 'triangle',
    glyph: 'cross',
    meaning:
      'İleride tali yolların bağlandığı bir kavşak vardır; öncelik ana yoldaki sürücünündür, yine de tali yoldan çıkanlara karşı dikkatli olunur.',
    memoryTip: 'Öncelik sende ama gözün tali yolda olsun.',
    examImportance: 'yüksek',
    relatedLessonSlug: 'kavsak-oncelik',
    keywords: ['ana-yol', 'tali', 'kavsak'],
  },
  {
    id: 'bisiklet-gecebilir',
    category: 'tehlike',
    name: 'Bisikletli Geçebilir',
    shape: 'triangle',
    glyph: 'bike',
    meaning:
      'İleride bisiklet yolunun taşıt yolu ile kesiştiği kesim vardır; bisikletliye dikkat edilir, gerekirse yol verilir.',
    memoryTip: 'Üçgendeki bisiklet uyarır, çemberdeki bisiklet yasaklar.',
    examImportance: 'orta',
    commonMistake: 'Uyarı üçgenini bisiklet giremez yasağı sanmak.',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['bisiklet', 'kesisme', 'uyari'],
  },
  {
    id: 'gizli-buzlanma',
    category: 'tehlike',
    name: 'Gizli Buzlanma',
    shape: 'triangle',
    glyph: 'snow',
    meaning:
      'Yol yüzeyinde fark edilmesi güç buzlanma olabilir; hız düşürülür, ani fren ve ani direksiyon hareketinden kaçınılır.',
    memoryTip: 'Kar tanesini gördüysen buzu göremeyebilirsin: köprü üstleri önce donar.',
    examImportance: 'yüksek',
    commonMistake: 'Havayı açık görüp gölgeli kesim ve köprülerdeki buzu hesaba katmamak.',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['buz', 'don', 'kaygan', 'kis'],
  },

  // ——— EK: YASAKLAYICI / KISITLAYICI (kırmızı çember) ———
  {
    id: 'kamyon-giremez',
    category: 'yasak',
    name: 'Kamyon Giremez',
    shape: 'ring',
    glyph: 'truck',
    meaning: 'Bu yola kamyonların girmesi yasaktır.',
    memoryTip: 'Çemberin içindeki kimse, giremeyen odur: kamyon içeride = kamyon dışarıda.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['kamyon', 'giremez', 'yasak'],
  },
  {
    id: 'otobus-giremez',
    category: 'yasak',
    name: 'Otobüs Giremez',
    shape: 'ring',
    glyph: 'bus',
    meaning: 'Bu yola otobüslerin girmesi yasaktır.',
    memoryTip: 'Kırmızı çember + otobüs = otobüse kapalı yol.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['otobus', 'giremez', 'yasak'],
  },
  {
    id: 'motosiklet-giremez',
    category: 'yasak',
    name: 'Motosiklet Giremez',
    shape: 'ring',
    glyph: 'motorcycle',
    meaning: 'Bu yola motosikletlerin girmesi yasaktır.',
    memoryTip: 'Kırmızı çember + motosiklet = iki teker giremez.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['motosiklet', 'giremez', 'yasak'],
  },
  {
    id: 'traktor-giremez',
    category: 'yasak',
    name: 'Traktör Giremez',
    shape: 'ring',
    glyph: 'tractor',
    meaning: 'Bu yola lastik tekerlekli traktörlerin girmesi yasaktır.',
    memoryTip: 'Hızlı akan yola yavaş araç sokulmaz: traktör çemberde = dışarıda.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['traktor', 'giremez', 'yasak'],
  },
  {
    id: 'el-arabasi-giremez',
    category: 'yasak',
    name: 'El Arabası Giremez',
    shape: 'ring',
    glyph: 'handcart',
    meaning: 'Bu yola el ile sürülen ve çekilen araçların girmesi yasaktır.',
    memoryTip: 'İnsan gücüyle iten girmez: el arabası çemberde.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['el-arabasi', 'giremez', 'yasak'],
  },
  {
    id: 'at-arabasi-giremez',
    category: 'yasak',
    name: 'At Arabası Giremez',
    shape: 'ring',
    glyph: 'horseCart',
    meaning: 'Bu yola hayvanla çekilen taşıtların girmesi yasaktır.',
    memoryTip: 'Hayvan gücüyle çekilen çemberde = giremez.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['at-arabasi', 'hayvanla-cekilen', 'giremez'],
  },
  {
    id: 'yaya-giremez',
    category: 'yasak',
    name: 'Yaya Giremez',
    shape: 'ring',
    glyph: 'pedestrian',
    meaning: 'Bu yola yayaların girmesi yasaktır (örneğin otoyollar).',
    memoryTip: 'Çemberdeki yürüyen figür = yürüyene kapalı yol.',
    examImportance: 'orta',
    commonMistake: 'Mavi daireli yaya yolu levhası ile karıştırmak.',
    relatedLessonSlug: 'yaya-gecidi',
    keywords: ['yaya', 'giremez', 'yasak'],
  },
  {
    id: 'u-donusu-yasak',
    category: 'yasak',
    name: 'U Dönüşü Yapılmaz',
    shape: 'ring',
    glyph: 'uTurn',
    meaning:
      'Bu kesimde geriye dönüş (U dönüşü) yapmak yasaktır; sola dönüş ayrıca yasaklanmadıysa yapılabilir.',
    memoryTip: 'U harfi çizen ok + kırmızı = geri dönmek yok.',
    examImportance: 'yüksek',
    commonMistake: 'U dönüşü yasağını sola dönüş yasağı sanmak; ikisi ayrı levhalardır.',
    relatedLessonSlug: 'kavsak-oncelik',
    keywords: ['u-donusu', 'geri-donus', 'yasak'],
  },
  {
    id: 'azami-hiz-40',
    category: 'yasak',
    name: 'Azami Hız 40',
    shape: 'ring',
    glyphText: '40',
    meaning: 'Bu kesimde en yüksek hız 40 km/saattir.',
    memoryTip: 'Kırmızı çember + rakam = tavan hız; üstüne çıkılmaz.',
    examImportance: 'yüksek',
    relatedLessonSlug: 'hiz-takip',
    keywords: ['hiz', 'azami', '40'],
  },
  {
    id: 'azami-hiz-60',
    category: 'yasak',
    name: 'Azami Hız 60',
    shape: 'ring',
    glyphText: '60',
    meaning: 'Bu kesimde en yüksek hız 60 km/saattir.',
    memoryTip: 'Levha varsa levha konuşur; genel sınır susar.',
    examImportance: 'yüksek',
    relatedLessonSlug: 'hiz-takip',
    keywords: ['hiz', 'azami', '60'],
  },
  {
    id: 'azami-hiz-80',
    category: 'yasak',
    name: 'Azami Hız 80',
    shape: 'ring',
    glyphText: '80',
    meaning: 'Bu kesimde en yüksek hız 80 km/saattir.',
    memoryTip: 'Kırmızı çember + rakam = üst hız sınırı.',
    examImportance: 'yüksek',
    relatedLessonSlug: 'hiz-takip',
    keywords: ['hiz', 'azami', '80'],
  },
  {
    id: 'azami-hiz-90',
    category: 'yasak',
    name: 'Azami Hız 90',
    shape: 'ring',
    glyphText: '90',
    meaning:
      'Bu kesimde en yüksek hız 90 km/saattir; otomobiller için yerleşim yeri dışındaki iki yönlü yolların genel sınırı da budur.',
    memoryTip: 'Şehir dışı iki yönlü yol = 90 zihinde kalsın.',
    examImportance: 'çok yüksek',
    commonMistake: 'Bölünmüş yol sınırı (110) ile karıştırmak.',
    relatedLessonSlug: 'hiz-takip',
    keywords: ['hiz', 'azami', '90', 'sehirlerarasi'],
  },
  {
    id: 'azami-hiz-100',
    category: 'yasak',
    name: 'Azami Hız 100',
    shape: 'ring',
    glyphText: '100',
    meaning: 'Bu kesimde en yüksek hız 100 km/saattir.',
    memoryTip: 'Kırmızı çember + rakam = üst hız sınırı.',
    examImportance: 'yüksek',
    relatedLessonSlug: 'hiz-takip',
    keywords: ['hiz', 'azami', '100'],
  },
  {
    id: 'azami-hiz-110',
    category: 'yasak',
    name: 'Azami Hız 110',
    shape: 'ring',
    glyphText: '110',
    meaning:
      'Bu kesimde en yüksek hız 110 km/saattir; otomobiller için bölünmüş yolların genel sınırı da budur.',
    memoryTip: 'Bölünmüş yol = 110; otoyol değil, karıştırma.',
    examImportance: 'çok yüksek',
    commonMistake: 'Bölünmüş yol ile otoyol sınırını (120) karıştırmak.',
    relatedLessonSlug: 'hiz-takip',
    keywords: ['hiz', 'azami', '110', 'bolunmus-yol'],
  },
  {
    id: 'azami-hiz-120',
    category: 'yasak',
    name: 'Azami Hız 120',
    shape: 'ring',
    glyphText: '120',
    meaning:
      'Bu kesimde en yüksek hız 120 km/saattir; otomobiller için otoyolların genel üst sınırı da budur.',
    memoryTip: 'Otoyolun tavanı 120, tabanı 40: ikisini çift hatırla.',
    examImportance: 'çok yüksek',
    relatedLessonSlug: 'hiz-takip',
    keywords: ['hiz', 'azami', '120', 'otoyol'],
  },
  {
    id: 'agirlik-siniri',
    category: 'yasak',
    name: 'Ağırlık Sınırlaması (16 t)',
    shape: 'ring',
    glyphText: '16t',
    meaning: 'Yüklü ağırlığı levhada yazılı değerden (16 ton) fazla olan taşıtlar bu yola giremez.',
    memoryTip: 't harfi ton demek: toplam yüklü ağırlığın tavanı.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['agirlik', 'ton', 'sinir'],
  },
  {
    id: 'aks-yuku-siniri',
    category: 'yasak',
    name: 'Dingil Ağırlığı Sınırlaması (7 t)',
    shape: 'ring',
    glyphText: '7t',
    meaning: 'Dingil başına düşen ağırlığı levhada yazılı değerden fazla olan taşıtlar giremez.',
    memoryTip: 'Küçük tonaj tek dingilin taşıdığını anlatır; toplam ağırlıkla karıştırma.',
    examImportance: 'orta',
    commonMistake: 'Dingil ağırlığını toplam yüklü ağırlık sanmak.',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['dingil', 'aks', 'ton', 'sinir'],
  },
  {
    id: 'genislik-siniri',
    category: 'yasak',
    name: 'Genişlik Sınırlaması (2 m)',
    shape: 'ring',
    glyphText: '2m',
    meaning: 'Yüküyle birlikte genişliği levhada yazılı değerden fazla olan taşıtlar giremez.',
    memoryTip: 'Değer kapının eni: aracın (yükle) sığması gerekir.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['genislik', 'sinir', 'dar'],
  },
  {
    id: 'yukseklik-siniri',
    category: 'yasak',
    name: 'Yükseklik Sınırlaması (3,5 m)',
    shape: 'ring',
    glyphText: '3.5m',
    meaning:
      'Yüküyle birlikte yüksekliği levhada yazılı değerden fazla olan taşıtlar giremez (alçak köprü, tünel, üst geçit önlerinde bulunur).',
    memoryTip: 'Değer tavanın boyu: yükün de dahil olduğunu unutma.',
    examImportance: 'yüksek',
    commonMistake: 'Değeri yol genişliği sanmak; ölçü aracın yüksekliğiyle karşılaştırılır.',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['yukseklik', 'sinir', 'kopru', 'tunel'],
  },
  {
    id: 'uzunluk-siniri',
    category: 'yasak',
    name: 'Uzunluk Sınırlaması (10 m)',
    shape: 'ring',
    glyphText: '10m',
    meaning: 'Yüküyle birlikte uzunluğu levhada yazılı değerden fazla olan taşıtlar giremez.',
    memoryTip: 'Keskin virajlı dar yollar uzun aracı sevmez.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['uzunluk', 'sinir', 'metre'],
  },
  {
    id: 'takip-mesafesi',
    category: 'yasak',
    name: 'Takip Mesafesi (70 m)',
    shape: 'ring',
    glyphText: '70m',
    meaning: 'Öndeki araca levhada yazılı mesafeden (70 m) daha fazla yaklaşmak yasaktır.',
    memoryTip: 'Rakam korunacak EN AZ aralıktır: bu kadar geride kal.',
    examImportance: 'çok yüksek',
    commonMistake: 'Değeri azami mesafe sanmak; tersine, korunması gereken asgari aralıktır.',
    relatedLessonSlug: 'hiz-takip',
    keywords: ['takip', 'mesafe', 'yaklasma'],
  },
  {
    id: 'gumruk-dur',
    category: 'yasak',
    name: 'Gümrük (Durmadan Geçmek Yasaktır)',
    shape: 'ring',
    glyphText: 'GÜMRÜK',
    meaning:
      'Gümrük veya kontrol noktasında durmak zorunludur; işaretin hizasında durulur, izin alınarak geçilir.',
    memoryTip: 'Çemberdeki yazı kapının adıdır: yazıyı gör, dur, izinle geç.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['gumruk', 'kontrol', 'durma'],
  },
  {
    id: 'sollama-yasagi-sonu',
    category: 'yasak',
    name: 'Geçme Yasağı Sonu',
    shape: 'ring',
    glyph: 'endBar',
    meaning:
      'Öndeki taşıtı geçme (sollama) yasağı bu noktada sona erer; genel geçme kuralları yeniden geçerlidir.',
    memoryTip: 'Çapraz çizgiler yasağın üstünü çizer: geçiş kurallara göre serbest.',
    examImportance: 'yüksek',
    commonMistake:
      'Levhayı görünce her koşulda sollamanın serbest olduğunu sanmak; görüş ve şerit kuralları sürer.',
    relatedLessonSlug: 'sollama-serit',
    keywords: ['sollama', 'yasak-sonu', 'gecme'],
  },
  {
    id: 'hiz-siniri-sonu',
    category: 'yasak',
    name: 'Hız Sınırlaması Sonu',
    shape: 'ring',
    glyph: 'endBar',
    meaning:
      'Levha ile konulan azami hız sınırlaması sona erer; yolun genel hız sınırları geçerli olur.',
    memoryTip: 'Sınır bitti, serbestlik bitmedi: genel sınır devreye girer.',
    examImportance: 'yüksek',
    commonMistake: 'Sınır bitince hızın serbest kaldığını sanmak.',
    relatedLessonSlug: 'hiz-takip',
    keywords: ['hiz', 'sinir-sonu'],
  },
  {
    id: 'tum-yasaklarin-sonu',
    category: 'yasak',
    name: 'Bütün Yasaklama ve Kısıtlamaların Sonu',
    shape: 'ring',
    glyph: 'endBar',
    meaning:
      'Levhalarla daha önce konulmuş bütün yasak ve kısıtlamalar (hız, geçme, takip mesafesi vb.) bu noktada sona erer.',
    memoryTip: 'Tek levha, bütün yasakların üstünü çizer.',
    examImportance: 'yüksek',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['yasak-sonu', 'kisitlama', 'serbest'],
  },

  // ——— EK: MECBURİYET (mavi daire) ———
  {
    id: 'saga-donus-mecburi',
    category: 'mecburiyet',
    name: 'İleride Sağa Mecburi Yön',
    shape: 'disc',
    glyph: 'turnRight',
    meaning: 'İlerideki kavşaktan sağa dönmek zorunludur; başka yöne devam edilemez.',
    memoryTip: 'Kıvrık ok ileride dön der; düz ok hemen bu yöne der.',
    examImportance: 'yüksek',
    relatedLessonSlug: 'kavsak-oncelik',
    keywords: ['mecburi', 'sag', 'donus'],
  },
  {
    id: 'sola-donus-mecburi',
    category: 'mecburiyet',
    name: 'İleride Sola Mecburi Yön',
    shape: 'disc',
    glyph: 'turnLeft',
    meaning: 'İlerideki kavşaktan sola dönmek zorunludur; başka yöne devam edilemez.',
    memoryTip: 'Kıvrılan ok = dönüş ileride, hazırlığını şimdiden yap.',
    examImportance: 'yüksek',
    relatedLessonSlug: 'kavsak-oncelik',
    keywords: ['mecburi', 'sol', 'donus'],
  },
  {
    id: 'sagdan-gidin',
    category: 'mecburiyet',
    name: 'Sağdan Gidiniz',
    shape: 'disc',
    glyph: 'keepRight',
    meaning: 'Levhanın bulunduğu ada, refüj veya engelin sağından geçmek zorunludur.',
    memoryTip: 'Eğik ok, trafiğin engelin hangi yanından akacağını çizer.',
    examImportance: 'yüksek',
    commonMistake: 'Levhayı sağa mecburi dönüş sanmak; sadece engelin sağından geçilir.',
    relatedLessonSlug: 'sollama-serit',
    keywords: ['sagdan', 'ada', 'refuj', 'engel'],
  },
  {
    id: 'yaya-yolu',
    category: 'mecburiyet',
    name: 'Yaya Yolu',
    shape: 'disc',
    glyph: 'pedestrian',
    meaning: 'Bu yol yalnız yayaların kullanımına ayrılmıştır; taşıtlar giremez.',
    memoryTip: 'Mavi daire + yürüyen = yol yürüyenin.',
    examImportance: 'orta',
    commonMistake: 'Kırmızı çemberli yaya giremez levhası ile karıştırmak.',
    relatedLessonSlug: 'yaya-gecidi',
    keywords: ['yaya', 'yol', 'mecburi'],
  },
  {
    id: 'asgari-hiz-30',
    category: 'mecburiyet',
    name: 'Mecburi Asgari Hız 30',
    shape: 'disc',
    glyphText: '30',
    meaning: 'Yol ve hava koşulları uygunken bu kesimde 30 km/saatin altında sürmek yasaktır.',
    memoryTip: 'Mavi daire + rakam = taban hız; kırmızı çember tavandı.',
    examImportance: 'yüksek',
    commonMistake: 'Mavi daireli hız değerini azami sınır sanmak; bu alt sınırdır.',
    relatedLessonSlug: 'hiz-takip',
    keywords: ['asgari', 'hiz', '30'],
  },
  {
    id: 'asgari-hiz-40',
    category: 'mecburiyet',
    name: 'Mecburi Asgari Hız 40',
    shape: 'disc',
    glyphText: '40',
    meaning:
      'Bu kesimde 40 km/saatin altında sürmek yasaktır; otoyolların genel asgari hızı da 40 km/saattir.',
    memoryTip: 'Otoyolun tabanı 40: yavaş araç otoyola çıkamaz.',
    examImportance: 'yüksek',
    relatedLessonSlug: 'hiz-takip',
    keywords: ['asgari', 'hiz', '40', 'otoyol'],
  },
  {
    id: 'asgari-hiz-50',
    category: 'mecburiyet',
    name: 'Mecburi Asgari Hız 50',
    shape: 'disc',
    glyphText: '50',
    meaning: 'Yol ve hava koşulları uygunken bu kesimde 50 km/saatin altında sürmek yasaktır.',
    memoryTip: 'Mavi zemin emirdir: en az bu hızla ak.',
    examImportance: 'yüksek',
    relatedLessonSlug: 'hiz-takip',
    keywords: ['asgari', 'hiz', '50'],
  },
  {
    id: 'asgari-hiz-sonu',
    category: 'mecburiyet',
    name: 'Mecburi Asgari Hız Sonu',
    shape: 'disc',
    glyph: 'endBar',
    meaning: 'Asgari hız zorunluluğu bu noktada sona erer.',
    memoryTip: 'Çizgi mavi emrin üstünü çizdi: taban hız kalktı.',
    examImportance: 'orta',
    relatedLessonSlug: 'hiz-takip',
    keywords: ['asgari', 'hiz', 'sonu'],
  },
  {
    id: 'zincir-mecburi',
    category: 'mecburiyet',
    name: 'Patinaj Zinciri Takmak Mecburidir',
    shape: 'disc',
    glyph: 'chains',
    meaning:
      'Karlı veya buzlu kesimde en az bir çift muharrik (çekici) tekerleğe patinaj zinciri takmak zorunludur.',
    memoryTip: 'Mavi daire emirdir: zincirsiz devam yok.',
    examImportance: 'orta',
    commonMistake: 'Zinciri çekişsiz tekerleklere takmak; zincir çekici aksa takılır.',
    relatedLessonSlug: 'arac-hazirlik',
    keywords: ['zincir', 'kar', 'patinaj', 'kis'],
  },

  // ——— EK: BİLGİ (mavi dikdörtgen) ———
  {
    id: 'ilk-yardim',
    category: 'bilgi',
    name: 'İlk Yardım',
    shape: 'rect-blue',
    glyph: 'cross',
    meaning: 'Yakında ilk yardım istasyonu veya sağlık kuruluşu vardır.',
    memoryTip: 'Mavi zemin + beyaz artı = acil yardım noktası.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['ilk-yardim', 'saglik', 'acil'],
  },
  {
    id: 'telefon',
    category: 'bilgi',
    name: 'Telefon',
    shape: 'rect-blue',
    glyph: 'phone',
    meaning: 'Yakında acil durumlarda kullanılabilecek telefon vardır.',
    memoryTip: 'Ahize simgesi = yardım çağırma noktası.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['telefon', 'acil', 'iletisim'],
  },
  {
    id: 'tamirhane',
    category: 'bilgi',
    name: 'Tamirhane',
    shape: 'rect-blue',
    glyph: 'wrenchTool',
    meaning: 'Yakında araç bakım ve onarım yeri vardır.',
    memoryTip: 'Anahtar simgesi = arızaya çare burada.',
    examImportance: 'orta',
    relatedLessonSlug: 'arac-hazirlik',
    keywords: ['tamir', 'bakim', 'onarim'],
  },
  {
    id: 'akaryakit',
    category: 'bilgi',
    name: 'Akaryakıt İstasyonu',
    shape: 'rect-blue',
    glyph: 'fuel',
    meaning: 'Yakında yakıt alınabilecek akaryakıt istasyonu vardır.',
    memoryTip: 'Pompa simgesi = depoyu doldurma fırsatı.',
    examImportance: 'orta',
    relatedLessonSlug: 'arac-hazirlik',
    keywords: ['akaryakit', 'benzin', 'istasyon'],
  },
  {
    id: 'otel',
    category: 'bilgi',
    name: 'Otel veya Motel',
    shape: 'rect-blue',
    glyph: 'bed',
    meaning: 'Yakında konaklama tesisi vardır; uzun yolculukta dinlenme planlanabilir.',
    memoryTip: 'Yatak simgesi = mola ve uyku noktası.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['otel', 'motel', 'konaklama'],
  },
  {
    id: 'lokanta',
    category: 'bilgi',
    name: 'Lokanta',
    shape: 'rect-blue',
    glyph: 'cutlery',
    meaning: 'Yakında yemek yenebilecek tesis vardır.',
    memoryTip: 'Çatal bıçak = yemek molası.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['lokanta', 'yemek', 'restoran'],
  },
  {
    id: 'cesme',
    category: 'bilgi',
    name: 'Çeşme',
    shape: 'rect-blue',
    glyph: 'fountain',
    meaning: 'Yakında içme suyu alınabilecek çeşme vardır.',
    memoryTip: 'Akan su simgesi = su ihtiyacını burada gider.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['cesme', 'su', 'icme-suyu'],
  },
  {
    id: 'kamp-yeri',
    category: 'bilgi',
    name: 'Kamp Yeri',
    shape: 'rect-blue',
    glyph: 'tent',
    meaning: 'Yakında çadırla kamp kurulabilecek alan vardır.',
    memoryTip: 'Çadır simgesi = konaklama açık havada.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['kamp', 'cadir', 'tesis'],
  },
  {
    id: 'otobus-duragi',
    category: 'bilgi',
    name: 'Otobüs Durağı',
    shape: 'rect-blue',
    glyph: 'bus',
    meaning: 'Otobüs durağının yerini gösterir; durağa 15 metre mesafe içinde park etmek yasaktır.',
    memoryTip: 'Durak gördüğünde 15 metre kuralı aklına gelsin.',
    examImportance: 'yüksek',
    commonMistake: 'Durak çevresindeki 15 metrelik park yasağını unutmak.',
    relatedLessonSlug: 'park-manevra',
    keywords: ['otobus', 'durak', '15-metre'],
  },
  {
    id: 'tramvay-duragi',
    category: 'bilgi',
    name: 'Tramvay Durağı',
    shape: 'rect-blue',
    glyph: 'tram',
    meaning:
      'Tramvay durağının yerini gösterir; durağa 15 metre mesafe içinde park etmek yasaktır.',
    memoryTip: 'Raylı durak da durak: 15 metre kuralı burada da geçerli.',
    examImportance: 'orta',
    relatedLessonSlug: 'park-manevra',
    keywords: ['tramvay', 'durak', '15-metre'],
  },
  {
    id: 'taksi-duragi',
    category: 'bilgi',
    name: 'Taksi Durağı',
    shape: 'rect-blue',
    glyphText: 'TAKSİ',
    meaning: 'Taksilerin durak yerini gösterir; diğer araçlar bu alana park edemez.',
    memoryTip: 'Yazı kimin adıysa yer onun: TAKSİ yazan yere taksi durur.',
    examImportance: 'orta',
    relatedLessonSlug: 'park-manevra',
    keywords: ['taksi', 'durak'],
  },
  {
    id: 'polis',
    category: 'bilgi',
    name: 'Polis',
    shape: 'rect-blue',
    glyphText: 'POLİS',
    meaning: 'Yakında polis birimi vardır.',
    memoryTip: 'Mavi levha + POLİS = yardım ve bildirim noktası.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['polis', 'guvenlik'],
  },
  {
    id: 'tek-yon',
    category: 'bilgi',
    name: 'Tek Yönlü Yol',
    shape: 'rect-blue',
    glyph: 'arrowRight',
    meaning:
      'Yolun ok yönünde tek yönlü işlediğini bildirir; karşı yönden araç gelmez ve yola ters yönde girilemez.',
    memoryTip: 'Dikdörtgen bilgilendirir: akış tek yönde, ters giren hatalıdır.',
    examImportance: 'yüksek',
    commonMistake: 'Tek yön levhasını mavi daireli mecburi yön ile karıştırmak.',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['tek-yon', 'ok', 'akis'],
  },
  {
    id: 'cikmaz-yol',
    category: 'bilgi',
    name: 'Çıkmaz Yol',
    shape: 'rect-blue',
    glyph: 'deadEnd',
    meaning: 'Girilen yolun ilerisinin taşıt trafiğine çıkışı olmadığını bildirir.',
    memoryTip: 'T şeklinin tepesindeki kırmızı bar = yolun sonu duvar.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['cikmaz', 'yol', 'son'],
  },
  {
    id: 'tunel',
    category: 'bilgi',
    name: 'Tünel',
    shape: 'rect-blue',
    glyph: 'tunnel',
    meaning:
      'İleride tünel vardır; gündüz de olsa yakını gösteren farlar yakılır, tünel içinde duraklamak ve park etmek yasaktır.',
    memoryTip: 'Kemer gördün, farı yak: tünelin ilk kuralı ışık.',
    examImportance: 'yüksek',
    commonMistake: 'Gündüz aydınlık diye far yakmamak.',
    relatedLessonSlug: 'isik-gece',
    keywords: ['tunel', 'far', 'isik'],
  },
  {
    id: 'okul-gecidi-bilgi',
    category: 'bilgi',
    name: 'Okul Geçidi (bilgi)',
    shape: 'rect-blue',
    glyph: 'children',
    meaning:
      'Okul geçidinin bulunduğu yeri gösterir; öğrencilere ve geçit görevlisine dikkat edilir.',
    memoryTip: 'Üçgen yaklaşımı, mavi kare yerini söyler.',
    examImportance: 'yüksek',
    relatedLessonSlug: 'yaya-gecidi',
    keywords: ['okul', 'gecit', 'cocuk'],
  },
  {
    id: 'havalimani',
    category: 'bilgi',
    name: 'Havalimanı',
    shape: 'rect-blue',
    glyph: 'airplane',
    meaning: 'Havalimanına giden yönü veya tesisi gösterir.',
    memoryTip: 'Mavi kare + uçak = terminal bu yönde.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['havalimani', 'ucak', 'terminal'],
  },
  {
    id: 'motorlu-tasit-yolu',
    category: 'bilgi',
    name: 'Motorlu Taşıt Yolu',
    shape: 'rect-blue',
    glyph: 'car',
    meaning:
      'Yalnız motorlu taşıtların kullanabileceği yolun başladığını bildirir; yaya, bisikletli ve hayvanla çekilen taşıt giremez.',
    memoryTip: 'Mavi kare + otomobil = motorlulara özel yol; yeşil olsaydı otoyoldu.',
    examImportance: 'orta',
    commonMistake: 'Bu yolu otoyol sanmak; otoyol levhası yeşildir.',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['motorlu', 'tasit', 'yol'],
  },

  // ——— EK: DURAKLAMA & PARK ———
  {
    id: 'engelli-parki',
    category: 'park',
    name: 'Engelli Park Yeri',
    shape: 'rect-blue',
    glyph: 'parkingP',
    meaning:
      'Bu park alanı engelli sürücü ve yolcuların araçlarına ayrılmıştır; engelli kartı olmayan araç buraya park edemez.',
    memoryTip: 'P burada herkese değil; ayrılan yer sahibinindir.',
    examImportance: 'yüksek',
    commonMistake: 'Boş görüp kısa süreliğine park etmek; ihlaldir ve cezası yüksektir.',
    relatedLessonSlug: 'park-manevra',
    keywords: ['engelli', 'park', 'ayrilmis'],
  },
  {
    id: 'park-saat-sinirli',
    category: 'park',
    name: 'Süre Sınırlı Park Yeri',
    shape: 'rect-blue',
    glyph: 'parkingP',
    meaning:
      'Park etmek serbesttir; ancak ek panelde belirtilen gün, saat aralığı veya süre sınırına uyulması zorunludur.',
    memoryTip: 'P altındaki yazı sözleşmedir: saati aşarsan izin biter.',
    examImportance: 'orta',
    commonMistake: 'Ek paneli okumadan yalnız P harfine güvenmek.',
    relatedLessonSlug: 'park-manevra',
    keywords: ['park', 'sure', 'saat', 'sinirli'],
  },
  {
    id: 'park-yasagi-sonu',
    category: 'park',
    name: 'Park Yasağı Sonu',
    shape: 'ring',
    glyph: 'endBar',
    meaning: 'Park etme yasağı bu noktada sona erer.',
    memoryTip: 'Çapraz çizgi yasağın üstünü çizdi: park kurallara uygun yerde serbest.',
    examImportance: 'orta',
    relatedLessonSlug: 'park-manevra',
    keywords: ['park', 'yasak-sonu'],
  },

  // ——— EK: OTOYOL & YÖNLENDİRME ———
  {
    id: 'otoyol-sonu',
    category: 'otoyol',
    name: 'Otoyol Sonu',
    shape: 'rect-green',
    glyph: 'endBar',
    meaning:
      'Otoyol bu noktada biter; otoyola özgü asgari ve azami hızlar sona erer, devam edilen yolun kuralları geçerli olur.',
    memoryTip: 'Yeşilin üstü çizildi: otoyol modu kapandı, hız gözden geçir.',
    examImportance: 'orta',
    relatedLessonSlug: 'hiz-takip',
    keywords: ['otoyol', 'son', 'bitis'],
  },
  {
    id: 'otoyol-cikisi',
    category: 'otoyol',
    name: 'Otoyol Çıkışı',
    shape: 'rect-green',
    glyph: 'arrowRight',
    meaning:
      'Otoyoldan ayrılma noktasını gösterir; asıl yavaşlama, çıkış (ayrılma) şeridine girildikten sonra yapılır.',
    memoryTip: 'Önce şerit, sonra fren: ana platformda yavaşlama.',
    examImportance: 'yüksek',
    commonMistake: 'Ana şeritte erkenden yavaşlayıp arkadaki akışı bozmak.',
    relatedLessonSlug: 'hiz-takip',
    keywords: ['otoyol', 'cikis', 'ayrilma'],
  },
  {
    id: 'otoyol-cikisi-300m',
    category: 'otoyol',
    name: 'Otoyol Çıkışı Yaklaşımı (300 m)',
    shape: 'rect-green',
    glyphText: '300m',
    meaning:
      'Otoyol çıkışına 300 metre kaldığını bildirir; sağ şeride geçilerek çıkışa hazırlanılır.',
    memoryTip: 'Rakamlar geri sayımdır: levhayı gör, sağa yanaş.',
    examImportance: 'orta',
    relatedLessonSlug: 'hiz-takip',
    keywords: ['otoyol', 'cikis', '300', 'yaklasim'],
  },

  // ——— EK: GEÇİCİ / ÇALIŞMA (sarı zemin — üçgen ile stilize) ———
  {
    id: 'serit-daralmasi-gecici',
    category: 'gecici',
    name: 'Şerit Daralması (çalışma bölgesi)',
    shape: 'triangle',
    glyph: 'narrow',
    meaning:
      'Çalışma nedeniyle ileride şerit sayısı azalır veya daralır (gerçek levha sarı zeminlidir); erken şerit değiştirilir, sırayla birleşilir.',
    memoryTip: 'Fermuar gibi: bir sen, bir o — erken karar, geç kavga çıkarmaz.',
    examImportance: 'orta',
    relatedLessonSlug: 'sollama-serit',
    keywords: ['serit', 'daralma', 'calisma', 'gecici'],
  },
  {
    id: 'is-makinesi-cikabilir',
    category: 'gecici',
    name: 'İş Makinesi Çıkabilir',
    shape: 'triangle',
    glyph: 'digger',
    meaning:
      'Çalışma bölgesinden yola iş makinesi girip çıkabilir; hız düşürülür ve ani durmaya hazırlıklı olunur.',
    memoryTip: 'Kepçe yavaştır ama geniştir: mesafeni şimdiden aç.',
    examImportance: 'orta',
    relatedLessonSlug: 'trafik-isaretleri',
    keywords: ['is-makinesi', 'kepce', 'calisma'],
  },
  {
    id: 'gecici-iki-yonlu',
    category: 'gecici',
    name: 'İki Yönlü Trafik (çalışma bölgesi)',
    shape: 'triangle',
    glyph: 'twoway',
    meaning:
      'Çalışma nedeniyle trafik geçici olarak karşılıklı iki yönlü akıtılır (sarı zeminli levha); şerit disiplinine ve karşı yöne dikkat edilir.',
    memoryTip: 'Sarı zemin geçicidir: bölünmüş yolda bile karşıdan araç gelebilir.',
    examImportance: 'orta',
    commonMistake: 'Bölünmüş yol alışkanlığıyla karşı akışı beklememek.',
    relatedLessonSlug: 'sollama-serit',
    keywords: ['iki-yonlu', 'calisma', 'gecici'],
  },

  // ——— EK: ÖNCELİK ———
  {
    id: 'ana-yol-sonu',
    category: 'oncelik',
    name: 'Ana Yol Sonu',
    shape: 'diamond',
    glyph: 'endBar',
    meaning:
      'Ana yol bu noktada biter; geçiş üstünlüğü kalkar ve kavşaklarda genel öncelik kuralları uygulanır.',
    memoryTip: 'Çizili eşkenar dörtgen = kral tacı indi, sıradan kurallara dön.',
    examImportance: 'yüksek',
    commonMistake: 'Levhadan sonra da önceliğin kendisinde olduğunu sanmak.',
    relatedLessonSlug: 'kavsak-oncelik',
    keywords: ['ana-yol', 'son', 'oncelik'],
  },
  {
    id: 'dar-gecit-oncelik',
    category: 'oncelik',
    name: 'Karşıdan Gelene Yol Ver',
    shape: 'ring',
    glyph: 'priorityArrows',
    meaning:
      'Dar kesimde geçiş önceliği karşı yönden gelenindir; kırmızı ok senin yönünü gösterir, karşıdan gelen geçinceye kadar beklenir.',
    memoryTip: 'Kırmızı ok tarafı yol verir: kırmızı sensin, bekle.',
    examImportance: 'çok yüksek',
    commonMistake:
      'Mavi kare olan öncelikli yön levhası ile karıştırmak; kırmızı çember daima kısıtlama getirir.',
    relatedLessonSlug: 'kavsak-oncelik',
    keywords: ['dar-gecit', 'yol-ver', 'karsidan-gelen'],
  },
  {
    id: 'dar-gecit-onceligi-sende',
    category: 'oncelik',
    name: 'Öncelikli Yön (dar geçit)',
    shape: 'rect-blue',
    glyph: 'priorityArrows',
    meaning:
      'Dar kesimde geçiş önceliği senin yönündedir; büyük beyaz ok senin yönünü gösterir, karşı yönden gelen bekler. Yine de dar kesime kontrollü girilir.',
    memoryTip: 'Mavi kare + büyük beyaz ok = geçiş hakkı sende.',
    examImportance: 'çok yüksek',
    commonMistake: 'Kırmızı çemberli eşini görünce de kendini öncelikli sanmak.',
    relatedLessonSlug: 'kavsak-oncelik',
    keywords: ['dar-gecit', 'oncelik', 'oncelikli-yon'],
  },
];

/* ---- yardımcılar (saf, test edilebilir) ---- */

function norm(s: string): string {
  return s
    .toLocaleLowerCase('tr')
    .replace(/[çğıöşü]/g, (c) => ({ ç: 'c', ğ: 'g', ı: 'i', ö: 'o', ş: 's', ü: 'u' })[c] ?? c);
}

export function filterSigns(query: string, category: SignCategory | 'all'): TrafficSign[] {
  const q = norm(query.trim());
  return SIGNS.filter((s) => {
    if (category !== 'all' && s.category !== category) return false;
    if (!q) return true;
    const hay = norm(s.name + ' ' + s.meaning + ' ' + s.keywords.join(' '));
    return hay.includes(q);
  });
}

export function signById(id: string): TrafficSign | undefined {
  return SIGNS.find((s) => s.id === id);
}

export function signsByCategory(): Record<SignCategory, number> {
  const out = {} as Record<SignCategory, number>;
  for (const s of SIGNS) out[s.category] = (out[s.category] ?? 0) + 1;
  return out;
}
