/**
 * A (motosiklet) ve D (otobüs) sınıfı araç bileşenleri — Evolution Faz E4 (çok-sınıflı temel).
 *
 * NEDEN AYRI DOSYA: `VEHICLE_PARTS` web uygulamasının (B odaklı) kütüphanesidir ve DEĞİŞMEZ.
 * Buradaki parçalar yalnız mobil içerik anlık görüntüsüne eklenir (`ALL_VEHICLE_PARTS`), böylece
 * web davranışı birebir korunur — `products.ts`'teki `MOBILE_PRODUCTS` deseninin aynısı.
 *
 * KİMLİK KURALI: parça `id`'si, mobil mekanik varlık kimliğiyle AYNIDIR (`assets/mech/<id>.webp`),
 * böylece görsel eşlemesi ayrı bir tablo gerektirmez.
 */

import type { VehiclePart } from './vehicle';

/** A sınıfı — motosiklet kumandaları, mekanikleri ve koruyucu donanım. */
export const MOTO_PARTS: VehiclePart[] = [
  {
    id: 'moto-kill-switch',
    name: 'Motor Durdurma (Kill) Anahtarı',
    system: 'kabin',
    licences: ['a'],
    desc: 'Sağ gidon kumandasındaki kırmızı anahtar; motoru kontağı kapatmadan anında durdurur.',
    tip: 'Acil durumda kontağa uzanmadan motoru kesmeni sağlar; kalkıştan önce RUN konumunda olmalı.',
    mistake: 'Motor çalışmıyor diye marşa yüklenmek — çoğu zaman kill anahtarı OFF kalmıştır.',
  },
  {
    id: 'moto-start-switch',
    name: 'Marş Düğmesi',
    system: 'kabin',
    licences: ['a'],
    desc: 'Sağ gidondaki marş düğmesi; debriyaj çekiliyken veya vites boştayken motoru çalıştırır.',
    tip: 'Çoğu motosiklette güvenlik kilidi vardır: yan sehpa açıkken vitesteyse marş basmaz.',
  },
  {
    id: 'moto-turn-switch',
    name: 'Sinyal Kumandası',
    system: 'kabin',
    licences: ['a'],
    desc: 'Sol gidondaki iterek çalışan sinyal anahtarı; ortasına basılarak iptal edilir.',
    tip: 'Motosiklet sinyalleri çoğunlukla kendiliğinden sönmez — dönüş bitince elle kapat.',
    mistake: 'Sinyali kapatmayı unutup arkadan geleni yanıltmak.',
  },
  {
    id: 'moto-horn-switch',
    name: 'Korna Düğmesi',
    system: 'kabin',
    licences: ['a'],
    desc: 'Sol gidon kumandasındaki korna düğmesi.',
    tip: 'Motosiklette görünürlük düşüktür; kör noktadaki sürücüyü uyarmak için kısa kullan.',
  },
  {
    id: 'moto-clutch-lever',
    name: 'Debriyaj Kolu',
    system: 'kabin',
    licences: ['a'],
    desc: 'Sol gidondaki kol; motor gücünü tekerleğe bağlayan kavramayı ayırır.',
    tip: 'Kalkışta yavaş bırak, gazı kademeli ver; kavrama noktası kolun ilk üçte birindedir.',
    inspection: [
      'Boşluğu kontrol et',
      'Kolun serbest dönüşünü dene',
      'Kablo/hidrolik kaçağına bak',
    ],
  },
  {
    id: 'moto-brake-lever',
    name: 'Ön Fren Kolu',
    system: 'kabin',
    licences: ['a'],
    desc: 'Sağ gidondaki kol; frenleme gücünün büyük bölümünü sağlayan ön freni çalıştırır.',
    tip: 'Ön fren aniden değil kademeli sıkılır; virajda dik dururken kullanılır.',
    mistake: 'Virajda yatarken sert ön fren yapmak — tekerlek kayar.',
  },
  {
    id: 'moto-ignition',
    name: 'Kontak Anahtarı',
    system: 'kabin',
    licences: ['a'],
    desc: 'OFF – ON – LOCK konumlu kontak; LOCK konumunda direksiyon kilitlenir.',
    tip: 'Park ederken LOCK konumu gidonu kilitler, hırsızlığa karşı ilk önlemdir.',
  },
  {
    id: 'moto-cluster',
    name: 'Gösterge Paneli',
    system: 'kabin',
    licences: ['a'],
    desc: 'Hız, devir, vites konumu, yakıt ve ikaz lambalarını gösteren dijital panel.',
    tip: 'Vites göstergesindeki N (neutral) yeşil yanıyorsa vites boştadır.',
  },
  {
    id: 'moto-gear-lever',
    name: 'Vites Pedalı',
    system: 'kabin',
    licences: ['a'],
    desc: 'Sol ayak altındaki pedal; yukarı-aşağı hareketle vites değiştirir.',
    tip: 'Klasik dizilim: 1 aşağı, boş, sonra yukarı 2-3-4-5. Vites değişiminde debriyajı çek.',
  },
  {
    id: 'moto-brake-pedal',
    name: 'Arka Fren Pedalı',
    system: 'kabin',
    licences: ['a'],
    desc: 'Sağ ayak altındaki pedal; arka tekerlek frenini çalıştırır.',
    tip: 'Ön ve arka fren birlikte kullanılır; yalnız arka fren mesafeyi uzatır.',
  },
  {
    id: 'moto-chain',
    name: 'Zincir (Şaft/Kayış)',
    system: 'dis',
    licences: ['a'],
    desc: 'Motor gücünü arka tekerleğe ileten zincir; gerginliği ve yağı düzenli kontrol edilir.',
    tip: 'Aşırı gevşek zincir atlar, aşırı gergin zincir rulmanları yer; üretici boşluğuna uy.',
    inspection: ['Zincir boşluğunu ölç', 'Yağlı mı bak', 'Dişli aşınmasını kontrol et'],
  },
  {
    id: 'moto-exhaust',
    name: 'Egzoz',
    system: 'dis',
    licences: ['a'],
    desc: 'Yanmış gazı dışarı atan ve sesi düşüren sistem.',
    tip: 'Egzoz motosiklette bacağa çok yakındır; durur durmaz dokunma, yanık riski yüksektir.',
  },
  {
    id: 'moto-fork',
    name: 'Ön Amortisör (Çatal)',
    system: 'dis',
    licences: ['a'],
    desc: 'Ön tekerleği gövdeye bağlayan ve darbeleri sönümleyen teleskopik çatal.',
    tip: 'Çatal borusunda yağ sızıntısı görürsen fren mesafesi ve tutunma bozulur; ertelemeden onar.',
  },
  {
    id: 'moto-brake-reservoir',
    name: 'Fren Hidroliği Deposu',
    system: 'kabin',
    licences: ['a'],
    desc: 'Gidondaki küçük depo; ön fren hidroliğini tutar ve seviyesi camdan görülür.',
    tip: 'Seviye MIN altındaysa balata bitmiş veya kaçak var demektir.',
  },
  {
    id: 'moto-oil-sight-glass',
    name: 'Yağ Seviye Camı',
    system: 'motor-bolmesi',
    licences: ['a'],
    desc: 'Motor yağ seviyesinin görüldüğü küçük gözetleme camı.',
    tip: 'Motosiklet düz ve dik dururken bak; yan sehpadayken seviye yanıltır.',
  },
  {
    id: 'moto-battery',
    name: 'Akü (12V)',
    system: 'motor-bolmesi',
    licences: ['a'],
    desc: 'Marş ve elektronik sistemleri besleyen küçük 12V akü.',
    tip: 'Uzun süre çalıştırılmayan motosikletin aküsü boşalır; kışın şarj cihazına bağla.',
  },
  {
    id: 'moto-front-wheel',
    name: 'Ön Tekerlek ve Disk',
    system: 'dis',
    licences: ['a'],
    desc: 'Ön tekerlek, fren diski ve lastik; yönlendirmenin ve frenlemenin çoğunu üstlenir.',
    tip: 'Lastik diş derinliği ve basıncı motosiklette hayati; yanak kesiği varsa değiştir.',
    inspection: ['Diş derinliğine bak', 'Basıncı ölç', 'Diskte çizik/çarpıklık kontrolü'],
  },
  {
    id: 'moto-mirror',
    name: 'Ayna',
    system: 'dis',
    licences: ['a'],
    desc: 'Gidona bağlanan dikiz aynası; arkadaki trafiği görmeyi sağlar.',
    tip: 'Aynalar omuz hizasını da gösterecek şekilde ayarlanır; yine de şerit değiştirmeden önce omuz at.',
  },
  {
    id: 'moto-helmet',
    name: 'Kask',
    system: 'muayene',
    licences: ['a'],
    desc: 'Kapalı (full face) kask; motosiklette sürücü ve yolcu için zorunludur.',
    tip: 'Kask çenesi altından kayışla sabitlenir; darbe almış kask görünürde sağlam olsa da değiştirilir.',
    mistake: 'Kaskı takıp kayışını bağlamamak — kaza anında kask kafada kalmaz.',
  },
  {
    id: 'moto-gloves',
    name: 'Koruyucu Eldiven',
    system: 'muayene',
    licences: ['a'],
    desc: 'Ele ve bileğe koruma sağlayan, kaymayı önleyen sürüş eldiveni.',
    tip: 'Düşüşte ilk yere gelen eldir; korumasız sürüş en sık yaralanma sebebidir.',
  },
  {
    id: 'moto-knee-guard',
    name: 'Dizlik',
    system: 'muayene',
    licences: ['a'],
    desc: 'Diz ve kaval kemiğini darbeye karşı koruyan sert kabuklu koruma.',
    tip: 'Şehir içi kısa sürüşlerde de takılır; düşük hızda bile diz yaralanması ağır olur.',
  },
  {
    id: 'moto-hiviz-vest',
    name: 'Reflektörlü Yelek',
    system: 'muayene',
    licences: ['a'],
    desc: 'Gece ve kötü görüşte fark edilmeyi sağlayan reflektörlü yelek.',
    tip: 'Motosiklet kazalarının çoğu "görmedim" ile başlar; görünürlük en ucuz güvenlik önlemidir.',
  },
];

/** D sınıfı — otobüs kumandaları, havalı fren sistemi ve yolcu güvenliği donanımı. */
export const BUS_PARTS: VehiclePart[] = [
  {
    id: 'bus-tachograph',
    name: 'Takograf',
    system: 'kabin',
    licences: ['d'],
    desc: 'Sürüş süresi, hız ve mesafeyi kaydeden cihaz; sürücü kartıyla çalışır.',
    tip: 'Sürüş-dinlenme sürelerinin denetimi bu kayıtla yapılır; kart takılı olmadan yola çıkılmaz.',
    mistake: 'Takografı yalnız hız kaydı sanmak; asıl amaç sürüş/dinlenme süresi denetimidir.',
  },
  {
    id: 'bus-brake-valves',
    name: 'Park ve Römork Fren Valfleri',
    system: 'kabin',
    licences: ['d'],
    desc: 'Sarı düğme park frenini, kırmızı düğme römork hava beslemesini kumanda eder.',
    tip: 'Sarıyı çekmek park frenini uygular; renk kodu her araçta aynıdır.',
  },
  {
    id: 'bus-air-gauges',
    name: 'Hava Basınç Göstergeleri',
    system: 'kabin',
    licences: ['d'],
    desc: 'Ön ve arka fren devrelerindeki hava basıncını gösteren ikili saat.',
    tip: 'Basınç güvenli aralığa çıkmadan hareket edilmez; düşerse uyarı sesi/lambası devreye girer.',
    inspection: ['Kontak açıkken basıncın yükselmesini bekle', 'İki devrenin de dolduğunu gör'],
  },
  {
    id: 'bus-door-panel',
    name: 'Kapı Kumanda Paneli',
    system: 'kabin',
    licences: ['d'],
    desc: 'Yolcu kapılarını açıp kapatan sürücü paneli.',
    tip: 'Kapı açıkken araç hareket etmez; kapatmadan önce basamakları kontrol et.',
  },
  {
    id: 'bus-retarder-stalk',
    name: 'Retarder (Yavaşlatıcı) Kolu',
    system: 'kabin',
    licences: ['d'],
    desc: 'Kademeli olarak aracı yavaşlatan, servis frenini korumak için kullanılan yardımcı fren.',
    tip: 'Uzun inişlerde retarder kullanılır; sürekli fren yapmak balataları ısıtıp fren kaybına yol açar.',
  },
  {
    id: 'bus-speed-knob',
    name: 'Hız/Rölanti Ayar Düğmesi',
    system: 'kabin',
    licences: ['d'],
    desc: 'Kaplumbağa–tavşan simgeli düğme; rölanti devrini ayarlar.',
    tip: 'Duraklamada motoru ısıtmak veya yardımcı sistemleri beslemek için devir yükseltilir.',
  },
  {
    id: 'bus-steering-wheel',
    name: 'Direksiyon ve Kumandalar',
    system: 'kabin',
    licences: ['d'],
    desc: 'Büyük çaplı direksiyon; üzerindeki tuşlar bilgi ekranı ve yardımcı sistemleri yönetir.',
    tip: 'Otobüste dönüş yarıçapı büyüktür; virajda arka tekerlerin içeriden geçtiğini unutma.',
  },
  {
    id: 'bus-air-suspension',
    name: 'Havalı Süspansiyon Kumandası',
    system: 'kabin',
    licences: ['d'],
    desc: 'Aracın yüksekliğini ayarlar; durakta yolcu binişi için gövde alçaltılabilir.',
    tip: 'Alçaltma (kneeling) yaşlı ve engelli yolcunun binişini kolaylaştırır; kalkmadan önce eski seviyeye al.',
  },
  {
    id: 'bus-exhaust-brake-switch',
    name: 'Egzoz Freni Anahtarı',
    system: 'kabin',
    licences: ['d'],
    desc: 'Egzoz çıkışını kısarak motorla yavaşlatma sağlayan yardımcı fren anahtarı.',
    tip: 'Kaygan zeminde ani kullanımı savrulmaya yol açabilir; kademeli kullan.',
  },
  {
    id: 'bus-battery-24v',
    name: 'Akü Grubu (24V)',
    system: 'motor-bolmesi',
    licences: ['d'],
    desc: 'Seri bağlı iki 12V akü; otobüs elektrik sistemini 24V ile besler.',
    tip: 'Takviye alırken 24V sisteme 12V kaynak bağlanmaz; kutup başları sıkı ve temiz olmalı.',
  },
  {
    id: 'bus-battery-isolator',
    name: 'Akü Şalteri (Ana Kesici)',
    system: 'motor-bolmesi',
    licences: ['d'],
    desc: 'Aracın tüm elektriğini tek hareketle kesen ana şalter.',
    tip: 'Uzun park ve bakımda kapatılır; yangın anında elektriği kesmenin en hızlı yoludur.',
  },
  {
    id: 'bus-air-tank',
    name: 'Hava Tankı',
    system: 'motor-bolmesi',
    licences: ['d'],
    desc: 'Fren sisteminin basınçlı havasını depolayan tank.',
    tip: 'Tankın altındaki tahliye valfi periyodik açılır; biriken su kışın donup fren kaybına yol açar.',
    inspection: ['Su tahliyesini yap', 'Kaçak sesi var mı dinle'],
  },
  {
    id: 'bus-coolant-reservoir',
    name: 'Soğutma Suyu Deposu',
    system: 'motor-bolmesi',
    licences: ['d'],
    desc: 'Büyük motorun soğutma suyunu tutan genleşme deposu.',
    tip: 'Sıcak motorda kapağı açma; seviye MIN–MAX arasında olmalı.',
  },
  {
    id: 'bus-dipstick',
    name: 'Yağ Çubuğu',
    system: 'motor-bolmesi',
    licences: ['d'],
    desc: 'Motor yağ seviyesini gösteren uzun çubuk.',
    tip: 'Araç düz zeminde ve motor soğukken ölç; sil, batır, tekrar çıkar.',
  },
  {
    id: 'bus-twin-wheel',
    name: 'Çift Tekerlek (İkiz Lastik)',
    system: 'dis',
    licences: ['d'],
    desc: 'Arka akslarda yükü paylaşan ikiz lastik düzeni.',
    tip: 'İçteki lastiğin inik olduğu çoğu zaman fark edilmez; basınç ölçümü tek tek yapılır.',
    inspection: ['İç ve dış lastiği ayrı ölç', 'Aralarına sıkışmış taş var mı bak'],
  },
  {
    id: 'bus-wheel-chock',
    name: 'Takoz',
    system: 'muayene',
    licences: ['d'],
    desc: 'Ağır aracın park hâlinde kaymasını önleyen takoz.',
    tip: 'Eğimli yolda park frenine ek olarak takoz konur; iniş yönünde tekerlek önüne yerleştirilir.',
  },
  {
    id: 'bus-emergency-door-release',
    name: 'Acil Kapı Açma',
    system: 'muayene',
    licences: ['d'],
    desc: 'Kapıyı havalı sistemden bağımsız açan acil durum valfi.',
    tip: 'Yolcu kabininde de bulunur; yerini ve kullanımını sefer öncesi yolculara göster.',
  },
  {
    id: 'bus-emergency-hammer',
    name: 'Cam Kırma Çekici',
    system: 'muayene',
    licences: ['d'],
    desc: 'Acil durumda camı kırıp tahliye sağlayan uçlu çekiç.',
    tip: 'Cam köşeden kırılır; çekiç yuvasında ve erişilebilir olmalıdır.',
  },
  {
    id: 'bus-fire-extinguisher',
    name: 'Yangın Söndürücü (6 kg)',
    system: 'muayene',
    licences: ['d'],
    desc: 'Otobüslerde zorunlu, büyük kapasiteli kuru tozlu söndürücü.',
    tip: 'Basınç saati yeşil bölgede olmalı; son kontrol tarihi geçmişse dolum yaptırılır.',
  },
  {
    id: 'bus-first-aid-kit',
    name: 'İlk Yardım Çantası (yolcu kapasiteli)',
    system: 'muayene',
    licences: ['d'],
    desc: 'Yolcu kapasitesine göre boyutlanan ilk yardım çantası.',
    tip: 'Malzemelerin son kullanma tarihi kontrol edilir; eksik malzeme sefer öncesi tamamlanır.',
  },
];

/** Mobil içerik anlık görüntüsünde servis edilen TAM liste (web listesi değişmez). */
export const LICENCE_PARTS: VehiclePart[] = [...MOTO_PARTS, ...BUS_PARTS];
