/**
 * ÖZGÜN ilk yardım soruları — 7. genişletme (Program 2 · Faz 9). ROADMAP C.4/E.6.
 * Kaynak = Resmî temel ilk yardım rehberleri; KENDİ İFADEMİZLE. Uzman onayı gereklidir.
 */
import type { QuestionInput } from '@ea/content-schema';

const SRC = 'Resmî temel ilk yardım rehberleri (özgün ifade; uzman onayı gerekli)';

export const ILKYARDIM_QUESTIONS_7: QuestionInput[] = [
  {
    id: 'ilkyardim-701',
    subject: 'ilkyardim',
    topic: 'ilkyardim-tanimi',
    difficulty: 'kolay',
    stem: 'İlk yardım kavramı en doğru biçimde nasıl tanımlanır?',
    options: [
      'Hasta veya yaralıya, olay yerinde eldeki imkânlarla ilaçsız olarak yapılan geçici destek uygulamalarıdır',
      'Yalnızca hastanede doktorların uyguladığı kesin tedavi yöntemidir',
      'Yalnızca ambulans ekiplerinin yapabileceği ameliyat öncesi işlemdir',
      'Yaralıya reçeteli ilaç yazma ve iğne yapma işlemidir',
    ],
    answerIndex: 0,
    explanation:
      'İlk yardım; hasta ya da yaralıya sağlık ekibi gelene kadar, olay yerinde mevcut araç gereçle ve ilaç kullanmadan yapılan geçici destek uygulamalarıdır. Amacı kesin tedavi değil, durumu koruyup kötüleşmeyi önlemektir.',
    whyWrong: [
      'Kesin tedavi ve ameliyat sağlık kuruluşlarında hekimlerce yapılan işlemlerdir; ilk yardım bunların yerini almaz.',
      'İlaç yazmak ve iğne yapmak ilk yardımın kapsamı dışındadır.',
    ],
    objective: 'İlk yardımın ilaçsız ve geçici destek olduğunu kavramak.',
    tags: ['ilkyardim-tanimi', 'tanim', 'ilacsiz'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-702',
    subject: 'ilkyardim',
    topic: 'ilkyardim-amaci',
    difficulty: 'kolay',
    stem: 'Aşağıdakilerden hangisi ilk yardımın temel amaçları arasında yer almaz?',
    options: [
      'Yaşamsal işlevleri sürdürerek hayatı kurtarmak',
      'Durumun daha kötüye gitmesini önlemek',
      'İyileşmeyi kolaylaştırmak',
      'Yaralıya kesin tanı koyup ilaçla tedavi etmek',
    ],
    answerIndex: 3,
    explanation:
      'İlk yardımın temel amaçları hayatı kurtarmak, durumun kötüleşmesini önlemek ve iyileşmeyi kolaylaştırmaktır. Kesin tanı koymak ve ilaçla tedavi etmek ise sağlık kuruluşlarının görevidir, ilk yardımın amacı değildir.',
    whyWrong: [
      'Hayatı kurtarmak, kötüleşmeyi önlemek ve iyileşmeyi kolaylaştırmak ilk yardımın bilinen amaçlarıdır.',
      'Tanı ve ilaçlı tedavi ilk yardımcının değil, hekimin sorumluluğundadır.',
    ],
    objective: 'İlk yardımın üç temel amacını tanımak.',
    tags: ['ilkyardim-amaci', 'amac', 'hayat-kurtarma'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-703',
    subject: 'ilkyardim',
    topic: 'ilkyardim-acil-tedavi-farki',
    difficulty: 'zor',
    stem: 'İlk yardım ile acil (tıbbi) tedavi arasındaki temel fark aşağıdakilerden hangisidir?',
    options: [
      'İkisi de yalnızca hastanede ve aynı kişiler tarafından yapılır',
      'İlk yardım ilaç ve tıbbi araçlarla yapılırken acil tedavi çıplak elle yapılır',
      'İlk yardım herhangi bir eğitimli kişinin olay yerinde ilaçsız yaptığı destek; acil tedavi ise sağlık personelinin araç, gereç ve ilaçla yaptığı tıbbi müdahaledir',
      'Aralarında hiçbir fark yoktur; iki kavram aynı şeyi anlatır',
    ],
    answerIndex: 2,
    explanation:
      'İlk yardım; ilaç ve özel tıbbi donanım olmadan, eğitim almış herhangi bir kişinin olay yerinde yaptığı geçici destektir. Acil tedavi ise doktor, hemşire, sağlık teknisyeni gibi personelin gerekli araç, gereç ve ilaçlarla uyguladığı tıbbi müdahaledir.',
    whyWrong: [
      'İlk yardım hastane dışında ve ilaçsız yapılır; ikisini aynı saymak yanlıştır.',
      'İlaç ve tıbbi araç kullanan taraf acil tedaviyi yürüten sağlık personelidir, ilk yardımcı değil.',
    ],
    objective: 'İlk yardım ile acil tedavinin farkını kavramak.',
    tags: ['ilkyardim-acil-tedavi-farki', 'fark', 'saglik-personeli'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-704',
    subject: 'ilkyardim',
    topic: 'ilkyardimci-ozellikleri',
    difficulty: 'kolay',
    stem: 'Bir ilk yardımcıda bulunması beklenen özelliklerden biri aşağıdakilerden hangisidir?',
    options: [
      'Sakin kalıp hızlı ve doğru karar verebilmek',
      'Panikleyerek çevredekileri de telaşa sürüklemek',
      'Yaralıya bilinen tüm ilaçları denemek',
      'Olay yerinden hemen uzaklaşarak sorumluluktan kaçınmak',
    ],
    answerIndex: 0,
    explanation:
      'İyi bir ilk yardımcı sakin ve soğukkanlı kalır, durumu doğru değerlendirip hızlı ve isabetli karar verir. Telaş, doğru müdahaleyi ve çevrenin güvenini olumsuz etkiler.',
    whyWrong: [
      'Panik yaymak hem ilk yardımcının hem çevrenin doğru davranmasını engeller.',
      'İlaç denemek ya da olay yerini terk etmek ilk yardımcı tutumuyla bağdaşmaz.',
    ],
    objective: 'İlk yardımcının sakin ve hızlı karar verme özelliğini bilmek.',
    tags: ['ilkyardimci-ozellikleri', 'sakinlik', 'karar'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-705',
    subject: 'ilkyardim',
    topic: 'ilkyardimci-tanimi',
    difficulty: 'kolay',
    stem: 'İlk yardımcı kime denir?',
    options: [
      'İlk yardım eğitimi almış ve gerektiğinde bu bilgiyi uygulayabilen herhangi bir kişiye',
      'Sadece hastanede görev yapan doktor ve hemşirelere',
      'Yalnızca ambulans şoförlerine',
      'Kaza yerinden geçen ama hiç eğitimi olmayan herkese',
    ],
    answerIndex: 0,
    explanation:
      'İlk yardımcı; ilk yardım eğitimi almış, olay yerinde durumu değerlendirip uygun geçici müdahaleyi yapabilen kişidir. Sağlık personeli olması şart değildir; eğitim almış herhangi bir vatandaş ilk yardımcı olabilir.',
    whyWrong: [
      'İlk yardımcı olmak yalnızca hastane çalışanlarına veya belirli mesleklere özgü değildir.',
      'Hiç eğitim almamış kişi ilk yardımcı sayılmaz; ölçüt uygun eğitimi almış olmaktır.',
    ],
    objective: 'İlk yardımcının eğitim almış kişi olduğunu bilmek.',
    tags: ['ilkyardimci-tanimi', 'egitim', 'tanim'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-706',
    subject: 'ilkyardim',
    topic: 'kbk-siralamasi',
    difficulty: 'orta',
    stem: 'İlk yardımın temel uygulama basamakları olan "Koruma - Bildirme - Kurtarma (KBK)" ne anlama gelir?',
    options: [
      'Önce olay yerini ve kişileri yeni tehlikelerden koru, sonra 112’ye haber ver, ardından uygun şekilde kurtarma/müdahale yap',
      'Önce yaralıyı kurtar, sonra 112’yi ara, en son olay yerini güvene al',
      'Önce fotoğraf çek, sonra yaralıyı taşı, en son haber ver',
      'Önce yaralıya su ver, sonra araca bindir, en son bekle',
    ],
    answerIndex: 0,
    explanation:
      'KBK sıralaması; önce olay yerini ve oradaki kişileri yeni tehlikelerden korumayı (Koruma), ardından 112’ye haber vermeyi (Bildirme), sonra da yaralılara uygun biçimde müdahale/kurtarma yapmayı (Kurtarma) ifade eder. Bu sıra, hem ilk yardımcıyı hem yaralıyı güvende tutar.',
    whyWrong: [
      'Kurtarmayı ilk sıraya almak, güvenlik alınmadan müdahale edileceği için ikinci bir kazaya yol açabilir.',
      'Fotoğraf çekmek veya su vermek KBK basamaklarının hiçbirinin yerini tutmaz.',
    ],
    objective: 'Koruma-Bildirme-Kurtarma sırasını kavramak.',
    tags: ['kbk-siralamasi', 'koruma-bildirme-kurtarma', 'siralama'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-707',
    subject: 'ilkyardim',
    topic: 'koruma-asamasi',
    difficulty: 'kolay',
    stem: 'İlk yardımdaki "Koruma" basamağı öncelikle neyi amaçlar?',
    options: [
      'Olay yerinde yeni kazaların ve tehlikelerin oluşmasını önleyerek herkesin güvenliğini sağlamayı',
      'Yaralının eşyalarını korumayı',
      'Yaralının kimlik bilgilerini gizlemeyi',
      'Kaza yerini olduğu gibi bırakıp hiçbir önlem almamayı',
    ],
    answerIndex: 0,
    explanation:
      'Koruma basamağının amacı, olay yerini güvenli hâle getirerek yeni kazaların ve ek tehlikelerin (yangın, ikinci çarpma vb.) oluşmasını önlemektir. Böylece hem yaralılar hem ilk yardımcı korunmuş olur.',
    whyWrong: [
      'Koruma, eşya veya kimlik gizleme ile ilgili değildir.',
      'Hiçbir önlem almamak korumanın amacına aykırıdır.',
    ],
    objective: 'Koruma basamağının güvenlik amacını bilmek.',
    tags: ['koruma-asamasi', 'guvenlik', 'ikinci-kaza'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-708',
    subject: 'ilkyardim',
    topic: 'bildirme-asamasi',
    difficulty: 'kolay',
    stem: 'İlk yardımdaki "Bildirme" basamağı hangi davranışı ifade eder?',
    options: [
      'Olayı en yakın komşuya anlatmayı',
      'Durumu sosyal medyada paylaşmayı',
      'Acil sağlık yardımı için 112’yi arayarak olayı yetkililere haber vermeyi',
      'Yaralıya olay hakkında bilgi vermeyi',
    ],
    answerIndex: 2,
    explanation:
      'Bildirme basamağı, acil sağlık hattı 112’nin aranarak olayın türü, yeri ve yaralı durumunun yetkili birimlere iletilmesini kapsar. Bu adım, profesyonel yardımın en kısa sürede yola çıkmasını sağlar.',
    whyWrong: [
      'Komşuya anlatmak veya sosyal medyada paylaşmak yetkili sağlık birimlerine haber vermenin yerini tutmaz.',
      'Bildirmenin muhatabı yaralı değil, acil yardım hizmetleridir.',
    ],
    objective: 'Bildirme basamağının 112’yi aramak olduğunu bilmek.',
    tags: ['bildirme-asamasi', '112', 'haber-verme'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-709',
    subject: 'ilkyardim',
    topic: '112-bilgi-verme',
    difficulty: 'orta',
    stem: '112 arandığında ilk yardımcının vermesi gereken bilgiler arasında aşağıdakilerden hangisi bulunmaz?',
    options: [
      'Olayın olduğu kesin adres/yer',
      'Olayın türü ve nasıl geliştiği',
      'Yaralı sayısı ve genel durumları',
      'İlk yardımcının aylık geliri',
    ],
    answerIndex: 3,
    explanation:
      '112 aranırken kesin yer/adres, olayın türü, yaralı sayısı ve durumları ile arayan kişinin kimliği bildirilir. İlk yardımcının kişisel geliri gibi bilgilerin acil müdahaleyle hiçbir ilgisi yoktur.',
    whyWrong: [
      'Adres, olayın türü ve yaralı sayısı, ekibin doğru yönlendirilmesi için gereken temel bilgilerdir.',
      'Gelir gibi kişisel maddi bilgiler acil çağrının içeriğine girmez.',
    ],
    objective: '112’ye verilecek temel bilgileri ayırt etmek.',
    tags: ['112-bilgi-verme', 'yer-olay-sayi-durum', 'ihbar'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-710',
    subject: 'ilkyardim',
    topic: '112-arama',
    difficulty: 'orta',
    stem: '112 ile yapılan görüşmede telefonun kapatılmasıyla ilgili doğru davranış hangisidir?',
    options: [
      'Bilgi verir vermez hemen kapatmak',
      'Görevliye hiç konuşma fırsatı vermeden kapatmak',
      'Görevli gerekli bilgileri alıp "kapatabilirsiniz" diyene kadar hattı açık tutmak',
      'Telefonu sürekli açıp kapatarak zaman kazanmak',
    ],
    answerIndex: 2,
    explanation:
      '112 görüşmesinde hattı ilk kapatan taraf ilk yardımcı olmamalıdır. Görevli, adresi ve durumu netleştirmek için ek sorular sorabilir ya da yönlendirme verebilir; bu nedenle görevli izin verene kadar telefon açık tutulur.',
    whyWrong: [
      'Erken kapatmak, görevlinin eksik bilgiyi tamamlamasını ve yönlendirme yapmasını engeller.',
      'Telefonu gereksiz açıp kapatmak iletişimi bozar ve zaman kaybettirir.',
    ],
    objective: 'Hattı görevli kapatana kadar açık tutmayı bilmek.',
    tags: ['112-arama', 'hat-kapatma', 'gorevli'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-711',
    subject: 'ilkyardim',
    topic: 'hayat-kurtarma-zinciri',
    difficulty: 'orta',
    stem: 'İlk yardımda sıkça kullanılan "hayat kurtarma zinciri" kavramı en iyi nasıl açıklanır?',
    options: [
      'Yaralının koluna takılan metal bir bileziktir',
      'Yalnızca hastanede uygulanan bir ameliyat tekniğidir',
      'Yaşamı kurtarmak için birbirini izleyen ve her biri diğerini tamamlayan halkalardan (haber verme, olay yerinde temel yaşam desteği, hızlı ve uygun nakil, hastanede tedavi) oluşan süreçtir',
      'Yaralıyı bağlamak için kullanılan bir sabitleme yöntemidir',
    ],
    answerIndex: 2,
    explanation:
      'Hayat kurtarma zinciri; acil yardımı haber verme, olay yerinde temel yaşam desteği uygulama, hızlı ve uygun biçimde nakletme ve hastanede ileri tedavi gibi birbirine bağlı halkalardan oluşur. Bir halkanın zayıf kalması, tüm zincirin etkisini azaltır.',
    whyWrong: [
      'Kavram fiziksel bir bileklik ya da sabitleme aracı değildir.',
      'Zincir yalnızca hastane aşamasını değil, haber vermeden tedaviye kadar tüm süreci kapsar.',
    ],
    objective: 'Hayat kurtarma zincirinin birbirine bağlı halkalar olduğunu kavramak.',
    tags: ['hayat-kurtarma-zinciri', 'zincir', 'sureç'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-712',
    subject: 'ilkyardim',
    topic: 'normal-nabiz',
    difficulty: 'kolay',
    stem: 'Sağlıklı bir erişkinde dinlenme hâlindeki normal nabız (kalp atım) sayısı yaklaşık hangi aralıktadır?',
    options: ['Dakikada 20-40', 'Dakikada 140-180', 'Dakikada 60-100', 'Dakikada 200-240'],
    answerIndex: 2,
    explanation:
      'Sağlıklı bir erişkinde dinlenme sırasında nabız genellikle dakikada 60-100 arasındadır. Bu değerin belirgin biçimde altına inmesi ya da üstüne çıkması, durumun değerlendirilmesi için önemli bir bulgu olabilir.',
    whyWrong: [
      'Dakikada 20-40 gibi çok düşük değerler erişkin için normal dinlenim nabzı değildir.',
      'Dakikada 140 ve üzeri değerler dinlenimdeki sağlıklı erişkin için beklenen aralık dışındadır.',
    ],
    objective: 'Erişkinde normal nabız aralığını bilmek.',
    tags: ['normal-nabiz', 'yasam-bulgulari', 'erişkin'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-713',
    subject: 'ilkyardim',
    topic: 'normal-solunum',
    difficulty: 'kolay',
    stem: 'Sağlıklı bir erişkinde dinlenme hâlindeki normal solunum (nefes alıp verme) sayısı yaklaşık kaçtır?',
    options: ['Dakikada 2-5', 'Dakikada 40-50', 'Dakikada 70-80', 'Dakikada 12-20'],
    answerIndex: 3,
    explanation:
      'Sağlıklı erişkinde dinlenirken solunum sayısı genellikle dakikada 12-20 arasındadır. Bir dakikada göğsün kaç kez inip kalktığı sayılarak değerlendirilir; belirgin sapmalar solunum sorununu düşündürebilir.',
    whyWrong: [
      'Dakikada 2-5 gibi çok düşük bir hız erişkin için normal değildir ve solunum yetersizliğine işaret eder.',
      'Dakikada 40 ve üzeri değerler dinlenimdeki sağlıklı erişkinde beklenmez.',
    ],
    objective: 'Erişkinde normal solunum aralığını bilmek.',
    tags: ['normal-solunum', 'yasam-bulgulari', 'solunum-sayisi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-714',
    subject: 'ilkyardim',
    topic: 'vucut-sicakligi',
    difficulty: 'kolay',
    stem: 'Sağlıklı bir insanda normal vücut sıcaklığı yaklaşık hangi aralıkta kabul edilir?',
    options: ['30-32 °C', '39-40 °C', '41-42 °C', '36-37 °C'],
    answerIndex: 3,
    explanation:
      'Sağlıklı bir insanda vücut sıcaklığı yaklaşık 36-37 °C dolayındadır. Bu değerin belirgin şekilde yükselmesi (ateş) veya düşmesi (hipotermi) vücutta bir sorun olduğunu gösterebilir.',
    whyWrong: [
      '30-32 °C aşırı düşük bir değerdir ve ciddi hipotermiye işaret eder; normal kabul edilmez.',
      '39 °C ve üzeri değerler ateş sınırındadır; sağlıklı normal aralığın üstündedir.',
    ],
    objective: 'Normal vücut sıcaklığı aralığını bilmek.',
    tags: ['vucut-sicakligi', 'yasam-bulgulari', 'normal-deger'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-715',
    subject: 'ilkyardim',
    topic: 'nabiz-olcumu',
    difficulty: 'orta',
    stem: 'Bir erişkinde nabız değerlendirilirken en sık kullanılan bölgelerden biri hangisidir?',
    options: [
      'Alın derisi',
      'Kulak memesi',
      'Ayak tırnağı',
      'Bilekteki atardamar (el bileği iç kısmı) veya boyundaki şah damarı',
    ],
    answerIndex: 3,
    explanation:
      'Nabız, atardamarın cilde yakın geçtiği yerlerden parmak uçlarıyla hissedilir. En sık el bileğinin iç kısmındaki atardamardan veya boyundaki şah damarından değerlendirilir. Nabız, başparmakla değil diğer parmakların uçlarıyla sayılır.',
    whyWrong: [
      'Alın, kulak memesi ya da ayak tırnağı nabzın güvenilir biçimde sayıldığı bölgeler değildir.',
      'Nabız hissetmek için atardamarın yüzeye yakın seyrettiği bölgeler seçilir.',
    ],
    objective: 'Nabzın hangi bölgelerden değerlendirildiğini bilmek.',
    tags: ['nabiz-olcumu', 'sah-damari', 'bilek'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-716',
    subject: 'ilkyardim',
    topic: 'kanin-gorevleri',
    difficulty: 'orta',
    stem: 'Kanın vücuttaki temel görevlerinden biri aşağıdakilerden hangisidir?',
    options: [
      'Kemikleri birbirine bağlamak',
      'Sesi iletmek',
      'Gözün görmesini sağlamak',
      'Oksijen ve besinleri dokulara taşımak, karbondioksit ve atık maddeleri uzaklaştırmak',
    ],
    answerIndex: 3,
    explanation:
      'Kan; akciğerlerden aldığı oksijeni ve sindirimden gelen besinleri dokulara taşır, dokularda oluşan karbondioksit ve atık maddeleri uzaklaştırır. Ayrıca vücut ısısının dağıtılmasına ve mikroplara karşı savunmaya da katkıda bulunur.',
    whyWrong: [
      'Kemikleri bağlamak bağ dokusunun ve eklemlerin görevidir, kanın değil.',
      'Ses iletimi ve görme, kanın taşıma görevinden farklı sistemlerin işleridir.',
    ],
    objective: 'Kanın taşıma görevini kavramak.',
    tags: ['kanin-gorevleri', 'oksijen-tasima', 'atik'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-717',
    subject: 'ilkyardim',
    topic: 'dolasim-sistemi',
    difficulty: 'orta',
    stem: 'Dolaşım sistemi temel olarak hangi yapılardan oluşur ve görevi nedir?',
    options: [
      'Yalnızca akciğerlerden oluşur; nefes almayı sağlar',
      'Kalp ve damarlardan oluşur; kanı vücuda pompalayıp dolaştırır',
      'Yalnızca kemiklerden oluşur; vücuda destek verir',
      'Yalnızca mide ve bağırsaklardan oluşur; besinleri sindirir',
    ],
    answerIndex: 1,
    explanation:
      'Dolaşım sistemi kalp ve damarlardan (atardamar, toplardamar, kılcal damar) oluşur. Kalp bir pompa gibi çalışarak kanı damarlar aracılığıyla tüm vücuda gönderir; böylece oksijen ve besin dokulara ulaşır, atıklar uzaklaştırılır.',
    whyWrong: [
      'Akciğerler solunum sisteminin, kemikler iskelet sisteminin, mide-bağırsaklar sindirim sisteminin parçasıdır.',
      'Dolaşımın merkezinde kanı pompalayan kalp ve onu taşıyan damarlar vardır.',
    ],
    objective: 'Dolaşım sisteminin kalp-damar yapısını kavramak.',
    tags: ['dolasim-sistemi', 'kalp', 'damar'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-718',
    subject: 'ilkyardim',
    topic: 'damar-cesitleri',
    difficulty: 'zor',
    stem: 'Atardamar, toplardamar ve kılcal damarın görevleriyle ilgili aşağıdakilerden hangisi doğrudur?',
    options: [
      'Atardamarlar kanı kalpten dokulara taşır; toplardamarlar kanı dokulardan kalbe geri getirir; kılcal damarlarda ise dokuyla alışveriş olur',
      'Atardamarlar kanı kalbe getirir; toplardamarlar kanı kalpten uzaklaştırır',
      'Kılcal damarlar kanı yalnızca depolar, hiç akış olmaz',
      'Üç damar türü de aynı görevi yapar, aralarında fark yoktur',
    ],
    answerIndex: 0,
    explanation:
      'Atardamarlar kanı kalpten alıp dokulara götürür; toplardamarlar kanı dokulardan toplayıp kalbe geri getirir. Kılcal damarlar ise atardamar ile toplardamar arasında yer alır ve oksijen, besin ile atık maddelerin dokuyla değiş tokuş edildiği ince damarlardır.',
    whyWrong: [
      'Kanı kalpten götüren atardamar, kalbe getiren toplardamardır; bunları ters tanımlamak yanlıştır.',
      'Kılcal damarlar kanı yalnızca depolamaz; asıl işlevleri madde alışverişidir ve üç damar türünün görevleri farklıdır.',
    ],
    objective: 'Damar türlerinin görevlerini ayırt etmek.',
    tags: ['damar-cesitleri', 'atardamar', 'toplardamar'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-719',
    subject: 'ilkyardim',
    topic: 'solunum-sistemi',
    difficulty: 'orta',
    stem: 'Solunum sistemiyle ilgili aşağıdakilerden hangisi doğrudur?',
    options: [
      'Kalp ve damarlardan oluşur; kanı pompalar',
      'Burun, soluk (nefes) borusu ve akciğerlerden oluşur; havadaki oksijenin alınıp karbondioksitin verilmesini sağlar',
      'Yalnızca mideden oluşur; besinleri parçalar',
      'Yalnızca kemik ve kaslardan oluşur; hareketi sağlar',
    ],
    answerIndex: 1,
    explanation:
      'Solunum sistemi başlıca burun, soluk borusu ve akciğerlerden oluşur. Bu sistem, soluk alırken havadaki oksijeni vücuda alır ve soluk verirken kandaki karbondioksiti dışarı atar; böylece dokuların oksijen ihtiyacı karşılanır.',
    whyWrong: [
      'Kalp ve damarlar dolaşım sistemine, mide sindirime, kemik-kas ise iskelet-kas sistemine aittir.',
      'Solunumun temel işlevi oksijen almak ve karbondioksit vermektir.',
    ],
    objective: 'Solunum sisteminin yapı ve görevini kavramak.',
    tags: ['solunum-sistemi', 'akciger', 'oksijen'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-720',
    subject: 'ilkyardim',
    topic: 'solunum-sistemi-gorev',
    difficulty: 'kolay',
    stem: 'Soluk (nefes) verme sırasında vücuttan dışarı atılan başlıca gaz hangisidir?',
    options: [
      'Oksijen',
      'Karbondioksit',
      'Azot gazının tamamı',
      'Su buharı yerine hiçbir gaz atılmaz',
    ],
    answerIndex: 1,
    explanation:
      'Soluk alırken havadaki oksijen kana geçer; soluk verirken ise dokularda oluşan karbondioksit akciğerler yoluyla dışarı atılır. Bu alışveriş, hücrelerin canlı kalması için süreklidir.',
    whyWrong: [
      'Oksijen soluk verirken atılan değil, soluk alırken vücuda alınan gazdır.',
      'Soluk vermede dışarı verilen başlıca gaz karbondioksittir; "hiçbir gaz atılmaz" ifadesi yanlıştır.',
    ],
    objective: 'Soluk vermede karbondioksitin atıldığını bilmek.',
    tags: ['solunum-sistemi-gorev', 'karbondioksit', 'gaz-alisverisi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-721',
    subject: 'ilkyardim',
    topic: 'iskelet-kas-sistemi',
    difficulty: 'orta',
    stem: 'İskelet ve kas sisteminin vücuttaki görevlerinden biri aşağıdakilerden hangisidir?',
    options: [
      'Kanı temizleyip idrar üretmek',
      'Besinleri sindirip emmek',
      'Vücuda destek ve şekil vermek, hareketi sağlamak ve bazı iç organları korumak',
      'Havadaki oksijeni kana geçirmek',
    ],
    answerIndex: 2,
    explanation:
      'İskelet, vücuda destek ve şekil verir, kalp-akciğer-beyin gibi organları çevreleyerek korur. Kaslar ise kemiklerle birlikte çalışarak hareketi sağlar. Bu iki yapı birlikte iskelet-kas sistemini oluşturur.',
    whyWrong: [
      'İdrar üretimi boşaltım sisteminin, sindirim ve emilim sindirim sisteminin görevidir.',
      'Oksijeni kana geçirmek solunum sisteminin işidir, iskelet-kas sisteminin değil.',
    ],
    objective: 'İskelet-kas sisteminin destek, hareket ve koruma görevini kavramak.',
    tags: ['iskelet-kas-sistemi', 'hareket', 'destek'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-722',
    subject: 'ilkyardim',
    topic: 'sindirim-bosaltim',
    difficulty: 'orta',
    stem: 'Sindirim ve boşaltım sistemleriyle ilgili aşağıdakilerden hangisi doğrudur?',
    options: [
      'Sindirim sistemi besinleri parçalayıp vücuda yararlı hâle getirir; boşaltım sistemi ise atık maddeleri (örneğin idrarı) vücuttan uzaklaştırır',
      'Sindirim sistemi kanı pompalar; boşaltım sistemi nefes aldırır',
      'İki sistem de yalnızca kemik yapımından sorumludur',
      'Sindirim sistemi görme, boşaltım sistemi işitmeyi sağlar',
    ],
    answerIndex: 0,
    explanation:
      'Sindirim sistemi; ağız, mide ve bağırsaklar yardımıyla besinleri parçalayıp emilebilir hâle getirir. Boşaltım sistemi ise başta böbrekler olmak üzere organlarla, vücutta oluşan atık maddeleri idrar biçiminde dışarı atar.',
    whyWrong: [
      'Kan pompalamak dolaşımın, nefes aldırmak solunumun görevidir.',
      'Bu sistemler kemik yapımından, görme veya işitmeden sorumlu değildir.',
    ],
    objective: 'Sindirim ve boşaltım sistemlerinin temel görevlerini ayırt etmek.',
    tags: ['sindirim-bosaltim', 'besin', 'atik'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-723',
    subject: 'ilkyardim',
    topic: 'ilkyardim-cantasi',
    difficulty: 'kolay',
    stem: 'Standart bir ilk yardım çantasında aşağıdakilerden hangisinin bulunması beklenmez?',
    options: [
      'Steril gazlı bez ve sargı bezleri',
      'Üçgen sargı, flaster ve makas',
      'Tek kullanımlık eldiven ve çengelli iğne',
      'Reçeteyle satılan güçlü ağrı kesici ve uyku ilaçları',
    ],
    answerIndex: 3,
    explanation:
      'İlk yardım çantasında steril gazlı bez, sargı bezleri, üçgen sargı, flaster, makas, çengelli iğne ve tek kullanımlık eldiven gibi malzemeler bulunur. İlk yardımda ilaç verilmediği için çantada reçeteli güçlü ilaçların bulundurulması uygun değildir.',
    whyWrong: [
      'Gazlı bez, sargı, üçgen sargı, eldiven ve makas ilk yardım çantasının bilinen içerikleridir.',
      'İlk yardımcı ilaç uygulamadığından çantaya reçeteli ilaç konması amaca aykırıdır.',
    ],
    objective: 'İlk yardım çantasının içeriğini ve ilaç bulundurulmadığını bilmek.',
    tags: ['ilkyardim-cantasi', 'malzeme', 'ilacsiz'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-724',
    subject: 'ilkyardim',
    topic: 'ucgen-sargi',
    difficulty: 'orta',
    stem: 'Üçgen sargı ilk yardımda en çok hangi amaçla kullanılır?',
    options: [
      'Yaralıya içecek taşımak için',
      'Kırık şüphesi olan kolu göğse asarak desteklemek (kol askısı) ve geniş bölgeleri sarıp sabitlemek için',
      'Olay yerini işaretlemek için',
      'Yaralının yüzünü tamamen kapatmak için',
    ],
    answerIndex: 1,
    explanation:
      'Üçgen sargı, kırık ya da yaralanma şüphesi olan kolu göğse asarak desteklemek (kol askısı yapmak), geniş yüzeyleri örtmek ve bölgeleri sabitlemek için kullanılan çok amaçlı bir sargıdır. Doğru uygulandığında yaralı bölgenin hareketini azaltır.',
    whyWrong: [
      'Üçgen sargı içecek taşımak veya olay yeri işaretlemek için tasarlanmış bir gereç değildir.',
      'Bilinci olan yaralının yüzünü tümüyle kapatmak solunumu engelleyebilir; sargının amacı bu değildir.',
    ],
    objective: 'Üçgen sargının kol askısı ve sabitleme amaçlarını bilmek.',
    tags: ['ucgen-sargi', 'kol-askisi', 'sabitleme'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-725',
    subject: 'ilkyardim',
    topic: 'turnike-endikasyon',
    difficulty: 'zor',
    stem: 'Aşağıdaki durumların hangisinde turnike uygulaması gündeme gelir?',
    options: [
      'Küçük bir kesikte kan sızması durumunda',
      'Burun kanamasında',
      'Doğrudan baskı gibi yöntemlerle durdurulamayan, hayatı tehdit eden kol veya bacak kanamasında ya da uzuv kopmasında son çare olarak',
      'Her türlü yüzeysel sıyrıkta ilk seçenek olarak',
    ],
    answerIndex: 2,
    explanation:
      'Turnike; doğrudan baskı ve bölgeyi yükseltme gibi yöntemlerle durdurulamayan, yaşamı tehdit eden kol/bacak kanamalarında veya uzuv kopması gibi durumlarda son çare olarak uygulanır. Gereksiz kullanımı dokuya zarar verebileceğinden ilk tercih değildir.',
    whyWrong: [
      'Küçük kesik, burun kanaması veya yüzeysel sıyrık turnike gerektirmez; bunlarda baskı yeterlidir.',
      'Turnike hiçbir zaman ilk seçenek değildir; ancak diğer yöntemler yetersiz kaldığında düşünülür.',
    ],
    objective: 'Turnikenin hangi durumlarda son çare olduğunu bilmek.',
    tags: ['turnike-endikasyon', 'son-care', 'hayati-kanama'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-726',
    subject: 'ilkyardim',
    topic: 'atardamar-kanama-mudahale',
    difficulty: 'zor',
    stem: 'Kolundan parlak kırmızı kanın fışkırdığı (atardamar kanaması) bilinci açık bir yaralıda ilk yardımcının izleyeceği doğru yaklaşım hangisidir?',
    options: [
      'Kanamayı görmezden gelip yalnızca su içirmek',
      'Yaraya çıplak elle bastırıp beklemek dışında hiçbir şey yapmamak',
      'Kanayan yere temiz bir bezle hemen ve kuvvetle doğrudan baskı uygulamak, kırık yoksa bölgeyi kalp seviyesinin üstüne kaldırmak ve 112’yi aramak; durdurulamıyorsa son çare olarak turnikeyi düşünmek',
      'Yaraya diş macunu sürüp sıkıca kapatmak',
    ],
    answerIndex: 2,
    explanation:
      'Atardamar kanaması hızlı kan kaybı riski taşıdığından acildir. Öncelik, temiz bir bezle kanayan bölgeye kuvvetli ve kesintisiz doğrudan baskı uygulamak, kırık yoksa bölgeyi kalp seviyesinin üstüne kaldırmak ve 112’yi aramaktır. Baskıyla durmayan, hayatı tehdit eden kanamada son çare olarak turnike düşünülür.',
    whyWrong: [
      'Kanamayı görmezden gelmek veya su içirmek hızlı kan kaybını durdurmaz.',
      'Yaraya diş macunu gibi maddeler sürmek kanamayı durdurmaz, enfeksiyon riskini artırır; çıplak elle temas yerine mümkünse eldiven/temiz bez kullanılmalıdır.',
    ],
    objective: 'Atardamar kanamasında baskı-yükseltme-112 sırasını kavramak.',
    tags: ['atardamar-kanama-mudahale', 'dogrudan-baski', 'acil'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-727',
    subject: 'ilkyardim',
    topic: 'bilinc-duzeyleri',
    difficulty: 'orta',
    stem: 'Bilinç düzeyiyle ilgili aşağıdaki sıralamalardan hangisi, en iyiden en ağıra doğru doğru verilmiştir?',
    options: [
      'Bilinçsiz → uykuya meyilli → uyanık (bilinci açık)',
      'Uyanık (bilinci açık) → uykuya meyilli (uyaranla yanıt veren) → bilinçsiz (yanıt vermeyen)',
      'Uykuya meyilli → uyanık → bilinçsiz',
      'Bilinç düzeyleri arasında bir sıralama yapılamaz',
    ],
    answerIndex: 1,
    explanation:
      'Bilinç düzeyi en iyiden en ağıra doğru genellikle şöyle değerlendirilir: uyanık ve çevresine tam yanıt veren (bilinci açık), uyarınca güçlükle yanıt veren (uykuya meyilli) ve hiçbir uyarana yanıt vermeyen (bilinçsiz). Yanıtın azalması durumun ağırlaştığını gösterir.',
    whyWrong: [
      'Bilinçsizle başlayan sıralama en iyiden en ağıra doğru olmadığı için yanlıştır.',
      'Uykuya meyilli durumu uyanıktan daha ağır olduğundan başa yazılamaz; ayrıca düzeyler arasında belirgin bir sıralama vardır.',
    ],
    objective: 'Bilinç düzeylerini iyiden ağıra sıralayabilmek.',
    tags: ['bilinc-duzeyleri', 'uyanik', 'bilincsiz'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-728',
    subject: 'ilkyardim',
    topic: 'gozbebegi-isik-tepkisi',
    difficulty: 'zor',
    stem: 'Sağlıklı bir kişide göz bebeklerinin ışığa verdiği normal tepki nasıldır?',
    options: [
      'Işık tutulduğunda göz bebekleri büyür',
      'Işık tutulduğunda göz bebekleri küçülür ve iki göz genellikle birbirine denk tepki verir',
      'Işıkta göz bebekleri hiç değişmez',
      'Işıkta yalnızca bir göz bebeği tamamen kaybolur',
    ],
    answerIndex: 1,
    explanation:
      'Normalde göze ışık tutulduğunda göz bebekleri küçülür (kasılır); karanlıkta ise büyür. Sağlıklı bir kişide her iki göz bebeği birbirine denk büyüklükte olup ışığa benzer biçimde tepki verir. Işığa tepkisizlik ya da iki göz arasında belirgin eşitsizlik önemli bir uyarı bulgusu olabilir.',
    whyWrong: [
      'Aydınlıkta göz bebeği büyümez, tersine küçülür.',
      'Göz bebeklerinin ışıkta hiç değişmemesi ya da birinin kaybolması normal bir tepki değildir.',
    ],
    objective: 'Göz bebeğinin ışıkta küçülme tepkisini bilmek.',
    tags: ['gozbebegi-isik-tepkisi', 'isik-refleksi', 'degerlendirme'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-729',
    subject: 'ilkyardim',
    topic: 'gozbebegi-kontrolu',
    difficulty: 'orta',
    stem: 'Bir yaralıda göz bebeklerinin büyüklüğünün ve ışığa tepkisinin kontrol edilmesi ilk yardımcıya öncelikle ne hakkında fikir verir?',
    options: [
      'Yaralının kan grubu hakkında',
      'Yaralının beyin ve genel durumuyla ilgili bir değişiklik olup olmadığı hakkında',
      'Yaralının boyu hakkında',
      'Yaralının kaç yaşında olduğu hakkında',
    ],
    answerIndex: 1,
    explanation:
      'Göz bebeklerinin büyüklüğü ve ışığa verdiği tepki, beynin durumu hakkında dolaylı bilgi verir. İki göz bebeğinin eşit olmaması veya ışığa tepki vermemesi, ciddi bir sorunun (örneğin kafa/beyin etkilenmesi) işareti olabileceğinden 112’ye bildirilecek önemli bir bulgudur.',
    whyWrong: [
      'Kan grubu, boy veya yaş göz bebeği tepkisiyle anlaşılamaz.',
      'Göz bebeği değerlendirmesinin amacı, yaralının genel/nörolojik durumundaki değişimi fark etmektir.',
    ],
    objective: 'Göz bebeği kontrolünün beyin/genel durum hakkında bilgi verdiğini kavramak.',
    tags: ['gozbebegi-kontrolu', 'degerlendirme', 'beyin'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-730',
    subject: 'ilkyardim',
    topic: 'ilkyardim-oncelikleri',
    difficulty: 'kolay',
    stem: 'İlk yardımcının bir olayda uygulama önceliğiyle ilgili aşağıdakilerden hangisi doğrudur?',
    options: [
      'Önce en çok bağıran ve gürültü çıkaran yaralıyla ilgilenmek',
      'Önce yaşamı doğrudan tehdit eden durumları (solunum/dolaşım sorunu, ciddi kanama gibi) ele almak',
      'Önce yüzeysel sıyrıkları temizlemek',
      'Önce yaralının kıyafetlerini düzeltmek',
    ],
    answerIndex: 1,
    explanation:
      'İlk yardımda öncelik, yaşamı doğrudan tehdit eden sorunlardır: solunum ve dolaşımın değerlendirilmesi ile ciddi kanamaların denetim altına alınması önce gelir. Yüzeysel yaralar ve konfora yönelik işlemler bu hayati önceliklerden sonra ele alınır.',
    whyWrong: [
      'En çok bağıran yaralı her zaman en ağır durumda olmayabilir; sessiz ve bilinci kapalı yaralı daha acil olabilir.',
      'Yüzeysel sıyrık ya da kıyafet düzeltmek hayati sorunların önüne geçmez.',
    ],
    objective: 'İlk yardımda hayati tehlikelerin önceliğini kavramak.',
    tags: ['ilkyardim-oncelikleri', 'yasamsal-tehlike', 'siralama'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
];
