/**
 * ÖZGÜN araç tekniği (motor) soruları — 7. genişletme (Program 2 · Faz 9). ROADMAP C.4/E.6.
 * Kaynak = MEB araç tekniği müfredatı; KENDİ İFADEMİZLE.
 * Odak: temel sistem özetleri + gösterge okuma.
 */
import type { QuestionInput } from '@ea/content-schema';

const SRC = 'MEB araç tekniği müfredatı (özgün ifade)';

export const MOTOR_QUESTIONS_7: QuestionInput[] = [
  {
    id: 'motor-701',
    subject: 'motor',
    topic: 'motor-tanimi',
    difficulty: 'orta',
    stem: 'Bir içten yanmalı motor, aracı hareket ettirmek için temelde hangi enerji dönüşümünü gerçekleştirir?',
    options: [
      'Elektrik enerjisini doğrudan sese çevirir',
      'Havayı sıkıştırarak yalnızca ısı üretir, hareket üretmez',
      'Yakıttaki kimyasal enerjiyi yanmayla ısıya, ısıyı da parçaların hareketiyle mekanik (hareket) enerjisine dönüştürür',
      'Suyun buharını elektriğe çevirip aküyü doldurur',
    ],
    answerIndex: 2,
    explanation:
      'Motorun görevi, yakıtın içinde depolanmış kimyasal enerjiyi kullanılabilir harekete çevirmektir. Silindir içinde yanan yakıt yüksek ısı ve basınç oluşturur; bu basınç pistonu iter, pistonun doğrusal hareketi krank mili aracılığıyla dönme hareketine çevrilir ve sonunda tekerleklere iletilir. Yani sıralama kimyasal → ısı → mekanik enerji biçimindedir.',
    whyWrong: [
      'Motor sesi üretebilir ama amacı bu değildir; enerjiyi harekete çevirir.',
      'Havanın sıkıştırılması sürecin bir parçasıdır; tek başına aracı yürüten şey değildir. Elektrik üretimi ise alternatörün işidir, motorun asıl amacı değil.',
    ],
    objective: 'Motorun kimyasal→ısı→mekanik enerji dönüşümü yaptığını kavramak.',
    tags: ['motor-tanimi', 'enerji-donusumu', 'temel-kavram'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-702',
    subject: 'motor',
    topic: 'benzinli-dizel-ozet',
    difficulty: 'orta',
    stem: 'Benzinli ve dizel motorları birbirinden ayıran temel çalışma farkı, özet olarak aşağıdakilerden hangisidir?',
    options: [
      'Benzinlide karışım bujinin kıvılcımıyla ateşlenir; dizelde ise yakıt, yüksek oranda sıkıştırılıp ısınan havada kendiliğinden tutuşar (bu yüzden dizelin sıkıştırma oranı daha yüksektir)',
      'Benzinli motor elektrikle, dizel motor yakıtla çalışır',
      'Dizel motorda yanma olmaz, yalnızca havanın sıkışması aracı yürütür',
      'İkisi de aynı biçimde bujiyle ateşlenir, aralarında çalışma farkı yoktur',
    ],
    answerIndex: 0,
    explanation:
      'Her iki motor da içten yanmalıdır, ancak yakıtı tutuşturma biçimleri farklıdır. Benzinlide hava-yakıt karışımı sıkıştırılır ve bujinin kıvılcımıyla ateşlenir. Dizelde yalnızca hava çok yüksek oranda sıkıştırılıp ısıtılır; bu sıcak havanın içine mazot püskürtüldüğünde yakıt kendiliğinden tutuşar. Yüksek sıkıştırma gerektiği için dizel motorların sıkıştırma oranı benzinliye göre daha yüksektir ve dizelde buji bulunmaz.',
    whyWrong: [
      'İkisi de yakıtla çalışan içten yanmalı motordur; benzinli elektrikle çalışmaz.',
      'Dizelde de yanma vardır; sıkışan havanın ısısı yakıtı tutuşturur. Ateşleme biçimleri aynı değildir, aralarındaki temel fark budur.',
    ],
    objective:
      'Benzinli-dizel farkını (buji ateşlemesi / sıkıştırmayla kendiliğinden tutuşma) özetlemek.',
    tags: ['benzinli-dizel', 'sikistirma', 'atesleme-farki'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-703',
    subject: 'motor',
    topic: 'iki-dort-zaman',
    difficulty: 'zor',
    stem: 'İki zamanlı ve dört zamanlı motorlar arasındaki temel fark aşağıdakilerden hangisidir?',
    options: [
      'İki zamanlı motorlarda yakıt kullanılmaz, dört zamanlıda kullanılır',
      'İki zamanlı motorlar yalnızca dizel, dört zamanlılar yalnızca benzinli olur',
      'İki zamanlı motorda soğutma yoktur, dört zamanlıda vardır',
      'Dört zamanlı motorda çevrim (emme-sıkıştırma-ateşleme/güç-egzoz) krank milinin iki turunda tamamlanır; iki zamanlıda ise aynı işler krank milinin bir turunda (iki strokta) tamamlanır',
    ],
    answerIndex: 3,
    explanation:
      'Fark, bir iş çevriminin kaç piston hareketinde tamamlandığıyla ilgilidir. Dört zamanlı motorda emme, sıkıştırma, ateşleme (güç) ve egzoz ayrı stroklar hâlinde gerçekleşir; çevrim krank milinin iki tam dönüşünde tamamlanır. İki zamanlı motorda bu işler birleştirilerek çevrim krank milinin bir tam dönüşünde (iki strokta) tamamlanır; bu yüzden her devirde bir güç darbesi alınır.',
    whyWrong: [
      'İki türde de yakıt kullanılır; fark çevrim sayısındadır.',
      'İki/dört zamanlı olmak yakıt cinsini (benzin/dizel) belirlemez ve iki zamanlı motorların da soğutması vardır.',
    ],
    objective: 'İki ve dört zamanlı motorların çevrim tamamlama farkını ayırt etmek.',
    tags: ['calisma-zamanlari', 'iki-zamanli', 'dort-zamanli'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-704',
    subject: 'motor',
    topic: 'sogutma-bilesenleri',
    difficulty: 'kolay',
    stem: 'Aşağıdakilerden hangisi motorun soğutma sisteminin bir bileşeni DEĞİLDİR?',
    options: ['Radyatör', 'Termostat', 'Devirdaim (su) pompası', 'Buji'],
    answerIndex: 3,
    explanation:
      'Soğutma sistemi; ısıyı havaya veren radyatör, suyun sıcaklığına göre dolaşımı açıp kapayan termostat, suyu devrede dolaştıran devirdaim (su) pompası ve gerektiğinde radyatöre hava çeken fandan oluşur. Buji ise soğutma sistemine değil, benzinli motorun ateşleme sistemine ait bir parçadır.',
    whyWrong: [
      'Radyatör, termostat ve su pompası doğrudan soğutma sisteminin temel parçalarıdır.',
      'Buji, hava-yakıt karışımını tutuşturan ateşleme elemanıdır; soğutmayla ilgisi yoktur.',
    ],
    objective:
      'Soğutma sistemi bileşenlerini (radyatör-termostat-pompa-fan) tanıyıp ateşleme parçasından ayırmak.',
    tags: ['sogutma-sistemi', 'bilesenler', 'radyator'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-705',
    subject: 'motor',
    topic: 'yaglama-ozet',
    difficulty: 'kolay',
    stem: 'Yağ karteri, yağ pompası ve yağ filtresi bir araya gelerek aracın hangi sistemini oluşturur ve bu sistemin temel amacı nedir?',
    options: [
      'Soğutma sistemini; motoru soğutmak',
      'Yağlama sistemini; hareketli parçalar arasında yağ filmi oluşturup sürtünmeyi ve aşınmayı azaltmak',
      'Yakıt sistemini; motora yakıt taşımak',
      'Şarj sistemini; aküyü doldurmak',
    ],
    answerIndex: 1,
    explanation:
      'Yağ karterinde biriken motor yağı, yağ pompasıyla basınçlandırılıp yağ filtresinden geçirilerek temizlenir ve hareketli parçalara gönderilir. Bu parçaların oluşturduğu yağlama sisteminin görevi, metal yüzeyler arasında ince bir yağ filmi oluşturarak sürtünmeyi, aşınmayı ve ısınmayı azaltmaktır; ayrıca kısmen soğutma ve temizleme de sağlar.',
    whyWrong: [
      'Soğutma sistemi su-radyatör-termostatla çalışır; yağ pompası ve karter ona ait değildir.',
      'Yakıt taşıma yakıt sisteminin, akü şarjı ise şarj sisteminin (alternatörün) işidir.',
    ],
    objective: 'Yağlama sistemi bileşenlerini ve sürtünme-aşınma azaltma amacını özetlemek.',
    tags: ['yaglama-sistemi', 'yag-pompasi', 'surtunme'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-706',
    subject: 'motor',
    topic: 'yakit-sistemi-ozet',
    difficulty: 'kolay',
    stem: 'Yakıt deposu, yakıt pompası, yakıt filtresi ve enjektörlerden oluşan yakıt sisteminin temel görevi aşağıdakilerden hangisidir?',
    options: [
      'Temizlenmiş yakıtı depodan alıp uygun basınç ve miktarda motora (yanma odasına) iletmek',
      'Egzoz gazlarını süzüp dışarı atmak',
      'Aküyü şarj edip elektrik üretmek',
      'Motoru istenen sıcaklıkta tutmak',
    ],
    answerIndex: 0,
    explanation:
      'Yakıt sistemi, depodaki yakıtı motora düzenli biçimde ulaştırır. Yakıt pompası yakıtı depodan çeker, filtre içindeki tortu ve suyu tutarak yakıtı temizler, enjektörler ise yakıtı doğru zamanda ve miktarda yanma odasına püskürtür. Böylece motor her çalışma koşulunda ihtiyaç duyduğu yakıtı alır.',
    whyWrong: [
      'Egzoz gazlarını yönlendirip azaltmak egzoz sisteminin işidir.',
      'Elektrik üretimi şarj sisteminin, sıcaklık dengesi ise soğutma sisteminin görevidir.',
    ],
    objective: 'Yakıt sistemi bileşenlerinin yakıtı temizleyip motora iletme işlevini özetlemek.',
    tags: ['yakit-sistemi', 'enjektor', 'yakit-pompasi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-707',
    subject: 'motor',
    topic: 'atesleme-sistemi',
    difficulty: 'orta',
    stem: 'Benzinli bir motorda ateşleme sisteminin (akü-bobin-buji hattı) temel görevi nedir?',
    options: [
      'Yakıtı depodan çekip enjektörlere basmak',
      'Sıkıştırılan hava-yakıt karışımını, her silindirde tam zamanında güçlü bir kıvılcımla tutuşturmak',
      'Egzoz gazındaki zararlı maddeleri temizlemek',
      'Motor yağını basınçlandırıp parçalara dağıtmak',
    ],
    answerIndex: 1,
    explanation:
      'Benzinli motorlarda yanmanın başlaması için bir kıvılcıma ihtiyaç vardır. Ateşleme sistemi, akünün düşük gerilimini bobinle çok yüksek gerilime çıkarır ve bujiye iletir; buji, sıkıştırılmış karışımın içinde kıvılcım atlatarak yanmayı başlatır. Bu kıvılcımın doğru silindirde ve tam doğru anda oluşması, motorun düzgün ve verimli çalışması için önemlidir.',
    whyWrong: [
      'Yakıtı basınçlandırıp püskürtmek yakıt sisteminin (pompa ve enjektör) işidir.',
      'Egzoz temizliği katalizörün, yağ dağıtımı ise yağlama sisteminin görevidir.',
    ],
    objective:
      'Benzinli motorda ateşleme sisteminin karışımı zamanında tutuşturma görevini kavramak.',
    tags: ['atesleme-sistemi', 'buji', 'kivilcim'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-708',
    subject: 'motor',
    topic: 'mars-sistemi-ozet',
    difficulty: 'kolay',
    stem: 'Motoru ilk hareketle döndürüp çalışmaya başlatan marş sistemini oluşturan iki temel eleman hangisidir?',
    options: [
      'Radyatör ve termostat',
      'Enjektör ve yakıt filtresi',
      'Akü ve marş motoru',
      'Alternatör ve triger kayışı',
    ],
    answerIndex: 2,
    explanation:
      'Marş sistemi, duran motoru ilk kez döndürmek için gereken gücü sağlar. Kontak çevrildiğinde akü, depoladığı elektriği marş motoruna verir; marş motoru da bir dişli aracılığıyla motoru döndürür. Motor kendi başına çalışmaya başlayınca marş motoru devreden çıkar. Yani marş sisteminin kalbi akü ile marş motorudur.',
    whyWrong: [
      'Radyatör-termostat soğutma, enjektör-filtre ise yakıt sistemine aittir; motoru döndürmezler.',
      'Alternatör motor çalışırken şarj üretir, triger kayışı zamanlama sağlar; ilk çevirme işini yapmazlar.',
    ],
    objective: 'Marş sisteminin akü ve marş motorundan oluştuğunu bilmek.',
    tags: ['mars-sistemi', 'aku', 'mars-motoru'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-709',
    subject: 'motor',
    topic: 'sarj-sistemi-ozet',
    difficulty: 'orta',
    stem: 'Motor çalışır durumdayken aracın elektrikli donanımlarını besleyen ve aküyü dolduran enerjiyi asıl olarak hangi eleman üretir?',
    options: [
      'Akü, çünkü elektriği sürekli kendisi üretir',
      'Marş motoru, çünkü motor döndükçe elektrik üretir',
      'Termostat, çünkü sıcaklığı elektriğe çevirir',
      'Alternatör; motorun döndürdüğü bu eleman elektrik üretir, hem donanımları besler hem aküyü şarj eder',
    ],
    answerIndex: 3,
    explanation:
      'Aküyü bir enerji deposu olarak düşünmek gerekir; elektriği depolar ama sürekli üretmez. Motor çalışırken elektriği üreten eleman alternatördür. Alternatör, motorun kayışla döndürdüğü bir jeneratör gibi çalışıp elektrik üretir; bu enerjiyle far, kalorifer, müzik sistemi gibi tüketicileri besler ve aynı zamanda aküyü doldurur. Bu görev bölüşümü sayesinde akü sürüş sırasında boşalmaz.',
    whyWrong: [
      'Akü elektriği depolar, sürekli üretmez; sürekli aküye yüklenmek onu bitirir.',
      'Marş motoru elektrik tüketerek motoru döndürür, üretmez; termostatın elektrikle ilgisi yoktur.',
    ],
    objective: 'Şarj sisteminde üretimin alternatöre, depolamanın aküye ait olduğunu ayırt etmek.',
    tags: ['sarj-sistemi', 'alternator', 'aku'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-710',
    subject: 'motor',
    topic: 'aktarma-ozet',
    difficulty: 'zor',
    stem: 'Önden motorlu, arkadan itişli bir araçta motor gücünün tekerleklere iletildiği aktarma organları hangi sırayla dizilir?',
    options: [
      'Diferansiyel → şaft → şanzıman → debriyaj',
      'Debriyaj → şanzıman → şaft → diferansiyel → tekerlekler',
      'Şanzıman → debriyaj → diferansiyel → şaft',
      'Alternatör → marş motoru → şaft → tekerlekler',
    ],
    answerIndex: 1,
    explanation:
      'Güç önce debriyajdan geçer; debriyaj motorun hareketini şanzımana bağlar ya da keser. Şanzıman uygun vites oranını seçer, şaft (kardan mili) bu hareketi arka aksa taşır, diferansiyel ise gücü iki tekerleğe pay eder ve virajda tekerleklerin farklı hızlarda dönmesine izin verir. Böylece hareket sırayla debriyaj → şanzıman → şaft → diferansiyel → tekerlekler yolunu izler.',
    whyWrong: [
      'Sıralamanın tersten yazılması güç akış yönüne aykırıdır; güç motordan tekerleğe doğru gider.',
      'Debriyaj her zaman şanzımandan önce gelir; alternatör ve marş motoru ise güç aktarma organı değildir.',
    ],
    objective: 'Aktarma organlarının motordan tekerleğe doğru sıralanışını kavramak.',
    tags: ['aktarma-organlari', 'debriyaj', 'diferansiyel'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-711',
    subject: 'motor',
    topic: 'fren-sistemi-ozet',
    difficulty: 'kolay',
    stem: 'Aracın servis (ayak) fren sisteminin temel görevi aşağıdakilerden hangisidir?',
    options: [
      'Sürücünün pedala uyguladığı kuvveti tekerleklere ileterek aracı yavaşlatmak ve durdurmak',
      'Motorun devrini yükseltmek',
      'Aracın farlarını yakmak',
      'Yakıt tüketimini otomatik ayarlamak',
    ],
    answerIndex: 0,
    explanation:
      'Fren sistemi, sürücünün fren pedalına uyguladığı kuvveti hidrolik yağ aracılığıyla tekerleklerdeki fren mekanizmasına (disk-balata veya kampana-pabuç) iletir. Oluşan sürtünme, tekerleklerin dönüşünü yavaşlatır ve aracı durdurur. Böylece hareket enerjisi sürtünmeyle ısıya dönüşerek harcanmış olur.',
    whyWrong: [
      'Motor devrini gaz sistemi belirler; fren tam tersine aracı yavaşlatır.',
      'Far yakmak elektrik sisteminin, yakıt ayarı ise yakıt sisteminin işidir; frenle ilgisi yoktur.',
    ],
    objective: 'Fren sisteminin pedal kuvvetini sürtünmeyle yavaşlamaya çevirdiğini kavramak.',
    tags: ['fren-sistemi', 'yavaslama', 'surtunme'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-712',
    subject: 'motor',
    topic: 'direksiyon-ozet',
    difficulty: 'zor',
    stem: 'Hidrolik direksiyon ile elektrikli direksiyon (EPS) sisteminin sürücüye direksiyonu çevirmede yardımcı olma biçimi arasındaki fark nedir?',
    options: [
      'İkisi de yalnızca kas gücüyle çalışır, hiçbir destek sağlamaz',
      'Hidrolik direksiyon motorla dönen bir pompanın oluşturduğu yağ basıncıyla destek verir; elektrikli direksiyon ise bir elektrik motoruyla destek sağlar (pompa ve hidrolik yağ gerektirmez)',
      'Elektrikli direksiyon aracı frenler, hidrolik direksiyon farları yakar',
      'Hidrolik direksiyon yalnızca yüksek hızda, elektrikli direksiyon yalnızca dururken çalışır',
    ],
    answerIndex: 1,
    explanation:
      'Her iki sistem de tekerlekleri çevirmek için gereken kuvveti azaltarak direksiyonu hafifletir, ama yardımı farklı yolla üretirler. Hidrolik direksiyonda motorun döndürdüğü bir pompa hidrolik yağı basınçlandırır ve bu basınç direksiyona destek verir. Elektrikli direksiyonda (EPS) ise bu işi bir elektrik motoru yapar; ayrı bir pompaya ve hidrolik yağa ihtiyaç duymadığı için bakımı daha azdır ve gücü elektronik olarak ayarlanabilir.',
    whyWrong: [
      'İkisi de sürücüye kuvvet desteği sağlar; sistemler tam kas gücüyle çalışmaz.',
      'Frenleme ve aydınlatma direksiyon sisteminin işi değildir; her iki destek de hem park hem seyir sırasında çalışır.',
    ],
    objective: 'Hidrolik ve elektrikli direksiyonun destek üretme biçimindeki farkı ayırt etmek.',
    tags: ['direksiyon-sistemi', 'hidrolik', 'elektrikli-direksiyon'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-713',
    subject: 'motor',
    topic: 'suspansiyon-ozet',
    difficulty: 'kolay',
    stem: 'Yay ve amortisörlerden oluşan süspansiyon sisteminin araçtaki temel görevi aşağıdakilerden hangisidir?',
    options: [
      'Motorun yakıtını süzmek',
      'Aracın hızını sınırlamak',
      'Egzoz gazını temizlemek',
      'Yoldan gelen darbeleri yumuşatmak, tekerleklerin yola temasını sürdürmek ve böylece hem sürüş konforunu hem yol tutuşunu sağlamak',
    ],
    answerIndex: 3,
    explanation:
      'Süspansiyon, tekerlekler ile araç gövdesi arasında bir tampon görevi görür. Yaylar yoldaki tümsek ve çukurlardan gelen darbeleri emerek gövdeye iletilen sarsıntıyı azaltır; amortisörler ise yayın oluşturduğu salınımı sönümleyerek tekerleğin yerden kesilmesini önler. Böylece hem yolcular sarsılmadan gider hem de tekerlekler yola basmaya devam ederek yol tutuşu ve frenleme güvenli kalır.',
    whyWrong: [
      'Yakıt süzme yakıt filtresinin, egzoz temizliği katalizörün işidir.',
      'Süspansiyonun hızı sınırlama gibi bir görevi yoktur; amacı konfor ve yol tutuşudur.',
    ],
    objective: 'Süspansiyonun darbe yumuşatma ve yol tutuşunu koruma görevini kavramak.',
    tags: ['suspansiyon', 'amortisor', 'yol-tutusu'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-714',
    subject: 'motor',
    topic: 'gosterge-renk-yesil',
    difficulty: 'kolay',
    stem: 'Gösterge panelinde YEŞİL (ya da mavi) renkli bir sembolün (örneğin yanıp sönen sinyal oku ya da yanan kısa far işareti) yanması genellikle neyi anlatır?',
    options: [
      'Bir donanımın o an çalışır/aktif olduğunu bildiren bilgi ışığıdır; bir arıza uyarısı değildir',
      'Her zaman ciddi bir arıza olduğunu ve derhâl durulması gerektiğini',
      'Motorun aşırı ısındığını',
      'Frenlerin tamamen boşaldığını',
    ],
    answerIndex: 0,
    explanation:
      'Gösterge panelinde renkler bir öncelik dili gibidir. Kırmızı çoğunlukla acil bir durumu ve durmayı gerektiren uyarıyı, sarı/turuncu dikkat edilmesi gereken bir uyarıyı, yeşil ve mavi ise yalnızca bir sistemin o an devrede/aktif olduğunu gösteren bilgi ışıklarını ifade eder. Örneğin yanan yeşil sinyal oku sinyalin çalıştığını, mavi far işareti uzun farların açık olduğunu bildirir; bunlar arıza değildir.',
    whyWrong: [
      'Yeşil/mavi ışıklar acil durum ya da arıza uyarısı değil, bilgi ışığıdır.',
      'Aşırı ısınma ve fren boşalması gibi ciddi durumlar kırmızı uyarılarla bildirilir, yeşil bilgi ışığıyla değil.',
    ],
    objective: 'Yeşil/mavi ikaz ışıklarının arıza değil bilgi anlamı taşıdığını kavramak.',
    tags: ['gosterge-paneli', 'ikaz-renkleri', 'bilgi-lambasi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-715',
    subject: 'motor',
    topic: 'yakit-gostergesi-ok',
    difficulty: 'kolay',
    stem: 'Birçok aracın yakıt göstergesindeki pompa sembolünün yanında küçük bir ok bulunur. Bu okun pratik işlevi nedir?',
    options: [
      'Aracın yakıt dolum kapağının (deponun) aracın hangi tarafında olduğunu gösterir; istasyonda hangi yöne yanaşılacağını anlamayı kolaylaştırır',
      'Motor yağının seviyesini gösterir',
      'Aracın gittiği yönü (kuzey-güney) gösteren pusuladır',
      'Lastik hava basıncının düştüğünü bildirir',
    ],
    answerIndex: 0,
    explanation:
      'Yakıt göstergesindeki pompa simgesinin yanındaki küçük ok (veya pompa hortumunun çizildiği taraf), yakıt dolum kapağının aracın sağ mı sol tarafında olduğunu gösterir. Özellikle yabancı olduğunuz bir araçla istasyona girerken hangi yöne yanaşmanız gerektiğini bu okla kolayca anlayabilirsiniz. Yakıt seviyesini ise ibrenin E (boş) ile F (dolu) arasındaki konumu gösterir.',
    whyWrong: [
      'Yağ seviyesi yağ çubuğuyla veya ayrı bir göstergeyle takip edilir; bu okla değil.',
      'Ok bir pusula değildir ve lastik basıncını da bildirmez; yalnızca depo kapağının yönünü gösterir.',
    ],
    objective: 'Yakıt göstergesindeki okun depo kapağı yönünü gösterdiğini bilmek.',
    tags: ['yakit-gostergesi', 'depo-kapagi', 'gosterge-okuma'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-716',
    subject: 'motor',
    topic: 'hiz-devir-iliskisi',
    difficulty: 'orta',
    stem: 'Araç aynı hızda giderken alt vitesten üst vitese geçildiğinde devir göstergesindeki (takometre) motor devri (rpm) genellikle nasıl değişir?',
    options: [
      'Devir yükselir, çünkü üst viteste motor daha hızlı döner',
      'Devir düşer, çünkü aynı hızı daha büyük bir vites oranıyla sağlamak motorun daha yavaş dönmesini sağlar',
      'Devir hiç değişmez, vitesin devirle ilgisi yoktur',
      'Devir sıfırlanır ve motor durur',
    ],
    answerIndex: 1,
    explanation:
      'Aynı araç hızını farklı vitesle sağlamak mümkündür. Üst vitese geçildiğinde dişli oranı değişir ve motor, aynı hızı korumak için daha düşük bir devirde döner; takometre ibresi aşağı iner. Bu, hem yakıt tüketimini düşürür hem de motorun daha sessiz ve rahat çalışmasını sağlar. Tersine alt vitese inildiğinde aynı hızda devir yükselir.',
    whyWrong: [
      'Üst viteste motor aynı hız için daha hızlı değil, daha yavaş döner; devir düşer.',
      'Vites ile devir doğrudan ilişkilidir; ayrıca vites değiştirmek motoru durdurmaz.',
    ],
    objective: 'Hız sabitken üst vitese geçişte devrin düştüğü ilişkisini kavramak.',
    tags: ['takometre', 'devir', 'vites'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-717',
    subject: 'motor',
    topic: 'kilometre-sayaci',
    difficulty: 'orta',
    stem: 'Gösterge panelindeki toplam kilometre sayacı (kilometre saati/odometre) ile sıfırlanabilen yol sayacı (trip) arasındaki fark nedir?',
    options: [
      'İkisi de aynı bilgiyi gösterir, aralarında hiçbir fark yoktur',
      'Toplam sayaç yalnızca hızı, trip sayaç yalnızca yakıtı gösterir',
      'Toplam sayaç aracın kullanım ömrü boyunca yaptığı toplam mesafeyi (sıfırlanamaz) gösterir; trip sayaç ise sürücünün istediğinde sıfırlayabildiği, örneğin bir yolculuğun mesafesini ölçen bölümdür',
      'Trip sayaç aracın toplam yaşını yıl olarak gösterir',
    ],
    answerIndex: 2,
    explanation:
      'Toplam kilometre sayacı, aracın fabrikadan çıktığından beri katettiği tüm mesafeyi gösterir ve normalde sıfırlanamaz; bu değer aracın yaşını, değerini ve periyodik bakım zamanını takip etmede kullanılır. Trip (yol) sayacı ise sürücünün dilediğinde sıfırlayabildiği bir sayaçtır; iki dolum arası mesafeyi veya belli bir yolculuğun uzunluğunu ölçmeye yarar. Bakım takibinde asıl ölçüt toplam kilometredir.',
    whyWrong: [
      'İki sayaç farklı amaçlıdır; biri toplam mesafeyi, diğeri sıfırlanabilir kısmi mesafeyi gösterir.',
      'Hız ayrı bir göstergeyle okunur; trip sayaç aracın yaşını yıl olarak vermez, mesafe ölçer.',
    ],
    objective:
      'Toplam kilometre sayacı ile sıfırlanabilir trip sayacın farkını ve bakım takibindeki rolünü bilmek.',
    tags: ['kilometre-sayaci', 'odometre', 'bakim-takibi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-718',
    subject: 'motor',
    topic: 'buzlanma-uyarisi',
    difficulty: 'orta',
    stem: 'Aracın dış sıcaklık göstergesi düşük bir değer (örneğin +3°C ve altı) gösterip ekranda kar tanesi/buzlanma sembolü belirdiğinde bu sürücüye ne anlatır?',
    options: [
      'Motorun aşırı ısındığını ve hemen durulması gerektiğini',
      'Yol yüzeyinde buzlanma riski oluşabileceğini; sürücünün hızını azaltıp takip mesafesini artırarak dikkatli sürmesi gerektiğini',
      'Klimanın arızalandığını',
      'Yakıtın bittiğini',
    ],
    answerIndex: 1,
    explanation:
      'Birçok araç dış hava sıcaklığını gösterir ve sıcaklık donma noktasına yaklaştığında (genellikle +3°C ile 0°C civarı) bir buzlanma/kar tanesi uyarısı verir. Bu uyarı, özellikle köprü, viyadük ve gölgeli kesimlerde yolun buzlanmış olabileceğini hatırlatır. Sürücü bu durumda hızını düşürmeli, ani direksiyon ve fren hareketlerinden kaçınmalı ve takip mesafesini artırmalıdır. Uyarı bir zorunluluk değil, dikkat çağrısıdır.',
    whyWrong: [
      'Motor sıcaklığı ayrı bir göstergeyle izlenir; bu uyarı dış hava ve yol koşuluyla ilgilidir.',
      'Sembol klima arızasını ya da yakıt bitişini değil, olası buzlanmayı bildirir.',
    ],
    objective: 'Dış sıcaklık/buzlanma uyarısını yol güvenliği açısından doğru yorumlamak.',
    tags: ['dis-sicaklik', 'buzlanma', 'kis-surus'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-719',
    subject: 'motor',
    topic: 'yakit-etiketi',
    difficulty: 'kolay',
    stem: 'Birçok aracın yakıt dolum kapağının iç yüzünde veya çevresinde "Kurşunsuz 95" ya da "Diesel" gibi bir yakıt cinsi etiketi/yazısı bulunur. Bu etiketin amacı nedir?',
    options: [
      'Araca konulması gereken doğru yakıt cinsini belirtip yanlış yakıt konmasını önlemek',
      'Deponun kaç litre olduğunu göstermek',
      'Lastik hava basıncını bildirmek',
      'Aracın azami hızını yazmak',
    ],
    answerIndex: 0,
    explanation:
      'Depo kapağının yanındaki yakıt cinsi etiketi, o araca hangi yakıtın konulacağını açıkça belirtir. Benzinli bir araca yanlışlıkla motorin, dizel bir araca benzin konması yakıt sistemine ve motora ciddi zarar verebileceği için bu etiket önemli bir uyarıdır. Özellikle başkasının aracına yakıt alırken ve istasyonda görevliyi yönlendirirken bu bilgiye bakmak, pahalı hataları önler.',
    whyWrong: [
      'Depo hacmi (litre) ve azami hız aracın el kitabında veya başka etiketlerde bulunur.',
      'Lastik hava basıncı ayrı bir etikette (genellikle kapı eşiğinde) belirtilir; yakıt etiketiyle karıştırılmamalıdır.',
    ],
    objective: 'Yakıt cinsi etiketinin doğru yakıt seçimi ve yanlış yakıtı önleme işlevini bilmek.',
    tags: ['yakit-cinsi', 'etiket', 'yanlis-yakit'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-720',
    subject: 'motor',
    topic: 'lastik-basinc-etiketi',
    difficulty: 'orta',
    stem: 'Bir araç için üreticinin önerdiği doğru lastik hava basıncı değerleri genellikle nerede yazılıdır?',
    options: [
      'Yalnızca lastiğin yan yüzeyinde, "205/55 R16" ifadesinin içinde',
      'Motor yağı kapağının üstünde',
      'Sürücü kapısının eşiğinde/orta direkte bulunan etikette, yakıt kapağının içinde ya da aracın kullanım (el) kitabında',
      'Ön camın üst köşesinde',
    ],
    answerIndex: 2,
    explanation:
      'Aracın önerilen lastik basınçları, o modele göre üretici tarafından belirlenir ve genellikle sürücü kapısının açıldığı eşikte/orta direkte yer alan bir etikette, kimi araçlarda yakıt kapağının içinde ya da kullanım kitabında yazar. Bu etiket, boş ve yüklü kullanım için ayrı değerler de verebilir. Lastiğin yanağındaki "205/55 R16" ifadesi ise lastiğin ölçüsünü belirtir, önerilen basıncı değil.',
    whyWrong: [
      'Lastik yanağındaki ölçü yazısı önerilen basıncı vermez; o yalnızca lastiğin boyutlarını gösterir.',
      'Yağ kapağı ve ön cam köşesi lastik basıncı bilgisi taşımaz; basınç etiketi araca özgü ayrı bir etikettir.',
    ],
    objective:
      'Önerilen lastik basıncı etiketinin yerini (kapı eşiği/yakıt kapağı/el kitabı) bilmek.',
    tags: ['lastik-basinci', 'etiket', 'uretici-degeri'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-721',
    subject: 'motor',
    topic: 'sicaklik-gostergesi',
    difficulty: 'orta',
    stem: 'Motor sıcaklık (hararet) göstergesinde "C" ve "H" harfleri ile ibrenin normal konumu neyi ifade eder?',
    options: [
      'C yakıtı, H havayı gösterir; ibre ortadayken depo yarı doludur',
      'C soğuk (cold), H sıcak/hararet (hot) ucudur; motor çalışma sıcaklığına gelince ibre genellikle ortalarda durur, H tarafına dayanması aşırı ısınmayı (hararet) gösterir',
      'C ve H frenlerin durumunu gösterir',
      'İbre daima H tarafında durmalı, orta konum arıza demektir',
    ],
    answerIndex: 1,
    explanation:
      'Sıcaklık göstergesinde "C" (cold) soğuk ucu, "H" (hot) sıcak ucu belirtir. Motor ilk çalıştığında ibre soğuk taraftadır; motor çalışma sıcaklığına ulaştıkça yükselip ortalarda dengelenir ve normalde orada kalır. İbrenin sürekli H tarafına doğru tırmanması ya da uyarı bölgesine girmesi motorun aşırı ısındığını (hararet) gösterir; bu durumda araç güvenli bir yerde durdurulup motor soğutulmalıdır.',
    whyWrong: [
      'C ve H sıcaklık uçlarıdır; yakıt, hava ya da fren durumunu göstermez.',
      'Normal durum ibrenin ortalarda olmasıdır; sürekli H tarafına dayanması sağlıklı değil, tersine hararet işaretidir.',
    ],
    objective: 'Sıcaklık göstergesinde C/H uçlarını ve normal orta konumu okuyabilmek.',
    tags: ['sicaklik-gostergesi', 'hararet', 'gosterge-okuma'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-722',
    subject: 'motor',
    topic: 'takometre-kirmizi',
    difficulty: 'zor',
    stem: 'Devir göstergesinde (takometre) yüksek devirlerde başlayan kırmızı bölge (redline) neyi ifade eder?',
    options: [
      'Motorun ısındığı sıcaklık bölgesini',
      'Motorun güvenle çıkabileceği en yüksek devir sınırını; bu bölgeye girmek ve orada sürekli kullanmak motora aşırı yük bindirip zarar verebilir',
      'Yakıtın bittiği bölgeyi',
      'En verimli ve tasarruflu sürüş bölgesini',
    ],
    answerIndex: 1,
    explanation:
      'Takometre, motorun dakikadaki devir sayısını (rpm) gösterir. Yüksek devirlerde başlayan kırmızı bölge, üreticinin belirlediği güvenli üst devir sınırını işaret eder. Motoru bu bölgeye zorlamak ve orada tutmak, parçalara aşırı yük bindirerek yıpranmayı ve hasar riskini artırır. Verimli ve motoru koruyan sürüş, devri bu kırmızı bölgeye sokmadan, orta devir aralığında zamanında vites değiştirerek yapılır.',
    whyWrong: [
      'Kırmızı bölge sıcaklık ya da yakıt seviyesiyle ilgili değildir; onların ayrı göstergeleri vardır.',
      'Kırmızı bölge verimli sürüş değil, tersine kaçınılması gereken en yüksek devir alanıdır.',
    ],
    objective: 'Takometredeki kırmızı bölgenin güvenli üst devir sınırı anlamını kavramak.',
    tags: ['takometre', 'kirmizi-bolge', 'devir-siniri'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-723',
    subject: 'motor',
    topic: 'vites-gostergesi',
    difficulty: 'kolay',
    stem: 'Otomatik vitesli bir araçta vites selektöründeki/göstergesindeki "P - R - N - D" harfleri sırasıyla neyi ifade eder?',
    options: [
      'Park - Geri (Reverse) - Boş (Neutral) - İleri Sürüş (Drive)',
      'Pompa - Radyatör - Motor - Debriyaj',
      'Benzin - Rölanti - Nötr - Dizel',
      'Park - Rölanti - Normal - Direksiyon',
    ],
    answerIndex: 0,
    explanation:
      'Otomatik şanzımanda konumlar İngilizce sözcüklerin baş harfleriyle gösterilir: P (Park) aracı park konumunda kilitler, R (Reverse) geri vitestir, N (Neutral) boş konumdur (güç aktarılmaz), D (Drive) ise normal ileri sürüş konumudur. Sürücü ileri gitmek için D, geri gitmek için R, park etmek için ise araç tam dururken P konumunu seçer.',
    whyWrong: [
      'Harfler soğutma, yakıt ya da motor parçalarını değil, vites konumlarını gösterir.',
      'Benzin/dizel gibi yakıt cinsleri veya "normal/rölanti" gibi kavramlar bu harflerin karşılığı değildir.',
    ],
    objective: 'Otomatik viteste P-R-N-D konumlarının anlamını bilmek.',
    tags: ['otomatik-vites', 'vites-konumlari', 'gosterge-okuma'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-724',
    subject: 'motor',
    topic: 'kemer-ikazi',
    difficulty: 'kolay',
    stem: 'Gösterge panelinde kırmızı renkli emniyet kemeri sembolü yanıp aynı anda kısa aralıklarla uyarı sesi geliyorsa bu ne anlama gelir?',
    options: [
      'Motor yağının bittiğini',
      'Araçtaki bir yolcunun veya sürücünün emniyet kemerinin takılı olmadığını; kemerin takılması gerektiğini',
      'Lastiklerin patladığını',
      'Yakıt deposunun dolduğunu',
    ],
    answerIndex: 1,
    explanation:
      'Emniyet kemeri sembolü, sürücü ya da yolcu koltuğundaki kemerin takılı olmadığını bildiren bir uyarıdır; çoğu araçta bir de uyarı sesiyle desteklenir. Kemer takıldığında ışık ve ses söner. Emniyet kemeri, kaza anında sürücü ve yolcuları koltukta tutarak yaralanmayı büyük ölçüde azaltan temel bir güvenlik donanımıdır; bu yüzden araç hareket etmeden takılmalıdır.',
    whyWrong: [
      'Yağ seviyesi, lastik ve yakıt durumu için ayrı gösterge ve semboller vardır.',
      'Bu sembol yalnızca kemerin takılı olmadığını hatırlatır; başka bir sistemin arızasını göstermez.',
    ],
    objective: 'Kemer ikaz sembolünün emniyet kemerinin takılı olmadığı anlamını bilmek.',
    tags: ['emniyet-kemeri', 'ikaz-sembolu', 'pasif-guvenlik'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-725',
    subject: 'motor',
    topic: 'fren-ikaz-sembolu',
    difficulty: 'orta',
    stem: 'Sürüş sırasında gösterge panelinde daire içinde ünlem işareti bulunan kırmızı fren ikaz sembolü yanarsa akla gelmesi gereken olasılıklar ve doğru davranış nedir?',
    options: [
      'Yalnızca farların açık kaldığını gösterir, önemsizdir',
      'El freninin (park freni) çekili kalmış olabileceği, fren hidroliği seviyesinin düşük olabileceği ya da fren sisteminde bir sorun bulunabileceği; önce el freni kontrol edilmeli, sorun sürerse fren sistemi güvenli şekilde kontrol ettirilmelidir',
      'Motorun soğuk olduğunu ve ısınması gerektiğini',
      'Yakıtın rezerve düştüğünü',
    ],
    answerIndex: 1,
    explanation:
      'Daire içinde ünlem işareti taşıyan kırmızı fren uyarısı birden çok anlama gelebilir: en sık nedeni el freninin tam indirilmemiş olmasıdır; ayrıca fren hidroliği seviyesinin azalması ya da fren sisteminde bir arıza da bu ışığı yakabilir. Fren güvenlikle doğrudan ilgili olduğu için önce el freninin tam indiği kontrol edilmeli; ışık sönmüyorsa araç güvenli biçimde durdurulup fren sistemi kontrol ettirilmelidir.',
    whyWrong: [
      'Bu kırmızı uyarı önemsiz değildir; frenle ilgili ciddi bir durumu işaret edebilir.',
      'Motor sıcaklığı ve yakıt seviyesi için ayrı göstergeler bulunur; bu sembol frenle ilgilidir.',
    ],
    objective: 'Kırmızı fren ikaz sembolünün olası nedenlerini ve doğru tepkiyi bilmek.',
    tags: ['fren-ikaz', 'el-freni', 'fren-hidroligi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-726',
    subject: 'motor',
    topic: 'icten-yanmali-tanim',
    difficulty: 'orta',
    stem: 'Otomobil motorlarına "içten yanmalı motor" denmesinin nedeni aşağıdakilerden hangisidir?',
    options: [
      'Motorun içinde su kaynadığı için',
      'Motorun kabinin içinde bulunduğu için',
      'Yakıtın bir dış kazanda değil, doğrudan motorun içinde (silindir/yanma odasında) yakılıp gücün orada üretildiği için',
      'Motorun yalnızca kapalı garajda çalıştığı için',
    ],
    answerIndex: 2,
    explanation:
      '"İçten yanmalı" ifadesi, yakıtın nerede yandığını anlatır. Bu motorlarda yakıt, ayrı bir dış kazanda değil, doğrudan motorun içindeki silindirde (yanma odasında) yakılır; oluşan yüksek basınçlı gaz pistonu iterek gücü aynı yerde üretir. Buhar makinesi gibi yakıtın dışarıda yakıldığı sistemlere ise "dıştan yanmalı" denir. Otomobil motorları bu yüzden içten yanmalı sınıfındadır.',
    whyWrong: [
      'İsmin su kaynamasıyla, motorun kabin içinde olmasıyla ya da garajla ilgisi yoktur.',
      'Belirleyici olan yakıtın motorun içinde yanmasıdır; bu, dıştan yanmalı sistemlerden farkını ortaya koyar.',
    ],
    objective:
      'İçten yanmalı motor kavramının yakıtın motor içinde yanmasından geldiğini kavramak.',
    tags: ['icten-yanmali', 'temel-kavram', 'motor-tanimi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-727',
    subject: 'motor',
    topic: 'motor-hacmi',
    difficulty: 'zor',
    stem: 'Bir aracın tanıtımında geçen "1.6 litre motor hacmi" ifadesi teknik olarak neyi anlatır?',
    options: [
      'Silindirlerin toplam süpürme (kurs) hacmini; yani tüm pistonların bir çevrimde süpürdüğü havanın toplam hacmini',
      'Yakıt deposunun 1,6 litre olduğunu',
      'Motor yağı kapasitesinin 1,6 litre olduğunu',
      'Soğutma suyunun 1,6 litre olduğunu',
    ],
    answerIndex: 0,
    explanation:
      'Motor hacmi (silindir hacmi), tüm silindirlerdeki pistonların alt ölü noktadan üst ölü noktaya çıkarken süpürdüğü hacimlerin toplamıdır. "1.6 litre" bu toplam süpürme hacmini ifade eder ve motorun bir çevrimde ne kadar hava-yakıt karışımı işleyebileceğine dair fikir verir; genel olarak daha büyük hacim, daha fazla güç potansiyeli ve çoğu zaman daha yüksek yakıt tüketimi anlamına gelir. Bu değerin depo, yağ ya da soğutma suyu miktarıyla ilgisi yoktur.',
    whyWrong: [
      'Yakıt deposu hacmi genellikle 40-60 litre gibi çok daha büyük ve ayrı bir değerdir.',
      'Motor yağı ve soğutma suyu miktarları da ayrı teknik değerlerdir; motor hacmiyle karıştırılmamalıdır.',
    ],
    objective: 'Motor hacminin silindirlerin toplam süpürme hacmi olduğunu kavramak.',
    tags: ['motor-hacmi', 'silindir-hacmi', 'temel-kavram'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-728',
    subject: 'motor',
    topic: 'yay-amortisor-fark',
    difficulty: 'zor',
    stem: 'Süspansiyonda yay ile amortisörün görevleri farklıdır. Bu görev ayrımı hangi seçenekte doğru verilmiştir?',
    options: [
      'Yay motoru soğutur, amortisör yakıtı süzer',
      'İkisi de aynı işi yapar, aralarında görev farkı yoktur',
      'Yay yoldan gelen darbeyi esneyerek karşılar ve enerjiyi geçici depolar; amortisör ise yayın oluşturduğu zıplama/salınımı sönümleyerek aracın sürekli inip çıkmasını engeller',
      'Amortisör aracı yaylandırır, yay ise sesi keser',
    ],
    answerIndex: 2,
    explanation:
      'Yay ve amortisör süspansiyonda birbirini tamamlar ama farklı iş yapar. Yay, yoldan gelen darbeyi esneyerek karşılar; sıkışıp açılarak sarsıntının gövdeye iletilmesini yumuşatır, ancak kendi başına bırakılırsa aracı bir süre zıplatmaya devam eder. Amortisör bu zıplamayı (salınımı) sönümler; yayın hareketini yavaşlatıp söndürerek tekerleğin yola çabuk oturmasını ve aracın kararlı kalmasını sağlar. Amortisör zayıfsa araç darbe sonrası uzun süre yaylanır.',
    whyWrong: [
      'Yay ve amortisörün soğutma, yakıt süzme gibi görevleri yoktur; ikisi de süspansiyon parçasıdır.',
      'İki parça aynı işi yapmaz; biri darbeyi karşılar, diğeri salınımı sönümler. Ses kesmek de asıl görevleri değildir.',
    ],
    objective:
      'Süspansiyonda yayın darbe karşılama, amortisörün salınım sönümleme görevini ayırt etmek.',
    tags: ['suspansiyon', 'yay', 'amortisor'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-729',
    subject: 'motor',
    topic: 'direksiyon-ikaz',
    difficulty: 'orta',
    stem: 'Gösterge panelinde direksiyon simgesi biçiminde bir ikaz (genellikle sarı ya da kırmızı direksiyon işareti) yandığında bu neyi gösterebilir ve nasıl değerlendirilmelidir?',
    options: [
      'Yakıt seviyesinin azaldığını',
      'Lastik desenlerinin aşındığını',
      'Direksiyon destek (hidrolik/elektrikli direksiyon) sisteminde bir sorun olabileceğini; direksiyon ağırlaşabileceği için sistemin kontrol ettirilmesi gerektiğini',
      'Farların açık kaldığını',
    ],
    answerIndex: 2,
    explanation:
      'Direksiyon simgesi biçimindeki ikaz, direksiyon destek sisteminde (elektrikli ya da hidrolik) bir sorun algılandığını bildirir. Böyle bir arızada destek azalabilir veya kesilebilir; direksiyon özellikle düşük hızda ve manevrada belirgin şekilde ağırlaşır. Araç yine yönlendirilebilir ama kontrol zorlaşacağı için sistem en kısa sürede kontrol ettirilmelidir. Renk ne kadar acil olduğuna dair ipucu verir; kırmızı daha ivedi bir uyarıdır.',
    whyWrong: [
      'Yakıt seviyesi, lastik aşınması ve farlar için ayrı gösterge ve semboller vardır.',
      'Bu sembol doğrudan direksiyon destek sistemiyle ilgilidir; diğer sistemlerin uyarısı değildir.',
    ],
    objective: 'Direksiyon ikaz sembolünü destek sistemi arızası olarak yorumlamak.',
    tags: ['direksiyon-ikaz', 'direksiyon-destegi', 'gosterge-okuma'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-730',
    subject: 'motor',
    topic: 'gosterge-oncontrol',
    difficulty: 'orta',
    stem: 'Kontak açıldığında gösterge panelindeki birçok ikaz lambasının hep birlikte yanıp, motor çalıştıktan kısa süre sonra sönmesi neyi anlatır?',
    options: [
      'Araçta ciddi bir arıza olduğunu ve kesinlikle çalıştırılmaması gerektiğini',
      'Sistemlerin kontak açılınca kendi kendini test etmesini (ön kontrol); lambaların yanması normaldir, motor çalışınca sönmeleri sistemlerin sağlıklı olduğunu gösterir, sönmeyen lamba ise ilgili sistemde bir uyarı/arıza demektir',
      'Akünün tamamen bittiğini',
      'Farların otomatik yandığını',
    ],
    answerIndex: 1,
    explanation:
      'Kontak açıldığında araç, ikaz lambalarını kısa süre yakarak hem ampullerin çalıştığını hem de sistemlerin kendini denetlediğini gösterir; buna bir tür ön kontrol (öz test) denir. Motor çalışıp sistemler sorunsuz bulununca bu lambaların çoğu söner. Eğer bir lamba (örneğin yağ basıncı, şarj, ABS veya motor arıza lambası) sönmeyip yanık kalırsa, o sistemde dikkat edilmesi gereken bir durum var demektir ve ilgili uyarı değerlendirilmelidir.',
    whyWrong: [
      'Lambaların açılışta topluca yanması arıza değil, normal öz testtir.',
      'Bu davranışın akünün bitmesiyle ya da farların yanmasıyla ilgisi yoktur; sönmeyen lamba asıl uyarıdır.',
    ],
    objective:
      'Kontak açılışındaki lamba öz testini yorumlayıp sönmeyen lambanın uyarı olduğunu bilmek.',
    tags: ['gosterge-paneli', 'oz-test', 'ikaz-lambalari'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
];
