/**
 * ÖZGÜN genişletme soruları — QIP 2.0 İçerik Genişletme · Faz 4.
 * Faz 3 boşluk analizinin en ince temalarını hedefler (ışıklı işaret, gösterge paneli, periyodik
 * bakım, kırık-çıkık, duraklama-park, güvenlik donanımı, fren, yakıt, farlar).
 *
 * Kaynak = resmî Karayolları Trafik mevzuatı + MEB/ODSGM müfredatı + ilk yardım standartları;
 * KENDİ İFADEMİZLE. Hiçbir uygulama/site/sınav sorusu kopyalanmamıştır. review: 'draft' — uzman onayı gerekir.
 */
import type { Question } from '@ea/content-schema';

const SRC = 'Resmî MEB/ODSGM müfredatı ve Karayolları Trafik mevzuatı (özgün ifade)';
const IY = 'Resmî ilk yardım standartları (özgün ifade)';

export const GENISLETME_QUESTIONS_1: Question[] = [
  // ——— Işıklı İşaret Cihazları ———
  {
    id: 'gen-isik-001',
    subject: 'trafik',
    topic: 'isikli-isaret-cihazlari',
    difficulty: 'kolay',
    stem: 'Kavşakta yalnızca yanıp sönen sarı ışık sürücüye ne anlatır?',
    options: [
      'Dur ve bekle',
      'Yavaşla, dikkatli ol ve kurallara göre geç',
      'Hızlan ve hemen geç',
      'Geri dön',
    ],
    answerIndex: 1,
    explanation:
      'Yanıp sönen sarı ışık bir uyarıdır: sürücü hızını azaltır, dikkatle yaklaşır ve geçiş kurallarına (öncelik) uyarak geçer.',
    whyWrong: [
      'Yanıp sönen sarı, tam durmayı gerektiren kırmızı değildir.',
      'Hızlanmak uyarı ışığının amacına aykırıdır.',
      'Geri dönüş söz konusu değildir.',
    ],
    objective: 'Yanıp sönen sarı ışığın uyarı anlamını kavramak.',
    tags: ['isikli-isaret', 'kavsak', 'uyari'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen-isik-002',
    subject: 'trafik',
    topic: 'sari-isik-karar',
    difficulty: 'orta',
    stem: 'Trafik ışığı yeşilden sarıya döndüğünde kavşağa çok yaklaşmış ve güvenle duramayacak olan sürücü ne yapmalıdır?',
    options: [
      'Ani fren yaparak durur',
      'Kavşağı güvenli biçimde boşaltarak geçer',
      'Kavşak ortasında durur',
      'Geri manevra yapar',
    ],
    answerIndex: 1,
    explanation:
      'Güvenle durulamayacak kadar yaklaşılmışsa ani fren arkadan çarpışmaya yol açabilir; sürücü kavşağı güvenle boşaltarak geçer.',
    whyWrong: [
      'Ani fren, arkadan gelen araç için çarpışma riski yaratır.',
      'Kavşak ortasında durmak trafiği kilitler ve tehlikelidir.',
      'Kavşakta geri manevra yasak ve tehlikelidir.',
    ],
    objective: 'Sarı ışıkta güvenli karar verebilmek.',
    tags: ['sari-isik', 'kavsak', 'karar'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen-isik-003',
    subject: 'trafik',
    topic: 'kirmizida-saga-donus',
    difficulty: 'orta',
    stem: 'Ülkemizde kırmızı ışıkta sağa dönüş kural olarak nasıldır?',
    options: [
      'Her zaman serbesttir',
      'Ayrı bir ok/işaret ile izin verilmedikçe yasaktır',
      'Gece serbesttir',
      'Yaya yoksa serbesttir',
    ],
    answerIndex: 1,
    explanation:
      'Kırmızı ışık dur anlamı taşır; sağa dönüşe yalnızca ayrı bir yeşil ok veya izin işareti varsa dönülebilir.',
    whyWrong: [
      'Her zaman serbest değildir; kırmızı dur demektir.',
      'Gece veya yaya durumuna bağlı bir serbestlik yoktur.',
      'İzin işareti olmadan yaya olmaması dönüşü serbest kılmaz.',
    ],
    objective: 'Kırmızı ışıkta dönüş kuralını bilmek.',
    tags: ['kirmizida-saga-donus', 'isik'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen-isik-004',
    subject: 'trafik',
    topic: 'isikli-isaret-cihazlari',
    difficulty: 'kolay',
    stem: 'Trafik ışığında kırmızı ile birlikte sarının da yandığı safha ne anlama gelir?',
    options: [
      'Hemen geç',
      'Birazdan yeşil yanacak; harekete hazırlan ama henüz geçme',
      'Dur ve motoru durdur',
      'Kavşakta geri git',
    ],
    answerIndex: 1,
    explanation:
      'Kırmızı+sarı safhası, yeşilin yanmak üzere olduğunu bildirir; sürücü hareket için hazırlanır ancak yeşil yanmadan geçmez.',
    whyWrong: [
      'Bu safhada geçiş hakkı henüz doğmamıştır.',
      'Motoru durdurmak gerekmez.',
      'Geri gitmek yasak ve tehlikelidir.',
    ],
    objective: 'Kırmızı+sarı geçiş safhasını yorumlamak.',
    tags: ['isikli-isaret', 'isik'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen-isik-005',
    subject: 'trafik',
    topic: 'isik-ihlali',
    difficulty: 'kolay',
    stem: 'Kırmızı ışıkta durmayıp geçmek (ışık ihlali) neden ciddi bir kuraldışı davranıştır?',
    options: [
      'Yalnızca yakıt harcar',
      'Kavşakta geçiş hakkı olan araç ve yayalarla çarpışma riski yaratır',
      'Sadece estetik bir sorundur',
      'Hiçbir sakıncası yoktur',
    ],
    answerIndex: 1,
    explanation:
      'Kırmızı ışık kavşağı diğer yönlere açar; ihlal, geçiş hakkı olan araç ve yayalarla ölümcül çarpışmalara yol açabilir ve yaptırımı vardır.',
    whyWrong: [
      'Sorun yakıt değil, can güvenliğidir.',
      'Estetik bir konu değildir.',
      'Ciddi sakıncası ve cezası vardır.',
    ],
    objective: 'Işık ihlalinin tehlikesini kavramak.',
    tags: ['isik-ihlali', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },

  // ——— Gösterge Paneli ———
  {
    id: 'gen-gosterge-001',
    subject: 'motor',
    topic: 'gosterge-paneli',
    difficulty: 'orta',
    stem: 'Sürüş sırasında kırmızı yağ basıncı ikaz lambası yanarsa sürücü ne yapmalıdır?',
    options: [
      'Yola devam eder',
      'Aracı güvenli yerde durdurup motoru derhal durdurur ve kontrol ettirir',
      'Klimayı kapatır',
      'Camları açar',
    ],
    answerIndex: 1,
    explanation:
      'Kırmızı yağ basıncı lambası yetersiz yağlanmayı gösterir; sürüşe devam motoru ağır hasara uğratır. Araç güvenle durdurulup motor durdurulmalı ve kontrol edilmelidir.',
    whyWrong: [
      'Devam etmek motoru sıkabilir/hasar verebilir.',
      'Klima kapatmak yağ basıncı sorununu çözmez.',
      'Cam açmak ilgisizdir.',
    ],
    objective: 'Kırmızı ikaz lambalarına doğru tepki vermek.',
    tags: ['gosterge', 'ikaz-lambalari', 'yaglama'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen-gosterge-002',
    subject: 'motor',
    topic: 'gosterge-paneli',
    difficulty: 'orta',
    stem: 'Gösterge panelinde akü/şarj (kırmızı akü sembolü) ikaz lambasının yanması neyi işaret eder?',
    options: [
      'Lastik basıncının düştüğünü',
      'Şarj sisteminde (alternatör/kayış) arıza olabileceğini',
      'Yakıtın bittiğini',
      'Kapının açık olduğunu',
    ],
    answerIndex: 1,
    explanation:
      'Akü sembollü ikaz, şarj sisteminin aküyü doldurmadığını gösterir (alternatör veya kayış arızası olabilir); kısa sürede kontrol ettirilmelidir.',
    whyWrong: [
      'Lastik basıncının ayrı bir ikaz sembolü vardır.',
      'Yakıt için ayrı gösterge vardır.',
      'Kapı ikazı farklıdır.',
    ],
    objective: 'Şarj ikaz lambasını tanımak.',
    tags: ['gosterge', 'sarj-lambasi', 'aku'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen-gosterge-003',
    subject: 'motor',
    topic: 'sicaklik-gostergesi',
    difficulty: 'orta',
    stem: 'Motor sıcaklık (hararet) göstergesi kırmızı bölgeye geldiğinde ilk yapılması gereken nedir?',
    options: [
      'Radyatör kapağını hemen açmak',
      'Aracı güvenli yerde durdurup motoru soğumaya bırakmak',
      'Hızlanarak rüzgârla soğutmak',
      'Kaloriferi kapatmak',
    ],
    answerIndex: 1,
    explanation:
      'Hararette araç durdurulur; sıcak radyatör kapağı asla açılmaz (yanık riski). Motorun soğuması beklenir ve neden araştırılır.',
    whyWrong: [
      'Sıcak radyatör kapağı basınçlı sıvı fışkırtıp ağır yanığa yol açar.',
      'Hızlanmak motoru daha çok ısıtır.',
      'Kalorifer açmak bir miktar yardımcı olabilir ama önce durulur.',
    ],
    objective: 'Hararet durumunda güvenli davranış.',
    tags: ['sicaklik-gostergesi', 'hararet', 'gosterge'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen-gosterge-004',
    subject: 'motor',
    topic: 'gosterge-paneli',
    difficulty: 'kolay',
    stem: 'Gösterge panelinde yeşil renkli ikaz lambaları genellikle neyi bildirir?',
    options: [
      'Ciddi bir arızayı',
      'Bir sistemin çalıştığını/aktif olduğunu (bilgi)',
      'Motorun durduğunu',
      'Yakıtın bittiğini',
    ],
    answerIndex: 1,
    explanation:
      'Yeşil lambalar bilgilendirme amaçlıdır ve ilgili sistemin (ör. sinyal, kısa far) çalıştığını/aktif olduğunu gösterir; kırmızı acil, sarı uyarı anlamı taşır.',
    whyWrong: [
      'Ciddi arıza genellikle kırmızı/sarı ile gösterilir.',
      'Motorun durması ayrı bir durumdur.',
      'Yakıt uyarısı ayrıdır.',
    ],
    objective: 'İkaz lambası renk kodlarını ayırt etmek.',
    tags: ['gosterge', 'ikaz-lambalari'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },

  // ——— Periyodik Bakım ———
  {
    id: 'gen-bakim-001',
    subject: 'motor',
    topic: 'periyodik-bakim',
    difficulty: 'kolay',
    stem: 'Motor yağının değişim zamanı genel olarak neye göre belirlenir?',
    options: [
      'Aracın rengine göre',
      'Üreticinin belirttiği kilometre veya süreye göre',
      'Sadece arıza çıkınca',
      'Lastik basıncına göre',
    ],
    answerIndex: 1,
    explanation:
      'Motor yağı, üreticinin el kitabında belirttiği kilometre veya zaman aralığında (hangisi önce dolarsa) değiştirilir; düzenli değişim motor ömrünü korur.',
    whyWrong: [
      'Rengin bakımla ilgisi yoktur.',
      'Arıza çıkmasını beklemek geç kalmaktır.',
      'Lastik basıncı ayrı bir konudur.',
    ],
    objective: 'Periyodik yağ değişimi mantığını bilmek.',
    tags: ['periyodik-bakim', 'yaglama'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen-bakim-002',
    subject: 'motor',
    topic: 'hava-filtresi',
    difficulty: 'orta',
    stem: 'Tıkanmış bir hava filtresinin araca etkisi ne olur?',
    options: [
      'Fren mesafesini kısaltır',
      'Yakıt tüketimini artırır ve motor performansını düşürür',
      'Lastik ömrünü uzatır',
      'Direksiyonu ağırlaştırır',
    ],
    answerIndex: 1,
    explanation:
      'Kirli/tıkalı hava filtresi motora yeterli hava girişini engeller; yanma bozulur, yakıt tüketimi artar ve güç düşer. Periyodik olarak değişmelidir.',
    whyWrong: [
      'Frenle ilgisi yoktur.',
      'Lastik ömrüyle ilgisi yoktur.',
      'Direksiyon hidroliği ayrı bir sistemdir.',
    ],
    objective: 'Hava filtresinin işlevini kavramak.',
    tags: ['filtre', 'hava-filtresi', 'periyodik-bakim'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen-bakim-003',
    subject: 'motor',
    topic: 'silecek-lastigi',
    difficulty: 'kolay',
    stem: 'Cam sileceği süpürgesi camda iz bırakıyor ve iyi temizlemiyorsa ne yapılmalıdır?',
    options: [
      'Görmezden gelinir',
      'Silecek lastiği/süpürgesi yenisiyle değiştirilir',
      'Cam açık bırakılır',
      'Sinyal kolu değiştirilir',
    ],
    answerIndex: 1,
    explanation:
      'Yıpranmış silecek lastiği görüşü bozar; yağmurda güvenliği doğrudan etkilediğinden yenisiyle değiştirilmelidir.',
    whyWrong: [
      'Görmezden gelmek yağışta görüşü tehlikeye atar.',
      'Camı açık bırakmak çözüm değildir.',
      'Sorun sinyal kolu değil, silecek lastiğidir.',
    ],
    objective: 'Görüş güvenliği için silecek bakımı.',
    tags: ['silecek', 'periyodik-bakim', 'gorus'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },

  // ——— Kırık, Çıkık ve Burkulma ———
  {
    id: 'gen-kirik-001',
    subject: 'ilkyardim',
    topic: 'kirik-cikik-burkulma',
    difficulty: 'orta',
    stem: 'Kapalı kırık şüphesi olan bir yaralıya ilk yardımda temel yaklaşım nedir?',
    options: [
      'Kırık bölgeyi düzeltmeye çalışmak',
      'Bölgeyi hareket ettirmeden atelle (alt ve üst eklemi içine alacak şekilde) tespit etmek',
      'Yaralıyı hemen ayağa kaldırmak',
      'Sıcak uygulamak',
    ],
    answerIndex: 1,
    explanation:
      'Kırık bölge oynatılmadan, alt ve üst eklemi de içine alan bir atelle sabitlenir; bu ağrıyı ve ek yaralanmayı azaltır. Kırık düzeltilmeye çalışılmaz.',
    whyWrong: [
      'Kırığı düzeltmeye çalışmak damar/sinir hasarına yol açabilir.',
      'Yaralıyı zorla ayağa kaldırmak zararlıdır.',
      'Kırıkta sıcak değil, tespit önceliklidir.',
    ],
    objective: 'Kırıkta tespit ilkesini kavramak.',
    tags: ['kirik', 'atel', 'tespit'],
    badge: 'official',
    review: 'draft',
    sourceRef: IY,
  },
  {
    id: 'gen-kirik-002',
    subject: 'ilkyardim',
    topic: 'kirik',
    difficulty: 'orta',
    stem: 'Açık kırıkta (kemik ucu dışarıda/yara var) ilk yardım sırası nasıl olmalıdır?',
    options: [
      'Kemiği içeri itmek',
      'Önce kanamayı kontrol etmek, yarayı temiz bezle örtmek, sonra atelle tespit etmek',
      'Yalnızca soğuk uygulamak',
      'Yaralıyı yürütmek',
    ],
    answerIndex: 1,
    explanation:
      'Açık kırıkta önce kanama kontrol edilir, yara temiz bir örtüyle kapatılır (kemik içeri itilmez), ardından bölge atelle sabitlenir ve sağlık ekibi beklenir.',
    whyWrong: [
      'Kemiği içeri itmek enfeksiyon ve hasar riskini artırır.',
      'Sadece soğuk uygulamak kanamayı ve tespiti göz ardı eder.',
      'Kırıkla yürütmek zararlıdır.',
    ],
    objective: 'Açık kırıkta doğru müdahale sırası.',
    tags: ['kirik', 'kanama', 'atel'],
    badge: 'official',
    review: 'draft',
    sourceRef: IY,
  },
  {
    id: 'gen-kirik-003',
    subject: 'ilkyardim',
    topic: 'burkulma',
    difficulty: 'kolay',
    stem: 'Ayak bileği burkulmasında uygulanacak temel ilk yardım yaklaşımı nedir?',
    options: [
      'Sıcak su torbası koymak ve masaj yapmak',
      'Bölgeyi dinlendirmek, soğuk uygulamak, bası ve yükseltme (RICE)',
      'Hemen yürütmek',
      'Sıkı sıkı bağlayıp koşturmak',
    ],
    answerIndex: 1,
    explanation:
      'Burkulmada dinlenme, soğuk uygulama, hafif bası ve bölgeyi yükseltme (RICE) şişliği ve ağrıyı azaltır. Erken dönemde sıcak ve masaj önerilmez.',
    whyWrong: [
      'Erken dönemde sıcak/masaj şişliği artırabilir.',
      'Burkulan bölgeyi zorlamak zararlıdır.',
      'Zorlayarak hareket ettirmek doğru değildir.',
    ],
    objective: 'Burkulmada RICE ilkesini uygulamak.',
    tags: ['burkulma', 'sicak-soguk-uygulama'],
    badge: 'best',
    review: 'draft',
    sourceRef: IY,
  },
  {
    id: 'gen-kirik-004',
    subject: 'ilkyardim',
    topic: 'cikik',
    difficulty: 'orta',
    stem: 'Eklem çıkığı olan bir yaralıda ilk yardımcı ne yapmalıdır?',
    options: [
      'Eklemi yerine oturtmaya çalışmak',
      'Eklemi bulunduğu konumda tespit edip sağlık kuruluşuna yönlendirmek',
      'Sıcak uygulayıp beklemek',
      'Yaralıyı zıplatmak',
    ],
    answerIndex: 1,
    explanation:
      'Çıkık yerine oturtulmaya çalışılmaz (damar/sinir hasarı riski); eklem bulunduğu konumda desteklenerek tespit edilir ve tıbbi yardıma yönlendirilir.',
    whyWrong: [
      'Yerine oturtma girişimi ciddi hasar verebilir.',
      'Sadece sıcak uygulamak yeterli/doğru değildir.',
      'Yaralıyı hareketlendirmek zararlıdır.',
    ],
    objective: 'Çıkıkta tespit ve sevk ilkesi.',
    tags: ['cikik', 'tespit'],
    badge: 'official',
    review: 'draft',
    sourceRef: IY,
  },

  // ——— Duraklama ve Park ———
  {
    id: 'gen-park-001',
    subject: 'trafik',
    topic: 'duraklama-park',
    difficulty: 'kolay',
    stem: 'Aşağıdaki yerlerden hangisinde duraklamak ve park etmek yasaktır?',
    options: [
      'Geniş bir otopark alanında',
      'Yaya ve okul geçitleri üzerinde',
      'İzin verilen park cebinde',
      'Evin önündeki uygun şeritte',
    ],
    answerIndex: 1,
    explanation:
      'Yaya ve okul geçitleri üzerinde duraklamak/park etmek yasaktır; bu alanlar yayaların güvenli geçişi için boş tutulmalıdır.',
    whyWrong: [
      'Uygun otoparkta park serbesttir.',
      'İzinli park cebinde park edilebilir.',
      'İzin verilen şeritte park mümkündür.',
    ],
    objective: 'Park/duraklama yasağı olan yerleri bilmek.',
    tags: ['duraklama-park', 'yaya'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen-park-002',
    subject: 'trafik',
    topic: 'duraklama-park',
    difficulty: 'orta',
    stem: 'Trafikte "duraklama" en doğru şekilde nasıl tanımlanır?',
    options: [
      'Aracı uzun süre terk etmek',
      'Yolcu indirip bindirmek veya kısa bir iş için aracı kısa süreli durdurmak',
      'Motoru kapatıp gece boyu bırakmak',
      'Aracı tamir için bırakmak',
    ],
    answerIndex: 1,
    explanation:
      'Duraklama; yolcu indirme-bindirme, yük alma-verme gibi nedenlerle aracın kısa süreli durdurulmasıdır. Uzun süreli bırakma park kapsamındadır.',
    whyWrong: [
      'Uzun süre terk etmek parktır.',
      'Gece boyu bırakmak parktır.',
      'Tamire bırakmak duraklama değildir.',
    ],
    objective: 'Duraklama ile parkı ayırt etmek.',
    tags: ['duraklama-park'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen-park-003',
    subject: 'trafik',
    topic: 'egimde-park',
    difficulty: 'zor',
    stem: 'Yokuş aşağı, bordürlü (kaldırımlı) bir yolda park eden sürücü ön tekerlekleri hangi yöne çevirmelidir?',
    options: [
      'Yoldan uzağa, bordüre (kaldırıma) doğru',
      'Yola paralel bırakır',
      'Yola doğru, trafiğe bakacak şekilde',
      'Fark etmez',
    ],
    answerIndex: 0,
    explanation:
      'Yokuş aşağı parkta araç kayarsa bordür engel olsun diye ön tekerlekler kaldırıma doğru çevrilir; ayrıca el freni çekilir ve vites takılır.',
    whyWrong: [
      'Tekerleği yola paralel bırakmak, kayma hâlinde aracı trafiğe sürükler.',
      'Yola doğru çevirmek aracı yola kaydırır.',
      'Tekerlek yönü güvenlik için önemlidir; fark eder.',
    ],
    objective: 'Eğimde güvenli park tekniğini bilmek.',
    tags: ['egimde-park', 'duraklama-park', 'guvenlik'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },

  // ——— Güvenlik Donanımı ———
  {
    id: 'gen-guvenlik-001',
    subject: 'trafik',
    topic: 'emniyet-kemeri',
    difficulty: 'kolay',
    stem: 'Araçta emniyet kemeri takma zorunluluğu kimleri kapsar?',
    options: [
      'Yalnızca sürücüyü',
      'Ön ve arka koltuktaki tüm yolcuları',
      'Sadece ön koltuktakileri',
      'Sadece uzun yolda gidenleri',
    ],
    answerIndex: 1,
    explanation:
      'Emniyet kemeri, araçta önde ve arkada oturan tüm yolcular için zorunludur; kaza anında ciddi yaralanma ve ölüm riskini belirgin biçimde azaltır.',
    whyWrong: [
      'Yalnızca sürücü değil, tüm yolcular kapsanır.',
      'Arka koltuk da dâhildir.',
      'Zorunluluk yol uzunluğuna bağlı değildir.',
    ],
    objective: 'Emniyet kemeri zorunluluğunun kapsamını bilmek.',
    tags: ['emniyet-kemeri', 'guvenlik-donanimi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen-guvenlik-002',
    subject: 'motor',
    topic: 'hava-yastigi',
    difficulty: 'orta',
    stem: 'Hava yastığı (airbag) sürücüyü en iyi hangi durumda korur?',
    options: [
      'Emniyet kemeri takılı değilken tek başına',
      'Emniyet kemeriyle birlikte kullanıldığında',
      'Yalnızca düşük hızda',
      'Yalnızca arka koltukta',
    ],
    answerIndex: 1,
    explanation:
      'Hava yastığı emniyet kemerini tamamlayan bir sistemdir; kemer takılı değilse tek başına yeterli korumayı sağlamaz, hatta zarar verebilir. İkisi birlikte etkilidir.',
    whyWrong: [
      'Kemersiz airbag tam koruma sağlamaz.',
      'Etkisi yalnızca düşük hızla sınırlı değildir.',
      'Ön koltuk sürücü/yolcu için tasarlanmıştır.',
    ],
    objective: 'Airbag–kemer birlikteliğini kavramak.',
    tags: ['hava-yastigi', 'emniyet-kemeri', 'guvenlik-donanimi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen-guvenlik-003',
    subject: 'trafik',
    topic: 'cocuk-guvenligi',
    difficulty: 'orta',
    stem: 'Belirli boy/yaşın altındaki çocuklar araçta nasıl taşınmalıdır?',
    options: [
      'Ön koltukta kucakta',
      'Yaşına/boyuna uygun çocuk koltuğu/oturağı ile ve ön koltukta oturmadan',
      'Arka koltukta kemersiz',
      'Bagajda',
    ],
    answerIndex: 1,
    explanation:
      'Çocuklar yaşına ve boyuna uygun çocuk koltuğu/yükseltici ile taşınır ve kural olarak ön koltukta oturtulmaz; bu, kaza anında ciddi yaralanmaları önler.',
    whyWrong: [
      'Kucakta taşımak son derece tehlikelidir.',
      'Kemersiz taşıma güvenli değildir.',
      'Bagajda taşıma kesinlikle yasaktır.',
    ],
    objective: 'Çocuk güvenliği kurallarını bilmek.',
    tags: ['cocuk-guvenligi', 'guvenlik-donanimi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },

  // ——— Fren Sistemi ———
  {
    id: 'gen-fren-001',
    subject: 'motor',
    topic: 'fren-sistemi',
    difficulty: 'orta',
    stem: 'ABS (kilitlenmeyi önleyici fren sistemi) sürücüye temel olarak ne sağlar?',
    options: [
      'Fren mesafesini her zeminde sıfırlar',
      'Ani/sert frende tekerlek kilitlenmesini önleyerek direksiyon hâkimiyetinin korunmasını sağlar',
      'Yakıt tüketimini azaltır',
      'Motor gücünü artırır',
    ],
    answerIndex: 1,
    explanation:
      'ABS, sert frende tekerleklerin kilitlenip kaymasını önler; böylece sürücü fren yaparken direksiyonla engelden kaçınabilir. Fren mesafesini her zeminde sıfırlamaz.',
    whyWrong: [
      'ABS fren mesafesini sıfırlamaz; hâkimiyeti korur.',
      'Yakıt tüketimiyle doğrudan ilgisi yoktur.',
      'Motor gücüyle ilgisi yoktur.',
    ],
    objective: 'ABS’nin işlevini doğru anlamak.',
    tags: ['fren', 'abs', 'fren-sistemi'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen-fren-002',
    subject: 'motor',
    topic: 'fren-bakim',
    difficulty: 'orta',
    stem: 'Fren pedalına basıldığında direksiyonda/pedalda titreme hissediliyorsa muhtemel neden ve doğru davranış nedir?',
    options: [
      'Normaldir, önemsenmez',
      'Disk/balata aşınması olabilir; fren sistemi kontrol ettirilmelidir',
      'Lastik havası fazladır, indirilmelidir',
      'Yakıt biter, depo doldurulur',
    ],
    answerIndex: 1,
    explanation:
      'Frende titreme genellikle aşınmış/deforme disk veya balatayı işaret eder; güvenlik açısından fren sistemi vakit geçirmeden kontrol ettirilmelidir.',
    whyWrong: [
      'Titreme normal değildir, arıza işaretidir.',
      'Lastik havasıyla ilgisi yoktur.',
      'Yakıtla ilgisi yoktur.',
    ],
    objective: 'Fren arıza belirtisini tanımak.',
    tags: ['fren', 'fren-bakim'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },

  // ——— Yakıt Sistemi ———
  {
    id: 'gen-yakit-001',
    subject: 'motor',
    topic: 'yakit-sistemi',
    difficulty: 'zor',
    stem: 'Benzinli bir araca yanlışlıkla dizel (veya tersi) yakıt konulduğu fark edilirse ne yapılmalıdır?',
    options: [
      'Motoru çalıştırıp yakıtı tüketmek',
      'Motoru çalıştırmadan aracı çektirip yakıt sistemini boşalttırmak',
      'Üzerine doğru yakıt eklemek',
      'Bir süre beklemek',
    ],
    answerIndex: 1,
    explanation:
      'Yanlış yakıtta motor çalıştırılmamalıdır; çalıştırmak yakıt sistemine ciddi hasar verebilir. Araç çektirilip yakıt sistemi boşaltılmalıdır.',
    whyWrong: [
      'Çalıştırmak yakıt pompası/enjektörlere zarar verir.',
      'Karışık yakıt sorunu çözmez.',
      'Beklemek sorunu gidermez.',
    ],
    objective: 'Yanlış yakıtta doğru davranışı bilmek.',
    tags: ['yakit', 'yanlis-yakit', 'yakit-sistemi'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen-yakit-002',
    subject: 'motor',
    topic: 'yakit-tasarrufu',
    difficulty: 'kolay',
    stem: 'Aşağıdakilerden hangisi yakıt tüketimini azaltır?',
    options: [
      'Sürekli ani hızlanma ve fren',
      'Sabit hızda gitmek, erken vites yükseltmek ve gereksiz yükü atmak',
      'Lastikleri sürekli düşük basınçta tutmak',
      'Bagajı ağır yükle dolu tutmak',
    ],
    answerIndex: 1,
    explanation:
      'Düzgün ve sabit hız, erken vites geçişi, uygun lastik basıncı ve gereksiz yükten kaçınmak yakıt tüketimini ve emisyonu azaltır.',
    whyWrong: [
      'Ani hızlan-fren yakıtı artırır.',
      'Düşük lastik basıncı tüketimi artırır.',
      'Gereksiz ağırlık tüketimi artırır.',
    ],
    objective: 'Ekonomik/çevreci sürüş davranışları.',
    tags: ['yakit-tasarrufu', 'cevre', 'yakit'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },

  // ——— Farlar ve Aydınlatma ———
  {
    id: 'gen-far-001',
    subject: 'trafik',
    topic: 'far-kullanimi',
    difficulty: 'orta',
    stem: 'Gece şehir dışında karşıdan araç yaklaşırken uzun huzmeli (uzun far) giden sürücü ne yapmalıdır?',
    options: [
      'Uzun farı açık tutar',
      'Karşı sürücüyü kör etmemek için kısa huzmeye (kısa far) geçer',
      'Farları tamamen söndürür',
      'Dörtlü flaşörü yakar',
    ],
    answerIndex: 1,
    explanation:
      'Karşıdan araç gelirken uzun far, diğer sürücüyü göz kamaştırıp kör edebilir; kaza riskini önlemek için kısa huzmeye geçilir.',
    whyWrong: [
      'Uzun farı açık tutmak karşı sürücüyü kör eder.',
      'Farları söndürmek görüşü yok eder, tehlikelidir.',
      'Dörtlü flaşör bu durumun çözümü değildir.',
    ],
    objective: 'Gece far görgüsünü uygulamak.',
    tags: ['far', 'gece', 'far-kullanimi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen-far-002',
    subject: 'trafik',
    topic: 'sis-lambasi',
    difficulty: 'orta',
    stem: 'Sis (arka/ön sis) lambaları ne zaman kullanılmalıdır?',
    options: [
      'Her sürüşte sürekli',
      'Yalnızca yoğun sis, kar veya şiddetli yağış gibi görüşün ciddi azaldığı durumlarda',
      'Gündüz açık havada',
      'Şehir içi normal sürüşte',
    ],
    answerIndex: 1,
    explanation:
      'Sis lambaları görüşün ciddi azaldığı sis/kar/şiddetli yağışta kullanılır; normal koşullarda yakılması diğer sürücüleri rahatsız eder ve yanıltır.',
    whyWrong: [
      'Sürekli kullanım diğer sürücüleri rahatsız eder.',
      'Açık havada gereksizdir.',
      'Normal şehir sürüşünde kullanılmaz.',
    ],
    objective: 'Sis lambası kullanım koşulunu bilmek.',
    tags: ['far', 'sis-lamba', 'far-turleri'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
];
