/**
 * ÖZGÜN trafik soruları — 2. genişletme (Program 1). ROADMAP C.4/E.6.
 * Kaynak = resmî MEB/ODSGM müfredatı + Karayolları Trafik mevzuatı; KENDİ İFADEMİZLE.
 */
import type { QuestionInput } from '@ea/content-schema';

const SRC = 'Resmî MEB/ODSGM müfredatı ve Karayolları Trafik mevzuatı (özgün ifade)';

export const TRAFIK_QUESTIONS_2: QuestionInput[] = [
  {
    id: 'trafik-201',
    subject: 'trafik',
    topic: 'hiz',
    difficulty: 'kolay',
    stem: 'Yerleşim yeri içindeki bir yolda otomobil için genel azami hız kaç km/saattir?',
    options: ['40 km/saat', '50 km/saat', '60 km/saat', '70 km/saat'],
    answerIndex: 1,
    explanation:
      'Yerleşim yeri içinde otomobiller için genel azami hız 50 km/saattir; farklı bir levha yoksa bu sınır uygulanır.',
    whyWrong: [
      '40 km/s ancak levhayla bildirilen daha düşük bir sınır olabilir.',
      '60 ve 70 km/s yerleşim yeri içi genel sınırın üzerindedir.',
    ],
    objective: 'Yerleşim yeri içi genel hız sınırını bilmek.',
    tags: ['hiz-siniri', 'yerlesim-ici', 'otomobil'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-202',
    subject: 'trafik',
    topic: 'hiz',
    difficulty: 'kolay',
    stem: 'Genel azami hızın 90 km/saat olduğu yerleşim yeri dışındaki bir yol kesiminde "50" yazılı hız sınırlaması levhası varsa, otomobil sürücüsü en fazla kaç km/saat hızla gidebilir?',
    options: ['50 km/saat', '70 km/saat', '90 km/saat', '110 km/saat'],
    answerIndex: 0,
    explanation:
      'Trafik işaret levhası ile bildirilen hız sınırı, o yol kesiminde genel hız sınırının önüne geçer; "50" levhası bulunan kesimde azami hız 50 km/saattir.',
    whyWrong: [
      '90 km/s genel sınırdır; levhayla farklı bir sınır bildirilen kesimde geçerliliğini yitirir.',
      '70 ve 110 km/s ne levhada yazan ne de o yolun genel sınırı olan değerlerdir.',
    ],
    objective: 'Levha ile genel hız sınırı çeliştiğinde levhadaki sınırın geçerli olduğunu bilmek.',
    tags: ['hiz-siniri', 'trafik-levhasi', 'levha-onceligi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-203',
    subject: 'trafik',
    topic: 'hiz',
    difficulty: 'orta',
    stem: 'Yerleşim yeri dışındaki bölünmüş (gidiş-gelişi ayrılmış) bir yolda otomobil için genel azami hız kaç km/saattir?',
    options: ['80 km/saat', '90 km/saat', '100 km/saat', '110 km/saat'],
    answerIndex: 3,
    explanation:
      'Yerleşim yeri dışındaki bölünmüş yollarda otomobil için genel azami hız 110 km/saattir; bu, otoyolun bir alt kademesidir.',
    whyWrong: [
      '90 km/s bölünmemiş yolun genel sınırıdır.',
      '80 ve 100 km/s bölünmüş yolun genel sınırının altındadır.',
    ],
    objective: 'Bölünmüş şehirlerarası yolun hız sınırını bilmek.',
    tags: ['hiz-siniri', 'bolunmus-yol', 'otomobil'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-204',
    subject: 'trafik',
    topic: 'hiz',
    difficulty: 'kolay',
    stem: 'Yağışlı havada zemin ıslak ve kaygan olduğunda sürücünün hızıyla ilgili en doğru davranış hangisidir?',
    options: [
      'Hızını azaltır ve takip mesafesini artırır',
      'Kuru yoldaki gibi aynı hızda sürer',
      'Hızını artırıp kaygan bölgeyi çabuk geçer',
      'Farlarını söndürerek yavaşlar',
    ],
    answerIndex: 0,
    explanation:
      'Islak ve kaygan zeminde frenleme mesafesi uzar; bu nedenle hız azaltılıp takip mesafesi artırılarak güvenlik sağlanır.',
    whyWrong: [
      'Aynı hızda sürmek kayma ve çarpışma riskini artırır.',
      'Hızlanmak kaygan zeminde savrulmaya yol açar.',
      'Far söndürmek görünürlüğü azaltır, çözüm değildir.',
    ],
    objective: 'Olumsuz yol koşullarında hızı uyarlamayı kavramak.',
    tags: ['kaygan-zemin', 'hiz-uyarlama', 'guvenli-surus'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-205',
    subject: 'trafik',
    topic: 'oncelik',
    difficulty: 'kolay',
    stem: 'Işık veya levha ile düzenlenmemiş, eş değer iki yolun kesiştiği kavşakta hangi araç ilk geçer?',
    options: [
      'Soldan gelen araç',
      'Sağdan gelen araç',
      'Daha hızlı olan araç',
      'Daha büyük olan araç',
    ],
    answerIndex: 1,
    explanation:
      'Kontrolsüz ve eş değer yolların kavşağında sürücü sağından gelen araca yol vermek zorundadır; öncelik sağdaki araçtadır.',
    whyWrong: [
      'Soldan gelen araca öncelik verilmez.',
      'Hız ya da araç büyüklüğü geçiş önceliği belirlemez.',
    ],
    objective: 'Kontrolsüz kavşakta sağ önceliğini uygulamak.',
    tags: ['gecis-onceligi', 'kontrolsuz-kavsak', 'sagdan-gelen'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-206',
    subject: 'trafik',
    topic: 'oncelik',
    difficulty: 'zor',
    stem: 'Bir ana yol ile tali yolun birleştiği kavşakta geçiş önceliği kime aittir?',
    options: [
      'Kavşağa önce yaklaşan araç',
      'Sağdaki araç her koşulda',
      'Ana yoldan gelen araç',
      'Tali yoldan gelen araç',
    ],
    answerIndex: 2,
    explanation:
      'Ana yol ile tali yolun kesiştiği yerde öncelik ana yoldaki araçtadır; tali yoldan gelen sürücü ana yola yol vermek zorundadır.',
    whyWrong: [
      'Sağ önceliği yalnızca eş değer yolların kavşağında geçerlidir.',
      'Kavşağa erken gelmek geçiş hakkı vermez.',
      'Tali yoldan gelen bekler, öncelikli değildir.',
    ],
    objective: 'Ana yol-tali yol önceliğini eş değer yol kuralından ayırt etmek.',
    tags: ['gecis-onceligi', 'ana-yol', 'tali-yol'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-207',
    subject: 'trafik',
    topic: 'oncelik',
    difficulty: 'kolay',
    stem: 'Siren ve tepe lambasını çalıştırmış bir ambulansla karşılaşan sürücü ne yapmalıdır?',
    options: [
      'Hızlanıp önünden çekilir',
      'Olduğu yerde durup korna çalar',
      'Ambulansı sollamaya çalışır',
      'Yavaşlayıp yol vererek geçmesini sağlar',
    ],
    answerIndex: 3,
    explanation:
      'Geçiş üstünlüğünü kullanan araçlara (ambulans, itfaiye vb.) tüm sürücüler yavaşlayıp yol vererek geçiş kolaylığı sağlamak zorundadır.',
    whyWrong: [
      'Hızlanmak öngörülemeyen bir manevra oluşturur.',
      'Trafiği kilitleyecek şekilde durup beklemek yolu kapatır.',
      'Geçiş üstünlüğündeki aracı sollamak yasaktır.',
    ],
    objective: 'Geçiş üstünlüğüne sahip araçlara yol vermeyi bilmek.',
    tags: ['gecis-ustunlugu', 'ambulans', 'yol-verme'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-208',
    subject: 'trafik',
    topic: 'isaretler',
    difficulty: 'kolay',
    stem: 'Sekizgen biçimli DUR levhasının bulunduğu yerde sürücüden istenen davranış nedir?',
    options: [
      'Tam olarak durur, yol açıksa geçer',
      'Sadece yavaşlayıp geçer',
      'Yalnızca korna çalar',
      'Hızını koruyarak geçer',
    ],
    answerIndex: 0,
    explanation:
      'DUR levhası sürücünün mutlaka tam olarak durmasını, yolun güvenli olduğunu görüp öyle geçmesini gerektirir.',
    whyWrong: [
      'Yavaşlayıp geçmek DUR kuralını karşılamaz.',
      'Korna çalmak durma zorunluluğunu ortadan kaldırmaz.',
      'Hızı koruyarak geçmek ağır bir ihlaldir.',
    ],
    objective: 'DUR levhasının tam durma zorunluluğunu bilmek.',
    tags: ['dur-levhasi', 'trafik-levhalari', 'kavsak'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-209',
    subject: 'trafik',
    topic: 'isaretler',
    difficulty: 'orta',
    stem: 'Tepesi aşağıya bakan, kırmızı kenarlı üçgen biçimindeki Yol Ver levhası sürücüye ne bildirir?',
    options: [
      'Geçiş hakkının kendisinde olduğunu',
      'Ana yoldaki araçlara yol vermesi gerektiğini',
      'Yolun tamamen kapalı olduğunu',
      'Park etmenin yasak olduğunu',
    ],
    answerIndex: 1,
    explanation:
      'Yol Ver levhası, sürücünün girmek üzere olduğu yoldaki araçlara geçiş önceliği tanıması gerektiğini bildirir.',
    whyWrong: [
      'Levha geçiş hakkını değil, yol verme yükümlülüğünü anlatır.',
      'Yolun kapalı olduğunu göstermez.',
      'Park yasağıyla ilgisi yoktur.',
    ],
    objective: 'Yol Ver levhasının anlamını kavramak.',
    tags: ['yol-ver', 'trafik-levhalari', 'gecis-onceligi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-210',
    subject: 'trafik',
    topic: 'isaretler',
    difficulty: 'kolay',
    stem: 'Kenarları kırmızı, zemini beyaz üçgen biçimindeki trafik levhaları genel olarak neyi ifade eder?',
    options: [
      'Kesin bir yasağı',
      'Zorunlu bir yönü',
      'Bir tehlikeye karşı uyarıyı',
      'Bir hizmet veya bilgiyi',
    ],
    answerIndex: 2,
    explanation:
      'Kırmızı kenarlı üçgen levhalar tehlike uyarı işaretleridir; ileride dikkat gerektiren bir durum olduğunu bildirir.',
    whyWrong: [
      'Yasaklama levhaları genelde daire biçimlidir.',
      'Zorunlu yön levhaları mavi zeminli dairelerdir.',
      'Hizmet/bilgi levhaları farklı renk ve biçimdedir.',
    ],
    objective: 'Tehlike uyarı levhalarının biçim ve anlamını tanımak.',
    tags: ['tehlike-uyari', 'trafik-levhalari', 'ucgen-levha'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-211',
    subject: 'trafik',
    topic: 'sollama',
    difficulty: 'kolay',
    stem: 'Başka bir araç tarafından geçilmekte (sollanmakta) olan aracın sürücüsü ne yapmalıdır?',
    options: [
      'Hızını artırarak geçişi zorlaştırmalıdır',
      'Sola yaklaşarak yolu kapatmalıdır',
      'Hızını artırmadan şeridinin sağına yaklaşıp geçen araca kolaylık sağlamalıdır',
      'Ani fren yaparak arkadaki aracı uyarmalıdır',
    ],
    answerIndex: 2,
    explanation:
      'Geçilen (sollanan) araç sürücüsü hızını artıramaz; bulunduğu şeridin sağına yaklaşarak geçiş yapan araca kolaylık sağlamak zorundadır.',
    whyWrong: [
      'Sollanırken hız artırmak yasaktır; geçiş süresini uzatarak tehlike yaratır.',
      'Sola yaklaşmak geçen aracın yolunu kapatır.',
      'Gereksiz ani fren, arkadan çarpma riski doğurur.',
    ],
    objective: 'Geçilen araç sürücüsünün hız artırmama ve sağa yaklaşma yükümlülüğünü bilmek.',
    tags: ['sollama', 'gecilen-arac', 'yukumluluk'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-212',
    subject: 'trafik',
    topic: 'sollama',
    difficulty: 'orta',
    stem: 'Öndeki araç, aşağıdaki durumların hangisinde istisna olarak sağından geçilebilir?',
    options: [
      'Trafik yoğun olduğunda',
      'Öndeki araç yavaş gittiğinde',
      'Sol şerit dolu olduğunda',
      'Öndeki araç sola dönüş işareti verip sola yaklaştığında',
    ],
    answerIndex: 3,
    explanation:
      'Geçme kural olarak soldan yapılır; ancak sola dönüş işareti vererek yolun soluna yaklaşmış bir aracın, güvenli koşullar sağlanarak sağından geçilmesine izin verilir.',
    whyWrong: [
      'Trafik yoğunluğu veya öndeki aracın yavaş olması tek başına sağdan geçme hakkı vermez.',
      'Sol şeridin dolu olması da sağdan geçişe izin doğurmaz; uygun an beklenir.',
    ],
    objective: 'Sağdan geçme istisnasını (sola dönüş işareti veren araç) bilmek.',
    tags: ['sollama', 'sagdan-gecme', 'istisna'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-213',
    subject: 'trafik',
    topic: 'sollama',
    difficulty: 'orta',
    stem: 'Sollamaya başlamadan önce sürücünün yapması gereken doğru davranış hangisidir?',
    options: [
      'Aynaları ve karşı yönü kontrol edip dönüş sinyali vermek',
      'Sinyal vermeden hızlıca geçmek',
      'Korna çalıp farları söndürmek',
      'Takip mesafesini tamamen kapatmak',
    ],
    answerIndex: 0,
    explanation:
      'Güvenli sollama için önce aynalar ve karşı yön kontrol edilir, sol sinyal verilerek niyet bildirilir ve yol uygunsa geçilir.',
    whyWrong: [
      'Sinyalsiz ani geçiş diğer sürücüleri şaşırtır.',
      'Far söndürmek görünürlüğü azaltır, sollamayı güvenli yapmaz.',
      'Takip mesafesini kapatmak çarpışma riskini artırır.',
    ],
    objective: 'Güvenli sollama adımlarını sıralayabilmek.',
    tags: ['sollama', 'ayna-kontrol', 'sinyal'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-214',
    subject: 'trafik',
    topic: 'takip-mesafesi',
    difficulty: 'kolay',
    stem: 'Normal hava ve yol koşullarında öndeki aracı en az kaç saniyelik mesafeden takip etmek güvenlidir?',
    options: ['Yarım saniye', '1 saniye', '2 saniye', 'Takip süresi önemli değildir'],
    answerIndex: 2,
    explanation:
      'İki saniye kuralı: öndeki araç bir noktadan geçtikten sonra kendimizin aynı noktaya en az iki saniyede varması güvenli takip mesafesini sağlar.',
    whyWrong: [
      'Yarım ya da 1 saniye ani frende çarpışmaya yetecek kadar yakındır.',
      'Takip süresi güvenliğin temel ölçütüdür, önemsiz değildir.',
    ],
    objective: 'İki saniye takip mesafesi kuralını bilmek.',
    tags: ['takip-mesafesi', 'iki-saniye', 'guvenli-surus'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-215',
    subject: 'trafik',
    topic: 'takip-mesafesi',
    difficulty: 'zor',
    stem: 'Takip mesafesini hızın yarısı kadar metre kuralıyla hesaplayan sürücü, 100 km/saat hızda en az kaç metre boşluk bırakmalıdır?',
    options: ['25 metre', '50 metre', '75 metre', '100 metre'],
    answerIndex: 1,
    explanation:
      'Hızın yarısı kadar metre kuralına göre 100 km/saat hızda en az 50 metrelik takip mesafesi bırakılmalıdır.',
    whyWrong: [
      '25 metre hesaplanan mesafenin yarısı kadardır, yetersizdir.',
      '75 ve 100 metre bu kuralın verdiği değerin üzerindedir.',
    ],
    objective: 'Hıza bağlı takip mesafesini hesaplayabilmek.',
    tags: ['takip-mesafesi', 'hiz-hesabi', 'guvenli-surus'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-216',
    subject: 'trafik',
    topic: 'donel-kavsak',
    difficulty: 'orta',
    stem: 'Dönel kavşakta (göbek/ada etrafında) geçiş önceliği kime aittir?',
    options: [
      'Kavşağa yeni giren araca',
      'Sağdan yaklaşan araca',
      'En hızlı giden araca',
      'Ada etrafında dönmekte olan araca',
    ],
    answerIndex: 3,
    explanation:
      'Dönel kavşakta öncelik, ada etrafında dönmekte olan araçtadır; kavşağa girecek sürücü içeride dönen araca yol verir.',
    whyWrong: [
      'Kavşağa yeni giren araç önceliğe sahip değildir.',
      'Genel sağ önceliği kuralı burada içerideki aracın önceliğinin yerini almaz.',
      'Hız geçiş önceliği belirlemez.',
    ],
    objective: 'Dönel kavşakta içerideki aracın önceliğini bilmek.',
    tags: ['donel-kavsak', 'gecis-onceligi', 'ada'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-217',
    subject: 'trafik',
    topic: 'donel-kavsak',
    difficulty: 'kolay',
    stem: 'Dönel kavşağa girmek üzere olan sürücü ne yapmalıdır?',
    options: [
      'İçeride dönmekte olan araçlara yol verir',
      'Doğrudan hızla girer',
      'Kornaya basıp girer',
      'Geri manevra yapar',
    ],
    answerIndex: 0,
    explanation:
      'Dönel kavşağa yaklaşan sürücü hızını azaltır ve ada etrafında dönmekte olan araçlara yol vererek uygun boşlukta katılır.',
    whyWrong: [
      'Yol vermeden hızla girmek çarpışmaya yol açar.',
      'Korna çalmak yol verme yükümlülüğünü ortadan kaldırmaz.',
      'Kavşakta geri manevra tehlikeli ve yanlıştır.',
    ],
    objective: 'Dönel kavşağa güvenli katılmayı bilmek.',
    tags: ['donel-kavsak', 'yol-verme', 'katilma'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-218',
    subject: 'trafik',
    topic: 'seritler',
    difficulty: 'orta',
    stem: 'Çok şeritli bir yolda yavaş giden araçlar hangi şeridi kullanmalıdır?',
    options: [
      'En soldaki şeridi',
      'Ortadaki şeridi',
      'Sağdaki (en dıştaki) şeridi',
      'İstediği herhangi bir şeridi',
    ],
    answerIndex: 2,
    explanation:
      'Yavaş giden ve seyir hâlindeki araçlar mümkün olduğunca en sağdaki şeridi kullanır; sol şeritler geçiş ve daha hızlı seyir içindir.',
    whyWrong: [
      'En sol şerit sürekli yavaş seyir için değildir.',
      'Orta şeridi sürekli işgal etmek trafiği yavaşlatır.',
      'Şerit seçimi keyfi değil, hıza göredir.',
    ],
    objective: 'Şerit disiplinini ve sağ şerit kullanımını bilmek.',
    tags: ['serit-kullanimi', 'sag-serit', 'yavas-arac'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-219',
    subject: 'trafik',
    topic: 'seritler',
    difficulty: 'kolay',
    stem: 'Şerit değiştirmeden hemen önce sürücünün yapması gereken nedir?',
    options: [
      'Sadece hızlanmak',
      'Ayna kontrolü yapıp dönüş sinyali vermek',
      'Farları yakıp söndürmek',
      'El frenini çekmek',
    ],
    answerIndex: 1,
    explanation:
      'Şerit değiştirmeden önce aynalar ve kör nokta kontrol edilir, sinyal verilerek diğer sürücülere niyet önceden bildirilir.',
    whyWrong: [
      'Sadece hızlanmak diğer araçları haberdar etmez.',
      'Far yakıp söndürmek şerit değiştirme işareti değildir.',
      'Seyir hâlinde el freni çekmek tehlikelidir.',
    ],
    objective: 'Güvenli şerit değiştirme adımlarını bilmek.',
    tags: ['serit-degistirme', 'sinyal', 'ayna-kontrol'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-220',
    subject: 'trafik',
    topic: 'seritler',
    difficulty: 'orta',
    stem: 'Yol üzerindeki devamlı (kesiksiz) çizgi sürücüye ne anlatır?',
    options: [
      'Sadece geceleri geçerli olduğunu',
      'Park alanını gösterdiğini',
      'İstenildiği an geçilebileceğini',
      'Geçilerek şerit değiştirilemeyeceğini',
    ],
    answerIndex: 3,
    explanation:
      'Devamlı (kesiksiz) çizgi geçilemez; bu çizgi üzerinden şerit değiştirmek ya da sollamak yasaktır.',
    whyWrong: [
      'Çizginin kuralı gece-gündüz aynıdır.',
      'Park alanını göstermez.',
      'İstenildiği an geçilebilen çizgi kesik çizgidir.',
    ],
    objective: 'Kesiksiz çizginin anlamını bilmek.',
    tags: ['yol-cizgileri', 'kesiksiz-cizgi', 'serit-degistirme'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-221',
    subject: 'trafik',
    topic: 'duraklama-park',
    difficulty: 'orta',
    stem: 'Trafikte duraklama aşağıdakilerden hangisini ifade eder?',
    options: [
      'Aracı uzun süre bırakıp gitmek',
      'Motoru kapatıp aracı terk etmek',
      'Yolcu indirip bindirmek ya da yük için kısa süreli durmak',
      'Trafik ışığında zorunlu beklemek',
    ],
    answerIndex: 2,
    explanation:
      'Duraklama; yolcu indirip bindirmek veya kısa süreli yük almak-vermek amacıyla aracı kısa süre durdurmaktır. Uzun süreli bekletme ise parktır.',
    whyWrong: [
      'Aracı uzun süre bırakmak parktır, duraklama değildir.',
      'Aracı terk etmek duraklama tanımına girmez.',
      'Işıkta zorunlu bekleme trafik gereği durmadır, duraklama sayılmaz.',
    ],
    objective: 'Duraklama kavramını park kavramından ayırt etmek.',
    tags: ['duraklama', 'park', 'tanim'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-222',
    subject: 'trafik',
    topic: 'duraklama-park',
    difficulty: 'orta',
    stem: 'Aşağıdaki yerlerin hangisinde park etmek yasaktır?',
    options: [
      'Kavşaklarda ve yaya geçitlerinin üzerinde',
      'Görüşün açık olduğu düz yolda',
      'İşaretlenmiş park cebinde',
      'Belediye otoparkında',
    ],
    answerIndex: 0,
    explanation:
      'Kavşaklar, yaya geçitleri, tüneller ve dar-tehlikeli yerlerde park etmek yasaktır; bu yerlerde park görüşü ve geçişi engeller.',
    whyWrong: [
      'Görüşü açık, park yasağı olmayan düz yolda park edilebilir.',
      'İşaretli park cebi park için ayrılmıştır.',
      'Otopark, park için düzenlenmiş alandır.',
    ],
    objective: 'Park etmenin yasak olduğu yerleri tanımak.',
    tags: ['park-yasagi', 'kavsak', 'yaya-gecidi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-223',
    subject: 'trafik',
    topic: 'duraklama-park',
    difficulty: 'zor',
    stem: 'Eğimli bir yolda park eden sürücünün, aracın kaymasını önlemek için yapması gereken en doğru davranış hangisidir?',
    options: [
      'El frenini çekmeden bırakmak',
      'El frenini çekip aracı uygun vitese takmak',
      'Yalnızca farları açık bırakmak',
      'Sadece kapıları kilitlemek',
    ],
    answerIndex: 1,
    explanation:
      'Eğimli yolda park ederken el freni çekilir ve araç uygun vitese takılır (yokuş yukarı ileri, yokuş aşağı geri); ayrıca tekerlekler bordüre çevrilerek kayma önlenir.',
    whyWrong: [
      'El freni çekilmezse araç eğimde kayabilir.',
      'Sadece far açık bırakmak aracı sabitlemez.',
      'Kapı kilitlemek kaymayı engellemez.',
    ],
    objective: 'Eğimli yolda güvenli park önlemlerini bilmek.',
    tags: ['egimli-park', 'el-freni', 'guvenli-surus'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-224',
    subject: 'trafik',
    topic: 'yaya',
    difficulty: 'kolay',
    stem: 'Yaya geçidine yaklaşan sürücü, geçitten geçmek üzere olan yaya için ne yapmalıdır?',
    options: [
      'Korna çalıp yayayı bekletir',
      'Hızlanıp yayadan önce geçer',
      'Yayayı sollar',
      'Yavaşlar ve gerekirse durarak yayaya yol verir',
    ],
    answerIndex: 3,
    explanation:
      'Yaya geçidinde öncelik yayanındır; sürücü yavaşlar ve gerekirse durarak yayanın güvenle geçmesini sağlar.',
    whyWrong: [
      'Korna çalıp yayayı bekletmek önceliği ihlal eder.',
      'Yayadan önce geçmeye çalışmak tehlikelidir.',
      'Geçitteki yayayı sollamak ağır bir kusurdur.',
    ],
    objective: 'Yaya geçidinde yaya önceliğini uygulamak.',
    tags: ['yaya-gecidi', 'yaya-onceligi', 'yol-verme'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-225',
    subject: 'trafik',
    topic: 'yaya',
    difficulty: 'kolay',
    stem: 'Görevlinin bulunduğu bir okul geçidinde, görevli dur işareti verdiğinde sürücü ne yapmalıdır?',
    options: [
      'Yavaşlayıp geçer',
      'Korna çalarak uyarır',
      'Durup görevlinin ve öğrencilerin geçişini bekler',
      'Şerit değiştirip devam eder',
    ],
    answerIndex: 2,
    explanation:
      'Okul geçidi görevlisinin işareti bağlayıcıdır; sürücü durup öğrencilerin güvenle karşıya geçmesini bekler.',
    whyWrong: [
      'Yavaşlayıp geçmek görevlinin dur işaretine aykırıdır.',
      'Korna çalmak durma zorunluluğunu kaldırmaz.',
      'Şerit değiştirip devam etmek çocukları tehlikeye atar.',
    ],
    objective: 'Okul geçidi görevlisinin işaretine uymayı bilmek.',
    tags: ['okul-gecidi', 'yaya-guvenligi', 'gorevli-isareti'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-226',
    subject: 'trafik',
    topic: 'yaya',
    difficulty: 'orta',
    stem: 'Yaya geçidine çok yakın bir yerde sürücünün yapması yasak olan davranış hangisidir?',
    options: [
      'Yavaşlamak',
      'Duraklamak ve sollama yapmak',
      'Yayaya yol vermek',
      'Gerektiğinde durmak',
    ],
    answerIndex: 1,
    explanation:
      'Yaya geçidine yaklaşırken ve geçit üzerinde duraklamak ile sollama yapmak yasaktır; bu davranışlar yayanın görüşünü ve güvenliğini tehlikeye atar.',
    whyWrong: [
      'Yavaşlamak beklenen güvenli davranıştır.',
      'Yayaya yol vermek zaten zorunludur.',
      'Yaya için durmak doğru davranıştır.',
    ],
    objective: 'Yaya geçidi yakınında yasak davranışları bilmek.',
    tags: ['yaya-gecidi', 'sollama-yasagi', 'duraklama-yasagi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-227',
    subject: 'trafik',
    topic: 'cevre',
    difficulty: 'kolay',
    stem: 'Yakıt tüketimini ve egzoz kirliliğini azaltmak için aşağıdakilerden hangisi doğrudur?',
    options: [
      'Ani hızlanma ve sert frenlerden kaçınmak',
      'Sürekli yüksek devirde gitmek',
      'Lastikleri düşük basınçta kullanmak',
      'Motoru sürekli rölantide bekletmek',
    ],
    answerIndex: 0,
    explanation:
      'Yumuşak hızlanma, uygun vites ve düzenli seyir yakıt tüketimini ve egzoz salımını azaltır; bu hem ekonomik hem çevreci sürüştür.',
    whyWrong: [
      'Sürekli yüksek devir yakıt tüketimini artırır.',
      'Düşük lastik basıncı tüketimi ve aşınmayı artırır.',
      'Gereksiz rölanti boşuna yakıt harcar ve kirlilik yaratır.',
    ],
    objective: 'Çevreci ve ekonomik sürüş ilkelerini bilmek.',
    tags: ['cevre', 'yakit-tasarrufu', 'ekonomik-surus'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-228',
    subject: 'trafik',
    topic: 'cevre',
    difficulty: 'kolay',
    stem: 'Gereksiz yere ve sürekli korna çalmak hangi çevre sorununa yol açar?',
    options: ['Hava kirliliğine', 'Su kirliliğine', 'Toprak kirliliğine', 'Gürültü kirliliğine'],
    answerIndex: 3,
    explanation:
      'Yersiz ve sürekli korna kullanımı gürültü kirliliği oluşturur; korna yalnızca tehlikeyi önlemek amacıyla kullanılmalıdır.',
    whyWrong: [
      'Korna sesi hava kirliliği yaratmaz.',
      'Su kirliliğiyle ilgisi yoktur.',
      'Toprak kirliliğine neden olmaz.',
    ],
    objective: 'Korna kullanımının gürültü kirliliği etkisini bilmek.',
    tags: ['cevre', 'gurultu-kirliligi', 'korna'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-229',
    subject: 'trafik',
    topic: 'cevre',
    difficulty: 'orta',
    stem: 'Trafikte beklerken motoru uzun süre rölantide (boşta) çalışır tutmak neye neden olur?',
    options: [
      'Yakıt tasarrufuna',
      'Motorun daha çabuk soğumasına',
      'Gereksiz yakıt tüketimi ve egzoz emisyonuna',
      'Daha temiz bir havaya',
    ],
    answerIndex: 2,
    explanation:
      'Uzun süreli rölanti gereksiz yakıt harcar ve egzoz emisyonuyla havayı kirletir; uzun beklemelerde motorun durdurulması daha doğrudur.',
    whyWrong: [
      'Rölantide bekletmek tasarruf sağlamaz.',
      'Motorun soğumasını hızlandırmaz.',
      'Havayı temizlemez, tam tersine kirletir.',
    ],
    objective: 'Gereksiz rölantinin çevresel etkisini kavramak.',
    tags: ['cevre', 'rolanti', 'emisyon'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-230',
    subject: 'trafik',
    topic: 'far-isik',
    difficulty: 'orta',
    stem: 'Gece yerleşim yeri dışında karşıdan araç gelirken sürücü farlarını nasıl kullanmalıdır?',
    options: [
      'Uzun (uzağı gösteren) farı açık tutar',
      'Uzun farı kapatıp kısa (yakın) farı kullanır',
      'Tüm farları söndürür',
      'Yalnızca dörtlü flaşörü yakar',
    ],
    answerIndex: 1,
    explanation:
      'Karşıdan araç geldiğinde uzun far kapatılıp kısa far kullanılır; böylece karşı sürücünün gözü kamaşmaz ve iki taraf da güvenle görür.',
    whyWrong: [
      'Uzun farı açık tutmak karşı sürücünün gözünü alır.',
      'Tüm farları söndürmek görüşü tamamen keser.',
      'Sadece flaşör yakmak yolu aydınlatmaz.',
    ],
    objective: 'Gece karşılaşmalarda far kullanımını bilmek.',
    tags: ['far-kullanimi', 'gece-surus', 'uzun-far'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-231',
    subject: 'trafik',
    topic: 'far-isik',
    difficulty: 'orta',
    stem: 'Sis farları hangi durumda kullanılmalıdır?',
    options: [
      'Her zaman şehir içinde',
      'Güneşli ve açık havada',
      'Gece açık yolda sürekli',
      'Yalnızca sis, yoğun yağmur ya da kar gibi görüşün azaldığı hâllerde',
    ],
    answerIndex: 3,
    explanation:
      'Sis farları yalnızca sis, yoğun yağış veya kar gibi görüşün belirgin azaldığı durumlarda kullanılır; açık havada kullanmak diğer sürücüleri rahatsız eder.',
    whyWrong: [
      'Şehir içinde sürekli sis farı gereksizdir.',
      'Güneşli havada sis farına ihtiyaç yoktur.',
      'Açık yolda sürekli sis farı yanlış kullanımdır.',
    ],
    objective: 'Sis farlarının doğru kullanım koşulunu bilmek.',
    tags: ['sis-fari', 'gorus-mesafesi', 'far-kullanimi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-232',
    subject: 'trafik',
    topic: 'emniyet-kemeri',
    difficulty: 'kolay',
    stem: 'Emniyet kemeri kullanımı ile ilgili aşağıdakilerden hangisi doğrudur?',
    options: [
      'Ön ve arka koltuktaki herkes için zorunludur',
      'Yalnızca sürücünün takması yeterlidir',
      'Yalnızca şehir dışında zorunludur',
      'Kısa mesafelerde gerekmez',
    ],
    answerIndex: 0,
    explanation:
      'Emniyet kemeri sürücü dâhil ön ve arka koltuktaki tüm yolcular için zorunludur; kaza anında yaralanma ve ölüm riskini belirgin azaltır.',
    whyWrong: [
      'Kemer yalnızca sürücüyle sınırlı değildir.',
      'Şehir içi-dışı ayrımı olmadan her yerde zorunludur.',
      'Kısa mesafede de kaza riski vardır, kemer gereklidir.',
    ],
    objective: 'Emniyet kemerinin kapsamını ve zorunluluğunu bilmek.',
    tags: ['emniyet-kemeri', 'zorunluluk', 'guvenli-surus'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-233',
    subject: 'trafik',
    topic: 'emniyet-kemeri',
    difficulty: 'zor',
    stem: 'Belirli boy ve ağırlığın altındaki çocuklar araçta nasıl taşınmalıdır?',
    options: [
      'Sürücünün kucağında',
      'Arka koltukta kemersiz',
      'Yaşına ve kilosuna uygun çocuk güvenlik koltuğunda',
      'Ön koltukta serbestçe',
    ],
    answerIndex: 2,
    explanation:
      'Belirli boy ve ağırlığın altındaki çocuklar yaşına ve kilosuna uygun çocuk güvenlik koltuğu/sistemi ile taşınmalıdır; yetişkin kemeri onlara tam uymaz.',
    whyWrong: [
      'Çocuğu kucakta taşımak kaza anında çok tehlikelidir.',
      'Kemersiz taşımak yasak ve risklidir.',
      'Ön koltukta serbestçe taşımak uygun değildir.',
    ],
    objective: 'Çocuk güvenlik koltuğu gerekliliğini bilmek.',
    tags: ['cocuk-koltugu', 'emniyet-kemeri', 'cocuk-guvenligi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-234',
    subject: 'trafik',
    topic: 'donusler',
    difficulty: 'orta',
    stem: 'Kavşakta sola dönecek olan sürücü, dönüşten önce hangi şeride yaklaşmalıdır?',
    options: [
      'Yolun en sağ şeridine',
      'Gidiş yönüne göre yolun soluna (ortaya yakın şeride)',
      'Karşı yönün şeridine',
      'Yol kenarındaki bankete',
    ],
    answerIndex: 1,
    explanation:
      'Sola dönüşte sürücü önceden gidiş yönüne göre yolun soluna yaklaşır ve dönüşü uygun şeritten yaparak diğer trafiği engellemez.',
    whyWrong: [
      'En sağ şerit sağa dönüş içindir.',
      'Karşı yönün şeridine geçmek yasak ve tehlikelidir.',
      'Banket dönüş şeridi değildir.',
    ],
    objective: 'Sola dönüşte doğru şerit yaklaşımını bilmek.',
    tags: ['sola-donus', 'serit-secimi', 'kavsak'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-235',
    subject: 'trafik',
    topic: 'donusler',
    difficulty: 'kolay',
    stem: 'Sağa ya da sola dönmeden önce sürücünün yapması gereken nedir?',
    options: [
      'Kornaya basmak',
      'Farları söndürmek',
      'Hızlanmak',
      'Dönüş sinyalini vererek niyetini önceden bildirmek',
    ],
    answerIndex: 3,
    explanation:
      'Dönüşten önce sürücü uygun dönüş sinyalini vererek niyetini diğer sürücü ve yayalara zamanında bildirir, ardından güvenle döner.',
    whyWrong: [
      'Korna dönüş niyetini bildirmez.',
      'Far söndürmek dönüş işareti değildir.',
      'Dönüşten önce hızlanmak tehlikelidir.',
    ],
    objective: 'Dönüş öncesi sinyal verme kuralını bilmek.',
    tags: ['donus-sinyali', 'donusler', 'niyet-bildirme'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-236',
    subject: 'trafik',
    topic: 'otoyol',
    difficulty: 'orta',
    stem: 'Otoyola katılan bir sürücü hızlanma şeridini nasıl kullanmalıdır?',
    options: [
      'Hızını akan trafiğe uydurup uygun aralıkta katılarak',
      'Yavaşlayıp durarak',
      'Aniden ana şeride geçerek',
      'Emniyet şeridinden ilerleyerek',
    ],
    answerIndex: 0,
    explanation:
      'Hızlanma şeridinde araç, otoyol trafiğinin hızına ulaşana kadar hızlanır ve akan trafikte uygun bir boşluk bulup güvenle katılır.',
    whyWrong: [
      'Hızlanma şeridinde durmak arkadan çarpışmaya yol açar.',
      'Trafik hızına uymadan aniden geçmek tehlikelidir.',
      'Emniyet şeridi katılım için kullanılmaz.',
    ],
    objective: 'Otoyola hızlanma şeridiyle güvenli katılmayı bilmek.',
    tags: ['otoyol', 'hizlanma-seridi', 'katilma'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-237',
    subject: 'trafik',
    topic: 'otoyol',
    difficulty: 'orta',
    stem: 'Otoyoldaki emniyet şeridi (banket) hangi amaçla kullanılır?',
    options: [
      'Normal seyir ve sollama için',
      'Hızlı gitmek isteyenlerin geçişi için',
      'Yalnızca arıza veya kaza gibi zorunlu hâllerde durmak için',
      'Uzun molalarda park etmek için',
    ],
    answerIndex: 2,
    explanation:
      'Emniyet şeridi yalnızca arıza, kaza ya da acil durum gibi zorunlu hâllerde durmak için kullanılır; normal seyir ve sollama için kullanılamaz.',
    whyWrong: [
      'Emniyet şeridinde seyir ve sollama yasaktır.',
      'Hızlı geçiş için kullanmak tehlikeli ve kural dışıdır.',
      'Keyfî park/mola yeri değildir.',
    ],
    objective: 'Emniyet şeridinin amacını bilmek.',
    tags: ['otoyol', 'emniyet-seridi', 'zorunlu-durma'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-238',
    subject: 'trafik',
    topic: 'otoyol',
    difficulty: 'kolay',
    stem: 'Aşağıdakilerden hangisi otoyola giremez?',
    options: ['Otomobiller', 'Yayalar, traktörler ve motorsuz araçlar', 'Otobüsler', 'Kamyonlar'],
    answerIndex: 1,
    explanation:
      'Otoyollara yayalar, motorsuz araçlar, traktör ve iş makineleri gibi düşük hızlı unsurlar giremez; bu yollar hızlı motorlu taşıt trafiği içindir.',
    whyWrong: [
      'Otomobiller otoyol trafiğinin doğal parçasıdır.',
      'Otobüsler otoyola girebilir.',
      'Kamyonlar da otoyolu kullanabilir.',
    ],
    objective: 'Otoyola giremeyen yol kullanıcılarını bilmek.',
    tags: ['otoyol', 'giris-yasagi', 'yaya'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-239',
    subject: 'trafik',
    topic: 'alkol',
    difficulty: 'orta',
    stem: 'Taksi, otobüs, kamyon gibi ticari araç veya kamu hizmeti aracı sürücüleri için kandaki yasal alkol sınırı nedir?',
    options: [
      '0.00 promil; hiç alkollü araç kullanamazlar',
      '0.20 promil',
      '0.50 promil',
      '1.00 promil',
    ],
    answerIndex: 0,
    explanation:
      'Ticari araç ve kamu hizmeti aracı sürücüleri alkollü olarak hiç araç kullanamaz; bu sürücüler için yasal sınır 0.00 promildir.',
    whyWrong: [
      '0.50 promil yalnızca hususi otomobil sürücülerine tanınan sınırdır.',
      '0.20 ve 1.00 promil mevzuatta bu sürücüler için tanımlı değerler değildir.',
    ],
    objective:
      'Ticari/kamu hizmeti aracı sürücüleri için alkol sınırının 0.00 promil olduğunu bilmek.',
    tags: ['alkol', 'promil', 'ticari-arac'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-240',
    subject: 'trafik',
    topic: 'alkol',
    difficulty: 'zor',
    stem: 'Ticari araç (taksi, minibüs, otobüs, kamyon) kullanan sürücüler için yasal alkol sınırı nedir?',
    options: [
      '0.50 promil',
      '0.80 promil',
      '0.00 promil (alkollü araç kullanamazlar)',
      '1.00 promil',
    ],
    answerIndex: 2,
    explanation:
      'Ticari araç sürücüleri için sınır 0.00 promildir; yani bu sürücüler herhangi bir düzeyde alkollüyken araç kullanamaz.',
    whyWrong: [
      '0.50 promil hususi otomobil sürücüsü içindir.',
      '0.80 ve 1.00 promil hiçbir sürücü sınıfı için yasal değildir.',
    ],
    objective: 'Ticari araçta sıfır alkol sınırını bilmek.',
    tags: ['alkol', 'promil', 'ticari-arac'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-241',
    subject: 'trafik',
    topic: 'hemzemin',
    difficulty: 'kolay',
    stem: 'Kollu (bariyerli) bir hemzemin geçitte bariyer kapalıyken sürücü ne yapmalıdır?',
    options: [
      'Bariyer açılana kadar durup bekler',
      'Bariyerin altından hızla geçer',
      'Kornaya basıp geçer',
      'Bariyeri kendisi kaldırır',
    ],
    answerIndex: 0,
    explanation:
      'Hemzemin geçitte bariyer kapalı (inik) veya ışık/ses uyarısı devredeyse sürücü durur; bariyer tümüyle açılıp yol güvenli olmadan geçmez.',
    whyWrong: [
      'Bariyerin altından geçmek çok ölümcül bir kuraldışıdır.',
      'Korna çalmak geçiş hakkı vermez.',
      'Bariyeri kaldırmak sürücünün yetkisinde değildir.',
    ],
    objective: 'Bariyerli hemzemin geçitte doğru davranışı bilmek.',
    tags: ['hemzemin-gecit', 'bariyer', 'demiryolu'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-242',
    subject: 'trafik',
    topic: 'hemzemin',
    difficulty: 'orta',
    stem: 'Bariyeri ve ışıklı uyarısı bulunmayan bir hemzemin geçide gelen sürücü nasıl davranmalıdır?',
    options: [
      'Hızını artırıp hemen geçer',
      'Durup sağa-sola bakarak tren gelmediğinden emin olduktan sonra geçer',
      'Hiç yavaşlamadan geçer',
      'Geçidin üzerinde bekler',
    ],
    answerIndex: 1,
    explanation:
      'Kontrolsüz (bariyersiz) hemzemin geçitte sürücü durup her iki yönü kontrol eder; tren gelmediğinden emin olunca geçidi hızla ve durmadan geçer.',
    whyWrong: [
      'Kontrol etmeden hızla geçmek ölümcül risktir.',
      'Yavaşlamadan geçmek treni fark etme şansı bırakmaz.',
      'Geçidin üzerinde beklemek son derece tehlikelidir.',
    ],
    objective: 'Kontrolsüz hemzemin geçitte dur-bak-geç davranışını bilmek.',
    tags: ['hemzemin-gecit', 'kontrolsuz-gecit', 'demiryolu'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-243',
    subject: 'trafik',
    topic: 'tunel',
    difficulty: 'kolay',
    stem: 'Tünele giren sürücü farlarını nasıl kullanmalıdır?',
    options: [
      'Tüm farlarını söndürür',
      'Yalnızca sis farını yakar',
      'Uzun farı sürekli açık tutar',
      'Kısa (yakın) farlarını yakar',
    ],
    answerIndex: 3,
    explanation:
      'Tünel içinde görüşü artırmak için kısa (yakın) farlar yakılır; böylece sürücü hem görür hem de diğer araçlarca görülür.',
    whyWrong: [
      'Farları söndürmek tünelde görüşü tehlikeli biçimde azaltır.',
      'Yalnızca sis farı normal koşulda yeterli aydınlatma sağlamaz.',
      'Uzun far diğer sürücülerin gözünü kamaştırabilir.',
    ],
    objective: 'Tünelde far kullanımını bilmek.',
    tags: ['tunel', 'far-kullanimi', 'gorunurluk'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-244',
    subject: 'trafik',
    topic: 'tunel',
    difficulty: 'orta',
    stem: 'Tünel içinde sürücü için aşağıdakilerden hangisi yasaktır?',
    options: [
      'Şeridinde düzgün ilerlemek',
      'Farlarını yakmak',
      'Durmak, geri gitmek ve U dönüşü yapmak',
      'Takip mesafesini korumak',
    ],
    answerIndex: 2,
    explanation:
      'Tünelde durmak, geri gitmek ve U dönüşü yapmak yasaktır; bu manevralar kapalı alanda çok tehlikeli çarpışmalara yol açabilir.',
    whyWrong: [
      'Şeritte düzgün ilerlemek doğru davranıştır.',
      'Farları yakmak tünelde zorunludur.',
      'Takip mesafesini korumak güvenlik gereğidir.',
    ],
    objective: 'Tünelde yasak manevraları bilmek.',
    tags: ['tunel', 'durma-yasagi', 'geri-gitme'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-245',
    subject: 'trafik',
    topic: 'kavsak',
    difficulty: 'zor',
    stem: 'Işıklı kavşakta ışık yeşile döndüğü hâlde kavşak içi araçlarla dolu ise sürücü ne yapmalıdır?',
    options: [
      'Kavşak boşalıp karşıya geçebileceğinden emin olana kadar girmez',
      'Işık yeşil olduğu için hemen girer',
      'Korna çalarak öndeki araçları zorlar',
      'Emniyet şeridinden dolaşarak geçer',
    ],
    answerIndex: 0,
    explanation:
      'Işık yeşil olsa bile kavşak dolu ve karşıya geçilemeyecekse sürücü girmez; aksi hâlde kavşak kilitlenir ve trafik tümüyle tıkanır.',
    whyWrong: [
      'Yeşil ışık, kavşağı kilitleyecek şekilde girme hakkı vermez.',
      'Korna çalıp zorlamak tıkanıklığı çözmez.',
      'Emniyet şeridinden dolaşmak kural dışıdır.',
    ],
    objective: 'Kavşağı kilitlememe (bloke etmeme) kuralını bilmek.',
    tags: ['kavsak', 'kavsak-kilitleme', 'isikli-kavsak'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-246',
    subject: 'trafik',
    topic: 'kavsak',
    difficulty: 'orta',
    stem: 'Kavşağa yaklaşan ve dönüş yapacak sürücünün doğru davranışı hangisidir?',
    options: [
      'Kavşağa son anda şerit değiştirerek girmek',
      'Önceden uygun şeride geçip hızını azaltmak',
      'Kavşağın ortasında yön kararı vermek',
      'Hızlanarak kavşağa dalmak',
    ],
    answerIndex: 1,
    explanation:
      'Kavşağa yaklaşan sürücü dönüş yönüne uygun şeride önceden geçer ve hızını azaltarak güvenli, öngörülebilir bir dönüş yapar.',
    whyWrong: [
      'Son anda şerit değiştirmek diğer sürücüleri şaşırtır.',
      'Kavşak ortasında karar vermek kararsız ve tehlikelidir.',
      'Hızlanarak girmek kaza riskini artırır.',
    ],
    objective: 'Kavşağa dönüş öncesi hazırlık davranışını bilmek.',
    tags: ['kavsak', 'serit-secimi', 'donus'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-247',
    subject: 'trafik',
    topic: 'isik',
    difficulty: 'kolay',
    stem: 'Trafik ışığında sarı (amber) ışık yandığında sürücü ne yapmalıdır?',
    options: [
      'Serbestçe geçebilir',
      'Hızlanması gerekir',
      'Geri gitmelidir',
      'Dur çizgisinde güvenli şekilde durmaya hazırlanmalıdır',
    ],
    answerIndex: 3,
    explanation:
      'Sarı ışık, kırmızıya geçileceğini haber verir; sürücü güvenli biçimde durabilecekse dur çizgisinde durur ve durmaya hazırlanır.',
    whyWrong: [
      'Sarı ışık serbest geçiş anlamına gelmez.',
      'Sarıda hızlanmak tehlikeli bir davranıştır.',
      'Geri gitmek ışık anlamıyla ilgisizdir.',
    ],
    objective: 'Sarı ışığın anlamını bilmek.',
    tags: ['trafik-isigi', 'sari-isik', 'dur-cizgisi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-248',
    subject: 'trafik',
    topic: 'isik',
    difficulty: 'zor',
    stem: 'Yanıp sönen kırmızı ışık sürücüye ne bildirir?',
    options: [
      'Serbestçe geçebilirsin',
      'Işığın arızalı olduğunu, dikkate almamanı',
      'Durup yol açık olduğunda dikkatle geçmeni',
      'Yalnızca biraz yavaşlamanı',
    ],
    answerIndex: 2,
    explanation:
      'Yanıp sönen kırmızı ışık DUR levhası gibi işlev görür; sürücü durup yolun güvenli olduğunu görünce dikkatle geçer.',
    whyWrong: [
      'Serbest geçiş anlamına gelmez.',
      'İşaret arızalı değildir, geçerli bir uyarıdır.',
      'Sadece yavaşlamak yeterli değildir, durmak gerekir.',
    ],
    objective: 'Yanıp sönen kırmızı ışığın anlamını bilmek.',
    tags: ['trafik-isigi', 'yanip-sonen-kirmizi', 'durma'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-249',
    subject: 'trafik',
    topic: 'gece',
    difficulty: 'orta',
    stem: 'Gece araç kullanırken görüş mesafesi kısaldığında sürücü ne yapmalıdır?',
    options: [
      'Hızını azaltıp farların aydınlattığı mesafede durabilecek şekilde sürmeli',
      'Hızını artırmalı',
      'Farlarını söndürmeli',
      'Takip mesafesini kısaltmalı',
    ],
    answerIndex: 0,
    explanation:
      'Gece görüş sınırlı olduğundan sürücü hızını, farların aydınlattığı mesafe içinde güvenle durabilecek şekilde ayarlamalıdır.',
    whyWrong: [
      'Hızı artırmak fren mesafesini görüş sınırının ötesine taşır.',
      'Farları söndürmek görüşü tamamen ortadan kaldırır.',
      'Takip mesafesini kısaltmak çarpışma riskini artırır.',
    ],
    objective: 'Gece görüşe uygun hız ayarını bilmek.',
    tags: ['gece-surus', 'gorus-mesafesi', 'hiz-uyarlama'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-250',
    subject: 'trafik',
    topic: 'gece',
    difficulty: 'orta',
    stem: 'Gece yeterince aydınlatılmış yerleşim yeri içinde sürücü hangi farı kullanmalıdır?',
    options: [
      'Uzun (uzağı gösteren) farı',
      'Kısa (yakın) farı',
      'Sürekli sis farını',
      'Hiç far kullanmadan',
    ],
    answerIndex: 1,
    explanation:
      'Aydınlatılmış yerleşim yeri içinde kısa (yakın) far kullanılır; uzun far diğer sürücülerin ve yayaların gözünü kamaştırır.',
    whyWrong: [
      'Uzun far şehir içinde göz kamaştırdığı için yasaktır.',
      'Sürekli sis farı görüş iyiyken gereksizdir.',
      'Gece farsız sürmek yasak ve tehlikelidir.',
    ],
    objective: 'Şehir içi gece far kullanımını bilmek.',
    tags: ['gece-surus', 'kisa-far', 'yerlesim-ici'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-251',
    subject: 'trafik',
    topic: 'kis-lastik',
    difficulty: 'kolay',
    stem: 'Kış lastiğinin kar ve buzlu zeminde sağladığı temel fayda nedir?',
    options: [
      'Yalnızca yakıt tüketimini azaltır',
      'Motor gücünü artırır',
      'Farların parlaklığını artırır',
      'Kar ve buzda yol tutuşunu ve frenlemeyi iyileştirir',
    ],
    answerIndex: 3,
    explanation:
      'Kış lastiği özel hamuru ve diş yapısıyla soğukta esnek kalır; kar ve buzda yol tutuşunu ve frenleme performansını belirgin artırır.',
    whyWrong: [
      'Temel amacı yakıt tasarrufu değildir.',
      'Motor gücüyle doğrudan ilgisi yoktur.',
      'Farların parlaklığını etkilemez.',
    ],
    objective: 'Kış lastiğinin işlevini bilmek.',
    tags: ['kis-lastigi', 'yol-tutusu', 'kar-buz'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-252',
    subject: 'trafik',
    topic: 'kis-lastik',
    difficulty: 'zor',
    stem: 'Ticari araçlarda kış lastiği kullanımı ülkemizde genellikle hangi dönemde zorunludur?',
    options: [
      'Tüm yıl boyunca',
      'Yalnızca yaz aylarında',
      'Yaklaşık 1 Aralık ile 1 Nisan arasındaki kış döneminde',
      'Hiçbir zaman zorunlu değildir',
    ],
    answerIndex: 2,
    explanation:
      'Yük ve yolcu taşıyan ticari araçlarda kış lastiği zorunluluğu ülkemizde genellikle yaklaşık 1 Aralık ile 1 Nisan arasındaki kış aylarını kapsar.',
    whyWrong: [
      'Zorunluluk tüm yılı kapsamaz.',
      'Yaz ayları kış lastiği dönemine karşılık gelmez.',
      'Ticari araçlar için hiç zorunlu olmaması yanlıştır.',
    ],
    objective: 'Kış lastiği zorunluluk dönemini bilmek.',
    tags: ['kis-lastigi', 'zorunluluk', 'ticari-arac'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-253',
    subject: 'trafik',
    topic: 'yorgunluk',
    difficulty: 'kolay',
    stem: 'Uzun bir yolculukta yorgunluğu önlemek için sürücü ne yapmalıdır?',
    options: [
      'Belirli aralıklarla mola verip dinlenmeli',
      'Hiç durmadan yola devam etmeli',
      'Daha hızlı giderek yolu kısaltmalı',
      'Camları kapatıp sürüşe devam etmeli',
    ],
    answerIndex: 0,
    explanation:
      'Uzun yolda yorgunluğu ve dikkat kaybını önlemek için düzenli aralıklarla mola verilip dinlenilmelidir; yorgunluk tepki süresini uzatır.',
    whyWrong: [
      'Durmadan devam etmek yorgunluğu ve kaza riskini artırır.',
      'Hızlanmak yorgun sürücüde tehlikeyi büyütür.',
      'Camları kapatmak yorgunluğu gidermez.',
    ],
    objective: 'Uzun yolda mola vererek yorgunluğu önlemeyi bilmek.',
    tags: ['yorgunluk', 'mola', 'guvenli-surus'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-254',
    subject: 'trafik',
    topic: 'yorgunluk',
    difficulty: 'zor',
    stem: 'Direksiyon başında uyku ve yorgunluk belirtileri hisseden sürücünün en doğru davranışı nedir?',
    options: [
      'Kahve içerek yola devam etmek',
      'Güvenli bir yerde durup dinlenmek ya da uyumak',
      'Camı açıp hızlanarak uyanık kalmak',
      'Radyonun sesini açıp sürmeyi sürdürmek',
    ],
    answerIndex: 1,
    explanation:
      'Uyku hâli sürüşü ölümcül biçimde tehlikeye atar; en güvenli çözüm güvenli bir yerde durup kısa bir dinlenme ya da uyku ile toparlanmaktır.',
    whyWrong: [
      'Kahve geçici etki yapar, uykuyu tam gidermez.',
      'Hızlanmak uykulu sürücüde riski büyütür.',
      'Radyo sesi uyanık kalmayı garanti etmez.',
    ],
    objective: 'Uyku hâlinde durup dinlenmenin önemini kavramak.',
    tags: ['yorgunluk', 'uyku-hali', 'guvenli-surus'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-255',
    subject: 'trafik',
    topic: 'kaza',
    difficulty: 'orta',
    stem: 'Trafik kazasına karışan veya arızalanan bir sürücünün, diğer sürücüleri uyarmak için ilk yapması gereken nedir?',
    options: [
      'Aracı olduğu yerde bırakıp uzaklaşmak',
      'Hemen aracı çalıştırıp yola devam etmek',
      'Sadece kornaya basmak',
      'Dörtlü flaşörü yakıp uygun mesafeye reflektör (üçgen) yerleştirmek',
    ],
    answerIndex: 3,
    explanation:
      'Kaza veya arızada önce dörtlü flaşör yakılır ve aracın gerisine görülebilecek uygun mesafeye reflektör (üçgen) konarak diğer sürücüler uyarılır.',
    whyWrong: [
      'Aracı bırakıp uzaklaşmak ikincil kazalara yol açabilir.',
      'Arızalı aracı sürmek tehlikeli olabilir.',
      'Sadece korna kalıcı bir uyarı sağlamaz.',
    ],
    objective: 'Kaza/arıza sonrası uyarı önlemlerini bilmek.',
    tags: ['kaza', 'reflektor', 'dortlu-flasor'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-256',
    subject: 'trafik',
    topic: 'kaza',
    difficulty: 'kolay',
    stem: 'Yaralının bulunduğu bir trafik kazasında olay yerinden yapılması gereken ilk çağrı nereye olmalıdır?',
    options: ['En yakın tamirciye', 'Sigorta acentesine', '112 Acil Çağrı hattına', 'Bir yakınına'],
    answerIndex: 2,
    explanation:
      'Yaralılı kazada zaman kritik olduğundan ilk olarak 112 Acil Çağrı hattı aranarak konum ve durum bildirilir, ambulans yönlendirilir.',
    whyWrong: [
      'Tamirci yaralıya müdahale edemez.',
      'Sigorta işlemleri sağlık müdahalesinden sonra gelir.',
      'Önce resmi acil hat aranmalıdır.',
    ],
    objective: 'Yaralılı kazada 112 çağrısının önceliğini bilmek.',
    tags: ['kaza', 'acil-cagri', 'ilk-yardim'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-257',
    subject: 'trafik',
    topic: 'sigorta',
    difficulty: 'orta',
    stem: 'Zorunlu Trafik Sigortası (Zorunlu Mali Sorumluluk Sigortası) neyi karşılar?',
    options: [
      'Kazada karşı tarafa (üçüncü kişilere) verilen zararları',
      'Sürücünün kendi aracının hasarını',
      'Aracın çalınmasını',
      'Motorun arızasını',
    ],
    answerIndex: 0,
    explanation:
      'Zorunlu Trafik Sigortası, aracın karıştığı kazada karşı tarafa (üçüncü kişilere) verilen bedeni ve maddi zararları karşılar; yasal olarak zorunludur.',
    whyWrong: [
      'Sürücünün kendi aracının hasarını kasko karşılar.',
      'Çalınmayı zorunlu trafik sigortası kapsamaz.',
      'Motor arızası bu sigortanın kapsamı dışındadır.',
    ],
    objective: 'Zorunlu trafik sigortasının kapsamını bilmek.',
    tags: ['sigorta', 'zorunlu-trafik-sigortasi', 'ucuncu-sahis'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-258',
    subject: 'trafik',
    topic: 'sigorta',
    difficulty: 'zor',
    stem: 'Kasko sigortası ile Zorunlu Trafik Sigortası arasındaki temel fark hangisidir?',
    options: [
      'İkisi de kanunen zorunludur',
      'Kasko isteğe bağlıdır ve genellikle sürücünün kendi aracının zararını karşılar',
      'Kasko yalnızca karşı tarafı korur',
      'Aralarında hiçbir fark yoktur',
    ],
    answerIndex: 1,
    explanation:
      'Zorunlu trafik sigortası karşı tarafın zararını karşılar ve zorunludur; kasko ise isteğe bağlıdır ve genelde sürücünün kendi aracındaki hasarları güvence altına alır.',
    whyWrong: [
      'Kasko zorunlu değil, isteğe bağlıdır.',
      'Kasko esasen kendi aracı için düzenlenir, sadece karşı taraf için değil.',
      'İki sigorta türü kapsam ve zorunluluk yönünden farklıdır.',
    ],
    objective: 'Kasko ile zorunlu trafik sigortasını ayırt etmek.',
    tags: ['sigorta', 'kasko', 'zorunlu-trafik-sigortasi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-259',
    subject: 'trafik',
    topic: 'ceza-puan',
    difficulty: 'zor',
    stem: 'Ceza puanı belirli sınırı geçen sürücünün sürücü belgesi bakımından sonuç nedir?',
    options: [
      'Hiçbir işlem yapılmaz',
      'Sadece sözlü uyarı verilir',
      'Aracı trafikten men edilir',
      '100 ceza puanı dolduğunda sürücü belgesi belirli süre geri alınır',
    ],
    answerIndex: 3,
    explanation:
      'Bir yıl içinde toplam 100 ceza puanına ulaşan sürücünün sürücü belgesi belirli bir süre geri alınır; tekrarlarda süre uzar.',
    whyWrong: [
      'Puan sınırı aşıldığında işlem yapılmaması yanlıştır.',
      'Yaptırım yalnızca sözlü uyarıdan ibaret değildir.',
      'Sonuç belgeye yöneliktir; aracın men edilmesi ayrı bir konudur.',
    ],
    objective: '100 ceza puanı ve belge geri alma sonucunu bilmek.',
    tags: ['ceza-puani', 'surucu-belgesi', 'yaptirim'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-260',
    subject: 'trafik',
    topic: 'ceza-puan',
    difficulty: 'zor',
    stem: 'Trafik kurallarına aykırı davranışlarda uygulanan ceza puanı sisteminin amacı nedir?',
    options: [
      'Sürücüleri ödüllendirmek',
      'Araç satışını artırmak',
      'Kural ihlallerini kayıt altına alıp tekrarlayan sürücüleri caydırmak',
      'Yakıt fiyatını belirlemek',
    ],
    answerIndex: 2,
    explanation:
      'Ceza puanı sistemi, ihlalleri sürücü bazında kayıt altına alarak tekrarlayan kural ihlallerini caydırmayı ve trafik güvenliğini artırmayı amaçlar.',
    whyWrong: [
      'Sistem ödüllendirmeye değil caydırmaya yöneliktir.',
      'Araç satışı ile ilgisi yoktur.',
      'Yakıt fiyatını belirlemez.',
    ],
    objective: 'Ceza puanı sisteminin amacını kavramak.',
    tags: ['ceza-puani', 'trafik-guvenligi', 'caydiricilik'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
];
