/**
 * ÖZGÜN araç tekniği (motor) soruları — 5. genişletme (Program 2 · Faz 9). ROADMAP C.4/E.6.
 * Kaynak = MEB araç tekniği müfredatı; KENDİ İFADEMİZLE.
 */
import type { QuestionInput } from '@ea/content-schema';

const SRC = 'MEB araç tekniği müfredatı (özgün ifade)';

export const MOTOR_QUESTIONS_5: QuestionInput[] = [
  {
    id: 'motor-501',
    subject: 'motor',
    topic: 'calisma-zamanlari',
    difficulty: 'kolay',
    stem: 'Dört zamanlı bir motorda aracı hareket ettiren gücün üretildiği zaman aşağıdakilerden hangisidir?',
    options: ['Emme zamanı', 'Egzoz zamanı', 'İş (ateşleme-genişleme) zamanı', 'Sıkıştırma zamanı'],
    answerIndex: 2,
    explanation:
      'Sıkıştırılmış dolgu ateşlendiğinde genişleyen yanma gazları pistonu büyük bir kuvvetle aşağı iter; motorun güç ürettiği tek an bu iş zamanıdır. Diğer üç zaman bu ana hazırlık yapar veya silindiri temizler.',
    whyWrong: [
      'Emme zamanında silindir yalnızca taze dolguyla doldurulur; güç üretilmez.',
      'Sıkıştırma, yanmayı verimli kılmak için yapılan hazırlık aşamasıdır.',
      'Egzoz zamanı yanmış gazların atıldığı temizlik aşamasıdır.',
    ],
    objective: 'Dört zamanlı çevrimde gücün hangi zamanda üretildiğini bilmek.',
    tags: ['dort-zamanli', 'is-zamani', 'motor-calismasi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-502',
    subject: 'motor',
    topic: 'calisma-zamanlari',
    difficulty: 'orta',
    stem: 'Dört zamanlı benzinli bir motorun emme zamanında silindirin içinde ne gerçekleşir?',
    options: [
      'Emme supabı açılır; aşağı inen piston silindire taze hava-yakıt dolgusunu çeker',
      'Her iki supap kapanır ve dolgu sıkıştırılır',
      'Buji çakar ve yanma başlar',
      'Egzoz supabı açılır ve yanmış gazlar dışarı atılır',
    ],
    answerIndex: 0,
    explanation:
      'Emme zamanında piston yukarıdan aşağıya inerken emme supabı açıktır. Silindirde oluşan alçak basınç, taze dolgunun (hava ya da hava-yakıt karışımı) içeri dolmasını sağlar.',
    whyWrong: [
      'Supapların kapanıp dolgunun sıkıştırılması bir sonraki zamanda olur.',
      'Bujinin çakması sıkıştırma sonundaki iş zamanının başlangıcıdır.',
      'Yanmış gazların atılması egzoz zamanının görevidir.',
    ],
    objective: 'Emme zamanında piston ve supap davranışını kavramak.',
    tags: ['dort-zamanli', 'emme-zamani', 'supap'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-503',
    subject: 'motor',
    topic: 'calisma-zamanlari',
    difficulty: 'zor',
    stem: 'Sıkıştırma zamanıyla ilgili doğru ifade aşağıdakilerden hangisidir?',
    options: [
      'Emme supabı açık kalır, yalnızca egzoz supabı kapanır',
      'Piston aşağı inerken dolgu kendiliğinden genişler',
      'Bu zamanda yanmış gazlar dışarı atılır',
      'Her iki supap da kapalıdır; yukarı çıkan piston dolguyu küçük bir hacme sıkıştırarak verimli yanmaya hazırlar',
    ],
    answerIndex: 3,
    explanation:
      'Sıkıştırma zamanında emme ve egzoz supapları tamamen kapalıdır. Piston yukarı çıkarken dolgu küçük bir hacme sıkışır; basıncı ve sıcaklığı artan dolgu, ateşlendiğinde çok daha güçlü ve verimli yanar.',
    whyWrong: [
      'Supaplardan biri açık kalsaydı dolgu sıkışmadan geri kaçardı.',
      'Bu zamanda piston iner değil, çıkar; dolgu genişlemez, sıkışır.',
      'Yanmış gazların atılması egzoz zamanına aittir.',
    ],
    objective: 'Sıkıştırma zamanında supap konumlarını ve amacı kavramak.',
    tags: ['dort-zamanli', 'sikistirma', 'supap'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-504',
    subject: 'motor',
    topic: 'calisma-zamanlari',
    difficulty: 'kolay',
    stem: 'Dört zamanlı bir motorda egzoz zamanının görevi nedir?',
    options: [
      'Silindire taze hava almak',
      'Açılan egzoz supabından yanmış gazları dışarı atarak silindiri bir sonraki çevrime hazırlamak',
      'Yakıtı depodan motora pompalamak',
      'Motor yağını soğutmak',
    ],
    answerIndex: 1,
    explanation:
      'İş zamanı tamamlandığında egzoz supabı açılır; yukarı çıkan piston yanmış gazları egzoz sistemine süpürür. Silindir boşaltılır ve çevrim yeniden emme zamanıyla başlar.',
    whyWrong: [
      'Taze dolgu alma görevi emme zamanınındır.',
      'Yakıtı pompalamak yakıt pompasının, yağı soğutmak yağlama sisteminin işidir.',
    ],
    objective: 'Egzoz zamanının çevrimdeki temizlik görevini bilmek.',
    tags: ['dort-zamanli', 'egzoz-zamani', 'cevrim'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-505',
    subject: 'motor',
    topic: 'motor-parcalari',
    difficulty: 'kolay',
    stem: 'Pistonun motordaki temel görevi aşağıdakilerden hangisidir?',
    options: [
      'Soğutma suyunu motor içinde dolaştırmak',
      'Farlar için elektrik üretmek',
      'Silindir içinde inip çıkarak yanma basıncını biyel kolu üzerinden krank miline iletmek',
      'Egzoz gazlarındaki zararlı maddeleri temizlemek',
    ],
    answerIndex: 2,
    explanation:
      'Piston, silindir içinde gidip gelen hareketli parçadır. İş zamanında yanma gazlarının basıncını üzerine alır ve bu kuvveti biyel (piston kolu) aracılığıyla krank miline aktarır.',
    whyWrong: [
      'Suyu dolaştıran devirdaim pompası, elektrik üreten alternatördür.',
      'Egzoz gazlarını temizleme görevi katalitik konvertöre aittir.',
    ],
    objective: 'Pistonun kuvvet iletimindeki rolünü öğrenmek.',
    tags: ['piston', 'biyel', 'motor-parcalari'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-506',
    subject: 'motor',
    topic: 'motor-parcalari',
    difficulty: 'orta',
    stem: 'Krank milinin görevi aşağıdakilerden hangisidir?',
    options: [
      'Pistonlardan gelen doğrusal (inip kalkan) hareketi dönme hareketine çevirmek',
      'Yakıtı silindire püskürtmek',
      'Fren basıncını tekerleklere dağıtmak',
      'Kabine giren havayı süzmek',
    ],
    answerIndex: 0,
    explanation:
      'Pistonlar silindir içinde yalnızca inip kalkar; tekerlekleri döndürmek içinse dönme hareketi gerekir. Krank mili, biyellerden aldığı bu doğrusal hareketi dönme hareketine çevirir ve aktarma organlarına iletir.',
    whyWrong: [
      'Yakıt püskürtme enjektörün görevidir.',
      'Fren basıncını fren sistemi dağıtır; hava süzme işini filtreler yapar.',
    ],
    objective: 'Krank milinin hareket dönüştürme görevini kavramak.',
    tags: ['krank-mili', 'hareket-donusumu', 'motor-parcalari'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-507',
    subject: 'motor',
    topic: 'motor-parcalari',
    difficulty: 'orta',
    stem: 'Eksantrik (kam) milinin motordaki görevi nedir?',
    options: [
      'Aküyü şarj etmek',
      'Motor yağını süzmek',
      'Tekerlek balansını dengelemek',
      'Üzerindeki kamlar aracılığıyla emme ve egzoz supaplarını tam zamanında açıp kapatmak',
    ],
    answerIndex: 3,
    explanation:
      'Eksantrik mili, krank milinden triger düzeneğiyle aldığı hareketle döner. Üzerindeki çıkıntılar (kamlar) supaplara basarak her supabın çevrim içinde doğru anda açılıp kapanmasını sağlar.',
    whyWrong: [
      'Aküyü alternatör şarj eder.',
      'Yağı süzen yağ filtresidir; balans işi tekerlek tarafına aittir.',
    ],
    objective: 'Eksantrik milinin supap zamanlamasındaki rolünü öğrenmek.',
    tags: ['eksantrik-mili', 'supap', 'zamanlama'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-508',
    subject: 'motor',
    topic: 'motor-parcalari',
    difficulty: 'kolay',
    stem: 'Emme ve egzoz supaplarının görev ayrımı hangi seçenekte doğru verilmiştir?',
    options: [
      'Emme supabı yanmış gazı atar; egzoz supabı yakıt püskürtür',
      'Emme supabı taze dolgunun silindire girmesini, egzoz supabı yanmış gazların dışarı atılmasını sağlar',
      'Her iki supap da yalnızca yağlama görevi yapar',
      'Supaplar yalnızca dizel motorlarda bulunur',
    ],
    answerIndex: 1,
    explanation:
      'Supaplar silindirin giriş-çıkış kapılarıdır: emme supabı açıldığında taze dolgu içeri girer, egzoz supabı açıldığında yanmış gazlar dışarı atılır. Kapalıyken silindiri sızdırmaz biçimde mühürlerler.',
    whyWrong: [
      'İlk seçenekte görevler ters ve yanlış eşlenmiştir; yakıt püskürtmeyi enjektör yapar.',
      'Supapların görevi yağlama değildir ve hem benzinli hem dizel motorlarda bulunurlar.',
    ],
    objective: 'Emme ve egzoz supaplarının görevlerini ayırt etmek.',
    tags: ['supap', 'emme', 'egzoz'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-509',
    subject: 'motor',
    topic: 'yag-basinc-musuru',
    difficulty: 'orta',
    stem: 'Yağ basınç müşürünün görevi aşağıdakilerden hangisidir?',
    options: [
      'Motor yağını kanallara pompalamak',
      'Azalan yağı otomatik olarak tamamlamak',
      'Yağlama sistemindeki basıncı izleyip basınç tehlikeli düzeye düştüğünde gösterge panelindeki yağ ikaz lambasını yaktırmak',
      'Yağ filtresini temizlemek',
    ],
    answerIndex: 2,
    explanation:
      'Müşür, yağ kanalındaki basıncı algılayan küçük bir sensör/anahtardır. Basınç güvenli sınırın altına indiğinde elektrik devresini kapatarak paneldeki kırmızı yağdanlık lambasını yakar ve sürücüyü uyarır.',
    whyWrong: [
      'Yağı basınçla dolaştıran parça yağ pompasıdır; müşür yalnızca ölçer ve bildirir.',
      'Hiçbir parça eksilen yağı kendiliğinden tamamlamaz; seviye sürücü tarafından kontrol edilir.',
    ],
    objective: 'Müşürün ölçme-uyarma görevini pompayla karıştırmamak.',
    tags: ['yag-basinci', 'musur', 'ikaz-lambasi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-510',
    subject: 'motor',
    topic: 'yag-basinc-musuru',
    difficulty: 'zor',
    stem: 'Yağ seviyesi çubukla tam ölçülüyor ve motordan anormal ses gelmiyor; buna rağmen yağ ikaz lambası ara ara yanıp sönüyorsa hangi olasılık da değerlendirilmelidir?',
    options: [
      'Yağ basınç müşürünün veya kablosunun arızalanıp yanlış sinyal veriyor olabileceği; yine de gerçek basınç servise ölçtürülmeden sürüşe güvenilmemesi',
      'Yakıt deposunun boşalmak üzere olduğu',
      'Lastik basıncının yükseldiği',
      'Silecek suyunun bittiği',
    ],
    answerIndex: 0,
    explanation:
      'Yağ lambası müşürden gelen sinyalle yanar; eskiyen müşür veya oksitlenen kablo yanıltıcı ikaz üretebilir. Ancak yağ basıncı motor için hayati olduğundan bu ihtimale güvenip yola devam edilmez; basınç manometreyle ölçtürülür.',
    whyWrong: [
      'Yakıt seviyesinin kendi göstergesi vardır; yağ lambasını etkilemez.',
      'Lastik basıncı ve silecek suyu yağlama devresinden tamamen bağımsızdır.',
    ],
    objective:
      'Sensör kaynaklı yanlış ikaz olasılığını bilmek ama basınç uyarısını asla hafife almamak.',
    tags: ['musur', 'yanlis-ikaz', 'teshis'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-511',
    subject: 'motor',
    topic: 'termostat',
    difficulty: 'orta',
    stem: 'Termostat sürekli açık konumda takılı kalırsa araçta hangi durum gözlenir?',
    options: [
      'Motor birkaç dakika içinde aşırı ısınır',
      'Soğutma suyu baştan itibaren radyatöre gittiği için motor çalışma sıcaklığına çok geç ulaşır; yakıt tüketimi artar ve kalorifer geç ısıtır',
      'Fren pedalı sertleşir',
      'Direksiyon boşluğu artar',
    ],
    answerIndex: 1,
    explanation:
      'Termostatın görevi motor soğukken suyu radyatöre göndermeyip hızlı ısınmayı sağlamaktır. Açık sıkışan termostat suyu sürekli radyatörde soğuttuğundan motor uzun süre soğuk çalışır: tüketim yükselir, aşınma artar, kalorifer geç ısınır.',
    whyWrong: [
      'Aşırı ısınma, termostatın açık değil kapalı sıkışmasının sonucudur.',
      'Fren pedalı ve direksiyon boşluğunun soğutma sistemiyle ilgisi yoktur.',
    ],
    objective: 'Açık sıkışan termostatın geç ısınma sorununu kavramak.',
    tags: ['termostat', 'gec-isinma', 'yakit-tuketimi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-512',
    subject: 'motor',
    topic: 'termostat',
    difficulty: 'zor',
    stem: 'Termostat kapalı konumda sıkışırsa sonuç ne olur?',
    options: [
      'Motor hiçbir zaman çalışma sıcaklığına ulaşamaz',
      'Yalnızca klima devre dışı kalır',
      'Yakıt tüketimi belirgin şekilde azalır',
      'Soğutma suyu radyatöre ulaşamaz; ısı atılamadığı için motor kısa sürede hararet yapar',
    ],
    answerIndex: 3,
    explanation:
      'Termostat, su belirli sıcaklığa gelene kadar radyatör devresini kapalı tutan bir vanadır. Kapalı sıkışırsa ısınan su radyatörde soğutulamaz; sıcaklık hızla tırmanır, hararet ikazı yanar ve motor durdurulmazsa ciddi hasar oluşabilir.',
    whyWrong: [
      'Isınamama sorunu tam tersine, açık sıkışan termostatta görülür.',
      'Klima ve yakıt tüketimi bu arızanın tipik ilk sonuçları değildir; asıl tehlike hararettir.',
    ],
    objective: 'Kapalı sıkışan termostat ile hararet arasındaki ilişkiyi kurmak.',
    tags: ['termostat', 'hararet', 'sogutma-sistemi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-513',
    subject: 'motor',
    topic: 'devirdaim-pompasi',
    difficulty: 'orta',
    stem: 'Devirdaim (su) pompası görevini yapamadığında hangi belirti ikilisinin birlikte görülmesi beklenir?',
    options: [
      'Farların sararması ve korna sesinin zayıflaması',
      'Lastik basıncının düşmesi ve direksiyonun titremesi',
      'Motorun hararet yapması ve su dolaşımı durduğu için kaloriferin yeterince ısıtmaması',
      'Yakıt göstergesinin sıfırlanması ve marşın basmaması',
    ],
    answerIndex: 2,
    explanation:
      'Devirdaim pompası soğutma suyunu motor ile radyatör arasında dolaştırır. Pompa görev yapamazsa su durur: motor ısıyı atamayıp hararet yapar; kalorifer peteğine sıcak su gelmediği için kabin de ısınmaz.',
    whyWrong: [
      'Far, korna ve marş elektrik sisteminin; lastik ve direksiyon titremesi yürüyen aksamın konusudur.',
      'Yakıt göstergesi soğutma sisteminden bağımsız çalışır.',
    ],
    objective: 'Su pompası arızasını hararet + soğuk kalorifer ikilisinden tanımak.',
    tags: ['devirdaim', 'su-pompasi', 'hararet'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-514',
    subject: 'motor',
    topic: 'hararet-mudahale',
    difficulty: 'kolay',
    stem: 'Seyir hâlinde hararet yükselmeye başladığında kaloriferi en sıcak kademede sonuna kadar açmanın amacı nedir?',
    options: [
      'Kalorifer peteği motor ısısının bir kısmını kabine aktararak soğutma sistemine destek olur ve sıcaklığın tırmanmasını yavaşlatır',
      'Kalorifer açılınca yakıt tüketimi sıfırlanır',
      'Kalorifer açılınca motor kendiliğinden rölantiye düşer',
      'Yalnızca camların buzlanmasını önlemek içindir',
    ],
    answerIndex: 0,
    explanation:
      'Kalorifer peteği, içinden geçen sıcak soğutma suyunun ısısını kabine üfleyen küçük bir radyatör gibidir. Hararet anında kaloriferi sonuna kadar açmak sistemden ek ısı atılmasını sağlar ve güvenli bir yerde durana kadar zaman kazandırır.',
    whyWrong: [
      'Kaloriferin yakıt tüketimini sıfırlama veya motoru rölantiye düşürme gibi bir etkisi yoktur.',
      'Buz çözme ayrı bir kullanım amacıdır; buradaki amaç motoru rahatlatmaktır.',
    ],
    objective: 'Hararet anında kaloriferin acil soğutma desteği olarak kullanılabileceğini bilmek.',
    tags: ['hararet', 'kalorifer', 'acil-mudahale'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-515',
    subject: 'motor',
    topic: 'debriyaj-kullanimi',
    difficulty: 'kolay',
    stem: 'Sürüş boyunca sol ayağı debriyaj pedalının üzerinde hafif bir baskıyla dinlendirmek neden yanlıştır?',
    options: [
      'Sinyal lambaları çalışmaz hâle gelir',
      'Küçük baskı bile debriyaj balatasını ve baskı rulmanını sürekli sürttürerek erken aşındırır',
      'Yakıt göstergesi yanlış değer gösterir',
      'El freni kendiliğinden devreye girer',
    ],
    answerIndex: 1,
    explanation:
      'Pedal üzerindeki hafif ağırlık dahi kavramayı kısmen ayırıp rulmanı sürekli çalıştırır ve balatayı kaydırır. Zamanla balata, baskı ve rulman erken biter. Ayak, vites değişimi dışında pedalın solundaki dinlenme alanında durmalıdır.',
    whyWrong: [
      'Sinyaller ve yakıt göstergesi debriyajdan bağımsız elektrik devreleridir.',
      'El freni yalnızca sürücü tarafından kumanda edilir.',
    ],
    objective: 'Ayağı debriyaj üzerinde tutma alışkanlığının aşınma maliyetini bilmek.',
    tags: ['debriyaj', 'kullanim-hatasi', 'asinma'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-516',
    subject: 'motor',
    topic: 'debriyaj-kullanimi',
    difficulty: 'orta',
    stem: 'Yokuşta bekleyen aracı geriye kaçmasın diye uzun süre yarı debriyajla (debriyajı kaydırarak) tutmanın sonucu nedir?',
    options: [
      'Debriyaj balatası kendini yeniler',
      'Motor daha iyi soğur',
      'Lastik basıncı yükselir',
      'Sürekli sürtünen debriyaj balatası aşırı ısınıp yanar (yanık koku); ömrü hızla kısalır — bekleme fren veya el freniyle yapılmalıdır',
    ],
    answerIndex: 3,
    explanation:
      'Yarı debriyajda balata, volan ile baskı arasında sürekli kayarak çalışır; kısa sürede aşırı ısınır, yanık kokusu yayar ve ömrü hızla tükenir. Yokuşta bekleyiş fren pedalı ya da el freniyle yapılmalı, kalkışta debriyaj kısa süreli kullanılmalıdır.',
    whyWrong: [
      'Balata kendini yenileyemez; sürtünme onu geri dönüşsüz aşındırır.',
      'Yarı debriyajın motor soğutmasına ve lastik basıncına etkisi yoktur.',
    ],
    objective: 'Yarı debriyajla bekleme alışkanlığının balatayı yaktığını kavramak.',
    tags: ['debriyaj', 'yari-debriyaj', 'yokus'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-517',
    subject: 'motor',
    topic: 'sanziman-yagi',
    difficulty: 'orta',
    stem: 'Şanzıman (vites kutusu) yağının görevi aşağıdakilerden hangisidir?',
    options: [
      'Birbiriyle çalışan dişlileri yağlayarak aşınmayı ve aşırı ısınmayı önlemek, sessiz ve rahat vites geçişine katkı sağlamak',
      'Motor silindirlerini yağlamak',
      'Gerektiğinde fren hidroliği yerine kullanılmak',
      'Egzoz gazlarını yumuşatmak',
    ],
    answerIndex: 0,
    explanation:
      'Vites kutusundaki dişliler sürekli yük altında birbirine geçerek çalışır. Şanzıman yağı bu dişlileri ve yatakları yağlar, ısıyı dağıtır ve senkronizasyonun rahat çalışmasını sağlayarak geçişleri yumuşatır.',
    whyWrong: [
      'Motor silindirlerini motor yağı yağlar; iki yağ farklı özelliktedir.',
      'Hiçbir yağ fren hidroliği yerine konmaz; egzozla da ilgisi yoktur.',
    ],
    objective: 'Şanzıman yağının motor yağından ayrı bir görev üstlendiğini öğrenmek.',
    tags: ['sanziman', 'disli-yagi', 'bakim'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-518',
    subject: 'motor',
    topic: 'sanziman-yagi',
    difficulty: 'zor',
    stem: 'Manuel vitesli bir araçta vitesler giderek zor geçiyor ve şanzımandan uğultu/çınlama sesi geliyorsa öncelikle ne kontrol ettirilmelidir?',
    options: [
      'Silecek suyu seviyesi',
      'Polen filtresi',
      'Şanzıman yağının seviyesi ve durumu; yağ azalmış ya da özelliğini yitirmiş olabilir',
      'Far ampulleri',
    ],
    answerIndex: 2,
    explanation:
      'Yağı azalan veya bozulan şanzımanda dişliler ve yataklar yeterince yağlanamaz: uğultu başlar, senkronlar zorlanır ve vites geçişleri sertleşir. Kaçak olup olmadığı da bakılmalı, yağ gerekirse tamamlanmalı ya da değiştirilmelidir.',
    whyWrong: [
      'Silecek suyu ve polen filtresi konfor donanımlarıdır; güç aktarımıyla ilgisizdir.',
      'Far ampullerinin vites geçişine etkisi yoktur.',
    ],
    objective: 'Zor vites geçişi + uğultu belirtisini şanzıman yağıyla ilişkilendirmek.',
    tags: ['sanziman', 'ariza-belirtisi', 'ugultu'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-519',
    subject: 'motor',
    topic: 'diferansiyel',
    difficulty: 'orta',
    stem: 'Araçlarda diferansiyel bulunmasaydı viraj dönüşlerinde ne yaşanırdı?',
    options: [
      'Araç virajları daha hızlı dönerdi',
      'İç ve dış tekerlekler farklı mesafe kat ettikleri hâlde aynı hızda dönmeye zorlanır; lastikler yerde sürterek aşınır ve dönüş güçleşirdi',
      'Motor daha az yakıt harcardı',
      'Frenler tamamen devre dışı kalırdı',
    ],
    answerIndex: 1,
    explanation:
      'Virajda dıştaki tekerlek içtekinden daha uzun bir yay çizer. Diferansiyel bu hız farkına izin verir. O olmasaydı iki tekerlek birbirine kilitli döner; lastikler kayarak aşınır, aktarma organları zorlanır ve araç dönmeye direnirdi.',
    whyWrong: [
      'Kilitli tekerlekler dönüşü kolaylaştırmaz, tam tersine zorlaştırırdı.',
      'Yakıt tasarrufu sağlamaz; sürtünme kayıpları artardı.',
      'Fren sistemi diferansiyelden bağımsız çalışır.',
    ],
    objective: 'Diferansiyelin virajdaki hız farkını neden karşıladığını kavramak.',
    tags: ['diferansiyel', 'viraj', 'aktarma-organlari'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-520',
    subject: 'motor',
    topic: 'on-duzen-ayrimi',
    difficulty: 'orta',
    stem: '"Araç düz yolda bir tarafa çekiyor" ve "belirli hızlarda direksiyon titriyor" şikâyetlerinin tipik nedenleri hangi seçenekte doğru eşleştirilmiştir?',
    options: [
      'Çekme = balans bozukluğu; titreme = rot bozukluğu',
      'Her iki şikâyet de yalnızca amortisör arızasından kaynaklanır',
      'Çekme = akü zayıflığı; titreme = buji arızası',
      'Çekme = rot (ön düzen) ayarsızlığı; belirli hızdaki direksiyon titremesi = balans bozukluğu',
    ],
    answerIndex: 3,
    explanation:
      'Rot ayarı tekerleklerin yola basma açısını belirler; bozulunca araç bir tarafa çeker ve lastik tek omuzdan aşınır. Balans ise jant-lastik ağırlık dengesidir; bozulunca belirli hız aralığında direksiyona titreşim gelir.',
    whyWrong: [
      'İlk seçenekte iki kavram birbiriyle yer değiştirmiştir.',
      'Amortisör arızası salınım yapar; akü ve bujinin bu şikâyetlerle ilgisi yoktur.',
    ],
    objective: 'Rot ve balans bozukluğunun belirtilerini birbirinden ayırt etmek.',
    tags: ['rot', 'balans', 'ariza-ayrimi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-521',
    subject: 'motor',
    topic: 'balans',
    difficulty: 'kolay',
    stem: 'Yeni lastik taktırıldığında balans ayarının da yaptırılması neden gerekir?',
    options: [
      'Jant-lastik bütününün ağırlık dağılımı değiştiği için; dengelenmeyen tekerlek hızda titreşim yaparak parçaları ve lastiği yıpratır',
      'Balans ayarı lastiğin rengini korur',
      'Balans yapılmazsa yakıt deposu küçülür',
      'Balans ayarı yalnızca kış lastiklerinde gerekir',
    ],
    answerIndex: 0,
    explanation:
      'Her lastiğin ağırlık dağılımı birebir aynı değildir. Yeni lastik janta takıldığında bütünün dengesi değişir; balans makinesinde küçük kurşun ağırlıklarla dengelenmezse tekerlek hızlandıkça titrer, rulman ve rotilleri yorar.',
    whyWrong: [
      'Balansın lastiğin görünümüyle veya yakıt deposuyla ilgisi yoktur.',
      'Balans, mevsim fark etmeksizin her lastik değişiminde yapılmalıdır.',
    ],
    objective: 'Lastik değişimi ile balans ayarı arasındaki zorunlu ilişkiyi bilmek.',
    tags: ['balans', 'lastik-degisimi', 'titresim'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-522',
    subject: 'motor',
    topic: 'fren-turleri',
    difficulty: 'kolay',
    stem: 'B sınıfı bir otomobilde servis (ayak) freni ile klasik el (park) freninin çalışma prensipleri hangi seçenekte doğru verilmiştir?',
    options: [
      'Her ikisi de hidrolik basınçla çalışır',
      'Servis freni mekanik, el freni hidroliktir',
      'Servis freni hidrolik basınçla, klasik el freni ise mekanik olarak (halat/tel üzerinden) çalışır',
      'Her ikisi de basınçlı havayla çalışır',
    ],
    answerIndex: 2,
    explanation:
      'Otomobilde pedala basıldığında kuvvet, fren hidroliği üzerinden tekerleklere basınç olarak iletilir. Klasik el freni ise koldan arka tekerleklere uzanan çelik halatla tamamen mekanik çalışır; bu sayede hidrolik arızasında bile tutabilir.',
    whyWrong: [
      'İki sistemin prensipleri aynı değildir; ikinci seçenekte de ters yazılmıştır.',
      'Basınçlı havalı frenler otomobillerde değil, kamyon ve otobüs gibi ağır taşıtlarda kullanılır.',
    ],
    objective: 'Hidrolik servis freni ile mekanik el freni ayrımını öğrenmek.',
    tags: ['fren-sistemi', 'hidrolik', 'el-freni'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-523',
    subject: 'motor',
    topic: 'fren-servo',
    difficulty: 'orta',
    stem: 'Fren güçlendiricisinin (servo) sürücüye sağladığı fayda nedir?',
    options: [
      'Fren balatalarının hiç aşınmamasını sağlar',
      'Pedala uygulanan kuvveti çoğunlukla motor vakumundan yararlanarak katlar; böylece az güçle etkili frenleme yapılır',
      'Aracı engel algılayınca kendiliğinden durdurur',
      'El frenini tamamen gereksiz kılar',
    ],
    answerIndex: 1,
    explanation:
      'Servo, pedal ile fren merkezi arasında oturan bir kuvvet çoğaltıcıdır; genellikle motorun emme vakumunu kullanır. Sürücünün ayak kuvvetini birkaç kat büyüterek uzun sürüşlerde bile yormayan, etkili bir frenleme sağlar.',
    whyWrong: [
      'Balata aşınması sürtünmenin doğal sonucudur; servo bunu engelleyemez.',
      'Kendiliğinden durdurma, ayrı bir sistem olan acil fren yardımcılarının işidir; el freni park için her zaman gereklidir.',
    ],
    objective: 'Servonun kuvvet çoğaltma görevini kavramak.',
    tags: ['fren-servo', 'vakum', 'fren-sistemi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-524',
    subject: 'motor',
    topic: 'fren-servo',
    difficulty: 'zor',
    stem: 'Uzun bir inişte yakıt tasarrufu umuduyla kontağı kapatıp motoru durdurarak inmek neden çok tehlikelidir?',
    options: [
      'Motor durunca fren güçlendiricisinin vakum desteği birkaç pedal basışından sonra tükenir ve pedal taş gibi sertleşir; ayrıca direksiyon desteği kesilir, kontak konumuna göre direksiyon kilitlenebilir',
      'Yalnızca radyo kapanır, başka bir etkisi olmaz',
      'Lastikler daha hızlı aşınır',
      'Klima gazı kaçar',
    ],
    answerIndex: 0,
    explanation:
      'Servo, vakumunu çalışan motordan alır. Motor durunca depodaki vakum birkaç frenlemede biter; pedal sertleşir ve fren gücü ciddi biçimde azalır. Direksiyon desteği de kesilir; anahtar yanlış konuma çevrilirse direksiyon kilidi devreye girebilir. İnişte doğru yöntem düşük viteste motor freni kullanmaktır.',
    whyWrong: [
      'Sorun konforla sınırlı değildir; fren ve direksiyon hâkimiyeti doğrudan tehlikeye girer.',
      'Lastik aşınması ve klima gazının konuyla ilgisi yoktur.',
    ],
    objective: 'Motor kapalıyken servonun ve direksiyon desteğinin devre dışı kaldığını bilmek.',
    tags: ['fren-servo', 'inis', 'motor-freni'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-525',
    subject: 'motor',
    topic: 'guvenlik-sistemleri',
    difficulty: 'kolay',
    stem: 'ASR (patinaj önleme / çekiş kontrol) sisteminin görevi nedir?',
    options: [
      'Farları karanlıkta otomatik yakmak',
      'Anlık yakıt tüketimini hesaplamak',
      'Ani frenlemede tekerleklerin kilitlenmesini önlemek',
      'Kalkışta ve hızlanmada çekiş tekerleklerinin patinaj yapmasını (boşa dönmesini) engelleyerek tutunmayı korumak',
    ],
    answerIndex: 3,
    explanation:
      'ASR, gaz verilirken tekerleklerden biri yol tutuşunu kaybedip boşa dönmeye başladığında o tekerleğe kısa fren uygular veya motor gücünü kısar. Özellikle karlı, ıslak ve gevşek zeminlerde kontrollü kalkış sağlar.',
    whyWrong: [
      'Frende kilitlenmeyi önlemek ASR değil ABS görevi olan ayrı bir işlevdir.',
      'Otomatik far ve tüketim hesabı konfor/gösterge donanımlarıdır.',
    ],
    objective: 'ASR kısaltmasının patinaj önleme işlevini öğrenmek.',
    tags: ['asr', 'patinaj', 'cekis-kontrol'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-526',
    subject: 'motor',
    topic: 'guvenlik-sistemleri',
    difficulty: 'orta',
    stem: 'ABS, ESP ve ASR kısaltmalarının görevleri hangi seçenekte doğru eşleştirilmiştir?',
    options: [
      'ABS = patinajı önler, ESP = frende kilitlenmeyi önler, ASR = savrulmayı dengeler',
      'ABS = frende tekerlek kilitlenmesini önler, ESP = savrulmayı algılayıp aracı dengeler, ASR = kalkış ve hızlanmada patinajı önler',
      'Üçü de yalnızca yakıt tasarrufu sağlayan sistemlerdir',
      'ABS = klima, ESP = müzik sistemi, ASR = far yıkama donanımıdır',
    ],
    answerIndex: 1,
    explanation:
      'Üç elektronik yardımcının görev alanı farklıdır: ABS sert frende kilitlenmeyi önleyip direksiyon hâkimiyetini korur; ESP aracın savrulma eğilimini algılayıp tek tek frenlemeyle dengeler; ASR gaz sırasında patinajı keser.',
    whyWrong: [
      'İlk seçenekte görevler birbirine karıştırılmıştır.',
      'Bunlar konfor veya tasarruf değil, aktif güvenlik sistemleridir.',
    ],
    objective: 'Üç aktif güvenlik kısaltmasını doğru görevlerle eşleştirmek.',
    tags: ['abs', 'esp', 'asr'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-527',
    subject: 'motor',
    topic: 'guvenlik-sistemleri',
    difficulty: 'zor',
    stem: 'ESP bir savrulma başlangıcını teknik olarak nasıl toparlar?',
    options: [
      'Sürücü koltuğunu öne çekerek',
      'Tüm tekerleklere aynı anda tam fren uygulayarak',
      'Sensörlerle sürücünün gitmek istediği yön ile aracın gerçek gidişini karşılaştırır; sapma algılayınca uygun tekerleklere tek tek fren uygular ve gerekirse motor gücünü kısar',
      'Direksiyonu sürücüden bağımsız tam tur çevirerek',
    ],
    answerIndex: 2,
    explanation:
      'ESP; direksiyon açısı, tekerlek hızları ve aracın dönme (savrulma) sensörlerini sürekli izler. Araç sürücünün istediği rotadan sapmaya başlarsa sistemi düzeltecek tekerleğe hedefli fren yapar ve gerekirse gücü azaltarak aracı rotada tutar.',
    whyWrong: [
      'Koltuk konumu ve direksiyonun zorla çevrilmesi ESP ile ilgisizdir.',
      'Tüm tekerleklere aynı anda tam fren savrulmayı düzeltmez; ESP hedefli ve seçici fren yapar.',
    ],
    objective: 'ESP tekniğinin seçici frenleme mantığını kavramak.',
    tags: ['esp', 'savrulma', 'sensor'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-528',
    subject: 'motor',
    topic: 'far-turleri',
    difficulty: 'kolay',
    stem: 'LED farların halojen farlara göre öne çıkan avantajları nelerdir?',
    options: [
      'Daha az enerji tüketmeleri, çok daha uzun ömürlü olmaları ve anında tam parlaklığa ulaşmaları',
      'Daha fazla yakıt tüketmeleri',
      'Yalnızca gündüz çalışabilmeleri',
      'Isıya dayanıksız oldukları için her yıl komple değiştirilmeleri',
    ],
    answerIndex: 0,
    explanation:
      'LED aydınlatma aynı ışık için halojene göre çok daha az elektrik harcar, on binlerce saat dayanır ve açıldığı anda tam parlaklık verir. Beyaza yakın ışığı da gece görüşünü destekler.',
    whyWrong: [
      'Az enerji çekmeleri dolaylı olarak yakıt yükünü azaltır, artırmaz.',
      'LED farlar gece kullanım için tasarlanır ve halojenden daha uzun ömürlüdür.',
    ],
    objective: 'LED ve halojen far teknolojilerinin temel farkını bilmek.',
    tags: ['led', 'halojen', 'aydinlatma'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-529',
    subject: 'motor',
    topic: 'far-turleri',
    difficulty: 'orta',
    stem: 'Halojen far ampulü değiştirilirken cam kısmına çıplak elle dokunulmamasının nedeni nedir?',
    options: [
      'Cam kısmın elektrik çarpmasına yol açması',
      'Parmak izinin ampulün garantisini geçersiz kılması',
      'Parmaktan bulaşan yağın, çok yüksek sıcaklıkta çalışan kuvars camda sıcak nokta oluşturarak ampulün ömrünü kısaltması, hatta patlamasına yol açabilmesi',
      'Ampulün dokunulduğu anda sönüp bir daha yanmaması',
    ],
    answerIndex: 2,
    explanation:
      'Halojen ampulün kuvars camı çalışırken çok yüksek sıcaklığa çıkar. Deriden bulaşan ince yağ tabakası bu noktada ısıyı düzensiz dağıtır; cam zayıflar, ampul erken yanar veya çatlayabilir. Ampul kâğıt havlu ya da eldivenle tutulmalı, dokunulursa alkolle silinmelidir.',
    whyWrong: [
      'Takılı olmayan ampul elektrik çarpmaz; sorun garanti değil ısı dağılımıdır.',
      'Ampul dokunmayla anında sönmez; hasar zamanla ortaya çıkar.',
    ],
    objective: 'Halojen ampul değişiminde temiz tutma kuralının gerekçesini öğrenmek.',
    tags: ['halojen', 'ampul-degisimi', 'bakim'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-530',
    subject: 'motor',
    topic: 'aydinlatma-ariza',
    difficulty: 'orta',
    stem: 'Aydınlatma arızasında ilk şüphelenilecek parçalar hangi seçenekte doğru eşleştirilmiştir?',
    options: [
      'Tek far sönükse sigorta; birden çok lamba sönükse ampul',
      'Tek far sönükse o farın ampulü; aynı devredeki birden çok lamba birden sönükse ortak sigorta',
      'Her iki durumda da önce alternatör değiştirilir',
      'Her iki durumda da yakıt pompası kontrol edilir',
    ],
    answerIndex: 1,
    explanation:
      'Tek bir lambanın sönmesi çoğunlukla o lambanın ampulünün ömrünü doldurduğunu gösterir. Aynı sigortadan beslenen birkaç lambanın aynı anda sönmesi ise ortak noktayı, yani sigortayı (veya ortak kabloyu) işaret eder.',
    whyWrong: [
      'İlk seçenekte mantık ters kurulmuştur.',
      'Alternatör tüm sistemi besler; tek devre arızasında ilk şüpheli değildir. Yakıt pompasının aydınlatmayla ilgisi yoktur.',
    ],
    objective: 'Ampul-sigorta ayrımını arızanın kapsamından çıkarabilmek.',
    tags: ['aydinlatma', 'sigorta', 'ampul'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-531',
    subject: 'motor',
    topic: 'plaka-lambasi',
    difficulty: 'kolay',
    stem: 'Plaka lambasının görevi aşağıdakilerden hangisidir?',
    options: [
      'Geri giderken yolu aydınlatmak',
      'Bagaj içini aydınlatmak',
      'Sürücüye arkadan gelen aracı göstermek',
      'Arka plakayı geceleri aydınlatarak plakanın diğer sürücüler ve görevliler tarafından okunabilmesini sağlamak',
    ],
    answerIndex: 3,
    explanation:
      'Plaka lambası, farlarla birlikte yanarak arka plakayı aydınlatır; plakanın karanlıkta da okunabilmesi yasal bir zorunluluktur. Arızalı plaka lambası muayenede ve denetimlerde eksiklik sayılır.',
    whyWrong: [
      'Geri yolunu geri vites lambası aydınlatır.',
      'Bagaj lambası ayrı bir iç aydınlatmadır; arkadaki aracı görmek için aynalar kullanılır.',
    ],
    objective: 'Plaka lambasının görevini ve zorunluluğunu bilmek.',
    tags: ['plaka-lambasi', 'aydinlatma', 'zorunlu-donanim'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-532',
    subject: 'motor',
    topic: 'korna',
    difficulty: 'kolay',
    stem: 'Korna aniden hiç ses vermez olduysa yapılacak ilk basit kontrol hangisidir?',
    options: [
      'Sigorta kutusundan korna sigortasının atıp atmadığına bakmak',
      'Motor yağını değiştirmek',
      'Lastik basınçlarını yükseltmek',
      'Radyatöre su eklemek',
    ],
    answerIndex: 0,
    explanation:
      'Korna elektrikle çalışan bir donanımdır ve kendi sigortası vardır. Ani ve tam susma çoğunlukla atmış bir sigortadan kaynaklanır; sigorta sağlamsa kumanda (direksiyon teli) ve korna ünitesi kontrol edilir.',
    whyWrong: [
      'Motor yağı, lastik basıncı ve soğutma suyu elektrik devresiyle ilgisizdir.',
      'Bunları değiştirmek korna arızasını gidermez.',
    ],
    objective: 'Elektrikli donanım arızasında ilk adımın sigorta kontrolü olduğunu bilmek.',
    tags: ['korna', 'sigorta', 'elektrik'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-533',
    subject: 'motor',
    topic: 'cam-suyu',
    difficulty: 'kolay',
    stem: 'Silecek su haznesine bulaşık deterjanı veya şampuan koymak neden önerilmez?',
    options: [
      'Cam suyunun rengini değiştirdiği için',
      'Aracın hızını düşürdüğü için',
      'Aşırı köpürerek görüşü bozması, hortum ve fıskiyelerde tortu bırakıp tıkaması, silecek lastiğine ve boyaya zarar verebilmesi nedeniyle; hazneye bu iş için üretilmiş cam suyu konmalıdır',
      'Deterjanın yakıtla karışması nedeniyle',
    ],
    answerIndex: 2,
    explanation:
      'Ev tipi deterjanlar yoğun köpük yapar; cama sıkıldığında görüşü kapatabilir. Kuruyan kalıntıları ince fıskiye deliklerini tıkar, silecek kauçuğunu sertleştirir ve boyada iz bırakabilir. Doğrusu, araç camları için üretilmiş hazır cam suyu kullanmaktır.',
    whyWrong: [
      'Sorun estetik ya da hızla ilgili değildir; görüş ve donanım zarar görür.',
      'Cam suyu haznesinin yakıt sistemiyle bağlantısı yoktur.',
    ],
    objective: 'Cam suyu haznesine uygun sıvı seçiminin gerekçesini bilmek.',
    tags: ['silecek-suyu', 'bakim', 'gorus'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-534',
    subject: 'motor',
    topic: 'cam-suyu',
    difficulty: 'kolay',
    stem: 'Kış aylarında silecek su haznesinde donmaya dayanıklı (antifrizli) cam suyu bulundurmanın önemi nedir?',
    options: [
      'Motorun daha hızlı ısınmasını sağlar',
      'Sıradan su donarak haznede ve fıskiyelerde hasar yapabilir; tam ihtiyaç anında cam yıkanamaz — donmayan cam suyu bu riski ortadan kaldırır',
      'Yakıt tüketimini azaltır',
      'Lastiklerin buz tutmasını engeller',
    ],
    answerIndex: 1,
    explanation:
      'Kışın yollardan sıçrayan çamur ve tuzlu su camı hızla kirletir; görüş için yıkama suyu hayati önem taşır. Haznedeki sıradan su donarsa hem sistem çalışmaz hem de genleşen buz hazneyi ve hortumları çatlatabilir.',
    whyWrong: [
      'Cam suyunun motor ısınmasıyla ve yakıt tüketimiyle ilgisi yoktur.',
      'Lastiklerin buzlanması cam suyuyla önlenemez.',
    ],
    objective: 'Kış koşullarında donmayan cam suyunun görüş güvenliğine katkısını bilmek.',
    tags: ['silecek-suyu', 'kis-bakimi', 'donma'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-535',
    subject: 'motor',
    topic: 'yakit-rezerv',
    difficulty: 'orta',
    stem: 'Depoda sürekli çok az yakıtla (ibre hep rezervde) dolaşmak neden araca zarar verebilir?',
    options: [
      'Depo dibindeki tortunun sisteme çekilme olasılığı artar; ayrıca depo içindeki elektrikli yakıt pompası yakıtın içinde çalışarak soğuduğundan az yakıtla zorlanır ve ömrü kısalır',
      'Araç hafiflediği için frenler zayıflar',
      'Rezervde sürüş lastik basıncını düşürür',
      'Rezervdeyken kabin sigortaları atar',
    ],
    answerIndex: 0,
    explanation:
      'Zamanla deponun dibinde tortu ve nem birikir; seviye hep diptayken bunların filtre ve enjektörlere taşınma riski artar. Modern araçlarda pompa deponun içindedir ve yakıta gömülü çalışarak soğur; sürekli düşük seviye pompayı ısıtıp yıpratır.',
    whyWrong: [
      'Yakıt azlığının fren gücüyle ve lastik basıncıyla ilgisi yoktur.',
      'Rezerv seviyesi elektrik sigortalarını etkilemez.',
    ],
    objective: 'Sürekli rezervde gezmenin pompa ve yakıt sistemi üzerindeki riskini kavramak.',
    tags: ['rezerv', 'yakit-pompasi', 'tortu'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-536',
    subject: 'motor',
    topic: 'yanlis-yakit',
    difficulty: 'zor',
    stem: 'Dizel bir araca konulan benzinin yakıt sistemine özellikle zarar vermesinin teknik nedeni nedir?',
    options: [
      'Benzinin renginin motorinden farklı olması',
      'Benzinin motorinden daha pahalı olması',
      'Dizel pompa ve enjektörlerin bizzat motorinin yağlayıcılığıyla çalışması; yağlayıcılığı çok düşük olan benzinin bu hassas parçaları kuru sürtünmeyle hızla aşındırması',
      'Benzinin depoda donarak boruları tıkaması',
    ],
    answerIndex: 2,
    explanation:
      'Motorin, yüksek basınçlı dizel pompası ve enjektörler için aynı zamanda yağlayıcı görevi görür. Benzin ise incedir ve çözücü gibi davranır; sisteme girdiğinde bu yağ filmini siler, metal yüzeyler kuru çalışıp kısa sürede aşınır. Bu yüzden yanlış yakıtta motor çalıştırılmamalıdır.',
    whyWrong: [
      'Renk ve fiyat farkının teknik hasarla ilgisi yoktur.',
      'Benzin donmaz; sorun tam tersine akışkanlığının fazla, yağlayıcılığının az olmasıdır.',
    ],
    objective: 'Yanlış yakıtın dizel sistemde neden ağır hasar yaptığını teknik olarak açıklamak.',
    tags: ['yanlis-yakit', 'dizel-pompa', 'yaglayicilik'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-537',
    subject: 'motor',
    topic: 'yanlis-yakit',
    difficulty: 'orta',
    stem: 'Benzinli bir araca yanlışlıkla motorin (dizel yakıtı) konursa ne beklenir?',
    options: [
      'Motor daha güçlü ve sessiz çalışır',
      'Hiçbir olumsuzluk yaşanmaz',
      'Yalnızca klima devre dışı kalır',
      'Motorin bujiyle sağlıklı tutuşamadığı için motor tekler, yoğun duman çıkarır ve kısa sürede stop eder; sistem temizlenmeden araç kullanılmamalıdır',
    ],
    answerIndex: 3,
    explanation:
      'Benzinli motor, kıvılcımla kolay tutuşan benzin için tasarlanmıştır. Ağır ve zor buharlaşan motorin bujiyle düzgün yanmaz: motor sarsılır, dumanlanır ve genellikle stop eder. Depo ve hatlar boşaltılıp temizlenmeden çalıştırma denenmemelidir.',
    whyWrong: [
      'Yanlış yakıt performans kazandırmaz; düzgün yanma gerçekleşmez.',
      'Sorunsuz çalışmaz ve klima ile sınırlı kalmaz; asıl etkilenen yanmadır.',
    ],
    objective: 'Benzinli araçta motorinin yol açtığı belirtileri ve yapılmaması gerekeni bilmek.',
    tags: ['yanlis-yakit', 'benzinli-motor', 'tekleme'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-538',
    subject: 'motor',
    topic: 'enjektor',
    difficulty: 'orta',
    stem: 'Kalitesiz veya tortulu yakıt kullanımı enjektörleri nasıl etkiler?',
    options: [
      'Enjektörlerin ömrünü uzatır',
      'Püskürtme deliklerini zamanla tıkayarak yakıtın ince zerrecikler hâlinde püskürtülmesini bozar; rölanti düzensizleşir, güç düşer ve tüketim artar',
      'Enjektörleri kendiliğinden temizler',
      'Yalnızca far ayarını bozar',
    ],
    answerIndex: 1,
    explanation:
      'Enjektör, yakıtı kılcal deliklerden sis gibi püskürterek verimli yanma sağlar. Kirli yakıttaki tortular bu delikleri daraltır; püskürtme deseni bozulunca yanma kötüleşir: sarsıntı, güç kaybı ve fazla tüketim ortaya çıkar. Güvenilir istasyonlardan yakıt almak en basit korumadır.',
    whyWrong: [
      'Tortu ömür uzatmaz, tıkanma ve aşınma yapar; kendiliğinden temizlenme olmaz.',
      'Far ayarının yakıt kalitesiyle ilgisi yoktur.',
    ],
    objective: 'Yakıt kalitesi ile enjektör sağlığı arasındaki ilişkiyi kurmak.',
    tags: ['enjektor', 'yakit-kalitesi', 'tikanma'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-539',
    subject: 'motor',
    topic: 'mars-kullanimi',
    difficulty: 'kolay',
    stem: 'Çalışmayan bir motoru çalıştırmaya uğraşırken marşa uzun süre kesintisiz basılı tutmak neden yanlıştır?',
    options: [
      'Çok yüksek akım çeken marş motoru aşırı ısınıp zarar görebilir ve akü kısa sürede boşalır; kısa denemeler yapıp aralarda beklemek gerekir',
      'Kornanın sigortası atar',
      'Lastikler aşırı ısınıp patlar',
      'Silecekler kendiliğinden devreye girer',
    ],
    answerIndex: 0,
    explanation:
      'Marş motoru kısa süreli çalışmak üzere tasarlanmış, çok yüksek akım çeken bir elektrik motorudur. Uzun basış sargılarını aşırı ısıtır ve aküyü hızla tüketir. Denemeler birkaç saniyeyle sınırlanmalı, aralarında soğuması için beklenmelidir.',
    whyWrong: [
      'Korna ayrı bir devrededir; marş basmakla sigortası atmaz.',
      'Lastikler ve silecekler marş devresinden etkilenmez.',
    ],
    objective: 'Marş motorunun kısa süreli kullanım kuralını ve gerekçesini bilmek.',
    tags: ['mars', 'kullanim-kurali', 'aku'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-540',
    subject: 'motor',
    topic: 'mars-kullanimi',
    difficulty: 'orta',
    stem: 'Motor çalıştığı hâlde marşa basmaya devam etmek ya da çalışan motorda yeniden marş basmak hangi parçalara zarar verir?',
    options: [
      'Radyatör ve termostata',
      'Silecek motoruna',
      'Marş dişlisi ile volan dişlisine; dönmekte olan volana zorla giren marş dişlisi kırılabilir veya dişliler yalar',
      'Polen filtresine',
    ],
    answerIndex: 2,
    explanation:
      'Marş dişlisi, motoru döndürmek için volanın dişli çemberine kısa süreli geçer. Motor kendi başına dönerken marşa basılırsa duran dişli, hızla dönen çembere çarparak zorlanır; dişler kırılabilir veya aşınıp yalayabilir. Bu pahalı bir onarımdır.',
    whyWrong: [
      'Radyatör, termostat ve polen filtresinin marş düzeneğiyle ilgisi yoktur.',
      'Silecek motoru ayrı bir devrede çalışır.',
    ],
    objective: 'Çalışan motorda marş basmanın dişli hasarına yol açtığını bilmek.',
    tags: ['mars-disli', 'volan', 'kullanim-hatasi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-541',
    subject: 'motor',
    topic: 'aku-oksitlenme',
    difficulty: 'orta',
    stem: 'Akü kutup başlarında beyazımsı-yeşilimsi bir tabaka (oksitlenme) birikmesi neye yol açar?',
    options: [
      'Akü kapasitesinin artmasına',
      'Bağlantı direncinin yükselmesine; marşın zayıflamasına ve şarjın düzensizleşmesine — kutup başları temizlenip koruyucu sürülmelidir',
      'Farların daha parlak yanmasına',
      'Yakıt tüketiminin azalmasına',
    ],
    answerIndex: 1,
    explanation:
      'Oksit tabakası, kutup başı ile kablo pabucu arasında elektriğin geçişini zorlaştıran bir direnç oluşturur. Sonuçta marş yeterli akımı alamaz, şarj da düzensizleşir. Tabaka temizlenmeli, bağlantı sıkılmalı ve üzerine ince koruyucu (özel sprey/vazelin) uygulanmalıdır.',
    whyWrong: [
      'Oksitlenme kapasite kazandırmaz; akım geçişini kısıtlar.',
      'Kötü bağlantı farları parlatmaz, aksine soluklaştırabilir; yakıt tüketimiyle ilgisi yoktur.',
    ],
    objective: 'Kutup başı oksitlenmesinin elektriksel etkisini ve giderme yolunu bilmek.',
    tags: ['aku', 'oksitlenme', 'kutup-basi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-542',
    subject: 'motor',
    topic: 'egzoz-susturucu',
    difficulty: 'orta',
    stem: 'Susturucusu delinmiş veya çürümüş bir egzozla dolaşmak neden yalnızca gürültü sorunu değildir?',
    options: [
      'Araç daha hızlı gittiği için',
      'Yakıt deposu genleştiği için',
      'Far ayarı bozulduğu için',
      'Kaçak yapan egzoz gazı aracın altından kabine sızabilir; içindeki karbonmonoksit renksiz ve kokusuz olduğundan yolcular fark etmeden zehirlenebilir',
    ],
    answerIndex: 3,
    explanation:
      'Sağlam egzoz, gazları aracın en arkasından atar. Delik susturucu ve borular gazı taban altına bırakır; kapı-taban boşluklarından kabine sızan karbonmonoksit hissedilmeden baş ağrısı, uyuklama ve zehirlenme yapar. Delik egzoz gecikmeden onarılmalıdır.',
    whyWrong: [
      'Delik egzoz hız kazandırmaz; performansı bile düşürebilir.',
      'Yakıt deposu ve far ayarının egzoz kaçağıyla ilgisi yoktur.',
    ],
    objective: 'Egzoz kaçağının kabin için zehirlenme riski taşıdığını kavramak.',
    tags: ['susturucu', 'egzoz-kacagi', 'karbonmonoksit'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-543',
    subject: 'motor',
    topic: 'egzoz-guvenlik',
    difficulty: 'zor',
    stem: 'Kapalı bir garajda motoru çalışır durumda bırakmak neden hayati tehlike oluşturur?',
    options: [
      'Egzozla çıkan karbonmonoksit renksiz ve kokusuz zehirli bir gazdır; kapalı hacimde hızla birikir ve fark edilmeden bilinç kaybına, hatta ölüme yol açabilir',
      'Garaj kapısının boyası solar',
      'Lastikler zemine yapışır',
      'Akü aşırı şarj olarak patlar',
    ],
    answerIndex: 0,
    explanation:
      'Karbonmonoksit, kandaki oksijen taşınmasını engelleyen sinsi bir gazdır; rengi ve kokusu olmadığı için birikimi fark edilmez. Motor; ısınma, klima ya da bakım amacıyla bile olsa yalnızca açık veya çok iyi havalandırılan yerlerde çalıştırılmalıdır.',
    whyWrong: [
      'Boya, lastik ve akü ile ilgili seçenekler gerçek tehlikeyi yansıtmaz.',
      'Asıl risk görünmez gaz birikimiyle gelen zehirlenmedir.',
    ],
    objective: 'Kapalı alanda çalışan motorun karbonmonoksit riskini bilmek.',
    tags: ['karbonmonoksit', 'kapali-alan', 'zehirlenme'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-544',
    subject: 'motor',
    topic: 'yakit-tuketimi',
    difficulty: 'kolay',
    stem: 'Aşağıdakilerden hangisi yakıt tüketimini ARTIRMAZ?',
    options: [
      'Bagajda sürekli gereksiz ağırlık taşımak',
      'Lastikleri olması gerekenden düşük basınçla kullanmak',
      'Uygun basınçlı lastiklerle, trafiğin akışına uygun dengeli ve sabit bir hızda seyretmek',
      'Sık sık ani gaz verip ani fren yapmak',
    ],
    answerIndex: 2,
    explanation:
      'Dengeli ve sabit hızda sürüş, motorun verimli aralıkta çalışmasını sağlar ve tüketimi düşürür. Fazla yük aracı ağırlaştırır, düşük basınçlı lastik yuvarlanma direncini büyütür, ani hızlanıp frenlemek de kazanılan enerjiyi boşa harcar.',
    whyWrong: [
      'Ek ağırlık her kalkışta fazladan yakıt ister.',
      'Sönük lastik ve agresif gaz-fren alışkanlığı tüketimi belirgin artırır.',
    ],
    objective: 'Tüketimi artıran ve azaltan etkenleri ayırt etmek.',
    tags: ['yakit-tuketimi', 'ekonomik-suru', 'lastik-basinci'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-545',
    subject: 'motor',
    topic: 'yakit-tuketimi',
    difficulty: 'orta',
    stem: 'Sürekli çok kısa mesafelerde kullanılan araçlarda 100 km başına yakıt tüketiminin yüksek çıkmasının temel nedeni nedir?',
    options: [
      'Kısa yolda lastik çapının küçülmesi',
      'Motorun çalışma sıcaklığına ulaşamadan yolculuğun bitmesi; soğuk motorun daha zengin karışım ve yüksek iç sürtünmeyle verimsiz çalışması',
      'Kısa yolculuklarda rüzgârın hep önden esmesi',
      'Yakıtın kısa yolda daha hızlı buharlaşması',
    ],
    answerIndex: 1,
    explanation:
      'Soğuk motorda yağ henüz akışkanlaşmamıştır ve yönetim sistemi daha fazla yakıt püskürtür. Kısa yolculukta motor tam ısınamadan durdurulur; verimsiz geçen bu ilk dakikalar toplam yolun büyük bölümünü oluşturduğu için ortalama tüketim yükselir.',
    whyWrong: [
      'Lastik çapı yolculuk süresine göre değişmez.',
      'Rüzgâr yönü ve buharlaşma bu farkın açıklaması değildir.',
    ],
    objective: 'Soğuk motorla yapılan kısa sürüşlerin tüketimi neden artırdığını kavramak.',
    tags: ['kisa-mesafe', 'soguk-motor', 'yakit-tuketimi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-546',
    subject: 'motor',
    topic: 'motor-takozu',
    difficulty: 'zor',
    stem: 'Rölantide ve vites geçişlerinde kabinde belirgin titreşim hissediliyor, gaz kesildiğinde motor sanki yerinden oynuyor gibi sarsılıyorsa; buji ve enjektörler sağlam çıktığında hangi parça kontrol ettirilmelidir?',
    options: [
      'Silecek lastikleri',
      'Plaka lambası',
      'Yakıt deposu kapağı',
      'Motor takozları (kulakları); yıpranan takozlar motor titreşimini sönümleyemez ve titreşim gövdeye geçer',
    ],
    answerIndex: 3,
    explanation:
      'Motor, gövdeye kauçuk-metal takozlarla (kulaklarla) bağlıdır; bunlar çalışma titreşimini emer. Yaşlanıp yumuşayan ya da yırtılan takoz, titreşimi ve motorun gaz anındaki hareketini doğrudan kabine iletir. Kontrolü ve değişimi görece basittir.',
    whyWrong: [
      'Silecek, plaka lambası ve depo kapağı titreşim iletimiyle ilgisizdir.',
      'Belirtiler ateşleme değil, mekanik bağlantı sorununa işaret etmektedir.',
    ],
    objective: 'Motor takozu aşınmasının kabin titreşimiyle bağlantısını kurmak.',
    tags: ['motor-takozu', 'titresim', 'teshis'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-547',
    subject: 'motor',
    topic: 'rolanti-titremesi',
    difficulty: 'orta',
    stem: 'Rölantide düzensiz ve titrek çalışan bir motor için aşağıdakilerden hangisi OLASI nedenlerden biri DEĞİLDİR?',
    options: [
      'Silecek motorunun arızalanması',
      'Bujilerden birinin sağlıklı ateşleme yapmaması',
      'Enjektörlerden birinin kısmen tıkanması',
      'Emme hattında hava (vakum) kaçağı bulunması',
    ],
    answerIndex: 0,
    explanation:
      'Rölanti düzensizliği; ateşleme (buji/bobin), yakıt (enjektör) veya hava (vakum kaçağı, kirli gaz kelebeği) tarafındaki dengesizliklerden doğar. Silecek motoru ise tamamen ayrı bir elektrik donanımıdır; motorun çalışma düzenini etkilemez.',
    whyWrong: [
      'Ateşlemeyen buji o silindiri boşa çalıştırır ve sarsıntı yapar.',
      'Tıkalı enjektör karışımı bozar; vakum kaçağı da rölantiyi dalgalandırır.',
    ],
    objective: 'Rölanti titremesinin olası kaynaklarını ilgisiz donanımdan ayırt etmek.',
    tags: ['rolanti', 'titreme', 'teshis'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-548',
    subject: 'motor',
    topic: 'hava-yastigi',
    difficulty: 'kolay',
    stem: 'Hava yastığı (airbag) hangi mantıkla çalışır?',
    options: [
      'Sürücü bir düğmeye bastığında şişer',
      'Şiddetli bir çarpışmayı algılayan sensörlerin komutuyla saniyenin çok küçük bir bölümünde şişerek başın ve gövdenin sert yüzeylere çarpmasını yumuşatır; tek kullanımlıktır',
      'Araç 50 km/s hızı geçtiği anda kendiliğinden şişer',
      'Yavaş yavaş şişer ve yolculuk boyunca şişik kalır',
    ],
    answerIndex: 1,
    explanation:
      'Çarpışma sensörleri ani ve şiddetli yavaşlamayı algıladığında gaz üreteci yastığı göz açıp kapayana dek şişirir; yastık darbeyi emdikten hemen sonra söner. Açılan yastık yenisiyle değiştirilmek zorundadır.',
    whyWrong: [
      'Sürücü komutuyla veya hız eşiğiyle değil, çarpışma algısıyla tetiklenir.',
      'Sürekli şişik bir yastık görüşü ve kullanımı engellerdi; sistem anlıktır.',
    ],
    objective: 'Hava yastığının sensörle tetiklenen anlık koruma mantığını öğrenmek.',
    tags: ['hava-yastigi', 'sensor', 'pasif-guvenlik'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-549',
    subject: 'motor',
    topic: 'hava-yastigi',
    difficulty: 'orta',
    stem: 'Hava yastığının emniyet kemeriyle birlikte tasarlandığı ifadesi ne anlama gelir?',
    options: [
      'Hava yastığı olan araçta kemer takmaya gerek kalmaz',
      'Kemer yalnızca arka koltuk yolcuları için gereklidir',
      'Yastık, kemerin yavaşlatıp yerinde tuttuğu bir vücudu karşılamak üzere hesaplanmıştır; kemersiz vücut patlama anında yastığa kontrolsüz çarparsa yastık koruyacağına ağır yaralanmaya bile yol açabilir',
      'Kemer takılınca hava yastığı devre dışı kalır',
    ],
    answerIndex: 2,
    explanation:
      'Hava yastığı tek başına bir koruma değil, kemerin tamamlayıcısıdır. Kemer gövdeyi koltukta tutup yavaşlatır; yastık kalan enerjiyi emer. Kemersiz bir vücut, büyük hızla açılan yastıkla ters zamanlamada buluşur ve bu çarpışma ciddi yaralanma üretebilir.',
    whyWrong: [
      'Yastık kemerin yerine geçmez; ikisi birlikte çalışır.',
      'Kemer tüm koltuklar için gereklidir ve takılması yastığı devre dışı bırakmaz.',
    ],
    objective: 'Kemer ile hava yastığının birlikte koruma sağladığını kavramak.',
    tags: ['hava-yastigi', 'emniyet-kemeri', 'pasif-guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-550',
    subject: 'motor',
    topic: 'supap-ayari',
    difficulty: 'zor',
    stem: 'Supap boşluğu ayarının bozulması (boşluğun aşırı açılması) kendini tipik olarak nasıl belli eder?',
    options: [
      'Motorun üst kısmından gelen ritmik metalik tıkırtı sesi, performans düşüşü ve düzensiz çalışma',
      'Lastiklerin virajda ötmesi',
      'Fren pedalının titremesi',
      'Kornanın kendiliğinden çalması',
    ],
    answerIndex: 0,
    explanation:
      'Boşluğu açılan supap mekanizmasında parçalar birbirine vurarak çalışır; motorun üstünden devirle hızlanan tıkırtı duyulur. Supaplar tam ve zamanında açılamadığı için dolgu alışverişi bozulur, güç düşer. Ayar servis tarafından yapılmalıdır.',
    whyWrong: [
      'Lastik ötmesi sürüş dinamiğiyle, pedal titremesi fren diskiyle ilgilidir.',
      'Korna devresinin supap mekanizmasıyla bağlantısı yoktur.',
    ],
    objective: 'Supap boşluğu bozukluğunun ses ve performans belirtisini tanımak.',
    tags: ['supap-ayari', 'tikirti', 'ariza-belirtisi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-551',
    subject: 'motor',
    topic: 'yag-pompasi-ariza',
    difficulty: 'orta',
    stem: 'Yağ pompası görevini yapamaz hâle gelirse motorda süreç nasıl ilerler?',
    options: [
      'Motor daha sessiz çalışmaya başlar',
      'Yakıt tüketimi belirgin şekilde düşer',
      'Yalnızca kalorifer soğuk üfler',
      'Yağ basıncı düşer ve kırmızı yağ lambası yanar; basınçsız kalan yataklar metal metale sürtünür — motor hemen durdurulmazsa kısa sürede ağır hasar (yatak sarması) oluşur',
    ],
    answerIndex: 3,
    explanation:
      'Yağ pompası, yağı basınçla en uzak yataklara kadar ulaştırır. Pompa durursa yağ filmi dakikalar içinde kaybolur; krank ve yatak yüzeyleri kuru sürtünmeyle ısınıp kaynar (yatak sarar). Kırmızı yağ lambası yandığında motor derhâl durdurulmalıdır.',
    whyWrong: [
      'Yağsız kalan motor sessizleşmez; ses ve sürtünme artar.',
      'Yakıt tüketimi düşmez; kalorifer ise soğutma sisteminin konusudur.',
    ],
    objective: 'Yağ pompası arızasının hızla ağır hasara dönüştüğünü kavramak.',
    tags: ['yag-pompasi', 'yatak-sarmasi', 'yag-basinci'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-552',
    subject: 'motor',
    topic: 'calisma-zamanlari',
    difficulty: 'zor',
    stem: 'Dört zamanlı bir motorda çevrimin (dört zamanın tamamının) gerçekleşmesi için krank mili kaç tur döner?',
    options: [
      'Yarım tur',
      'İki tam tur (720 derece); eksantrik mili ise aynı sürede yalnızca bir tur atar',
      'On tam tur',
      'Çeyrek tur',
    ],
    answerIndex: 1,
    explanation:
      'Her zaman, pistonun bir kez inmesi ya da çıkmasıdır ve krankın yarım turuna denk gelir. Dört zaman toplamda iki tam krank turu (720°) sürer. Supaplar çevrimde bir kez açıldığı için eksantrik mili krankın yarı hızında, yani çevrimde bir tur döner.',
    whyWrong: [
      'Yarım tur yalnızca tek bir zamanı karşılar.',
      'On tur ve çeyrek tur çevrim geometrisiyle bağdaşmaz.',
    ],
    objective: 'Dört zamanlı çevrim ile krank/eksantrik tur oranını bilmek.',
    tags: ['dort-zamanli', 'krank-turu', 'eksantrik'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-553',
    subject: 'motor',
    topic: 'aku-koruma',
    difficulty: 'kolay',
    stem: 'Aracını haftalarca kullanmayacak bir sürücünün akü için alabileceği doğru önlem hangisidir?',
    options: [
      'Aküyü tamamen boşaltıp öyle bırakmak',
      'Kutup başlarına düzenli su dökmek',
      'Eksi (şase) kutup başını sökmek ya da aküyü akıllı bir şarj cihazına bağlı tutmak',
      'Farları açık bırakarak akünün formda kalmasını sağlamak',
    ],
    answerIndex: 2,
    explanation:
      'Eksi kutup başı ayrıldığında alarm ve saat gibi bekleme tüketicileri devreden çıkar; akü yalnız kendi öz deşarjıyla baş başa kalır. Akıllı (bakım tipi) şarj cihazı da aküyü sürekli ideal seviyede tutar. İki yöntem de derin boşalmayı önler.',
    whyWrong: [
      'Boş bekletilen akü sülfatlaşır ve kalıcı kapasite kaybeder.',
      'Kutup başına su dökmek çözüm değildir; açık far ise aküyü korumaz, bitirir.',
    ],
    objective: 'Uzun süre kullanılmayacak araçta aküyü koruma yöntemlerini bilmek.',
    tags: ['aku', 'uzun-sure-park', 'koruma'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-554',
    subject: 'motor',
    topic: 'el-freni-kis',
    difficulty: 'orta',
    stem: 'Çok soğuk ve nemli kış gecelerinde araç uzun süre park edilecekse el freni konusunda hangi önlem önerilir?',
    options: [
      'Balataların dona yapışma riskine karşı düz ve güvenli zeminde el frenini çekmek yerine aracı viteste bırakmak (gerekirse tekerleğe takoz koymak)',
      'El frenini her zamankinden iki kat kuvvetle çekmek',
      'El frenini çekip aracı boş vitese almak her koşulda en güvenli yöntemdir',
      'Lastiklerin havasını bir miktar indirmek',
    ],
    answerIndex: 0,
    explanation:
      'Islak balata ve disk/kampana, aşırı soğukta birbirine buz tutarak yapışabilir; sabah fren çözülmez veya balata yüzeyi kopar. Düz zeminde araç viteste (otomatikte P konumunda) bırakılır; eğimde ise takozla desteklenerek risk azaltılır.',
    whyWrong: [
      'Daha kuvvetli çekmek yapışmayı önlemez, artırabilir.',
      'Boş viteste yalnız el frenine güvenmek donma gecesi risklidir; lastik havası indirmenin konuyla ilgisi yoktur.',
    ],
    objective: 'Donma riskli gecelerde el freni yerine vitesle park etme önlemini öğrenmek.',
    tags: ['el-freni', 'donma', 'kis-parki'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-555',
    subject: 'motor',
    topic: 'gunduz-farlari',
    difficulty: 'kolay',
    stem: 'Birçok yeni araçta kontak açılınca kendiliğinden yanan gündüz sürüş farlarının (DRL) amacı nedir?',
    options: [
      'Geceleri yolu aydınlatmak',
      'Gündüz aracın diğer sürücülerce daha kolay fark edilmesini sağlamak; çoğu araçta bu sırada arka lambalar yanmadığından gece mutlaka normal farlar açılmalıdır',
      'Yakıt tüketimini artırarak motoru ısıtmak',
      'Arka plakayı aydınlatmak',
    ],
    answerIndex: 1,
    explanation:
      'Gündüz farları, aracı gündüz ışığında öndeki trafiğe belirgin kılan görünürlük lambalarıdır; yolu aydınlatacak güçte değildir. Çoğu araçta DRL yanarken arka lambalar sönüktür; karanlıkta yalnızca DRL ile gitmek aracı arkadan görünmez yapar.',
    whyWrong: [
      'Yolu aydınlatma görevi kısa ve uzun farlarındır.',
      'DRL tüketimi artırmak için değil, görünürlük için vardır; plakayı plaka lambası aydınlatır.',
    ],
    objective: 'DRL amacını ve gece normal far açma gerekliliğini bilmek.',
    tags: ['gunduz-farlari', 'drl', 'gorunurluk'],
    review: 'draft',
    sourceRef: SRC,
  },
];
