/**
 * ÖZGÜN ilk yardım soruları — 6. genişletme (Program 2 · Faz 9). ROADMAP C.4/E.6.
 * Kaynak = Resmî temel ilk yardım rehberleri; KENDİ İFADEMİZLE. Uzman onayı gereklidir.
 */
import type { QuestionInput } from '@ea/content-schema';

const SRC = 'Resmî temel ilk yardım rehberleri (özgün ifade; uzman onayı gerekli)';

export const ILKYARDIM_QUESTIONS_6: QuestionInput[] = [
  {
    id: 'ilkyardim-601',
    subject: 'ilkyardim',
    topic: 'olay-yeri-guvenligi',
    difficulty: 'kolay',
    stem: 'Kaza yapan bir araca ilk ulaşan kişi, yaralıya dokunmadan önce kontağı kapatmayı neden ihmal etmemelidir?',
    options: [
      'Motorun ve elektrik sisteminin çalışır kalmasının kıvılcım ve yangın riski taşıması nedeniyle',
      'Aracın yakıt tüketimini durdurmak için',
      'Aracın radyosunun sesini kısmak için',
      'Yaralının koltuğunu geriye yatırabilmek için',
    ],
    answerIndex: 0,
    explanation:
      'Çalışır durumdaki motor ve elektrik devresi, dökülen yakıtı tutuşturabilecek kıvılcımlar üretebilir. Kontağın kapatılması bu riski azaltır ve olay yerini müdahale için daha güvenli hâle getirir.',
    whyWrong: [
      'Yakıt tasarrufu veya radyo sesi, kaza yerinde öncelikli bir kaygı değildir.',
      'Kontak kapatmanın amacı koltuğu ayarlamak değil, tutuşma riskini düşürmektir.',
    ],
    objective: 'Kontağın kapatılmasının yangın riskini azaltma amacını kavramak.',
    tags: ['olay-yeri-guvenligi', 'kontak', 'yangin-riski'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-602',
    subject: 'ilkyardim',
    topic: 'olay-yeri-guvenligi',
    difficulty: 'orta',
    stem: 'Kaza yerinde asfalta yayılmış yakıt kokusu alan ilk yardımcının aşağıdakilerden hangisini yapması yanlıştır?',
    options: [
      'Çevredekilerin sigara içmesine ve yakınlarda ateş yakılmasına izin vermemek',
      'Kokunun kaynağını bulmak için çakmakla etrafı aydınlatmak',
      'Yaralıları ve izleyicileri sızıntı bölgesinden uzaklaştırmak',
      'Kontağı kapatıp mümkünse aracın enerjisini kesmek',
    ],
    answerIndex: 1,
    explanation:
      'Yayılmış yakıt buharı küçük bir kıvılcımla bile tutuşabilir. Çakmak, kibrit veya sigara gibi açık ateş kaynakları bölgeye kesinlikle yaklaştırılmaz; kişiler uzaklaştırılır ve aracın enerjisi kesilir.',
    whyWrong: [
      'Sigara ve ateşe izin vermemek ile kişileri uzaklaştırmak doğru güvenlik önlemleridir.',
      'Kontağı kapatmak tutuşma riskini azaltan yerinde bir davranıştır.',
    ],
    objective: 'Yakıt sızıntısında ateş kaynaklarının uzak tutulması gerektiğini bilmek.',
    tags: ['olay-yeri-guvenligi', 'yakit-sizintisi', 'kivilcim'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-603',
    subject: 'ilkyardim',
    topic: 'iletisim-destek',
    difficulty: 'kolay',
    stem: 'Devrilen aracın içinde sıkışmış, bilinci açık ve korku içindeki bir sürücüye ilk yardımcının söyleyeceği en uygun söz hangisidir?',
    options: [
      'Hiç konuşmadan sessizce beklemek en doğrusudur',
      'Durumun çok kötü göründüğünü açıkça söylemek',
      'Yanında olduğunu, yardım ekiplerinin yolda olduğunu belirtip sakin kalmasını istemek',
      'Kendi başına çıkması için onu zorlamak',
    ],
    answerIndex: 2,
    explanation:
      'Sıkışmış ve korkmuş yaralıya, yalnız olmadığını ve yardımın geldiğini bilmek güven verir. İlk yardımcı sakin bir sesle yanında kalır, onu bilgilendirir ve moralini yüksek tutmaya çalışır.',
    whyWrong: [
      'Sessiz kalmak, korku içindeki yaralının paniğini artırabilir.',
      'Durumu olumsuz anlatmak veya zorla çıkarmaya çalışmak hem korkuyu hem yaralanma riskini büyütür.',
    ],
    objective: 'Sıkışmış bilinçli yaralıyla güven verici iletişimi bilmek.',
    tags: ['iletisim-destek', 'sikisma', 'sakinlestirme'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-604',
    subject: 'ilkyardim',
    topic: 'arac-icinden-cikarma',
    difficulty: 'zor',
    stem: 'Bacağı pedal bölgesine sıkışmış, bilinci açık, solunumu ve dolaşımı düzenli bir sürücü için yangın veya patlama tehlikesi de yokken doğru yaklaşım hangisidir?',
    options: [
      'Sürücüyü kollarından çekerek zorla kurtarmak',
      'Sıkışan bölümü aracın kriko ve aletleriyle rastgele kaldırmaya çalışmak',
      'Sürücünün kemerini çözüp kendi çabasıyla çıkmasını beklemek',
      'Yaşamsal bir zorunluluk olmadığından kurtarmayı itfaiye ve 112’ye bırakmak, bu sürede yaralıyı izleyip sakin tutmak',
    ],
    answerIndex: 3,
    explanation:
      'Hayati bir tehlike yoksa sıkışmış yaralı zorla çıkarılmaz; kaba kurtarma girişimleri gizli kırıkları, damar ve sinir hasarını ağırlaştırabilir. Donanımlı ekipler beklenirken yaralının bilinci, solunumu ve dolaşımı izlenir ve o sakinleştirilir.',
    whyWrong: [
      'Çekmek veya aletle kaldırmaya çalışmak dokularda yeni hasara ve enkazın oynamasına yol açabilir.',
      'Sıkışmış yaralının kendi çabasıyla çıkması çoğu zaman mümkün değildir ve yaralanmayı derinleştirebilir.',
    ],
    objective: 'Sıkışmada yaşamsal zorunluluk yoksa kurtarmanın ekiplere bırakıldığını kavramak.',
    tags: ['arac-icinden-cikarma', 'sikisma', 'bekleme'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-605',
    subject: 'ilkyardim',
    topic: '112-iletisim',
    difficulty: 'kolay',
    stem: 'Kalabalık bir kaza yerinde ilk yardımcının 112’nin aranmasını sağlamak için en etkili davranışı hangisidir?',
    options: [
      'Kalabalıktan belirli bir kişiyi işaret ederek "Mavi montlu bey, lütfen 112’yi arayın" demek',
      'Genel olarak "biri ambulans çağırsın" diye bağırmak',
      'Herkesin kendiliğinden arayacağını varsaymak',
      'Aramayı bir süre erteleyip önce fotoğraf çekmek',
    ],
    answerIndex: 0,
    explanation:
      'Kalabalığa geneli hedefleyen bir seslenişte herkes başkasının arayacağını düşünüp kimse aramayabilir. Belirli bir kişiyi seçip doğrudan görevlendirmek, çağrının gerçekten yapılmasını sağlayan en güvenilir yoldur.',
    whyWrong: [
      'Genel bir çağrı sorumluluğun dağılmasına ve kimsenin harekete geçmemesine yol açabilir.',
      'Aramayı ertelemek veya herkesin arayacağını varsaymak yardımı geciktirir.',
    ],
    objective: 'Kalabalıkta belirli kişi görevlendirerek 112 aratmayı bilmek.',
    tags: ['112-iletisim', 'gorev-paylasimi', 'kalabalik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-606',
    subject: 'ilkyardim',
    topic: '112-iletisim',
    difficulty: 'kolay',
    stem: 'Yardım edebilecek birkaç kişinin bulunduğu bir kaza yerinde ilk yardımcının görevleri paylaştırması neden yararlıdır?',
    options: [
      'Kalabalık dağılıp herkes evine gitsin diye',
      'Yol güvenliği, 112 çağrısı ve yaralının bakımı gibi işlerin aynı anda ve düzenli yürütülmesini sağlamak için',
      'Sorumluluğu tamamen başkalarına bırakabilmek için',
      'Olayla ilgilenen kişi sayısını azaltmak için',
    ],
    answerIndex: 1,
    explanation:
      'Bir kişi yolu güvenceye alırken, bir başkası 112’yi arayabilir ve bir diğeri yaralının yanında kalabilir. Görevlerin belirli kişilere dağıtılması, işlerin karışmadan ve zaman kaybetmeden yapılmasını sağlar.',
    whyWrong: [
      'Amaç kalabalığı dağıtmak veya sorumluluktan kaçmak değildir.',
      'Görev paylaşımı ilgilenen kişi sayısını azaltmaz; katkıyı düzenler.',
    ],
    objective: 'Olay yerinde görev paylaşımının değerini kavramak.',
    tags: ['112-iletisim', 'gorev-paylasimi', 'organizasyon'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-607',
    subject: 'ilkyardim',
    topic: 'kask-cikarma',
    difficulty: 'kolay',
    stem: 'Kaza geçiren, kaskı başında olan ve bilinci açık, nefes alan bir motosiklet sürücüsünde kaskla ilgili genel kural nedir?',
    options: [
      'Kask hemen çıkarılır; başın rahat etmesi gerekir',
      'Kask yalnızca yaralı istediğinde çıkarılır',
      'Kask kural olarak çıkarılmaz; baş ve boyun kaskla birlikte hareketsiz tutulur',
      'Kaskın çenelik kayışı sıkılır',
    ],
    answerIndex: 2,
    explanation:
      'Kaskı çıkarma girişimi baş ve boynu oynatarak olası omurga yaralanmasını ağırlaştırabilir. Solunum sorunu gibi zorlayıcı bir neden yoksa kask çıkarılmaz; yaralı, baş-boyun ekseni korunacak biçimde hareketsiz tutulur ve 112 beklenir.',
    whyWrong: [
      'Kaskı gereksiz yere çıkarmak boyun omurlarına zarar verebilir.',
      'Kayışı sıkmak solunumu güçleştirebilir; kaskı çıkarma kararı yaralının isteğine bırakılmaz.',
    ],
    objective: 'Kaskın kural olarak çıkarılmadığını bilmek.',
    tags: ['kask-cikarma', 'omurga', 'motosiklet'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-608',
    subject: 'ilkyardim',
    topic: 'kask-cikarma',
    difficulty: 'zor',
    stem: 'Motosiklet sürücüsünün kaskı hangi durumda ve nasıl çıkarılabilir?',
    options: [
      'Yaralı ayağa kalkabiliyorsa, tek elle hızlıca çekilerek',
      'Yaralı kaskı sıcak bulduğunda, çenesinden yukarı doğru',
      'Her kazadan sonra, tek başına ve hızla',
      'Solunumu durmuş ve müdahale için gerekliyse, mümkünse iki kişiyle baş-boyun ekseni korunarak dikkatlice',
    ],
    answerIndex: 3,
    explanation:
      'Kaskı çıkarmayı haklı kılan durum, solunumun durması gibi yaşamsal bir müdahale zorunluluğudur. Bu zorunlu hâlde işlem tercihen iki kişiyle yapılır: biri baş-boyun eksenini sabit tutarken diğeri kaskı yavaşça açar. Böylece boynun oynaması en aza indirilir.',
    whyWrong: [
      'Tek elle hızlı çekiş veya çeneden yukarı zorlama, boyuna büyük zarar verir.',
      'Sıcaklık veya rutin uygulama, kaskı çıkarmak için geçerli bir neden değildir.',
    ],
    objective: 'Kask çıkarma istisnasını ve iki kişilik tekniği kavramak.',
    tags: ['kask-cikarma', 'istisna', 'iki-kisi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-609',
    subject: 'ilkyardim',
    topic: 'gogus-yaralanmasi',
    difficulty: 'orta',
    stem: 'Emniyet kemeri takılıyken direksiyona göğsünü çarpan bir sürücüde göğüs bölgesi değerlendirilirken öncelikle nelere bakılır?',
    options: [
      'Nefes alışının rahat olup olmadığına, göğüste ağrı, morarma ve nefeste artan sızıya',
      'Yalnızca cildin renginin değişip değişmediğine',
      'Yalnızca nabzının sayısına',
      'Yalnızca gözbebeklerinin büyüklüğüne',
    ],
    answerIndex: 0,
    explanation:
      'Direksiyon çarpması göğüs kafesini ve içindeki organları zorlayabilir. Solunumun zorlaşması, göğüste ağrı, morarma ve nefes alırken artan sızı önemli uyarı işaretleridir; bu bulgular varsa yaralı rahat bırakılıp 112 aranır.',
    whyWrong: [
      'Cilt rengi veya nabız sayısı tek başına göğüs yaralanmasını değerlendirmeye yetmez.',
      'Gözbebeği değerlendirmesi göğüs travmasının doğrudan göstergesi değildir.',
    ],
    objective: 'Direksiyon travmasında göğüs değerlendirmesinin öğelerini bilmek.',
    tags: ['gogus-yaralanmasi', 'direksiyon-travmasi', 'degerlendirme'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-610',
    subject: 'ilkyardim',
    topic: 'gogus-yaralanmasi',
    difficulty: 'orta',
    stem: 'Göğsünü çarpan, derin nefes aldığında ve öksürdüğünde bir tarafında keskin ağrı duyan bilinci açık yaralı için uygun yaklaşım hangisidir?',
    options: [
      'Yaralıya derin nefes egzersizi zorla yaptırmak',
      'Yaralıyı en rahat ettiği pozisyonda tutmak, gereksiz hareketten kaçınmak ve 112 aramak',
      'Ağrıyan bölgeye sertçe bastırıp masaj yapmak',
      'Yaralıyı sırtüstü düz yatırıp hareketsiz zorlamak',
    ],
    answerIndex: 1,
    explanation:
      'Nefeste ve öksürükte artan tek taraflı keskin ağrı, kaburga bölgesinde yaralanmayı düşündürür. Yaralı en rahat ettiği pozisyonda bırakılır, gereksiz yere hareket ettirilmez ve sağlık ekibi çağrılır.',
    whyWrong: [
      'Zorla nefes egzersizi ve bölgeye bastırmak ağrıyı ve olası hasarı artırır.',
      'Yaralıyı rahatsız eden bir pozisyona zorlamak solunumu güçleştirebilir.',
    ],
    objective: 'Kaburga yaralanması şüphesinde rahat pozisyon ve gözlemi bilmek.',
    tags: ['gogus-yaralanmasi', 'kaburga', 'pozisyon'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-611',
    subject: 'ilkyardim',
    topic: 'karin-yaralanmasi',
    difficulty: 'orta',
    stem: 'Kaza sonrası bir yolcunun karnında, emniyet kemerinin geçtiği hat boyunca kızarıklık ve çürük görülmesi ilk yardımcıya ne düşündürmelidir?',
    options: [
      'Kemerin çok gevşek takıldığını',
      'Yalnızca giysinin lekelendiğini',
      'Bu bölgenin darbe aldığını ve altındaki organlarda gizli bir yaralanma olabileceğini',
      'Yaralanmanın kesinlikle önemsiz olduğunu',
    ],
    answerIndex: 2,
    explanation:
      'Kemer izi biçiminde beliren kızarıklık ve çürük, o hat boyunca ciddi bir darbenin işaretidir. Dışarıdan yara görülmese bile karın içi organlarda gizli yaralanma olabilir; yaralı yakından izlenir ve durum 112’ye bildirilir.',
    whyWrong: [
      'Kemer izi genellikle kemerin görevini yaptığını gösterir; asıl önemli olan altındaki olası hasardır.',
      'İzi önemsiz saymak, gelişebilecek iç yaralanmanın gözden kaçmasına yol açar.',
    ],
    objective: 'Emniyet kemeri izini olası iç yaralanma işareti olarak yorumlamak.',
    tags: ['karin-yaralanmasi', 'kemer-izi', 'gizli-yaralanma'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-612',
    subject: 'ilkyardim',
    topic: 'karin-yaralanmasi',
    difficulty: 'orta',
    stem: 'Karnına künt darbe alan, bilinci açık ve karın kaslarını gergin tutan bir yaralıya hangi pozisyon karın kaslarının gevşemesine yardımcı olur?',
    options: [
      'Yüzükoyun yatış',
      'Ayakta dik durma',
      'Baş aşağıda, ayaklar yukarıda yatış',
      'Sırtüstü yatıp dizlerin altına destek konarak bacakların hafifçe bükülü tutulması',
    ],
    answerIndex: 3,
    explanation:
      'Sırtüstü yatarken dizlerin altına destek konup bacakların hafifçe bükülmesi karın duvarındaki gerilimi azaltır ve ağrıyı hafifletebilir. Yaralıya ağızdan bir şey verilmez ve 112 beklenir.',
    whyWrong: [
      'Yüzükoyun yatış ve ayakta durma karın kaslarını gerginleştirir.',
      'Baş aşağı pozisyon karın içi organlara bası yaparak durumu ağırlaştırabilir.',
    ],
    objective: 'Karın yaralanmasında rahatlatıcı pozisyonu bilmek.',
    tags: ['karin-yaralanmasi', 'pozisyon', 'kunt-travma'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-613',
    subject: 'ilkyardim',
    topic: 'ozel-durum-hamile',
    difficulty: 'kolay',
    stem: 'Kaza geçiren, ileri gebelikteki bilinci kapalı ama solunumu düzenli bir kadın için hangi yatış pozisyonu tercih edilir?',
    options: [
      'Sol tarafı üzerine yan yatış',
      'Sırtüstü düz yatış',
      'Yüzükoyun yatış',
      'Oturur pozisyon',
    ],
    answerIndex: 0,
    explanation:
      'İleri gebelikte solunumu olan bilinçsiz kadın, tercihen sol tarafı üzerine yan yatırılır. Bu pozisyon hem hava yolunu korur hem de rahmin büyük bir ana damara yaptığı basıyı azaltarak dolaşımı rahatlatır.',
    whyWrong: [
      'Sırtüstü düz yatış, ileri gebelikte büyük damara bası yaparak kan dönüşünü azaltabilir.',
      'Yüzükoyun ve oturur pozisyon bilinci kapalı yaralıda hava yolu güvenliği açısından uygun değildir.',
    ],
    objective: 'Gebe kazazedede sol yan yatış tercihini bilmek.',
    tags: ['ozel-durum-hamile', 'sol-yan-yatis', 'pozisyon'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-614',
    subject: 'ilkyardim',
    topic: 'ozel-durum-hamile',
    difficulty: 'zor',
    stem: 'İleri gebelikteki bir kazazedenin sırtüstü uzun süre yatırılmasının sakıncalı olmasının temel nedeni nedir?',
    options: [
      'Sırtüstü yatışın gebeye can sıkıntısı vermesi',
      'Büyüyen rahmin, kalbe kan döndüren büyük ana damara bası yaparak dolaşımı bozabilmesi',
      'Sırtüstü yatışın solunumu tamamen durdurması',
      'Bu pozisyonun kemik kırıklarına yol açması',
    ],
    answerIndex: 1,
    explanation:
      'İleri gebelikte sırtüstü yatıldığında büyüyen rahim, kalbe kan taşıyan büyük toplardamara baskı yapabilir; bu da kalbe dönen kanı azaltarak tansiyon düşmesine ve halsizliğe yol açar. Sol yan yatış bu basıyı hafifletir.',
    whyWrong: [
      'Sorun konforla ilgili değil, ana damara binen basıyla ilgilidir.',
      'Pozisyon solunumu tümüyle durdurmaz ve kendiliğinden kırık oluşturmaz.',
    ],
    objective: 'Gebede sol yan yatışın dolaşım gerekçesini kavramak.',
    tags: ['ozel-durum-hamile', 'ana-damar', 'dolasim'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-615',
    subject: 'ilkyardim',
    topic: 'ozel-durum-yasli',
    difficulty: 'orta',
    stem: 'Düşme sonucu yaralanan yaşlı bir kazazedeye yaklaşırken ilk yardımcının dikkat etmesi gereken noktalardan biri hangisidir?',
    options: [
      'Yaşlı olduğu için müdahaleyi gereksiz görmek',
      'Hızlı olmak adına yaralıyı sertçe hareket ettirmek',
      'Kemikleri daha kırılgan olabileceğinden bölgeyi nazik değerlendirmek ve net, sakin bir dille iletişim kurmak',
      'Yaralıya hiç bilgi vermeden işlem yapmak',
    ],
    answerIndex: 2,
    explanation:
      'İleri yaşta kemikler daha kolay kırılabilir; bu nedenle yaralı bölge nazikçe değerlendirilir ve gereksiz hareketten kaçınılır. İşitme veya algı zorluğu olabileceğinden ilk yardımcı sakin, net ve anlaşılır biçimde konuşur.',
    whyWrong: [
      'Yaşı gerekçe göstererek müdahaleyi ertelemek doğru değildir.',
      'Sert hareket ve bilgilendirmeden işlem, yaralanmayı ve kaygıyı artırır.',
    ],
    objective: 'Yaşlı kazazedeye nazik ve net yaklaşımı bilmek.',
    tags: ['ozel-durum-yasli', 'kirik-riski', 'iletisim'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-616',
    subject: 'ilkyardim',
    topic: 'ozel-durum-cocuk',
    difficulty: 'orta',
    stem: 'Kaza geçiren, korkmuş ve ağlayan küçük bir çocuğa müdahale ederken ilk yardımcının izleyeceği en uygun tutum hangisidir?',
    options: [
      'Çocuğu susması için azarlamak',
      'Yanındaki ebeveyninden hemen uzaklaştırmak',
      'Çocuğa hiç konuşmadan hızlıca işlem yapmak',
      'Mümkünse ebeveyniyle temasını koruyup göz hizasına inerek yumuşak bir sesle sakinleştirmek',
    ],
    answerIndex: 3,
    explanation:
      'Korkmuş bir çocuk için güven duygusu çok önemlidir. İlk yardımcı mümkünse çocuğu ebeveyninden ayırmaz, göz hizasına inip yumuşak ve güven veren bir sesle konuşarak korkusunu azaltmaya çalışır; bu, iş birliğini kolaylaştırır.',
    whyWrong: [
      'Azarlamak veya ebeveynden ayırmak çocuğun korkusunu ve direncini artırır.',
      'Hiç konuşmadan işlem yapmak güven ilişkisini engeller.',
    ],
    objective: 'Çocuk kazazedede sakinleştirici, ebeveyn destekli yaklaşımı bilmek.',
    tags: ['ozel-durum-cocuk', 'sakinlestirme', 'ebeveyn'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-617',
    subject: 'ilkyardim',
    topic: 'sok',
    difficulty: 'kolay',
    stem: 'Ağır yaralı ve susadığını söyleyen bir kazazede ısrarla su isterse ilk yardımcı ne yapmalıdır?',
    options: [
      'Ağızdan su vermez; gerekirse yalnızca dudaklarını ıslak bir bezle nemlendirebilir',
      'Bol miktarda soğuk su içirmelidir',
      'Su yerine meyve suyu içirmelidir',
      'İstediği kadar su içmesine izin vermelidir',
    ],
    answerIndex: 0,
    explanation:
      'Ağır yaralıya ağızdan sıvı vermek; olası bir ameliyatı geciktirebilir, kusmaya ve bilinç bulanıksa boğulmaya yol açabilir. Susuzluk hissini hafifletmek için en fazla dudaklar nemli bir bezle ıslatılır; su içirilmez.',
    whyWrong: [
      'Bol su veya meyve suyu içirmek kusma ve tıbbi girişimi geciktirme riski taşır.',
      'Yaralının istediği kadar içmesine izin vermek bu riskleri daha da büyütür.',
    ],
    objective: 'Yaralıya ağızdan su verilmemesi kuralını bilmek.',
    tags: ['sok', 'agizdan-verme', 'susuzluk'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-618',
    subject: 'ilkyardim',
    topic: 'sok',
    difficulty: 'orta',
    stem: 'Soğuk ve nemli bir asfalt üzerinde yatan yaralının vücut ısısını korumak için ilk yardımcı hangisini yaparsa daha etkili olur?',
    options: [
      'Yalnızca yüzünü örtmek',
      'Hem üstünü örtmek hem de mümkünse altına bir örtü sererek zeminden ısı kaybını azaltmak',
      'Sadece üstünü örtmek, altını açık bırakmak',
      'Örtüyü sıkıca bağlayıp yaralıyı hareketsiz kılmak',
    ],
    answerIndex: 1,
    explanation:
      'Vücut, temas ettiği soğuk zemine de ısı verir. Yalnızca üstü örtülen yaralı alttan üşümeye devam eder; bu yüzden mümkünse yaralının altına da bir örtü serilerek zeminden ısı kaybı azaltılır. Isının korunması şok tablosunu hafifletmeye yardım eder.',
    whyWrong: [
      'Yalnızca yüzü veya yalnızca üstü örtmek alttan devam eden ısı kaybını önlemez.',
      'Örtüyü sıkıca bağlayıp hareketi engellemek örtünün amacı değildir; gerekirse yaralı yine değerlendirilebilmelidir.',
    ],
    objective: 'Soğukta zeminden ısı kaybını önlemeyi kavramak.',
    tags: ['sok', 'isi-kaybi', 'ortme'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-619',
    subject: 'ilkyardim',
    topic: 'sok',
    difficulty: 'zor',
    stem: 'Şok belirtileri olan bir yaralıda bacakları hafifçe yükseltme (şok pozisyonu) hangi durumda uygulanmaz?',
    options: [
      'Yaralının cildi soluk ve terliyse',
      'Yaralının nabzı hızlıysa',
      'Yaralıda bacak kırığı şüphesi, nefes güçlüğü ya da ciddi kafa/göğüs yaralanması varsa',
      'Yaralı üşüyorsa',
    ],
    answerIndex: 2,
    explanation:
      'Bacakları yükseltmek bazı şok tablolarında dolaşıma yardımcı olabilir; ancak bacakta kırık şüphesi varsa hareket zarar verir, nefes güçlüğü veya ciddi kafa/göğüs yaralanması varsa bu pozisyon durumu ağırlaştırabilir. Bu hâllerde bacak yükseltilmez.',
    whyWrong: [
      'Soluk-terli cilt, hızlı nabız ve üşüme şokun bulgularıdır; pozisyon kararını tek başına belirlemez.',
      'Asıl belirleyici, bacakta kırık ya da nefesi/beyni etkileyen ek yaralanma bulunup bulunmadığıdır.',
    ],
    objective: 'Şok pozisyonunun uygulanmadığı istisnaları bilmek.',
    tags: ['sok', 'sok-pozisyonu', 'istisna'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-620',
    subject: 'ilkyardim',
    topic: 'zehirlenme',
    difficulty: 'kolay',
    stem: 'Karbonmonoksit gazının özellikle tehlikeli olmasının başlıca nedeni nedir?',
    options: [
      'Keskin bir kokusuyla hemen fark edilmesi',
      'Yalnızca açık havada birikmesi',
      'Sadece çok yüksek ısıda oluşması',
      'Renksiz ve kokusuz olması nedeniyle varlığının çoğu zaman fark edilememesi',
    ],
    answerIndex: 3,
    explanation:
      'Karbonmonoksit renksiz ve kokusuz olduğundan solunduğu hâlde genellikle fark edilmez. Kişi baş ağrısı, baş dönmesi ve bulantı gibi belirtileri anlamlandıramadan giderek ağırlaşabilir; bu yüzden sinsi ve tehlikeli bir gazdır.',
    whyWrong: [
      'Gazın kokusu olmadığından koku yoluyla erken uyarı vermez.',
      'Kapalı ortamlarda birikir ve oluşumu yalnızca çok yüksek ısıya bağlı değildir.',
    ],
    objective: 'Karbonmonoksitin renksiz-kokusuz oluşunun riskini bilmek.',
    tags: ['zehirlenme', 'karbonmonoksit', 'renksiz-kokusuz'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-621',
    subject: 'ilkyardim',
    topic: 'zehirlenme',
    difficulty: 'orta',
    stem: 'Kapalı bir mekânda bulunan birden fazla kişide aynı anda baş ağrısı, baş dönmesi ve bulantı başlarsa ilk yardımcı öncelikle neyden şüphelenmeli ve ne yapmalıdır?',
    options: [
      'Ortak bir karbonmonoksit kaynağından; kişileri hızla temiz havaya çıkarıp ortamı havalandırmaktan ve 112’yi aramaktan',
      'Yiyecek zehirlenmesinden; herkese su içirmekten',
      'Grip salgınından; kişileri aynı odada dinlendirmekten',
      'Uykusuzluktan; perdeleri kapatıp odayı karartmaktan',
    ],
    answerIndex: 0,
    explanation:
      'Aynı kapalı ortamdaki birden çok kişinin eş zamanlı olarak baş ağrısı, baş dönmesi ve bulantı yaşaması karbonmonoksit zehirlenmesini akla getirmelidir. Kişiler derhâl temiz havaya çıkarılır, ortam havalandırılır ve 112 aranır.',
    whyWrong: [
      'Ortak ve ani belirtiler yiyecek zehirlenmesi ya da gribe göre çok daha çok gaz kaynağını düşündürür.',
      'Kişileri aynı ortamda tutmak veya odayı karartmak gaz solumaya devam etmelerine yol açar.',
    ],
    objective: 'Aynı ortamda ortak belirtilerin karbonmonoksiti düşündürdüğünü kavramak.',
    tags: ['zehirlenme', 'karbonmonoksit', 'tahliye'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-622',
    subject: 'ilkyardim',
    topic: 'zehirlenme',
    difficulty: 'kolay',
    stem: 'Bir ilaç ya da kimyasal maddeyle zehirlendiğinden şüphelenilen kişide, maddenin kutusunu veya şişesini saklamak neden önemlidir?',
    options: [
      'Daha sonra iade edip ücretini geri almak için',
      'Hangi maddenin ne kadar alındığının belirlenmesine yardımcı olarak sağlık ekibinin doğru tedaviyi seçmesini kolaylaştırmak için',
      'Kutuyu hatıra olarak saklamak için',
      'Zehirlenmenin ciddi olmadığını kanıtlamak için',
    ],
    answerIndex: 1,
    explanation:
      'İçilen ya da yutulan maddenin kutusu, şişesi veya varsa kusmuk örneği, hangi maddeyle karşılaşıldığını ve olası miktarı gösterir. Bu bilgi sağlık ekibinin doğru ve hızlı tedavi planlamasına yardımcı olur; bu yüzden saklanıp yaralıyla birlikte gönderilir.',
    whyWrong: [
      'Kutuyu saklamanın amacı iade veya hatıra değildir.',
      'Kutu, zehirlenmenin önemsizliğini kanıtlamak için değil, maddeyi tanımlamak için tutulur.',
    ],
    objective: 'Zehir kaynağı ambalajının tanı için saklandığını bilmek.',
    tags: ['zehirlenme', 'ilac-kutusu', 'madde-tespiti'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-623',
    subject: 'ilkyardim',
    topic: 'zehirlenme',
    difficulty: 'orta',
    stem: 'Bir çocuğun büyüklere ait bir ilaçtan yuttuğu fark edildiğinde, çocuğun bilinci açıksa ilk yardımcı ne yapmalıdır?',
    options: [
      'Çocuğu parmakla veya tuzlu suyla kusturmaya çalışmak',
      'Bir şey olmadığını düşünüp beklemek',
      '112’yi aramak, ilaç kutusunu yanına almak ve kusturmaya çalışmadan yönlendirmeyi beklemek',
      'Çocuğa bol süt içirip uyutmak',
    ],
    answerIndex: 2,
    explanation:
      'İlaç yutan çocukta ilk yardımcı kendi başına kusturmaya çalışmaz; bazı maddeler geri gelirken daha çok zarar verebilir. Doğru davranış 112’yi aramak, alınan ilacın kutusunu bulundurmak ve verilen yönlendirmeye uymaktır.',
    whyWrong: [
      'Kusturma girişimi ve süt içirme, bazı maddelerde tabloyu ağırlaştırabilir.',
      'Beklemek, hızla gelişebilecek belirtiler karşısında değerli zamanı kaybettirir.',
    ],
    objective: 'İlaç yutan çocukta kusturmadan 112’ye başvurmayı bilmek.',
    tags: ['zehirlenme', 'cocuk', 'ilac'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-624',
    subject: 'ilkyardim',
    topic: 'bogulma-tikanma',
    difficulty: 'kolay',
    stem: 'Boğazına lokma kaçan ama güçlü biçimde öksürebilen, konuşabilen bir kişiye ilk yardımcı ne yapmalıdır?',
    options: [
      'Hemen sırtına kuvvetli vurular yapmak',
      'Öksürmesini engelleyip su içirmek',
      'Karnına hemen bası uygulamak',
      'Öksürmesini engellemeden onu öksürmeye teşvik etmek ve yakından izlemek',
    ],
    answerIndex: 3,
    explanation:
      'Öksürebilen ve konuşabilen kişide hava yolu kısmen açıktır; öksürük cismi çıkarmanın en etkili yoludur. İlk yardımcı bu doğal çabaya karışmaz, kişiyi öksürmeye teşvik eder ve durumun kötüleşip kötüleşmediğini izler.',
    whyWrong: [
      'Kısmi tıkanmada sırta vurma veya karına bası, cismi tam tıkanmaya çevirebilir.',
      'Öksürüğü engellemek veya su içirmek durumu ağırlaştırabilir.',
    ],
    objective: 'Kısmi tıkanmada öksürüğe müdahale edilmediğini bilmek.',
    tags: ['bogulma-tikanma', 'kismi-tikanma', 'oksuruk'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-625',
    subject: 'ilkyardim',
    topic: 'bogulma-tikanma',
    difficulty: 'orta',
    stem: 'Başta öksürebilen bir kişide öksürük giderek zayıflar, sesi kesilir ve nefes alamaz duruma gelirse bu değişiklik neyi gösterir ve ne yapılır?',
    options: [
      'Kısmi tıkanmanın tam tıkanmaya dönüştüğünü; artık etkili müdahaleye (sırt vuruları ve karına bası) geçilmesi gerektiğini',
      'Kişinin iyileştiğini; müdahaleye gerek olmadığını',
      'Kişinin yorulduğunu; oturtup dinlendirmek gerektiğini',
      'Sadece heyecanlandığını; su içirmek gerektiğini',
    ],
    answerIndex: 0,
    explanation:
      'Öksürüğün zayıflaması, sesin kesilmesi ve nefes alamama, hava yolunun artık tam tıkandığını gösterir. Bu noktada kişi cismi kendi çabasıyla çıkaramaz; etkili müdahale olan sırt vuruları ve karına bası uygulamasına geçilir, gerekirse 112 aranır.',
    whyWrong: [
      'Belirtiler iyileşmeyi değil, tablonun ağırlaştığını gösterir.',
      'Su içirmek veya yalnızca dinlendirmek tam tıkanmada hayatı tehlikeye atar.',
    ],
    objective: 'Kısmi tıkanmanın tam tıkanmaya dönüşümünü tanıyıp müdahaleye geçmeyi bilmek.',
    tags: ['bogulma-tikanma', 'tam-tikanma', 'gecis'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-626',
    subject: 'ilkyardim',
    topic: 'hava-yolu',
    difficulty: 'orta',
    stem: 'Bilinci kapalı, sırtüstü yatan bir kişide hava yolunun tıkanmasına en sık yol açan neden aşağıdakilerden hangisidir?',
    options: [
      'Gözlerin kapalı olması',
      'Gevşeyen dil kökünün geriye kayarak hava yolunu kapatması',
      'Kolların iki yana açık durması',
      'Ayakların birbirine değmesi',
    ],
    answerIndex: 1,
    explanation:
      'Bilinç kaybında kaslar gevşer; sırtüstü yatan kişide dil kökü geriye doğru kayarak hava yolunu kapatabilir. Bu yüzden bilinci kapalı kişide hava yolunu açmak için baş geri-çene yukarı konumu verilir.',
    whyWrong: [
      'Göz kapaklarının veya kol-bacak duruşunun hava yolu açıklığıyla ilgisi yoktur.',
      'Tıkanmanın temel nedeni bu ayrıntılar değil, geriye kayan dil köküdür.',
    ],
    objective: 'Bilinç kaybında dil kökünün hava yolunu tıkadığını kavramak.',
    tags: ['hava-yolu', 'dil-koku', 'bilinc-kaybi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-627',
    subject: 'ilkyardim',
    topic: 'hava-yolu',
    difficulty: 'kolay',
    stem: 'Bilinci kapalı bir yaralıda baş geri-çene yukarı hareketinin temel amacı nedir?',
    options: [
      'Yaralının uykuya dalmasını sağlamak',
      'Yaralının başını ısıtmak',
      'Geriye kaymış dil kökünü öne alarak hava yolunu açmak',
      'Boyun kaslarını çalıştırmak',
    ],
    answerIndex: 2,
    explanation:
      'Bir el alına, diğer elin parmakları çene kemiğinin altına konularak baş hafifçe geriye eğilir ve çene yukarı kaldırılır. Bu hareket dili öne alarak hava yolunu açar ve solunumun değerlendirilmesini kolaylaştırır.',
    whyWrong: [
      'Amaç uyutmak veya ısıtmak değildir.',
      'Hareketin hedefi kas çalıştırmak değil, hava yolunu açık tutmaktır.',
    ],
    objective: 'Baş geri-çene yukarı manevrasının amacını bilmek.',
    tags: ['hava-yolu', 'bas-geri-cene-yukari', 'acma'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-628',
    subject: 'ilkyardim',
    topic: 'hava-yolu',
    difficulty: 'zor',
    stem: 'Boyun (omurga) yaralanması şüphesi olan bilinci kapalı bir yaralıda hava yolunu açarken ilk yardımcı neye özen gösterir?',
    options: [
      'Başı olabildiğince çok geriye atmaya',
      'Başı sağa sola çevirerek yolu genişletmeye',
      'Yaralıyı oturtarak başını öne eğmeye',
      'Boynu mümkün olduğunca az oynatarak, çeneyi öne-yukarı kaldırma ağırlıklı biçimde hava yolunu açmaya',
    ],
    answerIndex: 3,
    explanation:
      'Omurga yaralanması şüphesinde başı fazla geriye atmak boyuna zarar verebilir. Bu nedenle hava yolu, boyun en az oynatılarak ve çene öne-yukarı kaldırılarak açılmaya çalışılır; öncelik hem solunumu sağlamak hem de omuriliği korumaktır.',
    whyWrong: [
      'Başı çok geriye atmak veya sağa sola çevirmek boyun yaralanmasını ağırlaştırabilir.',
      'Bilinci kapalı yaralıyı oturtup başını öne eğmek hava yolu güvenliğini bozar.',
    ],
    objective: 'Omurga şüphesinde boynu koruyarak hava yolu açmayı kavramak.',
    tags: ['hava-yolu', 'omurga-suphesi', 'cene-kaldirma'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-629',
    subject: 'ilkyardim',
    topic: 'tyd-degerlendirme',
    difficulty: 'orta',
    stem: 'Yerde hareketsiz yatan bir kişiye ulaşan ilk yardımcı, olay yeri güvenliğini sağladıktan sonra ilk olarak hangi sırayı izler?',
    options: [
      'Önce bilinç durumunu kontrol eder, ardından hava yolunu açıp solunumu değerlendirir',
      'Önce kanamaları sarar, sonra bilincine bakar',
      'Önce yaralının cebindeki kimliğine bakar',
      'Önce yaralıyı ayağa kaldırmayı dener',
    ],
    answerIndex: 0,
    explanation:
      'Değerlendirmede öncelik yaşamsal işlevlerdir: ilk yardımcı önce kişinin bilinçli olup olmadığını kontrol eder, yanıt yoksa hava yolunu açıp solunumu değerlendirir. Bu sıralama, en hayati sorunların önce fark edilmesini sağlar.',
    whyWrong: [
      'Kimlik bakmak veya yaralıyı ayağa kaldırmak yaşamsal değerlendirmenin önüne geçmez.',
      'Kanamaya müdahale önemlidir ama önce bilinç ve solunum gibi hayati işlevler güvenceye alınır.',
    ],
    objective: 'Değerlendirmede bilinç-solunum sırasını bilmek.',
    tags: ['tyd-degerlendirme', 'bilinc', 'solunum'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-630',
    subject: 'ilkyardim',
    topic: 'kanama',
    difficulty: 'kolay',
    stem: 'Atardamar kanamasını dış görünümünden tanımaya yarayan tipik özellik hangisidir?',
    options: [
      'Koyu renkli kanın yavaşça sızması',
      'Açık-parlak kırmızı kanın kalp atışıyla uyumlu biçimde fışkırması',
      'Yalnızca cildin yüzeyinde nokta nokta kanama olması',
      'Hiç kan görülmemesi',
    ],
    answerIndex: 1,
    explanation:
      'Atardamar kanamasında oksijenden zengin, açık-parlak kırmızı kan, kalbin her atışıyla uyumlu olarak fışkırır. Bu görünüm, kanın daha koyu ve sürekli sızdığı toplardamar kanamasından ayırt edilmesini sağlar; hızlı kan kaybı riski taşıdığından acildir.',
    whyWrong: [
      'Koyu renkli ve sızıntı şeklindeki akış toplardamar kanamasına özgüdür.',
      'Nokta nokta yüzeysel kanama kılcal damar kanamasını tanımlar; kanın görülmemesi ise dış kanama değildir.',
    ],
    objective: 'Atardamar kanamasının görünümünü tanımak.',
    tags: ['kanama', 'atardamar', 'gorunum'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-631',
    subject: 'ilkyardim',
    topic: 'kanama',
    difficulty: 'zor',
    stem: 'Hayati bir kanamayı durdurmak için zorunlu olarak turnike uygulayan ilk yardımcı, uygulama saatini not ettikten sonra bu bilgiyi nerede belirtmelidir?',
    options: [
      'Kimseye söylemeden aklında tutmalıdır',
      'Turnikenin altına gizlemelidir',
      'Yaralının görünür bir yerine (örneğin alnına) yazarak veya bir kâğıtla yaralının üzerine iliştirerek belirtmelidir',
      'Yalnızca kendi telefonuna kaydetmelidir',
    ],
    answerIndex: 2,
    explanation:
      'Turnikenin ne zaman uygulandığı, uzvun ne kadar süredir kansız kaldığını gösteren hayati bir bilgidir. Bu saat, yaralıyı devralacak ekibin kolayca görebileceği bir yere (örneğin alına) yazılır veya üzerine iliştirilir; böylece bilgi yaralıyla birlikte taşınır.',
    whyWrong: [
      'Bilgiyi yalnızca akılda tutmak veya telefona kaydetmek, ilk yardımcı ayrıldığında saatin kaybolmasına yol açar.',
      'Turnikenin altına gizlenen bir not, devralan ekip tarafından görülmez.',
    ],
    objective: 'Turnike saatinin yaralı üzerinde görünür şekilde belirtildiğini bilmek.',
    tags: ['kanama', 'turnike', 'saat-notu'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-632',
    subject: 'ilkyardim',
    topic: 'kanama',
    difficulty: 'kolay',
    stem: 'Zorunlu olarak turnike uygulandıktan sonra ilk yardımcının aşağıdakilerden hangisini yapması doğrudur?',
    options: [
      'Turnikeyi belirli aralıklarla gevşetip yeniden sıkmak',
      'Turnikeyi tamamen çıkarıp yalnızca sargıyla değiştirmek',
      'Turnikeyi bir örtüyle örtüp gözden gizlemek',
      'Turnikeyi sağlık ekibi devralana kadar açmadan yerinde tutmak ve saatini bildirmek',
    ],
    answerIndex: 3,
    explanation:
      'Turnike, hayati kanamayı durdurmak için son çare olarak uygulanır ve ilk yardımcı tarafından gevşetilmez. Kanamayı yeniden başlatmamak için sağlık ekibi devralana kadar yerinde bırakılır; uygulama saati mutlaka ekibe bildirilir.',
    whyWrong: [
      'Turnikeyi gevşetip sıkmak veya çıkarmak, kontrol altına alınan hayati kanamayı yeniden başlatabilir.',
      'Turnikenin örtülerek gizlenmesi, ekibin onu fark etmesini ve süreyi bilmesini engeller.',
    ],
    objective: 'Turnikenin ekip devralana kadar gevşetilmediğini bilmek.',
    tags: ['kanama', 'turnike', 'gevsetmeme'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-633',
    subject: 'ilkyardim',
    topic: 'uzuv-kopmasi',
    difficulty: 'orta',
    stem: 'Kaza sonucu kopan bir uzvun sağlık kuruluşuna ulaştırılmasında doğru yöntem hangisidir?',
    options: [
      'Kopan parçayı temiz bir beze sarıp bir poşete koymak, o poşeti de içinde buz-su bulunan ikinci bir kaba yerleştirmek',
      'Kopan parçayı doğrudan buzun içine gömmek',
      'Kopan parçayı sıcak suya batırmak',
      'Kopan parçayı açıkta, yaralının yanında taşımak',
    ],
    answerIndex: 0,
    explanation:
      'Kopan uzuv önce temiz bir beze sarılıp su geçirmez bir poşete konur; bu poşet de içinde buz ve su bulunan ikinci bir kaba yerleştirilir. Bu "torba içinde torba" yöntemi, dokuyu soğuk tutarken doğrudan buzla temasını da engeller.',
    whyWrong: [
      'Uzvu doğrudan buza gömmek dokuda soğuk hasarına yol açar.',
      'Sıcak su veya açıkta taşımak dokunun bozulmasını hızlandırır.',
    ],
    objective: 'Kopan uzuvda torba içinde torba yöntemini bilmek.',
    tags: ['uzuv-kopmasi', 'torba-icinde-torba', 'nakil'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-634',
    subject: 'ilkyardim',
    topic: 'uzuv-kopmasi',
    difficulty: 'orta',
    stem: 'Kopan bir uzvun doğrudan buza ya da suya değdirilmemesinin nedeni nedir?',
    options: [
      'Uzvun ağırlaşacağı için',
      'Doğrudan buzun soğuk hasarına, suyun ise şişme ve doku bozulmasına yol açarak dokunun yeniden dikilme şansını azaltabilmesi',
      'Buzun uzvu görünmez kılması nedeniyle',
      'Suyun uzvu ısıtması nedeniyle',
    ],
    answerIndex: 1,
    explanation:
      'Kopan uzuv doğrudan buza değerse dokular soğuk hasarı görür; doğrudan suya batırılırsa şişer ve bozulur. Her iki durum da dokunun yeniden dikilme şansını azaltır. Bu yüzden uzuv beze ve poşete sarılarak buzlu kaptan yalıtılır.',
    whyWrong: [
      'Sorun uzvun ağırlığı veya görünürlüğü değildir.',
      'Su uzvu ısıtmaz; asıl sakınca dokunun bozulup nakil şansının düşmesidir.',
    ],
    objective: 'Kopan uzvun buz/su ile doğrudan temasının sakıncasını kavramak.',
    tags: ['uzuv-kopmasi', 'doku-korumasi', 'nakil'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-635',
    subject: 'ilkyardim',
    topic: 'yanik',
    difficulty: 'kolay',
    stem: 'Yanan bölgeye yapışmış giysi parçalarıyla ilgili doğru uygulama hangisidir?',
    options: [
      'Yapışan giysi zorla çekilerek çıkarılır',
      'Yapışan giysi makasla kesilerek yanık üzerinden sıyrılır',
      'Yapışan giysi yerinde bırakılır; yalnızca gevşek olan ve yanık bölgesine yapışmamış giysiler çıkarılır',
      'Yapışan giysi ıslatılıp ovularak çıkarılır',
    ],
    answerIndex: 2,
    explanation:
      'Yanığa yapışmış giysiyi çekmek, alttaki hasarlı cildi de koparıp yarayı derinleştirir ve enfeksiyon riskini artırır. Bu yüzden yapışan kısım yerinde bırakılır; yalnızca yaraya yapışmamış gevşek giysiler dikkatlice uzaklaştırılır.',
    whyWrong: [
      'Yapışan giysiyi çekmek, kesmek veya ovarak sıyırmak cilt hasarını büyütür.',
      'Islatıp ovmak da yapışan dokuyu zedeleyebilir; giysi yerinde bırakılmalıdır.',
    ],
    objective: 'Yanığa yapışmış giysinin çıkarılmadığını bilmek.',
    tags: ['yanik', 'yapisan-giysi', 'yara-korumasi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-636',
    subject: 'ilkyardim',
    topic: 'yanik',
    difficulty: 'kolay',
    stem: 'Yanık sonrası ciltte oluşan su toplaması (bül) ile ilgili doğru davranış hangisidir?',
    options: [
      'Bül iğneyle delinip suyu boşaltılır',
      'Bül sıkılarak söndürülür',
      'Bülün üzeri diş macunuyla kapatılır',
      'Bül patlatılmadan olduğu gibi bırakılır; üzeri temiz ve gevşek bir örtüyle korunur',
    ],
    answerIndex: 3,
    explanation:
      'Yanıkta oluşan su toplaması, altındaki hassas cildi mikroplardan koruyan doğal bir örtüdür. Patlatıldığında bu koruma kalkar ve enfeksiyon riski artar. Bu yüzden bül patlatılmaz; bölge temiz, gevşek bir örtüyle korunur.',
    whyWrong: [
      'Bülü delmek, sıkmak veya patlatmak enfeksiyon kapısını açar.',
      'Yanığa diş macunu gibi maddeler sürmek yarayı kirletir ve değerlendirmeyi zorlaştırır.',
    ],
    objective: 'Yanık bülünün patlatılmadığını bilmek.',
    tags: ['yanik', 'bul', 'enfeksiyon'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-637',
    subject: 'ilkyardim',
    topic: 'yanik',
    difficulty: 'kolay',
    stem: 'Yanık bölgesine diş macunu, yoğurt veya salça gibi maddeler sürmek neden yanlıştır?',
    options: [
      'Yarayı kirletip enfeksiyon riskini artırdıkları ve yara değerlendirmesini zorlaştırdıkları için',
      'Bu maddeler yanığı hemen iyileştirdiği için',
      'Cildi fazla soğuttukları için',
      'Yanığın rengini değiştirdikleri için',
    ],
    answerIndex: 0,
    explanation:
      'Halk arasında yaygın olsa da yanığa diş macunu, yoğurt veya salça sürmek yarayı kirletir, enfeksiyon riskini artırır ve sağlık ekibinin yarayı doğru değerlendirmesini güçleştirir. Doğru yaklaşım yanığı akan suyla soğutmak ve temiz bir bezle örtmektir.',
    whyWrong: [
      'Bu maddelerin yanığı iyileştirdiği doğru değildir; tam tersine zarar verirler.',
      'Sorun soğutma veya renk değil, kirlenme ve enfeksiyon riskidir.',
    ],
    objective: 'Yanığa halk usulü maddeler sürülmemesi gerektiğini bilmek.',
    tags: ['yanik', 'yanlis-uygulama', 'enfeksiyon'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-638',
    subject: 'ilkyardim',
    topic: 'yanik',
    difficulty: 'orta',
    stem: 'Vücudun geniş bir bölümünü kaplayan büyük bir yanıkta ilk yardımcının dikkat etmesi gereken önemli bir risk nedir?',
    options: [
      'Yaralının hemen acıkacağı',
      'Sıvı kaybı ve ısı kaybının şok tablosuna yol açabilmesi; bu nedenle bölgenin temiz bezle örtülüp yaralının 112’ye yönlendirilmesi',
      'Yanığın kendiliğinden geçeceği',
      'Yalnızca cildin renginin değişeceği',
    ],
    answerIndex: 1,
    explanation:
      'Geniş yanıklarda vücut, hasarlı cilt yüzeyinden hem sıvı hem de ısı kaybeder; bu da şok gelişimine zemin hazırlar. İlk yardımcı yanık bölgesini temiz bir bezle örterek ısı ve sıvı kaybını sınırlar, yaralıyı hareketsiz tutar ve hızla 112’ye yönlendirir.',
    whyWrong: [
      'Geniş yanık kendiliğinden geçmez; ciddi ve acil bir durumdur.',
      'Sorun yalnızca cilt rengi ya da açlık değil, sıvı-ısı kaybına bağlı şok riskidir.',
    ],
    objective: 'Geniş yanıkta sıvı-ısı kaybı ve şok riskini kavramak.',
    tags: ['yanik', 'genis-yanik', 'sok-riski'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-639',
    subject: 'ilkyardim',
    topic: 'sicak-carpmasi',
    difficulty: 'orta',
    stem: 'Bunaltıcı sıcak bir ortamda uzun süre kaldıktan sonra başı dönen, halsizleşen ve fazla terleyen bir kişiye ilk yardım olarak ne yapılır?',
    options: [
      'Kişiyi sıcak ortamda tutup üstünü kalın giysilerle örtmek',
      'Kişiyi güneş altında yürütmek',
      'Kişiyi serin ve gölge bir yere almak, sıkan giysilerini gevşetmek ve ıslak bezle serinletmek',
      'Kişiye sıcak içecek verip battaniyeye sarmak',
    ],
    answerIndex: 2,
    explanation:
      'Sıcağa bağlı halsizlikte öncelik vücudu serinletmektir. Kişi serin, gölge bir yere alınır, sıkan giysileri gevşetilir ve ıslak bez ya da hava akımıyla serinletilir; bilinci açık ve güvenle yutabiliyorsa küçük yudumlarla su verilebilir.',
    whyWrong: [
      'Kişiyi sıcakta tutmak, kalın örtmek veya sıcak içecek vermek vücut ısısını daha da artırır.',
      'Güneş altında yürütmek durumu ağırlaştırır.',
    ],
    objective: 'Sıcağa bağlı rahatsızlıkta serinletme adımlarını bilmek.',
    tags: ['sicak-carpmasi', 'serinletme', 'golge'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-640',
    subject: 'ilkyardim',
    topic: 'sicak-carpmasi',
    difficulty: 'orta',
    stem: 'Sıcak çarpması yaşayan bir kişiye su verilmesiyle ilgili doğru yaklaşım hangisidir?',
    options: [
      'Bilinci nasıl olursa olsun bol ve hızlı su içirilir',
      'Su yerine yalnızca gazlı içecek verilir',
      'Kişi bilincini yitirse bile ağzına su dökülür',
      'Kişinin bilinci açık ve güvenle yutabiliyorsa küçük yudumlarla su verilebilir; bilinci bulanıksa ağızdan sıvı verilmez',
    ],
    answerIndex: 3,
    explanation:
      'Sıvı kaybını gidermek önemlidir; ancak ağızdan su yalnızca bilinci açık ve güvenle yutabilen kişiye, küçük yudumlar hâlinde verilir. Bilinci bulanık veya kapalı kişiye ağızdan sıvı verilmez; çünkü sıvı soluk borusuna kaçabilir.',
    whyWrong: [
      'Bilinç durumuna bakmadan bol ve hızlı su vermek boğulma riski taşır.',
      'Bilinci kapalı kişinin ağzına su dökmek son derece tehlikelidir.',
    ],
    objective: 'Sıcak çarpmasında su vermenin bilinç koşuluna bağlı olduğunu bilmek.',
    tags: ['sicak-carpmasi', 'su-verme', 'bilinc'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-641',
    subject: 'ilkyardim',
    topic: 'donma',
    difficulty: 'kolay',
    stem: 'Soğukta donma belirtisi gösteren bir uzvun karla veya elle ovulması neden yanlıştır?',
    options: [
      'Donmuş dokuda oluşan buz kristalleri sürtünmeyle hücrelere daha çok zarar verebildiği için',
      'Ovmak uzvu fazla ısıttığı için',
      'Ovmak uzvu görünmez kıldığı için',
      'Kar uzvu kirlettiği için',
    ],
    answerIndex: 0,
    explanation:
      'Donan dokuda oluşan minik buz kristalleri, ovma sırasındaki sürtünmeyle hücreleri keserek hasarı artırabilir. Bu nedenle donmuş uzuv karla veya elle ovulmaz; ılık bir ortamda yavaşça ısınması sağlanır.',
    whyWrong: [
      'Ovmak uzvu ısıtmaktan çok, buz kristalleriyle dokuyu zedeler.',
      'Asıl sakınca görünürlük ya da kirlenme değil, mekanik doku hasarıdır.',
    ],
    objective: 'Donmuş uzvun ovulmamasının nedenini kavramak.',
    tags: ['donma', 'ovma-yasak', 'doku-hasari'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-642',
    subject: 'ilkyardim',
    topic: 'donma',
    difficulty: 'orta',
    stem: 'Elleri donma belirtisi gösteren bir kişide uzvun ısıtılmasıyla ilgili doğru yaklaşım hangisidir?',
    options: [
      'Uzvu doğrudan sobaya, ateşe veya çok sıcak suya tutmak',
      'Uzvu ılık bir ortamda yavaşça ısıtmak ve kişiyi soğuktan uzaklaştırmak',
      'Uzvu kar üzerinde bekletmek',
      'Uzvu buzlu suya batırmak',
    ],
    answerIndex: 1,
    explanation:
      'Donmuş uzuv ani ve aşırı ısıya (soba, ateş, çok sıcak su) maruz bırakılırsa dokular ek hasar görebilir; çünkü uyuşmuş uzuv sıcaklığı doğru algılayamaz. Doğru yaklaşım kişiyi soğuktan uzaklaştırıp uzvu ılık ortamda yavaşça ısıtmaktır.',
    whyWrong: [
      'Doğrudan ateş veya çok sıcak su, hissizleşmiş dokuda yanığa yol açabilir.',
      'Karda bekletmek veya buzlu suya batırmak donmayı derinleştirir.',
    ],
    objective: 'Donmuş uzvun yavaş ve ılık ısıtıldığını bilmek.',
    tags: ['donma', 'isitma', 'yavas'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-643',
    subject: 'ilkyardim',
    topic: 'iletisim-destek',
    difficulty: 'kolay',
    stem: 'Kaza sonrası aşırı korkmuş, çığlık atan ama bilinci açık bir yaralıyı sakinleştirmek için ilk yardımcının en uygun davranışı hangisidir?',
    options: [
      'Sesini yükseltip yaralıya bağırarak susmasını söylemek',
      'Yaralıyı görmezden gelip yalnızca çevreyle ilgilenmek',
      'Adıyla hitap edip göz teması kurarak sakin ve güven veren bir sesle konuşmak',
      'Yaralıya durumun umutsuz olduğunu söylemek',
    ],
    answerIndex: 2,
    explanation:
      'Panik hâlindeki yaralıyı sakinleştirmenin yolu güven vermektir. İlk yardımcı yaralıya adıyla seslenir, göz teması kurar, sakin ve net bir dille yanında olduğunu anlatır; bu, yaralının kaygısını azaltır ve iş birliğini kolaylaştırır.',
    whyWrong: [
      'Bağırmak veya görmezden gelmek yaralının paniğini büyütür.',
      'Umutsuz konuşmak korkuyu ve şok riskini artırır.',
    ],
    objective: 'Panikleyen bilinçli yaralıyı sakinleştirmeyi bilmek.',
    tags: ['iletisim-destek', 'panik', 'guven'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-644',
    subject: 'ilkyardim',
    topic: 'olay-yeri-guvenligi',
    difficulty: 'orta',
    stem: 'Gece ve az ışıklı bir yolda meydana gelen kazada ilk yardımcının kendi güvenliğini artırmak için yapması en uygun olan nedir?',
    options: [
      'Karanlıkta fark edilmemek için hareketsiz kalmak',
      'Yol ortasında telefonuyla ışık tutup beklemek',
      'Aracın farlarını söndürüp karanlıkta çalışmak',
      'Varsa reflektörlü (ışığı yansıtan) yelek giymek ve uygun mesafeye uyarı üçgeni/reflektör koyarak yaklaşan araçları uyarmak',
    ],
    answerIndex: 3,
    explanation:
      'Gece görüş düşük olduğundan ilk yardımcının hem kendisi hem de yaralılar yaklaşan sürücüler tarafından geç fark edilebilir. Reflektörlü yelek giymek ve uygun mesafeye uyarı üçgeni/reflektör yerleştirmek, ikinci bir kazayı önlemede önemli bir güvenlik önlemidir.',
    whyWrong: [
      'Hareketsiz kalmak veya yol ortasında beklemek görünürlüğü artırmaz, tehlikeyi büyütür.',
      'Işıkları söndürmek olay yerini daha da karanlık ve tehlikeli hâle getirir.',
    ],
    objective: 'Gece kazasında görünürlüğü artıran önlemleri bilmek.',
    tags: ['olay-yeri-guvenligi', 'gece-gorunurluk', 'reflektor'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-645',
    subject: 'ilkyardim',
    topic: 'olay-yeri-guvenligi',
    difficulty: 'zor',
    stem: 'Devrilmiş bir araçtan yola yakıt akmaya başladığı ve bölgede yakıt buharı yayıldığı bir kazada ilk yardımcının öncelikli davranışı hangisidir?',
    options: [
      'Yaralıları ve çevredekileri sızıntı bölgesinden güvenli uzaklığa almak, açık ateş kaynaklarını uzak tutmak ve 112 ile itfaiyeyi haberdar etmek',
      'Yaralılara müdahale için hemen sızıntının ortasına girmek',
      'Sızıntıyı toprakla kapatmaya çalışırken sigara içmek',
      'Aracı çalıştırıp güvenli yere sürmeyi denemek',
    ],
    answerIndex: 0,
    explanation:
      'Yayılan yakıt buharı küçük bir kıvılcımla tutuşabileceğinden öncelik, kişileri sızıntı bölgesinden uzaklaştırmak ve tüm ateş kaynaklarını (sigara, çakmak, kıvılcım) bölgeden uzak tutmaktır. Durum 112 ve itfaiyeye bildirilir; parlama riski yüksek bölgeye gereksiz girilmez.',
    whyWrong: [
      'Sızıntının ortasına girmek veya sigara içmek parlama-yangın riskini çok artırır.',
      'Devrik ve hasarlı aracı çalıştırmaya kalkmak kıvılcım oluşturarak yakıtı tutuşturabilir.',
    ],
    objective: 'Yakıt sızıntılı kazada tahliye ve ateş kaynağı yönetimini kavramak.',
    tags: ['olay-yeri-guvenligi', 'yakit-sizintisi', 'tahliye'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-646',
    subject: 'ilkyardim',
    topic: 'arac-icinden-cikarma',
    difficulty: 'orta',
    stem: 'Eğimli bir yolda kaza yapıp duran araca yaklaşan ilk yardımcı, güvenliği artırmak için kontağı kapatmanın yanında hangisini de yapmalıdır?',
    options: [
      'Aracın camlarını tek tek silmek',
      'El frenini çekmek ve mümkünse tekerlekleri takozla destekleyerek aracın kaymasını önlemek',
      'Aracın koltuklarını düzeltmek',
      'Aracın radyosunu açmak',
    ],
    answerIndex: 1,
    explanation:
      'Eğimli zeminde duran araç kayarak hem yaralılar hem de ilk yardımcı için tehlike oluşturabilir. Kontak kapatıldıktan sonra el freni çekilir ve mümkünse tekerleklere takoz konarak aracın hareket etmesi engellenir; böylece müdahale güvenli hâle gelir.',
    whyWrong: [
      'Cam silmek, koltuk düzeltmek veya radyo açmak güvenlikle ilgili değildir.',
      'Bu işlemler aracın kaymasını önlemez.',
    ],
    objective: 'Eğimde aracın kaymasını önleyici önlemleri bilmek.',
    tags: ['arac-icinden-cikarma', 'el-freni', 'kayma-onleme'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-647',
    subject: 'ilkyardim',
    topic: 'tasima-teknikleri',
    difficulty: 'orta',
    stem: 'Yangın gibi hayati bir tehlike nedeniyle bir yaralıyı tek başına kısa mesafede güvenli yere çekmek zorunda kalan ilk yardımcı, yaralıyı hangi yönde çekmelidir?',
    options: [
      'Yana doğru, gövdeyi bükerek',
      'Yalnızca bir kolundan asılarak',
      'Baş-boyun-gövde ekseni bozulmayacak biçimde vücudun uzun ekseni (baş-ayak) doğrultusunda',
      'Bacaklarından yukarı kaldırarak',
    ],
    answerIndex: 2,
    explanation:
      'Zorunlu acil taşımada yaralı, baş-boyun-gövde ekseni korunacak şekilde vücudun uzun ekseni doğrultusunda (baş-ayak hattında) çekilir. Böylece omurgaya binen zorlanma en aza indirilir. Bu yöntem yalnızca yangın gibi yaşamsal tehlikelerde uygulanır.',
    whyWrong: [
      'Gövdeyi bükerek yana çekmek veya tek koldan asılmak omurgayı zorlar.',
      'Bacaklardan yukarı kaldırmak eksende taşımayı bozar ve yeni yaralanmalara yol açabilir.',
    ],
    objective: 'Acil sürükleyerek taşımada uzun eksen kuralını bilmek.',
    tags: ['tasima-teknikleri', 'acil-tasima', 'uzun-eksen'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-648',
    subject: 'ilkyardim',
    topic: 'karin-yaralanmasi',
    difficulty: 'kolay',
    stem: 'Karnına darbe alan ve karnı ağrıyan bir yaralı susadığını söyleyip yemek isterse ilk yardımcı ne yapmalıdır?',
    options: [
      'İstediği yiyecek ve içeceği vermelidir',
      'Ağrı kesici bir hap vermelidir',
      'Karnına bastırarak ağrısını gidermeye çalışmalıdır',
      'Ağızdan hiçbir şey vermemeli; olası bir ameliyat ve kusma riski nedeniyle yaralıyı aç-susuz izleyip 112’ye bildirmelidir',
    ],
    answerIndex: 3,
    explanation:
      'Karın yaralanmasında ağızdan verilen yiyecek-içecek, gerekebilecek acil ameliyatı geciktirir ve kusmaya yol açabilir. Bu nedenle yaralıya ağızdan bir şey verilmez; rahat bir pozisyonda izlenir ve 112 aranır.',
    whyWrong: [
      'Yiyecek, içecek veya ağızdan ilaç vermek ameliyat ve kusma açısından risklidir.',
      'Karna bastırmak iç yaralanmayı ağırlaştırabilir.',
    ],
    objective: 'Karın yaralanmasında ağızdan bir şey verilmediğini bilmek.',
    tags: ['karin-yaralanmasi', 'agizdan-verme', 'ameliyat-riski'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-649',
    subject: 'ilkyardim',
    topic: 'ozel-durum-yasli',
    difficulty: 'orta',
    stem: 'Bilinci açık yaşlı bir kazazedeye müdahale ederken ilk yardımcının, 112’ye iletmek üzere öğrenmeye çalışması yararlı olan bilgi hangisidir?',
    options: [
      'Yaralının bilinen kronik hastalıkları ve düzenli kullandığı ilaçlar',
      'Yaralının en sevdiği yemek',
      'Yaralının çalıştığı iş yeri',
      'Yaralının memleketi',
    ],
    answerIndex: 0,
    explanation:
      'Yaşlı yaralılarda kronik hastalıklar ve düzenli kullanılan ilaçlar, tıbbi değerlendirmeyi doğrudan etkiler. İlk yardımcı bilinci açık yaralıdan bu bilgileri sakince öğrenip 112’ye ve gelen ekibe iletirse tedavi süreci kolaylaşır.',
    whyWrong: [
      'Sevilen yemek veya memleket gibi bilgiler tıbbi müdahale için gerekli değildir.',
      'İş yeri bilgisi acil tedavi kararını etkilemez.',
    ],
    objective: 'Yaşlı yaralıda hastalık ve ilaç bilgisinin önemini kavramak.',
    tags: ['ozel-durum-yasli', 'kronik-hastalik', 'ilac-bilgisi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-650',
    subject: 'ilkyardim',
    topic: 'sok',
    difficulty: 'orta',
    stem: 'Dış kanaması olan bir yaralıda kanamanın erkenden durdurulması, şok açısından neden önemlidir?',
    options: [
      'Kanamayı durdurmanın şokla hiçbir ilgisi yoktur',
      'Süren kan kaybı dolaşımdaki kan hacmini azaltarak şok gelişmesine zemin hazırladığından, kanamayı durdurmak aynı zamanda şoku önlemeye yardım eder',
      'Kanamayı durdurmak yalnızca yaranın görüntüsünü düzeltir',
      'Kanamayı durdurmak yaralının üşümesini sağlar',
    ],
    answerIndex: 1,
    explanation:
      'Devam eden dış kanama, vücuttaki dolaşan kan hacmini azaltır; bu da dokulara yeterli kan gitmemesi anlamına gelen şoka zemin hazırlar. Kanamanın erken ve etkili biçimde durdurulması, kan kaybını sınırlayarak şok gelişme riskini de azaltır.',
    whyWrong: [
      'Kanama kontrolü ile şok önleme arasında doğrudan bir ilişki vardır.',
      'Amaç görüntüyü düzeltmek veya üşütmek değil, kan hacmini korumaktır.',
    ],
    objective: 'Kanama kontrolünün şok önlemedeki rolünü kavramak.',
    tags: ['sok', 'kanama-kontrolu', 'kan-hacmi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-651',
    subject: 'ilkyardim',
    topic: 'hava-yolu',
    difficulty: 'orta',
    stem: 'Bilinci kapalı bir yaralının hava yolunu değerlendiren ilk yardımcı, ağız içinde takma diş, kırık diş parçası veya kan gibi bir engel görürse ne yapar?',
    options: [
      'Hepsini görmezden gelip beklemelidir',
      'Ağza parmağını sokup körlemesine tarar',
      'Ağızda açıkça görülen ve kolay ulaşılabilen gevşek engeli dikkatle uzaklaştırır; görünmeyen bir cismi körlemesine aramaz',
      'Yaralının ağzına su dökerek temizler',
    ],
    answerIndex: 2,
    explanation:
      'Hava yolunu tıkayabilecek, ağızda açıkça görülen ve kolayca alınabilen gevşek cisimler (takma diş, kırık diş parçası, pıhtı) dikkatle uzaklaştırılır. Ancak görünmeyen bir cisim körlemesine parmakla aranmaz; bu, cismi daha derine itebilir.',
    whyWrong: [
      'Görünen engeli görmezden gelmek hava yolu tıkanıklığını sürdürür.',
      'Körlemesine tarama veya ağza su dökmek cismi ilerletebilir ya da boğulmaya yol açabilir.',
    ],
    objective: 'Bilinçsiz yaralıda ağızdaki görünür engelin uzaklaştırılmasını bilmek.',
    tags: ['hava-yolu', 'agiz-kontrolu', 'takma-dis'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-652',
    subject: 'ilkyardim',
    topic: 'ozel-durum-cocuk',
    difficulty: 'orta',
    stem: 'Kaza geçiren bebek ve küçük çocuklarda ilk yardımcının özellikle dikkatli olması gerekir; çünkü:',
    options: [
      'Durumları hiçbir zaman değişmez',
      'İlk yardıma hiç ihtiyaç duymazlar',
      'Yalnızca uykuya ihtiyaçları vardır',
      'Genel durumları erişkinlere göre daha hızlı bozulabilir; bu nedenle yakın izlenmeli ve gecikmeden 112 aranmalıdır',
    ],
    answerIndex: 3,
    explanation:
      'Bebek ve küçük çocuklarda vücut daha küçük olduğundan durum erişkinlere kıyasla daha hızlı ağırlaşabilir. Bu yüzden yaşam bulguları yakından izlenir, gecikmeden 112 aranır ve çocuk mümkünse ebeveyniyle birlikte, sakin biçimde tutulur.',
    whyWrong: [
      'Çocukların durumu değişmez veya ilk yardım gerektirmez demek yanlıştır.',
      'İhtiyaçları uykuyla sınırlı değildir; hızlı değerlendirme ve gözlem gerekir.',
    ],
    objective: 'Çocuklarda durumun hızlı bozulabileceğini ve erken 112’yi kavramak.',
    tags: ['ozel-durum-cocuk', 'hizli-kotulesme', 'erken-112'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-653',
    subject: 'ilkyardim',
    topic: 'iletisim-destek',
    difficulty: 'kolay',
    stem: 'Bilinci açık bir yaralıdan sağlık ekibine iletmek üzere bilgi alırken ilk yardımcının sorması en yararlı olan sorulardan biri hangisidir?',
    options: [
      'Nerede ağrısı olduğu, nasıl bir kaza geçirdiği ve bilinen bir hastalığı ya da alerjisi olup olmadığı',
      'Kaç yıldır araç kullandığı',
      'En sevdiği rengin ne olduğu',
      'Hangi takımı tuttuğu',
    ],
    answerIndex: 0,
    explanation:
      'Bilinci açık yaralıdan ağrının yeri, olayın nasıl geliştiği ve bilinen hastalık ya da alerji gibi bilgiler alınması, sağlık ekibinin değerlendirmesini hızlandırır. İlk yardımcı bu bilgileri sakin sorularla öğrenip aktarır.',
    whyWrong: [
      'Araç kullanma süresi, renk tercihi veya takım tutmak tıbbi değerlendirme için gerekli değildir.',
      'Bu tür sorular yaralının durumu hakkında yararlı bilgi sağlamaz.',
    ],
    objective: 'Bilinçli yaralıdan yararlı tıbbi bilgi almayı bilmek.',
    tags: ['iletisim-destek', 'bilgi-alma', 'anamnez'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-654',
    subject: 'ilkyardim',
    topic: 'olay-yeri-guvenligi',
    difficulty: 'kolay',
    stem: 'Bir trafik kazasına ilk ulaşan kişinin genel yaklaşımı hangi sırayla özetlenir?',
    options: [
      'Önce yaralıyı araca bindir, sonra çevreye bak',
      'Önce olay yeri güvenliğini sağla, sonra yaralıyı değerlendir ve gerektiğinde 112’yi ara',
      'Önce fotoğraf çek, sonra evine dön',
      'Önce yaralıyı yürüt, sonra beklemeye başla',
    ],
    answerIndex: 1,
    explanation:
      'İlk yardımın temel akışı; önce olay yeri ve kendi güvenliğini sağlamak, ardından yaralının bilinç ve solunum gibi yaşamsal işlevlerini değerlendirmek ve gerektiğinde 112’yi arayarak yardım istemektir. Bu sıra hem ilk yardımcıyı hem yaralıyı korur.',
    whyWrong: [
      'Yaralıyı gereksiz yere hareket ettirmek ya da araca bindirmek yaralanmayı ağırlaştırabilir.',
      'Fotoğraf çekmek veya olay yerini terk etmek önceliği yaşamdan uzaklaştırır.',
    ],
    objective: 'İlk yardımın güvenlik-değerlendirme-haber verme sırasını kavramak.',
    tags: ['olay-yeri-guvenligi', 'genel-yaklasim', 'siralama'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-655',
    subject: 'ilkyardim',
    topic: 'tyd-degerlendirme',
    difficulty: 'orta',
    stem: 'Bilinci kapalı ama solunumu düzenli olan bir yaralının yanında sağlık ekibi beklenirken ilk yardımcı ne yapmalıdır?',
    options: [
      'Yaralıyı yalnız bırakıp uzaklaşmak',
      'Yaralıyı ayağa kaldırmaya çalışmak',
      'Yaralıyı uygun yan pozisyonda tutup solunumunu düzenli aralıklarla kontrol ederek yanında kalmak',
      'Yaralıya ağızdan su vermek',
    ],
    answerIndex: 2,
    explanation:
      'Bilinci kapalı fakat soluyan yaralı, hava yolunu korumak için uygun yan pozisyonda tutulur; ekip gelene kadar solunumu düzenli aralıklarla kontrol edilir ve yaralı yalnız bırakılmaz. Durum kötüleşirse hemen gerekli müdahaleye geçilebilir.',
    whyWrong: [
      'Yaralıyı yalnız bırakmak, solunumu durursa fark edilmemesine yol açar.',
      'Bilinci kapalı yaralıyı ayağa kaldırmak veya ağızdan su vermek tehlikelidir.',
    ],
    objective: 'Bilinçsiz soluyan yaralıda pozisyon ve sürekli gözlemi bilmek.',
    tags: ['tyd-degerlendirme', 'yan-pozisyon', 'gozlem'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
];
