/**
 * ÖZGÜN direksiyon (uygulama) soruları — 4. genişletme (Program 2 · Faz 9). ROADMAP C.4/E.6.
 * Kaynak = MEB direksiyon/uygulama müfredatı; KENDİ İFADEMİZLE.
 */
import type { QuestionInput } from '@ea/content-schema';

const SRC = 'MEB direksiyon (uygulama) müfredatı (özgün ifade)';

export const PRATIK_QUESTIONS_4: QuestionInput[] = [
  {
    id: 'pratik-401',
    subject: 'pratik',
    topic: 'sinav-guzergah-komutlari',
    difficulty: 'orta',
    stem: 'Direksiyon sınavında görevli "ilerideki kavşaktan sola dön" dediğinde aday kavşağa çok yaklaşmışsa ve güvenli hazırlık için yer kalmamışsa ne yapmalıdır?',
    options: [
      'Komutu kaçırmamak için aniden şerit değiştirip dönüşe girmek',
      'Sert fren yapıp kavşağın ortasında durarak düşünmek',
      'Manevrayı zorlamamak; güvenli hazırlık mümkün değilse sakin biçimde ilerleyip bir sonraki uygun yerden dönüşü tamamlamak',
      'Görevliye itiraz edip aracı yolun ortasında durdurmak',
    ],
    answerIndex: 2,
    explanation:
      'Sınavda değerlendirilen şey komuta anında uymak değil, manevrayı güvenle yapmaktır. Hazırlık için yer kalmadıysa ani şerit atlamak yerine sakin ilerlemek ve dönüşü bir sonraki uygun noktadan tamamlamak doğru davranıştır; görevliler güvenlik gerekçesiyle geciken manevrayı olumsuz saymaz.',
    whyWrong: [
      'Ani şerit değiştirip dönüşe dalmak, çevredeki araçları hazırlıksız yakalar ve elemeye götürecek bir güvenlik hatasıdır.',
      'Kavşak ortasında durmak veya aracı yol ortasında bırakmak trafiği kilitler ve tek başına ağır hata sayılır.',
    ],
    objective: 'Güzergâh komutuna güvenliği bozmadan, gerekirse geciktirerek uymayı öğrenmek.',
    tags: ['sinav-komutlari', 'guzergah', 'guvenli-manevra'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-402',
    subject: 'pratik',
    topic: 'sinav-guzergah-komutlari',
    difficulty: 'kolay',
    stem: 'Sınav görevlisi dönüş komutunu erkenden verdiğinde adayın en doğru davranışı hangisidir?',
    options: [
      'Komutu duyar duymaz direksiyonu kırmak',
      'Komutu zihninde tutup sinyal, ayna ve kör nokta kontrolüyle manevraya zamanında ve kademeli hazırlanmak',
      'Dönüş yerine gelene kadar komutu unutup son anda hatırlamaya çalışmak',
      'Görevliden komutu her seferinde üç kez tekrarlamasını istemek',
    ],
    answerIndex: 1,
    explanation:
      'Erken verilen komut adaya hazırlık süresi kazandırır. Doğru olan, komutu akılda tutup sinyali zamanında vermek, aynaları ve kör noktayı kontrol etmek ve gerekli şeride kademeli geçmektir. Böylece manevra telaşsız ve güvenli yapılır.',
    whyWrong: [
      'Komutu duyar duymaz direksiyon kırmak, henüz gözlem yapılmadığı için tehlikelidir.',
      'Komutu son ana bırakmak, hazırlıksız ve aceleci bir manevraya yol açar.',
    ],
    objective: 'Erken verilen güzergâh komutunu planlı hazırlığa çevirebilmek.',
    tags: ['sinav-komutlari', 'hazirlik', 'sinyal'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-403',
    subject: 'pratik',
    topic: 'donel-kavsak-serit',
    difficulty: 'orta',
    stem: 'İki şeritli bir dönel kavşakta sola denk gelen (üçüncü) çıkışı kullanacak sürücü kavşağa hangi şeritten girmelidir?',
    options: [
      'İç (sol) şeritten girip çıkışına yaklaşırken kontrollü biçimde dışa açılmalıdır',
      'Her zaman dış (sağ) şeritten girmelidir',
      'Şerit fark etmez, kavşak içinde istediği gibi geçebilir',
      'Kavşağa girmeden önce karşı yönden dolaşmalıdır',
    ],
    answerIndex: 0,
    explanation:
      'Dönel kavşakta uzak (sola denk gelen) çıkışlar için iç şerit kullanılır; sürücü kavşak içinde dönüşünü iç şeritte sürdürür ve çıkışına yaklaşırken sinyal verip gözlem yaparak dışa açılır. Bu düzen, kavşak içinde yol kesişmelerini azaltır.',
    whyWrong: [
      'Uzak çıkış için dış şeritten girmek, kavşak içinde uzun süre başkalarının çıkış hattını kesmeye yol açar.',
      'Şerit seçiminin önemsiz olduğunu düşünmek, kavşak içi çarpışmaların başlıca nedenidir.',
    ],
    objective: 'Dönel kavşakta çıkış yönüne göre doğru giriş şeridini seçebilmek.',
    tags: ['donel-kavsak', 'serit-secimi', 'kavsak'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-404',
    subject: 'pratik',
    topic: 'donel-kavsak-serit',
    difficulty: 'kolay',
    stem: 'Dönel kavşaktan ilk (sağa denk gelen) çıkışı kullanacak sürücü için doğru şerit ve sinyal kullanımı hangisidir?',
    options: [
      'İç şeritten girip sinyal vermeden çıkmak',
      'Dış şeritten girip sol sinyal vermek',
      'Kavşağın ortasından düz geçmek',
      'Dış (sağ) şeritten girmek ve sağ sinyalle ilk çıkıştan ayrılmak',
    ],
    answerIndex: 3,
    explanation:
      'İlk çıkıştan ayrılacak sürücü kavşağa dış (sağ) şeritten girer ve sağ sinyalini vererek niyetini bildirir. Böylece hem kavşağa girmeyi bekleyenler hem arkadaki sürücüler hareketi öngörebilir ve akış kesintiye uğramaz.',
    whyWrong: [
      'İç şeritten girip hemen ilk çıkışa yönelmek, dış şeritteki aracın yolunu keser.',
      'Sol sinyal vermek veya hiç sinyal vermemek diğer sürücülere yanlış ya da eksik bilgi verir.',
    ],
    objective: 'Yakın çıkış için dış şerit ve sağ sinyal kullanımını uygulayabilmek.',
    tags: ['donel-kavsak', 'cikis-sinyali', 'serit-secimi'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-405',
    subject: 'pratik',
    topic: 'donel-kavsak-serit',
    difficulty: 'orta',
    stem: 'Dönel kavşak içinde ilerlerken çıkışını kaçırdığını fark eden sürücü ne yapmalıdır?',
    options: [
      'Aniden fren yapıp kavşak içinde geri geri gitmek',
      'Panik yapmadan dönüşe devam edip bir tam tur atarak çıkışına yeniden ve hazırlıklı biçimde gelmek',
      'Kavşağın göbeğinin üzerinden kestirme geçmek',
      'Diğer şeride sinyalsiz dalarak son anda çıkışa yönelmek',
    ],
    answerIndex: 1,
    explanation:
      'Dönel kavşağın en büyük avantajı, kaçırılan çıkışın bir tam turla yeniden yakalanabilmesidir. Sürücü panik yapmadan dönüşünü sürdürür ve çıkışına ikinci gelişte sinyal ve gözlemle, hazırlıklı olarak yönelir. Kavşak içinde ani fren, geri gitme veya şerit kesme ciddi tehlike yaratır.',
    whyWrong: [
      'Kavşak içinde durmak ya da geri gitmek, arkadan gelenler için beklenmedik ve çok tehlikeli bir engeldir.',
      'Sinyalsiz şerit kesmek veya göbek üzerinden geçmek hem kural ihlali hem çarpışma nedenidir.',
    ],
    objective: 'Kaçırılan dönel kavşak çıkışını ek turla güvenle telafi edebilmek.',
    tags: ['donel-kavsak', 'cikis-kacirma', 'sakin-surus'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-406',
    subject: 'pratik',
    topic: 'egimde-park',
    difficulty: 'kolay',
    stem: 'Yokuş aşağı bakan bir eğimde, kaldırım kenarına park eden sürücü ön tekerlekleri hangi yöne çevirmelidir?',
    options: [
      'Tekerlekler dümdüz bırakılır',
      'Kaldırımdan dışa, yolun ortasına doğru',
      'Kaldırıma doğru; araç kayarsa ön tekerlek kaldırıma yaslanıp aracı durdurur',
      'Tekerlek yönünün eğimli parkta hiçbir önemi yoktur',
    ],
    answerIndex: 2,
    explanation:
      'Yokuş aşağı parkta ön tekerlekler kaldırıma doğru çevrilir. El freni ya da vites bir nedenle tutmazsa araç öne kaymaya başladığında ön tekerlek kaldırıma dayanır ve araç yola savrulmadan durur. Tekerlek yönü, eğimli parkın sessiz sigortasıdır.',
    whyWrong: [
      'Tekerlekleri düz bırakmak, fren boşalırsa aracın eğim boyunca yola kaymasına izin verir.',
      'Yokuş aşağı dururken tekerleği dışa çevirmek, kayan aracı doğrudan trafiğin içine yönlendirir.',
    ],
    objective: 'Yokuş aşağı parkta tekerlekleri kaldırıma çevirme kuralını uygulayabilmek.',
    tags: ['egimde-park', 'tekerlek-yonu', 'yokus-asagi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-407',
    subject: 'pratik',
    topic: 'egimde-park',
    difficulty: 'zor',
    stem: 'Yokuş yukarı bakan bir eğimde, yanında kaldırım bulunan yere park eden sürücü ön tekerlekleri neden kaldırımdan dışa (yola doğru) çevirir?',
    options: [
      'Araç geriye kayarsa ön tekerleğin arka yüzü kaldırıma dayanır ve kayma orada durur',
      'Yola doğru çevrilen tekerlek aracın daha hızlı kalkış yapmasını sağlar',
      'Kaldırıma çevrilen tekerlek lastiği çizeceği için',
      'Bu yönde bir kural yoktur, alışkanlıktır',
    ],
    answerIndex: 0,
    explanation:
      'Yokuş yukarı parkta araç kayarsa geriye doğru hareket eder. Ön tekerlekler kaldırımdan dışa çevrildiğinde, geri kayan aracın ön tekerleği kısa bir mesafede kaldırım taşına dayanır ve kayma orada biter. Yön mantığı, kayma yönü ile kaldırımın konumuna göre kurulur: yokuş aşağıda kaldırıma doğru, yokuş yukarıda kaldırımdan dışa.',
    whyWrong: [
      'Tekerlek yönünün kalkış hızıyla ya da lastiğin çizilmesiyle ilgisi yoktur; amaç kaymayı durdurmaktır.',
      'Bunu alışkanlık saymak, el freni boşaldığında aracın yola kayıp kazaya karışmasına yol açar.',
    ],
    objective:
      'Yokuş yukarı ve yokuş aşağı parkta tekerlek yönü farkını kayma mantığıyla açıklayabilmek.',
    tags: ['egimde-park', 'tekerlek-yonu', 'yokus-yukari'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-408',
    subject: 'pratik',
    topic: 'egimde-park',
    difficulty: 'kolay',
    stem: 'Eğimli bir yerde park edip araçtan inerken tekerlek yönüne ek olarak hangi önlemler alınmalıdır?',
    options: [
      'Yalnızca kapıları kilitlemek yeterlidir',
      'El frenini tam çekmek ve manuel araçta uygun vitesi takılı bırakmak (yokuş yukarı birinci, yokuş aşağı geri vites)',
      'Vitesi boşa alıp yalnızca ayak frenine güvenmek',
      'Motoru çalışır durumda bırakmak',
    ],
    answerIndex: 1,
    explanation:
      'Eğimde park güvenliği üç katmandan oluşur: doğru tekerlek yönü, tam çekilmiş el freni ve takılı bırakılan uygun vites. Manuel araçta yokuş yukarı birinci, yokuş aşağı geri vites takılı bırakılır; böylece el freni zayıflasa bile motor direnci aracı tutar.',
    whyWrong: [
      'Vitesi boşa almak, el freni gevşerse aracı tutacak ikinci bir güvence bırakmaz; ayak freni ise araçtan inince devrede değildir.',
      'Kapı kilidi ya da çalışır motor, aracın kaymasını önlemez.',
    ],
    objective: 'Eğimli parkta el freni ve vitesle çok katmanlı güvence kurabilmek.',
    tags: ['egimde-park', 'el-freni', 'vites'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-409',
    subject: 'pratik',
    topic: 'otoyol-katilim',
    difficulty: 'orta',
    stem: 'Otoyola hızlanma (katılma) şeridinden girerken doğru teknik hangisidir?',
    options: [
      'Şeridin başında durup otoyolun tamamen boşalmasını beklemek',
      'Yavaş hızla ilerleyip otoyoldaki araçların fren yapmasını ummak',
      'Hızlanma şeridine girer girmez sola dönüp akışa dalmak',
      'Şerit boyunca hızlanıp akış hızına yaklaşmak, ayna ve kör nokta kontrolüyle uygun boşluğu seçip sinyalle akışa katılmak',
    ],
    answerIndex: 3,
    explanation:
      'Hızlanma şeridinin amacı, katılmadan önce otoyol akışının hızına ulaşmaktır. Sürücü şerit boyunca hızlanır, sol ayna ve kör noktayı kontrol ederek trafikte uygun bir boşluk seçer ve sinyal vererek akışa neredeyse hız farkı olmadan katılır. Hız farkı ne kadar küçükse katılım o kadar güvenlidir.',
    whyWrong: [
      'Yavaş girip otoyoldakilerin fren yapmasını beklemek, yüksek hızlı trafikte zincirleme riske yol açar.',
      'Şeridin başında hemen sola dalmak, henüz hız ve gözlem tamamlanmadığı için tehlikelidir.',
    ],
    objective: 'Hızlanma şeridini akış hızına ulaşarak ve gözlemle kullanabilmek.',
    tags: ['otoyol', 'hizlanma-seridi', 'trafige-katilim'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-410',
    subject: 'pratik',
    topic: 'otoyol-katilim',
    difficulty: 'zor',
    stem: 'Zorunlu olmadıkça hızlanma şeridinin sonunda durup beklemek neden özellikle tehlikelidir?',
    options: [
      'Duran araç sıfır hızdan çok yüksek hızlı akışa katılmak zorunda kalır ve arkadan gelen katılımcılar için beklenmedik bir engel oluşturur',
      'Hızlanma şeridinde durmak yakıt tüketimini artırdığı için',
      'Otoyol kameraları duran aracı cezalandırdığı için',
      'Durunca motor hararet yapacağı için',
    ],
    answerIndex: 0,
    explanation:
      'Hızlanma şeridi hız kazanmak için tasarlanmıştır. Sonunda duran araç iki tehlike yaratır: sıfır hızdan yüksek hızlı akışa katılmak için çok büyük bir boşluk gerekir ve şeridi arkadan hızlanarak gelen araçlar duran aracı beklemez. Bu yüzden boşluk, durarak değil, hız eşitlenerek şerit boyunca aranır.',
    whyWrong: [
      'Sorunun özü yakıt, kamera ya da hararet değil, hız farkının yarattığı çarpışma riskidir.',
      'Bu tür gerekçeler tehlikenin mekanik ve trafiksel boyutunu gözden kaçırır.',
    ],
    objective: 'Hız farkının katılım güvenliği üzerindeki belirleyici etkisini kavramak.',
    tags: ['otoyol', 'hizlanma-seridi', 'hiz-farki'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-411',
    subject: 'pratik',
    topic: 'serit-degistirme-sds',
    difficulty: 'kolay',
    stem: 'Şerit değiştirmede öğretilen S-D-Ş sıralaması hangi adımları ifade eder?',
    options: [
      'Sağa yanaş - Dur - Şeride çık',
      'Sola bak - Dörtlü yak - Şerit değiştir',
      'Sinyal ver - Dikiz (ayna ve kör nokta) kontrol et - Şeridi güvenliyse değiştir',
      'Sabit hız - Direksiyon kır - Şeride gir',
    ],
    answerIndex: 2,
    explanation:
      'S-D-Ş, şerit değişiminin akılda kalıcı sırasıdır: önce sinyalle niyet bildirilir, ardından dikiz aynaları ve kör nokta kontrol edilir, en son güvenli olduğu görülünce şerit değiştirilir. Sıra bozulursa ya çevre habersiz kalır ya da görülmeyen bir araca doğru manevra yapılır.',
    whyWrong: [
      'Durmak, dörtlü yakmak ya da doğrudan direksiyon kırmak şerit değişiminin adımları değildir.',
      'Kontrolsüz veya sinyalsiz geçiş, yandaki aracı hazırlıksız yakalayan başlıca hatadır.',
    ],
    objective: 'Şerit değişiminde sinyal-dikiz-şerit sırasını doğru uygulayabilmek.',
    tags: ['serit-degistirme', 'sds', 'kor-nokta'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-412',
    subject: 'pratik',
    topic: 'serit-degistirme-sds',
    difficulty: 'orta',
    stem: 'Sinyal verdiği anda, beklemeden şerit değiştirmeye başlayan sürücünün hatası nedir?',
    options: [
      'Sinyal kolunu yanlış yöne itmiş olması',
      'Sinyalin bir bildirim olduğunu unutması; çevredeki sürücülere görüp tepki verecek süre tanımadan ve kontrolleri bitirmeden manevraya girmesi',
      'Sinyali gereğinden uzun süre açık tutması',
      'Şerit değiştirmeden önce hız yapması',
    ],
    answerIndex: 1,
    explanation:
      'Sinyal bir izin değil, niyet bildirimidir. Sinyalle aynı anda direksiyon kırmak, çevredeki sürücülere hazırlanma süresi tanımaz ve ayna ile kör nokta kontrolü tamamlanmadan manevra başlamış olur. Doğru akışta sinyalden sonra kısa bir gözlem payı bırakılır, güvenli olduğu görülünce geçilir.',
    whyWrong: [
      'Sorun sinyalin yönü ya da süresi değil, bildirim ile manevra arasındaki payın hiç bırakılmamasıdır.',
      'Hız tek başına bu hatanın nedeni değildir; sıralama bozulduğu için manevra kontrolsüzdür.',
    ],
    objective: 'Sinyal ile manevra arasında gözlem ve tepki payı bırakmayı öğrenmek.',
    tags: ['serit-degistirme', 'sinyal-zamanlama', 'gozlem'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-413',
    subject: 'pratik',
    topic: 'geri-duz-gitme',
    difficulty: 'orta',
    stem: 'Aracı geri geri düz bir hat üzerinde götürürken doğru bakış ve direksiyon tekniği hangisidir?',
    options: [
      'Gövde hafif sağa dönük, ana bakış omuz üzerinden arka camda; direksiyon küçük ve erken düzeltmelerle, araç sürünme hızında tutulur',
      'Yalnızca sol yan aynaya bakılır, direksiyon hızlı çevrilir',
      'Başı öne dönük tutup yalnız iç aynadan bakmak yeterlidir',
      'Gaz verilerek geri gidilir, yön son anda düzeltilir',
    ],
    answerIndex: 0,
    explanation:
      'Geri düz gitmede en geniş görüş, gövdeyi hafif sağa döndürüp omuz üzerinden arka cama bakmakla sağlanır; aynalar destek olarak taranır. Araç sürünme hızında tutulur ve yön sapmaları büyümeden küçük direksiyon hareketleriyle düzeltilir. Yavaşlık, hatayı düzeltme payıdır.',
    whyWrong: [
      'Tek aynaya bağlı kalmak arka görüşü daraltır; hızlı direksiyon geri harekette abartılı sapma yaratır.',
      'Gazla hızlı geri gitmek, düzeltme fırsatı bırakmadan aracı hattan çıkarır.',
    ],
    objective: 'Geri düz seyirde doğru bakış düzeni ve küçük düzeltme tekniğini uygulayabilmek.',
    tags: ['geri-manevra', 'geri-duz-gitme', 'bakis-teknigi'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-414',
    subject: 'pratik',
    topic: 'geri-duz-gitme',
    difficulty: 'kolay',
    stem: 'Manuel araçta geri viteste hız en sağlıklı nasıl kontrol edilir?',
    options: [
      'Gaza sonuna kadar basıp frenle dengelemek',
      'Vitesi boşa alıp aracın kendi kendine kaymasına izin vermek',
      'Genellikle gaz kullanmadan, debriyajı kavrama noktası çevresinde oynatarak aracı sürünme hızında tutmak; gerekince debriyaja basıp frenlemek',
      'Debriyajı tamamen bırakıp hızlanmasını beklemek',
    ],
    answerIndex: 2,
    explanation:
      'Geri vites oranı güçlü olduğundan çoğu manevrada gaz gerekmez; debriyaj kavrama noktası çevresinde hafifçe oynatılarak araç sürünme hızında tutulur. Yavaşlamak ya da durmak gerektiğinde debriyaja basılıp fren kullanılır. Bu, geri manevranın en hassas hız kontrol yöntemidir.',
    whyWrong: [
      'Gazla geri gitmek hızı büyütür ve küçük bir gecikmede çarpmaya yol açar.',
      'Vitesi boşa almak ya da debriyajı tümüyle bırakmak, hız üzerindeki hassas kontrolü ortadan kaldırır.',
    ],
    objective: 'Geri manevrada debriyajla sürünme hızını koruyabilmek.',
    tags: ['geri-manevra', 'debriyaj', 'hiz-kontrol'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-415',
    subject: 'pratik',
    topic: 'dar-sokak-karsilasma',
    difficulty: 'orta',
    stem: 'Dar bir sokakta karşıdan araç gelirken park etmiş araçlar sizin tarafınızdaki şeridi daraltıyorsa ne yapmalısınız?',
    options: [
      'Hızlanıp engeli karşı araçtan önce geçmek',
      'Uzun far yakıp karşı aracı durmaya zorlamak',
      'Engelin hizasında yol ortasında durup beklemek',
      'Engel kendi tarafınızda olduğu için uygun bir boşlukta bekleyip karşıdan gelene geçiş üstünlüğü tanımak',
    ],
    answerIndex: 3,
    explanation:
      'Dar yol karşılaşmalarında temel ilke, engelin kendi tarafında olduğu sürücünün beklemesidir; çünkü karşı şeride taşacak olan odur. Sürücü engelden önce uygun bir boşlukta durur, karşıdan gelen geçer, ardından kendi manevrasını yapar. Bu düzen kilitlenmeyi ve sürtüşmeyi önler.',
    whyWrong: [
      'Hızlanıp önce geçmeye çalışmak, iki aracı dar kesitte karşı karşıya sıkıştırır.',
      'Far ya da kornayla baskı kurmak veya engel hizasında yol ortasında durmak sorunu büyütür.',
    ],
    objective: 'Dar yolda engel tarafına göre bekleme önceliğini uygulayabilmek.',
    tags: ['dar-sokak', 'karsilasma', 'gecis-ustunlugu'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-416',
    subject: 'pratik',
    topic: 'dar-sokak-karsilasma',
    difficulty: 'zor',
    stem: 'İki aracın geçişemeyeceği kadar dar ve eğimli bir yolda, çıkan ve inen araç karşılaştığında genel teamül nedir?',
    options: [
      'Hangisi daha büyükse o geçer',
      'Geri gitmesi ve yeniden kalkışı daha zor olan yokuş çıkan araca kolaylık tanınır; genellikle inen araç uygun bir cebe çekilir veya geri alır',
      'İki araç da korna çalarak bekler',
      'Çıkan araç her koşulda geri geri en aşağıya kadar iner',
    ],
    answerIndex: 1,
    explanation:
      'Eğimli dar yolda kritik nokta, yokuş çıkan aracın durup yeniden kalkışının ve yokuş yukarı geri manevrasının çok daha zor ve riskli olmasıdır. Bu yüzden teamül, inen aracın uygun bir genişliğe çekilmesi ya da kontrollü geri almasıdır. Yine de belirleyici olan, o anda hangi aracın yakınında güvenli bir kaçış cebi bulunduğudur.',
    whyWrong: [
      'Araç büyüklüğü ya da korna, geçiş düzenini belirleyen bir ölçüt değildir.',
      'Çıkan aracı her koşulda geri göndermek, en zor ve tehlikeli manevrayı en dezavantajlı tarafa yüklemek olur.',
    ],
    objective: 'Eğimli dar yol karşılaşmasında manevra zorluğuna göre kolaylık tanımayı öğrenmek.',
    tags: ['dar-sokak', 'egimli-yol', 'karsilasma'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-417',
    subject: 'pratik',
    topic: 'cam-bugulanma',
    difficulty: 'kolay',
    stem: 'Yağmurlu havada ön cam içi hızla buğulanan sürücü buğuyu en çabuk nasıl giderir?',
    options: [
      'Klimayı (AC) çalıştırıp hava akışını ön cam moduna yönlendirmek; gerekirse camı bir miktar aralamak',
      'Kaloriferi tamamen kapatıp beklemek',
      'Sürüşe devam edip buğunun kendiliğinden geçmesini ummak',
      'Ön camın dışını sileceklerle daha hızlı silmek',
    ],
    answerIndex: 0,
    explanation:
      'Buğu, içerideki nemli havanın soğuk camda yoğuşmasıdır. En hızlı çözüm, nemi alan klimayı çalıştırıp hava akışını ön cam moduna vermektir; camı biraz aralamak da içerideki nemli havayı tazeler. Görüş kapanmışsa güvenli bir yerde durup camın açılması beklenir.',
    whyWrong: [
      'Kaloriferi kapatmak ya da beklemek nemi azaltmaz, buğu görüşü kapatmaya devam eder.',
      'Silecekler camın dışını temizler; iç yüzeydeki buğuya etkisi yoktur.',
    ],
    objective: 'Cam buğusunu klima ve doğru hava yönlendirmesiyle hızla giderebilmek.',
    tags: ['bugulanma', 'klima', 'gorus'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-418',
    subject: 'pratik',
    topic: 'cam-bugulanma',
    difficulty: 'orta',
    stem: 'Buğulanan camları sürüş sırasında elle veya bezle silmek neden yeterli bir çözüm değildir?',
    options: [
      'Bez cama zarar verip çizdiği için',
      'Silmek camın rengini değiştirdiği için',
      'Nemin kaynağı ortadan kalkmadığından buğu kısa sürede geri gelir; silme sırasında el ve göz yoldan ayrılır, iz kalan yüzey geceleyin parlamayı artırır',
      'Bezle silmek yalnızca dış camda işe yaradığı için',
    ],
    answerIndex: 2,
    explanation:
      'Bezle silmek belirtiyi geçici olarak giderir; içerideki nem sürdüğünden buğu hemen yeniden oluşur. Üstelik silme sırasında bir el direksiyondan, gözler yoldan ayrılır ve camda kalan izler gece karşı farlarda parlama yapar. Kalıcı çözüm, klima ve doğru hava yönlendirmesidir; arka cam için rezistans açılır.',
    whyWrong: [
      'Sorun camın çizilmesi ya da rengi değil, nemin kaynağının ortadan kalkmamasıdır.',
      'İç buğu için bez kısmen işe yarar; ama geçici olması ve sürücüyü sürüşten koparması onu yanlış yapar.',
    ],
    objective: 'Buğuya kaynak odaklı (nem giderici) çözümle yaklaşmayı öğrenmek.',
    tags: ['bugulanma', 'rezistans', 'dikkat-dagilma'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-419',
    subject: 'pratik',
    topic: 'gece-far-ayari',
    difficulty: 'zor',
    stem: 'Bagajı yüklü ve arka koltuğu dolu bir araçla gece yola çıkan sürücü far yükseklik (seviye) ayarını neden düşürmelidir?',
    options: [
      'Yük fardan güç çektiği için ışık zayıflar',
      'Arka yüklenen aracın burnu kalkar ve huzme yukarı bakarak karşıdan gelenlerin gözünü alır; seviye düğmesiyle huzme yeniden yola indirilir',
      'Yüklü araçta far ayarı yasal olarak kapatılmak zorunda olduğu için',
      'Seviye ayarı yalnızca yakıt tasarrufu sağladığı için',
    ],
    answerIndex: 1,
    explanation:
      'Arkaya binen yük aracın arkasını çökertir, burnunu kaldırır; farın huzmesi de yukarı bakmaya başlar. Bu, karşıdan gelen sürücüleri kamaştırır ve sizin yakın yol aydınlatmanızı bozar. Konsoldaki far seviye düğmesi, yük durumuna göre huzmeyi yeniden yola indirmek içindir.',
    whyWrong: [
      'Yükün farın elektrik gücüyle ya da yakıt tüketimiyle bir ilgisi yoktur.',
      'Ayar kapatılmaz; tam tersine yük arttıkça seviye kademesi düşürülerek kullanılır.',
    ],
    objective: 'Yük durumuna göre far seviye ayarını doğru kullanabilmek.',
    tags: ['far-ayari', 'gece-surus', 'yuklu-arac'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-420',
    subject: 'pratik',
    topic: 'gece-far-ayari',
    difficulty: 'orta',
    stem: 'Gece uzun farla seyrederken karşıdan gelen araçla karşılaşmada kısa fara geçişin doğru zamanlaması nedir?',
    options: [
      'İki araç yan yana geldiği anda geçilir',
      'Karşı araç geçtikten sonra geçilir',
      'Kısa fara hiç geçilmez, yalnızca hız düşürülür',
      'Karşı aracın ışıkları görünür görünmez, kamaştırma mesafesine girilmeden erkenden kısa fara geçilir; araçlar geçiştikten sonra yol boşsa uzuna dönülür',
    ],
    answerIndex: 3,
    explanation:
      'Kamaşma, araçlar yan yana gelmeden çok önce başlar. Bu yüzden kısa fara geçiş, karşı aracın ışıkları görünür görünmez, henüz kamaştırma mesafesine girilmeden yapılır. Erken geçiş karşı sürücünün görüşünü korur; araçlar geçişince yol boşsa uzun fara dönülerek görüş yeniden genişletilir.',
    whyWrong: [
      'Yan yana gelince ya da karşılaşmadan sonra geçmek, kamaşma zaten yaşandığı için çok geç kalmaktır.',
      'Yalnız hız düşürüp uzun farı açık tutmak, karşı sürücüyü saniyelerce kör bırakır.',
    ],
    objective: 'Kısa fara geçişi kamaştırma başlamadan önce zamanlayabilmek.',
    tags: ['gece-surus', 'kisa-far', 'zamanlama'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-421',
    subject: 'pratik',
    topic: 'sisli-hava-takip',
    difficulty: 'orta',
    stem: 'Yoğun siste öndeki aracı takip ederken en sık yapılan tehlikeli hata hangisidir?',
    options: [
      'Öndekinin stop lambalarına kilitlenip ona yakın gitmek ve kendi görüş mesafesi yerine öndekinin hızına güvenmek',
      'Takip mesafesini artırmak',
      'Hızı görüş mesafesine göre düşürmek',
      'Şerit çizgilerini yardımcı referans olarak izlemek',
    ],
    answerIndex: 0,
    explanation:
      'Siste stop lambaları güven verici bir çıpa gibi görünür; ancak lambalara kilitlenip yaklaşan sürücü, kendi görüşüne göre değil öndekinin kararlarına göre gitmeye başlar. Öndeki araç ani frenlediğinde ya da hatalı gittiğinde tepki payı kalmaz. Doğrusu mesafeyi artırmak ve hızı kendi görüş mesafene göre kurmaktır.',
    whyWrong: [
      'Mesafeyi artırmak ve hızı görüşe göre düşürmek hata değil, tam tersine sisin gerektirdiği davranıştır.',
      'Şerit çizgilerini referans almak, öndeki araca yapışmadan yolda kalmayı sağlayan doğru bir destektir.',
    ],
    objective: 'Siste öndeki araca değil, kendi görüş mesafesine göre sürmeyi öğrenmek.',
    tags: ['sis', 'takip-mesafesi', 'gorus-mesafesi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-422',
    subject: 'pratik',
    topic: 'sisli-hava-takip',
    difficulty: 'orta',
    stem: 'Arka sis lambasının kullanımıyla ilgili doğru yaklaşım hangisidir?',
    options: [
      'Her gece sürüşünde açık tutulur',
      'Yağmur çiselediği anda hemen açılır ve hiç kapatılmaz',
      'Görüşün ciddi biçimde düştüğü yoğun sis gibi durumlarda açılır; görüş düzelince kapatılır, çünkü gereksizken arkadaki sürücüyü kamaştırır ve fren lambasını maskeleyebilir',
      'Yalnızca park hâlinde kullanılır',
    ],
    answerIndex: 2,
    explanation:
      'Arka sis lambası çok parlaktır ve yalnızca görüşün ciddi düştüğü koşullarda, arkadan gelenlerin sizi erken fark etmesi için açılır. Görüş düzeldiğinde kapatılmalıdır; çünkü gereksiz kullanımda arkadaki sürücüyü kamaştırır ve parlaklığı fren lambasının fark edilmesini zorlaştırabilir.',
    whyWrong: [
      'Açık havada, her gece ya da hafif yağmurda sürekli açık tutmak arkadakiler için rahatsız edici ve yanıltıcıdır.',
      'Park lambası gibi kullanmak, lambanın amacını tümüyle karıştırmaktır.',
    ],
    objective: 'Arka sis lambasını yalnızca gerektiğinde açıp zamanında kapatabilmek.',
    tags: ['sis', 'sis-lambasi', 'aydinlatma'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-423',
    subject: 'pratik',
    topic: 'tunel-surus',
    difficulty: 'kolay',
    stem: 'Gündüz aydınlık bir yoldan tünele girmeden hemen önce sürücü ne yapmalıdır?',
    options: [
      'Farları kapatıp gözlerini kısmak',
      'Kısa farları yakmak, takıyorsa güneş gözlüğünü çıkarmak ve hız ile takip mesafesini karanlığa göre ayarlamak',
      'Dörtlü flaşörleri yakıp hızlanmak',
      'Tünel aydınlatıldığı için hiçbir hazırlık yapmamak',
    ],
    answerIndex: 1,
    explanation:
      'Tünele girişte gözler parlak ışıktan loş ortama birkaç saniyede uyum sağlar; bu sürede görüş zayıftır. Girişten önce kısa farlar yakılır, güneş gözlüğü çıkarılır, hız ve takip mesafesi bu geçici görüş kaybına göre ayarlanır. Farlar ayrıca aracınızın başkalarınca görülmesini sağlar.',
    whyWrong: [
      'Farsız girmek hem sizin görüşünüzü hem aracınızın görünürlüğünü azaltır.',
      'Dörtlü flaşör arıza bildirimidir; normal tünel girişinde yakılmaz.',
    ],
    objective: 'Tünel girişinde ışık ve göz uyumu hazırlığını yapabilmek.',
    tags: ['tunel', 'far-kullanimi', 'goz-uyumu'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-424',
    subject: 'pratik',
    topic: 'tunel-surus',
    difficulty: 'orta',
    stem: 'Tünel içinde seyrederken doğru sürüş davranışı hangisidir?',
    options: [
      'Duvara yakın gidip şerit ortasını boş bırakmak',
      'Öndeki araca yaklaşarak onun stop lambasını izlemek',
      'Fırsat buldukça şerit değiştirip hızlı ilerlemek',
      'Şeridi korumak, zorunlu değilse şerit değiştirmemek ve takip mesafesini açık yola göre artırmak',
    ],
    answerIndex: 3,
    explanation:
      'Tünelde kaçış alanı yoktur ve küçük bir hata zincirleme kazaya dönüşebilir. Bu yüzden şerit korunur, zorunlu olmadıkça şerit değiştirilmez ve takip mesafesi açık yola göre artırılır; böylece önde bir duraklama olursa tünel içinde güvenle durulabilir.',
    whyWrong: [
      'Tünelde gereksiz şerit değişimi, dar ve kapalı ortamda en riskli manevradır.',
      'Öndekine yaklaşmak ya da duvara yaslanmak, tepki ve manevra payını yok eder.',
    ],
    objective: 'Tünel içinde şerit disiplini ve artırılmış takip mesafesini uygulayabilmek.',
    tags: ['tunel', 'serit-disiplini', 'takip-mesafesi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-425',
    subject: 'pratik',
    topic: 'yaya-gecidi-yaklasim',
    difficulty: 'kolay',
    stem: 'Işıksız bir yaya geçidine yaklaşan sürücünün temel davranışı ne olmalıdır?',
    options: [
      'Hızı önceden azaltmak, geçidi ve kaldırım kenarlarını taramak; geçmek üzere bekleyen veya geçmekte olan yaya varsa durup yol vermek',
      'Yaya yoksa hızını artırarak geçmek',
      'Korna çalarak yayaları uyarıp hızını korumak',
      'Yalnızca geçidin üstünde yaya varsa yavaşlamak',
    ],
    answerIndex: 0,
    explanation:
      'Işıksız yaya geçidinde üstünlük yayanındır. Sürücü geçide her yaklaşımda hızını önceden düşürür, geçidi ve iki kaldırım kenarını tarar; geçmekte olan ya da geçmek üzere bekleyen yaya varsa durup yol verir. Hazırlıklı yaklaşım, son anda beliren yaya için durma payı bırakır.',
    whyWrong: [
      'Yaya görünmese bile geçide hızlı yaklaşmak, kaldırımdan aniden inen yaya için pay bırakmaz.',
      'Korna, yavaşlamanın ve yol vermenin yerini tutmaz; yayayı ürkütmekten başka işe yaramaz.',
    ],
    objective: 'Yaya geçidine hız azaltarak ve tarayarak yaklaşmayı alışkanlık edinmek.',
    tags: ['yaya-gecidi', 'yaya-onceligi', 'hiz-azaltma'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-426',
    subject: 'pratik',
    topic: 'yaya-gecidi-yaklasim',
    difficulty: 'orta',
    stem: 'Önünüzdeki araç bir yaya geçidinin önünde yavaşlayıp durduysa ne yapmalısınız?',
    options: [
      'Sinyal verip yanından hızla geçmek',
      'Korna çalarak öndeki aracı hareket ettirmeye çalışmak',
      'Siz de durmalısınız; duran aracın önünden görüşünüze kapalı bir yaya geçiyor olabilir ve duran aracı geçit üzerinde sollamak son derece tehlikelidir',
      'Karşı şeride geçip geçidi dolaşmak',
    ],
    answerIndex: 2,
    explanation:
      'Geçit önünde duran araç çoğu zaman bir yayaya yol vermektedir ve o yaya sizin görüşünüze kapalıdır. Duran aracın yanından geçmek, geçidin ortasındaki yayayla aniden karşılaşmak demektir. Doğru davranış durmak, öndeki araç hareket edip geçidin boş olduğu görülünce devam etmektir.',
    whyWrong: [
      'Duran aracı geçit hizasında sollamak, görünmeyen yayaya çarpmanın en bilinen senaryosudur.',
      'Korna ile baskı kurmak, yayaya yol veren sürücüyü hatalı davranışa itmeye çalışmaktır.',
    ],
    objective: 'Geçit önünde duran aracın arkasında durma refleksini kazanmak.',
    tags: ['yaya-gecidi', 'gizli-yaya', 'sollama-yasagi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-427',
    subject: 'pratik',
    topic: 'durakta-otobus',
    difficulty: 'orta',
    stem: 'Durakta yolcu indirip bindiren bir otobüsün yanından geçerken en önemli tehlike ve doğru davranış nedir?',
    options: [
      'Otobüsün geri kayması; bu yüzden arkasında beklenir',
      'Otobüsün önünden veya arkasından aniden yola çıkabilecek yayalar; hız düşürülür, geniş yan mesafe bırakılır ve durmaya hazır geçilir',
      'Otobüsün egzoz dumanı; camlar kapatılır',
      'Hiçbir tehlike yoktur, normal hızla geçilir',
    ],
    answerIndex: 1,
    explanation:
      'Duraktaki otobüs büyük bir görüş perdesidir: inen yolcular otobüsün önünden ya da arkasından, sizi görmeden yola çıkabilir. Bu yüzden otobüsün yanından hız düşürerek, geniş yan mesafe bırakarak ve her an durabilecek hazırlıkla geçilir; özellikle otobüsün ön tarafı ayrı bir dikkatle izlenir.',
    whyWrong: [
      'Otobüsün geri kayması ya da egzozu buradaki asıl risk değildir; risk görünmeyen yayadır.',
      'Normal hızla geçmek, otobüsün önünden fırlayan yolcu için hiçbir tepki payı bırakmaz.',
    ],
    objective: 'Duraktaki otobüsü görüş perdesi olarak değerlendirip temkinli geçmeyi öğrenmek.',
    tags: ['durak', 'otobus', 'gizli-yaya'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-428',
    subject: 'pratik',
    topic: 'durakta-otobus',
    difficulty: 'kolay',
    stem: 'Yerleşim yerinde duraktan ayrılmak için sinyal veren bir otobüse karşı arkadan gelen sürücünün doğru davranışı nedir?',
    options: [
      'Hızlanıp otobüsten önce geçmek',
      'Korna çalarak otobüsü beklemeye zorlamak',
      'Otobüse yapışarak takip etmek',
      'Hızını ayarlayıp otobüsün trafiğe katılışını kolaylaştırmak',
    ],
    answerIndex: 3,
    explanation:
      'Yerleşim yerlerinde duraktan kalkışını sinyalle bildiren toplu taşıma aracının trafiğe katılışı kolaylaştırılır. Arkadan gelen sürücü hızını ayarlayarak otobüse çıkış boşluğu tanır. Bu hem kurallı hem de akışı düzenli tutan bir davranıştır.',
    whyWrong: [
      'Hızlanıp önüne geçmeye çalışmak, kalkışa geçen büyük araçla sıkışma yaratır.',
      'Korna ile baskı kurmak ya da yapışık takip etmek güvenli mesafeyi ve nezaketi bozar.',
    ],
    objective: 'Duraktan kalkan toplu taşıma aracına katılım kolaylığı tanımayı öğrenmek.',
    tags: ['durak', 'otobus', 'yol-verme'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-429',
    subject: 'pratik',
    topic: 'okul-servisi',
    difficulty: 'kolay',
    stem: 'Önünüzdeki okul servisi durup uyarı (dur) ışıklarını yaktığında ne yapmalısınız?',
    options: [
      'Durup beklemelisiniz; ışıklar öğrenci indirilip bindirildiğini gösterir ve bu sırada servisi geçmek çok tehlikelidir',
      'Yavaşlamadan yanından geçmelisiniz',
      'Korna çalarak servisi kenara çekilmeye davet etmelisiniz',
      'Karşı şeride geçip hızla sollamalısınız',
    ],
    answerIndex: 0,
    explanation:
      'Okul servisinin yanıp sönen uyarı ışıkları, o anda öğrenci indirilip bindirildiğini bildirir. Çocuklar servis aracının önünden ya da arkasından aniden yola çıkabilir. Bu yüzden arkadan gelen sürücü durup ışıklar sönene ve servis hareket edene kadar bekler.',
    whyWrong: [
      'Işıklar yanarken servisin yanından geçmek, aracın önünden çıkan çocukla karşılaşma riskinin en yüksek olduğu andır.',
      'Korna çalmak ya da sollamak, çocukların güvenliğini doğrudan tehlikeye atar.',
    ],
    objective: 'Okul servisi uyarı ışıkları yanarken durup bekleme kuralını uygulamak.',
    tags: ['okul-servisi', 'cocuk-guvenligi', 'dur-isigi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-430',
    subject: 'pratik',
    topic: 'okul-servisi',
    difficulty: 'orta',
    stem: 'Okul çıkış saatinde, kenarda öğrenci bekleyen servis araçlarının bulunduğu bir sokaktan geçerken nasıl sürülmelidir?',
    options: [
      'Servisler durduğuna göre yol boştur, normal hızla geçilir',
      'Sadece korna çalarak ilerlenir',
      'Hız adım temposuna yakın düşürülür; çocukların araçların arasından aniden fırlayabileceği varsayılarak ayak fren üzerinde, durmaya hazır gidilir',
      'Uzun far yakılarak çocuklar uyarılır',
    ],
    answerIndex: 2,
    explanation:
      'Çocuklar trafiği yetişkin gibi değerlendiremez; topa, arkadaşına ya da servisine koşarken araçların arasından aniden çıkabilir. Bu yüzden okul çevresinde hız çok belirgin düşürülür, ayak fren pedalının üzerinde bekletilir ve park etmiş servislerin araları özel dikkatle taranır.',
    whyWrong: [
      'Duran servisler yolun boş olduğunu değil, çevrede çok sayıda çocuk olduğunu gösterir.',
      'Korna ya da far, aniden koşan bir çocuğu durduramaz; tek gerçek önlem düşük hızdır.',
    ],
    objective: 'Okul çevresinde çocuk davranışını öngörerek savunmacı sürüş uygulayabilmek.',
    tags: ['okul-servisi', 'cocuk-guvenligi', 'savunmaci-surus'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-431',
    subject: 'pratik',
    topic: 'iki-tekerlekli-gecis',
    difficulty: 'kolay',
    stem: 'Yolda bir bisikletliyi sollarken yan mesafe için doğru yaklaşım hangisidir?',
    options: [
      'Bisikletliye iyice yaklaşıp dar geçmek',
      'Belirgin biçimde geniş yan boşluk (yaklaşık bir buçuk metre) bırakmak; yol uygunsa geçiş için şeridi tümüyle değiştirmek',
      'Korna çalarak bisikletliyi kaldırıma çıkmaya zorlamak',
      'Bisikletlinin hemen arkasında aynı hızda kalmak',
    ],
    answerIndex: 1,
    explanation:
      'Bisikletli, çukur veya rüzgâr nedeniyle her an hafifçe yalpalayabilir; ayrıca yanından hızla dar geçen aracın hava akımı dengesini bozar. Bu yüzden geçişte belirgin geniş bir yan boşluk (yaklaşık bir buçuk metre) bırakılır; yol ve trafik uygunsa şeridi tümüyle değiştirmek en güvenlisidir.',
    whyWrong: [
      'Dar geçmek, bisikletlinin küçük bir yalpalamasında çarpma demektir.',
      'Korna ile baskı kurmak ya da arkasında asılı kalmak sorunu çözmez, bisikletliyi tedirgin eder.',
    ],
    objective: 'İki tekerlekliyi geniş yan mesafeyle ve sabırla geçmeyi öğrenmek.',
    tags: ['bisikletli', 'yan-mesafe', 'sollama'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-432',
    subject: 'pratik',
    topic: 'iki-tekerlekli-gecis',
    difficulty: 'orta',
    stem: 'Kuvvetli rüzgârlı veya yağışlı havada motosikletli sollanırken neden normalden de geniş pay bırakılmalıdır?',
    options: [
      'Motosiklet yağmurda daha hızlı gittiği için',
      'Motosikletli yağmurda sizi hiç göremeyeceği için',
      'Motosikletin farları yağmurda kamaştırdığı için',
      'İki tekerlekli araç rüzgârda ve kaygan zeminde aniden yalpalayabilir veya rota değiştirebilir; geniş pay bu beklenmedik sapmalara alan tanır',
    ],
    answerIndex: 3,
    explanation:
      'İki tekerlekli araçların dengesi rüzgâra ve zemine çok duyarlıdır: yan rüzgâr esintisi, su birikintisi veya kaygan şerit çizgisi motosikleti aniden yana kaydırabilir. Sollayan sürücü bu olası sapmayı kendi planına katmalı, yan mesafeyi normalden de geniş tutmalı ve geçişte agresif hız farkından kaçınmalıdır.',
    whyWrong: [
      'Motosikletin yağmurda hızlanması ya da farının kamaştırması gerçekçi gerekçeler değildir.',
      'Görüş azalabilir ama asıl sorun görmek değil, iki tekerleklinin denge hassasiyetidir.',
    ],
    objective: 'Olumsuz havada iki tekerleklinin denge riskini geçiş planına katabilmek.',
    tags: ['motosikletli', 'ruzgar', 'yan-mesafe'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-433',
    subject: 'pratik',
    topic: 'park-cikis-kor-nokta',
    difficulty: 'kolay',
    stem: 'Yol kenarındaki park yerinden ileri doğru çıkıp trafiğe katılırken kör nokta için ne yapılmalıdır?',
    options: [
      'Sinyal ve ayna kontrolüne ek olarak omuz üzerinden geriye bakıp aynada görünmeyen aracı veya bisikletliyi kontrol etmek, sonra yavaşça katılmak',
      'Aynada araç görünmüyorsa doğrudan gaza basıp çıkmak',
      'Yalnızca iç dikiz aynasına bakmak',
      'Kapıyı açıp dışarıya seslenerek yol istemek',
    ],
    answerIndex: 0,
    explanation:
      'Park hâlinden çıkışta aracın sol gerisi aynaların ölü bölgesidir; tam bu bölgede bir bisikletli ya da yaklaşan araç bulunabilir. Sinyal ve ayna kontrolünden sonra omuz üzerinden kısa bir bakışla kör nokta doğrulanır ve trafiğe yavaşça katılınır. Bu bakış, sınavda da beklenen bir alışkanlıktır.',
    whyWrong: [
      'Yalnızca aynaya güvenmek, tam kör noktadaki bisikletliyi görmemeye yol açar.',
      'Ayna boş diye ani gazla çıkmak, o sırada hızla yaklaşan aracı hazırlıksız yakalar.',
    ],
    objective: 'Park çıkışında omuz kontrolüyle kör noktayı doğrulama alışkanlığı kazanmak.',
    tags: ['park-cikisi', 'kor-nokta', 'omuz-kontrolu'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-434',
    subject: 'pratik',
    topic: 'park-cikis-kor-nokta',
    difficulty: 'zor',
    stem: 'İki yüksek araç (kamyonet, panelvan) arasındaki dik park yerinden geri geri çıkarken görüş neredeyse tamamen kapalıysa en güvenli yöntem nedir?',
    options: [
      'Korna çalıp normal hızda geri çıkmak',
      'Yandaki araçlar nasılsa sizi görür diyerek kesintisiz geri gitmek',
      'Aracın arkasını santim santim, sık sık durarak dışarı vermek; her duraklamada iki yönü de taramak ve mümkünse dışarıdan yönlendirecek birinden yardım almak',
      'Görüş açılana kadar gaza basıp hızla dışarı çıkmak',
    ],
    answerIndex: 2,
    explanation:
      'Yüksek araçlar arasında geri çıkarken, geçen trafiği siz ancak aracınızın arkası dışarı taştığında görebilirsiniz; onlar da sizi geç fark eder. Güvenli yöntem, aracı santim santim dışarı verip sık sık durmak, her duraklamada iki yönü taramak ve mümkünse dışarıdan bir gözcünün yönlendirmesinden yararlanmaktır.',
    whyWrong: [
      'Kesintisiz ya da hızlı geri çıkış, sizi ancak son anda görebilen araçla çarpışma riskini büyütür.',
      'Korna, geçen aracın ya da yayanın sizin arkanızı görmesini sağlamaz.',
    ],
    objective: 'Görüşü kapalı geri çıkışta kademeli ilerleme ve gözcü kullanımını öğrenmek.',
    tags: ['park-cikisi', 'geri-manevra', 'gorussuz-cikis'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-435',
    subject: 'pratik',
    topic: 'uc-nokta-donusu',
    difficulty: 'orta',
    stem: 'Dar bir yolda üç nokta dönüşü (üç hamlede geri dönüş) hangi adım sırasıyla yapılır?',
    options: [
      'Önce geri gidilir, sonra iki kez ileri alınır',
      'Sağa yanaşıp sinyal ve gözlemle başlanır; direksiyon sola tam kırılarak karşı kenara doğru ilerlenir, durup direksiyon sağa kırılarak geri alınır, son hamlede tekrar ileri çıkılıp araç yeni yönde düzeltilir',
      'Direksiyon hiç kırılmadan üç kez durup kalkılır',
      'Araç yol ortasında durdurulup yalnızca geri viteste döndürülür',
    ],
    answerIndex: 1,
    explanation:
      'Üç nokta dönüşü üç hamleden oluşur: sağa yanaşıp sinyal ve çift yönlü gözlemle başlanır; birinci hamlede direksiyon sola tam kırılarak karşı kenara kadar ilerlenir, ikinci hamlede direksiyon sağa kırılıp geri alınır, üçüncü hamlede yeniden ileri çıkılarak araç yeni yönde toparlanır. Her hamle arasında iki yön yeniden kontrol edilir.',
    whyWrong: [
      'Geriyle başlamak ya da direksiyonsuz durup kalkmak aracı döndürmez, yolu gereksiz işgal eder.',
      'Yol ortasında yalnız geri vitesle dönmeye çalışmak manevrayı uzatır ve trafiği kilitler.',
    ],
    objective: 'Üç nokta dönüşünün hamle sırasını ve ara gözlemlerini uygulayabilmek.',
    tags: ['uc-nokta-donusu', 'manevra', 'geri-donus'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-436',
    subject: 'pratik',
    topic: 'uc-nokta-donusu',
    difficulty: 'zor',
    stem: 'Üç nokta dönüşü için yer seçerken hangi konumlardan kaçınılmalıdır?',
    options: [
      'Geniş, düz ve iki yönden de iyi görülen sakin kesimlerden',
      'Trafiğin tamamen durduğu yerlerden',
      'Aydınlık ve kuru yollardan',
      'Tepe üstü, viraj yakını, kavşak ağzı gibi iki yönden gelen trafiğin sizi geç fark edeceği görüşü kısıtlı kesimlerden',
    ],
    answerIndex: 3,
    explanation:
      'Üç nokta dönüşü sırasında araç bir süre yolu enine kapatır. Tepe üstü, viraj çıkışı veya kavşak ağzı gibi yerlerde yaklaşan sürücüler yolu kapatan aracı ancak son anda görür ve duracak mesafeleri kalmaz. Manevra; düz, iki yönden uzak mesafeden görülebilen ve trafiği sakin bir kesimde yapılmalı, uygun bir yer yoksa dönüş için kavşak ya da dönel kavşak tercih edilmelidir.',
    whyWrong: [
      'Geniş, düz ve iyi görülen kesimler kaçınılacak değil, tam tersine tercih edilecek yerlerdir.',
      'Aydınlık ve kuru zemin manevra için sakınca değil avantajdır.',
    ],
    objective: 'Yolu enine kapatan manevralar için görüş temelli yer seçimi yapabilmek.',
    tags: ['uc-nokta-donusu', 'yer-secimi', 'gorus-mesafesi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-437',
    subject: 'pratik',
    topic: 'el-freni-kalkis',
    difficulty: 'orta',
    stem: 'El freni destekli yokuş kalkışında el freni tam olarak hangi anda bırakılmalıdır?',
    options: [
      'Debriyaj kavrama noktasına getirilip hafif gaz verildikten sonra, motorun yüklenip aracın öne çekildiği hissedildiği anda',
      'Motor çalıştırılır çalıştırılmaz, daha vites takılmadan',
      'Gaza basmadan önce, debriyaj hâlâ tam basılıyken',
      'Araç birkaç metre yol aldıktan sonra',
    ],
    answerIndex: 0,
    explanation:
      'El freninin görevi, çekiş oluşana kadar aracı yerinde tutmaktır. Debriyaj kavrama noktasına getirilip hafif gaz verildiğinde motor yüklenir ve araç öne çekilmek ister; el freni tam bu anda bırakılır. Böylece araç geriye hiç kaymadan, akıcı biçimde kalkar.',
    whyWrong: [
      'Çekiş oluşmadan (vitessiz ya da debriyaj tam basılıyken) bırakılan el freni, aracı yokuşta serbest bırakır ve geri kaçırır.',
      'Araç yol aldıktan sonra hâlâ çekili el freni, frenleri ısıtır ve kalkışı boğar.',
    ],
    objective: 'El frenini çekiş hissine göre doğru anda bırakabilmek.',
    tags: ['el-freni', 'yokus-kalkis', 'zamanlama'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-438',
    subject: 'pratik',
    topic: 'el-freni-kalkis',
    difficulty: 'kolay',
    stem: 'Yokuş kalkışında el frenini, motor daha yüklenmeden (çekiş oluşmadan) bırakmanın en olası sonucu nedir?',
    options: [
      'Araç olduğu yerde sabit kalır',
      'Motor devri kendiliğinden yükselir',
      'Aracı tutan kuvvet kalktığı için araç geriye doğru kaymaya başlar',
      'Araç aniden ileri fırlar',
    ],
    answerIndex: 2,
    explanation:
      'Yokuşta aracı geri kaydırmak isteyen yerçekimine karşı onu tutan şey el frenidir. Motor henüz yüklenmemişken, yani çekiş kuvveti oluşmamışken el freni bırakılırsa aracı tutan hiçbir kuvvet kalmaz ve araç geriye kayar. Sınavda geriye kayma, ciddi puan kaybettiren bir hatadır.',
    whyWrong: [
      'Çekiş yokken aracın sabit kalması ya da ileri fırlaması fiziksel olarak mümkün değildir.',
      'El freninin bırakılması motor devrini kendiliğinden değiştirmez.',
    ],
    objective: 'El freni ile çekiş kuvveti arasındaki görev devrini kavramak.',
    tags: ['el-freni', 'geri-kayma', 'yokus-kalkis'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-439',
    subject: 'pratik',
    topic: 'yarim-kavrama-surunme',
    difficulty: 'orta',
    stem: 'Dur-kalk trafiğinde araç adım hızında sürünürken (çok yavaş ilerlerken) doğru pedal kullanımı hangisidir?',
    options: [
      'İkinci viteste yüksek gazla gidip sık sık sert fren yapmak',
      'Birinci viteste, genellikle gaz kullanmadan debriyajı kavrama noktası çevresinde hafifçe oynatarak hızı ayarlamak; durmak gerekince debriyaja basıp frenlemek',
      'Vitesi boşa alıp aracı iterek ilerletmek',
      'Debriyajı tam bırakıp gaza yüklenmek',
    ],
    answerIndex: 1,
    explanation:
      'Adım hızındaki sürünme, birinci viteste ve çoğunlukla gazsız yapılır: debriyaj kavrama noktasının hemen çevresinde milimetrik oynatılır, araç hızlanınca pedala hafif basılır, yavaşlayınca hafif bırakılır. Durmak gerektiğinde debriyaja tam basılıp fren kullanılır. Bu, motoru boğmadan en hassas hız kontrolünü sağlar.',
    whyWrong: [
      'Yüksek gaz ve sert fren döngüsü sarsıntılı, yorucu ve arkadakiler için tehlikelidir.',
      'Boş vites ya da tam bırakılmış debriyajla adım hızı tutturulamaz; araç ya durur ya öne atılır.',
    ],
    objective: 'Yarım kavrama ile adım hızında hassas sürünmeyi uygulayabilmek.',
    tags: ['yarim-kavrama', 'dur-kalk-trafik', 'surunme'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-440',
    subject: 'pratik',
    topic: 'yarim-kavrama-surunme',
    difficulty: 'zor',
    stem: 'Yokuşta uzun süre bekleyen sürücünün aracı yarım debriyaj ve gazla yerinde tutması yerine el frenini kullanması neden önerilir?',
    options: [
      'El freni yakıt tüketimini artırdığı için',
      'Yarım debriyaj yokuşta yasak olduğu için',
      'El freni kalkışı hızlandırdığı için',
      'Yarım debriyajla bekleme, sürtünen balatayı aşırı ısıtıp aşındırır ve yanık kokusuyla kendini belli eder; el freni ise aracı yıpratmadan tutar ve ayakları dinlendirir',
    ],
    answerIndex: 3,
    explanation:
      'Yarım debriyajda balata, volana tam kenetlenmeden sürtünerek döner ve bu sürtünme dakikalar içinde ciddi ısınmaya, aşınmaya, hatta yanık kokusuna yol açar. Yokuşta uzun bekleyişte doğru olan, el frenini çekip debriyajı serbest bırakmaktır; kalkış zamanı gelince el freni destekli kalkış yapılır.',
    whyWrong: [
      'El freninin yakıtla ya da kalkış hızıyla ilgisi yoktur; amaç debriyajı korumaktır.',
      'Yarım debriyaj yasak değildir; ancak bekletme aracı olarak kullanılması mekanik olarak yanlıştır.',
    ],
    objective: 'Yokuş bekleyişinde debriyajı koruyan el freni alışkanlığını kazanmak.',
    tags: ['yarim-kavrama', 'balata-asinmasi', 'el-freni'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-441',
    subject: 'pratik',
    topic: 'fren-teknigi-abs',
    difficulty: 'zor',
    stem: 'ABS bulunmayan bir araçta kaygan zeminde yapılan sert frenle tekerlekler kilitlenip direksiyon yanıt vermez olursa ne yapılmalıdır?',
    options: [
      'Fren pedalı kısa aralıklarla bırakılıp yeniden basılır (pompalama); tekerlek her dönmeye başladığında direksiyon hâkimiyeti geri kazanılır',
      'Pedala daha da kuvvetli ve kesintisiz basılır',
      'El freni sonuna kadar çekilir',
      'Debriyaja basıp direksiyon hızla sağa sola çevrilir',
    ],
    answerIndex: 0,
    explanation:
      'Kilitlenen tekerlek dönmediği için yön tutmaz; araç direksiyona rağmen kaymaya devam eder. ABS olmayan araçta çözüm pompalamadır: pedal kısa aralıklarla bırakılıp yeniden basılır, tekerlek her dönüşe geçtiğinde direksiyon yeniden yanıt verir. Böylece hem yavaşlama hem yön kontrolü bir arada korunur.',
    whyWrong: [
      'Kilitli tekerleğe daha kuvvetli basmak kilidi çözmez, kaymayı sürdürür.',
      'El frenini çekmek arka tekerlekleri de kilitleyip savrulmayı başlatır; direksiyonu hızla sallamak kilitliyken hiçbir şey değiştirmez.',
    ],
    objective: 'ABS olmayan araçta pompalama frenle yön hâkimiyetini koruyabilmek.',
    tags: ['fren-pompalama', 'abs-yok', 'kaygan-zemin'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-442',
    subject: 'pratik',
    topic: 'fren-teknigi-abs',
    difficulty: 'orta',
    stem: 'ABS bulunan bir araçta ani tehlike karşısında fren nasıl kullanılır?',
    options: [
      'Pedal pompalanarak kısa kısa basılır',
      'Önce hafif, sonra kademe kademe artırılarak basılır',
      'Pedala kuvvetle ve kesintisiz basılır; pedaldaki titreşim sistemin çalıştığını gösterir ve bu sırada direksiyonla engelden kaçınılabilir',
      'Fren yerine yalnızca el freni kullanılır',
    ],
    answerIndex: 2,
    explanation:
      'ABS, pompalama işini sürücüden çok daha hızlı ve tekerlek başına yapar. Bu yüzden ABS bulunan araçta ani durumda pedala kuvvetle, kesintisiz basılır; pedalda hissedilen titreşim ve tıkırtı sistemin devrede olduğunu gösterir. Tekerlekler kilitlenmediği için aynı anda direksiyonla engelden kaçınmak da mümkündür.',
    whyWrong: [
      'ABS bulunan araçta pompalama ya da kademeli basış, sistemin sağlayacağı en kısa durma mesafesini uzatır.',
      'El freni ani durumda ana frenin yerini tutmaz; arka aksı kilitleyip savrulma yaratabilir.',
    ],
    objective: 'ABS bulunan ve bulunmayan araçlarda fren tekniği farkını ayırt edebilmek.',
    tags: ['abs', 'ani-fren', 'panik-fren'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-443',
    subject: 'pratik',
    topic: 'su-gecisi-fren',
    difficulty: 'orta',
    stem: 'Derin bir su birikintisinden geçtikten sonra frenlerle ilgili hangi önlem alınmalıdır?',
    options: [
      'Hemen yüksek hıza çıkıp frenleri rüzgârla kurutmak',
      'Islanan balataların tutuşu azalmış olabileceğinden düşük hızda, trafiği kontrol ederek fren birkaç kez hafifçe uygulanır; sürtünme ısısı balataları kurutup tutuşu geri getirir',
      'Frenlere hiç dokunmadan uzun süre gitmek',
      'Aracı durdurup balataları sökerek elle kurulamak',
    ],
    answerIndex: 1,
    explanation:
      'Su, balata ile disk arasına girerek frenin ilk tutuşunu belirgin azaltabilir. Sudan çıktıktan sonra sürücü, arkasını kontrol ederek düşük hızda birkaç kez hafif fren yapar; oluşan sürtünme ısısı yüzeyleri kurutur ve fren gücü geri gelir. Frenin tutup tutmadığı, ihtiyaç anından önce böyle sınanmış olur.',
    whyWrong: [
      'Hızlanmak ya da frene hiç dokunmamak, ilk gerçek fren ihtiyacında tutmayan pedal sürpriziyle sonuçlanır.',
      'Balata sökmek gibi bir müdahale gereksizdir; hafif frenleme yeterlidir.',
    ],
    objective: 'Su geçişi sonrası frenleri kontrollü kurutma alışkanlığı kazanmak.',
    tags: ['su-gecisi', 'fren-kurutma', 'islanan-balata'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-444',
    subject: 'pratik',
    topic: 'su-gecisi-fren',
    difficulty: 'kolay',
    stem: 'Yolu kaplayan derin sayılabilecek bir su birikintisinden geçmek zorunda kalan sürücü nasıl davranmalıdır?',
    options: [
      'Hızla dalıp suyu bir an önce geride bırakmalıdır',
      'Suyun ortasında durup derinliği ölçmelidir',
      'Gözü kapalı, normal seyir hızıyla geçmelidir',
      'Önce derinliği değerlendirmeli; geçilebilir görünüyorsa düşük viteste, yavaş ve sabit bir tempoyla, durmadan geçmelidir',
    ],
    answerIndex: 3,
    explanation:
      'Derin suya hızla girmek, motorun hava emişine su kaçırabilir ve görüşü kapatan bir su perdesi kaldırır. Doğru davranış, derinliği önceden değerlendirmek; geçilebilir görünüyorsa düşük viteste, yavaş ve sabit tempoyla, su içinde durmadan geçmektir. Derinlik belirsizse alternatif yol aranır.',
    whyWrong: [
      'Hızla dalmak su sıçratarak hem motoru hem görüşü riske atar.',
      'Suyun ortasında durmak, egzoz ve emiş yönünden en riskli senaryodur.',
    ],
    objective: 'Su geçişini düşük hız ve sabit tempoyla yönetebilmek.',
    tags: ['su-gecisi', 'derin-su', 'yavas-gecis'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-445',
    subject: 'pratik',
    topic: 'stepne-kullanimi',
    difficulty: 'kolay',
    stem: 'Lastik değişiminde takılan ince (geçici) stepne ile ilgili doğru bilgi hangisidir?',
    options: [
      'Geçici çözümdür; üzerinde yazan hız sınırının (genellikle 80 km/s dolayında) üzerine çıkılmamalı ve en kısa sürede asıl lastik taktırılmalıdır',
      'Normal lastikle tamamen aynıdır, süresiz kullanılabilir',
      'Yalnızca otoyolda kullanılmak için tasarlanmıştır',
      'Takıldıktan sonra araç daha hızlı gidebilir',
    ],
    answerIndex: 0,
    explanation:
      'İnce stepne, aracı en yakın servise ulaştırmak için tasarlanmış geçici bir çözümdür. Yapısı normal lastikten zayıf olduğundan üzerinde belirtilen hız sınırı (çoğunlukla 80 km/s dolayında) aşılmamalı, uzun mesafe ve yüksek hızdan kaçınılmalı, asıl lastik en kısa sürede taktırılmalıdır. Fren ve yol tutuş dengesi de stepneyle bir miktar bozulur.',
    whyWrong: [
      'Geçici stepneyi normal lastikle eşdeğer saymak, yüksek hızda patlama ve savrulma riski doğurur.',
      'Stepne aracı hızlandırmaz; tam tersine hız ve mesafe kısıtı getirir.',
    ],
    objective: 'Geçici stepnenin hız ve kullanım sınırlarını kavramak.',
    tags: ['stepne', 'hiz-siniri', 'lastik'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-446',
    subject: 'pratik',
    topic: 'sinav-arac-teslim',
    difficulty: 'kolay',
    stem: 'Direksiyon sınavında aday, bir önceki adayın kullandığı aracı teslim aldığında ilk yapması gereken nedir?',
    options: [
      'Zaman kaybetmemek için hemen motoru çalıştırıp kalkmak',
      'Görevliden aracı kendisinin ayarlamasını istemek',
      'Koltuk, aynalar ve baş desteğini kendi ölçülerine göre yeniden ayarlamak, emniyet kemerini takmak; vitesin boşta, el freninin çekili olduğunu görerek motoru öyle çalıştırmak',
      'Aracın rengini ve temizliğini kontrol etmek',
    ],
    answerIndex: 2,
    explanation:
      'Sınav aracı bir önceki adayın vücut ölçülerine göre ayarlıdır; koltuk, aynalar ve baş desteği size uymayabilir. Aday araca yerleşince bu ayarları kendine göre yapar, kemerini takar, vitesin boşta ve el freninin çekili olduğunu doğrulayıp motoru öyle çalıştırır. Bu hazırlık dizisi sınavın puanlanan ilk adımıdır.',
    whyWrong: [
      'Başkasının ayarlarıyla kalkmak hem görüşü hem pedal kontrolünü bozar ve daha ilk saniyede puan kaybettirir.',
      'Ayarları görevli değil, aracı kullanacak aday yapar; renk ve temizlik ise değerlendirme dışıdır.',
    ],
    objective: 'Sınav aracını teslim alırken kişisel ayar ve güvenlik dizisini uygulayabilmek.',
    tags: ['sinav-hazirlik', 'arac-teslim', 'surus-oncesi'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-447',
    subject: 'pratik',
    topic: 'sinav-arac-teslim',
    difficulty: 'orta',
    stem: 'Adayın sınav aracına yerleştikten sonra, hareket etmeden önce silecek, sinyal kolu, far düğmesi ve el freninin yerine kısaca göz atması neden önemlidir?',
    options: [
      'Görevliye bilgili görünmek için',
      'Alışık olmadığı araçta bu kumandaları sürüş sırasında el yordamıyla ararsa gözü ve dikkati yoldan ayrılır; yerlerini önceden bilmek ani ihtiyaçta doğru kumandaya anında ulaşmayı sağlar',
      'Kumandaların yeri her araçta aynı olduğu için gerek yoktur',
      'Sınav süresini uzatmak için',
    ],
    answerIndex: 1,
    explanation:
      'Kumandaların yeri ve yönü araçtan araca değişebilir. Yağmur başladığında sileceği, dönüşte sinyal kolunu el yordamıyla aramak, gözü ve zihni tam da kritik anda yoldan koparır. Harekete geçmeden yapılan birkaç saniyelik tanıma turu, sürüş boyunca kumandalara bakmadan ulaşmayı sağlar.',
    whyWrong: [
      'Amaç görüntü vermek ya da süre uzatmak değil, sürüş sırasındaki dikkat bölünmesini önlemektir.',
      'Kumanda düzeni her araçta aynı değildir; özellikle sinyal ve silecek kolları farklı konumlanabilir.',
    ],
    objective: 'Yabancı araçta kumanda tanıma alışkanlığının dikkat yönetimindeki rolünü kavramak.',
    tags: ['sinav-hazirlik', 'kumanda-tanima', 'dikkat-yonetimi'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-448',
    subject: 'pratik',
    topic: 'sinav-iptal',
    difficulty: 'orta',
    stem: 'Direksiyon sınavının park ve manevra bölümünde bariyere ya da dubaya çarpmanın değerlendirilmesi nasıldır?',
    options: [
      'Hiç değerlendirilmez, yalnızca sözlü uyarı yapılır',
      'Sınav sonunda küçük bir not düşülür',
      'Aday üç hakka kadar çarpabilir',
      'Aracın fiziksel sınır tanımadığını gösterdiği için ağır (elemeye götüren) hata grubunda değerlendirilir; gerçek trafikte bu, bir araca ya da yayaya çarpmanın karşılığıdır',
    ],
    answerIndex: 3,
    explanation:
      'Manevra alanındaki bariyer ve dubalar, gerçek trafikteki araçları, duvarları ve yayaları temsil eder. Bunlara çarpmak, adayın aracın boyutlarını ve manevrasını kontrol edemediğini gösterdiği için ağır hata grubunda ele alınır ve elemeye götürür. Çizgiye basmak gibi daha hafif ihlaller ise puan kırdırır.',
    whyWrong: [
      'Çarpmayı uyarıyla ya da küçük notla geçiştirmek, temsil ettiği gerçek riskle bağdaşmaz.',
      'Ağır hatalarda hak sayısı mantığı yoktur; güvenliği doğrudan bozan tek hata yeterlidir.',
    ],
    objective: 'Manevra alanındaki fiziksel temasın eleme mantığını kavramak.',
    tags: ['sinav-iptal', 'bariyer', 'agir-hata'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-449',
    subject: 'pratik',
    topic: 'sinav-iptal',
    difficulty: 'zor',
    stem: 'Sınavda sinyali biraz geç vermek ile geri park sırasında kaldırıma çarpmak arasındaki değerlendirme farkının temel ölçütü nedir?',
    options: [
      'Güvenliğin doğrudan tehlikeye girip girmediği: geç sinyal eksiklik olarak puan kırdırır; kaldırıma çarpmak araç hâkimiyeti kaybı sayıldığından tek başına elemeye götürebilir',
      'Hataların sınavın başında mı sonunda mı yapıldığı',
      'Görevlinin o günkü tutumu',
      'Aracın markası ve büyüklüğü',
    ],
    answerIndex: 0,
    explanation:
      'Sınav değerlendirmesinin omurgası, hatanın güvenliği ne ölçüde bozduğudur. Geç verilen sinyal bir eksikliktir ve puan kırdırır; ancak kaldırıma çarpmak, aracın fiziksel sınırlarının kontrol edilemediğini gösteren bir hâkimiyet kaybıdır ve tek başına elemeye götürebilir. Aday, hatalarını bu ölçekle tartmayı bilmelidir.',
    whyWrong: [
      'Hatanın zamanı, görevlinin tutumu ya da aracın markası değerlendirme ölçütü değildir.',
      'Bu tür dış etkenlere odaklanmak, adayın asıl geliştirmesi gereken güvenlik ölçüsünü gözden kaçırtır.',
    ],
    objective: 'Hafif ve ağır sınav hatalarını güvenlik etkisine göre ayırt edebilmek.',
    tags: ['sinav-iptal', 'hata-siniflama', 'puanlama'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-450',
    subject: 'pratik',
    topic: 'heyecan-nefes',
    difficulty: 'kolay',
    stem: 'Sınav sırası beklerken kalbi hızlanan ve elleri titreyen aday, heyecanını hangi basit teknikle yatıştırabilir?',
    options: [
      'Sıra gelene kadar telefonda hızlı oyunlar oynayarak',
      'Burnundan yavaşça derin nefes alıp ağzından daha da yavaş vererek bunu birkaç kez tekrarlamak; omuzları gevşetip dikkatini ilk yapacağı adıma (koltuk-ayna-kemer) yöneltmek',
      'Kahve ve enerji içeceği içerek',
      'Diğer adaylarla sınavın zorluğu hakkında konuşarak',
    ],
    answerIndex: 1,
    explanation:
      'Yavaş ve derin nefes, hızlanan kalp atışını dengeleyen en pratik yoldur: burundan yavaşça alınan nefes, ağızdan daha da yavaş verilir ve birkaç kez tekrarlanır. Omuzları bilinçli gevşetmek bedensel gerginliği azaltır; dikkati ilk somut adıma yöneltmek ise zihni belirsiz kaygıdan somut plana taşır.',
    whyWrong: [
      'Kafein ve enerji içecekleri kalp atışını daha da hızlandırıp titremeyi artırabilir.',
      'Hızlı oyunlar ya da zorluk sohbetleri zihni yatıştırmaz, kaygıyı besler.',
    ],
    objective: 'Sınav öncesi heyecanı nefes ve odak teknikleriyle yönetebilmek.',
    tags: ['heyecan-yonetimi', 'nefes-teknigi', 'sinav-psikolojisi'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-451',
    subject: 'pratik',
    topic: 'heyecan-nefes',
    difficulty: 'orta',
    stem: 'Sınav sürüşü sırasında paniğe kapıldığını hisseden (nefesi sıklaşan, direksiyonu kasılarak tutan) aday ne yapmalıdır?',
    options: [
      'Sınavı hemen bırakıp aracı yol ortasında durdurmak',
      'Daha hızlı giderek sınavı bir an önce bitirmeye çalışmak',
      'Trafik uygunsa hızını bir miktar azaltıp uzun bir nefes vermek, direksiyondaki kavramayı bilinçli gevşetmek ve dikkatini sınavın tamamı yerine yalnızca sıradaki tek adıma odaklamak',
      'Görevliyle sohbet ederek dikkatini sürüşten uzaklaştırmak',
    ],
    answerIndex: 2,
    explanation:
      'Panik anında beden kasılır ve zihin sınavın tamamına, kalan her şeye birden odaklanmaya çalışır. Çözüm bunun tersidir: trafik uygunsa hız bir miktar azaltılır, uzun bir nefes verilir, direksiyondaki kasılı kavrama bilinçli gevşetilir ve dikkat yalnızca sıradaki tek adıma (örneğin şu kavşakta sinyal) daraltılır. Küçük adımlar paniği dağıtır.',
    whyWrong: [
      'Aracı yol ortasında bırakmak ya da hızlanmak paniği çözmez, yeni ve gerçek tehlikeler yaratır.',
      'Sohbetle dikkati sürüşten koparmaya çalışmak, tam da kaçınılması gereken şeydir.',
    ],
    objective: 'Sürüş sırasındaki paniği hız, nefes ve tek adım odağıyla yönetebilmek.',
    tags: ['heyecan-yonetimi', 'panik', 'odaklanma'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-452',
    subject: 'pratik',
    topic: 'otoyol-katilim',
    difficulty: 'orta',
    stem: 'Otoyoldan çıkarken hız nerede düşürülmelidir?',
    options: [
      'Ana şeritte değil; yavaşlama (çıkış) şeridine girdikten sonra, çıkış virajının hızına kademeli inilerek',
      'Çıkışa birkaç kilometre kala ana şeritte iyice yavaşlayarak',
      'Yavaşlama şeridi hiç kullanılmadan doğrudan bağlantı yoluna girerek',
      'Hız hiç düşürülmez, viraja otoyol hızıyla girilir',
    ],
    answerIndex: 0,
    explanation:
      'Yavaşlama şeridinin amacı, hız düşürme işlemini ana akışın dışına taşımaktır. Sürücü sinyal verip çıkış şeridine akış hızıyla girer, frenlemeyi bu şeritte yapar ve bağlantı yolunun viraj hızına kademeli iner. Ana şeritte erken yavaşlamak, arkadan yüksek hızla gelenler için ciddi çarpma riski yaratır.',
    whyWrong: [
      'Ana şeritte yavaşlamak, otoyol hızındaki arkadaki araçlarla tehlikeli bir hız farkı doğurur.',
      'Viraja otoyol hızıyla girmek, çıkış rampalarındaki savrulma kazalarının başlıca nedenidir.',
    ],
    objective: 'Otoyol çıkışında yavaşlamayı doğru şeritte zamanlamak.',
    tags: ['otoyol', 'yavaslama-seridi', 'cikis'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-453',
    subject: 'pratik',
    topic: 'geri-duz-gitme',
    difficulty: 'zor',
    stem: 'Geri geri düz giderken aracın hattan saptığını fark eden sürücünün büyük direksiyon hareketiyle düzeltme yapması neden yanlıştır?',
    options: [
      'Direksiyon geri viteste kilitlendiği için',
      'Büyük hareket motoru stop ettirdiği için',
      'Geri viteste direksiyon hiç kullanılmadığı için',
      'Geri harekette direksiyon girdisi abartılı sonuç verir; büyük düzeltme aracı bu kez ters yöne fazla savurur ve zikzak başlar. Doğrusu sapmayı erken fark edip küçük ve kısa düzeltmeler yapmaktır',
    ],
    answerIndex: 3,
    explanation:
      'Geri harekette yönlendirme mantığı tersine döndüğü için aynı direksiyon girdisi ileri gidişe göre daha abartılı hissedilir ve gecikmeli düzeltilir. Sapma büyüdükten sonra yapılan büyük düzeltme aracı ters yöne fazla kaçırır; ardışık büyük düzeltmeler zikzak çizdirir. Çözüm, sürünme hızında gidip sapmayı milim düzeyindeyken küçük hareketlerle almaktır.',
    whyWrong: [
      'Direksiyon geri viteste kilitlenmez ve elbette kullanılır; sorun girdinin ölçüsüdür.',
      'Direksiyon hareketinin motoru durdurmakla bir ilgisi yoktur.',
    ],
    objective: 'Geri seyirde erken ve küçük düzeltme ilkesini kavramak.',
    tags: ['geri-duz-gitme', 'direksiyon-duzeltme', 'zikzak'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-454',
    subject: 'pratik',
    topic: 'yaya-gecidi-yaklasim',
    difficulty: 'kolay',
    stem: 'Yavaş ilerleyen kuyruk trafiğinde, önünüzdeki araçların durma ihtimali varken yaya geçidine gelindiğinde ne yapılmalıdır?',
    options: [
      'Öndeki araca yapışıp geçidin üzerinde beklemek',
      'İlerideki boşluğun aracınıza yetmeyeceği belliyse geçidin öncesinde durup geçidi boş bırakmak; yayaların geçiş yolu kapatılmaz',
      'Geçidin üzerinde durup yayalara el işareti yapmak',
      'Geçidi hızla geçip öndekine iyice yaklaşmak',
    ],
    answerIndex: 1,
    explanation:
      'Kuyruk trafiğinde araç, ancak geçidin karşısında kendisine yetecek boşluk varsa geçidin üzerinden ilerlemelidir. Boşluk yetmeyecekse geçidin öncesinde durulur ve geçit yayalar için açık bırakılır. Geçit üzerinde duran araç, yayaları araçların arasından, görünmez noktalardan geçmeye zorlar.',
    whyWrong: [
      'Geçit üzerinde beklemek, el işareti yapılsa bile yayaların güvenli geçiş hattını kapatır.',
      'Hızla geçip öndekine yapışmak hem takip mesafesini bozar hem sonraki geçitte aynı hatayı hazırlar.',
    ],
    objective: 'Kuyruk trafiğinde yaya geçidini boş bırakma alışkanlığı kazanmak.',
    tags: ['yaya-gecidi', 'kuyruk-trafik', 'gecit-bos-birakma'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-455',
    subject: 'pratik',
    topic: 'tunel-surus',
    difficulty: 'zor',
    stem: 'Uzun bir tünelin çıkışına yaklaşırken sürücüyü bekleyen iki etki ve doğru hazırlık nedir?',
    options: [
      'Zemin ıslanır ve motor soğur; kalorifer açılır',
      'Trafik yoğunlaşır ve yakıt azalır; depo kontrol edilir',
      'Gözler parlak gün ışığına geçişte kısa süre kamaşır ve açık kesitte yan rüzgâr aracı aniden itebilir; hız korunarak direksiyon iki elle kararlı tutulur ve şeritte kalmaya odaklanılır',
      'Farlar söner ve fren zayıflar; araç durdurulur',
    ],
    answerIndex: 2,
    explanation:
      'Tünel çıkışı, girişin aynadaki yansımasıdır: loş ortamdan parlak gün ışığına geçen gözler kısa süre kamaşır; ayrıca tünelin rüzgârdan korunan kesitinden açık alana çıkan araç yan rüzgârın ani itmesiyle karşılaşabilir. Doğru hazırlık, direksiyonu iki elle kararlı tutmak, hızda ani değişiklik yapmamak ve o birkaç saniyede şeritte kalmaya odaklanmaktır.',
    whyWrong: [
      'Tünel çıkışında motorun soğuması, yakıtın azalması ya da farların sönmesi gibi etkiler söz konusu değildir.',
      'Aracı durdurmak ya da kalorifer açmak, kamaşma ve yan rüzgâr etkilerine karşılık gelmeyen yanlış önlemlerdir.',
    ],
    objective: 'Tünel çıkışındaki kamaşma ve yan rüzgâr etkisine hazırlıklı olmak.',
    tags: ['tunel', 'yan-ruzgar', 'goz-uyumu'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
];
