/**
 * ÖZGÜN araç tekniği (motor) soruları — 6. genişletme (Program 2 · Faz 9). ROADMAP C.4/E.6.
 * Kaynak = MEB araç tekniği müfredatı; KENDİ İFADEMİZLE.
 */
import type { QuestionInput } from '@ea/content-schema';

const SRC = 'MEB araç tekniği müfredatı (özgün ifade)';

export const MOTOR_QUESTIONS_6: QuestionInput[] = [
  {
    id: 'motor-601',
    subject: 'motor',
    topic: 'aku-teshis',
    difficulty: 'orta',
    stem: 'Soğuk bir kış sabahı marşa basıldığında motor ağır ağır ve isteksizce dönüyor; aynı anda farlar sönükleşiyor ve korna cılız çıkıyorsa en olası neden hangisidir?',
    options: [
      'Silecek motorunun bozulması',
      'Polen filtresinin kirlenmesi',
      'Aküde yeterli enerji kalmaması (zayıf/yaşlı akü); soğukta akünün gücü daha da düştüğü için marş, far ve kornaya yetecek akımı sağlayamaması',
      'Egzoz susturucusunun delinmesi',
    ],
    answerIndex: 2,
    explanation:
      'Marş, far ve korna aynı akü kaynağından beslenir. Zayıf bir akü soğukta iyice güçsüzleşir; marş çekilirken gerilim düştüğü için tüm tüketiciler birden zayıflar. Marşın ağır dönmesiyle ışıkların sönükleşmesinin birlikte görülmesi tipik olarak akü/şarj zayıflığını işaret eder.',
    whyWrong: [
      'Silecek ve polen filtresi motorun dönüş gücüyle ve aydınlatmayla ilgisizdir.',
      'Delik susturucu bir ses/kaçak sorunudur; marş gücünü ve far parlaklığını etkilemez.',
    ],
    objective:
      'Soğukta ağır marş + sönükleşen tüketiciler belirtisini akü zayıflığıyla ilişkilendirmek.',
    tags: ['aku', 'soguk-mars', 'teshis'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-602',
    subject: 'motor',
    topic: 'debriyaj-teshis',
    difficulty: 'orta',
    stem: 'Manuel vitesli bir araçta debriyaj pedalına sonuna kadar basıldığı hâlde vitesler zor giriyor ve geçişlerde çıtırtı/sürtme sesi duyuluyorsa en olası neden hangisidir?',
    options: [
      'Far ampullerinin ömrünü doldurması',
      'Debriyajın kavramayı tam ayıramaması (balata, hidrolik/tel ayarı veya baskı sorunu); dönmeye devam eden dişlilerin senkronu zorlaması',
      'Lastik hava basıncının yükselmesi',
      'Ön cam suyunun bitmesi',
    ],
    answerIndex: 1,
    explanation:
      'Vitesin rahat girmesi için debriyaja basıldığında motorla şanzıman bağlantısının tamamen kesilmesi gerekir. Ayarı bozulan, havası kaçan hidrolik veya aşınmış debriyaj kavramayı tam ayıramaz; dişliler dönmeye devam ettiği için senkromeçler zorlanır, vites zor girer ve ses çıkar.',
    whyWrong: [
      'Far, lastik basıncı ve cam suyu güç aktarım hattından bağımsızdır; vites geçişini etkilemez.',
      'Belirti mekanik kavrama sorununa işaret eder, elektrik veya konfor donanımına değil.',
    ],
    objective: 'Debriyaj tam ayrılmadığında vitesin zor girmesi belirtisini tanımak.',
    tags: ['debriyaj', 'vites-gecmiyor', 'teshis'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-603',
    subject: 'motor',
    topic: 'atesleme-teshis',
    difficulty: 'zor',
    stem: 'Benzinli bir araçta gaz kesildiğinde ya da sürüş sırasında egzozdan zaman zaman "pat" diye patlama sesleri geliyorsa bu belirti en çok neyi düşündürür?',
    options: [
      'Lastik balansının bozulduğunu',
      'Amortisörlerin aşındığını',
      'Direksiyon rotunun ayarsız olduğunu',
      'Yanmanın silindir içinde tam zamanında tamamlanmadığını; yanmamış yakıtın sıcak egzozda geç tutuşarak patladığını (ateşleme/yakıt karışımı veya zamanlama sorunu)',
    ],
    answerIndex: 3,
    explanation:
      'Egzozdan gelen patlama (geri tepme), silindirde tam yanmayan yakıtın egzoz hattında geç tutuşmasıyla oluşur. Bozuk buji/bobin, zengin-fakir karışım veya ateşleme zamanlaması sorunları bunun tipik nedenleridir. Sistem servise kontrol ettirilmelidir; ihmal edilirse katalizör de zarar görebilir.',
    whyWrong: [
      'Balans ve amortisör titreşim/salınım sorunudur; egzoz patlamasıyla ilgisi yoktur.',
      'Rot ayarsızlığı aracın yana çekmesine yol açar, egzozdan ses gelmesine değil.',
    ],
    objective: 'Egzozdan patlama sesini eksik yanma/ateşleme sorunuyla ilişkilendirmek.',
    tags: ['atesleme', 'egzoz-patlamasi', 'teshis'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-604',
    subject: 'motor',
    topic: 'yakit-kokusu',
    difficulty: 'kolay',
    stem: 'Seyir hâlindeyken kabinde belirgin bir benzin/yakıt kokusu hissedilirse doğru davranış nedir?',
    options: [
      'Güvenli bir yerde durup motoru durdurmak, kontağı kapatmak ve yakıt kaçağı ihtimaline karşı sistemi kontrol ettirmeden yola devam etmemek',
      'Camları kapatıp koku geçene kadar hızlanarak sürüşü sürdürmek',
      'Kaloriferi son kademede açıp kokuyu dağıtmak',
      'Depoyu tıka basa doldurup yola devam etmek',
    ],
    answerIndex: 0,
    explanation:
      'Yakıt kokusu bir kaçağın işareti olabilir; sıcak parçalar ya da kıvılcım yakınında yakıt buharı yangın riski taşır. En güvenlisi uygun bir yerde durup motoru durdurmak, kontağı kapatmak, kıvılcım/ateşten uzak durmak ve kaçağın kaynağını kontrol ettirmektir.',
    whyWrong: [
      'Hızlanmak yangın riskini azaltmaz; kaçak sürerse tehlike büyür.',
      'Kaloriferle kokuyu dağıtmak sorunu gizler; depoyu doldurmak kaçağı artırabilir.',
    ],
    objective: 'Yakıt kokusunda durup kaynağı araştırma refleksini kazandırmak.',
    tags: ['yakit-kacagi', 'yangin-riski', 'acil-mudahale'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-605',
    subject: 'motor',
    topic: 'sarj-lambasi',
    difficulty: 'orta',
    stem: 'Sürüş sırasında akü/şarj ikaz lambası (akü şekli) yanıp sönmeden yolda kalırsa doğru değerlendirme hangisidir?',
    options: [
      'Lamba yanmasının hiçbir önemi yoktur, sürekli göz ardı edilebilir',
      'Şarj sistemi (alternatör veya kayış) artık aküyü doldurmuyor olabilir; araç bir süre akünün kalan enerjisiyle gider, bu yüzden gereksiz tüketiciler kapatılıp en kısa sürede servise gidilmelidir',
      'Derhâl motor durdurulmazsa motor patlar',
      'Lamba yalnızca yakıtın azaldığını gösterir',
    ],
    answerIndex: 1,
    explanation:
      'Sürüşte yanan şarj lambası genellikle alternatörün üretmediğini ya da tahrik kayışının gevşeyip koptuğunu gösterir. Motor bir süre akünün birikmiş enerjisiyle çalışmaya devam eder; ancak akü tükenince araç stop eder. Bu nedenle far, kalorifer fanı gibi gereksiz tüketiciler kapatılıp vakit kaybetmeden servise gidilmelidir.',
    whyWrong: [
      'Şarj uyarısı önemsiz değildir; enerji üretimi kesilmiştir.',
      'Motor bu uyarıyla "patlamaz"; ayrıca lamba yakıt seviyesini göstermez, onun ayrı göstergesi vardır.',
    ],
    objective: 'Şarj lambası yandığında sınırlı mesafeyle servise ulaşma davranışını bilmek.',
    tags: ['sarj-lambasi', 'alternator', 'sinirli-mesafe'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-606',
    subject: 'motor',
    topic: 'airbag-lambasi',
    difficulty: 'kolay',
    stem: 'Gösterge panelindeki hava yastığı (airbag/SRS) ikaz lambası sürekli yanık kalıyorsa bu ne anlama gelir?',
    options: [
      'Hava yastığının o an açıldığını',
      'Aracın hızının sınırlandığını',
      'Hava yastığı sisteminde bir arıza bulunduğunu; sistemin bir kazada beklenen şekilde açılmayabileceğini, bu yüzden vakit kaybetmeden kontrol ettirilmesi gerektiğini',
      'Motor yağının azaldığını',
    ],
    answerIndex: 2,
    explanation:
      'Kontak açıldığında kısa süre yanıp sönen airbag lambası normaldir; ancak sürekli yanık kalması sistemin kendi kendini denetlerken bir arıza (sensör, kablo, tokalık veya kumanda ünitesi) bulduğunu gösterir. Bu durumda yastık kazada açılmayabilir; sistem yetkili serviste kontrol ettirilmelidir.',
    whyWrong: [
      'Lamba yastığın açıldığını değil, denetimde arıza bulunduğunu bildirir.',
      'Hız sınırı ve yağ seviyesi bu lambanın konusu değildir; onların ayrı uyarıları vardır.',
    ],
    objective: 'Sürekli yanan airbag lambasının sistem arızası anlamını bilmek.',
    tags: ['hava-yastigi', 'ikaz-lambasi', 'pasif-guvenlik'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-607',
    subject: 'motor',
    topic: 'yana-cekme',
    difficulty: 'kolay',
    stem: 'Düz ve düzgün bir yolda araç hafifçe bir tarafa çekmeye başladıysa, servise gitmeden önce yapılabilecek en basit ilk kontrol hangisidir?',
    options: [
      'Motor yağının markasını değiştirmek',
      'Silecek lastiklerini yenilemek',
      'Polen filtresini temizlemek',
      'İki taraftaki lastiklerin hava basınçlarını ölçüp karşılaştırmak; bir taraftaki lastik sönükse araç o yöne çeker',
    ],
    answerIndex: 3,
    explanation:
      'Aracın yana çekmesinin en basit ve sık nedeni, bir taraftaki lastiğin diğerinden düşük basınçlı olmasıdır; sönük lastik daha çok yuvarlanma direnci yaratıp aracı o yöne çeker. Basınçlar eşitlendiği hâlde çekme sürüyorsa rot ayarı, fren veya süspansiyon kontrol ettirilmelidir.',
    whyWrong: [
      'Yağ markası ve silecek lastiği aracın yön tutuşuyla ilgisizdir.',
      'Polen filtresi kabin havasını temizler; direksiyon çekmesine etkisi yoktur.',
    ],
    objective: 'Yana çekmede önce lastik basınç farkını kontrol etme alışkanlığını edinmek.',
    tags: ['yana-cekme', 'lastik-basinci', 'teshis'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-608',
    subject: 'motor',
    topic: 'teker-rulmani',
    difficulty: 'zor',
    stem: 'Hız arttıkça yükselen, sürekli bir uğultu/uğuldama duyuluyor; ses viraj dönerken bir tarafta artıp diğer tarafta azalıyorsa en olası neden hangisidir?',
    options: [
      'Tekerlek göbeğindeki (aks) rulmanın aşınması; yük yön değiştirdikçe sesin şiddetlenip hafiflemesi rulman arızasının tipik belirtisidir',
      'Bujilerin kirlenmesi',
      'Yakıt filtresinin tıkanması',
      'Termostatın açık takılması',
    ],
    answerIndex: 0,
    explanation:
      'Aşınan tekerlek rulmanı, hızla orantılı sürekli bir uğultu üretir. Virajda aracın ağırlığı bir tarafa aktarıldığında o taraftaki rulmanın yükü değişir; bu yüzden ses sağa-sola dönüşte belirgin biçimde artıp azalır. Rulman gecikmeden değiştirilmelidir, aksi hâlde tekerlek boşluk yapabilir.',
    whyWrong: [
      'Kirli buji ve tıkalı yakıt filtresi motor çalışmasını bozar; hıza bağlı uğultu ve virajla değişen ses üretmez.',
      'Termostat sorunu soğutma/ısınma ile ilgilidir, tekerlekten gelen sesle değil.',
    ],
    objective: 'Hıza bağlı, virajla değişen uğultuyu tekerlek rulmanıyla ilişkilendirmek.',
    tags: ['teker-rulmani', 'ugultu', 'teshis'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-609',
    subject: 'motor',
    topic: 'rot-basi',
    difficulty: 'zor',
    stem: 'Direksiyonda hissedilen boşluğun yanı sıra bozuk/engebeli yolda ön taraftan "tık tık" sesleri geliyorsa öncelikle hangi grup kontrol ettirilmelidir?',
    options: [
      'Egzoz susturucusu ve katalizör',
      'Direksiyon-ön düzen bağlantı parçaları (rot başı, rotil gibi mafsallar); boşluk yapan bu parçalar hem sesin hem direksiyon boşluğunun kaynağı olabilir',
      'Polen filtresi ve klima gazı',
      'Silecek kolu ve fıskiyeler',
    ],
    answerIndex: 1,
    explanation:
      'Rot başı ve rotil gibi mafsallar, direksiyon hareketini tekerleklere iletir ve tekerleği araca bağlar. Zamanla boşluk yaparlar; bu boşluk direksiyonda oynama olarak hissedilir ve bozuk yolda mafsalın vurmasıyla "tık tık" ses çıkar. Aşınan bu parçalar güvenlik açısından ihmal edilmemelidir.',
    whyWrong: [
      'Egzoz ve katalizör güç/ses sistemidir; direksiyon boşluğuyla ilgisi yoktur.',
      'Polen filtresi, klima, silecek gibi donanımlar yön kontrolü ve mafsallarla ilgili değildir.',
    ],
    objective: 'Direksiyon boşluğu + ön taraf tıkırtısını rot başı/rotil aşınmasıyla bağdaştırmak.',
    tags: ['rot-basi', 'rotil', 'on-duzen'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-610',
    subject: 'motor',
    topic: 'fren-kaliper',
    difficulty: 'zor',
    stem: 'Kısa bir sürüşün ardından bir tekerleğin jantı diğerlerine göre çok daha sıcak, hafif bir yanık/kızgın metal kokusu var ve araç frene basılmadan da o yöne hafifçe çekiyorsa en olası neden hangisidir?',
    options: [
      'Yakıt pompasının zayıflaması',
      'Buji kablosunun gevşemesi',
      'O tekerlekteki fren kaliperinin (fren pistonunun) sıkışıp balatayı diske sürekli bastırması; sürekli sürtünme ısı, koku ve tek yöne çekme üretir',
      'Ön cam suyunun donması',
    ],
    answerIndex: 2,
    explanation:
      'Kaliperi sıkışan tekerlekte balata, pedala basılmasa bile diske sürtmeye devam eder. Bu sürekli sürtünme o tekerleği aşırı ısıtır, yanık kokusu yayar, yakıt tüketimini artırır ve aracı sürtünen tarafa çeker. Sıkışan kaliper/piston zaman geçirmeden onarılmalıdır.',
    whyWrong: [
      'Yakıt pompası ve buji kablosu motor çalışmasıyla ilgilidir; tek tekerlek ısınmasına yol açmaz.',
      'Cam suyunun donması jant sıcaklığıyla ve fren sürtünmesiyle ilgisizdir.',
    ],
    objective:
      'Tek jant aşırı ısınması + çekme + koku belirtisini sıkışan fren kaliperiyle ilişkilendirmek.',
    tags: ['fren-kaliper', 'balata-surtme', 'teshis'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-611',
    subject: 'motor',
    topic: 'yokusta-park',
    difficulty: 'orta',
    stem: 'Manuel vitesli bir araç eğimli bir yolda park edilirken, el freniyle birlikte hangi vites kademesi güvenlik için tercih edilmelidir?',
    options: [
      'Yokuş yukarı bakan araçta 1. vites, yokuş aşağı bakan araçta geri vites bırakmak (her iki durumda da el freni çekili olmalı)',
      'Her durumda boş viteste bırakmak',
      'Yokuş yukarıda geri vites, yokuş aşağıda 1. vites bırakmak',
      'Vites kademesinin hiçbir önemi yoktur; yalnızca el freni yeterlidir',
    ],
    answerIndex: 0,
    explanation:
      'Viteste bırakılan araçta motor sıkıştırması ek bir tutucu görevi görür; el freni çözülse bile araç kolayca kaçmaz. Aracın kaçma yönü aşağı doğru olduğundan, motor direncinin bu yöne karşı koyması istenir: yokuş yukarıda ileri (1.) vites, yokuş aşağıda geri vites tercih edilir. El freni de mutlaka çekilir; eğim fazlaysa tekerleğe takoz konur.',
    whyWrong: [
      'Boş viteste bırakılan araç yalnızca el frenine kalır; el freni çözülür/kaçarsa araç serbest kayar.',
      'Vitesin ters seçilmesi kaçma yönüne motor direncini azaltır; kademe önemsiz değildir.',
    ],
    objective: 'Eğimde el freniyle birlikte doğru park vitesini seçmeyi öğrenmek.',
    tags: ['yokusta-park', 'el-freni', 'vites'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-612',
    subject: 'motor',
    topic: 'kis-silecek',
    difficulty: 'kolay',
    stem: 'Karlı/buzlu bir gecede araç dışarıda park edilecekse silecekler ve cam için önerilen kış önlemi hangisidir?',
    options: [
      'Silecekleri camdan yukarı kaldırıp havada bırakmak veya araya bez koymak; sabah camdaki buzu silecekle değil, uygun kazıyıcı/buz çözücüyle temizlemek',
      'Sabah donmuş camı silecekleri çalıştırarak temizlemek',
      'Cam suyu haznesine kaynar su koymak',
      'Silecekleri en hızlı kademede bırakıp kontağı öyle kapatmak',
    ],
    answerIndex: 0,
    explanation:
      'Buzlu cama yapışan silecek lastikleri, çalıştırıldığında yırtılabilir ya da silecek motoru zorlanıp yanabilir. Bu yüzden gece silecekler camdan kaldırılır veya araya bez konur; sabah cam, silecekle değil kazıyıcı ve buz çözücüyle temizlenir. Buz çözülmeden sileceği çalıştırmak lastiği ve motoru yıpratır.',
    whyWrong: [
      'Donmuş camı silecekle temizlemek lastiği yırtar, motoru zorlar.',
      'Cama/hazneye kaynar su dökmek cam gerilimini bozup çatlatabilir; hazneye donmayan cam suyu konur.',
    ],
    objective: 'Kışın silecek ve camla ilgili donma önlemlerini bilmek.',
    tags: ['kis-bakimi', 'silecek', 'buz-cozme'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-613',
    subject: 'motor',
    topic: 'katalitik-hirsizligi',
    difficulty: 'orta',
    stem: 'Bir süre park edilip kalkan araç çalıştırıldığında egzoz aniden aşırı yüksek ve kaba bir gürültü çıkarmaya başladıysa (araç sanki susturucusuz gibi ötüyorsa) akla gelmesi gereken ihtimallerden biri nedir?',
    options: [
      'Lastik basıncının düştüğü',
      'Polen filtresinin tıkandığı',
      'Ön cam suyunun bittiği',
      'Egzoz hattının kesildiği; örneğin katalitik konvertörün çalınmak için kesilmiş olabileceği veya egzozda kopma/delik oluştuğu',
    ],
    answerIndex: 3,
    explanation:
      'Egzoz sistemi, gazları hem yönlendirir hem de susturur. Katalitik konvertör hırsızlık amacıyla kesildiğinde ya da egzoz borusu koptuğunda hat açık kalır; motor sesi hiç boğulmadan dışarı çıktığı için araç son derece gürültülü çalışır. Böyle bir durumda araç kullanılmadan kontrol ettirilmelidir; ayrıca kaçak gaz riski de vardır.',
    whyWrong: [
      'Lastik basıncı, polen filtresi ve cam suyu egzoz sesiyle ilgili değildir.',
      'Bu belirtiler egzoz hattındaki bir kopma/kesilmeye işaret eder, başka sistemlere değil.',
    ],
    objective:
      'Ani aşırı egzoz gürültüsünü egzoz hattı kesilmesi/katalizör hırsızlığıyla ilişkilendirmek.',
    tags: ['katalizor', 'egzoz-kesilmesi', 'teshis'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-614',
    subject: 'motor',
    topic: 'sasi-numarasi',
    difficulty: 'kolay',
    stem: 'Aracın şasi (VIN) numarasıyla ilgili doğru ifade aşağıdakilerden hangisidir?',
    options: [
      'Her araca özgü bir kimlik numarasıdır; ruhsatta yazar ve genellikle motor bölmesi, ön cam alt köşesi ya da kapı eşiği gibi bir yere de basılıdır',
      'Yalnızca aracın rengini belirtir',
      'Lastik basıncını gösteren bir sayıdır',
      'Yakıt deposunun hacmini bildirir',
    ],
    answerIndex: 0,
    explanation:
      'Şasi (VIN) numarası, her araca fabrikada verilen ve o araca özgü bir kimlik numarasıdır. Ruhsatta yer alır ve araç üzerinde de (motor bölmesi, ön cam alt köşesi, kapı eşiği/orta direk gibi) bir yere işlenir. Tescil, muayene, sigorta ve yedek parça işlemlerinde aracın doğru tanımlanmasını sağlar.',
    whyWrong: [
      'Numara rengi değil, aracın kimliğini belirtir.',
      'Lastik basıncı ve depo hacmi ayrı bilgilerdir; şasi numarasıyla ifade edilmez.',
    ],
    objective: 'Şasi (VIN) numarasının kimlik işlevini ve yerini bilmek.',
    tags: ['sasi-numarasi', 'vin', 'arac-kimligi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-615',
    subject: 'motor',
    topic: 'far-bugulanmasi',
    difficulty: 'orta',
    stem: 'Far camının içinde buğu/nem toplandığı görülüyorsa bunun tipik nedeni ve doğru değerlendirme nedir?',
    options: [
      'Motorun aşırı ısındığı; derhâl durulmalıdır',
      'Far muhafazasının sızdırmazlığının/havalandırmasının bozulup içeri nem girmesi; hafif buğu bir süre sonra kaybolabilir, ancak su birikiyorsa ampule ve elektriğe zarar vermeden önce müdahale edilmelidir',
      'Akünün şarj olmadığı',
      'Fren balatalarının bittiği',
    ],
    answerIndex: 1,
    explanation:
      'Far muhafazaları, ısı farkıyla oluşan nemin dışarı atılması için küçük havalandırma kanallarına sahiptir. Sızdırmazlık contası ya da bu kanallar bozulunca içeri nem girer ve cam içten buğulanır. Sıcaklık değişimiyle geçen hafif buğu sorun değildir; ancak içeride su damlacıkları/birikinti varsa ampul ve bağlantılar zarar görmeden onarılmalıdır.',
    whyWrong: [
      'Motor sıcaklığı, akü şarjı ve fren balatası far içindeki nemle ilgili değildir.',
      'Bu belirti far muhafazasının sızdırmazlık/havalandırma sorunudur, motor arızası değildir.',
    ],
    objective: 'Far içi buğulanmayı muhafaza sızdırmazlığı/havalandırmasıyla açıklamak.',
    tags: ['far', 'bugulanma', 'nem'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-616',
    subject: 'motor',
    topic: 'start-stop-teshis',
    difficulty: 'orta',
    stem: 'Otomatik dur-kalk (start-stop) sistemi olan bir araçta, sistem beklenen durumlarda motoru durdurmuyorsa bunun makul nedenlerinden biri hangisidir?',
    options: [
      'Aracın rengi',
      'Silecek suyunun dolu olması',
      'Akünün yeterince şarjlı olmaması, kabinin ısıtılıp/soğutulması için klima yükünün yüksek olması ya da motorun henüz çalışma sıcaklığına ulaşmamış olması gibi sistemin motoru durdurmayı uygun bulmadığı koşulların bulunması',
      'Lastiklerin yeni olması',
    ],
    answerIndex: 2,
    explanation:
      'Start-stop, yalnızca uygun koşullarda motoru durdurur. Akü zayıfsa (yeniden marş için yeterli enerji güvence altında değilse), klima kabini henüz istenen sıcaklığa getirmediyse ya da motor/soğutma sistemi soğuksa, sistem konforu ve güvenliği korumak için motoru çalışır tutar. Bu, çoğu zaman arıza değil, tasarlanmış bir davranıştır.',
    whyWrong: [
      'Aracın rengi ve lastiklerin yeniliği start-stop kararını etkilemez.',
      'Silecek suyunun dolu olması sistemle ilgisizdir.',
    ],
    objective: 'Start-stop devreye girmeme nedenlerini (akü/klima/sıcaklık) ayırt etmek.',
    tags: ['start-stop', 'aku', 'teshis'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-617',
    subject: 'motor',
    topic: 'lpg-sistemi',
    difficulty: 'kolay',
    stem: 'LPG sistemi bulunan bir araçla ilgili doğru ifade aşağıdakilerden hangisidir?',
    options: [
      'LPG tüpü genellikle bagaj bölümüne/stepne yuvasına yerleştirilir; ısıyla genleşmeye pay bırakmak için tüp tam dolu değil, belirli bir sınıra (yaklaşık dörtte üçü/gövdesinin çoğu) kadar doldurulur ve tüpün periyodik testi/muayenesi gerekir',
      'LPG tüpü motorun içine takılır',
      'LPG tüpü tavana kadar, ağzına kadar doldurulmalıdır',
      'LPG sistemi hiçbir kontrol veya muayene gerektirmez',
    ],
    answerIndex: 0,
    explanation:
      'LPG dönüşümlü araçlarda gaz tüpü genellikle bagajda ya da stepne yuvasında bulunur. Sıvı LPG sıcaklıkla genleştiği için tüp tam dolu değil, güvenli bir doluluk sınırına kadar doldurulur; böylece genleşmeye yer kalır. Ayrıca tüpün belirli aralıklarla test/muayenesi ve sistemin sızdırmazlık kontrolü gerekir.',
    whyWrong: [
      'Tüp motorun içine değil, ayrı bir bölmeye (çoğunlukla bagaja) yerleştirilir.',
      'Ağzına kadar doldurmak genleşme payı bırakmaz ve tehlikelidir; sistem düzenli kontrol gerektirir.',
    ],
    objective: 'LPG tüpünün konumu, doluluk sınırı ve muayene gerekliliğini bilmek.',
    tags: ['lpg', 'tup-doluluk', 'muayene'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-618',
    subject: 'motor',
    topic: 'hibrit-arac',
    difficulty: 'kolay',
    stem: 'Hibrit (benzin + elektrik) araçlarda "rejeneratif frenleme" ne anlama gelir?',
    options: [
      'Fren yaparken ve yavaşlarken normalde ısı olarak boşa giden hareket enerjisinin bir bölümünün elektrik motoru aracılığıyla elektriğe çevrilip aküyü şarj etmesi',
      'Frenlerin kendi kendini onarması',
      'Motorun frene basınca daha çok yakıt yakması',
      'El freninin otomatik olarak çekilmesi',
    ],
    answerIndex: 0,
    explanation:
      'Hibrit ve elektrikli araçlarda elektrik motoru, yavaşlama sırasında jeneratör gibi çalışabilir. Fren yaparken aracın hareket enerjisinin bir kısmı, ısı olarak kaybolmak yerine elektriğe dönüştürülüp aküye geri kazandırılır. Bu, hem yakıt tüketimini düşürür hem de fren balatalarının daha az yorulmasını sağlar.',
    whyWrong: [
      'Frenler kendini onarmaz; rejeneratif frenleme bir enerji geri kazanımıdır.',
      'Amaç daha çok yakıt yakmak değil, enerjiyi geri kazanmaktır; el freniyle de ilgisi yoktur.',
    ],
    objective: 'Hibritte rejeneratif frenlemenin enerji geri kazanımı mantığını kavramak.',
    tags: ['hibrit', 'rejeneratif-fren', 'sarj'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-619',
    subject: 'motor',
    topic: 'elektrikli-arac',
    difficulty: 'orta',
    stem: 'Elektrikli bir araçla ilgili aşağıdaki ifadelerden hangisi doğrudur?',
    options: [
      'Elektrikli araçlar yakıt deposu taşıdığı için istasyondan benzin alır',
      'Enerjisini şarj edilebilir yüksek voltajlı bir bataryadan alır; menzil planlaması ve şarj süresi önemlidir, yüksek voltaj nedeniyle şarj/onarım işlemlerinde güvenlik kurallarına uyulmalıdır',
      'Yüksek voltaj bulunmadığı için hiçbir güvenlik önlemi gerekmez',
      'Elektrikli araçlarda fren sistemi yoktur',
    ],
    answerIndex: 1,
    explanation:
      'Elektrikli araçlar, gücünü şarj edilebilir yüksek voltajlı bir bataryadan alan elektrik motoruyla hareket eder. Sürücünün kalan menzili ve şarj olanaklarını (süre, istasyon) önceden planlaması gerekir. Sistemde yüksek voltaj bulunduğu için şarj sırasında ve özellikle onarımlarda üreticinin güvenlik kurallarına uyulması zorunludur.',
    whyWrong: [
      'Elektrikli araçta benzin deposu ve yakıt yoktur; enerji bataryadan gelir.',
      'Yüksek voltaj ciddi bir tehlike kaynağıdır; güvenlik önlemleri gereklidir. Ayrıca bu araçlarda da fren sistemi vardır.',
    ],
    objective:
      'Elektrikli araçta enerji kaynağı, menzil ve yüksek voltaj güvenliğini temel düzeyde bilmek.',
    tags: ['elektrikli-arac', 'sarj', 'yuksek-voltaj'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-620',
    subject: 'motor',
    topic: 'radyator-kapagi',
    difficulty: 'zor',
    stem: 'Basınçlı soğutma sistemlerindeki radyatör/genleşme deposu kapağının kapalı bir basınç değeri altında çalışmasının teknik amacı nedir?',
    options: [
      'Yağ basıncını ölçmek',
      'Sistemi basınç altında tutarak soğutma suyunun kaynama noktasını yükseltmek; böylece motor yüksek sıcaklıklarda çalışsa bile su kolayca kaynayıp buharlaşmaz. Bu yüzden motor sıcakken kapak açılmamalıdır',
      'Yakıt tüketimini azaltmak',
      'Aküyü şarj etmek',
    ],
    answerIndex: 2,
    explanation:
      'Kapak, soğutma devresini belirli bir basınçta mühürler. Basınç arttıkça sıvının kaynama noktası yükselir; bu sayede su, atmosfer basıncındaki kaynama sıcaklığını aşan motor sıcaklıklarında bile sıvı hâlde kalır ve ısıyı taşımayı sürdürür. Sistem sıcakken kapak açılırsa basınç boşalır, kaynama noktası aniden düşer ve kaynayan su/buhar fışkırıp yakabilir.',
    whyWrong: [
      'Kapağın yağ basıncı ve yakıt tüketimiyle ilgisi yoktur.',
      'Aküyü şarj eden alternatördür; kapak elektrik üretmez.',
    ],
    objective: 'Radyatör kapağının basınç-kaynama noktası ilişkisindeki rolünü kavramak.',
    tags: ['radyator-kapagi', 'kaynama-noktasi', 'sogutma-sistemi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-621',
    subject: 'motor',
    topic: 'genlesme-deposu',
    difficulty: 'kolay',
    stem: 'Soğutma sistemindeki genleşme (yedek su) deposunun görevi aşağıdakilerden hangisidir?',
    options: [
      'Fren hidroliğini depolamak',
      'Yakıtı süzmek',
      'Motor yağını soğutmak',
      'Isınıp genleşen soğutma suyunun fazlasını geçici olarak barındırmak, soğuyunca geri vermek ve seviyenin gözle kolayca kontrol edilebildiği bir tampon hazne olmak',
    ],
    answerIndex: 3,
    explanation:
      'Soğutma suyu ısındıkça genleşir, soğudukça büzülür. Genleşme deposu bu hacim değişimini karşılar: genleşen suyun fazlasını alır, sistem soğuyunca suyu geri verir. Ayrıca üzerindeki en az-en çok çizgileri, soğutma suyu seviyesinin (motor soğukken) kolayca kontrol edilmesini sağlar.',
    whyWrong: [
      'Fren hidroliği ve yakıtın ayrı depo/hazneleri vardır.',
      'Motor yağını genleşme deposu değil, yağlama sistemi ve soğutma dolaylı olarak yönetir.',
    ],
    objective: 'Genleşme deposunun hacim tamponu ve seviye kontrol işlevini bilmek.',
    tags: ['genlesme-deposu', 'sogutma-suyu', 'seviye-kontrol'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-622',
    subject: 'motor',
    topic: 'radyator-hava-akisi',
    difficulty: 'orta',
    stem: 'Radyatörün ön yüzünün yaprak, böcek, çamur veya poşet gibi maddelerle örtülmesi neye yol açar?',
    options: [
      'Radyatörden geçen havanın azalması nedeniyle soğutmanın zayıflaması ve motorun daha kolay hararet yapması',
      'Farların daha parlak yanması',
      'Direksiyonun hafiflemesi',
      'Yakıt tüketiminin düşmesi',
    ],
    answerIndex: 0,
    explanation:
      'Radyatör, içinden geçen sıcak suyu üzerinden akan havayla soğutur. Ön yüzü tıkanırsa hava akışı azalır; su yeterince soğutulamaz ve motor özellikle yavaş/dur-kalk trafikte daha çabuk hararet yapar. Radyatör peteği bu yüzden temiz tutulmalı, önüne hava geçişini engelleyen maddeler yerleşmemelidir.',
    whyWrong: [
      'Far parlaklığı ve direksiyon hissi soğutma hava akışıyla ilgili değildir.',
      'Hararet riski artan bir motorda yakıt tüketimi düşmez, aksine olumsuz etkilenir.',
    ],
    objective: 'Radyatör hava akışının engellenmesiyle hararet arasındaki ilişkiyi kurmak.',
    tags: ['radyator', 'hava-akisi', 'hararet'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-623',
    subject: 'motor',
    topic: 'depo-kapagi',
    difficulty: 'zor',
    stem: 'Yakıt deposu kapağının gevşek bırakılması veya iyi kapatılmaması bazı araçlarda hangi belirtiye yol açabilir?',
    options: [
      'ABS lambasının yanmasına',
      'Yakıt buharı sisteminin (kaçak kontrolü) düzgün mühürlenememesi nedeniyle motor arıza (check engine) lambasının yanmasına; kapak düzgün kapatıldığında uyarı çoğu zaman kendiliğinden kaybolur',
      'Direksiyonun kilitlenmesine',
      'Kornanın çalmamasına',
    ],
    answerIndex: 1,
    explanation:
      'Modern araçlarda yakıt buharlarının çevreye kaçmasını önleyen bir sistem vardır ve bu sistemin mühürlenmesi için depo kapağının tam kapalı olması gerekir. Kapak gevşek kalırsa mühür bozulur; kendini denetleyen sistem bunu bir kaçak gibi algılar ve motor arıza lambasını yakabilir. Kapak doğru kapatılınca uyarı genellikle bir süre sonra söner.',
    whyWrong: [
      'ABS ve korna, yakıt buharı sistemiyle ilgili değildir; ayrı devrelerdir.',
      'Direksiyon kilidi kontak/anahtarla ilgilidir, depo kapağıyla değil.',
    ],
    objective: 'Gevşek depo kapağının motor arıza lambasını yakabileceğini bilmek.',
    tags: ['depo-kapagi', 'motor-ariza-lambasi', 'yakit-buhari'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-624',
    subject: 'motor',
    topic: 'atesleme-bobini',
    difficulty: 'orta',
    stem: 'Benzinli motorlarda ateşleme bobininin görevi aşağıdakilerden hangisidir?',
    options: [
      'Motor yağını basınçlandırmak',
      'Soğutma suyunu dolaştırmak',
      'Akünün düşük gerilimini, bujide kıvılcım atlatmaya yetecek çok yüksek gerilime yükseltmek',
      'Egzoz gazlarını temizlemek',
    ],
    answerIndex: 2,
    explanation:
      'Buji, hava-yakıt karışımını tutuşturmak için elektrotları arasında kıvılcım atlatır; bu da çok yüksek bir gerilim gerektirir. Ateşleme bobini, akünün nispeten düşük gerilimini bu yüksek gerilime yükselten elemandır. Bobin zayıflarsa kıvılcım yetersiz kalır; ilgili silindir teklemeye başlar.',
    whyWrong: [
      'Yağı basınçlandıran yağ pompası, suyu dolaştıran devirdaim pompasıdır.',
      'Egzoz gazlarını temizleme görevi katalitik konvertöre aittir; bobin ateşleme sistemine aittir.',
    ],
    objective: 'Ateşleme bobininin yüksek gerilim üretme görevini kavramak.',
    tags: ['atesleme-bobini', 'buji', 'yuksek-gerilim'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-625',
    subject: 'motor',
    topic: 'direksiyon-kullanimi',
    difficulty: 'orta',
    stem: 'Manevra sırasında direksiyonu sonuna kadar kırıp o konumda uzun süre zorlayarak beklemek neden sakıncalıdır?',
    options: [
      'Farların sönmesine yol açtığı için',
      'Yakıt deposunu boşalttığı için',
      'Lastik desenini değiştirdiği için',
      'Direksiyon sonuna dayandığında hidrolik direksiyon sistemi en yüksek basınçta zorlanır; bu konumda uzun süre beklemek pompayı, hortumları ve sızdırmazlıkları ısıtıp yıpratır',
    ],
    answerIndex: 3,
    explanation:
      'Direksiyon en son noktasına (dayanağına) geldiğinde hidrolik sistem içindeki basınç en yükseğe çıkar. Bu konumda gaz verip zorlayarak beklemek pompayı, hortumları ve keçeleri gereksiz yere ısıtıp yorar. Doğrusu, direksiyonu son noktadan bir miktar geri alarak beklemek ve sonuna kadar kırık tutmamaktır.',
    whyWrong: [
      'Far ve yakıt deposu direksiyon hidroliğiyle ilgili değildir.',
      'Lastik deseni bu davranıştan değil, aşınma ve yol koşullarından etkilenir.',
    ],
    objective: 'Direksiyonu sonuna kadar kırık tutmanın hidrolik sisteme zararını bilmek.',
    tags: ['hidrolik-direksiyon', 'kullanim-hatasi', 'asinma'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-626',
    subject: 'motor',
    topic: 'amortisor-testi',
    difficulty: 'orta',
    stem: 'Duran bir aracın bir köşesine bastırıp bıraktığınızda araç bir kez alçalıp yükseldikten sonra durmayıp birkaç kez zıplayarak salınmaya devam ediyorsa bu neyi gösterir?',
    options: [
      'O taraftaki amortisörün zayıfladığını; sağlam amortisör salınımı hızla sönümlerken, aşınmış amortisör aracı zıplatmaya devam eder',
      'Motor yağının fazla olduğunu',
      'Bujilerin kirlendiğini',
      'Radyatörün tıkandığını',
    ],
    answerIndex: 0,
    explanation:
      'Amortisörün görevi, yaydan gelen salınımı sönümleyerek tekerleğin yola sürekli basmasını sağlamaktır. Sağlam bir amortisörde araç bastırılıp bırakıldığında bir-iki harekette durulur. Salınım uzun sürerse amortisör görevini yapamıyor demektir; bu, hem sürüş konforunu hem yol tutuşunu ve fren mesafesini olumsuz etkiler.',
    whyWrong: [
      'Yağ fazlalığı ve kirli buji motor çalışmasıyla ilgilidir; süspansiyon salınımını açıklamaz.',
      'Radyatör tıkanması soğutma sorunudur; aracın zıplamasıyla ilgisi yoktur.',
    ],
    objective: 'Bastır-bırak testiyle zayıf amortisörü tanımayı öğrenmek.',
    tags: ['amortisor', 'salinim-testi', 'teshis'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-627',
    subject: 'motor',
    topic: 'yag-vizkozitesi',
    difficulty: 'zor',
    stem: 'Motor yağı kabında görülen "10W-40" gibi bir gösterim neyi ifade eder?',
    options: [
      'Yağın kaç litre olduğunu',
      'Yağın hangi renkte olduğunu',
      "Yağın akışkanlık (vizkozite) sınıfını; baştaki W'li sayı soğuktaki akışkanlığı, sondaki sayı yüksek sıcaklıktaki kıvamını belirtir. Araca daima üreticinin önerdiği vizkozite seçilmelidir",
      'Yağın kaç kilometrede bittiğini',
    ],
    answerIndex: 2,
    explanation:
      'Bu gösterim yağın vizkozite (akışkanlık) sınıfıdır. "W" (winter/kış) harfinden önceki sayı yağın soğukta ne kadar akıcı kaldığını, sonraki sayı ise yüksek çalışma sıcaklığında kıvamını korumasını ifade eder. Böylece yağ, soğuk ilk çalıştırmada da sıcak motorda da uygun film kalınlığını sağlar. Doğru seçim, üreticinin el kitabında belirttiği sınıftır.',
    whyWrong: [
      'Bu gösterim yağın miktarını (litre) veya rengini belirtmez.',
      'Değişim aralığını km/zaman olarak üretici ayrıca belirtir; vizkozite bunu ifade etmez.',
    ],
    objective: 'Yağ etiketindeki vizkozite gösterimini yorumlamak ve üretici önerisine uymak.',
    tags: ['motor-yagi', 'vizkozite', 'bakim'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-628',
    subject: 'motor',
    topic: 'oktan-sayisi',
    difficulty: 'orta',
    stem: 'Benzinde belirtilen oktan sayısı temel olarak neyi ifade eder?',
    options: [
      'Benzinin kaç litre olduğunu',
      'Benzinin, sıkıştırma sırasında kendiliğinden erken tutuşmaya (vuruntuya) karşı direncini; araca üreticinin önerdiği oktandaki yakıt konmalıdır',
      'Benzinin donma sıcaklığını',
      'Benzinin rengini',
    ],
    answerIndex: 1,
    explanation:
      'Oktan sayısı, benzinin sıkıştırma sırasında zamanından önce, kendiliğinden tutuşmaya (vuruntu/"knock") karşı ne kadar dayanıklı olduğunu gösterir. Yüksek oktanlı yakıt vuruntuya daha dirençlidir. Her motor belirli bir oktan için tasarlanır; bu yüzden araca, üreticinin el kitabında belirttiği oktan değerine uygun yakıt konması gerekir.',
    whyWrong: [
      'Oktan; miktar (litre), donma sıcaklığı ya da renk bilgisi değildir.',
      'Bunlar yakıtın ayrı özellikleridir; vuruntu direnciyle karıştırılmamalıdır.',
    ],
    objective: 'Oktan sayısının vuruntu direnci anlamını ve doğru yakıt seçimini bilmek.',
    tags: ['oktan', 'vuruntu', 'yakit-secimi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-629',
    subject: 'motor',
    topic: 'klima-bakimi',
    difficulty: 'kolay',
    stem: 'Klima açıldığında hava üflüyor ama eskisi gibi soğutmuyorsa olası nedenlerden biri ve doğru yaklaşım hangisidir?',
    options: [
      'Klima gazının zamanla azalmış olabileceği veya polen filtresinin/kondansatörün kirlenmiş olabileceği; sistemin serviste kontrol ettirilip gerekiyorsa gazının tamamlanması',
      'Motor yağının bittiği; hemen yağ eklenmesi',
      'Lastik basıncının düştüğü; lastiklerin şişirilmesi',
      'Akünün bittiği; akünün değiştirilmesi',
    ],
    answerIndex: 0,
    explanation:
      'Klimanın soğutması, kapalı devredeki soğutucu gaza bağlıdır. Zamanla azalan gaz, tıkanan polen filtresi ya da kirlenip hava alamayan kondansatör soğutmayı zayıflatır. Doğru yaklaşım sistemi serviste kontrol ettirmek; gaz eksikse tamamlatmak, filtreyi değiştirmek ve kondansatörü temizletmektir.',
    whyWrong: [
      'Motor yağı, lastik basıncı ve akü klimanın soğutma performansıyla doğrudan ilgili değildir.',
      'Bu parçaların değişimi soğutma zayıflığını gidermez.',
    ],
    objective: 'Klimanın soğutmama nedenlerini (gaz/filtre/kondansatör) tanımak.',
    tags: ['klima', 'sogutma', 'bakim'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-630',
    subject: 'motor',
    topic: 'silecek-lastigi',
    difficulty: 'kolay',
    stem: 'Silecek lastikleri eskidiğinde tipik olarak hangi belirti görülür ve bu neden önemlidir?',
    options: [
      'Cam üzerinde iz, çizgi ve silinmeyen bölgeler bırakır, ötme/takırdama sesi çıkarır; görüşü bozduğu için özellikle yağmurda tehlikelidir, bu yüzden zamanında değiştirilmelidir',
      'Motorun gücünü artırır',
      'Yakıt tüketimini düşürür',
      'Fren mesafesini kısaltır',
    ],
    answerIndex: 0,
    explanation:
      'Sertleşen, çatlayan veya kenarı bozulan silecek lastiği camı düzgün temizleyemez; su izleri, çizgiler ve silinmeyen alanlar bırakır, kimi zaman ötme sesi çıkarır. Yağmurlu havada görüşü doğrudan bozduğu için bu bir güvenlik sorunudur; lastikler belirli aralıklarla ve bozulunca hemen değiştirilmelidir.',
    whyWrong: [
      'Silecek lastiğinin motor gücü ve yakıt tüketimiyle ilgisi yoktur.',
      'Fren mesafesini frenler ve lastikler belirler; silecek lastiği değil.',
    ],
    objective: 'Eskiyen silecek lastiğinin görüş güvenliğine etkisini bilmek.',
    tags: ['silecek-lastigi', 'gorus', 'bakim'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-631',
    subject: 'motor',
    topic: 'lastik-ebadi',
    difficulty: 'orta',
    stem: 'Bir lastiğin yanağında yazan "205/55 R16" ifadesindeki değerler sırasıyla neyi gösterir?',
    options: [
      'Lastiğin fiyatını, rengini ve ağırlığını',
      'Lastik genişliğini (mm), kesit yükseklik oranını (%) ve uyduğu jant çapını (inç)',
      'Lastiğin üretim yılını, ayını ve gününü',
      'Lastik basıncını, diş derinliğini ve hızını',
    ],
    answerIndex: 1,
    explanation:
      'Bu gösterimde ilk sayı lastiğin milimetre cinsinden genişliğini, ikinci sayı yanak yüksekliğinin genişliğe oranını (yüzde), "R"den sonraki sayı ise lastiğin uyduğu jant çapını inç olarak belirtir. Yedek/yeni lastik alırken araca uygun ebadın seçilmesi için bu değerler önemlidir.',
    whyWrong: [
      'Fiyat, renk, ağırlık gibi bilgiler lastik ebadı gösteriminde yer almaz.',
      'Üretim tarihi (DOT) ve basınç/diş derinliği ayrı bilgilerdir; bu gösterimle ifade edilmez.',
    ],
    objective: 'Lastik ebadı gösterimindeki genişlik/oran/jant değerlerini okumak.',
    tags: ['lastik-ebadi', 'jant', 'olcu'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-632',
    subject: 'motor',
    topic: 'lastik-yasi',
    difficulty: 'orta',
    stem: 'Diş derinliği yeterli görünen bir lastiğin yaşça eskimiş olması neden önemlidir?',
    options: [
      'Eski lastik daha hızlı gider',
      'Lastik yaşlandıkça kauçuğu sertleşip çatlar; yeterli dişe rağmen yol tutuşu azalır ve ani hava kaybı riski artar. Bu yüzden az kullanılsa bile lastiğin üretim tarihi/yaşı göz önünde bulundurulmalıdır',
      'Eski lastik yakıt tüketimini düşürür',
      'Lastiğin yaşı yalnızca rengini etkiler',
    ],
    answerIndex: 2,
    explanation:
      'Lastik kauçuğu zamanla, az kullanılsa bile eskir: esnekliğini yitirir, sertleşir ve yüzeyinde kılcal çatlaklar oluşur. Diş derinliği yeterli olsa dahi böyle bir lastik, özellikle ıslak/soğuk yolda yeterince tutunamaz ve ani hava kaybına daha yatkın hâle gelir. Bu nedenle lastiğin yalnızca dişine değil, üretim tarihine/yaşına da bakılır.',
    whyWrong: [
      'Yaşlı lastik daha hızlı gitmez; performansı ve güvenliği düşer.',
      'Yakıt tüketimini düşürmez; yaşlanma yalnızca rengi değil, kauçuğun yapısını etkiler.',
    ],
    objective: 'Lastik yaşlanmasının, diş derinliğinden bağımsız güvenlik riskini kavramak.',
    tags: ['lastik-yasi', 'kauçuk-sertlesmesi', 'guvenlik'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-633',
    subject: 'motor',
    topic: 'stepne-kontrol',
    difficulty: 'kolay',
    stem: 'Araçta bulundurulan yedek lastik (stepne) ile ilgili sık ihmal edilen doğru uygulama hangisidir?',
    options: [
      'Stepnenin hiç kontrol edilmesine gerek yoktur',
      'Stepne bir kez şişirilince yıllarca hiç bakılmadan aynı basınçta kalır',
      'Stepnenin hava basıncı da düzenli aralıklarla kontrol edilmelidir; çünkü zamanla kendiliğinden basınç kaybeden bir stepne, tam ihtiyaç anında sönük çıkabilir',
      'Stepne yalnızca kışın kontrol edilir',
    ],
    answerIndex: 2,
    explanation:
      'Yedek lastik uzun süre kullanılmadan beklese de zamanla yavaşça hava kaybeder. Basıncı düzenli kontrol edilmezse, bir lastik patladığında takılan stepnenin de sönük olduğu ancak o an fark edilir. Bu yüzden diğer lastiklerle birlikte stepnenin basıncı ve durumu da periyodik olarak kontrol edilmelidir.',
    whyWrong: [
      'Stepne kontrolsüz bırakılmamalıdır; zamanla basınç kaybeder.',
      'Bir kez şişirmek yıllarca yetmez; kontrol yalnızca kışa özgü de değildir.',
    ],
    objective: 'Yedek lastiğin de düzenli basınç kontrolü gerektirdiğini bilmek.',
    tags: ['stepne', 'basinc-kontrol', 'bakim'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-634',
    subject: 'motor',
    topic: 'bas-destegi',
    difficulty: 'orta',
    stem: 'Koltuk baş desteğinin (kafalık) doğru ayarlanmasının güvenlik açısından önemi nedir?',
    options: [
      'Yalnızca yolculuğu daha konforlu yapmak için vardır, güvenlikle ilgisi yoktur',
      'Baş desteğinin üst kenarı yaklaşık baş hizasında olduğunda, özellikle arkadan çarpmalarda başın geriye savrulmasını sınırlayarak boyun (kamçı/whiplash) yaralanması riskini azaltır',
      'Baş desteği yükseğe alındığında yakıt tüketimini düşürür',
      'Baş desteği ne kadar aşağıda olursa o kadar iyi korur',
    ],
    answerIndex: 1,
    explanation:
      'Baş desteği bir konfor parçası gibi görünse de temel görevi güvenliktir. Özellikle arkadan çarpmada gövde öne itilirken baş geride kalıp ani şekilde geriye savrulur; bu, boyunda "kamçı" tipi yaralanmaya yol açar. Baş desteğinin üst kenarı baş hizasına ayarlandığında başın bu savrulması sınırlanır ve boyun daha iyi korunur.',
    whyWrong: [
      'Baş desteği yalnızca konfor için değil, boyun koruması içindir.',
      'Yakıt tüketimiyle ilgisi yoktur ve çok alçak ayar başı desteklemediği için korumayı azaltır.',
    ],
    objective: 'Baş desteğinin doğru ayarıyla boyun yaralanması riskini azaltmayı bilmek.',
    tags: ['bas-destegi', 'boyun-yaralanmasi', 'pasif-guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-635',
    subject: 'motor',
    topic: 'kemer-gerdirici',
    difficulty: 'orta',
    stem: 'Modern araçlardaki emniyet kemeri gerdiricisinin (ön gerdirici) işlevi nedir?',
    options: [
      'Kemeri sürüş boyunca gevşek tutmak',
      'Şiddetli bir çarpışma anında kemerdeki boşluğu anında toplayarak gövdeyi koltuğa daha sıkı ve erken kavramak; böylece vücudun ileri savrulmasını azaltıp hava yastığıyla uyumlu koruma sağlamak',
      'Kemeri kaza anında tamamen serbest bırakmak',
      'Kemeri yalnızca park hâlinde germek',
    ],
    answerIndex: 1,
    explanation:
      'Kemer gerdiricisi, çarpışma sensörleri şiddetli darbeyi algıladığında devreye girer ve kemerdeki gevşekliği bir anda toplar. Böylece gövde daha erken ve sıkı biçimde koltuğa oturur; ileri savrulma azalır ve hava yastığı vücudu doğru konumda karşılar. Kemer ile hava yastığı birbirini tamamlayan bir bütün olarak çalışır.',
    whyWrong: [
      'Gerdiricinin amacı kemeri gevşetmek değil, kaza anında germektir.',
      'Kemeri kaza anında serbest bırakmak korumayı ortadan kaldırırdı; sistem park hâlinde değil çarpışmada çalışır.',
    ],
    objective: 'Kemer ön gerdiricisinin çarpışmada boşluğu toplama işlevini kavramak.',
    tags: ['emniyet-kemeri', 'on-gerdirici', 'pasif-guvenlik'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-636',
    subject: 'motor',
    topic: 'hiz-sabitleyici',
    difficulty: 'kolay',
    stem: 'Hız sabitleyici (cruise control) sistemi ile ilgili doğru ifade hangisidir?',
    options: [
      'Aracın direksiyonunu da otomatik çevirir',
      'Sürücünün ayarladığı sabit hızı gaz pedalına basmadan korur; ancak kaygan zeminde, yoğun trafikte ve keskin virajlı yollarda kullanımı uygun değildir',
      'Frene basma ihtiyacını tamamen ortadan kaldırır',
      'Yalnızca şehir içi dur-kalk trafik için tasarlanmıştır',
    ],
    answerIndex: 1,
    explanation:
      'Hız sabitleyici, sürücünün belirlediği hızı gaz pedalına sürekli basmadan koruyarak özellikle uzun ve düz yollarda yorgunluğu azaltır. Ancak aracın yönetimi yine sürücüdedir. Islak/karlı-buzlu zeminde, yoğun trafikte ve keskin virajlı yollarda kullanılması güvenli değildir; bu koşullarda sürücünün hıza doğrudan hâkim olması gerekir.',
    whyWrong: [
      'Klasik hız sabitleyici direksiyonu çevirmez; yön kontrolü sürücüdedir.',
      'Fren ihtiyacını ortadan kaldırmaz; ayrıca dur-kalk trafik için değil, düzenli akışlı yollar için uygundur.',
    ],
    objective: 'Hız sabitleyicinin işlevini ve uygun olmayan kullanım koşullarını bilmek.',
    tags: ['hiz-sabitleyici', 'cruise-control', 'suru-yardimcisi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-637',
    subject: 'motor',
    topic: 'park-sensoru',
    difficulty: 'kolay',
    stem: 'Park sensörü ve geri görüş kamerası bulunan bir araçla ilgili doğru yaklaşım nedir?',
    options: [
      'Bu donanımlar varsa aynalara ve dönüp bakmaya artık hiç gerek kalmaz',
      'Kamera görüntüsü her koşulda gerçek mesafeyi birebir verir, tam güvenilir',
      'Sensör sesi olmadıkça kesinlikle engel yoktur',
      'Bu sistemler sürücüye yardımcıdır; ancak kör noktaları ve alçak/ince engelleri kaçırabildikleri için aynalarla ve gerektiğinde dönüp bakarak kontrol etmenin yerini tutmazlar',
    ],
    answerIndex: 3,
    explanation:
      'Park sensörü ve geri görüş kamerası manevrayı kolaylaştıran yardımcı donanımlardır. Ancak sensörler çok alçak, ince veya belirli açılardaki engelleri algılamayabilir; kamera görüşü de kirlenme, açı ve mesafe algısı nedeniyle yanıltabilir. Bu yüzden sorumluluk sürücüdedir: aynalar kullanılmalı ve gerektiğinde dönüp bakılmalıdır.',
    whyWrong: [
      'Bu donanımlar ayna ve dönüp bakmanın yerini almaz; yardımcıdır.',
      'Kamera her koşulda birebir mesafe vermez ve sensörün susması her zaman "engel yok" anlamına gelmez.',
    ],
    objective: 'Park yardımcılarının sınırlarını bilip aynalarla kontrolü sürdürmek.',
    tags: ['park-sensoru', 'geri-goru-kamerasi', 'suru-yardimcisi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-638',
    subject: 'motor',
    topic: 'kor-nokta-uyari',
    difficulty: 'orta',
    stem: 'Kör nokta uyarı sistemi sürücüye nasıl bir yardım sağlar?',
    options: [
      'Aynalarda görünmeyen kör noktada yandan gelen/seyreden bir araç bulunduğunda sürücüyü (genellikle ayna kenarındaki ışık ve/veya sesle) uyarır; yine de şerit değiştirmeden önce dönüp bakmak gerekir',
      'Aracı otomatik olarak durdurur',
      'Direksiyonu kilitleyerek şerit değiştirmeyi tamamen engeller',
      'Yalnızca gece çalışır ve farları yönetir',
    ],
    answerIndex: 0,
    explanation:
      'Kör nokta uyarı sistemi, aynalardan görülemeyen yan-arka bölgeyi sensörlerle izler. Bu alanda bir araç varken sürücüyü genellikle ayna kenarındaki bir ikaz ışığı ve/veya sesle uyarır. Bu, şerit değiştirmede güvenliği artırır; ancak sistem her durumu yakalamayabileceği için şerit değiştirmeden önce dönüp bakma alışkanlığı korunmalıdır.',
    whyWrong: [
      'Sistem aracı durdurmaz veya direksiyonu kilitlemez; yalnızca uyarır.',
      'Gündüz de çalışır ve farları yönetme işlevi yoktur.',
    ],
    objective: 'Kör nokta uyarısının işlevini ve dönüp bakmanın gerekliliğini bilmek.',
    tags: ['kor-nokta', 'suru-yardimcisi', 'serit-degistirme'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-639',
    subject: 'motor',
    topic: 'dpf',
    difficulty: 'zor',
    stem: 'Dizel araçlardaki partikül filtresi (DPF) ile ilgili doğru ifade aşağıdakilerden hangisidir?',
    options: [
      'Motor yağını süzen bir filtredir',
      'Egzozdaki kurum (is) parçacıklarını tutarak çevreye salınan zararlı partikülleri azaltır; sürekli çok kısa/düşük hızlı yollarda motor yeterince ısınmadığından filtre zamanla dolabilir ve uyarı verebilir',
      'Yakıt deposunun içindedir ve yakıtı soğutur',
      'Yalnızca benzinli araçlarda bulunur',
    ],
    answerIndex: 1,
    explanation:
      'Dizel partikül filtresi, egzozdaki kurum parçacıklarını tutup çevreye salınan partikül miktarını azaltan bir emisyon donanımıdır. Tuttuğu kurumun yakılıp temizlenmesi (rejenerasyon) için egzozun yeterince ısınması gerekir; sürekli çok kısa ve düşük hızlı sürüşlerde bu ısınma gerçekleşemeyeceği için filtre zamanla dolar ve uyarı verebilir. Bu durumda üreticinin önerdiği koşullarda sürüş ya da servis müdahalesi gerekir.',
    whyWrong: [
      'DPF motor yağını değil, egzoz kurumunu süzer; depoyla ve yakıt soğutmayla ilgisi yoktur.',
      'Bu donanım dizel araçların emisyon sistemine aittir, yalnızca benzinlilere özgü değildir.',
    ],
    objective: "DPF'nin egzoz kurumunu tutma işlevini ve kısa yol/rejenerasyon ilişkisini bilmek.",
    tags: ['dpf', 'partikul-filtresi', 'dizel-emisyon'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-640',
    subject: 'motor',
    topic: 'debriyaj-rulmani',
    difficulty: 'orta',
    stem: 'Bir araçta yalnızca debriyaj pedalına basıldığı anda ortaya çıkan, pedal bırakılınca kesilen bir sürtme/vınlama sesi duyuluyorsa öncelikle hangi parça akla gelmelidir?',
    options: [
      'Radyatör fanı',
      'Yakıt pompası',
      'Debriyaj baskı rulmanı (bilyası); yalnızca pedala basıldığında yük altına girdiği için aşındığında sesi bu anlarda duyulur',
      'Ön cam sileceği',
    ],
    answerIndex: 2,
    explanation:
      'Baskı rulmanı, debriyaj pedalına basıldığında baskı balatasına dayanarak kavramanın ayrılmasını sağlar. Yalnızca pedal basılıyken yük altında çalıştığından, aşındığında sesi tam bu anlarda (pedala basınca) çıkar, pedal bırakılınca kesilir. Bu tipik belirti baskı rulmanının değişmesi gerektiğini gösterir.',
    whyWrong: [
      'Radyatör fanı ve yakıt pompası sesi debriyaj pedalına bağlı olarak gelip gitmez.',
      'Silecek ayrı bir devrede çalışır; debriyaj pedalıyla ilgisi yoktur.',
    ],
    objective: 'Pedala basınca çıkıp bırakınca kesilen sesi baskı rulmanıyla ilişkilendirmek.',
    tags: ['debriyaj-rulmani', 'baski-bilyasi', 'teshis'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-641',
    subject: 'motor',
    topic: 'motor-bolmesi-guvenlik',
    difficulty: 'kolay',
    stem: 'Yeni durmuş, sıcak bir motorun kaputunu açıp kontrol yaparken hangi güvenlik önlemine dikkat edilmelidir?',
    options: [
      'Sıcak parçalara çıplak elle dokunmak sakıncasızdır',
      'Radyatör kapağı sıcakken rahatça açılabilir',
      'Motor durmuş olsa bile fan aniden dönebilir ve parçalar çok sıcak olabilir; bu yüzden dönen kısımlardan, sıcak yüzeylerden ve basınçlı sıcak sudan uzak durulmalı, gerekiyorsa motorun soğuması beklenmelidir',
      'Elektrik bağlantılarına ıslak elle dokunmak güvenlidir',
    ],
    answerIndex: 2,
    explanation:
      'Motor durduktan sonra bile soğutma fanı sıcaklık düşene kadar kendiliğinden çalışabilir ve parmakları yaralayabilir; egzoz, motor bloğu gibi yüzeyler yakacak kadar sıcaktır. Basınç altındaki soğutma suyu da sıcakken tehlikelidir. Bu nedenle sıcak motorda kontrol yaparken dönen ve sıcak kısımlardan uzak durulmalı, gerektiğinde motorun soğuması beklenmelidir.',
    whyWrong: [
      'Sıcak parçalara elle dokunmak yanığa yol açar; güvenli değildir.',
      'Radyatör kapağı sıcakken açılırsa kaynar su/buhar fışkırabilir; ıslak elle elektrik bağlantısına dokunmak da risklidir.',
    ],
    objective: 'Sıcak motor bölmesinde fan, sıcak yüzey ve basınç risklerine dikkat etmek.',
    tags: ['motor-bolmesi', 'fan', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-642',
    subject: 'motor',
    topic: 'kafa-contasi',
    difficulty: 'zor',
    stem: 'Yağ dolum kapağının altında ya da yağ çubuğunda açık kahverengi/sütlü, köpüklü bir bulaşık görülüyor ve soğutma suyu açıklanamayan şekilde eksiliyorsa akla gelmesi gereken ciddi ihtimal nedir?',
    options: [
      'Silindir kapağı contasının (kafa contası) yanmış/kaçırıyor olabileceği; soğutma suyu ile yağın karışması bu köpüklü görüntüyü oluşturur ve bu, vakit kaybetmeden kontrol gerektiren ağır bir sorundur',
      'Silecek suyunun bittiği',
      'Polen filtresinin kirlendiği',
      'Lastik dişlerinin aşındığı',
    ],
    answerIndex: 0,
    explanation:
      'Silindir kapağı contası yağ ve soğutma suyu kanallarını birbirinden ayırır. Conta kaçırdığında su ile yağ karışır; yağ kapağının altında ya da çubukta açık kahverengi/sütlü, köpüklü bir bulaşık (mayonez görünümü) oluşur ve soğutma suyu açıklanamayan biçimde eksilir. Bu ağır bir arızadır; motor zarar görmeden servise götürülmelidir.',
    whyWrong: [
      'Silecek suyu ve polen filtresi yağ-su karışımıyla ilgili değildir.',
      'Lastik aşınması bu belirtilerle ilgisizdir; sorun motorun iç sızdırmazlığındadır.',
    ],
    objective:
      'Yağda sütlü köpük + su eksilmesi belirtisini kafa contası arızasıyla ilişkilendirmek.',
    tags: ['kafa-contasi', 'yag-su-karisimi', 'teshis'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-643',
    subject: 'motor',
    topic: 'antifriz-kacagi',
    difficulty: 'orta',
    stem: 'Aracın park edildiği yerin altında yeşilimsi/pembemsi, hafif tatlı kokan bir sıvı lekesi görülüyor ve soğutma suyu azalıyorsa en olası neden nedir?',
    options: [
      'Fren hidroliğinin kaçırması',
      'Soğutma sisteminde (antifrizli su) bir kaçak bulunması; renkli ve tatlımsı kokulu bu sıvı genellikle antifrizdir ve kaçak bulunup giderilmelidir',
      'Motor yağının kaçırması',
      'Ön cam suyunun taşması',
    ],
    answerIndex: 1,
    explanation:
      'Antifriz katkılı soğutma suyu genellikle yeşil, pembe ya da mavi renkli ve hafif tatlımsı kokulu olur. Araç altında bu renkte bir sıvı görülmesi ve soğutma suyunun azalması, soğutma devresinde (hortum, radyatör, su pompası vb.) bir kaçağı düşündürür. Motor hararet yapmadan kaçağın kaynağı bulunup onarılmalıdır; ayrıca antifriz zehirlidir, hayvanlar/çocuklar için tehlike oluşturur.',
    whyWrong: [
      'Fren hidroliği ve motor yağı bu renk ve tatlı kokuda değildir; farklı görünürler.',
      'Cam suyunun taşması soğutma suyunun eksilmesini açıklamaz.',
    ],
    objective:
      'Araç altındaki renkli-tatlı sıvı + su eksilmesini antifriz kaçağıyla ilişkilendirmek.',
    tags: ['antifriz', 'sogutma-kacagi', 'teshis'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-644',
    subject: 'motor',
    topic: 'otomatik-vites-kullanimi',
    difficulty: 'kolay',
    stem: 'Otomatik şanzımanlı bir araçta pedalların kullanımıyla ilgili doğru ifade hangisidir?',
    options: [
      'Sağ ayakla gaz, sol ayakla fren yapmak en doğru yöntemdir',
      'Debriyaj pedalı olmadığından hem gaz hem fren tek ayakla (sağ ayakla) kullanılır; sol ayağı fren pedalına yerleştirme alışkanlığı, ani durumda iki pedala birden basma hatasına yol açabilir',
      'Otomatik viteste fren pedalına hiç gerek yoktur',
      'Otomatik araçta sol ayak sürekli fren pedalında tutulmalıdır',
    ],
    answerIndex: 1,
    explanation:
      'Otomatik şanzımanlı araçta debriyaj pedalı yoktur; bu yüzden gaz ve fren tek ayakla, sağ ayakla kullanılır. Sol ayağı sürekli fren pedalında tutmak, refleksle iki pedala birden basma ya da yanlış pedala basma riskini artırır. Sol ayak, kullanılmadığı zamanlarda uygun dinlenme alanında tutulur.',
    whyWrong: [
      'İki ayrı ayakla gaz-fren kullanmak otomatikte önerilen yöntem değildir; hata riskini artırır.',
      'Fren pedalı elbette gereklidir; ayrıca sol ayak sürekli fren pedalında tutulmaz.',
    ],
    objective: 'Otomatik viteste tek ayakla pedal kullanımının doğru olduğunu bilmek.',
    tags: ['otomatik-vites', 'pedal-kullanimi', 'kullanim-hatasi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-645',
    subject: 'motor',
    topic: 'otomatik-park-konumu',
    difficulty: 'orta',
    stem: 'Otomatik şanzımanlı bir araçta "P" (park) konumu ve el freniyle ilgili doğru uygulama hangisidir?',
    options: [
      'Park hâlinde vites herhangi bir konumda kalabilir',
      'Motor yalnızca "D" konumunda çalıştırılır',
      'Park ederken vites "P" konumuna alınır ve ek güvenlik için el freni de çekilir; motor genellikle "P" (ya da "N") konumunda çalıştırılır',
      'El freni otomatik araçlarda hiç kullanılmaz',
    ],
    answerIndex: 2,
    explanation:
      'Otomatik araçta park edilirken vites "P" konumuna alınır; bu konum şanzıman içinde bir kilit devreye sokarak aracı tutar. Yine de tek başına yeterli sayılmaz, özellikle eğimde ek güvenlik için el freni de çekilir. Motor genellikle "P" (veya "N") konumunda, fren basılıyken çalıştırılır. El freni otomatik araçta da gerekli bir güvenlik donanımıdır.',
    whyWrong: [
      'Vitesin park hâlinde herhangi bir konumda kalması güvenli değildir; "P" seçilmelidir.',
      'Motor "D" konumunda çalıştırılmaz; el freni de otomatik araçta kullanılan bir donanımdır.',
    ],
    objective: 'Otomatik araçta P konumu + el freni ve çalıştırma konumunu bilmek.',
    tags: ['otomatik-vites', 'park-konumu', 'el-freni'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-646',
    subject: 'motor',
    topic: 'rolanti-devri',
    difficulty: 'kolay',
    stem: 'Motor çalışırken devir saatinin (takometre) rölantide belirli bir düşük değerde durması ve klima devreye girince devrin bir miktar yükselmesi hakkında doğru değerlendirme nedir?',
    options: [
      'Rölanti devrinin belirli bir aralıkta olması normaldir; klima gibi ek yükler devreye girince motorun rölantiyi koruyabilmek için devri biraz yükseltmesi de olağandır',
      'Rölantide devrin yükselmesi her zaman ciddi arıza demektir',
      'Rölanti devrinin sıfır olması gerekir',
      'Klima açıldığında devrin değişmesi motorun bozulduğunu gösterir',
    ],
    answerIndex: 0,
    explanation:
      'Motor, boştayken (rölanti) belirli bir düşük devirde dengeli çalışacak şekilde ayarlanır. Klima kompresörü gibi bir yük devreye girip motora ek direnç bindirdiğinde, motor stop etmemek için devrini bir miktar yükseltir. Bu, arıza değil, motor yönetiminin rölantiyi koruma davranışıdır. Devrin sürekli dalgalanması ya da anormal düşüp yükselmesi ise ayrı bir konudur.',
    whyWrong: [
      'Klimayla devrin bir miktar yükselmesi normaldir; her zaman arıza demek değildir.',
      'Motor çalışırken rölanti devri sıfır olmaz; ayrıca klima açılınca hafif değişim bozulma göstergesi değildir.',
    ],
    objective: 'Normal rölanti devrini ve ek yükte hafif devir artışını olağan karşılamak.',
    tags: ['rolanti', 'takometre', 'klima-yuku'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-647',
    subject: 'motor',
    topic: 'yag-filtresi-degisimi',
    difficulty: 'kolay',
    stem: 'Motor yağı değişiminde yağ filtresinin de birlikte değiştirilmesi neden önerilir?',
    options: [
      'Yağ filtresi hiçbir zaman değiştirilmez',
      'Eski filtre içindeki kirli yağ ve tuttuğu tortular, yeni konan temiz yağı hemen kirletir; ayrıca dolmuş filtre yağın geçişini zorlaştırır. Bu yüzden yağla birlikte filtre de yenilenir',
      'Filtre yalnızca dizel araçlarda değiştirilir',
      'Filtre değişimi yakıt tüketimini artırır',
    ],
    answerIndex: 1,
    explanation:
      'Yağ filtresi, yağ içindeki metal parçacıkları ve tortuları tutar; zamanla dolar ve içinde kirli yağ kalır. Yağ değiştirilirken eski filtre bırakılırsa, hem içindeki kirli yağ yeniyle karışır hem de dolmuş filtre yağ akışını zorlaştırır. Bu nedenle yağ değişiminde filtre de birlikte yenilenir; böylece temiz yağın verimi korunur.',
    whyWrong: [
      'Filtre kalıcı değildir; belirli aralıklarla değişmesi gerekir ve yalnızca dizele özgü değildir.',
      'Yeni filtre yakıt tüketimini artırmaz; aksine motorun düzgün çalışmasına katkıda bulunur.',
    ],
    objective: 'Yağ değişiminde filtrenin de yenilenmesinin gerekçesini kavramak.',
    tags: ['yag-filtresi', 'yag-degisimi', 'bakim'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-648',
    subject: 'motor',
    topic: 'hava-filtresi-bakimi',
    difficulty: 'orta',
    stem: 'Kâğıt tipi hava filtresi çok kirlendiğinde en doğru uygulama hangisidir?',
    options: [
      'Benzinle yıkayıp güneşte kurutmak',
      'Suyla yıkayıp tekrar takmak',
      'Süresi/kilometresi geldiğinde ya da aşırı kirlendiğinde yenisiyle değiştirmek; kâğıt filtre sınırlı hafif temizlik dışında yıkanarak kalıcı biçimde temizlenemez',
      'Hiç değiştirmemek, ömür boyu aynı filtreyi kullanmak',
    ],
    answerIndex: 2,
    explanation:
      'Kâğıt hava filtresi, motora giren havadaki toz ve parçacıkları tutan gözenekli bir elemandır. Zamanla gözenekleri dolar ve hava akışını kısıtlar; bu da yanmayı bozup güç kaybına ve tüketim artışına yol açar. Kâğıt filtre benzin/suyla yıkanarak kalıcı temizlenemez, yapısı bozulur; bu yüzden süresi geldiğinde ya da aşırı kirlendiğinde yenisiyle değiştirilir.',
    whyWrong: [
      'Benzinle veya suyla yıkamak kâğıt filtrenin yapısını bozar; doğru yöntem değildir.',
      'Filtre ömür boyu kullanılamaz; belirli aralıklarla değiştirilmesi gerekir.',
    ],
    objective: 'Kâğıt hava filtresinin yıkanamayacağını, süresinde değişmesi gerektiğini bilmek.',
    tags: ['hava-filtresi', 'bakim', 'degisim'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-649',
    subject: 'motor',
    topic: 'motor-ariza-lambasi',
    difficulty: 'orta',
    stem: 'Motor arıza (check engine) lambası sabit (yanıp sönmeden) yanıyor ve araç normale yakın çalışıyorsa doğru davranış nedir?',
    options: [
      'Lambayı bant çekerek kapatmak',
      'Lamba sabit yanıyorsa hiçbir şey yapmaya gerek yoktur',
      'Aracı hemen terk edip çektirmek gerekir',
      'Motor yönetiminde kayıtlı bir arıza olduğunu kabul edip, ağır hızlanma/yüksek devirden kaçınarak yakın zamanda arıza kodunu okutup kontrol ettirmek; belirti ağırlaşır ya da lamba yanıp sönmeye başlarsa daha acil davranmak',
    ],
    answerIndex: 3,
    explanation:
      'Sabit yanan motor arıza lambası, motor yönetim sisteminin bir arıza (emisyon, sensör, yakıt/ateşleme vb.) kaydettiğini gösterir. Araç normale yakın gidiyorsa genellikle bir süre dikkatli sürülebilir; ancak ağır hızlanma ve yüksek devirden kaçınıp yakın zamanda arıza kodları okutulmalıdır. Lamba yanıp sönmeye dönerse (ör. ciddi tekleme) durum acildir ve daha temkinli davranmak gerekir.',
    whyWrong: [
      'Lambayı örtmek arızayı gizler, çözmez ve daha büyük hasara yol açabilir.',
      'Sabit yanan lamba önemsiz değildir; ancak araç normal gidiyorken hemen çektirmeyi de gerektirmez, kontrol ettirmek yeterlidir.',
    ],
    objective: 'Sabit yanan motor arıza lambasında ölçülü, kontrol odaklı davranışı bilmek.',
    tags: ['motor-ariza-lambasi', 'check-engine', 'teshis'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-650',
    subject: 'motor',
    topic: 'ikaz-onceligi',
    difficulty: 'zor',
    stem: 'Aşağıdaki gösterge ikazlarından hangisi, yandığında en kısa sürede güvenli bir yerde durup motoru durdurmayı gerektiren, "beklemeye gelmeyen" nitelikte bir uyarıdır?',
    options: [
      'Kırmızı yağ basıncı (yağdanlık) ikazı; yağlama basıncı düştüğünde motor kısa sürede ağır hasar görebileceğinden derhâl durulup motor durdurulmalıdır',
      'Yakıtın azaldığını bildiren rezerv göstergesi',
      'Cam suyunun azaldığını bildiren uyarı',
      'Kapının tam kapanmadığını bildiren uyarı',
    ],
    answerIndex: 0,
    explanation:
      'İkaz lambalarının aciliyeti aynı değildir. Kırmızı yağ basıncı ikazı, yağlama basıncının tehlikeli biçimde düştüğünü bildirir; yağsız kalan yataklar dakikalar içinde sarabileceği için bu uyarıda derhâl güvenli bir yerde durup motor durdurulmalıdır. Yakıt rezervi, cam suyu ya da kapı uyarıları önemli olsa da motoru anında durdurmayı gerektiren aciliyette değildir.',
    whyWrong: [
      'Yakıt rezervi yakında yakıt almayı gerektirir ama anında motor durdurmayı değil.',
      'Cam suyu ve kapı uyarıları motorun ömrünü tehdit eden acil durumlar değildir.',
    ],
    objective: 'Kırmızı yağ basıncı ikazının diğer uyarılara göre önceliğini kavramak.',
    tags: ['ikaz-onceligi', 'yag-basinci', 'acil-mudahale'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-651',
    subject: 'motor',
    topic: 'rolanti-stop',
    difficulty: 'zor',
    stem: 'Bir araç sürüşte iyi çalışıyor ama durur/rölantiye düşer düşmez motor sık sık kendiliğinden stop ediyorsa (özellikle klima açıkken) olası nedenlerden biri hangisidir?',
    options: [
      'Lastik dişlerinin aşınması',
      'Far ayarının bozulması',
      'Rölanti hava/yakıt dengesini etkileyen bir sorun (kirli gaz kelebeği, rölanti hava kaçağı ya da yakıt/ateşleme dengesizliği); ek yük binince zayıf rölantinin motoru boğması',
      'Plaka lambasının yanmaması',
    ],
    answerIndex: 2,
    explanation:
      'Rölanti, motorun boştayken düşük devirde dengede kaldığı hassas bir durumdur. Kirlenmiş gaz kelebeği, emme hattındaki hava kaçağı ya da yakıt/ateşleme dengesizliği rölanti devrini zayıflatır. Klima gibi bir yük devreye girip motora ek direnç bindirdiğinde, zaten zayıf olan rölanti bunu karşılayamaz ve motor stop eder. Sorun sürüşte belirgin olmayabilir çünkü o an motor yük altında daha kararlı çalışır.',
    whyWrong: [
      'Lastik, far ve plaka lambası motorun rölantide çalışmasıyla ilgili değildir.',
      'Bu donanımların motorun stop etmesine yol açması beklenmez.',
    ],
    objective:
      'Rölantide stop etme belirtisini hava/yakıt/rölanti dengesizliğiyle ilişkilendirmek.',
    tags: ['rolanti', 'stop-etme', 'teshis'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-652',
    subject: 'motor',
    topic: 'sivi-lekesi-teshis',
    difficulty: 'orta',
    stem: 'Aracın park edildiği zeminde sızıntı lekeleri görüldüğünde, sıvının rengi olası kaynak hakkında ipucu verir. Aşağıdaki eşleştirmelerden hangisi doğrudur?',
    options: [
      'Berrak su lekesi her zaman ciddi bir motor yağı kaçağıdır',
      'Koyu siyah/kahverengi yağlı leke motor yağını, yeşil/pembe renkli leke antifrizli soğutma suyunu düşündürür; klima çalışırken damlayan berrak su ise çoğunlukla yoğuşma suyudur ve normaldir',
      'Yeşil renkli leke fren hidroliğidir',
      'Sıvının rengi kaynağı hakkında hiçbir bilgi vermez',
    ],
    answerIndex: 1,
    explanation:
      'Sızan sıvının rengi olası kaynağı daraltmaya yardımcı olur: koyu siyah/kahverengi yağlı bir leke genellikle motor yağını, yeşil/pembe/mavi renkli leke antifrizli soğutma suyunu işaret eder. Sıcak günlerde klima çalışırken aracın altından damlayan berrak su ise çoğunlukla klimanın yoğuşma (terleme) suyudur ve normaldir. Renkli ve yağlı kaçaklar ise kontrol ettirilmelidir.',
    whyWrong: [
      'Berrak su her zaman yağ kaçağı değildir; çoğu zaman klima yoğuşma suyudur.',
      'Fren hidroliği yeşil değildir; ayrıca sıvının rengi kaynak hakkında değerli ipucu verir.',
    ],
    objective: 'Sızıntı rengiyle olası kaynağı (yağ/antifriz/klima suyu) ayırt etmek.',
    tags: ['sivi-kacagi', 'renk-teshis', 'park'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-653',
    subject: 'motor',
    topic: 'cam-turleri',
    difficulty: 'orta',
    stem: 'Araç camlarıyla ilgili doğru ifade aşağıdakilerden hangisidir?',
    options: [
      'Tüm camlar aynı tip normal cam olduğundan çarpınca keskin büyük parçalara ayrılır',
      'Ön cam, iki cam arasına yapıştırıcı katman konan lamine (katmanlı) yapıdadır; darbede dağılmayıp çatlar. Yan/arka camlar ise kırıldığında keskin olmayan küçük tanelere ayrılan temperli camdan yapılır',
      'Ön cam kırıldığında toz gibi dağılır',
      'Camların türünün güvenlikle bir ilgisi yoktur',
    ],
    answerIndex: 1,
    explanation:
      'Araçlarda güvenlik için farklı cam türleri kullanılır. Ön cam, iki cam tabakası arasına esnek bir ara katman yerleştirilen lamine yapıdadır; darbe aldığında dağılıp fırlamaz, çatlayarak yerinde kalır ve yolcuların dışarı savrulmasını da güçleştirir. Yan ve arka camlar ise temperlidir; kırıldığında keskin kenarlı büyük parçalar yerine küçük, nispeten zararsız tanelere ayrılır.',
    whyWrong: [
      'Araç camları normal cam değildir ve büyük keskin parçalara ayrılmaz; güvenlik için özel üretilir.',
      'Ön cam toz gibi dağılmaz; katmanlı yapısı sayesinde çatlayarak yerinde kalır. Cam türü doğrudan güvenlikle ilgilidir.',
    ],
    objective: 'Lamine ön cam ile temperli yan/arka cam ayrımını ve güvenlik amacını bilmek.',
    tags: ['cam-turleri', 'lamine-cam', 'temperli-cam'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-654',
    subject: 'motor',
    topic: 'cekme-halati',
    difficulty: 'kolay',
    stem: 'Arızalanan bir aracın halatla çekilerek taşınmasında temel güvenlik kuralıyla ilgili doğru ifade hangisidir?',
    options: [
      'Çekilen araçta kontak, direksiyon ve frenlerin çalışır durumda olması, aracın belirlenmiş çekme noktasından uygun halat/donanımla bağlanması ve iki araç arasında güvenli, gergin bir mesafe korunarak yavaş ve dikkatli gidilmesi gerekir',
      'Çekilen aracın kontağı tamamen kapatılmalı ve direksiyon kilitli kalmalıdır',
      'Halat ne kadar uzun ve gevşek olursa o kadar güvenlidir',
      'Çekme sırasında hız sınırı olmaksızın hızlı gidilebilir',
    ],
    answerIndex: 0,
    explanation:
      'Halatla çekmede, çekilen araçta direksiyon kilidinin açık (kontağın uygun konumda) ve fren sisteminin çalışır olması gerekir; aksi hâlde araç yönlendirilemez ve durdurulamaz. Halat aracın belirlenmiş çekme noktasına uygun donanımla bağlanır, iki araç arasında güvenli ve fazla sarkmayan bir mesafe korunur, yavaş ve ani hareketlerden kaçınarak gidilir. Motor çalışmıyorsa fren/direksiyon desteğinin zayıflayacağı da unutulmamalıdır.',
    whyWrong: [
      'Kontağın tamamen kapalı olması direksiyonu kilitleyip aracı yönetilemez kılar; bu tehlikelidir.',
      'Aşırı uzun/gevşek halat ani gerilmeyle kopabilir; ayrıca çekmede hızlı değil, yavaş ve dikkatli gidilmelidir.',
    ],
    objective: 'Halatla çekmede direksiyon/fren, bağlantı ve mesafe kurallarını bilmek.',
    tags: ['cekme-halati', 'arizali-arac', 'guvenlik'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-655',
    subject: 'motor',
    topic: 'periyodik-bakim-araligi',
    difficulty: 'kolay',
    stem: 'Aracın periyodik bakım zamanının belirlenmesiyle ilgili doğru ilke hangisidir?',
    options: [
      'Bakım yalnızca bir arıza ortaya çıkınca yapılır',
      'Üretici genellikle bir kilometre değeri ile bir süre (ör. belirli ay/yıl) belirtir; bunlardan hangisi önce dolarsa bakım o zaman yapılmalıdır. Böylece az kullanılan araç da zamana bağlı yaşlanan yağ/sıvılar nedeniyle ihmal edilmemiş olur',
      'Bakım aralığı sadece kilometreye bakılarak belirlenir, süre önemsizdir',
      'Bakım aralığı yalnızca aracın rengine göre değişir',
    ],
    answerIndex: 1,
    explanation:
      'Üreticiler bakım aralığını hem bir kilometre hem de bir süre (ay/yıl) olarak verir; kural, bu ikisinden hangisi önce dolarsa bakımın o zaman yapılmasıdır. Çünkü yağ ve sıvılar yalnızca kullanımla değil, zamanla da özelliğini yitirir. Böylece çok az kilometre yapan bir araç bile, süresi geldiğinde bakıma alınarak korunur. Bakımı arıza çıkmasını beklemek yerine düzenli yaptırmak esastır.',
    whyWrong: [
      'Bakımı arıza çıkınca yapmak, önlenebilir hasarların oluşmasına yol açar.',
      'Yalnızca kilometreye bakmak, az kullanılan araçta zamana bağlı yaşlanmayı göz ardı eder; aracın rengiyle ise hiçbir ilgisi yoktur.',
    ],
    objective: 'Bakım aralığında "km veya süre, hangisi önce dolarsa" ilkesini bilmek.',
    tags: ['periyodik-bakim', 'bakim-araligi', 'km-veya-sure'],
    review: 'draft',
    sourceRef: SRC,
  },
];
