/**
 * ÖZGÜN direksiyon (uygulama) soruları — 7. genişletme (Program 2 · Faz 9). ROADMAP C.4/E.6.
 * Odak: TEMEL BECERİLER ÖZETİ + SÜRÜŞ ÖNCESİ hazırlık. Kaynak = MEB direksiyon/uygulama müfredatı; KENDİ İFADEMİZLE.
 */
import type { QuestionInput } from '@ea/content-schema';

const SRC = 'MEB direksiyon (uygulama) müfredatı (özgün ifade)';

export const PRATIK_QUESTIONS_7: QuestionInput[] = [
  {
    id: 'pratik-701',
    subject: 'pratik',
    topic: 'surus-pozisyonu-koltuk',
    difficulty: 'orta',
    stem: 'Doğru sürüş pozisyonunda koltuğun ileri-geri mesafesi hangi ölçüte göre ayarlanır?',
    options: [
      'Debriyaj (kavrama) pedalına sonuna kadar basıldığında bacak tam gerilip kilitlenmeyecek, dizde hafif bir kıvrım kalacak ve sırt koltuğa yaslı olacak biçimde ayarlanır',
      'Bacak pedala ancak zar zor yetişecek kadar koltuk mümkün olduğunca geriye alınır',
      'Göğüs neredeyse direksiyona değecek kadar koltuk öne çekilir',
      'Koltuk her sürücü için aynı orta konumda bırakılır; kişinin boyuna göre değişmesine gerek yoktur',
    ],
    answerIndex: 0,
    explanation:
      'Koltuk mesafesi, debriyaja sonuna kadar basıldığında bacağın tam gerilmediği, dizde hafif bir kıvrımın kaldığı konuma göre ayarlanır. Bu, hem pedallara tam güç aktarmayı hem uzun sürüşte yorulmamayı sağlar. Sırt koltuğa yaslı kalmalı; böylece ani frende ve manevrada gövde desteklenir.',
    whyWrong: [
      'Bacak pedala zar zor yetişiyorsa debriyaj sonuna kadar basılamaz; acil frende de yeterli güç uygulanamaz.',
      'Göğsün direksiyona çok yakın olması, hava yastığı açıldığında yaralanma riski yaratır ve kol hareketini kısıtlar.',
      'Boy ve bacak uzunluğu kişiden kişiye değiştiği için sabit bir orta konum çoğu sürücüye uymaz.',
    ],
    objective: 'Debriyaj-diz kıvrımı ölçütüyle doğru koltuk mesafesini ayarlamayı öğrenmek.',
    tags: ['surus-pozisyonu', 'koltuk-ayari', 'pedal-hakimiyeti'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-702',
    subject: 'pratik',
    topic: 'kafalik-ayari',
    difficulty: 'kolay',
    stem: 'Baş desteğinin (kafalık) doğru ayarı neden önemlidir ve nasıl konumlandırılmalıdır?',
    options: [
      'Kafalık yalnızca konfor içindir; ayarının güvenlikle bir ilgisi yoktur',
      'Kafalık mümkün olduğunca aşağıda, ense hizasının altında tutulmalıdır',
      'Kafalığın üst kenarı başın üst hizasına yakın, arkası başa olabildiğince yakın olmalı; böylece arkadan çarpmada baş geriye savrulmaz ve boyun incinmesi (kamçı etkisi) azalır',
      'Görüş artsın diye kafalık tamamen çıkarılırsa daha güvenli olur',
    ],
    answerIndex: 2,
    explanation:
      'Arkadan çarpma anında gövde koltukla birlikte ileri iterken baş bir an geride kalır; bu ani zıtlık boyunda kamçı (whiplash) yaralanmasına yol açar. Doğru ayarlı kafalık, üst kenarı baş hizasında ve başa yakın durarak başı destekler ve bu savrulmayı sınırlar. Kafalık bir konfor parçası değil, pasif güvenlik donanımıdır.',
    whyWrong: [
      'Kafalık ayarı doğrudan boyun güvenliğini ilgilendirir; yalnızca konfor amacı taşımaz.',
      'Çok aşağıdaki bir kafalık başı destekleyemez, hatta bir dayanak noktası oluşturup zararı artırabilir.',
      'Kafalığı çıkarmak, arkadan çarpmada başı tümüyle korumasız bırakır.',
    ],
    objective: 'Kafalığın kamçı etkisine karşı doğru ayarını ve güvenlik işlevini kavramak.',
    tags: ['kafalik', 'boyun-guvenligi', 'surus-oncesi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-703',
    subject: 'pratik',
    topic: 'direksiyon-mesafe-ayari',
    difficulty: 'zor',
    stem: 'Direksiyonun mesafe ve yükseklik ayarının doğru yapıldığı en pratik biçimde nasıl anlaşılır?',
    options: [
      'Kollar dirsekten hiç kıvrılmayacak, tamamen düz ve kilitli uzanacak biçimde ayarlandığında ideal olur',
      'Direksiyon göğse dayanacak kadar yakına alındığında en iyi hâkimiyet sağlanır',
      'Direksiyon, gösterge panelini tümüyle örtecek kadar yukarı kaldırılır',
      'Kol uzatıldığında bilek direksiyonun üst kenarına düz biçimde yaslanıyor ve bu sırada omuz/sırt koltuktan ayrılmıyorsa mesafe uygundur; direksiyon, göstergeleri kapatmayacak yükseklikte tutulur',
    ],
    answerIndex: 3,
    explanation:
      'Bilek testi basit ve güvenilirdir: kol düz uzatıldığında bilek direksiyonun üst kenarına yaslanmalı ve bu sırada omuz koltuktan kalkmamalıdır. Bu konumda direksiyonu tuttuğunuzda dirsekler hafifçe kıvrık kalır; hem geniş açılı dönüşler rahat yapılır hem de omuz koltuğa yaslı kalarak kontrol korunur. Yükseklik ise gösterge ve ikaz lambalarını görmeyi engellemeyecek biçimde ayarlanır.',
    whyWrong: [
      'Kolların tümüyle düz ve kilitli olması, dönüşte omzun koltuktan kalkmasına ve tepkinin gecikmesine yol açar.',
      'Direksiyonu göğse dayamak, hava yastığı riskini artırır ve serbest manevra alanını daraltır.',
      'Göstergeleri örten bir direksiyon yüksekliği, hız ve ikaz lambalarının okunmasını engeller.',
    ],
    objective: 'Bilek testiyle direksiyon mesafe ve yüksekliğini doğru ayarlamayı öğrenmek.',
    tags: ['direksiyon-ayari', 'bilek-testi', 'surus-pozisyonu'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-704',
    subject: 'pratik',
    topic: 'ayna-uclusu-ayari',
    difficulty: 'orta',
    stem: 'İç dikiz aynası ile iki dış ayna (ayna üçlüsü) sürüş öncesinde nasıl ayarlanmalıdır?',
    options: [
      'Yalnızca iç ayna ayarlanır; dış aynalar gereksizdir',
      'İç ayna arka camı tam ortalayacak biçimde, dış aynalar ise kendi aracın kenarı en içte ince bir şerit hâlinde görünecek ve yolun büyük kısmı görünecek biçimde ayarlanır',
      'Dış aynalarda yalnızca kendi aracın gövdesi görünecek biçimde aynalar iyice içe çevrilir',
      'Aynalar sürüş sırasında ihtiyaç oldukça ayarlanır; önceden ayarlamaya gerek yoktur',
    ],
    answerIndex: 1,
    explanation:
      'Üç ayna birlikte arkayı ve iki yanı tarar. İç ayna arka camı ortalayacak biçimde kurulur; dış aynalarda ise kendi aracın kenarı yalnızca ince bir şerit kadar görünmeli, geri kalan alanı yol ve yandaki şeritler doldurmalıdır. Bu ayar en geniş görüşü verir ve kör noktaları küçültür. Ayarlar araç dururken yapılır.',
    whyWrong: [
      'Dış aynalar yan şeritleri ve kör noktayı görmek için şarttır; yalnız iç ayna yetmez.',
      'Aynaları iyice içe çevirip yalnız gövdeyi görmek, görüş alanını daraltıp kör noktayı büyütür.',
      'Aynaları hareket hâlinde ayarlamak dikkati dağıtır ve gözlem geç kalır.',
    ],
    objective: 'İç ve iki dış aynayı en geniş görüşü verecek biçimde ayarlamayı öğrenmek.',
    tags: ['ayna-ayari', 'ic-ayna', 'dis-ayna'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-705',
    subject: 'pratik',
    topic: 'ayna-kor-nokta-ayari',
    difficulty: 'zor',
    stem: 'Dış aynaları kör noktayı en aza indirecek biçimde ayarlamak için doğru yaklaşım nedir?',
    options: [
      'Dış aynaları içe çevirip kendi aracın yan gövdesini bolca görecek biçimde ayarlamak kör noktayı kapatır',
      'Kör nokta ayna ayarıyla hiç değişmez; yalnızca omuz üstü bakış işe yarar',
      'Dış aynalar biraz daha dışa açılarak aracın yalnızca kenar ucu görünecek kadar bırakılır; böylece iç aynayla dış aynanın gördüğü alanlar üst üste binmez, yan taraf daha geniş taranır ve kör nokta küçülür (yine de şerit değişiminde omuz kontrolü yapılır)',
      'Dış aynaları aşağı eğip yalnızca yakındaki asfaltı görecek biçimde ayarlamak en güvenlisidir',
    ],
    answerIndex: 2,
    explanation:
      'Dış aynalar çok içe bakacak biçimde ayarlanırsa iç aynanın gösterdiği alanı tekrar gösterir; bu da yan tarafı boşta bırakıp kör noktayı büyütür. Aynaları biraz daha dışa açıp aracın yalnızca kenar ucu görünecek kadar bırakmak, iç ve dış aynaların görüş alanlarının örtüşmesini önler ve yanı daha geniş tarar. Böylece kör nokta belirgin biçimde küçülür; yine de şerit değişiminden önce omuz üstü kontrol ihmal edilmez.',
    whyWrong: [
      'Aynaları içe çevirip gövdeyi bolca görmek, iç aynayla aynı alanı gösterip kör noktayı büyütür.',
      'Doğru ayna ayarı kör noktayı belirgin biçimde küçültür; ayarın etkisiz olduğu görüşü yanlıştır.',
      'Aynaları aşağı eğmek yalnızca zemini gösterir, yan şeritteki araçları hiç görmez.',
    ],
    objective: 'Dış ayna açısını kör noktayı küçültecek biçimde ayarlamayı kavramak.',
    tags: ['kor-nokta', 'dis-ayna', 'ayna-ayari'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-706',
    subject: 'pratik',
    topic: 'kemer-dogru-takma',
    difficulty: 'kolay',
    stem: 'Emniyet kemeri doğru biçimde nasıl takılır?',
    options: [
      'Omuz kayışı boyundan değil omuz üzerinden göğse çapraz geçmeli, alt kayış karın üzerinden değil kalça kemiği üzerinden oturmalı; kemer bükülmemeli ve gevşek bırakılmamalıdır',
      'Rahat olsun diye kemer koltuk arkasından ya da kol altından geçirilerek takılır',
      'Omuz kayışı sürekli boyna değdiği için başın arkasından dolandırılır',
      'Kısa mesafelerde ve şehir içinde kemer takmaya gerek yoktur',
    ],
    answerIndex: 0,
    explanation:
      'Emniyet kemeri, çarpışma kuvvetini iskeletin en güçlü noktalarına, yani omuz ve kalça kemiğine aktaracak biçimde takılmalıdır. Omuz kayışı boyundan değil omuz üzerinden geçmeli, alt kayış yumuşak karın yerine kalça kemiğine oturmalıdır. Bükülmüş ya da gevşek bir kemer, darbe anında koruma yüzeyini azaltır ve iç organ yaralanması riskini artırır.',
    whyWrong: [
      'Kemeri koltuk arkasından ya da kol altından geçirmek, çarpışmada onu işlevsiz bırakır.',
      'Kemeri başın arkasından dolamak koruma sağlamaz; kayış doğru yol üzerinde durmalıdır.',
      'Kaza kısa mesafede ve şehir içinde de olabilir; kemer her koşulda takılır.',
    ],
    objective: 'Emniyet kemerinin omuz-kalça hattından doğru takılışını kavramak.',
    tags: ['emniyet-kemeri', 'dogru-takma', 'pasif-guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-707',
    subject: 'pratik',
    topic: 'pedal-tanima',
    difficulty: 'orta',
    stem: 'Manuel vitesli araçta pedalların yerleşimi ve ayak kullanımıyla ilgili doğru bilgi hangisidir?',
    options: [
      'Her üç pedal da tek elle, yani yalnızca sağ ayakla kullanılır',
      'Debriyaj sağda, gaz solda yer alır',
      'Fren pedalı hem sol hem sağ ayakla dönüşümlü basılır',
      'Soldan sağa debriyaj-fren-gaz sırasıyla dizilir; debriyaj sol ayakla, fren ve gaz ise sağ ayakla kullanılır (sağ ayak fren ile gaz arasında gidip gelir)',
    ],
    answerIndex: 3,
    explanation:
      'Manuel araçta üç pedal soldan sağa debriyaj-fren-gaz sırasıyla dizilir. Debriyaj yalnız sol ayakla kullanılır; fren ve gaz ise sağ ayağın gidip gelmesiyle çalıştırılır. Bu iş bölümü, kalkış ve durmalarda ayakların birbirine karışmadan doğru pedala gitmesini sağlar.',
    whyWrong: [
      'Üç pedal tek ayakla kullanılamaz; debriyaj her zaman sol ayağa aittir.',
      'Debriyaj sol ayakla kullanıldığından soldadır, gaz ise en sağdadır; sıralama tersine söylenmiştir.',
      'Freni sol ayakla basmak manuel araçta alışılmış değildir ve debriyajla karışıklık yaratır.',
    ],
    objective: 'Manuel araçta pedal düzenini ve doğru ayak kullanımını tanımak.',
    tags: ['pedallar', 'debriyaj', 'ayak-kullanimi'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-708',
    subject: 'pratik',
    topic: 'ikaz-lambalari-kontrol',
    difficulty: 'orta',
    stem: 'Kontak açıldığında gösterge panelindeki ikaz (uyarı) lambalarıyla ilgili doğru davranış nedir?',
    options: [
      'İkaz lambalarına bakmaya gerek yoktur; önemli olan motoru bir an önce çalıştırmaktır',
      'Kontak açıldığında lambalar bir an yanıp test yapar; motor çalışınca yağ basıncı, akü şarj, ABS ve motor arıza gibi lambaların sönmesi beklenir. Sönmeyen kırmızı bir ikaz varsa yola çıkmadan nedeni araştırılır',
      'Panelde yanan tüm lambalar normaldir ve sürüşü hiçbir biçimde etkilemez',
      'Yalnızca yakıt lambası önemlidir; diğer ikazlar göz ardı edilebilir',
    ],
    answerIndex: 1,
    explanation:
      'Kontak açıldığında ikaz lambaları kısa bir öz test için yanar; motor çalıştıktan sonra yağ basıncı, akü şarj, ABS ve motor arıza gibi lambaların sönmesi gerekir. Bunlardan biri, özellikle kırmızı bir ikaz sönmeden kalıyorsa bir arıza işareti olabilir ve yola çıkmadan nedeni araştırılmalıdır. Göstergeleri okuma alışkanlığı, birçok sorunu daha yola çıkmadan yakalar.',
    whyWrong: [
      'İkazlara bakmamak, ciddi bir arızayı fark etmeden yola çıkmaya yol açar.',
      'Yanmaya devam eden bazı lambalar ciddi arıza işaretidir; hepsini normal saymak yanlıştır.',
      'Yağ, hararet ve fren gibi ikazlar da en az yakıt kadar kritik olabilir.',
    ],
    objective: 'Sürüş öncesi ikaz lambalarını okuyup arızayı erken fark etmeyi öğrenmek.',
    tags: ['ikaz-lambalari', 'gosterge-paneli', 'surus-oncesi-kontrol'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-709',
    subject: 'pratik',
    topic: 'gosterge-paneli-okuma',
    difficulty: 'kolay',
    stem: 'Sürüşe başlamadan önce ve sürüş sırasında hangi temel göstergeleri okumak doğrudur?',
    options: [
      'Yalnızca saat ve dış hava sıcaklığı göstergesi',
      'Yalnızca radyo frekansı ve ses seviyesi',
      'Yakıt seviyesi, motor hararet (sıcaklık) göstergesi, hız ve devir (rpm) göstergeleri ile ikaz lambaları',
      'Göstergeler hiçbir zaman okunmaz; sürücü yalnızca yolu izler',
    ],
    answerIndex: 2,
    explanation:
      'Sürüş öncesinde yakıtın yeterli olup olmadığı ve hararet göstergesinin normal aralıkta olduğu kontrol edilir. Sürüş sırasında ise hız göstergesi ile devir (rpm) göstergesi, uygun hız ve doğru vites için ara ara izlenir; ikaz lambaları da göz ucuyla takip edilir. Bu göstergeler aracın ve sürüşün durumunu özetler.',
    whyWrong: [
      'Saat ve dış sıcaklık, sürüş güvenliğini belirleyen göstergeler değildir.',
      'Radyo ayarlarının araç ve sürüş durumuyla ilgisi yoktur.',
      'Göstergeler sürüş boyunca ara ara okunmalıdır; tümüyle göz ardı edilmez.',
    ],
    objective: 'Temel gösterge panelini (yakıt, hararet, hız, devir) okumayı öğrenmek.',
    tags: ['gosterge-paneli', 'hararet', 'devir-gostergesi'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-710',
    subject: 'pratik',
    topic: 'motor-oncesi-kontrol',
    difficulty: 'zor',
    stem: 'Motoru çalıştırmadan hemen önce yapılan "el freni çekili, vites boşta, debriyaj basılı" kontrol dizisinin gerekçesi nedir?',
    options: [
      'Yalnızca aküyü korumak için yapılan bir işlemdir',
      'Sadece yakıt tasarrufu sağlamak amacıyla önerilir',
      'Yerleşmiş bir gelenektir; somut bir güvenlik gerekçesi yoktur',
      'Vites boştayken ve debriyaj basılıyken çalıştırmak, motor devreye girdiğinde aracın istem dışı ileri sıçramasını önler; el freni ise araç herhangi bir eğimde tutulu kalsın diye çekili bırakılır',
    ],
    answerIndex: 3,
    explanation:
      'Vites takılıyken ve debriyaja basmadan çalıştırılan araç, motor devreye girdiği an öne fırlayabilir; bu yüzden vites boşta tutulur ve ek güvence olarak debriyaja basılır. El freninin çekili olması ise, aracın fark edilmeyen bir eğimde kaymadan sabit durmasını sağlar. Bu üç adım birlikte, çalıştırma anını güvenli kılar.',
    whyWrong: [
      'Akünün korunması bu dizinin amacı değildir; asıl neden güvenliktir.',
      'Yakıt tasarrufu ile ilgisi yoktur; amaç kontrolsüz hareketi önlemektir.',
      'Bu bir alışkanlık değil, somut bir güvenlik gerekçesine dayanan kontroldür.',
    ],
    objective:
      'Çalıştırma öncesi vites-debriyaj-el freni kontrolünün güvenlik gerekçesini kavramak.',
    tags: ['motor-calistirma', 'vites-bosta', 'el-freni'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-711',
    subject: 'pratik',
    topic: 'kalkis-adimlari-ozet',
    difficulty: 'orta',
    stem: 'Manuel vitesli araçta düz zeminde kalkışın temel adım sırası hangisidir?',
    options: [
      'Debriyaja bas, 1. vitese al, sinyal ver ve aynalarla çevreyi kontrol et; el frenini indirirken debriyajı kavrama noktasına getirip gazı yumuşakça ver',
      'Önce gaza sonuna kadar bas, sonra vitesi tak',
      'El frenini indirmeden ve debriyaja basmadan 3. vitesle doğrudan kalkış yap',
      'Debriyaja hiç basmadan vites takıp hemen hareket et',
    ],
    answerIndex: 0,
    explanation:
      'Düzgün bir kalkış sırayla ilerler: debriyaja basılır, 1. vitese alınır, niyet sinyalle bildirilir ve aynalarla çevre kontrol edilir. Ardından el freni indirilirken debriyaj kavrama noktasına getirilip gaz yumuşakça verilir; araç yüklendikçe debriyaj tam bırakılır. Bu düzen, sarsıntısız ve güvenli bir kalkış sağlar.',
    whyWrong: [
      'Önce sonuna kadar gaz vermek motoru yükseltir ve kavrama anında araç sarsılır ya da fırlar.',
      '3. vitesle kalkış motoru boğar; debriyaj ve el freni adımlarının atlanması kalkışı bozar.',
      'Debriyaja basmadan vites takmak dişlileri zorlar ve düzgün kalkış yapılamaz.',
    ],
    objective: 'Manuel araçta düz zeminde kalkış adımlarını doğru sırayla uygulayabilmek.',
    tags: ['kalkis', 'debriyaj', 'sinyal'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-712',
    subject: 'pratik',
    topic: 'hiz-vites-devir',
    difficulty: 'orta',
    stem: 'Düz yolda hız arttıkça bir üst vitese ne zaman geçilir?',
    options: [
      'Vites hiç değiştirilmez; tüm yol tek viteste gidilir',
      'Motor devri (ve sesi) yükselip araç o vitese göre yeterli hıza ulaştığında bir üst vitese geçilir; motor zorlanmadan uygun devir aralığında tutulur',
      'Hız ne olursa olsun her zaman en yüksek viteste gidilir',
      'Vites yalnızca yokuş çıkarken değiştirilir; düz yolda değişmez',
    ],
    answerIndex: 1,
    explanation:
      'Vites yükseltmenin ölçütü motor devri ve sesidir: araç o viteste yeterli hıza ulaşıp devir yükseldiğinde bir üst vitese geçilir. Amaç, motoru ne boğacak kadar düşük ne de gereksiz yüksek devirde tutmadan uygun aralıkta çalıştırmaktır. Kulakla motorun zorlandığını duymak da doğru vites zamanının işaretidir.',
    whyWrong: [
      'Tek viteste gitmek, motoru ya boğar ya da sürekli yüksek devirde tutup zorlar.',
      'Düşük hızda en yüksek viteste gitmek motoru titretir ve stop ettirebilir.',
      'Vites, hız değiştikçe düz yolda da değiştirilir; yalnız yokuşla sınırlı değildir.',
    ],
    objective: 'Motor devri ve sesine göre üst vitese geçiş zamanını belirleyebilmek.',
    tags: ['vites-yukseltme', 'motor-devri', 'hiz-uyumu'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-713',
    subject: 'pratik',
    topic: 'kademeli-erken-fren',
    difficulty: 'orta',
    stem: 'Normal koşullarda doğru frenleme nasıl olmalıdır?',
    options: [
      'Durulacak yere iyice gelince tek hamlede ve sert biçimde frene basılır',
      'Fren yalnızca acil durumda kullanılır; normal yavaşlama motor freniyle yapılır',
      'Durulacak yer önceden görülüp frene erken ve kademeli (önce hafif, gerektikçe artan) basılır; böylece araç yumuşak durur, arkadaki sürücü uyarılmış olur ve kaygan zeminde kayma riski azalır',
      'Motor boşa alınıp yalnızca yolun eğimiyle yavaşlanır',
    ],
    answerIndex: 2,
    explanation:
      'İyi frenleme geç değil erken başlar: durulacak nokta önceden görülür ve frene önce hafif, gerektikçe artan bir biçimde basılır. Bu kademeli yaklaşım aracı yumuşak durdurur, arkadaki sürücüye erken uyarı verir ve kaygan zeminde tekerleklerin kilitlenip kaymasını önler. Son anda yapılan sert fren ise hem konforsuz hem risklidir.',
    whyWrong: [
      'Son anda tek hamlede sert fren, savrulma ve arkadan çarpılma riskini artırır.',
      'Fren yalnız acil durumla sınırlı değildir; normal yavaşlamaların da temel aracıdır.',
      'Motoru boşa alıp yalnız eğimle yavaşlamak, motor freni desteğini ve kontrolü ortadan kaldırır.',
    ],
    objective: 'Erken ve kademeli frenlemenin güvenlik üstünlüğünü kavramak.',
    tags: ['frenleme', 'kademeli-fren', 'erken-fren'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-714',
    subject: 'pratik',
    topic: 'viraj-hiz-secimi',
    difficulty: 'zor',
    stem: 'Viraja girmeden önce seçilecek hız neye göre belirlenir?',
    options: [
      'Her viraj aynı hızda alınır; virajın özelliği fark etmez',
      'Viraja mümkün olduğunca hızlı girip hız ayarını içeride fren yaparak yapmak en doğrusudur',
      'Hız yalnızca yol ıslaksa düşürülür; kuru yolda virajda hızın önemi yoktur',
      'Virajın keskinliği, görüş mesafesi ve zemin durumu birlikte değerlendirilir; keskin, görüşü kapalı veya kaygan virajda daha çok yavaşlanır ve hız düz kesimdeyken ayarlanıp viraja uygun hızda girilir',
    ],
    answerIndex: 3,
    explanation:
      'Viraj giriş hızı tek bir kurala değil, üç etkenin birleşimine göre seçilir: virajın keskinliği, önün ne kadar görülebildiği ve zeminin tutunma durumu. Keskin, görüşün kapalı olduğu ya da ıslak-kaygan bir virajda hız daha çok düşürülür. Hız ayarı tekerlekler düzken, yani viraja girmeden yapılır; böylece viraj içinde ani frene gerek kalmaz ve araç dengede kalır.',
    whyWrong: [
      'Her viraj aynı değildir; keskinlik ve görüş değiştikçe güvenli hız da değişir.',
      'Hızlı girip içeride fren yapmak, tutunmayı bölerek savrulmaya yol açar.',
      'Kuru yolda da keskin bir virajda aşırı hız aracı şeritten dışarı savurabilir.',
    ],
    objective: 'Viraj giriş hızını keskinlik, görüş ve zemine göre seçmeyi öğrenmek.',
    tags: ['viraj-hizi', 'gorus-mesafesi', 'hiz-secimi'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-715',
    subject: 'pratik',
    topic: 'donus-kontrol-dizisi',
    difficulty: 'orta',
    stem: 'Bir kavşaktan sağa ya da sola dönmeden önce doğru kontrol ve işaret sırası nedir?',
    options: [
      'Aynalardan çevreyi kontrol et, dönüş sinyalini yeterince önce ver, dönülecek yöndeki kör noktayı gerektiğinde omuz üstünden gör, hızı düşür ve uygun konumdan dön',
      'Önce direksiyonu kırıp dön, sinyali dönüşten sonra ver',
      'Sinyal vermeden yalnızca kornayla uyararak dön',
      'Aynalara hiç bakmadan doğrudan direksiyonu istenen yöne kır',
    ],
    answerIndex: 0,
    explanation:
      'Dönüş güvenli bir dizinin ürünüdür: önce aynalardan çevre görülür, niyet dönüşten yeterince önce sinyalle bildirilir, dönülecek yöndeki kör nokta gerektiğinde omuz üstünden kontrol edilir; ardından hız düşürülüp uygun konumdan dönülür. Bu ayna-sinyal-kör nokta sırası, hem arkadaki hem yandaki trafiği hesaba katar.',
    whyWrong: [
      'Sinyali dönüşten sonra vermek, kimseyi zamanında uyaramaz.',
      'Korna niyet bildirmez; dönüş için sinyal ve gözlem gerekir.',
      'Aynalara bakmadan dönmek, yandan ve arkadan gelen trafiği görmemeye yol açar.',
    ],
    objective: 'Dönüş öncesi ayna-sinyal-kör nokta kontrol dizisini uygulayabilmek.',
    tags: ['donus', 'sinyal', 'kor-nokta'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-716',
    subject: 'pratik',
    topic: 'geri-manevra-gozlem-ozet',
    difficulty: 'kolay',
    stem: 'Aracı geri geri hareket ettirirken temel gözlem nasıl yapılmalıdır?',
    options: [
      'Yalnızca dikiz aynasına bakmak yeterlidir',
      'Manevra çabuk bitsin diye geri gidiş mümkün olduğunca hızlı yapılır',
      'Geri gitmeden önce araç çevresi (özellikle arkada çocuk/engel) kontrol edilir; manevra sırasında gövde sağa dönülüp arka camdan bakılır, aynalar da kullanılır ve araç çok düşük hızda hareket ettirilir',
      'Geri giderken korna çalmak, gözlem yapmanın yerini tutar',
    ],
    answerIndex: 2,
    explanation:
      'Geri manevrada aracın arkası sürücünün en zor gördüğü alandır; bu yüzden gitmeden önce çevre, özellikle arkada çocuk ya da engel olup olmadığı kontrol edilir. Manevra sırasında gövde sağa dönülüp arka camdan bakılır, aynalar destekleyici olarak kullanılır ve araç tepki payı bırakacak kadar düşük hızda hareket ettirilir. Yavaşlık, burada güvenliğin temelidir.',
    whyWrong: [
      'Tek bir aynaya bakmak, arka ve yan kör noktaları gizler.',
      'Geri giderken hızlı gitmek tepki payını yok eder ve tehlike yaratır.',
      'Korna, arkadaki engeli görmenin yerini tutmaz.',
    ],
    objective: 'Geri manevrada çevre gözlemi, arka cam bakışı ve düşük hız ilkesini uygulamak.',
    tags: ['geri-manevra', 'gozlem', 'dusuk-hiz'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-717',
    subject: 'pratik',
    topic: 'dusuk-hiz-direksiyon',
    difficulty: 'zor',
    stem: 'Dar bir alanda çok düşük hızda direksiyon hâkimiyeti nasıl sağlanır?',
    options: [
      'Araç tamamen dururken direksiyonu zorlayarak çevirmek en doğru yöntemdir',
      'Debriyaj yarım (kavrama noktası) tutularak hız çok düşük ve sabit tutulur, direksiyon araç hafifçe hareket hâlindeyken çevrilir; böylece hem hıza hem yöne aynı anda hâkim olunur',
      'Gaz sonuna kadar verilip direksiyon hızla çevrilir',
      'Manevra boyunca gözler yalnızca ön tekerleğe sabitlenir',
    ],
    answerIndex: 1,
    explanation:
      'Dar manevralarda hız düşük ama kontrollü olmalıdır: debriyaj kavrama noktasında tutularak araç çok yavaş ve sabit ilerletilir, direksiyon ise araç hafifçe hareket hâlindeyken çevrilir. Böylece hem hız hem yön aynı anda yönetilir ve araç istenen yere oturur. Bakış, gidilecek yöne ve çevreye taşınır; yalnız ön tekere odaklanmak manevrayı bozar.',
    whyWrong: [
      'Araç dururken direksiyonu zorlamak lastik ve direksiyon mekanizmasını yıpratır; doğrusu hareket hâlinde çevirmektir.',
      'Sonuna kadar gaz vermek düşük hız hâkimiyetini bozar ve aracı fırlatır.',
      'Yalnız ön tekere bakmak, gidilecek yönü ve çevredeki engelleri gözden kaçırır.',
    ],
    objective: 'Yarım debriyaj ve hareket hâlinde direksiyonla düşük hız hâkimiyetini öğrenmek.',
    tags: ['dusuk-hiz', 'yarim-debriyaj', 'direksiyon-hakimiyeti'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-718',
    subject: 'pratik',
    topic: 'park-turleri-ozet',
    difficulty: 'kolay',
    stem: 'Paralel, dik ve açılı park türleri arasındaki temel fark nedir?',
    options: [
      'Üçü de aynıdır; yalnızca isimleri farklıdır',
      'Paralel park yalnızca geniş otoparklarda yapılabilir',
      'Dik park, aracı kaldırıma paralel biçimde tek hamlede ileri sürerek yapılan parktır',
      'Paralel parkta araç yola/kaldırıma paralel olarak genelde geri manevrayla iki araç arasına yerleştirilir; dik parkta araç yol kenarına dik açıyla (90 derece), açılı parkta ise eğik (örneğin 45 derece) konumlanır',
    ],
    answerIndex: 3,
    explanation:
      'Park türleri, aracın yola ve park yerine göre aldığı açıyla ayrılır. Paralel parkta araç yola paralel durur ve genellikle geri manevrayla iki araç arasına sokulur. Dik parkta araç yol kenarına dik (90 derece), açılı parkta ise eğik bir açıyla (örneğin 45 derece) yerleşir. Her biri farklı manevra ve direksiyon zamanlaması ister.',
    whyWrong: [
      'Park türleri aynı değildir; her biri farklı geometri ve manevra gerektirir.',
      'Paralel park özellikle dar cadde kenarlarında kullanılır; geniş otoparkla sınırlı değildir.',
      'Dik park kaldırıma paralel değil dik açıyladır ve çoğunlukla geri manevrayla yapılır.',
    ],
    objective: 'Paralel, dik ve açılı park türlerinin geometrik farkını kavramak.',
    tags: ['park-turleri', 'paralel-park', 'dik-park'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-719',
    subject: 'pratik',
    topic: 'guvenli-park-ozet',
    difficulty: 'orta',
    stem: 'Aracı park edip terk ederken güvenliği sağlamak için hangi işlemler bir bütün olarak yapılır?',
    options: [
      'Araç düzgün durdurulur, el freni (park freni) çekilir, manuel araçta uygun vites takılır (yokuşta yönüne göre 1. ya da geri vites), eğimliyse ön tekerlekler bordüre doğru çevrilir ve kontak kapatılır',
      'Yalnızca kontak kapatılır; el freni ve vites gereksizdir',
      'Vites boşta bırakılıp el freni indirilir',
      'Motor çalışır bırakılıp araçtan inilir',
    ],
    answerIndex: 0,
    explanation:
      'Aracı emniyetli bırakmak birkaç adımın birlikte yapılmasıdır: araç düzgün durdurulur, el freni çekilir, manuel araçta uygun vites takılır (yokuşta yönüne göre 1. ya da geri) ve eğimliyse ön tekerlekler bordüre doğru çevrilir. En son kontak kapatılır. Böylece el freni gevşese ya da tutmasa bile araç kendiliğinden ilerleyemez.',
    whyWrong: [
      'Yalnız kontağı kapatmak aracın eğimde kaymasını önlemez.',
      'Boşta ve el freni indirilmiş araç, en küçük eğimde bile kayabilir.',
      'Motoru çalışır bırakıp inmek hem güvensiz hem de istem dışı harekete açıktır.',
    ],
    objective: 'El freni, uygun vites ve teker yönüyle aracı emniyetli park etmeyi öğrenmek.',
    tags: ['guvenli-park', 'el-freni', 'teker-yonu'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-720',
    subject: 'pratik',
    topic: 'gece-far-ozet',
    difficulty: 'orta',
    stem: 'Gece sürüşünde uzun far ile kısa (yakın) far ne zaman kullanılmalıdır?',
    options: [
      'Gece her koşulda uzun far açık tutulur',
      'Karşıdan araç gelince, sürücüyü uyarmak için uzun far açılır',
      'Yerleşim yeri dışında yol boş ve karşıda/önde araç yokken uzun far kullanılabilir; karşıdan araç geldiğinde, öndeki araca yaklaşıldığında ve yerleşim yeri içinde kısa fara geçilir',
      'Gece yalnızca park (gabari) lambalarıyla, farlar kapalı gidilir',
    ],
    answerIndex: 2,
    explanation:
      'Uzun far, görüş mesafesini artırdığı için yerleşim yeri dışında yol boşken ve karşıda ya da önde araç yokken kullanılır. Karşıdan bir araç geldiğinde, öndeki araca yaklaşıldığında ve yerleşim yeri içinde kısa fara geçilir; böylece diğer sürücülerin gözü kamaşmaz. Farları doğru zamanda değiştirmek hem kendi görüşünü hem karşının güvenliğini korur.',
    whyWrong: [
      'Sürekli uzun far, karşıdan geleni ve öndeki aracı kamaştırıp tehlike yaratır.',
      'Karşıdan gelen araca uzun far yakmak, onu geçici olarak kör edebilir ve kural dışıdır.',
      'Yalnız park lambasıyla sürüş, gece için gereken görüşü hiçbir biçimde sağlamaz.',
    ],
    objective: 'Uzun ve kısa far kullanımının doğru zamanlamasını kavramak.',
    tags: ['gece-surus', 'far-kullanimi', 'uzun-kisa-far'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-721',
    subject: 'pratik',
    topic: 'yagmur-gorus-hiz',
    difficulty: 'orta',
    stem: 'Yağmurlu havada görüş ve hız nasıl yönetilmelidir?',
    options: [
      'Yağmurdan çabuk çıkmak için hız artırılır',
      'Silecekler çalıştırılıp ön cam açık tutulur, gündüz bile kısa farlar yakılarak görünürlük artırılır, hız azaltılıp takip mesafesi uzatılır ve ıslak zeminde fren yolu uzadığından ani fren ile ani direksiyondan kaçınılır',
      'Silecek ve fara gerek yoktur; görüş kendiliğinden yeterlidir',
      'Seyir hâlinde dörtlü flaşör sürekli yakılıp normal hızda devam edilir',
    ],
    answerIndex: 1,
    explanation:
      'Yağmurda hem görüş azalır hem zemin kayganlaşır; bu yüzden silecekler cam netliğini korumak için çalıştırılır ve gündüz bile kısa farlar yakılarak araç görünür kılınır. Hız düşürülüp takip mesafesi uzatılır, çünkü ıslak asfaltta fren yolu belirgin biçimde uzar. Ani fren ve ani direksiyon, tutunması azalmış lastiklerde kaymaya yol açacağından bunlardan kaçınılır.',
    whyWrong: [
      'Hızı artırmak, uzayan fren yolu nedeniyle tam tersine tehlikelidir.',
      'Silecek ve far olmadan görüş yetersiz kalır ve araç yeterince görünmez.',
      'Seyir hâlinde sürekli flaşör, dönüş ve şerit sinyalini işlevsiz kılıp diğerlerini yanıltır.',
    ],
    objective: 'Yağmurda görüş ve hızı silecek, far, mesafe ve yumuşak kullanımla yönetmek.',
    tags: ['yagmur', 'gorus', 'hiz-dusurme'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-722',
    subject: 'pratik',
    topic: 'takip-mesafesi-kavram',
    difficulty: 'kolay',
    stem: 'Öndeki araçla bırakılan takip mesafesi temelde neyi ifade eder?',
    options: [
      'Öndeki aracın plakasını rahatça okuyabilecek kadar yakın durmayı',
      'Hızdan bağımsız olarak her zaman sabit birkaç metreyi',
      'Yalnızca otoyolda bırakılması gereken bir boşluğu',
      'Öndeki araç aniden yavaşladığında sürücünün durumu fark edip fren yapması için gereken tepki ve fren payını; bu yüzden hız arttıkça ve hava kötüleştikçe mesafe de artırılır',
    ],
    answerIndex: 3,
    explanation:
      'Takip mesafesi, öndeki araç aniden yavaşladığında tehlikeyi fark etme (tepki) ve durabilme (fren) için gereken boşluktur. Hız arttıkça hem tepki sırasında alınan yol hem fren mesafesi uzadığı için bırakılacak mesafe de büyür. Yağmur, buz ya da sis gibi koşullarda bu pay daha da açılır. Yakın takip, en sık arkadan çarpma nedenidir.',
    whyWrong: [
      'Plakayı okuyacak kadar yakın durmak, tehlikeli derecede kısa bir mesafedir.',
      'Mesafe sabit değildir; hızla birlikte artar.',
      'Takip mesafesi yalnız otoyolda değil, şehir içinde de gereklidir.',
    ],
    objective: 'Takip mesafesini tepki ve fren payı olarak kavrayıp hıza göre ayarlamak.',
    tags: ['takip-mesafesi', 'fren-mesafesi', 'tepki-suresi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-723',
    subject: 'pratik',
    topic: 'arac-teslim-alma',
    difficulty: 'kolay',
    stem: 'Direksiyon sınavında ya da yabancı bir araca binerken aracı teslim alırken hangi ön kontrol yararlıdır?',
    options: [
      'Araç çevresinde kısa bir göz gezdirmesi (lastikler, farlar, cam ve aynalar), ardından içeride koltuk-ayna-kemer ayarı ile vites şeması ve pedal yerleşimini tanımak',
      'Doğrudan gaza basıp aracı deneyerek yola çıkmak',
      'Yalnızca yakıt seviyesine bakmak yeterlidir',
      'Hiçbir kontrol yapmadan hemen hareket etmek',
    ],
    answerIndex: 0,
    explanation:
      'Bir aracı teslim alırken önce çevresinde kısa bir göz gezdirmek (lastikler, farlar, cam ve aynalar) belirgin bir eksikliği daha yola çıkmadan gösterir. Sonra içeride koltuk, ayna ve kemer kişiye göre ayarlanır; vites şeması ve pedal yerleşimi tanınır. Özellikle yabancı bir araçta geri vitesin nasıl takıldığını bilmek, manevra anındaki şaşkınlığı önler.',
    whyWrong: [
      'Gaza basıp denemek kontrolsüz ve tehlikelidir; aracı tanımanın yerini tutmaz.',
      'Yalnız yakıt seviyesine bakmak, lastik ve ayar gibi kritik ayrıntıları atlar.',
      'Hiç kontrol yapmadan hareket etmek, tanınmayan bir araçta riski büyütür.',
    ],
    objective: 'Aracı teslim alırken dış tur ve iç ayar-tanıma kontrolünü uygulayabilmek.',
    tags: ['arac-tanima', 'on-kontrol', 'sinav-hazirlik'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-724',
    subject: 'pratik',
    topic: 'surus-sonrasi-birakma',
    difficulty: 'kolay',
    stem: 'Sürüş bittikten sonra aracı bırakırken hangi işlemler yapılmalıdır?',
    options: [
      'Yalnızca kapıyı çarpıp uzaklaşmak',
      'Motoru ve farları açık bırakıp inmek',
      'Motor durdurulur, farlar ve varsa açık kalan tüketiciler kapatılır, el freni çekilip uygun vites takılır, camlar kapatılır ve araçtan inip kapılar kilitlenir',
      'Araç boşta ve el freni indirilmiş biçimde bırakılır',
    ],
    answerIndex: 2,
    explanation:
      'Aracı bırakırken de bir kapanış düzeni izlenir: motor durdurulur, farlar ve açık kalan elektrik tüketicileri kapatılır, el freni çekilip uygun vites takılır. Camlar kapatılır ve araçtan inildikten sonra kapılar kilitlenir. Bu adımlar hem akünün boşalmasını hem aracın istem dışı hareketini hem de güvenlik açığını önler.',
    whyWrong: [
      'Kapatma işlemlerini atlayıp uzaklaşmak, aracı güvenceye almadan bırakmaktır.',
      'Farları açık unutmak aküyü bitirir; motoru açık bırakmak güvensizdir.',
      'Boşta ve frensiz bırakılan araç, en küçük eğimde bile kayabilir.',
    ],
    objective: 'Sürüş sonrası aracı kapatma ve güvenceye alma adımlarını uygulamak.',
    tags: ['surus-sonrasi', 'arac-birakma', 'kontak-kapatma'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-725',
    subject: 'pratik',
    topic: 'yakit-ikmali-guvenlik',
    difficulty: 'kolay',
    stem: 'Akaryakıt istasyonunda yakıt ikmali yapılırken güvenlik için doğru davranış nedir?',
    options: [
      'Motor çalışır hâlde ve sigara içilerek ikmal yapılabilir',
      'Motor durdurulur ve kontak kapatılır, sigara içilmez ve açık ateşten uzak durulur; ikmal boyunca telefonla oyalanılmaz ve yakıt tabancası statik elektriğe karşı dikkatle tutulur',
      'İkmal sırasında motor çalışır bırakılırsa yakıt daha hızlı alınır',
      'Yakıt yere ya da araca taşsa bile önemli değildir, silmeye gerek yoktur',
    ],
    answerIndex: 1,
    explanation:
      'Yakıt buharı kolay tutuşur; bu yüzden ikmal sırasında motor durdurulur, kontak kapatılır, sigara içilmez ve her türlü açık ateşten uzak durulur. Statik elektrik kıvılcımı da tutuşmaya yol açabileceğinden yakıt tabancası dikkatle tutulur ve telefonla oyalanmaktan kaçınılır. Taşan yakıt hem yangın hem çevre riski olduğundan temizlenir.',
    whyWrong: [
      'Motor çalışırken ve sigara içilirken ikmal, doğrudan yangın ve patlama riski yaratır.',
      'Motorun çalışır olmasının yakıt alım hızıyla ilgisi yoktur; yalnızca tehlike üretir.',
      'Taşan yakıt yangın ve çevre kirliliği riski taşır; mutlaka temizlenmelidir.',
    ],
    objective: 'Yakıt ikmalinde motor kapalı ve ateşsiz güvenlik kurallarını kavramak.',
    tags: ['yakit-ikmali', 'yangin-guvenligi', 'motor-kapali'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-726',
    subject: 'pratik',
    topic: 'lastik-gozle-kontrol',
    difficulty: 'zor',
    stem: 'Sürüş öncesi lastiklerin gözle kontrolünde nelere bakılmalıdır?',
    options: [
      'Yalnızca lastiğin markasına ve modeline bakmak yeterlidir',
      'Lastiğin rengi solmuş mu diye bakmak en önemli kontroldür',
      'Yalnızca ön lastikler kontrol edilir; arka lastikler önemsizdir',
      'Diş (sırt) derinliğinin yeterli olup olmadığı, yanaklarda çatlak ya da şişkinlik bulunup bulunmadığı, saplanmış yabancı cisim (çivi vb.) olup olmadığı ve gözle belli olan iniklik (düşük basınç) kontrol edilir; dört lastik de gözden geçirilir',
    ],
    answerIndex: 3,
    explanation:
      'Lastiğin gözle kontrolü birkaç noktada toplanır: sırt (diş) derinliği yeterli mi, yanaklarda çatlak ya da balon gibi şişkinlik var mı, sırtına çivi benzeri bir cisim saplanmış mı ve lastik gözle belli olacak kadar inik mi. Bu belirtiler yol tutuşunu ve patlama riskini doğrudan etkiler. Kontrol yalnız ön değil, dört lastiği de kapsamalıdır.',
    whyWrong: [
      'Marka ve model, lastiğin o anki güvenliği hakkında bilgi vermez.',
      'Lastiğin rengi bir güvenlik ölçütü değildir; diş, yanak ve basınç önemlidir.',
      'Arka lastikler de yol tutuşu ve güvenlik için kritiktir; yalnız önü kontrol etmek eksiktir.',
    ],
    objective:
      'Lastikte diş derinliği, yanak, yabancı cisim ve basıncı gözle kontrol etmeyi öğrenmek.',
    tags: ['lastik-kontrol', 'dis-derinligi', 'surus-oncesi-kontrol'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-727',
    subject: 'pratik',
    topic: 'cam-ayna-gorus-temiz',
    difficulty: 'kolay',
    stem: 'Sürüşe başlamadan önce görüşü açık tutmak için camlar ve aynalarla ilgili ne yapılmalıdır?',
    options: [
      'Ön cam, arka cam ve aynalar temiz ve buğusuz olmalı; kar, buz veya çiy varsa tamamen temizlenmeli, cam yıkama suyu yeterli olmalı ve gerekirse buğu giderici (defrost) çalıştırılmalıdır',
      'Yalnızca sürücünün önündeki küçük bir alanın açılması yeterlidir',
      'Buğulu camla sürüşe başlanabilir; cam nasılsa yolda kendiliğinden açılır',
      'Aynaların kirli olması görüşü etkilemez',
    ],
    answerIndex: 0,
    explanation:
      'Güvenli sürüş açık bir görüşle başlar: ön cam, arka cam ve tüm aynalar temiz ve buğusuz olmalıdır. Kar, buz ya da çiy varsa camın tamamı temizlenir; yalnız küçük bir alan açmak yan ve arka görüşü kapalı bırakır. Cam yıkama suyunun yeterli olması ve gerektiğinde buğu gidericinin çalıştırılması, yolda görüşün bozulmasını önler.',
    whyWrong: [
      'Yalnız küçük bir alanı açmak, yan ve arka görüşü kapalı bırakarak tehlike yaratır.',
      'Buğulu camla yola çıkmak, görüşü en zayıf anda hareket etmek demektir.',
      'Kirli aynalar arkadaki ve yandaki trafiği net göstermez; görüşü doğrudan bozar.',
    ],
    objective: 'Sürüş öncesi cam ve ayna temizliği ile buğu yönetimini uygulamak.',
    tags: ['cam-temizligi', 'bugulanma', 'gorus'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-728',
    subject: 'pratik',
    topic: 'bakis-uzak-ileri',
    difficulty: 'orta',
    stem: 'Düz yolda seyir sırasında bakış nereye yöneltilmelidir?',
    options: [
      'Sürekli olarak aracın hemen önündeki asfalta bakılır',
      'Bakış yalnızca hız göstergesinde tutulur',
      'Bakış olabildiğince ileriye taşınıp yolun genişçe bir kesiti taranır; uzağı görmek tehlikeleri erken fark ettirir ve şeritte salınmadan gitmeyi kolaylaştırır, arada aynalar ve göstergeler de kontrol edilir',
      'Gözler kapatılıp yalnız direksiyon hissiyle sürülür',
    ],
    answerIndex: 2,
    explanation:
      'Bakışı olabildiğince ileriye taşımak, tehlikeleri henüz uzaktayken fark ettirir ve tepki için zaman kazandırır. Uzağa bakan sürücü aracını şeridin ortasında daha kararlı tutar, çünkü küçük yön düzeltmeleri erkenden yapılır. İleri bakış esas alınırken aynalar ve göstergeler de göz ucuyla ara ara taranır. Yalnız yakına bakmak ise geç tepkiye ve salınmaya yol açar.',
    whyWrong: [
      'Hemen öne bakmak, tehlikeyi geç fark ettirir ve araç şeritte salınır.',
      'Yalnız hız göstergesine bakmak, yolu ve trafiği tümüyle gözden kaçırır.',
      'Gözleri kapatmak, sürüşü tümüyle imkânsız ve tehlikeli kılar.',
    ],
    objective: 'Düz yolda bakışı ileriye taşıyıp geniş tarama alışkanlığını kazanmak.',
    tags: ['bakis-teknigi', 'uzak-bakis', 'serit-takibi'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-729',
    subject: 'pratik',
    topic: 'ayna-tarama-aliskanlik',
    difficulty: 'orta',
    stem: 'Sürüş boyunca aynaların kullanımıyla ilgili doğru alışkanlık nedir?',
    options: [
      'Aynalara yalnızca sürüşün başında bir kez bakmak yeterlidir',
      'Aynalar düzenli aralıklarla (birkaç saniyede bir) ve özellikle şerit değiştirme, dönüş, yavaşlama ile fren öncesinde taranır; böylece arkadaki ve yandaki trafik sürekli bilinir',
      'Aynalara yalnızca geri manevra yaparken bakılır',
      'Aynalar dikkati dağıttığı için mümkün olduğunca az kullanılır',
    ],
    answerIndex: 1,
    explanation:
      'Ayna kullanımı bir alışkanlık hâline gelmelidir: aynalar düzenli aralıklarla, birkaç saniyede bir taranır ve özellikle şerit değiştirme, dönüş, yavaşlama ile fren öncesinde mutlaka kontrol edilir. Bu düzenli tarama, arkadan ve yandan gelen trafiğin sürekli bilinmesini sağlar. Ayna kontrolü bir kerelik değil, sürekli bir gözlem alışkanlığıdır.',
    whyWrong: [
      'Sürüşün başında bir kez bakmak, trafiğin sürekli değiştiği yolda güncel bilgi vermez.',
      'Yalnız geri manevrada bakmak, seyir hâlindeki arka ve yan trafiği gözden kaçırır.',
      'Aynaları az kullanmak, arkadaki tehlikeyi bilmeden karar vermeye yol açar.',
    ],
    objective: 'Sürüş boyunca düzenli ayna tarama alışkanlığını benimsemek.',
    tags: ['ayna-tarama', 'gozlem', 'aliskanlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-730',
    subject: 'pratik',
    topic: 'kapi-kemer-son-kontrol',
    difficulty: 'orta',
    stem: 'Hazırlık tamamlandıktan sonra harekete geçmeden hemen önce yapılacak son kontrol nedir?',
    options: [
      'Yalnızca sürücünün kemeri takılıysa yola çıkılır; yolcular kendi sorumluluğundadır',
      'Kapılardan biri tam kapanmasa da hareket edilebilir',
      'Son kontrol gereksizdir; hazırlık bitince doğrudan hareket edilir',
      'Tüm kapıların tam kapalı olduğu, sürücü dâhil bütün yolcuların emniyet kemerini taktığı, el freninin kalkışta indirileceği ve vitesin doğru konumda olduğu son bir kez gözden geçirilir',
    ],
    answerIndex: 3,
    explanation:
      'Kalkıştan hemen önce kısa bir son kontrol, unutulan bir ayrıntıyı yakalar: tüm kapılar tam kapalı mı, sürücü dâhil herkes kemerini takmış mı, el freni ve vites kalkışa hazır mı. Bu gözden geçirme, hareket hâlinde açılan bir kapı ya da takılmamış bir kemer gibi tehlikeleri baştan önler. Kısa sürer ama güvenli bir başlangıcın güvencesidir.',
    whyWrong: [
      'Yalnız sürücünün kemeri yetmez; sürücü dâhil tüm yolcular kemer takmalıdır.',
      'Tam kapanmamış bir kapı, hareket hâlinde açılıp ciddi tehlike yaratabilir.',
      'Son kontrolü atlamak, eksik ya da güvensiz bir kalkışa yol açabilir.',
    ],
    objective: 'Kalkış öncesi kapı-kemer-el freni-vites son kontrolünü uygulamak.',
    tags: ['son-kontrol', 'kapi-kemer', 'kalkis-oncesi'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
];
