/**
 * ÖZGÜN trafik adabı soruları — 2. genişletme (Program 1). ROADMAP C.4/E.6.
 * Kaynak = MEB Trafik Adabı müfredatı; KENDİ İFADEMİZLE.
 */
import type { QuestionInput } from '@ea/content-schema';

const SRC = 'MEB Trafik Adabı müfredatı (özgün ifade)';

export const ADAB_QUESTIONS_2: QuestionInput[] = [
  {
    id: 'adab-201',
    subject: 'adab',
    topic: 'hiz-adabi',
    difficulty: 'kolay',
    stem: 'Çocukların oyun oynadığı dar bir sokağa girdiniz. Hız adabı açısından en doğru davranış hangisidir?',
    options: [
      'Adım hızına inip her an durmaya hazır şekilde ilerlemek',
      'Normal şehir hızını koruyup dikkatli bakmak',
      'Çocuklar kenara çekilsin diye korna çalmak',
      'Bölgeyi çabucak terk etmek için hızlanmak',
    ],
    answerIndex: 0,
    explanation:
      'Çocuklar ani ve öngörülemez hareket edebilir; oyun alanı çevresinde adım hızına inip her an durabilecek şekilde ilerlemek hem hız adabının hem de can güvenliğinin gereğidir.',
    whyWrong: [
      'Normal hızı korumak, aniden çıkan bir çocuğa tepki verecek mesafeyi bırakmaz.',
      'Kornayla acele ettirmek veya hızlanmak çocukları doğrudan tehlikeye atar.',
    ],
    objective: 'Yaya ve çocuk yoğun bölgelerde hızı koşullara göre düşürmeyi kavramak.',
    tags: ['hiz-adabi', 'cocuk-guvenligi', 'yavaslama'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-202',
    subject: 'adab',
    topic: 'korna-kullanimi',
    difficulty: 'kolay',
    stem: 'Hastane ve okulların bulunduğu bir caddede ilerliyorsunuz. Korna kullanımı konusunda hangisi doğrudur?',
    options: [
      'Trafik yavaş diye sabırsızlıkla korna çalmak',
      'Tanıdıkları selamlamak için korna çalmak',
      'Öndeki araç yavaş kalkınca uzun korna çalmak',
      'Yalnızca gerçek bir tehlikeyi haber vermek için kısa korna kullanmak',
    ],
    answerIndex: 3,
    explanation:
      'Korna bir sabırsızlık ya da selamlaşma aracı değil, tehlikeyi önlemek için kullanılan bir uyarı düzeneğidir; hastane çevresi gibi hassas yerlerde gereksiz korna insanları rahatsız eder.',
    whyWrong: [
      'Sabırsızlık veya selamlaşma için korna çalmak gürültü kirliliği yaratır.',
      'Öndeki araca uzun korna çalmak baskı kurmak ve saygısızlıktır.',
    ],
    objective: 'Kornanın yalnızca tehlike uyarısı amacıyla kullanılacağını benimsemek.',
    tags: ['korna-kullanimi', 'cevre', 'nezaket'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-203',
    subject: 'adab',
    topic: 'selektor',
    difficulty: 'orta',
    stem: 'Gündüz otoyolda sol şeritte ilerlerken arkanızdaki sürücü sürekli selektör yapıp sizi sıkıştırıyor. Doğru tutumunuz ne olmalı?',
    options: [
      'Aynı şekilde selektör yapıp tepki göstermek',
      'İnadına hızınızı düşürüp yavaşlamak',
      'Güvenli olduğunda sağ şeride geçip yol vermek',
      'Frene basıp arkadaki sürücüyü korkutmak',
    ],
    answerIndex: 2,
    explanation:
      'Sol şerit sürekli seyir için değil sollama içindir; işiniz bitince güvenli biçimde sağa geçip yol vermek hem kurala hem trafik adabına uygundur ve arkadakinin hatasını büyütmeden çözer.',
    whyWrong: [
      'Karşılık olarak selektör yapmak yalnızca gerginliği tırmandırır.',
      'İnadına yavaşlamak veya ani fren yapmak tehlikeli bir öfke tepkisidir.',
    ],
    objective:
      'Sol şeridi boşaltıp hızlı gelen araca yol vermeyi ve provokasyona kapılmamayı öğrenmek.',
    tags: ['selektor', 'hosgoru', 'serit-kullanimi'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-204',
    subject: 'adab',
    topic: 'yasli-saygi',
    difficulty: 'kolay',
    stem: 'Yaya geçidinden yavaş adımlarla geçen yaşlı bir yaya, siz beklerken henüz karşıya ulaşamadı. Ne yaparsınız?',
    options: [
      'Yaklaşıp yavaşça geçmesi için baskı yapmak',
      'Sabırla bekleyip güvenle karşıya geçmesini sağlamak',
      'Korna çalarak acele etmesini istemek',
    ],
    answerIndex: 1,
    explanation:
      'Yaşlı yayalar daha yavaş hareket eder ve aceleye getirildiğinde dengesini kaybedebilir; sabırla beklemek yaşa gösterilen saygının ve güvenliğin bir gereğidir.',
    whyWrong: [
      'Baskı yapmak veya korna çalmak yaşlı yayayı telaşlandırıp düşürebilir.',
      'Aceleye getirmek denge kaybı ve kaza riski doğurur.',
    ],
    objective: 'Yaşlı yayalara ek sabır ve saygı göstermeyi içselleştirmek.',
    tags: ['yasli-saygi', 'sabir', 'yaya-gecidi'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-205',
    subject: 'adab',
    topic: 'engelli-saygi',
    difficulty: 'kolay',
    stem: 'Otoparkta yalnızca engelli aracı için ayrılmış boş bir yer var ve siz aceledesiniz. Doğru davranış hangisidir?',
    options: [
      'Boş olsa da oraya park etmeyip başka yer aramak',
      'Kısa süre kalacağım diye oraya park etmek',
      'Aracı bırakıp hızlıca işimi görmek',
      'Dörtlüleri yakıp engelli yerine park etmek',
    ],
    answerIndex: 0,
    explanation:
      'Engelli park yeri, hareket kısıtlılığı olan bireylerin araçlarına rahat inip binebilmesi için ayrılmıştır; boş olsa bile oraya park etmemek engelli bireylerin hakkına saygının açık göstergesidir.',
    whyWrong: [
      'Kısa süre bile olsa oraya park etmek, o an gelen bir engelli bireyi mağdur edebilir.',
      'Dörtlü yakmak veya acele etmek kuralı ihlal etmeyi meşru kılmaz.',
    ],
    objective: 'Engelli bireylere ayrılmış alanlara saygı göstermeyi ilke edinmek.',
    tags: ['engelli-saygi', 'park', 'sorumluluk'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-206',
    subject: 'adab',
    topic: 'cocuk-guvenligi',
    difficulty: 'orta',
    stem: 'Yol kenarında oynayan çocukların topu aniden önünüzdeki yola yuvarlandı. En doğru tepki nedir?',
    options: [
      'Topa aldırmadan hızla geçmek',
      'Korna çalıp çocukları uzak tutmaya çalışmak',
      'Hemen yavaşlayıp durmaya hazırlanmak, çünkü topun peşinden çocuk gelebilir',
      'Topu ezmemek için ani şerit değiştirmek',
    ],
    answerIndex: 2,
    explanation:
      'Yola kaçan bir topun ardından çoğu zaman onu almak için koşan bir çocuk gelir; hız kesip durmaya hazır olmak öngörülü sürüşün ve çocuk güvenliğinin temel kuralıdır.',
    whyWrong: [
      'Hızla geçmek, topun peşinden çıkabilecek çocuğa çarpma riski doğurur.',
      'Ani şerit değiştirmek yan trafikle çarpışmaya yol açabilir.',
    ],
    objective: 'Çocukların bulunduğu ortamda tehlikeyi önceden okuyup hız kesmeyi kavramak.',
    tags: ['cocuk-guvenligi', 'hiz-adabi', 'ongoru'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-207',
    subject: 'adab',
    topic: 'ambulans',
    difficulty: 'orta',
    stem: 'Yoğun trafikte önünüzden sirenli bir ambulans geçip yolu açtı. Trafiği aşmak için ambulansın hemen arkasına takılmak doğru mudur?',
    options: [
      'Evet, açılan yoldan hızlıca ilerlemek gerekir',
      'Evet, ambulans nasılsa yolu açıyor',
      'Sadece çok acelem varsa takılabilirim',
      'Hayır, ambulansın arkasına takılmak izinsiz geçiş üstünlüğü kullanmaktır ve tehlikelidir',
    ],
    answerIndex: 3,
    explanation:
      'Ambulansa yol açan sürücüler yeniden şeride dönerken arkasına takılan aracı beklemez; bu davranış hem yasa dışı geçiş üstünlüğü kullanımı hem de ciddi bir kaza riskidir.',
    whyWrong: [
      'Açılan yolu kendi çıkarına kullanmak, yol veren sürücüleri tehlikeye atar.',
      'Acele, geçiş üstünlüğü olmayan bir aracın öncelik kullanmasını haklı çıkarmaz.',
    ],
    objective:
      'Geçiş üstünlüğü olan aracın arkasına takılmanın kural dışı ve tehlikeli olduğunu kavramak.',
    tags: ['ambulans', 'gecis-ustunlugu', 'sorumluluk'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-208',
    subject: 'adab',
    topic: 'sabir',
    difficulty: 'orta',
    stem: 'Dolu bir otoparkta önünüzdeki sürücü, çıkmak üzere olan bir aracın boşaltacağı yeri bekliyor ve yolu kapatıyor. Sabırlı bir sürücü ne yapar?',
    options: [
      'Korna çalıp öndeki sürücüyü sıkıştırmak',
      'Kısa süre bekleyip sıranın açılmasına anlayış göstermek',
      'Yandan sıkışıp o yeri kapmaya çalışmak',
      'Camı açıp yüksek sesle çıkışmak',
    ],
    answerIndex: 1,
    explanation:
      'Otoparkta yer beklemek herkesin başına gelebilecek kısa bir gecikmedir; birkaç saniye sabretmek gereksiz gerginliği önler ve nazik bir sürüş kültürünü besler.',
    whyWrong: [
      'Kornayla sıkıştırmak veya bağırmak gerilimi artırır.',
      'Bekleyenin yerini kapmak haksızlıktır ve tartışmaya yol açar.',
    ],
    objective: 'Otopark gibi dar alanlarda sabır ve anlayışla hareket etmeyi öğrenmek.',
    tags: ['sabir', 'otopark', 'nezaket'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-209',
    subject: 'adab',
    topic: 'empati',
    difficulty: 'orta',
    stem: 'Önünüzdeki yabancı plakalı araç, yolu bilmediği için kavşakta tereddüt edip yavaşlıyor. Empatik yaklaşım hangisidir?',
    options: [
      'Anlayışla mesafe bırakıp yönünü bulmasına fırsat vermek',
      'Arkasından korna çalıp acele ettirmek',
      'Yanına sokulup el kol hareketiyle azarlamak',
      'Sıkıştırıp geçişe zorlamak',
    ],
    answerIndex: 0,
    explanation:
      'Yolu bilmeyen bir sürücünün duraksaması anlaşılabilir bir durumdur; onun yerine kendinizi koyup mesafe bırakmak hem güvenli hem de hoşgörülü bir davranıştır.',
    whyWrong: [
      'Korna ve sıkıştırma, tereddütteki sürücüyü daha çok şaşırtıp hata yaptırır.',
      'Azarlamak dikkat dağıtır ve gereksiz gerginlik yaratır.',
    ],
    objective: 'Yol bilmeyen veya duraksayan sürücülere empatiyle yaklaşmayı geliştirmek.',
    tags: ['empati', 'hosgoru', 'kavsak'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-210',
    subject: 'adab',
    topic: 'ofke',
    difficulty: 'orta',
    stem: 'Girmek üzere olduğunuz boş park yerini başka bir sürücü aniden önünüze geçip kaptı. Öfke kontrolü açısından en doğru davranış nedir?',
    options: [
      'Aracın önünü kesip yerini bırakmasını istemek',
      'Camı açıp bağırarak tepki göstermek',
      'Sinirlenmeden başka bir yer arayıp sükunetinizi korumak',
      'Aracına yaklaşıp korkutucu manevralar yapmak',
    ],
    answerIndex: 2,
    explanation:
      'Bir park yeri, öfkelenip çatışmaya girmeye değmeyecek kadar küçük bir meseledir; sakin kalıp başka yer aramak hem zamanınızı hem huzurunuzu korur.',
    whyWrong: [
      'Önünü kesmek veya bağırmak kolayca kavgaya dönüşebilir.',
      'Korkutucu manevralar hem tehlikeli hem de yasa dışıdır.',
    ],
    objective: 'Küçük haksızlıklar karşısında öfkeyi kontrol edip çatışmadan kaçınmayı kavramak.',
    tags: ['ofke', 'sakinlik', 'otopark'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-211',
    subject: 'adab',
    topic: 'nezaket',
    difficulty: 'kolay',
    stem: 'Dar bir geçitte karşıdan gelen sürücü size yol verip beklemenizi sağladı ve rahatça geçtiniz. En uygun davranış hangisidir?',
    options: [
      'Hiçbir tepki vermeden yola devam etmek',
      'Kornaya basıp geçtiğinizi belirtmek',
      'Hızlanıp hızla uzaklaşmak',
      'El kaldırarak ya da baş sallayarak teşekkür etmek',
    ],
    answerIndex: 3,
    explanation:
      'Size gösterilen bir inceliğe kısa bir teşekkür işaretiyle karşılık vermek, trafikte olumlu ve nazik bir iletişim kültürünü güçlendirir.',
    whyWrong: [
      'Karşılık vermemek, gösterilen jesti görmezden gelmektir.',
      'Korna, teşekkür yerine rahatsızlık izlenimi verebilir.',
    ],
    objective: 'Yol veren sürücülere teşekkür işaretiyle nezaket göstermeyi öğrenmek.',
    tags: ['nezaket', 'iletisim', 'tesekkur'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-212',
    subject: 'adab',
    topic: 'hosgoru',
    difficulty: 'orta',
    stem: 'Şehirlerarası bir yolda önünüzde yavaş ilerleyen bir traktör var ve sollama için uygun yer henüz yok. Hoşgörülü sürücü nasıl davranır?',
    options: [
      'Dip mesafeye girip korna çalarak baskı yapmak',
      'Takip mesafesini koruyup güvenli sollama yeri gelene kadar sabretmek',
      'Görüş kapalıyken zorla sollamaya kalkmak',
      'Selektör yapıp traktörü kenara çekmeye zorlamak',
    ],
    answerIndex: 1,
    explanation:
      'Tarım araçları da yolu kullanma hakkına sahiptir; güvenli sollama fırsatı doğana kadar mesafe koruyup sabretmek hem hoşgörünün hem de kaza önlemenin gereğidir.',
    whyWrong: [
      'Baskı yapmak veya kör noktada sollamaya kalkmak ölümcül kazalara yol açar.',
      'Selektörle zorlamak, traktör sürücüsünü tehlikeli bir manevraya itebilir.',
    ],
    objective: 'Yavaş seyreden araçlara hoşgörü gösterip güvenli sollamayı beklemeyi kavramak.',
    tags: ['hosgoru', 'sollama', 'sabir'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-213',
    subject: 'adab',
    topic: 'saygi',
    difficulty: 'orta',
    stem: 'Aracınızı park ederken tam bir evin garaj çıkışının önüne denk geliyorsunuz. Saygılı bir sürücü ne yapar?',
    options: [
      'Kısa süre kalacağım diye çıkışı kapatıp park etmek',
      'Çıkışı kısmen kapatıp öylece bırakmak',
      'Garaj çıkışını kapatmayacak uygun bir yere park etmek',
      'Not bırakıp çıkışın önüne park etmek',
    ],
    answerIndex: 2,
    explanation:
      'Bir garaj veya bahçe çıkışını kapatmak, o evin sahibinin aracını kullanamamasına yol açar; başkasının hakkını gözetip uygun bir yere park etmek trafik adabının gereğidir.',
    whyWrong: [
      'Kısa süre bile olsa çıkışı kapatmak ev sahibini mağdur edebilir.',
      'Not bırakmak, çıkışı kapatmanın doğurduğu sıkıntıyı ortadan kaldırmaz.',
    ],
    objective: 'Park ederken başkalarının geçiş ve çıkış hakkını gözetmeyi benimsemek.',
    tags: ['saygi', 'park', 'sorumluluk'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-214',
    subject: 'adab',
    topic: 'paylasim',
    difficulty: 'orta',
    stem: 'İki şeridin tek şeride düştüğü bir daralmada araçlar birleşmek zorunda. Yol paylaşımı açısından en doğru yöntem hangisidir?',
    options: [
      'Sırayla, birer birer geçerek fermuar sistemiyle katılmak',
      'Boşluk bırakmayıp kimseyi araya almamak',
      'Zorla öne geçmeye çalışıp sıkıştırmak',
      'Korna çalıp diğerlerini durdurmaya çalışmak',
    ],
    answerIndex: 0,
    explanation:
      'Şerit daralmalarında araçların sırayla, birer birer katıldığı fermuar sistemi trafiği en akıcı ve adil biçimde ilerletir; karşılıklı özveri tıkanmayı önler.',
    whyWrong: [
      'Boşluk bırakmamak ve zorla öne geçmek tıkanıklığı ve sürtüşmeyi artırır.',
      'Kornayla baskı kurmak düzeni değil kaosu besler.',
    ],
    objective: 'Şerit daralmalarında sıra ve paylaşım ilkesiyle (fermuar) hareket etmeyi öğrenmek.',
    tags: ['paylasim', 'serit-birlesme', 'ozveri'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-215',
    subject: 'adab',
    topic: 'sorumluluk',
    difficulty: 'orta',
    stem: 'Uzun bir yolculuğun sonunda göz kapaklarınız ağırlaşıyor ve dikkatiniz dağılıyor. Sorumlu bir sürücü ne yapar?',
    options: [
      'Pencereyi açıp yola devam etmek yeterlidir',
      'Daha hızlı gidip bir an önce varmaya çalışmak',
      'Güvenli bir yerde durup dinlenmek ya da mola vermek',
      'Yüksek sesle müzik açıp uyanık kalmaya çalışmak',
    ],
    answerIndex: 2,
    explanation:
      'Uykulu sürüş, alkollü sürüş kadar tehlikelidir çünkü tepki süresini ve dikkati ciddi biçimde düşürür; güvenli bir yerde durup dinlenmek hayat kurtaran sorumlu bir karardır.',
    whyWrong: [
      'Pencere açmak veya müzik uykuyu yalnızca kısa süre erteler, çözmez.',
      'Hızlanmak, yorgunlukla birleşince kaza riskini katlar.',
    ],
    objective: 'Yorgunluk ve uykululuk halinde sürüşü bırakıp dinlenmenin sorumluluğunu kavramak.',
    tags: ['sorumluluk', 'yorgunluk', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-216',
    subject: 'adab',
    topic: 'iletisim',
    difficulty: 'orta',
    stem: 'Şerit değiştirmek veya dönüş yapmak üzeresiniz. Diğer sürücülerle sağlıklı iletişim için ne yapmalısınız?',
    options: [
      'Niyetinizi belli etmeden ani manevra yapmak',
      'Manevradan yeterince önce sinyal (dönüş lambası) vermek',
      'Sadece ayna kontrolü yapıp sinyal vermemek',
      'Manevra bittikten sonra sinyal vermek',
    ],
    answerIndex: 1,
    explanation:
      'Dönüş sinyali, diğer sürücülere niyetinizi önceden bildiren en temel iletişim aracıdır; manevradan yeterince önce verilen sinyal herkesin güvenle konumlanmasını sağlar.',
    whyWrong: [
      'Sinyalsiz ani manevra, çevredeki sürücüleri hazırlıksız yakalayıp kazaya yol açar.',
      'Manevra bitince verilen sinyalin uyarı değeri kalmaz.',
    ],
    objective: 'Manevra niyetini zamanında sinyalle bildirerek güvenli iletişim kurmayı kavramak.',
    tags: ['iletisim', 'sinyal', 'serit-degistirme'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-217',
    subject: 'adab',
    topic: 'stres',
    difficulty: 'orta',
    stem: 'Arkanızdaki sürücü size çok yaklaşıp korna ve selektörle baskı yaparak sizi gerginleştiriyor. Stresi yönetmenin en doğru yolu nedir?',
    options: [
      'Ani fren yaparak ona ders vermek',
      'Gerilip hızınızı gereksiz yere artırmak',
      'Aynı şekilde tepki gösterip inatlaşmak',
      'Sakin kalıp güvenli olduğunda yol vererek uzaklaşmasını sağlamak',
    ],
    answerIndex: 3,
    explanation:
      'Arkadan baskı yapan agresif bir sürücüye kapılmak sizin sürüşünüzü de tehlikeye atar; sakinliğinizi koruyup uygun yerde yol vermek gerilimi sizden uzaklaştıran en güvenli yoldur.',
    whyWrong: [
      'Ani fren yapmak arkadan çarpışmaya davetiye çıkarır.',
      'Gerilip hızlanmak veya inatlaşmak stresi ve riski büyütür.',
    ],
    objective: 'Arkadan gelen baskı karşısında sakin kalıp güvenli davranmayı öğrenmek.',
    tags: ['stres', 'ofke', 'yol-verme'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-218',
    subject: 'adab',
    topic: 'hiz-adabi',
    difficulty: 'zor',
    stem: 'Yağmur nedeniyle yol ıslak ve görüş azaldı, ancak hız sınırı levhası kuru hava değerini gösteriyor. Hız adabı açısından ne yaparsınız?',
    options: [
      'Yol ve hava koşullarına göre sınırın altında, daha yavaş sürmek',
      'Levhadaki sınıra kadar hızlanmak serbesttir',
      'Trafik akışına uymak için hızlı gitmek',
      'Görüş azaldığı için farları kapatıp yavaşlamak',
    ],
    answerIndex: 0,
    explanation:
      'Hız sınırı, ideal koşullardaki üst sınırdır; ıslak zeminde fren mesafesi uzar ve görüş azalır, bu yüzden koşullara göre sınırın altında sürmek hız adabının ve güvenliğin gereğidir.',
    whyWrong: [
      'Kötü havada bile azami sınıra çıkmak kayma ve çarpışma riskini artırır.',
      'Farları kapatmak görüşü daha da azaltır; doğru olan yavaşlamaktır.',
    ],
    objective: 'Hız sınırının koşullara göre uyarlanması gerektiğini kavramak.',
    tags: ['hiz-adabi', 'yagmur', 'guvenli-surus'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-219',
    subject: 'adab',
    topic: 'korna-kullanimi',
    difficulty: 'orta',
    stem: 'Bir düğün konvoyunda ya da trafikte tanıdığınızı görünce uzun uzun korna çalmak isteyebilirsiniz. Bu konuda doğru tutum hangisidir?',
    options: [
      'Kutlama için istediğim kadar korna çalabilirim',
      'Tanıdıkları selamlamak için sık korna çalmak uygundur',
      'Kornayı yalnızca tehlike anında kullanıp gereksiz gürültüden kaçınmak',
      'Trafik yoğunsa korna çalarak dikkat çekmek gerekir',
    ],
    answerIndex: 2,
    explanation:
      'Korna bir kutlama veya selamlaşma aracı değildir; gereksiz ve sürekli korna çevredeki insanları rahatsız eden gürültü kirliliği yaratır, bu yüzden yalnızca tehlike uyarısı için kullanılmalıdır.',
    whyWrong: [
      'Kutlama veya selamlaşma amaçlı korna gürültü kirliliğine yol açar.',
      'Yoğun trafikte korna çalmak akışı değiştirmez, yalnızca gerginlik yaratır.',
    ],
    objective:
      'Kornanın kutlama veya selamlaşma için değil yalnızca uyarı için kullanılacağını benimsemek.',
    tags: ['korna-kullanimi', 'cevre', 'saygi'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-220',
    subject: 'adab',
    topic: 'selektor',
    difficulty: 'orta',
    stem: 'Trafikte önünüzdeki araç sizce yavaş gidiyor ve sabırsızlanıyorsunuz. Selektörü nasıl kullanmak doğrudur?',
    options: [
      'Öndeki hızlansın diye sürekli selektör yapmak',
      'Selektörü baskı aracı olarak değil, yalnızca gerektiğinde nazik uyarı için kullanmak',
      'Selektörle birlikte korna çalıp iyice baskı yapmak',
      'Dip mesafeye girip selektörle sıkıştırmak',
    ],
    answerIndex: 1,
    explanation:
      'Selektör, öndeki sürücüyü sıkıştırmak veya cezalandırmak için değil; sollama niyetini bildirmek ya da bir tehlikeyi haber vermek gibi durumlarda nazikçe kullanılan bir işaret aracıdır.',
    whyWrong: [
      'Sürekli selektörle baskı yapmak saldırganlıktır ve öndeki sürücüyü tedirgin eder.',
      'Korna ve dip mesafeyle birleşen selektör tehlikeli bir sıkıştırmaya dönüşür.',
    ],
    objective: 'Selektörü baskı değil, ölçülü bir iletişim aracı olarak kullanmayı kavramak.',
    tags: ['selektor', 'iletisim', 'ofke'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-221',
    subject: 'adab',
    topic: 'yasli-saygi',
    difficulty: 'orta',
    stem: 'Önünüzdeki durakta yaşlı bir yolcu otobüse binmekte zorlanıyor ve otobüs bir süre bekliyor. Trafik adabına uygun davranış nedir?',
    options: [
      'Korna çalıp otobüsün kalkmasını beklemek',
      'Tehlikeli şekilde solundan geçip acele etmek',
      'Sabırla bekleyip yaşlı yolcunun rahatça binmesine anlayış göstermek',
      'Otobüsün önünü kesip durdurmak',
    ],
    answerIndex: 2,
    explanation:
      'Yaşlı yolcuların binip inmesi biraz zaman alabilir; bu kısa gecikmeyi sabırla karşılamak, yaşa duyulan saygının ve toplumsal nezaketin bir yansımasıdır.',
    whyWrong: [
      'Korna çalmak veya önünü kesmek yaşlı yolcuyu telaşlandırır ve tehlike yaratır.',
      'Otobüsün solundan tehlikeli geçiş, durakta inen yolcular için risklidir.',
    ],
    objective: 'Yaşlı yolcuların bulunduğu duraklarda sabır ve saygı göstermeyi kavramak.',
    tags: ['yasli-saygi', 'sabir', 'durak'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-222',
    subject: 'adab',
    topic: 'engelli-saygi',
    difficulty: 'kolay',
    stem: 'Kaldırımdaki engelli rampasının tam önünde kısa bir işiniz için durmak istiyorsunuz. Doğru davranış hangisidir?',
    options: [
      'Kısa süre kalacağım için rampanın önüne durmak',
      'Rampanın yarısını kapatacak şekilde durmak',
      'Dörtlüleri yakıp rampanın önünde beklemek',
      'Rampayı kapatmadan, tekerlekli sandalye geçişini engellemeyecek bir yere durmak',
    ],
    answerIndex: 3,
    explanation:
      'Engelli rampaları, tekerlekli sandalye kullananların kaldırıma çıkabilmesi için hayati öneme sahiptir; rampayı kapatmamak engelli bireylerin bağımsız hareketine gösterilen saygının gereğidir.',
    whyWrong: [
      'Kısa süre bile rampayı kapatmak, o an gelen bir engelli bireyin geçişini imkânsız kılar.',
      'Dörtlü yakmak rampayı kapatmayı meşru hale getirmez.',
    ],
    objective:
      'Engelli rampalarını açık tutarak engelli bireylerin erişimine saygı göstermeyi benimsemek.',
    tags: ['engelli-saygi', 'kaldirim', 'park'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-223',
    subject: 'adab',
    topic: 'cocuk-guvenligi',
    difficulty: 'kolay',
    stem: 'Aracınızda küçük bir çocuk yolculuk edecek. Sorumlu ve adaba uygun davranış hangisidir?',
    options: [
      'Çocuğu yaşına ve boyuna uygun oto koltuğunda ve kemerli oturtmak',
      'Çocuğu kucakta taşımak yeterlidir',
      'Kısa yolda kemer takmaya gerek yoktur',
      'Arka koltukta kemersiz oturması sorun değildir',
    ],
    answerIndex: 0,
    explanation:
      'Çocuklar, yetişkin emniyet kemeri ve normal koltuk için fazla küçüktür; yaşına uygun oto koltuğu ve kemer, olası bir kazada onları ciddi yaralanmadan koruyan en önemli tedbirdir.',
    whyWrong: [
      'Kucakta taşıma, ani frende çocuğun savrulmasına yol açar.',
      'Kısa yol da olsa kemersiz yolculuk hayati risk taşır.',
    ],
    objective: 'Çocukların uygun koruma sistemiyle taşınması sorumluluğunu kavramak.',
    tags: ['cocuk-guvenligi', 'emniyet-kemeri', 'sorumluluk'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-224',
    subject: 'adab',
    topic: 'ambulans',
    difficulty: 'orta',
    stem: 'Tek şeritli dar bir yolda ilerlerken arkadan sirenli bir ambulans yaklaşıyor ve sağa yanaşacak yer sınırlı. En doğru davranış nedir?',
    options: [
      'Hızlanıp ambulansın önünde geniş bir yere kadar gitmeye çalışmak',
      'Uygun ilk noktada mümkün olduğunca sağa yanaşıp gerekiyorsa durarak yol açmak',
      'Olduğunuz yerde durup ambulansın çaresini kendisinin bulmasını beklemek',
      'Ambulans geçene kadar aynı hızda ilerlemeye devam etmek',
    ],
    answerIndex: 1,
    explanation:
      'Geçiş üstünlüğü olan araca yol vermek zorunludur; dar yolda bile ilk uygun noktada sağa yanaşıp gerekirse durarak ambulansa geçiş sağlamak bir hayatı kurtarabilir.',
    whyWrong: [
      'Önünde hızlanmaya çalışmak ambulansı geciktirir ve tehlike yaratır.',
      'Rastgele durup şeridi kapatmak ya da aynı hızda gitmek geçişi engeller.',
    ],
    objective: 'Dar yolda geçiş üstünlüğü aracına ilk uygun noktada yol vermeyi kavramak.',
    tags: ['ambulans', 'gecis-ustunlugu', 'yol-verme'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-225',
    subject: 'adab',
    topic: 'empati',
    difficulty: 'zor',
    stem: 'Yolda yavaş ilerleyen bir cenaze konvoyuyla karşılaştınız. Empati ve saygı açısından en doğru davranış nedir?',
    options: [
      'Konvoyu bölerek aralarından hızla geçmek',
      'Korna çalıp konvoyun hızlanmasını beklemek',
      'Konvoyun bütünlüğünü bozmadan, saygıyla ve sabırla ilerlemek',
      'Sıkışıp konvoyun önüne geçmeye çalışmak',
    ],
    answerIndex: 2,
    explanation:
      'Cenaze konvoyu, yas tutan insanları taşır; konvoyu bölmeden sabır ve saygıyla ilerlemek, empatinin ve toplumsal duyarlılığın açık bir göstergesidir.',
    whyWrong: [
      'Konvoyun arasından geçmek hem saygısızlık hem de tehlikeli bir manevradır.',
      'Korna çalmak veya öne geçmeye çalışmak yas ortamına saygısızlıktır.',
    ],
    objective: 'Cenaze konvoyu gibi hassas durumlarda empati ve saygıyla davranmayı kavramak.',
    tags: ['empati', 'saygi', 'hosgoru'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-226',
    subject: 'adab',
    topic: 'ofke',
    difficulty: 'zor',
    stem: 'Bir kavşakta başka bir sürücü dikkatsizce önünüze girip sizi sert fren yapmaya zorladı ve öfkeniz kabardı. En olgun davranış hangisidir?',
    options: [
      'Peşine düşüp aynı şekilde önünü kesmek',
      'Yanına gelip camdan bağırarak hesap sormak',
      'Aracınızla sıkıştırıp gözünü korkutmak',
      'Uzun uzun korna çalıp arkasından kovalamak',
      'Derin bir nefes alıp öfkenizi yatıştırarak güvenli sürüşe geri dönmek',
    ],
    answerIndex: 4,
    explanation:
      'Öfkeyle verilen tepkiler muhakemeyi zayıflatıp yeni kazalara yol açar; birkaç saniye nefes alıp sakinleşmek hem sizi hem çevrenizi koruyan olgun bir tutumdur.',
    whyWrong: [
      'Peşine düşmek, önünü kesmek veya kovalamak karşılıklı bir trafik terörüne dönüşebilir.',
      'Bağırmak ve sıkıştırmak çatışmayı büyütür, çözmez.',
    ],
    objective: 'Ani kışkırtmalar karşısında öfkeyi yatıştırıp güvenli sürüşe dönmeyi kavramak.',
    tags: ['ofke', 'sakinlik', 'kavsak'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-227',
    subject: 'adab',
    topic: 'paylasim',
    difficulty: 'kolay',
    stem: 'Yerleşim yerinde durağından kalkmak için sola sinyal veren bir toplu taşıma otobüsü var. Trafik adabına uygun davranış nedir?',
    options: [
      'Hızlanıp otobüsün önünden geçmek',
      'Hızınızı azaltıp otobüsün yeniden trafiğe katılmasına yol vermek',
      'Korna çalıp otobüsün beklemesini istemek',
    ],
    answerIndex: 1,
    explanation:
      'Yerleşim yerinde durağından ayrılmak için sinyal veren toplu taşıma aracına yol vermek hem bir kural hem de yolu paylaşma adabının gereğidir.',
    whyWrong: [
      'Otobüsün önünden geçmek, onun trafiğe katılmasını zorlaştırır.',
      'Korna çalmak gereksiz baskı yaratır ve akışı bozar.',
    ],
    objective: 'Duraktan kalkan toplu taşıma aracına yol vererek yol paylaşımını kavramak.',
    tags: ['paylasim', 'toplu-tasima', 'yol-verme'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-228',
    subject: 'adab',
    topic: 'sorumluluk',
    difficulty: 'zor',
    stem: 'Sürüş sırasında telefonunuza önemli bir mesaj geldi ve hemen bakmak istiyorsunuz. Sorumlu davranış hangisidir?',
    options: [
      'Telefona bakmayıp gerekirse güvenli bir yerde durduktan sonra ilgilenmek',
      'Kısa bir bakış zarar vermez, hemen okumak',
      'Kırmızı ışıkta beklerken mesajlaşmayı sürdürmek',
      'Direksiyonu dizle tutup iki elle yazmak',
    ],
    answerIndex: 0,
    explanation:
      'Sürerken telefona bakmak, birkaç saniyeliğine bile olsa gözü yoldan ayırıp tepki süresini yok eder; mesaja ancak güvenli bir yerde durduktan sonra bakmak sorumlu bir sürücünün tercihidir.',
    whyWrong: [
      'Kısa bir bakış bile onlarca metre boyunca kör sürüş demektir.',
      'Işıkta veya dizle direksiyon tutarak yazmak dikkati dağıtır ve tehlikelidir.',
    ],
    objective: 'Sürüş sırasında telefon kullanımından kaçınma sorumluluğunu kavramak.',
    tags: ['sorumluluk', 'dikkat-dagilmasi', 'telefon'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-229',
    subject: 'adab',
    topic: 'hosgoru',
    difficulty: 'kolay',
    stem: 'Işıklarda önünüzdeki yeni sürücünün aracı yeşilde stop yaptı ve tekrar çalıştırmaya çalışıyor. Hoşgörülü davranış nedir?',
    options: [
      'Uzun korna çalıp panikletmek',
      'Selektör yapıp acele ettirmek',
      'Sakin bekleyip toparlanmasına fırsat tanımak',
      'Yandan sıkışıp geçerek tepki göstermek',
    ],
    answerIndex: 2,
    explanation:
      'Aracın stop etmesi herkesin başına gelebilir ve panikleyen sürücü daha çok hata yapar; sakin bekleyip fırsat tanımak hoşgörünün ve güvenli sürüşün gereğidir.',
    whyWrong: [
      'Korna ve selektör yeni sürücüyü daha çok telaşlandırıp süreci uzatır.',
      'Yandan sıkışıp geçmek kavşakta tehlike yaratır.',
    ],
    objective: 'Beklenmedik aksaklıklar yaşayan sürücülere hoşgörüyle yaklaşmayı kavramak.',
    tags: ['hosgoru', 'sabir', 'acemi-surucu'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-230',
    subject: 'adab',
    topic: 'saygi',
    difficulty: 'orta',
    stem: 'Yaya kaldırımı boş görünüyor ve oraya park etmek işinizi kolaylaştıracak. Yayalara saygı açısından ne yaparsınız?',
    options: [
      'Kaldırım boşsa kısa süre park etmek uygundur',
      'Kaldırıma park etmeyip yaya geçişini engellemeyecek uygun bir yer aramak',
      'Kaldırımın yarısına park edip yayalara yer bırakmak',
      'Dörtlüleri yakıp kaldırıma park etmek',
    ],
    answerIndex: 1,
    explanation:
      'Kaldırım yayalara, özellikle bebek arabası ve tekerlekli sandalye kullananlara aittir; oraya park etmek onları taşıt yoluna inmeye zorlar, bu yüzden kaldırıma park etmemek yayalara saygının gereğidir.',
    whyWrong: [
      'Kaldırıma tam veya yarım park etmek yaya geçişini daraltıp tehlike yaratır.',
      'Dörtlü yakmak kaldırımı işgal etmeyi meşru kılmaz.',
    ],
    objective: 'Kaldırımları yayalara bırakarak yaya güvenliğine saygı göstermeyi benimsemek.',
    tags: ['saygi', 'yaya-saygi', 'park'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
];
