/**
 * ÖZGÜN trafik adabı soruları — 7. genişletme (Program 2 · Faz 9). ROADMAP C.4/E.6.
 * Kaynak = MEB Trafik Adabı müfredatı; KENDİ İFADEMİZLE.
 * Bu genişletmenin odağı: TEMEL KAVRAMLAR ve TANIMLAR (değer temelli, güvenlik öncelikli, empatik).
 */
import type { QuestionInput } from '@ea/content-schema';

const SRC = 'MEB Trafik Adabı müfredatı (özgün ifade)';

export const ADAB_QUESTIONS_7: QuestionInput[] = [
  {
    id: 'adab-701',
    subject: 'adab',
    topic: 'trafik-adabi-tanimi',
    difficulty: 'kolay',
    stem: '"Trafik adabı" kavramı en doğru biçimde nasıl tanımlanır?',
    options: [
      'Yalnızca yazılı trafik kurallarına eksiksiz uymaktır',
      'Kuralların ötesinde; yolu paylaşan herkese saygı, empati ve sorumlulukla yaklaşmayı gerektiren bir değerler bütünüdür',
      'Trafik cezalarından kaçınmayı sağlayan pratik ipuçları toplamıdır',
      'Yalnızca deneyimli sürücülerin zamanla kazandığı bir sürüş yeteneğidir',
    ],
    answerIndex: 1,
    explanation:
      'Trafik adabı, ceza korkusuyla değil; karşımızdakini bir insan olarak görmekten doğan saygı, empati ve sorumluluk gibi değerlerle sürmektir. Kurallar asgari sınırı çizer, adap ise o sınırın ötesinde gönüllü bir olgunluktur.',
    whyWrong: [
      'Kurallara uymak adabın bir parçasıdır ama tamamı değildir; adap, kural olmayan yerlerde de nasıl davrandığımızla ilgilidir.',
      'Adabı ceza kaçınma taktiğine indirgemek, onun değer temelli özünü görmezden gelir.',
      'Adap yaşa ya da deneyime değil tutuma bağlıdır; acemi bir sürücü de adaplı olabilir.',
    ],
    objective: 'Trafik adabını, kuralların ötesinde bir değerler bütünü olarak tanımlayabilmek.',
    tags: ['trafik-adabi-tanimi', 'deger', 'tanim'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-702',
    subject: 'adab',
    topic: 'deger-kavrami',
    difficulty: 'orta',
    stem: 'Trafik adabı sabır, saygı ve hoşgörü gibi "değerler" üzerine kuruludur. Trafikte bir "değer"i bir "kural"dan ayıran temel özellik nedir?',
    options: [
      'Değerler yazılı olduğu için kurallardan daha bağlayıcıdır',
      'Değerler yalnızca trafikte, kurallar ise her yerde geçerlidir',
      'Kural dıştan bir denetimle zorlanır; değer ise kişinin içselleştirdiği, denetim olmasa da davranışına yön veren bir inançtır',
      'Değerler ve kurallar aslında aynı şeydir, aralarında fark yoktur',
    ],
    answerIndex: 2,
    explanation:
      'Kurala ceza korkusuyla uyulur; değere ise inanıldığı için uyulur. Bir sürücü hız sınırına radar olduğu için değil, hız güvenliği tehdit ettiği için uyuyorsa kuralı bir değere dönüştürmüş demektir. Adabın kalıcılığı bu içselleştirmeden gelir.',
    whyWrong: [
      'Değerler çoğu zaman yazılı değildir; bağlayıcılıkları dıştan değil vicdandan gelir.',
      'Değerler trafikle sınırlı değildir; saygı ve sorumluluk hayatın her alanında geçerlidir.',
      'Kural ile değer aynı şey değildir: biri dış zorlama, diğeri iç kabuldür.',
    ],
    objective: 'Değer ile kural arasındaki içselleştirme farkını kavramak.',
    tags: ['deger-kavrami', 'kural-deger', 'icsellestirme'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-703',
    subject: 'adab',
    topic: 'sabir-tanimi',
    difficulty: 'kolay',
    stem: 'Trafikte bir değer olarak "sabır" en doğru biçimde nasıl tanımlanır?',
    options: [
      'İstenmeyen bir durum karşısında öfkeye ve aceleye kapılmadan sakinliğini ve sağduyusunu koruyabilme olgunluğudur',
      'Hiçbir koşulda hızlanmamak ve her zaman en yavaş şeritte gitmektir',
      'Haklı olunduğunda bile her haktan vazgeçip sürekli geri çekilmektir',
      'Trafikte hiç duygu hissetmemek, tamamen tepkisiz kalmaktır',
    ],
    answerIndex: 0,
    explanation:
      'Sabır, duygusuzluk ya da pasiflik değildir; gecikme, sıkışıklık ya da bir hata karşısında öfkeye teslim olmadan aklıselimi koruyabilmektir. Sabırlı sürücü durumu değiştiremediğinde tepkisini yönetir ve güvenliği riske atmaz.',
    whyWrong: [
      'Sabır sürekli yavaş gitmek değildir; yerine göre kararlı ve akıcı sürmeyi de içerir.',
      'Sabır her hakkından vazgeçmek anlamına gelmez; sağduyuyla, gerektiğinde hakkını da güvenle kullanmayı kapsar.',
      'Sabır duygusuzluk değil, duyguyu yönetebilmektir.',
    ],
    objective: 'Sabrı, olumsuz durumlarda sağduyuyu koruma olgunluğu olarak tanımlamak.',
    tags: ['sabir-tanimi', 'ozdenetim', 'tanim'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-704',
    subject: 'adab',
    topic: 'hosgoru-siniri',
    difficulty: 'zor',
    stem: 'Hoşgörü, trafikte başkalarının hatalarını olgunlukla karşılamaktır. Ancak hoşgörünün de bir sınırı vardır. Bu sınır en doğru nasıl ifade edilir?',
    options: [
      'Hoşgörünün sınırı yoktur; her davranış koşulsuz hoş görülmelidir',
      'Hoşgörü yalnızca tanıdığımız sürücülere gösterilmelidir',
      'Hoşgörü, karşı tarafın konumuna ve aracının türüne göre ayarlanmalıdır',
      'Başkasının hatasını sükûnetle karşılamak hoşgörüdür; ancak bu, tehlikeli bir davranışı görmezden gelip güvenlikten ödün vermeye dönüşmemelidir',
    ],
    answerIndex: 3,
    explanation:
      'Hoşgörü, bir hataya öfkeyle karşılık vermemektir; ama tekrarlayan ya da can güvenliğini tehdit eden bir davranışı "hoş görüp" önlem almamak değildir. Örneğin agresif bir sürücüye kızmamak hoşgörüdür; ondan uzaklaşmak ise güvenliktir. İkisi birbirini tamamlar.',
    whyWrong: [
      'Sınırsız hoşgörü, tehlikeli davranışları normalleştirir ve güvenliği zedeler.',
      'Hoşgörüyü tanıdıklıkla ya da aracın türüyle sınırlamak, onu değer olmaktan çıkarıp ayrımcılığa çevirir.',
    ],
    objective:
      'Hoşgörü ile güvenlik önlemi arasındaki dengeyi kurup hoşgörünün güvenlikten ödün vermeyeceğini kavramak.',
    tags: ['hosgoru-siniri', 'guvenlik', 'defansif-surus'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-705',
    subject: 'adab',
    topic: 'nezaket-tanimi',
    difficulty: 'kolay',
    stem: 'Trafikte "nezaket" değeri en doğru biçimde neyi ifade eder?',
    options: [
      'Yalnızca teşekkür işareti yapmaktır; başka bir davranışla ilgisi yoktur',
      'Kurallar zorunlu kılmasa bile hiçbir sürücüye yol vermemektir',
      'Zorunlu olmadığı hâlde, karşımızdakinin işini kolaylaştıran, incelik ve saygı gösteren gönüllü davranışlardır',
      'Yalnızca trafik yoğunken gösterilmesi gereken bir görgü kuralıdır',
    ],
    answerIndex: 2,
    explanation:
      'Nezaket, kuralın zorlamadığı yerde gönüllü olarak gösterilen inceliktir: sıkışık trafikte yan yoldaki araca yer açmak, bir yayaya gülümseyerek yol vermek gibi. Zorunluluktan değil saygıdan doğduğu için trafik ikliminin ısınmasını sağlar.',
    whyWrong: [
      'Nezaket tek bir jestten ibaret değildir; yer açmaktan sabırlı beklemeye kadar geniş bir tutumdur.',
      'Yol vermemek nezaketin tam tersidir.',
      'Nezaket yoğunlukla sınırlı değildir; her koşulda gösterilebilen bir değerdir.',
    ],
    objective: 'Nezaketi, zorunlu olmayan gönüllü incelik davranışları olarak tanımlamak.',
    tags: ['nezaket-tanimi', 'saygi', 'tanim'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-706',
    subject: 'adab',
    topic: 'sorumluluk-tanimi',
    difficulty: 'orta',
    stem: 'Trafikte "sorumluluk" değeri en kapsamlı biçimde nasıl tanımlanır?',
    options: [
      'Yalnızca kendi aracına zarar gelmesini önlemektir',
      'Kendi davranışlarının; kendisi, yolcuları, diğer sürücüler ve yayalar üzerindeki sonuçlarını üstlenmek ve bunları önceden hesaba katmaktır',
      'Bir kaza olduğunda kusuru en hızlı biçimde karşı tarafa yıkabilmektir',
      'Sadece trafik cezası ödeyecek kadar para bulundurmaktır',
    ],
    answerIndex: 1,
    explanation:
      'Sorumluluk, direksiyondaki kişinin yalnızca kendinden değil, davranışının dokunduğu herkesten sorumlu olduğunu kabul etmesidir. Bu hem hata yapıldığında sonucunu üstlenmeyi hem de daha önemlisi olası sonuçları önceden düşünüp önlem almayı kapsar.',
    whyWrong: [
      'Sorumluluk yalnızca kendi aracını korumak değil, çevredeki herkesin güvenliğini gözetmektir.',
      'Kusuru karşıya yıkmak sorumluluğun değil, ondan kaçmanın ifadesidir.',
    ],
    objective: 'Sorumluluğu, davranışın tüm sonuçlarını üstlenmek ve öngörmek olarak tanımlamak.',
    tags: ['sorumluluk-tanimi', 'ongoru', 'tanim'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-707',
    subject: 'adab',
    topic: 'ofke-tanimi',
    difficulty: 'kolay',
    stem: 'Öfke, engellenme ya da haksızlığa karşı doğal bir duygudur. Öfkenin trafikteki en temel tehlikesi nedir?',
    options: [
      'Muhakemeyi ve dikkati daraltıp sürücüyü, sakinken asla yapmayacağı riskli davranışlara yöneltmesidir',
      'Yalnızca sürücünün moralini bozması, sürüşe hiçbir etkisinin olmamasıdır',
      'Aracın yakıt tüketimini artırmasıdır',
      'Sadece uzun yolculuklarda ortaya çıkması, şehir içinde etkisiz olmasıdır',
    ],
    answerIndex: 0,
    explanation:
      'Öfke doğal bir duygudur; sorun onu hissetmek değil, direksiyonda kontrolsüz bırakmaktır. Öfkeli beyin tehlikeyi olduğundan küçük, kendini olduğundan güçlü görür; böylece sabır yerini dürtüye, sağduyu yerini inada bırakır. Bu yüzden öfke sürüşün en riskli hâllerinden biridir.',
    whyWrong: [
      'Öfkenin etkisi moralle sınırlı değildir; doğrudan karar ve dikkat kalitesini düşürür.',
      'Öfke bir yakıt sorunu değil, bir güvenlik sorunudur.',
      'Öfke her ortamda, şehir içi dâhil, riski artırır.',
    ],
    objective: 'Öfkenin muhakemeyi daraltarak riskli davranışa yol açtığını kavramak.',
    tags: ['ofke-tanimi', 'risk-algisi', 'psikoloji'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-708',
    subject: 'adab',
    topic: 'empati-tanimi',
    difficulty: 'orta',
    stem: 'Trafikte "empati" değeri en doğru biçimde nasıl tanımlanır ve uygulanır?',
    options: [
      'Kendini yalnızca kendi aracının çıkarları açısından düşünmektir',
      'Diğer sürücülerin hatalarını sürekli affedip hiçbir önlem almamaktır',
      'Yalnızca kaza anında yaralılara acımaktır',
      'Karşımızdaki sürücünün ya da yayanın durumunu, kısıtlarını ve bakış açısını onun yerine geçerek anlamaya çalışmak ve davranışımızı buna göre ayarlamaktır',
    ],
    answerIndex: 3,
    explanation:
      'Empati, "onun yerinde ben olsaydım" diye düşünebilmektir. Acemi bir sürücünün tedirginliğini, yaşlı bir yayanın yavaşlığını ya da yanımdaki motosikletlinin kırılganlığını anladığımda ona alan ve zaman tanırım. Empati böylece soyut bir duygudan somut bir güvenlik davranışına dönüşür.',
    whyWrong: [
      'Yalnızca kendi çıkarını düşünmek empatinin değil, bencilliğin tanımıdır.',
      'Empati önlemsiz affetmek değildir; anlamakla birlikte güvenli davranmayı da içerir.',
      'Empati kaza anıyla sınırlı değildir; her an, herkese yönelik bir bakış açısıdır.',
    ],
    objective:
      'Empatiyi, karşıdakinin bakış açısını anlayıp davranışı ona göre ayarlamak olarak tanımlamak.',
    tags: ['empati-tanimi', 'perspektif', 'tanim'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-709',
    subject: 'adab',
    topic: 'stres-surus-etkisi',
    difficulty: 'kolay',
    stem: 'Stres altındaki bir sürücünün bedeninde ve zihninde olanlar düşünüldüğünde, stresin sürüşe temel etkisi nedir?',
    options: [
      'Stres dikkati artırdığı için sürüşü her zaman güvenli kılar',
      'Stresin sürüşe hiçbir bedensel ya da zihinsel etkisi yoktur',
      'Kas gerginliği, daralan dikkat ve sabırsızlık yaratarak tepkileri aceleci ve hatalı hâle getirir',
      'Yalnızca sürücünün ruh hâlini etkiler, davranışına hiç yansımaz',
    ],
    answerIndex: 2,
    explanation:
      'Stres, beden "tehdit" algıladığında devreye girer: kaslar gerilir, nefes hızlanır, dikkat alanı daralır. Bu tabloda sürücü çevresini yeterince tarayamaz, küçük gecikmelere büyük tepkiler verir ve aceleci kararlar alır. Bu yüzden stresi fark edip yönetmek güvenli sürüşün parçasıdır.',
    whyWrong: [
      'Yoğun stres dikkati keskinleştirmez, tersine daraltır.',
      'Stresin bedensel ve zihinsel etkileri ölçülebilir düzeyde gerçektir.',
      'Stres yalnızca hissedilen bir ruh hâli değildir; doğrudan davranışa yansır.',
    ],
    objective: 'Stresin dikkati daraltıp tepkileri bozan bedensel-zihinsel etkisini kavramak.',
    tags: ['stres-surus-etkisi', 'dikkat', 'psikoloji'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-710',
    subject: 'adab',
    topic: 'motivasyon-dikkat',
    difficulty: 'orta',
    stem: 'Sürücünün ruh hâli ve niyeti (motivasyonu) ile dikkati arasında yakın bir ilişki vardır. Bu ilişki en doğru nasıl açıklanır?',
    options: [
      'Motivasyon ne olursa olsun dikkat her zaman aynı düzeyde kalır',
      '"Bir an önce varmak" ya da "onu geçmek" gibi hedeflere kilitlenen bir zihin, dikkatini o hedefe yoğunlaştırıp çevredeki diğer tehlikeleri gözden kaçırabilir',
      'Yüksek motivasyon her zaman daha güvenli sürüş demektir',
      'Dikkat yalnızca fiziksel yorgunlukla ilgilidir, niyetle ilgisi yoktur',
    ],
    answerIndex: 1,
    explanation:
      'Zihin neye motive olursa dikkatini oraya toplar. "Kırmızıya yakalanmadan geçme" hedefine kilitlenen sürücü, o sırada geçide adım atan yayayı fark etmeyebilir. Bu yüzden acele, hırs ya da inat gibi motivasyonlar dikkati daraltarak güvenli sürüşün önündeki en sinsi engellerden biri olur.',
    whyWrong: [
      'Motivasyon, dikkatin yönünü ve genişliğini doğrudan etkiler; sabit kalmaz.',
      '"Yüksek motivasyon" yanlış hedefe (yarışmak gibi) yönelmişse güvenliği azaltır.',
      'Dikkat yalnızca yorgunlukla değil, zihnin neye odaklandığıyla da belirlenir.',
    ],
    objective:
      'Motivasyonun dikkati yönlendirip daraltabildiğini ve bunun güvenliğe etkisini kavramak.',
    tags: ['motivasyon-dikkat', 'dikkat', 'odak-daralmasi'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-711',
    subject: 'adab',
    topic: 'iletisim-tanimi',
    difficulty: 'orta',
    stem: 'Trafik, sürücülerin birbiriyle sürekli "iletişim kurduğu" bir ortamdır. Trafikte iletişim en doğru biçimde nasıl tanımlanır?',
    options: [
      'Sinyal, far, korna, göz teması ve aracın konumu gibi işaretlerle niyetimizi diğerlerine anlaşılır biçimde bildirmek ve onların işaretlerini doğru okumaktır',
      'Yalnızca korna çalarak diğer sürücüleri uyarmaktır',
      'Karşıdaki sürücüyle sözlü olarak tartışabilmektir',
      'Sosyal medyada trafikle ilgili paylaşım yapmaktır',
    ],
    answerIndex: 0,
    explanation:
      'Trafikte konuşamayız; niyetimizi işaretlerle anlatırız. Zamanında verilen bir sinyal "sağa geçeceğim" der; bir göz teması "seni gördüm, geç" anlamına gelir. İyi bir sürücü hem niyetini açıkça bildirir hem de başkalarının işaretlerini doğru okur. İletişim böylece öngörülebilirliği ve güvenliği artırır.',
    whyWrong: [
      'İletişim yalnızca kornadan ibaret değildir; asıl araçlar sinyal, konum ve göz temasıdır.',
      'Trafikte iletişim tartışmak değil, niyet bildirmektir.',
      'Sosyal medya paylaşımı, trafik içi anlık iletişim değildir.',
    ],
    objective: 'Trafik iletişimini, işaretlerle niyet bildirme ve okuma süreci olarak tanımlamak.',
    tags: ['iletisim-tanimi', 'sinyal', 'goz-temasi'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-712',
    subject: 'adab',
    topic: 'beden-dili',
    difficulty: 'kolay',
    stem: 'Trafikte aracın kendisi de bir tür "beden dili" konuşur. Aşağıdakilerden hangisi bu araç beden diline bir örnektir?',
    options: [
      'Sürücünün araç içinde yüksek sesle müzik dinlemesi',
      'Aracın markasının pahalı olması',
      'Sürücünün kişisel giyim tarzı',
      'Aracın hızını erkenden azaltıp şerit içinde hafifçe kenara yanaşarak "yol veriyorum, geçebilirsin" niyetini sezdirmesi',
    ],
    answerIndex: 3,
    explanation:
      'İnsanlar gibi araçlar da sözsüz bir dil konuşur: yavaşlayıp kenara yanaşmak "buyur geç", tereddütle ilerlemek "kararsızım" mesajı verir. Bu sinyalleri bilinçli ve tutarlı kullanmak, diğer sürücülerin niyetimizi okumasını ve trafiğin akıcı, güvenli işlemesini sağlar.',
    whyWrong: [
      'Araç içindeki müziğin sesi, dışarıdaki sürücülerle bir iletişim kurmaz.',
      'Aracın markası ya da fiyatı bir niyet bildirmez.',
      'Sürücünün giyimi, trafikteki davranışsal iletişimin bir parçası değildir.',
    ],
    objective: 'Aracın hareket ve konumuyla niyet ilettiği "beden dilini" tanımak.',
    tags: ['beden-dili', 'iletisim', 'niyet-bildirme'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-713',
    subject: 'adab',
    topic: 'bencillik-paylasim',
    difficulty: 'orta',
    stem: 'Trafikte "bencillik" ile "paylaşım" arasındaki temel fark en doğru nasıl açıklanır?',
    options: [
      'Bencillik hızlı, paylaşım ise yavaş sürmektir',
      'İkisi arasında pratikte hiçbir fark yoktur',
      'Bencil sürücü yolu yalnızca kendi menfaatine göre kullanır; paylaşımcı sürücü ise yolun herkese ait ortak bir alan olduğunu kabul edip başkalarının hakkını da gözetir',
      'Bencillik yalnızca otoparkta, paylaşım yalnızca otoyolda geçerlidir',
    ],
    answerIndex: 2,
    explanation:
      'Trafik, sınırlı bir alanın binlerce kişiyle paylaşıldığı bir ortamdır. Bencil sürücü "önce ben" diyerek boşlukları kapar, sıra tanımaz; paylaşımcı sürücü ise yolun ortak olduğunu bilir ve kendi hakkı kadar başkasının hakkını da hesaba katar. Adap, bu paylaşım bilincinden doğar.',
    whyWrong: [
      'Fark hızda değil zihniyettedir; bencillik yavaş süren bir sürücüde de olabilir.',
      'İki tutum arasındaki fark, tüm trafik kültürünü belirleyecek kadar büyüktür.',
      'Bu tutumlar belirli mekânlara değil, sürücünün bakış açısına bağlıdır.',
    ],
    objective: 'Bencillik ile paylaşım tutumları arasındaki zihniyet farkını kavramak.',
    tags: ['bencillik-paylasim', 'ortak-alan', 'hak'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-714',
    subject: 'adab',
    topic: 'trafik-teroru-kavrami',
    difficulty: 'orta',
    stem: 'Haberlerde sıkça geçen "trafik terörü" kavramı en doğru biçimde neyi anlatır?',
    options: [
      'Yalnızca trafikte yaşanan olağan sıkışıklık ve gecikmeleri',
      'Öfke, saldırganlık ve kural tanımazlıkla başkalarının can güvenliğini kasıtlı biçimde tehdit eden; yol kesme, sıkıştırma, üzerine sürme gibi davranışları',
      'Aracın teknik arızadan dolayı yolda kalmasını',
      'Trafik cezalarının yüksek olmasını',
    ],
    answerIndex: 1,
    explanation:
      '"Trafik terörü", trafikteki sıradan hatalardan farklıdır; öfke ve saldırganlığın kasıtlı bir tehdide dönüştüğü davranışları anlatır: birinin önünü kesmek, üzerine yürümek, aracıyla korkutmak. Bunlar yalnızca birer görgüsüzlük değil, insanların hayatını hedef alan ve hukuken de suç sayılan ağır davranışlardır.',
    whyWrong: [
      'Olağan sıkışıklık ya da gecikme terör değil, trafiğin doğal bir parçasıdır.',
      'Teknik bir arıza kasıtlı bir tehdit değildir.',
      'Cezaların düzeyi, bu kavramla ilgili değildir.',
    ],
    objective: 'Trafik terörünü, kasıtlı ve saldırgan can tehdidi davranışları olarak tanımlamak.',
    tags: ['trafik-teroru-kavrami', 'saldirganlik', 'yol-ofkesi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-715',
    subject: 'adab',
    topic: 'feragat-erdemi',
    difficulty: 'kolay',
    stem: 'Trafik adabında "feragat" (haktan gönüllü vazgeçme) bir erdem olarak neyi ifade eder?',
    options: [
      'Geçiş hakkı kendinde olsa bile, güvenliği ve akışı korumak için gerektiğinde bu hakkı gönüllüce karşı tarafa bırakabilmektir',
      'Trafikte hiçbir hakkını asla kullanmamak ve sürekli beklemektir',
      'Yalnızca korktuğumuz büyük araçlara yol vermektir',
      'Hakkımızı almak için sonuna kadar direnmektir',
    ],
    answerIndex: 0,
    explanation:
      'Feragat, "hakkım var ama şu an vazgeçiyorum" diyebilme olgunluğudur. Kavşakta önceliği olsa bile ısrar etmenin tehlike ya da kilitlenme doğuracağını gören sürücü hakkını gönüllü bırakır. Bu bir zayıflık değil; güvenliği ve ortak akışı bireysel haktan üstün tutan bir erdemdir.',
    whyWrong: [
      'Feragat, hiç hak kullanmamak değil; gerektiğinde bilinçli olarak vazgeçebilmektir.',
      'Feragat korkuya değil sağduyuya dayanır; yalnızca büyük araçlarla sınırlı değildir.',
      'Sonuna kadar direnmek, feragatin tam tersidir.',
    ],
    objective: 'Feragati, güvenlik için haktan gönüllü vazgeçebilme erdemi olarak tanımlamak.',
    tags: ['feragat-erdemi', 'yol-verme', 'olgunluk'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-716',
    subject: 'adab',
    topic: 'aliskanlik-otomasyon',
    difficulty: 'zor',
    stem: 'Deneyimli sürücülerin çoğu davranışı zamanla "otomatikleşir" (alışkanlığa döner). Bu otomatikleşmenin trafik adabı açısından çift yönlü etkisi en doğru nasıl açıklanır?',
    options: [
      'Otomatikleşme her zaman iyidir; alışkanlıklar asla sorun çıkarmaz',
      'Otomatikleşme her zaman tehlikelidir; sürüş hiçbir zaman alışkanlığa dönmemelidir',
      'Alışkanlıkların davranışla hiçbir ilgisi yoktur',
      'İyi alışkanlıklar (sinyal verme, ayna kontrolü) güvenliği kolaylaştırır; ancak kötü alışkanlıklar da farkında olmadan otomatikleşip yanlışı "normal" hâle getirebilir, bu yüzden alışkanlıkları ara sıra gözden geçirmek gerekir',
    ],
    answerIndex: 3,
    explanation:
      'Beyin, sık tekrarlanan davranışları otomatiğe alarak dikkatimizi serbest bırakır; bu sayede sinyal vermeyi ya da ayna kontrolünü düşünmeden yaparız. Ama aynı mekanizma kötü davranışları da otomatikleştirir: sinyalsiz dönmek ya da hız aşımı zamanla "normal" gibi hissedilir. Bu yüzden olgun sürücü alışkanlıklarını zaman zaman sorgular.',
    whyWrong: [
      'Otomatikleşme, kötü davranışlar söz konusu olduğunda tehlikelidir; koşulsuz iyi değildir.',
      'Otomatikleşme büsbütün kötü de değildir; iyi alışkanlıklar güvenliğin temelidir.',
      'Alışkanlıklar davranışın büyük bölümünü belirler; ilgisiz değildir.',
    ],
    objective:
      'Alışkanlığın hem iyi hem kötü davranışı otomatikleştirdiğini ve öz denetimin gereğini kavramak.',
    tags: ['aliskanlik-otomasyon', 'ozdenetim', 'davranis'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-717',
    subject: 'adab',
    topic: 'rol-model-olma',
    difficulty: 'kolay',
    stem: 'Kurallara uyan bir sürücünün, çevresindeki diğer insanlar için bir "rol model" olması ne anlama gelir?',
    options: [
      'Diğer sürücülerin davranışının bizi hiç etkilemediği anlamına gelir',
      'Bizim adaplı davranışımızın; çevremizdeki sürücülere ve özellikle çocuklara örnek olup olumlu davranışların yayılmasına katkı sağlamasıdır',
      'Yalnızca sürüş yarışmalarında birinci olmaktır',
      'Aracımızı en pahalı ve gösterişli hâle getirmektir',
    ],
    answerIndex: 1,
    explanation:
      'Trafikte davranışlar bulaşıcıdır: bir sürücünün yayaya sabırla yol vermesi, arkadaki sürücüye de aynı inceliği hatırlatır. Rol model olmak, "herkes bozuyor, ben de bozayım" demek yerine doğruyu yaşayıp örnek olmaktır. Bu, özellikle bizi izleyen çocuklar için geleceğin trafik kültürünü şekillendirir.',
    whyWrong: [
      'Rol model olmak, etkileşimi yok saymak değil, çevreyi olumlu yönde etkilemektir.',
      'Rol model olmak bir yarışma başarısı değil, bir davranış örnekliğidir.',
      'Aracın gösterişi değil, sürücünün tutumu örnek olur.',
    ],
    objective: 'Adaplı davranışın çevreye örnek olup olumlu kültürü yaydığını kavramak.',
    tags: ['rol-model-olma', 'ornek-olma', 'trafik-kulturu'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-718',
    subject: 'adab',
    topic: 'kazanin-toplumsal-maliyeti',
    difficulty: 'orta',
    stem: 'Bir trafik kazası yalnızca kazaya karışanları değil, tüm toplumu etkiler. Kazaların "toplumsal maliyeti" kavramı en doğru neyi kapsar?',
    options: [
      'Yalnızca hasar gören aracın tamir masrafını',
      'Yalnızca sürücünün ödeyeceği trafik cezasını',
      'Maddi hasarların yanı sıra kaybedilen canları, sakat kalmaları, ailelerin yaşadığı duygusal yıkımı, iş gücü kaybını ve sağlık sistemine binen yükü kapsayan geniş bir bedeller bütününü',
      'Sadece o gün trafikte oluşan kısa süreli sıkışıklığı',
    ],
    answerIndex: 2,
    explanation:
      'Bir kazanın faturası tamir masrafından çok daha büyüktür: bir hayatın sönmesi, geride kalanların onarılamaz acısı, iş gücü ve üretim kaybı, hastane ile rehabilitasyon yükü... Bu bedelleri doğrudan ya da dolaylı olarak tüm toplum öder. Adaplı sürüş, işte bu görünmeyen maliyeti azaltan bir sorumluluktur.',
    whyWrong: [
      'Tamir masrafı, toplumsal maliyetin yalnızca küçük ve görünen bir parçasıdır.',
      'Ceza, maliyetin kendisi değil; caydırıcılık amaçlı küçük bir kalemdir.',
      'Kısa süreli sıkışıklık, kazanın uzun vadeli insani ve ekonomik yükünün yanında önemsiz kalır.',
    ],
    objective: 'Kazaların toplumsal maliyetinin, maddi hasarı aşan geniş kapsamını kavramak.',
    tags: ['kazanin-toplumsal-maliyeti', 'toplumsal-sorumluluk', 'kaza'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-719',
    subject: 'adab',
    topic: 'surdurulebilir-trafik-kulturu',
    difficulty: 'orta',
    stem: '"Sürdürülebilir bir trafik kültürü" kavramı en doğru biçimde neyi anlatır?',
    options: [
      'Adaplı davranışların bireysel bir çabayla sınırlı kalmayıp; eğitim, örnek olma ve toplumsal kabul yoluyla kuşaktan kuşağa aktarılarak kalıcı hâle gelmesidir',
      'Yalnızca daha fazla trafik cezası kesilerek sağlanan geçici bir düzendir',
      'Herkesin aracını daha az kullanmasıyla trafiğin tamamen bitmesidir',
      'Trafik sorunlarının yalnızca yeni yollar yapılarak çözülmesidir',
    ],
    answerIndex: 0,
    explanation:
      'Bir kültür, tek tek iyi davranışlardan değil; bu davranışların yaygınlaşıp benimsenmesinden ve yeni kuşaklara aktarılmasından doğar. Sürdürülebilir trafik kültürü, adabın ceza korkusuna değil ortak bir değere dayandığı, ebeveynden çocuğa taşınarak kendini yenileyen bir düzendir.',
    whyWrong: [
      'Yalnızca cezaya dayalı düzen, denetim gevşediğinde çözülür; sürdürülebilir değildir.',
      'Sürdürülebilirlik, trafiğin bitmesi değil, sağlıklı biçimde yönetilmesidir.',
      'Yalnızca altyapı yatırımı, davranış kültürü olmadan kalıcı çözüm sağlamaz.',
    ],
    objective:
      'Sürdürülebilir trafik kültürünü, aktarılabilir ve içselleştirilmiş bir değerler düzeni olarak kavramak.',
    tags: ['surdurulebilir-trafik-kulturu', 'trafik-kulturu', 'egitim'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-720',
    subject: 'adab',
    topic: 'kural-deger-vicdan',
    difficulty: 'zor',
    stem: 'Denetim, kamera ya da başka hiç kimsenin olmadığı bir anda bile kurallara uyan bir sürücüyü buna yönelten şey nedir; bu durum kural ile değer ilişkisi hakkında neyi gösterir?',
    options: [
      'Sürücü aslında hâlâ ceza korkusuyla hareket etmektedir',
      'Kimse yokken kurala uymanın hiçbir anlamı yoktur',
      'Bu davranış tümüyle şansa bağlıdır, bir nedeni yoktur',
      'Sürücüyü yönlendiren şey vicdanıdır; kuralı bir değere dönüştürüp içselleştirdiği için dış denetim olmasa da doğru davranır ve bu, adabın en olgun hâlidir',
    ],
    answerIndex: 3,
    explanation:
      'Kurala yalnızca görüldüğümüz için uyuyorsak, denetim kalktığında kural da kalkar. Oysa vicdan, kimsenin görmediği yerde bile bizi doğruya bağlayan bir iç denetimdir. Kuralı bir değere dönüştürmüş sürücü, gece yarısı bomboş bir kavşakta bile kırmızıda durur; çünkü artık kuraldan değil, kendi değerinden hareket etmektedir. Adabın olgunluğu buradadır.',
    whyWrong: [
      'Kimse yokken de kurala uyan sürücü, tam da ceza korkusunu aşmış olandır.',
      'Denetimsiz anda kurala uymak anlamsız değildir; asıl karakteri o an belli eder.',
      'Bu davranış şans değil, içselleştirilmiş bir değerin sonucudur.',
    ],
    objective:
      'Vicdanın, kuralı içselleştirilmiş bir değere dönüştürerek denetimsiz uyumu sağladığını kavramak.',
    tags: ['kural-deger-vicdan', 'vicdan', 'icsellestirme'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
];
