/**
 * ÖZGÜN trafik adabı soruları — 4. genişletme (Program 2 · Faz 9). ROADMAP C.4/E.6.
 * Kaynak = MEB Trafik Adabı müfredatı; KENDİ İFADEMİZLE.
 */
import type { QuestionInput } from '@ea/content-schema';

const SRC = 'MEB Trafik Adabı müfredatı (özgün ifade)';

export const ADAB_QUESTIONS_4: QuestionInput[] = [
  {
    id: 'adab-401',
    subject: 'adab',
    topic: 'fermuar-kurali',
    difficulty: 'orta',
    stem: 'Yol daralması öncesinde kapanacak şeritten gelen araçlar daralma noktasına kadar ilerleyip katılmaya çalışıyor. Devam eden şeritteki sürücü olarak ne yapmalısınız?',
    options: [
      'Öndeki araca iyice yaklaşıp boşluk bırakmadan girişleri engellemek',
      'Korna çalarak onların en baştan sıraya girmeleri gerektiğini anlatmaya çalışmak',
      'Fermuar (bir sen, bir ben) düzeniyle her seferinde bir aracın önünüze katılmasına izin vermek',
      'Siz de kapanacak şeride geçip daha önden katılmaya çalışmak',
    ],
    answerIndex: 2,
    explanation:
      'Fermuar yöntemi, her iki şeridin daralma noktasına kadar kullanılmasını ve araçların sırayla birleşmesini öngörür; bu düzen hem adil hem de trafiği en akıcı tutan yöntemdir.',
    whyWrong: [
      'Boşluk bırakmadan girişleri engellemek katılmak isteyen aracı riskli manevralara zorlar ve akışı bozar.',
      'Kapanacak şeridi sonuna kadar kullanan sürücü kural ihlali yapmış olmaz; ona kızmak fermuar mantığını yanlış anlamaktır.',
    ],
    objective: 'Şerit daralmalarında fermuar yöntemiyle sırayla ve adil birleşmeyi kavramak.',
    tags: ['fermuar-kurali', 'serit-birlesme', 'paylasim'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-402',
    subject: 'adab',
    topic: 'serit-izleme',
    difficulty: 'orta',
    stem: 'Şehirler arası bölünmüş yolda sollamanızı tamamladınız; sağ şerit tamamen boş. Şerit izleme adabına göre ne yapmalısınız?',
    options: [
      'Sinyal verip sağ şeride dönmek; sol şeridi yalnızca sollama için kullanmak',
      'Hız sınırında gittiğiniz sürece sol şeritte kalmaya devam etmek',
      'Arkadan hızlı bir araç görünene kadar sol şeridi kullanmak',
      'Hangi şeridin daha rahat olduğuna göre canınızın istediği şeritte gitmek',
    ],
    answerIndex: 0,
    explanation:
      'Sol şerit sürekli işgal edilecek bir seyir şeridi değil, sollama şerididir; geçiş bitince sağa dönmek hem kuraldır hem de arkadan gelenlerin güvenli geçişine saygıdır.',
    whyWrong: [
      'Hız sınırında olmak sol şeridi kalıcı olarak kullanma hakkı vermez; arkadaki akışı tıkar.',
      'Birinin görünmesini beklemek geç kalmaktır; hızlı gelen araç sizi tehlikeli biçimde sağdan geçmeye yönelebilir.',
    ],
    objective:
      'Sol şeridin yalnızca sollama için kullanıldığını ve sonra sağa dönülmesi gerektiğini kavramak.',
    tags: ['serit-izleme', 'sol-serit', 'sollama'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-403',
    subject: 'adab',
    topic: 'makas-atma',
    difficulty: 'kolay',
    stem: 'Akan trafikte bir sürücü, sinyal vermeden art arda şerit değiştirerek (makas atarak) araçların arasından sıyrılıyor. Bu davranış için en doğru değerlendirme hangisidir?',
    options: [
      'Trafiği hızlandırdığı için aslında yararlı bir sürüş tarzıdır',
      'Direksiyon hâkimiyeti iyi olan sürücüler için sakıncası yoktur',
      'Yalnızca şehir içinde sakıncalıdır, otoyolda serbesttir',
      'Çevresindeki sürücüleri ani frene zorlayan, zincirleme kazaya davetiye çıkaran saygısız bir ihlaldir',
    ],
    answerIndex: 3,
    explanation:
      'Makas atmak, diğer sürücülerin tepki payını yok eder; tek bir yanlış hesap zincirleme kazaya dönüşebilir. Kazandırdığı birkaç saniye, yarattığı riskin yanında hiçtir.',
    whyWrong: [
      'Makas trafiği hızlandırmaz; ani frenler dalga etkisiyle akışı daha da yavaşlatır.',
      'Beceri, diğer sürücülerin vereceği ani tepkileri kontrol edemez; risk herkese yayılır.',
    ],
    objective: 'Makas atmanın herkes için oluşturduğu riski ve adaba aykırılığını kavramak.',
    tags: ['makas-atma', 'agresif-surus', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-404',
    subject: 'adab',
    topic: 'kavsak-kilitlenmesi',
    difficulty: 'zor',
    stem: 'Işık yeşil yanıyor, ancak kavşağın çıkışındaki trafik durmuş durumda; geçerseniz kavşağın ortasında kalacaksınız. Ne yapmalısınız?',
    options: [
      'Işık yeşil olduğu için geçiş hakkınızı kullanıp kavşağa girmek',
      'Işık yeşil olsa bile çıkışta yeterli boşluk oluşana kadar kavşağa girmemek',
      'Korna çalarak öndeki araçları kavşaktan çıkmaya zorlamak',
      'Boşluk bulmak için kavşak içinde şerit değiştirmek',
    ],
    answerIndex: 1,
    explanation:
      'Çıkışı dolu bir kavşağa girmek, ışık değiştiğinde kavşağın ortasında kalmanıza ve tüm yönlerin kilitlenmesine yol açar; yeşil ışık ancak kavşağı terk edebilecekseniz geçiş hakkı verir.',
    whyWrong: [
      'Yeşil ışık kavşağın ortasında kalma hakkı vermez; kilitlenme herkesin yolunu keser.',
      'Korna çalmak duran trafiği açmaz; kavşak içinde şerit aramak düğümü büyütür.',
    ],
    objective: 'Çıkışı dolu kavşağa girmeyerek kavşak kilitlenmesini önlemeyi kavramak.',
    tags: ['kavsak-kilitlenmesi', 'yesil-isik', 'trafik-akisi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-405',
    subject: 'adab',
    topic: 'uzun-far-gorgusu',
    difficulty: 'orta',
    stem: 'Gece seyir hâlindeyken arkanızdaki araç uzun farlarını açık tutuyor ve iç aynadan gözünüz kamaşıyor. En doğru davranış hangisidir?',
    options: [
      'Ani fren yapıp arkadaki sürücüye ders vermek',
      'Fren lambalarını arka arkaya yakıp söndürerek gözdağı vermek',
      'İç aynayı gece (kamaşma önleyici) konumuna alıp sakin kalmak ve uygun yerde geçmesine imkân tanımak',
      'Hızlanarak aracın ışık alanından çıkmaya çalışmak',
    ],
    answerIndex: 2,
    explanation:
      'Kamaşmayı aynanın gece konumu çözer; gerginliği ise tepki değil, sakin kalıp uygun yerde yol vermek çözer. Böylece hem görüşünüzü hem huzurunuzu korursunuz.',
    whyWrong: [
      'Ani fren, arkadan çarpmayla sonuçlanabilecek kasıtlı ve tehlikeli bir misillemedir.',
      'Hızlanmak sizi kendi güvenli hızınızın üstüne çıkarır; sorunu başka bir riske dönüştürür.',
    ],
    objective:
      'Arkadan gelen far baskısını misilleme yapmadan, teknik ve sakin yollarla yönetmeyi kavramak.',
    tags: ['uzun-far-gorgusu', 'kamasma', 'sakinlik'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-406',
    subject: 'adab',
    topic: 'uzun-far-gorgusu',
    difficulty: 'kolay',
    stem: 'Gece şehir dışında önünüzdeki aracı bir süredir takip ediyorsunuz. Far görgüsü açısından doğru olan hangisidir?',
    options: [
      'Kısa fara geçmek; uzun far öndeki sürücüyü aynalarından kamaştırır',
      'Yolu daha iyi görmek için uzun farla takibe devam etmek',
      'Uzun ve kısa far arasında sürekli geçiş yapmak',
      'Farları tamamen kapatıp öndeki aracın ışığıyla ilerlemek',
    ],
    answerIndex: 0,
    explanation:
      'Uzun far, öndeki sürücünün aynalarından yansıyarak gözünü alır ve görüşünü bozar; bir aracı takip ederken kısa fara geçmek hem kural hem görgü gereğidir.',
    whyWrong: [
      'Kendi görüşünüz için öndekinin görüşünü feda etmek bencilce ve tehlikelidir.',
      'Farları kapatmak sizi hem görünmez hem görüşsüz bırakır; asla yapılmaz.',
    ],
    objective: 'Araç takip ederken kısa far kullanma görgüsünü benimsemek.',
    tags: ['uzun-far-gorgusu', 'gece-surusu', 'nezaket'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-407',
    subject: 'adab',
    topic: 'yaya-gecidi-gorgusu',
    difficulty: 'zor',
    stem: 'Önünüzdeki araç, işaretli yaya geçidinin önünde göremediğiniz bir nedenle durdu. Ne yapmalısınız?',
    options: [
      'Sinyal verip yanından dikkatlice geçmek',
      'Korna çalarak neden durduğunu sormak',
      'Arıza yaptığını varsayıp beklemeden sollamak',
      'Bir yayaya yol veriyor olabileceğini düşünüp arkasında durmak; kesinlikle yanından geçmeye çalışmamak',
    ],
    answerIndex: 3,
    explanation:
      'Geçit önünde duran araç çoğu zaman sizin göremediğiniz bir yayaya yol veriyordur; onu sollamak, tam o anda geçide adım atan yayaya çarpmakla sonuçlanabilecek en tehlikeli hatalardan biridir.',
    whyWrong: [
      'Yanından geçmek, duran aracın gövdesinin gizlediği yayayı son anda karşınızda bulmanız demektir.',
      'Korna, geçitteki yayayı telaşlandırır ve duran sürücüyü baskılar; hiçbir sorunu çözmez.',
    ],
    objective: 'Yaya geçidi önünde duran aracın asla sollanmaması gerektiğini kavramak.',
    tags: ['yaya-gecidi-gorgusu', 'sollama-yasagi', 'gizli-yaya'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-408',
    subject: 'adab',
    topic: 'yaya-gecidi-gorgusu',
    difficulty: 'kolay',
    stem: 'Kırmızı ışığa yaklaşıyorsunuz; önünüzde yaya geçidi ve ondan önce duruş çizgisi var. Nerede durmalısınız?',
    options: [
      'Yaya geçidinin üzerinde, ışığa en yakın noktada',
      'Duruş çizgisinin gerisinde; yaya geçidini yayaların kullanımına tamamen açık bırakarak',
      'Geçidin yarısına kadar sokulup beklemek',
      'Öndeki araca değecek kadar yaklaşarak yer kazanmak',
    ],
    answerIndex: 1,
    explanation:
      'Duruş çizgisi tam da bunun için çizilir: aracınız çizginin gerisindeyken yayalar geçidi rahat ve güvenle kullanır; zebra üzerinde duran araç yayaları taşıt yoluna dolaşmaya zorlar.',
    whyWrong: [
      'Zebranın üzerinde durmak yayaları araçların arasından geçmeye mecbur bırakır.',
      'Öne sokulmak size zaman kazandırmaz; yalnızca yayaların alanını işgal eder.',
    ],
    objective:
      'Kırmızı ışıkta duruş çizgisinin gerisinde durup geçidi açık bırakma görgüsünü benimsemek.',
    tags: ['yaya-gecidi-gorgusu', 'durus-cizgisi', 'kirmizi-isik'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-409',
    subject: 'adab',
    topic: 'empati',
    difficulty: 'kolay',
    stem: 'Sağanak sonrası yol kenarında büyük bir su birikintisi var; hemen yanındaki otobüs durağında insanlar bekliyor. Ne yaparsınız?',
    options: [
      'Hızı iyice azaltıp mümkünse birikintiden uzak geçerek kimseye su sıçratmamak',
      'Hızı korumak; su sıçraması sürücünün sorumluluğu değildir',
      'Korna çalıp duraktakileri geriye çekilmeleri için uyarmak',
      'Birikintiden hızla geçip bir an önce uzaklaşmak',
    ],
    answerIndex: 0,
    explanation:
      'Duraktakilerin kaçacak yeri yoktur; yavaşlayıp mesafe bırakmak, insanların üstünü ıslatmamak için gereken tek şeydir ve empatinin en somut hâlidir.',
    whyWrong: [
      'Sıçrayan su tamamen sürücünün hız ve rota tercihinin sonucudur; sorumluluk sürücünündür.',
      'Korna çalmak insanları rahatsız eder; sorumluluğu mağdura yıkmaktır.',
    ],
    objective:
      'Su birikintisi yanındaki yayalara sıçratmamak için hız ve rota ayarlamayı kavramak.',
    tags: ['empati', 'su-sicratma', 'otobus-duragi'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-410',
    subject: 'adab',
    topic: 'yaya-dikkati',
    difficulty: 'orta',
    stem: 'Kulaklık takıp telefonuyla ilgilenen bir yaya, trafiği hiç kontrol etmeden ilerideki geçide doğru yürüyor. Doğru yaklaşım hangisidir?',
    options: [
      '"Bakmıyorsa sorumluluk onda" deyip hızınızı korumak',
      'Uzun uzun korna çalıp irkilterek kendine getirmek',
      'Sizi fark etmemiş olabileceğini varsayıp hızı düşürmek ve durmaya hazır olmak',
      'Yanından hızla geçip gözünü korkutmak',
    ],
    answerIndex: 2,
    explanation:
      'Dikkati dağınık bir yaya çevresini algılamaz; sürücünün olgunluğu, karşısındakinin hatasını öngörüp kendi önlemini almasında görülür. Hızı düşürüp hazırlıklı olmak olası faciayı önler.',
    whyWrong: [
      'Kusur yayada olsa bile çarpmanın bedeli bir insan hayatıdır; "sorumluluk onda" savunması kimseyi geri getirmez.',
      'İrkiltmek yayayı öngörülemez bir yöne sıçratabilir; riski azaltmaz, büyütür.',
    ],
    objective: 'Dikkati dağınık yayaların hatasını öngörüp önlemi sürücü olarak almayı kavramak.',
    tags: ['yaya-dikkati', 'telefon', 'ongorulu-surus'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-411',
    subject: 'adab',
    topic: 'yaya-sorumlulugu',
    difficulty: 'kolay',
    stem: 'Yaya olarak karşıya geçeceksiniz; işaretli yaya geçidi yaklaşık otuz metre ileride. Trafik adabına uygun davranış hangisidir?',
    options: [
      'Bulunduğunuz yerden, araçların arasından hızlıca geçmek',
      'Araçlara el edip oldukları yerde durmalarını sağlamak',
      'Koşarak geçip süreyi kısaltmak',
      'Birkaç adım fazla yürüyüp geçidi kullanmak; sürücülerin sizi beklediği yerden geçmek',
    ],
    answerIndex: 3,
    explanation:
      'Trafik adabı yalnız sürücüler için değildir; yaya geçidi, sürücülerin yaya beklediği ve yavaşladığı yerdir. Otuz metrelik yürüyüş, öngörülemeyen bir noktada yola çıkmanın riskiyle kıyaslanamaz.',
    whyWrong: [
      'Araç aralarından çıkan yaya, sürücülerin en geç fark ettiği yayadır.',
      'Koşmak görüşü ve dengeyi bozar; riski azaltmaz, artırır.',
    ],
    objective: 'Yaya olarak da kurallara uyup geçitleri kullanma sorumluluğunu benimsemek.',
    tags: ['yaya-sorumlulugu', 'yaya-gecidi', 'kural-saygisi'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-412',
    subject: 'adab',
    topic: 'bisiklet-mesafesi',
    difficulty: 'orta',
    stem: 'Dar bir yolda önünüzde bisikletli var; karşıdan da araç geldiği için şu an güvenli yan mesafe bırakarak geçemiyorsunuz. Ne yapmalısınız?',
    options: [
      'Bisikletliyle karşı araç arasındaki boşluktan süzülerek geçmek',
      'Bisikletlinin arkasında sabırla bekleyip en az 1,5 metre yan mesafe bırakabileceğiniz uygun yerde geçmek',
      'Korna çalarak bisikletlinin banketten gitmesini sağlamak',
      'Bisikletliye iyice yaklaşıp geçme niyetinizi hissettirmek',
    ],
    answerIndex: 1,
    explanation:
      'Bisikletliyi geçerken yaklaşık 1,5 metre yan mesafe bırakılmalıdır; bu mesafe verilemiyorsa geçiş ertelenir. Birkaç saniyelik bekleyiş, bir insanın dengesi ve hayatıdır.',
    whyWrong: [
      'İki araç arasından süzülmek bisikletliyi hava akımı ve ani manevra riskiyle baş başa bırakır.',
      'Korna ve yakın takip, dengesi hassas bisikletliyi düşürebilecek baskı araçlarıdır.',
    ],
    objective:
      'Bisikletliyi geçerken 1,5 metre kuralını ve gerektiğinde geçişi ertelemeyi kavramak.',
    tags: ['bisiklet-mesafesi', 'yan-mesafe', 'sabir'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-413',
    subject: 'adab',
    topic: 'bisiklet-mesafesi',
    difficulty: 'orta',
    stem: 'Yol kenarına park ettiniz; kapıyı açıp ineceksiniz ve bu yoldan bisikletliler geçiyor. En güvenli alışkanlık hangisidir?',
    options: [
      'Kapıyı açmadan önce aynadan ve omuz üzerinden arkayı kontrol etmek; kapıya uzak elinizle açarak gövdenizi arkaya döndürmek',
      'Kapıyı hızla açıp hızla inmek; süre kısalırsa risk de azalır',
      'Önce kapıyı aralayıp bisikletlinin sizi görüp yavaşlamasını beklemek',
      'İnerken dörtlüleri yakmak; ışık yanıyorsa kontrol gerekmez',
    ],
    answerIndex: 0,
    explanation:
      'Aniden açılan kapı, bisikletlinin kaçamayacağı görünmez bir engeldir. Kapıya uzak elle açmak gövdeyi doğal olarak arkaya döndürür ve kör noktadaki bisikletliyi görmenizi sağlar.',
    whyWrong: [
      'Hızlı açmak riski kısaltmaz; bisikletlinin tepki süresini sıfırlar.',
      'Sorumluluğu bisikletliye atmak (görsün, yavaşlasın) kapıyı açanın yükümlülüğünü ortadan kaldırmaz.',
    ],
    objective: 'Kapı açarken arkayı kontrol etme alışkanlığıyla bisikletlileri korumayı öğrenmek.',
    tags: ['bisiklet-mesafesi', 'kapi-acma', 'kor-nokta'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-414',
    subject: 'adab',
    topic: 'paylasim',
    difficulty: 'orta',
    stem: 'Önünüzde elektrikli scooter kullanan biri var; dengesi bisikletliden bile hassas ve küçük tümseklerde zorlanıyor. Nasıl davranmalısınız?',
    options: [
      'Scooter yol aracı olmadığı için varlığını dikkate almamak',
      'Yakınından hızla geçip yolun taşıtlara ait olduğunu hatırlatmak',
      'Takip mesafesini artırmak ve geniş yan mesafeyle, hızı düşürerek geçmek',
      'Korna çalarak kaldırıma çıkmasını istemek',
    ],
    answerIndex: 2,
    explanation:
      'Küçük tekerlekli ve korumasız scooter kullanıcısı, trafikteki en kırılgan gruptandır; ona mesafe ve alan bırakmak, yolun tüm kullanıcılarla paylaşıldığını kabul etmenin gereğidir.',
    whyWrong: [
      'Yeni ulaşım araçlarını yok saymak, trafikte var olan gerçek bir insanı yok saymaktır.',
      'Yakın ve hızlı geçiş, oluşan hava akımıyla scooterlıyı devirebilir.',
    ],
    objective:
      'Scooter gibi yeni ve kırılgan yol kullanıcılarına mesafeyle saygı göstermeyi kavramak.',
    tags: ['paylasim', 'scooter', 'kirilgan-kullanici'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-415',
    subject: 'adab',
    topic: 'kamyon-kor-noktasi',
    difficulty: 'zor',
    stem: 'Kavşakta sağa dönüş sinyali veren uzun bir kamyonun sağında, dar bir boşluk var ve siz de sağa döneceksiniz. Bu boşluğa girmek neden yanlıştır?',
    options: [
      'Kamyonlar kavşakta her zaman sola döndüğü için',
      'Kamyon dönüşte uzunluğu nedeniyle sağa doğru yer kaplar ve sağ yanı sürücünün göremediği kör noktadır; araya giren araç ezilme riski altındadır',
      'Kamyonun yanından geçmek yalnızca yakıt israfına yol açtığı için',
      'Dar boşluktan geçmek aynaları çizebileceği için',
    ],
    answerIndex: 1,
    explanation:
      'Uzun araçlar dönüşe geniş başlar ve dönerken arka kısımları içeri süpürür; üstelik sağ yanları en derin kör noktalarıdır. Sinyal veren kamyonun sağına sokulmak, görünmeden ezilme riskinin ta kendisidir.',
    whyWrong: [
      'Sorun ayna çizmek gibi maddi bir detay değil, sürücünün sizi hiç görememesi ve dönüşte üzerinize gelmesidir.',
      'Kamyonun ne yöne döneceğini sinyali söyler; varsayımlarla değil işaretle hareket edilir.',
    ],
    objective: 'Dönen uzun araçların iç kör noktasına asla girilmemesi gerektiğini kavramak.',
    tags: ['kamyon-kor-noktasi', 'saga-donus', 'uzun-arac'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-416',
    subject: 'adab',
    topic: 'kamyon-kor-noktasi',
    difficulty: 'orta',
    stem: 'Büyük bir kamyonu arkadan takip ediyorsunuz. Kamyon sürücüsünün sizi görüp görmediğini nasıl değerlendirirsiniz?',
    options: [
      'Kamyonun büyüklüğü sayesinde sürücü arkasını her zaman görür',
      'Onun yan aynasında sürücüyü göremiyorsanız onun da sizi göremediğini bilir, konumunuzu buna göre ayarlarsınız',
      'Korna çalarak varlığınızı düzenli aralıklarla duyurursunuz',
      'İyice yaklaşırsanız sizi daha kolay fark eder',
    ],
    answerIndex: 1,
    explanation:
      'Basit ve güvenilir kural şudur: aynasında sürücüyü göremiyorsanız, o da sizi göremiyordur. Kamyonun hemen arkası derin bir kör noktadır; görünür konumda kalmak sizin elinizdedir.',
    whyWrong: [
      'Büyük araçların kör noktaları küçük araçlardan daha geniştir; büyüklük görüş sağlamaz.',
      'Yaklaştıkça kör noktanın daha da içine girersiniz; görünürlük mesafeyle artar, yakınlıkla değil.',
    ],
    objective: 'Ayna kuralıyla uzun araçların kör noktalarından uzak konumlanmayı öğrenmek.',
    tags: ['kamyon-kor-noktasi', 'ayna-kurali', 'takip-konumu'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-417',
    subject: 'adab',
    topic: 'yasam-koridoru',
    difficulty: 'orta',
    stem: 'Üç şeritli tek yönlü bir yolda trafik tamamen durdu ve arkadan ambulans sireni duyuluyor. Yaşam koridoru nasıl oluşturulmalıdır?',
    options: [
      'En soldaki şerit sola, diğer şeritlerdekiler sağa yanaşır; koridor en sol ile ortanca şerit arasında açılır',
      'Bütün araçlar olduğu yerde bekler; ambulans boşluk bulur',
      'Bütün araçlar en sağdaki emniyet şeridine geçer',
      'Sadece en arkadaki araçlar kenara çekilir',
    ],
    answerIndex: 0,
    explanation:
      'Yaygın uygulamada en soldaki araçlar sola, kalan şeritlerdekiler sağa yanaşır; böylece acil aracın kullanacağı sürekli bir koridor sol tarafta açılır. Herkesin aynı düzeni bilmesi koridoru hızlı oluşturur.',
    whyWrong: [
      'Kimse hareket etmezse siren yaklaşınca panik manevraları başlar; düzenli koridor bunu önler.',
      'Herkesin sağa yığılması emniyet şeridini tıkar ve tek taraflı bir düğüm yaratır.',
    ],
    objective: 'Çok şeritli yolda yaşam koridorunun hangi düzenle açıldığını öğrenmek.',
    tags: ['yasam-koridoru', 'ambulans', 'cok-serit'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-418',
    subject: 'adab',
    topic: 'yasam-koridoru',
    difficulty: 'zor',
    stem: 'Bölünmemiş iki yönlü bir yolda karşı yönden siren çalan bir ambulans yaklaşıyor; kendi şeridi yoğun. Siz ne yapmalısınız?',
    options: [
      'Karşı yöndeki araç sizi ilgilendirmediği için hiçbir şey yapmamak',
      'Hızlanıp ambulans gelmeden önce o bölgeden uzaklaşmak',
      'Hızı azaltıp sağa yanaşmak; ambulansın gerektiğinde sizin şeridinizi kullanarak geçebilmesine alan bırakmak',
      'Uzun far yakarak ambulansı kendi şeridinde kalması için uyarmak',
    ],
    answerIndex: 2,
    explanation:
      'Bölünmemiş yolda sıkışan ambulans çoğu kez karşı şeride taşarak ilerler; sizin sağa yanaşmanız ona bu manevra için güvenli alan açar. Geçiş üstünlüğü yönden bağımsız bir sorumluluktur.',
    whyWrong: [
      '"Karşı yön beni ilgilendirmez" yaklaşımı, ambulansın tek geçiş seçeneğini kapatabilir.',
      'Hızlanmak hem tehlikelidir hem de ambulansla aynı noktada buluşma riskinizi artırır.',
    ],
    objective:
      'Bölünmemiş yolda karşı yönden gelen acil araca da alan açma sorumluluğunu kavramak.',
    tags: ['yasam-koridoru', 'gecis-ustunlugu', 'iki-yonlu-yol'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-419',
    subject: 'adab',
    topic: 'engelli-hakki',
    difficulty: 'orta',
    stem: 'Engelli park yerine, engelli kartı olmayan bir aracın park ettiğini gördünüz. En uygun davranış hangisidir?',
    options: [
      'Aracın önünü kendi aracınızla kapatıp sahibine ders vermek',
      'Durumu otopark görevlisine veya yetkililere bildirmek; kavga ve cezalandırma işini üstlenmemek',
      'Aracın camına hakaret içeren bir not bırakmak',
      'Madem yer işgal edilmiş, siz de başka bir engelli yerine park etmek',
    ],
    answerIndex: 1,
    explanation:
      'Haksızlığa tepkiniz haklı olabilir; ancak yaptırım uygulamak vatandaşın değil yetkilinin işidir. Bildirmek sorunu çözer, kavga ise yeni bir sorun yaratır.',
    whyWrong: [
      'Aracın önünü kesmek sizi de ihlalci yapar ve gerginliği fiziksel çatışmaya taşıyabilir.',
      'Bir ihlale başka bir ihlalle karşılık vermek, engelli bireylerin hakkını iki kez gasbeder.',
    ],
    objective: 'Kural ihlaline öfkeyle değil, doğru mercie bildirerek tepki vermeyi öğrenmek.',
    tags: ['engelli-hakki', 'ihlal-bildirimi', 'sakinlik'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-420',
    subject: 'adab',
    topic: 'park-gorgusu',
    difficulty: 'kolay',
    stem: 'Kalabalık bir otoparkta aracınızı bıraktınız; ancak çizgilerin üzerine denk gelip iki park yerini birden kapattığınızı fark ettiniz. Ne yaparsınız?',
    options: [
      'Kısa süre kalacaksanız aracı öyle bırakmak',
      '"Nasılsa başka yer bulurlar" deyip gitmek',
      'Dörtlüleri yakıp iki yeri kapattığınızı belirtmek',
      'Kısa bir manevrayla aracı tek park yerinin sınırları içine almak',
    ],
    answerIndex: 3,
    explanation:
      'Bir dakikalık düzeltme manevrası, bir başka sürücünün dakikalarca yer aramasını önler. Park çizgileri, sınırlı alanı adil paylaşmanın sessiz sözleşmesidir.',
    whyWrong: [
      '"Kısa süre" mazereti, o sürede yer arayan sürücünün kaybettiği zamanı geri getirmez.',
      'Dörtlü yakmak işgali meşrulaştırmaz; işaret vermek düzeltmenin yerini tutmaz.',
    ],
    objective: 'Park alanını tek araçlık sınırlar içinde kullanma görgüsünü benimsemek.',
    tags: ['park-gorgusu', 'cizgi-ihlali', 'paylasim'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-421',
    subject: 'adab',
    topic: 'park-gorgusu',
    difficulty: 'kolay',
    stem: 'Otoparkta boş bir yer gördünüz; ancak başka bir sürücünün sinyal vererek o yer için beklediği açıkça belli. Ne yaparsınız?',
    options: [
      'Önce davrananın hakkına saygı gösterip kendinize başka yer aramak',
      'Daha çevik davranıp yeri ondan önce kapmak',
      'Yerin ortasına yaya olarak birini dikip aracınızı getirmek',
      'Korna çalarak yeri sizin gördüğünüzü ilan etmek',
    ],
    answerIndex: 0,
    explanation:
      'Sinyal vererek bekleyen sürücü o yer üzerindeki niyetini herkese duyurmuştur; sıraya saygı, otoparkta da geçerli bir adap kuralıdır. Kapılan yer kazanç değil, gerginlik kaynağıdır.',
    whyWrong: [
      'Yer kapmak birkaç dakika kazandırırken karşı tarafta öfke ve çatışma doğurur.',
      'Yer tutmak için insan dikmek hem tehlikeli hem de hakkaniyete aykırıdır.',
    ],
    objective: 'Park yerinde bekleme sırasına ve ilk gelenin hakkına saygıyı benimsemek.',
    tags: ['park-gorgusu', 'sira-hakki', 'nezaket'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-422',
    subject: 'adab',
    topic: 'park-gorgusu',
    difficulty: 'orta',
    stem: 'Kısa bir işiniz için aracınızı yaya geçidinin hemen bitişiğine park etmek istiyorsunuz. Bu neden sakıncalıdır?',
    options: [
      'Aracınız egzoz gazıyla yayaları rahatsız edeceği için',
      'Park süresi kısa olunca ceza yazılamayacağı için',
      'Park eden araç, geçide adım atan yayayı — özellikle kısa boylu çocukları — sürücülerin görüşünden gizler ve kaza riskini büyütür',
      'Aracın lastikleri geçit boyalarını aşındıracağı için',
    ],
    answerIndex: 2,
    explanation:
      'Geçidin dibine park eden araç bir görüş duvarı oluşturur: yaklaşan sürücü, aracın arkasından çıkan yayayı ancak son anda görür. Bu yüzden geçit çevresi park için değil, görüş için boş bırakılır.',
    whyWrong: [
      'Sorun estetik ya da egzoz değil, görüş hattının kapanmasıyla doğan can tehlikesidir.',
      'Sürenin kısalığı riski küçültmez; kaza için tek bir an yeterlidir.',
    ],
    objective: 'Yaya geçidi çevresinin görüş güvenliği için boş bırakılması gerektiğini kavramak.',
    tags: ['park-gorgusu', 'gorus-hatti', 'yaya-guvenligi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-423',
    subject: 'adab',
    topic: 'park-gorgusu',
    difficulty: 'orta',
    stem: 'Market önünde boş yer yok; aracınızı kısa süreliğine otobüs durağının cebine bırakmayı düşünüyorsunuz. Doğru değerlendirme hangisidir?',
    options: [
      'Otobüs gelmeden dönerseniz sakıncası yoktur',
      'Durağı işgal etmek otobüsü yolun ortasında durmaya zorlar; yolcular taşıt yoluna iner ve trafik tıkanır — durağa park edilmez',
      'Dörtlü yakılırsa durakta beklemek serbesttir',
      'Duraklar geceleri park yeri olarak kullanılabilir',
    ],
    answerIndex: 1,
    explanation:
      'Durak cebi, otobüsün yoldan çekilip yolcularını güvenle indirebilmesi için tasarlanmıştır; orayı işgal eden araç, inen yaşlıyı da bebek arabalı yolcuyu da taşıt yolunun ortasına mecbur eder.',
    whyWrong: [
      '"Otobüs gelmeden dönerim" hesabı çoğu zaman tutmaz; otobüs tarifesi size göre işlemez.',
      'Dörtlü lambalar işgale meşruiyet kazandıran bir sihirli düğme değildir.',
    ],
    objective: 'Otobüs duraklarının işlevini ve neden işgal edilmemesi gerektiğini kavramak.',
    tags: ['park-gorgusu', 'otobus-duragi', 'toplu-tasima'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-424',
    subject: 'adab',
    topic: 'nezaket',
    difficulty: 'kolay',
    stem: 'Kalabalık bir akaryakıt istasyonunda yakıt aldınız; ödeme yapacak ve marketten alışveriş de yapacaksınız. Görgülü davranış hangisidir?',
    options: [
      'Aracı pompanın önünde bırakıp bütün işleri halletmek',
      'Alışverişi uzatıp aracı pompada dinlendirmek',
      'Sıradakilerin beklemesinde sakınca yoktur; herkes sırasını savar',
      'Mümkünse aracı pompanın önünden çekip uygun bir yere aldıktan sonra ödeme ve alışverişi yapmak',
    ],
    answerIndex: 3,
    explanation:
      'Pompa, istasyonun ortak ve dar kaynağıdır; yakıtı biten aracın çekilmesi, arkadaki sürücülerin gereksiz beklemesini önler. Küçük bir zahmet, herkes için akıcılık demektir.',
    whyWrong: [
      'Pompayı market otoparkı gibi kullanmak, sırada bekleyen herkesin dakikalarını harcar.',
      '"Herkes bekler" bakışı, sizin başkasını beklettiğiniz gerçeğini değiştirmez.',
    ],
    objective:
      'Ortak kullanılan dar alanlarda (pompa vb.) işgal süresini kısaltma görgüsünü edinmek.',
    tags: ['nezaket', 'akaryakit-istasyonu', 'ortak-alan'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-425',
    subject: 'adab',
    topic: 'cevre-gorgusu',
    difficulty: 'kolay',
    stem: 'Seyir hâlindeyken yolcunuz, boş pet şişeyi camdan atmak üzere. Ne yaparsınız?',
    options: [
      'Nazikçe engelleyip şişeyi araçtaki atık torbasında biriktirmesini, ilk molada geri dönüşüme atacağınızı söylemek',
      'Araç sizin olsa da davranış onun; karışmamak',
      'Cam kenarına atmasını, yol kenarının zaten kirli olduğunu söylemek',
      'Şişeyi siz alıp bir sonraki boş araziye atmak',
    ],
    answerIndex: 0,
    explanation:
      'Araçtan savrulan atık hem doğayı kirletir hem arkadan gelenler için tehlike oluşturur. Sürücü, aracındaki yolcuların çevreye verdiği zarardan da sorumludur; kibar bir uyarı çoğu zaman yeterlidir.',
    whyWrong: [
      'Sessiz kalmak, çevreye verilen zarara ortak olmaktır.',
      '"Zaten kirli" mantığı kirliliği normalleştirir; her atık bir öncekine eklenir.',
    ],
    objective:
      'Araç içindeki atık yönetiminde yolcuları da kapsayan çevre sorumluluğunu üstlenmek.',
    tags: ['cevre-gorgusu', 'atik', 'yolcu'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-426',
    subject: 'adab',
    topic: 'gurultu-gorgusu',
    difficulty: 'kolay',
    stem: 'Bir arkadaşınız, aracına yüksek ses çıkaran modifiyeli bir egzoz taktırmayı "havalı" bulduğunu söylüyor. Trafik adabı açısından doğru değerlendirme hangisidir?',
    options: [
      'Ses, aracın fark edilmesini sağladığı için güvenliğe katkıdır',
      'Gece kullanılmadığı sürece sorun yoktur',
      'Bu egzozlar gürültü kirliliği yaratır; hastaları, yaşlıları, bebekleri ve tüm çevreyi rahatsız eder — hem kural ihlali hem görgüsüzlüktür',
      'Şehir dışında serbest olduğu için sakıncası yoktur',
    ],
    answerIndex: 2,
    explanation:
      'Egzoz gürültüsü, dinlemek istemeyen binlerce insana zorla dinletilen bir sestir; uyuyan bebekten hastanedeki hastaya kadar herkesi etkiler. Araçların gürültü sınırları bu yüzden mevzuatla belirlenmiştir.',
    whyWrong: [
      '"Fark edilme" bahanesi, sürekli ve rahatsız edici gürültünün mazereti olamaz.',
      'Gürültü kirliliği saat ve yer ayrımı olmaksızın çevre hakkı ihlalidir.',
    ],
    objective: 'Araç gürültüsünün çevre hakkına etkisini ve gürültü görgüsünü kavramak.',
    tags: ['gurultu-gorgusu', 'egzoz', 'cevre-hakki'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-427',
    subject: 'adab',
    topic: 'sorumluluk',
    difficulty: 'kolay',
    stem: 'Kar yağışının ardından yola çıkacaksınız; aracınızın camlarında ve tavanında kalın bir kar tabakası var. Doğru davranış hangisidir?',
    options: [
      'Sadece ön camda küçük bir görüş deliği açıp yola çıkmak',
      'Yola çıkmadan önce tüm camları, farları, plakayı ve tavandaki karı temizlemek; seyirde savrulan kar arkadakilerin görüşünü kapatabilir',
      'Kar nasılsa rüzgârla uçar; hiçbir şey yapmadan çıkmak',
      'Silecekleri çalıştırıp gerisini yola bırakmak',
    ],
    answerIndex: 1,
    explanation:
      'Tavandaki kar, fren anında ön cama kayarak sizi kör edebilir; seyir hâlinde savrulan kütleler ise arkadaki araçların camına iner. Birkaç dakikalık temizlik, hem sizin hem başkalarının görüşünü korur.',
    whyWrong: [
      'Küçük bir delikten bakmak, yanlardan ve aynalardan gelen tüm bilgiyi yok sayar.',
      'Uçan kar rastgele değil, tam arkanızdaki aracın üstüne gider; sorumluluk sizindir.',
    ],
    objective:
      'Kışın araç üzerindeki karın kendisi ve başkaları için temizlenme sorumluluğunu kavramak.',
    tags: ['sorumluluk', 'kar-temizligi', 'gorus'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-428',
    subject: 'adab',
    topic: 'ofke-fizyolojisi',
    difficulty: 'zor',
    stem: 'Trafikte öfkelendiğinizde kalp atışınız hızlanır ve vücudunuz strese hazırlanır. Bu fizyolojik durumun sürüş açısından en önemli sonucu nedir?',
    options: [
      'Refleksler güçlendiği için daha iyi araç kullanılır',
      'Öfke yalnızca ses tonunu etkiler; sürüş becerisi değişmez',
      'Vücut birkaç saniyede eski hâline döner; kalıcı etkisi yoktur',
      'Dikkat daralır, riskler olduğundan küçük görünür ve karar kalitesi düşer; sakinleşmeden önemli manevra kararı verilmemelidir',
    ],
    answerIndex: 3,
    explanation:
      'Öfke anında beden "savaş" moduna geçer: bakış açısı daralır, sabır azalır ve riskli seçenekler cazip görünür. Bu yüzden soğuma teknikleri — derin nefes, mesafe açma, gerekirse mola — öfke geçmeden karar almayı erteler.',
    whyWrong: [
      'Hızlanan refleks, bozulan muhakemeyi telafi etmez; yanlış karara daha hızlı ulaşırsınız.',
      'Stres hormonlarının etkisi dakikalarca sürer; "bir saniyede geçti" hissi yanıltıcıdır.',
    ],
    objective: 'Öfkenin algı ve karar süreçlerine fizyolojik etkisini bilerek soğumayı öncelemek.',
    tags: ['ofke-fizyolojisi', 'sogutma-teknikleri', 'karar-kalitesi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-429',
    subject: 'adab',
    topic: 'ofke-fizyolojisi',
    difficulty: 'orta',
    stem: 'Evde yaşadığınız büyük bir tartışmanın hemen ardından öfkeyle çıktınız ve direksiyona geçmek üzeresiniz. En doğru davranış nedir?',
    options: [
      'Yola çıkmayı erteleyip birkaç dakika yürüyerek veya derin nefes alarak sakinleşmek; öfkeliyken direksiyona geçmemek',
      'Hemen yola çıkmak; araç kullanmak sinir boşaltmanın iyi bir yoludur',
      'Müziği sonuna kadar açıp hızlanarak kafa dağıtmak',
      'Öfkeyi bastırmak için bir an önce trafiğe karışıp meşgul olmak',
    ],
    answerIndex: 0,
    explanation:
      'Trafiğe taşınan öfke, yoldaki en küçük aksaklığı bile kavga sebebine çevirir. Direksiyona ancak zihin sakinleştikten sonra geçmek, kendinize ve başkalarına karşı temel bir sorumluluktur.',
    whyWrong: [
      'Aracı sinir boşaltma aracı olarak kullanmak, gaz pedalını öfkenin emrine vermektir.',
      'Yüksek müzik ve hız öfkeyi bastırmaz; riskli davranışı besler.',
    ],
    objective: 'Duygusal olarak sarsılmışken sürüşü erteleme alışkanlığını kazanmak.',
    tags: ['ofke-fizyolojisi', 'soguma', 'suruse-hazirlik'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-430',
    subject: 'adab',
    topic: 'guvenli-mesafe',
    difficulty: 'orta',
    stem: 'Trafikte makas atarak ilerleyen agresif bir sürücü bir süredir çevrenizde tehlikeli manevralar yapıyor. En doğru davranış hangisidir?',
    options: [
      'Şerit değiştirmesini engelleyerek ona bir ders vermek',
      'Peşine takılıp plakasını okumaya çalışmak',
      'Onunla hiç etkileşime girmeden hızınızı ve şeridinizi koruyup aranızdaki mesafeyi açmak; gerekirse yol vermek',
      'Aynı manevraları yaparak ondan uzaklaşmak',
    ],
    answerIndex: 2,
    explanation:
      'Agresif sürücüyle mücadele etmek, onun riskini kendi üzerinize almaktır. En güvenli strateji görünmez olmaktır: mesafe açın, öngörülebilir seyredin ve tehlikenin uzaklaşmasına izin verin.',
    whyWrong: [
      'Engelleme ve ders verme girişimleri, agresif sürücünün hedefini siz yaparsınız.',
      'Onun tarzını taklit etmek, yoldaki tehlikeli araç sayısını bire değil ikiye çıkarır.',
    ],
    objective: 'Hatalı ve agresif sürücülere tepki yerine mesafeyle karşılık vermeyi öğrenmek.',
    tags: ['guvenli-mesafe', 'agresif-surucu', 'etkilesimden-kacinma'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-431',
    subject: 'adab',
    topic: 'ozur-dileme',
    difficulty: 'kolay',
    stem: 'Dalgınlıkla sinyal vermeden şerit değiştirdiniz ve bir sürücüyü fren yapmak zorunda bıraktınız; hatanızı fark ettiniz. Ne yaparsınız?',
    options: [
      'Hiçbir şey olmamış gibi devam etmek; nasılsa bir daha karşılaşmazsınız',
      'Elinizi kaldırıp özür anlamına gelen bir işaret yapmak, hatayı üstlenmek ve sürüşe daha dikkatli devam etmek',
      'Suçu karşı tarafın hızlı gelmesine atmak',
      'Durup aracından inerek yüz yüze özür dilemek',
    ],
    answerIndex: 1,
    explanation:
      'Elin kalkıp hafifçe sallanması, trafikte "kusura bakma, hatam" demenin evrensel yoludur. Bu küçük işaret karşı tarafın öfkesini çoğu zaman anında söndürür ve olası bir gerginliği başlamadan bitirir.',
    whyWrong: [
      'Hatayı görmezden gelmek, mağdur sürücünün öfkesini büyütür ve yol öfkesini tetikleyebilir.',
      'Akan trafikte durup inmek, özrü yeni bir tehlikeye dönüştürür; işaret yeterlidir.',
    ],
    objective: 'Trafikte hatayı üstlenip el işaretiyle özür dileme görgüsünü edinmek.',
    tags: ['ozur-dileme', 'el-isareti', 'iletisim'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-432',
    subject: 'adab',
    topic: 'nezaket',
    difficulty: 'kolay',
    stem: 'Yol verdiğiniz sürücü hiçbir teşekkür işareti yapmadan geçip gitti ve buna içerlediniz. Olgun yaklaşım hangisidir?',
    options: [
      'Bir daha kimseye yol vermemeye karar vermek',
      'Peşinden gidip neden teşekkür etmediğini sormak',
      'Arkasından korna çalarak sitem etmek',
      'Nezaketin karşılık beklemeden yapıldığını hatırlayıp durumu dert etmemek; doğru davranış kendi başına değerlidir',
    ],
    answerIndex: 3,
    explanation:
      'Trafik adabı bir alışveriş değildir; yol vermenin amacı teşekkür toplamak değil, trafiği güvenli ve insani kılmaktır. Karşılık gelmediğinde bozulmak, iyiliği pazarlığa çevirir.',
    whyWrong: [
      'Tek bir nezaketsizlik yüzünden herkesi cezalandırmak, sizi de kaba sürücülerden birine dönüştürür.',
      'Sitem kornası ve takip, küçük bir kırgınlığı gereksiz bir gerginliğe büyütür.',
    ],
    objective: 'Nezaketi karşılık beklentisinden bağımsız bir ilke olarak içselleştirmek.',
    tags: ['nezaket', 'beklentisizlik', 'olgunluk'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-433',
    subject: 'adab',
    topic: 'yolcu-sorumlulugu',
    difficulty: 'kolay',
    stem: 'Arkadaşınız sizi aracıyla bırakıyor ve tam kapınızın önünde, dönemecin üzerinde durmayı teklif ediyor. İyi bir yolcu olarak ne yaparsınız?',
    options: [
      'Trafiği ve görüşü engellemeyecek güvenli bir yerde inmeyi önermek; birkaç adım yürümeyi göze almak',
      'Kapının önünde inmekte ısrar etmek; yolculuğun amacı budur',
      'Dönemecin üzerinde dörtlü yaktırarak inmek',
      'Araç yavaşlamışken hareket hâlinde atlamak',
    ],
    answerIndex: 0,
    explanation:
      'İniş noktasını seçmek de yolcunun sorumluluğudur: dönemeç üzerinde duran araç, arkadan gelenlerin göremeyeceği bir engeldir. Birkaç adımlık yürüyüş, herkes için güvenli bir vedadır.',
    whyWrong: [
      'Konfor için ısrar etmek, sürücüyü tehlikeli bir noktada durmaya zorlar.',
      'Dörtlü lamba, görüşe kapalı yerde durmanın riskini ortadan kaldırmaz.',
    ],
    objective: 'Yolcu olarak iniş-biniş noktasının güvenliğini gözetme sorumluluğunu benimsemek.',
    tags: ['yolcu-sorumlulugu', 'inis-binis', 'guvenli-nokta'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-434',
    subject: 'adab',
    topic: 'yolcu-sorumlulugu',
    difficulty: 'orta',
    stem: 'Yolcu olduğunuz araçta sürücü bir yandan mesaj yazmaya çalışıyor. En doğru davranış hangisidir?',
    options: [
      'Karışmamak; araç ve ehliyet onun',
      'Telefonu elinden çekip almak',
      'Kırıcı olmadan telefonu bırakmasını rica etmek; mesaj acilse onun yerine sizin yazmayı teklif etmek',
      'Siz de telefonunuza gömülüp görmezden gelmek',
    ],
    answerIndex: 2,
    explanation:
      'O araçtaki yaşamlardan biri de sizinki; sessiz kalmak riske ortak olmaktır. Yardım teklifiyle birleşen nazik bir uyarı, sürücüyü savunmaya itmeden sorunu çözer.',
    whyWrong: [
      '"Araç onun" düşüncesi, kazanın sonuçlarının herkese ait olduğunu unutturur.',
      'Telefonu çekip almak ani bir irkilme ve direksiyon hatası yaratabilir.',
    ],
    objective:
      'Yolcunun, sürücünün dikkat dağıtıcı davranışına yapıcı biçimde müdahale etmesini öğrenmek.',
    tags: ['yolcu-sorumlulugu', 'telefon', 'yapici-uyari'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-435',
    subject: 'adab',
    topic: 'akran-baskisi',
    difficulty: 'orta',
    stem: 'Araçtaki arkadaşlarınız, yan şeritteki tanıdıkla "yarışmanız" için sizi gaza getirmeye çalışıyor. Ne yaparsınız?',
    options: [
      'Kısa bir hızlanmayla gönüllerini alıp sonra yavaşlamak',
      'Teklifi kesin bir dille reddedip hız sınırında sürmeye devam etmek; direksiyondayken kararların yalnız sürücüye ait olduğunu hatırlatmak',
      'Trafiğin boş olduğu bir yerde denemek',
      'Arkadaşlarınız bozulmasın diye isteklerine uymak',
    ],
    answerIndex: 1,
    explanation:
      'Direksiyondaki kişi, araçtaki herkesin hayatının emanetçisidir; bu emanet alkışla ya da ısrarla devredilemez. Akran baskısına verilecek en olgun yanıt, net ve tartışmasız bir "hayır"dır.',
    whyWrong: [
      '"Kısa bir hızlanma" da yarıştır; kaza için tek bir an yeterlidir.',
      'Boş yol yanılsaması, yarış kazalarının en sık kurulduğu tuzaktır.',
    ],
    objective: 'Sürücü olarak akran baskısına karşı net sınır koymayı öğrenmek.',
    tags: ['akran-baskisi', 'yaris', 'sinir-koyma'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-436',
    subject: 'adab',
    topic: 'kural-saygisi',
    difficulty: 'kolay',
    stem: 'Trafik durma noktasında ve birçok araç emniyet şeridinden ilerliyor; "herkes gidiyor" düşüncesi size de cazip gelmeye başladı. Doğru değerlendirme hangisidir?',
    options: [
      'Çoğunluk yapıyorsa artık kural fiilen değişmiş demektir',
      'Kısa mesafede kullanmak ihlal sayılmaz',
      'Cezadan korkmuyorsanız kullanabilirsiniz',
      'Çoğunluğun ihlali kuralı değiştirmez; emniyet şeridi acil durumlar ve acil araçlar içindir, boş bırakılmalıdır',
    ],
    answerIndex: 3,
    explanation:
      'Emniyet şeridi, o anda göremediğiniz bir kazazedenin ambulans yoludur. Kaç kişinin ihlal ettiği önemli değildir; şeridi boş tutan her sürücü, o koridoru bir başkasının hayatı için korur.',
    whyWrong: [
      '"Herkes yapıyor" sürü psikolojisidir; ihlalin yaygınlığı onu haklı çıkarmaz.',
      'Meselenin özü ceza değil, tıkanan şeridin geciktirdiği yardımdır.',
    ],
    objective: 'Sürü psikolojisine kapılmadan emniyet şeridinin amacına sadık kalmayı öğrenmek.',
    tags: ['kural-saygisi', 'emniyet-seridi', 'suru-psikolojisi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-437',
    subject: 'adab',
    topic: 'kural-saygisi',
    difficulty: 'kolay',
    stem: 'Gideceğiniz sokağa ulaşmak için tek yönlü yolda yalnızca elli metre ters yönde ilerlemek işinizi epey kısaltacak. Ne yaparsınız?',
    options: [
      'Kısa da olsa ters yöne girmeyip kurallara uygun güzergâhtan dolaşmak',
      'Dörtlüleri yakıp yavaşça ters yönde ilerlemek',
      'Yol boşsa hızlıca girip çıkmak',
      'Geri viteste giderek "ters yöne girmemiş" olmak',
    ],
    answerIndex: 0,
    explanation:
      'Tek yönlü yoldaki sürücüler ve yayalar karşıdan araç gelmeyeceğine güvenerek hareket eder; elli metrelik ihlal bu güveni bozar ve en beklenmedik anda burun buruna gelmeyle sonuçlanır.',
    whyWrong: [
      'Dörtlü lamba veya düşük hız, ihlalin yarattığı sürpriz unsurunu ortadan kaldırmaz.',
      'Geri viteste gitmek de aynı yönde harekettir; kuralı dolanmak kurala uymak değildir.',
    ],
    objective: 'Kısa ve "zararsız" görünen ihlallerin güven düzenini bozduğunu kavramak.',
    tags: ['kural-saygisi', 'ters-yon', 'guven'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-438',
    subject: 'adab',
    topic: 'kural-saygisi',
    difficulty: 'orta',
    stem: 'Kavşağa yaklaşırken ışık yeşilden sarıya döndü ve güvenle durabileceğiniz mesafedesiniz. Doğru davranış hangisidir?',
    options: [
      'Gaza basıp sarı bitmeden kavşağı geçmek',
      'Ani fren yapıp olduğunuz yerde durmak',
      'Hızlanmak yerine yavaşlayıp duruş çizgisinde durmak; sarı ışık durmaya hazırlanma ve kavşağı boşaltma uyarısıdır',
      'Kavşağa girip ortasında ışığın dönmesini beklemek',
    ],
    answerIndex: 2,
    explanation:
      'Sarı ışık bir yarış başlatma tabancası değil, "duruşa hazırlan" uyarısıdır. Sarıda gaza basan sürücü, kırmızıya kalan kavşakta yan yönden erken kalkan araçla buluşma riskini satın alır.',
    whyWrong: [
      'Sarıda hızlanmak, kavşak kazalarının en klasik senaryosudur.',
      'Güvenle durulabilecekken ani fren de gereksizdir; kontrollü yavaşlama esastır.',
    ],
    objective: 'Sarı ışığın hızlanma değil durma uyarısı olduğunu içselleştirmek.',
    tags: ['kural-saygisi', 'sari-isik', 'kavsak'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-439',
    subject: 'adab',
    topic: 'serit-izleme',
    difficulty: 'zor',
    stem: 'Kavşakta sola dönmeniz gerektiğini son anda fark ettiniz; ancak en sağ şeritte kaldınız. En doğru davranış hangisidir?',
    options: [
      'Sinyal verip birkaç şeridi birden keserek sol şeride geçmek',
      'Bulunduğunuz şeridin yönüne uygun devam edip dönüşü ileride güvenli ve kurallı bir noktadan planlamak',
      'Kavşak içinde yavaşlayıp diğer araçların size yol açmasını beklemek',
      'Durup geri geri giderek sol şeride ulaşmak',
    ],
    answerIndex: 1,
    explanation:
      'Yanlış şeritte kalmanın bedeli birkaç dakikalık dolaşmaktır; son anda şerit kesmenin bedeli ise kaza olabilir. Navigasyon her zaman yeni rota bulur — olgun sürücü rotayı değil, güvenliği korur.',
    whyWrong: [
      'Kavşak ağzında çoklu şerit değişimi, yan araçlara tepki şansı bırakmaz.',
      'Kavşakta durmak, beklemek veya geri gitmek arkadan gelen akışı tehlikeye atar.',
    ],
    objective: 'Yanlış şeritte kalınca manevrayı değil rotayı düzeltmeyi öğrenmek.',
    tags: ['serit-izleme', 'yanlis-serit', 'rota-duzeltme'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-440',
    subject: 'adab',
    topic: 'nezaket',
    difficulty: 'kolay',
    stem: 'Dar bir sokakta karşı yönden gelen tanıdığınızla karşılaştınız ve camdan cama kısa bir sohbet etmek istiyorsunuz. Doğru davranış hangisidir?',
    options: [
      'Araçları yan yana durdurup sohbeti kısa tutmak',
      'Dörtlüleri yakıp arkadakilerin beklemesinde sakınca görmemek',
      'Arkadan gelen olursa el sallayıp beklemesini istemek',
      'Selamlaşıp geçmek; sohbet gerekiyorsa uygun bir yere park ederek görüşmek',
    ],
    answerIndex: 3,
    explanation:
      'Yol, sohbet salonu değil ortak geçiş alanıdır; yan yana duran iki araç sokağı tamamen kilitler. Gerçek nezaket tanıdığa değil, arkada bekleyen herkese gösterilendir.',
    whyWrong: [
      '"Kısa sohbet" bile arkada kuyruk oluşturur; kısalığın ölçüsü bekleyene göre değişir.',
      'Dörtlü yakmak veya el sallamak, yolu işgal etme hakkı vermez.',
    ],
    objective: 'Yol üzerinde durarak trafiği bekletmemeyi ve sohbeti uygun yere taşımayı öğrenmek.',
    tags: ['nezaket', 'yol-isgali', 'dusuncelilik'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-441',
    subject: 'adab',
    topic: 'hayvan-duyarliligi',
    difficulty: 'orta',
    stem: 'Gece yerleşim yerinde önünüze aniden bir kedi çıktı; arkanızda da bir araç var. En doğru tepki hangisidir?',
    options: [
      'Direksiyonu ani kırmadan kontrollü şekilde yavaşlamak; aynadan arkayı kontrol edip güvenliyse durmak',
      'Direksiyonu sert kırıp karşı şeride kaçmak',
      'Gözlerinizi kapatıp hızı korumak',
      'Korna çalıp hız kesmeden devam etmek',
    ],
    answerIndex: 0,
    explanation:
      'Hayvana duyarlılık ile trafik güvenliği birlikte düşünülür: kontrollü yavaşlama çoğu zaman canlıyı kurtarır; ani direksiyon ise arkadaki ve karşıdaki insanları tehlikeye atar. Önce kontrol, sonra merhamet — ikisi bir arada mümkündür.',
    whyWrong: [
      'Sert direksiyon manevrası, bir hayvanı kurtarırken bir insanı kaybettirebilir.',
      'Hiç tepki vermemek de duyarsızlıktır; kontrollü yavaşlamak çoğu durumda yeterlidir.',
    ],
    objective: 'Yola çıkan hayvanlara kontrollü ve güvenli biçimde tepki vermeyi öğrenmek.',
    tags: ['hayvan-duyarliligi', 'ani-durum', 'kontrollu-tepki'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-442',
    subject: 'adab',
    topic: 'sorumluluk',
    difficulty: 'orta',
    stem: 'Seyir hâlindeyken şeridin ortasına düşmüş büyük bir yük (örneğin bir mobilya parçası) gördünüz ve son anda çarpmadan geçtiniz. Sorumlu davranış hangisidir?',
    options: [
      'Siz kurtulduğunuza göre yola devam etmek',
      'Sosyal medyada paylaşmak üzere seyir hâlinde video çekmek',
      'Güvenli bir yerde durup durumu acil çağrı merkezine (112) bildirmek; arkadan gelenler için ciddi tehlike oluşturur',
      'Geri geri gidip cismi kendiniz kaldırmaya çalışmak',
    ],
    answerIndex: 2,
    explanation:
      'Sizin atlattığınız tehlike, arkadan gelen ve daha az şanslı olan sürücüyü bekliyor. Güvenli yerden yapılan bir bildirim, ekiplerin cismi kaldırmasını sağlar ve görmediğiniz bir kazayı önler.',
    whyWrong: [
      '"Ben kurtuldum" deyip gitmek, tehlikeyi arkadakilere miras bırakmaktır.',
      'Akan trafikte geri gitmek veya yola inmek, bir tehlikeyi ikiye katlar.',
    ],
    objective: 'Yoldaki tehlikeleri yetkililere bildirme sorumluluğunu benimsemek.',
    tags: ['sorumluluk', 'tehlike-bildirimi', 'dayanisma'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-443',
    subject: 'adab',
    topic: 'kaza-yeri-gorgusu',
    difficulty: 'orta',
    stem: 'Yol kenarında maddi hasarlı bir kaza var; ekipler gelmiş, yardımınıza ihtiyaç yok. Ne yapmalısınız?',
    options: [
      'İyice yavaşlayıp olayı detaylıca izlemek',
      'Yavaşlamayı abartmadan, telefonla görüntü almadan dikkatinizi yola verip geçmek',
      'Telefonla video çekip sosyal medyada paylaşmak',
      'Durup ekiplere akıl vermek',
    ],
    answerIndex: 1,
    explanation:
      'Kaza yerinde dikizleme ve çekim yapma merakı, arkada ani frenlere ve yeni kazalara yol açar; üstelik kazazedelerin zor anını görüntülemek mahremiyetlerine saygısızlıktır. İhtiyaç yoksa en iyi yardım, akıcı ve dikkatli geçiştir.',
    whyWrong: [
      'İzlemek için yavaşlayan her araç, arkasında bir fren zinciri başlatır.',
      'Kazazedeyi kaydetmek yardım değildir; zor bir anı seyirlik malzemeye çevirir.',
    ],
    objective: 'Kaza yerinde dikizlemeden, çekim yapmadan ve akışı bozmadan geçmeyi öğrenmek.',
    tags: ['kaza-yeri-gorgusu', 'mahremiyet', 'dikkat'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-444',
    subject: 'adab',
    topic: 'ofke-yonetimi',
    difficulty: 'orta',
    stem: 'Kavşakta iki sürücü araçlarından inmiş, hararetle tartışıyor ve gerginlik giderek büyüyor. Olaya tanık olan sürücü olarak ne yaparsınız?',
    options: [
      'Aranıza girip taraflardan birini haklı çıkarmak',
      'Kenara çekilip olayı telefonla çekmek',
      'Korna çalarak tartışmayı bastırmak',
      'Fiziksel olarak araya girmeden güvenli mesafede kalmak; olay büyüyorsa yetkililere haber vermek',
    ],
    answerIndex: 3,
    explanation:
      'Öfkeli bir tartışmaya taraf olarak katılmak ateşe odun taşımaktır. Güvenli mesafeden durumu izlemek ve tehlike büyüyorsa yetkilileri aramak, hem size hem taraflara yapılabilecek en gerçek yardımdır.',
    whyWrong: [
      'Taraf tutmak tartışmayı üç kişilik kavgaya çevirebilir.',
      'Çekim yapmak veya korna çalmak gerginliği düşürmez; tahrik unsuru ekler.',
    ],
    objective:
      'Trafik kavgasına tanık olunca tırmandırmadan, doğru kanaldan müdahil olmayı öğrenmek.',
    tags: ['ofke-yonetimi', 'taniklik', 'yetkiliye-bildirme'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-445',
    subject: 'adab',
    topic: 'dayanisma',
    difficulty: 'kolay',
    stem: 'Otoparkta yan araca binmek üzereyken komşu aracın farlarının açık unutulduğunu gördünüz; sürücüsü az ileride yürüyor. Ne yaparsınız?',
    options: [
      'Kibarca seslenip farlarının açık kaldığını haber vermek',
      'Size ait olmayan bir konuya karışmamak',
      'Aracın kapısını zorlayıp farları kendiniz kapatmak',
      'Camına "farların açık" yazan öfkeli bir not bırakmak',
    ],
    answerIndex: 0,
    explanation:
      'Trafik adabı yalnızca yolda değil, park yerinde de yaşar. On saniyelik bir sesleniş, bir yabancıyı akşam bitmiş aküyle yolda kalmaktan kurtarır; dayanışma tam olarak budur.',
    whyWrong: [
      '"Bana ne" tutumu, sizin de bir gün ihtiyaç duyacağınız yardımlaşma kültürünü zayıflatır.',
      'Başkasının aracına müdahale etmek iyi niyetle bile olsa doğru değildir; haber vermek yeterlidir.',
    ],
    objective: 'Küçük fırsatlarda yol kullanıcıları arasındaki dayanışmayı yaşatmayı öğrenmek.',
    tags: ['dayanisma', 'yardimlasma', 'nezaket'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-446',
    subject: 'adab',
    topic: 'engelli-hakki',
    difficulty: 'kolay',
    stem: 'Otoparkta tekerlekli sandalye kullanan bir sürücü, sandalyesini aracına yüklüyor ve bu işlem sizin çıkışınızı birkaç dakika geciktiriyor. Doğru davranış hangisidir?',
    options: [
      'Motoru gaza basarak hazırlanması gerektiğini hissettirmek',
      'Camı açıp "acele et" diye seslenmek',
      'Korna çalmadan, baskı hissettirmeden sabırla beklemek; herkesin hazırlanma süresi aynı değildir',
      'Aracınızı iyice yaklaştırıp beklediğinizi göstermek',
    ],
    answerIndex: 2,
    explanation:
      'Sizin için sıradan olan biniş, onun için çok adımlı bir işlemdir. Sessizce beklemek yalnızca sabır değil, karşınızdakinin gündelik çabasına duyulan saygıdır; hissettirilen baskı ise o çabayı zorlaştırır.',
    whyWrong: [
      'Gaz, korna ve seslenme, aceleyle yapılan yüklemede düşme ve yaralanma riski doğurur.',
      'Aracı yaklaştırmak, manevra alanına ihtiyaç duyan kişiyi sıkıştırır.',
    ],
    objective: 'Engelli yol kullanıcılarının zaman ihtiyacına baskısız saygı göstermeyi öğrenmek.',
    tags: ['engelli-hakki', 'sabir', 'empati'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-447',
    subject: 'adab',
    topic: 'guvenli-mesafe',
    difficulty: 'kolay',
    stem: 'Önünüzdeki minibüs (dolmuş), yolcu indirip bindirmek için sık sık ve kısa aralıklarla duruyor. En doğru davranış hangisidir?',
    options: [
      'Her duruşunda korna çalarak tepkinizi göstermek',
      'Takip mesafesini artırıp duruşlarını öngörerek sakin sürmek; uygun ve güvenli bir yerde kurallı şekilde geçmek',
      'Dibine yapışarak durmasına fırsat vermemek',
      'Her duruşunda ani şerit değiştirip önüne geçmeye çalışmak',
    ],
    answerIndex: 1,
    explanation:
      'Toplu taşıma aracının sık durması işinin doğasıdır; buna öfkelenmek trafiğin gerçeğiyle kavga etmektir. Mesafeyi açan sürücü hem ani duruşlara hazırlıklı olur hem de sakinliğini korur.',
    whyWrong: [
      'Korna ve yakın takip, inen-binen yolcular için tehlike yaratır.',
      'Her duruşta ani şerit değiştirmek, yan şeritlerdeki akışı sürekli riske sokar.',
    ],
    objective: 'Sık duran araçların arkasında mesafe ve öngörüyle sakin seyretmeyi öğrenmek.',
    tags: ['guvenli-mesafe', 'dolmus', 'ongoru'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-448',
    subject: 'adab',
    topic: 'serit-izleme',
    difficulty: 'orta',
    stem: 'Otoyol gişesine yaklaşırken yanlış ödeme şeridine girdiğinizi fark ettiniz; doğru şeridin kuyruğu yoğun. Ne yapmalısınız?',
    options: [
      'Son anda direksiyon kırıp kuyruğun önüne girmek',
      'Gişe adacığının üzerinden geçip şerit değiştirmek',
      'Girdiğiniz şeritte durup geri geri çıkmak',
      'Akışa uyup düzeltmeyi güvenli noktadan yapmak ya da doğru kuyruğun sonuna, sırayla eklenmek',
    ],
    answerIndex: 3,
    explanation:
      'Gişe bölgesi, ani manevraların en pahalıya mal olduğu dar bir huni gibidir. Yanlış şeridin bedeli birkaç dakika sıra beklemektir; kuyruk önüne kırmanın bedeli ise hem kaza hem de sırasını bekleyen herkese haksızlıktır.',
    whyWrong: [
      'Son anda kırılan direksiyon, arkadan gelen aracın tepki payını yok eder.',
      'Gişe bölgesinde durmak veya geri gitmek, dar alanda zincirleme riske davetiyedir.',
    ],
    objective:
      'Gişe ve daralma bölgelerinde son anda şerit kesmeden, sırayla düzeltme yapmayı öğrenmek.',
    tags: ['serit-izleme', 'gise', 'sira-saygisi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-449',
    subject: 'adab',
    topic: 'ofke-yonetimi',
    difficulty: 'zor',
    stem: 'Trafikte gerginlik yaşadığınız bir sürücü, aracıyla sizi ısrarla takip etmeye başladı. En güvenli davranış hangisidir?',
    options: [
      "Evinize gitmeden, kapılar kilitli şekilde kalabalık bir yere veya polis noktasına yönelmek; gerekiyorsa 112'yi aramak",
      'Hızlanarak onu arkanızda bırakmaya çalışmak',
      'Uygun bir yerde durup araçtan inerek yüzleşmek',
      'Ani fren yaparak takibi caydırmak',
    ],
    answerIndex: 0,
    explanation:
      'Takip eden öfkeli bir sürücüye karşı en güçlü savunma, yüzleşme değil güvenli alandır: eve gitmek adresinizi göstermek olur; kalabalık ve resmî noktalar ise saldırganların çekildiği yerlerdir. Gerektiğinde 112 aranır.',
    whyWrong: [
      'Hız yarışına dönüşen kaçış, iki araçlık tehlikeli bir kovalamaca yaratır.',
      'İnip yüzleşmek veya ani fren yapmak, olayı fiziksel saldırıya ya da kazaya taşıyabilir.',
    ],
    objective:
      'Yol öfkesinin takibe dönüştüğü durumda güvenli alan ve resmî yardım stratejisini öğrenmek.',
    tags: ['ofke-yonetimi', 'takip-edilme', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-450',
    subject: 'adab',
    topic: 'defansif-surus',
    difficulty: 'orta',
    stem: 'Öncelik sizde olsa bile diğer sürücülerin hata yapabileceğini hesaba katarak sürmek (defansif sürüş), trafik adabıyla nasıl ilişkilidir?',
    options: [
      'İlişkisi yoktur; adap yalnızca nezaket kurallarını kapsar',
      'Defansif sürüş hakkından vazgeçmek anlamına geldiği için adaba aykırıdır',
      'Haklı olmayı değil güvenliği önceleyen bu tutum, empati ve sorumluluğun birleşimidir; trafik adabının özünü oluşturur',
      'Sadece acemi sürücülerin başvurduğu geçici bir yöntemdir',
    ],
    answerIndex: 2,
    explanation:
      'Kaza istatistikleri "haklıydı" notuyla teselli vermez. Başkasının hatasına alan bırakan sürücü, hem kendi canını hem hata yapanın canını korur; adap tam da bu öngörülü hoşgörüdür.',
    whyWrong: [
      'Adap yalnız selamlaşma nezaketi değildir; güvenliği gözeten her davranış adabın parçasıdır.',
      'Önlem almak haktan vazgeçmek değil, hakkı kazasız kullanmaktır.',
    ],
    objective:
      'Defansif sürüşün trafik adabının güvenlik ve empati boyutuyla bütünleştiğini kavramak.',
    tags: ['defansif-surus', 'ongoru', 'hosgoru'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
];
