/**
 * ÖZGÜN trafik ve çevre soruları — 6. genişletme (Program 2 · Faz 9). ROADMAP C.4/E.6.
 * Kaynak = resmî müfredat/mevzuat; KENDİ İFADEMİZLE.
 */
import type { QuestionInput } from '@ea/content-schema';

const SRC = 'Karayolları Trafik Yönetmeliği + MEB müfredatı (özgün ifade)';

export const TRAFIK_QUESTIONS_6: QuestionInput[] = [
  {
    id: 'trafik-601',
    subject: 'trafik',
    topic: 'oncelik-dort-yol',
    difficulty: 'zor',
    stem: 'Işıklı işaret ve görevlinin bulunmadığı, bütün kolları eşit (aynı değerde) olan bir kavşağa dört araç dört ayrı koldan hemen hemen aynı anda gelmiştir. Temel geçiş önceliği kuralı hangisidir?',
    options: [
      'Kavşağa en yüksek hızla giren araç önce geçer',
      'Her sürücü kendi sağındaki araca geçiş hakkını verir',
      'En büyük ve ağır araç önce geçer',
      'Farını yakan araç öncelik kazanır',
    ],
    answerIndex: 1,
    explanation:
      'Eşit kollu kontrolsüz kavşakta öncelik sağdan gelene aittir; her sürücü kendi sağındaki araca yol verir. Dört araç birlikte geldiğinde bu kural bir kilit yaratabileceğinden sürücüler göz teması kurup birbirine kolaylık göstererek sırayla geçer.',
    whyWrong: [
      'Hız bir öncelik ölçütü değildir; hızlı girmek kural değil ihlaldir.',
      'Aracın büyüklüğü veya ağırlığı geçiş hakkı vermez.',
      'Far yakmak istek bildirir ama kuralın yerini almaz.',
    ],
    objective: 'Eşit kavşakta sağdan gelene öncelik kuralını çok araçlı durumda uygulamak.',
    tags: ['kavsak', 'gecis-hakki', 'sagdan-gelen'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-602',
    subject: 'trafik',
    topic: 'oncelik-ana-tali',
    difficulty: 'kolay',
    stem: 'Işıklı işaretin bulunmadığı bir kavşakta siz ana yolda ilerliyorsunuz; sağınızdaki tali yoldan bir araç kavşağa yaklaşıyor. Geçiş önceliği kimindir?',
    options: [
      'Sağdan geldiği için tali yoldaki araç önce geçer',
      'İki araç da durup el işaretiyle anlaşır',
      'Ana yolda ilerleyen siz öncelikli olduğunuz için tali yoldaki araç size yol verir',
      'Kavşağa daha yakın olan önce geçer',
    ],
    answerIndex: 2,
    explanation:
      'Ana yol - tali yol kesişiminde öncelik ana yola aittir. Sağdan gelme kuralı yalnızca eşit değerli yollarda geçerlidir; burada tali yoldaki araç, ana yoldaki trafiğe yol vermek zorundadır.',
    whyWrong: [
      'Sağdan gelme kuralı eşit yollar içindir; ana yol bu kuralın önüne geçer.',
      'Anlaşma değil, net bir öncelik kuralı işler.',
      'Kavşağa yakınlık öncelik ölçütü değildir.',
    ],
    objective: 'Ana yolun sağdan gelme kuralına üstün olduğunu kavramak.',
    tags: ['ana-yol', 'tali-yol', 'gecis-hakki'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-603',
    subject: 'trafik',
    topic: 'donus-yaya-karsi-arac',
    difficulty: 'zor',
    stem: 'Işıklı bir kavşakta sola dönmek üzeresiniz. Aynı anda karşı yönden düz gelen bir araç ile dönmek istediğiniz yolda karşıdan karşıya geçen yayalar var. Nasıl davranırsınız?',
    options: [
      'Hem karşıdan düz gelen araca hem de geçen yayalara yol verir, yol boşalınca dönerim',
      'Önce yayaları geçirir, karşıdan gelen aracın önünden hızla dönerim',
      'Karşıdan gelen aracı geçirir, yayaların arasından süzülürüm',
      'Sinyal verdiğim için önce ben döner, sonra beklerim',
    ],
    answerIndex: 0,
    explanation:
      'Sola dönen sürücü kavşakta en düşük önceliğe sahiptir: hem karşıdan düz gelen araç hem de gireceği yoldaki yayalar ondan önce geçer. Her ikisi de yolu boşaltmadan dönüş tamamlanmaz.',
    whyWrong: [
      'Karşıdan gelen aracın önünden dönmek çarpışma riski yaratır.',
      'Yayaların arasından geçmek yaya önceliğini ihlal eder.',
      'Sinyal vermek dönüş hakkı doğurmaz; yalnızca niyeti bildirir.',
    ],
    objective: 'Sola dönüşte hem karşı araç hem yaya önceliğinin sürdüğünü kavramak.',
    tags: ['sola-donus', 'yaya-onceligi', 'kavsak'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-604',
    subject: 'trafik',
    topic: 'saga-serbest-ok',
    difficulty: 'orta',
    stem: 'Işıklı kavşakta ana ışık kırmızı yanarken, sağ tarafta ayrı bir yeşil ok ışığı yanmaktadır. Sağa dönmek isteyen sürücü ne yapabilir?',
    options: [
      'Ok yansa da kırmızıda hiçbir şekilde dönemez',
      'Yol açıksa, dönüş yönündeki yaya ve araçlara yol vererek okun gösterdiği yöne dönebilir',
      'Bütün yönlere serbestçe hareket edebilir',
      'Kavşağın ortasında durup ana ışığın yeşile dönmesini bekler',
    ],
    answerIndex: 1,
    explanation:
      'Ana ışık kırmızı olsa bile yanan yeşil ok, yalnızca okun gösterdiği yöndeki hareketi serbest bırakır. Sürücü, o yöndeki yayalara ve trafiğe yol vererek dikkatle dönebilir.',
    whyWrong: [
      'Ok tam da bu durumda dönüşe izin verdiği için mutlak yasak yanlıştır.',
      'Serbestlik tek yönle sınırlıdır; tüm yönleri kapsamaz.',
      'Ok yanarken kavşak ortasında beklemek gereksizdir ve trafiği tıkar.',
    ],
    objective: 'Kırmızı ile birlikte yanan yeşil okun tek yönlü serbestlik anlamını bilmek.',
    tags: ['yesil-ok', 'saga-donus', 'isikli-kavsak'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-605',
    subject: 'trafik',
    topic: 'kirmizida-saga-donus',
    difficulty: 'kolay',
    stem: 'Ülkemizde, ayrı bir yeşil ok ışığı bulunmayan bir kavşakta kırmızı ışıkta sağa dönmek ile ilgili hangisi doğrudur?',
    options: [
      'Yol boşsa serbesttir',
      'Gece serbesttir',
      'Yavaş dönülürse serbesttir',
      'Yasaktır; kırmızı ışık o yöndeki tüm hareketleri durdurur',
    ],
    answerIndex: 3,
    explanation:
      'Ülkemizde kırmızı ışıkta sağa dönüş serbest değildir. Ayrı bir yeşil sağa dönüş oku yanmıyorsa, kırmızı ışık o koldaki bütün hareketleri durdurur; sürücü yeşili beklemek zorundadır.',
    whyWrong: [
      'Yolun boş olması kırmızı ışığın durdurma anlamını değiştirmez.',
      'Gece ayrıcalığı diye bir kural yoktur.',
      'Yavaş dönmek de kırmızı ışık ihlalidir.',
    ],
    objective: 'Yeşil ok olmadan kırmızıda sağa dönüşün yasak olduğunu bilmek.',
    tags: ['kirmizi-isik', 'saga-donus', 'isik-ihlali'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-606',
    subject: 'trafik',
    topic: 'sari-isik-karar',
    difficulty: 'zor',
    stem: 'Kavşağa yaklaşırken ışık sarıya döndü; ancak durak çizgisine o kadar yakınsınız ki sert fren yapmadan güvenle duramayacaksınız. En doğru davranış hangisidir?',
    options: [
      'Ani ve sert fren yaparak çizgide durmaya çalışmak',
      'Hızlanıp kırmızı yanmadan geçmeye çalışmak',
      'Hızı artırmadan, kavşağı boşaltacak şekilde dikkatle geçmek',
      'Kavşağın ortasında durup beklemek',
    ],
    answerIndex: 2,
    explanation:
      'Sarı ışıkta esas, güvenle durabiliyorsanız durmaktır. Durak çizgisine çok yakınsanız ve güvenle duramıyorsanız, hızı artırmadan kavşağı boşaltacak biçimde geçmek arkadan çarpılmayı önleyen doğru davranıştır.',
    whyWrong: [
      'Çok yakında sert fren yapmak arkadan çarpışmaya yol açar.',
      'Hızlanmak sarı ışığın uyarı amacına aykırıdır ve riski büyütür.',
      'Kavşak ortasında durmak trafiği kilitler ve tehlikelidir.',
    ],
    objective: 'Sarı ışıkta durma-geçme kararını mesafeye göre vermek.',
    tags: ['sari-isik', 'karar-mesafesi', 'fren'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-607',
    subject: 'trafik',
    topic: 'hemzemin-arac-kalmasi',
    difficulty: 'zor',
    stem: 'Bariyerli bir hemzemin (demiryolu) geçidi üzerinde aracınız stop edip çalışmıyor ve hareket etmiyorsa öncelikli olarak ne yapmalısınız?',
    options: [
      'Motoru çalıştırmak için defalarca denemek ve araçta kalmak',
      'Aracı ittirmek için arkadan gelen araçlardan yardım istemek',
      'Dörtlü ikazı yakıp aracın içinde beklemek',
      'Herkesi hızla araçtan indirip geçitten uzaklaştırmak ve tren geliyorsa yetkilileri uyarmak',
    ],
    answerIndex: 3,
    explanation:
      'Ray üzerinde kalan araçta can güvenliği her şeyin önündedir. Önce tüm yolcular indirilip geçitten güvenli mesafeye uzaklaştırılır; imkan varsa araç raydan çıkarılmaya çalışılır ve tren yaklaşıyorsa görevliler uyarılır.',
    whyWrong: [
      'Ray üzerinde marş denemekle vakit kaybetmek ölümcül olabilir.',
      'İtme için beklerken tren gelebilir; önce insanlar tahliye edilir.',
      'Araçta beklemek en tehlikeli seçenektir.',
    ],
    objective: 'Hemzemin geçitte kalan araçta önce can güvenliğini sağlamayı bilmek.',
    tags: ['hemzemin-gecit', 'acil-durum', 'tahliye'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-608',
    subject: 'trafik',
    topic: 'otoyol-geri-gitme',
    difficulty: 'orta',
    stem: 'Otoyolda ilerlerken çıkışınızı geçtiğinizi fark ettiniz. Ne yapmanız gerekir?',
    options: [
      'Emniyet şeridinden geri giderek kaçırdığınız çıkışa dönmek',
      'Geri gitmeden ve durmadan seyre devam edip bir sonraki çıkıştan ayrılmak',
      'Uygun bir yerden U dönüşü yaparak geri dönmek',
      'Durup arkadaki araçların yavaşlamasını beklemek',
    ],
    answerIndex: 1,
    explanation:
      'Otoyolda geri gitmek, durmak ve U dönüşü yapmak kesinlikle yasaktır; bu hareketler yüksek hızlı trafikte ölümcül kazalara yol açar. Çıkışı kaçıran sürücü seyrine devam eder ve bir sonraki çıkıştan ayrılır.',
    whyWrong: [
      'Emniyet şeridinde geri gitmek otoyolun en tehlikeli ihlallerindendir.',
      'Otoyolda U dönüşü yapmak yasaktır.',
      'Akan trafikte durmak arkadan çarpışmaya davetiye çıkarır.',
    ],
    objective: 'Otoyolda geri gitme ve U dönüşü yasağını, kaçan çıkış durumunda bilmek.',
    tags: ['otoyol', 'geri-gitme', 'cikis'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-609',
    subject: 'trafik',
    topic: 'emniyet-seridi-hak',
    difficulty: 'orta',
    stem: 'Otoyolun emniyet şeridini hangi durumda kullanmak kurallara uygundur?',
    options: [
      'Trafik sıkıştığında sırayı beklememek için',
      'Acele eden her sürücü için',
      'Arızalanan araçların çekilmesi, zorunlu duruşlar ve görev hâlindeki geçiş üstünlüğüne sahip araçlar için',
      'Yavaş giden araçları sağdan geçmek için',
    ],
    answerIndex: 2,
    explanation:
      'Emniyet şeridi seyir için değil, acil durumlar içindir: arızalanıp duran araçlar, mecburi duruşlar ve siren çalıştırmış ambulans, itfaiye, polis gibi araçlar kullanır. Normal sürücülerin sıra geçmek için kullanması ağır ihlaldir.',
    whyWrong: [
      'Trafik sıkışıklığı emniyet şeridini kullanma hakkı vermez.',
      'Acele etmek bir gerekçe değildir; şerit acil durumlara ayrılmıştır.',
      'Sağdan geçmek için kullanmak hem yasak hem tehlikelidir.',
    ],
    objective: 'Emniyet şeridini kullanmaya kimlerin ve hangi durumların hak verdiğini bilmek.',
    tags: ['otoyol', 'emniyet-seridi', 'gecis-ustunlugu'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-610',
    subject: 'trafik',
    topic: 'u-donusu-refuj',
    difficulty: 'orta',
    stem: 'Bölünmüş bir yolda refüjde bırakılmış dönüş boşluğundan U dönüşü yapmak isteyen sürücü için hangisi doğrudur?',
    options: [
      'Levha veya çizgiyle yasaklanmamışsa ve trafiği tehlikeye düşürmüyorsa, her iki yöndeki araçlara yol vererek dönebilir',
      'Karşı yönden gelen araçlar ona yol vermek zorundadır',
      'Sinyal verdiği anda hiç beklemeden dönebilir',
      'Hızlı dönerse önceliğe gerek yoktur',
    ],
    answerIndex: 0,
    explanation:
      'Refüjdeki dönüş açıklıklarından U dönüşü ancak yasaklayıcı işaret yoksa ve trafik güvenliği bozulmuyorsa yapılabilir. Dönen sürücü, akan trafiğe sonradan katıldığı için her iki yöndeki araçlara yol vermek zorundadır.',
    whyWrong: [
      'Dönüş yapan araca öncelik tanınmaz; yol verecek olan odur.',
      'Sinyal niyeti bildirir, geçiş hakkı doğurmaz.',
      'Hız, yol verme yükümlülüğünü ortadan kaldırmaz.',
    ],
    objective: 'Refüj boşluğunda U dönüşünün koşullarını ve yol verme yükümlülüğünü bilmek.',
    tags: ['u-donusu', 'refuj', 'gecis-hakki'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-611',
    subject: 'trafik',
    topic: 'u-donusu-yasak-yer',
    difficulty: 'orta',
    stem: 'Aşağıdaki yerlerin hangisinde U dönüşü (geri dönüş) yapmak kesinlikle sakıncalı ve yasaktır?',
    options: [
      'Görüşün açık olduğu geniş ve düz yollarda',
      'Dönüşe izin veren işaretin bulunduğu kavşaklarda',
      'Refüjde dönüşe ayrılmış boşluklarda',
      'Görüşün yetersiz olduğu tepe üstlerinde, keskin virajlarda ve otoyollarda',
    ],
    answerIndex: 3,
    explanation:
      'U dönüşü, karşıdan gelen sürücünün aracınızı geç fark edeceği yerlerde ölümcüldür. Tepe üstü, keskin viraj gibi görüşün kapalı olduğu kesimlerde ve otoyollarda U dönüşü yasaktır.',
    whyWrong: [
      'Görüşün açık olduğu düz yol, güvenli dönüş için elverişli olabilir.',
      'İşaretle izin verilen kavşakta dönüş kurala uygundur.',
      'Refüj boşlukları zaten dönüş için düzenlenmiş yerlerdir.',
    ],
    objective: 'U dönüşünün görüşün kapalı olduğu yerlerde ve otoyolda yasak olduğunu bilmek.',
    tags: ['u-donusu', 'gorus-mesafesi', 'yasak-yer'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-612',
    subject: 'trafik',
    topic: 'park-arasi-yaya',
    difficulty: 'zor',
    stem: 'Yol kenarına sıralı park etmiş araçların arasından, önü görünmeyen bir noktadan karşıya geçmek isteyen yayaların çıkabileceği bir sokakta ilerliyorsunuz. En doğru davranış hangisidir?',
    options: [
      'Park sırasının yanından hızlanarak hızla geçmek',
      'Hızı düşürüp park etmiş araçların aralarını tarayarak, aniden çıkabilecek yayaya hazır olmak',
      'Korna çalarak yayaları uzak tutmak',
      'Park eden araçlara yaklaşıp orta şeride geçmek',
    ],
    answerIndex: 1,
    explanation:
      'Park etmiş araçlar bir görüş perdesidir; özellikle çocuklar araçların arasından aniden yola çıkabilir. Sürücü hızını düşürmeli, boşlukları taramalı ve her an durabilecek şekilde hazır olmalıdır.',
    whyWrong: [
      'Hızlanmak, aniden çıkan yayaya tepki süresini yok eder.',
      'Korna, görünmeyen yayayı önceden durduramaz.',
      'Karşı şeride geçmek başka bir çarpışma riski doğurur; asıl çözüm yavaşlamaktır.',
    ],
    objective: 'Park etmiş araçlar arasından çıkan yaya riskine karşı hız düşürmeyi kavramak.',
    tags: ['yaya-guvenligi', 'gorus-perdesi', 'park-etmis-arac'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-613',
    subject: 'trafik',
    topic: 'tarim-araci-sollama',
    difficulty: 'orta',
    stem: 'Yerleşim yeri dışında, önünüzde çok düşük hızla giden bir traktör (tarım aracı) var ve onu geçmek istiyorsunuz. Doğru davranış hangisidir?',
    options: [
      'Traktör yavaş olduğu için görüş kapalı olsa bile hemen geçmek',
      'Traktöre iyice yaklaşıp sıkıştırarak kenara çekilmesini sağlamak',
      'Karşı şeridin yeterince uzağa kadar boş ve görüşün açık olduğu bir yerde, güvenli mesafe bırakarak geçmek',
      'Korna çalıp selektör yaparak traktörü durdurmak',
    ],
    answerIndex: 2,
    explanation:
      'Traktör yavaş olsa da geçiş kuralı değişmez: sollama ancak karşı şerit yeterince uzağa kadar boş, görüş açık ve çizgiler izin veriyorsa yapılır. Geçiş sırasında araca yeterli yan mesafe bırakılır.',
    whyWrong: [
      'Görüş kapalıyken geçmek karşıdan gelenle kafa kafaya çarpışma demektir.',
      'Yavaş aracı sıkıştırmak tehlikeli ve kaba bir davranıştır.',
      'Traktörü durdurmaya çalışmak sollama kuralının yerine geçmez.',
    ],
    objective: 'Yavaş tarım aracını sollamada görüş ve mesafe koşullarını bilmek.',
    tags: ['sollama', 'tarim-araci', 'gorus-mesafesi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-614',
    subject: 'trafik',
    topic: 'yuklu-kamyon-takip',
    difficulty: 'orta',
    stem: 'Önünüzde ağır yüklü bir kamyonu takip ediyorsunuz. Takip mesafesi konusunda neden normalden daha dikkatli olmalısınız?',
    options: [
      'Yüklü kamyon geç yavaşlar ve önünü göremezsiniz; ayrıca kasadan malzeme düşebileceği için daha uzun takip mesafesi gerekir',
      'Kamyon hızlı durduğu için ona çok yaklaşmak gerekir',
      'Kamyonun arkasında durmak yakıt tasarrufu sağlar diye yakın durmak gerekir',
      'Kamyonu ürkütmemek için tampona yakın gitmek gerekir',
    ],
    answerIndex: 0,
    explanation:
      'Yüklü kamyonun arkasında ilerlerken hem önünüzü göremezsiniz hem de kamyonun kasasından taş veya malzeme düşebilir. Ağır araç uzun mesafede durduğundan, yeterli takip mesafesi hem görüş hem tepki payı sağlar.',
    whyWrong: [
      'Yüklü ağır araç hızlı değil, geç durur; yaklaşmak tehlikelidir.',
      'Yakın takip yakıt için değerlendirilecek bir davranış değildir ve risklidir.',
      'Tampona yakın gitmek görüşü kapatır ve çarpışma riskini artırır.',
    ],
    objective: 'Yüklü ağır araç takibinde artırılmış takip mesafesinin gerekçesini kavramak.',
    tags: ['takip-mesafesi', 'agir-tasit', 'gorus'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-615',
    subject: 'trafik',
    topic: 'gece-goz-kamasmasi',
    difficulty: 'orta',
    stem: 'Gece yerleşim yeri dışında, karşıdan gelen aracın uzun farları gözünüzü kamaştırdı. Ne yapmalısınız?',
    options: [
      'Karşı aracın farlarına dik bakarak yolu takip etmek',
      'Kendi uzun farlarımı yakıp karşılık vermek',
      'Gözleri korumak için gözleri kapatıp aynı hızla gitmek',
      'Hızı azaltmak, bakışı yolun sağ kenarına yöneltmek ve gerekirse durmak',
    ],
    answerIndex: 3,
    explanation:
      'Göz kamaşmasında bir an için görüş kaybolur. Doğru davranış hızı azaltmak, bakışı ışık kaynağından kaçırıp yolun sağ kenar çizgisine yöneltmek ve görüş çok bozulduysa güvenli şekilde yavaşlayıp durmaktır.',
    whyWrong: [
      'Işığa dik bakmak kamaşmayı artırır ve görüşü tamamen kaybettirir.',
      'Uzun farla karşılık vermek karşı sürücüyü de kör eder; iki taraflı tehlike doğar.',
      'Gözleri kapatarak sürmek kontrolü tümüyle kaybettirir.',
    ],
    objective: 'Gece göz kamaşmasında sağ kenara bakıp yavaşlamayı bilmek.',
    tags: ['gece-surus', 'goz-kamasmasi', 'far'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-616',
    subject: 'trafik',
    topic: 'sisli-hava-takip',
    difficulty: 'orta',
    stem: 'Yoğun sis nedeniyle görüş mesafesinin çok kısaldığı bir yolda öndeki aracı takip ederken nasıl davranmalısınız?',
    options: [
      'Öndeki aracın arka lambalarını yakından takip ederek yol bulmak',
      'Hızı görüş mesafesine göre azaltmak ve takip mesafesini normalden çok daha uzun tutmak',
      'Uzun farları yakıp hızlanarak sisli bölgeyi bir an önce geçmek',
      'Öndeki aracın tam arkasına geçip onun hızına uymak',
    ],
    answerIndex: 1,
    explanation:
      'Siste tehlike çok geç görülür. Güvenlik, hızı görüş mesafesi içinde durabilecek kadar düşürmek ve öndeki araçla arayı normalden çok daha açık tutmakla sağlanır; sis farları ve kısa far kullanılır.',
    whyWrong: [
      'Arka lambaları yakından takip, öndeki ani durunca çarpışma demektir.',
      'Uzun far siste beyaz bir perde oluşturarak görüşü daha da bozar.',
      'Öndeki aracın arkasına yapışmak takip mesafesi kuralını ihlal eder.',
    ],
    objective: 'Siste hız ve takip mesafesini görüşe göre ayarlamayı bilmek.',
    tags: ['sis', 'takip-mesafesi', 'gorus-mesafesi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-617',
    subject: 'trafik',
    topic: 'park-lambasi-aydinlatmasiz',
    difficulty: 'kolay',
    stem: 'Yeterince aydınlatılmamış bir yol kenarında geceleyin park eden sürücü, aracının fark edilmesi için ne yapmalıdır?',
    options: [
      'Bütün ışıkları söndürüp aracı karanlıkta bırakmalıdır',
      'Uzun farları açık bırakmalıdır',
      'Aracın görülebilmesi için park (durum) lambalarını yakmalı, gerekiyorsa yansıtıcı ile işaretlemelidir',
      'Dörtlü ikazı sabaha kadar yakık tutup gitmelidir',
    ],
    answerIndex: 2,
    explanation:
      'Aydınlatması yetersiz yolda karanlıkta park eden araç, arkadan gelen için görünmez bir engeldir. Aracın belli olması için park (durum) lambaları yakılır; gerekirse yansıtıcı veya işaretle konumu belirtilir.',
    whyWrong: [
      'Bütün ışıkları söndürmek aracı görünmez kılar ve çarpışmaya yol açar.',
      'Uzun far park için kullanılmaz; karşıdan gelenleri kamaştırır.',
      'Aküyü bitirecek şekilde dörtlüyü bırakıp gitmek doğru bir işaretleme değildir.',
    ],
    objective: 'Aydınlatmasız yolda park ederken park lambası kullanımını bilmek.',
    tags: ['park', 'gece', 'park-lambasi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-618',
    subject: 'trafik',
    topic: 'okul-servisi-isaret',
    difficulty: 'kolay',
    stem: 'Okul servis (taşıtı) araçlarını diğer araçlardan ayıran ve sürücüleri uyaran temel özellik hangisidir?',
    options: [
      'Üzerlerinde OKUL TAŞITI yazısı ve durup öğrenci indirip bindirirken yakılan özel uyarı ışıkları bulunması',
      'Yalnızca gece çalışmaları',
      'Diğer araçlara göre çok daha hızlı olmaları',
      'Hiçbir ayırt edici işaret taşımamaları',
    ],
    answerIndex: 0,
    explanation:
      'Okul taşıtları, arkasındaki OKUL TAŞITI yazısı ve öğrenci indirip bindirirken yaktıkları uyarı ışıklarıyla belli olur. Bu işaretler diğer sürücülere çocukların yakında olduğunu ve dikkatli olmaları gerektiğini bildirir.',
    whyWrong: [
      'Okul taşıtları gündüz de yoğun çalışır; gece ile sınırlı değildir.',
      'Hız değil, güvenlik ve dikkat ön plandadır.',
      'Okul taşıtları belirgin işaretler taşımak zorundadır.',
    ],
    objective: 'Okul taşıtının ayırt edici işaret ve uyarı ışıklarını tanımak.',
    tags: ['okul-tasiti', 'uyari-isigi', 'cocuk-guvenligi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-619',
    subject: 'trafik',
    topic: 'kaza-ilk-gelen',
    difficulty: 'zor',
    stem: 'Yaralıların bulunduğu bir trafik kazası yerine ilk gelen sürücü olarak sorumluluğunuz nedir?',
    options: [
      'Olayla ilgim yoksa hiç durmadan geçip gitmek',
      'Sadece fotoğraf çekip yola devam etmek',
      'Yaralıları hemen araçtan çekip çıkararak bir kenara taşımak',
      'Kaza yerini trafiğe karşı işaretleyip güvenliği almak, 112 gibi acil numaraları aramak ve bilgim ölçüsünde ilk yardım yapmak',
    ],
    answerIndex: 3,
    explanation:
      'Kazaya ilk gelen sürücü, ikincil kazaları önlemek için olay yerini işaretleyip güvenliği alır, acil yardımı (112) çağırır ve bilgisi ölçüsünde ilk yardım uygular. Bunlar yasal ve insani bir yükümlülüktür.',
    whyWrong: [
      'Yaralı varken durmadan geçmek yardım yükümlülüğünün ihlalidir.',
      'Yalnızca fotoğraf çekip gitmek hem yararsız hem sorumsuzdur.',
      'Zorunluluk yoksa yaralıyı bilinçsizce çekmek omurga gibi yaralanmaları ağırlaştırabilir.',
    ],
    objective:
      'Kaza yerine ilk gelen sürücünün güvenlik, ihbar ve ilk yardım yükümlülüklerini bilmek.',
    tags: ['kaza-yeri', 'ilk-yardim', 'yukumluluk'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-620',
    subject: 'trafik',
    topic: 'ehliyetsize-arac',
    difficulty: 'kolay',
    stem: 'Sürücü belgesi olmayan bir yakınınızın aracınızı kullanmasına izin vermeniz nasıl değerlendirilir?',
    options: [
      'Kısa mesafe için sorun değildir',
      'Yasaktır; belgesiz kişiye araç kullandıran araç sahibi de sorumlu tutulur ve cezalandırılır',
      'Araç sahibinin sorumluluğu yoktur, yalnızca kullanan cezalıdır',
      'Boş ve tenha yollarda serbesttir',
    ],
    answerIndex: 1,
    explanation:
      'Sürücü belgesi olmayan kişiye araç kullandırmak yasaktır. Sadece kullanan değil, aracı ona veren sahibi de sorumlu tutularak cezalandırılır; çünkü ehliyetsiz sürücü trafikte ciddi risk oluşturur.',
    whyWrong: [
      'Mesafenin kısalığı ehliyet zorunluluğunu kaldırmaz.',
      'Aracı veren de yasal olarak sorumludur; sorumluluk yalnız sürücüde değildir.',
      'Yolun tenha olması belgesiz sürüşü serbest kılmaz.',
    ],
    objective: 'Belgesiz kişiye araç kullandırmanın araç sahibini de sorumlu kıldığını bilmek.',
    tags: ['surucu-belgesi', 'sorumluluk', 'ehliyetsiz'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-621',
    subject: 'trafik',
    topic: 'kirmizi-yaya-sorumluluk',
    difficulty: 'zor',
    stem: 'Yaya, kendi kırmızı ışığında kurala aykırı biçimde yola girdi. Yeşil ışıkta ilerleyen sürücünün sorumluluğu nedir?',
    options: [
      'Yaya kuralı ihlal ettiği için sürücünün hiçbir sorumluluğu yoktur',
      'Sürücü hakkını kullanıp yoluna devam edebilir',
      'Sürücü yeşil ışıkta olsa da yayaya çarpmamak için fren yapmak, hız kesmek gibi her türlü tedbiri almak zorundadır',
      'Sürücü korna çalarsa yükümlülükten kurtulur',
    ],
    answerIndex: 2,
    explanation:
      'Yeşil ışık geçiş hakkı verir ama insan hayatını riske atma hakkı vermez. Yaya kural dışı da olsa yola girmişse, sürücü çarpmayı önlemek için frenlemek ve hızını kesmek dahil elinden gelen her tedbiri almakla yükümlüdür.',
    whyWrong: [
      'Yayanın kusuru, sürücünün kaçınma yükümlülüğünü ortadan kaldırmaz.',
      'Hakkı olsa da çarpma pahasına yola devam etmek kabul edilemez.',
      'Korna çalmak, çarpmayı önleme yükümlülüğünün yerine geçmez.',
    ],
    objective: 'Yaya kusurlu olsa da sürücünün çarpmayı önleme yükümlülüğünü kavramak.',
    tags: ['yaya-guvenligi', 'kirmizi-isik', 'sorumluluk'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-622',
    subject: 'trafik',
    topic: 'dar-kopru-karsilasma',
    difficulty: 'orta',
    stem: 'Aynı anda iki aracın sığamayacağı dar bir köprüye siz ve karşıdan gelen bir araç aynı anda yaklaşıyorsunuz. Genel kural olarak geçiş kolaylığını kim sağlar?',
    options: [
      'Köprüye henüz girmemiş olan araç, karşıdan gelen araç köprüyü boşaltana kadar bekler',
      'Aracı büyük olan önce geçer',
      'İki araç da yavaşça aynı anda girer',
      'Korna çalan araç önce geçer',
    ],
    answerIndex: 0,
    explanation:
      'Dar köprü, tünel gibi yalnızca bir aracın geçebileceği yerlerde köprüye önce giren araca kolaylık gösterilir; henüz girmemiş olan araç, karşı taraf geçişini tamamlayana kadar uygun yerde bekler.',
    whyWrong: [
      'Araç büyüklüğü öncelik ölçütü değildir.',
      'İki aracın aynı anda girmesi sıkışma ve çarpışma doğurur.',
      'Korna bir geçiş hakkı doğurmaz.',
    ],
    objective: 'Dar köprü ve geçitte önce girene kolaylık gösterme kuralını bilmek.',
    tags: ['dar-gecit', 'kopru', 'gecis-kolayligi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-623',
    subject: 'trafik',
    topic: 'karsidan-gelene-oncelik-levhasi',
    difficulty: 'kolay',
    stem: 'Dar bir yol kesimine girerken karşıdan gelen araca öncelik verilmesi gerektiğini bildiren trafik işaretini gören sürücü ne yapmalıdır?',
    options: [
      'Hızlanıp dar kesime karşı araçtan önce girmelidir',
      'Karşı araca korna çalıp geçmesini engellemelidir',
      'İşareti dikkate almadan geçmelidir',
      'Dar kesimde karşıdan gelen araca yol vermeli, gerekirse durup beklemelidir',
    ],
    answerIndex: 3,
    explanation:
      'Bu işaret, dar kesimde geçiş önceliğinin karşıdan gelen araçta olduğunu bildirir. Sürücü, karşı araç geçişini tamamlayana kadar uygun yerde bekleyerek yol verir.',
    whyWrong: [
      'Hızlanıp önce girmek işaretin tam tersi bir davranıştır.',
      'Korna, karşı aracın öncelik hakkını ortadan kaldırmaz.',
      'İşareti yok saymak dar kesimde karşılaşma ve sıkışmaya yol açar.',
    ],
    objective: 'Karşıdan gelene öncelik işaretinin anlamını uygulamak.',
    tags: ['levha', 'gecis-onceligi', 'dar-yol'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-624',
    subject: 'trafik',
    topic: 'sollama-yasak-levhasi',
    difficulty: 'kolay',
    stem: 'İçinde iki araç sembolü bulunan, kırmızı kenarlı yuvarlak "Öndeki taşıtı geçmek yasaktır" işaretinin bulunduğu kesimde sürücü ne yapmalıdır?',
    options: [
      'Yol boşsa öndeki aracı geçebilir',
      'İşaretin geçerli olduğu kesim boyunca öndeki aracı sollamamalıdır',
      'Yalnızca kamyonları geçebilir',
      'Hızlanıp bir an önce geçmelidir',
    ],
    answerIndex: 1,
    explanation:
      'Geçme yasağı işareti, o kesimde görüş veya yol koşullarının sollamaya elverişsiz olduğunu bildirir. Sürücü, yasak biten işaret gelene kadar öndeki aracı geçemez.',
    whyWrong: [
      'Yolun boş görünmesi yasağı kaldırmaz; tehlike genellikle görünmeyen kesimdedir.',
      'Yasak araç türüne göre ayrım yapmaz.',
      'Hızlanıp geçmek doğrudan işaret ihlalidir.',
    ],
    objective: 'Geçme yasağı levhasına uymayı bilmek.',
    tags: ['levha', 'sollama-yasagi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-625',
    subject: 'trafik',
    topic: 'mecburi-yon-oku',
    difficulty: 'kolay',
    stem: 'Kavşakta, mavi zemin üzerine beyaz bir okla yalnızca ileri gidilebileceğini gösteren mecburi yön işareti bulunuyorsa sürücü ne yapmalıdır?',
    options: [
      'Dilediği yöne dönebilir',
      'Geri dönüş yapabilir',
      'Yalnızca okun gösterdiği yönde, yani ileri hareket etmelidir',
      'Kavşakta durup beklemelidir',
    ],
    answerIndex: 2,
    explanation:
      'Mavi zeminli ok işaretleri mecburi yönü gösterir; sürücü yalnızca okun gösterdiği yönde hareket edebilir. Yalnızca ileri okunun olduğu yerde sağa, sola veya geri dönüş yapılamaz.',
    whyWrong: [
      'İşaret zaten serbest yön seçimini kaldırır.',
      'Geri dönüş bu işaretin tam olarak yasakladığı harekettir.',
      'Kavşakta beklemek değil, gösterilen yönde ilerlemek gerekir.',
    ],
    objective: 'Mecburi yön (mavi ok) işaretine uymayı bilmek.',
    tags: ['levha', 'mecburi-yon', 'mavi-levha'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-626',
    subject: 'trafik',
    topic: 'tehlike-viraj-levhasi',
    difficulty: 'kolay',
    stem: 'Kenarları kırmızı üçgen bir levha üzerinde keskin bir viraj sembolü gören sürücü ne anlamalıdır?',
    options: [
      'İleride tehlikeli bir viraj olduğunu; hızını azaltıp dikkatli olması gerektiğini',
      'İleride park yeri bulunduğunu',
      'Virajda sollamanın serbest olduğunu',
      'Yolun bittiğini',
    ],
    answerIndex: 0,
    explanation:
      'Kırmızı kenarlı üçgen levhalar tehlike-uyarı işaretleridir. Viraj sembolü, ileride keskin bir dönüş bulunduğunu; sürücünün hızını azaltıp direksiyona hakim olması gerektiğini bildirir.',
    whyWrong: [
      'Park yeri bilgisi tehlike üçgeni ile değil, bilgi levhalarıyla verilir.',
      'Virajda görüş kapalı olduğu için sollama zaten sakıncalıdır.',
      'Yolun bittiğini bildiren işaret bu değildir.',
    ],
    objective: 'Tehlikeli viraj uyarı levhasının anlamını bilmek.',
    tags: ['levha', 'tehlike-uyari', 'viraj'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-627',
    subject: 'trafik',
    topic: 'kasis-levhasi',
    difficulty: 'kolay',
    stem: 'Üçgen bir tehlike-uyarı levhasında yolda tümsek (kasis) bulunduğunu gösteren işareti gören sürücü ne yapmalıdır?',
    options: [
      'Hızlanarak kasisin üzerinden sıçramalıdır',
      'Levhayı dikkate almadan geçmelidir',
      'Korna çalarak geçmelidir',
      'Hızını azaltarak kasise yavaş ve kontrollü girmelidir',
    ],
    answerIndex: 3,
    explanation:
      'Kasis (tümsek) uyarı levhası, yolda ani bir yükseklik farkı olduğunu bildirir. Yüksek hızla girilen kasis araç hakimiyetini bozar ve araca zarar verir; sürücü hızını azaltıp kontrollü geçmelidir.',
    whyWrong: [
      'Hızla sıçramak hem araç hakimiyetini kaybettirir hem araca zarar verir.',
      'Levhayı yok saymak sarsıntı ve kontrol kaybı doğurur.',
      'Korna kasisin etkisini azaltmaz; asıl gereken yavaşlamaktır.',
    ],
    objective: 'Kasis uyarı levhasında hız azaltmayı bilmek.',
    tags: ['levha', 'tehlike-uyari', 'kasis'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-628',
    subject: 'trafik',
    topic: 'kaygan-yol-levhasi',
    difficulty: 'orta',
    stem: 'Kayan bir araç sembolü taşıyan üçgen uyarı levhasının bulunduğu bir kesimde sürücünün doğru davranışı hangisidir?',
    options: [
      'Hızını artırıp kaygan bölgeyi hızla geçmek',
      'Hızını azaltmak, ani fren ve direksiyon hareketlerinden kaçınmak, takip mesafesini artırmak',
      'Sert fren yaparak aracı kontrol altında tutmak',
      'Levhayı yalnızca yağmurlu havada dikkate almak',
    ],
    answerIndex: 1,
    explanation:
      'Kaygan yol levhası, zeminin tutunmayı azaltan bir yüzeye sahip olduğunu bildirir. Sürücü hızını azaltır, ani gaz-fren-direksiyon hareketlerinden kaçınır ve takip mesafesini artırır; çünkü kaygan zeminde fren mesafesi uzar.',
    whyWrong: [
      'Hızlanmak kaygan zeminde kaymayı ve savrulmayı davet eder.',
      'Sert fren, kaygan zeminde tekerlekleri kilitleyip kontrolü kaybettirir.',
      'Uyarı hava durumuna bağlı değildir; zemin kuru görünse de kaygan olabilir.',
    ],
    objective: 'Kaygan yol uyarısında yumuşak sürüş ve mesafe artırmayı bilmek.',
    tags: ['levha', 'kaygan-yol', 'fren-mesafesi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-629',
    subject: 'trafik',
    topic: 'hayvan-cikabilir-levhasi',
    difficulty: 'kolay',
    stem: 'Üçgen tehlike-uyarı levhasında bir geyik veya ehli hayvan sembolü bulunması sürücüye neyi anlatır?',
    options: [
      'İleride hayvanat bahçesi bulunduğunu',
      'Bu yolda hayvan taşımanın yasak olduğunu',
      'Yola hayvan çıkabileceğini; sürücünün hızını azaltıp dikkatli olması gerektiğini',
      'Hayvanların bu yolda serbestçe otlayabileceğini',
    ],
    answerIndex: 2,
    explanation:
      'Hayvan sembollü uyarı levhaları, o kesimde yola aniden hayvan çıkabileceğini bildirir. Sürücü hızını azaltıp uyanık olmalı; özellikle alacakaranlık ve gece saatlerinde daha dikkatli sürmelidir.',
    whyWrong: [
      'Levha bir tesis tanıtımı değil, tehlike uyarısıdır.',
      'Hayvan taşıma yasağı bu işaretle bildirilmez.',
      'İşaret otlatma izni değil, çıkabilecek hayvana karşı uyarıdır.',
    ],
    objective: 'Hayvan çıkabilir uyarı levhasının anlamını bilmek.',
    tags: ['levha', 'tehlike-uyari', 'hayvan'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-630',
    subject: 'trafik',
    topic: 'yandan-ruzgar-levhasi',
    difficulty: 'orta',
    stem: 'Yandan kuvvetli rüzgar uyarısı yapan levhanın bulunduğu açık bir kesime giren sürücü nasıl davranmalıdır?',
    options: [
      'Direksiyonu sıkıca kavramalı, hızını azaltmalı ve aracın yana savrulabileceğini hesaba katmalıdır',
      'Camları açıp rüzgarın geçmesini beklemelidir',
      'Hızlanarak rüzgarın etkisinden kurtulmalıdır',
      'Direksiyonu gevşek tutup aracın kendiliğinden düzelmesini beklemelidir',
    ],
    answerIndex: 0,
    explanation:
      'Yandan gelen kuvvetli rüzgar aracı, özellikle köprü ve açık kesim çıkışlarında yana itebilir. Sürücü direksiyona hakim olmalı, hızını azaltmalı ve rüzgarın kesildiği ani anlarda aracın sarsılabileceğini öngörmelidir.',
    whyWrong: [
      'Cam açmak rüzgarın araca etkisini gidermez.',
      'Hızlanmak yana savrulma etkisini büyütür.',
      'Direksiyonu gevşek tutmak, rüzgar itince kontrol kaybına yol açar.',
    ],
    objective: 'Yandan rüzgar uyarısında direksiyon hakimiyeti ve hız azaltmayı bilmek.',
    tags: ['levha', 'tehlike-uyari', 'ruzgar'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-631',
    subject: 'trafik',
    topic: 'gabari-yukseklik-levhasi',
    difficulty: 'orta',
    stem: 'Bir köprü altına veya tünel girişine yaklaşırken kırmızı çember içinde "3,5 m" yazan yükseklik (gabari) levhasını gören sürücü için hangisi doğrudur?',
    options: [
      'Levha yalnızca kamyonları ilgilendirir',
      'Hızını artırırsa yüksek araçla da geçebilir',
      'Levhadaki değer aracın hızını gösterir',
      'Yükü ile birlikte aracının yüksekliği bu değeri aşıyorsa oradan geçemez',
    ],
    answerIndex: 3,
    explanation:
      'Yükseklik levhası, geçilecek yapının izin verdiği azami yüksekliği bildirir. Aracın yüküyle birlikte yüksekliği bu değeri aşıyorsa geçiş yapamaz; zorlaması köprüye veya araca ciddi zarar verir.',
    whyWrong: [
      'Levha, o yükseklikteki her aracı bağlar; yalnız kamyonlara özgü değildir.',
      'Hız, aracın fiziksel yüksekliğini değiştirmez.',
      'Değer yükseklik sınırıdır, hız değil.',
    ],
    objective: 'Yükseklik (gabari) levhasının anlamını ve yük yüksekliğiyle ilişkisini bilmek.',
    tags: ['levha', 'gabari', 'yukseklik-siniri'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-632',
    subject: 'trafik',
    topic: 'engelli-park-yeri',
    difficulty: 'kolay',
    stem: 'Yalnızca engelli araçlarına ayrıldığı işaretlenmiş bir park yerine, engelli olmayan bir sürücünün aracını park etmesi nasıl değerlendirilir?',
    options: [
      'Kısa süreli ise sorun değildir',
      'Yasaktır; bu yerler engelli sürücülerin ihtiyacı için ayrılmıştır ve işgali cezalandırılır',
      'Boşsa herkes kullanabilir',
      'Gece serbesttir',
    ],
    answerIndex: 1,
    explanation:
      'Engelliler için ayrılmış park yerleri, hareket kısıtı olan sürücülerin erişimini kolaylaştırmak için düzenlenmiştir. Bu yerlere yetkisiz park etmek yasaktır ve cezai yaptırıma bağlanmıştır.',
    whyWrong: [
      'Sürenin kısalığı, ihtiyaç sahibinin yerini işgal etmeyi haklı çıkarmaz.',
      'Yerin boş görünmesi, o an gelecek engelli sürücünün hakkını ortadan kaldırmaz.',
      'Gece için bir ayrıcalık yoktur.',
    ],
    objective: 'Engelli park yerlerinin yetkisiz işgalinin yasak olduğunu bilmek.',
    tags: ['park', 'engelli-park', 'ihlal'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-633',
    subject: 'trafik',
    topic: 'kaldirima-park',
    difficulty: 'kolay',
    stem: 'Aracını kaldırıma (yaya yoluna) park eden bir sürücü için hangisi doğrudur?',
    options: [
      'Kaldırım genişse serbesttir',
      'Trafiğe engel olmuyorsa serbesttir',
      'Yasaktır; kaldırım yayalarındır, park eden araç yayaları taşıt yoluna inmek zorunda bırakır',
      'Yalnızca ticari araçlar için yasaktır',
    ],
    answerIndex: 2,
    explanation:
      'Kaldırım yayaların güvenli alanıdır. Buraya park eden araç yayaları, özellikle çocuk, yaşlı ve engellileri taşıt yoluna inip yürümek zorunda bırakır; bu yüzden kaldırıma park yasaktır.',
    whyWrong: [
      'Kaldırımın genişliği, onun yayalara ait olduğu gerçeğini değiştirmez.',
      'Araç engel olmasa bile kaldırım park yeri değildir.',
      'Yasak araç türüne bağlı değildir; tüm araçları kapsar.',
    ],
    objective: 'Kaldırıma park etmenin yaya güvenliği açısından yasak olduğunu bilmek.',
    tags: ['park', 'kaldirim', 'yaya-guvenligi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-634',
    subject: 'trafik',
    topic: 'kor-nokta-serit',
    difficulty: 'orta',
    stem: 'Şerit değiştirmeden hemen önce, aynalara baktıktan sonra bir de omuz üzerinden hızlı bir bakış (dönüp bakmak) yapmanın nedeni nedir?',
    options: [
      'Aynalarda görünmeyen kör noktadaki bir aracı veya motosikletliyi fark etmek',
      'Arkadaki sürücüye niyeti göstermek',
      'Direksiyon hakimiyetini artırmak',
      'Yakıt tüketimini düşürmek',
    ],
    answerIndex: 0,
    explanation:
      'Yan aynalar aracın hemen arka yanındaki bir bölgeyi, yani kör noktayı göstermez. Şerit değiştirmeden önce omuz üzerinden atılan kısa bir bakış, kör noktada bulunabilecek bir araç veya motosikletliyi görmeyi sağlar.',
    whyWrong: [
      'Niyet göstermek sinyalle yapılır; omuz kontrolünün amacı görmektir.',
      'Bu bakışın direksiyon hakimiyetiyle doğrudan ilgisi yoktur.',
      'Yakıt tüketimiyle hiçbir ilişkisi yoktur.',
    ],
    objective: 'Şerit değiştirmeden önce kör nokta kontrolünün amacını bilmek.',
    tags: ['serit-degistirme', 'kor-nokta', 'ayna-kontrolu'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-635',
    subject: 'trafik',
    topic: 'gorus-hiz-uyumu',
    difficulty: 'zor',
    stem: 'Gece veya sisli havada araç kullanırken hızın ayarlanmasında temel ilke hangisidir?',
    options: [
      'Yol boşsa görüşten bağımsız olarak azami hızla gidilebilir',
      'Öndeki araç ne kadar hızlıysa o hıza uyulur',
      'Hız her zaman sabit tutulur',
      'Araç, farların aydınlattığı yani görülebilen mesafe içinde durabilecek hızda sürülür',
    ],
    answerIndex: 3,
    explanation:
      'Güvenli hızın ölçütü, görüş mesafesidir: sürücü, önünü görebildiği mesafe içinde aracını durdurabileceği bir hızda gitmelidir. Görüş azaldıkça hız da azaltılır; aksi hâlde engel görüldüğünde durmak için mesafe kalmaz.',
    whyWrong: [
      'Azami hız bir üst sınırdır; görüş kısaldığında bu hız güvenli değildir.',
      'Öndeki aracın hızı, sizin görüş mesafenizi belirlemez.',
      'Hızı sabit tutmak, değişen görüş koşullarını göz ardı eder.',
    ],
    objective: 'Hızı görüş mesafesi içinde durabilecek şekilde ayarlamayı kavramak.',
    tags: ['hiz', 'gorus-mesafesi', 'fren-mesafesi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-636',
    subject: 'trafik',
    topic: 'kavsak-yaklasim-hiz',
    difficulty: 'kolay',
    stem: 'Görüşün kısıtlı olduğu, kontrolsüz bir kavşağa yaklaşan sürücünün hızıyla ilgili doğru davranış hangisidir?',
    options: [
      'Kavşağı hızla geçip riski kısaltmak',
      'Hızını azaltmak, gerekirse durabilecek şekilde kavşağa kontrollü girmek',
      'Hızını hiç değiştirmemek',
      'Gözlerini kapatıp korna çalarak geçmek',
    ],
    answerIndex: 1,
    explanation:
      'Kontrolsüz kavşakta hangi yönden araç veya yaya çıkacağı önceden bilinemez. Sürücü hızını azaltıp gerektiğinde durabilecek şekilde kavşağa girmeli, yan yolları kontrol etmelidir.',
    whyWrong: [
      'Hızla geçmek, aniden çıkan araç veya yayaya tepki süresini yok eder.',
      'Hızı değiştirmemek kavşağın taşıdığı riski göz ardı etmektir.',
      'Korna görüş sağlamaz; asıl gereken yavaşlayıp bakmaktır.',
    ],
    objective: 'Kontrolsüz kavşağa yaklaşırken hız azaltmayı bilmek.',
    tags: ['kavsak', 'hiz', 'gorus'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-637',
    subject: 'trafik',
    topic: 'islak-zemin-kayma',
    difficulty: 'orta',
    stem: 'Su birikintili ıslak bir yolda yüksek hızda giderken lastiklerle zemin arasına su girmesi sonucu aracın yol tutuşunu kaybetmesine (su üzerinde kayma) karşı en etkili önlem nedir?',
    options: [
      'Lastik hava basıncını iyice düşürmek',
      'Su birikintisine yüksek hızla girmek',
      'Hızı düşük tutmak, lastik diş derinliğini yeterli tutmak ve su birikintilerine yavaş girmek',
      'Sert fren yaparak aracı yavaşlatmak',
    ],
    answerIndex: 2,
    explanation:
      'Islak zeminde yüksek hızda lastik suyu tahliye edemezse araç su üzerinde kayar ve yol tutuşu kaybolur. Bunu önlemenin yolu hızı düşük tutmak, yeterli diş derinliğine sahip lastik kullanmak ve su birikintilerine yavaş girmektir.',
    whyWrong: [
      'Basıncı düşük lastik su tahliyesini zorlaştırır, kaymayı artırır.',
      'Birikintiye hızla girmek tam da kaymayı tetikleyen davranıştır.',
      'Kayma anında sert fren, kontrolü büsbütün kaybettirir.',
    ],
    objective: 'Islak zeminde su üzerinde kaymayı önleyen önlemleri bilmek.',
    tags: ['islak-zemin', 'lastik', 'hiz'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-638',
    subject: 'trafik',
    topic: 'uyusturucu-ilac-surus',
    difficulty: 'orta',
    stem: 'Uyuşturucu ya da uyku veren, sersemlik yapan bir madde veya ilaç etkisindeyken araç kullanmak ile ilgili hangisi doğrudur?',
    options: [
      'Yasaktır ve ağır yaptırıma bağlıdır; bu maddeler algı, dikkat ve tepki hızını bozar',
      'Az miktarda alınırsa sorun olmaz',
      'Yalnızca uzun yolda sakıncalıdır',
      'Reçeteli ilaç her durumda sürüşe engel değildir',
    ],
    answerIndex: 0,
    explanation:
      'Uyuşturucu ve sersemlik veren maddeler dikkati, algıyı ve tepki hızını bozarak sürücüyü trafikte tehlikeli hâle getirir. Bu maddelerin etkisinde araç kullanmak yasaktır ve ağır yaptırımlara bağlanmıştır.',
    whyWrong: [
      'Az miktar bile dikkat ve tepkiyi bozabilir; güvenli bir alt sınır kabul edilmez.',
      'Tehlike yol uzunluğuna değil, maddenin etkisine bağlıdır.',
      'Uyku yapan reçeteli ilaçlar da sürüşü tehlikeye atabilir; etken maddeye dikkat edilmelidir.',
    ],
    objective: 'Uyuşturucu ve sersemlik veren madde etkisinde sürüşün yasak olduğunu bilmek.',
    tags: ['uyusturucu', 'ilac', 'dikkat'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-639',
    subject: 'trafik',
    topic: 'hamile-emniyet-kemeri',
    difficulty: 'orta',
    stem: 'Hamile bir yolcunun otomobilde emniyet kemeri kullanımı ile ilgili en doğru bilgi hangisidir?',
    options: [
      'Hamileler kemer takmamalıdır',
      'Kemerin karın bölgesinin tam üzerinden geçmesi gerekir',
      'Kemer yalnızca omuzdan takılmalı, kucak kısmı kullanılmamalıdır',
      'Kemer takılmalı; kucak kemeri karnın altından, kalça üzerinden; omuz kemeri göğüs ortasından geçecek şekilde konumlandırılmalıdır',
    ],
    answerIndex: 3,
    explanation:
      'Hamilelikte de emniyet kemeri hayat kurtarır. Doğru kullanım, kucak kemerini karnın üzerinden değil altından, kalça kemikleri üzerinden geçirmek; omuz kemerini ise göğsün ortasından, karna baskı yapmadan konumlandırmaktır.',
    whyWrong: [
      'Kemersiz yolculuk, çarpışmada hem anne hem bebek için çok daha risklidir.',
      'Kemerin karın üzerinden geçmesi, darbe anında karna baskı yapar; doğrusu karnın altından geçirmektir.',
      'Yalnızca omuz kemeri, gövdeyi yeterince tutmaz; kucak kısmı da gereklidir.',
    ],
    objective: 'Hamilelikte emniyet kemerinin doğru konumlandırılmasını bilmek.',
    tags: ['emniyet-kemeri', 'hamile', 'guvenli-kullanim'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-640',
    subject: 'trafik',
    topic: 'geri-manevra-guvenlik',
    difficulty: 'orta',
    stem: 'Dar bir alanda geri manevra yapacak sürücünün güvenlik açısından yapması gereken nedir?',
    options: [
      'Sadece dikiz aynasına bakıp hızla geri gitmek',
      'Manevradan önce aracın arkasını kontrol etmek, gerekirse inip bakmak veya bir gözcüden yardım almak ve yavaş hareket etmek',
      'Korna çalarak arkadakilerin kaçmasını beklemek',
      'Geri giderken telefonla konuşarak beklemek',
    ],
    answerIndex: 1,
    explanation:
      'Aracın hemen arkası, sürücünün göremediği bir kör alandır; burada özellikle çocuklar bulunabilir. Geri manevradan önce arka kontrol edilir, gerekirse inilip bakılır veya bir gözcüden yardım alınır ve manevra yavaş yapılır.',
    whyWrong: [
      'Yalnız aynaya güvenip hızlı geri gitmek, arkadaki alçak engeli veya çocuğu göremez.',
      'Korna kontrolün yerine geçmez; görmek esastır.',
      'Manevra sırasında dikkat dağıtan hiçbir şeyle uğraşılmaz.',
    ],
    objective: 'Geri manevrada arka kontrolü ve yavaş hareketi benimsemek.',
    tags: ['geri-manevra', 'kor-alan', 'yaya-guvenligi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-641',
    subject: 'trafik',
    topic: 'kask-zorunlulugu',
    difficulty: 'kolay',
    stem: 'Motosiklet ve motorlu bisiklet sürücüleri ile bunların yolcuları için koruyucu başlık (kask) kullanımı hangi durumda gereklidir?',
    options: [
      'Yalnızca şehirlerarası yolda',
      'Yalnızca sürücü için, yolcu muaftır',
      'Hem sürücü hem yolcu için, kask takmak zorunludur',
      'Yalnızca yüksek hızda',
    ],
    answerIndex: 2,
    explanation:
      'Motosiklet ve motorlu bisikletlerde koruyucu başlık takmak hem sürücü hem yolcu için zorunludur. Kask, kaza anında ölümcül kafa yaralanmalarını önemli ölçüde azaltan en temel koruyucudur.',
    whyWrong: [
      'Zorunluluk yolun türüne göre değişmez; şehir içinde de geçerlidir.',
      'Yalnız sürücü değil, arkadaki yolcu da kask takmak zorundadır.',
      'Düşük hızdaki bir kaza bile ağır kafa yaralanmasına yol açabilir.',
    ],
    objective: 'Kask zorunluluğunun sürücü ve yolcuyu kapsadığını bilmek.',
    tags: ['motosiklet', 'kask', 'koruyucu-donanim'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-642',
    subject: 'trafik',
    topic: 'tasan-yuk-gece-isaret',
    difficulty: 'orta',
    stem: 'Aracın arkasından taşan uzun bir yükün en uç noktası, gece ve görüşün az olduğu zamanlarda nasıl işaretlenmelidir?',
    options: [
      'Kırmızı ışık veya kırmızı yansıtıcı (reflektör) ile',
      'Beyaz bir bezle',
      'Hiçbir işaret gerekmez',
      'Yeşil ışıkla',
    ],
    answerIndex: 0,
    explanation:
      'Taşan yükün ucu, arkadan gelen sürücüler tarafından geç fark edilir. Gündüz kırmızı bez veya işaretle; gece ve görüşün az olduğu zamanlarda ise kırmızı ışık veya kırmızı yansıtıcı ile belirtilerek çarpışma önlenir.',
    whyWrong: [
      'Beyaz bez gece yeterince dikkat çekmez; kural kırmızı işarettir.',
      'İşaretsiz taşan yük, arkadan çarpışmaya davetiye çıkarır.',
      'Yeşil ışık tehlike-uyarı rengi değildir.',
    ],
    objective: 'Taşan yükün gece kırmızı ışık veya yansıtıcı ile işaretlenmesini bilmek.',
    tags: ['yukleme', 'tasan-yuk', 'gece-isaret'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-643',
    subject: 'trafik',
    topic: 'romork-yolcu-yasagi',
    difficulty: 'orta',
    stem: 'Yük taşımak için kullanılan bir römork veya tarım römorkunda insan taşınması ile ilgili genel kural nedir?',
    options: [
      'Kısa mesafede serbesttir',
      'Oturarak gidilirse serbesttir',
      'Yavaş gidilirse serbesttir',
      'Yük römorkunda insan taşınması kural olarak yasaktır',
    ],
    answerIndex: 3,
    explanation:
      'Yük römorkları insan taşımak için tasarlanmamıştır; oturma düzeni, tutunma yeri ve güvenlik donanımı yoktur. Bu nedenle yük römorklarında ve tarım römorklarında insan taşımak kural olarak yasaktır; savrulma ve düşme riski çok yüksektir.',
    whyWrong: [
      'Mesafenin kısalığı düşme ve savrulma riskini ortadan kaldırmaz.',
      'Römorkta oturmak, ani fren veya sarsıntıda güvenlik sağlamaz.',
      'Yavaş gitmek bile devrilme veya düşmeyi önlemez.',
    ],
    objective: 'Yük römorkunda insan taşımanın yasak olduğunu bilmek.',
    tags: ['romork', 'yolcu-yasagi', 'yukleme'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-644',
    subject: 'trafik',
    topic: 'refuj-gecme-yasagi',
    difficulty: 'zor',
    stem: 'Bölünmüş bir yolda gidiş ve geliş yönlerini ayıran refüjün (orta ayırıcının) üzerinden geçerek karşı yöne geçmek nasıl değerlendirilir?',
    options: [
      'Trafik azsa serbesttir',
      'Yasaktır; refüj iki yönü ayırmak içindir, üzerinden geçmek karşı yöne çıkıp kafa kafaya çarpışma riski doğurur',
      'Acele eden sürücüler için serbesttir',
      'Refüj alçaksa serbesttir',
    ],
    answerIndex: 1,
    explanation:
      'Refüj, karşılıklı yönleri fiziksel olarak ayırarak kafa kafaya çarpışmaları önler. Refüj üzerinden karşı yöne geçmek, aracı ters yönden gelen trafiğin karşısına çıkarır ve bu yüzden yasaktır; karşı yöne ancak dönüşe izin verilen açıklıklardan geçilir.',
    whyWrong: [
      'Trafiğin azlığı, karşı yöne çıkmanın yarattığı ölümcül riski değiştirmez.',
      'Acele bir gerekçe değildir; kural herkes için geçerlidir.',
      'Refüjün alçak olması onun ayırıcı işlevini ortadan kaldırmaz.',
    ],
    objective: 'Refüj üzerinden karşı yöne geçmenin yasak olduğunu kavramak.',
    tags: ['refuj', 'bolunmus-yol', 'ters-yon'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-645',
    subject: 'trafik',
    topic: 'kavsak-ortasi-durma',
    difficulty: 'kolay',
    stem: 'Trafiğin sıkışık olduğu bir anda ışık yeşile döndü; ancak kavşağın karşı tarafı doludur ve kavşakta durmak zorunda kalacaksınız. Ne yapmalısınız?',
    options: [
      'Yeşil yandığı için kavşağa girip ortada beklemek',
      'Korna çalarak öndeki araçları itmek',
      'Karşı taraf boşalıp kavşağı geçebileceğinizden emin olmadan kavşağa girmemek',
      'Kavşağın ortasında durup diğer yönlere yol vermemek',
    ],
    answerIndex: 2,
    explanation:
      'Kavşak içinde durup kalmak, diğer yönlerin geçişini kilitler ve trafiği tıkar. Işık yeşil olsa bile, karşı taraf kavşağı geçmenize yetecek kadar boşalmadan kavşağa girilmez.',
    whyWrong: [
      'Yeşil ışık, kavşağı boşaltamayacağınız hâlde girme hakkı vermez.',
      'Korna öndeki tıkanıklığı açmaz; yalnızca gürültü yaratır.',
      'Kavşak ortasında durmak tam da önlenmek istenen kilitlenmeyi doğurur.',
    ],
    objective: 'Kavşağı boşaltamayacaksa kavşağa girmeme kuralını bilmek.',
    tags: ['kavsak', 'trafik-akisi', 'yesil-isik'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-646',
    subject: 'trafik',
    topic: 'uzun-far-kullanimi',
    difficulty: 'kolay',
    stem: 'Gece yerleşim yeri dışında, karşıdan gelen veya önünde takip ettiği araç bulunmayan boş bir yolda sürücü hangi farı kullanabilir?',
    options: [
      'Uzağı iyi görebilmek için uzun huzmeli (uzun) farları',
      'Yalnızca park lambalarını',
      'Sadece sis farlarını',
      'Hiçbir far kullanmadan gitmeyi',
    ],
    answerIndex: 0,
    explanation:
      'Karşıdan araç gelmeyen ve önde takip edilen araç bulunmayan açık yolda, daha uzağı görebilmek için uzun far kullanılabilir. Ancak karşıdan araç geldiğinde veya bir araca yaklaşıldığında derhal kısa fara geçilmelidir.',
    whyWrong: [
      'Park lambaları yolu aydınlatmaz; seyir için yeterli değildir.',
      'Sis farları sis olmayan durumda gerekli aydınlatmayı vermez.',
      'Gece farsız sürmek görüşü yok eder ve son derece tehlikelidir.',
    ],
    objective: 'Boş açık yolda uzun far kullanımını ve kısa fara geçme koşulunu bilmek.',
    tags: ['far-isik', 'uzun-far', 'gece-surus'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-647',
    subject: 'trafik',
    topic: 'arka-sis-lambasi',
    difficulty: 'orta',
    stem: 'Aracın arka sis lambasının doğru kullanımı ile ilgili hangisi doğrudur?',
    options: [
      'Gece her zaman açık tutulmalıdır',
      'Şehir içinde sürekli yanmalıdır',
      'Öndeki aracı uyarmak için kullanılır',
      'Yalnızca yoğun sis veya kar gibi görüşü ciddi düşüren durumlarda yakılır, görüş açılınca söndürülür',
    ],
    answerIndex: 3,
    explanation:
      'Arka sis lambası çok parlaktır; amacı, yoğun sis veya kar gibi görüşün çok düştüğü durumlarda aracın arkadan fark edilmesini sağlamaktır. Görüş normalken açık bırakılırsa arkadaki sürücüyü rahatsız eder ve fren lambasıyla karışır.',
    whyWrong: [
      'Gece açık normal koşullarda sürekli yakmak arkadaki sürücüyü kamaştırır.',
      'Şehir içi aydınlık yolda arka sis lambasına gerek yoktur.',
      'Arka sis lambası öne değil, arkadaki sürücüye yönelik bir işaret verir.',
    ],
    objective: 'Arka sis lambasının yalnızca düşük görüşte kullanılacağını bilmek.',
    tags: ['far-isik', 'arka-sis-lambasi', 'sis'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-648',
    subject: 'trafik',
    topic: 'far-ile-uyari',
    difficulty: 'orta',
    stem: 'Öndeki aracı, hızlanıp yol vermesi için farla (selektörle) sürekli rahatsız eden, sıkıştıran bir sürücü için ne söylenebilir?',
    options: [
      'Trafiği hızlandırdığı için doğru davranıştır',
      'Yanlış ve tehlikelidir; baskı ve sıkıştırma kaza riskini artırır, geçiş hakkı da doğurmaz',
      'Yalnızca gündüz sakıncalıdır',
      'Öndeki araç yavaşsa serbesttir',
    ],
    answerIndex: 1,
    explanation:
      'Farla sürekli sinyal vererek öndeki aracı sıkıştırmak, sürücüde panik ve yanlış manevralara yol açar. Selektör bir geçiş hakkı doğurmaz; bu davranış hem trafik adabına aykırı hem de kaza riskini artıran tehlikeli bir baskıdır.',
    whyWrong: [
      'Baskı trafiği güvenli biçimde hızlandırmaz, tehlikeyi büyütür.',
      'Davranış gece de gündüz de aynı ölçüde sakıncalıdır.',
      'Öndeki aracın yavaşlığı, onu sıkıştırma hakkı vermez.',
    ],
    objective: 'Farla sıkıştırmanın geçiş hakkı doğurmadığını ve tehlikeli olduğunu kavramak.',
    tags: ['far-isik', 'selektor', 'trafik-adabi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-649',
    subject: 'trafik',
    topic: 'donus-sinyal-zamani',
    difficulty: 'kolay',
    stem: 'Bir kavşakta sağa veya sola dönecek sürücü dönüş sinyalini ne zaman vermelidir?',
    options: [
      'Dönüşe başladığı anda',
      'Dönüş bittikten sonra',
      'Dönüşe girmeden yeterince önce, arkadan ve yandan gelenlerin niyeti anlayabileceği zamanda',
      'Yalnızca trafik varsa',
    ],
    answerIndex: 2,
    explanation:
      'Dönüş sinyali, diğer sürücü ve yayaların niyeti önceden anlayıp önlem alması içindir. Bu yüzden sinyal dönüşe girmeden yeterince önce verilir; dönüş anında verilen sinyalin uyarı değeri kalmaz.',
    whyWrong: [
      'Dönüş anında verilen sinyal, arkadakine tepki için zaman bırakmaz.',
      'Dönüş bitince verilen sinyalin hiçbir işlevi yoktur.',
      'Sinyal, trafik olsun olmasın önceden verilmesi gereken bir kuraldır.',
    ],
    objective: 'Dönüş sinyalinin manevradan yeterince önce verileceğini bilmek.',
    tags: ['donus', 'sinyal', 'manevra'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-650',
    subject: 'trafik',
    topic: 'okul-bolgesi-hiz',
    difficulty: 'kolay',
    stem: 'Okulların giriş ve çıkış saatlerinde bir okulun önünden geçen sürücünün en doğru davranışı hangisidir?',
    options: [
      'Hızını iyice azaltıp her an yola çıkabilecek öğrencilere karşı hazırlıklı olmak',
      'Korna çalarak öğrencileri uzak tutmak',
      'Boş göründüğü an hızlanıp bölgeyi geçmek',
      'Öğrencilerin kendisini görüp durmasını beklemek',
    ],
    answerIndex: 0,
    explanation:
      'Okul çevresinde, özellikle giriş çıkış saatlerinde çocuklar ani ve öngörülemez hareket eder. Sürücü hızını iyice azaltmalı, frene hazır olmalı ve her an yola bir öğrenci çıkabileceğini varsaymalıdır.',
    whyWrong: [
      'Korna çocukları ürkütüp yanlış yöne kaçırabilir.',
      'Hızlanmak, aniden çıkan çocuğa tepki süresini yok eder.',
      'Çocuğun aracı fark edip duracağını varsaymak güvenli değildir; dikkat sürücüde olmalıdır.',
    ],
    objective: 'Okul çevresinde hız azaltıp çocuk hareketine hazır olmayı bilmek.',
    tags: ['okul-bolgesi', 'cocuk-guvenligi', 'hiz'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-651',
    subject: 'trafik',
    topic: 'uzun-inis-motor-freni',
    difficulty: 'orta',
    stem: 'Uzun ve dik bir inişte frenlerin aşırı ısınıp verimini kaybetmesini önlemek için en doğru yöntem hangisidir?',
    options: [
      'Vitesi boşa alıp yalnızca fren pedalıyla inmek',
      'İnişe yüksek hızla girip zamanı kısaltmak',
      'Motoru durdurup kontağı kapatarak inmek',
      'Uygun bir küçük vitese geçip motor freninden yararlanmak, frene aralıklı basmak',
    ],
    answerIndex: 3,
    explanation:
      'Uzun inişte sürekli fren pedalına basmak frenleri ısıtıp verimini düşürür. Doğru yöntem, uygun bir küçük vitese geçerek motor freninden yararlanmak ve fren pedalını sürekli değil aralıklı kullanmaktır.',
    whyWrong: [
      'Vitesi boşa almak motor frenini devre dışı bırakır; tüm yük frene biner ve frenler ısınır.',
      'Yüksek hızla inmek kontrolü zorlaştırır ve fren yükünü artırır.',
      'Kontağı kapatmak direksiyon ve fren desteğini kaybettirerek çok tehlikeli olur.',
    ],
    objective: 'Uzun inişte motor freninden yararlanmayı bilmek.',
    tags: ['inis', 'motor-freni', 'fren'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-652',
    subject: 'trafik',
    topic: 'sollama-yasak-yer',
    difficulty: 'orta',
    stem: 'Aşağıdaki yerlerden hangisinde öndeki aracı geçmek (sollama) genel olarak yasaktır?',
    options: [
      'Görüşün açık olduğu düz ve geniş yollarda',
      'Tepe üstlerinde, keskin virajlarda, yaya geçitlerinde ve kavşaklarda',
      'Karşı şeridin uzun süre boş olduğu yollarda',
      'Geçme yasağı işareti bulunmayan her yerde',
    ],
    answerIndex: 1,
    explanation:
      'Sollama, karşı şeridin görülebildiği ve boş olduğu yerlerde yapılabilir. Tepe üstü ve keskin viraj görüşü kapatır; yaya geçidi ve kavşak ise yaya ile başka araçların hareket alanıdır. Bu yerlerde sollama yasaktır.',
    whyWrong: [
      'Görüşün açık olduğu düz yol, güvenli sollamanın yapılabileceği yerdir.',
      'Karşı şeridin uzun süre boş ve görüşün açık olması sollamaya elverişlidir.',
      'İşaret olmasa da tepe, viraj, kavşak gibi yerlerde sollama kural gereği yasaktır.',
    ],
    objective: 'Görüşün kapalı olduğu yerler ile kavşak ve yaya geçidinde sollama yasağını bilmek.',
    tags: ['sollama', 'yasak-yer', 'gorus-mesafesi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-653',
    subject: 'trafik',
    topic: 'tramvay-oncelik',
    difficulty: 'orta',
    stem: 'Bir kavşakta, rayları üzerinde hareket eden bir tramvay ile lastik tekerlekli sıradan bir araç karşılaştığında geçiş önceliği kimindir?',
    options: [
      'Her zaman lastik tekerlekli araçta',
      'Sağdan gelene bakılır, tramvayın türü önemli değildir',
      'Rayları üzerinde hareket eden tramvayda; diğer araçlar ona yol verir',
      'Kavşağa önce girene',
    ],
    answerIndex: 2,
    explanation:
      'Raylı taşıtlar, rayların dışına çıkarak manevra yapamaz ve durma mesafeleri uzundur. Bu nedenle kavşaklarda ray üzerinde hareket eden tramvaylara geçiş önceliği tanınır; diğer araçlar onlara yol verir.',
    whyWrong: [
      'Öncelik lastik tekerlekli araçta değil, raylı taşıttadır.',
      'Raylı taşıtın önceliği, sağdan gelme kuralının önüne geçer.',
      'Tramvay manevra yapamadığı için kavşağa giriş sırasına göre değil, kural gereği önceliklidir.',
    ],
    objective: 'Kavşakta raylı taşıta öncelik verildiğini bilmek.',
    tags: ['oncelik', 'tramvay', 'kavsak'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-654',
    subject: 'trafik',
    topic: 'yol-ver-dur-fark',
    difficulty: 'orta',
    stem: 'DUR (sekizgen) levhası ile Yol Ver (ters üçgen) levhasının sürücüye yüklediği yükümlülük arasındaki temel fark nedir?',
    options: [
      'DUR levhasında mutlaka tam durmak gerekir; Yol Ver levhasında ise yavaşlayıp gerekiyorsa yol verilir, yol boşsa durmadan geçilebilir',
      'İkisi de mutlaka tam durmayı gerektirir',
      'İkisinde de durmadan geçilebilir',
      'DUR yalnızca gece, Yol Ver yalnızca gündüz geçerlidir',
    ],
    answerIndex: 0,
    explanation:
      'DUR levhasında sürücü, yol boş olsa bile durma çizgisinde tam olarak durup öyle geçmek zorundadır. Yol Ver levhasında ise tam durma zorunluluğu yoktur; sürücü yavaşlar, gerekirse yol verir, ancak yol güvenliyse durmadan geçebilir.',
    whyWrong: [
      'Yol Ver levhası her zaman tam durmayı gerektirmez; ikisini aynı saymak yanlıştır.',
      'DUR levhasında durmadan geçmek ihlaldir.',
      'Levhaların geçerliliği gece-gündüz ayrımına bağlı değildir.',
    ],
    objective: 'DUR ve Yol Ver levhaları arasındaki durma yükümlülüğü farkını bilmek.',
    tags: ['levha', 'dur', 'yol-ver'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-655',
    subject: 'trafik',
    topic: 'bisikletli-saga-donus',
    difficulty: 'zor',
    stem: 'Sağa dönmek üzere olan bir sürücü, sağ tarafında aynı yöne giden bir bisikletli fark ederse nasıl davranmalıdır?',
    options: [
      'Bisikletliden önce hızla dönmeye çalışmak',
      'Korna çalıp bisikletliyi durdurmaya çalışmak',
      'Bisikletlinin arasından sıyrılarak dönmek',
      'Bisikletlinin geçmesini beklemek ya da güvenli mesafe oluşana kadar dönmemek; onu sıkıştırmamak',
    ],
    answerIndex: 3,
    explanation:
      'Sağa dönerken sağdaki bisikletli, dönüş yayının içinde sıkışıp kalabilir. Sürücü bisikletliyi geçmesini beklemeli veya güvenli mesafe oluşmadan dönmemeli; asla onun önünü keserek sıkıştırmamalıdır.',
    whyWrong: [
      'Bisikletlinin önünden aceleyle dönmek onu düşme veya çarpışma riskine sokar.',
      'Korna bisikletlinin dengesini bozup düşmesine yol açabilir.',
      'Bisikletlinin yanından sıyrılmak yeterli yan mesafeyi ortadan kaldırır.',
    ],
    objective: 'Sağa dönüşte sağdaki bisikletliyi sıkıştırmamayı kavramak.',
    tags: ['bisiklet', 'saga-donus', 'yan-mesafe'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-656',
    subject: 'trafik',
    topic: 'gece-yavas-arac-gorunurluk',
    difficulty: 'orta',
    stem: 'Gece karayolunda ilerleyen traktör gibi yavaş ve ağır bir aracın arkadan gelen sürücüler tarafından fark edilmesi neden özellikle önemlidir?',
    options: [
      'Yavaş araçların gece sürmesi tamamen yasak olduğu için',
      'Hızlı gelen araç önündeki yavaş aracı geç fark ederse arkadan çarpma riski çok yükseldiği için, bu araçların lamba ve yansıtıcılarının çalışır olması gerekir',
      'Yavaş araçların farı olması gerekmediği için',
      'Gece görüşün gündüzden daha iyi olduğu için',
    ],
    answerIndex: 1,
    explanation:
      'Gece, arkadan hızla yaklaşan bir sürücü önündeki yavaş aracın hızını yanlış değerlendirebilir. Yavaş aracın arka lambaları ve yansıtıcıları çalışır durumda değilse, aradaki hız farkı yüzünden arkadan çarpma riski çok yükselir.',
    whyWrong: [
      'Yavaş araçların gece seyri kural gereği yasak değildir; görünür olmaları gerekir.',
      'Bütün motorlu araçların gece için aydınlatma ve yansıtıcı bulundurması gerekir.',
      'Gece görüş gündüzden daha kısıtlıdır, daha iyi değil.',
    ],
    objective: 'Gece yavaş araçların görünürlüğünün arkadan çarpmayı önlemedeki önemini kavramak.',
    tags: ['gece-surus', 'gorunurluk', 'yansitici'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-657',
    subject: 'trafik',
    topic: 'refuj-tanim',
    difficulty: 'kolay',
    stem: 'Trafikte "refüj" (orta ayırıcı) hangi bölümü ifade eder?',
    options: [
      'Taşıt yolunun en sağ kenarındaki durma şeridini',
      'Kavşaktaki yaya geçidini',
      'Taşıtların güvenli seyri için, karşılıklı yönleri veya aynı yöndeki şeritleri birbirinden ayıran, yükseltilmiş veya çizgilerle belirlenmiş bölümü',
      'Yol kenarındaki park cebini',
    ],
    answerIndex: 2,
    explanation:
      'Refüj, gidiş-geliş yönlerini veya trafik akımlarını birbirinden ayıran orta bölümdür; genellikle yükseltilmiş bir ada veya ayırıcı ile oluşturulur ve kafa kafaya çarpışmaları önlemede önemli rol oynar.',
    whyWrong: [
      'En sağ kenardaki bölüm banket veya emniyet şerididir.',
      'Yaya geçidi taşıt yolunu yayaların geçmesi için ayrılmış bölümdür.',
      'Park cebi, araçların duraklaması için ayrılmış kenar bölümdür.',
    ],
    objective: 'Refüj (orta ayırıcı) kavramını doğru tanımlamak.',
    tags: ['refuj', 'tanimlar', 'bolunmus-yol'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-658',
    subject: 'trafik',
    topic: 'arac-terk-guvenlik',
    difficulty: 'kolay',
    stem: 'Aracını park edip yanından ayrılacak bir sürücünün güvenlik için yapması gereken hangisidir?',
    options: [
      'El frenini çekmek, motoru durdurmak, aracı uygun vitese takıp kontak anahtarını alarak kapıları kilitlemek',
      'Motoru çalışır bırakıp gitmek',
      'El frenini çekmeden aracı boşta bırakmak',
      'Anahtarı üzerinde bırakıp kapıları açık tutmak',
    ],
    answerIndex: 0,
    explanation:
      'Terk edilen araç kendiliğinden hareket etmemeli ve yetkisiz kişilerce kullanılmamalıdır. Bunun için el freni çekilir, motor durdurulur, araç uygun vitese takılır, kontak anahtarı alınır ve kapılar kilitlenir.',
    whyWrong: [
      'Motoru çalışır bırakmak hem yakıt israfı hem güvenlik ve hırsızlık riskidir.',
      'El freni çekilmeyen ve boşta bırakılan araç kendiliğinden kayabilir.',
      'Anahtarı üzerinde ve kapıları açık bırakmak aracın yetkisiz kullanımına davetiye çıkarır.',
    ],
    objective: 'Park edilen aracı güvenli biçimde terk etme adımlarını bilmek.',
    tags: ['park', 'el-freni', 'arac-guvenligi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-659',
    subject: 'trafik',
    topic: 'cocuk-top-yol',
    difficulty: 'zor',
    stem: 'Yol kenarında top oynayan çocukların bulunduğu bir sokakta ilerlerken, topun yola doğru yuvarlandığını gördünüz. En doğru öngörülü davranış hangisidir?',
    options: [
      'Çocuklar yola çıkmaz diye varsayıp aynı hızla devam etmek',
      'Korna çalıp hızlanarak bölgeyi geçmek',
      'Yalnızca topa dikkat edip çocukları göz ardı etmek',
      'Bir çocuğun topun peşinden düşünmeden yola fırlayabileceğini öngörüp derhal hızı kesmek ve durmaya hazır olmak',
    ],
    answerIndex: 3,
    explanation:
      'Yola yuvarlanan top, çoğu zaman peşinden koşan bir çocuğun geleceğinin habercisidir. Çocuklar tehlikeyi değerlendiremeden yola fırlayabilir; öngörülü sürücü hemen hızını keser ve durmaya hazır olur.',
    whyWrong: [
      'Çocukların yola çıkmayacağını varsaymak, en sık ölümlü kazalara yol açan hatadır.',
      'Hızlanmak, yola fırlayan çocuğa tepki süresini tamamen yok eder.',
      'Topu değil, asıl onun peşinden gelebilecek çocuğu öngörmek gerekir.',
    ],
    objective: 'Yola giren topun ardından çocuk gelebileceğini öngörüp yavaşlamayı kavramak.',
    tags: ['yaya-guvenligi', 'cocuk', 'ongoru'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-660',
    subject: 'trafik',
    topic: 'gecis-hakki-devretme',
    difficulty: 'zor',
    stem: 'Kavşakta geçiş hakkı sizde olduğu hâlde, yan yoldan gelen bir araç kural tanımadan kavşağa girip önünüzü kesmek üzereyse ne yapmalısınız?',
    options: [
      'Hakkım var deyip hız kesmeden devam etmek',
      'Kaza olmaması için hakkımdan vazgeçip fren yapmak ve o aracın geçmesine izin vermek',
      'Korna çalıp hızlanarak önce geçmeye çalışmak',
      'Aracımla o aracı durmaya zorlamak',
    ],
    answerIndex: 1,
    explanation:
      'Geçiş hakkı bir öncelik tanır ama kaza yapma hakkı vermez. Karşı taraf kuralı çiğneyip önünüze çıkıyorsa, güvenli sürüşün gereği hakkınızdan vazgeçip fren yaparak çarpışmayı önlemektir.',
    whyWrong: [
      'Hakka güvenip devam etmek, önlenebilir bir kazaya neden olur.',
      'Hızlanıp önce geçmeye çalışmak çarpışmayı kaçınılmaz kılar.',
      'Diğer aracı zorlamak, iki aracı da tehlikeye atan saldırgan bir davranıştır.',
    ],
    objective: 'Kaza tehlikesi karşısında geçiş hakkından vazgeçmenin önceliğini kavramak.',
    tags: ['gecis-hakki', 'savunmaci-surus', 'kavsak'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
];
