/**
 * ÖZGÜN direksiyon (uygulama) soruları — 6. genişletme (Program 2 · Faz 9). ROADMAP C.4/E.6.
 * Kaynak = MEB direksiyon/uygulama müfredatı; KENDİ İFADEMİZLE.
 */
import type { QuestionInput } from '@ea/content-schema';

const SRC = 'MEB direksiyon (uygulama) müfredatı (özgün ifade)';

export const PRATIK_QUESTIONS_6: QuestionInput[] = [
  {
    id: 'pratik-601',
    subject: 'pratik',
    topic: 'sinav-arac-tanima',
    difficulty: 'kolay',
    stem: 'Direksiyon sınavına kendi eğitim aracınızdan farklı bir araçla girecekseniz, hareket etmeden önce hangi ayrıntıyı tanımak özellikle işe yarar?',
    options: [
      'Aracın müzik sisteminin nasıl çalıştığını',
      'Yakıt deposunun kaç litre olduğunu',
      'Vites şemasını ve geri vitesin hangi hareketle (kilit halkasını çekerek ya da kola bastırarak) takıldığını',
      'Aracın kaç kilometrede olduğunu',
    ],
    answerIndex: 2,
    explanation:
      'Her aracın vites deseni ve özellikle geri vitesin devreye alınış biçimi farklıdır; kimi araçta kolun altındaki halka çekilir, kiminde kola bastırılır. Bu ayrıntı manevra anında bilinmezse geri vites bulunamaz, motor stop eder ve telaş büyür. Kalkıştan önce vites şemasına bir kez göz atmak bu tökezlemeyi baştan önler.',
    whyWrong: [
      'Müzik sistemi, depo hacmi ya da kilometre bilgisi sürüşü ve manevrayı etkilemez.',
      'Sınavda değerlendirilen sürüş becerisidir; bu ayrıntılar becerinin sergilenmesine katkı sağlamaz.',
    ],
    objective:
      'Yabancı sınav aracında vites şemasını ve geri vites mekanizmasını önceden tanımanın önemini kavramak.',
    tags: ['sinav-hazirlik', 'vites-semasi', 'geri-vites'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-602',
    subject: 'pratik',
    topic: 'sinav-hazirlik-sirasi',
    difficulty: 'orta',
    stem: 'Sınav aracına oturan adayın hareketten önceki hazırlığında öğretilen mantıklı sıralama hangisidir?',
    options: [
      'Önce koltuk ve direksiyon mesafesi ayarlanır, sonra aynalar düzenlenir, en son emniyet kemeri takılır; sıra bu yönde ilerler çünkü oturuş değişince ayna açısı da değişir',
      'Önce kemer takılır, sonra koltuk ileri çekilir, en son aynalara bakılır',
      'Önce aynalar ayarlanır, sonra koltuk konumu değiştirilir',
      'Sıralamanın hiçbir önemi yoktur; hepsi rastgele yapılabilir',
    ],
    answerIndex: 0,
    explanation:
      'Ayna açısı, sürücünün gövde ve baş konumuna göre belirlenir; bu yüzden önce koltuk ile direksiyon mesafesi oturur, ardından aynalar bu son konuma göre ayarlanır, en son emniyet kemeri takılır. Ters sırada yapılırsa koltuğu sonradan oynatan aday aynalarını yeniden bozar. Görevli bu hazırlığın yapıldığını ve mantıklı bir düzende ilerlediğini gözlemler.',
    whyWrong: [
      'Koltuğu aynalardan sonra ayarlamak, ayarlanmış ayna açısını yeniden bozar ve iş iki kez yapılır.',
      'Sıralamayı önemsiz saymak, hazırlığın eksik ya da dağınık yapılmasına yol açar.',
    ],
    objective: 'Hareket öncesi koltuk-ayna-kemer hazırlığını doğru sırayla yapabilmek.',
    tags: ['sinav-hazirlik', 'koltuk-ayar', 'ayna-ayar'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-603',
    subject: 'pratik',
    topic: 'sinav-motor-stop-toparlama',
    difficulty: 'orta',
    stem: 'Sınav sırasında kalkışta motoru bir kez stop ettiren adayın en doğru davranışı nedir?',
    options: [
      'Telaşlanıp arka arkaya marşa basarak aracı zorlamak',
      'El frenini çekip vitesi boşa alarak sakince yeniden çalıştırmak, sonra düzgün bir kalkış yapmak; tek seferlik stop tek başına elemeli sayılmaz, asıl bakılan toparlanabilmektir',
      'Aracı stop hâlinde bırakıp görevliyi beklemek',
      'Motoru çalıştırmadan debriyaja basıp aracın kendiliğinden yürümesini beklemek',
    ],
    answerIndex: 1,
    explanation:
      'Tek bir stop çoğunlukla heyecana bağlıdır ve başlı başına adayı elemez; görevlinin izlediği, adayın soğukkanlılıkla toparlanıp güvenli bir kalkış yapabilmesidir. Doğru refleks vitesi boşa alıp aracı emniyete almak, sakince yeniden çalıştırmak ve düzgün kalkıştır. Panikle tekrar tekrar stop ettirmek ise araç hâkimiyeti zafiyetine dönüşerek asıl sorunu büyütür.',
    whyWrong: [
      'Panikle üst üste marşa yüklenmek yeni stopları ve hâkimiyet kaybını davet eder.',
      'Aracı öylece bırakmak ya da motorsuz yürüme beklemek, kalkış problemini hiç çözmez.',
    ],
    objective: 'Tek seferlik motor stopunda sakin toparlanmanın önemini kavramak.',
    tags: ['sinav-degerlendirme', 'motor-stop', 'toparlanma'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-604',
    subject: 'pratik',
    topic: 'sinav-geri-kayma-tolerans',
    difficulty: 'zor',
    stem: 'Yokuş kalkışında geriye kaymanın sınav değerlendirmesindeki yeri en doğru nasıl açıklanır?',
    options: [
      'Yokuşta her türlü geri hareket serbesttir, hiç puan etkilemez',
      'Aracın geriye kayması yalnızca arkada araç varsa dikkate alınır',
      'Kalkışta motor teklerse geri kayma otomatik olarak görmezden gelinir',
      'Fark edilmeyecek kadar küçük, kontrollü ve tehlike doğurmayan bir kayma genelde tolere edilebilir; belirgin, sürüklenen ya da arkadaki mesafeyi tehdit eden geri kayma ise ağır hata olarak not edilir',
    ],
    answerIndex: 3,
    explanation:
      'Manuel araçta rampa kalkışında bir an tereddüt kaçınılmaz olabilir; bu yüzden gözle zor seçilen, kontrollü ve kimseyi tehlikeye atmayan çok küçük bir kayma çoğu zaman hoş görülür. Ancak aracın belirgin biçimde geriye sürüklenmesi, arkadaki araca ya da bordüre yaklaşması araç hâkimiyeti eksikliği sayılıp ağır hata olarak değerlendirilir. Bu yüzden kalkış el freni desteğiyle ya da hızlı ve dengeli debriyaj-gaz uyumuyla yapılır.',
    whyWrong: [
      'Geri kaymayı tümüyle serbest saymak, rampa kalkışının en kritik güvenlik ölçütünü yok saymaktır.',
      'Motor teklemesi ya da arkada araç olmaması, sürüklenen bir kaymanın hâkimiyet eksikliği olduğu gerçeğini değiştirmez.',
    ],
    objective:
      'Rampa kalkışında tolere edilen küçük kayma ile ağır hata sayılan sürüklenmeyi ayırt edebilmek.',
    tags: ['sinav-degerlendirme', 'rampa-kalkis', 'geri-kayma'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-605',
    subject: 'pratik',
    topic: 'sinav-serit-takibi',
    difficulty: 'kolay',
    stem: 'Sınav güzergâhında düz seyir sırasında şerit takibi bakımından adaydan beklenen nedir?',
    options: [
      'Aracın orta ve sağ şeritler arasında serbestçe salınması',
      'Sürekli şerit çizgisinin üzerinde giderek iki şeridi birden kullanma',
      'Aracın şeridin ortasında, çizgilere eşit uzaklıkta ve salınmadan tutulması; şerit değişimleri yalnızca gerektiğinde ve sinyalle yapılır',
      'Şeritten şeride sık geçerek trafiğe hâkim olunduğunu göstermek',
    ],
    answerIndex: 2,
    explanation:
      'Düzgün şerit takibi, aracın şeridin ortasında iki çizgiye de yaklaşık eşit uzaklıkta ve titremeden tutulmasıdır. Bu, bakışın yeterince ileriye taşındığının ve direksiyonun küçük düzeltmelerle kullanıldığının işaretidir. Şerit içinde sağa sola salınmak ya da gereksiz yere şerit değiştirmek, hem hâkimiyet eksikliği hem öngörüsüzlük olarak not edilir.',
    whyWrong: [
      'Şeritler arası salınma, bakışın araca fazla yakına düştüğünü ve direksiyonun geç düzeltildiğini gösterir.',
      'Gereksiz sık şerit değişimi hâkimiyet değil, plansızlık ve çevredekileri şaşırtma olarak değerlendirilir.',
    ],
    objective: 'Güzergâhta şeridin ortasında salınmadan seyir tutturmayı öğrenmek.',
    tags: ['sinav-degerlendirme', 'serit-takibi', 'arac-hakimiyeti'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-606',
    subject: 'pratik',
    topic: 'sinav-gorevli-iletisim',
    difficulty: 'kolay',
    stem: 'Sınav boyunca yanındaki görevliyle sohbet başlatmaya çalışan adayın bu davranışı neden sakıncalıdır?',
    options: [
      'Görevli konuşmayı kesinlikle yanıtlayamayacağı için',
      'Sohbet dikkati yoldan ve gözlemden koparır; ayrıca gelecek yön talimatının kaçırılmasına yol açabilir, oysa aday sürüşe ve komutları dinlemeye odaklanmalıdır',
      'Konuşmak yakıt tüketimini artırdığı için',
      'Görevlinin ismini öğrenmek yasak olduğu için',
    ],
    answerIndex: 1,
    explanation:
      'Sürüş, bölünmemiş dikkat ister; görevliyle sohbet gözü ve zihni yoldan alıp gözlem ile karar arasındaki bağı zayıflatır. Dahası konuşma sırasında gelecek bir yön talimatı ya da bir tehlike gözden kaçabilir. Aday nazik ama kısa yanıtlarla yetinip dikkatini sürüşe ve komutları dinlemeye ayırmalıdır.',
    whyWrong: [
      'Görevlinin yanıt verip vermemesi mesele değildir; asıl sorun adayın dikkatinin dağılmasıdır.',
      'Yakıt ya da isim öğrenme konuyla ilgisizdir; sakıncanın kaynağı dikkat kaybıdır.',
    ],
    objective: 'Sınavda dikkatin bölünmemesi için gereksiz sohbetten kaçınmayı kavramak.',
    tags: ['sinav-degerlendirme', 'dikkat', 'gorevli-iletisimi'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-607',
    subject: 'pratik',
    topic: 'sinav-bitis-park',
    difficulty: 'kolay',
    stem: 'Sınav güzergâhı tamamlanıp görevli "aracı buraya park edebilirsiniz" dediğinde bitiş manevrasının doğru sırası nedir?',
    options: [
      'Motoru hemen kapatıp sonra frene basmak',
      'Kemeri açıp aracı boşta bırakarak inmek',
      'El frenini çekmeden vitesi boşa alıp inmek',
      'Aracı güvenli ve düz biçimde durdurmak, vitesi boşa (ya da rampada uygun vitese) almak, el frenini çekmek, motoru kapatmak ve ancak sonra kemeri çözüp inmek',
    ],
    answerIndex: 3,
    explanation:
      'Bitiş de sürüşün bir parçasıdır ve düzeni görevli izler. Doğru sıra; aracı sarsıntısız durdurmak, el frenini çekip aracı emniyete almak, motoru kapatmak ve en son emniyet kemerini çözmektir. Rampada ise vites ve tekerlek yönü önlemleri de eklenir. Bu düzen, aracı tam güvenceye almadan araçtan kopmayı önler.',
    whyWrong: [
      'Motoru frene basmadan ya da aracı emniyete almadan kapatmak, düzensiz ve riskli bir bitiştir.',
      'El freni çekilmeden boşta bırakılan araç, özellikle en küçük eğimde bile kayabilir.',
    ],
    objective: 'Sınav sonu durma ve park sırasını doğru uygulayabilmek.',
    tags: ['sinav-arac-teslim', 'bitis-manevra', 'el-freni'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-608',
    subject: 'pratik',
    topic: 'sinav-hiz-limiti',
    difficulty: 'orta',
    stem: 'Sınav sırasında güzergâhtaki diğer araçlar hız sınırının üzerinde akıyorsa aday ne yapmalıdır?',
    options: [
      'Yürürlükteki hız sınırına ve yol koşullarına uygun hızda kalmalı; trafiğe ayak uydurmak için sınırı aşmamalıdır, akışa uymak sınırı çiğnemeyi haklı çıkarmaz',
      'Geride kalmamak için akan trafikle aynı hıza çıkmalı',
      'Diğerlerinden hızlı giderek kendine güvenini göstermeli',
      'Hız sınırını yalnızca radar varsa dikkate almalı',
    ],
    answerIndex: 0,
    explanation:
      'Hız sınırı, çevredeki araçların davranışına göre değişmeyen bir kuraldır; başkalarının aşması adaya aşma izni vermez. Aday yürürlükteki sınırın ve yol-görüş koşullarının elverdiği güvenli hızda kalmalı, gereksiz yavaşlıktan da kaçınıp akışı tıkamamalıdır. Sınırı aşmak, trafiğe uymak gerekçesiyle bile ağır hata sayılır.',
    whyWrong: [
      'Akan trafiğe uymak için sınırı aşmak, kuralı çiğneyen çoğunluğu örnek almaktır.',
      'Diğerlerini geçmeye çalışmak ya da sınırı yalnızca radara bağlamak, hız kuralının amacını yok sayar.',
    ],
    objective: 'Çevredeki akış ne olursa olsun hız sınırına uyma ilkesini benimsemek.',
    tags: ['sinav-degerlendirme', 'hiz-siniri', 'kural'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-609',
    subject: 'pratik',
    topic: 'sinav-dur-cizgisi',
    difficulty: 'orta',
    stem: 'Sınav güzergâhında "DUR" levhası bulunan bir kavşakta adayın doğru davranışı nedir?',
    options: [
      'Yol boşsa yavaşlayıp durmadan geçmek',
      'Yalnızca sağ-sol araç görürse durmak',
      'Dur çizgisinde tekerlekler tamamen durana kadar araç durdurulur, ardından sağ-sol güvenli görülünce hareket edilir; yuvarlanarak geçmek ağır hata sayılır',
      'Kornaya basıp yavaşça geçmek',
    ],
    answerIndex: 2,
    explanation:
      '"DUR" levhası, yol boş görünse bile tam duruşu zorunlu kılar; araç dur çizgisinde tekerlekler dönmeyi bırakana dek durdurulmalıdır. Sınavda "yuvarlanarak" ya da yavaşlayıp geçmek, kuralı çiğnemek olarak ağır hata biçiminde not edilir. Tam duruştan sonra sağ ve sol güvenli görülünce hareket edilir.',
    whyWrong: [
      'Yol boş diye durmadan geçmek, levhanın kesin duruş talebini görmezden gelmektir.',
      'Sadece araç görünce durmak ya da kornayla geçmek, "DUR" kuralının tam duruş şartını karşılamaz.',
    ],
    objective: 'DUR levhasında tam duruş yükümlülüğünü sınav bağlamında uygulayabilmek.',
    tags: ['sinav-degerlendirme', 'dur-levhasi', 'tam-durus'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-610',
    subject: 'pratik',
    topic: 'sinav-ayna-tarama',
    difficulty: 'kolay',
    stem: 'Sınavda ayna kontrollerinin yalnızca göz ucuyla değil, hafif bir baş hareketiyle yapılması neden önerilir?',
    options: [
      'Baş hareketi boynu dinlendirdiği için',
      'Ayna kontrolünün gerçekten yapıldığı görevli tarafından görülebilsin ve aday da geniş açıyı daha iyi tarayabilsin diye; sadece göz ucuyla bakış hem yetersiz kalır hem fark edilmez',
      'Baş çevirmek aracı otomatik yavaşlattığı için',
      'Aynalar ancak baş hareketiyle çalıştığı için',
    ],
    answerIndex: 1,
    explanation:
      'Şerit değişimi, dönüş ve fren öncesi yapılan ayna kontrolü, belirgin bir baş hareketiyle yapıldığında hem daha geniş açı taranır hem de görevli bu gözlemin gerçekten yapıldığını görür. Yalnızca göz ucuyla atılan bakış çoğu zaman yetersizdir ve dışarıdan fark edilmez. Gözlem yapıldığı hâlde belli edilmezse, yapılmadı gibi değerlendirilebilir.',
    whyWrong: [
      'Amaç boynu dinlendirmek ya da aracı yavaşlatmak değil, taramayı hem etkili hem görünür kılmaktır.',
      'Aynalar baş hareketine bağlı çalışmaz; baş hareketi taramanın kapsamını ve görünürlüğünü artırır.',
    ],
    objective: 'Ayna kontrolünü etkili ve görünür biçimde yapmanın önemini kavramak.',
    tags: ['sinav-degerlendirme', 'ayna-kontrol', 'gozlem'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-611',
    subject: 'pratik',
    topic: 'sinav-komut-yanlis-yon',
    difficulty: 'zor',
    stem: 'Görevlinin dönüş komutunu yanlış yöne yorumlayıp dönmeye hazırlanan aday, hatasını son anda fark ederse ne yapmalıdır?',
    options: [
      'Fark ettiği anda direksiyonu sert kırıp doğru yöne ani manevra yapmak',
      'Hiç aldırmadan yanlış yöne dönüşü tamamlamak',
      'Aniden durup geri geri gelerek doğru sokağa girmek',
      'Şeridini ve hızını korumak, güvenli değilse yanlış dönüşü zorlamamak; durumu kısaca görevliye belirtip bir sonraki uygun yerden güvenle düzeltmek, ani ve tehlikeli düzeltmeden kaçınmaktır',
    ],
    answerIndex: 3,
    explanation:
      'Bir yön hatasını düzeltmek için yapılan ani direksiyon ya da ani duruş, arkadan gelen ve yandaki trafiği hazırlıksız yakalayarak asıl tehlikeyi yaratır. Doğru davranış, güvenliği bozacak bir düzeltmeyi zorlamamak, şeridi korumak ve durumu görevliye kısaca söyleyip ilk uygun ve güvenli noktadan yolu düzeltmektir. Sınavda tek başına bir yön şaşırması, güvenli sürüşten daha az önemlidir.',
    whyWrong: [
      'Son anda sert kırış ya da ani duruş, küçük bir yön hatasını ciddi bir kaza riskine çevirir.',
      'Trafikte geri gelmek çoğu yerde yasak ve tehlikelidir; yanlış dönüşü inatla tamamlamak da güvenliği bozabilir.',
    ],
    objective:
      'Yön hatasını ani manevrayla değil, güvenli ve kademeli düzeltmeyle çözmeyi öğrenmek.',
    tags: ['sinav-guzergah-komutlari', 'yon-hatasi', 'guvenli-duzeltme'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-612',
    subject: 'pratik',
    topic: 'sinav-yaya-onceligi',
    difficulty: 'orta',
    stem: 'Sınav güzergâhında yaya geçidinde bekleyen ya da geçmeye başlayan yayaya yol vermemek nasıl değerlendirilir?',
    options: [
      'Yaya kendi dikkat etmesi gerektiği için önemsiz sayılır',
      'Yalnızca yayaya çarpılırsa dikkate alınır',
      'Yaya önceliğinin çiğnenmesi güvenlik açısından ağır (elemeli) hata olarak değerlendirilir; sürücü geçide yaklaşırken hızını azaltıp gerekiyorsa durup yol vermelidir',
      'Sadece okul bölgesindeki geçitlerde önemlidir',
    ],
    answerIndex: 2,
    explanation:
      'Yaya geçidinde öncelik yayanındır ve bu önceliğin çiğnenmesi doğrudan can güvenliğini ilgilendirir; bu yüzden sınavda ağır, çoğunlukla elemeli bir hata olarak değerlendirilir. Aday geçide yaklaşırken hızını erkenden düşürmeli, yaya varsa durup güvenle geçmesini beklemelidir. Yalnızca çarpma anını ölçüt saymak, önceliğin amacını yok saymaktır.',
    whyWrong: [
      'Yayanın dikkatli olmasını beklemek, sürücüye tanınan yol verme yükümlülüğünü ortadan kaldırmaz.',
      'Riski çarpmaya ya da tek bir bölgeye indirgemek, yaya önceliği kuralının kapsamını daraltır.',
    ],
    objective: 'Yaya geçidinde yol vermeme davranışının ağır hata olduğunu kavramak.',
    tags: ['sinav-degerlendirme', 'yaya-onceligi', 'elemeli-hata'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-613',
    subject: 'pratik',
    topic: 'sinav-vites-hiz-uyumu',
    difficulty: 'kolay',
    stem: 'Sınavda düşük hızda yüksek viteste (örneğin 20 km/s hızda dördüncü vitesle) ilerleyip motoru zorlayan aday nasıl değerlendirilir?',
    options: [
      'Vites ile hız uyumsuzluğu, araç hâkimiyeti ve teknik zafiyet olarak not edilir; hıza uygun vitese inilmesi, motorun ne zorlanması ne de aşırı devirde çalışması beklenir',
      'Yakıt tasarrufu sağladığı için olumlu puan alır',
      'Vites seçimi sınavda hiç değerlendirilmez',
      'Yalnızca motor stop ederse dikkate alınır',
    ],
    answerIndex: 0,
    explanation:
      'Hıza uygun vites seçmek, aracı doğru kullanmanın temel göstergesidir. Düşük hızda yüksek viteste gitmek motoru tıkır tıkır zorlayıp titreştirir ve gaza gerektiği anda ani yanıt alınamaz; bu, teknik hâkimiyet eksikliği olarak not edilir. Aday hız düştükçe uygun vitese inmeli, motoru ne boğmalı ne de gereksiz yüksek devirde tutmalıdır.',
    whyWrong: [
      'Motoru zorlamak yakıt tasarrufu değil, düzensiz ve verimsiz sürüş anlamına gelir.',
      'Vites seçimi sürüş becerisinin parçasıdır; yalnızca motor stopuyla sınırlı değildir.',
    ],
    objective: 'Hız ile vites uyumunun sınav değerlendirmesindeki yerini bilmek.',
    tags: ['sinav-degerlendirme', 'vites-secimi', 'hiz-uyumu'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-614',
    subject: 'pratik',
    topic: 'sinav-kavsak-gozlem',
    difficulty: 'orta',
    stem: 'Sınavda kavşağa yaklaşan aday, yalnızca görevlinin verdiği yön komutuna odaklanıp çevre gözlemini ihmal ederse ne olur?',
    options: [
      'Komuta odaklanmak her zaman en doğru davranıştır, sorun olmaz',
      'Komuta uymak yeterli görülür, gözlem gerekmez',
      'Görevli komutu yerine getirmek kadar sağ-sol-yaya gözlemini de bekler; komuta kilitlenip taramayı atlamak, yol verme ve güvenlik hatalarına yol açarak olumsuz değerlendirilir',
      'Kavşakta gözlem yalnızca ışık kırmızıysa gereklidir',
    ],
    answerIndex: 2,
    explanation:
      'Yön komutu adaya nereye gideceğini söyler; ama kavşağın güvenli geçilmesi adayın kendi gözlemine bağlıdır. Yalnızca komuta kilitlenip sağdan geleni, karşıdan dönüşü ve yayayı taramayı atlamak, yol verme ve güvenlik hatalarına kapı aralar. Görevli, komuta uyulmasını da doğru çevre taramasının yapılmasını da birlikte değerlendirir.',
    whyWrong: [
      'Komut yalnızca yönü belirler; kavşağın güvenliğini sağlayan adayın gözlemidir.',
      'Kavşak gözlemi ışık durumundan bağımsız her zaman gereklidir; sadece kırmızıya bağlanamaz.',
    ],
    objective: 'Yön komutu ile çevre gözlemini birlikte yürütmenin gerekliliğini kavramak.',
    tags: ['sinav-degerlendirme', 'kavsak-gozlem', 'yol-verme'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-615',
    subject: 'pratik',
    topic: 'sinav-park-duzeltme',
    difficulty: 'orta',
    stem: 'Sınavın park bölümünde aday, aracı cebe ilk hamlede tam oturtamayıp bir düzeltme hamlesi yaparsa bu nasıl değerlendirilir?',
    options: [
      'Her düzeltme hamlesi otomatik olarak elemeli hata sayılır',
      'Kontrollü ve güvenli yapılan makul sayıda düzeltme kabul edilir; asıl olumsuzluk çok sayıda deneme, bordüre/dubaya çarpma ya da aracı çarpık ve tehlikeli bırakmaktır',
      'Park sırasında hiçbir düzeltmeye izin verilmez',
      'Düzeltme yapmak yerine aracı olduğu gibi bırakmak daha iyidir',
    ],
    answerIndex: 1,
    explanation:
      'Park manevrasında araç ilk hamlede tam oturmayabilir; kontrollü ve güvenli yapılan makul bir düzeltme hâkimiyet göstergesidir, ceza konusu değildir. Değerlendirmeyi olumsuza çeviren, çok sayıda tekrarlı deneme, bordüre veya dubaya temas ve aracın çarpık, taşan ya da tehlikeli konumda bırakılmasıdır. Yani ölçüt hamle sayısından çok, sonucun güvenli ve düzgün olmasıdır.',
    whyWrong: [
      'Tek bir düzeltmeyi bile elemeli saymak, gerçekçi park pratiğine aykırıdır.',
      'Aracı çarpık ve düzeltmeden bırakmak, hatalı park olarak zaten olumsuz değerlendirilir.',
    ],
    objective: 'Park manevrasında makul düzeltme ile hatalı parkı ayırt edebilmek.',
    tags: ['sinav-degerlendirme', 'park-manevra', 'duzeltme-hamlesi'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-616',
    subject: 'pratik',
    topic: 'viraj-geometri',
    difficulty: 'orta',
    stem: 'Görüşü kısıtlı bir dönemece güvenli girişte "geniş gir, dar çık" ilkesi ne anlama gelir?',
    options: [
      'Viraja şeridin dış tarafından girip görüş açısını uzatmak, tepe/apeks noktasına doğru içe yaklaşmak ve çıkışta yeniden şerit içinde konumlanmak; bu, dönüşü yumuşatır ve daha erken görmeyi sağlar',
      'Viraja tam gaz girip fren yaparak dar çıkmak',
      'Virajı her zaman karşı şeridi kullanarak kesmek',
      'Viraj boyunca sürekli iç şeride yaslanıp çıkışta dışa savrulmak',
    ],
    answerIndex: 0,
    explanation:
      'Dönemece dış taraftan girmek, sürücünün virajın devamını daha erken görmesini sağlar ve dönüş yayını genişleterek direksiyonu yumuşatır. Araç kademeli olarak iç kısma (apeks) yaklaşır, ardından çıkışta yeniden kendi şeridinin içine yerleşir. Bütün bu hat kendi şeridi içinde kalınarak kurulur; amaç karşı şeride taşmak değil, görüşü ve dengeyi artırmaktır.',
    whyWrong: [
      'Tam gazla girip virajda fren yapmak, savrulma riskini artıran tam tersi bir tekniktir.',
      'Karşı şeridi kullanmak ya da iç şeride sürekli yaslanmak, hem kural ihlali hem denge kaybıdır.',
    ],
    objective: 'Dönemeçte geniş giriş-dar çıkış hattını şerit içinde uygulayabilmek.',
    tags: ['viraj-teknigi', 'gorus-mesafesi', 'donemec'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-617',
    subject: 'pratik',
    topic: 'kamyon-arkasi-takip',
    difficulty: 'zor',
    stem: 'Otoyolda büyük bir kamyonun hemen arkasına sokulup onun oluşturduğu rüzgâr boşluğunda (hava perdesinde) sürmek neden tehlikelidir?',
    options: [
      'Yakıt tüketimini artırdığı için',
      'Kamyonun lastikleri daha çok ısındığı için',
      'Bu kadar yakın takipte önü göremezsiniz, kamyon ani frende sizin durma payınızı bırakmaz ve savrulan bir taş ya da patlayan lastik parçası doğrudan sizi bulur; kazanılan yakıt, kaybedilen güvenlik payının yanında hiçtir',
      'Kamyon şoförü sizi hiç göremediği için yalnızca korna gerekir',
    ],
    answerIndex: 2,
    explanation:
      'Büyük aracın hemen arkasındaki rüzgâr boşluğu hava direncini biraz azaltsa da, bu yakınlıkta öndeki aracın ötesini görmek imkânsızdır ve kamyon aniden yavaşladığında durma mesafeniz kalmaz. Ayrıca kamyonun lastiğinden fırlayan taş ya da patlayan sırt parçası doğrudan camınıza gelir. Kazanılan cüzi yakıt, feda edilen görüş ve fren payının yanında anlamsızdır; takip mesafesi büyük araçlarda daha da açılmalıdır.',
    whyWrong: [
      'Asıl tehlike yakıt ya da lastik ısınması değil, yok olan görüş ve fren mesafesidir.',
      'Kör noktada kalmak sorunun bir parçasıdır ama çözüm korna değil, mesafeyi açmaktır.',
    ],
    objective: 'Büyük araç arkasında yakın takibin görüş ve fren risklerini kavramak.',
    tags: ['takip-mesafesi', 'buyuk-arac', 'gorus'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-618',
    subject: 'pratik',
    topic: 'park-arac-kapi-riski',
    difficulty: 'orta',
    stem: 'Yol kenarına dizili park etmiş araçların ya da yolcu indiren bir aracın yanından geçerken hangi ani tehlikeye karşı hazırlıklı olunmalıdır?',
    options: [
      'Araçların alarmının çalması',
      'Araçların üzerine kar yağması',
      'Park etmiş araçların farlarının yanması',
      'Bir kapının aniden açılması ya da araçların arasından bir yolcunun/yayanın çıkması; bu yüzden park sırasına yan mesafe bırakılır ve hız azaltılarak açılabilecek kapı payı korunur',
    ],
    answerIndex: 3,
    explanation:
      'Park etmiş araçların yanı, en sık kapı açılması ve araç arasından çıkan yaya sürprizlerinin yaşandığı yerdir; inen bir yolcu ya da bisikletli kapısını kontrol etmeden açabilir. Bu şeridin yanından geçerken hız düşürülür ve mümkünse bir kapı genişliği kadar yan mesafe bırakılır. Böylece aniden açılan kapı ya da çıkan yaya için tepki payı korunur.',
    whyWrong: [
      'Alarm, far ya da kar birikmesi burada sürücüyü tehdit eden ani hareketler değildir.',
      'Asıl risk aniden açılan kapı ve araç arasından çıkan yaya olduğu için, hazırlık yan mesafe ve düşük hızdır.',
    ],
    objective: 'Park sırası yanından geçerken kapı ve yaya sürprizine karşı önlem almayı öğrenmek.',
    tags: ['park-arac', 'ani-kapi', 'yan-mesafe'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-619',
    subject: 'pratik',
    topic: 'bisikletli-sollama-hiz',
    difficulty: 'orta',
    stem: 'Bir bisikletliyi sollarken yan mesafe kadar hız da neden önemlidir?',
    options: [
      'Yüksek hızla ve yakından geçen aracın yarattığı ani hava basıncı bisikletliyi sarsıp dengesini bozabilir; hız düşürülüp geniş yan mesafe bırakıldığında bu emme-itme etkisi azalır',
      'Hızlı geçmek bisikletliyi daha çabuk geride bırakıp daha güvenli olur',
      'Bisikletlinin hızını ölçmek için yavaşlamak gerekir',
      'Hızın bisikletliyle hiçbir ilgisi yoktur, yalnızca mesafe önemlidir',
    ],
    answerIndex: 0,
    explanation:
      'Yakından ve hızlı geçen bir araç, önce bir hava dalgasıyla iter sonra ardındaki emişle çeker; bu ani basınç değişimi zaten dar bir denge üzerindeki bisikletliyi savurabilir. Hız düşürülüp geniş yan mesafe bırakıldığında bu emme-itme etkisi belirgin biçimde azalır. Bu yüzden sollama hem yavaşlayarak hem de yeterli açıklık bırakılarak yapılır.',
    whyWrong: [
      'Hızlı geçmek maruz kalma süresini kısaltmaz; tam tersine hava basıncı etkisini şiddetlendirir.',
      'Bisikletlinin hızını ölçmek gibi bir gereklilik yoktur; mesele denge ve güvenli açıklıktır.',
    ],
    objective: 'Bisikletli sollamada hız düşürmenin hava basıncı etkisini azalttığını kavramak.',
    tags: ['bisikletli', 'sollama', 'yan-mesafe'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-620',
    subject: 'pratik',
    topic: 'karsidan-sollayan-arac',
    difficulty: 'zor',
    stem: 'Çift yönlü bir yolda karşıdan gelen bir aracın sollamaya çıkıp sizin şeridinize girdiğini gördüğünüzde en doğru davranış nedir?',
    options: [
      'Farları yakıp hızlanarak kafa kafaya gelmeden önce onu geçmeye çalışmak',
      'Şeridinizi koruyup hiç yavaşlamamak, sollama yapanın geri dönmesini beklemek',
      'Kornaya basıp olduğunuz yerde durmak ve gözleri kapatmak',
      'Hızınızı azaltıp mümkün olduğunca sağa, banket ya da yol kenarına yanaşmak; böylece karşı araca dönüş için yer açar ve olası çarpışmanın şiddetini düşürürsünüz',
    ],
    answerIndex: 3,
    explanation:
      'Karşıdan sollamaya çıkıp şeridinize giren araç kafa kafaya çarpışma riski yaratır; bu anda amaç ona kendi şeridine dönebileceği yeri ve zamanı açmaktır. Doğru davranış hızı kesip mümkün olduğunca sağa, gerekirse bankete yanaşmaktır; hem ona boşluk açılır hem olası temasın kapanma hızı düşer. Hızlanarak yarışmak ya da hiç önlem almamak, çarpışmayı neredeyse kaçınılmaz kılar.',
    whyWrong: [
      'Hızlanmak kapanma hızını artırır ve iki aracı daha sert bir çarpışmaya taşır.',
      'Şeridi koruyup hiç yavaşlamamak ya da olduğu yerde donup kalmak, karşı araca kaçış alanı bırakmaz.',
    ],
    objective:
      'Karşıdan gelen sollama tehlikesinde sağa yanaşıp yavaşlamayı refleks hâline getirmek.',
    tags: ['karsi-yon', 'sollama-tehlikesi', 'kacinma'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-621',
    subject: 'pratik',
    topic: 'arkadan-hizli-araca-yol',
    difficulty: 'kolay',
    stem: 'Bölünmüş yolda arkanızdan sizden hızlı gelen bir araç sizi geçmek istiyorsa doğru davranış nedir?',
    options: [
      'Hızı biraz artırıp geçmesine izin vermemek',
      'Güvenliyse sağ şeride geçerek ya da sağda kalarak yol vermek; sol şeridi geçiş için boşaltmak, inatla önünde yavaş gitmemek',
      'Fren yapıp arkadaki aracı uyarmak',
      'Sola geçip önünü kesmek',
    ],
    answerIndex: 1,
    explanation:
      'Sol şeritler sollama içindir; arkadan gelen daha hızlı araç geçmek istediğinde ona yol açmak hem kural hem güvenlik gereğidir. Güvenli olduğunda sağ şeride geçilir ya da zaten sağda kalınır ve sol şerit boşaltılır. Önünde inatla yavaş gitmek ya da fren yaparak "ders vermeye" çalışmak, öfke ve tehlikeli manevraları körükler.',
    whyWrong: [
      'Hızlanıp geçişi engellemek, gereksiz gerginlik ve riskli sollama denemelerine yol açar.',
      'Fren yaparak uyarmak ya da önünü kesmek, arkadan çarpma ve çatışma riskini büyütür.',
    ],
    objective: 'Arkadan gelen hızlı araca güvenle yol verme davranışını benimsemek.',
    tags: ['serit-disiplini', 'yol-verme', 'sag-serit'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-622',
    subject: 'pratik',
    topic: 'motosiklet-serit-arasi',
    difficulty: 'orta',
    stem: 'Yoğun şehir trafiğinde şerit değiştirecek sürücü, motosikletlerin şeritler arasından ilerleyebildiğini neden özellikle hesaba katmalıdır?',
    options: [
      'Motosiklet dar olduğundan araç sıraları arasından hızla yaklaşabilir ve son anda kör noktaya girebilir; bu yüzden şerit değiştirmeden önce ayna kontrolüne ek olarak omuz üzerinden bakış şarttır',
      'Motosikletler sadece en sağ şeritte gidebildiği için',
      'Motosikletler trafik kurallarına tabi olmadığı için',
      'Motosikletlerin farı gündüz görünmediği için',
    ],
    answerIndex: 0,
    explanation:
      'Motosiklet dar profili sayesinde duran ya da yavaş araç sıralarının arasından beklenmedik biçimde hızla yaklaşabilir; bu, aynada geç görülür ve kör noktaya son anda girebilir. Bu yüzden yoğun trafikte şerit değiştirmeden önce ayna kontrolü tek başına yeterli değildir; mutlaka omuz üzerinden dönülüp bakılmalıdır. Motosikletlinin varlığı görülmeden yapılan şerit değişimi, en sık motosiklet kazalarından biridir.',
    whyWrong: [
      'Motosikletler yalnız sağ şeritle sınırlı değildir; şeritler arasından ilerleyebilirler.',
      'Motosikletler de kurallara tabidir ve farları görünür; sorun onların değil, sürücünün kör nokta ihmalidir.',
    ],
    objective:
      'Şerit değişiminde motosikletlerin şerit arası ilerlemesini öngörüp omuz kontrolü yapmayı öğrenmek.',
    tags: ['motosiklet', 'kor-nokta', 'serit-degistirme'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-623',
    subject: 'pratik',
    topic: 'engebe-capraz-gecis',
    difficulty: 'zor',
    stem: 'Yol kenarındaki keskin bir seti ya da tek taraflı çıkıntıyı (örneğin garaj girişindeki yüksek bordür geçişini) aşarken hangi teknik jant ve lastiği en iyi korur?',
    options: [
      'Engebeye mümkün olduğunca dik yerine hafif çapraz (açılı) yaklaşıp tekerlekleri sırayla, düşük hızda ve engel anında frenden ayağı çekerek geçirmek; böylece darbe iki tekerleğe aynı anda binmez ve yumuşar',
      'Sete tam gazla ve iki tekerlekle aynı anda çarparak hızla aşmak',
      'Set üzerinde frene basılı tutarak yavaş yavaş sürtmek',
      'Tekerleklerden yalnızca birini havaya kaldırıp diğerini sürterek geçmek',
    ],
    answerIndex: 0,
    explanation:
      'Keskin bir sete iki ön tekerlek aynı anda dik olarak çarparsa darbe ani ve tek yükte gelir; jant ezilmesi ve lastik patlaması riski artar. Hafif açılı yaklaşıldığında tekerlekler seti sırayla aşar, darbe zamana yayılır ve süspansiyon her tekerleği ayrı ayrı yumuşatır. Hız düşük tutulur ve engel anında frenden ayak çekilir; böylece çökmüş süspansiyon yerine açık süspansiyonla temas edilir.',
    whyWrong: [
      'Tam gazla ve iki tekerlekle aynı anda çarpmak, darbeyi en sert ve en yıkıcı hâline getirir.',
      'Set üzerinde fren basılı sürtmek ya da bir tekerleği havada tutmak, hem aracı hem lastiği zorlar ve dengeyi bozar.',
    ],
    objective:
      'Keskin engebeyi açılı, düşük hızlı ve frensiz geçerek jant-lastik hasarını azaltmayı öğrenmek.',
    tags: ['engebe', 'jant-koruma', 'gecis-teknigi'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-624',
    subject: 'pratik',
    topic: 'cukur-kacinma',
    difficulty: 'orta',
    stem: 'İleride yolda derin bir çukuru geç fark eden sürücü, kaçınmak için neden ani direksiyon yerine önce hızı düşürmeyi düşünmelidir?',
    options: [
      'Ani direksiyon her zaman en hızlı çözümdür',
      'Fren yapmak lastiği patlatacağı için yalnızca direksiyon kullanılmalıdır',
      'Çukurlar zaten araca zarar vermez',
      'Yüksek hızda yapılan ani direksiyon, aracı karşı şeride ya da yan şeritteki araca savurabilir; hız düşürüldüğünde hem çukurun vereceği darbe azalır hem güvenli bir yön düzeltmesi için zaman ve tutunma payı kalır',
    ],
    answerIndex: 3,
    explanation:
      'Bir çukuru son anda ani direksiyonla atlatmaya çalışmak, aracı komşu şeride ya da karşı yöne savurarak çukurdan daha büyük bir tehlike doğurabilir. Önce hız düşürüldüğünde hem çukurun darbesi hafifler hem de gerekiyorsa küçük ve kontrollü bir yön düzeltmesi için zaman ile lastik tutunma payı kalır. Kaçınılamıyorsa direksiyon düz tutulup çukur yavaş hızda göğüslenir; bu, ani savrulmadan daha güvenlidir.',
    whyWrong: [
      'Ani direksiyon en hızlı görünse de en riskli seçenektir; kontrolü kolayca yitirtir.',
      'Çukurlar jant, lastik ve süspansiyona zarar verebilir; fren yapmak da tek başına lastiği patlatmaz.',
    ],
    objective: 'Çukura karşı ani direksiyon yerine önce hız düşürmeyi tercih etmeyi öğrenmek.',
    tags: ['cukur', 'hiz-dusurme', 'kacinma'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-625',
    subject: 'pratik',
    topic: 'tunelde-serit-degistirme',
    difficulty: 'kolay',
    stem: 'Tünel içinde seyrederken şerit değiştirme ve sollama konusunda doğru davranış nedir?',
    options: [
      'Tünelde dilediğince şerit değiştirilebilir',
      'Tünelde yalnızca sağdan sollama yapılır',
      'Aksi bir işaretleme yoksa tünel içinde şerit değiştirmekten ve sollamadan kaçınılır; şerit korunur, öndeki araçla güvenli mesafe bırakılıp sabit hızla ilerlenir',
      'Tünelde farlar kapatılıp hızlanılır',
    ],
    answerIndex: 2,
    explanation:
      'Tüneller genellikle dar, kaçış alanı sınırlı ve şerit değişimine elverişsiz kapalı kesimlerdir; bu yüzden aksi belirtilmedikçe içeride şerit değiştirmek ve sollamak sakıncalıdır. Doğrusu şeridi korumak, öndeki araçla güvenli mesafe bırakıp sabit hızla ve farlar yanık biçimde ilerlemektir. Şerit disiplini, bir sorun anında da trafiğin düzenli akmasını sağlar.',
    whyWrong: [
      'Serbestçe şerit değiştirmek ya da sağdan sollamak, tünelin dar ve kapalı yapısında tehlike üretir.',
      'Tünelde farlar açık tutulur; kapatıp hızlanmak görünürlüğü ve güvenliği birlikte bozar.',
    ],
    objective: 'Tünel içinde şerit koruma ve sollamama kuralını uygulayabilmek.',
    tags: ['tunel', 'serit-disiplini', 'sollama'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-626',
    subject: 'pratik',
    topic: 'golgeli-viraj-buz',
    difficulty: 'zor',
    stem: 'Soğuk bir günde yolun büyük bölümü kuru olsa bile, ağaçlık ya da yüksek duvar gölgesinde kalan virajlara girerken neden ekstra dikkatli olunmalıdır?',
    options: [
      'Gölgeli kesimlerde far otomatik yandığı için',
      'Gölgeli bölümler güneş görmediğinden zemindeki nem ya da kırağı buza dönüşüp gizli bir buzlanma oluşturabilir; kuru yola alışmış sürücü, viraj ortasında beklenmedik kayganlıkla karşılaşabilir',
      'Gölgede yol her zaman daha pürüzlü olduğu için',
      'Gölgeli virajlarda rüzgâr her zaman daha güçlü olduğu için',
    ],
    answerIndex: 1,
    explanation:
      'Güneş gören kesimler kurusa da, gün boyu gölgede kalan viraj ve orman altı bölümler nemi ve kırağıyı koruyup ince, çoğu zaman fark edilmeyen bir buz tabakası oluşturabilir. Kuru asfalta güvenip virajı hızlı alan sürücü, tam dönüş ortasında ani tutunma kaybıyla karşılaşır. Bu yüzden gölgeli virajlara girmeden hız düşürülür, viraj içinde ani fren ve direksiyondan kaçınılıp sabit gazla geçilir.',
    whyWrong: [
      'Farın yanması ya da yolun pürüzü, buradaki asıl tehlike olan gizli buzlanmayı açıklamaz.',
      'Rüzgâr her gölgeli virajda güçlü değildir; belirleyici etken güneş görmeyen zeminin buz tutmasıdır.',
    ],
    objective: 'Gölgeli viraj ve kesimlerdeki gizli buzlanma riskini öngörüp hız ayarlamak.',
    tags: ['buzlanma', 'golge', 'viraj'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-627',
    subject: 'pratik',
    topic: 'cizgisi-silik-yol',
    difficulty: 'kolay',
    stem: 'Şerit çizgileri silinmiş ya da hiç bulunmayan çift yönlü bir yolda sürücü aracını nasıl konumlandırmalıdır?',
    options: [
      'Yolun sağ yarısında, kendi tarafında kalarak; karşıdan araç geldiğinde biraz daha sağa yanaşıp yeterli açıklık bırakarak ve gerektiğinde hızı azaltarak ilerlemelidir',
      'Yolun tam ortasından giderek karşıdan gelene göre karar vermelidir',
      'Sol yarıyı kullanıp karşı aracı sağdan geçmelidir',
      'Çizgi olmadığından konumun bir önemi kalmaz, dilediği yerden gidebilir',
    ],
    answerIndex: 0,
    explanation:
      'Çizgi olmasa da yolun mantığı değişmez: sürücü kendi sağ yarısında kalır ve karşıdan gelenle güvenli açıklığı korur. Karşı araç yaklaştığında biraz daha sağa yanaşılır, görüş ya da genişlik dardır diye hız azaltılır. Yolun ortasından gitmek ya da sol yarıyı kullanmak, çizgi yokluğunu bir serbestlik sanmaktır ve kafa kafaya karşılaşma riskini doğurur.',
    whyWrong: [
      'Ortadan gitmek, karşıdan araç çıktığında iki tarafı da hazırlıksız yakalar.',
      'Sol yarıyı kullanmak ya da konumu önemsiz saymak, çift yönlü yolun temel güvenlik ilkesini çiğner.',
    ],
    objective: 'Çizgisiz yolda sağ yarıda kalarak güvenli konumlanmayı öğrenmek.',
    tags: ['serit-yok', 'yol-konumu', 'karsi-yon'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-628',
    subject: 'pratik',
    topic: 'karli-yokus-kalkis',
    difficulty: 'orta',
    stem: 'Karlı bir yokuşta durduktan sonra yeniden kalkarken patinajı önlemek için doğru yaklaşım nedir?',
    options: [
      'Bol gaz verip tekerleği döndürerek karı ezmeye çalışmak',
      'Gazı ölçülü ve yumuşak vermek, debriyajı sabırla kavratmak, mümkünse durmadan ağır tempoda süreklilik korumak; çünkü karlı yokuşta bir kez durup patinaja girmek yeniden kalkışı çok zorlaştırır',
      'Debriyajı aniden bırakıp motoru zorlamak',
      'El frenini çekili bırakıp gaza yüklenmek',
    ],
    answerIndex: 1,
    explanation:
      'Karlı yokuşun en zor anı, tutunmanın zaten düşük olduğu yerde yeniden kalkıştır; bu yüzden en iyisi mümkünse hiç durmadan ağır ve düzenli bir tempoyla ilerlemeyi sürdürmektir. Durmak zorunlu ise kalkışta gaz ölçülü ve yumuşak verilir, debriyaj sabırla kavratılır; ani güç tekerleği boşa döndürüp patinaja sokar. Bir kez patinaja girildiğinde lastik karı cilalar ve kalkış iyice imkânsızlaşır.',
    whyWrong: [
      'Bol gaz karı ezmez; tekerleği boşa döndürüp altını buzlaştırarak tutunmayı büsbütün bitirir.',
      'Debriyajı fırlatmak ya da el freni çekiliyken gaza yüklenmek, kalkışı hem sarsıntılı hem tutunmasız yapar.',
    ],
    objective: 'Karlı yokuşta yumuşak güçle ve süreklilikle patinajsız kalkışı öğrenmek.',
    tags: ['kar', 'yokus-kalkis', 'patinaj'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-629',
    subject: 'pratik',
    topic: 'zincir-takma-yeri',
    difficulty: 'kolay',
    stem: 'Kar zincirini takmak için durulacak yerin seçiminde en doğru davranış hangisidir?',
    options: [
      'Zincir viraj içinde, hızlıca takılmalıdır',
      'Zincir yalnızca yol ortasında takılabilir',
      'Mümkün olduğunca düz, güvenli ve trafiği aksatmayan bir yere (geniş banket, park cebi) çekilip dörtlü flaşör yakılarak takılır; dar, dönemeç ya da görüşün kısıtlı olduğu noktalarda durulmaz',
      'Zincir hareket hâlindeyken takılmalıdır',
    ],
    answerIndex: 2,
    explanation:
      'Zincir takmak zaman alır ve sürücü araç dışında, yol seviyesinde çalışır; bu yüzden durulacak yerin güvenliği hayatidir. Düz, geniş ve trafiği aksatmayan bir banket ya da park cebi seçilir, dörtlü flaşör yakılır ve gerekiyorsa reflektör konur. Dönemeç, tepe altı ya da dar kesimde durmak, arkadan gelen için görülmeyen bir engel yaratır.',
    whyWrong: [
      'Viraj içi ya da yol ortası, hem çalışanı hem trafiği tehlikeye atan en riskli yerlerdir.',
      'Zincir araç dururken takılır; hareket hâlinde takmak diye bir yöntem yoktur.',
    ],
    objective: 'Kar zinciri takmak için güvenli durak yeri seçmeyi öğrenmek.',
    tags: ['kar-zinciri', 'guvenli-durak', 'kis-surusu'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-630',
    subject: 'pratik',
    topic: 'cekilen-arac-kontak',
    difficulty: 'orta',
    stem: 'Halatla çekilen bir aracın kontağıyla ilgili en önemli nokta nedir?',
    options: [
      'Kontak tümüyle kapatılmalı ve anahtar çıkarılmalıdır; direksiyon zaten kilitli kaldığından güvenli olur',
      'Kontak marş konumunda bırakılıp motor sürekli çalıştırılmaya çalışılmalıdır',
      'Kontağın açık ya da kapalı olması hiç fark etmez',
      'Kontak açık (direksiyon kilidi çözülmüş) konumda tutulmalıdır; kontak kapatılıp anahtar çıkarılırsa direksiyon kilitlenir ve çekilen araç virajda yön veremez',
    ],
    answerIndex: 3,
    explanation:
      'Çoğu araçta kontak kapatılıp anahtar çıkarıldığında direksiyon kilidi devreye girer ve simit dönmez; çekilen araç virajda yönlendirilemez hâle gelir. Bu yüzden çekilen aracın kontağı, direksiyon kilidini açan konumda (anahtar takılı, kontak açık) tutulur; böylece hem direksiyon döner hem fren ve sinyal beslenir. Ayrıca çekme halatına görünür bir işaret bağlanır ve iki araç arası mesafe kısa ve düzenli tutulur.',
    whyWrong: [
      'Anahtarı çıkarmak direksiyonu kilitler; bu, çekilen aracı virajda yönsüz bırakır.',
      'Kontağın durumu kritik bir güvenlik konusudur; marş konumunda tutup motoru zorlamak da yanlıştır.',
    ],
    objective:
      'Çekilen araçta kontağın açık tutulmasının direksiyon kilidiyle ilişkisini kavramak.',
    tags: ['arac-cekme', 'direksiyon-kilidi', 'kontak'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-631',
    subject: 'pratik',
    topic: 'yol-yuzeyi-okuma',
    difficulty: 'orta',
    stem: 'Kış sürüşünde yol yüzeyine bakıp buzlu (kaygan) kesimi önceden sezmek için hangi ipuçları işe yarar?',
    options: [
      'Yalnızca hava sıcaklığı sıfırın çok altındaysa buz olabilir',
      'Yolun rengi ve parlaklığı okunur: mat-beyazımsı ya da ıslakmış gibi parlayan koyu kesimler (siyah buz), köprü/gölge/gölet kenarları buzlu olabilir; buralara girmeden hız düşürülür',
      'Buz yalnızca kar yağarken oluşur, kuru havada olmaz',
      'Buzlu zemin her zaman gözle net görüldüğü için ayrıca dikkat gerekmez',
    ],
    answerIndex: 1,
    explanation:
      'Buzlu zemin çoğu zaman ıslak asfalt gibi görünür; koyu ve camsı parlayan kesimler ("siyah buz") ya da mat-beyaz lekeler kayganlığın habercisidir. Köprü üstleri, gölge alanlar, nehir-gölet kenarları ve tünel ağızları erken donar. Bu işaretler görülünce daha üzerine gelmeden hız düşürülür; ani fren, gaz ve direksiyondan kaçınılır. Sıcaklık sıfır dolayındayken kuru görünen yol bile buzlu olabilir.',
    whyWrong: [
      'Buz için havanın çok soğuk olması şart değildir; sıfır dolayında ve nemli zeminde de oluşur.',
      'Siyah buz çoğu kez ıslak asfalttan ayırt edilemez; "her zaman net görülür" varsayımı tehlikelidir.',
    ],
    objective: 'Yol yüzeyinin renk ve parlaklığından gizli buzlanmayı okumayı öğrenmek.',
    tags: ['siyah-buz', 'yol-okuma', 'kis-surusu'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-632',
    subject: 'pratik',
    topic: 'serit-disiplini-sag',
    difficulty: 'kolay',
    stem: 'Bölünmüş çok şeritli bir yolda sürekli orta ya da sol şeritte yavaşça seyretmek neden yanlıştır?',
    options: [
      'Sol ve orta şeritte yakıt tüketimi arttığı için',
      'Sağ şerit esas seyir şerididir; sol şeritler sollama ve daha hızlı akış içindir. Boşken solda kalmak arkadan gelenleri sağdan geçmeye zorlar, trafik akışını bozar ve tehlikeli sollamaları körükler',
      'Orta şeritte aynalar daha az kullanıldığı için',
      'Sol şeritte hız sınırı olmadığı için',
    ],
    answerIndex: 1,
    explanation:
      'Çok şeritli yollarda esas olan sağ şeritten seyretmek, sol şeritleri sollama ve daha hızlı akış için boş bırakmaktır. Sağ şerit boşken solda yavaş gitmek, arkadan gelenleri sağdan geçmeye ve gereksiz şerit değişimlerine iter; bu, akışı bozup çarpışma riskini artırır. Sollama bittiğinde ya da arkadan hızlı araç geldiğinde sağa dönülür.',
    whyWrong: [
      'Sorun yakıt ya da ayna kullanımı değil, akış düzeninin ve şerit mantığının bozulmasıdır.',
      'Sol şeritte de hız sınırı geçerlidir; şerit seçimi hız sınırını ortadan kaldırmaz.',
    ],
    objective:
      'Çok şeritli yolda sağ şerit esasını ve gereksiz solda kalmanın sakıncasını kavramak.',
    tags: ['serit-disiplini', 'sag-serit', 'akis'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-633',
    subject: 'pratik',
    topic: 'navigasyon-bakis-disiplini',
    difficulty: 'orta',
    stem: 'Seyir hâlinde navigasyon ekranını kullanırken güvenli bakış disiplini nasıl olmalıdır?',
    options: [
      'Ekrana istenildiği kadar uzun bakılabilir, önemli olan yolu ara ara kontrol etmektir',
      'Navigasyon yalnızca durunca kurulmalı, hareket hâlinde ekrana ise en fazla bir-iki saniyelik kısa bakışlarla göz atılmalı; asıl güven sesli yönergelere verilmeli ve karmaşık ekran işlemleri güvenli bir yerde durulup yapılmalıdır',
      'Ekran sürücünün kucağında tutulup sürekli izlenmelidir',
      'Adres, direksiyondayken ve seyir hâlindeyken yazılmalıdır',
    ],
    answerIndex: 1,
    explanation:
      'Bir-iki saniyelik bir ekran bakışı bile şehir hızında onlarca metre kör sürüş demektir; bu yüzden hedef seyir hâlinde durmadan yönergeyi almaktır. Navigasyon araç dururken kurulur, hareket hâlinde ekrana yalnızca çok kısa göz atılır ve asıl olarak sesli yönergelere güvenilir. Adres girme gibi karmaşık işlemler kesinlikle güvenli bir yere durularak yapılır.',
    whyWrong: [
      'Ekrana uzun bakmak, arada yola bakmak onu telafi etmez; kör kalınan an tehlikeyi çoktan doğurur.',
      'Ekranı kucakta izlemek ya da seyir hâlinde adres yazmak, dikkatin en tehlikeli biçimde dağılmasıdır.',
    ],
    objective: 'Navigasyon kullanımında kısa bakış ve sesli yönerge disiplinini benimsemek.',
    tags: ['navigasyon', 'dikkat', 'iki-saniye'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-634',
    subject: 'pratik',
    topic: 'sollama-oncesi-degerlendirme',
    difficulty: 'orta',
    stem: 'Çift yönlü tek şeritli bir yolda öndeki aracı sollamaya karar vermeden önce sürücünün yapması gereken temel değerlendirme nedir?',
    options: [
      'Karşı yönün yeterince uzağa kadar boş ve görüşün açık olduğundan emin olmak, sollamanın izinli olduğunu (kesik çizgi, işaretleme) doğrulamak ve manevrayı bitirip güvenle dönebilecek mesafeyi hesaplamak; kuşku varsa sollamaktan vazgeçmek',
      'Öndeki araç yavaşsa görüşe bakmadan hemen geçmek',
      'Sadece sinyal verip karşı yönü kontrol etmeden çıkmak',
      'Sollamayı virajda ya da tepe üstünde, görüş kapalıyken denemek',
    ],
    answerIndex: 0,
    explanation:
      'Sollama, karşı yönü bir süreliğine işgal ettiği için en riskli manevralardan biridir. Çıkmadan önce karşı yönün yeterince uzağa kadar boş ve görüşün açık olduğu, sollamanın izinli olduğu ve manevrayı tamamlayıp güvenle geri dönecek mesafenin bulunduğu birlikte değerlendirilir. En küçük kuşkuda sollamadan vazgeçilir; kaybedilen birkaç saniye, alınan riskin yanında önemsizdir.',
    whyWrong: [
      'Öndeki yavaş diye görüşe bakmadan geçmek, kafa kafaya çarpışmanın en sık nedenidir.',
      'Görüş kapalı virajda ya da tepe üstünde sollamak, karşıdan geleni göremeden şerit işgal etmektir.',
    ],
    objective: 'Sollama öncesi görüş, izin ve mesafe değerlendirmesini yapabilmek.',
    tags: ['sollama', 'gorus-mesafesi', 'karar'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-635',
    subject: 'pratik',
    topic: 'daralan-yol-oncelik',
    difficulty: 'kolay',
    stem: 'Tek şeride düşen dar bir köprü ya da geçitte, "karşıdan gelen araca yol ver" işareti bulunuyorsa ne yapılmalıdır?',
    options: [
      'Önce siz geçip karşıdan geleni bekletmelisiniz',
      'İşareti görmezden gelip hızlanarak dar kesime ilk girmeye çalışmalısınız',
      'Kornaya basıp geçiş hakkının sizde olduğunu belirtmelisiniz',
      'Dar kesime girmeden önce durup ya da yavaşlayıp karşıdan gelen araç geçene kadar beklemeli, yol boşaldığında geçmelisiniz',
    ],
    answerIndex: 3,
    explanation:
      'İki aracın yan yana sığamadığı dar kesimlerde geçiş sırası işaretle belirlenir; "karşıdan gelene yol ver" işareti önceliğin karşı yönde olduğunu söyler. Bu durumda dar kesime girmeden önce yavaşlanır ya da uygun yerde durulup karşı araç geçene kadar beklenir. Yol boşaldığında geçiş yapılır. İşareti yok sayıp önce girmeye çalışmak, dar kesimin ortasında kilitlenmeye ve geri manevraya yol açar.',
    whyWrong: [
      'İşaret önceliği karşı tarafa verdiğinden, önce geçmeye kalkmak kuralı çiğnemektir.',
      'Hızlanıp ilk girmek ya da kornayla üstünlük iddia etmek, dar kesimde karşılaşma ve tıkanma riski yaratır.',
    ],
    objective: 'Daralan yolda öncelik işaretine göre bekleyip geçmeyi öğrenmek.',
    tags: ['dar-gecit', 'gecis-onceligi', 'levha'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-636',
    subject: 'pratik',
    topic: 'sola-donus-bekleme',
    difficulty: 'zor',
    stem: 'Kavşakta sola dönmek için karşıdan gelen trafiğin geçmesini beklerken ön tekerlekler neden düz tutulmalıdır?',
    options: [
      'Düz tekerlek yakıt tükettirmediği için',
      'Sola kırık tekerlek motoru zorladığı için',
      'Tekerlek düzken sinyal daha iyi görüldüğü için',
      'Beklerken tekerlekler sola kırılı olursa ve arkadan bir araç çarparsa, araç doğrudan karşı şeride, gelen trafiğin içine itilir; tekerlekler düzken ise ileri, kendi şeridi yönünde gider',
    ],
    answerIndex: 3,
    explanation:
      'Sola dönüş için beklerken tekerlekleri şimdiden sola kırmak sıradan bir alışkanlık gibi görünür ama tehlikelidir: arkadan çarpılırsa kırılı tekerlekler aracı doğrudan karşıdan gelen trafiğin içine sürükler. Tekerlekler düz tutulduğunda aynı darbe aracı ileri, kendi şeridi doğrultusunda iter ve kafa kafaya çarpışma önlenir. Direksiyon ancak dönüşe geçileceği anda kırılır.',
    whyWrong: [
      'Yakıt, sinyal görünürlüğü ya da motor zorlanması bu kuralın gerekçesi değildir.',
      'Asıl mesele arkadan çarpma anında aracın hangi yöne savrulacağıdır; düz tekerlek karşı şeride itilmeyi önler.',
    ],
    objective: 'Sola dönüş beklemesinde tekerlekleri düz tutmanın güvenlik nedenini kavramak.',
    tags: ['sola-donus', 'bekleme', 'arkadan-carpma'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-637',
    subject: 'pratik',
    topic: 'yaya-goz-temasi',
    difficulty: 'kolay',
    stem: 'Yol kenarında geçmek için bekleyen bir yayaya yaklaşırken, onun niyetini anlamak için sürücünün başvurabileceği pratik yöntem nedir?',
    options: [
      'Yayanın mutlaka geçmeyeceğini varsayıp hızlanmak',
      'Yayayla göz teması kurmaya çalışmak ve baş-vücut yönü ile ayak hareketinden geçme niyetini okumak; temas kurulamıyorsa yayanın her an adım atabileceği varsayılıp hız düşürülür',
      'Farları sürekli yakıp söndürerek yayayı hızlıca geçirmeye zorlamak',
      'Yaya yaşlıysa durmak, gençse durmamak',
    ],
    answerIndex: 1,
    explanation:
      'Yayanın niyetini okumanın en iyi yolu, mümkünse göz teması kurmak ve vücut yönü ile ilk adım hareketini izlemektir; bunlar geçme niyetinin en güvenilir işaretleridir. Göz teması kurulamıyor ya da yaya (özellikle çocuk, yaşlı, dikkati dağınık kişi) yola bakmıyorsa, her an adım atabileceği varsayılarak hız düşürülür ve durmaya hazır olunur. Sürücü niyeti tahmin etmek yerine güvenli tarafta kalmalıdır.',
    whyWrong: [
      'Geçmeyeceğini varsayıp hızlanmak, yanlış tahminde doğrudan yayaya çarpmayı getirir.',
      'Farla zorlamak ya da yaşa göre karar vermek, güvenli yol verme ilkesinin yerini tutmaz.',
    ],
    objective: 'Yayanın geçiş niyetini göz teması ve vücut diliyle okumayı öğrenmek.',
    tags: ['yaya', 'goz-temasi', 'niyet-okuma'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-638',
    subject: 'pratik',
    topic: 'uzun-yol-yorgunluk',
    difficulty: 'kolay',
    stem: 'Uzun bir yolculukta sürüş yorgunluğunu yönetmek için önerilen temel yaklaşım nedir?',
    options: [
      'Ortalama iki saatte bir ya da yorgunluk belirtileri başladığında (esneme, ağırlaşan göz kapağı, dikkat dağınıklığı) güvenli bir yerde mola verip kısa süre dinlenmek; uykusuzken direksiyona geçmemek',
      'Yorgunluk hissedilse de mümkün olduğunca durmadan devam etmek',
      'Pencereyi açıp yüksek sesle müzik dinlemenin uykuyu tümüyle önlediğine güvenmek',
      'Yorulunca hızı artırıp yolculuğu bir an önce bitirmek',
    ],
    answerIndex: 0,
    explanation:
      'Yorgunluk, tepki süresini uzatıp dikkati böldüğü için alkol kadar tehlikeli olabilir; en etkili önlem, yorgunluk birikmeden yaklaşık iki saatte bir ve ilk belirtilerde (esneme, göz kapaklarının ağırlaşması, şerit sapması) mola vermektir. Kısa bir dinlenme, hava alma ve gerekiyorsa kısa bir uyku tazeler. Cam açmak ya da müzik geçici bir uyarıdır; uykuyu yenmez, bu yüzden uykuluyken sürüşe hiç başlanmamalıdır.',
    whyWrong: [
      'Durmadan devam etmek yorgunluğu biriktirir ve mikro uykulara (bir anlık dalıp gitme) yol açar.',
      'Cam açmak, müzik ya da hızlanmak yorgunluğun çözümü değildir; uykuyu maskeleyip riski büyütür.',
    ],
    objective: 'Uzun yolda mola ve yorgunluk belirtisi yönetimini kavramak.',
    tags: ['yorgunluk', 'mola', 'uzun-yol'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-639',
    subject: 'pratik',
    topic: 'gece-kenar-tarama',
    difficulty: 'orta',
    stem: 'Gece şehirlerarası bir yolda seyrederken hayvan çıkışına karşı bakış nasıl yönetilmelidir?',
    options: [
      'Yalnızca yol ortasındaki çizgiye bakmak yeterlidir',
      'Bakış yalnız şerit içinde tutulur, kenarlara hiç bakılmaz',
      'Farın aydınlattığı alanla birlikte yol kenarları ve hendekler de taranır; karanlıkta parlayan iki nokta (hayvan gözlerinin yansıması) görülürse hız hemen azaltılır, çünkü bir hayvanın ardından sürünün gelebileceği düşünülür',
      'Uzun far sürekli kapalı tutulup yavaş gidilir',
    ],
    answerIndex: 2,
    explanation:
      'Gece hayvanlar çoğunlukla yol kenarından ve hendeklerden aniden girer; bu yüzden bakış yalnız şerit içinde değil, farın kenar aydınlatması boyunca da gezdirilmelidir. Karanlıkta beliren, parlayan iki nokta hayvan gözlerinin far yansımasıdır ve görülür görülmez hız azaltılır; bir hayvanın arkasından başkalarının gelebileceği varsayılır. Uygun yerde uzun far, kenarları daha erken görmeyi sağlar.',
    whyWrong: [
      'Yalnız orta çizgiye ya da şerit içine bakmak, tehlikenin geldiği kenarları karanlıkta bırakır.',
      'Uzun farı sürekli kapalı tutmak, boş yolda kenarları görme mesafesini gereksiz yere kısaltır.',
    ],
    objective:
      'Gece yol kenarı taraması ve göz yansımasıyla hayvan çıkışını erken sezmeyi öğrenmek.',
    tags: ['gece-surus', 'hayvan-cikmasi', 'kenar-tarama'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-640',
    subject: 'pratik',
    topic: 'serit-daralmasi-fermuar',
    difficulty: 'orta',
    stem: 'İki şeridin tek şeride düştüğü bir yol çalışması ya da daralmada trafiğin en akıcı ve güvenli ilerlemesini sağlayan yöntem hangisidir?',
    options: [
      'Her aracın daralma noktasına kadar kendi şeridinde ilerleyip birleşme yerinde sırayla, dönüşümlü olarak (fermuar gibi) tek şeride katılması',
      'Kapanan şeritteki herkesin çok önceden diğer şeride geçip tek sıra olması',
      'Kapanan şeridi kullananların hızlanıp öndekilerin önüne zorla girmesi',
      'İki şeridin de daralmayı görmezden gelip yan yana sıkışarak devam etmesi',
    ],
    answerIndex: 0,
    explanation:
      'Şerit daralmasında en verimli düzen, araçların birleşme noktasına kadar iki şeridi de kullanıp tam daralma yerinde sırayla, bir o şeritten bir bu şeritten dönüşümlü olarak katılmasıdır; buna fermuar sistemi denir. Bu yöntem her iki şeridin kapasitesini kullandığı için kuyruğu kısaltır ve ani şerit değişimlerini azaltır. Katılan araca yer açmak, birleşme yerinde nezaket değil, akışın gereğidir.',
    whyWrong: [
      'Herkesin çok önceden tek şeride yığılması, bir şeridi boş bırakıp kuyruğu gereksiz uzatır.',
      'Zorla öne girmek ya da yan yana sıkışmak, sürtüşme ve tıkanma yaratıp akışı büsbütün bozar.',
    ],
    objective: 'Şerit daralmasında fermuar (dönüşümlü katılma) yöntemini kavramak.',
    tags: ['serit-daralmasi', 'fermuar', 'yol-calismasi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-641',
    subject: 'pratik',
    topic: 'buyuk-arac-donus-payi',
    difficulty: 'zor',
    stem: 'Sağa dönmek üzere yavaşlayan bir kamyon ya da otobüsün sağ tarafından geçmeye çalışmak neden çok tehlikelidir?',
    options: [
      'Büyük araçlar dönerken korna çaldığı için',
      'Uzun araçlar sağa dönerken önce sola doğru genişçe açılıp geniş bir yay çizer; sağda kalan boşluğa giren araç ya da bisikletli, dönüşü tamamlayan aracın arka tekerlekleri tarafından kaldırıma sıkıştırılıp ezilebilir (kör nokta ve iz farkı)',
      'Büyük araçların freni daha yavaş tuttuğu için',
      'Kamyonların egzozu görüşü kapattığı için',
    ],
    answerIndex: 1,
    explanation:
      'Uzun araçlar dar bir köşeyi dönebilmek için sağa dönmeden önce sola doğru genişçe açılır; bu, sağ tarafta geçici bir boşluk yanılsaması yaratır. Bu boşluğa giren araç ya da bisikletli, dönüş tamamlanırken içeriden dönen arka tekerleklerin ve şoförün göremediği kör noktanın arasında kaldırıma sıkışabilir. Bu yüzden dönüş sinyali veren büyük aracın sağından asla geçilmez; arkasında güvenli mesafede beklenir.',
    whyWrong: [
      'Korna ya da egzoz değil, aracın çizdiği geniş yay ile iz farkı ve kör nokta tehlikeyi yaratır.',
      'Fren süresi burada belirleyici değildir; asıl mesele dönüş geometrisi ve sıkışma riskidir.',
    ],
    objective: 'Büyük araçların dönüş geometrisini ve sağ taraf sıkışma riskini kavramak.',
    tags: ['buyuk-arac', 'donus-payi', 'kor-nokta'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-642',
    subject: 'pratik',
    topic: 'viraj-fren-zamanlama',
    difficulty: 'orta',
    stem: 'Bir virajı güvenli ve dengeli almak için frenleme ve gaz kullanımının doğru zamanlaması nedir?',
    options: [
      'Frene viraj ortasında, en keskin noktada basmak',
      'Viraja hızlı girip içeride gaz kesmeden dönmek',
      'Viraj boyunca frene basılı gitmek',
      'Yavaşlama viraja girmeden düz kesimde tamamlanır; virajın içinde ise sabit ya da hafifçe artan gazla, ani fren yapmadan geçilir. Çıkışta yol düzeldikçe kademeli hızlanılır',
    ],
    answerIndex: 3,
    explanation:
      'Lastiğin tutunması hem dönmeye hem frenlemeye aynı anda yetmez; bu yüzden hız kesme işi viraja girmeden, tekerlekler düzken tamamlanır. Viraj içinde sabit ya da hafifçe artan gazla araç dengede tutulur; içeride yapılan ani fren, ağırlığı öne bindirip arkayı hafifleterek savrulmaya yol açabilir. Çıkışta yol düzeldikçe direksiyon açılır ve kademeli hızlanılır.',
    whyWrong: [
      'Viraj ortasında ya da boyunca fren yapmak, tutunmayı bölerek savrulma ve kayma riskini artırır.',
      'Viraja hızlı girip içeride hiç yavaşlamamak, dönüş yayını tutamayıp şeritten taşmaya yol açar.',
    ],
    objective: 'Virajda frenlemeyi giriş öncesine alıp içeride sabit gazla geçmeyi öğrenmek.',
    tags: ['viraj', 'fren-zamanlama', 'denge'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-643',
    subject: 'pratik',
    topic: 'yol-calismasi-gecis',
    difficulty: 'kolay',
    stem: 'Yol çalışması yapılan, işçilerin ve konilerin bulunduğu bir kesimden geçerken doğru davranış nedir?',
    options: [
      'Çalışma alanında hız serbesttir, normal hızla geçilir',
      'İşçilere yakın geçmek için sağa iyice yanaşıp hızlanmak',
      'Uyarı levhalarına ve varsa işaretçinin (flamacı) yönlendirmesine uyulur, hız belirgin biçimde düşürülür, işçilere ve makinelere yan mesafe bırakılır; ani fren ve manevradan kaçınılıp çalışanların aniden öne çıkabileceği düşünülür',
      'Konilerin arasından kestirme yaparak geçmek',
    ],
    answerIndex: 2,
    explanation:
      'Yol çalışması alanı; yeri değişen işçiler, hareket eden makineler ve daralan şeritler nedeniyle öngörülemez bir bölgedir. Uyarı levhalarına ve varsa işaretçinin talimatına uyulur, hız erkenden düşürülür ve çalışanlarla makinelere olabildiğince yan mesafe bırakılır. Bir işçinin aniden öne çıkabileceği ya da bir aracın manevra yapabileceği hesaba katılarak hazır olunur; koniler bir sınır değil, uyulması gereken bir güzergâhtır.',
    whyWrong: [
      'Çalışma alanında hız çoğu zaman özel olarak sınırlandırılır; serbest saymak kural ihlali ve tehlikedir.',
      'İşçilere yakın hızlanmak ya da konilerin arasından kestirmek, doğrudan can güvenliğini tehdit eder.',
    ],
    objective: 'Yol çalışması alanında hız, mesafe ve işaretçi uyumunu uygulayabilmek.',
    tags: ['yol-calismasi', 'isci-guvenligi', 'hiz-dusurme'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-644',
    subject: 'pratik',
    topic: 'dortlu-flasor-kullanim',
    difficulty: 'kolay',
    stem: 'Dörtlü flaşörün (tehlike uyarı ışıkları) yanlış kullanımıyla ilgili doğru bilgi hangisidir?',
    options: [
      'Yağmurda görünürlük artsın diye seyir hâlinde sürekli yakılabilir',
      'Sollama yaparken flaşör yakmak yeterlidir, sinyal gerekmez',
      'Park yasağı olan yerde flaşör yakınca durmak serbest olur',
      'Flaşör seyir hâlinde sinyalin yerini tutmaz; yanıkken sağa-sola dönüş sinyali verilemez ve niyet belirsizleşir. Doğru kullanım; arıza, kaza, aracın durması ya da ani tehlikeli yavaşlama gibi durumlarda diğerlerini uyarmaktır',
    ],
    answerIndex: 3,
    explanation:
      'Dörtlü flaşör bir "duruyorum ya da tehlikedeyim" uyarısıdır; arıza, kaza, zorunlu durma ya da ani ve beklenmedik yavaşlamada çevreyi uyarmak için kullanılır. Seyir hâlinde sürekli yakmak yanlıştır, çünkü flaşör yanıkken dönüş sinyali verilemez ve aracın niyeti okunamaz hâle gelir. Ayrıca flaşör yakmak park ya da duraklama yasağını kaldırmaz.',
    whyWrong: [
      'Yağmurda sürekli flaşör, dönüş ve şerit sinyalini işlevsiz bırakıp diğer sürücüleri yanıltır.',
      'Sollamada sinyalin yerini tutmaz ve flaşör yakmak hiçbir duraklama-park yasağını geçersiz kılmaz.',
    ],
    objective: 'Dörtlü flaşörün doğru kullanım amacını ve yanlış kullanımlarını ayırt edebilmek.',
    tags: ['dortlu-flasor', 'uyari', 'sinyal'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-645',
    subject: 'pratik',
    topic: 'lastik-basinci-tutus',
    difficulty: 'kolay',
    stem: 'Lastik hava basıncının önerilen değerin belirgin altında olması sürüşü nasıl etkiler?',
    options: [
      'Yol tutuşunu ve fren performansını iyileştirir',
      'Yalnızca lastik ömrünü uzatır, sürüşü etkilemez',
      'Direksiyon ağırlaşır, yakıt tüketimi ve lastik ısınması artar, viraj ve frende yol tutuşu bozulur; aşırı düşük basınçta lastik yüksek hızda ısınıp patlayabilir',
      'Aracı daha hızlı ve dengeli yapar',
    ],
    answerIndex: 2,
    explanation:
      'Düşük basınçlı lastik yanaklarından fazla ezilir; bu, direksiyonu ağırlaştırır, yuvarlanma direncini ve yakıt tüketimini artırır ve lastiği aşırı ısıtır. Viraj ve frende temas yüzeyi düzensizleştiği için yol tutuşu bozulur; çok düşük basınçta yüksek hızda biriken ısı, ani patlamaya kadar gidebilir. Bu yüzden basınç düzenli olarak, üreticinin önerdiği değerde tutulur.',
    whyWrong: [
      'Düşük basınç yol tutuşunu ve freni iyileştirmez; tam tersine bozar.',
      'Lastik ömrünü uzatmaz; düzensiz ve hızlı aşınmaya yol açar, sürüşü de belirgin biçimde etkiler.',
    ],
    objective: 'Düşük lastik basıncının yol tutuşu, yakıt ve güvenliğe etkisini kavramak.',
    tags: ['lastik-basinci', 'yol-tutusu', 'guvenlik'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-646',
    subject: 'pratik',
    topic: 'yandan-giren-arac',
    difficulty: 'zor',
    stem: 'Yandaki şeritten bir aracın sinyal vermeden ve mesafe bırakmadan aniden önünüze girmesi durumunda en doğru tepki nedir?',
    options: [
      'Bakışı gidilecek boşlukta tutup ayağı gazdan çekmek ve kontrollü frenle mesafeyi yeniden açmak; gerekiyorsa kısa kornayla uyarmak, ancak refleksle ani ve kontrolsüz şerit değişiminden kaçınmaktır',
      'Direksiyonu bakmadan yan şeride kırıp hemen kaçmak',
      'Öfkeyle hızlanıp aracın hemen arkasına yapışmak',
      'Gözleri kapatıp frene sonuna kadar tek hamlede basmak',
    ],
    answerIndex: 0,
    explanation:
      'Aniden önünüze giren araca karşı en büyük ikincil tehlike, düşünmeden yapılan sert şerit kaçışıdır; yan şeritte araç ya da kör noktada başka bir tehlike olabilir. Doğrusu bakışı ilerideki güvenli boşlukta tutmak, gazı bırakıp kontrollü frenle takip mesafesini yeniden açmaktır; gerekiyorsa kısa bir kornayla uyarılır. Panikle direksiyon kırmak ya da öfkeyle yapışmak, tek bir kabalığı çok araçlı bir kazaya çevirebilir.',
    whyWrong: [
      'Bakmadan yan şeride kaçmak, oradaki bir aracın üzerine gitme riskini doğurur.',
      'Hızlanıp arkasına yapışmak ya da gözleri kapatıp panik fren yapmak, kontrolü ve güvenliği birlikte kaybettirir.',
    ],
    objective:
      'Ani şerit ihlaline karşı panik manevra yerine kontrollü fren ve mesafe açmayı öğrenmek.',
    tags: ['ani-giris', 'panik-onleme', 'takip-mesafesi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-647',
    subject: 'pratik',
    topic: 'tepe-viraj-sollama-yasagi',
    difficulty: 'zor',
    stem: 'Tepe üstüne yaklaşırken ya da görüşün kapandığı bir viraj öncesinde sollama neden yapılmaz?',
    options: [
      'Tepe ve virajda motor gücü düştüğü için',
      'Bu kesimlerde karşı yönün yeterince ilerisi görülemez; tam sollama sırasında tepenin ardından ya da virajın devamından çıkan bir araçla kafa kafaya çarpışma kaçınılmaz olabilir, çünkü geri dönecek ne mesafe ne zaman kalır',
      'Tepe üstünde lastikler yere değmediği için',
      'Virajda sinyal ışıkları çalışmadığı için',
    ],
    answerIndex: 1,
    explanation:
      'Sollama, karşı yönü bir süre işgal ettiği için ancak yeterince ileriye kadar boş ve görüşün açık olduğu yerlerde güvenlidir. Tepe üstü ve kapalı viraj öncesinde karşı yönün ilerisi görülemez; tam siz karşı şeritteyken tepenin ardından ya da virajın devamından bir araç çıkarsa geri dönecek mesafe de zaman da kalmaz. Bu yüzden bu kesimler sollamanın yasak olduğu, en tehlikeli noktalardır ve genelde işaretlerle de belirtilir.',
    whyWrong: [
      'Motor gücü ya da lastik teması değil, görüş yokluğu ve geri dönüş payının olmaması belirleyicidir.',
      'Sinyal ışıklarının çalışması bu tehlikeyle ilgili değildir; sorun karşı yönü görememektir.',
    ],
    objective:
      'Tepe ve kapalı viraj öncesinde sollama yasağının görüş temelli gerekçesini kavramak.',
    tags: ['sollama-yasagi', 'tepe-ustu', 'gorus'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-648',
    subject: 'pratik',
    topic: 'gece-kirsal-yaya',
    difficulty: 'kolay',
    stem: 'Gece aydınlatması olmayan kırsal bir yolda, yol kenarında yürüyen yansıtıcısız yayalara karşı doğru davranış nedir?',
    options: [
      'Yaya görülmediği için normal hızda devam etmek',
      'Yalnızca uzun far açıksa yavaşlamak',
      'Koyu giyimli ve yansıtıcısız yayaların son anda görülebileceği düşünülerek hız düşük tutulur, görüş mesafesi içinde durabilecek şekilde sürülür; yayaya yaklaşırken karşıdan araç yoksa uzun far, varsa kısa far kullanılır',
      'Kornaya sürekli basarak ilerlemek',
    ],
    answerIndex: 2,
    explanation:
      'Aydınlatmasız kırsal yolda koyu giyimli, yansıtıcısız yayalar farın aydınlattığı alana ancak son anda girer; bu yüzden hız, görüş mesafesi içinde durabilecek kadar düşük tutulmalıdır. Karşıdan araç yokken uzun far kenarları daha erken gösterir, araç geldiğinde kısa fara geçilir. Yaya, bisikletli ya da hayvanın her an belirebileceği varsayılarak hazır sürülür.',
    whyWrong: [
      'Yaya görülmedi diye normal hızla gitmek, görüş mesafesinden uzun bir fren yolu bırakır.',
      'Sürekli korna çözüm değildir; belirleyici olan hızın görüşe uydurulması ve doğru far kullanımıdır.',
    ],
    objective: 'Gece kırsal yolda görüş mesafesine uygun hız ve far kullanımını uygulamak.',
    tags: ['gece-surus', 'kirsal-yol', 'yaya'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-649',
    subject: 'pratik',
    topic: 'su-sicratma-yaya',
    difficulty: 'kolay',
    stem: 'Yağmurdan sonra kaldırım kenarındaki su birikintisinin yanında yaya varken sürücünün doğru davranışı nedir?',
    options: [
      'Birikintiye gelmeden hızını azaltıp mümkünse birikintiden biraz uzak bir hat izlemek; böylece hem yayanın üzerine su sıçratılmaz hem de ıslak zeminde araç dengesi korunur',
      'Normal hızla geçip suyun sıçramasını önemsememek',
      'Hızlanarak birikintiyi bir an önce geride bırakmak',
      'Kornaya basıp yayayı uzaklaşması için uyararak hızla geçmek',
    ],
    answerIndex: 0,
    explanation:
      'Su birikintisine hızla girmek hem yayanın üzerine su sıçratarak rahatsızlık ve haksızlık yaratır hem de tek taraflı su direnciyle aracı o yöne çekip dengeyi bozabilir. Doğrusu birikintiye gelmeden hızı azaltmak ve mümkünse şerit içinde birikintiden biraz uzak bir hat tutmaktır. Bu, hem trafik adabının hem sürüş güvenliğinin gereğidir.',
    whyWrong: [
      'Su sıçratmayı önemsememek, kaçınılabilir bir rahatsızlığı ve saygısızlığı görmezden gelmektir.',
      'Hızlanmak sıçramayı ve dengesizliği artırır; korna, yavaşlamanın yerini tutmaz.',
    ],
    objective:
      'Yaya yanındaki su birikintisinde yavaşlama ve hat seçimini adap-güvenlik ilkesiyle uygulamak.',
    tags: ['su-birikintisi', 'yaya', 'trafik-adabi'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-650',
    subject: 'pratik',
    topic: 'uzun-arac-takip-gorus',
    difficulty: 'zor',
    stem: 'Önünüzde giden uzun bir kamyonun ya da otobüsün arkasında takip mesafesini normalden daha fazla açmanın en önemli nedeni nedir?',
    options: [
      'Büyük aracın egzoz gazından etkilenmemek için',
      'Kamyonların stop lambaları küçük olduğu için',
      'Büyük araçlar her zaman daha yavaş gittiği için',
      'Uzun aracın gerisinde çok yakın durursanız hem onun ötesindeki trafiği ve tehlikeleri göremezsiniz hem de o ani frende ya da bir şey düşürdüğünde tepki veremezsiniz; mesafeyi açmak ileriyi görmenizi ve sollama için de daha iyi karar vermenizi sağlar',
    ],
    answerIndex: 3,
    explanation:
      'Uzun bir araç, önündeki trafiği ve yoldaki tehlikeleri bir duvar gibi kapatır; onun hemen arkasında durursanız ileriyi hiç göremez, yalnızca kamyonun stoplarına tepki verebilirsiniz. Mesafeyi açtığınızda hem aracın yanından ilerisini görüp erken karar verebilir hem de ani frene ya da düşen bir yüke tepki için pay bırakırsınız. Bu görüş payı, güvenli sollama kararı için de gereklidir.',
    whyWrong: [
      'Egzoz gazı bir konfor meselesidir; asıl neden görüşün kapanması ve fren payının kalmamasıdır.',
      'Büyük araç her zaman yavaş değildir ve stop lambası boyutu da temel sorun değildir; sorun ileriyi görememektir.',
    ],
    objective: 'Uzun araç arkasında mesafe açmanın görüş ve karar avantajını kavramak.',
    tags: ['takip-mesafesi', 'buyuk-arac', 'gorus'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-651',
    subject: 'pratik',
    topic: 'dar-viraj-karsi-arac',
    difficulty: 'orta',
    stem: 'Çift yönlü dar bir virajda karşıdan gelen aracın orta çizgiye taşarak geldiğini görürseniz ne yapmalısınız?',
    options: [
      'Orta çizgiye siz de yaklaşıp geçiş hakkınızı korumak',
      'Farları yakıp aynı hızla devam etmek',
      'Hızı azaltıp mümkün olduğunca kendi şeridinizin sağına yanaşmak, gerekirse durmak; karşı aracın taşmasına karşı yan mesafe yaratıp temas riskini düşürmek',
      'Sola kırıp karşı aracın arkasından dolaşmak',
    ],
    answerIndex: 2,
    explanation:
      'Dar virajda karşıdan gelen bir aracın orta çizgiye taşması sık görülür ve kafa kafaya temas riski yaratır. Bu durumda haklılık aramak yerine güvenlik önceliklidir: hız azaltılır, kendi şeridinin en sağına yanaşılır ve gerekirse durulur. Böylece taşan araca yan mesafe açılır ve olası bir temasın hızı da düşürülmüş olur.',
    whyWrong: [
      'Orta çizgiye yaklaşıp hak aramak, iki aracı da tam karşılaşma noktasına iter.',
      'Aynı hızla devam etmek ya da sola kırmak, mesafeyi kapatıp çarpışmayı olası kılar.',
    ],
    objective: 'Dar virajda taşan karşı araca karşı sağa yanaşıp yavaşlamayı öğrenmek.',
    tags: ['dar-viraj', 'karsi-yon', 'yan-mesafe'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-652',
    subject: 'pratik',
    topic: 'acil-arac-yol-verme',
    difficulty: 'orta',
    stem: 'Arkanızdan siren ve tepe lambasıyla gelen bir ambulans ya da itfaiye aracına yol verirken doğru davranış nedir?',
    options: [
      'Olduğunuz yerde ani fren yapıp durmak',
      'Aracı hızlandırıp acil aracın önünde gitmeye çalışmak',
      'Kavşağın tam ortasında durup beklemek',
      'Sakin biçimde sağa yanaşıp gerekiyorsa durarak yol açmak; kavşak içindeyseniz kavşağı boşaltıp uygun yerde beklemek, kırmızı ışıkta bile önce güvenliği sağlayıp geçiş için yer açmak',
    ],
    answerIndex: 3,
    explanation:
      'Geçiş üstünlüğü olan ambulans, itfaiye ya da polis aracına yol vermek zorunludur; doğrusu paniklemeden sağa yanaşıp gerekiyorsa durarak ona serbest bir hat açmaktır. Kavşak içindeyseniz orada durup tıkamak yerine kavşağı boşaltıp uygun bir yerde beklenir. Ani ve düşünmeden yapılan duruşlar arkadan çarpmaya yol açacağından, yanaşma sakin ve öngörülü olmalıdır.',
    whyWrong: [
      'Bulunduğunuz yerde ani fren, hem arkadan çarpmaya hem acil aracın hattını tıkamaya yol açar.',
      'Acil aracın önünde gitmeye çalışmak ya da kavşak ortasında durmak, geçişi engelleyip tehlike yaratır.',
    ],
    objective: 'Geçiş üstünlüğü olan araca sağa yanaşarak güvenle yol vermeyi öğrenmek.',
    tags: ['acil-arac', 'yol-verme', 'siren'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-653',
    subject: 'pratik',
    topic: 'cocuk-top-cikma',
    difficulty: 'orta',
    stem: 'Yerleşim yerinde park etmiş araçların arasından yola bir top yuvarlandığını gören sürücünün öngörülü davranışı ne olmalıdır?',
    options: [
      'Topun ardından bir çocuğun aniden koşarak yola çıkabileceğini varsayıp hemen hızı kesmek, ayağı fren üzerine almak ve durmaya hazır olmak',
      'Sadece topa çarpmamak için hafifçe sağa kırıp devam etmek',
      'Top zararsız olduğu için hızı hiç değiştirmemek',
      'Kornaya basıp aynı hızla geçmek',
    ],
    answerIndex: 0,
    explanation:
      'Yola yuvarlanan bir top, çoğu zaman peşinden gelen ve çevreye bakmadan koşan bir çocuğun habercisidir; deneyimli sürücü topu değil, arkasından çıkacak çocuğu düşünür. Bu yüzden hız hemen kesilir, ayak fren üzerine alınır ve tam durmaya hazır olunur. Görüşü kapatan park sıralarının arkası özellikle izlenir; öngörü, tehlike ortaya çıkmadan yavaşlamaktır.',
    whyWrong: [
      'Yalnız topa odaklanıp sağa kırmak, asıl tehlike olan çocuğu gözden kaçırır.',
      'Hızı değiştirmemek ya da kornayla geçmek, aniden çıkabilecek çocuk için tepki payı bırakmaz.',
    ],
    objective: 'Yola çıkan top işaretinden çocuk tehlikesini öngörüp erken yavaşlamayı öğrenmek.',
    tags: ['cocuk', 'ongoru', 'yerlesim-yeri'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-654',
    subject: 'pratik',
    topic: 'gece-yagmur-gorus',
    difficulty: 'orta',
    stem: 'Gece yağmurda seyrederken şerit çizgilerinin ve yol kenarının seçilmesi neden zorlaşır ve sürücü nasıl davranmalıdır?',
    options: [
      'Islak zeminde far daha iyi yansıdığı için görüş artar, önlem gerekmez',
      'Görüş sorunu yalnızca silecek eskiyse yaşanır, hızın önemi yoktur',
      'Gece yağmurda en doğrusu uzun farı sürekli açık tutmaktır',
      'Islak asfalt far ışığını yansıtıp dağıttığından çizgiler ve kenar zor seçilir, karşıdan gelen farlar daha çok kamaştırır; hız düşürülür, takip mesafesi artırılır ve gerektiğinde öndeki aracın güvenli izi referans alınır',
    ],
    answerIndex: 3,
    explanation:
      'Islak asfalt bir ayna gibi davranıp far ışığını yansıtır ve dağıtır; bu yüzden gece yağmurda şerit çizgileri ile yol kenarı zor seçilir, karşıdan gelen farların kamaşması da artar. Doğru davranış hızı düşürmek, takip mesafesini açmak ve görüşü görüş mesafesine uydurmaktır; çizgiler kaybolduğunda öndeki aracın güvenli izi geçici bir referans olabilir. Islakta uzun far, yansıyıp kamaşmayı artırdığı için çoğu zaman kısa far daha nettir.',
    whyWrong: [
      'Islak zemin görüşü artırmaz; ışığı dağıtıp çizgi ve kenar seçimini zorlaştırır.',
      'Yağmurda sürekli uzun far kamaşmayı büyütür; sorun yalnız sileceğe bağlı değildir, hız belirleyicidir.',
    ],
    objective: 'Gece yağmurda görüş kaybına karşı hız, mesafe ve referans yönetimini uygulamak.',
    tags: ['gece-surus', 'yagmur', 'gorus'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-655',
    subject: 'pratik',
    topic: 'inis-sonu-kavsak',
    difficulty: 'orta',
    stem: 'Uzun bir inişin sonunda kırmızı ışıklı bir kavşak ya da kesin duruş gerektiren bir nokta varsa sürücü hızını nasıl yönetmelidir?',
    options: [
      'İnişin son metrelerine bırakıp orada sert fren yapmak',
      'Hızı inişin başından itibaren vitesle ve kademeli frenle kontrol altında tutmak; kavşağa kadar aracın enerjisini erkenden düşürüp son duruşu rahat ve kontrollü yapmak, çünkü inişte biriken hız son anda sert frenle zor durdurulur',
      'İnişte hızlanıp kavşağa gelince motoru stop ettirmek',
      'Boş viteste inip yalnızca ışığa yakınken frene basmak',
    ],
    answerIndex: 1,
    explanation:
      'İnişte yer çekimi aracı sürekli hızlandırır; hız kontrolü sona bırakılırsa biriken enerjiyi son metrelerde sert frenle durdurmak hem güç hem risklidir, ıslak-kaygan zeminde kayma getirebilir. Doğrusu inişin başından itibaren uygun vites ve motor freniyle hızı sınırlamak, gerektiğinde kademeli frenle desteklemektir; böylece kavşağa yaklaşırken araç zaten yavaşlamış olur ve duruş rahat, kontrollü yapılır. Boş viteste inmek motor frenini yok edip bu kontrolü ortadan kaldırır.',
    whyWrong: [
      'Frenlemeyi son metrelere bırakmak, biriken hızı ağır ve kayma riskli bir sert frene zorlar.',
      'İnişte hızlanmak ya da boş viteste inmek, kavşağa yüksek ve zor kontrol edilen bir hızla varmak demektir.',
    ],
    objective: 'İniş sonundaki duruşu, hızı baştan vites ve kademeli frenle yöneterek yapabilmek.',
    tags: ['yokus-inis', 'kavsak', 'hiz-yonetimi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
];
