/**
 * ÖZGÜN ilk yardım soruları — 3. genişletme (Program 1). ROADMAP C.4/E.6.
 * Kaynak = Resmî temel ilk yardım rehberleri; KENDİ İFADEMİZLE. Uzman onayı gereklidir.
 */
import type { QuestionInput } from '@ea/content-schema';

const SRC = 'Resmî temel ilk yardım rehberleri (özgün ifade; uzman onayı gerekli)';

export const ILKYARDIM_QUESTIONS_3: QuestionInput[] = [
  {
    id: 'ilkyardim-301',
    subject: 'ilkyardim',
    topic: 'abc-degerlendirme',
    difficulty: 'orta',
    stem: 'İlk yardımda yaşamsal işlevlerin değerlendirilmesinde kullanılan "ABC" kısaltması hangi sırayı ifade eder?',
    options: [
      'Ateş – Bilinç – Cilt rengi',
      'Ağrı – Bulantı – Baş dönmesi',
      'Hava yolu – Solunum – Dolaşım',
      'Ağız – Boğaz – Akciğer',
    ],
    answerIndex: 2,
    explanation:
      'ABC; hava yolu, solunum ve dolaşım sözcüklerinin sırasını anlatan bir kısaltmadır. İlk yardımcı yaşamsal işlevleri bu öncelik sırasıyla değerlendirir: önce hava yolunu açar, sonra solunumu ve dolaşımı kontrol eder.',
    whyWrong: [
      'Ateş, ağrı veya bulantı gibi bulgular ABC sırasını tanımlamaz.',
      'Ağız-boğaz-akciğer gibi eşleştirmeler ABC kısaltmasının karşılığı değildir.',
    ],
    objective: 'ABC değerlendirmesinin hava yolu-solunum-dolaşım sırasını kavramak.',
    tags: ['abc-degerlendirme', 'hava-yolu', 'solunum', 'dolasim'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-302',
    subject: 'ilkyardim',
    topic: 'abc-degerlendirme',
    difficulty: 'kolay',
    stem: 'Bilinci kapalı erişkin bir kişide dolaşımın (nabzın) olup olmadığı en güvenilir olarak nereden değerlendirilir?',
    options: [
      'Boyundaki şah damarı (şahdamar) bölgesinden',
      'El başparmağının ucundan',
      'Ayak tabanından',
      'Alın bölgesinden',
    ],
    answerIndex: 0,
    explanation:
      'Erişkinde büyük atardamar olan boyundaki şah damarı, dolaşımı değerlendirmek için en güvenilir bölgedir; buradan birkaç saniye nabız yoklanır. Uç bölgelerdeki nabız, dolaşım zayıfladığında hissedilmeyebilir.',
    whyWrong: [
      'Başparmak ucu veya ayak tabanı gibi uç noktalarda nabız, dolaşım zayıfken alınamayabilir.',
      'Alın bölgesinde güvenilir bir nabız noktası yoktur.',
    ],
    objective: 'Erişkinde nabzın şah damarından değerlendirildiğini bilmek.',
    tags: ['abc-degerlendirme', 'nabiz', 'dolasim'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-303',
    subject: 'ilkyardim',
    topic: 'temel-yasam-destegi',
    difficulty: 'orta',
    stem: 'Erişkin bir kişide temel yaşam desteğine (kalp masajı ve yapay solunuma) hangi durumda başlanır?',
    options: [
      'Kişi baygın ama düzenli nefes alıyorsa',
      'Kişinin yalnızca kolu kırıksa',
      'Kişi ağrıdan yakınıyorsa',
      'Bilinci kapalıysa ve solunumu yoksa (ya da normal solumuyorsa)',
    ],
    answerIndex: 3,
    explanation:
      'Temel yaşam desteği; bilinci kapalı olan ve solunumu bulunmayan (ya da normal olmayan) kişide başlatılır. Önce bilinç, sonra hava yolu ve solunum değerlendirilir; solunum yoksa vakit kaybetmeden göğüs basılarına geçilir.',
    whyWrong: [
      'Düzenli nefes alan baygın kişiye kalp masajı yapılmaz; ona koma pozisyonu verilir.',
      'Yalnızca kol kırığı veya ağrı, temel yaşam desteği başlatma nedeni değildir.',
    ],
    objective: 'Temel yaşam desteğinin başlatılma koşulunu kavramak.',
    tags: ['temel-yasam-destegi', 'solunum', 'bilinc-kaybi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-304',
    subject: 'ilkyardim',
    topic: 'temel-yasam-destegi',
    difficulty: 'orta',
    stem: 'Erişkinde göğüs basıları uygulanırken her basının ardından nelere dikkat edilmelidir?',
    options: [
      'Elleri göğüsten tamamen kaldırıp yerini değiştirmeye',
      'Göğsün eski hâline (tam olarak) geri gelmesine izin vermeye',
      'Basıyı olabildiğince yavaşlatmaya',
      'Her basıda bir soluk vermeye',
    ],
    answerIndex: 1,
    explanation:
      'Her göğüs basısından sonra ellerin teması kesilmeden göğsün tam olarak eski hâline gelmesine (geri dönmesine) izin verilir; böylece kalp yeniden kanla dolar. Bası ve gevşeme süreleri dengeli tutulur.',
    whyWrong: [
      'Elleri her seferinde kaldırıp yeniden yerleştirmek basının yerini şaşırtır ve zaman kaybettirir.',
      'Basıyı yavaşlatmak veya her basıda soluk vermek etkili dolaşımı bozar.',
    ],
    objective: 'Göğüs basısında göğsün tam geri gelmesinin önemini kavramak.',
    tags: ['temel-yasam-destegi', 'kalp-masaji', 'teknik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-305',
    subject: 'ilkyardim',
    topic: 'temel-yasam-destegi',
    difficulty: 'zor',
    stem: 'Yaklaşık 1-8 yaş arası bir çocukta dış kalp masajı, erişkine göre genellikle nasıl uygulanır?',
    options: [
      'İki elin topuğuyla ve daha derin bastırılarak',
      'Yumrukla göğse vurularak',
      'Çoğunlukla tek elin topuğuyla ve daha az derinlikte bastırılarak',
      'Yalnızca karın bölgesine bastırılarak',
    ],
    answerIndex: 2,
    explanation:
      'Çocukta göğüs kafesi erişkine göre daha küçük ve narindir; bu nedenle kalp masajı çoğunlukla tek elin topuğuyla, göğüs kemiğinin alt yarısına ve erişkinden daha az derinlikte uygulanır. Bebekte ise iki parmak tekniği kullanılır.',
    whyWrong: [
      'İki elle derin bası, çocukta kaburga ve iç organ yaralanmasına yol açabilir.',
      'Yumrukla vurmak veya karına bastırmak hiçbir yaşta doğru kalp masajı tekniği değildir.',
    ],
    objective: 'Çocukta kalp masajı tekniğini erişkin ve bebekten ayırt etmek.',
    tags: ['temel-yasam-destegi', 'cocuk', 'kalp-masaji'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-306',
    subject: 'ilkyardim',
    topic: 'kanama',
    difficulty: 'orta',
    stem: 'Atardamar (atar damar) kanamasını toplardamar kanamasından ayıran en belirgin özellik hangisidir?',
    options: [
      'Kanın açık kırmızı renkte ve kalp atımına uyumlu biçimde fışkırarak akması',
      'Kanın koyu renkte ve sızarak akması',
      'Kanamanın her zaman kendiliğinden hemen durması',
      'Kanın hiç akmayıp yalnızca morarma olması',
    ],
    answerIndex: 0,
    explanation:
      'Atardamar kanamasında kan, oksijence zengin olduğu için açık kırmızıdır ve basınç yüksek olduğundan kalp atımına uyumlu olarak fışkırır. Bu tür kanama hızlı kan kaybına yol açtığından acil ve etkili baskı gerektirir.',
    whyWrong: [
      'Koyu renkli ve sızıntı biçiminde akış toplardamar kanamasının özelliğidir.',
      'Atardamar kanaması kendiliğinden kolayca durmaz; morarma ise cilt altı kanamayı düşündürür.',
    ],
    objective: 'Atardamar ve toplardamar kanamasını akış özelliklerinden ayırt etmek.',
    tags: ['kanama', 'atardamar', 'belirti'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-307',
    subject: 'ilkyardim',
    topic: 'kanama',
    difficulty: 'kolay',
    stem: 'Bir kazada yaralının vücuduna büyük bir cisim (örneğin demir çubuk) saplanmışsa ilk yardımda ne yapılır?',
    options: [
      'Cisim hızlıca çekilip çıkarılır',
      'Cisim ileri geri oynatılarak gevşetilir',
      'Cismin üzerine basılarak içeri itilir',
      'Cisim yerinde bırakılır, çevresi desteklenerek sabitlenir ve 112 aranır',
    ],
    answerIndex: 3,
    explanation:
      'Saplanan cisim damar ve dokuları tıkaç gibi tutabildiğinden çıkarılırsa şiddetli kanama ve ek hasar oluşabilir. Cisim olduğu yerde bırakılır, çevresine destek konularak oynamayacak biçimde sabitlenir ve derhal 112 aranır.',
    whyWrong: [
      'Cismi çekmek veya oynatmak kanamayı ve iç yaralanmayı ağırlaştırır.',
      'Cismi içeri itmek dokulara daha fazla zarar verir.',
    ],
    objective: 'Saplanan cismin çıkarılmayıp sabitlenmesi ilkesini kavramak.',
    tags: ['kanama', 'saplanan-cisim', 'sabitleme'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-308',
    subject: 'ilkyardim',
    topic: 'sok',
    difficulty: 'kolay',
    stem: 'Şok belirtileri gösteren bir yaralıya ağızdan su veya yiyecek verilmemesinin başlıca nedeni nedir?',
    options: [
      'Yaralının iştahını kapatmamak için',
      'Bilinci bozulabileceğinden kusma ve soluk borusuna kaçma (boğulma) riski bulunduğu için',
      'Su yaralıya lezzetsiz geleceği için',
      'Su kanamayı doğrudan artıracağı için',
    ],
    answerIndex: 1,
    explanation:
      'Şoktaki yaralının bilinci her an bozulabilir; ağızdan verilen sıvı veya besin kusmaya ve soluk borusuna kaçarak boğulmaya yol açabilir. Ayrıca gerekebilecek acil işlemler için midenin boş olması önemlidir. Bu nedenle ağızdan bir şey verilmez.',
    whyWrong: [
      'Sakınca iştah veya lezzetle ilgili değildir.',
      'Su içmek kanamayı doğrudan artırmaz; asıl tehlike boğulma ve kusma riskidir.',
    ],
    objective: 'Şokta ağızdan besin/sıvı verilmemesinin gerekçesini kavramak.',
    tags: ['sok', 'guvenlik', 'beslenme-yasagi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-309',
    subject: 'ilkyardim',
    topic: 'kirik-cikik-burkulma',
    difficulty: 'orta',
    stem: 'Omuz ya da parmak gibi bir eklemin yerinden çıktığı (çıkık) durumda ilk yardımcı ne yapmalıdır?',
    options: [
      'Eklemi hızlıca çekip yerine oturtmaya çalışmak',
      'Eklemi defalarca hareket ettirmek',
      'Eklemi bulunduğu şekilde sabitleyip soğuk uygulayarak sağlık kuruluşuna yönlendirmek',
      'Çıkık bölgeyi sıcak suya sokmak',
    ],
    answerIndex: 2,
    explanation:
      'Çıkıkta eklem yüzeyleri yerinden ayrılmıştır; ilk yardımcı eklemi yerine oturtmaya çalışmaz, çünkü bu damar ve sinir hasarına yol açabilir. Eklem bulunduğu konumda sabitlenir, şişme için soğuk uygulanabilir ve yaralı sağlık kuruluşuna yönlendirilir.',
    whyWrong: [
      'Eklemi çekip yerine oturtmaya çalışmak çevre dokularda ciddi hasar oluşturabilir.',
      'Bölgeyi hareket ettirmek veya sıcak suya sokmak ağrıyı ve şişliği artırır.',
    ],
    objective: 'Çıkıkta eklemin yerine oturtulmayıp sabitlenmesi ilkesini kavramak.',
    tags: ['kirik-cikik-burkulma', 'cikik', 'sabitleme'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-310',
    subject: 'ilkyardim',
    topic: 'kirik-cikik-burkulma',
    difficulty: 'kolay',
    stem: 'Kapalı bir kırığı düşündüren belirtilerden biri aşağıdakilerden hangisidir?',
    options: [
      'Bölgede şişlik, şekil bozukluğu ve hareketle artan şiddetli ağrı',
      'Ciltte kaşıntı ve kızarıklık',
      'Ateşin aniden yükselmesi',
      'Karın bölgesinde açlık hissi',
    ],
    answerIndex: 0,
    explanation:
      'Kapalı kırıkta deri bütünlüğü bozulmadığı hâlde kırık bölgede şişlik, şekil bozukluğu (deformite), morarma ve hareketle artan şiddetli ağrı görülür; bölge çoğu zaman kullanılamaz. Bu belirtilerde kırık gibi davranılıp bölge sabitlenir.',
    whyWrong: [
      'Kaşıntı ve kızarıklık daha çok alerji veya cilt sorunlarını düşündürür.',
      'Ateş yükselmesi ve açlık hissi kırığın tipik belirtileri değildir.',
    ],
    objective: 'Kapalı kırığın belirtilerini tanımak.',
    tags: ['kirik-cikik-burkulma', 'belirti', 'kirik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-311',
    subject: 'ilkyardim',
    topic: 'kirik-cikik-burkulma',
    difficulty: 'zor',
    stem: 'Kırık şüphesi olan bir kol veya bacağa atel (destek) uygulanırken uyulması gereken temel kural nedir?',
    options: [
      'Yalnızca kırığın tam üzerini sarmak',
      'Ateli çok gevşek bağlayıp bölgeyi serbest bırakmak',
      'Kırık bölgeyi önce elle düzeltip sonra sarmak',
      'Atelin, kırığın bir alt ve bir üst eklemini de içine alacak şekilde uygulanması',
    ],
    answerIndex: 3,
    explanation:
      'Atel, kırık bölgeyi hareketsiz kılmalıdır; bunun için atelin kırığın hem bir alt hem de bir üst eklemini içine alacak uzunlukta olması gerekir. Böylece kırık uçların oynaması ve ek doku hasarı engellenir. Atel ne dolaşımı kesecek kadar sıkı ne de işe yaramayacak kadar gevşek bağlanır.',
    whyWrong: [
      'Yalnızca kırığın üzerini sarmak komşu eklemlerin hareketini engellemez.',
      'Çok gevşek atel tespit sağlamaz; kırığı elle düzeltmeye çalışmak ise damar-sinir hasarına yol açabilir.',
    ],
    objective: 'Atel uygulamasında bir alt ve bir üst eklemi içine alma kuralını kavramak.',
    tags: ['kirik-cikik-burkulma', 'atel', 'tespit'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-312',
    subject: 'ilkyardim',
    topic: 'yanik',
    difficulty: 'orta',
    stem: 'İkinci derece bir yanıkta ciltte görülen tipik bulgu aşağıdakilerden hangisidir?',
    options: [
      'Yalnızca hafif kızarıklık ve kuruluk',
      'İçi sıvı dolu su kabarcıklarının (bül) oluşması',
      'Ciltte hiçbir değişiklik olmaması',
      'Bölgenin tümüyle soğuması',
    ],
    answerIndex: 1,
    explanation:
      'İkinci derece yanıkta cildin daha derin katmanları etkilenir; kızarıklık ve ağrının yanında içi sıvı dolu su kabarcıkları (bül) oluşur. Bu kabarcıklar patlatılmaz, bölge soğuk suyla soğutulup temiz bezle örtülür.',
    whyWrong: [
      'Yalnızca hafif kızarıklık ve kuruluk birinci derece yanığın bulgusudur.',
      'Ciltte hiçbir değişiklik olmaması veya soğuma yanık tablosunu tanımlamaz.',
    ],
    objective: 'İkinci derece yanığı su kabarcığı bulgusuyla tanımak.',
    tags: ['yanik', 'ikinci-derece', 'belirti'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-313',
    subject: 'ilkyardim',
    topic: 'yanik',
    difficulty: 'kolay',
    stem: 'Cilde temizlik maddesi gibi bir kimyasal döküldüğünde (kimyasal yanık) ilk yapılması gereken nedir?',
    options: [
      'Bölgeyi kuru bezle silip kapatmak',
      'Üzerine krem veya merhem sürmek',
      'Bulaşmış giysileri çıkarıp bölgeyi bol akan suyla uzun süre yıkamak',
      'Bölgeyi ovarak kimyasalı yaymak',
    ],
    answerIndex: 2,
    explanation:
      'Kimyasal yanıkta öncelik, maddenin ciltten uzaklaştırılıp seyreltilmesidir; bunun için kimyasal bulaşmış giysiler çıkarılır ve bölge bol akan temiz suyla uzun süre yıkanır. Ardından yara temiz bezle örtülüp sağlık kuruluşuna başvurulur.',
    whyWrong: [
      'Kuru bezle silmek veya krem sürmek kimyasalı ciltte tutarak hasarı artırır.',
      'Bölgeyi ovmak kimyasalı çevre dokulara yayar ve yanığı derinleştirir.',
    ],
    objective: 'Kimyasal cilt yanığında bol su ile yıkama ilkesini kavramak.',
    tags: ['yanik', 'kimyasal', 'yikama'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-314',
    subject: 'ilkyardim',
    topic: 'bilinc-kaybi',
    difficulty: 'orta',
    stem: 'Sara (epilepsi) nöbeti geçiren, kasılıp yere düşen ve titreyen bir kişiye ilk yardımda ne yapılır?',
    options: [
      'Çevredeki tehlikeli cisimleri uzaklaştırıp başını korumak ve nöbetin geçmesini beklemek',
      'Kollarını ve bacaklarını sıkıca tutup kasılmayı zorla durdurmak',
      'Ağzına sert bir cisim veya parmak yerleştirmek',
      'Kişiyi ayağa kaldırıp yürütmeye çalışmak',
    ],
    answerIndex: 0,
    explanation:
      'Nöbet sırasında amaç, kişinin kendine zarar vermesini önlemektir; çevredeki sert ve tehlikeli cisimler uzaklaştırılır, başının altına yumuşak bir şey konularak korunur ve nöbetin kendiliğinden geçmesi beklenir. Nöbet sonrası solunumu varsa koma pozisyonu verilir.',
    whyWrong: [
      'Kişiyi zorla tutmak kas ve eklem yaralanmasına yol açabilir.',
      'Ağza cisim veya parmak sokmak dişlerin kırılmasına, tıkanmaya ve yaralanmaya neden olabilir.',
    ],
    objective: 'Nöbet geçiren kişide güvenliği sağlama ilkesini kavramak.',
    tags: ['bilinc-kaybi', 'nobet', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-315',
    subject: 'ilkyardim',
    topic: 'bilinc-kaybi',
    difficulty: 'kolay',
    stem: 'Şeker hastası olduğu bilinen, açlıkla birlikte terleme ve titreme başlayan ancak bilinci açık ve güvenle yutkunabilen bir kişiye ilk yardım olarak ne verilebilir?',
    options: [
      'Hiçbir şey verilmemeli, hemen yatırılmalı',
      'Bol miktarda tuzlu su',
      'Şekerli bir içecek ya da kolay yutulabilen tatlı bir besin',
      'Soğuk duş aldırılmalı',
    ],
    answerIndex: 2,
    explanation:
      'Bu belirtiler kan şekerinin düşmesini düşündürür; bilinci açık ve güvenle yutkunabilen kişiye şekerli bir içecek veya tatlı bir besin verilerek kan şekerinin yükselmesine yardımcı olunur. Bilinç kapalıysa ağızdan hiçbir şey verilmez ve 112 aranır.',
    whyWrong: [
      'Tuzlu su kan şekerini yükseltmez ve fayda sağlamaz.',
      'Soğuk duş belirtileri gidermez; bilinci kapalı kişiye ağızdan bir şey vermek ise tehlikelidir.',
    ],
    objective: 'Kan şekeri düşüklüğünde bilinci açık kişiye şeker verilebileceğini kavramak.',
    tags: ['bilinc-kaybi', 'kan-sekeri', 'beslenme'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-316',
    subject: 'ilkyardim',
    topic: 'koma-pozisyonu',
    difficulty: 'kolay',
    stem: 'Bilinci kapalı fakat solunumu olan bir yaralıya koma (kurtarma) pozisyonu verilirken temel olarak nasıl yatırılır?',
    options: [
      'Sırtüstü ve düz biçimde',
      'Yan tarafına, başı hafifçe geriye ve yüzü biraz aşağı bakacak şekilde',
      'Yüzükoyun ve kolları altında kalacak biçimde',
      'Oturur konumda başı öne düşmüş hâlde',
    ],
    answerIndex: 1,
    explanation:
      'Koma pozisyonunda yaralı yan tarafına yatırılır; baş hafifçe geriye alınıp yüz biraz aşağı bakacak şekilde konumlandırılır. Böylece dil geriye kaçmaz, ağızdaki salgı ve kusmuk dışarı akarak hava yolu açık kalır.',
    whyWrong: [
      'Sırtüstü düz yatışta dil veya kusmuk hava yolunu tıkayabilir.',
      'Yüzükoyun yatış solunumu zorlaştırır; oturur konum bilinci kapalı yaralı için uygun değildir.',
    ],
    objective: 'Koma pozisyonunda yaralının yan yatırılışını kavramak.',
    tags: ['koma-pozisyonu', 'hava-yolu', 'teknik'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-317',
    subject: 'ilkyardim',
    topic: 'bogulma-tikanma',
    difficulty: 'orta',
    stem: 'Suda boğulma tehlikesi geçiren birine yardım ederken ilk yardımcının öncelikli davranışı ne olmalıdır?',
    options: [
      'Yüzme bilse de bilmese de hemen suya atlamak',
      'Kişiye uzaktan bağırıp beklemek',
      'Önce kendi güvenliğini düşünmek; mümkünse kıyıdan ip, sırık uzatmak veya yüzdürücü bir nesne atmak',
      'Suya taş atarak kişiyi uyarmak',
    ],
    answerIndex: 2,
    explanation:
      'Boğulmakta olan kişi panik hâlinde kurtarıcıyı da suya çekebilir; bu yüzden ilk yardımcı önce kendi güvenliğini sağlar. Mümkünse suya girmeden kıyıdan bir ip, sırık veya yüzdürücü bir cisim uzatılıp atılarak kişi kıyıya çekilmeye çalışılır ve 112 aranır.',
    whyWrong: [
      'Bilinçsizce suya atlamak, ilk yardımcının da boğulmasına yol açabilir.',
      'Yalnızca bağırıp beklemek ya da taş atmak kişiye yardımcı olmaz.',
    ],
    objective: 'Suda boğulmada önce kendi güvenliği ve uzaktan kurtarma ilkesini kavramak.',
    tags: ['bogulma-tikanma', 'su-guvenligi', 'kurtarma'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-318',
    subject: 'ilkyardim',
    topic: 'bogulma-tikanma',
    difficulty: 'kolay',
    stem: 'Bir yaş altı bir bebekte hava yolu yabancı cisimle tıkandığında, erişkindeki karına bası (Heimlich) yerine hangi yöntem uygulanır?',
    options: [
      'Sırtına (kürek kemikleri arasına) vurma ile göğse bası dönüşümlü olarak uygulanır',
      'Bebeğin karnına kuvvetle bastırılır',
      'Bebek ayaklarından tutulup sallanır',
      'Bebeğe bol su içirilir',
    ],
    answerIndex: 0,
    explanation:
      'Bebeklerde karına bası iç organlara zarar verebileceğinden uygulanmaz; bunun yerine bebek yüzüstü kol üzerine alınıp başı gövdesinden aşağıda tutularak sırtına (kürek kemikleri arasına) vurulur ve gerektiğinde göğse bası ile dönüşümlü sürdürülür.',
    whyWrong: [
      'Bebeğin karnına bası uygulamak iç organ yaralanmasına yol açabilir.',
      'Bebeği ayaklarından sallamak veya su içirmek tehlikeli ve etkisizdir.',
    ],
    objective: 'Bebekte hava yolu tıkanıklığında sırt vurusu ve göğse bası yöntemini kavramak.',
    tags: ['bogulma-tikanma', 'bebek', 'hava-yolu'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-319',
    subject: 'ilkyardim',
    topic: 'zehirlenme',
    difficulty: 'kolay',
    stem: 'Ağız yoluyla (yenilerek veya içilerek) zehirlenen bir kişide ilk yardımcının kendiliğinden yapmaması gereken nedir?',
    options: [
      'Kişiyi kendi kararıyla zorla kusturmaya çalışmak',
      'Kişinin bilincini ve solunumunu değerlendirmek',
      '112 Acil Sağlık hattını aramak',
      'Alınan madde ve ambalajı hakkında bilgi toplamak',
    ],
    answerIndex: 0,
    explanation:
      'Bazı maddeler (örneğin aşındırıcı kimyasallar) kusturulduğunda yemek borusuna ve hava yoluna ikinci kez zarar verir. Bu nedenle ilk yardımcı kendi kararıyla kusturmaya çalışmaz; bilinç ile solunumu değerlendirir, madde bilgisini toplar ve 112 hattının yönlendirmesine uyar.',
    whyWrong: [
      'Bilinç ile solunumu değerlendirmek ve 112 hattını aramak doğru ve gerekli adımlardır.',
      'Alınan madde ile ambalajı hakkında bilgi toplamak sağlık ekibine yardımcı olur.',
    ],
    objective: 'Zehirlenmede kendiliğinden kusturmanın sakıncasını kavramak.',
    tags: ['zehirlenme', 'kusturma', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-320',
    subject: 'ilkyardim',
    topic: 'kazazede-tasima',
    difficulty: 'orta',
    stem: 'Yangın gibi hayati bir tehlike nedeniyle bir yaralıyı tek başınıza kısa mesafede güvenli yere çekmeniz gerektiğinde uygun yöntem hangisidir?',
    options: [
      'Yaralıyı tek kolundan tutup yana doğru savurmak',
      'Baş-boyun-gövde ekseni olabildiğince korunacak biçimde, koltuk altından ya da ayak bileklerinden düz çekerek sürüklemek',
      'Yaralıyı sırtına alıp koşmak',
      'Yaralıyı belinden büküp taşımak',
    ],
    answerIndex: 1,
    explanation:
      'Zorunlu ve acil bir tahliyede tek ilk yardımcı, yaralının baş-boyun-gövde eksenini koruyarak koltuk altlarından veya ayak bileklerinden tutup düz bir hat üzerinde sürükleyerek güvenli alana çeker. Amaç, tehlikeden uzaklaştırırken omurgayı olabildiğince az zorlamaktır.',
    whyWrong: [
      'Tek koldan savurmak veya belinden bükmek omurga ve boyun hasarını ağırlaştırır.',
      'Ağır bir yaralıyı sırta alıp koşmak hem yaralıyı hem ilk yardımcıyı tehlikeye atar.',
    ],
    objective: 'Zorunlu tahliyede eksen koruyarak sürükleme yöntemini kavramak.',
    tags: ['kazazede-tasima', 'surukleme', 'omurga'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-321',
    subject: 'ilkyardim',
    topic: 'donma-sicak-carpmasi',
    difficulty: 'orta',
    stem: 'Sıcak ve güneşli ortamda uzun süre kaldıktan sonra cildi sıcak-kuru ve kızarık olan, başı dönen ve bilinci bulanıklaşan bir kişide (sıcak/güneş çarpması) ilk yardım olarak ne yapılır?',
    options: [
      'Kişi sıcakta tutulup üzeri kalın örtüyle örtülür',
      'Kişiye ağır egzersiz yaptırılır',
      'Kişi serin ve gölge bir yere alınıp giysileri gevşetilir, vücudu ılık-serin suyla veya ıslak bezle soğutulur ve 112 aranır',
      'Kişiye sıcak içecekler içirilir',
    ],
    answerIndex: 2,
    explanation:
      'Sıcak çarpmasında vücut ısısı tehlikeli biçimde yükselir; kişi hemen serin ve gölge bir yere alınır, sıkan giysileri gevşetilir ve vücudu ılık-serin suyla ya da ıslak bezlerle soğutulur. Bilinci açıksa su verilebilir; durum ciddi olduğundan 112 aranır.',
    whyWrong: [
      'Kişiyi sıcakta tutmak, kalın örtüyle örtmek veya sıcak içecek vermek vücut ısısını daha da yükseltir.',
      'Ağır egzersiz, zaten aşırı ısınmış vücudu daha da zorlar.',
    ],
    objective: 'Sıcak çarpmasında serinletme ve soğutma ilkesini kavramak.',
    tags: ['donma-sicak-carpmasi', 'sicak-carpmasi', 'sogutma'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-322',
    subject: 'ilkyardim',
    topic: 'kalp-krizi',
    difficulty: 'zor',
    stem: 'Kalp krizi geçirdiğinden şüphelenilen bir kişinin bilinci kapanır ve solunumu durursa ilk yardımcı ne yapmalıdır?',
    options: [
      'Derhal temel yaşam desteğine (göğüs basısına) başlamak ve 112 ile iletişimi sürdürmek',
      'Kişiyi oturtup su içirmeye çalışmak',
      'Ağrı geçene kadar beklemek',
      'Kişiyi ayağa kaldırıp yürütmek',
    ],
    answerIndex: 0,
    explanation:
      'Kalp krizi, kalbin tümüyle durmasına (kalp durması) ilerleyebilir. Bilinç kapanır ve solunum durursa vakit kaybetmeden temel yaşam desteğine başlanır; göğüs basıları uygulanır ve 112 çağrısı sürdürülür. Erken başlanan kalp masajı yaşam şansını artırır.',
    whyWrong: [
      'Solunumu durmuş kişiye su içirmeye çalışmak ya da onu yürütmek hayati zaman kaybettirir.',
      'Ağrının geçmesini beklemek, kalp durmasında geri dönüşü zorlaştırır.',
    ],
    objective: 'Kalp krizinin kalp durmasına ilerlediğinde temel yaşam desteğine geçmeyi kavramak.',
    tags: ['kalp-krizi', 'temel-yasam-destegi', 'acil'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
];
