/**
 * ÖZGÜN trafik ve çevre soruları — 4. genişletme (Program 2 · Faz 9). ROADMAP C.4/E.6.
 * Kaynak = resmî müfredat/mevzuat; KENDİ İFADEMİZLE.
 */
import type { QuestionInput } from '@ea/content-schema';

const SRC = 'Karayolları Trafik Yönetmeliği + MEB müfredatı (özgün ifade)';

export const TRAFIK_QUESTIONS_4: QuestionInput[] = [
  {
    id: 'trafik-401',
    subject: 'trafik',
    topic: 'serit-disiplini',
    difficulty: 'kolay',
    stem: 'Yerleşim yeri dışında, aynı yönde birden fazla şeridi olan bir yolda sürücü hangi şeridi izlemelidir?',
    options: [
      'Yol boş olduğu sürece en sol şeridi',
      'Dilediği herhangi bir şeridi',
      'Gidişe ayrılan en sağdaki şeridi; sol şeritleri geçişlerde',
      'Sürekli orta şeridi',
    ],
    answerIndex: 2,
    explanation:
      'Şerit disiplininin temeli sağdan seyretmektir: yerleşim yeri dışında araçlar gidişe ayrılan en sağ şeridi izler, soldaki şeritler ise geçiş (sollama) gibi manevralar için kullanılır.',
    whyWrong: [
      'Sol şeridi sürekli işgal etmek geçiş yapacak araçları engeller ve kural ihlalidir.',
      'Şerit seçimi keyfe bağlı değildir; sağ şerit esas, sol şeritler manevra içindir.',
      'Orta şeridi gerekçesiz biçimde sürekli kullanmak da sağdan seyretme kuralına aykırıdır.',
    ],
    objective: 'Sağ şeridin esas seyir şeridi olduğunu kavramak.',
    tags: ['serit-kullanimi', 'sag-serit', 'yerlesim-disi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-402',
    subject: 'trafik',
    topic: 'serit-disiplini',
    difficulty: 'orta',
    stem: 'Bir sürücünün aracını şerit çizgisinin üzerinde sürerek iki şeridi birden kullanması nasıl değerlendirilir?',
    options: [
      'Şerit ihlalidir ve yasaktır',
      'Yol boşsa serbesttir',
      'Yalnızca gece yasaktır',
      'Geniş araçlar için normal kabul edilir',
    ],
    answerIndex: 0,
    explanation:
      'Her araç tek bir şerit içinde seyretmek zorundadır. Çizgi üzerinde giderek iki şeridi birden işgal etmek hem diğer araçların hareketini kısıtlar hem de şerit ihlali olarak cezalandırılır.',
    whyWrong: [
      'Yolun boş olması kuralı ortadan kaldırmaz; şerit düzeni her koşulda geçerlidir.',
      'Kural gece-gündüz ayrımı yapmaz.',
      'Genişliği ne olursa olsun araç, işaretlenmiş tek şerit içinde kalmalıdır.',
    ],
    objective: 'Tek şerit içinde seyretme zorunluluğunu bilmek.',
    tags: ['serit-kullanimi', 'serit-ihlali'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-403',
    subject: 'trafik',
    topic: 'serit-disiplini',
    difficulty: 'orta',
    stem: 'Yoğun trafikte araçların arasından sık sık şerit değiştirerek (slalom yaparak) ilerleyen sürücü için ne söylenebilir?',
    options: [
      'Trafiği hızlandırdığı için yararlıdır',
      'Deneyimli sürücüler için sakıncasızdır',
      'Sadece otoyolda sakıncalıdır',
      'Kural ihlalidir; kaza riskini ciddi biçimde artırır',
    ],
    answerIndex: 3,
    explanation:
      'Trafiği tehlikeye düşürecek şekilde art arda şerit değiştirmek yasaktır. Bu davranış diğer sürücülerin öngöremeyeceği ani manevralar yarattığı için zincirleme kazalara zemin hazırlar.',
    whyWrong: [
      'Slalom trafiği hızlandırmaz; akışı bozar ve ani fren zincirine yol açar.',
      'Deneyim, kuralları esnetme hakkı vermez.',
      'Bu davranış yalnızca otoyolda değil, her yolda tehlikeli ve yasaktır.',
    ],
    objective: 'Gereksiz ve art arda şerit değiştirmenin ihlal olduğunu kavramak.',
    tags: ['serit-kullanimi', 'agresif-surus', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-404',
    subject: 'trafik',
    topic: 'serit-disiplini',
    difficulty: 'kolay',
    stem: 'Öndeki aracı geçme (sollama) manevrası tamamlandığında sürücü ne yapmalıdır?',
    options: [
      'Sol şeritte seyrine devam etmelidir',
      'Geçtiği aracı güvenli mesafede geride bıraktıktan sonra sinyal vererek sağ şeride dönmelidir',
      'Frene basarak geçtiği aracın önünde yavaşlamalıdır',
      'Sinyal vermeden hızla sağ şeride girmelidir',
    ],
    answerIndex: 1,
    explanation:
      'Geçiş, sağ şeride güvenle dönülünce tamamlanmış sayılır. Sürücü geçtiği aracı aynadan görecek kadar mesafe bıraktıktan sonra sağ sinyalini yakar ve seyir şeridine döner.',
    whyWrong: [
      'Sol şeritte kalmak geçiş şeridini gereksiz işgal etmektir.',
      'Geçilen aracın önüne girip yavaşlamak arkadan çarpma riski doğurur.',
      'Sinyalsiz ve ani şerit dönüşü diğer sürücüleri hazırlıksız yakalar.',
    ],
    objective: 'Sollamanın sağ şeride güvenli dönüşle tamamlandığını bilmek.',
    tags: ['sollama', 'serit-kullanimi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-405',
    subject: 'trafik',
    topic: 'serit-disiplini',
    difficulty: 'zor',
    stem: 'İki yönlü bir yolun ortasında biri devamlı, biri kesik olmak üzere yan yana iki çizgi vardır. Hangi sürücü öndeki aracı geçmek için karşı şeridi kullanabilir?',
    options: [
      'Devamlı çizgi kendi tarafında olan sürücü',
      'Her iki yöndeki sürücüler de',
      'Kesik çizgi kendi tarafında olan sürücü',
      'Hiçbir yöndeki sürücü',
    ],
    answerIndex: 2,
    explanation:
      'Yan yana çizilmiş çift çizgide her sürücü kendi tarafındaki çizgiye uyar: kesik çizgi tarafındaki sürücü güvenliyse karşı şeridi kullanıp geçebilir, devamlı çizgi tarafındaki sürücü ise çizgiyi aşamaz.',
    whyWrong: [
      'Devamlı çizgi kendi tarafında olan sürücü için çizgiyi aşmak yasaktır.',
      'İki yön için aynı anda serbestlik yoktur; çizgiler yönlere göre ayrı hüküm taşır.',
      'Kesik çizgi tarafındaki sürücüye geçiş izni verildiği için “hiçbiri” yanlıştır.',
    ],
    objective: 'Karma (devamlı + kesik) çizgi kombinasyonunun yönlere göre okunmasını öğrenmek.',
    tags: ['yol-cizgileri', 'sollama', 'serit-kullanimi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-406',
    subject: 'trafik',
    topic: 'yol-kavramlari',
    difficulty: 'orta',
    stem: 'Trafik mevzuatındaki tanıma göre "geçiş yolu" aşağıdakilerden hangisidir?',
    options: [
      'İki şehri birbirine bağlayan ana yol',
      'Araçların bir mülke (bina, arsa, tesis) girip çıkması için yapılmış yol bölümü',
      'Yayaların karşıya geçmesi için ayrılmış alan',
      'Otoyolun hizmet tesislerine ayrılan bölümü',
    ],
    answerIndex: 1,
    explanation:
      'Geçiş yolu, taşıtların karayolundan ayrılıp bir mülke girmesine ya da mülkten çıkıp karayoluna katılmasına yarayan bağlantı bölümüdür; bu tanım park yasakları gibi kuralların da dayanağıdır.',
    whyWrong: [
      'Şehirleri bağlayan yollar devlet yolu/ana yol kavramlarına girer.',
      'Yayalara ayrılan alan yaya geçididir.',
      'Otoyol hizmet tesislerinin bağlantıları ayrı bir kavramdır; mülk girişini anlatmaz.',
    ],
    objective: 'Geçiş yolu kavramını doğru tanımlamak.',
    tags: ['tanimlar', 'gecis-yolu'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-407',
    subject: 'trafik',
    topic: 'yol-kavramlari',
    difficulty: 'orta',
    stem: 'Bir kavşak ya da karayolunu başka bir karayoluna bağlayan, giriş-çıkış hareketlerinin yapıldığı yol bölümüne ne ad verilir?',
    options: ['Bağlantı yolu', 'Banket', 'Yaya yolu', 'Ada'],
    answerIndex: 0,
    explanation:
      'Bağlantı yolu, bir karayolunu diğerine bağlayarak araçların yol değiştirmesine imkân veren bölümdür; kavşak kolları ve otoyol giriş-çıkış rampaları bu kapsamdadır.',
    whyWrong: [
      'Banket, taşıt yolunun kenarındaki yumuşak zeminli emniyet bölümüdür.',
      'Yaya yolu yayaların kullanımına ayrılmıştır; araç bağlantısı sağlamaz.',
      'Ada, taşıt akımlarını ayırmak için yükseltilmiş veya çizilmiş alandır.',
    ],
    objective: 'Bağlantı yolu kavramını banket, ada gibi kavramlardan ayırt etmek.',
    tags: ['tanimlar', 'baglanti-yolu'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-408',
    subject: 'trafik',
    topic: 'yol-kavramlari',
    difficulty: 'orta',
    stem: 'Bir apartmanın otopark girişinin (geçiş yolunun) önüne veya üzerine park etmek isteyen sürücü için kural nedir?',
    options: [
      'Kısa süreli olması şartıyla serbesttir',
      'Sadece gece yasaktır',
      'Dörtlü ikaz yakılırsa serbesttir',
      'Yasaktır; geçiş yollarının önü ve üzeri park edilemeyen yerlerdendir',
    ],
    answerIndex: 3,
    explanation:
      'Geçiş yolları, mülke giriş-çıkışın tek noktasıdır; önüne veya üzerine park eden araç bu hakkı tamamen engeller. Bu nedenle geçiş yollarının önü ve üzeri park yasağı kapsamındadır.',
    whyWrong: [
      'Sürenin kısalığı engellemeyi ortadan kaldırmaz; yasak süreye bağlı değildir.',
      'Yasak gündüz de geçerlidir.',
      'Dörtlü ikaz yakmak, yasak yere park etmeyi kurallara uygun hâle getirmez.',
    ],
    objective: 'Geçiş yolu önünde park yasağını bilmek.',
    tags: ['park-yasagi', 'gecis-yolu'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-409',
    subject: 'trafik',
    topic: 'arac-isiklari',
    difficulty: 'kolay',
    stem: 'Dönüş (sinyal) lambası ne zaman söndürülmelidir?',
    options: [
      'Manevraya başlar başlamaz',
      'Bir sonraki kavşağa gelince',
      'Dönüş veya şerit değiştirme manevrası tamamlanınca',
      'Yaklaşık bir dakika sonra kendiliğinden sönmesi beklenir',
    ],
    answerIndex: 2,
    explanation:
      'Sinyal, manevra süresince niyeti bildirir; manevra bitince söndürülür. Açık unutulan sinyal diğer sürücülere yanlış bilgi verir ve kavşaklarda tehlikeli yanılgılara yol açar.',
    whyWrong: [
      'Manevra başında söndürülen sinyal, manevranın devamını bildirmez.',
      'Sonraki kavşağa kadar açık kalan sinyal yanlış dönüş beklentisi oluşturur.',
      'Sinyali izlemek ve kapatmak sürücünün sorumluluğudur; kendiliğinden sönmesine güvenilmez.',
    ],
    objective: 'Sinyalin manevra süresiyle sınırlı kullanılacağını bilmek.',
    tags: ['sinyal', 'isik-kullanimi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-410',
    subject: 'trafik',
    topic: 'arac-isiklari',
    difficulty: 'orta',
    stem: 'Gece, öndeki bir aracı yakın mesafeden takip eden sürücü hangi farları kullanmalıdır?',
    options: [
      'Uzağı gösteren (uzun huzmeli) farları',
      'Sis farlarını',
      'Yalnızca park lambalarını',
      'Yakını gösteren (kısa huzmeli) farları',
    ],
    answerIndex: 3,
    explanation:
      'Uzun huzme, öndeki aracın iç ve yan aynalarından yansıyarak sürücüsünü kamaştırır. Bu nedenle bir aracı takip ederken kısa huzmeli farlar kullanılır.',
    whyWrong: [
      'Uzun far takip sırasında öndeki sürücüyü aynalardan kamaştırır.',
      'Sis farları yalnızca sis, kar, sağanak gibi görüşü azaltan hava koşullarında kullanılır.',
      'Sadece park lambalarıyla seyretmek yetersizdir ve yasaktır.',
    ],
    objective: 'Takip hâlinde kısa huzme kullanma kuralını bilmek.',
    tags: ['far-kullanimi', 'gece-surusu'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-411',
    subject: 'trafik',
    topic: 'arac-isiklari',
    difficulty: 'orta',
    stem: 'Gündüz vakti yoğun kar yağışı görüşü belirgin biçimde azaltıyorsa sürücü ışıklar konusunda ne yapmalıdır?',
    options: [
      'Gündüz de olsa yakını gösteren farlarını yakmalıdır',
      'Gündüz olduğu için hiçbir ışık yakmamalıdır',
      'Yalnızca dörtlü ikaz ışıklarını yakıp seyrine devam etmelidir',
      'Uzağı gösteren farları sürekli açık tutmalıdır',
    ],
    answerIndex: 0,
    explanation:
      'Görüşü azaltan sis, kar, sağanak gibi koşullarda gündüz dahi kısa huzmeli farların yakılması gerekir; amaç yolu görmek kadar aracın diğer sürücülerce fark edilmesini sağlamaktır.',
    whyWrong: [
      'Işıksız araç, görüşün düştüğü ortamda diğer sürücüler için görünmez hâle gelir.',
      'Dörtlü ikaz seyir hâlinde kullanılmaz; arıza ve zorunlu durumların işaretidir.',
      'Uzun huzme yağışta yansıyıp görüşü daha da bozar.',
    ],
    objective: 'Görüşü azaltan hava koşullarında gündüz far yakma zorunluluğunu bilmek.',
    tags: ['far-kullanimi', 'kotu-hava', 'gorus'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-412',
    subject: 'trafik',
    topic: 'arac-isiklari',
    difficulty: 'kolay',
    stem: 'Dörtlü ikaz (acil uyarı) ışıkları hangi durumda kullanılır?',
    options: [
      'Yağmurlu havada seyir hâlindeyken',
      'Kavşaktan düz geçileceğini bildirmek için',
      'Yasak yere kısa süreli park ederken',
      'Arıza, kaza gibi nedenlerle aracın diğer trafik için tehlike oluşturduğu durumlarda',
    ],
    answerIndex: 3,
    explanation:
      'Dörtlü ikaz, aracın zorunlu nedenlerle yol üzerinde kaldığını ve tehlike oluşturduğunu bildirir. Arıza, kaza veya mecburi duraklamada yakılır; olağan seyirde kullanılmaz.',
    whyWrong: [
      'Yağmurda seyir hâlinde dörtlü yakmak sinyal görünürlüğünü yok eder ve yanıltıcıdır.',
      'Düz geçiş için herhangi bir ikaz ışığı öngörülmemiştir.',
      'Dörtlü ikaz, yasak yere park etmeye meşruluk kazandırmaz.',
    ],
    objective: 'Acil uyarı ışıklarının yalnızca tehlike bildirimi için olduğunu kavramak.',
    tags: ['dortlu-ikaz', 'isik-kullanimi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-413',
    subject: 'trafik',
    topic: 'arac-isiklari',
    difficulty: 'orta',
    stem: 'Gece karanlık bir yolda yalnızca park lambaları yanar durumda seyretmek için ne söylenebilir?',
    options: [
      'Şehir içinde yeterlidir',
      'Yasaktır; park lambaları seyir aydınlatması değildir',
      'Yakıt tasarrufu sağladığı için önerilir',
      'Kısa mesafelerde sakıncası yoktur',
    ],
    answerIndex: 1,
    explanation:
      'Park lambaları aracın yalnızca yerini belli etmek içindir; yolu aydınlatmaz ve yeterli görünürlük sağlamaz. Gece seyirde kısa veya (uygun koşullarda) uzun huzmeli farlar kullanılmalıdır.',
    whyWrong: [
      'Şehir içinde de seyir için en az kısa huzmeli far gerekir.',
      'Lamba seçimi yakıt ekonomisiyle değil, güvenli görüş kuralıyla belirlenir.',
      'Kısa mesafe de olsa yetersiz aydınlatma çarpışma riski doğurur.',
    ],
    objective: 'Park lambalarıyla seyretmenin yasak olduğunu bilmek.',
    tags: ['far-kullanimi', 'gece-surusu', 'park-lambasi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-414',
    subject: 'trafik',
    topic: 'arac-isiklari',
    difficulty: 'kolay',
    stem: 'Bir aracın arkasında yanan beyaz geri vites lambası çevredeki sürücülere ne anlatır?',
    options: [
      'Aracın geri manevraya başladığını veya başlayacağını',
      'Aracın fren yaptığını',
      'Aracın arızalı olduğunu',
      'Aracın sola döneceğini',
    ],
    answerIndex: 0,
    explanation:
      'Geri vitese takıldığında yanan beyaz lamba, aracın geriye hareket edeceği konusunda arkadaki sürücüleri ve yayaları uyarır; bu araca yaklaşırken ekstra dikkat gerekir.',
    whyWrong: [
      'Fren, kırmızı fren lambalarıyla bildirilir.',
      'Arıza dörtlü ikaz ışıklarıyla bildirilir.',
      'Dönüşler turuncu sinyal lambalarıyla bildirilir.',
    ],
    objective: 'Geri vites lambasının anlamını bilmek.',
    tags: ['gerivites-lambasi', 'isik-anlamlari'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-415',
    subject: 'trafik',
    topic: 'duraklama-park-mesafeleri',
    difficulty: 'kolay',
    stem: 'Kavşaklara ve yaya geçitlerine en fazla kaç metre mesafe içinde duraklamak yasaktır?',
    options: ['3 metre', '10 metre', '5 metre', '20 metre'],
    answerIndex: 2,
    explanation:
      'Kavşaklar ile yaya ve okul geçitlerine 5 metre mesafe içinde duraklamak yasaktır; bu bölgede duran araç görüşü kapatarak hem yayaları hem dönen araçları tehlikeye atar.',
    whyWrong: [
      '3 metre kuraldaki değerden azdır; yasak alanın tamamını kapsamaz.',
      '10 ve 20 metre kuralda geçen mesafeler değildir; kural 5 metredir.',
    ],
    objective: 'Kavşak ve geçitlere 5 metre duraklama yasağını ezberlemek.',
    tags: ['duraklama-yasagi', 'kavsak', 'mesafe-kurali'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-416',
    subject: 'trafik',
    topic: 'duraklama-park-mesafeleri',
    difficulty: 'kolay',
    stem: 'Otobüs, tramvay ve taksi duraklarına en fazla kaç metre mesafe içinde duraklamak yasaktır?',
    options: ['5 metre', '10 metre', '15 metre', '25 metre'],
    answerIndex: 2,
    explanation:
      'Duraklara 15 metre mesafe içinde duraklamak yasaktır; bu alan toplu taşıma araçlarının yanaşması ve yolcu indirip bindirmesi için boş kalmalıdır.',
    whyWrong: [
      '5 metre kavşak ve yaya geçitleri için geçerli mesafedir.',
      '10 ve 25 metre mevzuattaki durak mesafesi değildir.',
    ],
    objective: 'Duraklara 15 metre duraklama yasağını bilmek.',
    tags: ['duraklama-yasagi', 'durak', 'mesafe-kurali'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-417',
    subject: 'trafik',
    topic: 'duraklama-park-mesafeleri',
    difficulty: 'orta',
    stem: 'Yangın musluklarına (hidrantlara) hangi mesafe içinde park etmek yasaktır?',
    options: ['1 metre', '2 metre', '3 metre', '5 metre'],
    answerIndex: 3,
    explanation:
      'Yangın musluklarına 5 metre mesafe içinde park etmek yasaktır; itfaiyenin acil durumda hidranta engelsiz ulaşabilmesi bu boşluğa bağlıdır.',
    whyWrong: [
      '1 ve 2 metre, itfaiye aracının hidranta yanaşıp hortum bağlaması için yeterli alan bırakmaz.',
      '3 metre de kuraldaki değer değildir; mevzuat 5 metrelik boşluk ister.',
    ],
    objective: 'Yangın musluğu çevresindeki park yasağı mesafesini bilmek.',
    tags: ['park-yasagi', 'yangin-muslugu', 'mesafe-kurali'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-418',
    subject: 'trafik',
    topic: 'duraklama-park-mesafeleri',
    difficulty: 'zor',
    stem: 'Duraklamanın yasak olduğu bir yerde park etmek isteyen sürücü için ne söylenebilir?',
    options: [
      'Duraklama yasağı parkı kapsamaz; park edebilir',
      'Sürücü araçta kalırsa park edebilir',
      'Yarım saati geçmemek şartıyla park edebilir',
      'Park edemez; duraklamanın yasak olduğu her yerde park da yasaktır',
    ],
    answerIndex: 3,
    explanation:
      'Park, duraklamadan daha uzun süreli bir bırakmadır. Kısa süreli durmanın bile yasaklandığı bir yerde aracın daha uzun süre bırakılması öncelikle yasaktır; park yasakları duraklama yasaklarını kapsar.',
    whyWrong: [
      'Mantık terstir: daha hafif eylem (duraklama) yasaksa daha ağırı (park) da yasaktır.',
      'Sürücünün araçta kalması, yasak yerdeki bekleyişi kurallara uygun yapmaz.',
      'Yasak süre koşuluna bağlanmamıştır; yarım saat sınırı diye bir istisna yoktur.',
    ],
    objective: 'Duraklama yasağı ile park yasağı arasındaki kapsama ilişkisini kavramak.',
    tags: ['duraklama-yasagi', 'park-yasagi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-419',
    subject: 'trafik',
    topic: 'okul-tasiti',
    difficulty: 'kolay',
    stem: 'Önünüzdeki okul taşıtı durmuş ve arkasındaki kırmızı DUR ışığını yakmıştır. Ne yapmalısınız?',
    options: [
      'Korna çalarak yavaşça yanından geçersiniz',
      'Hızlanıp beklemeden geçersiniz',
      'Işık sönene kadar durup beklersiniz',
      'Sol şeride geçip normal hızla devam edersiniz',
    ],
    answerIndex: 2,
    explanation:
      'DUR ışığı yanan okul taşıtı öğrenci indirip bindiriyordur. Arkadan gelen sürücüler ışık sönünceye kadar durup beklemek zorundadır; çocuklar aniden yola çıkabilir.',
    whyWrong: [
      'Korna çalmak geçme yasağını kaldırmaz, üstelik çocukları ürkütebilir.',
      'Beklemeden geçmek indirme-bindirme sırasındaki çocuklar için ölümcül risktir.',
      'Şerit değiştirerek geçmek de aynı yasağın ihlalidir.',
    ],
    objective: 'DUR ışığı yanan okul taşıtının geçilemeyeceğini bilmek.',
    tags: ['okul-tasiti', 'dur-isigi', 'cocuk-guvenligi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-420',
    subject: 'trafik',
    topic: 'okul-tasiti',
    difficulty: 'kolay',
    stem: 'Okul taşıtı sürücüsü aracın DUR ışığını hangi durumda yakabilir?',
    options: [
      'Yalnızca öğrenci indirip bindirdiği sırada',
      'Yoğun trafikte yol istemek için',
      'Kavşaklarda geçiş önceliği almak için',
      'Servis güzergâhı boyunca sürekli',
    ],
    answerIndex: 0,
    explanation:
      'DUR ışığının anlamı nettir: araç durmuş, öğrenciler iniyor veya biniyor. Bu ışığın başka amaçla yakılması diğer sürücülerde güven kaybı yaratır ve kural ihlalidir.',
    whyWrong: [
      'DUR ışığı yol isteme aracı değildir; amaç dışı kullanımı yasaktır.',
      'Okul taşıtının kavşaklarda geçiş önceliği yoktur.',
      'Sürekli yanan ışık gerçek indirme-bindirme anını anlamsızlaştırır.',
    ],
    objective: 'Okul taşıtı DUR ışığının kullanım koşulunu bilmek.',
    tags: ['okul-tasiti', 'dur-isigi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-421',
    subject: 'trafik',
    topic: 'okul-tasiti',
    difficulty: 'orta',
    stem: 'Bölünmemiş iki yönlü bir yolda, karşı yönden gelen okul taşıtı durmuş ve DUR ışığını yakmıştır. Karşı yönden yaklaşan sürücü ne yapmalıdır?',
    options: [
      'Kendi şeridi ayrı olduğu için normal hızla devam etmelidir',
      'Selektör yapıp geçmelidir',
      'Sadece hızını biraz azaltmalıdır',
      'O da durup indirme-bindirme bitene kadar beklemelidir',
    ],
    answerIndex: 3,
    explanation:
      'Bölünmemiş yolda inen öğrenciler yolun karşısına da geçebilir. Bu nedenle DUR ışığı yanan okul taşıtının hizasına gelen karşı yön sürücüsü de durup beklemelidir.',
    whyWrong: [
      'Bölünmemiş yolda “ayrı şerit” koruması yoktur; çocuk her iki yöne çıkabilir.',
      'Selektör bir geçiş hakkı doğurmaz.',
      'Yavaşlamak yeterli değildir; kural durmayı gerektirir.',
    ],
    objective: 'Bölünmemiş yolda okul taşıtı kuralının iki yönü de bağladığını kavramak.',
    tags: ['okul-tasiti', 'cocuk-guvenligi', 'iki-yonlu-yol'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-422',
    subject: 'trafik',
    topic: 'hemzemin-gecit',
    difficulty: 'kolay',
    stem: 'Demiryolu ile karayolunun aynı seviyede kesiştiği hemzemin geçitte geçiş üstünlüğü kime aittir?',
    options: [
      'İlk gelen karayolu aracına',
      'Demiryolu aracına (trene)',
      'Ağır tonajlı karayolu aracına',
      'Toplu taşıma araçlarına',
    ],
    answerIndex: 1,
    explanation:
      'Tren ne yavaşlayabilir ne de yön değiştirebilir; fren mesafesi yüzlerce metredir. Bu nedenle hemzemin geçitlerde geçiş üstünlüğü her zaman demiryolu aracınındır.',
    whyWrong: [
      'İlk gelme kuralı karayolu kavşakları içindir; raylı araca karşı geçerli değildir.',
      'Tonaj, trene karşı öncelik doğurmaz.',
      'Toplu taşıma araçları da geçitte trene yol vermek zorundadır.',
    ],
    objective: 'Hemzemin geçitte mutlak önceliğin trende olduğunu bilmek.',
    tags: ['hemzemin-gecit', 'gecis-ustunlugu', 'tren'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-423',
    subject: 'trafik',
    topic: 'hemzemin-gecit',
    difficulty: 'zor',
    stem: 'Hemzemin geçidin karşı tarafında trafik durmuş, ilerleme imkânı yoktur. Geçide yaklaşan sürücü ne yapmalıdır?',
    options: [
      'Geçidin öncesinde durmalı; rayların üzerinde kalma ihtimali varsa geçide hiç girmemelidir',
      'Geçide girip sıranın açılmasını rayların üzerinde beklemelidir',
      'Karşı şeridi kullanarak kuyruğun önüne geçmelidir',
      'Korna çalarak öndeki araçları ilerlemeye zorlamalıdır',
    ],
    answerIndex: 0,
    explanation:
      'Hemzemin geçit ancak tek hamlede, duraksamadan geçilebilecekse geçilir. Karşı taraf tıkalıyken geçide giren araç raylar üzerinde mahsur kalabilir; bu, tren kazalarının en ölümcül senaryosudur.',
    whyWrong: [
      'Raylar üzerinde beklemek, gelen trene karşı kaçış imkânı bırakmaz.',
      'Karşı şeridi kullanmak hem sollama yasağını ihlal eder hem de tehlikeyi büyütür.',
      'Korna, öndeki tıkanıklığı çözmez; sorumluluk geçide girmeme kararındadır.',
    ],
    objective: 'Geçide ancak kesintisiz geçiş mümkünse girilebileceğini kavramak.',
    tags: ['hemzemin-gecit', 'guvenlik', 'tikanik-trafik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-424',
    subject: 'trafik',
    topic: 'tunel-kurallari',
    difficulty: 'orta',
    stem: 'Tünel içinde seyreden sürücü, takip mesafesi konusunda nasıl davranmalıdır?',
    options: [
      'Tünelde mesafe kuralı uygulanmaz',
      'Öndeki araca açık yoldakinden daha fazla mesafe bırakmalıdır',
      'Öndeki araca iyice yaklaşarak konvoy düzeni kurmalıdır',
      'Mesafeyi yalnızca çıkışa yaklaşırken artırmalıdır',
    ],
    answerIndex: 1,
    explanation:
      'Tünelde kaçış alanı yoktur, görüş kısıtlıdır ve olası bir kaza zincirleme büyür. Bu yüzden tünelde takip mesafesi açık yoldakine göre artırılmalıdır.',
    whyWrong: [
      'Mesafe kuralı tünelde ortadan kalkmaz; tersine önemi artar.',
      'Yakın takip, tünel içindeki ani duruşlarda zincirleme kazaya yol açar.',
      'Mesafe tünel boyunca korunmalıdır, yalnız çıkışta değil.',
    ],
    objective: 'Tünelde takip mesafesinin artırılması gerektiğini bilmek.',
    tags: ['tunel', 'takip-mesafesi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-425',
    subject: 'trafik',
    topic: 'tunel-kurallari',
    difficulty: 'orta',
    stem: 'Tünel içinde aracı arızalanan sürücünün öncelikli davranışı ne olmalıdır?',
    options: [
      'Aracın içinde oturup trafiğin açılmasını beklemek',
      'Dörtlü ikazı yakıp aracı mümkünse cebe veya en sağa çekmek, sonra yardım istemek',
      'Aracı şeridin ortasında bırakıp tünel dışına yürümek',
      'Geri geri sürerek tünelden çıkmaya çalışmak',
    ],
    answerIndex: 1,
    explanation:
      'Tünelde arızada sıra bellidir: dörtlü ikaz yakılır, araç mümkünse acil durum cebine veya en sağa alınır, motor durdurulur ve acil telefonla ya da 112 ile yardım istenir.',
    whyWrong: [
      'Araç içinde beklemek, arkadan çarpma ve olası yangın-duman riskine açıktır.',
      'Şerit ortasında ikazsız bırakılan araç arkadan gelenler için tuzaktır.',
      'Tünelde geri gitmek kesinlikle yasaktır ve çok tehlikelidir.',
    ],
    objective: 'Tünel içi arıza prosedürünü öğrenmek.',
    tags: ['tunel', 'ariza', 'acil-durum'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-426',
    subject: 'trafik',
    topic: 'cekme-kurallari',
    difficulty: 'zor',
    stem: 'Freni bozulmuş bir otomobil başka bir araçla çekilecekse hangi kurala uyulmalıdır?',
    options: [
      'Halatla bağlanmalı ve normal hızda çekilmelidir',
      'Zincirle bağlanıp yalnızca gece çekilmelidir',
      'Freni bozuk araç hiçbir şekilde çekilemez, yerinde onarılır',
      'Çeki demiri gibi sert bağlantıyla bağlanmalı ve saatte 15 kilometreyi aşmayan hızla çekilmelidir',
    ],
    answerIndex: 3,
    explanation:
      'Freni çalışmayan araç, halatla çekilirse çeken araca çarpar. Bu nedenle sert bağlantı (çeki demiri) zorunludur ve çekiş hızı saatte 15 kilometreyi geçemez.',
    whyWrong: [
      'Halat esnektir; frenleyemeyen aracı tutamaz.',
      'Gece-gündüz ayrımı diye bir kural yoktur; belirleyici olan bağlantı türü ve hızdır.',
      'Kurallara uygun sert bağlantıyla çekilmesi mümkündür; mutlak yasak yoktur.',
    ],
    objective: 'Freni bozuk aracın çekilme koşullarını (çeki demiri + düşük hız) bilmek.',
    tags: ['cekme', 'ariza', 'ceki-demiri'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-427',
    subject: 'trafik',
    topic: 'cekme-kurallari',
    difficulty: 'zor',
    stem: 'Bir aracı halatla çekerken iki araç arasındaki bağlantı için hangi kural geçerlidir?',
    options: [
      'Bağlantı uzunluğu 5 metreyi geçemez; 2,5 metreden uzunsa üzerine kırmızı bez veya yansıtıcı takılır',
      'Bağlantı en az 10 metre olmalıdır',
      'Bağlantı uzunluğu için bir sınır yoktur',
      'Bağlantıya yalnızca beyaz bez bağlanır',
    ],
    answerIndex: 0,
    explanation:
      'Çeken ve çekilen araç arasındaki açıklık en fazla 5 metre olabilir; bağlantı 2,5 metreden uzunsa diğer sürücülerin fark etmesi için üzerine kırmızı bez veya yansıtıcı konur.',
    whyWrong: [
      '10 metre ve üzeri bağlantı kontrolü imkânsız hâle getirir; kural tam tersidir.',
      'Sınırsız uzunluk, araya başka araç girmesi gibi ciddi tehlikeler doğurur.',
      'Uyarı gereci kırmızı renklidir; beyaz bez görünürlük sağlamaz.',
    ],
    objective: 'Çekme bağlantısının uzunluk ve işaretleme kurallarını bilmek.',
    tags: ['cekme', 'baglanti', 'isaretleme'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-428',
    subject: 'trafik',
    topic: 'cekme-kurallari',
    difficulty: 'orta',
    stem: 'Halat veya çeki demiriyle çekilmekte olan araçta kimler bulunabilir?',
    options: [
      'Tüm aile üyeleri',
      'En fazla iki yolcu',
      'Yalnızca direksiyon hâkimiyetini sağlayacak sürücü',
      'Hiç kimse; araç boş çekilir',
    ],
    answerIndex: 2,
    explanation:
      'Çekilen araçta direksiyonu ve frenleri kontrol edecek bir sürücü bulunmalıdır; ancak yolcu taşımak yasaktır, çünkü çekilen araç kaza anında korumasızdır.',
    whyWrong: [
      'Aile üyeleri dâhil yolcu taşınması yasaktır.',
      'Kural sayı sınırı değil, tam yasak koyar: sürücü dışında kimse binemez.',
      'Aracın tamamen boş olması da yanlıştır; yönlendirme için sürücü gerekir.',
    ],
    objective: 'Çekilen araçta yalnızca sürücü bulunabileceğini bilmek.',
    tags: ['cekme', 'yolcu-yasagi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-429',
    subject: 'trafik',
    topic: 'cekme-kurallari',
    difficulty: 'orta',
    stem: 'B sınıfı sürücü belgesi olan bir otomobil sürücüsü, belgesine ek bir sınıf almadan en fazla kaç kilograma kadar römork çekebilir?',
    options: ['300 kilogram', '750 kilogram', '1.500 kilogram', '3.500 kilogram'],
    answerIndex: 1,
    explanation:
      'B sınıfı belge, azami yüklü ağırlığı 750 kilogramı geçmeyen hafif römorkun çekilmesine izin verir; daha ağır römorklar için ek belge (BE) gerekir.',
    whyWrong: [
      '300 kilogram sınırın altında bir değerdir; kural 750 kilograma kadar izin verir.',
      '1.500 kilogram hafif römork sınırını aşar; BE sınıfı gerektirir.',
      '3.500 kilogram B sınıfının çekebileceği araç toplamıyla ilgili başka bir sınırdır, römork sınırı değildir.',
    ],
    objective: 'B sınıfı belgeyle çekilebilecek hafif römork sınırını bilmek.',
    tags: ['romork', 'surucu-belgesi', 'b-sinifi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-430',
    subject: 'trafik',
    topic: 'yukleme-kurallari',
    difficulty: 'kolay',
    stem: 'Araca yüklenen yük ile ilgili aşağıdakilerden hangisi doğrudur?',
    options: [
      'Yük plakayı kapatabilir, ışıkları kapatamaz',
      'Yük yalnızca gündüz ışıkları kapatabilir',
      'Kısa yolculuklarda yükün ışıkları kapatması sorun olmaz',
      'Yük; plakayı, ışıkları ve sürücünün görüşünü hiçbir şekilde kapatamaz',
    ],
    answerIndex: 3,
    explanation:
      'Yükleme güvenliğinin temel şartı görünürlüktür: yük plakayı, stop-sinyal gibi ışıkları ve sürücünün görüş alanını örtemez; aksi hâlde araç trafikte tanınamaz ve manevraları okunamaz hâle gelir.',
    whyWrong: [
      'Plaka da ışıklar kadar korunması gereken bir tanıtım ögesidir.',
      'Gündüz-gece ayrımı yoktur; ışıklar her an görünür olmalıdır.',
      'Yolculuk süresi kuralı değiştirmez.',
    ],
    objective: 'Yükün plaka, ışık ve görüşü kapatamayacağını bilmek.',
    tags: ['yukleme', 'plaka', 'gorunurluk'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-431',
    subject: 'trafik',
    topic: 'yukleme-kurallari',
    difficulty: 'orta',
    stem: 'Aracın arkasından taşan uzun bir yükün en uç noktasına gündüz ne takılmalıdır?',
    options: [
      'Kırmızı bez veya kırmızı yansıtıcı',
      'Beyaz ışık',
      'Mavi bayrak',
      'Herhangi bir işaret gerekmez',
    ],
    answerIndex: 0,
    explanation:
      'Arkadan taşan yükün ucu diğer sürücüler tarafından geç fark edilir. Bu nedenle taşan uca gündüz kırmızı bez veya yansıtıcı, gece ise kırmızı ışık takılması zorunludur.',
    whyWrong: [
      'Beyaz ışık gece için de yanlıştır; arkada kırmızı esastır.',
      'Mavi bayrağın mevzuatta böyle bir işlevi yoktur.',
      'İşaretsiz taşan yük, arkadan yaklaşan araçlar için görünmez engeldir.',
    ],
    objective: 'Taşan yükün işaretlenme kurallarını bilmek.',
    tags: ['yukleme', 'tasan-yuk', 'isaretleme'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-432',
    subject: 'trafik',
    topic: 'yukleme-kurallari',
    difficulty: 'kolay',
    stem: 'Kum, çakıl gibi tozan veya saçılabilen maddeler açık kasa araçla nasıl taşınmalıdır?',
    options: [
      'Kasa ağzına kadar doldurularak',
      'Hızlı gidilerek saçılmaya fırsat vermeden',
      'Üzeri branda ile örtülerek, yola dökülmeyecek şekilde',
      'Yalnızca gece saatlerinde',
    ],
    answerIndex: 2,
    explanation:
      'Saçılabilen yüklerin üzeri örtülür ve yola dökülmeyecek biçimde yüklenir; dökülen malzeme arkadaki araçların camını kırar, yolu kayganlaştırır ve çevreyi kirletir.',
    whyWrong: [
      'Ağzına kadar doldurmak saçılmayı artırır.',
      'Hız, savrulan taneciklerin arkadaki araçlara çarpma gücünü büyütür.',
      'Gece taşımak dökülmeyi engellemez; çözüm örtmektir.',
    ],
    objective: 'Saçılabilir yüklerin örtülerek taşınması gerektiğini bilmek.',
    tags: ['yukleme', 'cevre', 'guvenlik'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-433',
    subject: 'trafik',
    topic: 'kaza-sorumluluk',
    difficulty: 'kolay',
    stem: 'Yalnızca maddi hasarla sonuçlanan bir kazada taraflar kusur konusunda anlaşırsa ne yapabilirler?',
    options: [
      'Araçları oldukları yerde bırakıp polis beklemek zorundadırlar',
      'Kaza tespit tutanağını kendi aralarında doldurup araçlarını güvenli bir yere çekebilirler',
      'Tutanak tutmadan ayrılabilirler',
      'Yalnızca sigorta şirketleri gelene kadar bekleyebilirler',
    ],
    answerIndex: 1,
    explanation:
      'Ölüm ve yaralanma yoksa ve taraflar anlaşıyorsa, kendi aralarında maddi hasarlı kaza tespit tutanağı düzenleyip fotoğraf aldıktan sonra araçlarını trafiği aksatmayacak güvenli bir yere çekebilirler.',
    whyWrong: [
      'Anlaşma varsa polis beklemek zorunlu değildir; yolu kapatmak ayrıca sakıncalıdır.',
      'Tutanaksız ayrılmak sigorta sürecini dayanaksız bırakır.',
      'Sigorta şirketinin olay yerine gelmesi diye bir zorunluluk yoktur.',
    ],
    objective: 'Maddi hasarlı kazada anlaşmalı tutanak uygulamasını bilmek.',
    tags: ['kaza-tutanagi', 'maddi-hasar'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-434',
    subject: 'trafik',
    topic: 'kaza-sorumluluk',
    difficulty: 'orta',
    stem: 'Yaralanmalı bir trafik kazasında, güvenlik zorunlu kılmadıkça kazaya karışan araçlar için hangisi doğrudur?',
    options: [
      'Yetkililer gelene kadar yerleri değiştirilmez',
      'Hemen yol kenarına çekilmeleri zorunludur',
      'Sürücüler araçlarını evlerine götürebilir',
      'Araçlar en yakın otoparka çekilir',
    ],
    answerIndex: 0,
    explanation:
      'Yaralanmalı ve ölümlü kazalarda araçların konumu, kusurun belirlenmesinde delildir. Trafik güvenliği açısından zorunlu olmadıkça araçların ve izlerin yeri değiştirilmez; yetkililer beklenir.',
    whyWrong: [
      'Kenara çekme zorunluluğu maddi hasarlı anlaşmalı kazalar içindir.',
      'Olay yerinden aracıyla ayrılan sürücü delil karartmış ve suç işlemiş olur.',
      'Otoparka çekme kararı ancak inceleme sonrası yetkililerce verilir.',
    ],
    objective: 'Yaralanmalı kazada olay yerinin korunması kuralını bilmek.',
    tags: ['kaza-yeri', 'delil', 'yaralanmali-kaza'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-435',
    subject: 'trafik',
    topic: 'kaza-sorumluluk',
    difficulty: 'zor',
    stem: 'Aşağıdaki davranışlardan hangisi trafik kazalarında "asli (esas) kusur" sayılan hâllerdendir?',
    options: [
      'Emniyet kemeri takmamak',
      'Farları ayarsız kullanmak',
      'Aracın bakımını geciktirmek',
      'Kırmızı ışıkta geçmek',
    ],
    answerIndex: 3,
    explanation:
      'Kırmızı ışık veya görevlinin dur işaretinde geçmek, mevzuatta sayılan asli kusur hâllerindendir; kazaya bu ihlalle karışan sürücü esas kusurlu kabul edilir. Arkadan çarpma ve karşı şeride geçme de aynı listededir.',
    whyWrong: [
      'Kemersiz yolculuk ayrı bir ihlaldir ama asli kusur listesinde yer almaz.',
      'Ayarsız far kusur değerlendirmesinde etken olabilir; sayılı asli kusurlardan değildir.',
      'Bakım eksikliği sorumluluk doğurabilir fakat asli kusur hâli olarak sayılmamıştır.',
    ],
    objective: 'Asli kusur sayılan tipik ihlalleri tanımak.',
    tags: ['asli-kusur', 'kaza-sorumlulugu', 'kirmizi-isik'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-436',
    subject: 'trafik',
    topic: 'kaza-sorumluluk',
    difficulty: 'kolay',
    stem: 'Bir trafik kazasına karışan sürücünün yasal yükümlülüğü nedir?',
    options: [
      'Hasar küçükse olay yerinden ayrılabilir',
      'Yalnızca kendi aracının hasarını tespit etmek',
      'Durmak, gerekli önlemleri almak ve kimlik ile sigorta bilgilerini paylaşmak',
      'Sadece tanık bulmak',
    ],
    answerIndex: 2,
    explanation:
      'Kazaya karışan herkes durmak, tehlikeye karşı önlem almak, yaralılara yardım etmek ve istenirse kimlik, belge ve sigorta bilgilerini vermek zorundadır. Olay yerinden kaçmak ayrıca sorumluluk doğurur.',
    whyWrong: [
      'Hasarın küçüklüğü ayrılma hakkı vermez; karşı tarafın onayı ve tutanak gerekir.',
      'Yalnız kendi hasarına bakmak yükümlülüklerin çok azıdır.',
      'Tanık bulmak yararlı olabilir ama yasal zorunluluklar bunlardan ibaret değildir.',
    ],
    objective: 'Kazaya karışan sürücünün temel yükümlülüklerini bilmek.',
    tags: ['kaza-sonrasi', 'yukumluluk'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-437',
    subject: 'trafik',
    topic: 'kaza-sorumluluk',
    difficulty: 'zor',
    stem: 'Maddi hasarlı bir kazada taraflardan biri kusur konusunda anlaşmaya yanaşmıyorsa ne yapılmalıdır?',
    options: [
      'Anlaşan taraf tek başına tutanak doldurup gidebilir',
      'Trafik zabıtası çağrılmalı ve araçlar inceleme tamamlanana kadar korunmalıdır',
      'Kusuru büyük görünen taraf suçu kabul etmek zorundadır',
      'Taraflar araçlarını çekip konuyu daha sonra kendileri çözer',
    ],
    answerIndex: 1,
    explanation:
      'Anlaşmalı tutanak yalnızca iki tarafın da imzasıyla geçerlidir. Anlaşmazlık varsa trafik zabıtası çağrılır; kusur, resmî tespitle belirlenir ve bu tespit sigorta sürecinin dayanağı olur.',
    whyWrong: [
      'Tek imzalı tutanak anlaşmalı tutanak sayılmaz.',
      'Kusur kabulü zorlanamaz; tespit resmî makamındır.',
      'Tespit yapılmadan dağılmak, hak kaybına ve ispat sorununa yol açar.',
    ],
    objective: 'Anlaşmazlık hâlinde resmî tespit gerektiğini bilmek.',
    tags: ['kaza-tutanagi', 'anlasmazlik', 'trafik-zabitasi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-438',
    subject: 'trafik',
    topic: 'kavsak-serit-secimi',
    difficulty: 'kolay',
    stem: 'Kavşaktan sağa dönecek olan sürücü hangi şeridi kullanmalı ve dönüşü nasıl yapmalıdır?',
    options: [
      'En sağ şeride girmeli ve dar bir kavisle dönmelidir',
      'En sol şeride girmeli ve geniş kavisle dönmelidir',
      'Orta şeritten dilediği kavisle dönmelidir',
      'Hangi şeritte ise oradan dönmelidir',
    ],
    answerIndex: 0,
    explanation:
      'Sağa dönüş, en sağ şeritten ve dar kavisle yapılır; böylece araç karşı ve yan akımların alanına taşmadan kendi gideceği yolun sağ şeridine oturur.',
    whyWrong: [
      'Sol şeritten sağa dönmek, sağdaki araçların yolunu kesmek demektir.',
      'Orta şeritten dönüş, iki yandaki akımı da tehlikeye atar.',
      'Dönüş şeridi keyfe göre değil, dönüş yönüne göre seçilir.',
    ],
    objective: 'Sağa dönüşün şerit ve kavis kuralını bilmek.',
    tags: ['saga-donus', 'serit-secimi', 'kavsak'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-439',
    subject: 'trafik',
    topic: 'donus-teknikleri',
    difficulty: 'orta',
    stem: 'Kavşakta sola dönüş yapan sürücünün izlemesi gereken kavis nasıl olmalıdır?',
    options: [
      'Mümkün olan en dar kavis',
      'Kavşak merkezinin üzerinden kestirme',
      'Önce sağa açılıp sonra keskin dönüş',
      'Geniş kavis; kavşak merkezinin dışından dolaşarak',
    ],
    answerIndex: 3,
    explanation:
      'Kural kısaca "sağa dar, sola geniş"tir: sola dönüş geniş kavisle yapılır ki araç karşı yönden gelen trafiğin şeridine erken girmesin ve dönülen yolun doğru şeridine yerleşsin.',
    whyWrong: [
      'Dar kavisle sola dönen araç karşı akımın şeridini kesmiş olur.',
      'Kavşak merkezinden kestirme, dönüş çizgilerini ve karşı akımı ihlal eder.',
      'Sola dönüş öncesi sağa açılmak arkadaki ve yandaki sürücüleri yanıltır.',
    ],
    objective: '"Sağa dar, sola geniş kavis" kuralını kavramak.',
    tags: ['sola-donus', 'kavis', 'donus-teknigi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-440',
    subject: 'trafik',
    topic: 'kavsak-serit-secimi',
    difficulty: 'orta',
    stem: 'Kavşağa yaklaşan sürücünün şerit seçimiyle ilgili doğru davranış hangisidir?',
    options: [
      'Şeridini kavşağın içinde belirlemek',
      'Kavşak içinde boş bulduğu şeride geçmek',
      'Gideceği yöne uygun şeridi kavşağa girmeden önce seçmek ve kavşakta şerit değiştirmemek',
      'Her kavşakta en soldaki şeridi kullanmak',
    ],
    answerIndex: 2,
    explanation:
      'Kavşak, akımların kesiştiği en riskli alandır; şerit değişikliği kavşaktan önce tamamlanır. Kavşak içinde şerit değiştirmek diğer sürücülerin yön beklentisini bozar ve yasaktır.',
    whyWrong: [
      'Kavşak içi, karar verme yeri değil, kararın uygulandığı yerdir.',
      'Boş şeride atlama, dönüş hâlindeki araçlarla çakışma yaratır.',
      'Sol şerit yalnızca sola dönüş veya mevzuatın izin verdiği hâller içindir.',
    ],
    objective: 'Şerit seçiminin kavşaktan önce tamamlanması gerektiğini bilmek.',
    tags: ['kavsak', 'serit-secimi', 'serit-degistirme'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-441',
    subject: 'trafik',
    topic: 'kavsak-serit-secimi',
    difficulty: 'zor',
    stem: 'Tek yönlü bir yoldan sola dönüş yapacak sürücü dönüşten önce hangi şeride girmelidir?',
    options: [
      'En sağ şeride',
      'Yolun en sol şeridine',
      'Orta şeride',
      'Herhangi bir şeride; tek yönde fark etmez',
    ],
    answerIndex: 1,
    explanation:
      'Tek yönlü yolda karşı akım olmadığından sola dönecek araç yolun en soluna yaklaşır; böylece soldaki dönüş noktasına diğer şeritleri kesmeden ulaşır.',
    whyWrong: [
      'Sağ şeritten sola dönüş, aradaki tüm şeritleri kesmek demektir.',
      'Orta şeritten dönüş, soldaki şeritte düz devam eden araçlarla çakışır.',
      'Tek yönlü olması şerit disiplinini kaldırmaz; dönüş yönüne en yakın şerit esastır.',
    ],
    objective: 'Tek yönlü yolda sola dönüş için sol şeride yaklaşma kuralını bilmek.',
    tags: ['tek-yonlu-yol', 'sola-donus', 'serit-secimi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-442',
    subject: 'trafik',
    topic: 'otoyol-kurallari',
    difficulty: 'kolay',
    stem: 'Otoyoldan çıkacak olan sürücü hızını nerede azaltmalıdır?',
    options: [
      'Yavaşlama şeridine geçtikten sonra',
      'Otoyolun seyir şeridinde, çıkıştan çok önce',
      'Çıkış rampasının sonunda ani frenle',
      'Hız azaltmaya gerek yoktur',
    ],
    answerIndex: 0,
    explanation:
      'Çıkışlardaki yavaşlama şeridi tam bu iş içindir: sürücü seyir hızıyla bu şeride geçer, hız azaltmayı ana akımın dışında yapar. Böylece arkadan gelen hızlı trafik yavaşlamak zorunda kalmaz.',
    whyWrong: [
      'Seyir şeridinde erken yavaşlamak arkadan çarpma riskini büyütür.',
      'Rampanın sonuna hızla girip ani fren yapmak savrulmaya yol açar.',
      'Çıkış kavisleri otoyol hızına göre tasarlanmamıştır; hız mutlaka düşürülür.',
    ],
    objective: 'Yavaşlama şeridinin işlevini ve kullanımını bilmek.',
    tags: ['otoyol', 'yavaslama-seridi', 'cikis'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-443',
    subject: 'trafik',
    topic: 'otoyol-kurallari',
    difficulty: 'orta',
    stem: 'Otoyolda çıkışını kaçıran sürücü ne yapmalıdır?',
    options: [
      'Emniyet şeridinde geri geri giderek çıkışa dönmelidir',
      'İlk uygun yerden U dönüşü yapmalıdır',
      'Bir sonraki çıkışa kadar devam etmelidir',
      'Durup yardım çağırmalıdır',
    ],
    answerIndex: 2,
    explanation:
      'Otoyolda geri gitmek ve dönüş yapmak kesinlikle yasaktır. Çıkışı kaçıran sürücünün tek doğru seçeneği bir sonraki çıkışa kadar devam edip oradan güzergâhına dönmesidir.',
    whyWrong: [
      'Otoyolda geri gitmek en ağır ihlallerdendir; ölümcül kaza riski taşır.',
      'Otoyolda U dönüşü yasaktır; refüj geçişleri yalnızca yetkili araçlar içindir.',
      'Çıkış kaçırmak acil durum değildir; durmak da ihlal oluşturur.',
    ],
    objective: 'Otoyolda geri gitme ve dönüş yasağını kavramak.',
    tags: ['otoyol', 'geri-gitme-yasagi', 'u-donusu'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-444',
    subject: 'trafik',
    topic: 'otoyol-kurallari',
    difficulty: 'orta',
    stem: 'Trafiğin durma noktasına geldiği bir otoyolda bazı sürücülerin emniyet şeridinden ilerlemesi nasıl değerlendirilir?',
    options: [
      'Sıkışıklığı azalttığı için doğrudur',
      'Kısa mesafede yapılırsa serbesttir',
      'Yalnızca yerli plakalı araçlara serbesttir',
      'İhlaldir; emniyet şeridi acil durumlar ve görevli araçlar için boş kalmalıdır',
    ],
    answerIndex: 3,
    explanation:
      'Emniyet şeridi; arızalanan araçlar, ambulans, itfaiye ve müdahale ekipleri için ayrılmıştır. Sıkışıklıkta bu şeritten ilerlemek hem ağır bir ihlaldir hem de yardımın kazazedeye ulaşmasını geciktirir.',
    whyWrong: [
      'Emniyet şeridini işgal etmek sıkışıklığı çözmez; acil geçiş yolunu kapatır.',
      'Mesafenin kısalığı ihlali ortadan kaldırmaz.',
      'Kural plakaya göre değişmez; herkes için aynıdır.',
    ],
    objective: 'Emniyet şeridi ihlalinin niteliğini ve sonuçlarını kavramak.',
    tags: ['otoyol', 'emniyet-seridi', 'ihlal'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-445',
    subject: 'trafik',
    topic: 'otoyol-kurallari',
    difficulty: 'zor',
    stem: 'Otoyollarda araçlar için geçerli olan asgari (en düşük) hız sınırı kaç km/saattir?',
    options: ['20 km/saat', '40 km/saat', '60 km/saat', '80 km/saat'],
    answerIndex: 1,
    explanation:
      'Otoyol yüksek hızlı ve kesintisiz akış için tasarlandığından burada asgari hız kuralı vardır: zorunlu hâller dışında 40 km/saatin altında seyredilemez; çok yavaş araç, hızlı akış içinde engel etkisi yaratır.',
    whyWrong: [
      '20 km/saat otoyol akışı için tehlikeli derecede düşüktür; kuraldaki değer değildir.',
      '60 ve 80 km/saat asgari değil, bazı araç sınıflarının azami sınırlarına yakın değerlerdir.',
    ],
    objective: 'Otoyolda asgari hız kuralını bilmek.',
    tags: ['otoyol', 'asgari-hiz', 'hiz-siniri'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-446',
    subject: 'trafik',
    topic: 'arac-muayenesi',
    difficulty: 'kolay',
    stem: 'Hususi otomobillerin periyodik araç muayenesi hangi aralıklarla yapılır?',
    options: [
      'Her yıl',
      'İlk muayene 2. yılda, sonra her yıl',
      'İlk muayene 3. yılda, sonrasında 2 yılda bir',
      'Beş yılda bir',
    ],
    answerIndex: 2,
    explanation:
      'Hususi otomobiller tescilden sonraki 3. yılın sonunda ilk muayeneye girer; sonraki muayeneler 2 yılda bir tekrarlanır. Bu periyot aracın teknik güvenliğini düzenli olarak belgelendirir.',
    whyWrong: [
      'Her yıl muayene, otomobil için değil bazı ticari araç sınıfları için geçerlidir.',
      '2. yılda ilk muayene ve yıllık tekrar otomobil periyodu değildir.',
      'Beş yıllık aralık mevzuatta yoktur; teknik kontrol için fazla uzundur.',
    ],
    objective: 'Otomobil muayene periyodunu (3 yıl + 2 yılda bir) bilmek.',
    tags: ['arac-muayenesi', 'periyot', 'otomobil'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-447',
    subject: 'trafik',
    topic: 'arac-muayenesi',
    difficulty: 'orta',
    stem: 'Muayene süresi geçtiği hâlde muayenesi yaptırılmamış bir araçla trafiğe çıkan sürücü için hangisi doğrudur?',
    options: [
      'Ceza uygulanır ve araç muayeneye sevk edilir; süresi geçmiş araçla trafiğe çıkılamaz',
      'İlk denetimde yalnızca sözlü uyarı yapılır',
      'Araç hususi ise yaptırım uygulanmaz',
      'Muayene, isteğe bağlı bir işlemdir',
    ],
    answerIndex: 0,
    explanation:
      'Periyodik muayene zorunludur; süresi geçmiş araçla trafiğe çıkan sürücüye idari para cezası uygulanır ve aracın muayenesinin yaptırılması istenir. Muayenesiz araç fren, ışık gibi sistemleri belgelenmemiş araçtır.',
    whyWrong: [
      'Sözlü uyarı diye bir kademe yoktur; ihlal cezaya bağlanmıştır.',
      'Hususi araçlar da zorunluluğun kapsamındadır.',
      'Muayene isteğe bağlı değil, yasal zorunluluktur.',
    ],
    objective: 'Muayenesi geçmiş araçla trafiğe çıkmanın yaptırımını bilmek.',
    tags: ['arac-muayenesi', 'yaptirim'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-448',
    subject: 'trafik',
    topic: 'zorunlu-sigorta',
    difficulty: 'kolay',
    stem: 'Zorunlu mali sorumluluk (trafik) sigortası bulunmayan bir araç için hangisi doğrudur?',
    options: [
      'Yalnızca şehirlerarası yolda kullanılamaz',
      'Sahibi deneyimliyse kullanılabilir',
      'Kasko varsa trafik sigortasına gerek kalmaz',
      'Trafiğe çıkarılamaz; tespit edilirse trafikten men edilir',
    ],
    answerIndex: 3,
    explanation:
      'Trafik sigortası, kazada üçüncü kişilere verilecek zararın güvencesidir ve yasal zorunluluktur. Sigortasız araç trafiğe çıkarılamaz; denetimde tespit edilirse ceza uygulanır ve araç trafikten men edilir.',
    whyWrong: [
      'Yasak yol türüne göre değil, tüm karayolları için geçerlidir.',
      'Sürücü deneyimi sigorta zorunluluğunu kaldırmaz.',
      'Kasko isteğe bağlıdır ve zorunlu sigortanın yerine geçmez.',
    ],
    objective: 'Zorunlu trafik sigortasız aracın trafiğe çıkamayacağını bilmek.',
    tags: ['zorunlu-sigorta', 'trafikten-men'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-449',
    subject: 'trafik',
    topic: 'zorunlu-sigorta',
    difficulty: 'orta',
    stem: 'Aşağıdaki belgelerden hangisinin denetimlerde ibraz edilmek üzere araçta bulundurulması zorunludur?',
    options: [
      'Aracın satış faturası',
      'Zorunlu mali sorumluluk sigortası poliçesi',
      'Kasko poliçesi',
      'Servis bakım kitapçığı',
    ],
    answerIndex: 1,
    explanation:
      'Denetimlerde sürücüden sürücü belgesi, araç tescil belgesi ve zorunlu trafik sigortası poliçesi istenir; bu üçlü, sürücünün ve aracın trafiğe çıkma şartlarını belgeler.',
    whyWrong: [
      'Satış faturası tescil aşamasında kullanılır; araçta taşınması gerekmez.',
      'Kasko isteğe bağlı bir sigortadır; denetimde aranmaz.',
      'Bakım kitapçığı aracın servis geçmişini gösterir, yasal belge değildir.',
    ],
    objective: 'Araçta bulundurulması zorunlu belgeleri ayırt etmek.',
    tags: ['zorunlu-belgeler', 'sigorta-policesi', 'denetim'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-450',
    subject: 'trafik',
    topic: 'belge-geri-alma',
    difficulty: 'orta',
    stem: 'Hususi otomobil sürücüsü ilk kez yasal sınırın üzerinde alkollü olarak araç kullanırken tespit edilirse sürücü belgesine ne olur?',
    options: [
      '6 ay süreyle geri alınır',
      'Yalnızca para cezası uygulanır, belgeye dokunulmaz',
      'Süresiz olarak iptal edilir',
      '15 gün süreyle geri alınır',
    ],
    answerIndex: 0,
    explanation:
      'Alkollü araç kullanma ilk tespitinde para cezasının yanında sürücü belgesi 6 ay süreyle geri alınır. Tekrarında süreler ağırlaşır; sistem caydırıcılık üzerine kuruludur.',
    whyWrong: [
      'Para cezası tek başına yeterli görülmez; belge geri alma da uygulanır.',
      'Süresiz iptal ilk ihlalin değil, tekrarlanan ağır ihlallerin sonucudur.',
      '15 gün gibi kısa bir süre mevzuatta yoktur; ilk ihlalde süre 6 aydır.',
    ],
    objective: 'İlk alkol ihlalinde belge geri alma süresini bilmek.',
    tags: ['alkol', 'belge-geri-alma', 'yaptirim'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-451',
    subject: 'trafik',
    topic: 'belge-geri-alma',
    difficulty: 'zor',
    stem: 'Alkollü araç kullanmaktan ikinci kez yakalanan sürücünün belgesi ne kadar süreyle geri alınır?',
    options: ['6 ay', '1 yıl', '2 yıl', '5 yıl'],
    answerIndex: 2,
    explanation:
      'Alkol ihlalinde süreler kademelidir: ilk tespitte 6 ay, ikinci tespitte 2 yıl, üçüncü tespitte 5 yıl geri alma uygulanır; ileri kademelerde ayrıca eğitim ve değerlendirme şartları devreye girer.',
    whyWrong: [
      '6 ay ilk ihlalin süresidir.',
      '1 yıl bu kademelendirmede yer almaz.',
      '5 yıl üçüncü ihlalin süresidir.',
    ],
    objective: 'Alkol ihlallerindeki kademeli geri alma sürelerini bilmek.',
    tags: ['alkol', 'belge-geri-alma', 'tekrar-ihlal'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-452',
    subject: 'trafik',
    topic: 'belge-geri-alma',
    difficulty: 'zor',
    stem: 'Bir yıl içinde hız sınırını yüzde otuzdan fazla aşmaktan 5 kez ceza alan sürücünün belgesi ne kadar süreyle geri alınır?',
    options: ['3 ay', '6 ay', '1 yıl', '2 yıl'],
    answerIndex: 2,
    explanation:
      "Hız sınırını %30'dan fazla aşma ihlalini bir yıl içinde 5 kez işleyen sürücünün belgesi 1 yıl süreyle geri alınır; kural, sistematik hız ihlalcisini trafikten uzaklaştırmayı amaçlar.",
    whyWrong: [
      '3 ay ve 6 ay bu ihlal için öngörülen süreler değildir.',
      '2 yıl, alkolde ikinci ihlal gibi başka yaptırımların süresidir.',
    ],
    objective: 'Tekrarlanan ağır hız ihlalinin belgeye etkisini bilmek.',
    tags: ['hiz-ihlali', 'belge-geri-alma'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-453',
    subject: 'trafik',
    topic: 'ceza-puani',
    difficulty: 'orta',
    stem: 'Bir yıl içinde toplam 100 ceza puanını ilk kez dolduran sürücüye hangi yaptırım uygulanır?',
    options: [
      'Yalnızca yazılı uyarı gönderilir',
      'Belgesi süresiz iptal edilir',
      'Araç trafikten men edilir',
      'Belgesi 2 ay geri alınır ve eğitime tabi tutulur',
    ],
    answerIndex: 3,
    explanation:
      'Ceza puanı sisteminde bir yılda 100 puanı dolduran sürücünün belgesi ilk seferde 2 ay geri alınır ve sürücü eğitime tabi tutulur; amaç ceza değil davranış düzeltmedir.',
    whyWrong: [
      'Uyarıyla geçiştirilecek bir eşik değildir; belge fiilen geri alınır.',
      'Süresiz iptal ilk doluşta değil, tekrarlarda gündeme gelir.',
      'Yaptırım araca değil sürücü belgesine yöneliktir.',
    ],
    objective: '100 ceza puanının ilk doluştaki sonucunu bilmek.',
    tags: ['ceza-puani', 'belge-geri-alma', 'egitim'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-454',
    subject: 'trafik',
    topic: 'ceza-puani',
    difficulty: 'zor',
    stem: 'Bir yıl içinde 100 ceza puanını ikinci kez dolduran sürücüye ne uygulanır?',
    options: [
      'Belgesi 4 ay geri alınır ve psikoteknik değerlendirmeye tabi tutulur',
      'Belgesi yine 2 ay geri alınır',
      'Yalnızca para cezası uygulanır',
      'Belge geri alınmaz, ek puan silinir',
    ],
    answerIndex: 0,
    explanation:
      'İkinci kez 100 puanı dolduran sürücünün belgesi 4 ay geri alınır; ayrıca psikoteknik değerlendirme ve psikiyatri uzmanı muayenesine tabi tutulur. Kademelenme, tekrar eden riskli sürücüyü hedefler.',
    whyWrong: [
      '2 ay ilk doluşun yaptırımıdır; ikinci doluşta süre artar.',
      'Yalnız para cezası bu eşikte öngörülmemiştir.',
      'Puan silme diye bir uygulama yoktur; yaptırım ağırlaşır.',
    ],
    objective: 'Ceza puanı sisteminin kademeli yaptırımlarını bilmek.',
    tags: ['ceza-puani', 'psikoteknik', 'tekrar-ihlal'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-455',
    subject: 'trafik',
    topic: 'gorevli-isareti',
    difficulty: 'kolay',
    stem: 'Kavşakta trafik ışığı yeşil yandığı hâlde trafik polisi size "dur" işareti veriyor. Ne yapmalısınız?',
    options: [
      'Işık yeşil olduğu için geçersiniz',
      'Korna çalarak polisi uyarırsınız',
      'Görevlinin işaretine uyar ve durursunuz',
      'Yavaşlayarak geçersiniz',
    ],
    answerIndex: 2,
    explanation:
      'Uyulacakların sıralamasında trafik görevlisi en üsttedir; görevlinin işareti ışıklarla çelişirse görevliye uyulur. Işık yeşil olsa bile "dur" işareti veren polise uymak zorunludur.',
    whyWrong: [
      'Yeşil ışık, görevlinin işareti karşısında geçerliliğini yitirir.',
      'Korna çalmak görevliye itiraz anlamı taşır ve kural ihlalidir.',
      'Yavaş da olsa geçmek, dur talimatının ihlalidir.',
    ],
    objective: 'Görevli işaretinin ışıklara üstünlüğünü kavramak.',
    tags: ['trafik-gorevlisi', 'oncelik-sirasi', 'isikli-isaret'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-456',
    subject: 'trafik',
    topic: 'gecis-ustunlugu',
    difficulty: 'orta',
    stem: 'Görev hâlindeki bir ambulans ile bir itfaiye aracı aynı kavşağa aynı anda gelirse hangisi önce geçer?',
    options: [
      'İtfaiye aracı',
      'Ambulans (cankurtaran ve yaralı taşıyan araçlar)',
      'Kavşağa önce giren',
      'Plaka numarası küçük olan',
    ],
    answerIndex: 1,
    explanation:
      'Geçiş üstünlüğü olan araçlar da kendi aralarında sıralanır: önce cankurtaran ve yaralı taşıyan araçlar, sonra itfaiye, ardından güvenlik ve koruma araçları gelir; insan hayatı en üsttedir.',
    whyWrong: [
      'İtfaiye sıralamada ambulanstan sonra gelir.',
      '"Önce giren geçer" kuralı olağan araçlar içindir; üstünlüklü araçlarda sıra bellidir.',
      'Plaka numarasının geçiş sırasıyla ilgisi yoktur.',
    ],
    objective: 'Geçiş üstünlüğü araçlarının kendi içindeki sırasını bilmek.',
    tags: ['gecis-ustunlugu', 'ambulans', 'itfaiye'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-457',
    subject: 'trafik',
    topic: 'gecis-ustunlugu',
    difficulty: 'kolay',
    stem: 'Ambulans, itfaiye gibi araçlar geçiş üstünlüğü hakkını hangi şartla kullanabilir?',
    options: [
      'Her zaman, koşulsuz olarak',
      'Yalnızca gece saatlerinde',
      'Sürücüsü acele ettiği her durumda',
      'Görev hâlindeyken ve sesli ile ışıklı uyarı cihazlarını birlikte kullanarak',
    ],
    answerIndex: 3,
    explanation:
      'Geçiş üstünlüğü göreve bağlı bir haktır: araç görev hâlinde olmalı ve siren ile tepe lambasını birlikte çalıştırarak diğer sürücüleri uyarmalıdır. Görev dışında bu araçlar da genel kurallara uyar.',
    whyWrong: [
      'Görev dışındayken üstünlük kullanılamaz; koşulsuz hak değildir.',
      'Hakkın gece-gündüzle ilgisi yoktur; görev ve uyarı şartına bağlıdır.',
      'Kişisel acele, geçiş üstünlüğü doğurmaz.',
    ],
    objective: 'Geçiş üstünlüğünün görev ve uyarı şartına bağlı olduğunu bilmek.',
    tags: ['gecis-ustunlugu', 'siren', 'gorev-hali'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-458',
    subject: 'trafik',
    topic: 'kis-surusu',
    difficulty: 'kolay',
    stem: 'Buzlanma olan bir yolda takip mesafesi nasıl ayarlanmalıdır?',
    options: [
      'Kuru yoldakinin birkaç katına çıkarılmalıdır',
      'Kuru yoldakiyle aynı tutulmalıdır',
      'Öndeki araç yavaşsa kısaltılabilir',
      'Takip mesafesi buzda önemsizdir',
    ],
    answerIndex: 0,
    explanation:
      'Buzlu zeminde lastik ile yol arasındaki tutunma ciddi biçimde azalır ve duruş mesafesi kat kat uzar. Bu yüzden takip mesafesi kuru yoldakinin birkaç katına çıkarılmalıdır.',
    whyWrong: [
      'Aynı mesafe, uzayan fren mesafesi karşısında yetersiz kalır.',
      'Öndekinin yavaşlığı, sizin duruş mesafenizi kısaltmaz.',
      'Buzda mesafe önemsiz değil, tam tersine hayati önemdedir.',
    ],
    objective: 'Buzlu zeminde takip mesafesinin artırılması gerektiğini bilmek.',
    tags: ['buzlanma', 'takip-mesafesi', 'kis'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-459',
    subject: 'trafik',
    topic: 'kis-surusu',
    difficulty: 'orta',
    stem: 'Karlı zeminde duran araçla kalkış yaparken tekerleklerin patinaj yapmaması için ne yapılmalıdır?',
    options: [
      'Gaza sonuna kadar basılmalıdır',
      'Gaza yumuşak basılmalı, gerekirse kalkış 2. viteste yapılmalıdır',
      'Debriyaj aniden bırakılmalıdır',
      'El freni çekiliyken kalkılmalıdır',
    ],
    answerIndex: 1,
    explanation:
      'Patinajın nedeni tekerleğe zeminin taşıyabileceğinden fazla güç gitmesidir. Yumuşak gaz ve gerektiğinde 2. viteste kalkış, tekerleğe giden torku azaltarak tutunmayı korur.',
    whyWrong: [
      'Tam gaz, tekerleği anında boşa döndürür ve aracı yana kaydırabilir.',
      'Ani bırakılan debriyaj tork darbesi yaratır; patinajı tetikler.',
      'El freni çekiliyken kalkış aktarma organlarını zorlar, patinajı çözmez.',
    ],
    objective: 'Karda patinajsız kalkış tekniğini öğrenmek.',
    tags: ['kar', 'kalkis', 'patinaj'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-460',
    subject: 'trafik',
    topic: 'kis-surusu',
    difficulty: 'orta',
    stem: 'Buzlanma olan uzun bir inişte hız en güvenli şekilde nasıl kontrol edilir?',
    options: [
      'Vites boşa alınarak frenle',
      'Düşük vitese geçip motor freninden yararlanarak, ani frenden kaçınarak',
      'Sürekli sert fren yaparak',
      'El freni kademeli çekilerek',
    ],
    answerIndex: 1,
    explanation:
      'Buzlu inişte hız, düşük viteste motor freniyle kontrol edilir; fren pedalı ancak yumuşak ve kademeli kullanılır. Ani fren tekerlekleri kilitleyip aracı kayar hâle getirir.',
    whyWrong: [
      'Boş viteste araç serbest kalır; kontrol tamamen frene biner ve kayma başlar.',
      'Sert fren buz üzerinde tekerlek kilitlenmesi ve savrulma demektir.',
      'El freni yalnızca arka tekerleklere etki eder; seyir hâlinde çekilmesi savrulmaya yol açar.',
    ],
    objective: 'Buzlu inişte motor freni kullanımını kavramak.',
    tags: ['buzlanma', 'inis', 'motor-freni'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
];
