/**
 * ÖZGÜN araç tekniği (motor) soruları — 3. genişletme (Program 1). ROADMAP C.4/E.6.
 * Kaynak = MEB araç tekniği müfredatı; KENDİ İFADEMİZLE.
 */
import type { QuestionInput } from '@ea/content-schema';

const SRC = 'MEB araç tekniği müfredatı (özgün ifade)';

export const MOTOR_QUESTIONS_3: QuestionInput[] = [
  {
    id: 'motor-301',
    subject: 'motor',
    topic: 'abs',
    difficulty: 'orta',
    stem: 'Sürüş sırasında yalnızca ABS ikaz lambası yanarsa fren sistemiyle ilgili doğru değerlendirme hangisidir?',
    options: [
      'Fren sistemi tamamen devre dışı kalmıştır, araç hiç duramaz',
      'El freni otomatik olarak devreye girer',
      'Normal frenler çalışmaya devam eder, yalnızca kilitlenmeyi önleme özelliği devre dışı olabilir',
      'Motorun gücü kendiliğinden artar',
    ],
    answerIndex: 2,
    explanation:
      'ABS ikazı yandığında kilitlenmeyi önleyici sistem arızalı olabilir; ancak temel hidrolik fren düzeni çalışmaya devam eder. Ani ve sert frende tekerlekler kilitlenebileceğinden dikkatli olunmalı ve sistem en kısa sürede kontrol ettirilmelidir.',
    whyWrong: [
      'ABS arızası temel fren sistemini tamamen devre dışı bırakmaz; araç yine frenler.',
      'El freni kendiliğinden devreye girmez; ABS ile ilgisi yoktur.',
      'ABS ikazının motor gücüyle bir ilişkisi yoktur.',
    ],
    objective: 'ABS ikaz lambası yandığında temel frenlerin çalışmaya devam ettiğini kavramak.',
    tags: ['abs', 'fren-sistemi', 'ikaz-lambasi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-302',
    subject: 'motor',
    topic: 'fren-sistemi',
    difficulty: 'zor',
    stem: 'Fren pedalı normalden yumuşak inip neredeyse tabana kadar gidiyorsa bu en olası olarak neyi gösterir?',
    options: [
      'Lastik basıncının fazla yüksek olduğunu',
      'Fren sisteminde hava, hidrolik kaçağı veya hidrolik seviyesinin düştüğünü',
      'Akünün tam şarjlı olduğunu',
      'Motorun aşırı ısındığını',
    ],
    answerIndex: 1,
    explanation:
      'Sağlıklı bir fren pedalı belirli bir noktadan sonra sertleşir. Pedalın yumuşayıp tabana kadar gitmesi hidrolik hatta hava kaçtığını, bir kaçak bulunduğunu veya fren hidroliği seviyesinin düştüğünü gösterir. Frenleme zayıflar; vakit kaybetmeden kontrol ettirilmelidir.',
    whyWrong: [
      'Lastik basıncı fren pedalının boşalmasına yol açmaz.',
      'Akü şarjı ve motor sıcaklığı pedalın yumuşamasıyla doğrudan ilişkili değildir.',
    ],
    objective:
      'Yumuşayan/boşalan fren pedalının hidrolik sistem sorununa işaret ettiğini kavramak.',
    tags: ['fren-sistemi', 'fren-hidroligi', 'ariza'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-303',
    subject: 'motor',
    topic: 'fren-sistemi',
    difficulty: 'orta',
    stem: 'Fren yapıldığında araç sürekli bir tarafa (sağa ya da sola) çekiyorsa bunun olası nedeni nedir?',
    options: [
      'Farların açık unutulmuş olması',
      'Yakıt deposunun tam dolu olması',
      'Radyatörün yeni takılmış olması',
      'Sağ ve sol tekerlekler arasında frenleme kuvvetinin dengesiz olması (balata/kaliper/hidrolik farkı)',
    ],
    answerIndex: 3,
    explanation:
      'Frende araç bir yana çekiyorsa sağ ve sol tekerleklerdeki frenleme kuvveti eşit değildir; bir taraftaki balata, kaliper ya da hidrolik hat sorunlu olabilir. Bu durum acil frenlerde savrulmaya yol açabileceğinden tehlikelidir ve fren sistemi kontrol ettirilmelidir.',
    whyWrong: [
      'Farların açık olması ya da yakıt seviyesinin frenlemede yana çekmeyle ilgisi yoktur.',
      'Yeni radyatör frenleme dengesini etkilemez.',
    ],
    objective: 'Frende yana çekmenin dengesiz frenleme kuvvetinden kaynaklandığını kavramak.',
    tags: ['fren-sistemi', 'balata', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-304',
    subject: 'motor',
    topic: 'guvenlik-donanimi',
    difficulty: 'kolay',
    stem: 'Aracın hava yastığının (airbag) temel görevi aşağıdakilerden hangisidir?',
    options: [
      'Çarpışma anında açılarak sürücü ve yolcunun sert yüzeylere çarpma etkisini azaltmak',
      'Motoru soğutmak',
      'Yakıt tüketimini düşürmek',
      'Aküyü şarj etmek',
    ],
    answerIndex: 0,
    explanation:
      'Hava yastığı, ciddi bir çarpışmada saniyenin çok küçük bir diliminde şişerek sürücü ve yolcunun direksiyon veya gösterge paneli gibi sert yüzeylere çarpmasını yumuşatır. Emniyet kemeriyle birlikte çalışır; kemer takılı değilse koruma etkisi belirgin biçimde azalır.',
    whyWrong: [
      'Motoru soğutma görevi soğutma sistemine aittir.',
      'Hava yastığının yakıt tüketimi ya da akü şarjıyla ilgisi yoktur.',
    ],
    objective: 'Hava yastığının çarpışmada darbe etkisini azaltma işlevini kavramak.',
    tags: ['guvenlik-donanimi', 'hava-yastigi', 'emniyet-kemeri'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-305',
    subject: 'motor',
    topic: 'guvenlik-donanimi',
    difficulty: 'orta',
    stem: 'Elektronik denge (kayma önleyici) kontrol sistemi olan ESP sürücüye hangi temel faydayı sağlar?',
    options: [
      'Yakıt deposunu büyütmek',
      'Farları otomatik açmak',
      'Motor yağını değiştirmek',
      'Savrulma/kayma anında tekerlekleri ayrı ayrı frenleyip aracın kontrolde kalmasına yardımcı olmak',
    ],
    answerIndex: 3,
    explanation:
      'ESP, ani manevra veya kaygan zeminde aracın savrulmaya başladığını algılar; gerekli tekerleği tek tek frenleyip gerektiğinde motor gücünü azaltarak aracın istenen yönde kalmasına yardımcı olur. Böylece kontrol kaybı ve savrulma riski azalır.',
    whyWrong: [
      'ESP sisteminin yakıt deposu veya far kumandasıyla ilgisi yoktur.',
      'Motor yağı değişimi bakım işidir; ESP sisteminin görevi değildir.',
    ],
    objective: 'ESP sisteminin savrulmayı önleyerek araç kontrolünü koruma işlevini kavramak.',
    tags: ['guvenlik-donanimi', 'esp', 'yol-tutus'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-306',
    subject: 'motor',
    topic: 'gosterge-ikaz-lambalari',
    difficulty: 'kolay',
    stem: 'Gösterge panelindeki ikaz lambalarının renkleriyle ilgili genel kural aşağıdakilerden hangisidir?',
    options: [
      'Tüm renkler aynı anlama gelir',
      'Kırmızı ikaz acil/tehlike ve genellikle durmayı; sarı (turuncu) ikaz ise kontrol/dikkat gerektirir',
      'Yeşil ikaz her zaman ağır bir arıza demektir',
      'Sarı ikaz motoru hemen durdurmayı gerektirir',
    ],
    answerIndex: 1,
    explanation:
      'İkaz lambalarında renk, sorunun aciliyetini bildirir. Kırmızı ikaz ciddi/acil bir durumu ve çoğunlukla aracı güvenle durdurmayı gerektirir; sarı-turuncu ikaz bir arıza ya da kontrol ihtiyacını, yeşil-mavi ise çalışan bir işlevi (sinyal, uzun far gibi) belirtir.',
    whyWrong: [
      'Renkler farklı aciliyet düzeylerini gösterir; hepsi aynı anlama gelmez.',
      'Yeşil lambalar genellikle aktif bir işlevi bildirir, ağır arıza değil; sarı ikaz genellikle acil durmayı değil kontrolü gerektirir.',
    ],
    objective: 'İkaz lambası renklerinin aciliyet anlamını (kırmızı-sarı-yeşil) kavramak.',
    tags: ['gosterge-ikaz-lambalari', 'ikaz-lambasi', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-307',
    subject: 'motor',
    topic: 'gosterge-ikaz-lambalari',
    difficulty: 'orta',
    stem: 'Gösterge panelinde lastik basıncı ikaz lambası yandığında doğru davranış nedir?',
    options: [
      'Göstergeyi kapatıp yola devam etmek',
      'Hızı artırarak basıncı yükseltmeye çalışmak',
      'Uygun bir yerde durup lastik basınçlarını kontrol etmek ve gerekiyorsa uygun değere tamamlamak',
      'Klimayı açmak',
    ],
    answerIndex: 2,
    explanation:
      'Lastik basıncı ikazı, en az bir lastiğin basıncının önerilen değerin altına düştüğünü ya da lastiğin sönük/patlak olabileceğini gösterir. Düşük basınç yol tutuşunu bozar, aşınmayı ve yakıt tüketimini artırır. Güvenli bir yerde durup basınçlar kontrol edilmeli ve tamamlanmalıdır.',
    whyWrong: [
      'İkazı kapatmak sorunu gizler; basınç düşük kalır.',
      'Hızı artırmak basıncı düzeltmez; klimanın lastik basıncıyla ilgisi yoktur.',
    ],
    objective: 'Lastik basıncı ikaz lambasına doğru ve güvenli tepkiyi kavramak.',
    tags: ['gosterge-ikaz-lambalari', 'lastik-basinci', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-308',
    subject: 'motor',
    topic: 'yaglama-sistemi',
    difficulty: 'orta',
    stem: 'Motor yağlama sisteminde yağ pompasının görevi aşağıdakilerden hangisidir?',
    options: [
      'Yağı basınçla alıp motorun yağlanması gereken parçalarına dolaştırmak',
      'Yakıtı ateşlemek',
      'Egzoz gazını süzmek',
      'Aküyü şarj etmek',
    ],
    answerIndex: 0,
    explanation:
      'Yağ pompası, karterdeki yağı emerek basınçlandırır ve yağ kanalları aracılığıyla krank mili, yataklar ve eksantrik gibi hareketli parçalara ulaştırır. Böylece sürekli ve basınçlı yağlama sağlanır; basınç düşerse yağ ikaz lambası uyarır.',
    whyWrong: [
      'Yakıtı ateşleme görevi benzinli motorda bujiye aittir.',
      'Egzoz gazını süzme ve akü şarjı yağ pompasının işi değildir.',
    ],
    objective: 'Yağ pompasının yağı basınçla dolaştırma işlevini kavramak.',
    tags: ['yaglama-sistemi', 'yag-pompasi', 'motor'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-309',
    subject: 'motor',
    topic: 'yaglama-sistemi',
    difficulty: 'kolay',
    stem: 'Motor yağının depolandığı, motorun alt kısmındaki hazneye ne ad verilir?',
    options: ['Radyatör', 'Yakıt deposu', 'Silindir kapağı', 'Karter (yağ karteri)'],
    answerIndex: 3,
    explanation:
      'Karter, motorun altında bulunan ve motor yağının toplandığı hazne bölümüdür. Yağ pompası yağı buradan alıp motora dolaştırır; kullanılan yağ süzülüp tekrar kartere döner. Yağ değişiminde eski yağ karter tapasından boşaltılır.',
    whyWrong: [
      'Radyatör soğutma suyunu soğutur; yağ deposu değildir.',
      'Yakıt deposu yakıtı, silindir kapağı ise supap düzenini barındırır; yağın toplandığı yer karterdir.',
    ],
    objective: 'Motor yağının karterde depolandığını kavramak.',
    tags: ['yaglama-sistemi', 'karter', 'yag'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-310',
    subject: 'motor',
    topic: 'yaglama-sistemi',
    difficulty: 'zor',
    stem: 'Motora yağ çubuğundaki üst (maks) işaretin belirgin biçimde üzerinde fazla yağ konması hangi soruna yol açabilir?',
    options: [
      'Motor gücünün kalıcı olarak artması',
      'Krank milinin yağı köpürtmesi, basınç dengesinin bozulması ve conta/keçelerin zorlanması',
      'Lastiklerin şişmesi',
      'Farların daha parlak yanması',
    ],
    answerIndex: 1,
    explanation:
      'Yağ seviyesi fazla olduğunda dönen krank mili yağa çarpar; yağ köpürür, yağlama ve basınç dengesi bozulur. Ayrıca artan iç basınç conta ve keçeleri zorlayarak yağ kaçaklarına yol açabilir. Bu nedenle yağ, çubuktaki min-maks işaretleri arasında tutulmalıdır.',
    whyWrong: [
      'Fazla yağ motor gücünü artırmaz; tersine yağlama sorunları çıkarır.',
      'Yağ seviyesinin lastik basıncı veya farlarla bir ilişkisi yoktur.',
    ],
    objective: 'Aşırı motor yağının yağlama ve conta üzerindeki olumsuz etkisini kavramak.',
    tags: ['yaglama-sistemi', 'yag-seviyesi', 'ariza'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-311',
    subject: 'motor',
    topic: 'sogutma-sistemi',
    difficulty: 'kolay',
    stem: 'Aracın içini ısıtan kalorifer (ısıtma) sistemi ısıyı temel olarak nereden alır?',
    options: ['Aküden', 'Fren balatalarından', 'Isınan motor soğutma suyundan', 'Lastiklerden'],
    answerIndex: 2,
    explanation:
      'Kalorifer, ısınmış motor soğutma suyunu kabin içindeki küçük bir radyatörden (kalorifer peteği) geçirir; fan bu petek üzerinden havayı ısıtarak kabine üfler. Bu nedenle motor çalışma sıcaklığına ulaşmadan iç ısıtma tam verim vermez.',
    whyWrong: [
      'Akü elektrik sağlar; kabin ısısının kaynağı değildir.',
      'Fren balataları ve lastikler ısıtma sisteminin ısı kaynağı değildir.',
    ],
    objective: 'Kalorifer sisteminin ısıyı motor soğutma suyundan aldığını kavramak.',
    tags: ['sogutma-sistemi', 'kalorifer', 'isitma'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-312',
    subject: 'motor',
    topic: 'sogutma-sistemi',
    difficulty: 'orta',
    stem: 'Soğutma sisteminde su kaçağı olduğunu düşündüren belirti aşağıdakilerden hangisidir?',
    options: [
      'Genleşme deposundaki su seviyesinin sık sık azalması ve park yerinde zemine sıvı damlaması',
      'Farların daha parlak yanması',
      'Lastik dişinin derinleşmesi',
      'Egzoz sesinin kısılması',
    ],
    answerIndex: 0,
    explanation:
      'Soğutma suyunun sürekli eksilmesi ve aracın altında sıvı izleri; hortum, radyatör ya da bağlantılarda kaçak olabileceğini gösterir. Kaçak giderilmezse su azalır ve motor hararet yapar; bu yüzden seviye takip edilip kaçağın kaynağı bulunarak onarılmalıdır.',
    whyWrong: [
      'Farların parlaklığı ve egzoz sesi soğutma kaçağını göstermez.',
      'Lastik dişi kullanımla derinleşmez, aşınarak azalır; soğutma kaçağıyla ilgisi yoktur.',
    ],
    objective: 'Soğutma suyu kaçağının belirtilerini (seviye düşüşü, zemine damlama) kavramak.',
    tags: ['sogutma-sistemi', 'su-kacagi', 'hararet'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-313',
    subject: 'motor',
    topic: 'lastikler',
    difficulty: 'orta',
    stem: 'Diş derinliği yeterli görünse bile eski lastiklerin değiştirilmesi gerekebilmesinin nedeni nedir?',
    options: [
      'Lastik yaşlandıkça daha güçlü tutunur',
      'Eski lastik yakıt üretir',
      'Lastik markası her yıl değişir',
      'Kauçuk zamanla sertleşip çatlar; esnekliğini yitirdiği için yol tutuşu ve güvenliği azalır',
    ],
    answerIndex: 3,
    explanation:
      'Lastiğin kauçuk yapısı yıllar içinde hava, ısı ve güneşin etkisiyle sertleşir; yanaklarında çatlaklar oluşur. Diş derinliği yeterli olsa bile yaşlanmış lastik esnekliğini kaybederek yol tutuşunu ve frenlemeyi olumsuz etkiler; bu yüzden üretim tarihi de dikkate alınır.',
    whyWrong: [
      'Lastik yaşlandıkça tutuşu artmaz, tersine azalır.',
      'Lastik yakıt üretmez; markanın her yıl değişmesi bir güvenlik ölçütü değildir.',
    ],
    objective: 'Lastik yaşlanmasının (kauçuk sertleşmesi) güvenliğe etkisini kavramak.',
    tags: ['lastikler', 'lastik-yasi', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-314',
    subject: 'motor',
    topic: 'lastikler',
    difficulty: 'zor',
    stem: 'Islak yolda yüksek hızda lastik ile zemin arasına su tabakası girip aracın tutuşunu kaybetmesine ne ad verilir ve bu risk nasıl azaltılır?',
    options: [
      'Buna hararet denir; klima açılarak azalır',
      'Buna su kızağı (aquaplaning) denir; hızı düşürmek ve yeterli diş derinliğine sahip lastik kullanmak riski azaltır',
      'Buna balans denir; akü değişimiyle azalır',
      'Buna rölanti denir; far açarak azalır',
    ],
    answerIndex: 1,
    explanation:
      'Yüksek hızda ve su birikintili yolda lastik, suyu yeterince tahliye edemeyince zeminle teması kesilir; araç su üstünde kayar (su kızağı / aquaplaning) ve fren ile direksiyon etkisiz kalır. Hızı düşürmek ve yeterli diş derinliğine sahip lastik kullanmak bu riski azaltır.',
    whyWrong: [
      'Bu olay hararet, balans veya rölanti değildir.',
      'Klima, akü değişimi veya far açmak su kızağı riskini azaltmaz; belirleyici olan hız ve lastik diş derinliğidir.',
    ],
    objective: 'Su kızağı (aquaplaning) olayını ve önleme yöntemini kavramak.',
    tags: ['lastikler', 'aquaplaning', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-315',
    subject: 'motor',
    topic: 'lastikler',
    difficulty: 'kolay',
    stem: 'Lastiklerin belirli aralıklarla ön-arka yer değiştirmesinin (lastik rotasyonu) temel amacı nedir?',
    options: [
      'Lastik renklerini eşitlemek',
      'Yakıt tüketimini tamamen sıfırlamak',
      'Lastiklerin daha dengeli aşınmasını sağlayıp ömrünü uzatmak',
      'Aküyü şarj etmek',
    ],
    answerIndex: 2,
    explanation:
      'Ön ve arka lastikler, çeken ve yönlendiren aksa bağlı olarak farklı oranlarda aşınır. Belirli aralıklarla yerlerinin değiştirilmesi aşınmayı daha dengeli hâle getirir; böylece lastikler daha uzun ömürlü olur ve yol tutuş dengesi korunur.',
    whyWrong: [
      'Rotasyonun renk eşitleme ya da akü şarjıyla ilgisi yoktur.',
      'Yakıt tüketimini sıfırlamaz; amacı dengeli aşınma ve ömürdür.',
    ],
    objective: 'Lastik rotasyonunun dengeli aşınma ve ömür amacını kavramak.',
    tags: ['lastikler', 'lastik-rotasyonu', 'bakim'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-316',
    subject: 'motor',
    topic: 'aku-elektrik',
    difficulty: 'orta',
    stem: 'Bakım gerektiren (kapaklı) bir akünün sıvı seviyesi düştüğünde eklenmesi gereken nedir?',
    options: ['Musluk suyu', 'Saf/distile su (üretici sınırına kadar)', 'Motor yağı', 'Antifriz'],
    answerIndex: 1,
    explanation:
      'Kapaklı (bakımlı) akülerde elektrolit seviyesi zamanla düşebilir; plakaların üstünü örtecek şekilde yalnızca saf/distile su eklenir. Musluk suyundaki kireç ve mineraller plakalara zarar verir. Bakımsız (kapalı) akülerde ise dışarıdan su eklenmez.',
    whyWrong: [
      'Musluk suyundaki mineraller akü plakalarına zarar verir.',
      'Motor yağı ve antifriz aküye eklenmez; elektrolit için uygun değildir.',
    ],
    objective: 'Bakımlı aküye yalnızca saf/distile su eklendiğini kavramak.',
    tags: ['aku-elektrik', 'elektrolit', 'bakim'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-317',
    subject: 'motor',
    topic: 'aku-elektrik',
    difficulty: 'orta',
    stem: 'Atan bir sigortanın yerine daha yüksek amperajlı (daha güçlü) bir sigorta takmak neden sakıncalıdır?',
    options: [
      'Farlar tamamen söner',
      'Motor yağı azalır',
      'Lastik basıncı düşer',
      'Devre aşırı akıma karşı korunmaz; kablolar aşırı ısınıp erime ve yangın riski doğar',
    ],
    answerIndex: 3,
    explanation:
      'Sigorta, devreyi belirli bir akım sınırında koruyacak şekilde seçilir. Daha yüksek amperajlı sigorta takılırsa aşırı akımda atmaz; kablolar aşırı ısınabilir, yalıtım erir ve yangın çıkabilir. Sigorta her zaman üreticinin belirttiği değerde kullanılmalıdır.',
    whyWrong: [
      'Yüksek amperajlı sigorta farları söndürmez; asıl sorun korumanın ortadan kalkmasıdır.',
      'Sigorta değeri motor yağı ya da lastik basıncıyla ilgili değildir.',
    ],
    objective: 'Sigortanın doğru amperajda kullanılmasının güvenlik gerekçesini kavramak.',
    tags: ['aku-elektrik', 'sigorta', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-318',
    subject: 'motor',
    topic: 'far-aydinlatma',
    difficulty: 'orta',
    stem: 'Sis farlarının kullanımıyla ilgili doğru ifade aşağıdakilerden hangisidir?',
    options: [
      'Her zaman, açık ve güneşli havada da yakılmalıdır',
      'Yalnızca sis, yoğun yağış veya kar gibi görüşün ciddi biçimde azaldığı durumlarda kullanılır',
      'Gündüz görüşü açık yolda sürekli yakmak gerekir',
      'Sadece park hâlinde kullanılır',
    ],
    answerIndex: 1,
    explanation:
      'Sis farları; sis, yoğun yağmur veya kar nedeniyle görüşün belirgin biçimde azaldığı durumlarda yolu ve aracı daha görünür kılmak için kullanılır. Görüş normalken, özellikle arka sis farı, arkadaki sürücüleri rahatsız edip yanıltacağından yakılmamalıdır.',
    whyWrong: [
      'Açık havada sis farı yakmak gereksizdir ve diğer sürücüleri rahatsız eder.',
      'Sis farı bir park lambası değildir; açık yolda sürekli yakılması amacına aykırıdır.',
    ],
    objective: 'Sis farlarının yalnızca düşük görüş koşullarında kullanıldığını kavramak.',
    tags: ['far-aydinlatma', 'sis-fari', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-319',
    subject: 'motor',
    topic: 'far-aydinlatma',
    difficulty: 'kolay',
    stem: 'Farların, stop ve sinyal lambalarının düzenli kontrol edilip temiz tutulmasının temel nedeni nedir?',
    options: [
      'Yolu iyi aydınlatıp aracın niyetini diğer sürücülere doğru göstererek görüş ve görünürlük güvenliğini sağlamak',
      'Motor gücünü artırmak',
      'Yakıt deposunu büyütmek',
      'Lastik ömrünü uzatmak',
    ],
    answerIndex: 0,
    explanation:
      'Farlar yolu aydınlatır; stop ve sinyal lambaları ise sürücünün duracağını ya da döneceğini diğerlerine bildirir. Kirli, yanık ya da çalışmayan lambalar hem görüşü hem görünürlüğü azaltarak kaza riskini artırır; bu yüzden düzenli kontrol edilmelidir.',
    whyWrong: [
      'Aydınlatmanın motor gücü ya da yakıt deposu ile ilgisi yoktur.',
      'Lambaların temizliği lastik ömrünü belirlemez.',
    ],
    objective:
      'Aydınlatma ve sinyal lambalarının görüş-görünürlük güvenliğindeki önemini kavramak.',
    tags: ['far-aydinlatma', 'sinyal', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-320',
    subject: 'motor',
    topic: 'motor-calismama',
    difficulty: 'zor',
    stem: 'Marş motoru motoru çevirdiği (marş dönüyor) hâlde motor bir türlü çalışmıyorsa olası neden aşağıdakilerden hangisidir?',
    options: [
      'Lastik basıncının yüksek olması',
      'Farların açık kalması',
      'Motora yakıt gelmemesi veya ateşleme sisteminde arıza olması (yakıt bitmiş, buji/enjeksiyon sorunu vb.)',
      'Amortisörlerin eskimesi',
    ],
    answerIndex: 2,
    explanation:
      'Marşın dönmesi akü ve marş motorunun iş gördüğünü gösterir; buna rağmen motor çalışmıyorsa sorun genellikle yakıt veya ateşleme tarafındadır. Yakıt bitmiş, yakıt pompası/enjeksiyon arızalı ya da (benzinlide) buji-ateşleme sorunlu olabilir; kontrol bu yönde yapılır.',
    whyWrong: [
      'Lastik basıncı ve amortisör motorun çalışmamasıyla ilgili değildir.',
      'Farların açık olması aküyü tüketir; ancak marş zaten dönüyorsa sorun yakıt/ateşleme tarafındadır.',
    ],
    objective:
      'Marş döndüğü hâlde çalışmayan motorun yakıt/ateşleme kaynaklı olabileceğini kavramak.',
    tags: ['motor-calismama', 'yakit-sistemi', 'atesleme'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-321',
    subject: 'motor',
    topic: 'motor-calismama',
    difficulty: 'orta',
    stem: 'Kontak anahtarı dönmüyor ve araç çalışmıyorsa, direksiyonun hafifçe sağa-sola oynatılması hangi durumu çözebilir?',
    options: [
      'Lastik patlağını',
      'Yakıtın bitmesini',
      'Motor hararetini',
      'Anahtarla birlikte devreye giren direksiyon kilidinin anahtarı bloke etmesini',
    ],
    answerIndex: 3,
    explanation:
      'Araç park edilip direksiyon çevrildiğinde direksiyon kilidi devreye girip anahtarın dönmesini engelleyebilir. Direksiyon hafifçe sağa-sola oynatılırken anahtar çevrilirse kilit çözülür ve kontak açılır. Bu bir arıza değil, güvenlik amaçlı bir mekanizmadır.',
    whyWrong: [
      'Lastik patlağı, yakıt bitmesi veya hararet anahtarın dönmemesine yol açmaz.',
      'Bu durum direksiyon kilidinden kaynaklanır; diğer seçenekler bambaşka sorunlardır.',
    ],
    objective: 'Anahtarın dönmemesinin direksiyon kilidinden kaynaklanabileceğini kavramak.',
    tags: ['motor-calismama', 'direksiyon-kilidi', 'kontak'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-322',
    subject: 'motor',
    topic: 'periyodik-bakim',
    difficulty: 'kolay',
    stem: 'Aracın üreticinin belirttiği aralıklarla periyodik bakıma götürülmesinin temel amacı nedir?',
    options: [
      'Aracın rengini korumak',
      'Aşınan parçaların zamanında değişmesini sağlayıp arızaları önlemek, güvenliği ve araç ömrünü korumak',
      'Yalnızca aracın azami hızını artırmak',
      'Sadece kullanılan yakıt markasını değiştirmek',
    ],
    answerIndex: 1,
    explanation:
      'Periyodik bakımda yağ, filtreler, fren, lastik ve kayış gibi parçalar kontrol edilip gerektiğinde değiştirilir. Böylece arızalar büyümeden önlenir, güvenlik sağlanır ve aracın ömrü uzar. Düzenli bakım hem güvenli hem ekonomik sürüşün temelidir.',
    whyWrong: [
      'Bakımın amacı rengi korumak ya da yakıt markası değiştirmek değildir.',
      'Bakım aracı yalnızca hızlandırmaz; asıl amaç güvenlik ve arıza önlemedir.',
    ],
    objective: 'Periyodik bakımın arıza önleme, güvenlik ve araç ömrü amacını kavramak.',
    tags: ['periyodik-bakim', 'bakim', 'guvenlik'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-323',
    subject: 'motor',
    topic: 'periyodik-bakim',
    difficulty: 'kolay',
    stem: 'Ön cam yıkama suyu ve silecek lastiklerinin düzenli kontrol edilmesi neden önemlidir?',
    options: [
      'Temiz cam ve iyi silecek, sürüş sırasında net görüş sağlayarak güvenliği artırır',
      'Motor gücünü artırır',
      'Aküyü şarj eder',
      'Yakıt tüketimini sıfırlar',
    ],
    answerIndex: 0,
    explanation:
      'Cam yıkama suyu ve sağlam silecek lastikleri; tozlu, çamurlu ya da yağışlı havada camı temizleyerek sürücünün önünü net görmesini sağlar. Eskimiş silecek iz bırakır, boş cam suyu haznesi ise camı temizleyemez; her ikisi de görüşü bozarak güvenliği tehlikeye atar.',
    whyWrong: [
      'Cam suyu ve sileceğin motor gücü ya da akü şarjıyla ilgisi yoktur.',
      'Yakıt tüketimini sıfırlamaz; katkısı net görüş sağlamasıdır.',
    ],
    objective: 'Cam suyu ve silecek bakımının net görüş yoluyla güvenliğe katkısını kavramak.',
    tags: ['periyodik-bakim', 'silecek', 'gorus'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-324',
    subject: 'motor',
    topic: 'yakit-sistemi',
    difficulty: 'zor',
    stem: 'Dizel (mazotlu) bir araca yanlışlıkla benzin konulduğu fark edildiğinde en doğru davranış nedir?',
    options: [
      'Depoyu ağzına kadar doldurup normal şekilde yola devam etmek',
      'Depoya bir miktar su ekleyerek karışımı dengelemek',
      'Motoru çalıştırmadan aracı çektirip depoyu boşalttırmak ve yakıt sistemini temizletmek',
      'Aracı gaza yükleyerek yanlış yakıtı bir an önce tüketmek',
    ],
    answerIndex: 2,
    explanation:
      'Dizel motor benzinle çalışacak şekilde tasarlanmamıştır; yanlış yakıt, yakıt pompası ve enjeksiyon sistemine ciddi zarar verebilir. En doğru davranış motoru çalıştırmadan (mümkünse kontağı bile açmadan) aracı servise çektirmek, depoyu boşalttırıp sistemi temizletmektir.',
    whyWrong: [
      'Yanlış yakıtla yola devam etmek yakıt sistemine ağır ve pahalı hasar verebilir.',
      'Depoya su eklemek ya da yakıtı gaza yükleyerek tüketmeye çalışmak sorunu büyütür.',
    ],
    objective: 'Yanlış yakıt alındığında motoru çalıştırmadan müdahale gerektiğini kavramak.',
    tags: ['yakit-sistemi', 'yanlis-yakit', 'ariza'],
    review: 'draft',
    sourceRef: SRC,
  },
];
