/**
 * ÖZGÜN direksiyon (uygulama) soruları — 2. genişletme (Program 1 — Sürüş Akademisi).
 * Kaynak = MTSK direksiyon eğitimi + MEB direksiyon sınavı uygulaması; KENDİ İFADEMİZLE.
 */
import type { QuestionInput } from '@ea/content-schema';

const SRC = 'MTSK direksiyon eğitimi ve MEB direksiyon sınavı uygulaması (özgün ifade)';

export const PRATIK_QUESTIONS_2: QuestionInput[] = [
  {
    id: 'pratik-201',
    subject: 'pratik',
    topic: 'arac-kontrol',
    difficulty: 'orta',
    stem: 'Sürüş öncesi koltuk ayarında ayak pedalları ve direksiyon açısından doğru oturuş nasıl olmalıdır?',
    options: [
      'Koltuk mümkün olduğunca geride, kollar tamamen gergin olacak biçimde uzakta olmalı',
      'Debriyaj sonuna kadar basıldığında diz tam kilitlenmeli, sırt öne eğik olmalı',
      'Debriyaj sonuna kadar basıldığında dizde hafif kıvrım kalmalı, bilekler direksiyonun üst kenarına rahat uzanmalı',
      'Koltuk direksiyona yapışık, göğüs korna hizasında olmalı',
    ],
    answerIndex: 2,
    explanation:
      'Doğru oturuşta pedallar sonuna kadar basıldığında dizde hafif bir kıvrım kalır; bu, pedallara tam güç aktarmayı ve yorulmadan hâkimiyeti sağlar. Direksiyonda ise bileklerin üst kenara değecek uzaklıkta olması, kolların rahat ve kıvrımlı kalmasını sağlar. Böylece ani manevralarda kollar kilitlenmez.',
    whyWrong: [
      'Kollar tamamen gergin ve koltuk çok geride olursa direksiyona güç aktarımı ve pedal kontrolü zayıflar.',
      'Koltuğun direksiyona yapışık olması hava yastığı riski oluşturur ve hareket alanını kısıtlar.',
    ],
    objective:
      'Sürüş öncesi pedal ve direksiyon mesafesine göre güvenli oturuş ayarını yapabilmek.',
    tags: ['arac-kontrol', 'koltuk-ayari', 'oturus'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-202',
    subject: 'pratik',
    topic: 'motor-calistirma',
    difficulty: 'kolay',
    stem: 'Manuel vitesli araçta kontak anahtarını marş konumuna getirmeden hemen önce hangi hazırlık yapılmalıdır?',
    options: [
      'El freni çekili, vites boşta ve debriyaj basılıyken çalıştırmak',
      'Vites birinci konumdayken debriyaja basmadan marşa basmak',
      'El freni indirilmiş, vites geride iken marşa basmak',
      'Gaz pedalı sonuna kadar basılıyken marşa basmak',
    ],
    answerIndex: 0,
    explanation:
      'Motoru güvenle çalıştırmak için el freni çekili olmalı, vites boşta bulunmalı ve debriyaja basılmalıdır. Bu üçlü, marş anında aracın istem dışı hareket etmesini engeller ve marş motorunun yükünü azaltır. Debriyaja basmak, marş sırasında şanzımanı motordan ayırır.',
    whyWrong: [
      'Vites takılıyken debriyaja basmadan marşa basmak aracı öne ya da geri sıçratabilir.',
      'Gaz sonuna kadar basılı çalıştırma motoru gereksiz yorar ve kontrolsüz kalkışa yol açar.',
    ],
    objective:
      'Motor çalıştırma öncesi el freni, vites ve debriyaj güvenlik kontrolünü sıralayabilmek.',
    tags: ['motor-calistirma', 'el-freni', 'debriyaj'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-203',
    subject: 'pratik',
    topic: 'hareket',
    difficulty: 'orta',
    stem: 'Park hâlindeki araçla sol şeride katılmak için harekete geçerken izlenmesi gereken doğru sıra nedir?',
    options: [
      'Doğrudan direksiyonu sola kırıp şeride girmek',
      'Önce sola kır, sonra aynaya bakıp sinyal vermek',
      'Sadece iç dikiz aynasına bakıp hızla çıkmak',
      'Sol sinyali ver, iç ve sol dış aynayı kontrol et, sol omuz üstünden kör noktayı gör, uygunsa yavaşça şeride gir',
    ],
    answerIndex: 3,
    explanation:
      'Trafiğe katılırken önce niyeti bildirmek için sinyal verilir, ardından iç ve dış aynalarla arkadan gelen araçlar izlenir. Aynaların görmediği kör nokta ise sol omuz üstünden dönülerek kontrol edilir. Tüm alan boşsa araç yavaşça ve akışa uygun hızla şeride sokulur.',
    whyWrong: [
      'Aynalara ve kör noktaya bakmadan doğrudan şeride girmek arkadan gelen araçla çarpışma riski doğurur.',
      'Yalnızca iç dikiz aynası kör noktayı göstermez; yandaki aracı fark etmeden çıkmak tehlikelidir.',
    ],
    objective: 'Duraktan trafiğe katılırken sinyal-ayna-kör nokta sıralamasını uygulayabilmek.',
    tags: ['hareket', 'sinyal', 'kor-nokta'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-204',
    subject: 'pratik',
    topic: 'debriyaj',
    difficulty: 'orta',
    stem: 'Kalkış sırasında debriyajı çok hızlı bırakmanın en olası sonucu aşağıdakilerden hangisidir?',
    options: [
      'Araç yumuşak ve sarsıntısız kalkar',
      'Motor tekler ya da araç zıplayarak stop eder',
      'Yakıt tüketimi belirgin biçimde azalır',
      'Direksiyon kilitlenir',
    ],
    answerIndex: 1,
    explanation:
      'Debriyaj pedalını kavrama noktasını hissetmeden aniden bırakmak, motor devrinin tekerlek yüküne uyum sağlamasına fırsat vermez; motor tekler ve çoğu zaman araç zıplayarak stop eder. Doğru kalkışta pedal kavrama noktasına kadar yavaş bırakılıp az gazla eşlik edilir.',
    whyWrong: [
      'Debriyajın ani bırakılması sarsıntısız kalkış değil, tam tersine sarsıntı ve stop üretir.',
      'Bu hareketin yakıt tüketimi veya direksiyon kilidi ile doğrudan bir ilgisi yoktur.',
    ],
    objective: 'Debriyajı ani bırakmanın motoru teklettiğini ve stop ettirdiğini kavramak.',
    tags: ['debriyaj', 'kalkis', 'motor-stop'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-205',
    subject: 'pratik',
    topic: 'rampa',
    difficulty: 'zor',
    stem: 'Yokuşta el freni çekiliyken durmuş araçla geri kaymadan kalkış için doğru koordinasyon nedir?',
    options: [
      'El frenini indir, sonra debriyaja hiç dokunmadan sadece gaza yüklen',
      'Debriyajı tamamen bırak, ardından el frenini indir',
      'Debriyajı kavrama noktasına getir, hafif gaz ver, aracın öne yüklendiğini hissedince el frenini yavaşça indir',
      'Önce gaz pedalını dibe bas, sonra el frenini bırakıp debriyajı çek',
    ],
    answerIndex: 2,
    explanation:
      'Rampada geri kaçmadan kalkmak için debriyaj kavrama noktasına getirilir ve hafif gazla motor yüklenir; aracın burnunun hafifçe kalktığı hissedildiğinde el freni yavaşça indirilir. Böylece motorun çekişi devreye girmeden fren bırakılmadığı için araç geriye kaymaz.',
    whyWrong: [
      'Debriyaja dokunmadan yalnız gaza yüklenmek çekiş oluşturmaz ve fren bırakılınca araç geri kayar.',
      'Debriyajı tamamen bırakıp sonra fren indirmek çoğu zaman motoru teklettirir ve stop ettirir.',
    ],
    objective: 'Yokuş kalkışında debriyaj-gaz-el freni koordinasyonuyla geri kaymayı önleyebilmek.',
    tags: ['rampa', 'el-freni', 'debriyaj'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-206',
    subject: 'pratik',
    topic: 'geri-park',
    difficulty: 'zor',
    stem: 'Bir park cebine geri geri girerken direksiyon ve ayna kullanımı için doğru yaklaşım nedir?',
    options: [
      'Geri giderken yalnızca öne bakmak yeterlidir',
      'Geri giderken arka cama ve her iki dış aynaya sırayla bakıp direksiyonu boşluğun hizasına göre kırmak',
      'Direksiyonu tek seferde sonuna kadar kırıp gaz vermek',
      'Geri hareketi hızlı yapıp son anda frene basmak',
    ],
    answerIndex: 1,
    explanation:
      'Geri park ederken görüş sürekli arka cam ile iki dış ayna arasında paylaştırılır; aracın arkası ve tekerleklerin boşluğa göre konumu izlenir. Direksiyon, boşluğun hizasına göre kademeli kırılır ve araç düşük hızda, debriyajla kontrol edilerek yönlendirilir.',
    whyWrong: [
      'Yalnızca öne bakmak, aracın arkasındaki engelleri ve şerit çizgilerini görmeyi engeller.',
      'Direksiyonu tek hamlede sonuna kadar kırıp gaz vermek aracı kontrolsüz ve hatalı açıyla sokar.',
    ],
    objective:
      'Geri park manevrasında ayna-arka cam paylaşımı ve kademeli direksiyon kullanımını uygulayabilmek.',
    tags: ['geri-park', 'ayna-kontrol', 'manevra'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-207',
    subject: 'pratik',
    topic: 'paralel-park',
    difficulty: 'zor',
    stem: 'Yol kenarında iki araç arasına paralel park yaparken referans alınması gereken ilk adım nedir?',
    options: [
      'Önündeki araca çok yakın durup direksiyonu hemen kırmak',
      'Boşluğu ölçmeden geri geri girmeye başlamak',
      'Park boşluğunu geçip sinyal vermeden durmak',
      'Sağ sinyal ver, boşluğun önündeki araçla yaklaşık yan yana ve uygun aralıkta dur, sonra geri manevraya başla',
    ],
    answerIndex: 3,
    explanation:
      'Paralel parkta ilk adım sağ sinyalle niyeti bildirip, boşluğun önündeki araçla yaklaşık yan yana ve bir aracın genişliği kadar aralık bırakarak durmaktır. Bu referans konumu, geri manevrada direksiyonun doğru anda kırılmasını ve aracın boşluğa düzgün açıyla oturmasını sağlar.',
    whyWrong: [
      'Öndeki araca çok yakın durup hemen kırmak, aracın boşluğa yanlış açıyla girmesine yol açar.',
      'Boşluğu ölçmeden ve referans almadan geri girmek hatalı ve tehlikeli park doğurur.',
    ],
    objective: 'Paralel park öncesi sinyal ve referans konumlanmasını doğru kurabilmek.',
    tags: ['paralel-park', 'sinyal', 'referans'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-208',
    subject: 'pratik',
    topic: 'donel-kavsak',
    difficulty: 'orta',
    stem: 'Dönel kavşağa (göbekli kavşak) girerken temel yol verme kuralı nedir?',
    options: [
      'Kavşak içinde dönmekte olan araçlara yol ver, uygun boşlukta gir',
      'Kavşağa girecek araçların hepsi sana yol vermek zorundadır',
      'Kavşağa her zaman durmadan ve hız kesmeden girilir',
      'Kavşak içinde önce sen geçersin, içeridekiler bekler',
    ],
    answerIndex: 0,
    explanation:
      'Dönel kavşakta öncelik, ada etrafında dönmekte olan araçlara aittir. Kavşağa girecek sürücü, soldan gelen ve hâlihazırda dönen araçlara yol verir; ancak uygun ve güvenli boşluk oluştuğunda kavşağa girer. Bu kural, kavşak içi akışın kilitlenmeden sürmesini sağlar.',
    whyWrong: [
      'Kavşağa girenlerin öncelikli olduğu düşüncesi yanlıştır; öncelik içeride dönenlerdedir.',
      'Hız kesmeden veya içeridekini bekletmeden girmek çarpışmaya ve akış kilitlenmesine yol açar.',
    ],
    objective: 'Dönel kavşakta içeride dönen araca yol verme önceliğini kavramak.',
    tags: ['donel-kavsak', 'yol-verme', 'oncelik'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-209',
    subject: 'pratik',
    topic: 'ayna-kontrol',
    difficulty: 'kolay',
    stem: 'Sürüş sırasında dikiz ve yan aynalar ne sıklıkla kontrol edilmelidir?',
    options: [
      'Yalnızca dönüş yapılacağı anda bir kez',
      'Sadece park ederken',
      'Düzenli aralıklarla ve her manevra, şerit değişimi ile yavaşlama öncesinde',
      'Aynalar ayarlandıktan sonra yola çıkınca hiç bakmaya gerek yoktur',
    ],
    answerIndex: 2,
    explanation:
      'Aynalar, sürücünün trafiği sürekli izlemesini sağlayan araçlardır; bu yüzden düzenli aralıklarla ve özellikle her şerit değişimi, dönüş, yavaşlama ya da park manevrası öncesinde kontrol edilmelidir. Böylece arkadan ve yandan gelen araçların konumu her an bilinir.',
    whyWrong: [
      'Aynaya yalnızca dönüş anında bakmak, o ana kadar oluşan trafik değişimini kaçırmaya yol açar.',
      'Aynaları ayarlayıp bir daha bakmamak, kör nokta ve arka trafik farkındalığını tamamen ortadan kaldırır.',
    ],
    objective: 'Aynaların düzenli ve manevra öncesi kontrol alışkanlığını benimsemek.',
    tags: ['ayna-kontrol', 'trafik-takip', 'manevra'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-210',
    subject: 'pratik',
    topic: 'kor-nokta',
    difficulty: 'orta',
    stem: 'Aynaların göremediği kör nokta, şerit değiştirmeden önce nasıl güvenle kontrol edilir?',
    options: [
      'İç dikiz aynasına biraz daha uzun bakarak',
      'Gitmek istenen yöndeki omuz üstünden kısa bir bakışla, direksiyon hâkimiyeti korunarak',
      'Kornaya basıp yandaki aracı uyararak',
      'Camı açıp kafayı tamamen dışarı çıkararak',
    ],
    answerIndex: 1,
    explanation:
      'Kör nokta, yan aynaların kapsamadığı ve aracın hemen arka yan tarafında kalan bölgedir. Bu alan yalnızca gidilecek yöndeki omuz üstünden atılan kısa bir bakışla görülebilir. Bakış kısa tutulur ve direksiyon hâkimiyeti korunur ki araç istemsizce yön değiştirmesin.',
    whyWrong: [
      'İç dikiz aynası kör noktayı göstermez; ne kadar uzun bakılsa da yandaki araç görülmez.',
      'Kornaya basmak kör noktadaki aracı görmeyi sağlamaz; kontrol yalnızca omuz üstü bakışla yapılır.',
    ],
    objective: 'Şerit değişimi öncesi kör noktayı omuz üstü bakışla kontrol edebilmek.',
    tags: ['kor-nokta', 'seritdegistirme', 'ayna-kontrol'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-211',
    subject: 'pratik',
    topic: 'vites',
    difficulty: 'kolay',
    stem: 'Aracın hızı düşerken motorun teklememesi için vites kullanımı nasıl olmalıdır?',
    options: [
      'Hız düşse de yüksek viteste kalınır',
      'Vites hiç değiştirilmeden fren tamamen kullanılır',
      'Doğrudan boşa alınıp öyle gidilir',
      'Hıza uygun olarak kademeli biçimde küçük viteslere geçilir',
    ],
    answerIndex: 3,
    explanation:
      'Araç yavaşlarken motor devri düşer; hıza uygun küçük vitese kademeli geçilmezse motor tekler ve stop edebilir. Doğru teknik, hız azaldıkça vitesi kademeli olarak düşürmek, böylece motor devrini uygun aralıkta tutup çekiş ve hâkimiyeti korumaktır.',
    whyWrong: [
      'Hız düşerken yüksek viteste kalmak motoru tekletir ve stop ile sonuçlanabilir.',
      'Uzun süre boşta gitmek motor freninden yararlanmayı engeller ve hâkimiyeti zayıflatır.',
    ],
    objective: 'Yavaşlarken hıza uygun kademeli vites düşürmeyi uygulayabilmek.',
    tags: ['vites', 'hiz-kontrol', 'motor-stop'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-212',
    subject: 'pratik',
    topic: 'durus',
    difficulty: 'orta',
    stem: 'Trafik ışığında güvenli ve düzgün bir duruş için doğru fren-debriyaj kullanımı nedir?',
    options: [
      'Önce frenle hızı düşür, araç neredeyse duracakken debriyaja bas ki motor stop etmesin',
      'Duruştan çok önce debriyaja basıp uzun mesafe boşta süzülmek',
      'Sadece el freniyle sert biçimde durmak',
      'Fren yerine motoru stop ettirerek durmak',
    ],
    answerIndex: 0,
    explanation:
      'Düzgün duruşta önce fren pedalıyla hız kademeli düşürülür; araç neredeyse duracak hıza geldiğinde debriyaja basılır ki motor stop etmesin. Debriyaja çok erken basıp uzun süzülmek motor freninden yararlanmayı engeller ve hâkimiyeti azaltır.',
    whyWrong: [
      'Duruştan çok önce debriyaja basıp boşta süzülmek motor frenini devre dışı bırakır ve fren mesafesini uzatabilir.',
      'Yalnız el freniyle sert durmak tekerleklerin kilitlenmesine ve savrulmaya yol açabilir.',
    ],
    objective: 'Duruşta fren ile debriyajın doğru sıralı kullanımını uygulayabilmek.',
    tags: ['durus', 'debriyaj', 'fren'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-213',
    subject: 'pratik',
    topic: 'sinyal',
    difficulty: 'kolay',
    stem: 'Şerit değiştirmeden veya dönüşten ne zaman sinyal verilmelidir?',
    options: [
      'Manevra tamamlandıktan sonra',
      'Tam dönüş anında, direksiyon kırılırken',
      'Manevradan yeterince önce, diğer sürücülerin fark edebileceği bir zamanda',
      'Sinyal vermek zorunlu değildir, isteğe bağlıdır',
    ],
    answerIndex: 2,
    explanation:
      'Sinyal, sürücünün niyetini önceden bildiren bir iletişim aracıdır; bu yüzden manevradan yeterince önce, arkadaki ve karşıdaki sürücülerin tepki verebileceği bir zamanda verilmelidir. Geç verilen ya da hiç verilmeyen sinyal, diğer sürücülerin hazırlanmasını engeller.',
    whyWrong: [
      'Manevra bittikten sonra sinyal vermek hiçbir işe yaramaz; amacı önceden haber vermektir.',
      'Sinyal isteğe bağlı değildir; yön değiştirmeden önce vermek kuraldır ve sınavda eksikliği puan kaybettirir.',
    ],
    objective: 'Sinyalin manevradan yeterince önce verilmesi gerektiğini kavramak.',
    tags: ['sinyal', 'seritdegistirme', 'iletisim'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-214',
    subject: 'pratik',
    topic: 'yol-verme',
    difficulty: 'orta',
    stem: 'Kontrolsüz (ışıksız, levhasız) ve eşdeğer yolların kesiştiği bir kavşakta genel yol verme kuralı nedir?',
    options: [
      'Soldan gelene yol verilir',
      'Sağdan gelen araca yol verilir',
      'Büyük araca her zaman öncelik verilir',
      'Hız yapan araç her zaman geçer',
    ],
    answerIndex: 1,
    explanation:
      'Trafik işareti ve ışığın bulunmadığı eşdeğer yolların kesiştiği kavşakta genel kural, sağdan gelen aracın geçiş üstünlüğüne sahip olmasıdır. Sürücü sağındaki araca yol verir. Bu kural, kavşakta kimin önce geçeceği konusunda ortak ve öngörülebilir bir düzen sağlar.',
    whyWrong: [
      'Soldan gelene yol vermek kuralın tersidir; öncelik sağdaki araçtadır.',
      'Aracın büyüklüğü ya da hızı geçiş üstünlüğü belirlemez; ölçüt yön ve kurallardır.',
    ],
    objective: 'Kontrolsüz kavşakta sağdan gelene yol verme kuralını uygulayabilmek.',
    tags: ['yol-verme', 'kavsak-donus', 'oncelik'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-215',
    subject: 'pratik',
    topic: 'manevra',
    difficulty: 'orta',
    stem: 'Dar bir sokakta üç hamleli (geri dönüş) manevra yapılırken güvenlik açısından en önemli davranış nedir?',
    options: [
      'Manevrayı olabildiğince hızlı bitirmek',
      'Yalnızca öne bakıp direksiyonu çevirmek',
      'Aynalara hiç bakmadan sezgiyle dönmek',
      'Her hamlede yayaları ve gelen araçları kontrol edip düşük hızda, aynaları kullanarak ilerlemek',
    ],
    answerIndex: 3,
    explanation:
      'Üç hamleli dönüş, aracı dar bir alanda ileri-geri hareketlerle ters yöne çevirme manevrasıdır. En kritik davranış, her hamle öncesi ve sırasında yayaları ile yaklaşan araçları kontrol etmek, aynaları kullanmak ve düşük hızda ilerlemektir. Böylece manevra çevreyi tehlikeye atmadan tamamlanır.',
    whyWrong: [
      'Manevrayı hızlı bitirmeye çalışmak kontrolü zorlaştırır ve çarpışma riskini artırır.',
      'Yalnızca öne bakmak ya da aynaları kullanmamak arkadaki engel ve araçları görmeyi engeller.',
    ],
    objective:
      'Dar alanda dönüş manevrasında çevre kontrolü ve düşük hız disiplinini uygulayabilmek.',
    tags: ['manevra', 'ayna-kontrol', 'hiz-kontrol'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-216',
    subject: 'pratik',
    topic: 'sinav-hata',
    difficulty: 'zor',
    stem: 'Direksiyon sınavında bir hareketin ağır (elemeli) hata sayılmasının temel mantığı nedir?',
    options: [
      'Hareket can ve mal güvenliğini doğrudan tehlikeye atıyorsa ağır hata sayılır',
      'Yalnızca aracın camı kirliyse ağır hata olur',
      'Sadece sürücünün heyecanlanması ağır hata sayılır',
      'Direksiyonu tek elle tutmak estetik olmadığı için her zaman doğrudan sınavı bitirir',
    ],
    answerIndex: 0,
    explanation:
      'Sınavda hataların ağırlığı, güvenlik üzerindeki etkisine göre belirlenir. Kırmızı ışıkta geçmek, yayaya yol vermemek ya da bir çarpışmaya yol açacak hareket gibi can ve mal güvenliğini doğrudan tehlikeye atan davranışlar ağır ve elemeli kabul edilir. Mantık, ortaya çıkan tehlike düzeyini ölçmektir.',
    whyWrong: [
      'Camın kirli olması güvenliği doğrudan tehlikeye atmaz; ağır hatanın ölçütü tehlike düzeyidir.',
      'Heyecanlanmak tek başına hata değildir; değerlendirilen, ortaya çıkan güvenlik riskidir.',
    ],
    objective: 'Sınavda ağır hatanın güvenlik tehlikesi ölçütüne dayandığını kavramak.',
    tags: ['sinav-hata', 'guvenlik', 'degerlendirme'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-217',
    subject: 'pratik',
    topic: 'sinav-puanlama',
    difficulty: 'zor',
    stem: 'Sinyal vermeyi veya ayna kontrolünü atlamak sınav değerlendirmesinde genellikle nasıl ele alınır?',
    options: [
      'Hiç dikkate alınmaz, önemsizdir',
      'Her durumda doğrudan sınavı bitirir',
      'Güvenliği tehlikeye atmadıkça puan kaybettiren eksiklik olarak değerlendirilir, biriktikçe sonucu etkiler',
      'Yalnızca eğitmenin keyfine bağlıdır, kuralı yoktur',
    ],
    answerIndex: 2,
    explanation:
      'Sinyal veya ayna kontrolünü atlamak, tek başına bir çarpışmaya yol açmadığı sürece genellikle puan kaybettiren eksiklik olarak değerlendirilir. Bu tür eksiklikler biriktikçe toplam değerlendirmeyi olumsuz etkiler ve başarısızlığa götürebilir. Ancak bu atlamalar bir tehlike doğurursa ağırlığı artar.',
    whyWrong: [
      'Bu eksiklikler önemsiz değildir; değerlendirmede puan kaybı olarak kaydedilir.',
      'Her ayna veya sinyal eksikliği doğrudan elemeli değildir; ölçüt, oluşan güvenlik riskidir.',
    ],
    objective:
      'Sinyal/ayna eksikliğinin puan kaybı olarak değerlendirildiğini ve tehlikeyle ağırlaştığını kavramak.',
    tags: ['sinav-puanlama', 'sinyal', 'ayna-kontrol'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-218',
    subject: 'pratik',
    topic: 'gerialma',
    difficulty: 'orta',
    stem: 'Aracı düz bir çizgide geri alırken (gerileme) doğru görüş ve hız yönetimi nasıl olmalıdır?',
    options: [
      'Hızlı geri gidip son anda durmak',
      'Düşük hızda, gövdeyi sağa dönüp arka camdan bakarak ve aynalarla destekleyerek gerilemek',
      'Yalnızca iç dikiz aynasına bakıp gaz vermek',
      'Direksiyonu sürekli sağa sola oynatarak ilerlemek',
    ],
    answerIndex: 1,
    explanation:
      'Düz geri gitmede sürücü gövdesini hafifçe sağa döndürüp arka camdan doğrudan bakar ve bu görüşü dış aynalarla destekler. Hız çok düşük tutulur, çoğunlukla debriyaj yarım bırakılarak araç yürütülür. Böylece arkadaki engeller ve yayalar zamanında görülüp durulabilir.',
    whyWrong: [
      'Hızlı geri gidip son anda durmak, arkadaki engeli fark etmeyi ve zamanında durmayı zorlaştırır.',
      'Yalnız iç aynaya bakmak arka alanın büyük kısmını göstermez; doğrudan arkaya bakmak gerekir.',
    ],
    objective: 'Düz geri manevrada arkaya bakış ve düşük hız yönetimini uygulayabilmek.',
    tags: ['gerialma', 'ayna-kontrol', 'hiz-kontrol'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-219',
    subject: 'pratik',
    topic: 'seritdegistirme',
    difficulty: 'orta',
    stem: 'Çok şeritli yolda güvenli şerit değiştirmenin doğru adımları hangisidir?',
    options: [
      'Direksiyonu hızlıca kır, sonra sinyal ver',
      'Sinyal vermeden boşluk görünce hemen geç',
      'Sadece iç dikiz aynasına bakıp geçmek yeterlidir',
      'Aynaları kontrol et, sinyal ver, kör noktayı omuz üstünden gör, boşluk uygunsa yumuşak biçimde şeridi değiştir',
    ],
    answerIndex: 3,
    explanation:
      'Güvenli şerit değişimi bir dizi kontrolle yapılır: önce aynalarla arka trafik izlenir, sinyalle niyet bildirilir, ardından kör nokta omuz üstünden kontrol edilir. Hedef şeritte yeterli boşluk varsa direksiyon yumuşakça kırılarak şerit değiştirilir. Bu sıralama sürprizleri ve ani manevraları önler.',
    whyWrong: [
      'Önce direksiyonu kırıp sonra sinyal vermek, niyeti geç bildirdiği için tehlikelidir.',
      'Sadece iç aynaya bakmak kör noktadaki aracı göstermez; omuz üstü kontrol şarttır.',
    ],
    objective: 'Şerit değişiminde ayna-sinyal-kör nokta-boşluk sırasını uygulayabilmek.',
    tags: ['seritdegistirme', 'sinyal', 'kor-nokta'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-220',
    subject: 'pratik',
    topic: 'acil-durum',
    difficulty: 'zor',
    stem: 'Sürüş sırasında önden ani bir engel çıktığında önerilen doğru davranış nedir?',
    options: [
      'Fren pedalına kararlı basıp direksiyonla güvenli bir kaçış yönü aramak, ABS varsa pedalı bırakmadan basılı tutmak',
      'Gözleri kapatıp direksiyonu bırakmak',
      'El frenini sonuna kadar aniden çekmek',
      'Gaza basarak engeli hızla geçmeye çalışmak',
    ],
    answerIndex: 0,
    explanation:
      'Ani engelde doğru davranış, fren pedalına kararlı ve kontrollü basmak ve aynı anda gözle güvenli bir kaçış yönü aramaktır. ABS bulunan araçlarda pedal basılı tutulur, böylece tekerlekler kilitlenmeden yön verilebilir. Amaç hem hızı kesmek hem de çarpışmadan kaçınacak alanı bulmaktır.',
    whyWrong: [
      'Gözleri kapatıp direksiyonu bırakmak her türlü kontrolü yitirmek demektir ve kazayı kaçınılmaz kılar.',
      'Yüksek hızda el frenini aniden çekmek arka tekerlekleri kilitleyip aracı savurabilir.',
    ],
    objective: 'Ani engelde kontrollü fren ve kaçış yönü arama davranışını kavramak.',
    tags: ['acil-durum', 'fren', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-221',
    subject: 'pratik',
    topic: 'kavsak-donus',
    difficulty: 'orta',
    stem: 'Işıklı bir kavşakta sola dönüş yapacak sürücü dönüşten önce hangi hazırlığı yapmalıdır?',
    options: [
      'Sağ şeride geçip sağ sinyal vermek',
      'Hız kesmeden en soldaki karşı şeride girmek',
      'Erkenden sol sinyal verip uygun sol şeride yaklaşmak, karşıdan gelen araçlara ve yayalara yol vermek',
      'Dönüş anında hiç sinyal vermeden hızlıca dönmek',
    ],
    answerIndex: 2,
    explanation:
      'Sola dönüşte sürücü erkenden sol sinyal verir, kurallara uygun biçimde sol şeride yaklaşır ve dönüş sırasında karşıdan gelen düz giden araçlarla geçtiği yoldaki yayalara yol verir. Bu hazırlık, dönüşün öngörülebilir, güvenli ve akışı bozmayan biçimde yapılmasını sağlar.',
    whyWrong: [
      'Sola dönüş için sağ şeride geçip sağ sinyal vermek yönle çelişir ve diğer sürücüleri yanıltır.',
      'Hız kesmeden ve yol vermeden dönmek karşıdan gelen araç ve yayalar için ciddi tehlike oluşturur.',
    ],
    objective:
      'Işıklı kavşakta sola dönüş için sinyal, şerit ve yol verme hazırlığını uygulayabilmek.',
    tags: ['kavsak-donus', 'sinyal', 'yol-verme'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-222',
    subject: 'pratik',
    topic: 'hiz-kontrol',
    difficulty: 'orta',
    stem: 'Yaklaşan keskin bir virajda hız kontrolü nasıl yapılmalıdır?',
    options: [
      'Viraj içinde sert fren yaparak hız kesilir',
      'Viraja girmeden önce hız uygun düzeye düşürülür, viraj içinde sabit ve dengeli hızla dönülür',
      'Viraja yüksek hızla girilip çıkışta yavaşlanır',
      'Virajda debriyaja basılı tutup boşta dönülür',
    ],
    answerIndex: 1,
    explanation:
      'Doğru viraj tekniğinde hız, viraja girmeden önce fren ve uygun vitesle güvenli düzeye düşürülür; viraj içinde ise sabit, dengeli bir hızla dönülür. Viraj ortasında sert fren yapmak aracın dengesini bozup savrulmaya yol açabilir. Fren önce, çekiş viraj içinde ilkesi geçerlidir.',
    whyWrong: [
      'Viraj içinde sert fren yapmak ağırlık aktarımını bozar ve aracı savurabilir.',
      'Virajda boşta gitmek motor freninden ve çekişten yararlanmayı engeller, hâkimiyeti zayıflatır.',
    ],
    objective: 'Virajda hızı önceden düşürüp dengeli hızla dönme ilkesini uygulayabilmek.',
    tags: ['hiz-kontrol', 'viraj', 'fren'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-223',
    subject: 'pratik',
    topic: 'debriyaj',
    difficulty: 'orta',
    stem: 'Debriyajın yarım (kavrama noktası) bırakıldığı an aracın davranışından nasıl anlaşılır?',
    options: [
      'Motor tamamen susar',
      'Araç geri geri gitmeye başlar',
      'Direksiyon aniden kilitlenir',
      'Motor sesi hafif değişir, aracın burnu hafifçe kalkar ve araç ileri doğru yüklenmeye başlar',
    ],
    answerIndex: 3,
    explanation:
      'Kavrama noktası, debriyaj balatalarının volana temas edip gücü aktarmaya başladığı andır. Bu anda motor sesi hafifçe değişir, aracın burnu az yükselir ve araç ileri doğru yüklenmeye başlar. Sürücü bu belirtileri hissederek pedalı sabit tutar ve yumuşak, sarsıntısız kalkış yapar.',
    whyWrong: [
      'Motorun tamamen susması kavrama noktasını değil, hatalı kullanımdan doğan stop durumunu gösterir.',
      'Kavrama noktasında araç geri gitmez ya da direksiyon kilitlenmez; belirti öne yüklenmedir.',
    ],
    objective: 'Debriyajın kavrama noktasını araç davranışından tanıyabilmek.',
    tags: ['debriyaj', 'kavrama-noktasi', 'kalkis'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-224',
    subject: 'pratik',
    topic: 'rampa',
    difficulty: 'zor',
    stem: 'Yokuş yukarı trafikte ilerlerken önündeki araç durduğunda geri kaymayı önlemenin en güvenli yolu nedir?',
    options: [
      'Araç dururken el frenini devreye alıp kalkışta debriyaj-gaz-el freni koordinasyonuyla hareket etmek',
      'Yalnızca debriyajı sürekli yarım basılı tutup beklemek',
      'Vitesi boşa alıp fren yapmadan beklemek',
      'Aracı geri bırakıp arkadaki araca yaslamak',
    ],
    answerIndex: 0,
    explanation:
      'Yokuşta beklerken en güvenli yöntem, aracı durdurup el frenini devreye almaktır; böylece ayak pedallardan kurtulur ve araç geri kaymaz. Yeniden hareket ederken debriyaj kavrama noktasına getirilir, hafif gaz verilir ve çekiş hissedilince el freni indirilir. Bu koordinasyon geri kaçışı önler.',
    whyWrong: [
      'Debriyajı sürekli yarım tutup beklemek balataları aşırı ısıtıp yıpratır ve dikkat dağıldığında araç kayabilir.',
      'Vitesi boşa alıp fren yapmadan beklemek aracın kontrolsüzce geri kaymasına yol açar.',
    ],
    objective:
      'Yokuşta beklerken el freniyle geri kaymayı önleme ve güvenli kalkışı uygulayabilmek.',
    tags: ['rampa', 'el-freni', 'debriyaj'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-225',
    subject: 'pratik',
    topic: 'ayna-kontrol',
    difficulty: 'orta',
    stem: 'Dış yan aynalar sürüş için en doğru biçimde nasıl ayarlanır?',
    options: [
      'Aracın kendi gövdesi aynanın tam ortasında görünecek biçimde',
      'Yalnızca gökyüzü görünecek biçimde yukarı çevrilerek',
      'Kendi aracın gövdesi aynanın iç kenarında ince bir şerit hâlinde kalacak, arka yan yolun büyük kısmı görünecek biçimde',
      'Aynalar tamamen aşağı, sadece zemin görünecek biçimde',
    ],
    answerIndex: 2,
    explanation:
      'Dış aynalar, kendi aracın gövdesi iç kenarda yalnızca ince bir referans şeridi olarak kalacak ve arka yan yolun mümkün olan en geniş bölümü görünecek biçimde ayarlanır. Bu ayar kör noktayı küçültür ve arkadan yaklaşan araçların daha erken fark edilmesini sağlar.',
    whyWrong: [
      'Aracın gövdesinin aynanın ortasında durması görüş alanının çoğunu boşa harcar ve kör noktayı büyütür.',
      'Aynayı yalnız gökyüzüne ya da zemine çevirmek yol ve araç görüşünü tamamen ortadan kaldırır.',
    ],
    objective: 'Dış aynaları kör noktayı en aza indirecek biçimde ayarlayabilmek.',
    tags: ['ayna-kontrol', 'kor-nokta', 'ayna-ayari'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-226',
    subject: 'pratik',
    topic: 'kor-nokta',
    difficulty: 'orta',
    stem: 'Sağa dönüş yapmadan önce özellikle hangi kör nokta tehlikesi kontrol edilmelidir?',
    options: [
      'Sol arkadan gelen kamyonlar',
      'Sağ tarafta, aracın yanından ilerleyen bisikletli veya motosikletli ile yayalar',
      'Yalnızca karşıdan gelen araçlar',
      'Arkadaki aracın far durumu',
    ],
    answerIndex: 1,
    explanation:
      'Sağa dönüşte en tehlikeli kör nokta, aracın sağ yanında ve arka sağ tarafında ilerleyen bisikletli, motosikletli ve yayaların bulunduğu bölgedir. Dönüşten önce sağ ayna ve sağ omuz üstü bakışla bu alan kontrol edilmelidir; aksi hâlde dönerken yanda ilerleyen bir kullanıcı sıkışabilir.',
    whyWrong: [
      'Sola dönmediğimiz için sol arkadan gelen kamyon bu manevranın öncelikli kör nokta tehlikesi değildir.',
      'Yalnız karşıdan gelen araçlara bakmak, sağ yandaki bisikletli ve yayayı gözden kaçırmaya yol açar.',
    ],
    objective:
      'Sağa dönüşte sağ yandaki kör nokta ve savunmasız yol kullanıcılarını kontrol edebilmek.',
    tags: ['kor-nokta', 'kavsak-donus', 'yaya'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-227',
    subject: 'pratik',
    topic: 'sinyal',
    difficulty: 'kolay',
    stem: 'Dönüş veya şerit değişimi tamamlandıktan sonra sinyal kolu ile ne yapılmalıdır?',
    options: [
      'Sinyal otomatik dönmediyse elle kapatılmalıdır',
      'Sinyal sürekli açık bırakılmalıdır',
      'Sinyal yerine dörtlü flaşör açılmalıdır',
      'Kornaya basılarak manevra bitirilmelidir',
    ],
    answerIndex: 0,
    explanation:
      'Manevra tamamlandığında sinyal görevini bitirmiştir; direksiyon kendiliğinden düzelirken sinyal otomatik kapanmazsa sürücü kolu elle kapatmalıdır. Açık unutulan sinyal, arkadaki sürücülere yanlış niyet bildirir ve onların hatalı kararlar almasına yol açabilir.',
    whyWrong: [
      'Sinyali sürekli açık bırakmak diğer sürücüleri yanıltır ve gereksiz manevra beklentisi oluşturur.',
      'Manevra bitiminde dörtlü flaşör açmanın ya da kornaya basmanın bir gerekçesi yoktur.',
    ],
    objective: 'Manevra sonrası sinyalin kapatılması gerektiğini kavramak.',
    tags: ['sinyal', 'seritdegistirme', 'iletisim'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-228',
    subject: 'pratik',
    topic: 'vites',
    difficulty: 'orta',
    stem: 'Manuel vitesli araçta vites değiştirirken debriyaj ve gaz nasıl kullanılmalıdır?',
    options: [
      'Debriyaja basmadan vites zorlanarak takılır',
      'Gaz sonuna kadar basılıyken vites değiştirilir',
      'Vites değişimi sırasında hem debriyaj hem gaz tamamen bırakılır ve araç boşta uzun süre gider',
      'Debriyaja tam bas, gazı bırak, vitesi değiştir, sonra gazla eş zamanlı debriyajı yumuşakça bırak',
    ],
    answerIndex: 3,
    explanation:
      'Doğru vites değişiminde debriyaja tam basılır, gaz bırakılır ve vites uygun konuma alınır; ardından debriyaj yumuşakça bırakılırken gazla eşlik edilir. Bu uyum sarsıntısız geçiş sağlar. Debriyaja basmadan vites zorlamak dişlileri yıpratır, gaz basılı değişim ise motoru aşırı zorlar.',
    whyWrong: [
      'Debriyaja basmadan vitesi zorlamak şanzıman dişlilerine zarar verir ve sesli takılmaya yol açar.',
      'Gaz sonuna kadar basılıyken vites değiştirmek motoru aşırı devirde zorlar ve sarsıntı yapar.',
    ],
    objective: 'Vites değişiminde debriyaj-gaz uyumunu doğru sırayla uygulayabilmek.',
    tags: ['vites', 'debriyaj', 'gaz'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-229',
    subject: 'pratik',
    topic: 'sinav-hata',
    difficulty: 'zor',
    stem: 'Direksiyon sınavında kavşağa yaklaşırken ayna kontrolü yapmadan şerit değiştirmenin değerlendirilme mantığı nedir?',
    options: [
      'Her koşulda önemsiz sayılır',
      'Sadece hız yüksekse dikkate alınır',
      'Trafiği kontrol etmeden yapılan şerit değişimi güvenlik ihmali olarak değerlendirilir; bir tehlike doğurursa ağır hataya dönüşür',
      'Aracın rengi değerlendirmeyi belirler',
    ],
    answerIndex: 2,
    explanation:
      'Ayna kontrolü yapmadan şerit değiştirmek, arkadaki trafiği görmeden yön değiştirmek anlamına gelir ve bir güvenlik ihmalidir. Değerlendirmede bu bir eksiklik olarak kaydedilir; yandan gelen bir araçla çarpışma ya da ani fren gerektiren bir durum doğarsa hata ağırlaşır ve elemeli hâle gelebilir. Ölçüt oluşan tehlikedir.',
    whyWrong: [
      'Trafiği kontrol etmeden yön değiştirmek önemsiz değildir; her hâlde bir eksiklik olarak değerlendirilir.',
      'Değerlendirme aracın rengi gibi ölçütlere değil, davranışın güvenlik üzerindeki etkisine dayanır.',
    ],
    objective:
      'Kontrolsüz şerit değişiminin güvenlik ihmali ve tehlikeyle ağırlaşan hata olduğunu kavramak.',
    tags: ['sinav-hata', 'seritdegistirme', 'ayna-kontrol'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-230',
    subject: 'pratik',
    topic: 'hareket',
    difficulty: 'kolay',
    stem: 'Emniyet kemerini bağlamadan araçla harekete geçmek sürüş açısından neden yanlıştır?',
    options: [
      'Yakıt tüketimini artırdığı için',
      'Kaza anında sürücüyü koltukta tutan temel korumayı devre dışı bıraktığı ve kural ihlali olduğu için',
      'Motorun ısınmasını geciktirdiği için',
      'Yalnızca estetik göründüğü için',
    ],
    answerIndex: 1,
    explanation:
      'Emniyet kemeri, ani duruş ve çarpışmada sürücüyü koltukta tutarak direksiyona veya cama çarpmasını önleyen temel güvenlik donanımıdır. Kemersiz harekete geçmek bu korumayı devre dışı bırakır ve aynı zamanda bir trafik kuralı ihlalidir; sınavda da hareket öncesi kemer bağlamak beklenen davranıştır.',
    whyWrong: [
      'Emniyet kemerinin yakıt tüketimi ya da motorun ısınmasıyla hiçbir ilgisi yoktur.',
      'Kemer estetik bir unsur değil, kaza anında hayat kurtaran bir güvenlik ekipmanıdır.',
    ],
    objective:
      'Hareket öncesi emniyet kemerinin güvenlik ve kural açısından zorunluluğunu kavramak.',
    tags: ['hareket', 'kemer', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
];
