/**
 * ÖZGÜN ilk yardım soruları (Sprint 3 genişletme). ROADMAP C.4/E.6.
 * Kaynak = resmî temel ilk yardım bilgisi; KENDİ İFADEMİZLE. review: 'draft' — İLK YARDIM
 * EĞİTMENİ onayı ZORUNLU (yayın öncesi). Hiçbir kaynak kopyalanmamıştır.
 */
import type { Question } from '@ea/content-schema';

const SRC = 'Resmî temel ilk yardım bilgisi (özgün ifade) — uzman onayı bekliyor';

export const ILKYARDIM_QUESTIONS: Question[] = [
  {
    id: 'ilkyardim-101',
    subject: 'ilkyardim',
    topic: 'olay-yeri',
    difficulty: 'kolay',
    stem: 'Bir trafik kazasına ilk ulaşan kişi olarak yapmanız gereken ilk iş nedir?',
    options: [
      'Yaralıyı hemen araçtan çıkarmak',
      'Önce kendinizin ve çevrenin güvenliğini sağlamak',
      'Yaralıya su içirmek',
      'Kaza yerini fotoğraflamak',
    ],
    answerIndex: 1,
    explanation:
      'İlk yardımın altın kuralı, olay yerinde önce kendinizin ve çevredekilerin güvenliğini sağlamaktır; güvenli olmayan ortamda müdahale ikinci bir kazaya yol açar.',
    whyWrong: [
      'Zorunluluk olmadıkça yaralıyı çıkarmak omurga yaralanmasını ağırlaştırabilir.',
      'Bilinci/durumu belirsiz yaralıya sıvı verilmez.',
    ],
    objective: 'Olay yerinde güvenlik önceliğini kavramak.',
    tags: ['olay-yeri', 'guvenlik', 'ilk-adim'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-102',
    subject: 'ilkyardim',
    topic: 'olay-yeri',
    difficulty: 'kolay',
    stem: 'Ülkemizde acil sağlık yardımı için aranması gereken telefon numarası hangisidir?',
    options: ['110', '155', '112', '156'],
    answerIndex: 2,
    explanation:
      '112, ülkemizde acil sağlık hizmetlerinin tek numarasıdır; olay yeri, olay türü ve yaralı sayısı açıkça bildirilmelidir.',
    whyWrong: ['110 itfaiye, 155 polis, 156 jandarma numarasıdır.'],
    objective: 'Acil sağlık ihbar numarasını bilmek.',
    tags: ['olay-yeri', 'ihbar', 'iletisim'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-103',
    subject: 'ilkyardim',
    topic: 'tyd',
    difficulty: 'orta',
    stem: 'Erişkin bir kişide dış kalp masajı dakikada kaç bası hızında uygulanmalıdır?',
    options: ['60-80', '80-100', '100-120', '140-160'],
    answerIndex: 2,
    explanation:
      'Erişkinde göğüs basıları dakikada 100-120 hızında yapılır; bu tempo, dolaşımı yeterli düzeyde sürdürmek için önerilen aralıktır.',
    whyWrong: [
      'Dakikada 100 altındaki hız dolaşımı yeterince desteklemez.',
      '120 üzerindeki hız basıların derinliğini ve etkinliğini düşürür.',
    ],
    objective: 'Erişkin göğüs basısı hızını bilmek.',
    tags: ['tyd', 'kalp-masaji', 'canlandirma'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-104',
    subject: 'ilkyardim',
    topic: 'tyd',
    difficulty: 'orta',
    stem: 'Erişkinde temel yaşam desteği sırasında göğüs basısı yaklaşık ne kadar derinlikte olmalıdır?',
    options: ['Yaklaşık 2 cm', 'Yaklaşık 8 cm', 'Yaklaşık 5 cm', 'Yaklaşık 10 cm'],
    answerIndex: 2,
    explanation:
      'Erişkinde göğüs kemiği yaklaşık 5 cm çökecek şekilde bastırılır; bu derinlik kalbin yeterince sıkışıp kanı pompalaması için gereklidir.',
    whyWrong: [
      '2 cm gibi sığ bası dolaşımı oluşturmaz.',
      'Aşırı derin bası kaburga ve iç organ yaralanmasına yol açabilir.',
    ],
    objective: 'Göğüs basısı derinliğini kavramak.',
    tags: ['tyd', 'kalp-masaji', 'canlandirma'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-105',
    subject: 'ilkyardim',
    topic: 'tyd',
    difficulty: 'orta',
    stem: 'Erişkinde temel yaşam desteğinde göğüs basısının suni solunuma oranı nedir?',
    options: ['15 bası / 2 soluk', '5 bası / 1 soluk', '30 bası / 5 soluk', '30 bası / 2 soluk'],
    answerIndex: 3,
    explanation:
      'Erişkinde 30 göğüs basısının ardından 2 kurtarıcı soluk verilir ve bu 30:2 döngüsü kesintisiz sürdürülür.',
    whyWrong: [
      'Erişkin uygulamasında oran 15:2 değil 30:2 olarak önerilir.',
      'Soluk sayısının artırılması basıya ayrılan süreyi azaltır.',
    ],
    objective: 'Bası/soluk oranını bilmek.',
    tags: ['tyd', 'canlandirma', 'oran'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-106',
    subject: 'ilkyardim',
    topic: 'tyd',
    difficulty: 'orta',
    stem: 'Bilinci kapalı bir kişide hava yolunu açmak için uygulanan temel yöntem hangisidir?',
    options: [
      'Baş-çene pozisyonu (başı geriye, çeneyi yukarı)',
      'Başı öne doğru bükmek',
      'Kişiyi yüzükoyun çevirmek',
      'Omuzlardan sarsmak',
    ],
    answerIndex: 0,
    explanation:
      'Bilinci kapalı kişide dil geriye kayarak hava yolunu tıkayabilir; baş geriye itilip çene yukarı kaldırılarak (baş-çene pozisyonu) hava yolu açılır.',
    whyWrong: [
      'Başı öne bükmek hava yolunu daha da daraltır.',
      'Sarsmak bilinç değerlendirmesi içindir, hava yolunu açmaz.',
    ],
    objective: 'Hava yolu açma yöntemini kavramak.',
    tags: ['tyd', 'hava-yolu', 'bas-cene'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-107',
    subject: 'ilkyardim',
    topic: 'tyd',
    difficulty: 'zor',
    stem: 'Bir kişinin solunumunu değerlendirirken kullanılan "bak-dinle-hisset" yöntemi neyi kontrol eder?',
    options: [
      'Nabzın sayısını',
      'Kan basıncını',
      'Göğüs hareketini, solunum sesini ve hava akımını',
      'Vücut ısısını',
    ],
    answerIndex: 2,
    explanation:
      'Bak-dinle-hisset yönteminde göğsün inip kalkmasına bakılır, solunum sesi dinlenir ve yanağa gelen hava akımı hissedilir; böylece solunum olup olmadığı değerlendirilir.',
    whyWrong: [
      'Bu yöntem nabız ya da kan basıncını ölçmez.',
      'Vücut ısısı bu değerlendirmenin konusu değildir.',
    ],
    objective: 'Solunum değerlendirmesini kavramak.',
    tags: ['tyd', 'solunum', 'degerlendirme'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-108',
    subject: 'ilkyardim',
    topic: 'bilinc',
    difficulty: 'kolay',
    stem: 'Yaralının bilincini değerlendirmek için ilk olarak ne yapılır?',
    options: [
      'Omuzlarına hafifçe dokunup yüksek sesle seslenmek',
      'Yüzüne su serpmek',
      'Kollarını kaldırmak',
      'Nabzını saymak',
    ],
    answerIndex: 0,
    explanation:
      'Bilinç kontrolünde kişinin omuzlarına hafifçe dokunulup yüksek sesle "iyi misiniz?" diye seslenilir; yanıt yoksa bilinç kapalı kabul edilir.',
    whyWrong: [
      'Yüze su serpmek güvenilir bir bilinç değerlendirmesi değildir.',
      'Nabız kontrolü bilinç değerlendirmesinden sonra gelir.',
    ],
    objective: 'Bilinç değerlendirmesinin ilk adımını bilmek.',
    tags: ['bilinc', 'degerlendirme', 'tyd'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-109',
    subject: 'ilkyardim',
    topic: 'pozisyon',
    difficulty: 'orta',
    stem: 'Bilinci kapalı ancak solunumu ve nabzı olan bir kişiye hangi pozisyon verilir?',
    options: [
      'Sırtüstü düz yatış',
      'Oturur pozisyon',
      'Koma (yan yatış) pozisyonu',
      'Ayakları yukarıda yatış',
    ],
    answerIndex: 2,
    explanation:
      'Bilinci kapalı fakat solunumu olan kişi yan yatırılır (koma pozisyonu); böylece dil geriye kaçmaz ve ağızdaki sıvı dışarı akarak hava yolu açık kalır.',
    whyWrong: [
      'Sırtüstü yatışta dil veya kusmuk hava yolunu tıkayabilir.',
      'Ayakları yukarı pozisyon şokta uygulanır, bilinç kapalıyken uygun değildir.',
    ],
    objective: 'Koma pozisyonunun endikasyonunu kavramak.',
    tags: ['pozisyon', 'koma-pozisyonu', 'bilinc'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-110',
    subject: 'ilkyardim',
    topic: 'pozisyon',
    difficulty: 'orta',
    stem: 'Koma (yan yatış) pozisyonunun temel amacı aşağıdakilerden hangisidir?',
    options: [
      'Kanamayı durdurmak',
      'Kırığı sabitlemek',
      'Vücut ısısını yükseltmek',
      'Hava yolunun açık kalmasını sağlamak',
    ],
    answerIndex: 3,
    explanation:
      'Koma pozisyonu, bilinci kapalı kişide dilin geriye kaçmasını ve ağızdaki sıvıların hava yolunu tıkamasını önleyerek solunum yolunun açık kalmasını sağlar.',
    whyWrong: [
      'Kanama kontrolü ayrı bir müdahaledir.',
      'Kırık sabitleme bu pozisyonun amacı değildir.',
    ],
    objective: 'Koma pozisyonunun amacını açıklamak.',
    tags: ['pozisyon', 'hava-yolu', 'koma-pozisyonu'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-111',
    subject: 'ilkyardim',
    topic: 'kanama',
    difficulty: 'kolay',
    stem: 'Kol veya bacaktaki dış kanamada ilk uygulanması gereken yöntem hangisidir?',
    options: [
      'Hemen turnike bağlamak',
      'Kanayan yere temiz bezle doğrudan baskı uygulamak',
      'Yarayı ovalamak',
      'Yaraya buz bastırmak',
    ],
    answerIndex: 1,
    explanation:
      'Dış kanamada ilk yapılacak, kanayan bölgeye temiz bir bezle doğrudan ve sürekli baskı uygulamaktır; çoğu kanama bu yöntemle kontrol altına alınır.',
    whyWrong: [
      'Turnike ilk seçenek değil, son çaredir.',
      'Yarayı ovmak kanamayı ve zedelenmeyi artırır.',
    ],
    objective: 'Dış kanamada ilk müdahaleyi bilmek.',
    tags: ['kanama', 'baski', 'dis-kanama'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-112',
    subject: 'ilkyardim',
    topic: 'kanama',
    difficulty: 'orta',
    stem: 'Koldaki bir kanamada doğrudan baskıya ek olarak yapılması önerilen nedir?',
    options: [
      'Kanayan bölgeyi kalp seviyesinin üstüne kaldırmak',
      'Kolu kalp seviyesinin altına indirmek',
      'Kolu hızlıca sallamak',
      'Yaraya diş macunu sürmek',
    ],
    answerIndex: 0,
    explanation:
      'Doğrudan baskıyla birlikte, kırık yoksa kanayan bölge kalp seviyesinin üstüne kaldırılır; bu, bölgeye giden kan akımını azaltarak kanamayı yavaşlatır.',
    whyWrong: [
      'Bölgeyi aşağıda tutmak kanamayı artırır.',
      'Yaraya diş macunu gibi maddeler sürmek enfeksiyon riski oluşturur.',
    ],
    objective: 'Kanamada bölgeyi yükseltmenin yararını kavramak.',
    tags: ['kanama', 'yukseltme', 'dis-kanama'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-113',
    subject: 'ilkyardim',
    topic: 'kanama',
    difficulty: 'zor',
    stem: 'Turnike uygulaması ilk yardımda hangi durumda tercih edilir?',
    options: [
      'Her kanamada ilk seçenek olarak',
      'Küçük kesiklerde',
      'Burun kanamasında',
      'Baskı ve yükseltmeyle durmayan, hayatı tehdit eden şiddetli kanamada son çare olarak',
    ],
    answerIndex: 3,
    explanation:
      'Turnike; doğrudan baskı ve bölgeyi yükseltme gibi yöntemlerle durdurulamayan, yaşamı tehdit eden şiddetli kanamalarda başvurulan son çaredir.',
    whyWrong: [
      'Turnike ilk seçenek değildir; gereksiz kullanımı doku hasarına yol açar.',
      'Küçük kesik ve burun kanamasında turnikeye gerek yoktur.',
    ],
    objective: 'Turnikenin doğru endikasyonunu kavramak.',
    tags: ['kanama', 'turnike', 'son-care'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-114',
    subject: 'ilkyardim',
    topic: 'kanama',
    difficulty: 'orta',
    stem: 'Zorunlu olarak turnike uygulandığında mutlaka not edilmesi gereken bilgi nedir?',
    options: [
      'Yaralının adı',
      'Turnikenin uygulandığı saat',
      'Kazanın oluş şekli',
      'Yaralının kan grubu',
    ],
    answerIndex: 1,
    explanation:
      'Turnike uygulandığında bağlanma saati mutlaka yazılır; çünkü sağlık ekibi dokunun ne kadar süredir kansız kaldığını bilmek zorundadır.',
    whyWrong: ['Ad, kaza şekli veya kan grubu turnike süresini izlemek için yeterli değildir.'],
    objective: 'Turnikede saat kaydının önemini bilmek.',
    tags: ['kanama', 'turnike', 'saat'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-115',
    subject: 'ilkyardim',
    topic: 'kanama',
    difficulty: 'zor',
    stem: 'İç kanama olabileceğini düşündüren belirtilerden biri aşağıdakilerden hangisidir?',
    options: [
      'Ciltte kızarıklık ve kaşıntı',
      'Yüksek ateş ve terleme',
      'Kaslarda kramp',
      'Ciltte solukluk, soğukluk, hızlı ve zayıf nabız',
    ],
    answerIndex: 3,
    explanation:
      'İç kanamada dolaşımdaki kan azaldığı için cilt solar, soğur ve nemlenir; nabız hızlanıp zayıflar. Bu belirtiler şok tablosuyla birlikte görülür.',
    whyWrong: [
      'Kızarıklık ve kaşıntı daha çok alerjik tepkilerde görülür.',
      'Yüksek ateş iç kanamanın tipik belirtisi değildir.',
    ],
    objective: 'İç kanama belirtilerini tanımak.',
    tags: ['kanama', 'ic-kanama', 'belirti'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-116',
    subject: 'ilkyardim',
    topic: 'sok',
    difficulty: 'orta',
    stem: 'Kanama veya kırık bulunmayan bir şok tablosunda yaralıya hangi pozisyon verilir?',
    options: [
      'Ayakları yaklaşık 30 cm yukarı kaldırılmış sırtüstü yatış',
      'Yüzükoyun yatış',
      'Başı dik oturuş',
      'Ayakları aşağıda sarkan oturuş',
    ],
    answerIndex: 0,
    explanation:
      'Şokta, kanama ve kırık yoksa yaralı sırtüstü yatırılıp ayakları yaklaşık 30 cm yükseltilir; bu, beyne giden kan akışını desteklemeyi amaçlar.',
    whyWrong: [
      'Yüzükoyun yatış solunumu ve değerlendirmeyi zorlaştırır.',
      'Oturuş pozisyonu beyin kan akımını desteklemez.',
    ],
    objective: 'Şok pozisyonunu kavramak.',
    tags: ['sok', 'pozisyon', 'dolasim'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-117',
    subject: 'ilkyardim',
    topic: 'sok',
    difficulty: 'orta',
    stem: 'Şok belirtileri gösteren bir yaralıya ilk yardımda aşağıdakilerden hangisi yapılmalıdır?',
    options: [
      'Bol miktarda su ve yiyecek vermek',
      'Yürüterek dolaştırmak',
      'Soğuk suyla ıslatmak',
      'Üzerini örterek vücut ısısını korumak',
    ],
    answerIndex: 3,
    explanation:
      'Şoktaki yaralının üzeri örtülerek üşümesi önlenir; ısı kaybı tabloyu ağırlaştırır. Ayrıca bilinç durumu belirsiz kişiye ağızdan bir şey verilmez.',
    whyWrong: [
      'Şoktaki kişiye yiyecek/içecek verilmez.',
      'Yürütmek veya soğutmak durumu kötüleştirir.',
    ],
    objective: 'Şokta ısı korumasının önemini kavramak.',
    tags: ['sok', 'isi-korumasi', 'mudahale'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-118',
    subject: 'ilkyardim',
    topic: 'sok',
    difficulty: 'zor',
    stem: 'İlk yardım açısından şok, en genel anlamda hangi durumu ifade eder?',
    options: [
      'Vücut ısısının aşırı yükselmesini',
      'Kaslarda ani kasılmayı',
      'Dokuların yeterli kan ve oksijen alamadığı dolaşım yetersizliğini',
      'Kan şekerinin yükselmesini',
    ],
    answerIndex: 2,
    explanation:
      'Şok, dolaşımın bozulması sonucu doku ve organların yeterli kan ile oksijen alamadığı yaşamı tehdit eden bir durumdur; erken tanınması önemlidir.',
    whyWrong: [
      'Şok ateş yüksekliği ya da kas kasılması değildir.',
      'Kan şekeri değişimi başka acil durumları tanımlar.',
    ],
    objective: 'Şok kavramını tanımlamak.',
    tags: ['sok', 'dolasim', 'tanim'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-119',
    subject: 'ilkyardim',
    topic: 'yanik',
    difficulty: 'kolay',
    stem: 'Sıcak sıvıyla oluşan birinci derece bir yanıkta ilk yapılması gereken nedir?',
    options: [
      'Yanık bölgesine buz koymak',
      'Yanan yeri bol soğuk suyla soğutmak',
      'Diş macunu sürmek',
      'Yoğurt sürmek',
    ],
    answerIndex: 1,
    explanation:
      'Yanık bölgesi bol soğuk su altında bir süre soğutulur; bu, ısının derine ilerlemesini durdurur ve ağrıyı azaltır.',
    whyWrong: [
      'Doğrudan buz uygulaması dokuyu ayrıca zedeler.',
      'Diş macunu, yoğurt gibi maddeler enfeksiyon riski oluşturur ve sürülmez.',
    ],
    objective: 'Yanıkta doğru soğutmayı bilmek.',
    tags: ['yanik', 'sogutma', 'mudahale'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-120',
    subject: 'ilkyardim',
    topic: 'yanik',
    difficulty: 'orta',
    stem: 'Yanık bölgesine aşağıdakilerden hangisinin uygulanması yanlıştır?',
    options: [
      'Bol soğuk su',
      'Diş macunu, yoğurt veya salça',
      'Temiz ve kuru örtü',
      'Bölgeyi serin tutma',
    ],
    answerIndex: 1,
    explanation:
      'Yanığa diş macunu, yoğurt, salça gibi maddeler sürmek yanlıştır; bunlar enfeksiyon riskini artırır ve doktorun yarayı değerlendirmesini güçleştirir.',
    whyWrong: [
      'Bol soğuk su ve temiz örtü doğru uygulamalardır.',
      'Bölgeyi serin tutmak yararlıdır.',
    ],
    objective: 'Yanıkta yapılan hataları ayırt etmek.',
    tags: ['yanik', 'yanlis-uygulama', 'enfeksiyon'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-121',
    subject: 'ilkyardim',
    topic: 'yanik',
    difficulty: 'orta',
    stem: 'El bileğinde yanık oluşan bir kişide bölge şişmeden önce ne yapılması uygundur?',
    options: [
      'Bölgedeki yüzük ve saati çıkarmak',
      'Yüzüğü olduğu gibi bırakmak',
      'Bölgeyi sıkıca sarmak',
      'Su temasından kaçınmak',
    ],
    answerIndex: 0,
    explanation:
      'Yanık bölgesi şişebileceği için yüzük, saat, bilezik gibi sıkan eşyalar şişme başlamadan çıkarılır; aksi halde dolaşımı engelleyebilir.',
    whyWrong: [
      'Takıları bırakmak şişince dolaşımı sıkıştırır.',
      'Bölgeyi sıkıca sarmak da dolaşımı bozar; su ile soğutma zaten gereklidir.',
    ],
    objective: 'Yanıkta sıkan eşyaları çıkarmanın önemini kavramak.',
    tags: ['yanik', 'sisme', 'dolasim'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-122',
    subject: 'ilkyardim',
    topic: 'kirik',
    difficulty: 'orta',
    stem: 'Kol veya bacakta kırık şüphesi olan yaralıya ilk yardımda ne yapılır?',
    options: [
      'Kırık bölgeyi düzeltmeye çalışmak',
      'Yaralıyı ayağa kaldırıp yürütmek',
      'Kırık bölgeyi olduğu gibi, hareketsiz kalacak biçimde sabitlemek',
      'Kemiği yerine oturtmak',
    ],
    answerIndex: 2,
    explanation:
      'Kırık şüphesinde bölge, bulunduğu konumda hareketsiz kalacak şekilde tespit edilir (atellenir); amaç, hareketle sinir ve damar zedelenmesini önlemektir.',
    whyWrong: [
      'Kırığı düzeltmeye/yerine oturtmaya çalışmak zararı artırır.',
      'Yaralıyı yürütmek kırığı kötüleştirir.',
    ],
    objective: 'Kırıkta hareketsiz kılma ilkesini kavramak.',
    tags: ['kirik', 'tespit', 'atel'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-123',
    subject: 'ilkyardim',
    topic: 'nakil',
    difficulty: 'zor',
    stem: 'Trafik kazasında yaralı, aşağıdaki durumlardan hangisinde yerinden hareket ettirilmelidir?',
    options: [
      'Bilinci kapalı olduğunda',
      'Yangın veya patlama gibi hayati bir tehlike söz konusu olduğunda',
      'Ağrısı olduğunda',
      'Susadığını söylediğinde',
    ],
    answerIndex: 1,
    explanation:
      'Yaralı, zorunlu olmadıkça hareket ettirilmez; yalnızca yangın, patlama, boğulma gibi ortamda kalması yaşamı tehdit eden durumlarda uygun tekniklerle çıkarılır.',
    whyWrong: [
      'Bilinç kapalıyken bile omurga korunarak yaralı yerinde bırakılır.',
      'Ağrı ya da susama hareket ettirmeyi gerektirmez.',
    ],
    objective: 'Yaralıyı hareket ettirme koşulunu kavramak.',
    tags: ['nakil', 'hareket-ettirme', 'omurga'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-124',
    subject: 'ilkyardim',
    topic: 'nakil',
    difficulty: 'orta',
    stem: 'Kazazedeyi araçtan çıkarma zorunluluğu doğduğunda dikkat edilmesi gereken en önemli nokta nedir?',
    options: [
      'Yaralıyı olabildiğince hızlı çekmek',
      'Yaralının kollarından tutup kaldırmak',
      'Yaralıyı yürüterek çıkarmak',
      'Baş, boyun ve gövde ekseninin bozulmamasına özen göstermek',
    ],
    answerIndex: 3,
    explanation:
      'Zorunlu çıkarmada baş-boyun-gövde aynı eksende tutularak omurga bütünlüğü korunur; bu ilke, omurga yaralanmasının ağırlaşmasını önler.',
    whyWrong: [
      'Hızlıca ya da kollardan çekmek omurgayı zedeleyebilir.',
      'Ağır yaralıyı yürütmek uygun bir taşıma değildir.',
    ],
    objective: 'Zorunlu taşımada omurga korumasını kavramak.',
    tags: ['nakil', 'tasima', 'omurga'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-125',
    subject: 'ilkyardim',
    topic: 'bogulma',
    difficulty: 'orta',
    stem: 'Yemek yerken nefes borusu tamamen tıkanan, konuşamayan ve öksüremeyen bilinci açık yetişkine ne uygulanır?',
    options: [
      'Su içirmek',
      'Sırtına ve karnına bası yaparak (karına bası manevrası) cismi çıkarmaya çalışmak',
      'Yatırıp dinlendirmek',
      'Öksürmesini engellemek',
    ],
    answerIndex: 1,
    explanation:
      'Tam tıkanmada kişi konuşamaz ve öksüremez; arkadan sarılıp karın üst bölgesine içe-yukarı bası yapılarak (Heimlich manevrası) yabancı cismin çıkması sağlanmaya çalışılır.',
    whyWrong: [
      'Tıkanıklıkta su içirmek durumu ağırlaştırır.',
      'Kişiyi yatırıp beklemek değerli zamanı kaybettirir.',
    ],
    objective: 'Tam hava yolu tıkanıklığında müdahaleyi bilmek.',
    tags: ['bogulma', 'heimlich', 'hava-yolu'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-126',
    subject: 'ilkyardim',
    topic: 'bogulma',
    difficulty: 'kolay',
    stem: 'Nefes yolu kısmen tıkanan, öksürebilen ve konuşabilen bir kişide ilk yardımcı ne yapmalıdır?',
    options: [
      'Kişiyi öksürmeye teşvik edip yakından izlemek',
      'Sırtına sertçe vurmak',
      'Karnına kuvvetle bastırmak',
      'Ağzına parmak sokmak',
    ],
    answerIndex: 0,
    explanation:
      'Kısmi tıkanıklıkta kişi öksürebiliyor ve konuşabiliyorsa hava yolu bir miktar açıktır; en etkili yol öksürmesini desteklemek ve durumu yakından izlemektir.',
    whyWrong: [
      'Kişi öksürebiliyorken agresif bası tıkanmayı tama çevirebilir.',
      'Ağza körlemesine parmak sokmak cismi daha derine itebilir.',
    ],
    objective: 'Kısmi tıkanıklıkta doğru davranışı kavramak.',
    tags: ['bogulma', 'kismi-tikanma', 'oksuruk'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-127',
    subject: 'ilkyardim',
    topic: 'bayilma',
    difficulty: 'kolay',
    stem: 'Ayakta iken aniden bayılan ve kısa sürede kendine gelmesi beklenen bir kişiye ne yapılır?',
    options: [
      'Sırtüstü yatırıp ayaklarını hafifçe yükseltmek ve temiz hava sağlamak',
      'Ayakta tutmaya çalışmak',
      'Yüzüne tokat atmak',
      'Oturtup su içirmek',
    ],
    answerIndex: 0,
    explanation:
      'Bayılan kişi sırtüstü yatırılıp ayakları hafifçe kaldırılır ve ortam havalandırılır; böylece beyne kan akışı artar ve kişi genellikle kısa sürede kendine gelir.',
    whyWrong: [
      'Ayakta tutmak beyne kan gitmesini güçleştirir.',
      'Bilinci tam yerine gelmemiş kişiye sıvı vermek tehlikelidir.',
    ],
    objective: 'Bayılmada doğru pozisyonu kavramak.',
    tags: ['bayilma', 'pozisyon', 'dolasim'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-128',
    subject: 'ilkyardim',
    topic: 'zehirlenme',
    difficulty: 'orta',
    stem: 'Kapalı bir garajda egzoz gazından zehirlenmiş kişiye ulaşan ilk yardımcı öncelikle ne yapmalıdır?',
    options: [
      'Kişiye su içirmek',
      'Kişiyi silkelemek',
      'Kişiyi olduğu yerde bırakıp beklemek',
      'Kendi güvenliğini alıp ortamı havalandırmak ve kişiyi temiz havaya çıkarmak',
    ],
    answerIndex: 3,
    explanation:
      'Solunum yoluyla (gazla) zehirlenmede öncelik, ilk yardımcının kendi güvenliğini sağlayıp ortamı havalandırması ve kişiyi temiz havaya çıkarmasıdır; ardından 112 aranır.',
    whyWrong: [
      'Gazlı ortama korunmasız girmek ikinci bir kurban yaratır.',
      'Su içirmek gaz zehirlenmesinde öncelikli ya da güvenli değildir.',
    ],
    objective: 'Gazla zehirlenmede güvenlik ve temiz hava önceliğini kavramak.',
    tags: ['zehirlenme', 'solunum-yolu', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-129',
    subject: 'ilkyardim',
    topic: 'donma',
    difficulty: 'zor',
    stem: 'Soğukta uzun süre kalıp elleri donmaya başlayan bir kişiye ilk yardımda ne yapılmamalıdır?',
    options: [
      'Kişiyi ılık bir ortama almak',
      'Donan bölgeyi kar ile ya da sertçe ovmak',
      'Islak giysilerini kuru olanlarla değiştirmek',
      'Bilinci açıksa ılık içecek vermek',
    ],
    answerIndex: 1,
    explanation:
      'Donan bölge kar ile ya da sertçe ovulmamalıdır; ovmak zaten hasarlı olan dokuyu daha da zedeler. Kişi yavaşça ılık ortama alınıp korunur.',
    whyWrong: [
      'Ilık ortama almak ve kuru giysi doğru uygulamalardır.',
      'Bilinci açık kişiye ılık içecek vermek uygundur.',
    ],
    objective: 'Donmada yapılmaması gerekenleri kavramak.',
    tags: ['donma', 'yanlis-uygulama', 'isitma'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-130',
    subject: 'ilkyardim',
    topic: 'tyd',
    difficulty: 'zor',
    stem: 'Erişkinde göğüs basıları göğsün hangi bölgesine uygulanır?',
    options: [
      'Göğüs kemiğinin alt ucuna',
      'Sol meme başının üzerine',
      'Göğsün ortasına, göğüs kemiğinin alt yarısına',
      'Karın üst bölgesine',
    ],
    answerIndex: 2,
    explanation:
      'Göğüs basıları göğsün ortasında, göğüs kemiğinin (iman tahtası) alt yarısı üzerine yapılır; el bu bölgeye yerleştirilerek dik biçimde bastırılır.',
    whyWrong: [
      'Kemiğin en alt ucuna bası iç organları zedeleyebilir.',
      'Karın bölgesine ya da yana yapılan bası kalbi etkili sıkıştırmaz.',
    ],
    objective: 'Göğüs basısının doğru yerini bilmek.',
    tags: ['tyd', 'kalp-masaji', 'bası-yeri'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
];
