/**
 * ÖZGÜN direksiyon (uygulama) soruları — 3. genişletme (Program 1). ROADMAP C.4/E.6.
 * Kaynak = MEB direksiyon/uygulama müfredatı; KENDİ İFADEMİZLE.
 */
import type { QuestionInput } from '@ea/content-schema';

const SRC = 'MEB direksiyon (uygulama) müfredatı (özgün ifade)';

export const PRATIK_QUESTIONS_3: QuestionInput[] = [
  {
    id: 'pratik-301',
    subject: 'pratik',
    topic: 'arac-hazirlik',
    difficulty: 'orta',
    stem: 'Uzun bir yolculuğa çıkmadan önce aracın çevresinde yapılan dış kontrolde (araç turu) öncelikle nelere bakılır?',
    options: [
      'Sadece yakıt göstergesine bakmak yeterlidir',
      'Yalnızca radyo ve klima ayarlarını kontrol etmek',
      'Lastiklerin hava basıncı ve diş durumu, farlar, sinyaller ve araç altında sıvı sızıntısı olup olmadığı kontrol edilir',
      'Yalnızca koltuk kılıflarının temizliğini kontrol etmek',
    ],
    answerIndex: 2,
    explanation:
      'Yola çıkmadan önce yapılan dış kontrol; lastik basıncı ve dişleri, aydınlatma ve sinyallerin çalışması ile araç altında yağ veya soğutma sıvısı sızıntısı gibi güvenliği doğrudan etkileyen unsurları kapsar. Bu kısa gözlem, yolda arıza ve kaza riskini azaltır.',
    whyWrong: [
      'Yakıt göstergesi önemlidir ama tek başına güvenli sürüş için yeterli bir dış kontrol değildir.',
      'Radyo, klima ve koltuk temizliği konforla ilgilidir; aracın yol güvenliğini belirlemez.',
    ],
    objective: 'Sürüş öncesi araç dış (tur) kontrolünde güvenlik unsurlarını gözden geçirebilmek.',
    tags: ['arac-hazirlik', 'lastik-kontrol', 'surus-oncesi'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-302',
    subject: 'pratik',
    topic: 'arac-hazirlik',
    difficulty: 'kolay',
    stem: 'Kontak açıldığında yanan yağ basıncı veya akü (şarj) ikaz ışığı, motor çalıştıktan sonra sönmüyorsa ne yapılmalıdır?',
    options: [
      'Işıklar önemsizdir, yola devam edilir',
      'Sürüşe başlanmadan arıza araştırılır; sorun giderilmeden yola çıkılmaz',
      'Gaz verilerek ışığın sönmesi beklenir',
      'Radyo açılarak dikkat başka yöne çekilir',
    ],
    answerIndex: 1,
    explanation:
      'Yağ basıncı ve şarj ikaz ışıkları motorun temel çalışma güvenliğiyle ilgilidir; motor çalışınca sönmeleri gerekir. Sönmüyorsa ciddi bir arıza belirtisidir ve sürüşe devam etmek motora zarar verebilir ya da yolda arızaya yol açar. Bu yüzden sorun giderilmeden yola çıkılmaz.',
    whyWrong: [
      'İkaz ışıklarını yok saymak, motorun yağsız kalması gibi ağır arızalarla sonuçlanabilir.',
      'Gaz vermek ya da radyo açmak arızayı gidermez; yalnızca belirtiyi görmezden gelmiş olursunuz.',
    ],
    objective: 'Gösterge panelindeki ikaz ışıklarını yorumlayıp arıza durumunda doğru davranmak.',
    tags: ['arac-hazirlik', 'ikaz-isiklari', 'gosterge-paneli'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-303',
    subject: 'pratik',
    topic: 'koltuk-ayna-ayari',
    difficulty: 'kolay',
    stem: 'Sürücü koltuğunun baş desteği (koltuk başlığı) güvenlik açısından nasıl ayarlanmalıdır?',
    options: [
      'Mümkün olduğunca aşağıda, boyun hizasının altında olmalı',
      'Tamamen çıkarılmalı, hiç kullanılmamalı',
      'En yukarı çekilip öylece bırakılmalı, konumun önemi yoktur',
      'Üst kenarı başın tepesine yakın, ortası ise baş arkasını karşılayacak yükseklikte olmalı',
    ],
    answerIndex: 3,
    explanation:
      'Baş desteği, arkadan çarpma anında başın geriye savrulmasını sınırlayarak boyun (kamçı) yaralanmasını önlemek içindir. Bunun için üst kenarı başın tepesine yakın, ortası ise baş arkasını karşılayacak yükseklikte ayarlanmalıdır. Çok alçak destek koruma sağlamaz.',
    whyWrong: [
      'Baş desteğinin çok alçak olması, çarpma anında başın destek üzerinden geriye devrilmesine yol açar.',
      'Desteği çıkarmak ya da konumunu önemsememek boyun yaralanması riskini artırır.',
    ],
    objective: 'Baş desteğini boyun yaralanmasını önleyecek doğru yükseklikte ayarlayabilmek.',
    tags: ['koltuk-ayari', 'bas-destegi', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-304',
    subject: 'pratik',
    topic: 'koltuk-ayna-ayari',
    difficulty: 'kolay',
    stem: 'İç dikiz aynası en doğru biçimde nasıl ayarlanır?',
    options: [
      'Sürüş oturuşunda baş hareket ettirilmeden arka camın tamamını çerçeveleyecek biçimde',
      'Yalnızca aracın tavanı görünecek biçimde yukarı çevrilerek',
      'Yan koltuktaki yolcuyu görecek biçimde yana çevrilerek',
      'Sürücünün kendi yüzünü görebileceği biçimde',
    ],
    answerIndex: 0,
    explanation:
      'İç dikiz aynası, normal sürüş oturuşunda baş çevrilmeden arka camın olabildiğince tamamını gösterecek biçimde ayarlanır. Böylece arkadan gelen trafik tek bakışta izlenebilir. Yanlış açı, arka görüşü daraltır ve arkadaki araçların fark edilmesini geciktirir.',
    whyWrong: [
      'Tavanı ya da sürücünün yüzünü gösteren açı, arka trafiği izleme amacına hizmet etmez.',
      'Aynayı yan yolcuya çevirmek arka görüşü tamamen ortadan kaldırır.',
    ],
    objective: 'İç dikiz aynasını arka camı çerçeveleyecek biçimde doğru ayarlayabilmek.',
    tags: ['ayna-ayari', 'ic-dikiz-ayna', 'arka-gorus'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-305',
    subject: 'pratik',
    topic: 'kalkis',
    difficulty: 'orta',
    stem: 'Düz zeminde sarsıntısız (yumuşak) bir kalkış için gaz ve debriyaj nasıl kullanılmalıdır?',
    options: [
      'Debriyaj basılıyken gaz sonuna kadar verilir, sonra debriyaj birden bırakılır',
      'Hafif ve sabit gaz verilirken debriyaj kavrama noktasına kadar yavaşça bırakılır, araç yüklenince pedal tümüyle serbest bırakılır',
      'Gaz hiç verilmeden debriyaj hızla bırakılır',
      'Önce el freni indirilir, ardından debriyaj ve gaza aynı anda sonuna kadar basılır',
    ],
    answerIndex: 1,
    explanation:
      'Yumuşak kalkışta amaç, motor gücünü tekere yavaş ve dengeli aktarmaktır. Bunun için hafif, sabit gaz verilirken debriyaj kavrama noktasına kadar yavaşça bırakılır; araç ileri yüklenmeye başladığında pedal tam serbest bırakılır. Ani hareketler sarsıntıya ya da stop etmeye yol açar.',
    whyWrong: [
      'Debriyajı birden bırakmak, gaz ne olursa olsun aracı sıçratır veya motoru stop ettirir.',
      'Gaz vermeden kalkışa çalışmak çoğu zaman motorun teklemesine yol açar.',
    ],
    objective: 'Yumuşak kalkış için gaz-debriyaj dengesini doğru kurabilmek.',
    tags: ['kalkis', 'debriyaj', 'gaz-kontrol'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-306',
    subject: 'pratik',
    topic: 'debriyaj-kavrama',
    difficulty: 'kolay',
    stem: 'Debriyaj kullanılmadığı anlarda sol ayak nerede tutulmalıdır?',
    options: [
      'Sürekli debriyaj pedalının üzerinde yarı basılı',
      'Fren pedalının üzerinde hazır',
      'Pedalın solundaki ayak dayama yerinde (ölü pedal) dinlendirilir',
      'Havada, hiçbir yere değmeden',
    ],
    answerIndex: 2,
    explanation:
      'Sol ayak, debriyaj kullanılmadığında pedalın solundaki ayak dayama (ölü pedal) bölümünde dinlendirilir. Böylece pedala istemsiz baskı yapılmaz, bacak yorulmaz ve ani manevralarda gövde desteklenir. Ayağı debriyaj üzerinde tutmak balatayı sürekli aşındırır.',
    whyWrong: [
      'Ayağı debriyaj üzerinde yarı basılı tutmak patinaja ve erken balata aşınmasına yol açar.',
      'Sol ayağı frene koymak, iki ayağın fren-gaz düzeninde karışmasına neden olabilir.',
    ],
    objective: 'Sol ayağın kullanılmadığında ölü pedalda dinlendirilmesi gerektiğini kavramak.',
    tags: ['debriyaj', 'ayak-konumu', 'olu-pedal'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-307',
    subject: 'pratik',
    topic: 'vites-degisimi',
    difficulty: 'kolay',
    stem: 'Araç hızlanırken bir üst vitese geçme zamanı genellikle nasıl anlaşılır?',
    options: [
      'Motor devri (ses ve titreşim) yükselip araç o vitese göre yeterli hıza ulaştığında üst vitese geçilir',
      'Araç durmak üzereyken üst vitese geçilir',
      'Hız ne olursa olsun her birkaç saniyede bir vites yükseltilir',
      'Motor çok düşük devirde titrerken üst vitese geçilir',
    ],
    answerIndex: 0,
    explanation:
      'Araç hızlandıkça motor devri ve sesi yükselir; devir uygun aralığa gelip araç o vitese göre yeterli hıza ulaştığında bir üst vitese geçilir. Bu, motoru zorlamadan ekonomik ve dengeli sürüş sağlar. Çok erken veya çok geç geçiş motoru zorlar.',
    whyWrong: [
      'Araç yavaşlarken ya da düşük devirde üst vitese geçmek motoru tekletir.',
      'Hızı gözetmeden belirli sürelerle vites yükseltmek motorun uygun devirde kalmasını sağlamaz.',
    ],
    objective: 'Üst vitese geçiş zamanını motor devri ve hıza göre belirleyebilmek.',
    tags: ['vites-degisimi', 'motor-devri', 'ust-vites'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-308',
    subject: 'pratik',
    topic: 'vites-degisimi',
    difficulty: 'kolay',
    stem: 'Vites değiştirirken gözler nerede olmalıdır?',
    options: [
      'Vites koluna bakılarak konum doğrulanmalıdır',
      'Gösterge paneline sabitlenmelidir',
      'Debriyaj pedalına bakılmalıdır',
      'Yolda ve trafikte kalmalı, vites kolu ele alışkanlıkla bulunmalıdır',
    ],
    answerIndex: 3,
    explanation:
      'Vites değişimi sırasında gözler yolda ve trafikte kalmalıdır; vites kolunun konumu elle, alışkanlıkla bulunur. Gözü yoldan ayırıp vites koluna bakmak, o kısa sürede önde gelişen bir tehlikeyi kaçırmaya yol açar. Bu yüzden vites değişimi ele güvenerek yapılır.',
    whyWrong: [
      'Vites koluna veya göstergeye bakmak, gözü yoldan ayırdığı için tehlikelidir.',
      'Debriyaj pedalına bakmanın da gözü yoldan alması dışında bir yararı yoktur.',
    ],
    objective: 'Vites değişiminde gözlerin yolda kalması gerektiğini kavramak.',
    tags: ['vites-degisimi', 'goz-yolda', 'dikkat'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-309',
    subject: 'pratik',
    topic: 'rampada-kalkis',
    difficulty: 'zor',
    stem: 'El freni kullanmadan, yalnızca ayak frenini bırakarak yokuşta kalkış yaparken geri kaymayı en aza indiren teknik nedir?',
    options: [
      'Fren ve gazı hiç kullanmadan yalnız debriyajla kalkmak',
      'Önce gaza uzun süre yüklenip sonra debriyaja basmak',
      'Debriyajı kavrama noktasında tutup ayağı frenden hızlıca gaza geçirerek, çekiş oluştuğu an aracı ileri yüklemek',
      'Debriyajı tam bırakıp aracın kendi kendine kalkmasını beklemek',
    ],
    answerIndex: 2,
    explanation:
      'El freni kullanılmadığında geri kaymayı azaltan yöntem, debriyajı kavrama noktasında tutup ayağı frenden gaza olabildiğince hızlı geçirmektir; çekiş oluştuğu an araç ileri yüklenerek kısa bir kayma dışında hareket başlar. Kavrama noktası tutulmadan bu geçiş yapılırsa araç geri kaçar veya stop eder.',
    whyWrong: [
      'Gaza uzun süre yüklenip sonra debriyaja basmak, kalkış anını kaçırır ve motoru gereksiz yükseltir.',
      'Debriyajı tam bırakıp beklemek ya da hiç gaz vermemek çoğu yokuşta motoru stop ettirir.',
    ],
    objective:
      'El freni kullanmadan yokuş kalkışında fren-gaz geçişini hızlı ve dengeli yapabilmek.',
    tags: ['rampada-kalkis', 'debriyaj', 'fren-gaz-gecisi'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-310',
    subject: 'pratik',
    topic: 'yokus-inis',
    difficulty: 'orta',
    stem: 'Uzun ve dik bir inişte (yokuş aşağı) hız kontrolü en güvenli biçimde nasıl sağlanır?',
    options: [
      'Vites boşa alınıp yalnızca fren pedalıyla inilir',
      'Uygun küçük vitese geçilerek motor freninden yararlanılır, fren yalnızca destekleyici olarak kullanılır',
      'Debriyaj sürekli basılı tutulup araç serbest bırakılır',
      'Yüksek viteste kalıp sık sık sert fren yapılır',
    ],
    answerIndex: 1,
    explanation:
      'Dik inişte sürekli fren kullanmak balataları ısıtıp fren gücünü azaltabilir. Güvenli yöntem, uygun küçük vitese geçip motor freninden yararlanmak; fren pedalını yalnızca destekleyici olarak, kısa ve kontrollü kullanmaktır. Böylece hız kontrol altında tutulur.',
    whyWrong: [
      'Boşta ya da debriyaj basılı inmek motor frenini devre dışı bırakır ve tüm yük frenlere biner.',
      'Yüksek viteste kalıp sürekli sert fren yapmak frenlerin aşırı ısınıp zayıflamasına yol açar.',
    ],
    objective: 'Dik inişte motor freninden yararlanarak hızı güvenle kontrol edebilmek.',
    tags: ['yokus-inis', 'motor-freni', 'hiz-kontrol'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-311',
    subject: 'pratik',
    topic: 'geri-manevra',
    difficulty: 'orta',
    stem: 'Geri giderken aracın arkasını istenen yöne yöneltmek için direksiyon ne yönde çevrilir?',
    options: [
      'Aracın arkasının gitmesi istenen yöne doğru çevrilir',
      'Her zaman sola çevrilir',
      'Aracın arkasının gitmesi istenen yönün tersine çevrilir',
      'Direksiyon sabit tutulur, yön yalnızca gazla ayarlanır',
    ],
    answerIndex: 0,
    explanation:
      'Geri manevrada aracın arkası, direksiyonun çevrildiği yöne doğru gider; arkayı sağa yöneltmek için direksiyon sağa, sola yöneltmek için sola çevrilir. Bu ilkeyi bilmek, geri park ve dar alan manevralarında doğru yön vermeyi kolaylaştırır.',
    whyWrong: [
      'Direksiyonu her zaman aynı yöne ya da gidilecek yönün tersine çevirmek aracı yanlış yöne sokar.',
      'Yön gazla değil, direksiyonun çevrildiği yönle belirlenir.',
    ],
    objective: 'Geri manevrada direksiyon yönü ile aracın arka yönü ilişkisini kavramak.',
    tags: ['geri-manevra', 'direksiyon-yonu', 'manevra'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-312',
    subject: 'pratik',
    topic: 'geri-manevra',
    difficulty: 'zor',
    stem: 'Dar bir alanda direksiyon kırılı hâlde geri manevra yapılırken, aracın ön ucuyla ilgili gözden kaçan tehlike nedir?',
    options: [
      'Ön uç hiç hareket etmez, yalnızca arka döner',
      'Ön uç arka ile aynı yöne, aynı miktarda kayar',
      'Ön far kendiliğinden söner',
      'Ön uç, dönülen yönün tersine doğru dışa savrulur ve yandaki araç, direk veya yayaya çarpabilir',
    ],
    answerIndex: 3,
    explanation:
      'Araç geri dönerken arka içeri girerken ön uç, dönülen yönün tersine doğru geniş bir yay çizerek dışa savrulur. Bu salınım fark edilmezse aracın ön köşesi yandaki araca, direğe veya yayaya çarpabilir. Bu yüzden manevrada yalnız arka değil, ön uç da izlenmelidir.',
    whyWrong: [
      'Aracın ön ucu hareketsiz değildir; direksiyon kırılıyken belirgin biçimde dışa salınır.',
      'Ön uç arka ile aynı yöne değil, ters yöne doğru savrulur.',
    ],
    objective: 'Geri dönüşte ön ucun dışa savrulma tehlikesini fark edip kontrol edebilmek.',
    tags: ['geri-manevra', 'on-uc-savrulmasi', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-313',
    subject: 'pratik',
    topic: 'paralel-park',
    difficulty: 'orta',
    stem: 'Önde ve arkada araç bulunan bir paralel park yerinden güvenle çıkmak için doğru yaklaşım nedir?',
    options: [
      'Direksiyonu kırıp doğrudan öne çıkmak',
      'Aynaya bakmadan hızlıca şeride dalmak',
      'Aracı hafif geri alıp öne pay açmak, sinyal verip aynaları ve kör noktayı kontrol ederek uygun boşlukta yavaşça şeride katılmak',
      'Kornaya basıp beklemeden çıkmak',
    ],
    answerIndex: 2,
    explanation:
      'Dar bir paralel park yerinden çıkarken önce aracı hafifçe geriye alıp öne manevra payı açmak işi kolaylaştırır. Ardından sinyal verilir, aynalar ve kör nokta kontrol edilir; arkadan gelen trafikte uygun boşluk oluştuğunda araç yavaşça şeride katılır. Kontrolsüz çıkış çarpışmaya yol açar.',
    whyWrong: [
      'Doğrudan öne kırıp çıkmak, öndeki araca çarpma ve karşı şeride taşma riski taşır.',
      'Aynaya bakmadan dalmak ya da yalnız kornaya güvenmek arkadan gelen aracı görmeyi sağlamaz.',
    ],
    objective: 'Paralel park yerinden gözlem ve sinyalle güvenli çıkış yapabilmek.',
    tags: ['paralel-park', 'park-cikis', 'kor-nokta'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-314',
    subject: 'pratik',
    topic: 'paralel-park',
    difficulty: 'orta',
    stem: 'Paralel park tamamlandıktan sonra aracın konumunun doğru olduğunu değerlendiren ölçüt nedir?',
    options: [
      'Aracın kaldırıma çıkmış olması',
      'Aracın kaldırıma yakın ve ona paralel durması, ön-arka araçlarla makul ve dengeli mesafe bırakması',
      'Aracın yola doğru açılı, arkası dışarıda durması',
      'Aracın diğer araçlara değecek kadar yakın olması',
    ],
    answerIndex: 1,
    explanation:
      'Başarılı paralel parkta araç, kaldırıma yakın ve ona paralel durmalı, öndeki ve arkadaki araçlarla makul, dengeli bir mesafe bırakmalıdır. Böylece araç trafiği engellemez, komşu araçların çıkışını da zorlaştırmaz. Açılı veya kaldırıma çıkmış duruş hatalı sayılır.',
    whyWrong: [
      'Kaldırıma çıkmak ya da yola açılı durmak trafiği ve yayaları engeller, hatalı parktır.',
      'Diğer araçlara değecek kadar yakın durmak onların manevrasını imkânsız kılar.',
    ],
    objective: 'Tamamlanan paralel parkta doğru konumu değerlendirebilmek.',
    tags: ['paralel-park', 'park-konumu', 'kaldirim-mesafesi'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-315',
    subject: 'pratik',
    topic: 'dik-park',
    difficulty: 'zor',
    stem: 'Boş bir dik (90 derece) park cebine geri geri girerken izlenecek doğru manevra sırası nedir?',
    options: [
      'Cebe ileri yönde, direksiyon sabit girilir',
      'Direksiyon tek seferde sonuna kadar kırılıp gazla girilir',
      'Aynalara bakmadan sezgiyle geri gidilir',
      'Cebi hafif geçip hizalanılır, uygun noktada direksiyon boşluğa doğru kırılır, aynalar ve arka izlenerek yavaşça geri girilir, araç düzelince direksiyon toparlanır',
    ],
    answerIndex: 3,
    explanation:
      'Dik park manevrasında araç, park cebini hafifçe geçip hizalanır; uygun referans noktasında direksiyon boşluğa doğru kırılır ve aynalarla arka izlenerek düşük hızda geri girilir. Araç çizgilere paralel hâle geldikçe direksiyon toparlanır. Bu kademeli yaklaşım aracı cebe düzgün oturtur.',
    whyWrong: [
      'İleri girmek veya direksiyonu tek hamlede sonuna kadar kırıp gazlamak aracı yanlış açıyla sokar.',
      'Aynalara bakmadan geri gitmek komşu araçları ve yayaları görmeyi engeller.',
    ],
    objective:
      'Dik park cebine geri girişte kademeli direksiyon ve gözlem sırasını uygulayabilmek.',
    tags: ['dik-park', 'geri-manevra', 'ayna-kontrol'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-316',
    subject: 'pratik',
    topic: 'dik-park',
    difficulty: 'orta',
    stem: 'Dik park edilmiş bir cepten öne doğru çıkarken en önemli güvenlik önlemi nedir?',
    options: [
      'Yavaşça ilerleyip iki yandan gelen araçları ve önden geçen yayaları görene kadar burnu dikkatle dışarı vermek',
      'Hızla çıkıp trafiğe hemen katılmak',
      'Sadece sol aynaya bakıp çıkmak',
      'Kornaya basıp gözlem yapmadan çıkmak',
    ],
    answerIndex: 0,
    explanation:
      'Dik cepten çıkarken yanlardaki park etmiş araçlar görüşü kapatır; bu yüzden araç yavaşça ilerletilip burnu dikkatle dışarı verilerek iki yandan gelen araçlar ve önden geçen yayalar görülene kadar temkinli davranılır. Ani ve hızlı çıkış, görülemeyen bir araçla çarpışmaya yol açar.',
    whyWrong: [
      'Hızlı çıkış, yanlardan gelen görülemeyen araç veya yaya için ciddi çarpışma riski taşır.',
      'Tek aynaya bakmak ya da yalnız kornaya güvenmek çevrenin tümünü görmeyi sağlamaz.',
    ],
    objective: 'Dik park cebinden çıkarken kademeli ve gözlemli çıkış yapabilmek.',
    tags: ['dik-park', 'park-cikis', 'yaya-guvenligi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-317',
    subject: 'pratik',
    topic: 'seritler-donusler',
    difficulty: 'orta',
    stem: 'Çok şeritli bir yolda sağa dönüş tamamlandığında araç normalde hangi şeride yerleşmelidir?',
    options: [
      'Karşı yönün en soldaki şeridine',
      'Orta şeride, sinyal vermeden',
      'Girdiği yolun kendi yönündeki en sağ (dönüşe en yakın) şeride',
      'Kaldırıma en yakın park şeridine',
    ],
    answerIndex: 2,
    explanation:
      'Sağa dönüşte araç, döndüğü yolun kendi yönündeki en sağ şeridine yerleşir. Bu, dönüşü kısa ve düzenli tutar, karşı trafiğe taşmayı ve gereksiz şerit ihlallerini önler. Dönüşten sonra gerekirse uygun kontrolle iç şeride geçilebilir.',
    whyWrong: [
      'Karşı yönün şeridine geçmek ciddi bir kural ihlali ve kafa kafaya çarpışma riskidir.',
      'Dönüşü geniş alıp orta veya uzak şeride yerleşmek diğer araçların yolunu keser.',
    ],
    objective: 'Dönüş sonrası doğru (en yakın) şeride yerleşme kuralını uygulayabilmek.',
    tags: ['seritler-donusler', 'donus-serit', 'yol-pozisyonu'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-318',
    subject: 'pratik',
    topic: 'seritler-donusler',
    difficulty: 'kolay',
    stem: 'Düz bir yolda şerit içinde ilerlerken aracın konumu nasıl olmalıdır?',
    options: [
      'Şerit çizgisine sürekli basarak',
      'Şeridin ortasında, iki çizgiye de yaklaşık eşit mesafede',
      'Sürekli sağ çizgiye yaslanarak',
      'İki şeride birden yayılarak',
    ],
    answerIndex: 1,
    explanation:
      'Araç, şeridin ortasında ve iki çizgiye de yaklaşık eşit uzaklıkta tutulmalıdır. Bu konum, yandan gelen araçlara güvenli boşluk bırakır ve sürücüye küçük düzeltmeler için pay tanır. Çizgiye basmak veya iki şeride yayılmak komşu şeritteki araçları tehlikeye atar.',
    whyWrong: [
      'Çizgiye basmak ya da bir tarafa yaslanmak yandaki araçla güvenli mesafeyi bozar.',
      'İki şeride yayılmak diğer sürücüleri şaşırtır ve sıkışmaya yol açar.',
    ],
    objective: 'Şerit içinde dengeli yol pozisyonunu koruyabilmek.',
    tags: ['seritler-donusler', 'serit-takibi', 'yol-pozisyonu'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-319',
    subject: 'pratik',
    topic: 'seritler-donusler',
    difficulty: 'orta',
    stem: 'Çok şeritli bir yolda, geçiş (sollama) yapmıyorken normal seyirde hangi şerit kullanılmalıdır?',
    options: [
      'Sürekli en sol şerit',
      'İstenen herhangi bir şerit, kural yoktur',
      'En soldaki şeritte yavaş gitmek serbesttir',
      'Sağ şerit; sol şeritler yalnızca öndeki aracı geçmek için kullanılıp geçiş sonrası tekrar sağa dönülür',
    ],
    answerIndex: 3,
    explanation:
      'Çok şeritli yollarda genel kural, normal seyirde sağ şeritte gitmek; sol şeritleri yalnızca öndeki aracı geçmek için kullanıp geçişten sonra tekrar sağa dönmektir. Sol şeridi gereksiz yere sürekli işgal etmek trafiği yavaşlatır ve kural ihlalidir.',
    whyWrong: [
      'En sol şeritte sürekli ya da yavaş gitmek arkadan gelen hızlı trafiği tıkar ve kurala aykırıdır.',
      'Şerit seçiminde kural olmadığını düşünmek yanlıştır; sağdan gitme esastır.',
    ],
    objective: 'Çok şeritli yolda sağdan gitme ve sollama sonrası sağa dönme kuralını uygulamak.',
    tags: ['seritler-donusler', 'serit-kurallari', 'sollama'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-320',
    subject: 'pratik',
    topic: 'kavsak-gecis',
    difficulty: 'orta',
    stem: 'Işıklı bir kavşağa yaklaşırken ışık yeşilden sarıya döndüğünde kural olarak ne yapılmalıdır?',
    options: [
      'Güvenle durulabilecek mesafedeyse yavaşlayıp durmak; kavşağa çok girilmişse ve durmak tehlikeliyse geçişi dikkatle tamamlamak',
      'Her durumda gaza basıp hızla geçmek',
      'Kavşağın ortasında durup beklemek',
      'Sarı ışıkta her koşulda sert fren yaparak durmak',
    ],
    answerIndex: 0,
    explanation:
      'Sarı ışık, kırmızıya hazırlık uyarısıdır. Kural olarak güvenle durulabilecek mesafedeyse yavaşlayıp durak çizgisinde durulur; ancak araç kavşağa çok girmişse ve durmak arkadan çarpma gibi bir tehlike doğuruyorsa geçiş dikkatle tamamlanır. Amaç ani ve tehlikeli hareketlerden kaçınmaktır.',
    whyWrong: [
      'Sarıda her zaman gaza basmak, kırmızıya yakalanma ve kavşak içi çarpışma riski doğurur.',
      'Kavşak ortasında durmak ya da her koşulda sert fren yapmak arkadan çarpma ve kilitlenmeye yol açar.',
    ],
    objective: 'Sarı ışıkta dur/geç kararını güvenlik ölçütüne göre verebilmek.',
    tags: ['kavsak-gecis', 'sari-isik', 'trafik-isiklari'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-321',
    subject: 'pratik',
    topic: 'kavsak-gecis',
    difficulty: 'kolay',
    stem: 'Yeşil ışıkta sağa dönerken, döndüğünüz yoldaki yaya geçidinden yayalar geçiyorsa ne yapılır?',
    options: [
      'Yayalar bekler, araç önce geçer',
      'Kornaya basıp yayaları hızlandırmak',
      'Yayalara yol verilir, geçişleri bitince dönüş tamamlanır',
      'Yayaların arasından dikkatlice geçilir',
    ],
    answerIndex: 2,
    explanation:
      'Işık sürücü için yeşil olsa da dönülen yoldaki yaya geçidini kullanan yayaların geçiş üstünlüğü vardır. Sürücü durup yayalara yol verir, geçişleri tamamlanınca dönüşünü sürdürür. Yaya önceliği, kavşak güvenliğinin temel kurallarından biridir.',
    whyWrong: [
      'Yayaları bekletip önce geçmek ya da aralarından geçmek yaya önceliğini ihlal eder ve tehlikelidir.',
      'Korna çalmak yayaları uyarmaz, yalnızca baskı kurar ve güvenliği artırmaz.',
    ],
    objective: 'Dönüşte yaya geçidindeki yayalara yol verme kuralını uygulayabilmek.',
    tags: ['kavsak-gecis', 'yaya-onceligi', 'donus'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-322',
    subject: 'pratik',
    topic: 'kavsak-gecis',
    difficulty: 'orta',
    stem: 'İleride trafik sıkışıkken ve kavşağın karşı tarafında duracak yer yokken kavşağa nasıl davranılır?',
    options: [
      'Kavşağa girip ortada beklemek',
      'Kornaya basıp öndekileri zorlamak',
      'Sinyal verip kavşak içinde durmak',
      'Kavşağa girilmez; karşı tarafta aracın sığacağı boşluk oluşana kadar kavşak öncesinde beklenir',
    ],
    answerIndex: 3,
    explanation:
      'Karşı tarafta duracak yer yokken kavşağa girmek, ışık kırmızıya döndüğünde aracın kavşak ortasında kalıp yan yönlerin geçişini kilitlemesine yol açar. Doğru davranış, karşıda aracın sığacağı boşluk açılana kadar kavşak öncesinde beklemektir. Böylece kavşak akışı tıkanmaz.',
    whyWrong: [
      'Kavşağa girip ortada beklemek yan yönlerdeki trafiği ve yayaları kilitler.',
      'Korna çalmak ya da kavşak içinde sinyalle durmak tıkanıklığı çözmez, düzeni bozar.',
    ],
    objective: 'Karşı tarafı boş olmayan kavşağa girmeyip akışı kilitlememeyi öğrenmek.',
    tags: ['kavsak-gecis', 'kavsak-kilitleme', 'trafik-akisi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-323',
    subject: 'pratik',
    topic: 'hiz-mesafe-kontrol',
    difficulty: 'kolay',
    stem: 'Normal koşullarda öndeki araçla güvenli takip mesafesini belirlemenin pratik yolu nedir?',
    options: [
      'Öndeki aracın hemen arkasına yaklaşmak',
      'Öndeki araç sabit bir noktayı geçtikten sonra en az iki saniye geçtiğinde o noktaya varacak kadar mesafe bırakmak',
      'Hız ne olursa olsun tek araç boyu mesafe yeterlidir',
      'Mesafe önemli değildir, önemli olan frenlerin iyi olmasıdır',
    ],
    answerIndex: 1,
    explanation:
      'Güvenli takip mesafesi, hızla birlikte değişen bir zaman ölçütüyle belirlenir: öndeki araç bir noktayı geçtikten en az iki saniye sonra o noktaya varılıyorsa mesafe uygundur. Bu süre, önde ani bir fren olduğunda tepki verip durmaya yetecek payı sağlar. Olumsuz havada süre artırılır.',
    whyWrong: [
      'Öndeki araca yaklaşmak, ani frende arkadan çarpmayı neredeyse kaçınılmaz kılar.',
      'Sabit tek araç boyu mesafe yüksek hızda çok yetersizdir; mesafe hızla artmalıdır.',
    ],
    objective: 'İki saniye kuralıyla güvenli takip mesafesini belirleyebilmek.',
    tags: ['hiz-mesafe-kontrol', 'takip-mesafesi', 'iki-saniye'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-324',
    subject: 'pratik',
    topic: 'hiz-mesafe-kontrol',
    difficulty: 'zor',
    stem: 'Aracın hızı iki katına çıktığında frenleme (durma) mesafesi yaklaşık nasıl değişir?',
    options: [
      'Yaklaşık dört katına çıkar',
      'Yaklaşık aynı kalır',
      'Yaklaşık yarısına iner',
      'Yalnızca çok az artar',
    ],
    answerIndex: 0,
    explanation:
      'Frenleme mesafesi hızın karesiyle orantılı olarak artar; bu nedenle hız iki katına çıktığında yalnız fren mesafesi kabaca dört katına çıkar. Buna sürücünün tepki mesafesi de eklenir. Bu ilişki, yüksek hızda neden çok daha erken ve dikkatli davranmak gerektiğini açıklar.',
    whyWrong: [
      'Durma mesafesinin sabit kalması ya da azalması fizik kurallarına aykırıdır.',
      'Mesafenin yalnızca çok az artması, hız-mesafe ilişkisini ciddi biçimde küçümsemektir.',
    ],
    objective: 'Hız ile frenleme mesafesi arasındaki kare ilişkisini kavramak.',
    tags: ['hiz-mesafe-kontrol', 'frenleme-mesafesi', 'hiz'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-325',
    subject: 'pratik',
    topic: 'hiz-mesafe-kontrol',
    difficulty: 'zor',
    stem: 'Görüşün kısıtlı olduğu (tepe üstü, keskin viraj, sis) durumlarda hız nasıl ayarlanmalıdır?',
    options: [
      'Yol boşmuş gibi normal hızda gidilir',
      'Hız artırılıp bölge çabucak geçilir',
      'Görülebilen mesafe içinde güvenle durabilecek kadar hız düşürülür',
      'Yalnızca farlar açılır, hız değiştirilmez',
    ],
    answerIndex: 2,
    explanation:
      'Temel güvenlik ilkesi, sürücünün önünde net görebildiği mesafe içinde aracı durdurabilecek bir hızda gitmesidir. Tepe üstü, keskin viraj veya sis gibi görüşün kısıtlandığı yerlerde bu mesafe kısaldığından hız da düşürülmelidir. Aksi hâlde aniden beliren bir engelde durmak imkânsızlaşır.',
    whyWrong: [
      'Görüş kısıtlıyken normal hızda gitmek, aniden çıkan engelde durmaya yetecek mesafe bırakmaz.',
      'Hızlanmak ya da yalnız far açıp hızı korumak görüş mesafesi sorununu çözmez.',
    ],
    objective: 'Hızı, güvenle durulabilecek görüş mesafesine göre ayarlayabilmek.',
    tags: ['hiz-mesafe-kontrol', 'gorus-mesafesi', 'hiz-ayari'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-326',
    subject: 'pratik',
    topic: 'hiz-mesafe-kontrol',
    difficulty: 'kolay',
    stem: 'Okul, hastane ve yoğun yaya bölgelerinden geçerken sürücü ne yapmalıdır?',
    options: [
      'Normal hızını korumak',
      'Kornaya basıp yayaları uyarmak yeterlidir',
      'Yalnızca sinyal vererek geçmek',
      'Hızı belirgin biçimde düşürmek ve özellikle çocuklar için her an durmaya hazır olmak',
    ],
    answerIndex: 3,
    explanation:
      'Okul ve yoğun yaya bölgelerinde yayalar, özellikle çocuklar, aniden yola çıkabilir. Bu yüzden sürücü hızını belirgin biçimde düşürmeli ve her an durabilecek biçimde temkinli ilerlemelidir. Düşük hız, hem tepki süresi hem de olası bir çarpışmanın şiddeti açısından belirleyicidir.',
    whyWrong: [
      'Normal hızı korumak, aniden yola çıkan bir yaya için durma payı bırakmaz.',
      'Korna veya sinyal, hız düşürmenin yerini tutmaz; asıl önlem yavaşlamaktır.',
    ],
    objective: 'Yaya yoğun bölgelerde hız düşürüp temkinli sürüşü uygulayabilmek.',
    tags: ['hiz-mesafe-kontrol', 'okul-bolgesi', 'yaya-guvenligi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-327',
    subject: 'pratik',
    topic: 'sinyal-kullanimi',
    difficulty: 'orta',
    stem: 'Dönel kavşakta (göbekli kavşak) çıkış yaparken doğru sinyal kullanımı nasıldır?',
    options: [
      'Girişte de çıkışta da sinyal verilmez',
      'Çıkmak istenen kola yaklaşırken sağ sinyal verilir',
      'Kavşağa girerken her zaman sol sinyal verilip çıkışta kapatılır',
      'Yalnızca kornaya basmak yeterlidir',
    ],
    answerIndex: 1,
    explanation:
      'Dönel kavşakta genel uygulama, çıkmak istediğiniz kola yaklaşırken sağ sinyali vererek çıkış niyetini bildirmektir. Böylece kavşağa girmeyi bekleyen ve arkanızdaki sürücüler hareketinizi öngörebilir. Doğru zamanlı çıkış sinyali, kavşak içi kararsızlığı ve çarpışmayı önler.',
    whyWrong: [
      'Hiç sinyal vermemek, diğer sürücülerin sizin çıkışınızı öngörmesini engeller.',
      'Yalnız kornaya basmak niyet bildirmez; iletişim sinyalle sağlanır.',
    ],
    objective: 'Dönel kavşakta çıkış öncesi sağ sinyal kullanımını uygulayabilmek.',
    tags: ['sinyal-kullanimi', 'donel-kavsak', 'cikis-sinyali'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-328',
    subject: 'pratik',
    topic: 'sinyal-kullanimi',
    difficulty: 'kolay',
    stem: 'Yol kenarına park etmek veya duraklamak için sağa yanaşırken ne yapılmalıdır?',
    options: [
      'Sağ sinyal verip aynadan arkayı kontrol ederek yavaşça sağa yanaşmak',
      'Sinyal vermeden aniden sağa çekmek',
      'Sol sinyal verip sağa yanaşmak',
      'Dörtlü flaşör yakıp hızla durmak',
    ],
    answerIndex: 0,
    explanation:
      'Sağa yanaşıp duraklama veya park niyeti, sağ sinyalle önceden bildirilir; ayna ile arkadan gelen trafik kontrol edilir ve hız kademeli düşürülerek yavaşça sağa yanaşılır. Bu, arkadaki sürücülerin ve varsa bisikletlilerin hazırlanmasını sağlar.',
    whyWrong: [
      'Sinyalsiz ve ani sağa çekiş, arkadan geleni ve sağdaki bisikletliyi hazırlıksız yakalar.',
      'Sola sinyal vermek yönle çelişir; dörtlüyle ani durmak da niyeti doğru bildirmez.',
    ],
    objective: 'Sağa yanaşma öncesi doğru sinyal ve ayna kontrolünü uygulayabilmek.',
    tags: ['sinyal-kullanimi', 'duraklama', 'saga-yanasma'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-329',
    subject: 'pratik',
    topic: 'kor-nokta',
    difficulty: 'orta',
    stem: 'Kamyon ve otobüs gibi büyük araçların yakınında seyrederken kör noktalar açısından en doğru davranış nedir?',
    options: [
      'Uzun süre yanlarında, aynı hizada seyretmek',
      'Hemen arkalarına çok yakın durmak',
      'Kör noktalarında uzun kalmamak; ya güvenle geçmek ya da geride, sürücünün görebileceği bir mesafede kalmak',
      'Farları yakıp yanlarında beklemek',
    ],
    answerIndex: 2,
    explanation:
      'Büyük araçların yanları, önü ve arkasında geniş kör noktalar vardır; sürücü aynalarından sizi göremeyebilir. Güvenli davranış, bu bölgelerde uzun kalmamak, gerekiyorsa kararlı biçimde geçmek ya da aracın gerisinde, sürücünün sizi görebileceği bir mesafede kalmaktır. Aracın aynasını göremiyorsanız sürücü de sizi göremez.',
    whyWrong: [
      'Büyük aracın yanında uzun süre aynı hizada kalmak, o araç şerit değiştirdiğinde sıkışma riski doğurur.',
      'Arkasına çok yakın durmak hem kör noktada kalmak hem de ani frende çarpmak demektir.',
    ],
    objective: 'Büyük araçların kör noktalarında kalmadan güvenli konum almayı öğrenmek.',
    tags: ['kor-nokta', 'buyuk-arac', 'guvenli-mesafe'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-330',
    subject: 'pratik',
    topic: 'kor-nokta',
    difficulty: 'orta',
    stem: 'Bir otoparkta veya evin önünde geri manevraya başlamadan önce arka kör nokta için en güvenli önlem nedir?',
    options: [
      'Yalnızca iç aynaya bakmak',
      'Hızlıca geri gidip son anda durmak',
      'Kornaya basıp beklemeden geri gitmek',
      'Şüphe varsa araçtan inip arkayı kontrol etmek; özellikle küçük çocuk veya alçak engel olmadığından emin olduktan sonra çok yavaş geri gitmek',
    ],
    answerIndex: 3,
    explanation:
      'Aracın hemen arkasındaki alçak bölge, aynalardan görünmeyen ciddi bir kör noktadır; burada küçük bir çocuk ya da alçak engel gözden kaçabilir. En güvenli önlem, şüphe varsa araçtan inip arkayı kontrol etmek, ardından çok yavaş ve gözlem yaparak geri gitmektir. Görülemeyen alan en büyük risktir.',
    whyWrong: [
      'Yalnız iç aynaya bakmak, aracın hemen arkasındaki alçak kör noktayı göstermez.',
      'Hızlı geri gitmek ya da yalnız kornaya güvenmek, arkadaki çocuğu veya engeli fark etmeyi sağlamaz.',
    ],
    objective:
      'Geri manevra öncesi arka kör noktayı, gerekirse inip kontrol dâhil önlemlerle güvenceye almak.',
    tags: ['kor-nokta', 'geri-manevra', 'cocuk-guvenligi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-331',
    subject: 'pratik',
    topic: 'gece-surus',
    difficulty: 'kolay',
    stem: 'Gece boş bir yolda uzun far (uzun huzme) kullanırken karşıdan bir araç geldiğinde ne yapılır?',
    options: [
      'Uzun far açık tutulur',
      'Karşı sürücünün gözünü almamak için kısa fara (yakın huzme) geçilir',
      'Farlar tamamen kapatılır',
      'Dörtlü flaşör yakılır',
    ],
    answerIndex: 1,
    explanation:
      'Uzun far, karşıdan gelen sürücünün gözünü alarak onu birkaç saniye görmez hâle getirebilir. Bu yüzden karşıdan araç geldiğinde ya da öndeki araca yaklaşıldığında kısa fara geçilir. Karşı araç geçtikten sonra yol yeniden boşsa uzun fara dönülebilir.',
    whyWrong: [
      'Uzun farı açık tutmak karşı sürücüyü kör ederek kazaya yol açabilir.',
      'Farları tamamen kapatmak ya da flaşör yakmak yolu göremez hâle getirir ve yanlış sinyal verir.',
    ],
    objective: 'Gece karşı araç varken uzun fardan kısa fara geçme kuralını uygulamak.',
    tags: ['gece-surus', 'far-kullanimi', 'uzun-far'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-332',
    subject: 'pratik',
    topic: 'gece-surus',
    difficulty: 'orta',
    stem: 'Gece sürüşünde karşıdan gelen aracın farları gözünüzü kamaştırdığında ne yapmalısınız?',
    options: [
      'Bakışı yolun sağ kenar çizgisine kaydırıp hızı düşürerek şeridi takip etmek',
      'Doğrudan karşı farlara bakmaya devam etmek',
      'Gözleri kapatıp hızı korumak',
      'Kendi uzun farınızı yakıp karşılık vermek',
    ],
    answerIndex: 0,
    explanation:
      'Karşı farın kamaştırması geçici görme kaybı yaratır. Doğru tepki, doğrudan ışığa bakmamak; bakışı yolun sağ kenar çizgisine kaydırıp bu çizgiyi rehber alarak şeridi korumak ve hızı düşürmektir. Böylece göz kamaşması geçene kadar yolda kalınır.',
    whyWrong: [
      'Doğrudan farlara bakmak kamaşmayı artırır ve birkaç saniye kör kalmaya yol açar.',
      'Gözleri kapatmak ya da karşıya uzun far yakmak tehlikeyi büyütür, çözmez.',
    ],
    objective:
      'Gece far kamaşmasında sağ kenarı rehber alıp hızı düşürerek yolda kalmayı öğrenmek.',
    tags: ['gece-surus', 'far-kamasmasi', 'gorus'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-333',
    subject: 'pratik',
    topic: 'gece-surus',
    difficulty: 'zor',
    stem: 'Gece sürüşünde uygun hızın belirlenmesinde temel ölçüt nedir?',
    options: [
      'Gündüzle aynı hızda gitmek',
      'Yol boş göründüğü için hızı artırmak',
      'Farların aydınlattığı mesafe içinde güvenle durabilecek bir hızda gitmek',
      'Yalnızca hız limitine uymak, görüşü dikkate almamak',
    ],
    answerIndex: 2,
    explanation:
      'Gece görüş, farların aydınlattığı mesafeyle sınırlıdır. Güvenli hız, bu aydınlanan mesafe içinde beliren bir engelde aracı durdurabilecek düzeyde olmalıdır. Kısa farla bu mesafe daha da kısaldığından hız buna göre ayarlanır. Hız limiti üst sınırdır; görüş elverişsizse limitin altına inilir.',
    whyWrong: [
      'Gece gündüzle aynı hızda ya da daha hızlı gitmek, kısıtlı görüş nedeniyle durma payı bırakmaz.',
      'Yalnız hız limitine bakıp görüşü yok saymak, farın gösterdiği mesafeyi aşan bir hıza yol açar.',
    ],
    objective: 'Gece hızını farın aydınlattığı durma mesafesine göre ayarlayabilmek.',
    tags: ['gece-surus', 'hiz-kontrol', 'far-mesafesi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-334',
    subject: 'pratik',
    topic: 'olumsuz-hava',
    difficulty: 'orta',
    stem: 'Yağmurlu ve ıslak zeminde sürüşte kayma (su üstünde kızaklama) riskini azaltmak için ne yapılır?',
    options: [
      'Hızı artırıp su birikintilerini çabuk geçmek',
      'Takip mesafesini kısaltmak',
      'Ani fren ve sert direksiyonla yol denemek',
      'Hızı düşürmek, takip mesafesini artırmak, ani fren ve direksiyondan kaçınmak',
    ],
    answerIndex: 3,
    explanation:
      'Islak zeminde lastiğin yola tutunması azalır; yüksek hızda lastikle yol arasına su girip kızaklama (aquaplaning) olabilir. Riski azaltmak için hız düşürülür, takip mesafesi artırılır ve fren, gaz, direksiyon hareketleri yumuşak yapılır. Ani hareketler tutunmayı büsbütün kaybettirir.',
    whyWrong: [
      'Hızı artırmak su üstünde kızaklama olasılığını doğrudan yükseltir.',
      'Takip mesafesini kısaltmak ya da ani fren-direksiyon uygulamak ıslak yolda savrulmaya yol açar.',
    ],
    objective: 'Islak zeminde hız, mesafe ve yumuşak kumandayla kayma riskini azaltabilmek.',
    tags: ['olumsuz-hava', 'islak-zemin', 'aquaplaning'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-335',
    subject: 'pratik',
    topic: 'olumsuz-hava',
    difficulty: 'kolay',
    stem: 'Yoğun sisli bir yolda sürüş yaparken far kullanımı nasıl olmalıdır?',
    options: [
      'Uzun far yakmak görüşü artırır',
      'Kısa far ve varsa sis farı kullanmak, hızı düşürmek',
      'Farları kapatıp dörtlü flaşörle gitmek',
      'Yalnızca park (gabari) lambalarıyla ilerlemek',
    ],
    answerIndex: 1,
    explanation:
      'Siste uzun far, ışığı sis parçacıklarından geri yansıtıp bir beyaz perde oluşturarak görüşü daha da bozar. Doğru kullanım kısa far ve varsa sis farıdır; ayrıca görüş kısaldığı için hız belirgin biçimde düşürülür. Böylece hem yol az da olsa görülür hem de öndeki araçlara zamanında tepki verilir.',
    whyWrong: [
      'Uzun far siste görüşü artırmaz, aksine yansıyan ışıkla bozar.',
      'Farları kapatmak ya da yalnız park lambasıyla gitmek aracı görünmez ve yolu karanlık kılar.',
    ],
    objective: 'Siste kısa/sis farı ve düşük hızla güvenli sürüşü uygulayabilmek.',
    tags: ['olumsuz-hava', 'sis', 'far-kullanimi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-336',
    subject: 'pratik',
    topic: 'olumsuz-hava',
    difficulty: 'orta',
    stem: 'Buzlu veya karlı zeminde araç hâkimiyetini korumak için kumanda hareketleri nasıl olmalıdır?',
    options: [
      'Gaz, fren ve direksiyon yumuşak ve kademeli kullanılır, hız düşük tutulur',
      'Hızlı gaz verip tekerleği döndürerek buz kırılır',
      'Sert ve ani fren yapılır',
      'Direksiyon hızlı ve büyük açılarla çevrilir',
    ],
    answerIndex: 0,
    explanation:
      'Buzlu-karlı zeminde tutunma çok azdır; her ani hareket tekerleklerin kaymasına yol açar. Bu yüzden gaz, fren ve direksiyon yumuşak ve kademeli kullanılır, hız düşük tutulur ve takip mesafesi artırılır. Yavaş ve öngörülü kumanda, kaymayı önlemenin temelidir.',
    whyWrong: [
      'Hızlı gaz vermek tekerleği patinaj yaptırıp aracın yönünü kaybettirir.',
      'Sert fren ya da ani büyük direksiyon hareketleri kaygan zeminde savrulmaya yol açar.',
    ],
    objective: 'Kaygan zeminde yumuşak, kademeli kumanda ile hâkimiyeti korumayı öğrenmek.',
    tags: ['olumsuz-hava', 'buzlu-zemin', 'arac-hakimiyeti'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-337',
    subject: 'pratik',
    topic: 'acil-durum',
    difficulty: 'zor',
    stem: 'Sürüş sırasında fren pedalı tutmaz veya boşalırsa yapılması gereken doğru yaklaşım nedir?',
    options: [
      'Kontağı hemen kapatıp direksiyonu bırakmak',
      'Gaza basıp bir an önce durağa varmaya çalışmak',
      'Fren pedalını üst üste pompalamayı denemek, küçük viteslere geçip motor freninden yararlanmak ve el frenini kademeli çekerek aracı güvenle yavaşlatmak',
      'Kapıyı açıp araçtan atlamak',
    ],
    answerIndex: 2,
    explanation:
      'Fren boşaldığında panik yerine kademeli önlemler uygulanır: pedal üst üste pompalanarak basınç geri kazanılmaya çalışılır, küçük viteslere inilerek motor freninden yararlanılır ve el freni kademeli, kontrollü çekilerek araç yavaşlatılır. Aynı anda dörtlü yakılıp güvenli bir kenara yönelinir.',
    whyWrong: [
      'Kontağı kapatmak direksiyon ve fren desteğini kilitleyebilir, direksiyonu bırakmak hâkimiyeti yitirir.',
      'Gaza basmak hızı artırır; araçtan atlamak neredeyse kesin ağır yaralanma demektir.',
    ],
    objective:
      'Fren arızasında pompalama-motor freni-el freni sırasıyla güvenli yavaşlamayı öğrenmek.',
    tags: ['acil-durum', 'fren-arizasi', 'motor-freni'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-338',
    subject: 'pratik',
    topic: 'acil-durum',
    difficulty: 'zor',
    stem: 'Yüksek hızda seyrederken ön lastiklerden biri aniden patlarsa ilk doğru tepki nedir?',
    options: [
      'Hemen sert fren yapmak',
      'Direksiyonu patlayan tarafın tersine sertçe kırmak',
      'Gaza basıp hızı korumak',
      'Direksiyonu iki elle sıkıca ve düz tutmak, gazı yavaşça bırakmak, sert fren yapmadan hızı azaltıp aracı güvenle kenara almak',
    ],
    answerIndex: 3,
    explanation:
      'Lastik patladığında araç patlayan tarafa doğru çekmeye başlar. Sert fren veya ani direksiyon aracı savurabilir. Doğru tepki, direksiyonu iki elle sıkıca ve düz tutmak, gazı yavaşça bırakıp hızın kendiliğinden düşmesini beklemek ve kontrol sağlandıkça yumuşak biçimde güvenli bir kenara yanaşmaktır.',
    whyWrong: [
      'Sert fren, dengesi bozulmuş araçta savrulmayı tetikler.',
      'Direksiyonu ani kırmak ya da gaza basmak kontrol kaybını büyütür.',
    ],
    objective: 'Lastik patlamasında direksiyonu düz tutup yumuşak yavaşlama tepkisini uygulamak.',
    tags: ['acil-durum', 'lastik-patlamasi', 'arac-hakimiyeti'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-339',
    subject: 'pratik',
    topic: 'acil-durum',
    difficulty: 'orta',
    stem: 'Araç yolda arızalanıp durduğunda güvenliği sağlamak için ne yapılır?',
    options: [
      'Araçta oturup beklemek, başka önlem almamak',
      'Dörtlü flaşörü yakıp aracı mümkünse güvenli bir kenara almak, uyarı üçgenini yeterli mesafeye koymak ve gerekiyorsa yol dışında beklemek',
      'Aracı şeritte bırakıp uzaklaşmak',
      'Yalnızca kaputu açıp beklemek',
    ],
    answerIndex: 1,
    explanation:
      'Arızada öncelik, aracı ve çevredekileri gelen trafikten korumaktır. Dörtlü flaşör yakılır, araç mümkünse emniyet şeridine veya kenara alınır ve arkadan gelenlerin zamanında görebilmesi için uyarı üçgeni yeterli mesafeye yerleştirilir. Gerekiyorsa yolcular korkuluk arkasında güvenli bir yerde bekler.',
    whyWrong: [
      'Hiçbir uyarı almadan araçta beklemek, arkadan gelen için görünmez bir engel oluşturur.',
      'Aracı şeritte bırakıp uzaklaşmak ya da yalnız kaput açmak, gelen trafiği yeterince uyarmaz.',
    ],
    objective:
      'Yolda arıza durumunda flaşör, kenar ve uyarı üçgeni ile güvenliği sağlamayı öğrenmek.',
    tags: ['acil-durum', 'ariza', 'uyari-ucgeni'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-340',
    subject: 'pratik',
    topic: 'sinav-hatalari',
    difficulty: 'orta',
    stem: 'Direksiyon sınavında motorun tekrar tekrar stop etmesi (aracın sık sık sönmesi) nasıl değerlendirilir?',
    options: [
      'Araç hâkimiyeti ve debriyaj-gaz kontrolündeki eksikliği gösteren bir hata olarak kaydedilir; sıklaşması sonucu olumsuz etkiler',
      'Hiç dikkate alınmaz',
      'Sınavı otomatik kazandırır',
      'Yalnızca motora zarar verir, değerlendirmeyle ilgisi yoktur',
    ],
    answerIndex: 0,
    explanation:
      'Motorun sık stop etmesi, adayın debriyaj-gaz uyumunu ve araç hâkimiyetini tam kuramadığını gösterir; bu, değerlendirmede bir eksiklik olarak kaydedilir. Bir kez olması küçük bir hata sayılabilirse de tekrarlanması araç hâkimiyeti puanını düşürür ve kavşak gibi yerlerde tehlike doğurursa ağırlaşır.',
    whyWrong: [
      'Motorun sık sönmesi göz ardı edilmez; araç hâkimiyeti göstergesidir.',
      'Bu durum sınav kazandırmaz ve yalnız mekanik değil, sürüş becerisi açısından değerlendirilir.',
    ],
    objective: 'Sık motor stopunun araç hâkimiyeti eksikliği olarak değerlendirildiğini kavramak.',
    tags: ['sinav-hatalari', 'motor-stop', 'arac-hakimiyeti'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-341',
    subject: 'pratik',
    topic: 'sinav-hatalari',
    difficulty: 'zor',
    stem: 'Direksiyon sınavında güvenlik gerektirmediği hâlde sürekli çok yavaş ve tereddütlü gitmek nasıl değerlendirilir?',
    options: [
      'Ne kadar yavaş gidilirse o kadar güvenli sayılır, olumludur',
      'Değerlendirmeyle hiç ilgisi yoktur',
      'Trafik akışını gereksiz aksatan ve kararlılık eksikliği gösteren bir hata olarak değerlendirilebilir',
      'Yalnızca yakıt tüketimini etkiler',
    ],
    answerIndex: 2,
    explanation:
      'Güvenli sürüş yalnızca yavaş gitmek değil, koşullara uygun ve kararlı sürmektir. Gereksiz yere aşırı yavaş ve tereddütlü ilerlemek trafik akışını aksatır, arkada sıkışma yaratır ve adayın yol/hız değerlendirmesinde kararsızlığını gösterir. Bu nedenle bu davranış da değerlendirmede eksiklik sayılabilir.',
    whyWrong: [
      'Her zaman daha yavaş gitmek daha güvenli değildir; akışı bozan yavaşlık da hatadır.',
      'Bu davranış değerlendirme dışı ya da yalnız yakıtla ilgili değildir; sürüş kararlılığını yansıtır.',
    ],
    objective: 'Koşulsuz aşırı yavaşlığın da bir sürüş eksikliği olabileceğini kavramak.',
    tags: ['sinav-hatalari', 'trafik-akisi', 'hiz-uygunlugu'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-342',
    subject: 'pratik',
    topic: 'sinav-psikolojisi',
    difficulty: 'kolay',
    stem: 'Direksiyon sınavına girmeden önce heyecanı yönetmek için en yararlı yaklaşım hangisidir?',
    options: [
      'Sınavı önemsizmiş gibi görüp hiç hazırlanmamak',
      'Son ana kadar başka adaylarla hata konuşup gerginliği artırmak',
      'Uykusuz gelip yorgunluğu görmezden gelmek',
      'Yeterince dinlenmek, birkaç derin ve yavaş nefes alarak sakinleşmek ve çalışılan adımlara güvenmek',
    ],
    answerIndex: 3,
    explanation:
      'Ölçülü bir heyecan doğaldır; ancak yönetilmezse dikkat ve koordinasyonu bozar. İyi dinlenmek, sınav öncesi birkaç derin ve yavaş nefesle bedeni sakinleştirmek ve çalışılan adımlara güvenmek, heyecanı kontrol altında tutar. Sakin bir zihin, öğrenilen becerileri daha iyi uygular.',
    whyWrong: [
      'Hiç hazırlanmamak ya da uykusuz gelmek özgüveni değil, hata olasılığını artırır.',
      'Sınav öncesi hata konuşmalarına dalmak gerginliği ve dikkat dağınıklığını büyütür.',
    ],
    objective: 'Sınav öncesi dinlenme ve nefes teknikleriyle heyecanı yönetmeyi öğrenmek.',
    tags: ['sinav-psikolojisi', 'heyecan-yonetimi', 'sinav-hazirligi'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-343',
    subject: 'pratik',
    topic: 'sinav-psikolojisi',
    difficulty: 'orta',
    stem: 'Sınav sırasında küçük bir hata yaptığını fark eden aday nasıl davranmalıdır?',
    options: [
      'Panikleyip hatayı düşünerek sürüşün geri kalanını aksatmak',
      'Sakin kalıp dikkatini yeniden yola vererek kalan sürüşü güvenle sürdürmek',
      'Sınavı kaybettiğini düşünüp gelişigüzel sürmek',
      'Görevliyle tartışıp hatanın sayılmamasını istemek',
    ],
    answerIndex: 1,
    explanation:
      'Tek bir küçük hata çoğu zaman sonucu belirlemez; asıl risk, hataya takılıp paniklemek ve dikkatin dağılmasıyla yeni ve daha ağır hatalar yapmaktır. Doğru davranış, sakin kalıp dikkati yeniden yola vermek ve kalan sürüşü güvenle, kurallara uygun tamamlamaktır.',
    whyWrong: [
      'Panikleyip hataya takılmak dikkati dağıtır ve zincirleme yeni hatalara yol açar.',
      'Sürüşü gelişigüzel yapmak ya da görevliyle tartışmak durumu yalnızca kötüleştirir.',
    ],
    objective: 'Sınavda hata sonrası paniklemeden toparlanıp sürüşü sürdürmeyi öğrenmek.',
    tags: ['sinav-psikolojisi', 'hata-sonrasi', 'odaklanma'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-344',
    subject: 'pratik',
    topic: 'sinav-psikolojisi',
    difficulty: 'kolay',
    stem: 'Sınav görevlisinin verdiği yön talimatını (örneğin bir sonraki sokaktan sağa dön) net anlamayan aday ne yapmalıdır?',
    options: [
      'Sakin biçimde talimatı tekrar sormak ve emin olduktan sonra güvenle uygulamak',
      'Tahmin yürütüp rastgele bir yöne dönmek',
      'Hiçbir şey sormadan olduğu gibi düz devam etmek',
      'Aniden ve son anda sert manevra yaparak dönmeyi denemek',
    ],
    answerIndex: 0,
    explanation:
      'Talimatı net anlamamak doğaldır ve sorun değildir; güvenlik açısından doğru olan, sakin biçimde talimatı tekrar sorup emin olduktan sonra manevrayı zamanında ve kurallara uygun yapmaktır. Tahminle ya da son anda sert manevrayla dönmek hem tehlikeli hem de hatadır.',
    whyWrong: [
      'Tahminle rastgele dönmek yanlış manevraya ve tehlikeye yol açar.',
      'Hiç sormadan devam etmek ya da son anda sert dönmek güvenliği ve değerlendirmeyi olumsuz etkiler.',
    ],
    objective: 'Anlaşılmayan talimatı tekrar sorup güvenle uygulamanın doğru olduğunu kavramak.',
    tags: ['sinav-psikolojisi', 'talimat', 'iletisim'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
];
