/**
 * ÖZGÜN direksiyon (uygulama) soruları — 5. genişletme (Program 2 · Faz 9). ROADMAP C.4/E.6.
 * Kaynak = MEB direksiyon/uygulama müfredatı; KENDİ İFADEMİZLE.
 */
import type { QuestionInput } from '@ea/content-schema';

const SRC = 'MEB direksiyon (uygulama) müfredatı (özgün ifade)';

export const PRATIK_QUESTIONS_5: QuestionInput[] = [
  {
    id: 'pratik-501',
    subject: 'pratik',
    topic: 'direksiyon-tutus-teknigi',
    difficulty: 'orta',
    stem: 'Direksiyon çevirmede öğretilen "itme-çekme" yöntemi nasıl uygulanır?',
    options: [
      'İki el direksiyonda çaprazlanarak tek hamlede sonuna kadar çevrilir',
      'Bir el direksiyonu dönüş yönünde yukarıdan aşağı çekerken diğer el aşağıdan yukarı iter; eller çaprazlanmadan, simidin üzerinde kayarak sırayla çalışır',
      'Direksiyon tek elin bileğiyle döndürülür, diğer el vites üzerinde bekler',
      'Eller simitten kaldırılıp direksiyonun kendi kendine dönmesi beklenir',
    ],
    answerIndex: 1,
    explanation:
      'İtme-çekme yönteminde bir el simidi dönüş yönüne doğru çekerken diğer el karşı taraftan iter; eller hiçbir anda çaprazlanmaz ve simit üzerindeki tutuş sürekli korunur. Böylece dönüşün her anında direksiyona tam hâkim kalınır ve gerektiğinde hareket anında durdurulabilir.',
    whyWrong: [
      'Kolları çaprazlayarak tek hamlede çevirmek, kolların kilitlendiği anda düzeltme yapmayı zorlaştırır.',
      'Tek bilekle döndürmek veya simidi serbest bırakmak, direksiyon üzerindeki kontrolü tümüyle şansa bırakır.',
    ],
    objective: 'İtme-çekme direksiyon tekniğinin çalışma mantığını uygulayabilmek.',
    tags: ['direksiyon-teknigi', 'itme-cekme', 'arac-hakimiyeti'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-502',
    subject: 'pratik',
    topic: 'direksiyon-tutus-teknigi',
    difficulty: 'zor',
    stem: 'Direksiyonu avuç içine yaslayıp tek elin ayasıyla hızla çevirmek (ayayla sıvazlama) neden sakıncalı bir alışkanlıktır?',
    options: [
      'Direksiyon simidinin yüzeyini zamanla parlattığı için',
      'Yalnızca yakıt tüketimini artırdığı için',
      'Sinyal kolunun yanlışlıkla açılmasına yol açtığı için',
      'Simit kavranmadığı için ani bir düzeltme gerektiğinde el tutamak bulamaz; çukur veya darbeyle geri tepen direksiyon avuçtan kurtulur ve hâkimiyet kaybolur',
    ],
    answerIndex: 3,
    explanation:
      'Ayayla çevirmede parmaklar simidi kavramaz; direksiyon yalnızca sürtünmeyle döndürülür. Tekerlek bir çukura girip simit geri teptiğinde ya da ani düzeltme gerektiğinde el simidi yakalayamaz ve araç kısa süreliğine yönsüz kalır. Manevralarda bile en az bir elin simidi gerçekten kavraması gerekir.',
    whyWrong: [
      'Sorun simidin parlaması ya da yakıt değil, kavramasız tutuşun ani durumda boşa çıkmasıdır.',
      'Sinyal kolu ihtimali ikincil bir ayrıntıdır; asıl risk direksiyonun elden kurtulmasıdır.',
    ],
    objective: 'Kavramasız (aya ile) direksiyon çevirmenin hâkimiyet riskini açıklayabilmek.',
    tags: ['direksiyon-teknigi', 'avuc-ici-donus', 'kontrol-kaybi'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-503',
    subject: 'pratik',
    topic: 'direksiyon-tutus-teknigi',
    difficulty: 'kolay',
    stem: 'Gövde sağa dönük hâlde geri geri düz giderken direksiyon hangi elle ve nereden tutulur?',
    options: [
      'Sol el, direksiyonun üst orta noktasını kavrar; böylece küçük el hareketleri aracın yönüne kolayca çevrilebilir',
      'İki el simidin en altında birleştirilir',
      'Sağ el direksiyonun altından, sol el vitesten tutar',
      'Direksiyon dizle desteklenir, eller serbest kalır',
    ],
    answerIndex: 0,
    explanation:
      'Geri düz giderken gövde sağa döndüğü için sağ el genellikle yolcu koltuğuna destek olur; direksiyonu sol el üst orta noktadan kavrar. Üst noktadan tutuş, elin hangi yöne kayarsa aracın arkasının da o yöne gideceğini hissettirir ve küçük düzeltmeleri kolaylaştırır.',
    whyWrong: [
      'Simidin altından ya da iki elle alttan tutmak, dönüş yönünü ters algılatır ve düzeltmeleri karıştırır.',
      'Direksiyonu dizle desteklemek hiçbir manevrada kabul edilebilir bir tutuş değildir.',
    ],
    objective: 'Geri düz seyirde tek elle üst noktadan direksiyon tutuşunu uygulayabilmek.',
    tags: ['direksiyon-teknigi', 'geri-manevra', 'tutus'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-504',
    subject: 'pratik',
    topic: 'bakis-teknigi-viraj',
    difficulty: 'kolay',
    stem: 'Viraja girerken bakışlar nereye yönlendirilmelidir?',
    options: [
      'Aracın hemen önündeki asfalta',
      'Hız göstergesine',
      'Virajın çıkışına, yani gidilmek istenen noktaya; araç bakışın yöneldiği hattı izler',
      'Karşı şeritteki araçların tekerleklerine',
    ],
    answerIndex: 2,
    explanation:
      'Direksiyon elin değil, gözün gittiği yere kırılır: sürücü viraj boyunca çıkış noktasına baktığında eller dönüş açısını kendiliğinden ve akıcı biçimde ayarlar. Burnunun önüne bakan sürücü virajı parça parça, ani düzeltmelerle döner ve şeridinden taşar.',
    whyWrong: [
      'Aracın hemen önüne bakmak dönüş hattını görmeyi engeller; düzeltmeler hep gecikir.',
      'Gösterge ya da karşı araçların tekerleklerine kilitlenmek, aracı bakılan yöne sürükleme eğilimi doğurur.',
    ],
    objective: 'Virajda bakışı çıkış noktasına taşıyarak akıcı dönüş yapabilmek.',
    tags: ['bakis-teknigi', 'viraj', 'cikisa-bakma'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-505',
    subject: 'pratik',
    topic: 'bakis-teknigi-viraj',
    difficulty: 'orta',
    stem: 'Yolda bir engel (çukur, duran araç) fark eden sürücünün gözlerini engele kilitlemesi neden tehlikelidir?',
    options: [
      'Bakış hedefe kilitlenince eller de aracı istemsizce o hedefe yöneltir; kaçınmak için engele değil, geçilecek boş alana bakılmalıdır',
      'Engele bakmak göz yorgunluğu yaptığı için',
      'Engel uzaktan olduğundan küçük görünüp yanılttığı için',
      'Bakış sabitlenince silecekler otomatik çalıştığı için',
    ],
    answerIndex: 0,
    explanation:
      'Buna hedef kilitlenmesi denir: sürücü neye bakarsa aracı oraya sürme eğilimindedir. Engele kilitlenen bakış, kaçınma manevrasını tam da engelin üzerine yöneltir. Doğru teknik, engeli çevresel görüşte tutup bakışı geçilecek boşluğa taşımaktır; direksiyon bakışı izler.',
    whyWrong: [
      'Göz yorgunluğu ya da boyut yanılgısı buradaki asıl sorun değildir.',
      'Sileceklerle bakış arasında hiçbir bağlantı yoktur; seçenek konuyla ilgisizdir.',
    ],
    objective: 'Hedef kilitlenmesini tanıyıp bakışı kaçış boşluğuna yönlendirmeyi öğrenmek.',
    tags: ['bakis-teknigi', 'hedef-kilitlenmesi', 'kacinma'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-506',
    subject: 'pratik',
    topic: 'bakis-teknigi-viraj',
    difficulty: 'orta',
    stem: 'Şehir içi sürüşte bakışın taranması gereken uzaklık için doğru yaklaşım hangisidir?',
    options: [
      'Yalnızca öndeki aracın tamponuna bakmak yeterlidir',
      'Bakış hep en uzak noktada sabit tutulur, yakın çevre hiç taranmaz',
      'Gözler kapalı devre yalnızca aynalarda gezdirilir',
      'Bakış, aracın yaklaşık on-on beş saniye sonra varacağı uzaklığa taşınır ve yakın ile uzak arasında sürekli gidip gelerek tarama yapılır',
    ],
    answerIndex: 3,
    explanation:
      'Trafiği erken okumak için bakış, aracın on-on beş saniye sonra ulaşacağı bölgeye kadar taşınır; ışıklar, yayalar ve duraklamalar orada, henüz vakit varken görülür. Gözler bu uzak bölge ile yakın çevre ve aynalar arasında ritimle gezdirilir; hiçbir noktaya uzun süre takılı kalınmaz.',
    whyWrong: [
      'Öndeki tampona kilitlenen sürücü, trafiği değil yalnızca öndeki aracın fren lambasını sürer.',
      'Sadece uzağa ya da sadece aynalara bakmak, görüş alanının diğer yarısını karanlıkta bırakır.',
    ],
    objective: 'Şehir içinde ileri tarama mesafesini ve yakın-uzak bakış ritmini kurabilmek.',
    tags: ['bakis-teknigi', 'ileri-tarama', 'sehir-ici'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-507',
    subject: 'pratik',
    topic: 'takip-mesafesi-sayma',
    difficulty: 'kolay',
    stem: 'Takip mesafesi için gereken iki saniye, saat kullanmadan pratik olarak nasıl sayılır?',
    options: [
      'Motorun devir sesindeki değişiklik dinlenerek',
      'Öndeki araç sabit bir noktayı geçince normal tempoda "seksen sekiz, seksen dokuz" denir; sayı bitmeden o noktaya varılıyorsa mesafe kısadır',
      'Kilometre saatine bakıp hız ikiye bölünerek',
      'Öndeki aracın plakası okunabiliyorsa mesafe yeterli sayılır',
    ],
    answerIndex: 1,
    explanation:
      'Normal konuşma temposunda söylenen "seksen sekiz, seksen dokuz" sözcüklerinin her biri yaklaşık bir saniye sürer. Öndeki araç bir direği ya da gölgeyi geçtiği anda saymaya başlanır; sayım bitmeden aynı noktaya varılıyorsa iki saniyelik pay yok demektir ve mesafe açılır.',
    whyWrong: [
      'Motor sesi ya da hızı ikiye bölmek saniye ölçmez; bunlar mesafeyle ilgili güvenilir bilgi vermez.',
      'Plakanın okunması çok kısa mesafede bile mümkündür; güvenli payın ölçüsü olamaz.',
    ],
    objective: 'İki saniye kuralını sözcük sayma tekniğiyle ölçebilmek.',
    tags: ['takip-mesafesi', 'sayma-teknigi', 'iki-saniye'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-508',
    subject: 'pratik',
    topic: 'takip-mesafesi-sayma',
    difficulty: 'orta',
    stem: 'Kuru yolda iki saniye olan takip payı, ıslak ve kaygan zeminde nasıl değişmelidir?',
    options: [
      'Islak zeminde de iki saniye aynen yeterlidir',
      'Islakta bir saniyeye indirilebilir, çünkü herkes yavaşlar',
      'Süre en az iki katına (yaklaşık dört saniyeye) çıkarılır; kar ve buzda daha da artırılır',
      'Takip payı süreyle değil, korna sesiyle ayarlanır',
    ],
    answerIndex: 2,
    explanation:
      'Islak zeminde lastiğin tutunması azalır ve durma mesafesi belirgin uzar; iki saniyelik pay bu uzamayı karşılamaz. Bu yüzden süre en az dört saniyeye çıkarılır; kar ve buzda çok daha büyük pay bırakılır. Zemin kötüleştikçe mesafe kuralı da büyür.',
    whyWrong: [
      'İki saniyeyi ıslakta korumak, uzayan fren mesafesini hesaba katmamaktır.',
      'Payı kısaltmak ya da kornayla ölçmeye çalışmak, fizik gerçeğini tersine çevirmeye çalışmaktır.',
    ],
    objective: 'Takip süresini zemin koşuluna göre ölçekleyebilmek.',
    tags: ['takip-mesafesi', 'islak-zemin', 'dort-saniye'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-509',
    subject: 'pratik',
    topic: 'yokus-inis-vites',
    difficulty: 'orta',
    stem: 'Uzun bir inişte hangi vitesin kullanılacağına karar vermek için öğretilen pratik kural nedir?',
    options: [
      'Aynı yokuşu çıkarken hangi vites gerekiyorsa, inerken de yaklaşık o vites seçilir; motor freni ancak böyle yeterli direnç üretir',
      'İnişte daima en yüksek vites kullanılır',
      'İnişte vites seçimi önemsizdir, fren her şeyi çözer',
      'İnişe her zaman birinci vitesle başlanır',
    ],
    answerIndex: 0,
    explanation:
      'Eğim ne kadar dikse motor freninin de o kadar güçlü olması gerekir. Pratik ölçü şudur: bu yokuş tırmanılıyor olsaydı hangi vites gerekecekse, inişte de o civarda bir vites seçilir. Böylece hız, frene yaslanmadan motor direnciyle dengede tutulur.',
    whyWrong: [
      'Yüksek vites neredeyse hiç motor freni üretmez; bütün yük ayak frenine biner.',
      'Her inişe birinci vitesle başlamak ise motoru gereksiz yere aşırı devre zorlar; ölçü eğimin dikliğidir.',
    ],
    objective: 'İniş vitesini "çıkışta gereken vites" kuralıyla seçebilmek.',
    tags: ['yokus-inis', 'vites-secimi', 'motor-freni'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-510',
    subject: 'pratik',
    topic: 'yokus-inis-vites',
    difficulty: 'kolay',
    stem: 'Yokuş aşağı vitesi boşa alarak ya da debriyaja basılı tutarak inmek neden tehlikelidir?',
    options: [
      'Motor daha çok yakıt harcadığı için',
      'Vites göstergesi bozulacağı için',
      'Araç daha yavaş ineceği için',
      'Motor freni tamamen devreden çıkar; araç serbest kütle gibi hızlanır ve hız kontrolü tek başına ısınacak olan frene kalır',
    ],
    answerIndex: 3,
    explanation:
      'Boş viteste ya da debriyaj basılıyken motorla tekerlek arasındaki bağ kopar; motor freni sıfırlanır. Araç eğimle serbestçe hızlanır, tüm yavaşlatma işi ayak frenine yüklenir ve uzun inişte fren ısınıp zayıflayabilir. İniş boyunca vites takılı, debriyaj serbest kalmalıdır.',
    whyWrong: [
      'Boşta inmek yakıt kazandırmaz; modern araçlarda vites takılıyken gazsız iniş daha az yakar.',
      'Araç yavaşlamaz, tam tersine bağ koptuğu için giderek hızlanır.',
    ],
    objective: 'Boş vites/debriyajla inişin motor frenini yok ettiğini kavramak.',
    tags: ['yokus-inis', 'bos-vites', 'motor-freni'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-511',
    subject: 'pratik',
    topic: 'fren-fading',
    difficulty: 'zor',
    stem: 'Uzun bir inişte fren pedalı derinleşmeye başlamış, araçtan yanık benzeri bir koku geliyorsa bu neyin işaretidir ve ne yapılmalıdır?',
    options: [
      'Lastik havası düşmüştür; hızlanıp inişi kısa sürede bitirmek gerekir',
      'Frenler aşırı ısınıp zayıflamaya (fading) başlamıştır; vites düşürülüp motor frenine geçilir ve ilk güvenli yerde durup frenlerin soğuması beklenir',
      'Klima gazı eksilmiştir; camlar açılır',
      'Bu durum normaldir, pedala daha sert basarak devam edilir',
    ],
    answerIndex: 1,
    explanation:
      'Sürekli frenlemeyle balata ve diskler aşırı ısınınca sürtünme kuvveti düşer; pedal derinleşir, koku yayılır ve fren giderek tutmaz olur. Buna fading denir. İlk yapılacak iş vites düşürüp hız kontrolünü motor frenine devretmek, ardından güvenli bir yerde durup frenleri soğutmaktır; ısınmış frenle inişe devam edilmez.',
    whyWrong: [
      'Belirtiler lastik ya da klimayla ilgili değildir; hızlanmak riski büyütür.',
      'Pedala daha sert yüklenmek ısıyı daha da artırır ve freni tamamen bitirebilir.',
    ],
    objective: 'Fren zayıflamasının (fading) belirtilerini tanıyıp doğru müdahaleyi yapabilmek.',
    tags: ['fading', 'fren-isinmasi', 'uzun-inis'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-512',
    subject: 'pratik',
    topic: 'fren-fading',
    difficulty: 'orta',
    stem: 'Uzun rampalarda fren zayıflamasını (fading) daha oluşmadan önlemenin temel yolu nedir?',
    options: [
      'Hızı düşük vitesle motor frenine yaptırıp ayak frenini yalnızca kısa ve aralıklı düzeltmeler için kullanmak',
      'Fren pedalına iniş boyunca hafifçe sürekli basılı gitmek',
      'El frenini hafif çekili tutarak inmek',
      'İnişten önce fren hidroliğini boşaltmak',
    ],
    answerIndex: 0,
    explanation:
      'Fading, frenin uzun süre kesintisiz sürtünmesinden doğan ısıyla oluşur. Önlemenin yolu, ana yavaşlatma işini düşük vitesteki motor frenine devretmek ve ayak frenini yalnızca kısa dokunuşlarla kullanmaktır; aradaki serbest anlar balata ve diskin soğumasına izin verir.',
    whyWrong: [
      'Sürekli hafif basılı pedal, freni aralıksız sürttüğü için ısıyı en hızlı biriktiren kullanımdır.',
      'El frenini çekili tutmak arka frenleri ısıtır; hidrolik boşaltmak ise freni tümüyle devre dışı bırakır.',
    ],
    objective: 'Fading oluşmadan motor freni ve aralıklı fren kullanımıyla önlem alabilmek.',
    tags: ['fading', 'motor-freni', 'onleme'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-513',
    subject: 'pratik',
    topic: 'kademeli-fren',
    difficulty: 'orta',
    stem: 'Uzun inişte "kademeli fren" (bas-bırak) tekniği nasıl uygulanır ve sürekli hafif sürtmeye göre üstünlüğü nedir?',
    options: [
      'Pedala tek seferde sonuna kadar basılır ve öyle tutulur',
      'Fren yerine yalnızca korna kullanılır',
      'Hız arttığında pedala belirgin biçimde basılıp hız istenen düzeye inince pedal tamamen bırakılır; serbest aralıklarda frenler soğur, sürekli sürtmede ise ısı kesintisiz birikir',
      'Fren yalnızca viraj ortalarında kullanılır',
    ],
    answerIndex: 2,
    explanation:
      'Kademeli frende hız belli bir eşiğe çıkınca pedala kararlı basılır, hız düşünce pedal tümüyle serbest bırakılır ve bu döngü tekrarlanır. Pedalın boşta kaldığı aralıklar disk ve balatanın soğumasını sağlar; iniş boyunca hafifçe sürtmeye devam eden frende ise soğuma anı hiç olmaz ve ısı zayıflamaya götürür.',
    whyWrong: [
      'Pedalı sonuna kadar basılı tutmak hem yolcuları sarsar hem freni kesintisiz ısıtır.',
      'Korna hız kesmez; viraj ortası ise frenin en istenmediği yerdir.',
    ],
    objective: 'Bas-bırak fren döngüsünün soğuma mantığını uygulayabilmek.',
    tags: ['kademeli-fren', 'fren-teknigi', 'uzun-inis'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-514',
    subject: 'pratik',
    topic: 'kademeli-fren',
    difficulty: 'kolay',
    stem: 'Duracağınız yeri önceden görüp frene erken ve hafif başlamanın arkadaki sürücü açısından yararı nedir?',
    options: [
      'Arkadaki sürücü sizi daha kolay sollayabilir',
      'Fren lambası erken yanarak arkadakine yavaşlayacağınızı önceden bildirir; arkadaki de kademeli yavaşlar ve zincirleme çarpma riski azalır',
      'Arkadaki aracın yakıt tüketimi düşer',
      'Hiçbir yararı yoktur; fren yalnızca sürücünün kendisini ilgilendirir',
    ],
    answerIndex: 1,
    explanation:
      'Erken başlayan hafif fren, lambayı erken yakarak arkadaki sürücüye zaman kazandırır; herkes kademeli yavaşlar. Son anda yapılan sert fren ise arkadakini hazırlıksız yakalar ve arkadan çarpmaların başlıca nedenidir. Fren, aynı zamanda arkaya verilen bir mesajdır.',
    whyWrong: [
      'Amaç sollanmak ya da yakıt değil, arkadaki trafiğe erken haber vermektir.',
      'Freni yalnız kendi işi saymak, arkadan çarpılma riskini görmezden gelmektir.',
    ],
    objective: 'Erken ve hafif frenin arkaya uyarı işlevini kavramak.',
    tags: ['kademeli-fren', 'fren-lambasi', 'arkadan-carpma'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-515',
    subject: 'pratik',
    topic: 'aquaplaning',
    difficulty: 'orta',
    stem: 'Islak yolda araç su yastığına (aquaplaning) binip yüzmeye başladığı anda sürücü ne yapmalıdır?',
    options: [
      'Sert fren yapıp direksiyonu hızla sağa kırmak',
      'Gaza basarak su tabakasını yarmaya çalışmak',
      'El frenini çekmek',
      'Gazdan yumuşakça çekilmek, direksiyonu düz ve sabit tutmak, ani fren ve ani direksiyondan kaçınıp lastiklerin yolu yeniden tutmasını beklemek',
    ],
    answerIndex: 3,
    explanation:
      'Su yastığında lastikler yolla temasını yitirmiştir; fren ve direksiyon o anda işlemez. Doğru davranış gazı yumuşakça bırakıp hızın kendiliğinden düşmesini sağlamak ve direksiyonu düz tutmaktır. Temas geri geldiğinde tekerlekler düz olduğu için araç savrulmadan yoluna devam eder.',
    whyWrong: [
      'Yüzen tekerleğe sert fren ya da ani direksiyon, temas geri geldiği anda aracı savurur.',
      'Gaza basmak ya da el freni çekmek, temassız tekerlekleri büsbütün kontrolsüzleştirir.',
    ],
    objective: 'Su yastığı anında gaz kesme ve sabit direksiyon davranışını uygulayabilmek.',
    tags: ['aquaplaning', 'su-yastigi', 'islak-zemin'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-516',
    subject: 'pratik',
    topic: 'aquaplaning',
    difficulty: 'orta',
    stem: 'Sağanak altında seyrederken direksiyonun aniden hafifleyip boşalmış gibi hissedilmesi neyin belirtisidir?',
    options: [
      'Lastiklerin su tabakası üzerine binip yolla temasını kaybetmeye başladığının; hız kesilmez ve düzeltme yapılmazsa araç tümüyle yüzmeye geçer',
      'Direksiyon pompasının arızalandığının',
      'Yolun yeni asfaltlandığının',
      'Rüzgârın tamamen durduğunun',
    ],
    answerIndex: 0,
    explanation:
      'Direksiyondaki his, ön lastiklerin yolla temasından gelir. Su birikmiş şeritte direksiyonun aniden hafiflemesi, lastiğin suyu atamayıp tabakanın üzerine binmeye başladığını gösterir. Bu ilk uyarıda gazdan çekilip hız düşürülmezse araç tam su yastığına geçer.',
    whyWrong: [
      'Pompa arızası genellikle direksiyonu ağırlaştırır, hafifletmez; belirti tam tersidir.',
      'Asfaltın yaşı ya da rüzgâr, sağanakta gelen bu ani hafifleme hissini açıklamaz.',
    ],
    objective: 'Su yastığının ilk belirtisini direksiyon hissinden tanıyabilmek.',
    tags: ['aquaplaning', 'belirti', 'direksiyon-hissi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-517',
    subject: 'pratik',
    topic: 'patinaj-kalkis',
    difficulty: 'kolay',
    stem: 'Kaygan zeminde kalkış sırasında çekiş tekerlekleri patinaja başladığında gaz pedalı için doğru tepki nedir?',
    options: [
      'Gaza sonuna kadar basıp tekerleği zorla tutundurmak',
      'Debriyajı aniden bırakmak',
      'Gaz hafifçe azaltılır; tekerleğe giden güç düşünce lastik zemini yeniden yakalar ve araç yürümeye başlar',
      'Direksiyonu iki yana hızla sallamak',
    ],
    answerIndex: 2,
    explanation:
      'Patinaj, tekerleğe zeminin taşıyabileceğinden fazla güç gitmesidir. Çözüm gücü artırmak değil azaltmaktır: gaz hafifçe kesildiğinde dönüş yavaşlar, lastik zemini yakalar ve araç ilerler. Kaygan kalkışın anahtarı az gaz ve sabırlı debriyajdır.',
    whyWrong: [
      'Daha çok gaz tekerleği yalnızca daha hızlı boşa döndürür, zemini de cilalar.',
      'Debriyajı fırlatmak ya da direksiyon sallamak, zaten zayıf olan tutunmayı büsbütün bozar.',
    ],
    objective: 'Patinajda gücü azaltarak tutunmayı geri kazanmayı öğrenmek.',
    tags: ['patinaj', 'kalkis', 'gaz-kontrolu'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-518',
    subject: 'pratik',
    topic: 'patinaj-kalkis',
    difficulty: 'orta',
    stem: 'Karlı-buzlu düz zeminde bazı sürücülerin kalkışı birinci yerine ikinci vitesle yapmasının nedeni nedir?',
    options: [
      'İkinci vites debriyajı hiç aşındırmadığı için',
      'İkinci viteste tekerleğe daha az ve daha yumuşak tork gittiği için patinaj eğilimi azalır; kalkış debriyajı biraz daha uzun kavratılarak yapılır',
      'İkinci vites motoru daha çabuk ısıttığı için',
      'Birinci vites karda tamamen devre dışı kaldığı için',
    ],
    answerIndex: 1,
    explanation:
      'Birinci vitesin güçlü tork iletimi kaygan zeminde tekerleği kolayca boşa döndürür. İkinci vites aynı gaz açıklığında tekerleğe daha yumuşak güç ilettiği için lastik kopma noktasına daha zor ulaşır. Debriyajın biraz daha uzun ve sabırlı kavratılmasıyla araç patinajsız yürütülür.',
    whyWrong: [
      'Debriyaj ikinci viteste de aşınır; kalkış biraz daha uzun kavramayla yapıldığı için özen ister.',
      'Motor ısısı ya da birinci vitesin devre dışı kalması diye bir durum söz konusu değildir.',
    ],
    objective: 'Karda ikinci vitesle kalkışın tork mantığını açıklayabilmek.',
    tags: ['patinaj', 'kar', 'ikinci-vites-kalkis'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-519',
    subject: 'pratik',
    topic: 'savrulma-karsi-manevra',
    difficulty: 'zor',
    stem: 'Kaygan yolda aracın arkası sola doğru kaymaya (savrulmaya) başladığında direksiyon hangi yöne çevrilmelidir?',
    options: [
      'Arkanın kaydığı yöne, yani sola doğru yumuşakça çevrilir; ön tekerlekler gidiş hattıyla yeniden hizalanınca düzeltme geri alınır',
      'Kaymanın tersine, sonuna kadar sağa kırılır',
      'Direksiyon hiç oynatılmaz, sıkıca düz tutulur',
      'Direksiyon bırakılıp iki elle el frenine sarılır',
    ],
    answerIndex: 0,
    explanation:
      'Arka sola kayarken aracın burnu sağa döner; sürücü direksiyonu kayma yönüne (sola) yumuşakça çevirirse ön tekerlekler gitmek istenen hatla yeniden hizalanır ve araç toparlanır. Düzeltme abartılmadan yapılır ve araç toparlanırken kademeli geri alınır; aksi hâlde savrulma bu kez öbür yöne sıçrar.',
    whyWrong: [
      'Ters yöne sert kırmak savrulmayı büyütür ve aracı karşı yöne fırlatır.',
      'Direksiyonu donuk tutmak ya da el frenine sarılmak, dönmeye başlamış aracı tümüyle kontrolsüz bırakır.',
    ],
    objective: 'Savrulma başlangıcında kayma yönüne yumuşak düzeltme yapabilmek.',
    tags: ['savrulma', 'karsi-manevra', 'kaygan-zemin'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-520',
    subject: 'pratik',
    topic: 'savrulma-karsi-manevra',
    difficulty: 'orta',
    stem: 'Savrulma başlangıcında gaz ve fren pedalları nasıl kullanılmalıdır?',
    options: [
      'Frene sonuna kadar basılır',
      'Gaza köklenerek araç savrulmadan çekip çıkarılır',
      'Ani fren yapılmaz; gaz yumuşakça azaltılır ve bakış gidilmek istenen yöne taşınarak direksiyon düzeltmesiyle birlikte aracın toparlanması beklenir',
      'Debriyaja basıp gözler kapatılır',
    ],
    answerIndex: 2,
    explanation:
      'Savrulan araçta lastiklerin sınırlı tutunması yön düzeltmesine ayrılmalıdır; ani fren ya da ani gaz bu tutunmayı çalar ve savrulmayı derinleştirir. Doğrusu gazı yumuşakça azaltmak, sert pedal girdilerinden kaçınmak ve bakışı gidilmek istenen noktada tutarak direksiyon düzeltmesini desteklemektir.',
    whyWrong: [
      'Tam fren, kayan tekerlekleri kilitleyip aracı büsbütün döndürür.',
      'Gaza köklemek arka tekerleklerin son tutunma payını da koparır.',
    ],
    objective: 'Savrulmada pedal girdilerini yumuşatma ilkesini uygulayabilmek.',
    tags: ['savrulma', 'gaz-kontrolu', 'panik-onleme'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-521',
    subject: 'pratik',
    topic: 'abs-anlama',
    difficulty: 'zor',
    stem: 'ABS fren sisteminin sürücüye sağladığı asıl kazanım hangisidir?',
    options: [
      'Her zeminde durma mesafesini yarıya indirmesi',
      'Fren balatalarının hiç aşınmamasını sağlaması',
      'Frene basılıyken bile korna sesini güçlendirmesi',
      'Tekerlek kilitlenmesini önleyerek tam frende bile direksiyonla yön verebilmeyi koruması; durma mesafesi ise gevşek kar ve çakıl gibi zeminlerde kısalmayabilir, hatta uzayabilir',
    ],
    answerIndex: 3,
    explanation:
      'ABS öncelikle bir yön koruma sistemidir: tekerleklerin kilitlenmesini önlediği için tam frende bile araç direksiyona yanıt verir ve engelden kaçınılabilir. Durma mesafesi çoğu sert zeminde kısalsa da gevşek kar ve çakılda tekerleğin önünde birikinti oluşamadığından uzayabilir; ABS hız ve mesafe kuralının yerini tutmaz.',
    whyWrong: [
      'ABS mesafeyi her koşulda kısaltan sihirli bir sistem değildir; asıl işlevi yönlendirilebilirliktir.',
      'Balata aşınması ya da korna, sistemin çalışma alanıyla ilgisizdir.',
    ],
    objective: 'ABS kazanımını doğru sınırlarıyla (yön hâkimiyeti) tanımlayabilmek.',
    tags: ['abs', 'yon-hakimiyeti', 'fren-mesafesi'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-522',
    subject: 'pratik',
    topic: 'yagmur-kaygan-yuzeyler',
    difficulty: 'kolay',
    stem: 'Uzun süren kuraklıktan sonra başlayan yağmurun ilk dakikalarında yol neden en kaygan hâlindedir?',
    options: [
      'İlk damlalar asfaltı soğutup büzdüğü için',
      'Yol yüzeyinde birikmiş toz, lastik kalıntısı ve yağ ilk suyla kaygan bir film oluşturur; bu tabaka ancak bir süre yağıştan sonra yıkanıp akar',
      'Silecekler ilk dakikalarda çalışmadığı için',
      'İlk dakikalarda lastik basıncı düştüğü için',
    ],
    answerIndex: 1,
    explanation:
      'Kuru günlerde asfaltta toz, egzoz kalıntısı, lastik tozu ve yağ birikir. Yağmurun ilk damlaları bu birikintiyi çözerek yüzeye ince, sabunumsu bir film serer; yol en kaygan bu evrede olur. Sağanak sürüp yüzeyi yıkadıkça tutunma kısmen geri gelir. Bu yüzden yağışın ilk dakikalarında hız ve takip payı hemen ayarlanmalıdır.',
    whyWrong: [
      'Asfaltın soğuması ya da lastik basıncı bu ani kayganlığı yaratan etken değildir.',
      'Sileceklerin çalışması cam içindir; yolun tutunmasıyla ilgisi yoktur.',
    ],
    objective: 'Yağışın ilk dakikalarındaki film tabakası riskini tanımak.',
    tags: ['yagmur', 'ilk-dakikalar', 'kayganlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-523',
    subject: 'pratik',
    topic: 'yagmur-kaygan-yuzeyler',
    difficulty: 'orta',
    stem: 'Islak havada şehir içinde özellikle hangi yüzeylerin üzerinde frenlemekten ve ani manevradan kaçınılmalıdır?',
    options: [
      'Metal mazgal ve rögar kapakları, boyalı yol çizgileri ve yaya geçidi boyaları, ıslak yapraklar ile ray geçişleri; bunlar ıslakken asfalttan çok daha kaygandır',
      'Yeni dökülmüş kumlu asfalt dışında her yüzey aynıdır',
      'Yalnızca köprü altları',
      'Beton zeminler; asfalt ıslakken hiç kaymaz',
    ],
    answerIndex: 0,
    explanation:
      'Metal kapaklar, yol boyaları, ezilmiş ıslak yapraklar ve raylar suyla birleşince buz kadar kayganlaşabilir. Bu yüzeyler görüldüğünde fren ve dönüş girişleri mümkünse öncesinde tamamlanır; üzerlerinden düz direksiyonla, sabit hızla geçilir. Şehir içi kaymaların çoğu bu küçük yüzeylerde başlar.',
    whyWrong: [
      'Islak asfalt da kayar; ama sayılan yüzeyler ondan belirgin biçimde daha risklidir.',
      'Riski köprü altı ya da betonla sınırlamak, en sık karşılaşılan mazgal ve boya tuzağını gözden kaçırır.',
    ],
    objective: 'Islakta yerel kaygan yüzeyleri tanıyıp üzerinde manevradan kaçınmak.',
    tags: ['islak-zemin', 'mazgal', 'yol-cizgisi'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-524',
    subject: 'pratik',
    topic: 'gece-kamasma-ayna',
    difficulty: 'kolay',
    stem: 'Gece arkadan gelen aracın uzun farları iç dikiz aynasından gözünüzü kamaştırıyorsa ne yapılmalıdır?',
    options: [
      'Aynayı tavana doğru çevirip hiç kullanmamak',
      'Arkadaki araca fren yaparak gözdağı vermek',
      'İç aynanın gece (kamaşma önleyici) konumuna alınması; ayna altındaki mandalla veya otomatik kararan aynayla yansıma söndürülür, arkadaki araç görünmeye devam eder',
      'Gözleri kısıp aynaya bakmamaya çalışmak',
    ],
    answerIndex: 2,
    explanation:
      'İç dikiz aynalarının altındaki küçük mandal, aynayı gece konumuna alır; yansıyan far ışığı sönükleşir ama arkadaki aracın konumu izlenebilir kalır. Otomatik kararan aynalar bunu kendiliğinden yapar. Aynayı devre dışı bırakmak yerine kamaşmayı söndürmek doğru çözümdür.',
    whyWrong: [
      'Aynayı tavana çevirmek arka görüşü tümüyle kapatır; kamaşmadan da tehlikelidir.',
      'Fren yaparak ceza kesmeye kalkmak, kamaşan gözlerle yapılabilecek en riskli harekettir.',
    ],
    objective: 'İç aynanın gece konumunu kamaşmaya karşı kullanabilmek.',
    tags: ['gece-surus', 'ayna-gece-konumu', 'kamasma'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-525',
    subject: 'pratik',
    topic: 'kapali-otopark',
    difficulty: 'kolay',
    stem: 'Güneşli bir günden kapalı otoparkın iniş rampasına girerken doğru hazırlık hangisidir?',
    options: [
      'Rampaya normal seyir hızıyla girip içeride yavaşlamak',
      'Uzun farları yakıp kornaya basmak',
      'Güneş gözlüğünü takılı bırakıp hızlanmak',
      'Kısa farları yakmak, güneş gözlüğünü çıkarmak ve rampaya adım hızında girmek; gözler loşluğa birkaç saniyede alışana kadar görüş zayıftır',
    ],
    answerIndex: 3,
    explanation:
      'Parlak dış ortamdan loş rampaya geçişte gözlerin uyumu birkaç saniye alır ve bu sürede rampadaki yaya ya da araç görülmeyebilir. Girişten önce kısa farlar yakılır, güneş gözlüğü çıkarılır ve rampaya sürünme hızında girilir; varsa köşe aynaları kontrol edilir.',
    whyWrong: [
      'Normal hızla girmek, gözün kör olduğu ilk saniyeleri en dar ve dik alanda geçirmek demektir.',
      'Uzun far kapalı alanda yansıyıp kamaştırır; gözlüğü takılı bırakmak loşluğu koyulaştırır.',
    ],
    objective: 'Otopark rampasına ışık ve hız hazırlığıyla girmeyi öğrenmek.',
    tags: ['kapali-otopark', 'rampa', 'goz-uyumu'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-526',
    subject: 'pratik',
    topic: 'kapali-otopark',
    difficulty: 'orta',
    stem: 'Kapalı otoparkın içinde ilerlerken hız ve gözlem nasıl olmalıdır?',
    options: [
      'Yürüyüş hızında sürülür; kolon araları ve araç aralarından çıkabilecek yayalar ile geri çıkmakta olan araçların geri vites lambaları sürekli taranır',
      'Otoparkta trafik kuralı geçerli olmadığı için serbest hızla gidilir',
      'Yalnızca boş park yeri aranır, çevre gözlenmez',
      'Dörtlü flaşör yakılıp hızlıca tur atılır',
    ],
    answerIndex: 0,
    explanation:
      'Otopark, yayalarla araçların iç içe olduğu ve görüşün kolonlarla bölündüğü dar bir alandır. Hız yürüyüş temposuna indirilir; araçların arasından çıkabilecek yayalar ve cebinden geri çıkmaya hazırlanan araçların beyaz geri vites lambaları özellikle izlenir. Boş yer arayışı gözlemin önüne geçmemelidir.',
    whyWrong: [
      'Otopark kuralsız bölge değildir; düşük hız ve yol verme ilkeleri burada da geçerlidir.',
      'Bakışı yalnızca boş cebe kilitleyen sürücü, önünden çıkan yayayı en son fark eden kişidir.',
    ],
    objective: 'Otopark içinde yürüyüş hızı ve geri lambası taramasını alışkanlık edinmek.',
    tags: ['kapali-otopark', 'yaya', 'geri-vites-lambasi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-527',
    subject: 'pratik',
    topic: 'yuklu-arac-fren-mesafesi',
    difficulty: 'orta',
    stem: 'Bagajı ve koltukları tam dolu bir araçla seyrederken fren davranışı neden değişir ve sürücü ne yapmalıdır?',
    options: [
      'Yüklü araç daha çabuk durur; mesafe kısaltılabilir',
      'Artan kütle nedeniyle durma mesafesi uzar ve araç frende daha geç yanıt verir; takip mesafesi artırılmalı, frene daha erken başlanmalıdır',
      'Yük yalnızca yakıtı etkiler, freni etkilemez',
      'Yüklüyken fren hiç kullanılmaz, yalnız motor freniyle gidilir',
    ],
    answerIndex: 1,
    explanation:
      'Fren, aracın hareket enerjisini ısıya çevirir; kütle arttıkça sönümlenecek enerji de artar ve aynı pedal kuvvetiyle araç daha uzun mesafede durur. Yüklü araçta takip payı büyütülür, frenlemeye boş araca göre daha erken başlanır ve inişlerde motor freni daha önemli hâle gelir.',
    whyWrong: [
      'Yüklü aracın daha çabuk durduğu inanışı fiziğe aykırıdır; tam tersi geçerlidir.',
      'Yükün etkisini yakıtla sınırlamak, uzayan fren mesafesini hesaba katmamaktır.',
    ],
    objective: 'Yükün durma mesafesine etkisini sürüş planına yansıtabilmek.',
    tags: ['yuklu-arac', 'fren-mesafesi', 'takip-mesafesi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-528',
    subject: 'pratik',
    topic: 'kis-zincir-buzlanma',
    difficulty: 'kolay',
    stem: 'Tekerleklere kar zinciri takılıyken sürüş hızı için doğru davranış nedir?',
    options: [
      'Zincir taktıktan sonra normal seyir hızına dönülür',
      'Zincirliyken en az 90 km/s ile gidilir',
      'Hız belirgin biçimde düşük tutulur, zincir üreticisinin sınırı (genellikle 50 km/s dolayı) aşılmaz; ani kalkış ve sert frenden kaçınılır, karsız asfalta çıkınca zincir sökülür',
      'Zincirliyken hız yalnızca inişlerde önemlidir',
    ],
    answerIndex: 2,
    explanation:
      'Zincir, karda tutunma içindir; yüksek hızda hem kopup araca ve çevreye zarar verir hem sürüşü sarsıntılı yapar. Hız düşük tutulur ve üreticinin belirttiği sınır (çoğunlukla 50 km/s civarı) aşılmaz. Zincirle kuru asfaltta sürmek de hem zinciri hem yolu ve lastiği yıpratır; kar bitince sökülür.',
    whyWrong: [
      'Zincir hız serbestisi vermez; tam tersine hız tavanı getirir.',
      'Riski inişle sınırlamak, düz yolda kopan zincirin verdiği zararı görmezden gelmektir.',
    ],
    objective: 'Zincirli sürüşte hız sınırı ve söküm zamanını bilmek.',
    tags: ['kar-zinciri', 'hiz-siniri', 'kis-surusu'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-529',
    subject: 'pratik',
    topic: 'kis-zincir-buzlanma',
    difficulty: 'orta',
    stem: 'Kar zinciri hangi tekerleklere takılmalıdır?',
    options: [
      'Motordan güç alan (çekiş yapan) akstaki tekerleklere; önden çekişli araçta öne, arkadan itişli araçta arkaya',
      'Her araçta yalnızca arka tekerleklere',
      'Yalnızca sol taraftaki tekerleklere',
      'Stepneye',
    ],
    answerIndex: 0,
    explanation:
      'Zincirin görevi çekiş gücünü kara aktarmaktır; bu yüzden motorun döndürdüğü aksa takılır. Önden çekişli araçlarda ön, arkadan itişli araçlarda arka tekerleklere takılır; dört çekerlerde üretici talimatına bakılır. Yanlış aksa takılan zincir kalkışta işe yaramaz.',
    whyWrong: [
      'Her aracı arkadan itişli saymak, bugün yaygın olan önden çekişlilerde zinciri boşa takmaktır.',
      'Tek tarafa ya da stepneye zincir takmanın çekişe hiçbir katkısı olmaz.',
    ],
    objective: 'Zinciri muharrik aksa takma kuralını uygulayabilmek.',
    tags: ['kar-zinciri', 'cekis-aksi', 'kis-surusu'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-530',
    subject: 'pratik',
    topic: 'kis-zincir-buzlanma',
    difficulty: 'orta',
    stem: 'Soğuk havalarda köprü ve viyadük üstlerinin yolun diğer bölümlerinden önce buzlanmasının nedeni nedir ve sürücü ne yapmalıdır?',
    options: [
      'Köprüler daha çok tuzlandığı için buzlanmaz; önlem gerekmez',
      'Köprü zemini alttan da soğuk havayla temas ettiğinden yol gövdesinden önce donar; köprü ve viyadük girişlerinde hız önceden düşürülür, üzerinde ani fren ve manevradan kaçınılır',
      'Köprülerde rüzgâr olmadığı için buz erimez',
      'Köprü asfaltı farklı renkte olduğu için',
    ],
    answerIndex: 1,
    explanation:
      'Yol gövdesi altındaki toprak ısıyı bir süre tutar; köprü tabliyesinin ise hem üstü hem altı soğuk havayla sarılıdır ve önce donar. Hava sıcaklığı sıfıra yaklaştığında yol kuru görünse bile köprü üstü buzlu olabilir. Köprüye girmeden hız düşürülür, üstünde düz direksiyon ve sabit gazla geçilir.',
    whyWrong: [
      'Tuzlama garantisi yoktur ve köprüde rüzgâr çoğu zaman daha da şiddetlidir.',
      'Asfalt rengi buzlanma sırasını belirlemez; belirleyen alttan soğumadır.',
    ],
    objective: 'Köprü üstü erken buzlanma riskini öngörüp sürüşü ayarlamak.',
    tags: ['buzlanma', 'kopru', 'kis-surusu'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-531',
    subject: 'pratik',
    topic: 'arac-cekme',
    difficulty: 'kolay',
    stem: 'Arızalı bir araç halatla çekilirken çekilen aracın direksiyonunda neden mutlaka sürücü belgesi olan biri oturmalıdır?',
    options: [
      'Halatın düğümünü izlemek için',
      'Çekilen aracın direksiyonunu doğrultmak ve gerektiğinde frenlemek gerekir; bu işi ancak araç kullanmayı bilen belgeli bir sürücü yapabilir',
      'Radyoyu açık tutmak için',
      'Sadece kapıların kilitli kalması için',
    ],
    answerIndex: 1,
    explanation:
      'Çekilen araç kendi başına yön tutmaz: virajlarda direksiyonun çevrilmesi, duruşlarda halat gerginliğine göre fren yapılması gerekir. Bu nedenle çekilen aracın başında sürücü belgesi olan biri bulunmalıdır. Motoru çalışmayan araçta fren ve direksiyon desteğinin zayıfladığı, pedal ile simidin sertleşeceği de bilinmelidir.',
    whyWrong: [
      'Halat gözlemek yolcunun da yapabileceği bir iştir; direksiyon ve fren ise sürücülük gerektirir.',
      'Radyo ya da kilit, çekilen aracın yön ve fren ihtiyacıyla ilgisizdir.',
    ],
    objective: 'Çekilen araçta belgeli sürücü bulundurma zorunluluğunun gerekçesini bilmek.',
    tags: ['arac-cekme', 'cekilen-arac', 'kural'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-532',
    subject: 'pratik',
    topic: 'arac-cekme',
    difficulty: 'zor',
    stem: 'Halatla çekmede kalkış ve seyir sırasında halat gerginliği nasıl yönetilir?',
    options: [
      'Çeken araç hızla kalkar, halatın kendiliğinden gerilmesi beklenir',
      'Halat bol bırakılır; ara sıra gerilip boşalması normaldir',
      'Çeken araç halat gerilene kadar sürünme hızında ilerler, gerginlik oluşunca yumuşakça hızlanır; çekilen araç hafif fren baskısıyla halatı sürekli gergin tutar ve ani boşalıp kasılmaları önler',
      'Çekilen araç sık sık sert fren yaparak halatı test eder',
    ],
    answerIndex: 2,
    explanation:
      'Halatlı çekmenin en riskli anı, boşalan halatın aniden kasılmasıdır: kopma, bağlantı fırlaması ve sarsıntılı savrulma buradan doğar. Çeken sürücü kalkışı halat gerilene kadar sürünerek yapar; çekilen sürücü ise hafif fren baskısıyla halatı hep gergin tutar. Böylece güç aktarımı darbe yerine süreklilikle olur.',
    whyWrong: [
      'Hızlı kalkış, gevşek halatın kırbaç gibi kasılıp kopmasının başlıca nedenidir.',
      'Halatı bol bırakmak ya da sert frenlerle sınamak, her gerilme anını bir darbeye çevirir.',
    ],
    objective: 'Halatlı çekmede gerginlik yönetimini iki araç arasında kurabilmek.',
    tags: ['arac-cekme', 'halat-gerginligi', 'koordinasyon'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-533',
    subject: 'pratik',
    topic: 'sinav-direksiyon-hakimiyeti',
    difficulty: 'orta',
    stem: 'Direksiyon sınavında görevliler adayın "araç hâkimiyetini" hangi gözlemlerden değerlendirir?',
    options: [
      'Şerit içinde salınmadan gitme, direksiyonu kontrollü kullanma, manevralarda az sayıda düzeltmeyle sonuca ulaşma ve kaldırıma sürtmeme gibi gözlemlerden',
      'Yalnızca adayın kıyafetinden',
      'Aracın markasından ve renginden',
      'Sınavın hangi saatte yapıldığından',
    ],
    answerIndex: 0,
    explanation:
      'Araç hâkimiyeti soyut bir kanı değildir; görevli somut belirtilere bakar: araç şerit içinde salınıyor mu, direksiyon telaşsız ve ölçülü mü kullanılıyor, park ve dönüş manevraları kaç düzeltmeyle tamamlanıyor, kaldırım ya da dubalara temas var mı. Bu gözlemlerin toplamı hâkimiyet notunu oluşturur.',
    whyWrong: [
      'Kıyafet, aracın rengi ya da sınav saati değerlendirme ölçütü değildir.',
      'Değerlendirme adayın sürüş davranışına, yani gözlemlenebilir hâkimiyet belirtilerine dayanır.',
    ],
    objective: 'Sınavda araç hâkimiyetinin hangi davranışlardan okunduğunu bilmek.',
    tags: ['sinav-degerlendirme', 'arac-hakimiyeti', 'serit-takibi'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-534',
    subject: 'pratik',
    topic: 'sinav-direksiyon-hakimiyeti',
    difficulty: 'kolay',
    stem: 'Sınav sürüşünde kolu cam kenarına dayayıp direksiyonu uzun süre tek elle kullanmak nasıl değerlendirilir?',
    options: [
      'Rahatlık işareti sayılıp olumlu puan getirir',
      'Görevli bunu hiç fark etmez',
      'Sınav aracında serbesttir, özel araçta yasaktır',
      'Araç hâkimiyeti zafiyeti olarak not edilir; vites ve kumanda kullanımı dışında iki elin direksiyonda olması beklenir',
    ],
    answerIndex: 3,
    explanation:
      'Tek elle gevşek sürüş, ani bir durumda direksiyona geç müdahale demektir ve görevli bunu hâkimiyet eksikliği olarak değerlendirir. Vites değiştirme ve kumanda kullanımı dışında iki el direksiyonda, tutuş dengeli olmalıdır. Sınav, özensiz alışkanlıkların değil güvenli tekniğin sergilendiği yerdir.',
    whyWrong: [
      'Gevşeklik görüntüsü sınavda rahatlık değil özensizlik olarak okunur.',
      'Kurallar sınav aracına özgü değildir; güvenli tutuş her sürüşün gereğidir.',
    ],
    objective: 'Sınavda iki elle dengeli direksiyon tutuşunun beklendiğini bilmek.',
    tags: ['sinav-degerlendirme', 'tek-el-surus', 'tutus'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-535',
    subject: 'pratik',
    topic: 'sinav-direksiyon-hakimiyeti',
    difficulty: 'orta',
    stem: 'Sınav boyunca gereksiz ani gaz ve ani frenlerle sarsıntılı araç kullanan adayın durumu nasıl değerlendirilir?',
    options: [
      'Dinamik sürüş sayılıp övgü alır',
      'Akıcılık ve araç hâkimiyeti yönünden olumsuz not edilir; hız ve pedal geçişlerinin yumuşak, sürüşün öngörülü olması beklenir',
      'Yakıt tüketimi arttığı için yalnızca uyarı yapılır',
      'Sarsıntı yalnızca yolcu konforu meselesidir, sınavı ilgilendirmez',
    ],
    answerIndex: 1,
    explanation:
      'Sarsıntılı pedal kullanımı, trafiği geç okuyup son anda tepki vermenin dışa vurumudur; görevli bunu öngörü ve hâkimiyet eksikliği olarak değerlendirir. Beklenen, duraklamaları erken görüp yumuşak geçişlerle hız ayarlamaktır. Akıcı sürüş hem konfor hem güvenlik göstergesidir.',
    whyWrong: [
      'Ani gaz-fren dinamiklik değil, plansızlık işaretidir.',
      'Konfor gerekçesi tek başına değil; sarsıntı, sürüş planlamasındaki eksikliği gösterdiği için not edilir.',
    ],
    objective: 'Yumuşak pedal geçişlerinin sınavdaki değerlendirme karşılığını bilmek.',
    tags: ['sinav-degerlendirme', 'akicilik', 'pedal-kontrolu'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-536',
    subject: 'pratik',
    topic: 'sinyal-zamanlama-denge',
    difficulty: 'zor',
    stem: 'Döneceğiniz sokaktan hemen önce başka bir ara sokak varsa dönüş sinyali ne zaman verilmelidir?',
    options: [
      'İki sokaktan da çok önce, en erken noktada verilir',
      'Sinyal hiç verilmez, dönüş sürpriz yapılır',
      'Aradaki sokağın hizası geçildikten sonra verilir; daha erken verilen sinyal, çevredekilere ilk sokağa dönüleceği izlenimi vererek yanıltır',
      'Dönüş tamamlandıktan sonra verilir',
    ],
    answerIndex: 2,
    explanation:
      'Sinyalin değeri doğru bilgi vermesindedir. Ara sokaktan önce yakılan sinyal, oradan çıkmaya hazırlanan sürücüye "bu araç benden önce dönüyor" dedirtebilir ve onu yola çıkartabilir. Doğru zamanlama, yanıltıcı sapağın hizası geçilir geçilmez sinyali verip hazırlığı sürdürmektir: erken ama yanıltmayacak kadar.',
    whyWrong: [
      'En erken nokta her zaman en doğru nokta değildir; yanlış sokağa işaret eden sinyal tehlike üretir.',
      'Sinyalsiz ya da dönüşten sonra sinyal, bildirimin amacını tümüyle ortadan kaldırır.',
    ],
    objective: 'Sinyal zamanlamasını yanıltmama ilkesine göre ayarlayabilmek.',
    tags: ['sinyal-zamanlama', 'ara-sokak', 'yaniltmama'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-537',
    subject: 'pratik',
    topic: 'u-donusu-secimi',
    difficulty: 'orta',
    stem: 'Yönünüzü tersine çevirmek için U dönüşü mü üç nokta dönüşü mü yapılacağına neyle karar verilir?',
    options: [
      'Yolun genişliği, görüş uzunluğu ve trafik yoğunluğuyla: araç tek hamlede karşı yöne dönebilecek genişlik ve güvenli boşluk varsa U dönüşü; yol darsa ve tek hamle yetmiyorsa üç nokta dönüşü seçilir',
      'Aracın rengiyle',
      'Her zaman üç nokta dönüşü zorunludur',
      'Yakıt göstergesinin durumuyla',
    ],
    answerIndex: 0,
    explanation:
      'Seçimin ölçüsü yol kesitidir: dönüş yasak değilse, yol aracın dönüş çapına yetiyorsa ve iki yönden de yeterli görüş ile boşluk varsa tek hamlelik U dönüşü hem kısa hem akıcıdır. Yol dar kaldığında dönüş zorlanmaz; ileri-geri hamleli üç nokta dönüşüne geçilir. Yanlış olan, dar yolda U dönüşünü zorlayıp yolu kapatmaktır.',
    whyWrong: [
      'Araç rengi ya da yakıt durumu manevra seçimiyle ilgisizdir.',
      'Üç nokta dönüşü zorunluluk değil, dar kesit için tasarlanmış alternatiftir.',
    ],
    objective: 'U dönüşü ile üç nokta dönüşü arasında yol kesitine göre seçim yapabilmek.',
    tags: ['u-donusu', 'uc-nokta-donusu', 'manevra-secimi'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-538',
    subject: 'pratik',
    topic: 'u-donusu-secimi',
    difficulty: 'orta',
    stem: 'İzin verilen bir yerde U dönüşü yapacak sürücü, konum ve öncelik açısından neye dikkat etmelidir?',
    options: [
      'Sağ şeritten geniş kavis alarak döner ve önceliği kendisinde sayar',
      'Dönüşe kavşak ortasında karar verip anında direksiyon kırar',
      'U dönüşü yapan araç her zaman geçiş üstünlüğüne sahiptir',
      'Dönüşe en soldaki uygun şeritten, sol sinyalle hazırlanır; karşıdan gelenlere ve arkadan gelen trafiğe yol verdikten sonra döner, çünkü öncelik dönüş yapanda değildir',
    ],
    answerIndex: 3,
    explanation:
      'U dönüşü akan trafiği kesen bir manevradır; öncelik dönüş yapanda değil, yoluna devam edenlerdedir. Sürücü sol sinyalle en soldaki uygun konuma yerleşir, karşı yönden ve arkadan gelenleri kontrol eder, güvenli boşluk oluşunca tek hamlede döner. Sağdan geniş kavis almak, sağ şeritteki trafiği hazırlıksız yakalar.',
    whyWrong: [
      'Sağ şeritten dönüş, aradaki şeritlerde seyredenlerin yolunu keser.',
      'U dönüşü yapana öncelik tanıyan bir kural yoktur; ani kararla dönmek trafiği kilitleyebilir.',
    ],
    objective: 'U dönüşünde konumlanma ve öncelik kurallarını uygulayabilmek.',
    tags: ['u-donusu', 'gecis-onceligi', 'konumlanma'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-539',
    subject: 'pratik',
    topic: 'yan-ruzgar',
    difficulty: 'orta',
    stem: 'Köprü çıkışı, viyadük ve açık ova kesimlerinde aniden bastıran yan rüzgâra karşı sürücü nasıl hazırlanır?',
    options: [
      'Camlar açılarak rüzgârın içeri alınmasıyla',
      'Direksiyon iki elle kavranır, hız düşürülür ve aracın rüzgârla itilmesi küçük, sakin düzeltmelerle karşılanır; büyük araçların yanından geçerken ek itki beklenir',
      'Rüzgâra karşı sürekli korna çalınarak',
      'Hızlanıp rüzgârlı bölgeden bir an önce çıkılarak',
    ],
    answerIndex: 1,
    explanation:
      'Yan rüzgâr, kesitin açıldığı köprü ve viyadük çıkışlarında aracı bir anda şeritten itebilir. Hazırlık: iki elle dengeli tutuş, düşürülmüş hız ve itmeyi abartısız küçük düzeltmelerle karşılamak. Kamyon-otobüs sollarken önce rüzgâr kesilir, aracın önünden çıkınca yeniden vurur; bu ikili itki de beklenerek karşılanır.',
    whyWrong: [
      'Cam açmak ya da korna, aracın rüzgârla itilmesini etkilemez.',
      'Hızlanmak, aynı itkinin daha büyük şerit sapmasına dönüşmesi demektir.',
    ],
    objective: 'Yan rüzgâr bölgelerinde tutuş, hız ve düzeltme hazırlığını yapabilmek.',
    tags: ['yan-ruzgar', 'kopru-cikisi', 'direksiyon-duzeltme'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-540',
    subject: 'pratik',
    topic: 'kis-hazirlik-gorus',
    difficulty: 'kolay',
    stem: 'Karlı bir sabah yola çıkmadan önce araçta yapılması gereken temizlik hangisidir?',
    options: [
      'Yalnızca ön camın sürücü hizasında küçük bir bölme açmak',
      'Karın sürüş sırasında rüzgârla uçmasını beklemek',
      'Tüm camları, aynaları ve farları temizlemek; tavan ve kaputtaki karı da almak, çünkü frende öne kayarak camı kapatabilir veya arkadaki araçların üzerine savrulabilir',
      'Sadece silecekleri çalıştırıp yola çıkmak',
    ],
    answerIndex: 2,
    explanation:
      'Görüş, camın tamamından sağlanır; küçük bir delikten sürüş kör sürüştür. Aynalar, farlar ve stop lambaları da görünürlük için temizlenir. Tavandaki kar ilk frende öne kayıp ön camı bir anda örtebilir, seyirde ise arkadaki araçlara savrulur; bu yüzden kaput ve tavan da karlardan arındırılır.',
    whyWrong: [
      'Küçük bölme ya da yalnız silecek, yan ve arka görüşü tamamen kapalı bırakır.',
      'Uçmasını beklemek, karın en kritik anda (frende) cama inmesine davetiye çıkarır.',
    ],
    objective: 'Kışın hareket öncesi tam görüş temizliğini alışkanlık edinmek.',
    tags: ['kis-hazirlik', 'kar-temizligi', 'gorus'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-541',
    subject: 'pratik',
    topic: 'kis-hazirlik-gorus',
    difficulty: 'zor',
    stem: 'Dondurucu soğukta gece dışarıda kalacak manuel vitesli araç düz zeminde park edilirken bazı sürücüler el frenini neden çekmez?',
    options: [
      'Nemli fren mekanizması gece çekili konumda donarak sabah bırakılamayabilir; bunun yerine araç düz zeminde vites takılı bırakılır, tekerleklere gerekirse takoz konur',
      'El freni soğukta kendiliğinden boşaldığı için',
      'Kışın el freni kullanmak yasak olduğu için',
      'El freni çekilirse motor çalışmayacağı için',
    ],
    answerIndex: 0,
    explanation:
      'Islak ve karlı günün ardından gelen sert donda, çekili el freninin teli ya da balata teması buz tutup kilitlenebilir; sabah fren bırakılamaz. Bu koşulda düz zeminde el freni çekilmeden araç vites takılı bırakılır ve gerekirse tekerlek takozlanır. Eğimli yerde ise el freni gerekliyse çekilir; asıl güvence tekerlek yönü ve vitestir.',
    whyWrong: [
      'El freni soğukta boşalmaz; sorun tam tersine çözülemeyecek kadar tutması, yani donmasıdır.',
      'Kışın el freni yasağı ya da marş engeli diye bir kural yoktur.',
    ],
    objective: 'Sert soğukta el freni donması riskine karşı park önlemini bilmek.',
    tags: ['kis-hazirlik', 'el-freni-donmasi', 'park'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-542',
    subject: 'pratik',
    topic: 'kasis-gecis',
    difficulty: 'kolay',
    stem: 'Hız kesici kasisin üzerinden geçerken doğru teknik hangisidir?',
    options: [
      'Kasise hızla girip üstünde sert fren yapmak',
      'Kasisi tek tekerlekle yandan almaya çalışmak',
      'Kasis üzerinde tam gaz vermek',
      'Kasise varmadan yavaşlamak, üzerinden geçerken frenden ayağı kaldırmak ve kasisi mümkün olduğunca dik açıyla, sabit düşük hızla aşmak',
    ],
    answerIndex: 3,
    explanation:
      'Yavaşlama kasise varmadan tamamlanır; tümseğin üzerinde fren basılı olursa ön süspansiyon zaten çökmüş hâlde darbeyi sert alır. Frenden kaldırınca süspansiyon açılır ve tümseği yumuşak yutar. Kasis dik açıyla, düz direksiyonla ve sabit düşük hızla geçilir; yan almak aracı çaprazlama sallar.',
    whyWrong: [
      'Kasis üstünde fren ya da gaz, süspansiyonu en kötü anında yükler ve darbeyi büyütür.',
      'Tek tekerlekle yandan almak şeridi bozar ve aracı çapraz sarsıntıya sokar.',
    ],
    objective: 'Kasisi frensiz, dik açılı ve düşük sabit hızla geçmeyi öğrenmek.',
    tags: ['kasis', 'suspansiyon', 'gecis-teknigi'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-543',
    subject: 'pratik',
    topic: 'serit-planlama-levha',
    difficulty: 'orta',
    stem: 'Tanımadığı büyük bir kavşağa yaklaşan sürücü, doğru şeride son anda değil erkenden yerleşmeyi nasıl başarır?',
    options: [
      'Kavşağa girdikten sonra diğer araçlara sorarak',
      'Kavşak üstü yön levhalarını ve asfalttaki şerit oklarını uzaktan okuyup gideceği yöne ayrılan şeridi önceden seçerek; böylece son metrelerde şerit kesme zorunluluğu doğmaz',
      'Hep en soldaki şeridi kullanarak',
      'Navigasyon sesini kapatarak',
    ],
    answerIndex: 1,
    explanation:
      'Büyük kavşaklarda yön bilgisi metrelerce önceden levhalarla ve asfalt oklarıyla verilir. Bunları uzaktan okuyan sürücü şeridini sakin bir S-D-Ş dizisiyle erkenden değiştirir; okumayı geciktiren sürücü ise kavşak ağzında ya şerit kesmek ya yanlış yöne gitmek arasında sıkışır. Erken okuma, son anda manevrayı önler.',
    whyWrong: [
      'Kavşak içinde soru sorulmaz, plan kavşaktan önce yapılır.',
      'Her yönde sol şeridi tutmak, sağa ayrılan yönlerde yine son anda kesmeye götürür.',
    ],
    objective: 'Levha ve ok okuyarak kavşak öncesi erken şeritlenmeyi uygulayabilmek.',
    tags: ['serit-planlama', 'yon-levhasi', 'kavsak-hazirligi'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-544',
    subject: 'pratik',
    topic: 'hiz-korlugu',
    difficulty: 'orta',
    stem: 'Uzun süre otoyol hızında giden sürücü şehre indiğinde hızını neden göstergeden kontrol etmelidir?',
    options: [
      'Şehirde gösterge daha doğru çalıştığı için',
      'Otoyolda gösterge kilitlendiği için',
      'Göz uzun süre yüksek hıza alışınca hız algısı körelir; 70-80 km/s bile yavaş hissedilir ve sürücü fark etmeden şehir sınırının çok üzerinde seyredebilir',
      'Şehirde hız zaten önemsiz olduğu için',
    ],
    answerIndex: 2,
    explanation:
      'Hız algısı göreceli çalışır: saatlerce 120 km/s gören göz, 80 km/s hızı yürüme temposu gibi algılar. Buna hız körlüğü denir. Otoyoldan çıkışlarda ve şehir girişlerinde his değil gösterge esas alınmalı, hız bilinçli olarak birkaç kez kontrol edilip düşürülmelidir.',
    whyWrong: [
      'Göstergenin doğruluğu yol tipine göre değişmez; değişen sürücünün algısıdır.',
      'Şehirde hız önemsiz değil, tam tersine yayalar nedeniyle en kritik değişkendir.',
    ],
    objective: 'Hız körlüğünü tanıyıp geçişlerde göstergeyle doğrulama alışkanlığı kazanmak.',
    tags: ['hiz-korlugu', 'algi', 'otoyol-cikisi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-545',
    subject: 'pratik',
    topic: 'arac-referans-noktalari',
    difficulty: 'kolay',
    stem: 'Trafikte öndeki aracın arkasında dururken bırakılacak boşluk için öğretilen pratik referans nedir?',
    options: [
      'Öndeki aracın arka lastiklerinin yere değdiği nokta kaputun üzerinden görülebiliyorsa boşluk yeterlidir; bu pay, öndeki araç arızalanırsa direksiyon kırıp çıkmaya da yeter',
      'Öndeki aracın tamponuna değecek kadar yaklaşmak',
      'İki araç boyu geride durmak her koşulda zorunludur',
      'Boşluğun hiçbir önemi yoktur',
    ],
    answerIndex: 0,
    explanation:
      'Duruşta öndeki aracın arka lastiklerinin asfalta değdiği çizgi görülebiliyorsa araçlar arasında birkaç metrelik sağlıklı bir pay var demektir. Bu boşluk, öndeki araç stop ederse manevrayla çıkmaya, arkadan yaklaşan araç görüldüğünde ise öne kaçış payı yaratmaya yeter. Tampona yapışan sürücü kendini kilitler.',
    whyWrong: [
      'Tampona yaklaşmak, öndeki araç kalkamazsa sizi de o şeride hapseder.',
      'İki araç boyu düz yolda gereksiz uzundur; ölçü görülebilir lastik temas çizgisidir.',
    ],
    objective: 'Duruş boşluğunu lastik-görme referansıyla ayarlayabilmek.',
    tags: ['referans-noktasi', 'durus-boslugu', 'kacis-payi'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-546',
    subject: 'pratik',
    topic: 'vites-dusurme-motor-freni',
    difficulty: 'zor',
    stem: 'Yüksek hızda seyrederken aniden çok düşük bir vitese (örneğin beşinciden ikinciye) geçmek neden risklidir?',
    options: [
      'Vites kolu kırılacağı için',
      'Debriyaj bırakıldığında motor devri aniden fırlar ve çekiş tekerlekleri sert motor freniyle âdeta kilitlenme etkisi yaşar; kaygan zeminde bu, savrulmayı tetikleyebilir ve mekanik zorlanma yaratır',
      'Yakıt göstergesi sıfırlanacağı için',
      'Hiçbir riski yoktur, en hızlı yavaşlama böyle yapılır',
    ],
    answerIndex: 1,
    explanation:
      'Vites atlanarak sert düşüşte debriyaj bırakıldığı anda motor devri sıçrar ve güçlü motor freni çekiş tekerleklerini bir anda yavaşlatır; bu, özellikle ıslak-kaygan zeminde frenle kilitlenmeye benzer bir kayma başlatabilir. Doğrusu, hızın önce frenle düşürülüp vitesin hıza uygun kademeye sırayla indirilmesidir.',
    whyWrong: [
      'Risk kol ya da göstergede değil, tekerleğe binen ani motor freni darbesindedir.',
      'En hızlı ve dengeli yavaşlama frenle yapılır; vites sıçratmak fren yerine geçmez.',
    ],
    objective:
      'Sert vites düşürmenin çekiş tekerleğine etkisini kavrayıp kademeli düşüşü benimsemek.',
    tags: ['vites-dusurme', 'motor-freni', 'kaygan-zemin'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-547',
    subject: 'pratik',
    topic: 'yaya-iletisim',
    difficulty: 'orta',
    stem: 'Durup yol verdiğiniz yayaya diğer şeritler adına da "geç" işareti yapmak neden tehlikelidir?',
    options: [
      'El işareti trafikte kaba sayıldığı için',
      'Yaya işareti anlamayabileceği için',
      'Yayanın geçişi zaten yasak olduğu için',
      'Siz yalnızca kendi şeridinizi güvenceye alabilirsiniz; işaretle yüreklendirilen yaya, yandaki şeritten gelen ve durmayan aracın önüne sizin güvencenizle adım atabilir',
    ],
    answerIndex: 3,
    explanation:
      'Sürücünün verebileceği tek garanti kendi aracının durduğudur. "Geç" işareti yaya tarafından tüm yolun güvenli olduğu biçiminde okunur; oysa yan şeritten gelen sürücü durmayabilir. Doğrusu durup beklemek ve yayanın tüm şeritleri kendi gözüyle kontrol ederek geçmesine alan bırakmaktır.',
    whyWrong: [
      'Sorun nezaket ya da işaretin anlaşılması değil, verilemeyecek bir güvencenin verilmesidir.',
      'Yaya geçidinde geçiş yasak değildir; tersine öncelik çoğu durumda yayanındır.',
    ],
    objective: 'Başka şeritler adına güvence verme hatasından kaçınmayı öğrenmek.',
    tags: ['yaya-iletisimi', 'gec-isareti', 'coklu-serit'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-548',
    subject: 'pratik',
    topic: 'park-teknoloji-guven',
    difficulty: 'kolay',
    stem: 'Park sensörü ve geri görüş kamerası bulunan araçta omuz ve ayna kontrolleri için doğru yaklaşım nedir?',
    options: [
      'Sensör ve kamera yardımcıdır; alçak nesneleri, ince direkleri ve aniden giren yayayı kaçırabildikleri için omuz, ayna ve cam kontrolleri aynen sürdürülür',
      'Sensör varsa başka hiçbir kontrol gerekmez',
      'Kamera açıkken aynalara bakmak yasaktır',
      'Sensör sesi kapatılırsa manevra daha güvenli olur',
    ],
    answerIndex: 0,
    explanation:
      'Sensor ve kamera görüşü tamamlar, yerine geçmez: kameranın açısı sınırlıdır, sensörler alçak bordürü ya da ince demiri geç algılayabilir, hareketli yaya ekrana son anda girer. Bu yüzden manevrada omuz üzerinden bakış, aynalar ve doğrudan cam gözlemi teknoloji varken de sürer; ekran yalnızca ek bilgidir.',
    whyWrong: [
      'Kontrolleri teknolojiye devretmek, sistemin kör kaldığı ilk nesnede çarpma demektir.',
      'Aynaya bakma yasağı ya da sensör kapatma önerisi diye bir kural yoktur.',
    ],
    objective: 'Park teknolojilerini gözlemin yerine değil yanına koymayı öğrenmek.',
    tags: ['park-sensoru', 'geri-kamera', 'gozlem'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-549',
    subject: 'pratik',
    topic: 'donuste-iz-farki',
    difficulty: 'zor',
    stem: 'Dar bir köşeden sağa dönerken arka tekerleğin kaldırıma sürtmesinin nedeni ve çözümü nedir?',
    options: [
      'Lastik basıncının düşük olması; basınç artırılır',
      'Direksiyonun geç düzeltilmesi; dönüşte direksiyon hiç kırılmaz',
      'Arka tekerlekler dönüşte ön tekerleklerden daha içeriden bir iz çizer (iz farkı); köşe biraz ileri alınarak dönüşe geç başlanır ve direksiyon köşe hizası geçilirken kırılır',
      'Aracın arkasının ağır olması; bagaj boşaltılır',
    ],
    answerIndex: 2,
    explanation:
      'Dönen araçta arka aks, ön aksın izinin içinden gider; buna iz farkı denir. Direksiyon köşeye erken kırılırsa ön tekerlek kurtulsa bile arka tekerlek bordüre biner. Çözüm, aracı köşe hizasını biraz geçirene kadar düz sürmek ve dönüşü ondan sonra başlatmaktır; böylece arka iz de köşeyi temiz döner.',
    whyWrong: [
      'Lastik basıncı ya da bagaj yükü, geometrik iz farkını ortadan kaldırmaz.',
      'Direksiyonu hiç kırmamak dönüşü imkânsız kılar; mesele kırmayı doğru ana ertelemektir.',
    ],
    objective: 'İz farkını hesaba katarak dar dönüşe geç girmeyi öğrenmek.',
    tags: ['iz-farki', 'dar-donus', 'kaldirim-surtme'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-550',
    subject: 'pratik',
    topic: 'sollama-sonrasi-donus',
    difficulty: 'orta',
    stem: 'Sollama tamamlandıktan sonra sağ şeride dönüşün doğru zamanı nasıl belirlenir?',
    options: [
      'Sollanan aracın burnu görünür görünmez hemen kırılır',
      'Sollanan aracın önüne mümkün olan en yakın mesafede girilir',
      'Şeride dönüş hiç yapılmaz, sol şeritte devam edilir',
      'Sollanan araç iç dikiz aynasında bütünüyle görününce sağ sinyal verilir ve kademeli dönülür; bu, önüne yeterli boşluk bırakıldığının pratik göstergesidir',
    ],
    answerIndex: 3,
    explanation:
      'Sollamanın son hatası erken dönmektir: geçilen aracın önüne dar girmek onu frene zorlar. Pratik ölçü, sollanan aracın iç aynada tamamı görünene kadar sol şeritte kalmaktır; bu görüntü, araya güvenli boşluk girdiğini gösterir. Sonrasında sinyalle, ani kesmeden kademeli dönülür.',
    whyWrong: [
      'Burun görünür görünmez ya da en yakın mesafede dönmek, sollanan aracın güvenlik payını çalar.',
      'Sol şeridi işgal ederek devam etmek de kurallara aykırıdır; geçiş bitince sağa dönülür.',
    ],
    objective: 'Sollama sonrası dönüş zamanını iç ayna ölçütüyle belirleyebilmek.',
    tags: ['sollama', 'serit-donusu', 'ic-ayna-olcutu'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-551',
    subject: 'pratik',
    topic: 'hayvan-cikmasi',
    difficulty: 'orta',
    stem: 'Kırsal yolda önünüze aniden bir hayvan çıktığında temel davranış ne olmalıdır?',
    options: [
      'Şeridi koruyarak kontrollü fren yapmak; ani ve sert şerit değiştirmek karşı trafiğe ya da şarampole savrulma riski taşıdığından çoğu zaman çarpışmadan daha ağır sonuç doğurur',
      'Direksiyonu gözü kapalı karşı şeride kırmak',
      'Korna çalıp hızlanarak hayvandan önce geçmek',
      'Farları söndürüp beklemek',
    ],
    answerIndex: 0,
    explanation:
      'Ani engelde en büyük ikincil tehlike, refleksle yapılan sert kaçış manevrasıdır: karşı şeritte araç, yol dışında şarampol olabilir. Doğru davranış şeridi koruyup elden gelen en kontrollü freni yapmaktır. Ayrıca yolda tek hayvan görüldüğünde arkasından sürünün gelebileceği düşünülüp hız erken düşürülür.',
    whyWrong: [
      'Bakılmadan yapılan şerit kaçışı, hayvan çarpmasını kafa kafaya çarpışmaya çevirebilir.',
      'Hızlanmak ya da far söndürmek durumu yalnızca içinden çıkılmaz yapar.',
    ],
    objective: 'Ani hayvan çıkışında şeridi koruyarak kontrollü frenlemeyi öğrenmek.',
    tags: ['hayvan-cikmasi', 'kirsal-yol', 'kacinma'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-552',
    subject: 'pratik',
    topic: 'su-birikintisi-tek-taraf',
    difficulty: 'zor',
    stem: 'Yalnızca sağ tekerleklerin gireceği derin bir su birikintisine yüksek hızla girmek araçta hangi etkiyi yaratır?',
    options: [
      'Araç daha dengeli hâle gelir',
      'Sudaki taraf ani dirençle yavaşlarken kuru taraf hızını korur; araç bir anda birikinti tarafına çekilir ve direksiyon gevşek tutuluyorsa şeritten sapabilir',
      'Yalnızca cam biraz kirlenir, sürüş etkilenmez',
      'Motor devri kendiliğinden yükselir',
    ],
    answerIndex: 1,
    explanation:
      'Tek taraftaki tekerleklerin suya girmesi, aracın iki yanına eşit olmayan direnç uygular: sulu taraf frenlenmiş gibi yavaşlar ve araç o yana doğru çeker. Önlem, birikintiyi uzaktan görüp hızı önceden düşürmek ve direksiyonu iki elle sıkıca kavrayarak çekmeyi küçük düzeltmelerle karşılamaktır.',
    whyWrong: [
      'Asimetrik direnç dengeyi artırmaz, tam tersine ani bir yön çekmesi yaratır.',
      'Cam kirlenmesi ya da devir değişimi buradaki asıl tehlikeyi tanımlamaz.',
    ],
    objective: 'Tek taraflı su direncinin yön çekmesine karşı hazırlıklı olmak.',
    tags: ['su-birikintisi', 'asimetrik-direnc', 'direksiyon-tutus'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-553',
    subject: 'pratik',
    topic: 'gunes-kamasmasi',
    difficulty: 'kolay',
    stem: 'Gün doğumu ve batımında alçak güneş tam karşıdan vurduğunda sürücü ne yapmalıdır?',
    options: [
      'Gözlerini kısarak aynı hızda devam etmek',
      'Güneşe uzun farla karşılık vermek',
      'Güneşliği indirmek, hızı düşürüp takip mesafesini artırmak ve ön camın temiz olmasına dikkat etmek; kirli cam ışığı dağıtarak kamaşmayı büyütür',
      'Yolun soluna geçerek gölgede sürmek',
    ],
    answerIndex: 2,
    explanation:
      'Alçak güneş, ışıklı tabelaları ve fren lambalarını görünmez edecek kadar kamaştırabilir. Güneşlik indirilir, hız ve takip payı görüşteki kayba göre ayarlanır. Az bilinen etken camdır: iç-dış kiri ve silecek izleri güneşi cam boyunca dağıtır; temiz cam kamaşmayı belirgin azaltır.',
    whyWrong: [
      'Göz kısarak hızını korumak, görmeden sürmeye devam etmektir.',
      'Uzun far güneşe etki etmez; şeride ters geçmek ise başlı başına tehlikedir.',
    ],
    objective: 'Alçak güneş kamaşmasına hız, mesafe ve cam temizliğiyle önlem almak.',
    tags: ['gunes-kamasmasi', 'gorus', 'cam-temizligi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-554',
    subject: 'pratik',
    topic: 'bordursuz-egim-park',
    difficulty: 'zor',
    stem: 'Kenarında bordür (kaldırım taşı) bulunmayan eğimli bir yol kenarına park ederken ön tekerlekler hangi yöne çevrilir?',
    options: [
      'İnişte de çıkışta da yolun dışına (banket tarafına) çevrilir; dayanak olacak bordür bulunmadığından kayan araç trafiğin içine değil yol dışına yönelmelidir',
      'İnişte içe, çıkışta dışa çevrilir; bordürlü yolla aynıdır',
      'Bordür yoksa tekerlek yönünün önemi kalmaz',
      'Her durumda yolun ortasına doğru çevrilir',
    ],
    answerIndex: 0,
    explanation:
      'Bordürlü parkta tekerlek yönü, kayan aracı bordüre yaslandırma hesabıyla kurulur. Bordür yoksa yaslanacak dayanak da yoktur; tek güvenli ilke, fren tutmazsa aracın yol dışına (bankete) yuvarlanmasını sağlamaktır. Bu yüzden eğim yönü fark etmeksizin tekerlekler yolun dışına çevrilir; el freni ve vites önlemleri aynen alınır.',
    whyWrong: [
      'Bordürlü kural burada geçersizdir; çünkü kuralın dayanağı olan taş yoktur.',
      'Yönü önemsiz saymak ya da yol ortasına çevirmek, kayan aracı doğrudan trafiğe gönderir.',
    ],
    objective: 'Bordürsüz eğimde tekerlekleri yol dışına çevirme ilkesini uygulayabilmek.',
    tags: ['egimde-park', 'bordursuz-yol', 'tekerlek-yonu'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-555',
    subject: 'pratik',
    topic: 'rampada-bekleme-mesafesi',
    difficulty: 'kolay',
    stem: 'Yokuş yukarı trafikte, duran bir aracın arkasında beklerken düz yola göre neden daha fazla boşluk bırakılmalıdır?',
    options: [
      'Yokuşta korna sesi daha az duyulduğu için',
      'Boşluk motorun soğumasını sağladığı için',
      'Yokuşta beklemek yasak olduğu için',
      'Öndeki araç kalkışta bir miktar geriye kayabilir; bırakılan ek boşluk bu kaymayı karşılar ve gerekirse şeritten çıkma payı da verir',
    ],
    answerIndex: 3,
    explanation:
      'Manuel araçların bir bölümü rampa kalkışında kısa bir geri kayma yaşar; öndekine yapışık duran araç bu kaymada temas alır. Yokuşta öndekiyle aradaki pay bilinçli olarak büyütülür; bu pay ayrıca öndeki araç kalkamazsa manevrayla çıkabilme imkânı verir. Kendi kalkışınızda da arkanızdaki mesafe aynı nedenle önemlidir.',
    whyWrong: [
      'Korna ya da motor soğuması, mesafe kuralının gerekçesi değildir.',
      'Yokuşta trafik gereği beklemek yasak değildir; önemli olan bekleme biçimidir.',
    ],
    objective: 'Rampada öndekinin geri kayma payını hesaba katarak durabilmek.',
    tags: ['rampa', 'bekleme-mesafesi', 'geri-kayma'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
];
