/**
 * ÖZGÜN trafik soruları (Sprint 3 genişletme). ROADMAP C.4/E.6.
 * Kaynak = resmî MEB/ODSGM müfredatı + Karayolları Trafik mevzuatı; KENDİ İFADEMİZLE.
 * Hiçbir uygulama/site sorusu kopyalanmamıştır. review: 'draft' — uzman onayı gerekir.
 */
import type { Question } from '@ea/content-schema';

const SRC = 'Resmî MEB/ODSGM müfredatı ve Karayolları Trafik mevzuatı (özgün ifade)';

export const TRAFIK_QUESTIONS: Question[] = [
  {
    id: 'trafik-101',
    subject: 'trafik',
    topic: 'hiz',
    difficulty: 'kolay',
    stem: 'Yağışlı, sisli veya buzlanma olan bir yolda sürücü hızını nasıl ayarlamalıdır?',
    options: [
      'Yasal hız sınırında sabit olarak devam eder',
      'Hızını yol ve hava koşullarına göre yasal sınırın da altına düşürür',
      'Trafiği aksatmamak için hızını artırır',
      'Yalnızca sisli havada yavaşlar, yağmurda gerek yoktur',
    ],
    answerIndex: 1,
    explanation:
      'Yasal hız sınırı bir tavandır; her koşulda o hızla gidilebileceği anlamına gelmez. Görüşün azaldığı veya yol tutuşunun düştüğü yağışlı, sisli ve buzlu havalarda sürücü hızını koşullara göre azaltmak, gerekirse yasal sınırın çok altına inmek zorundadır.',
    whyWrong: [
      'Yasal sınır azami değerdir; kötü koşulda bu hızda gitmek güvenli ve kurallara uygun değildir.',
      'Hızı artırmak fren ve durma mesafesini uzatarak tehlikeyi büyütür.',
      'Yağmur da görüşü ve yol tutuşunu azaltır; yavaşlama yalnızca sise özgü değildir.',
    ],
    objective:
      'Kötü hava ve yol koşullarında hızın koşullara göre azaltılması zorunluluğunu kavramak.',
    tags: ['hiz', 'hava-kosullari', 'yagis-sis'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-102',
    subject: 'trafik',
    topic: 'hiz',
    difficulty: 'kolay',
    stem: 'Otoyolda otomobiller için genel azami hız sınırı kaç km/saattir?',
    options: ['90', '100', '110', '120'],
    answerIndex: 3,
    explanation:
      'Otoyollarda otomobiller için genel azami hız 120 km/saattir; bu, en yüksek genel hız sınırının uygulandığı yol tipidir.',
    whyWrong: [
      '110 km/s yerleşim dışı bölünmüş yolun sınırıdır, otoyolun değil.',
      '90 ve 100 km/s otoyol genel sınırının altındadır.',
    ],
    objective: 'Otoyol azami hız sınırını bilmek.',
    tags: ['hiz-siniri', 'otoyol', 'otomobil'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-103',
    subject: 'trafik',
    topic: 'hiz',
    difficulty: 'orta',
    stem: 'Yerleşim yeri dışındaki bölünmüş bir kara yolunda otomobil için genel azami hız kaç km/saattir?',
    options: ['90', '100', '110', '120'],
    answerIndex: 2,
    explanation:
      'Yerleşim yeri dışındaki bölünmüş yollarda otomobil için genel azami hız 110 km/saattir; bu, otoyolun bir alt kademesidir.',
    whyWrong: [
      '90 km/s bölünmemiş (iki yönlü) şehirlerarası yolun sınırıdır.',
      '120 km/s yalnızca otoyolda geçerlidir.',
    ],
    objective: 'Bölünmüş şehirlerarası yolda hız sınırını ayırt etmek.',
    tags: ['hiz-siniri', 'bolunmus-yol', 'sehirlerarasi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-104',
    subject: 'trafik',
    topic: 'hiz',
    difficulty: 'orta',
    stem: 'Yerleşim yeri dışındaki bölünmemiş (iki yönlü) kara yolunda otomobil için genel azami hız kaç km/saattir?',
    options: ['70', '80', '90', '110'],
    answerIndex: 2,
    explanation:
      'Yerleşim yeri dışındaki bölünmemiş iki yönlü yollarda otomobil için genel azami hız 90 km/saattir; karşı yönden gelen trafik nedeniyle sınır bölünmüş yoldan düşüktür.',
    whyWrong: [
      '110 km/s yalnızca bölünmüş yolda geçerlidir.',
      '70 ve 80 km/s bu yol tipinin genel sınırının altındadır.',
    ],
    objective: 'Bölünmemiş şehirlerarası yolda hız sınırını ayırt etmek.',
    tags: ['hiz-siniri', 'iki-yonlu-yol', 'sehirlerarasi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-105',
    subject: 'trafik',
    topic: 'oncelik',
    difficulty: 'kolay',
    stem: 'Işıklı işaret veya trafik görevlisi bulunmayan, eşit yollu bir kavşakta geçiş önceliği kime aittir?',
    options: [
      'Kendi soluna gelen araca',
      'Kendi sağına gelen araca',
      'Daha büyük olan araca',
      'Kavşağa daha hızlı yaklaşan araca',
    ],
    answerIndex: 1,
    explanation:
      'Işıksız ve görevlisiz eşit yollu kavşakta sürücü sağından gelen araca geçiş hakkı verir; bu, temel sağ önceliği kuralıdır.',
    whyWrong: [
      'Aracın büyüklüğü veya hızı önceliği belirlemez.',
      'Öncelik soldan değil, sağdan gelene aittir.',
    ],
    objective: 'Eşit yollu kavşakta sağ önceliği kuralını bilmek.',
    tags: ['gecis-onceligi', 'kavsak', 'sagdan-gelen'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-106',
    subject: 'trafik',
    topic: 'oncelik',
    difficulty: 'orta',
    stem: 'Ana yol ile tali yolun kesiştiği bir kavşakta tali yoldan gelen sürücü ne yapmalıdır?',
    options: [
      'Ana yoldaki araçlara geçiş hakkı verir',
      'Korna çalarak önce geçer',
      'Her durumda önce kendisi geçer',
      'Hızlanarak kavşağı hızlıca boşaltır',
    ],
    answerIndex: 0,
    explanation:
      'Ana yol her zaman önceliklidir; tali yoldan gelen sürücü durup ana yoldaki trafiğe yol vermek, yol boşaldığında güvenle katılmak zorundadır.',
    whyWrong: [
      'Korna çalmak geçiş önceliği kazandırmaz.',
      'Tali yoldan gelenin her durumda önce geçme hakkı yoktur.',
    ],
    objective: 'Ana yol - tali yol önceliğini ayırt etmek.',
    tags: ['gecis-onceligi', 'ana-yol', 'tali-yol'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-107',
    subject: 'trafik',
    topic: 'isaretler',
    difficulty: 'kolay',
    stem: "Sekiz kenarlı, kırmızı zeminli 'DUR' levhası sürücüden ne yapmasını ister?",
    options: [
      'Yalnızca yavaşlamasını',
      'Mutlaka tam durup yol vermesini',
      'Korna çalıp geçmesini',
      'Sağa dönmesini',
    ],
    answerIndex: 1,
    explanation:
      "'DUR' levhasında sürücü, önü boş olsa bile durma çizgisinde aracını tamamen durdurur, kontrol eder ve yol açık ise güvenle hareket eder.",
    whyWrong: [
      'Sadece yavaşlamak yeterli değildir; tam duruş zorunludur.',
      'Levha bir dönüş mecburiyeti bildirmez.',
    ],
    objective: 'DUR levhasının tam duruş zorunluluğunu bilmek.',
    tags: ['trafik-isareti', 'dur-levhasi', 'yol-ver'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-108',
    subject: 'trafik',
    topic: 'isaretler',
    difficulty: 'orta',
    stem: 'Mavi zemin üzerine beyaz sembollü, daire biçimindeki trafik işaretleri genel olarak neyi bildirir?',
    options: [
      'Yasaklama ve kısıtlamayı',
      'Tehlike uyarısını',
      'Mecburiyeti (yapılması zorunlu davranışı)',
      'Sadece bilgilendirmeyi',
    ],
    answerIndex: 2,
    explanation:
      'Mavi zeminli daire işaretler mecburiyet bildirir; örneğin mecburi yön veya asgari hız gibi yapılması zorunlu davranışları gösterir.',
    whyWrong: [
      'Yasaklama kırmızı kenarlı dairelerle bildirilir.',
      'Tehlike uyarısı üçgen işaretlerle verilir.',
    ],
    objective: 'İşaret renk/biçim gruplarının anlamını ayırt etmek.',
    tags: ['trafik-isareti', 'mecburiyet', 'mavi-daire'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-109',
    subject: 'trafik',
    topic: 'isaretler',
    difficulty: 'kolay',
    stem: 'Kenarları kırmızı, zemini açık renk olan üçgen biçimli trafik işaretleri neyi belirtir?',
    options: ['Tehlike uyarısını', 'Park yerini', 'Bir mecburiyeti', 'Yalnızca bilgilendirmeyi'],
    answerIndex: 0,
    explanation:
      'Kırmızı kenarlı üçgen işaretler tehlike uyarısı grubudur; sürücüyü kavşak, viraj, kayan yol gibi olası tehlikelere karşı önceden uyarır.',
    whyWrong: [
      'Park ve bilgilendirme genellikle mavi/dikdörtgen işaretlerle verilir.',
      'Mecburiyet mavi daire işaretlerle bildirilir.',
    ],
    objective: 'Tehlike uyarı işaretlerinin biçimini tanımak.',
    tags: ['trafik-isareti', 'tehlike-uyari', 'ucgen'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-110',
    subject: 'trafik',
    topic: 'isaretler',
    difficulty: 'zor',
    stem: 'Bir kavşakta trafik görevlisi, ışıklı işaret ve levha birbiriyle çelişirse sürücü hangi öncelik sırasına uyar?',
    options: [
      'Yer çizgileri > levha > ışık > görevli',
      'Levha > görevli > ışık > yer çizgileri',
      'Işıklı işaret > görevli > levha',
      'Görevli olmadan yalnızca levha yeterlidir',
      'Trafik görevlisi > ışıklı işaret > levha > yer işaretlemeleri',
    ],
    answerIndex: 4,
    explanation:
      'Çelişki durumunda uyulacak sıra en üstte trafik görevlisi, sonra ışıklı işaret, sonra levha ve en son yol üzerindeki yer işaretlemeleridir.',
    whyWrong: [
      'Yer çizgileri en düşük önceliğe sahiptir, en üste konulamaz.',
      'Trafik görevlisinin talimatı ışık ve levhanın önündedir.',
    ],
    objective: 'Trafiği düzenleyen unsurların öncelik sırasını bilmek.',
    tags: ['trafik-isareti', 'oncelik-sirasi', 'trafik-gorevlisi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-111',
    subject: 'trafik',
    topic: 'sollama',
    difficulty: 'zor',
    stem: 'Aşağıdaki yerlerin hangisinde öndeki aracı sollamak (geçmek) yasaktır?',
    options: [
      'Görüşün açık olduğu düz yolda',
      'Tepe üstü, dönemeç ve yaya geçitlerinde',
      'Sollama şeridi bulunan bölünmüş yolda',
      'Geçiş izni veren kesik yol çizgisi varken',
    ],
    answerIndex: 1,
    explanation:
      'Görüşün kısıtlı olduğu tepe üstü ve dönemeçlerde, ayrıca yaya/okul geçitlerinde sollama yasaktır; bu yerlerde karşı yönü ve yayaları görmek mümkün olmaz.',
    whyWrong: [
      'Görüşün açık olduğu düz yol ve kesik çizgili kesim sollamaya uygundur.',
      'Sollama şeridi zaten geçiş için ayrılmıştır.',
    ],
    objective: 'Sollamanın yasak olduğu yerleri ayırt etmek.',
    tags: ['sollama', 'yasak-yerler', 'gorus-mesafesi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-112',
    subject: 'trafik',
    topic: 'sollama',
    difficulty: 'kolay',
    stem: 'Kural olarak öndeki bir araç hangi taraftan geçilerek sollanır?',
    options: ['Sağdan', 'Soldan', 'Banketten', 'Her iki taraftan serbestçe'],
    answerIndex: 1,
    explanation:
      'Sollama kural olarak sol şeritten yapılır; sürücü sinyal verir, karşı yönü ve arkasını kontrol eder, geçişi güvenle tamamlar ve tekrar sağ şeride döner.',
    whyWrong: [
      'Sağdan geçmek yalnızca özel durumlarda (ör. sola dönmek üzere bekleyen aracın sağından) söz konusudur.',
      'Banketten geçmek yasaktır ve tehlikelidir.',
    ],
    objective: 'Sollamanın yapılacağı doğru tarafı bilmek.',
    tags: ['sollama', 'sol-serit', 'gecis'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-113',
    subject: 'trafik',
    topic: 'takip-mesafesi',
    difficulty: 'kolay',
    stem: 'İki saniye kuralı neyi ayarlamak için kullanılır?',
    options: [
      'Aracın azami hızını',
      'Fren balatasının ömrünü',
      'Motor devir sayısını',
      'Öndeki araçla güvenli takip mesafesini',
    ],
    answerIndex: 3,
    explanation:
      'İki saniye kuralı, öndeki aracın geçtiği sabit bir noktaya en az iki saniye sonra ulaşacak şekilde güvenli takip mesafesi bırakmayı sağlar; fren için tepki payı verir.',
    whyWrong: [
      'Kural hızı, balatayı veya motor devrini belirlemez.',
      'Amaç, ani frende arkadan çarpmayı önleyecek mesafeyi korumaktır.',
    ],
    objective: 'İki saniye kuralının takip mesafesi amacını bilmek.',
    tags: ['takip-mesafesi', 'iki-saniye', 'guvenli-surus'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-114',
    subject: 'trafik',
    topic: 'takip-mesafesi',
    difficulty: 'zor',
    stem: 'Takip mesafesinin en az hızın yarısı kadar metre olması kuralına göre, 90 km/saat hızda kaç metre mesafe bırakılmalıdır?',
    options: ['20 metre', '30 metre', '45 metre', '90 metre'],
    answerIndex: 2,
    explanation:
      'Hızın yarısı kadar metre kuralına göre 90 km/saatte en az 45 metre takip mesafesi bırakılır; hız arttıkça bırakılması gereken mesafe de artar.',
    whyWrong: [
      '90 metre, hızın tamamına eşit yanlış bir hesaptır.',
      '20 ve 30 metre kuralın gerektirdiği asgari mesafenin altındadır.',
    ],
    objective: 'Hıza bağlı takip mesafesini hesaplayabilmek.',
    tags: ['takip-mesafesi', 'hiz-yarisi', 'hesaplama'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-115',
    subject: 'trafik',
    topic: 'donel-kavsak',
    difficulty: 'kolay',
    stem: 'Dönel kavşakta (göbekli kavşak) geçiş önceliği kime aittir?',
    options: [
      'Kavşağa yeni girecek araçlara',
      'Ada etrafında dönmekte olan araçlara',
      'Sağdaki araca',
      'Daha büyük araca',
    ],
    answerIndex: 1,
    explanation:
      'Dönel kavşakta ada etrafında dönmekte olan araçlar önceliklidir; kavşağa girecek sürücü bu araçlara yol verir ve uygun boşlukta katılır.',
    whyWrong: [
      'Kavşağa yeni girecek araç öncelikli değildir, yol vermek zorundadır.',
      'Aracın büyüklüğü dönel kavşakta öncelik sağlamaz.',
    ],
    objective: 'Dönel kavşakta öncelik kuralını bilmek.',
    tags: ['donel-kavsak', 'gecis-onceligi', 'ada'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-116',
    subject: 'trafik',
    topic: 'donel-kavsak',
    difficulty: 'orta',
    stem: 'Dönel kavşaktan çıkarken sürücü hangi işareti vermelidir?',
    options: ['Sol sinyal', 'Dörtlü flaşör', 'Hiçbir işaret', 'Sağ sinyal'],
    answerIndex: 3,
    explanation:
      'Dönel kavşaktan çıkmadan önce sağ sinyal verilir; böylece diğer sürücüler adayı terk edeceğinizi önceden anlar ve trafik güvenli akar.',
    whyWrong: [
      'Sol sinyal adada dönmeye devam edileceğini çağrıştırır, çıkışta yanıltır.',
      'İşaret vermemek diğer sürücüler için tahmin edilemez bir manevradır.',
    ],
    objective: 'Dönel kavşak çıkışında doğru sinyali bilmek.',
    tags: ['donel-kavsak', 'sinyal', 'cikis'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-117',
    subject: 'trafik',
    topic: 'seritler',
    difficulty: 'kolay',
    stem: 'Şehirlerarası bölünmüş bir yolda normal şartlarda hangi şeritte seyredilir?',
    options: [
      'En soldaki şeritte',
      'Ortadaki şeritte',
      'En sağdaki uygun şeritte',
      'İstenilen herhangi bir şeritte',
    ],
    answerIndex: 2,
    explanation:
      'Normal seyirde en sağdaki uygun şerit kullanılır; sol şeritler sollama ve geçiş içindir, boş yere sol şeritte gitmek trafiği aksatır.',
    whyWrong: [
      'En sol ve orta şeritler sürekli seyir için değil, geçiş içindir.',
      'İstenilen her şeritte serbestçe gitmek şerit kullanım kuralına aykırıdır.',
    ],
    objective: 'Normal seyirde doğru şerit seçimini bilmek.',
    tags: ['seritler', 'sag-serit', 'seyir'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-118',
    subject: 'trafik',
    topic: 'seritler',
    difficulty: 'orta',
    stem: 'Çok şeritli bölünmüş bir yolda en sol şerit esas olarak ne için kullanılır?',
    options: [
      'Sürekli seyir için',
      'Sollama, geçiş ve sola dönüş için',
      'Duraklama için',
      'Yavaş araçların gitmesi için',
    ],
    answerIndex: 1,
    explanation:
      'En sol şerit sollama, geçiş ve sola dönüş manevraları içindir; manevra bitince araç tekrar sağdaki uygun şeride döner.',
    whyWrong: [
      'Sol şeritte sürekli seyretmek arkadan gelen hızlı trafiği engeller.',
      'Sol şeritte duraklamak yasaktır ve tehlikelidir.',
    ],
    objective: 'Şeritlerin kullanım amacını ayırt etmek.',
    tags: ['seritler', 'sol-serit', 'sollama'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-119',
    subject: 'trafik',
    topic: 'duraklama-park',
    difficulty: 'zor',
    stem: 'Kural olarak kavşaklara ve bunlara kaç metre mesafedeki yerlere duraklamak yasaktır?',
    options: ['3 metre', '5 metre', '10 metre', '15 metre'],
    answerIndex: 1,
    explanation:
      'Kavşaklara ve kavşaklara 5 metre mesafedeki yerlere duraklamak yasaktır; bu alanda duran araç görüşü ve dönüşleri engeller.',
    whyWrong: [
      '3 metre kuralda belirtilen mesafeden azdır.',
      '10 ve 15 metre gerçek yasak mesafeden fazladır.',
    ],
    objective: 'Duraklamanın yasak olduğu mesafeyi bilmek.',
    tags: ['duraklama', 'kavsak', 'yasak-mesafe'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-120',
    subject: 'trafik',
    topic: 'duraklama-park',
    difficulty: 'kolay',
    stem: "Trafikte 'duraklama' ile 'park etme' arasındaki temel fark nedir?",
    options: [
      'Duraklama, yolcu indirip bindirmek gibi nedenlerle yapılan kısa süreli durmadır',
      'Duraklama ile park tamamen aynı şeydir',
      'Park, duraklamadan daha kısa süreli durmadır',
      'Duraklama yalnızca gece yapılabilir',
    ],
    answerIndex: 0,
    explanation:
      'Duraklama; yolcu indirip bindirmek veya kısa bir iş için yapılan kısa süreli durmadır. Park ise aracı sürücüsüz veya uzun süre bırakmaktır.',
    whyWrong: [
      'İki kavram aynı değildir; süre ve amaç bakımından ayrılır.',
      'Park kısa değil, daha uzun süreli bırakmadır.',
    ],
    objective: 'Duraklama ve park kavramlarını ayırt etmek.',
    tags: ['duraklama', 'park', 'tanim'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-121',
    subject: 'trafik',
    topic: 'duraklama-park',
    difficulty: 'orta',
    stem: 'Yaya geçidinin üzerine park etmek konusunda kural nedir?',
    options: ['Serbesttir', 'Kısa süre için serbesttir', 'Yasaktır', 'Yalnızca gündüz serbesttir'],
    answerIndex: 2,
    explanation:
      'Yaya ve okul geçitleri üzerine park etmek yasaktır; buraya bırakılan araç yayaların güvenli geçişini engeller ve görüşü kapatır.',
    whyWrong: [
      'Geçit üzerinde kısa süreli park da yayaları tehlikeye atar.',
      'Gündüz ya da gece fark etmeksizin geçit üzeri park yasaktır.',
    ],
    objective: 'Yaya geçidi üzerinde park yasağını bilmek.',
    tags: ['park', 'yaya-gecidi', 'yasak-yerler'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-122',
    subject: 'trafik',
    topic: 'yaya',
    difficulty: 'kolay',
    stem: 'Işıklı işaret bulunmayan bir yaya geçidine yaklaşan sürücü, geçide girmek üzere olan yaya varsa ne yapmalıdır?',
    options: [
      'Korna çalıp geçmeli',
      'Hızlanarak geçmeli',
      'Yayadan önce geçmeli',
      'Yavaşlayıp yayaya geçiş hakkı vermeli',
    ],
    answerIndex: 3,
    explanation:
      'Işıksız yaya geçidinde yaya önceliklidir; sürücü yavaşlar, gerektiğinde durur ve yayanın güvenle geçmesini sağlar.',
    whyWrong: [
      'Korna çalmak veya hızlanmak yaya önceliğini ortadan kaldırmaz.',
      'Sürücünün yayadan önce geçme hakkı yoktur.',
    ],
    objective: 'Yaya geçidinde yaya önceliğini bilmek.',
    tags: ['yaya', 'yaya-gecidi', 'gecis-onceligi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-123',
    subject: 'trafik',
    topic: 'yaya',
    difficulty: 'orta',
    stem: 'Yaya geçidi önünde durmuş bir aracın yanından geçerken ne yapmalısınız?',
    options: [
      'Hızlanarak geçmek',
      'Durmadan sollayarak geçmek',
      'Yavaşlayıp gerekirse durarak geçidi kontrol etmek',
      'Korna çalarak devam etmek',
    ],
    answerIndex: 2,
    explanation:
      'Durmuş araç, karşıya geçen yayayı görüşünüzden gizleyebilir; bu nedenle yavaşlar, gerekirse durur ve geçidi kontrol ederek ilerlersiniz.',
    whyWrong: [
      'Durmadan sollamak, aracın önünden çıkan yayaya çarpma riski taşır.',
      'Hızlanmak veya korna çalmak tehlikeyi ortadan kaldırmaz.',
    ],
    objective: 'Yaya geçidinde durmuş araç yanından güvenli geçişi bilmek.',
    tags: ['yaya', 'yaya-gecidi', 'guvenli-surus'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-124',
    subject: 'trafik',
    topic: 'yaya',
    difficulty: 'orta',
    stem: 'Okul geçidi görevlisi elindeki DUR işaretini yola doğru tuttuğunda sürücü ne yapar?',
    options: [
      'Yavaşlayıp geçer',
      'Durur ve öğrencilerin karşıya geçmesini bekler',
      'Korna çalar',
      'Şerit değiştirerek devam eder',
    ],
    answerIndex: 1,
    explanation:
      'Okul geçidi görevlisinin DUR işareti bağlayıcıdır; sürücü aracını durdurur ve öğrenciler güvenle geçtikten sonra görevlinin izniyle hareket eder.',
    whyWrong: [
      'Yavaşlayıp geçmek, görevlinin durma talimatına aykırıdır.',
      'Şerit değiştirmek çocukların bulunduğu geçitte tehlike yaratır.',
    ],
    objective: 'Okul geçidi görevlisinin talimatına uymayı bilmek.',
    tags: ['yaya', 'okul-gecidi', 'gorevli'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-125',
    subject: 'trafik',
    topic: 'cevre',
    difficulty: 'kolay',
    stem: 'Yakıt tüketimini ve egzoz salımını azaltmak için sürücü nasıl davranmalıdır?',
    options: [
      'Sürekli ani hızlanıp ani fren yapmalı',
      'Mümkün olduğunca sabit ve dengeli hızda seyretmeli',
      'Motoru sürekli yüksek devirde tutmalı',
      'Lastikleri düşük basınçta kullanmalı',
    ],
    answerIndex: 1,
    explanation:
      'Sabit ve dengeli hızda seyretmek gereksiz hızlanma-frenlemeyi azaltır; böylece hem yakıt tüketimi hem de egzoz kaynaklı hava kirliliği düşer.',
    whyWrong: [
      'Ani hızlanma ve frenleme yakıt tüketimini artırır.',
      'Yüksek devir ve düşük lastik basıncı çevreye daha çok zarar verir.',
    ],
    objective: 'Çevre dostu sürüş alışkanlıklarını bilmek.',
    tags: ['cevre', 'yakit-tasarrufu', 'ekonomik-surus'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-126',
    subject: 'trafik',
    topic: 'cevre',
    difficulty: 'orta',
    stem: 'Trafikte uzun süreli beklemelerde çevre ve yakıt açısından en doğru davranış nedir?',
    options: [
      'Motoru rölantide çalışır bırakmak',
      'Uygun durumda motoru durdurmak',
      'Gaz vererek beklemek',
      'Farları söndürüp motoru açık tutmak',
    ],
    answerIndex: 1,
    explanation:
      'Uzun süreli beklemelerde motoru durdurmak gereksiz yakıt yakılmasını ve egzoz salımını önler; bu, hem çevre hem ekonomi için doğru davranıştır.',
    whyWrong: [
      'Rölantide veya gaz vererek beklemek boşa yakıt tüketir ve hava kirletir.',
      'Farla ilgili tercih yakıt salımını azaltmaz.',
    ],
    objective: 'Uzun beklemede çevreci davranışı bilmek.',
    tags: ['cevre', 'rolanti', 'emisyon'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-127',
    subject: 'trafik',
    topic: 'cevre',
    difficulty: 'orta',
    stem: 'Lastiklerin olması gerekenden düşük basınçta kullanılması çevre açısından neye yol açar?',
    options: [
      'Yakıt tüketimini ve egzoz salımını artırır',
      'Yakıt tüketimini azaltır',
      'Çevreye hiçbir etkisi olmaz',
      'Motorun daha az ısınmasını sağlar',
    ],
    answerIndex: 0,
    explanation:
      'Düşük lastik basıncı yuvarlanma direncini artırır; bu da daha fazla yakıt yakılmasına ve dolayısıyla daha yüksek egzoz salımına neden olur.',
    whyWrong: [
      'Düşük basınç yakıt tüketimini azaltmaz, tam tersine artırır.',
      'Basınç sorunu hem çevreyi hem de sürüş güvenliğini etkiler.',
    ],
    objective: 'Lastik basıncının çevre ve yakıt üzerindeki etkisini bilmek.',
    tags: ['cevre', 'lastik-basinci', 'yakit-tuketimi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-128',
    subject: 'trafik',
    topic: 'far-isik',
    difficulty: 'kolay',
    stem: 'Gece karşı yönden araç gelirken göz kamaştırmamak için hangi far kullanılır?',
    options: [
      'Uzağı gösteren (uzun huzme) far',
      'Yakını gösteren (kısa huzme) far',
      'Dörtlü flaşör',
      'Sadece sinyal lambası',
    ],
    answerIndex: 1,
    explanation:
      'Karşıdan araç gelirken uzun huzme kapatılır ve yakını gösteren kısa far kullanılır; böylece karşı sürücünün gözü kamaşmaz ve kazadan kaçınılır.',
    whyWrong: [
      'Uzun huzme karşı sürücünün gözünü kamaştırır.',
      'Flaşör ve sinyal yolu aydınlatma amacı taşımaz.',
    ],
    objective: 'Karşılaşmalarda doğru far kullanımını bilmek.',
    tags: ['far-isik', 'kisa-far', 'gece-surusu'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-129',
    subject: 'trafik',
    topic: 'far-isik',
    difficulty: 'orta',
    stem: 'Yeterince aydınlatılmış yerleşim yeri içindeki yollarda hangi farın kullanılması kuraldır?',
    options: [
      'Uzağı gösteren (uzun huzme) far',
      'Yakını gösteren (kısa huzme) far',
      'Yalnızca sis farı',
      'Hiç far kullanılmaması',
    ],
    answerIndex: 1,
    explanation:
      'Aydınlatması yeterli yerleşim yeri içi yollarda kısa huzme (yakın) far kullanılır; uzun huzme diğer sürücülerin ve yayaların gözünü kamaştırdığı için kullanılmaz.',
    whyWrong: [
      'Aydınlatılmış şehir içi yolda uzun huzme kullanmak yasaktır.',
      'Gece far kullanmamak görünürlüğü ortadan kaldırır.',
    ],
    objective: 'Yerleşim yeri içinde doğru far seçimini bilmek.',
    tags: ['far-isik', 'yakin-far', 'yerlesim-yeri'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-130',
    subject: 'trafik',
    topic: 'far-isik',
    difficulty: 'zor',
    stem: 'Sisli havada uzağı gösteren (uzun huzme) farın kullanılması neden sakıncalıdır?',
    options: [
      'Işık sis damlacıklarından geri yansıyıp sürücünün görüşünü daha da bozar',
      'Ampulü daha çabuk yakar',
      'Aküyü aniden bitirir',
      'Motoru gereğinden fazla ısıtır',
    ],
    answerIndex: 0,
    explanation:
      'Sisli havada uzun huzme, sisteki su damlacıklarından geri yansıyarak bir ışık perdesi oluşturur ve görüşü azaltır; bu nedenle yakın far veya varsa sis farı kullanılır.',
    whyWrong: [
      'Sorun ampul, akü veya motor değil, görüşün bozulmasıdır.',
      'Doğru tercih uzun huzme değil, yakın/sis farıdır.',
    ],
    objective: 'Sisli havada far kullanım kuralını bilmek.',
    tags: ['far-isik', 'sis', 'gorus-mesafesi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-131',
    subject: 'trafik',
    topic: 'emniyet-kemeri',
    difficulty: 'kolay',
    stem: 'Emniyet kemeri kullanımı hangi durumda zorunludur?',
    options: [
      'Yalnızca şehirlerarası yolda',
      'Yalnızca ön koltukta',
      'Yalnızca otoyolda',
      'Yalnızca gece sürüşünde',
      'Hem yerleşim yeri içinde hem dışında, ön ve arka tüm koltuklarda',
    ],
    answerIndex: 4,
    explanation:
      'Emniyet kemeri kullanımı yol ve zaman ayrımı yapılmaksızın hem yerleşim içi hem dışı yollarda, ön ve arka tüm koltuklarda zorunludur.',
    whyWrong: [
      'Kemer zorunluluğu yalnızca ön koltukla veya otoyolla sınırlı değildir.',
      'Şehir içi kısa mesafede de kemer takılmalıdır.',
    ],
    objective: 'Emniyet kemeri zorunluluğunun kapsamını bilmek.',
    tags: ['emniyet-kemeri', 'zorunluluk', 'guvenlik'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-132',
    subject: 'trafik',
    topic: 'emniyet-kemeri',
    difficulty: 'orta',
    stem: 'Emniyet kemerinin temel güvenlik işlevi nedir?',
    options: [
      'Çarpışma anında sürücü ve yolcunun ileri savrulmasını önlemek',
      'Yakıt tasarrufu sağlamak',
      'Direksiyon hakimiyetini artırmak',
      'Motoru aşırı ısınmadan korumak',
    ],
    answerIndex: 0,
    explanation:
      'Emniyet kemeri, çarpışma veya ani frende bedeni koltukta tutarak ileri savrulmayı, cama veya direksiyona çarpmayı önler ve yaralanma şiddetini azaltır.',
    whyWrong: [
      'Kemerin yakıt, motor veya direksiyon hakimiyetiyle ilgisi yoktur.',
      'İşlevi doğrudan can güvenliğini korumaktır.',
    ],
    objective: 'Emniyet kemerinin koruyucu işlevini bilmek.',
    tags: ['emniyet-kemeri', 'carpisma', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-133',
    subject: 'trafik',
    topic: 'donusler',
    difficulty: 'kolay',
    stem: 'Sağa dönüş yapacak sürücü dönüşten önce ne yapmalıdır?',
    options: [
      'Sol şeride geçmeli',
      'En sağ şeride yaklaşıp sağ sinyal vermeli',
      'Hızını artırmalı',
      'Geniş kavis için önce sola yönelmeli',
    ],
    answerIndex: 1,
    explanation:
      'Sağa dönecek sürücü önceden en sağ şeride yaklaşır, sağ sinyalini verir, hızını azaltır ve yolun sağ kenarını izleyerek dar bir kavisle döner.',
    whyWrong: [
      'Sola geçmek veya sola yönelmek sağ dönüşte hatalı ve tehlikelidir.',
      'Dönüş öncesi hız artırmak değil azaltmak gerekir.',
    ],
    objective: 'Sağa dönüş manevrasının doğru sırasını bilmek.',
    tags: ['donusler', 'saga-donus', 'sinyal'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-134',
    subject: 'trafik',
    topic: 'donusler',
    difficulty: 'orta',
    stem: 'İki yönlü bir yolda sola dönüş yapacak sürücü genel olarak ne yapar?',
    options: [
      'En sağ şeride yaklaşır',
      'Yolun/şeridin soluna yaklaşır, sinyal verir ve karşıdan gelen trafiğe yol verir',
      'Hiç sinyal vermeden döner',
      'Kavşakta durup geri manevra yapar',
    ],
    answerIndex: 1,
    explanation:
      'Sola dönecek sürücü önceden yolun soluna/sol şeride yaklaşır, sol sinyalini verir ve karşı yönden gelen araçlar ile geçiş hakkı olanlara yol verdikten sonra döner.',
    whyWrong: [
      'Sağ şeritten sola dönmek diğer şeritleri keser ve tehlikelidir.',
      'Sinyal vermeden dönmek diğer sürücüleri yanıltır.',
    ],
    objective: 'Sola dönüş manevrasını ve yol verme sırasını bilmek.',
    tags: ['donusler', 'sola-donus', 'yol-ver'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-135',
    subject: 'trafik',
    topic: 'otoyol',
    difficulty: 'orta',
    stem: 'Bir araç otoyola nasıl katılır?',
    options: [
      'Doğrudan seyir şeridine çıkarak',
      'Emniyet şeridinden yavaşça girerek',
      'Katılım noktasında durup bekleyerek',
      'Hızlanma şeridinde yeterli hıza ulaşıp uygun aralıkta katılarak',
    ],
    answerIndex: 3,
    explanation:
      'Otoyola giriş, hızlanma şeridinde akan trafiğin hızına yaklaşıp uygun bir boşluk bulunduğunda güvenle seyir şeridine katılarak yapılır.',
    whyWrong: [
      'Doğrudan seyir şeridine çıkmak veya durup beklemek arkadan çarpışmaya yol açar.',
      'Emniyet şeridi katılım için değil, acil durumlar içindir.',
    ],
    objective: 'Otoyola güvenli katılımı bilmek.',
    tags: ['otoyol', 'hizlanma-seridi', 'katilim'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-136',
    subject: 'trafik',
    topic: 'otoyol',
    difficulty: 'orta',
    stem: 'Otoyoldaki emniyet şeridi (banket) esas olarak ne amaçla kullanılır?',
    options: [
      'Normal seyir ve sollama için',
      'Yalnızca arıza, kaza ve acil durumlar için',
      'Daha hızlı gitmek için',
      'Serbestçe park etmek için',
    ],
    answerIndex: 1,
    explanation:
      'Emniyet şeridi yalnızca arıza, kaza ve acil durumlarda kullanılır; normal seyir, sollama veya trafiği geçmek amacıyla kullanılması yasaktır.',
    whyWrong: [
      'Emniyet şeridinde seyretmek veya sollamak ağır ihlaldir.',
      'Bu şerit park veya hız yapma amacıyla kullanılamaz.',
    ],
    objective: 'Emniyet şeridinin kullanım amacını bilmek.',
    tags: ['otoyol', 'emniyet-seridi', 'acil-durum'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-137',
    subject: 'trafik',
    topic: 'otoyol',
    difficulty: 'zor',
    stem: 'Otoyolda seyir hâlindeyken aracınız arızalanırsa öncelikli olarak ne yaparsınız?',
    options: [
      'Bulunduğunuz şeritte durup beklersiniz',
      'Aracı emniyet şeridine çekip dörtlüleri yakar ve reflektörü uygun mesafeye koyarsınız',
      'Geri geri en yakın çıkışa gidersiniz',
      'Aracı olduğu yerde bırakıp yola yürürsünüz',
    ],
    answerIndex: 1,
    explanation:
      'Arıza durumunda araç mümkün olduğunca emniyet şeridine alınır, dörtlü flaşörler yakılır ve arkadan gelenleri uyarmak için reflektör yeterli mesafeye yerleştirilir.',
    whyWrong: [
      'Seyir şeridinde durmak veya geri gitmek büyük kaza riski taşır.',
      'Aracı yol ortasında bırakıp yürümek trafiği ve canları tehlikeye atar.',
    ],
    objective: 'Otoyolda arıza durumunda doğru davranışı bilmek.',
    tags: ['otoyol', 'ariza', 'reflektor'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-138',
    subject: 'trafik',
    topic: 'alkol',
    difficulty: 'zor',
    stem: 'Hususi (özel) otomobil sürücüsü için kandaki yasal azami alkol sınırı kaç promildir?',
    options: ['0.00', '0.20', '0.80', '1.00', '0.50'],
    answerIndex: 4,
    explanation:
      'Hususi otomobil sürücüleri için yasal azami sınır 0.50 promildir; bu sınırın üzerinde araç kullanmak yasaktır ve idari yaptırım uygulanır.',
    whyWrong: [
      '0.80 ve 1.00 promil yasal sınırın üzerindedir.',
      'Ticari araç ve bazı sürücü gruplarında sınır 0.00 olsa da hususi otomobilde 0.50 uygulanır.',
    ],
    objective: 'Hususi otomobilde yasal alkol sınırını bilmek.',
    tags: ['alkol', 'yasal-sinir', 'promil'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-139',
    subject: 'trafik',
    topic: 'oncelik',
    difficulty: 'zor',
    stem: 'Sesli ve ışıklı uyarı cihazlarını çalıştırmış bir ambulans arkanızdan yaklaşırsa ne yaparsınız?',
    options: [
      'Hızlanıp ambulansın önünden gidersiniz',
      'Yavaşlayıp uygun şekilde yol verir, gerekirse durursunuz',
      'Bulunduğunuz yerde hiç hareket etmezsiniz',
      'Korna çalarak devam edersiniz',
    ],
    answerIndex: 1,
    explanation:
      'Sesli ve ışıklı uyarı veren ambulans geçiş üstünlüğüne sahiptir; sürücü yavaşlayıp yolu açar, gerekirse güvenli bir yerde durarak aracın geçmesini sağlar.',
    whyWrong: [
      'Ambulansın önünde gitmeye çalışmak geçişini engeller.',
      'Hiç hareket etmemek veya korna çalmak yol açma yükümlülüğünü yerine getirmez.',
    ],
    objective: 'Geçiş üstünlüğü olan araca yol verme kuralını bilmek.',
    tags: ['gecis-ustunlugu', 'ambulans', 'yol-ver'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-140',
    subject: 'trafik',
    topic: 'isik',
    difficulty: 'kolay',
    stem: 'Kavşakta kırmızı ışıkla karşılaşan sürücü ne yapmalıdır?',
    options: [
      'Dikkatli biçimde geçmeli',
      'Sağa dönerek devam etmeli',
      'Korna çalıp geçmeli',
      'Durma çizgisinin gerisinde durmalı',
    ],
    answerIndex: 3,
    explanation:
      'Kırmızı ışık dur anlamındadır; sürücü durma çizgisinin gerisinde durur ve ışık yeşile dönene kadar bekler.',
    whyWrong: [
      'Kırmızıda geçmek veya ayrı bir ok ışığı yokken sağa dönmek yasaktır.',
      'Korna çalmak geçiş hakkı sağlamaz.',
    ],
    objective: 'Kırmızı ışıkta durma kuralını bilmek.',
    tags: ['isik', 'kirmizi-isik', 'durma-cizgisi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
];
