/**
 * ÖZGÜN trafik ve çevre soruları — 7. genişletme (Program 2 · Faz 9). ROADMAP C.4/E.6.
 * Kaynak = resmî müfredat/mevzuat; KENDİ İFADEMİZLE.
 * Bu dalga: trafik işaretlerini TANIMA (tehlike/yasak/mecburiyet/bilgi/otoyol/yatay) + ÇEVRE ağırlıklı.
 */
import type { QuestionInput } from '@ea/content-schema';

const SRC = 'Karayolları Trafik Yönetmeliği + MEB müfredatı (özgün ifade)';

export const TRAFIK_QUESTIONS_7: QuestionInput[] = [
  {
    id: 'trafik-701',
    subject: 'trafik',
    topic: 'gevsek-malzeme-levhasi',
    difficulty: 'kolay',
    stem: 'Kenarları kırmızı üçgen bir levhada, tekerlekten sıçrayan taş taneleri sembolü (gevşek malzeme) bulunması sürücüye neyi bildirir?',
    options: [
      'Yol yüzeyinde tekerleklerin fırlatabileceği gevşek malzeme (mıcır) bulunduğunu; hızı azaltıp araya mesafe koyması gerektiğini',
      'İleride ücretsiz park yeri bulunduğunu',
      'Bu yolun tamamen trafiğe kapalı olduğunu',
      'Yolda yalnızca kamyonların geçebileceğini',
    ],
    answerIndex: 0,
    explanation:
      'Kırmızı kenarlı üçgen levhalar tehlike-uyarı işaretidir. Gevşek malzeme sembolü, kaplamada sabitlenmemiş taş ve çakıl bulunduğunu bildirir; yüksek hızda bu taneler tekerlekten fırlayıp araçlara zarar verebilir ve zemin kaygan olabilir. Sürücü hızını azaltıp öndeki araçla mesafeyi açar.',
    whyWrong: [
      'Park yeri, tehlike üçgeniyle değil mavi bilgi levhasıyla gösterilir.',
      'Yol kapalı bilgisi kırmızı yasak işaretiyle verilir.',
      'Araç türü kısıtı yasaklayıcı çember içinde belirtilir, üçgen uyarıda değil.',
    ],
    objective: 'Gevşek malzeme uyarı levhasını tanıyıp hız azaltmayı bilmek.',
    tags: ['levha', 'tehlike-uyari', 'gevsek-malzeme'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-702',
    subject: 'trafik',
    topic: 'dusen-kaya-levhasi',
    difficulty: 'kolay',
    stem: 'Kırmızı kenarlı üçgen bir levhada, bir yamaçtan yola doğru düşen kaya parçaları sembolü gören sürücü ne anlamalıdır?',
    options: [
      'İleride kamp alanı bulunduğunu',
      'Yamaçtan yola taş ve kaya düşebileceğini; dikkatli olup hızı azaltması gerektiğini',
      'Bu kesimde madencilik yapıldığı için geçişin yasak olduğunu',
      'Yolun bittiğini',
    ],
    answerIndex: 1,
    explanation:
      'Düşen kaya uyarı levhası, dik yamaç veya kaya yarması bulunan kesimlerde yola taş ve kaya parçalarının düşebileceğini bildirir. Sürücü hızını azaltmalı, yol yüzeyindeki parçalara karşı uyanık olmalı ve yamaç dibinde gereksiz yere durmamalıdır.',
    whyWrong: [
      'Kamp alanı bir hizmet-bilgi levhasıyla gösterilir, tehlike üçgeniyle değil.',
      'Geçiş yasağı kırmızı yasaklayıcı işaretle bildirilir.',
      'Yolun bitişi ayrı bir işaretle belirtilir; bu levha kaya düşmesi uyarısıdır.',
    ],
    objective: 'Düşen kaya uyarı levhasının anlamını bilmek.',
    tags: ['levha', 'tehlike-uyari', 'dusen-kaya'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-703',
    subject: 'trafik',
    topic: 'tunel-uyari-levhasi',
    difficulty: 'orta',
    stem: 'Kırmızı kenarlı üçgen bir levhada tünel sembolü bulunması sürücüye ileride tünel olduğunu bildirir. Bu uyarıyı gören sürücünün en doğru davranışı hangisidir?',
    options: [
      'Tünele girmeden farları söndürmek',
      'Tünel çıkışına kadar hızlanmak',
      'Kısa farları yakmak, güneş gözlüğünü çıkarmak ve hızını tünel koşullarına uygun ayarlamak',
      'Tünelde geri gitmeye hazırlanmak',
    ],
    answerIndex: 2,
    explanation:
      'Tünel uyarı levhası, kapalı ve az aydınlık bir kesime yaklaşıldığını bildirir. Sürücü tünele girmeden kısa farlarını yakar, takılıysa güneş gözlüğünü çıkarır ve gözünün karanlığa uyum süresini hesaba katarak hızını güvenli seviyeye çeker.',
    whyWrong: [
      'Tünelde far söndürmek görüşü ve görünürlüğü yok eder.',
      'Tünelde hızlanmak dar ve kapalı ortamda kaza riskini artırır.',
      'Tünelde geri gitmek yasaktır ve son derece tehlikelidir.',
    ],
    objective: 'Tünel uyarı levhasına karşı far yakma ve hız ayarını bilmek.',
    tags: ['levha', 'tehlike-uyari', 'tunel'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-704',
    subject: 'trafik',
    topic: 'deniz-kiyisi-levhasi',
    difficulty: 'zor',
    stem: 'Kırmızı kenarlı üçgen bir levhada, aracın suya doğru ilerlediğini gösteren "rıhtım veya su kıyısında biten yol" sembolü neyi uyarır?',
    options: [
      'İleride yüzme havuzu bulunduğunu',
      'Yolun bu kesimde genişlediğini',
      'Bu noktada balık satışı yapıldığını',
      'Yolun rıhtım, iskele veya su kıyısında son bulduğunu; dikkatsiz sürüşte araçla suya girme tehlikesi olduğunu',
    ],
    answerIndex: 3,
    explanation:
      'Bu tehlike-uyarı levhası, taşıt yolunun bir rıhtım, iskele ya da su kenarında sona erdiğini bildirir. Özellikle gece ve sisli havada su kenarı geç fark edilir; sürücü hızını iyice azaltıp durabilecek şekilde ilerlemeli, araçla suya girme tehlikesini göz önünde tutmalıdır.',
    whyWrong: [
      'Yüzme havuzu bir tesis bilgisidir; tehlike üçgeniyle gösterilmez.',
      'Yol genişlemesi bu sembolle değil, ilgili yol işaretiyle bildirilir.',
      'Levha ticari bir tanıtım değil, su kıyısı tehlikesine karşı uyarıdır.',
    ],
    objective: 'Su kıyısında biten yol uyarısını tanıyıp durma hazırlığı yapmak.',
    tags: ['levha', 'tehlike-uyari', 'rihtim', 'su-kiyisi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-705',
    subject: 'trafik',
    topic: 'alcak-ucus-levhasi',
    difficulty: 'orta',
    stem: 'Kırmızı kenarlı üçgen bir levhada alçaktan uçan uçak sembolü bulunması sürücüye neyi bildirir?',
    options: [
      'Yol yakınında havaalanı bulunduğunu ve alçaktan uçan uçakların ani ses ve gölgesiyle dikkatin dağılabileceğini',
      'Bu yolda uçak bileti satıldığını',
      'Yolun uçuş nedeniyle tamamen kapatıldığını',
      'İleride sadece motosikletlerin geçebileceğini',
    ],
    answerIndex: 0,
    explanation:
      'Alçak uçuş uyarı levhası, yolun yakınında bir havaalanı veya iniş-kalkış hattı bulunduğunu ve alçaktan geçen uçakların ani gürültüsü ile gölgesinin sürücünün dikkatini dağıtabileceğini bildirir. Sürücü hazırlıklı olmalı ve dikkatini yola vermelidir.',
    whyWrong: [
      'Levha ticari bir bilgi vermez; bir tehlike uyarısıdır.',
      'Yol kapatma bilgisi kırmızı yasak işaretiyle verilir.',
      'Araç türü kısıtı yasaklayıcı çemberle gösterilir, bu üçgenle değil.',
    ],
    objective: 'Alçak uçuş uyarı levhasının anlamını bilmek.',
    tags: ['levha', 'tehlike-uyari', 'alcak-ucus'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-706',
    subject: 'trafik',
    topic: 'hemzemin-bariyerli-levha',
    difficulty: 'orta',
    stem: 'Kırmızı kenarlı üçgen bir levhada bariyer (kapı/çit) sembolü, bariyerli bir demir yolu (hemzemin) geçidine yaklaşıldığını bildirir. Sürücünün doğru davranışı hangisidir?',
    options: [
      'Bariyer açıksa hiç yavaşlamadan hızla geçmek',
      'Hızını azaltıp geçide kontrollü yaklaşmak, bariyer kapalı veya kapanmak üzereyse durup beklemek',
      'Bariyer kapanırken hızlanıp altından geçmek',
      'Geçit üzerinde durup treni izlemek',
    ],
    answerIndex: 1,
    explanation:
      'Bariyerli hemzemin geçit uyarısı, ileride bekçili/bariyerli bir demir yolu kesişimi olduğunu bildirir. Sürücü hızını azaltıp kontrollü yaklaşır; bariyer kapalı veya kapanmak üzereyse durup tren geçişini bekler, geçit boşalıp bariyer açılınca ilerler.',
    whyWrong: [
      'Bariyer açık olsa da hızla geçmek, ani kapanma veya geçitte kalma riski doğurur.',
      'Kapanan bariyerin altından geçmeye çalışmak ölümcül bir ihlaldir.',
      'Geçit üzerinde durmak, tren gelmesi hâlinde felaketle sonuçlanır.',
    ],
    objective: 'Bariyerli hemzemin geçit uyarısında kontrollü yaklaşmayı bilmek.',
    tags: ['levha', 'hemzemin-gecit', 'bariyer'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-707',
    subject: 'trafik',
    topic: 'hemzemin-bariyersiz-levha',
    difficulty: 'kolay',
    stem: 'Kırmızı kenarlı üçgen bir levhada lokomotif (tren) sembolü bulunması sürücüye neyi bildirir?',
    options: [
      'İleride tren garı lokantası bulunduğunu',
      'Demir yolu taşımacılığının yasak olduğunu',
      'İleride bariyersiz (bekçisiz) bir demir yolu geçidi olduğunu; sürücünün yavaşlayıp iki tarafı kontrol etmesi gerektiğini',
      'Bu yolda hız sınırının kalktığını',
    ],
    answerIndex: 2,
    explanation:
      'Lokomotif sembollü uyarı levhası, ileride bariyeri ve bekçisi bulunmayan bir demir yolu geçidi olduğunu bildirir. Bu geçitlerde koruma olmadığı için sürücü hızını iyice azaltmalı, geçide yaklaşırken her iki yönü dikkatle kontrol edip tren gelmediğinden emin olduktan sonra geçmelidir.',
    whyWrong: [
      'Levha bir tesis tanıtımı değil, geçit tehlikesi uyarısıdır.',
      'Taşımacılık yasağı bu işaretle bildirilmez.',
      'Uyarı levhası hız sınırını belirlemez; aksine dikkat ve yavaşlama gerektirir.',
    ],
    objective: 'Bariyersiz hemzemin geçit uyarısını tanımak.',
    tags: ['levha', 'hemzemin-gecit', 'bariyersiz'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-708',
    subject: 'trafik',
    topic: 'iki-yonlu-trafik-levha',
    difficulty: 'orta',
    stem: 'Tek yönlü ilerlediği bir yolda sürücü, kırmızı kenarlı üçgen levhada yukarı-aşağı bakan iki ok (iki yönlü trafik) sembolünü gördü. Bu ne anlama gelir?',
    options: [
      'İleride yolun iki yönlü hâle geleceğini; karşıdan araç gelebileceği için sola geçmeden dikkatli olması gerektiğini',
      'Yolun çift katlı köprüye dönüştüğünü',
      'İleride yalnızca sağa dönülebileceğini',
      'Bu kesimde park etmenin serbest olduğunu',
    ],
    answerIndex: 0,
    explanation:
      'İki yönlü trafik uyarı levhası, o ana kadar tek yönlü olan yolun ileride karşılıklı iki yönlü akışa döneceğini bildirir. Sürücü, artık karşıdan araç gelebileceğini bilerek kendi şeridinde kalmalı, sollama ve sol şeride geçişte çok daha dikkatli davranmalıdır.',
    whyWrong: [
      'Levha bir köprü yapısını değil, trafik yönünün değiştiğini bildirir.',
      'Dönüş zorunluluğu mavi mecburi işaretle verilir, bu üçgenle değil.',
      'Park bilgisi bu tehlike uyarısıyla ilgili değildir.',
    ],
    objective: 'İki yönlü trafik uyarısını tanıyıp karşı yön riskini kavramak.',
    tags: ['levha', 'tehlike-uyari', 'iki-yonlu-trafik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-709',
    subject: 'trafik',
    topic: 'yol-daralmasi-levha',
    difficulty: 'kolay',
    stem: 'Kırmızı kenarlı üçgen bir levhada, yolun her iki kenardan içe doğru daraldığını gösteren sembol sürücüye neyi bildirir?',
    options: [
      'İleride yolun genişleyeceğini',
      'İleride taşıt yolunun daralacağını; hızı azaltıp şerit düzenine dikkat etmesi gerektiğini',
      'Bu kesimde iki şeridin ayrılacağını',
      'Yalnızca yayaların geçebileceğini',
    ],
    answerIndex: 1,
    explanation:
      'Yol daralması uyarı levhası, taşıt yolunun ileride daraldığını bildirir. Daralan kesimde araçlar birbirine yaklaşacağından sürücü hızını azaltmalı, şerit düzenine uymalı ve gerekirse karşıdan veya yandan gelene kolaylık göstererek geçmelidir.',
    whyWrong: [
      'Sembol daralmayı gösterir; genişleme değil.',
      'Şeritlerin ayrılması ayrı bir işaretle bildirilir.',
      'Yaya kısıtı bu tehlike üçgeniyle değil, ilgili işaretlerle verilir.',
    ],
    objective: 'Yol daralması uyarı levhasını tanıyıp hız azaltmayı bilmek.',
    tags: ['levha', 'tehlike-uyari', 'yol-daralmasi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-710',
    subject: 'trafik',
    topic: 'isikli-isaret-uyari-levha',
    difficulty: 'kolay',
    stem: 'Kırmızı kenarlı üçgen bir levhada trafik ışığı (üç renkli işaret cihazı) sembolü bulunması ne anlama gelir?',
    options: [
      'İleride ışıklı işaret cihazı (trafik lambası) bulunduğunu; sürücünün yavaşlayıp ışığın durumuna göre durmaya hazır olması gerektiğini',
      'Işıkların arızalı olduğunu',
      'Bu yolda ışıklara uyulmayabileceğini',
      'İleride elektrik santrali olduğunu',
    ],
    answerIndex: 0,
    explanation:
      'Işıklı işaret cihazı uyarı levhası, sürücünün henüz göremediği bir noktada trafik lambası bulunduğunu önceden bildirir. Böylece sürücü yavaşlar ve ışık kırmızıya döndüğünde durabilecek hıza iner; ani frenle yakalanmaz.',
    whyWrong: [
      'Levha arıza bilgisi vermez; cihazın varlığını haber verir.',
      'Işıklara uymama diye bir izin yoktur; aksine hazırlıklı olmak gerekir.',
      'Levha bir tesis değil, trafik lambasını haber verir.',
    ],
    objective: 'Işıklı işaret cihazı uyarı levhasını tanımak.',
    tags: ['levha', 'tehlike-uyari', 'isikli-isaret'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-711',
    subject: 'trafik',
    topic: 'donel-kavsak-uyari-levha',
    difficulty: 'zor',
    stem: 'Kırmızı kenarlı üçgen levhadaki dairesel ok düzeni (dönel kavşak uyarısı) ile mavi zeminli daire içinde dönen oklar (ada etrafında dönünüz) işareti arasındaki temel fark nedir?',
    options: [
      'İkisi de aynı anlama gelir ve birbirinin yerine kullanılır',
      'Üçgen levha ileride dönel kavşak olduğunu haber veren uyarıdır; mavi daireli işaret ise adanın etrafından hangi yönde dönüleceğini gösteren mecburiyet işaretidir',
      'Üçgen levha park yeri, mavi işaret benzin istasyonu gösterir',
      'Üçgen levha dönüşü yasaklar, mavi işaret dönüşe izin verir',
    ],
    answerIndex: 1,
    explanation:
      'Kırmızı kenarlı üçgen, tehlike-uyarı grubundandır ve ileride bir dönel kavşak (ada) bulunduğunu önceden haber verir. Mavi zeminli daire ise mecburiyet grubundandır ve ada çevresinde hangi yönde dönüleceğini bildirir. Renk ve şekil, işaretin görevini belirler.',
    whyWrong: [
      'İki işaret farklı gruptandır; anlamları ve görevleri aynı değildir.',
      'Hiçbiri park veya benzin bilgisi vermez.',
      'Üçgen levha dönüşü yasaklamaz; yalnızca kavşağı haber verir.',
    ],
    objective: 'Dönel kavşak uyarısı ile ada etrafında dönünüz işaretini ayırt etmek.',
    tags: ['levha', 'donel-kavsak', 'tehlike-uyari', 'mecburiyet'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-712',
    subject: 'trafik',
    topic: 'kontrolsuz-kavsak-levha',
    difficulty: 'zor',
    stem: 'Ana yolda ilerlerken kırmızı kenarlı üçgen bir levhada, yana bağlanan tali yolu gösteren kavşak sembolü (kontrolsüz kavşak) gördünüz. Bu uyarıya karşı en doğru davranış hangisidir?',
    options: [
      'Ana yolda olduğum için hız kesmeden geçmek',
      'Korna çalıp tali yoldakilerin durmasını beklemek',
      'Hızı azaltıp tali yoldan çıkabilecek araçları kollamak; öncelik bende olsa da tedbiri elden bırakmamak',
      'Tali yola girmek için hemen sağa yönelmek',
    ],
    answerIndex: 2,
    explanation:
      'Kontrolsüz kavşak uyarısı, ışık veya görevliyle düzenlenmemiş bir kesişime yaklaşıldığını bildirir. Ana yolda öncelik sizde olsa bile, tali yoldan kural tanımadan çıkabilecek bir araç olabilir; bu yüzden hızı azaltıp yan yolları kollamak, savunmacı sürüşün gereğidir.',
    whyWrong: [
      'Önceliğe güvenip hız kesmemek, kural tanımayan bir araçla çarpışma doğurabilir.',
      'Korna, yan yoldan çıkanı durduracağının garantisi değildir.',
      'Levha tali yola girmeyi emretmez; yaklaşan kavşağı haber verir.',
    ],
    objective: 'Kontrolsüz kavşak uyarısında öncelikli olsa da tedbiri sürdürmek.',
    tags: ['levha', 'tehlike-uyari', 'kavsak', 'savunmaci-surus'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-713',
    subject: 'trafik',
    topic: 'kamyon-giremez-levha',
    difficulty: 'kolay',
    stem: 'Beyaz zeminli, kırmızı çember içinde bir kamyon sembolü bulunan işaret sürücüye neyi bildirir?',
    options: [
      'O yola kamyonların (yük taşıtlarının) girmesinin yasak olduğunu',
      'İleride kamyon garajı bulunduğunu',
      'Yalnızca kamyonların geçebileceğini',
      'Kamyonların park edebileceği yeri',
    ],
    answerIndex: 0,
    explanation:
      'Kırmızı çember içine alınmış semboller yasaklama bildirir. İçinde kamyon bulunan bu işaret, belirtilen yola kamyon sınıfı yük taşıtlarının girmesinin yasak olduğunu gösterir; genellikle dar, eğimli veya yerleşim içi yollarda kullanılır.',
    whyWrong: [
      'Garaj bilgisi mavi bilgi levhasıyla verilir.',
      'Kırmızı çember izin değil, yasak anlamı taşır.',
      'Park yeri bilgisi P işaretiyle gösterilir.',
    ],
    objective: 'Kamyon giremez yasak işaretini tanımak.',
    tags: ['levha', 'yasaklayici', 'kamyon'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-714',
    subject: 'trafik',
    topic: 'motosiklet-giremez-levha',
    difficulty: 'kolay',
    stem: 'Kırmızı çember içinde bir motosiklet sembolü bulunan işaret neyi ifade eder?',
    options: [
      'Motosikletlerin park yerini',
      'O yola motosikletlerin girmesinin yasak olduğunu',
      'Yalnızca motosikletlerin geçebileceğini',
      'İleride motosiklet tamircisi bulunduğunu',
    ],
    answerIndex: 1,
    explanation:
      'Kırmızı çember içindeki motosiklet sembolü, o yola motosikletlerin girişinin yasaklandığını bildirir. Yasaklayıcı işaretler, belirtilen araç türünün o kesimde ilerlemesine izin vermez.',
    whyWrong: [
      'Park yeri bilgisi bu yasak işaretiyle verilmez.',
      'Kırmızı çember izin değil, yasak anlamındadır.',
      'Tamir yeri bilgisi mavi bilgi levhasıyla gösterilir.',
    ],
    objective: 'Motosiklet giremez yasak işaretini tanımak.',
    tags: ['levha', 'yasaklayici', 'motosiklet'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-715',
    subject: 'trafik',
    topic: 'traktor-giremez-levha',
    difficulty: 'orta',
    stem: 'Kırmızı çember içinde lastik tekerlekli traktör sembolü bulunan işaretin bulunduğu yol için hangisi doğrudur?',
    options: [
      'Bu yolda yalnızca traktörler ilerleyebilir',
      'Traktörler bu yola giremez; genellikle hızlı ve yoğun trafiğin olduğu yollarda kullanılır',
      'Traktörler bu yolda park edebilir',
      'İleride tarım fuarı bulunmaktadır',
    ],
    answerIndex: 1,
    explanation:
      'Kırmızı çember içindeki lastik tekerlekli traktör sembolü, bu araçların o yola girmesinin yasak olduğunu bildirir. Çok yavaş olan traktörler, hızlı akan yollarda büyük hız farkı ve tehlike yarattığından bu tür kesimlere alınmaz.',
    whyWrong: [
      'İşaret izin değil yasak bildirir; yalnızca traktör geçer demek yanlıştır.',
      'Park bilgisi bu işaretle verilmez.',
      'Fuar gibi etkinlik bilgisi trafik yasak işaretiyle gösterilmez.',
    ],
    objective: 'Lastik tekerlekli traktör giremez işaretini tanımak.',
    tags: ['levha', 'yasaklayici', 'traktor'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-716',
    subject: 'trafik',
    topic: 'at-arabasi-giremez-levha',
    difficulty: 'orta',
    stem: 'Kırmızı çember içinde hayvanla (at ile) çekilen bir araba sembolü bulunan işaret neyi bildirir?',
    options: [
      'Bu yolda ata binmenin serbest olduğunu',
      'İleride hayvan pazarı bulunduğunu',
      'Bütün araçların bu yolda çok yavaş gitmesi gerektiğini',
      'Hayvanla çekilen taşıtların (at arabası, fayton vb.) bu yola girmesinin yasak olduğunu',
    ],
    answerIndex: 3,
    explanation:
      'Kırmızı çember içindeki hayvanla çekilen araç sembolü, at arabası ve benzeri taşıtların o yola girişinin yasak olduğunu bildirir. Çok yavaş ilerleyen bu taşıtlar, hızlı akan yollarda hız farkı ve engel oluşturduğundan bu kesimlere alınmaz.',
    whyWrong: [
      'İşaret hayvanla çekilen taşıtı yasaklar; ata binmeyle ilgili bir izin vermez.',
      'Pazar gibi etkinlik bilgisi bu yasak işaretiyle verilmez.',
      'Yasak, tüm araçların hızıyla değil, belirli taşıt türüyle ilgilidir.',
    ],
    objective: 'Hayvanla çekilen taşıt giremez işaretini tanımak.',
    tags: ['levha', 'yasaklayici', 'at-arabasi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-717',
    subject: 'trafik',
    topic: 'azami-agirlik-levha',
    difficulty: 'zor',
    stem: 'Kırmızı çember içinde "10 t" yazan azami ağırlık levhasının bulunduğu bir köprüye yaklaşan sürücü için hangisi doğrudur?',
    options: [
      'Levha yalnızca yükü ağır kamyonları bağlar, diğerlerini ilgilendirmez',
      'Yüklü hâliyle toplam ağırlığı 10 tonu aşan araç bu köprüden geçemez',
      'Hız düşürülürse ağır araç da geçebilir',
      'Levhadaki değer aracın uzunluğunu gösterir',
    ],
    answerIndex: 1,
    explanation:
      'Azami ağırlık işareti, yolun veya köprünün taşıyabileceği en yüksek toplam ağırlığı bildirir. Aracın yüküyle birlikte toplam ağırlığı bu değeri aşıyorsa geçiş yapamaz; zorlaması köprünün taşıma sınırını aşarak yapıya ve can güvenliğine ciddi tehlike oluşturur.',
    whyWrong: [
      'Sınır, ağırlığı aşan her aracı bağlar; belirli bir kamyon türüyle sınırlı değildir.',
      'Hız düşürmek aracın fiziksel ağırlığını azaltmaz.',
      'Değer ağırlık sınırıdır; uzunluk veya başka bir ölçü değildir.',
    ],
    objective: 'Azami ağırlık işaretini ve yüklü toplam ağırlıkla ilişkisini bilmek.',
    tags: ['levha', 'yasaklayici', 'azami-agirlik'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-718',
    subject: 'trafik',
    topic: 'azami-genislik-levha',
    difficulty: 'orta',
    stem: 'Kırmızı çember içinde birbirine bakan iki ok ile "2 m" değeri yazan azami genişlik levhası neyi bildirir?',
    options: [
      'Yolun 2 metre uzunluğunda olduğunu',
      'Hız sınırının 2 km/saat olduğunu',
      'Yükü ile birlikte genişliği 2 metreyi aşan araçların bu kesimden geçemeyeceğini',
      'Şeridin 2 metre sağa kaydığını',
    ],
    answerIndex: 2,
    explanation:
      'Azami genişlik işareti, dar geçit, tünel veya köprü ağzı gibi kesimlerden geçebilecek en fazla araç genişliğini bildirir. Aracın kendisi veya yükü bu değerden geniş ise oradan geçemez; zorlaması yapıya ve karşı trafiğe tehlike oluşturur.',
    whyWrong: [
      'Değer yol uzunluğu değil, genişlik sınırıdır.',
      'İşaret hız değil, genişlik sınırı bildirir.',
      'Şerit kayması bu işaretle değil, yatay işaretleme ve yönlendirmeyle gösterilir.',
    ],
    objective: 'Azami genişlik işaretinin anlamını bilmek.',
    tags: ['levha', 'yasaklayici', 'azami-genislik'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-719',
    subject: 'trafik',
    topic: 'u-donusu-yasak-levha',
    difficulty: 'orta',
    stem: 'Kırmızı çember içinde, üzeri kırmızı çizgiyle çizilmiş U biçiminde bir ok bulunan işaretin bulunduğu yerde sürücü ne yapamaz?',
    options: [
      'Sağa dönemez',
      'Öndeki aracı geçemez',
      'U dönüşü (geri dönüş) yaparak karşı yöne geçemez',
      'Şerit değiştiremez',
    ],
    answerIndex: 2,
    explanation:
      'Üzeri çizili U biçimindeki ok, o noktada U dönüşünün yasak olduğunu bildirir. İşaretin bulunduğu kesimde araç, geri dönüş yaparak karşı yöne geçemez; dönüşe izin verilen başka bir noktaya kadar ilerlemek zorundadır.',
    whyWrong: [
      'Sağa dönüş yasağı ayrı bir işaretle (sağa dönülmez) gösterilir.',
      'Geçme yasağı, iki taşıt sembollü ayrı bir işaretle bildirilir.',
      'Şerit değiştirme yasağı bu işaretin konusu değildir.',
    ],
    objective: 'U dönüşü yasak işaretinin anlamını bilmek.',
    tags: ['levha', 'yasaklayici', 'u-donusu'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-720',
    subject: 'trafik',
    topic: 'tasit-giremez-levha',
    difficulty: 'zor',
    stem: 'İçi tümüyle boş, kenarı kırmızı bir daire biçimindeki (taşıt trafiğine kapalı) işareti gören sürücü için hangisi doğrudur?',
    options: [
      'Yol yalnızca kamyonlara kapalıdır',
      'Yol yalnızca gece kapalıdır',
      'Yalnızca yayaların girmesi yasaktır',
      'Bu yola bütün taşıtların girmesi yasaktır; sürücü o yola giremez',
    ],
    answerIndex: 3,
    explanation:
      'Kenarı kırmızı, içi boş daire biçimindeki işaret, o yola bütün taşıtların girişinin yasak olduğunu bildirir. Belirli bir araç türü değil, genel olarak taşıt trafiği kapatılmıştır; sürücü bu yola giremez.',
    whyWrong: [
      'Yasak belirli bir araç türüyle sınırlı değil, tüm taşıtları kapsar.',
      'İşaret gece-gündüz ayrımı yapmaz; süreklidir.',
      'Yasak yayalara değil, taşıtlara yöneliktir.',
    ],
    objective: 'Taşıt trafiğine kapalı yol işaretini tanımak.',
    tags: ['levha', 'yasaklayici', 'tasit-giremez'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-721',
    subject: 'trafik',
    topic: 'bisiklet-giremez-levha',
    difficulty: 'kolay',
    stem: 'Kırmızı çember içinde bir bisiklet sembolü bulunan işaret neyi bildirir?',
    options: [
      'O yola bisikletlerin girmesinin yasak olduğunu',
      'Bu yolun yalnızca bisikletlere ayrıldığını',
      'İleride bisiklet kiralama noktası bulunduğunu',
      'Bisikletlilerin park edebileceği yeri',
    ],
    answerIndex: 0,
    explanation:
      'Kırmızı çember içindeki bisiklet sembolü, o yola bisiklet girmesinin yasak olduğunu bildirir. Bisiklete ayrılmış yol ise mavi zeminli mecburi işaretle gösterilir; renk ve zemin, işaretin yasak mı yoksa mecburiyet mi olduğunu belirler.',
    whyWrong: [
      'Bisiklete ayrılmış yol mavi mecburi işaretle gösterilir, bu kırmızı yasakla değil.',
      'Kiralama noktası bir bilgi levhasıyla belirtilir.',
      'Park yeri bilgisi bu yasak işaretiyle verilmez.',
    ],
    objective: 'Bisiklet giremez yasak işaretini tanımak.',
    tags: ['levha', 'yasaklayici', 'bisiklet'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-722',
    subject: 'trafik',
    topic: 'yaya-giremez-levha',
    difficulty: 'kolay',
    stem: 'Kırmızı çember içinde yürüyen bir yaya sembolü bulunan işaret neyi ifade eder?',
    options: [
      'İleride yaya geçidi bulunduğunu',
      'Bu yola yayaların girmesinin yasak olduğunu',
      'Bu yolun yalnızca yayalara ayrıldığını',
      'Yayaların koşmaması gerektiğini',
    ],
    answerIndex: 1,
    explanation:
      'Kırmızı çember içindeki yaya sembolü, yayaların o yola girmesinin yasak olduğunu bildirir. Örneğin otoyol bağlantıları gibi hızlı ve tehlikeli kesimlerde yaya geçişi bu işaretle engellenir.',
    whyWrong: [
      'Yaya geçidi ayrı bir bilgi/işaretle gösterilir.',
      'Yalnızca yayalara ayrılmış yol mavi mecburi işaretle belirtilir.',
      'İşaret koşma-yürüme ayrımı yapmaz; girişi tümüyle yasaklar.',
    ],
    objective: 'Yaya giremez yasak işaretini tanımak.',
    tags: ['levha', 'yasaklayici', 'yaya'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-723',
    subject: 'trafik',
    topic: 'saga-donulmez-levha',
    difficulty: 'orta',
    stem: 'Kırmızı çember içinde, sağa dönen bir okun üzeri kırmızı çizgiyle çizilmiş işaret sürücüye neyi bildirir?',
    options: [
      'Sağa dönüşün zorunlu olduğunu',
      'İleride sağda park yeri bulunduğunu',
      'Bu kavşakta sağa dönüşün yasak olduğunu',
      'Sağdan gidilmesi gerektiğini',
    ],
    answerIndex: 2,
    explanation:
      'Üzeri çizili sağa dönüş oku, o kavşakta sağa dönmenin yasak olduğunu bildirir. Sürücü sağa yönelemez; yoluna devam eder veya izin verilen bir başka yönü kullanır.',
    whyWrong: [
      'Dönüş zorunluluğu mavi mecburi işaretle gösterilir, üzeri çizili kırmızı işaretle değil.',
      'Park bilgisi bu işaretle verilmez.',
      'Sağdan gidiniz talimatı mavi mecburi işaretle bildirilir.',
    ],
    objective: 'Sağa dönülmez yasak işaretini tanımak.',
    tags: ['levha', 'yasaklayici', 'donus-yasagi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-724',
    subject: 'trafik',
    topic: 'korna-yasak-levha',
    difficulty: 'orta',
    stem: 'Kırmızı çember içinde, üzeri çizili bir korna (sesli ikaz cihazı) sembolü bulunan işaret neyi bildirir ve bu aynı zamanda hangi çevre sorununu önlemeye yöneliktir?',
    options: [
      'Sesli ikaz cihazı (korna) çalmanın yasak olduğunu; gürültü kirliliğini önlemeye yönelik olduğunu',
      'Radyonun kapatılması gerektiğini',
      'Bu yolda müzik yayını yapıldığını',
      'Kornanın sürekli çalınması gerektiğini',
    ],
    answerIndex: 0,
    explanation:
      'Üzeri çizili korna sembolü, o kesimde sesli ikaz cihazı çalmanın yasak olduğunu bildirir. Genellikle hastane, okul ve yerleşim çevresi gibi yerlerde konulur; hem trafik düzenini hem de gürültü kirliliğine karşı çevre ve insan sağlığını korumayı amaçlar.',
    whyWrong: [
      'İşaret radyo veya müzik cihazıyla değil, korna kullanımıyla ilgilidir.',
      'Levha bir yayın bilgisi değildir.',
      'İşaret kornayı yasaklar; sürekli çalmayı emretmez.',
    ],
    objective: 'Korna çalmak yasak işaretini tanıyıp gürültü kirliliğiyle ilişkilendirmek.',
    tags: ['levha', 'yasaklayici', 'korna', 'gurultu-kirliligi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-725',
    subject: 'trafik',
    topic: 'saga-mecburi-levha',
    difficulty: 'kolay',
    stem: 'Mavi zemin üzerinde sağı gösteren beyaz bir ok bulunan daire biçimindeki işaret sürücüye neyi bildirir?',
    options: [
      'Sürücünün sağa dönmesinin zorunlu olduğunu',
      'Sağa dönüşün yasak olduğunu',
      'İleride sağda tehlike bulunduğunu',
      'Sağda park yeri bulunduğunu',
    ],
    answerIndex: 0,
    explanation:
      'Mavi zeminli daire içindeki oklar mecburi yönü gösterir. Sağı gösteren ok, sürücünün o noktada sağa dönmesinin zorunlu olduğunu bildirir; başka yön seçilemez.',
    whyWrong: [
      'Dönüş yasağı kırmızı çemberli, üzeri çizili işaretle gösterilir.',
      'Tehlike uyarısı kırmızı kenarlı üçgenle verilir.',
      'Park yeri bilgisi P işaretiyle bildirilir.',
    ],
    objective: 'Sağa mecburi yön işaretini tanımak.',
    tags: ['levha', 'mecburiyet', 'saga-mecburi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-726',
    subject: 'trafik',
    topic: 'sola-mecburi-levha',
    difficulty: 'kolay',
    stem: 'Mavi zeminli daire içinde sola bakan beyaz bir ok bulunan işaret ne anlama gelir?',
    options: [
      'Sola dönüşün yasak olduğunu',
      'Sürücünün sola dönmesinin zorunlu olduğunu',
      'Solda otopark bulunduğunu',
      'İleride keskin sol viraj olduğunu',
    ],
    answerIndex: 1,
    explanation:
      'Mavi zeminli, sola bakan ok işareti mecburi yön grubundandır ve sürücünün o noktada sola dönmesi gerektiğini bildirir. Mecburi yön işaretleri, kavşakta hangi yönde ilerleneceğini bağlayıcı olarak belirler.',
    whyWrong: [
      'Sola dönüş yasağı kırmızı çemberli üzeri çizili işaretle gösterilir.',
      'Otopark bilgisi P işaretiyle verilir.',
      'Keskin viraj uyarısı kırmızı kenarlı üçgenle bildirilir.',
    ],
    objective: 'Sola mecburi yön işaretini tanımak.',
    tags: ['levha', 'mecburiyet', 'sola-mecburi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-727',
    subject: 'trafik',
    topic: 'sagdan-gidiniz-levha',
    difficulty: 'orta',
    stem: 'Mavi zeminli daire içinde, bir engelin sağından geçmeyi gösteren aşağı-sağa yönelmiş beyaz ok (sağdan gidiniz) işareti sürücüye neyi bildirir?',
    options: [
      'İleride sağa dönülmesi gerektiğini',
      'Önündeki refüj, ada veya engelin sağ tarafından geçmesi gerektiğini',
      'Sağ şeridin kapalı olduğunu',
      'Sağda tehlike bulunduğunu',
    ],
    answerIndex: 1,
    explanation:
      'Sağdan gidiniz işareti, önde bir refüj, ada, ağaçlık ya da yol çalışması gibi bir engel bulunduğunda sürücünün bu engelin sağ tarafından geçmesi gerektiğini bildiren mecburiyet işaretidir. Amaç, akışı doğru tarafa yönlendirip karşı yöne geçişi önlemektir.',
    whyWrong: [
      'İşaret kavşakta dönüş değil, engelin hangi yandan geçileceğini belirtir.',
      'Şerit kapanması ayrı işaret ve yönlendirmelerle gösterilir.',
      'Tehlike uyarısı kırmızı kenarlı üçgenle verilir.',
    ],
    objective: 'Sağdan gidiniz mecburiyet işaretini tanımak.',
    tags: ['levha', 'mecburiyet', 'sagdan-gidiniz'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-728',
    subject: 'trafik',
    topic: 'asgari-hiz-levha',
    difficulty: 'zor',
    stem: 'Mavi zeminli daire içinde beyaz renkle "60" yazan mecburi asgari hız levhasının bulunduğu kesim için hangisi doğrudur?',
    options: [
      'Bu kesimde 60 km/saat üstüne çıkmak yasaktır',
      'Levha yalnızca kamyonlar içindir',
      'Yol ve trafik uygunsa sürücü en az 60 km/saat hızla gitmelidir; bu hızın çok altında giderek akışı engelleyemez',
      'Bu kesimde durmak zorunludur',
    ],
    answerIndex: 2,
    explanation:
      'Mavi zeminli asgari hız işareti, o kesimde belirtilen değerin altına düşmemeyi bildiren bir mecburiyet işaretidir. Sürücü, yol ve trafik durumu elverdiği sürece en az bu hızda gitmeli; çok yavaş sürerek arkadan gelenlere engel olup tehlike yaratmamalıdır.',
    whyWrong: [
      'Bu bir azami hız sınırı değildir; alt sınır bildirir.',
      'Kural belirli bir araç türüne değil, o kesimdeki tüm uygun araçlara yöneliktir.',
      'İşaret durmayı değil, belirli bir hızın altına düşmemeyi emreder.',
    ],
    objective: 'Mecburi asgari hız işaretini azami hız sınırından ayırt etmek.',
    tags: ['levha', 'mecburiyet', 'asgari-hiz'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-729',
    subject: 'trafik',
    topic: 'zincir-mecburi-levha',
    difficulty: 'orta',
    stem: 'Mavi zeminli daire içinde, üzerine zincir takılmış bir tekerlek sembolü bulunan işaret neyi bildirir?',
    options: [
      'Bu kesimden geçen araçlarda kar zinciri takılı olmasının zorunlu olduğunu',
      'Zincirli araçların bu yola giremeyeceğini',
      'İleride lastik tamircisi bulunduğunu',
      'Aracın çekileceğini',
    ],
    answerIndex: 0,
    explanation:
      'Mavi zeminli zincirli tekerlek işareti, karlı ve buzlu geçitlerde araçlarda kar zinciri kullanmanın zorunlu olduğunu bildiren bir mecburiyet işaretidir. Zincir, kaygan zeminde tekerleğin tutuşunu artırarak kaymayı önler.',
    whyWrong: [
      'İşaret zinciri yasaklamaz; aksine zorunlu kılar.',
      'Tamir yeri bilgisi mavi bilgi levhasıyla verilir.',
      'Aracın çekilmesiyle ilgili bir bilgi vermez.',
    ],
    objective: 'Kar zinciri takmak mecburidir işaretini tanımak.',
    tags: ['levha', 'mecburiyet', 'kar-zinciri'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-730',
    subject: 'trafik',
    topic: 'ada-etrafinda-donunuz-levha',
    difficulty: 'orta',
    stem: 'Mavi zeminli daire içinde, bir ada çevresinde dönen oklar bulunan "ada etrafında dönünüz" işareti sürücüye neyi bildirir?',
    options: [
      'Adanın etrafında dönmenin yasak olduğunu',
      'Ortadaki adanın çevresinde, okların gösterdiği yönde dönerek ilerlenmesi gerektiğini',
      'Bu noktada geri dönüş yapılamayacağını',
      'İleride park adası bulunduğunu',
    ],
    answerIndex: 1,
    explanation:
      'Bu mecburiyet işareti, dönel kavşakta ortadaki adanın çevresinde okların gösterdiği yönde dönülerek ilerleneceğini bildirir. Sürücü ada etrafında ters yönde ilerleyemez; belirtilen yöne uymak zorundadır.',
    whyWrong: [
      'İşaret dönmeyi yasaklamaz; belirli yönde dönmeyi emreder.',
      'Geri dönüş yasağı ayrı bir kırmızı yasak işaretiyle gösterilir.',
      'Park adası bilgisi bu mecburiyet işaretiyle verilmez.',
    ],
    objective: 'Ada etrafında dönünüz mecburiyet işaretini tanımak.',
    tags: ['levha', 'mecburiyet', 'donel-kavsak'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-731',
    subject: 'trafik',
    topic: 'ileri-saga-mecburi-levha',
    difficulty: 'orta',
    stem: 'Mavi zeminli daire içinde biri ileri, biri sağa bakan iki beyaz ok bulunan işaret sürücüye ne yapmasını emreder?',
    options: [
      'Yalnızca geri dönmesini',
      'Yalnızca sola dönmesini',
      'İleri gitmek ile sağa dönmekten birini seçmesini; bu iki yön dışında hareket edememesini',
      'Kavşakta durup beklemesini',
    ],
    answerIndex: 2,
    explanation:
      'İleri ve sağa bakan iki oklu mecburi yön işareti, sürücünün ya ileri gidebileceğini ya da sağa dönebileceğini bildirir. Sola dönüş ve geri dönüş bu işaretle yasaklanmış olur; sürücü izin verilen iki yönden birini seçer.',
    whyWrong: [
      'Geri dönüş bu işaretin izin vermediği hareketlerdendir.',
      'Sola dönüş de bu işaretle yasaklanmıştır.',
      'İşaret durmayı değil, gösterilen yönlerde ilerlemeyi emreder.',
    ],
    objective: 'İleri ve sağa mecburi yön işaretini tanımak.',
    tags: ['levha', 'mecburiyet', 'ileri-saga'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-732',
    subject: 'trafik',
    topic: 'mecburi-bisiklet-yolu-levha',
    difficulty: 'kolay',
    stem: 'Mavi zeminli daire içinde beyaz bir bisiklet sembolü bulunan işaret neyi bildirir?',
    options: [
      'Bu yolun bisiklet trafiğine ayrıldığını (mecburi bisiklet yolu)',
      'Bisikletlerin bu yola giremeyeceğini',
      'İleride bisiklet yarışı olduğunu',
      'Bisiklet park yerini',
    ],
    answerIndex: 0,
    explanation:
      'Mavi zeminli daire içindeki bisiklet sembolü mecburiyet grubundandır ve o yolun bisikletlere ayrıldığını bildirir. Kırmızı çember içindeki aynı sembol ise tersini, yani bisiklet girişinin yasak olduğunu gösterir; işaretin rengi anlamı belirler.',
    whyWrong: [
      'Bisiklet girişi yasağı kırmızı çemberli işaretle gösterilir.',
      'Yarış gibi etkinlik bilgisi trafik işaretiyle verilmez.',
      'Park yeri bilgisi bu mecburiyet işaretiyle bildirilmez.',
    ],
    objective: 'Mecburi bisiklet yolu işaretini yasak işaretinden ayırmak.',
    tags: ['levha', 'mecburiyet', 'bisiklet-yolu'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-733',
    subject: 'trafik',
    topic: 'mecburi-yaya-yolu-levha',
    difficulty: 'kolay',
    stem: 'Mavi zeminli daire içinde yürüyen bir yaya sembolü bulunan işaret ne anlama gelir?',
    options: [
      'Bu yolun yayalara ayrıldığını (mecburi yaya yolu)',
      'Yayaların bu yola giremeyeceğini',
      'Yayaların koşması gerektiğini',
      'İleride yaya geçidi bulunmadığını',
    ],
    answerIndex: 0,
    explanation:
      'Mavi zeminli daire içindeki yaya sembolü, o yolun yaya trafiğine ayrıldığını bildiren bir mecburiyet işaretidir. Aynı sembolün kırmızı çember içinde bulunması ise yaya girişinin yasak olduğu anlamına gelir.',
    whyWrong: [
      'Yaya girişi yasağı kırmızı çemberli işaretle gösterilir.',
      'İşaret koşma-yürüme ayrımı yapmaz; yolu yayalara ayırır.',
      'Yaya geçidiyle ilgili olumsuz bir bilgi vermez.',
    ],
    objective: 'Mecburi yaya yolu işaretini tanımak.',
    tags: ['levha', 'mecburiyet', 'yaya-yolu'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-734',
    subject: 'trafik',
    topic: 'hastane-bilgi-levha',
    difficulty: 'kolay',
    stem: 'Mavi zemin üzerine beyaz "H" harfi ve sağlık sembolü bulunan bilgi işareti sürücüye neyi tanıtır?',
    options: [
      'İleride otel bulunduğunu',
      'İleride hastane bulunduğunu',
      'Bu kesimde korna çalmanın yasak olduğunu',
      'Yolun kapalı olduğunu',
    ],
    answerIndex: 1,
    explanation:
      'Mavi zeminli bilgi işaretleri sürücüye hizmet ve tesisleri tanıtır. Beyaz "H" harfli bu işaret, yakında bir hastane bulunduğunu bildirir; acil durumda yön bulmayı kolaylaştırır. Hastane çevresinde ayrıca gürültüye karşı dikkatli olunmalıdır.',
    whyWrong: [
      'Otel bilgisi yatak sembollü ayrı bir işaretle verilir.',
      'Korna yasağı kırmızı çemberli üzeri çizili işaretle gösterilir.',
      'Yol kapalı bilgisi bir bilgi işareti değil, yasak işaretidir.',
    ],
    objective: 'Hastane bilgi işaretini tanımak.',
    tags: ['levha', 'bilgi-isareti', 'hastane'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-735',
    subject: 'trafik',
    topic: 'ilk-yardim-bilgi-levha',
    difficulty: 'kolay',
    stem: 'Beyaz zemin üzerine kırmızı bir haç (artı) sembolü bulunan bilgi işareti neyi tanıtır?',
    options: [
      'İleride akaryakıt istasyonu bulunduğunu',
      'Kan bağışı yasağını',
      'İleride ilk yardım (sağlık) hizmeti verilen bir yer bulunduğunu',
      'Yolun buzlu olduğunu',
    ],
    answerIndex: 2,
    explanation:
      'Kırmızı haç sembollü bilgi işareti, yakında ilk yardım hizmeti verilen bir yer bulunduğunu tanıtır. Kaza veya sağlık sorununda hızlı yardım almaya yönlendiren bir işarettir.',
    whyWrong: [
      'Akaryakıt bilgisi pompa sembollü ayrı bir işaretle verilir.',
      'İşaret bir yasak bildirmez; bir hizmeti tanıtır.',
      'Yol koşulu uyarısı kırmızı kenarlı üçgenle gösterilir.',
    ],
    objective: 'İlk yardım bilgi işaretini tanımak.',
    tags: ['levha', 'bilgi-isareti', 'ilk-yardim'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-736',
    subject: 'trafik',
    topic: 'tamirhane-bilgi-levha',
    difficulty: 'kolay',
    stem: 'Mavi zeminli bir bilgi işareti üzerinde İngiliz anahtarı (somun anahtarı) sembolü bulunması neyi tanıtır?',
    options: [
      'İleride demir-çelik fabrikası bulunduğunu',
      'Bu yolda tamir yapılamayacağını',
      'Yol bakım çalışması olduğunu',
      'İleride araç tamiri yapılan bir yer (tamirhane) bulunduğunu',
    ],
    answerIndex: 3,
    explanation:
      'Anahtar sembollü mavi bilgi işareti, yakında araç tamiri yapılan bir tamirhane bulunduğunu tanıtır. Arızalanan araç sürücüsü için yol boyunca hangi hizmetlerin bulunduğunu gösteren bilgi işaretlerinden biridir.',
    whyWrong: [
      'İşaret bir sanayi tesisini değil, tamir hizmetini tanıtır.',
      'İşaret bir yasak bildirmez; hizmet yerini gösterir.',
      'Yol çalışması, işçi sembollü ayrı bir uyarı işaretiyle bildirilir.',
    ],
    objective: 'Tamirhane bilgi işaretini tanımak.',
    tags: ['levha', 'bilgi-isareti', 'tamirhane'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-737',
    subject: 'trafik',
    topic: 'akaryakit-bilgi-levha',
    difficulty: 'kolay',
    stem: 'Mavi zeminli bilgi işareti üzerinde yakıt pompası sembolü bulunması sürücüye neyi bildirir?',
    options: [
      'İleride akaryakıt istasyonu bulunduğunu',
      'Bu yolda yakıt taşımanın yasak olduğunu',
      'İleride benzin fiyatlarının yazdığını',
      'Aracın yakıtının bittiğini',
    ],
    answerIndex: 0,
    explanation:
      'Yakıt pompası sembollü mavi bilgi işareti, yakında bir akaryakıt istasyonu bulunduğunu tanıtır. Özellikle uzun yollarda sürücünün yakıt ihtiyacını önceden planlamasına yardımcı olur.',
    whyWrong: [
      'İşaret bir yasak bildirmez; hizmet yerini tanıtır.',
      'İşaret fiyat bilgisi vermez; istasyonun varlığını gösterir.',
      'İşaret aracın yakıt durumuyla ilgili değildir.',
    ],
    objective: 'Akaryakıt istasyonu bilgi işaretini tanımak.',
    tags: ['levha', 'bilgi-isareti', 'akaryakit'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-738',
    subject: 'trafik',
    topic: 'telefon-bilgi-levha',
    difficulty: 'kolay',
    stem: 'Mavi zeminli bir bilgi işareti üzerinde telefon ahizesi sembolü bulunması neyi tanıtır?',
    options: [
      'Telefonla konuşmanın serbest olduğunu',
      'Yakında kullanılabilecek bir telefon (acil çağrı) noktası bulunduğunu',
      'Bu yolda telefon çekmediğini',
      'İleride elektronik mağazası bulunduğunu',
    ],
    answerIndex: 1,
    explanation:
      'Telefon sembollü mavi bilgi işareti, yol kenarında acil durumlarda kullanılabilecek bir telefon veya çağrı noktası bulunduğunu tanıtır. Kaza veya arıza durumunda yardım istemeyi kolaylaştırmayı amaçlar.',
    whyWrong: [
      'İşaret, sürüş sırasında telefon kullanımı için bir izin vermez.',
      'İşaret şebeke kapsamıyla ilgili bilgi vermez.',
      'İşaret bir mağazayı değil, telefon noktasını tanıtır.',
    ],
    objective: 'Telefon bilgi işaretini tanımak.',
    tags: ['levha', 'bilgi-isareti', 'telefon'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-739',
    subject: 'trafik',
    topic: 'konaklama-bilgi-levha',
    difficulty: 'orta',
    stem: 'Mavi zeminli bir bilgi işareti üzerinde yatak sembolü bulunması sürücüye neyi tanıtır?',
    options: [
      'İleride hastane bulunduğunu',
      'Bu kesimde durmanın yasak olduğunu',
      'Yakında konaklama yeri (otel, motel) bulunduğunu; yorulan sürücünün dinlenebileceğini',
      'İleride mobilya satışı yapıldığını',
    ],
    answerIndex: 2,
    explanation:
      'Yatak sembollü mavi bilgi işareti, yakında konaklanabilecek bir tesis bulunduğunu tanıtır. Uzun yolda yorgunluk hisseden sürücü için dinlenip uyku ihtiyacını gidereceği yeri gösterir; yorgun sürüşün önlenmesine katkı sağlar.',
    whyWrong: [
      'Hastane bilgisi "H" sembollü ayrı bir işaretle verilir.',
      'İşaret bir yasak değil, konaklama hizmetini tanıtır.',
      'İşaret ticari bir ürünü değil, konaklama tesisini gösterir.',
    ],
    objective: 'Konaklama bilgi işaretini tanımak.',
    tags: ['levha', 'bilgi-isareti', 'konaklama'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-740',
    subject: 'trafik',
    topic: 'lokanta-bilgi-levha',
    difficulty: 'kolay',
    stem: 'Mavi zeminli bir bilgi işareti üzerinde çatal ve bıçak sembolü bulunması neyi tanıtır?',
    options: [
      'Yolda kayganlık olduğunu',
      'Bu kesimde park etmenin serbest olduğunu',
      'Mutfak eşyası satıldığını',
      'Yakında yemek yenilebilecek bir lokanta (restoran) bulunduğunu',
    ],
    answerIndex: 3,
    explanation:
      'Çatal-bıçak sembollü mavi bilgi işareti, yakında yemek hizmeti veren bir lokanta bulunduğunu tanıtır. Yol boyunca sürücüye sunulan hizmetleri gösteren bilgi işaretlerinden biridir.',
    whyWrong: [
      'Kayganlık uyarısı kırmızı kenarlı üçgenle gösterilir.',
      'İşaret park bilgisi değil, yemek hizmetini tanıtır.',
      'İşaret ticari ürün değil, lokanta hizmetini gösterir.',
    ],
    objective: 'Lokanta bilgi işaretini tanımak.',
    tags: ['levha', 'bilgi-isareti', 'lokanta'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-741',
    subject: 'trafik',
    topic: 'kamp-yeri-bilgi-levha',
    difficulty: 'kolay',
    stem: 'Yol kenarındaki çadır resimli mavi levha, sürücüye hangi tesisin yakında olduğunu haber verir?',
    options: [
      'Yakında kamp (çadırlı konaklama) alanı bulunduğunu',
      'Bu yolda çadır kurmanın yasak olduğunu',
      'İleride asker uygulaması olduğunu',
      'Yolun toprak olduğunu',
    ],
    answerIndex: 0,
    explanation:
      'Çadır sembollü mavi bilgi işareti, yakında kamp yapılabilecek bir alan bulunduğunu tanıtır. Yol boyunca konaklama ve dinlenme seçeneklerini gösteren bilgi işaretlerindendir.',
    whyWrong: [
      'İşaret bir yasak değil, kamp alanını tanıtır.',
      'İşaret bir uygulama noktası bildirmez.',
      'Yol yüzeyiyle ilgili uyarılar farklı işaretlerle verilir.',
    ],
    objective: 'Kamp yeri bilgi işaretini tanımak.',
    tags: ['levha', 'bilgi-isareti', 'kamp-yeri'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-742',
    subject: 'trafik',
    topic: 'park-yeri-bilgi-levha',
    difficulty: 'kolay',
    stem: 'Mavi zemin üzerine beyaz büyük "P" harfi bulunan bilgi işareti neyi bildirir?',
    options: [
      'Bu kesimde park etmenin yasak olduğunu',
      'Araçların park edebileceği bir yer bulunduğunu',
      'Yolun sadece yayalara ait olduğunu',
      'İleride benzin istasyonu bulunduğunu',
    ],
    answerIndex: 1,
    explanation:
      'Mavi zeminli "P" harfli bilgi işareti, araçların kurallara uygun biçimde park edebileceği bir alanı gösterir. Park yasağı ise tam tersine, kırmızı çember ve çizgilerle bildirilir.',
    whyWrong: [
      'Park yasağı kırmızı çemberli işaretle gösterilir; "P" izin verir.',
      'İşaret yaya yolu bilgisi vermez.',
      'Akaryakıt bilgisi pompa sembollü ayrı işaretle verilir.',
    ],
    objective: 'Park yeri bilgi işaretini tanımak.',
    tags: ['levha', 'bilgi-isareti', 'park-yeri'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-743',
    subject: 'trafik',
    topic: 'cikmaz-yol-bilgi-levha',
    difficulty: 'orta',
    stem: 'Mavi zeminli bir bilgi işareti üzerinde, sonu kapalı (T biçiminde) bir yol sembolü bulunması sürücüye neyi bildirir?',
    options: [
      'Yolun ileride ikiye ayrılacağını',
      'İleride otoyol başladığını',
      'Girilen yolun çıkışı olmayan bir çıkmaz yol olduğunu; buradan devam edilemeyeceğini',
      'Bu yolda park etmenin yasak olduğunu',
    ],
    answerIndex: 2,
    explanation:
      'Çıkmaz yol bilgi işareti, girilen yolun ileride kapandığını ve o yönden devam edilemeyeceğini bildirir. Sürücü, gideceği yer o yolda değilse gereksiz yere girmez; girmişse uygun yerden geri dönmek zorunda kalır.',
    whyWrong: [
      'Yolun ayrılması ayrı bir yön işaretiyle gösterilir.',
      'Otoyol başlangıcı yeşil zeminli otoyol işaretiyle bildirilir.',
      'Park yasağı bu bilgi işaretiyle değil, kırmızı çemberle verilir.',
    ],
    objective: 'Çıkmaz yol bilgi işaretini tanımak.',
    tags: ['levha', 'bilgi-isareti', 'cikmaz-yol'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-744',
    subject: 'trafik',
    topic: 'tek-yon-bilgi-levha',
    difficulty: 'orta',
    stem: 'Mavi zeminli dikdörtgen bir bilgi işareti üzerinde tek yöne bakan uzun beyaz bir ok bulunması neyi bildirir?',
    options: [
      'İleride sağa dönmenin zorunlu olduğunu',
      'Yolun tek yönlü olduğunu ve trafiğin yalnızca okun gösterdiği yönde aktığını',
      'Karşıdan araç gelebileceğini',
      'Bu yola girmenin yasak olduğunu',
    ],
    answerIndex: 1,
    explanation:
      'Tek yönlü yol bilgi işareti, o yolda trafiğin yalnızca okun gösterdiği yönde tek taraflı aktığını bildirir. Bu yolda karşıdan araç gelmez; ters yönden girmek ise ağır bir ihlaldir.',
    whyWrong: [
      'Dönüş zorunluluğu mavi daireli mecburi işaretle gösterilir.',
      'Tek yönlü yolda karşıdan araç gelmesi beklenmez; iki yönlü trafik ayrı işaretle uyarılır.',
      'İşaret bir yasak değil, yolun tek yönlü olduğu bilgisini verir.',
    ],
    objective: 'Tek yönlü yol bilgi işaretini tanımak.',
    tags: ['levha', 'bilgi-isareti', 'tek-yon'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-745',
    subject: 'trafik',
    topic: 'devamli-cizgi-yatay',
    difficulty: 'zor',
    stem: 'Taşıt yolunun ortasındaki şerit çizgisi devamlı (kesiksiz) ise sürücü için hangisi doğrudur?',
    options: [
      'Devamlı çizgi geçilemez; sürücü bu çizgiyi aşarak karşı şeride geçemez ve öndeki aracı sollayamaz',
      'Devamlı çizgi istenildiği zaman geçilebilir',
      'Devamlı çizgi yalnızca gece geçerlidir',
      'Devamlı çizgi park yerini gösterir',
    ],
    answerIndex: 0,
    explanation:
      'Yol yüzeyindeki devamlı (kesiksiz) boyuna çizgi, o kesimde şerit değiştirmenin ve karşı şeride geçmenin yasak olduğunu bildirir. Genellikle görüşün kapalı olduğu viraj ve tepe kesimlerinde çizilir; sürücü bu çizgiyi aşamaz ve sollama yapamaz.',
    whyWrong: [
      'Serbest geçiş kesik çizgide mümkündür; devamlı çizgide değil.',
      'Çizginin geçerliliği gece-gündüz ayrımına bağlı değildir.',
      'Boyuna çizgi park yeri değil, şerit düzenini gösterir.',
    ],
    objective: 'Devamlı yol çizgisinin geçilemez olduğunu bilmek.',
    tags: ['yatay-isaretleme', 'devamli-cizgi', 'sollama'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-746',
    subject: 'trafik',
    topic: 'kesik-cizgi-yatay',
    difficulty: 'kolay',
    stem: 'Taşıt yolunun ortasındaki şerit çizgisi kesik (aralıklı) ise bu sürücüye neyi bildirir?',
    options: [
      'Şerit değiştirmenin kesinlikle yasak olduğunu',
      'Yolun bittiğini',
      'Trafik güvenliği elverdiğinde bu çizginin geçilerek şerit değiştirilebileceğini veya sollama yapılabileceğini',
      'Bu kesimde park edilebileceğini',
    ],
    answerIndex: 2,
    explanation:
      'Kesik (aralıklı) boyuna çizgi, trafik güvenliği elverdiğinde geçilebilen bir çizgidir. Sürücü karşı şerit boş ve görüş yeterliyse bu çizgiyi aşarak şerit değiştirebilir veya öndeki aracı geçebilir.',
    whyWrong: [
      'Kesin geçiş yasağı devamlı çizgiyle bildirilir; kesik çizgide değil.',
      'Kesik çizgi yolun bittiğini göstermez.',
      'Boyuna çizgi park bilgisi vermez.',
    ],
    objective: 'Kesik yol çizgisinin uygun koşulda geçilebileceğini bilmek.',
    tags: ['yatay-isaretleme', 'kesik-cizgi', 'serit-degistirme'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-747',
    subject: 'trafik',
    topic: 'yaya-gecidi-cizgileri-yatay',
    difficulty: 'orta',
    stem: 'Taşıt yolu üzerine enine çizilmiş kalın beyaz şeritler (yaya geçidi çizgileri) sürücüye neyi bildirir ve buna nasıl davranılır?',
    options: [
      'Aracın park edeceği yeri; üzerine park edilebilir',
      'Yayaların karşıdan karşıya geçtiği yeri; sürücü yavaşlar, geçen veya geçmek üzere olan yayaya yol verir',
      'Sollama yapılacak yeri',
      'Hız denemesi yapılacak yeri',
    ],
    answerIndex: 1,
    explanation:
      'Taşıt yoluna enine çizilmiş kalın beyaz şeritler yaya geçidini gösterir. Sürücü bu çizgilere yaklaşırken hızını azaltır; geçitte bulunan veya geçmek üzere olan yayalara yol verir ve geçit üzerine park etmez.',
    whyWrong: [
      'Yaya geçidi çizgileri park yeri değildir; üzerine park etmek yasaktır.',
      'Yaya geçidinde sollama yapmak yasaktır.',
      'Geçit, hız denemesi değil, yaya güvenliği için ayrılmış bir alandır.',
    ],
    objective: 'Yaya geçidi çizgilerini tanıyıp yol verme davranışını bilmek.',
    tags: ['yatay-isaretleme', 'yaya-gecidi', 'yaya-onceligi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-748',
    subject: 'trafik',
    topic: 'yonlendirme-oklari-yatay',
    difficulty: 'zor',
    stem: 'Kavşağa yaklaşırken bulunduğunuz şeridin zeminine boyanmış ok yalnızca sola dönüşü gösteriyorsa doğru davranış hangisidir?',
    options: [
      'Yer okunun gösterdiği yönde, yani sola dönmek; başka yöne gitmek istiyorsam önceden uygun şeride geçmek',
      'Okları dikkate almadan istediğim yöne gitmek',
      'Bu şeritte düz devam etmek',
      'Şeridin üzerinde durup beklemek',
    ],
    answerIndex: 0,
    explanation:
      'Şerit zeminine boyanmış yönlendirme okları, o şeridin kavşakta hangi yön için ayrıldığını bildirir. Yalnızca sola dönüş oku bulunan şeritte sürücü sola dönmek zorundadır; başka yöne gidecekse kavşağa girmeden önce doğru şeride geçmelidir.',
    whyWrong: [
      'Yer oklarını yok saymak, yanlış şeritten dönerek trafik düzenini bozar ve kaza doğurur.',
      'Yalnızca sola dönüş oku bulunan şeritte düz devam edilemez.',
      'Şerit üzerinde durup beklemek akışı tıkar; gösterilen yönde ilerlenir.',
    ],
    objective: 'Şerit üzeri yönlendirme oklarına göre önceden şerit seçmeyi bilmek.',
    tags: ['yatay-isaretleme', 'yonlendirme-oku', 'serit-secimi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-749',
    subject: 'trafik',
    topic: 'sari-cizgi-yatay',
    difficulty: 'zor',
    stem: 'Taşıt yolunun kenarına (bordür boyunca) çizilmiş devamlı sarı çizgi sürücüye genel olarak neyi bildirir?',
    options: [
      'O kesimde duraklamanın ve park etmenin yasak olduğunu',
      'Bu kesimde park etmenin serbest olduğunu',
      'Yolun kaygan olduğunu',
      'Bisiklet yolunu',
    ],
    answerIndex: 0,
    explanation:
      'Yol kenarında bordür boyunca çekilen devamlı sarı çizgi, o kesimde duraklama ve park etme yasağını bildirir. Sürücü bu çizginin bulunduğu yere aracını bırakamaz; aksi hâlde trafik akışını ve güvenliği engeller.',
    whyWrong: [
      'Sarı kenar çizgisi park serbestliği değil, yasağı bildirir.',
      'Kayganlık uyarısı kırmızı kenarlı üçgen levhayla gösterilir.',
      'Bisiklet yolu ayrı işaret ve işaretlemelerle belirtilir.',
    ],
    objective: 'Kenardaki devamlı sarı çizginin duraklama-park yasağı anlamını bilmek.',
    tags: ['yatay-isaretleme', 'sari-cizgi', 'park-yasagi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-750',
    subject: 'trafik',
    topic: 'otoyol-baslangic-levha',
    difficulty: 'orta',
    stem: 'Yeşil zeminli bir levhada, üzerinden yol geçen köprü benzeri otoyol sembolü bulunması sürücüye neyi bildirir?',
    options: [
      'Yolun toprak yola dönüştüğünü',
      'Otoyolun başladığını; bu kesimde otoyol kurallarının (asgari-azami hız, yayaların ve yavaş araçların giremeyeceği vb.) geçerli olduğunu',
      'Yolun kapandığını',
      'İleride yalnızca yaya yolu bulunduğunu',
    ],
    answerIndex: 1,
    explanation:
      'Otoyol başlangıç işareti, yeşil zeminli otoyol sembolüyle gösterilir ve bu noktadan itibaren otoyol kurallarının başladığını bildirir. Otoyolda yayalar, hayvanlar, motorsuz ve çok yavaş araçlar giremez; hız ve şerit kurallarına uyulması zorunludur.',
    whyWrong: [
      'İşaret yol yüzeyinin türünü değil, otoyolun başladığını bildirir.',
      'İşaret bir yol kapanması değildir.',
      'Otoyol yaya girişine kapalıdır; yaya yolu bildirmez.',
    ],
    objective: 'Otoyol başlangıç işaretini ve otoyol kurallarının başladığını bilmek.',
    tags: ['levha', 'otoyol', 'otoyol-baslangic'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-751',
    subject: 'trafik',
    topic: 'otoyol-cikis-levha',
    difficulty: 'orta',
    stem: 'Otoyolda ilerlerken yeşil zeminli bir levhada bir yer adı ile birlikte aşağı-sağa ayrılan ok ve mesafe (örneğin 500 m) bilgisi görüyorsanız bu ne anlama gelir?',
    options: [
      'Otoyolun tamamen kapandığını',
      'Bu noktada geri dönüş yapılabileceğini',
      'Belirtilen mesafe sonra o yer için otoyoldan ayrılış (çıkış) olduğunu; ayrılacaksanız şeridinizi önceden hazırlamanız gerektiğini',
      'Hız sınırının kalktığını',
    ],
    answerIndex: 2,
    explanation:
      'Otoyol çıkış (ayrılma) levhaları yeşil zeminlidir ve belirtilen mesafe sonra hangi yer için otoyoldan ayrılınacağını bildirir. Ayrılacak sürücü, ani manevra yapmamak için önceden en sağ (ayrılma) şeridine geçip hızını çıkışa uygun ayarlamalıdır.',
    whyWrong: [
      'Levha otoyolun kapandığını değil, bir çıkış olduğunu bildirir.',
      'Otoyolda geri dönüş yasaktır; levha bunu göstermez.',
      'Levha hız sınırını kaldırmaz; yol bilgisi verir.',
    ],
    objective: 'Otoyol çıkış levhasını okuyup önceden şerit hazırlamayı bilmek.',
    tags: ['levha', 'otoyol', 'cikis'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-752',
    subject: 'trafik',
    topic: 'ekonomik-surus-cevre',
    difficulty: 'zor',
    stem: 'Yakıt tüketimini ve dolayısıyla egzoz kirliliğini azaltan ekonomik sürüş açısından aşağıdakilerden hangisi en doğrudur?',
    options: [
      'Sürekli ani hızlanma ve sert fren yaparak trafikte hızlı ilerlemek',
      'Motoru yüksek devirlerde zorlamak',
      'Lastikleri düşük basınçta kullanmak',
      'Yumuşak gaz-fren kullanmak, uygun viteste gitmek, gereksiz duruş ve rölantiden kaçınmak ve sabit hızı korumak',
    ],
    answerIndex: 3,
    explanation:
      'Ekonomik ve çevreci sürüşte amaç, motoru gereksiz yere zorlamamaktır. Yumuşak gaz-fren kullanmak, motoru uygun devirde ve viteste çalıştırmak, gereksiz rölanti ve ani hızlanmalardan kaçınmak ve mümkün olduğunca sabit hızı korumak hem yakıtı hem egzoz salımını azaltır.',
    whyWrong: [
      'Ani hızlanma ve sert fren yakıt tüketimini ve emisyonu belirgin biçimde artırır.',
      'Motoru yüksek devirde zorlamak yakıtı ve kirliliği artırır.',
      'Düşük lastik basıncı yuvarlanma direncini artırıp yakıt tüketimini yükseltir.',
    ],
    objective: 'Ekonomik sürüşün yakıt ve emisyonu azaltan ilkelerini kavramak.',
    tags: ['cevre', 'ekonomik-surus', 'yakit-tasarrufu', 'emisyon'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-753',
    subject: 'trafik',
    topic: 'motor-bakimi-emisyon-cevre',
    difficulty: 'orta',
    stem: 'Aracın düzenli bakımının (hava filtresi, buji, motor ayarı vb.) çevre açısından temel faydası nedir?',
    options: [
      'Bakımlı motorun yakıtı daha verimli yakması, böylece yakıt tüketiminin ve zararlı egzoz gazı salımının azalması',
      'Aracın renginin korunması',
      'Egzoz sesinin daha yüksek çıkması',
      'Yakıt tüketiminin artması',
    ],
    answerIndex: 0,
    explanation:
      'Bakımsız bir motor yakıtı eksik ve verimsiz yakar; bu da hem yakıt tüketimini hem de zararlı egzoz gazı salımını artırır. Düzenli bakımı yapılan motor yakıtı tam yakar, daha az kirletici üretir; çevreye ve bütçeye katkı sağlar.',
    whyWrong: [
      'Bakımın amacı estetik değil, verimli ve temiz çalışmadır.',
      'Bakım, egzoz sesini artırmak için değil, verimi yükseltmek içindir.',
      'Bakım yakıt tüketimini artırmaz; azaltır.',
    ],
    objective: 'Düzenli motor bakımının emisyonu azalttığını kavramak.',
    tags: ['cevre', 'motor-bakimi', 'emisyon'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-754',
    subject: 'trafik',
    topic: 'elektrikli-arac-cevre',
    difficulty: 'orta',
    stem: 'Elektrikli araçların, içten yanmalı (benzin/dizel) araçlara göre çevreye en belirgin katkısı hangisidir?',
    options: [
      'Daha yüksek egzoz gürültüsü çıkarması',
      'Kullanım sırasında egzozdan zararlı gaz salmaması ve çok daha sessiz çalışması',
      'Hiç enerjiye ihtiyaç duymaması',
      'Lastik kullanmaması',
    ],
    answerIndex: 1,
    explanation:
      'Elektrikli araçlar elektrik motoruyla çalıştığı için kullanım sırasında egzozdan karbon ve kirletici gaz salmaz; ayrıca çok daha sessiz çalışarak gürültü kirliliğini azaltır. Bu yönleriyle hava kalitesi ve şehir gürültüsü açısından belirgin bir avantaj sağlar.',
    whyWrong: [
      'Elektrikli araçlar daha sessizdir; gürültüyü artırmaz.',
      'Elektrikli araç enerjisiz çalışmaz; şarj edilmesi gerekir.',
      'Elektrikli araç da lastik kullanır; bu bir fark değildir.',
    ],
    objective: 'Elektrikli aracın egzoz emisyonu ve gürültü açısından çevreye katkısını bilmek.',
    tags: ['cevre', 'elektrikli-arac', 'emisyon'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-755',
    subject: 'trafik',
    topic: 'atik-motor-yagi-cevre',
    difficulty: 'zor',
    stem: 'Araç bakımında değiştirilen kullanılmış (atık) motor yağı ile ilgili çevre açısından doğru davranış hangisidir?',
    options: [
      'Toprağa veya kanalizasyona dökmek',
      'Bahçeyi sulamak için kullanmak',
      'Ağaç diplerine dökerek ot bitmesini önlemek',
      'Toprağa, suya veya kanalizasyona dökmemek; sızdırmaz kapta toplayıp yetkili toplama noktalarına (geri dönüşüme) teslim etmek',
    ],
    answerIndex: 3,
    explanation:
      'Atık motor yağı çok tehlikeli bir kirleticidir; az miktarı bile büyük hacimde su kaynağını kirletebilir. Bu yüzden toprağa, suya veya kanalizasyona dökülmez; sızdırmaz bir kapta biriktirilip yetkili atık yağ toplama noktalarına ya da geri dönüşüm merkezlerine teslim edilmelidir.',
    whyWrong: [
      'Yağı toprağa veya kanalizasyona dökmek toprağı ve su kaynaklarını ağır biçimde kirletir.',
      'Atık yağla sulama, bitkilere ve toprağa zarar verir.',
      'Ağaç diplerine dökmek toprağı ve yer altı suyunu zehirler.',
    ],
    objective: 'Atık motor yağının doğaya dökülmeyip geri dönüşüme verilmesini bilmek.',
    tags: ['cevre', 'atik-yag', 'geri-donusum'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-756',
    subject: 'trafik',
    topic: 'atik-lastik-cevre',
    difficulty: 'orta',
    stem: 'Ömrünü tamamlamış (aşınmış) araç lastikleri ile ilgili çevreye en uygun davranış hangisidir?',
    options: [
      'Açık alanda yakarak yok etmek',
      'Dere kenarına veya boş araziye atmak',
      'Yetkili toplama ve geri dönüşüm noktalarına teslim etmek',
      'Yol kenarına bırakmak',
    ],
    answerIndex: 2,
    explanation:
      'Atık lastikler doğada uzun süre çözülmez ve yakıldığında yoğun zehirli duman çıkarır. Bu nedenle açıkta yakılmaz veya doğaya atılmaz; yetkili toplama ve geri dönüşüm noktalarına verilerek yeniden değerlendirilmesi sağlanır.',
    whyWrong: [
      'Lastik yakmak havayı zehirli gazlarla ağır biçimde kirletir.',
      'Doğaya atılan lastik hem görüntü hem toprak-su kirliliği yaratır.',
      'Yol kenarına bırakmak hem çevre kirliliği hem trafik tehlikesidir.',
    ],
    objective: 'Atık lastiklerin geri dönüşüme verilmesini bilmek.',
    tags: ['cevre', 'atik-lastik', 'geri-donusum'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-757',
    subject: 'trafik',
    topic: 'atik-aku-cevre',
    difficulty: 'orta',
    stem: 'Ömrünü tamamlamış araç aküsünün çevreye ve doğaya rastgele atılması neden özellikle sakıncalıdır?',
    options: [
      'İçinde bulunan asit ve kurşun gibi maddeler toprağı ve su kaynaklarını kirletip canlılara zarar verdiği için; akü yetkili noktalara teslim edilmelidir',
      'Aküler çok hafif olduğu için',
      'Aküler tamamen zararsız olduğu için sorun olmaz',
      'Aküler yeniden kullanılamadığı için',
    ],
    answerIndex: 0,
    explanation:
      'Araç aküleri asit ve kurşun gibi zararlı maddeler içerir; doğaya atıldığında bu maddeler toprağa ve yer altı suyuna karışarak uzun süreli kirlilik ve sağlık riski oluşturur. Bu yüzden atık aküler doğaya atılmaz, yetkili toplama noktalarına teslim edilir.',
    whyWrong: [
      'Sorun ağırlıkla değil, içerdiği tehlikeli maddelerle ilgilidir.',
      'Aküler zararsız değildir; ağır kirletici içerir.',
      'Atık aküler geri dönüşümle yeniden değerlendirilebilir; asıl sorun doğaya atılmasıdır.',
    ],
    objective: 'Atık akünün tehlikeli içeriğini ve doğru bertarafını bilmek.',
    tags: ['cevre', 'atik-aku', 'geri-donusum'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-758',
    subject: 'trafik',
    topic: 'hurda-arac-cevre',
    difficulty: 'orta',
    stem: 'Ömrünü tamamlamış (hurda) bir aracın çevre açısından en uygun şekilde elden çıkarılması nasıl olur?',
    options: [
      'Boş bir araziye bırakılıp çürümeye terk edilmesiyle',
      'Yetkili söküm ve geri dönüşüm tesislerine teslim edilerek parça ve malzemelerinin geri kazanılmasıyla',
      'Yakılarak yok edilmesiyle',
      'Denize veya göle bırakılmasıyla',
    ],
    answerIndex: 1,
    explanation:
      'Hurda araçlar; yağ, akü, lastik ve metal gibi çevreye zarar verebilecek pek çok parça içerir. En doğru yöntem, aracı yetkili söküm ve geri dönüşüm tesislerine teslim etmektir; böylece tehlikeli maddeler güvenle ayrıştırılır ve metaller yeniden kazanılır.',
    whyWrong: [
      'Araziye terk edilen araç toprak ve su kirliliğine yol açar.',
      'Aracı yakmak zehirli gazlar ve ağır kirlilik oluşturur.',
      'Suya bırakmak su ekosistemini ciddi biçimde zehirler.',
    ],
    objective: 'Hurda aracın yetkili geri dönüşüm tesisine teslim edilmesini bilmek.',
    tags: ['cevre', 'hurda-arac', 'geri-donusum'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-759',
    subject: 'trafik',
    topic: 'yola-cop-atmak-cevre',
    difficulty: 'kolay',
    stem: 'Araç kullanırken cam açıp yola izmarit, ambalaj veya benzeri çöp atmak nasıl değerlendirilir?',
    options: [
      'Yanlış ve zararlıdır; çevreyi kirletir, yangına yol açabilir ve arkadan gelenler için tehlike oluşturur',
      'Cam açıkken sorun değildir',
      'Küçük çöpler için serbesttir',
      'Şehir dışında serbesttir',
    ],
    answerIndex: 0,
    explanation:
      'Araçtan yola çöp atmak hem görüntü ve çevre kirliliği yaratır hem de yanan izmarit kuru bitki örtüsünde yangın başlatabilir; atılan cisimler arkadan gelen sürücüler için tehlike oluşturur. Atıklar araçta biriktirilip uygun çöp kutularına atılmalıdır.',
    whyWrong: [
      'Camın açık olması çöp atmayı meşru kılmaz.',
      'Çöpün küçük olması kirletici ve tehlikeli olmasını değiştirmez.',
      'Şehir dışı için de böyle bir serbestlik yoktur; doğa daha da hassastır.',
    ],
    objective: 'Araçtan yola çöp atmanın çevre ve güvenlik açısından zararını kavramak.',
    tags: ['cevre', 'atik', 'yangin-riski'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-760',
    subject: 'trafik',
    topic: 'gereksiz-yuk-cevre',
    difficulty: 'orta',
    stem: 'Araçta gereksiz yere sürekli ağır yük veya kullanılmayan bagaj/portbagaj taşımanın yakıt ve çevre üzerindeki etkisi nedir?',
    options: [
      'Yakıt tüketimini ve egzoz salımını azaltır',
      'Aracı daha çevreci yapar',
      'Hiçbir etkisi yoktur',
      'Aracın ağırlığını ve hava direncini artırarak yakıt tüketimini ve egzoz salımını yükseltir',
    ],
    answerIndex: 3,
    explanation:
      'Gereksiz yük ve kullanılmayan tavan/arka bagajlar aracın ağırlığını ve hava direncini artırır; bu da motorun daha çok yakıt harcamasına ve daha fazla egzoz gazı çıkarmasına yol açar. İhtiyaç olmayan yükün araçtan çıkarılması hem yakıt hem çevre açısından yararlıdır.',
    whyWrong: [
      'Fazla yük yakıtı azaltmaz; artırır.',
      'Gereksiz yük aracı çevreci yapmaz; tersine kirliliği artırır.',
      'Ağırlık ve direnç artışı yakıt tüketimini gözle görülür biçimde etkiler.',
    ],
    objective: 'Gereksiz yükün yakıt ve emisyonu artırdığını kavramak.',
    tags: ['cevre', 'yakit-tasarrufu', 'yukleme'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-761',
    subject: 'trafik',
    topic: 'katalitik-konvertor-cevre',
    difficulty: 'zor',
    stem: 'Benzinli araçların egzoz sistemine takılan katalitik konvertörün (katalizörün) temel çevresel görevi nedir?',
    options: [
      'Egzozdan çıkan zararlı gazları kimyasal olarak daha az zararlı gazlara dönüştürerek hava kirliliğini azaltmak',
      'Aracın sesini yükseltmek',
      'Yakıt deposunu büyütmek',
      'Motorun gücünü sınırsız artırmak',
    ],
    answerIndex: 0,
    explanation:
      'Katalitik konvertör, egzoz gazındaki karbonmonoksit ve yanmamış yakıt gibi zararlı bileşenleri kimyasal tepkimelerle daha az zararlı gazlara dönüştürür. Böylece araçtan çıkan kirleticiler azaltılır ve hava kalitesinin korunmasına katkı sağlanır; bu parçanın çıkarılması emisyonu ciddi biçimde artırır.',
    whyWrong: [
      'Katalizörün amacı sesi yükseltmek değil, kirleticileri azaltmaktır.',
      'Yakıt deposuyla ilgili bir işlevi yoktur.',
      'Katalizör motor gücünü artırmak için değil, egzozu temizlemek için vardır.',
    ],
    objective: 'Katalitik konvertörün egzoz kirliliğini azaltma görevini bilmek.',
    tags: ['cevre', 'katalitik-konvertor', 'emisyon'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-762',
    subject: 'trafik',
    topic: 'siyah-duman-cevre',
    difficulty: 'orta',
    stem: 'Bir aracın egzozundan sürekli yoğun siyah duman çıkması çevre ve araç açısından neyi gösterir?',
    options: [
      'Aracın çok verimli çalıştığını',
      'Yakıtın tam yandığını',
      'Yakıtın verimsiz ve eksik yandığını; motorun ayar veya bakıma ihtiyacı olduğunu ve havayı fazladan kirlettiğini',
      'Aracın yeni olduğunu',
    ],
    answerIndex: 2,
    explanation:
      'Egzozdan çıkan yoğun siyah duman, yakıtın tam yanmadığını ve motorun ayar ya da bakıma ihtiyaç duyduğunu gösterir. Bu durum hem yakıt israfına yol açar hem de havaya fazladan partikül ve kirletici salarak çevreyi ve insan sağlığını olumsuz etkiler; araç bakıma alınmalıdır.',
    whyWrong: [
      'Yoğun siyah duman verimli çalışmanın değil, verimsizliğin işaretidir.',
      'Tam yanmada bu tür yoğun siyah duman oluşmaz.',
      'Duman aracın yaşıyla değil, yanma ve bakım durumuyla ilgilidir.',
    ],
    objective: 'Egzozdan siyah dumanın eksik yanma ve kirlilik işareti olduğunu kavramak.',
    tags: ['cevre', 'emisyon', 'motor-bakimi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-763',
    subject: 'trafik',
    topic: 'toplu-tasima-cevre',
    difficulty: 'kolay',
    stem: 'Kısa mesafelerde mümkün olduğunda toplu taşımayı, yürümeyi veya bisikleti tercih etmenin çevreye katkısı nedir?',
    options: [
      'Trafiğe çıkan özel araç ve dolayısıyla toplam egzoz salımı ile trafik yoğunluğunu azaltması',
      'Hiçbir katkısı olmaması',
      'Hava kirliliğini artırması',
      'Yakıt tüketimini yükseltmesi',
    ],
    answerIndex: 0,
    explanation:
      'Herkesin ayrı ayrı özel araç kullanması yerine toplu taşımanın, yürümenin veya bisikletin tercih edilmesi; yola çıkan araç sayısını azaltır. Bu da toplam egzoz salımını, yakıt tüketimini ve trafik yoğunluğunu düşürerek hava kalitesine katkı sağlar.',
    whyWrong: [
      'Toplu taşımanın çevreye katkısı vardır; etkisiz değildir.',
      'Tam tersine hava kirliliğini azaltır.',
      'Kişi başına düşen yakıt tüketimini düşürür.',
    ],
    objective: 'Toplu taşıma tercihinin emisyon ve trafiği azalttığını kavramak.',
    tags: ['cevre', 'toplu-tasima', 'emisyon'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-764',
    subject: 'trafik',
    topic: 'modifiye-egzoz-cevre',
    difficulty: 'orta',
    stem: 'Aracın egzoz susturucusunu çıkarmak veya sesini artıracak şekilde değiştirmek çevre açısından hangi soruna yol açar?',
    options: [
      'Hava kirliliğini tümüyle ortadan kaldırır',
      'Gürültü kirliliğine yol açarak çevredeki insanları rahatsız eder ve huzuru bozar',
      'Yakıt tüketimini düşürür',
      'Hiçbir soruna yol açmaz',
    ],
    answerIndex: 1,
    explanation:
      'Egzoz susturucusu, motor sesini azaltarak gürültüyü sınırlar. Susturucunun çıkarılması veya sesi artıracak şekilde değiştirilmesi, çevrede yüksek ve rahatsız edici sese yani gürültü kirliliğine yol açar; bu hem insan sağlığını hem huzuru olumsuz etkiler ve kurallara aykırıdır.',
    whyWrong: [
      'Susturucuyu çıkarmak hava kirliliğini gidermez; ayrı bir sorundur.',
      'Bu değişiklik yakıt tüketimiyle ilgili bir iyileştirme sağlamaz.',
      'Gürültü kirliliği yarattığı için soruna yol açar.',
    ],
    objective: 'Egzoz değişikliğinin gürültü kirliliği yarattığını kavramak.',
    tags: ['cevre', 'gurultu-kirliligi', 'egzoz'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-765',
    subject: 'trafik',
    topic: 'soguk-rolanti-cevre',
    difficulty: 'zor',
    stem: 'Soğuk havada aracı çalıştırıp uzun süre yerinde (rölantide) ısınmaya bırakmak yerine, çevre ve yakıt açısından önerilen davranış hangisidir?',
    options: [
      'Motoru yarım saat rölantide bekletmek',
      'Aracı gaza basılı hâlde yüksek devirde ısıtmak',
      'Motoru çalıştırdıktan kısa süre sonra düşük hız ve yumuşak sürüşle yola çıkıp motorun sürüş sırasında ısınmasını sağlamak',
      'Motoru gece boyunca çalışır bırakmak',
    ],
    answerIndex: 2,
    explanation:
      'Aracı uzun süre rölantide ısıtmak yakıt israfına ve gereksiz egzoz salımına yol açar; üstelik motor yerinde beklerken verimli ısınmaz. Doğru davranış, çalıştırdıktan kısa süre sonra düşük hız ve yumuşak sürüşle yola çıkmak, böylece motorun sürüş sırasında daha hızlı ve temiz ısınmasını sağlamaktır.',
    whyWrong: [
      'Uzun süreli rölanti yakıt harcar ve gereksiz kirlilik üretir.',
      'Soğuk motoru yüksek devirde zorlamak hem motora hem çevreye zarar verir.',
      'Motoru gece boyu çalışır bırakmak büyük yakıt israfı ve ağır kirliliktir.',
    ],
    objective: 'Uzun rölanti yerine sürerek ısıtmanın çevreci olduğunu kavramak.',
    tags: ['cevre', 'rolanti', 'yakit-tasarrufu'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
];
