/**
 * ÖZGÜN trafik adabı soruları — 3. genişletme (Program 1). ROADMAP C.4/E.6.
 * Kaynak = MEB Trafik Adabı müfredatı; KENDİ İFADEMİZLE.
 */
import type { QuestionInput } from '@ea/content-schema';

const SRC = 'MEB Trafik Adabı müfredatı (özgün ifade)';

export const ADAB_QUESTIONS_3: QuestionInput[] = [
  {
    id: 'adab-301',
    subject: 'adab',
    topic: 'hiz-adabi',
    difficulty: 'orta',
    stem: 'Yoğun sis nedeniyle görüş mesafesi birkaç metreye düştü. Hız adabı ve güvenlik açısından en doğru davranış hangisidir?',
    options: [
      'Öndeki aracın stop lambalarını takip ederek hızlı ilerlemek',
      'Uzun farları açıp normal hızda devam etmek',
      'Dörtlüleri yakıp aynı hızı korumak',
      'Hızı görüş mesafesine göre iyice düşürüp takip mesafesini artırmak ve sis farlarını kullanmak',
    ],
    answerIndex: 3,
    explanation:
      'Sisli havada görüş ve fren mesafesi ciddi biçimde bozulur; hızı düşürüp mesafeyi açmak ve sis farını kullanmak koşullara uyum sağlayan hız adabının gereğidir.',
    whyWrong: [
      'Öndekinin stop lambalarına güvenip hızlı gitmek, o araç durunca çarpma riski doğurur.',
      'Uzun far, sisten geri yansıyıp görüşü daha da azaltır ve göz kamaştırır.',
    ],
    objective: 'Görüşün azaldığı hava koşullarında hızı ve takip mesafesini uyarlamayı kavramak.',
    tags: ['hiz-adabi', 'sis', 'guvenli-surus'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-302',
    subject: 'adab',
    topic: 'trafik-kurallari-saygi',
    difficulty: 'orta',
    stem: 'Göbekli (döner) bir kavşağa girmek üzeresiniz ve kavşağın içinde dönmekte olan araçlar var. Kurallara uygun davranış nedir?',
    options: [
      'Sinyal vermeden hızla kavşağa dalmak',
      'Kavşak içinde dönen araçlara yol verip uygun boşlukta katılmak',
      'İçerideki araçlar dursun diye korna çalmak',
      '"Hakkım" diyerek onlardan önce girmeye çalışmak',
    ],
    answerIndex: 1,
    explanation:
      'Döner kavşaklarda öncelik kavşak içinde dönen aracındır; uygun boşluğu bekleyip katılmak hem kurala hem de akıcı ve güvenli trafiğe hizmet eder.',
    whyWrong: [
      'Yol vermeden dalmak, dönen araçlarla çarpışmaya yol açar.',
      'Kornayla veya zorla öne geçmek kavşak düzenini bozar ve gerginlik yaratır.',
    ],
    objective: 'Döner kavşakta kavşak içindeki araca öncelik verme kuralını benimsemek.',
    tags: ['trafik-kurallari-saygi', 'doner-kavsak', 'yol-verme'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-303',
    subject: 'adab',
    topic: 'cevre-bilinci',
    difficulty: 'kolay',
    stem: 'Araç içinde bir ambalaj ve izmarit birikti. Çevre bilinci açısından doğru davranış hangisidir?',
    options: [
      'Camdan dışarı atmak, nasılsa küçük bir çöp',
      'Kırmızı ışıkta yola bırakmak',
      'İzmariti yola, ambalajı ise çöp kutusuna atmak',
      'Çöpleri araçta biriktirip uygun bir çöp kutusuna atmak',
    ],
    answerIndex: 3,
    explanation:
      'Araçtan yola atılan her çöp doğayı kirletir, kanalları tıkar ve izmarit yangına yol açabilir; çöpü araçta biriktirip uygun yere atmak çevreye saygının basit ama önemli bir göstergesidir.',
    whyWrong: [
      'Camdan çöp atmak, küçük olsa bile çevre kirliliği ve görüntü kirliliği yaratır.',
      'İzmariti yola atmak hem kirletir hem de kuru ortamda yangın riski doğurur.',
    ],
    objective: 'Araçtan çöp atmamayı ve atıkları uygun biçimde toplamayı ilke edinmek.',
    tags: ['cevre-bilinci', 'cop', 'sorumluluk'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-304',
    subject: 'adab',
    topic: 'gecis-ustunlugu',
    difficulty: 'zor',
    stem: 'Otoyolda trafik tamamen durdu ve arkadan sirenli araçların yaklaştığı duyuluyor. En doğru davranış nedir?',
    options: [
      'Olduğunuz yerde hiç kımıldamadan beklemek',
      'Emniyet şeridinden ilerleyip trafiği aşmaya çalışmak',
      'Şeritler arasında yaşam koridoru (acil durum koridoru) oluşacak şekilde araçların kenarlara yanaşması',
      'Sirenli araçlar gelene kadar araçtan inip beklemek',
    ],
    answerIndex: 2,
    explanation:
      'Trafik durduğunda araçların kenarlara yanaşarak orta bölümde bir yaşam koridoru bırakması, sirenli araçların olay yerine hızla ulaşmasını sağlar ve hayat kurtarır.',
    whyWrong: [
      'Herkesin olduğu yerde kalması, ortada geçiş için boşluk bırakmaz.',
      'Emniyet şeridini kişisel çıkar için kullanmak hem yasak hem de tehlikelidir; araçtan inmek ise trafiğe çıkma riski doğurur.',
    ],
    objective: 'Duran trafikte geçiş üstünlüğü araçları için yaşam koridoru oluşturmayı kavramak.',
    tags: ['gecis-ustunlugu', 'yasam-koridoru', 'otoyol'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-305',
    subject: 'adab',
    topic: 'yaya-onceligi',
    difficulty: 'kolay',
    stem: 'Bir kavşakta sağa dönüş yapacaksınız; döneceğiniz yolda yayalar karşıdan karşıya geçiyor. Doğru davranış hangisidir?',
    options: [
      'Yayaların geçişini tamamlamasını bekleyip sonra dönmek',
      'Korna çalıp yayaları hızlandırmak',
      'Yayaların arasından sıyrılıp dönüşü tamamlamak',
      '"Aracım döndüğü için öncelik bende" deyip geçmek',
    ],
    answerIndex: 0,
    explanation:
      'Dönüş yaptığınız yola giren yayalar öncelik hakkına sahiptir; onların güvenle geçişini bekleyip sonra dönmek yaya önceliğinin temel bir uygulamasıdır.',
    whyWrong: [
      'Kornayla yayaları hızlandırmaya çalışmak onları paniğe sürükler.',
      'Yayaların arasından geçmek veya önceliği kendine mal etmek ciddi kaza riski taşır.',
    ],
    objective: 'Dönüş sırasında karşıya geçen yayalara öncelik vermeyi kavramak.',
    tags: ['yaya-onceligi', 'donus', 'kavsak'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-306',
    subject: 'adab',
    topic: 'empati',
    difficulty: 'kolay',
    stem: 'Yaya geçidinde bebek arabası iten bir ebeveyn yavaşça karşıya geçiyor. Empatik davranış hangisidir?',
    options: [
      'Korna çalıp acele ettirmek',
      'Arabanın önünden hızla geçmek',
      'Tam durup güvenle ve rahatça geçmelerini beklemek',
      'Yavaşlayıp yanlarından sıyrılarak geçmek',
    ],
    answerIndex: 2,
    explanation:
      'Bebek arabasıyla geçen bir ebeveyn hem yavaş ilerler hem de savunmasız bir yükü taşır; tam durup beklemek kendini onların yerine koyan empatik ve güvenli bir davranıştır.',
    whyWrong: [
      'Korna çalmak ebeveyni telaşlandırır ve bebeği riske atar.',
      'Önünden geçmek veya yanlarından sıyrılmak, ani bir hareket karşısında tehlike yaratır.',
    ],
    objective:
      'Bebek arabalı yayalar gibi savunmasız kişilere empatiyle tam öncelik vermeyi kavramak.',
    tags: ['empati', 'yaya-onceligi', 'bebek-arabasi'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-307',
    subject: 'adab',
    topic: 'ofke-yonetimi',
    difficulty: 'zor',
    stem: 'Bir kavşakta iki araç ramak kala bir kazadan döndü; her iki sürücü de durdu ve ortam gergin. En olgun davranış nedir?',
    options: [
      'Camı açıp suçun karşı tarafta olduğunu bağırarak söylemek',
      'Sakinleşip gerekirse özür dileyerek durumu yatıştırmak ve yola güvenle devam etmek',
      'Araçtan inip tartışmayı büyütmek',
      'Kavga videosu çekip paylaşmakla tehdit etmek',
    ],
    answerIndex: 1,
    explanation:
      'Gerginliğin tırmandığı anlarda sakinleşmek ve gerekirse özür dilemek çatışmayı hızla söndürür; kimin haklı olduğunu ispatlamaya çalışmak yerini yeni bir tehlikeye bırakabilir.',
    whyWrong: [
      'Bağırmak veya araçtan inmek, küçük bir olayı fiziksel bir kavgaya dönüştürebilir.',
      'Tehdit etmek gerilimi büyütür ve hiçbir sorunu çözmez.',
    ],
    objective: 'Ani bir olay sonrası öfkeyi yatıştırıp çatışmayı büyütmemeyi kavramak.',
    tags: ['ofke-yonetimi', 'sakinlik', 'uzlasma'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-308',
    subject: 'adab',
    topic: 'korna-kullanimi',
    difficulty: 'kolay',
    stem: 'Bir yakınınızı almak için evinin önüne geldiniz. Onu aşağı çağırmak için ne yapmalısınız?',
    options: [
      'Aşağı inene kadar korna çalmak',
      'Uzun bir korna ile geldiğinizi duyurmak',
      'Birkaç kez kısa korna çalıp beklemek',
      'Telefonla arayıp ya da mesaj atarak gürültü yapmadan beklemek',
    ],
    answerIndex: 3,
    explanation:
      'Korna bir çağırma veya haber verme aracı değildir; birini evden çağırmak için telefon kullanmak, mahalledeki insanları rahatsız eden gereksiz gürültünün önüne geçer.',
    whyWrong: [
      'Sürekli veya uzun korna, çevredeki herkes için gürültü kirliliği yaratır.',
      'Kısa da olsa çağırma amaçlı korna, kornanın amacı dışında kullanımıdır.',
    ],
    objective: 'Kornayı çağırma amacıyla kullanmayıp çevreyi rahatsız etmemeyi benimsemek.',
    tags: ['korna-kullanimi', 'gurultu', 'cevre-bilinci'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-309',
    subject: 'adab',
    topic: 'okul-cocuk',
    difficulty: 'kolay',
    stem: 'Okul önünde görevli bir okul geçit görevlisi, çocukları geçirmek için size "dur" işareti verdi. Doğru davranış hangisidir?',
    options: [
      'Durup görevlinin işaretine uyarak çocukların geçmesini beklemek',
      'Görevliyi dikkate almadan yavaşça geçmek',
      'Korna çalıp geçiş isteğinizi belirtmek',
      'Çocuklar geçmeden hızlıca sıyrılıp gitmek',
    ],
    answerIndex: 0,
    explanation:
      'Okul geçit görevlisinin işareti, çocukların güvenle geçmesi için verilir ve mutlaka uyulmalıdır; durup beklemek hem kuralın hem de çocuk güvenliğinin gereğidir.',
    whyWrong: [
      'Görevliyi dikkate almamak çocukları doğrudan tehlikeye atar.',
      'Kornayla veya sıyrılarak geçmek, geçit güvenliğini bozar ve saygısızlıktır.',
    ],
    objective:
      'Okul geçit görevlisinin işaretine uyup çocukların güvenliğini önceliklendirmeyi kavramak.',
    tags: ['okul-cocuk', 'okul-gecidi', 'yaya-onceligi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-310',
    subject: 'adab',
    topic: 'sabir',
    difficulty: 'kolay',
    stem: 'Hemzemin (demiryolu) geçidinde bariyerler inmeye başladı. Sabırlı ve güvenli davranış nedir?',
    options: [
      'Bariyer tam inmeden hızla karşıya geçmek',
      'Bariyerlerin arasından slalom yaparak geçmek',
      'Bariyerin önünde durup açılmasını sabırla beklemek',
      'Tren görünmüyorsa bariyeri kaldırıp geçmek',
    ],
    answerIndex: 2,
    explanation:
      'Bariyerler inmeye başladığında bir tren yaklaşıyor demektir; durup sabırla beklemek, birkaç dakikalık gecikmeyi göze alan ve hayat kurtaran bir davranıştır.',
    whyWrong: [
      'Bariyer inerken geçmeye çalışmak ölümcül bir kazaya yol açabilir.',
      'Slalom yapmak veya bariyeri kaldırmak hem yasak hem de son derece tehlikelidir.',
    ],
    objective: 'Hemzemin geçitte bariyerlere uyup sabırla beklemenin hayati önemini kavramak.',
    tags: ['sabir', 'hemzemin-gecit', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-311',
    subject: 'adab',
    topic: 'stres-yorgunluk',
    difficulty: 'orta',
    stem: 'Şehir içinde müziği oldukça yüksek sesle dinliyorsunuz. Bu durumla ilgili en doğru yaklaşım hangisidir?',
    options: [
      'Ses yüksekliği sürüşü etkilemez, sorun yoktur',
      'Sadece gece sesi kısmak yeterlidir',
      'Camlar kapalıysa istediğiniz ses seviyesinde dinleyebilirsiniz',
      'Sesi, siren ve korna gibi uyarıları duyabileceğiniz bir seviyeye indirmek',
    ],
    answerIndex: 3,
    explanation:
      'Aşırı yüksek müzik, ambulans sireni veya uyarı kornası gibi hayati sesleri duymanızı engeller; sesi bu uyarıları duyabileceğiniz seviyede tutmak trafik güvenliğinin bir parçasıdır.',
    whyWrong: [
      'Yüksek ses her saatte çevreyi rahatsız eder ve dikkati dağıtır.',
      'Camların kapalı olması, dışarıdaki uyarıları duyamama sorununu ortadan kaldırmaz.',
    ],
    objective: 'Araç içi ses seviyesini dış uyarıları duyabilecek düzeyde tutmayı kavramak.',
    tags: ['stres-yorgunluk', 'dikkat', 'siren'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-312',
    subject: 'adab',
    topic: 'engelli-yasli',
    difficulty: 'kolay',
    stem: 'Koltuk değneğiyle yürüyen bir yaya, yaya geçidinden yavaşça geçmeye çalışıyor. Doğru davranış hangisidir?',
    options: [
      'Korna çalıp geçişini hızlandırmaya çalışmak',
      'Tamamen durup güvenle geçmesi için sabırla beklemek',
      'Yanından dikkatlice sıyrılıp geçmek',
      'El işaretiyle daha hızlı yürümesini istemek',
    ],
    answerIndex: 1,
    explanation:
      'Hareket kısıtlılığı olan bir yaya daha yavaş ilerler ve aceleye getirildiğinde dengesini kaybedebilir; tam durup beklemek ona gösterilen saygının ve güvenliğin gereğidir.',
    whyWrong: [
      'Korna veya el işaretiyle acele ettirmek, dengesi kısıtlı yayayı düşürebilir.',
      'Yanından sıyrılıp geçmek, ani bir hareket karşısında büyük tehlike doğurur.',
    ],
    objective: 'Hareket kısıtlılığı olan yayalara ek sabır ve saygı göstermeyi kavramak.',
    tags: ['engelli-yasli', 'yaya-onceligi', 'sabir'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-313',
    subject: 'adab',
    topic: 'cevre-bilinci',
    difficulty: 'kolay',
    stem: 'Birini beklerken aracınızı uzun süre çalışır durumda (rölantide) bırakıyorsunuz. Çevre bilinci açısından doğru olan nedir?',
    options: [
      'Uzun beklemelerde motoru durdurup gereksiz yakıt tüketimi ve egzoz salımını önlemek',
      'Motoru çalışır bırakmak yakıt tüketmez, sorun yoktur',
      'Klima için motoru her zaman çalışır tutmak gerekir',
      'Rölantideki egzoz gazı çevreye zarar vermez',
    ],
    answerIndex: 0,
    explanation:
      'Rölantide bekleyen bir motor boşuna yakıt yakar ve egzoz gazıyla havayı kirletir; uzun beklemelerde motoru durdurmak hem çevreyi hem bütçeyi korur.',
    whyWrong: [
      'Çalışan motor rölantide de yakıt tüketir ve egzoz gazı üretir.',
      'Egzoz gazı, miktarı az bile olsa hava kirliliğine katkıda bulunur.',
    ],
    objective: 'Uzun beklemelerde motoru durdurarak gereksiz salımı önlemeyi benimsemek.',
    tags: ['cevre-bilinci', 'rolanti', 'yakit-tasarrufu'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-314',
    subject: 'adab',
    topic: 'hiz-adabi',
    difficulty: 'zor',
    stem: 'Tepe üstüne veya görüşün kapalı olduğu keskin bir viraja yaklaşıyorsunuz ve önünüzde yavaş bir araç var. Hız adabı ve güvenlik açısından ne yaparsınız?',
    options: [
      'Yol boş görünüyorsa hızlıca sollamak',
      'Selektör yapıp öndekini hızlanmaya zorlamak',
      'Görüş kapalı olsa da orta çizgiden ilerleyip fırsat kollamak',
      'Sollamaktan vazgeçip görüş mesafesine göre hızı düşürerek takip etmek',
    ],
    answerIndex: 3,
    explanation:
      'Tepe üstü ve keskin virajlarda karşıdan geleni göremezsiniz; bu noktalarda sollamamak ve görüş mesafesine göre hızı düşürmek, çarpışmayı önleyen temel bir hız adabıdır.',
    whyWrong: [
      'Yol boş "görünse" de görüş kapalıyken sollamak, karşıdan gelen araçla kafa kafaya çarpışmaya yol açar.',
      'Selektörle baskı yapmak veya orta çizgide ilerlemek tehlikeyi büyütür.',
    ],
    objective:
      'Görüşün kapalı olduğu yerlerde sollamaktan kaçınıp hızı görüşe göre ayarlamayı kavramak.',
    tags: ['hiz-adabi', 'sollama', 'gorus-mesafesi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-315',
    subject: 'adab',
    topic: 'trafik-kurallari-saygi',
    difficulty: 'orta',
    stem: 'Bir kavşakta trafik ışığı yeşil yanıyor, ancak trafik polisi sizin yönünüze "dur" işareti veriyor. Hangisine uymalısınız?',
    options: [
      'Işık yeşil olduğu için geçmek',
      'Hangisine uyacağınıza kendiniz karar vermek',
      'Trafik polisinin işaretine uymak, çünkü görevlinin işareti ışıktan önceliklidir',
      'Kornaya basıp polisin çekilmesini beklemek',
    ],
    answerIndex: 2,
    explanation:
      'Trafiği düzenleyen bir görevli varken onun işaretleri, ışık ve levhaların önüne geçer; polisin "dur" işaretine uymak hem kuraldır hem de o an bilmediğiniz bir tehlikeden sizi koruyabilir.',
    whyWrong: [
      'Işığın yeşil olması, görevlinin işaretini yok saymanızı gerektirmez.',
      'Kornayla görevliyi yönlendirmeye çalışmak hem kuralsız hem saygısızdır.',
    ],
    objective: 'Trafik görevlisinin işaretinin ışık ve levhalardan öncelikli olduğunu kavramak.',
    tags: ['trafik-kurallari-saygi', 'trafik-polisi', 'oncelik'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-316',
    subject: 'adab',
    topic: 'empati',
    difficulty: 'orta',
    stem: 'Dik bir yokuşta önünüzdeki araç kalkışta zorlanıp bir miktar geri kayıyor. Empatik ve güvenli davranış nedir?',
    options: [
      'Takip mesafesini artırıp araca yeterli alan bırakmak',
      'Dibine kadar yaklaşıp baskı yapmak',
      'Korna çalıp acele ettirmek',
      'Selektör yapıp sıkıştırmak',
    ],
    answerIndex: 0,
    explanation:
      'Yokuşta kalkış herkes için zorlayıcı olabilir; öne fazla sokulmayıp mesafe bırakmak, hem geri kayması olası araca alan tanır hem de sürücüyü baskı altına almadan anlayış gösterir.',
    whyWrong: [
      'Dibine yaklaşmak, araç geri kayarsa çarpışmaya davetiye çıkarır.',
      'Korna ve selektörle baskı, zorlanan sürücüyü daha çok telaşlandırıp hata yaptırır.',
    ],
    objective: 'Yokuşta zorlanan sürücüye mesafe bırakıp empatiyle davranmayı kavramak.',
    tags: ['empati', 'yokus', 'takip-mesafesi'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-317',
    subject: 'adab',
    topic: 'paylasim',
    difficulty: 'kolay',
    stem: 'Şehir içinde yol kenarında ilerleyen bir bisikletliyi sollayacaksınız. Doğru davranış hangisidir?',
    options: [
      'Bisikletlinin hemen yanından hızla geçmek',
      'Yeterli yan güvenlik mesafesi bırakıp hızı azaltarak sollamak',
      'Korna çalıp bisikletliyi iyice kenara itmek',
      '"Bisikletli engel" deyip sıkıştırarak geçmek',
    ],
    answerIndex: 1,
    explanation:
      'Bisikletli, yolu paylaşan korunması gereken bir yol kullanıcısıdır; hızı azaltıp yeterli yan mesafe bırakarak sollamak, olası bir dengesizlik anında onu korur.',
    whyWrong: [
      'Yanından hızla ve yakın geçmek, oluşan hava akımıyla bisikletlinin dengesini bozabilir.',
      'Kornayla itmek veya sıkıştırmak, bisikletliyi düşme tehlikesiyle karşı karşıya bırakır.',
    ],
    objective:
      'Bisikletlileri sollarken yeterli yan mesafe bırakıp yolu güvenle paylaşmayı kavramak.',
    tags: ['paylasim', 'bisiklet', 'sollama'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-318',
    subject: 'adab',
    topic: 'cevre-bilinci',
    difficulty: 'orta',
    stem: 'Yakıt tüketimini ve egzoz salımını azaltmak isteyen çevre bilincine sahip bir sürücü nasıl davranır?',
    options: [
      'Sürekli ani hızlanıp ani fren yaparak ilerler',
      'Sürekli yüksek devirde ve gereksiz yüksek hızda sürer',
      'Yumuşak gaz-fren, uygun vites ve düzenli bir hızla ekonomik sürüş yapar',
      'Her durakta gaza basarak motoru yüksek devirde tutar',
    ],
    answerIndex: 2,
    explanation:
      'Yumuşak ivmelenme, uygun viteste sürüş ve düzenli hız, yakıt tüketimini ve dolayısıyla egzoz salımını belirgin biçimde azaltır; bu, çevreye saygının somut bir uygulamasıdır.',
    whyWrong: [
      'Ani gaz-fren ve yüksek devirli sürüş yakıt tüketimini ve emisyonu artırır.',
      'Motoru gereksiz yere yüksek devirde tutmak hem yakıt harcar hem çevreyi kirletir.',
    ],
    objective: 'Ekonomik ve yumuşak sürüşün çevreye ve yakıt tasarrufuna katkısını kavramak.',
    tags: ['cevre-bilinci', 'ekonomik-surus', 'emisyon'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-319',
    subject: 'adab',
    topic: 'yaya-onceligi',
    difficulty: 'zor',
    stem: 'Çok şeritli bir yolda durup bir yayayı karşıya geçmesi için el işaretiyle çağırmak istiyorsunuz. Bu davranışın en önemli sakıncası nedir?',
    options: [
      'Yan şeritteki başka bir aracı göremeyebilirsiniz; yayayı çağırmak, onu göremeyen sürücünün önüne itebilir',
      'Yayayı çağırmak her zaman en güvenli davranıştır',
      'El işareti trafiği hızlandırdığı için sorun yoktur',
      'Yaya zaten kendi güvenliğinden sorumludur, sizin için sakıncası yoktur',
    ],
    answerIndex: 0,
    explanation:
      'Çok şeritli yolda siz durup yol verseniz de yan şeritteki araç yayayı görmeyebilir; onu "geç" diye çağırmak, hiç beklemediği bir aracın önüne çıkmasına neden olabilir. Doğrusu, kendi şeridinizde durup yayanın kendi kararıyla ve tüm şeritleri görerek geçmesine izin vermektir.',
    whyWrong: [
      'Yayayı çağırmak, göremediğiniz diğer şeritler yüzünden her zaman güvenli değildir.',
      '"Sorumluluk yayada" veya "trafiği hızlandırır" mantığı, oluşabilecek ölümcül riski görmezden gelir.',
    ],
    objective: 'Çok şeritli yolda yayayı körü körüne çağırmanın gizli tehlikesini kavramak.',
    tags: ['yaya-onceligi', 'cok-serit', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-320',
    subject: 'adab',
    topic: 'ofke-yonetimi',
    difficulty: 'orta',
    stem: 'Bir sürücü size kaba bir el hareketi yapıp bağırdı. Öfke yönetimi açısından en doğru tepki nedir?',
    options: [
      'Aynı el hareketini ona da yapmak',
      'Peşine takılıp hesap sormak',
      'Tepki vermeyip görmezden gelerek sakin bir şekilde yolunuza devam etmek',
      'Yanına yaklaşıp gözdağı vermek',
    ],
    answerIndex: 2,
    explanation:
      'Kaba bir davranışa karşılık vermek yalnızca gerilimi tırmandırır; tepki vermeyip sakin kalmak, hem çatışmayı bitirir hem de olgunluğun ve öz güvenin göstergesidir.',
    whyWrong: [
      'Aynı hareketle karşılık vermek veya peşine takılmak sözlü tartışmayı fiziksel bir çatışmaya taşıyabilir.',
      'Gözdağı vermek tehlikeli manevralara ve yeni kazalara yol açar.',
    ],
    objective: 'Provokasyona karşılık vermeden öfkeyi kontrol etmeyi kavramak.',
    tags: ['ofke-yonetimi', 'provokasyon', 'sakinlik'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-321',
    subject: 'adab',
    topic: 'sorumluluk',
    difficulty: 'zor',
    stem: 'Aracınız otoyolda arıza yapıp durdu. Kendinizin ve diğerlerinin güvenliği için en doğru davranış hangisidir?',
    options: [
      'Araçta oturup yardım gelmesini beklemek',
      'Aracın yanında ayakta durup telefonla ilgilenmek',
      'Dörtlüleri yakmadan aracı ittirmeye çalışmak',
      'Dörtlüleri yakıp mümkünse aracı emniyet şeridine almak, reflektörlü üçgeni uygun mesafeye koymak ve yolcularla bariyerin güvenli tarafına geçmek',
    ],
    answerIndex: 3,
    explanation:
      'Arızada öncelik görünürlük ve güvenli alandır: dörtlüler ve reflektörlü üçgen sizi arkadan gelenlere önceden haber verir, bariyerin güvenli tarafına geçmek ise olası bir çarpmadan sizi korur.',
    whyWrong: [
      'Araçta veya taşıt yolu tarafında beklemek, arkadan gelen bir araç çarparsa ölümcül olabilir.',
      'Uyarı işareti koymadan aracı ittirmek, siz ve araç için büyük tehlike yaratır.',
    ],
    objective:
      'Yolda kalınca görünürlük ve güvenli bekleme adımlarını doğru sırayla uygulamayı kavramak.',
    tags: ['sorumluluk', 'ariza', 'reflektor'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-322',
    subject: 'adab',
    topic: 'okul-cocuk',
    difficulty: 'orta',
    stem: 'Çocukların oynadığı bir bölgede geri manevra yaparak park yerinden çıkacaksınız. En güvenli davranış hangisidir?',
    options: [
      'Manevradan önce arkayı ve çevreyi kontrol etmek, gerekirse inip bakmak ve çok yavaş ilerlemek',
      'Sadece dikiz aynasına bakıp hızlıca geri çıkmak',
      'Korna çalıp çocuklar kaçsın diye beklemek',
      '"Arkada kimse yoktur" varsayıp normal hızda geri gitmek',
    ],
    answerIndex: 0,
    explanation:
      'Küçük çocuklar aracın arkasındaki kör alanda kolayca gözden kaçar; manevra öncesi çevreyi kontrol etmek, gerekirse inip bakmak ve çok yavaş ilerlemek bu ölümcül riski önler.',
    whyWrong: [
      'Sadece aynaya bakmak, aracın hemen arkasındaki alçak boylu bir çocuğu göstermeyebilir.',
      'Kornaya güvenmek veya "kimse yoktur" varsaymak, öngörülemeyen çocuk hareketlerini hesaba katmaz.',
    ],
    objective:
      'Çocukların bulunduğu alanda geri manevrayı kör alan kontrolüyle güvenli yapmayı kavramak.',
    tags: ['okul-cocuk', 'geri-manevra', 'kor-alan'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-323',
    subject: 'adab',
    topic: 'hiz-adabi',
    difficulty: 'orta',
    stem: 'Yol kenarında dörtlüleri yanan, arıza yapmış bir araç ve yanında bekleyen insanlar görüyorsunuz. Doğru davranış nedir?',
    options: [
      'Aynı hızda yanlarından geçmek',
      'Korna çalıp uzaklaşmalarını istemek',
      'Hızı azaltıp, mümkünse yan şeride geçerek onlara güvenli mesafe bırakmak',
      'Merak edip yavaşlayarak uzun uzun bakmak ve trafiği aksatmak',
    ],
    answerIndex: 2,
    explanation:
      'Yol kenarında bekleyen insanlar korunmasızdır; hızı azaltıp mümkünse bir şerit uzaktan geçmek, onlara güvenli bir alan bırakır ve olası bir kazayı önler.',
    whyWrong: [
      'Aynı hızda ve yakın geçmek, kenardaki kişiler için ciddi risk oluşturur.',
      'Sadece merakla yavaşlayıp bakmak (dikizlemek) arkadaki trafiği aksatır ve zincirleme kazalara yol açabilir.',
    ],
    objective:
      'Yol kenarındaki arıza/kaza noktalarında hız kesip güvenli mesafe bırakmayı kavramak.',
    tags: ['hiz-adabi', 'yol-kenari', 'guvenli-mesafe'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-324',
    subject: 'adab',
    topic: 'engelli-yasli',
    difficulty: 'kolay',
    stem: 'Önünüzdeki araçta yaşlı bir sürücü var; temkinli ve tereddütlü ilerliyor. Hoşgörülü davranış hangisidir?',
    options: [
      'Korna ve selektörle acele ettirmek',
      'Takip mesafesini koruyup anlayışla, baskı yapmadan ilerlemek',
      'Dibine yaklaşıp sıkıştırmak',
      'Yanına gelip el kol hareketiyle uyarmak',
    ],
    answerIndex: 1,
    explanation:
      'Yaşlı bir sürücünün daha temkinli olması doğaldır; ona mesafe bırakıp baskı yapmadan ilerlemek, hem güvenli hem de yaşa gösterilen saygıyı yansıtan hoşgörülü bir tutumdur.',
    whyWrong: [
      'Korna, selektör ve sıkıştırma yaşlı sürücüyü paniğe sürükleyip hata yaptırabilir.',
      'Yanına gelip uyarmak dikkat dağıtır ve tehlike yaratır.',
    ],
    objective: 'Yaşlı ve temkinli sürücülere hoşgörü ve mesafeyle yaklaşmayı kavramak.',
    tags: ['engelli-yasli', 'hosgoru', 'takip-mesafesi'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-325',
    subject: 'adab',
    topic: 'gecis-ustunlugu',
    difficulty: 'orta',
    stem: 'Kavşakta ışık size yeşil yandı, tam geçecekken yandan sirenli bir itfaiye aracı kavşağa giriyor. Ne yapmalısınız?',
    options: [
      'Yeşil bile olsa durup geçiş üstünlüğü olan araca yol vermek',
      '"Işık yeşil, geçiş hakkı bende" deyip devam etmek',
      'Hızlanıp itfaiyeden önce kavşağı geçmek',
      'Korna çalıp itfaiyeyi durdurmaya çalışmak',
    ],
    answerIndex: 0,
    explanation:
      'Geçiş üstünlüğü olan araçlar, ışık yeşil olsa bile önceliğe sahiptir; durup yol vermek yasal bir zorunluluktur ve itfaiyenin bir an önce olay yerine ulaşmasını sağlar.',
    whyWrong: [
      'Yeşil ışık, geçiş üstünlüğü aracının önüne çıkma hakkı vermez.',
      'Hızlanıp geçmeye çalışmak veya kornayla durdurmaya kalkmak ağır bir kaza riski yaratır.',
    ],
    objective: 'Yeşil ışıkta bile geçiş üstünlüğü aracına yol verme zorunluluğunu kavramak.',
    tags: ['gecis-ustunlugu', 'itfaiye', 'kavsak'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-326',
    subject: 'adab',
    topic: 'trafik-kurallari-saygi',
    difficulty: 'kolay',
    stem: 'Bir kavşakta "DUR" levhası var ve yol boş görünüyor. Doğru davranış hangisidir?',
    options: [
      'Yol boşsa yavaşlayıp durmadan geçmek',
      'Tam olarak durup güvenliği kontrol ettikten sonra geçmek',
      'Sadece hızı biraz azaltmak yeterlidir',
      'Levhayı görmezden gelip normal hızda geçmek',
    ],
    answerIndex: 1,
    explanation:
      '"DUR" levhası, yol boş görünse bile tam duruş yapıp gelen olmadığından emin olmayı gerektirir; bu kısa duruş, göremediğiniz bir aracın yaratacağı kazayı önler.',
    whyWrong: [
      'Yavaşlayıp durmadan geçmek, "DUR" levhasının anlamına ve kurala aykırıdır.',
      'Sadece hız azaltmak veya levhayı yok saymak, kör noktadaki bir tehlikeyi gözden kaçırmanıza yol açabilir.',
    ],
    objective: '"DUR" levhasında yol boş olsa bile tam duruş yapma kuralına saygıyı kavramak.',
    tags: ['trafik-kurallari-saygi', 'dur-levhasi', 'kavsak'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-327',
    subject: 'adab',
    topic: 'sabir',
    difficulty: 'orta',
    stem: 'Yol çalışması nedeniyle yol tek şeride düşmüş ve bir işaretçi (bayrakçı) trafiği sırayla yönlendiriyor. Doğru davranış nedir?',
    options: [
      'İşaretçiyi dikkate almadan ilerlemek',
      'Karşı yönden gelenleri beklemeden geçmek',
      'İşaretçinin yönlendirmesine uyup sıranızı sabırla beklemek',
      'Korna çalıp önündekileri sıkıştırmak',
    ],
    answerIndex: 2,
    explanation:
      'Tek şeride düşen yolda trafiği güvenle akıtmak için işaretçi karşılıklı geçişi sırayla düzenler; onun yönlendirmesine uyup sabırla beklemek hem kural hem de kaza önlemenin gereğidir.',
    whyWrong: [
      'İşaretçiyi yok sayıp geçmek, karşı yönden gelen araçla kafa kafaya çarpışmaya yol açabilir.',
      'Kornayla baskı yapmak düzeni bozar ve çalışan işçiler için tehlike yaratır.',
    ],
    objective:
      'Yol çalışmasında işaretçinin yönlendirmesine uyup sırayla ve sabırla geçmeyi kavramak.',
    tags: ['sabir', 'yol-calismasi', 'isaretci'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-328',
    subject: 'adab',
    topic: 'paylasim',
    difficulty: 'kolay',
    stem: 'Şerit değiştirmeden önce trafikte motosikletlilerle yolu paylaşan bir sürücü ne yapmalıdır?',
    options: [
      'Sadece öndeki araçlara bakıp şeridi değiştirmek',
      'Ayna kontrolüyle birlikte kör noktayı da kontrol edip motosikletli olup olmadığına bakmak',
      'Motosikletler küçük olduğu için onları dikkate almamak',
      'Sinyal vermeden hızlıca geçmek',
    ],
    answerIndex: 1,
    explanation:
      'Motosikletler küçük olduğu için aynalarda ve kör noktada kolayca gözden kaçar; şerit değiştirmeden önce kör noktayı da kontrol etmek, yolu paylaşan motosikletlileri korur.',
    whyWrong: [
      'Sadece öne veya aynaya bakmak, kör noktadaki bir motosikletliyi kaçırmanıza yol açar.',
      'Motosikletleri önemsememek veya sinyalsiz geçmek ölümcül kazalara neden olur.',
    ],
    objective:
      'Şerit değiştirmeden önce motosikletliler için kör nokta kontrolünü alışkanlık edinmek.',
    tags: ['paylasim', 'motosiklet', 'kor-nokta'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-329',
    subject: 'adab',
    topic: 'stres-yorgunluk',
    difficulty: 'orta',
    stem: 'Beklemediğiniz bir trafik sıkışıklığına yakalandınız ve gerginliğiniz artıyor. Stresi yönetmenin sağlıklı yolu nedir?',
    options: [
      'Sürekli şerit değiştirip boşluk aramak',
      'Öndeki araçlara sinirlenip korna çalmak',
      'Emniyet şeridine geçip trafiği aşmaya çalışmak',
      'Gecikmeyi kabullenip derin nefes alarak, sakin kalıp güvenli sürüşe odaklanmak',
    ],
    answerIndex: 3,
    explanation:
      'Sıkışıklık çoğu zaman kontrolünüz dışındadır; durumu kabullenip sakinleşmek, stresin kararlarınızı bozmasını önler ve gereksiz risklere girmenizi engeller.',
    whyWrong: [
      'Sürekli şerit değiştirmek ve korna çalmak ne trafiği açar ne de stresi azaltır; yalnızca riski artırır.',
      'Emniyet şeridini kişisel çıkar için kullanmak hem yasak hem de acil araçların geçişini engeller.',
    ],
    objective:
      'Kontrol dışı sıkışıklıkta durumu kabullenip stresi güvenli biçimde yönetmeyi kavramak.',
    tags: ['stres-yorgunluk', 'trafik-sikisikligi', 'sakinlik'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-330',
    subject: 'adab',
    topic: 'empati',
    difficulty: 'orta',
    stem: 'Rüzgarlı ve yağmurlu havada önünüzdeki motosikletli, dengesini korumak için şerit içinde biraz daha geniş seyrediyor. Empatik davranış nedir?',
    options: [
      'Dibine yaklaşıp geçmesi için baskı yapmak',
      'Korna çalıp kenara çekilmesini istemek',
      'Takip mesafesini artırıp ona daha fazla alan bırakarak anlayış göstermek',
      'Sıkışıp yanından hızla geçmek',
    ],
    answerIndex: 2,
    explanation:
      'Motosikletli, kötü havada dengesini korumak için konumunu ayarlar ve dış etkilere çok daha açıktır; ona mesafe ve alan bırakmak, kendini onun yerine koyan empatik ve güvenli bir tutumdur.',
    whyWrong: [
      'Baskı yapmak veya korna çalmak, dengesini korumaya çalışan sürücüyü düşürebilir.',
      'Sıkışıp hızla geçmek, oluşan hava akımıyla motosikletlinin dengesini bozar.',
    ],
    objective:
      'Kötü hava koşullarında motosikletlilere alan bırakıp empatiyle davranmayı kavramak.',
    tags: ['empati', 'motosiklet', 'kotu-hava'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-331',
    subject: 'adab',
    topic: 'nezaket',
    difficulty: 'kolay',
    stem: 'Otoyolda şerit değiştirirken bir kamyon yavaşlayıp sizi araya aldı. Nazik bir teşekkür için ne yapabilirsiniz?',
    options: [
      'Hiçbir şey yapmadan devam etmek',
      'Uzun uzun korna çalmak',
      'Kısa süre dörtlüleri (flaşör) yakıp teşekkür ettiğinizi belirtmek',
      'Hızlanıp önünden hemen uzaklaşmak',
    ],
    answerIndex: 2,
    explanation:
      'Otoyolda size yol veren bir sürücüye kısa süre dörtlü yakarak teşekkür etmek yaygın ve nazik bir işarettir; bu jest, trafikte olumlu bir iletişim kültürünü besler.',
    whyWrong: [
      'Karşılık vermemek, gösterilen inceliği görmezden gelmektir.',
      'Uzun korna teşekkür yerine rahatsızlık izlenimi verir; hemen uzaklaşmak da jesti değersiz kılar.',
    ],
    objective:
      'Yol veren sürücülere uygun bir işaretle (dörtlü) nezaketle teşekkür etmeyi kavramak.',
    tags: ['nezaket', 'tesekkur', 'otoyol'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-332',
    subject: 'adab',
    topic: 'yaya-onceligi',
    difficulty: 'kolay',
    stem: 'Kavşakta ışığınız yeşile döndü, ama bir yaya karşıdan karşıya geçişini henüz tamamlamadı. Ne yaparsınız?',
    options: [
      'Yeşil yandığı için korna çalıp yayayı uyarmak',
      'Yaya geçişini tamamlayana kadar bekleyip sonra hareket etmek',
      'Yayanın arkasından hızla geçmek',
      'Yayanın önünden sıyrılıp geçmek',
    ],
    answerIndex: 1,
    explanation:
      'Işığın yeşile dönmesi, geçişini tamamlamamış bir yayanın üstüne yürüme hakkı vermez; onun güvenle karşıya ulaşmasını beklemek yaya önceliğinin ve nezaketin gereğidir.',
    whyWrong: [
      'Kornayla yayayı sıkıştırmak paniğe ve dengesizliğe yol açar.',
      'Önünden veya arkasından hızla geçmek, ani bir hareket karşısında kazaya davetiye çıkarır.',
    ],
    objective: 'Yeşil ışıkta bile geçişini tamamlamamış yayaya öncelik vermeyi kavramak.',
    tags: ['yaya-onceligi', 'kavsak', 'sabir'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-333',
    subject: 'adab',
    topic: 'okul-cocuk',
    difficulty: 'orta',
    stem: 'Okul çıkış saatinde bir okulun önünden geçiyorsunuz; kaldırımda ve çevrede çok sayıda çocuk var. En doğru davranış nedir?',
    options: [
      'Hızı iyice düşürüp her an durmaya hazır ilerlemek ve okul önüne çift park etmemek',
      'Normal şehir hızını koruyup dikkatli bakmak',
      'Korna çalıp çocukların kenara çekilmesini istemek',
      'Kısa süre için okul kapısının önüne çift park etmek',
    ],
    answerIndex: 0,
    explanation:
      'Okul çıkışında çocuklar ani ve öngörülemez hareket edebilir; hızı iyice düşürmek, her an durmaya hazır olmak ve görüşü kapatan çift parktan kaçınmak çocuk güvenliğinin gereğidir.',
    whyWrong: [
      'Normal hızı korumak, aniden yola çıkan bir çocuğa tepki mesafesi bırakmaz.',
      'Kornayla acele ettirmek veya çift park etmek, görüşü kapatıp çocuklar için tehlike yaratır.',
    ],
    objective: 'Okul çıkış saatinde hızı düşürüp yolu tıkamamayı çocuk güvenliği için kavramak.',
    tags: ['okul-cocuk', 'hiz-adabi', 'cift-park'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-334',
    subject: 'adab',
    topic: 'sorumluluk',
    difficulty: 'orta',
    stem: 'Bir arkadaşınızın kullandığı araçta yolcusunuz. İyi ve sorumlu bir yolcu olarak nasıl davranırsınız?',
    options: [
      'Sürücünün dikkatini dağıtmamak, gerekirse yol tarifi veya navigasyon konusunda yardımcı olmak',
      'Sürücüyü daha hızlı gitmesi için sürekli teşvik etmek',
      'Yüksek sesle şakalaşıp sürücünün gözünü yoldan ayırtmak',
      'Sürekli telefonu sürücünün önüne tutup bir şeyler göstermek',
    ],
    answerIndex: 0,
    explanation:
      'Trafik güvenliği sadece sürücünün değil yolcunun da sorumluluğudur; dikkatini dağıtmamak ve gerektiğinde yol tarifiyle yardımcı olmak, iyi bir yolcunun katkısıdır.',
    whyWrong: [
      'Sürücüyü hızlanmaya teşvik etmek onu riskli davranışa iter.',
      'Yüksek sesle oyalamak veya telefon göstermek sürücünün dikkatini yoldan ayırıp kazaya yol açabilir.',
    ],
    objective: 'Yolcunun da trafik güvenliğine katkı sağlama sorumluluğunu kavramak.',
    tags: ['sorumluluk', 'yolcu', 'dikkat'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-335',
    subject: 'adab',
    topic: 'ofke-yonetimi',
    difficulty: 'orta',
    stem: 'Uzun bir kırmızı ışıkta ve yoğun trafikte giderek sinirleniyor, direksiyona vurmak istiyorsunuz. Öfkenizi yönetmek için en doğru yol nedir?',
    options: [
      'Kornaya asılıp gerginliği boşaltmak',
      'Öndeki araçları suçlayıp yüksek sesle söylenmek',
      'Boşluk buldukça agresif manevralarla ilerlemek',
      'Derin nefes alıp beklemenin geçici olduğunu hatırlayarak sakinleşmek',
    ],
    answerIndex: 3,
    explanation:
      'Trafikte biriken gerginlik, farkında olmadan agresif kararlara dönüşebilir; derin nefes almak ve durumun geçici olduğunu hatırlamak, öfkeyi büyümeden yatıştıran basit ve etkili bir yöntemdir.',
    whyWrong: [
      'Kornaya asılmak veya söylenmek trafiği açmaz, yalnızca çevreyi rahatsız eder.',
      'Agresif manevralar birikmiş öfkeyi tehlikeli davranışlara çevirip kaza riskini artırır.',
    ],
    objective: 'Trafikte biriken gerginliği nefes ve farkındalıkla yatıştırmayı kavramak.',
    tags: ['ofke-yonetimi', 'sakinlik', 'oz-kontrol'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-336',
    subject: 'adab',
    topic: 'engelli-yasli',
    difficulty: 'kolay',
    stem: 'Karşıya geçmek isteyen bir yaya, kornayı ve çevresel sesleri fark etmiyor ve işitme engelli olabileceğini düşünüyorsunuz. Doğru davranış nedir?',
    options: [
      'Duyana kadar korna çalmaya devam etmek',
      'Sesli uyarı yapıp geçmesini beklemek',
      'Göz teması kurmaya çalışıp tam durarak, temkinle geçişini beklemek',
      'Duymuyorsa hızlıca yanından geçmek',
    ],
    answerIndex: 2,
    explanation:
      'İşitme engelli bir yaya sesli uyarıları algılayamaz; korna ve sesli işaret yerine göz teması kurup tam durarak beklemek, ona güvenli ve saygılı bir geçiş sağlar.',
    whyWrong: [
      'Korna ve sesli uyarı, işitme engelli bir yayaya ulaşmaz; yalnızca çevreyi rahatsız eder.',
      'Duymuyor diye hızla yanından geçmek, ani hareketi karşısında ciddi tehlike doğurur.',
    ],
    objective:
      'İşitme engelli olabilecek yayalara görsel iletişimle ve tam durarak yaklaşmayı kavramak.',
    tags: ['engelli-yasli', 'yaya-onceligi', 'iletisim'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-337',
    subject: 'adab',
    topic: 'korna-kullanimi',
    difficulty: 'orta',
    stem: 'Görüşün kapalı olduğu dar bir geçitte veya kör bir köşede ilerliyorsunuz. Kornanın yerinde (doğru) kullanımı hangisidir?',
    options: [
      'Karşıdan gelen olursa korkutmak için uzun korna çalmak',
      'Varlığınızı önceden haber vermek için kısa bir korna çalmak',
      'Korna çalmaya hiç gerek yoktur, hızlıca geçmek en iyisidir',
      'Sürekli korna çalarak geçmek',
    ],
    answerIndex: 1,
    explanation:
      'Kornanın asıl amacı tehlikeyi önlemektir; görüşün kapalı olduğu kör köşede kısa bir korna ile varlığınızı haber vermek, karşıdan geleni uyaran doğru ve yerinde bir kullanımdır.',
    whyWrong: [
      'Uzun veya sürekli korna karşı tarafı ürkütür ve gereksiz gürültü yaratır.',
      'Kör köşede hiç uyarı vermeden hızlı geçmek, ani karşılaşmada kaza riskini artırır.',
    ],
    objective:
      'Kör köşelerde kısa kornayı bir uyarı/haber verme aracı olarak doğru kullanmayı kavramak.',
    tags: ['korna-kullanimi', 'kor-kose', 'uyari'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-338',
    subject: 'adab',
    topic: 'yaya-onceligi',
    difficulty: 'orta',
    stem: 'Trafik sıkışık ve yavaş ilerliyor; tam yaya geçidinin üzerinde durmak üzeresiniz. Doğru davranış nedir?',
    options: [
      'Yaya geçidini boş bırakacak şekilde geçidin gerisinde durmak',
      'Geçidin üzerinde durup trafiğin açılmasını beklemek',
      'Yayalar arasından ilerleyip geçidi geçmek',
      'Yaya geçidini kısmen kapatarak durmak',
    ],
    answerIndex: 0,
    explanation:
      'Yaya geçidi yalnızca yayalara aittir; sıkışıklıkta geçidin üzerine çıkmadan gerisinde durmak, yayaların taşıt yoluna inmeden güvenle geçmesini sağlar.',
    whyWrong: [
      'Geçidin üzerinde durmak yayaları araçların arasından geçmeye zorlar.',
      'Geçidi kısmen kapatmak veya yayalar arasından ilerlemek yaya güvenliğini bozar.',
    ],
    objective: 'Sıkışık trafikte yaya geçidini boş tutup yaya geçişini engellememeyi kavramak.',
    tags: ['yaya-onceligi', 'trafik-sikisikligi', 'yaya-gecidi'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-339',
    subject: 'adab',
    topic: 'stres-yorgunluk',
    difficulty: 'zor',
    stem: 'Tek başınıza uzun bir yolculuğa çıkacaksınız. Yorgunluk ve dikkat kaybını önlemek için en doğru plan hangisidir?',
    options: [
      'Molasız gidip bir an önce varmaya çalışmak',
      'Yorulunca kahve içip devam etmek yeterlidir',
      'Düzenli aralıklarla (yaklaşık her iki saatte bir) mola vermek ve mümkünse sürüşü paylaşmak',
      'Yorgunluk hissedince hızlanıp yolu kısaltmak',
    ],
    answerIndex: 2,
    explanation:
      'Uzun yolda yorgunluk tepki süresini ve dikkati düşürür; düzenli molalar ve mümkünse sürüşü paylaşmak, yorgunluğun birikip tehlikeye dönüşmesini önleyen sorumlu bir plandır.',
    whyWrong: [
      'Molasız sürmek yorgunluğu biriktirip mikro uykulara ve kazaya yol açabilir.',
      'Kahve ya da hızlanmak yorgunluğu yalnızca kısa süre erteler, çözmez ve riski artırır.',
    ],
    objective: 'Uzun yolculukta molalarla ve sürüş paylaşımıyla yorgunluğu önlemeyi kavramak.',
    tags: ['stres-yorgunluk', 'uzun-yol', 'mola'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-340',
    subject: 'adab',
    topic: 'trafik-kurallari-saygi',
    difficulty: 'orta',
    stem: 'Işık ve levha bulunmayan, eşdeğer yolların kesiştiği kontrolsüz bir kavşağa aynı anda iki araç yaklaştı. Kim yol vermelidir?',
    options: [
      'Daha hızlı olan araç önce geçer',
      'Daha büyük olan araç önce geçer',
      'Korna çalan araç önce geçer',
      'Sağdan gelen araca yol verilir; yani kendi sağınızdaki araca öncelik tanınır',
    ],
    answerIndex: 3,
    explanation:
      'Kontrolsüz ve eşdeğer kavşaklarda öncelik sağdan gelenindir; bu kurala uymak, herkesin aynı anda geçmeye çalışmasından doğacak karmaşayı ve kazayı önler.',
    whyWrong: [
      'Hız, büyüklük veya korna öncelik kazandırmaz; bunlar kişisel dayatmalardır.',
      'Bu yanlış ölçütlere göre davranmak kavşakta çarpışmaya yol açar.',
    ],
    objective: 'Kontrolsüz eşdeğer kavşakta sağdan gelene yol verme kuralını kavramak.',
    tags: ['trafik-kurallari-saygi', 'kontrolsuz-kavsak', 'yol-verme'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-341',
    subject: 'adab',
    topic: 'paylasim',
    difficulty: 'orta',
    stem: 'Otoyolda büyük bir kamyonun (TIR) hemen önüne geçip ardından hızlıca yavaşlamak üzeresiniz. Bu neden tehlikelidir ve ne yapmalısınız?',
    options: [
      'Kamyonlar çok hızlı durabildiği için sakıncası yoktur',
      'Kamyonların fren mesafesi uzundur; önlerine ani girip kesmemeli, yeterli boşluk bırakmalısınız',
      'Kamyonun önünde yavaşlamak onu uyarır, bu yüzden faydalıdır',
      'Kamyonun kör noktasında kalıp beklemek en güvenlisidir',
    ],
    answerIndex: 1,
    explanation:
      'Ağır araçların durma mesafesi çok daha uzundur; önlerine ani girip yavaşlamak, kamyonun zamanında duramayıp size çarpmasına yol açabilir. Doğrusu, yeterli boşluk bırakıp kör noktalarında oyalanmamaktır.',
    whyWrong: [
      'Kamyonlar ağır olduğu için hızlı duramaz; bu yüzden önlerini kesmek çok risklidir.',
      'Önünde yavaşlamak "uyarı" değil tehlike yaratır; kör noktada kalmak da görülmemenize neden olur.',
    ],
    objective:
      'Ağır araçların uzun fren mesafesini gözetip önlerini kesmemeyi ve kör noktalarından kaçınmayı kavramak.',
    tags: ['paylasim', 'kamyon', 'fren-mesafesi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-342',
    subject: 'adab',
    topic: 'stres-yorgunluk',
    difficulty: 'kolay',
    stem: 'Önemli bir randevunuz var ve trafikte acele etmekten kaynaklanan stresi yaşamak istemiyorsunuz. En doğru yaklaşım nedir?',
    options: [
      'Son dakikada çıkıp trafikte hızlanarak yetişmeye çalışmak',
      'Geç kalınca riskli manevralarla zaman kazanmaya çalışmak',
      'Trafik kötüyse emniyet şeridini kullanmak',
      'Yola erken çıkıp zaman baskısını ve acele stresini baştan önlemek',
    ],
    answerIndex: 3,
    explanation:
      'Acele stresinin çoğu, geç çıkmaktan doğar; erken yola çıkıp zaman payı bırakmak, trafikte gerginlik ve riskli davranış ihtiyacını en baştan ortadan kaldırır.',
    whyWrong: [
      'Son dakikada çıkıp hızlanmak, zaman baskısını ve kaza riskini artırır.',
      'Riskli manevralar ve emniyet şeridi kullanımı hem tehlikeli hem yasaktır.',
    ],
    objective: 'Erken yola çıkarak zaman baskısı stresini önlemeyi kavramak.',
    tags: ['stres-yorgunluk', 'planlama', 'acele'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-343',
    subject: 'adab',
    topic: 'trafik-kurallari-saygi',
    difficulty: 'kolay',
    stem: 'Kısa bir mesafeye gideceksiniz ve araçta arka koltukta da yolcu var. Emniyet kemeri konusunda doğru olan nedir?',
    options: [
      'Kısa yolda bile ön ve arka tüm yolcular emniyet kemerini takmalıdır',
      'Kısa mesafede kemer takmaya gerek yoktur',
      'Sadece ön koltuktakiler kemer takmalıdır',
      'Arka koltukta kemer takmak isteğe bağlıdır',
    ],
    answerIndex: 0,
    explanation:
      'Kazaların önemli kısmı kısa mesafelerde ve düşük hızda olur; ön-arka tüm yolcuların kemer takması, olası bir çarpışmada savrulmayı önleyen hayati bir kuraldır.',
    whyWrong: [
      'Kısa mesafe veya düşük hız, kemeri gereksiz kılmaz; kaza her an olabilir.',
      'Arka koltukta kemersiz oturmak, ani frende ciddi yaralanmaya yol açar.',
    ],
    objective: 'Kısa yolda ve tüm koltuklarda emniyet kemeri kullanımının zorunluluğunu kavramak.',
    tags: ['trafik-kurallari-saygi', 'emniyet-kemeri', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-344',
    subject: 'adab',
    topic: 'ofke-yonetimi',
    difficulty: 'zor',
    stem: 'Dar bir kavşakta karşı sürücüyle "yol hakkı benim" diye inatlaşıyorsunuz ve ikiniz de geçmiyorsunuz. En olgun çözüm nedir?',
    options: [
      '"Hakkımı savunurum" deyip inatla beklemeye devam etmek',
      'Egoyu bir kenara bırakıp feragat ederek karşı sürücüye yol vermek ve tıkanıklığı çözmek',
      'Korna çalıp karşı tarafı geri gitmeye zorlamak',
      'Aracı yavaşça karşıya doğru sürüp gözdağı vermek',
    ],
    answerIndex: 1,
    explanation:
      'İnatlaşma yolu tümüyle kilitler ve kimseye fayda sağlamaz; küçük bir feragatle yol vermek, hem tıkanıklığı hem de gereksiz gerilimi en hızlı biçimde çözen olgun bir davranıştır.',
    whyWrong: [
      'İnatla beklemek yolu kilitler ve gerginliği tırmandırır.',
      'Kornayla zorlamak veya araçla gözdağı vermek çatışmayı büyütür, çözmez.',
    ],
    objective: 'Yol hakkı tartışmasında egoyu bırakıp feragatle çözüm üretmeyi kavramak.',
    tags: ['ofke-yonetimi', 'feragat', 'inatlasma'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-345',
    subject: 'adab',
    topic: 'cevre-bilinci',
    difficulty: 'orta',
    stem: 'Şehir içi kısa mesafelerde trafik yoğunluğunu ve hava kirliliğini azaltmak isteyen, çevre bilincine sahip biri için hangisi daha uygundur?',
    options: [
      'Her zaman tek başına özel araç kullanmak',
      'Aracı gereksiz yere rölantide çalıştırmak',
      'Uygun olduğunda toplu taşımayı, yürüyüşü ya da araç paylaşımını tercih etmek',
      'Kısa mesafeleri bile yüksek hızda araçla gitmek',
    ],
    answerIndex: 2,
    explanation:
      'Yol üzerindeki araç sayısını azaltan her seçim trafiği ve kirliliği hafifletir; uygun durumlarda toplu taşıma, yürüyüş veya araç paylaşımı çevreye saygının somut bir uygulamasıdır.',
    whyWrong: [
      'Her zaman tek başına araç kullanmak trafik ve emisyon yükünü artırır.',
      'Rölantide çalıştırma ve gereksiz yüksek hız, hem yakıt israfı hem de kirliliktir.',
    ],
    objective:
      'Ulaşım tercihlerinin trafik ve çevre üzerindeki etkisini gözeterek karar vermeyi kavramak.',
    tags: ['cevre-bilinci', 'toplu-tasima', 'arac-paylasimi'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-346',
    subject: 'adab',
    topic: 'sabir',
    difficulty: 'orta',
    stem: 'Gişe veya feribot kuyruğunda uzun bir sıra oluşmuş. Sabır ve adap açısından doğru davranış nedir?',
    options: [
      'Yandan ilerleyip sıranın önüne kaynak yapmak',
      'Korna çalıp öndekileri sıkıştırmak',
      'Emniyet şeridinden gidip en öne geçmek',
      'Sıraya saygı gösterip beklemek ve araya girmemek',
    ],
    answerIndex: 3,
    explanation:
      'Kuyrukta herkes aynı şekilde bekler; sıraya saygı gösterip araya girmemek, adaletli ve sabırlı bir davranıştır ve gereksiz sürtüşmeleri önler.',
    whyWrong: [
      'Yandan kaynak yapmak, uzun süredir bekleyenlerin hakkını çiğnemektir.',
      'Kornayla sıkıştırmak veya emniyet şeridinden öne geçmek gerginlik yaratır ve kuralsızdır.',
    ],
    objective: 'Kuyrukta sıra ve bekleme adabına saygı göstermeyi kavramak.',
    tags: ['sabir', 'sira-adabi', 'nezaket'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
];
