/**
 * ÖZGÜN araç tekniği soruları — 2. genişletme (Program 1). ROADMAP C.4/E.6.
 * Kaynak = resmî MEB/ODSGM araç tekniği müfredatı; KENDİ İFADEMİZLE.
 */
import type { QuestionInput } from '@ea/content-schema';

const SRC = 'Resmî MEB/ODSGM araç tekniği müfredatı (özgün ifade)';

export const MOTOR_QUESTIONS_2: QuestionInput[] = [
  {
    id: 'motor-201',
    subject: 'motor',
    topic: 'filtre',
    difficulty: 'kolay',
    stem: 'Hava filtresinin motor açısından temel görevi aşağıdakilerden hangisidir?',
    options: [
      'Yakıtı ateşlemek',
      'Aküyü şarj etmek',
      'Motora giren havadaki toz ve kiri süzerek temiz hava sağlamak',
      'Frenleri soğutmak',
    ],
    answerIndex: 2,
    explanation:
      'Hava filtresi, silindirlere giren havadaki toz, kum ve kir parçacıklarını tutar; böylece motorun temiz hava almasını ve iç parçaların aşınmadan korunmasını sağlar. Tıkalı filtre motor verimini düşürür.',
    whyWrong: [
      'Yakıtı ateşleme görevi benzinlide bujiye aittir.',
      'Akü şarjı alternatörün işidir; frenlerin soğutulmasıyla filtrenin ilgisi yoktur.',
    ],
    objective: 'Hava filtresinin havayı süzme ve motoru koruma işlevini kavramak.',
    tags: ['filtre', 'hava-filtresi', 'bakim'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-202',
    subject: 'motor',
    topic: 'filtre',
    difficulty: 'orta',
    stem: 'Yakıt filtresinin tıkanması durumunda motorda hangi belirti görülmesi beklenir?',
    options: [
      'Farların daha parlak yanması',
      'Lastik basıncının artması',
      'Akünün daha hızlı şarj olması',
      'Motor gücünde düşme, tekleme ve zor çalışma',
    ],
    answerIndex: 3,
    explanation:
      'Yakıt filtresi, yakıttaki tortu ve kirleri tutar. Tıkandığında motora yeterli yakıt gidemez; bu da güç kaybına, teklemeye ve motorun zor çalışmasına yol açar. Belirli aralıklarla değiştirilmelidir.',
    whyWrong: [
      'Yakıt filtresinin farların parlaklığıyla ilgisi yoktur.',
      'Lastik basıncı ve akü şarjı yakıt filtresinden etkilenmez.',
    ],
    objective: 'Yakıt filtresi tıkanmasının motor performansına etkisini kavramak.',
    tags: ['filtre', 'yakit-filtresi', 'bakim'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-203',
    subject: 'motor',
    topic: 'yaglama',
    difficulty: 'orta',
    stem: 'Motorda yağ filtresinin görevi aşağıdakilerden hangisidir?',
    options: [
      'Egzoz gazını temizlemek',
      'Dolaşan motor yağındaki metal partikül ve kirleri süzmek',
      'Yakıt basıncını yükseltmek',
      'Soğutma suyunu ısıtmak',
    ],
    answerIndex: 1,
    explanation:
      'Yağ filtresi, motor içinde dolaşan yağdaki metal talaşı, kurum ve kir parçacıklarını süzer; böylece temiz yağın parçalara ulaşmasını sağlayarak aşınmayı azaltır. Genellikle yağ değişiminde birlikte değiştirilir.',
    whyWrong: [
      'Egzoz gazını katalitik konvertör işler, yağ filtresi değil.',
      'Yakıt basıncı ve soğutma suyu ile yağ filtresinin bir ilgisi yoktur.',
    ],
    objective: 'Yağ filtresinin yağı süzme işlevini ve değişim mantığını kavramak.',
    tags: ['yaglama', 'yag-filtresi', 'bakim'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-204',
    subject: 'motor',
    topic: 'buji',
    difficulty: 'orta',
    stem: 'Benzinli motorlarda bujilerin zamanla aşınması veya kirlenmesi hangi soruna yol açar?',
    options: [
      'Ateşlemenin zayıflaması, teklemeye ve zor çalışmaya neden olması',
      'Lastiklerin erken aşınması',
      'Fren hidroliğinin azalması',
      'Direksiyonun kilitlenmesi',
    ],
    answerIndex: 0,
    explanation:
      'Bujiler hava-yakıt karışımını kıvılcımla ateşler. Aşınan veya kurum bağlamış bujiler zayıf kıvılcım üretir; bu da teklemeye, güç kaybına ve motorun zor çalışmasına yol açar. Periyodik olarak değiştirilmelidir.',
    whyWrong: [
      'Buji durumu lastik aşınmasını doğrudan etkilemez.',
      'Fren hidroliği ve direksiyon kilidi bujiyle ilgili değildir.',
    ],
    objective: 'Buji aşınmasının ateşleme ve motor çalışmasına etkisini kavramak.',
    tags: ['buji', 'atesleme', 'bakim'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-205',
    subject: 'motor',
    topic: 'buji',
    difficulty: 'zor',
    stem: 'Dizel motorlarda soğuk havada ilk çalıştırmayı kolaylaştırmak için kullanılan eleman aşağıdakilerden hangisidir?',
    options: [
      'Ateşleme bujisi',
      'Katalitik konvertör',
      'Alternatör',
      'Yakıt filtresi',
      'Kızdırma bujisi (ısıtma bujisi)',
    ],
    answerIndex: 4,
    explanation:
      'Dizel motorlar yakıtı sıkıştırma ısısıyla tutuşturur; ateşleme bujisi kullanmaz. Ancak soğukta yanma odasını ısıtıp ilk çalıştırmayı kolaylaştırmak için kızdırma bujisi bulunur. Bu, benzinlideki ateşleme bujisinden farklıdır.',
    whyWrong: [
      'Ateşleme bujisi benzinli motorlara özgüdür.',
      'Katalitik konvertör egzozu, alternatör ise şarjı ilgilendirir; ilk çalıştırmayı ısıtmazlar.',
    ],
    objective: 'Dizelde kızdırma bujisinin soğuk çalıştırmadaki rolünü kavramak.',
    tags: ['buji', 'dizel', 'motor-cesit'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-206',
    subject: 'motor',
    topic: 'mars',
    difficulty: 'kolay',
    stem: 'Marş motorunun (marş dinamosu) temel görevi aşağıdakilerden hangisidir?',
    options: [
      'Aküyü şarj etmek',
      'Motoru ilk hareketle döndürüp çalışmasını başlatmak',
      'Fren yapmak',
      'Egzoz gazını temizlemek',
    ],
    answerIndex: 1,
    explanation:
      'Marş motoru, aküden aldığı elektrik enerjisiyle krank milini döndürerek motorun ilk hareketini sağlar; motor çalışmaya başladığında görevi biter. Sürekli değil, yalnızca çalıştırma anında devreye girer.',
    whyWrong: [
      'Aküyü marş motoru değil alternatör şarj eder.',
      'Fren ve egzoz temizliğiyle marş motorunun ilgisi yoktur.',
    ],
    objective: 'Marş motorunun motoru ilk çalıştırma işlevini kavramak.',
    tags: ['mars', 'aku', 'elektrik'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-207',
    subject: 'motor',
    topic: 'mars',
    difficulty: 'orta',
    stem: 'Kontak açıldığında marş motoru motoru çeviremiyorsa (marş zayıf/basmıyor) en olası nedenlerden biri hangisidir?',
    options: [
      'Lastik dişlerinin aşınması',
      'Egzoz susturucusunun paslanması',
      'Akünün zayıf/boşalmış olması ya da kutup başlarının gevşek olması',
      'Silecek lastiğinin eskimesi',
    ],
    answerIndex: 2,
    explanation:
      'Marş motoru gücünü aküden alır. Akü boşalmış, zayıf ya da kutup başları oksitlenip gevşek ise marş motoruna yeterli akım gitmez ve motor dönmez. Önce akü ve bağlantıları kontrol edilir.',
    whyWrong: [
      'Lastik dişi ve silecek lastiği marş sistemini etkilemez.',
      'Egzoz susturucusunun paslanmasının marşın basmasıyla ilgisi yoktur.',
    ],
    objective: 'Marş basmamasının akü kaynaklı nedenlerini kavramak.',
    tags: ['mars', 'aku', 'ariza'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-208',
    subject: 'motor',
    topic: 'alternator',
    difficulty: 'orta',
    stem: 'Alternatörün arızalanması durumunda sürüş sırasında hangi belirti öne çıkar?',
    options: [
      'Lastik basıncının kendiliğinden artması',
      'Fren pedalının sertleşmesi',
      'Klimanın daha iyi soğutması',
      'Gösterge panelinde şarj (akü) ikazının yanması ve zamanla akünün boşalması',
    ],
    answerIndex: 3,
    explanation:
      'Alternatör motor çalışırken elektrik üretip aküyü şarj eder ve sistemi besler. Arızalandığında şarj sağlanamaz; panelde akü ikazı yanar ve zamanla akü boşalarak araç stop edebilir.',
    whyWrong: [
      'Lastik basıncı ve fren pedalı alternatör arızasından böyle etkilenmez.',
      'Alternatör arızası klimanın soğutmasını iyileştirmez, tersine elektrik yetersizliğine yol açar.',
    ],
    objective: 'Alternatör arızasının şarj ikazı ile ilişkisini kavramak.',
    tags: ['alternator', 'sarj', 'gosterge'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-209',
    subject: 'motor',
    topic: 'sarj',
    difficulty: 'orta',
    stem: 'Alternatörü döndürerek şarj üretilmesini sağlayan ve gevşerse/koparsa şarj sorununa yol açan parça hangisidir?',
    options: [
      'Triger kayışı',
      'Vantilatör/alternatör (V) kayışı',
      'Fren balatası',
      'Debriyaj teli',
    ],
    answerIndex: 1,
    explanation:
      'Alternatör, motordan aldığı hareketi V (vantilatör) kayışı aracılığıyla alır ve döndürülerek elektrik üretir. Bu kayış gevşer ya da koparsa alternatör dönemez, şarj kesilir ve akü boşalır.',
    whyWrong: [
      'Triger kayışı krank ile eksantrik milini senkronlar; şarjı doğrudan üretmez.',
      'Fren balatası ve debriyaj teli şarj üretimiyle ilgili değildir.',
    ],
    objective: 'V kayışının alternatör şarjındaki rolünü kavramak.',
    tags: ['sarj', 'alternator', 'kayis'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-210',
    subject: 'motor',
    topic: 'antifriz',
    difficulty: 'kolay',
    stem: 'Soğutma sistemindeki antifriz seviyesi ve karışımının kontrol edilmesi neden önemlidir?',
    options: [
      'Yeterli antifriz kışın donmayı, yazın erken kaynamayı önleyerek motoru korur',
      'Antifriz farların parlaklığını artırır',
      'Antifriz lastik ömrünü uzatır',
      'Antifriz fren mesafesini kısaltır',
    ],
    answerIndex: 0,
    explanation:
      'Antifriz, soğutma suyunun donma noktasını düşürür ve kaynama noktasını yükseltir. Yeterli ve doğru oranda antifriz, kışın donmayı ve yazın erken kaynamayı önleyerek motorun zarar görmesini engeller.',
    whyWrong: [
      'Antifrizin farların parlaklığıyla bir ilgisi yoktur.',
      'Lastik ömrü ve fren mesafesi antifrizle ilgili değildir.',
    ],
    objective: 'Antifriz seviyesi/karışım kontrolünün önemini kavramak.',
    tags: ['antifriz', 'sogutma', 'bakim'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-211',
    subject: 'motor',
    topic: 'radyator',
    difficulty: 'orta',
    stem: 'Soğutma suyu seviyesi kontrol edilirken doğru davranış aşağıdakilerden hangisidir?',
    options: [
      'Motor çok sıcakken radyatör kapağını hemen açıp bakmak',
      'Motor soğukken genleşme (yedek su) deposundaki seviyeyi min-maks arasında tutmak',
      'Su seviyesini hiç kontrol etmemek',
      'Suyun yerine yağ eklemek',
    ],
    answerIndex: 1,
    explanation:
      'Soğutma suyu seviyesi, motor soğukken genleşme deposundaki alt-üst (min-maks) işaretleri arasında olmalıdır. Sıcak motorda basınçlı sistem tehlikeli olduğundan kapak açılmaz; kontrol soğuk motorda yapılır.',
    whyWrong: [
      'Sıcak motorda radyatör kapağı açılırsa basınçlı sıcak su fışkırıp yanığa yol açar.',
      'Suyu hiç kontrol etmemek ya da yerine yağ koymak sistemi bozar.',
    ],
    objective: 'Soğutma suyu seviyesinin güvenli kontrolünü kavramak.',
    tags: ['radyator', 'sogutma', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-212',
    subject: 'motor',
    topic: 'amortisor',
    difficulty: 'kolay',
    stem: 'Aracın amortisörlerinin (süspansiyon) temel görevi aşağıdakilerden hangisidir?',
    options: [
      'Motoru soğutmak',
      'Yakıt tüketimini ölçmek',
      'Aküyü şarj etmek',
      'Yol düzensizliklerinden gelen sarsıntıları söndürüp tekerleğin yola tutunmasını sağlamak',
    ],
    answerIndex: 3,
    explanation:
      'Amortisörler, yoldan gelen darbe ve titreşimleri söndürür; tekerleklerin yolla temasını koruyarak sürüş konforunu ve yol tutuşunu artırır. Bu da frenleme ve direksiyon güvenliğine katkı sağlar.',
    whyWrong: [
      'Motoru soğutma görevi soğutma sistemine aittir.',
      'Yakıt ölçümü ve akü şarjı amortisörle ilgili değildir.',
    ],
    objective: 'Amortisörün titreşim söndürme ve yol tutuş işlevini kavramak.',
    tags: ['amortisor', 'suspansiyon', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-213',
    subject: 'motor',
    topic: 'amortisor',
    difficulty: 'orta',
    stem: 'Amortisörleri arızalı bir araçta hangi olumsuzluk beklenir?',
    options: [
      'Yakıt deposunun hızlı dolması',
      'Frenlemede ve virajda yol tutuşun azalması, aracın zıplaması ve savrulmaya yatkınlığı',
      'Motor sesinin tamamen kesilmesi',
      'Akünün aşırı şarj olması',
    ],
    answerIndex: 1,
    explanation:
      'Zayıflamış amortisörler yol darbelerini söndüremez; tekerlekler zıplayarak yolla temasını kaybeder. Bu, fren mesafesinin uzamasına, virajda savrulmaya ve genel yol tutuş kaybına yol açarak güvenliği tehlikeye atar.',
    whyWrong: [
      'Yakıt deposu ve akü şarjı amortisör durumundan etkilenmez.',
      'Amortisör arızası motor sesini kesmez.',
    ],
    objective: 'Amortisör arızasının yol tutuş ve güvenliğe etkisini kavramak.',
    tags: ['amortisor', 'yol-tutus', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-214',
    subject: 'motor',
    topic: 'rot-balans',
    difficulty: 'orta',
    stem: 'Direksiyon belirli bir hızda titriyorsa (özellikle yüksek hızda) en olası neden aşağıdakilerden hangisidir?',
    options: [
      'Tekerlek balans ayarının bozuk olması',
      'Akünün yeni olması',
      'Depoda az yakıt bulunması',
      'Farların açık olması',
    ],
    answerIndex: 0,
    explanation:
      'Tekerlek balansı bozulduğunda dönen tekerlek ağırlık dağılımı dengesizleşir; bu da özellikle yüksek hızda direksiyona yansıyan titreşime yol açar. Balans ayarı yaptırılarak giderilir.',
    whyWrong: [
      'Yeni akü ya da az yakıt direksiyon titreşimi yapmaz.',
      'Farların açık olmasının direksiyon titremesiyle ilgisi yoktur.',
    ],
    objective: 'Balans bozukluğunun direksiyon titreşimi ile ilişkisini kavramak.',
    tags: ['rot-balans', 'lastik', 'direksiyon'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-215',
    subject: 'motor',
    topic: 'sanziman',
    difficulty: 'orta',
    stem: 'Otomatik şanzımanlı bir aracın manuel şanzımanlıdan temel farkı aşağıdakilerden hangisidir?',
    options: [
      'Otomatik şanzımanlı araç yakıt kullanmaz',
      'Otomatik şanzımanda motor bulunmaz',
      'Otomatik şanzımanda debriyaj pedalı yoktur; vites geçişleri kendiliğinden yapılır',
      'Otomatik şanzımanlı araçta fren gerekmez',
    ],
    answerIndex: 2,
    explanation:
      'Otomatik şanzıman, vites kademelerini hıza ve yüke göre kendiliğinden değiştirir; sürücü ayrı bir debriyaj pedalı kullanmaz. Manuel şanzımanda ise vites, debriyaja basılarak elle değiştirilir.',
    whyWrong: [
      'Her iki tür de yakıtla çalışan bir motora sahiptir.',
      'Fren her araçta gereklidir; şanzıman türüne bağlı değildir.',
    ],
    objective: 'Otomatik ve manuel şanzıman farkını kavramak.',
    tags: ['sanziman', 'debriyaj', 'aktarma'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-216',
    subject: 'motor',
    topic: 'debriyaj',
    difficulty: 'zor',
    stem: 'Kalkışta ve yüklenmede motor devri yükseldiği hâlde araç yeterince hızlanmıyor ve yanık kokusu geliyorsa bu en çok neyi düşündürür?',
    options: [
      'Lastik basıncının yüksek olduğunu',
      'Debriyaj (kavrama) balatasının aşınıp kaydığını',
      'Radyatörün yeni olduğunu',
      'Akünün tam şarjlı olduğunu',
    ],
    answerIndex: 1,
    explanation:
      'Debriyaj balatası aşındığında baskı yeterli olmaz ve kavrama kayar; motor devri artsa da güç tekerleğe tam iletilemez, sürtünmeden yanık kokusu gelir. Bu durumda debriyaj kontrol/onarım gerektirir.',
    whyWrong: [
      'Yüksek lastik basıncı bu belirtileri vermez.',
      'Yeni radyatör ve tam şarjlı akü debriyaj kaymasıyla ilgili değildir.',
    ],
    objective: 'Debriyaj kaymasının belirtilerini kavramak.',
    tags: ['debriyaj', 'kavrama', 'ariza'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-217',
    subject: 'motor',
    topic: 'triger',
    difficulty: 'zor',
    stem: 'Triger (zaman) kayışının üretici tarafından belirtilen periyotta değiştirilmesi neden önemlidir?',
    options: [
      'Kayış değişimi lastik basıncını ayarlar',
      'Kayış değişimi yakıt deposunu temizler',
      'Kayış değişimi far ayarını yapar',
      'Kayışın motorla bir ilgisi yoktur',
      'Kayışın kopması hâlinde supap ve pistonlar çarpışarak motor ağır hasar görebilir',
    ],
    answerIndex: 4,
    explanation:
      'Triger kayışı krank ile eksantrik milinin senkron dönmesini sağlar. Ömrünü tamamlayıp koparsa zamanlama bozulur; birçok motorda supaplar ve pistonlar çarpışarak ciddi ve pahalı hasar oluşur. Bu yüzden periyodik değişim şarttır.',
    whyWrong: [
      'Triger değişiminin lastik basıncıyla ilgisi yoktur.',
      'Yakıt deposu temizliği ve far ayarı triger kayışıyla ilgili değildir.',
    ],
    objective: 'Triger kayışı periyodik değişiminin kritik önemini kavramak.',
    tags: ['triger', 'kayis', 'bakim'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-218',
    subject: 'motor',
    topic: 'yakit',
    difficulty: 'orta',
    stem: 'Modern motorlarda enjektörün görevi aşağıdakilerden hangisidir?',
    options: [
      'Yakıtı ince zerreler hâlinde ve doğru miktarda yanma odasına/emme kanalına püskürtmek',
      'Yanma odasında kıvılcım oluşturmak',
      'Aküyü şarj etmek',
      'Direksiyonu yönlendirmek',
    ],
    answerIndex: 0,
    explanation:
      'Enjektör, basınçlı yakıtı ölçülü ve püskürtülmüş biçimde ortama gönderir; iyi karışım ve verimli yanma sağlar. Ateşleme ise benzinlide bujinin kıvılcımıyla olur; enjektör yalnızca yakıtı püskürtür.',
    whyWrong: [
      'Kıvılcımı buji üretir, enjektör değil.',
      'Akü şarjı ve direksiyon yönlendirmesi enjektörün görevi değildir.',
    ],
    objective: 'Enjektörün yakıt püskürtme işlevini kavramak.',
    tags: ['yakit', 'enjektor', 'atesleme'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-219',
    subject: 'motor',
    topic: 'yakit',
    difficulty: 'kolay',
    stem: 'Yakıt pompasının temel görevi aşağıdakilerden hangisidir?',
    options: [
      'Motoru soğutmak',
      'Fren yapmak',
      'Depodaki yakıtı motora/enjeksiyon sistemine basınçla iletmek',
      'Elektrik üretmek',
    ],
    answerIndex: 2,
    explanation:
      'Yakıt pompası, depodaki yakıtı yeterli basınçla emerek yakıt sistemine ve motora gönderir. Arızalanırsa motora yakıt gitmez; araç çalışmaz ya da yolda stop edebilir.',
    whyWrong: [
      'Motoru soğutma görevi soğutma sistemine aittir.',
      'Fren yapma ve elektrik üretme yakıt pompasının görevi değildir.',
    ],
    objective: 'Yakıt pompasının yakıt iletme işlevini kavramak.',
    tags: ['yakit', 'yakit-pompasi', 'motor'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-220',
    subject: 'motor',
    topic: 'motor-cesit',
    difficulty: 'zor',
    stem: 'Dört zamanlı içten yanmalı bir motorun çalışma zamanları hangi sırayla gerçekleşir?',
    options: [
      'Egzoz - Emme - Ateşleme - Sıkıştırma',
      'Sıkıştırma - Emme - Egzoz - Ateşleme',
      'Ateşleme - Egzoz - Sıkıştırma - Emme',
      'Emme - Egzoz - Sıkıştırma - Ateşleme',
      'Emme - Sıkıştırma - Ateşleme (iş) - Egzoz',
    ],
    answerIndex: 4,
    explanation:
      'Dört zamanlı motorda çevrim; havanın/karışımın alındığı emme, sıkıştırma, yanmanın olduğu ateşleme (iş) ve yanmış gazların atıldığı egzoz zamanları sırasıyla tekrarlanır. Bu döngü motorun sürekli güç üretmesini sağlar.',
    whyWrong: [
      'Diğer sıralamalar çevrimin gerçek işleyişine uymaz.',
      'Emme yapılmadan sıkıştırma ya da ateşleme mantıken gerçekleşemez.',
    ],
    objective: 'Dört zamanlı motorun çalışma zamanlarını sırasıyla kavramak.',
    tags: ['motor-cesit', 'dort-zaman', 'calisma'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-221',
    subject: 'motor',
    topic: 'motor-cesit',
    difficulty: 'orta',
    stem: 'İçten yanmalı bir motorda güç nasıl üretilir?',
    options: [
      'Yalnızca akünün elektriğiyle',
      'Yakıt-hava karışımının silindir içinde yanmasıyla oluşan basıncın pistonu itmesiyle',
      'Rüzgar gücüyle',
      'Fren sürtünmesiyle',
    ],
    answerIndex: 1,
    explanation:
      'İçten yanmalı motorda yakıt-hava karışımı silindir içinde yanar; oluşan yüksek basınçlı gaz pistonu iterek krank milini döndürür. Bu doğrusal hareket dönme hareketine çevrilerek tekerleklere güç iletilir.',
    whyWrong: [
      'Klasik içten yanmalı motor gücü sadece aküden almaz; akü marş ve elektriği besler.',
      'Rüzgar ve fren sürtünmesi motor gücünün kaynağı değildir.',
    ],
    objective: 'İçten yanmalı motorda güç üretim ilkesini kavramak.',
    tags: ['motor-cesit', 'yanma', 'piston'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-222',
    subject: 'motor',
    topic: 'egzoz',
    difficulty: 'kolay',
    stem: 'Egzoz sistemindeki susturucunun (egzoz susturucusu) temel işlevi nedir?',
    options: [
      'Motora hava basmak',
      'Aküyü soğutmak',
      'Vites değiştirmek',
      'Yanmış gazların çıkış sesini azaltmak',
    ],
    answerIndex: 3,
    explanation:
      'Susturucu, egzozdan atılan yanmış gazların oluşturduğu yüksek sesi azaltarak gürültüyü düşürür. Egzoz sistemi ayrıca gazların araçtan güvenli biçimde uzaklaştırılmasını sağlar.',
    whyWrong: [
      'Motora hava sağlama görevi hava emme sistemine aittir.',
      'Aküyü soğutma ve vites değiştirme susturucunun işi değildir.',
    ],
    objective: 'Susturucunun egzoz sesini azaltma işlevini kavramak.',
    tags: ['egzoz', 'susturucu', 'ses'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-223',
    subject: 'motor',
    topic: 'egzoz',
    difficulty: 'zor',
    stem: 'Egzozdan sürekli koyu siyah duman gelmesi genellikle neyi gösterir?',
    options: [
      'Lastiklerin yeni olduğunu',
      'Akünün tam şarjlı olduğunu',
      'Yakıtın fazla/eksik yanması, karışımın zengin olması gibi bir yakıt-yanma sorununu',
      'Direksiyonun hafiflediğini',
    ],
    answerIndex: 2,
    explanation:
      'Koyu siyah egzoz dumanı çoğunlukla yakıtın tam yanmadığını, karışımın gereğinden zengin olduğunu gösterir; enjeksiyon, hava filtresi veya yanma ile ilgili bir soruna işaret eder. Kontrol ettirilmesi gerekir.',
    whyWrong: [
      'Duman rengi lastik ya da akü durumunu göstermez.',
      'Direksiyonun hafiflemesiyle egzoz dumanı arasında ilişki yoktur.',
    ],
    objective: 'Siyah egzoz dumanının yanma sorununa işaret ettiğini kavramak.',
    tags: ['egzoz', 'duman', 'ariza'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-224',
    subject: 'motor',
    topic: 'hararet',
    difficulty: 'orta',
    stem: 'Radyatör önündeki soğutma fanının (vantilatör) görevi aşağıdakilerden hangisidir?',
    options: [
      'Yakıtı depolamak',
      'Özellikle düşük hızda ve rölantide radyatöre hava çekerek soğutmayı desteklemek',
      'Fren balatasını sıkıştırmak',
      'Aküyü şarj etmek',
    ],
    answerIndex: 1,
    explanation:
      'Araç yavaşken ya da dururken radyatörden yeterli hava geçmez; soğutma fanı devreye girip radyatöre hava çekerek suyun soğumasını sağlar. Böylece trafik ve rölantide motorun aşırı ısınması önlenir.',
    whyWrong: [
      'Yakıt depolama görevi yakıt deposuna aittir.',
      'Fren ve akü şarjı fanın görevi değildir.',
    ],
    objective: 'Soğutma fanının düşük hızda soğutmayı destekleme işlevini kavramak.',
    tags: ['hararet', 'fan', 'sogutma'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-225',
    subject: 'motor',
    topic: 'hararet',
    difficulty: 'orta',
    stem: 'Soğutma sistemindeki termostatın görevi aşağıdakilerden hangisidir?',
    options: [
      'Motorun çalışma sıcaklığına ulaşınca su geçişini ayarlayarak sıcaklığı dengede tutmak',
      'Yakıtı ateşlemek',
      'Direksiyonu döndürmek',
      'Lastik dişini derinleştirmek',
    ],
    answerIndex: 0,
    explanation:
      'Termostat, motor soğukken suyun radyatöre gitmesini kısıp motorun çabuk ısınmasını sağlar; çalışma sıcaklığına ulaşınca açılarak su dolaşımını serbest bırakır. Böylece ideal sıcaklık korunur.',
    whyWrong: [
      'Yakıtı ateşleme görevi benzinlide bujiye aittir.',
      'Direksiyon ve lastik dişiyle termostatın ilgisi yoktur.',
    ],
    objective: 'Termostatın motor sıcaklığını dengeleme işlevini kavramak.',
    tags: ['hararet', 'termostat', 'sogutma'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-226',
    subject: 'motor',
    topic: 'sogutma',
    difficulty: 'orta',
    stem: 'Su (devir daim) pompasının soğutma sistemindeki görevi nedir?',
    options: [
      'Aküyü şarj etmek',
      'Egzoz sesini kısmak',
      'Yakıt püskürtmek',
      'Soğutma suyunu motor ile radyatör arasında dolaştırmak',
    ],
    answerIndex: 3,
    explanation:
      'Su pompası, soğutma suyunu motor bloğu ile radyatör arasında sürekli dolaştırır; ısınan su radyatörde soğutulup tekrar motora gönderilir. Pompa arızalanırsa dolaşım durur ve motor kısa sürede hararet yapar.',
    whyWrong: [
      'Aküyü alternatör şarj eder; su pompası değil.',
      'Egzoz sesini susturucu keser, yakıtı enjektör püskürtür.',
    ],
    objective: 'Su pompasının soğutma suyunu dolaştırma işlevini kavramak.',
    tags: ['sogutma', 'su-pompasi', 'hararet'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-227',
    subject: 'motor',
    topic: 'lastik',
    difficulty: 'kolay',
    stem: 'Kış lastiklerinin yaz lastiklerine göre soğuk ve karlı-buzlu yolda sağladığı temel avantaj nedir?',
    options: [
      'Yakıtı ateşlemesi',
      'Düşük sıcaklıkta sertleşmeyen yapısı ve diş deseni ile daha iyi yol tutuş ve frenleme sağlaması',
      'Aküyü şarj etmesi',
      'Motoru soğutması',
    ],
    answerIndex: 1,
    explanation:
      'Kış lastikleri, düşük sıcaklıkta esnekliğini koruyan karışım ve özel diş desenine sahiptir; kar, buz ve ıslak soğuk zeminde yaz lastiğine göre daha iyi tutunma ve daha kısa fren mesafesi sağlar.',
    whyWrong: [
      'Lastiğin yakıt ateşleme ya da akü şarjıyla ilgisi yoktur.',
      'Motoru soğutmak soğutma sisteminin görevidir.',
    ],
    objective: 'Kış lastiğinin soğuk-karlı yolda sağladığı güvenlik avantajını kavramak.',
    tags: ['lastik', 'kis-lastigi', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-228',
    subject: 'motor',
    topic: 'lastik',
    difficulty: 'kolay',
    stem: 'Lastik patladığında kullanılmak üzere araçta bulundurulan yedek lastiğe ne ad verilir?',
    options: ['Stepne (yedek lastik)', 'Balata', 'Enjektör', 'Amortisör'],
    answerIndex: 0,
    explanation:
      'Stepne, yolda lastik patladığında ya da hava kaybettiğinde geçici olarak takılan yedek lastiktir. Aracın kriko ve bijon anahtarıyla birlikte stepnenin de sağlam ve basınçlı olması önemlidir.',
    whyWrong: [
      'Balata fren sistemine, enjektör yakıt sistemine aittir.',
      'Amortisör süspansiyon parçasıdır; yedek lastik değildir.',
    ],
    objective: 'Stepnenin yedek lastik olduğunu ve işlevini kavramak.',
    tags: ['lastik', 'stepne', 'guvenlik'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-229',
    subject: 'motor',
    topic: 'fren',
    difficulty: 'kolay',
    stem: 'El freninin (park freni) temel görevi aşağıdakilerden hangisidir?',
    options: [
      'Motoru çalıştırmak',
      'Farları yakmak',
      'Park hâlindeki aracın kendiliğinden hareket etmesini önlemek',
      'Yakıt tüketimini artırmak',
    ],
    answerIndex: 2,
    explanation:
      'El freni (park freni), duran aracı yerinde sabit tutar; özellikle eğimli zeminde aracın kaymasını önler. Genellikle arka tekerleklere etki eder ve park sırasında mutlaka çekilmelidir.',
    whyWrong: [
      'Motoru çalıştırma görevi marş sistemine aittir.',
      'Farları yakma ve yakıt tüketimiyle el freninin ilgisi yoktur.',
    ],
    objective: 'El freninin park hâlinde aracı sabitleme işlevini kavramak.',
    tags: ['fren', 'el-freni', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-230',
    subject: 'motor',
    topic: 'fren',
    difficulty: 'orta',
    stem: 'Hidrolik fren sisteminde fren hidroliğinin (fren yağı) görevi nedir?',
    options: [
      'Motoru yağlamak',
      'Aküyü soğutmak',
      'Lastiği şişirmek',
      'Pedala uygulanan basıncı fren mekanizmasına ileterek frenleme kuvveti oluşturmak',
    ],
    answerIndex: 3,
    explanation:
      'Fren hidroliği, fren pedalına basıldığında oluşan basıncı sıvı aracılığıyla tekerlek fren mekanizmalarına iletir; böylece balatalar diske/kampanaya bastırılır. Seviyesi düşük ya da kaçak varsa frenleme zayıflar.',
    whyWrong: [
      'Motoru yağlamak motor yağının görevidir.',
      'Aküyü soğutmak ve lastiği şişirmek fren hidroliğinin işi değildir.',
    ],
    objective: 'Fren hidroliğinin basınç iletme işlevini kavramak.',
    tags: ['fren', 'fren-hidroligi', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-231',
    subject: 'motor',
    topic: 'fren',
    difficulty: 'zor',
    stem: 'Uzun ve dik bir yokuş inişinde sürekli fren pedalına basmak yerine önerilen güvenli yöntem nedir?',
    options: [
      'Vitesi boşa alıp inmek',
      'Uygun düşük vitese geçerek motor freninden yararlanmak',
      'El frenini çekili tutarak inmek',
      'Kontağı kapatıp inmek',
    ],
    answerIndex: 1,
    explanation:
      'Uzun inişte sürekli fren kullanmak balataları ısıtıp fren performansını düşürür (fren kaybı). Uygun düşük vitese geçilerek motor freninden yararlanılır; motorun tutuşu hızı sınırlar ve frenler yedekte kalır.',
    whyWrong: [
      'Vitesi boşa almak motor frenini devre dışı bırakır ve hız kontrolsüz artar.',
      'El frenini çekili tutmak arka tekeri kilitleyip savrulmaya, kontağı kapatmak direksiyon/fren desteğinin kaybına yol açar.',
    ],
    objective: 'Yokuş inişinde motor freni kullanımının güvenlik gerekçesini kavramak.',
    tags: ['fren', 'motor-freni', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-232',
    subject: 'motor',
    topic: 'aku',
    difficulty: 'orta',
    stem: 'Akü bakımında kutup başları (terminaller) ile ilgili doğru uygulama hangisidir?',
    options: [
      'Kutup başlarının temiz, sıkı ve oksitlenmemiş olması sağlanmalıdır',
      'Kutup başları ne kadar gevşek olursa o kadar iyidir',
      'Kutup başlarına sürekli su dökülmelidir',
      'Kutup başları hiç kontrol edilmez',
    ],
    answerIndex: 0,
    explanation:
      'Akü kutup başları temiz, sıkı ve oksit (beyaz-yeşil tortu) tutmamış olmalıdır. Gevşek ya da oksitli bağlantı akım geçişini zorlaştırır; marş ve şarj sorunlarına yol açar. Bu yüzden düzenli kontrol edilir.',
    whyWrong: [
      'Gevşek kutup başı temas direncini artırır ve arıza yapar.',
      'Sürekli su dökmek ya da hiç kontrol etmemek doğru bakım değildir.',
    ],
    objective: 'Akü kutup başlarının doğru bakımını kavramak.',
    tags: ['aku', 'kutup-basi', 'bakim'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-233',
    subject: 'motor',
    topic: 'aku',
    difficulty: 'zor',
    stem: 'Boşalmış bir aküye başka araçtan takviye (çapraz kablo) yapılırken doğru yaklaşım aşağıdakilerden hangisidir?',
    options: [
      'Kabloların bağlanma sırasına ve kutuplara dikkat edilmeden rastgele bağlanabilir',
      'Kablolar çalışan motora hiç bağlanmaz, yalnızca boş aküye takılır',
      'Takviye yaparken kutupların ters bağlanması sorun yaratmaz',
      'Takviye için kablo yerine su kullanılır',
      'Kablolar doğru kutuplara (artı-artı, eksi-eksi) bağlanır ve kıvılcım/patlama riskine karşı dikkatli olunur',
    ],
    answerIndex: 4,
    explanation:
      'Takviyede kablolar doğru kutuplara (artı-artı, eksi-eksi) bağlanmalıdır; ters bağlantı elektronik aksama zarar verir. Akü çevresinde patlayıcı gaz bulunabileceğinden kıvılcıma karşı dikkatli olunmalı ve sıralamaya uyulmalıdır.',
    whyWrong: [
      'Kutupların rastgele ya da ters bağlanması kısa devre, hasar ve patlama riski oluşturur.',
      'Takviye, kaynak araçtan kabloyla yapılır; su ile takviye mümkün değildir.',
    ],
    objective: 'Akü takviyesinde doğru bağlantı ve güvenlik ilkelerini kavramak.',
    tags: ['aku', 'takviye', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-234',
    subject: 'motor',
    topic: 'elektrik',
    difficulty: 'kolay',
    stem: 'Dörtlü ikaz (flaşör) lambalarının kullanım amacı aşağıdakilerden hangisidir?',
    options: [
      'Motoru soğutmak',
      'Yakıt tüketimini azaltmak',
      'Aracın arıza, tehlike veya diğer sürücüleri uyarma durumunda bulunduğunu bildirmek',
      'Vites değiştirmek',
    ],
    answerIndex: 2,
    explanation:
      'Dörtlü ikaz lambaları, aracın arızalandığını, tehlikeli bir durum bulunduğunu ya da diğer sürücülerin dikkatinin çekilmesi gerektiğini bildirmek için kullanılır. Tüm sinyaller aynı anda yanıp söner.',
    whyWrong: [
      'Motoru soğutmak soğutma sisteminin görevidir.',
      'Yakıt tüketimi ve vites değiştirmeyle flaşörün ilgisi yoktur.',
    ],
    objective: 'Dörtlü ikaz lambalarının uyarı amacını kavramak.',
    tags: ['elektrik', 'flasor', 'guvenlik'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-235',
    subject: 'motor',
    topic: 'direksiyon',
    difficulty: 'orta',
    stem: 'Direksiyonda fazla boşluk (serbest hareket) bulunması neden tehlikelidir?',
    options: [
      'Yakıt tüketimini sıfırlar',
      'Motoru güçlendirir',
      'Aküyü şarj eder',
      'Aracın yönlendirilmesini geciktirip zorlaştırarak hakimiyeti azaltır',
    ],
    answerIndex: 3,
    explanation:
      'Direksiyonda aşırı boşluk, sürücünün verdiği yön komutunun tekerleklere gecikmeli ve belirsiz aktarılmasına yol açar; bu da özellikle acil manevralarda hakimiyet kaybı riski oluşturur. Kontrol ve onarım gerektirir.',
    whyWrong: [
      'Direksiyon boşluğu yakıt tüketimini sıfırlamaz ve motoru güçlendirmez.',
      'Akü şarjıyla direksiyon boşluğunun ilgisi yoktur.',
    ],
    objective: 'Direksiyon boşluğunun hakimiyet ve güvenliğe etkisini kavramak.',
    tags: ['direksiyon', 'bosluk', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-236',
    subject: 'motor',
    topic: 'gosterge',
    difficulty: 'kolay',
    stem: 'Yakıt göstergesinin ibresi rezerv (kırmızı) bölgeye yaklaştığında doğru davranış nedir?',
    options: [
      'İlk uygun istasyonda yakıt ikmali yapmak',
      'Göstergeyi kapatıp yola devam etmek',
      'Klimayı açarak yakıt üretmek',
      'Lastik basıncını düşürmek',
    ],
    answerIndex: 0,
    explanation:
      'Yakıt göstergesi rezerve düştüğünde depodaki yakıt sınırlıdır; sürücü ilk uygun istasyonda ikmal yapmalıdır. Yakıtın tamamen bitmesi araçta stop etmeye ve yakıt sisteminde soruna yol açabilir.',
    whyWrong: [
      'Klima yakıt üretmez; tersine tüketimi artırır.',
      'Göstergeyi kapatmak ya da lastik basıncını düşürmek yakıt sorununu çözmez.',
    ],
    objective: 'Yakıt göstergesi rezerv uyarısına doğru tepkiyi kavramak.',
    tags: ['gosterge', 'yakit', 'rezerv'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-237',
    subject: 'motor',
    topic: 'gosterge',
    difficulty: 'orta',
    stem: 'Gösterge panelindeki devir saati (takometre) sürücüye hangi bilgiyi verir?',
    options: [
      'Kalan yakıt miktarını',
      'Motorun dakikadaki devir sayısını (rpm), böylece uygun vites/gaz kullanımına yardımcı olur',
      'Dış hava sıcaklığını',
      'Lastik basıncını',
    ],
    answerIndex: 1,
    explanation:
      'Devir saati, motorun dakikadaki dönüş sayısını (devir/rpm) gösterir. Sürücü bu bilgiyle motoru aşırı yükleme veya yüksek devirde zorlamadan uygun vitesi ve gaz seviyesini seçerek verimli ve güvenli sürüş yapabilir.',
    whyWrong: [
      'Kalan yakıt ayrı yakıt göstergesiyle takip edilir.',
      'Dış sıcaklık ve lastik basıncı için farklı göstergeler bulunur.',
    ],
    objective: 'Devir saatinin (takometre) motor devrini gösterme işlevini kavramak.',
    tags: ['gosterge', 'takometre', 'devir'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-238',
    subject: 'motor',
    topic: 'aktarma',
    difficulty: 'zor',
    stem: 'Diferansiyelin araçtaki temel görevi aşağıdakilerden hangisidir?',
    options: [
      'Motoru soğutmak',
      'Yakıtı ateşlemek',
      'Aküyü şarj etmek',
      'Egzoz gazını temizlemek',
      'Virajda dış ve iç tekerleğin farklı hızlarda dönebilmesini sağlarken gücü tekerleklere iletmek',
    ],
    answerIndex: 4,
    explanation:
      'Virajda dıştaki tekerlek içtekinden daha uzun yol alır ve daha hızlı dönmesi gerekir. Diferansiyel, tahrik gücünü tekerleklere iletirken bu hız farkına izin verir; böylece lastik sürtme ve zorlanma olmadan dönüş yapılır.',
    whyWrong: [
      'Motoru soğutma görevi soğutma sistemine aittir.',
      'Yakıtı ateşleme ve akü şarjı diferansiyelin görevi değildir.',
    ],
    objective: 'Diferansiyelin tekerlek hız farkına izin verme işlevini kavramak.',
    tags: ['aktarma', 'diferansiyel', 'viraj'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-239',
    subject: 'motor',
    topic: 'yaglama',
    difficulty: 'kolay',
    stem: 'Motor yağ seviyesi yağ çubuğu (yağ mili) ile kontrol edilirken doğru yöntem hangisidir?',
    options: [
      'Motor düz zeminde ve durgunken çubuk silinip tekrar daldırılarak min-maks arası kontrol edilir',
      'Motor tam gaz çalışırken çubuk çekilerek bakılır',
      'Yağ seviyesi hiç kontrol edilmez',
      'Çubuk yerine lastik basıncı ölçülür',
    ],
    answerIndex: 0,
    explanation:
      'Yağ seviyesi, araç düz zemindeyken ve motor durgunken kontrol edilir: çubuk çıkarılıp silinir, tekrar sonuna kadar daldırılıp çekilir ve yağın alt-üst (min-maks) işaretleri arasında olduğu doğrulanır. Eksikse uygun yağ eklenir.',
    whyWrong: [
      'Motor çalışırken/tam gazda ölçüm hem yanıltıcı hem tehlikelidir.',
      'Yağ seviyesini hiç kontrol etmemek motoru riske atar; lastik basıncı farklı bir kontroldür.',
    ],
    objective: 'Yağ çubuğu ile doğru yağ seviyesi kontrolünü kavramak.',
    tags: ['yaglama', 'yag-seviyesi', 'bakim'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-240',
    subject: 'motor',
    topic: 'antifriz',
    difficulty: 'orta',
    stem: 'Soğuk kış koşullarında soğutma sistemine yalnızca saf su konması hangi riski doğurur?',
    options: [
      'Motorun aşırı güçlenmesi',
      'Farların sönmesi',
      'Lastiklerin şişmesi',
      'Suyun donarak genleşmesi; radyatör, hortum ve motor bloğunda çatlama/hasar riski',
    ],
    answerIndex: 3,
    explanation:
      'Saf su 0 derecede donar ve donarken hacmi artar. Antifrizsiz sistemde soğukta donan su genleşerek radyatörü, hortumları ve hatta motor bloğunu çatlatabilir. Bu yüzden uygun oranda antifriz kullanılmalıdır.',
    whyWrong: [
      'Antifrizsiz su motoru güçlendirmez.',
      'Far sönmesi ve lastik şişmesiyle soğutma suyunun donması arasında ilişki yoktur.',
    ],
    objective: 'Antifrizsiz saf suyun donma-genleşme riskini kavramak.',
    tags: ['antifriz', 'donma', 'sogutma'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
];
