/**
 * ÖZGÜN genişletme — 2. tur (Premium Kalite Programı · Faz 2). ROADMAP C.4/E.6.
 * Kaynak = MEB müfredatı ve Karayolları Trafik Yönetmeliği; KENDİ İFADEMİZLE.
 *
 * ODAK — Faz 0 denetiminde SAYILARAK bulunan boşluklar:
 *   ESP/ASR/çekiş 0 · bagaj ve yük yerleşimi 0 · römork/karavan 1 · motosiklet 3 ·
 *   motor bölmesi 1 · araç içi kumandalar (konu başlığı yok) · ABS 4
 *
 * KALİTE SÖZLEŞMESİ (Faz 1'de kazanılanı Faz 2 geri almasın diye):
 *   · her soruda EN AZ BİR çeldirici doğru şık kadar uzun — "en uzunu seç" pay vermez
 *   · çeldiriciler AYNI ALANDAN ve akla yatkın; "Direksiyonu döndürmek" tipi gürültü yok
 *   · "asla / her zaman / kesinlikle" yalnız çeldiricilerde biriktirilmez
 *   · "Hiçbiri", "Fark etmez" gibi içeriksiz şık yok
 * Bu sözleşmeyi `quality-gate.test.ts` ve `expansion-quality.test.ts` ölçüyor.
 */
import type { QuestionInput } from '@ea/content-schema';

const SRC = 'MEB müfredatı + Karayolları Trafik Yönetmeliği (özgün ifade)';

export const GENISLETME_QUESTIONS_2: QuestionInput[] = [
  /* ─────────────────────────  ESP · ASR · ÇEKİŞ SİSTEMLERİ  ───────────────────────── */
  {
    id: 'gen2-esp-001',
    subject: 'motor',
    topic: 'esp-savrulma-onleyici',
    difficulty: 'orta',
    stem: 'Elektronik denge (savrulma önleyici) sistemi ESP, aracın savrulmaya başladığını nasıl anlar?',
    options: [
      'Motor devrini ve yakıt tüketimini izleyerek sürücünün agresif sürdüğü anları belirler',
      'Fren balatalarının sıcaklığını ölçüp aşırı ısınan tekerleği tespit etmeye çalışır',
      'Lastik hava basınçlarını sürekli okuyup aralarındaki dengesizliği hesaba katar',
      'Direksiyon açısı ile aracın gerçek dönme hareketini karşılaştırıp aradaki farkı ölçer',
    ],
    answerIndex: 3,
    explanation:
      'ESP; direksiyon açısı sensörü, tekerlek hız sensörleri ve aracın kendi ekseni etrafındaki dönüşünü ölçen sensör verilerini sürekli karşılaştırır. Sürücünün gitmek istediği yön ile aracın fiilen gittiği yön ayrışmaya başladığında sistem devreye girer.',
    whyWrong: [
      'Devir ve tüketim bilgisi sürüş tarzını gösterebilir ama savrulmayı ölçmez.',
      'Lastik basıncı ayrı bir sistemin (TPMS) işidir; balata sıcaklığı ise ESP girdisi değildir.',
    ],
    objective: 'ESP’nin savrulmayı hangi ölçümle algıladığını açıklamak.',
    tags: ['esp', 'guvenlik-sistemleri', 'savrulma'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen2-esp-002',
    subject: 'motor',
    topic: 'esp-savrulma-onleyici',
    difficulty: 'zor',
    stem: 'ESP savrulmayı algıladığında aracı rotada tutmak için hangi müdahaleyi yapar?',
    options: [
      'Dört tekerleğe aynı anda tam fren uygulayarak aracı olabildiğince kısa mesafede durdurur',
      'Direksiyon kutusunu kilitleyip sürücünün direksiyonu daha fazla çevirmesini engeller',
      'Seçtiği tek bir tekerleğe hedefli fren uygular ve gerekirse motor gücünü azaltır',
      'Süspansiyonu sertleştirip aracın yere basma kuvvetini geçici olarak yükseltir',
    ],
    answerIndex: 2,
    explanation:
      'ESP’nin gücü, frenin dört tekerleğe eşit değil, seçmeli uygulanmasından gelir. Aracın burnu içe kaçıyorsa dış ön tekerleğe, arka savruluyorsa uygun tekerleğe kısa bir fren basıncı verilir; bu, aracı döndüren bir kuvvet oluşturur. Gerekirse motor gücü de kısılır.',
    whyWrong: [
      'Dört tekerleğe birden tam fren yapmak savrulmayı azaltmaz, çoğu zaman büyütür.',
      'Direksiyonu kilitlemek ya da süspansiyonu sertleştirmek ESP’nin çalışma biçimi değildir.',
    ],
    objective: 'ESP’nin seçmeli fren ve güç kısma ile aracı rotada tuttuğunu kavramak.',
    tags: ['esp', 'guvenlik-sistemleri', 'secmeli-fren'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen2-esp-003',
    subject: 'motor',
    topic: 'esp-savrulma-onleyici',
    difficulty: 'orta',
    stem: 'Sürüş sırasında gösterge panelindeki ESP sembolü kısa kısa yanıp sönüyorsa bu ne anlama gelir?',
    options: [
      'Sistem arızalanmıştır ve aracın bir an önce servise çekilmesi gerektiğini bildiriyordur',
      'Sistem o anda devreye girmiş, tutuş sınırına yaklaşıldığını sürücüye bildiriyordur',
      'Aracın hız sınırlayıcısı devrede olduğu için sürücüye hatırlatma yapılıyordur',
      'Lastik basınçlarından biri düştüğü için sürücünün kontrol etmesi isteniyordur',
    ],
    answerIndex: 1,
    explanation:
      'ESP sembolünün yanıp sönmesi arıza değil, çalışma bildirimidir: sistem o anda müdahale ediyor demektir. Sürücünün doğru tepkisi hızı azaltmak ve gaz-direksiyon girdilerini yumuşatmaktır. Sembolün SABİT yanması ise arıza ya da sistemin kapatılmış olduğu anlamına gelir.',
    whyWrong: [
      'Arıza durumunda sembol yanıp sönmez, sabit yanar.',
      'Hız sınırlayıcı ve lastik basıncı ikazlarının kendi sembolleri vardır.',
    ],
    objective: 'ESP ikazının yanıp sönmesi ile sabit yanması arasındaki farkı ayırt etmek.',
    tags: ['esp', 'gosterge-paneli', 'ikaz-lambasi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen2-esp-004',
    subject: 'motor',
    topic: 'cekis-kontrol',
    difficulty: 'orta',
    stem: 'Çekiş kontrol sistemi (ASR/TCS) ile kilitlenmeyi önleyici fren sistemi (ABS) arasındaki temel işlev farkı nedir?',
    options: [
      'ASR aracın hızını sınırlar, ABS ise fren balatalarının aşınmasını yavaşlatan bir donanımdır',
      'ASR yalnızca dizel araçlarda, ABS ise yalnızca benzinli araçlarda görev yapan sistemlerdir',
      'ASR frende kilitlenmeyi, ABS ise kalkışta patinajı önleyen birbirinin yerine geçen sistemlerdir',
      'ASR gaz verirken tekerleğin boşa dönmesini, ABS ise frende tekerleğin kilitlenmesini önler',
    ],
    answerIndex: 3,
    explanation:
      'İkisi de tekerlek ile yol arasındaki tutuşu korur ama zıt yönlerde çalışır: ASR gaz verilirken çekiş tekerleği boşa dönmeye başlarsa o tekerleğe fren uygular veya motor gücünü kısar; ABS ise frenlemede tekerlek kilitlenmeye başlayınca fren basıncını çözer.',
    whyWrong: [
      'İki sistemin görevi yer değiştirmez; yakıt cinsiyle de ilgileri yoktur.',
      'ASR bir hız sınırlayıcı değildir; ABS’nin amacı balata ömrü değil, yön hâkimiyetidir.',
    ],
    objective: 'ASR ile ABS’nin birbirine zıt görevlerini ayırt etmek.',
    tags: ['asr', 'abs', 'cekis-kontrol', 'guvenlik-sistemleri'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen2-esp-005',
    subject: 'pratik',
    topic: 'cekis-kontrol',
    difficulty: 'zor',
    stem: 'Derin kara saplanan bir araçta bazı sürücülerin çekiş kontrolünü geçici olarak kapatmasının teknik gerekçesi nedir?',
    options: [
      'Sistem kapalıyken motor daha yüksek devir yapabildiği için soğukta daha çabuk ısınır',
      'Sistem kapalıyken fren balataları devreye girmediğinden yakıt tüketimi belirgin düşer',
      'Sistem kapalıyken lastiğin bir miktar dönerek altındaki karı savurup zemin bulması beklenir',
      'Sistem kapalıyken direksiyon hidroliği devreye girer ve ön tekerlekler çok daha kolay çevrilir',
    ],
    answerIndex: 2,
    explanation:
      'Çekiş kontrolü, tekerlek dönmeye başlar başlamaz gücü keser; asfaltta doğru olan bu davranış, derin karda ya da çamurda ters teper çünkü lastiğin altındaki gevşek malzemeyi savurup sert zemine ulaşması engellenir. Bu yüzden birçok araçta sistemi geçici kapatan bir düğme bulunur; çıkıldıktan sonra yeniden açılır.',
    whyWrong: [
      'Sistemin kapatılmasının motor ısınmasıyla ya da yakıt tüketimiyle bir ilgisi yoktur.',
      'Direksiyon hidroliği çekiş kontrolünden bağımsız çalışır.',
    ],
    objective: 'Çekiş kontrolünün gevşek zeminde neden geçici kapatılabildiğini açıklamak.',
    tags: ['cekis-kontrol', 'asr', 'kis-surusu'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen2-esp-006',
    subject: 'motor',
    topic: 'cekis-kontrol',
    difficulty: 'orta',
    stem: 'ABS, ESP ve ASR gibi elektronik destek sistemleriyle donatılmış bir araç için doğru değerlendirme hangisidir?',
    options: [
      'Bu sistemler fizik yasalarını değiştirdiğinden aracın viraj hızı sınırsız biçimde artar',
      'Bu sistemler kış lastiği ihtiyacını tamamen ortadan kaldırdığı için yazlık lastikle sürüş yeterlidir',
      'Bu sistemler bulunan araçta takip mesafesi ve hız kuralları uygulanmak zorunda değildir',
      'Bu sistemler tutuş sınırını genişletmez; yalnızca sınıra yaklaşıldığında sürücüye yardım eder',
    ],
    answerIndex: 3,
    explanation:
      'Elektronik destek sistemleri lastiğin yolla arasındaki sürtünmeyi artırmaz; yalnızca var olan tutuşu daha verimli kullanır. Tutuş bittiğinde ESP de ABS de bir şey yapamaz. Bu yüzden hız, takip mesafesi ve mevsime uygun lastik kuralları bu araçlarda da aynen geçerlidir.',
    whyWrong: [
      'Hiçbir elektronik sistem lastiğin fiziksel tutuş sınırını büyütmez.',
      'Destek sistemleri kuralların ya da kış lastiğinin yerine geçmez.',
    ],
    objective: 'Elektronik destek sistemlerinin fiziksel sınırı değiştirmediğini kavramak.',
    tags: ['esp', 'abs', 'asr', 'surus-guvenligi'],
    review: 'draft',
    sourceRef: SRC,
  },

  /* ─────────────────────────  BAGAJ · YÜK YERLEŞİMİ  ───────────────────────── */
  {
    id: 'gen2-bagaj-001',
    subject: 'trafik',
    topic: 'bagaj-yuk-yerlesimi',
    difficulty: 'orta',
    stem: 'Bagaja ağır bir yük yerleştirilirken en doğru yerleşim hangisidir?',
    options: [
      'Yük, bagajın arka kapağa en yakın ucuna ve olabildiğince yükseğe yerleştirilmelidir',
      'Yük, arka koltuk sırtlığına yaslanacak biçimde alta ve ortaya yerleştirilmelidir',
      'Yük, bagajın bir köşesine sıkıştırılıp diğer taraf boş bırakılarak dengelenmelidir',
      'Yük, kaymasın diye arka cam hizasına kadar yığılıp üstü örtüyle kapatılmalıdır',
    ],
    answerIndex: 1,
    explanation:
      'Ağır yük aracın ağırlık merkezine yakın, mümkün olduğunca alçak ve ortalanmış durmalıdır: arka koltuk sırtlığına yaslanmış, bagaj tabanına oturan bir yük hem ani frende öne fırlamaz hem de aracın yol tutuşunu en az bozar.',
    whyWrong: [
      'Yükü arkaya ve yükseğe koymak arka aksı bastırır, direksiyonu hafifletir ve devrilme eğilimini artırır.',
      'Tek köşeye yığılan yük aracı yana yatırır; cam hizasına kadar yığmak ise arka görüşü tamamen kapatır.',
    ],
    objective:
      'Bagajdaki ağır yükün alçak, ortalanmış ve öne yaslanmış olması gerektiğini kavramak.',
    tags: ['bagaj', 'yuk-yerlesimi', 'agirlik-merkezi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen2-bagaj-002',
    subject: 'trafik',
    topic: 'bagaj-yuk-yerlesimi',
    difficulty: 'zor',
    stem: 'Arka koltuk yatırılarak taşınan sabitlenmemiş ağır bir yükün ani frenlemedeki en büyük tehlikesi nedir?',
    options: [
      'Yük öne doğru fırlayarak koltuklardaki kişilere ağır biçimde çarpabilir',
      'Yükün sürtünmesi bagaj halısını yıpratır ve aracın ikinci el değerini düşürür',
      'Yük hareket ederken çıkardığı ses sürücünün dikkatini bir süre dağıtabilir',
      'Yükün yer değiştirmesi bagaj aydınlatmasının kablosunu koparıp lambayı söndürebilir',
    ],
    answerIndex: 0,
    explanation:
      'Ani frenlemede yük, aracın hızıyla orantılı bir kinetik enerjiyle öne doğru hareket eder; birkaç kilogramlık bir cisim bile bu koşulda ciddi bir darbe kuvvetine ulaşır. Bu yüzden arka koltuk yatırıldığında yük mutlaka bağlanmalı ya da yük filesiyle ayrılmalıdır.',
    whyWrong: [
      'Halı yıpranması, ses ve kablo hasarı gerçek olabilir ama hiçbiri can güvenliği düzeyinde bir tehlike değildir.',
    ],
    objective: 'Sabitlenmemiş yükün ani frende yolculara çarpma riskini kavramak.',
    tags: ['bagaj', 'yuk-sabitleme', 'kaza-guvenligi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen2-bagaj-003',
    subject: 'motor',
    topic: 'bagaj-yuk-yerlesimi',
    difficulty: 'orta',
    stem: 'Aracın azami yüklü ağırlığını aşacak biçimde yüklenmesi hangi sonuçlara yol açar?',
    options: [
      'Fren mesafesi uzar, lastikler aşırı zorlanır ve süspansiyon ile aktarma organları yıpranır',
      'Aracın ağırlık merkezi alçaldığı için yol tutuşu artar ve virajlarda daha kararlı olur',
      'Motor daha çok yük altında çalıştığı için çalışma sıcaklığına daha hızlı ulaşır ve verimi artar',
      'Lastiklerin yere basma alanı büyüdüğünden frenleme performansı belirgin biçimde iyileşir',
    ],
    answerIndex: 0,
    explanation:
      'Aşırı yük her güvenlik unsurunu aynı anda kötüleştirir: durma mesafesi uzar, lastikler tasarım sınırının üstünde ısınıp patlama riskine girer, süspansiyon ve fren sistemi tasarlandığından fazla zorlanır. Ayrıca yasal olarak da ihlaldir.',
    whyWrong: [
      'Yük ağırlık merkezini genellikle YÜKSELTİR; yol tutuşu iyileşmez, bozulur.',
      'Isınma ve temas alanı gerekçeleri güvenlik kazancı sağlamaz; fren performansı düşer.',
    ],
    objective: 'Aşırı yüklemenin fren, lastik ve süspansiyon üzerindeki etkisini açıklamak.',
    tags: ['yuk-yerlesimi', 'azami-agirlik', 'fren-mesafesi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen2-bagaj-004',
    subject: 'trafik',
    topic: 'bagaj-yuk-yerlesimi',
    difficulty: 'orta',
    stem: 'Tavan taşıyıcısına (port bagaj) yük bağlayan bir sürücünün dikkat etmesi gereken temel nokta nedir?',
    options: [
      'Yükün ağırlığı ne olursa olsun tavan taşıyıcının tasarımı gereği sorun çıkmaz',
      'Yük yalnızca öne doğru bağlanmalı, arka tarafı serbest bırakılarak esnemesi sağlanmalıdır',
      'Üreticinin belirttiği tavan yükü sınırı aşılmamalı ve yük her yönden sıkıca bağlanmalıdır',
      'Yükün üzeri branda ile örtülürse bağlamaya gerek kalmaz, branda kaymayı kendisi önler',
    ],
    answerIndex: 2,
    explanation:
      'Tavana konan yük ağırlık merkezini belirgin biçimde yükseltir; bu yüzden üreticinin verdiği tavan yükü sınırı bağlayıcıdır. Yük öne, arkaya ve yanlara karşı ayrı ayrı sabitlenmeli, yolculuk sırasında bağların gevşeyip gevşemediği molalarda kontrol edilmelidir.',
    whyWrong: [
      'Tavan taşıyıcının da bir taşıma sınırı vardır; sınırsız yük taşınamaz.',
      'Tek yönlü bağlama ya da yalnızca branda ile örtme, yükün savrulmasını engellemez.',
    ],
    objective: 'Tavan yükünde ağırlık sınırı ve çok yönlü sabitleme gereğini kavramak.',
    tags: ['bagaj', 'tavan-tasiyici', 'yuk-sabitleme'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen2-bagaj-005',
    subject: 'trafik',
    topic: 'bagaj-yuk-yerlesimi',
    difficulty: 'orta',
    stem: 'Aracın arkasından taşan bir yükün gündüz ve gece nasıl işaretlenmesi gerekir?',
    options: [
      'Gündüz kırmızı bez veya levha ile, gece kırmızı ışık veya yansıtıcı ile işaretlenir',
      'Gündüz beyaz bez ile, gece ise aracın dörtlü ikaz lambaları yakılarak belirtilir',
      'Gündüz herhangi bir işaret gerekmez; yalnızca gece bagaj kapağı açık bırakılır',
      'Gündüz de gece de yalnızca aracın arka sis lambası yakılarak yeterli uyarı sağlanır',
    ],
    answerIndex: 0,
    explanation:
      'Taşan yükün en uç noktası, arkadan gelen sürücülerin aracın gerçek uzunluğunu görebilmesi için işaretlenir: gündüz kırmızı bez veya levha, gece ile görüşün az olduğu zamanlarda kırmızı ışık ya da yansıtıcı kullanılır.',
    whyWrong: [
      'Beyaz bez, dörtlü ikaz veya sis lambası yükün ucunun nerede bittiğini göstermez.',
      'Bagaj kapağının açık bırakılması yükün konumunu belirtmez ve ayrıca tehlikelidir.',
    ],
    objective: 'Taşan yükün gündüz ve gece işaretleme kurallarını bilmek.',
    tags: ['yuk-yerlesimi', 'tasan-yuk', 'isaretleme'],
    review: 'draft',
    sourceRef: SRC,
  },

  /* ─────────────────────────  RÖMORK · KARAVAN  ───────────────────────── */
  {
    id: 'gen2-romork-001',
    subject: 'pratik',
    topic: 'romork-cekme',
    difficulty: 'zor',
    stem: 'Römork veya karavan çekerken yüksek hızda ortaya çıkan "yalpalama" (sallanma) hissedildiğinde doğru tepki nedir?',
    options: [
      'Gazı bırakıp direksiyonu düz tutarak hızın kendiliğinden düşmesini beklemek',
      'Direksiyonu yalpanın tersine hızlı hareketlerle çevirip römorku düzeltmeye çalışmak',
      'Gaza yüklenip hızlanarak römorkun arkadan gerilmesini ve hizalanmasını sağlamak',
      'Fren pedalına sert biçimde basıp aracı olabildiğince kısa mesafede durdurmaya çalışmak',
    ],
    answerIndex: 0,
    explanation:
      'Yalpalama, römorkun kendi salınım frekansına girmesiyle başlar ve her düzeltme hareketi salınımı büyütür. Doğru davranış gazı yumuşakça bırakmak, direksiyonu sabit ve düz tutmak, hız düştükçe salınımın sönmesini beklemektir. Güvenli bir yerde durup yük dağılımı ve ok ağırlığı kontrol edilmelidir.',
    whyWrong: [
      'Direksiyonla düzeltmeye çalışmak salınımı besler ve durumu hızla kötüleştirir.',
      'Hızlanmak yalpayı büyütür; sert fren ise römorkun aracı iterek katlanmasına yol açabilir.',
    ],
    objective: 'Römork yalpalamasında gazı bırakıp direksiyonu sabit tutmayı öğrenmek.',
    tags: ['romork', 'karavan', 'yalpalama', 'surus-guvenligi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen2-romork-002',
    subject: 'trafik',
    topic: 'romork-cekme',
    difficulty: 'orta',
    stem: 'Römork çeken bir araçta yükün ağırlık dağılımıyla ilgili doğru ilke hangisidir?',
    options: [
      'Yükün büyük bölümü römorkun en arkasına konarak çeki demirine binen yük azaltılmalıdır',
      'Yük bütünüyle römorkun ön ucuna yığılarak çeki demirine olabildiğince fazla ağırlık verilmelidir',
      'Yükün ağırlıklı bölümü römork tekerlek aksının biraz önüne, alçak ve dengeli yerleştirilmelidir',
      'Yükün nasıl dağıtıldığının bir önemi yoktur; römorkun kendi frenleri dengeyi sağlar',
    ],
    answerIndex: 2,
    explanation:
      'Römorkta kararlılık, ağırlığın aksın hemen önünde ve alçakta toplanmasıyla sağlanır. Bu yerleşim çeki demirine ölçülü bir bastırma kuvveti bırakır. Ağırlık arkaya kayarsa ok yukarı kalkar ve yalpalama riski hızla artar.',
    whyWrong: [
      'Arkaya yığmak çeki noktasındaki ağırlığı azaltıp römorku kararsız hâle getirir.',
      'Öne aşırı yığmak arka aksı ezer; römork frenleri yanlış yük dağılımını telafi etmez.',
    ],
    objective: 'Römork yükünün aksın önünde ve alçakta toplanması gerektiğini kavramak.',
    tags: ['romork', 'yuk-yerlesimi', 'ceki-demiri'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen2-romork-003',
    subject: 'pratik',
    topic: 'romork-cekme',
    difficulty: 'zor',
    stem: 'Römork takılı bir araçla geri manevra yapılırken direksiyon hareketinin römorka etkisi nasıldır?',
    options: [
      'Römork, çeken aracın direksiyonuyla aynı yöne ve aynı miktarda hareket ederek onu geriye doğru izler',
      'Römorkun arkası, direksiyonun çevrildiği yönün TERSİNE doğru kayar; hareket ters ve abartılıdır',
      'Römork geri viteste kendi tekerlekleriyle yönlendiğinden direksiyondan etkilenmez',
      'Römork geri manevrada olduğu yerde sabit kalır, yalnızca çeken araç kendi ekseninde döner',
    ],
    answerIndex: 1,
    explanation:
      'Geri giderken çeken araç römorku itmiş olur; direksiyon sağa çevrildiğinde römorkun arkası sola yönelir. Bu yüzden manevra küçük direksiyon girdileriyle, sık sık durup aynalardan kontrol ederek yapılır. Deneyimsiz sürücülerin en sık hatası büyük ve geç düzeltmelerdir.',
    whyWrong: [
      'Römork ileri giderken aracı izler; geri giderken bu ilişki tersine döner.',
      'Römorkun tekerlekleri yönlendirilmez ve manevrada sabit kalmaz.',
    ],
    objective: 'Römorkla geri manevrada direksiyon-römork ilişkisinin ters olduğunu kavramak.',
    tags: ['romork', 'geri-manevra', 'karavan'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen2-romork-004',
    subject: 'trafik',
    topic: 'romork-cekme',
    difficulty: 'orta',
    stem: 'Römork veya karavan çeken bir araçta takip mesafesi konusunda doğru yaklaşım nedir?',
    options: [
      'Römork ek fren gücü sağladığı için takip mesafesi normalden kısaltılabilir',
      'Takip mesafesi römorksuz sürüşle aynı tutulur; toplam ağırlığın frenlemeye etkisi yoktur',
      'Toplam ağırlık ve fren mesafesi arttığı için takip mesafesi belirgin biçimde artırılmalıdır',
      'Takip mesafesi yalnızca römork yüklüyse artırılır; boş römorkta değiştirmeye hiç gerek yoktur',
    ],
    answerIndex: 2,
    explanation:
      'Römork, aracın toplam kütlesini büyütür; aynı hızda durmak için gereken mesafe uzar. Ayrıca fren sırasında römorkun itme etkisi aracı dengesizleştirebilir. Bu yüzden takip mesafesi normal sürüşe göre belirgin biçimde açılır ve frenlemeye erken başlanır.',
    whyWrong: [
      'Römork fren gücü eklemez; aksine durdurulacak kütleyi büyütür.',
      'Boş römork bile ek kütle ve ek fren mesafesi demektir.',
    ],
    objective: 'Römorkla sürüşte takip mesafesinin artırılması gerektiğini kavramak.',
    tags: ['romork', 'takip-mesafesi', 'fren-mesafesi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen2-romork-005',
    subject: 'trafik',
    topic: 'romork-cekme',
    difficulty: 'orta',
    stem: 'Römork bağlantısı yapıldıktan sonra yola çıkmadan önce yapılması gereken kontroller hangileridir?',
    options: [
      'Yalnızca çeki demirinin kilitli olduğuna bakmak, diğer kontrolleri ilk molaya bırakmak',
      'Kilit, emniyet halatı, elektrik soketi ile stop-sinyal lambalarının çalışması ve lastik basınçları',
      'Yalnızca römork lastiklerinin havasına bakmak; aydınlatma çeken araçtan beslendiği için ayrıca gerekmez',
      'Yalnızca römork üzerindeki yükün brandayla örtülüp örtülmediğini gözden geçirmek yeterlidir',
    ],
    answerIndex: 1,
    explanation:
      'Römork bağlantısı bir kontrol listesidir: çeki topuzunun kilitlendiği, emniyet halatının bağlandığı, elektrik soketinin takıldığı ve buna bağlı olarak stop, sinyal ile plaka aydınlatmasının çalıştığı, ayrıca römork lastiklerinin basınç ve diş durumu tek tek doğrulanır.',
    whyWrong: [
      'Tek bir maddeye bakmak, kalan maddelerin yolda arıza vermesini engellemez.',
      'Aydınlatma çeken araçtan beslense de soket ya da ampul arızası yolda ortaya çıkar; kontrol gerekir.',
    ],
    objective: 'Römork bağlantısı sonrası yapılacak kontrol listesini bilmek.',
    tags: ['romork', 'on-kontrol', 'karavan'],
    review: 'draft',
    sourceRef: SRC,
  },

  /* ─────────────────────────  MOTOSİKLET  ───────────────────────── */
  {
    id: 'gen2-moto-001',
    subject: 'trafik',
    topic: 'motosiklet-guvenlik',
    difficulty: 'orta',
    stem: 'Otomobil sürücüsünün kavşakta motosikletlileri fark etmekte zorlanmasının başlıca nedeni nedir?',
    options: [
      'Motosikletlerin kural gereği gündüz saatlerinde farlarını sürekli kapalı tutmak zorunda olması',
      'Motosikletlerin dar siluetinin direk, ayna ve diğer araçların arkasında kolayca kaybolması',
      'Motosikletlerin otomobillerden daha yavaş gitmesi ve bu yüzden geç görünmesi',
      'Motosikletlerin egzoz sesinin kavşaklarda duyulmaması ve dikkat çekmemesi',
    ],
    answerIndex: 1,
    explanation:
      'Motosiklet önden bakıldığında çok dar bir siluet oluşturur; ön direk, dikiz aynası ya da öndeki bir araç onu kolayca gizler. Ayrıca dar cisimlerin yaklaşma hızı gözle yanlış tahmin edilir. Bu yüzden kavşakta bir kez değil, iki kez bakmak öğretilir.',
    whyWrong: [
      'Motosikletlerde gündüz farı yakmak yaygın bir güvenlik uygulamasıdır, yasak değildir.',
      'Motosikletler yavaş olmak zorunda değildir; ses de görünürlüğün yerine geçmez.',
    ],
    objective: 'Motosikletin dar siluetinden doğan görünürlük sorununu kavramak.',
    tags: ['motosiklet', 'kavsak', 'gorunurluk'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen2-moto-002',
    subject: 'trafik',
    topic: 'motosiklet-guvenlik',
    difficulty: 'orta',
    stem: 'Motosiklet ve motorlu bisiklet sürücüleri ile yolcuları için koruma başlığı (kask) kullanımıyla ilgili doğru ifade hangisidir?',
    options: [
      'Kask yalnızca şehirlerarası yollarda ve yalnızca sürücü için zorunlu tutulmuştur',
      'Kask yalnızca belirli bir hızın üzerine çıkıldığında takılması gereken bir donanımdır',
      'Kask hem sürücü hem yolcu için zorunludur ve standartlara uygun olmalıdır',
      'Kask kullanımı sürücünün tercihine bırakılmıştır; yalnızca sınavda zorunlu tutulur',
    ],
    answerIndex: 2,
    explanation:
      'Koruma başlığı sürücü ve yolcu ayrımı yapmadan zorunludur ve standartlara uygun, doğru takılmış olmalıdır. Kask, motosiklet kazalarında ölümcül kafa yaralanmalarını azaltan tek en etkili donanımdır.',
    whyWrong: [
      'Zorunluluk yol türüne, hıza ya da yalnızca sürücüye bağlı değildir.',
      'Kask kullanımı kişisel tercih değil, yasal bir yükümlülüktür.',
    ],
    objective: 'Kask zorunluluğunun sürücü ve yolcuyu birlikte kapsadığını bilmek.',
    tags: ['motosiklet', 'kask', 'koruyucu-donanim'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen2-moto-003',
    subject: 'pratik',
    topic: 'motosiklet-guvenlik',
    difficulty: 'zor',
    stem: 'Islak zeminde ilerleyen bir motosikletliyi sollarken otomobil sürücüsünün ek olarak dikkat etmesi gereken nedir?',
    options: [
      'Sollama sırasında oluşan hava basıncı ve su sıçraması motosikletlinin dengesini bozabilir',
      'Motosikletli ıslak zeminde daha hızlı gittiği için sollama süresi normalden uzun sürer',
      'Motosikletin frenleri ıslakken çalışmadığından sollama sonrası aniden hızlanması beklenir',
      'Islak zeminde motosikletin egzoz gazı arttığı için sollama sırasında görüş kısıtlanır',
    ],
    answerIndex: 0,
    explanation:
      'Yakından ve hızlı yapılan sollama, iki tekerlekli aracı iten bir hava dalgası ve tekerleklerden savrulan su bırakır; ıslak zeminde tutuşu zaten azalmış olan motosikletli bu etkiyle dengesini kaybedebilir. Doğrusu hızı azaltmak ve geniş yan mesafeyle geçmektir.',
    whyWrong: [
      'Motosikletin ıslakta daha hızlı gitmesi ya da frenlerinin çalışmaması gibi bir durum yoktur.',
      'Egzoz gazı sollamada görüşü kısıtlayan bir etken değildir.',
    ],
    objective: 'Motosikletliyi sollarken hava basıncı ve su sıçramasının etkisini kavramak.',
    tags: ['motosiklet', 'sollama', 'islak-zemin'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen2-moto-004',
    subject: 'pratik',
    topic: 'motosiklet-guvenlik',
    difficulty: 'orta',
    stem: 'Motosikletin frenlemesiyle ilgili doğru bilgi hangisidir?',
    options: [
      'Yalnızca arka fren kullanılmalıdır; ön fren motosiklette hiçbir koşulda devreye alınmaz',
      'Ön ve arka fren birlikte, kademeli biçimde kullanılır; frenleme gücünün çoğu öndedir',
      'Ön ve arka frenin ikisi de aynı anda sonuna kadar sıkılarak en kısa mesafede durulur',
      'Fren yerine motor freni yeterlidir; motosiklette fren kolları yalnızca park için kullanılır',
    ],
    answerIndex: 1,
    explanation:
      'Frenlemede ağırlık öne aktarıldığı için ön tekerlek daha çok yol tutar ve frenleme gücünün büyük bölümünü o üretir. Doğru teknik iki freni de kademeli ve birlikte kullanmaktır; ani ve tam sıkma tekerleği kilitleyip düşmeye yol açabilir.',
    whyWrong: [
      'Ön freni hiç kullanmamak fren mesafesini ciddi biçimde uzatır.',
      'İki freni birden sonuna kadar sıkmak kilitlenme ve düşme riski yaratır; motor freni tek başına yetmez.',
    ],
    objective: 'Motosiklette ön-arka fren dengesini ve kademeli frenlemeyi kavramak.',
    tags: ['motosiklet', 'fren-teknigi', 'surus-teknigi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen2-moto-005',
    subject: 'trafik',
    topic: 'motosiklet-guvenlik',
    difficulty: 'orta',
    stem: 'Motosiklet sürücüsünün kask dışında kullanması önerilen koruyucu donanımlar hangileridir?',
    options: [
      'Yalnızca güneş gözlüğü ve ince kumaştan yapılmış rahat bir yazlık giysi yeterlidir',
      'Yalnızca eldiven; ceket, pantolon ve bot yalnızca uzun yolculuklarda gerekli olur',
      'Korumalı ceket ve pantolon, eldiven ile bilekleri kapatan sağlam ayakkabı veya bot',
      'Yalnızca yansıtıcı yelek; darbe koruması kaskın kendisi tarafından zaten sağlanır',
    ],
    answerIndex: 2,
    explanation:
      'Düşme anında vücudun asfaltla ilk temas eden bölgeleri eller, dirsekler, dizler ve ayak bilekleridir. Korumalı ceket ve pantolon, eldiven ile bilekleri saran bot bu bölgeleri hem sıyrıktan hem darbeden korur. Kask yalnızca başı korur.',
    whyWrong: [
      'İnce yazlık giysi ve güneş gözlüğü düşmede hiçbir koruma sağlamaz.',
      'Koruma ihtiyacı yolun uzunluğuna bağlı değildir; yansıtıcı yelek görünürlük sağlar ama darbe korumaz.',
    ],
    objective: 'Motosiklette kask dışındaki koruyucu donanımları saymak.',
    tags: ['motosiklet', 'koruyucu-donanim', 'kask'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen2-moto-006',
    subject: 'trafik',
    topic: 'motosiklet-guvenlik',
    difficulty: 'zor',
    stem: 'Motosikletliler için yol yüzeyindeki hangi unsurlar otomobillere göre çok daha büyük tehlike oluşturur?',
    options: [
      'Rögar kapağı, boyalı çizgiler, mazgal ve yol üzerindeki çakıl ile yağ lekeleri',
      'Yol kenarındaki bilgi levhaları ile kilometre taşlarının yerleşim düzeni',
      'Yolun asfalt renginin açık ya da koyu olması ve şerit çizgilerinin genişliği ile aralığı',
      'Yol boyunca dikilmiş ağaçların gövde kalınlığı ve gölge bıraktıkları alanlar',
    ],
    answerIndex: 0,
    explanation:
      'İki tekerlekli araç dengesini tutuşa borçludur ve yalnızca iki küçük temas alanı vardır. Kaygan metal kapaklar, ıslak boya çizgileri, mazgallar ve dağılmış çakıl bu temas alanını bir anda kaybettirebilir; otomobilde aynı yüzey fark bile edilmez.',
    whyWrong: ['Levhalar, asfalt rengi ya da ağaçlar tutuşla ilgili bir tehlike oluşturmaz.'],
    objective: 'Motosiklet için kaygan yüzeylerin neden daha tehlikeli olduğunu kavramak.',
    tags: ['motosiklet', 'yol-yuzeyi', 'kayma-riski'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen2-moto-007',
    subject: 'trafik',
    topic: 'motosiklet-guvenlik',
    difficulty: 'orta',
    stem: 'Trafikte motosikletli bir araca yaklaşan otomobil sürücüsünün takip mesafesiyle ilgili doğru davranışı nedir?',
    options: [
      'Motosiklet küçük olduğu için takip mesafesi otomobile göre kısaltılabilir',
      'Takip mesafesi motosikletlerde önemsizdir; asıl önemli olan bırakılan yan mesafedir',
      'Motosiklet çok kısa mesafede durabildiğinden takip mesafesi normalden fazla tutulur',
      'Takip mesafesi yalnızca motosikletin arkasında yolcu varsa artırılmalıdır',
    ],
    answerIndex: 2,
    explanation:
      'Motosiklet, hafif olduğu ve iyi bir sürücü elinde çok kısa mesafede durabildiği için önündeki ani duruşu otomobilden daha çabuk gerçekleştirebilir. Arkasındaki otomobilin aynı mesafede durması mümkün olmayabilir; bu yüzden takip mesafesi açılır.',
    whyWrong: [
      'Aracın küçük olması durma mesafesini kısaltmaz; mesafeyi kısaltmak riski büyütür.',
      'Yan mesafe önemlidir ama takip mesafesinin yerine geçmez; yolcu olup olmaması ölçüt değildir.',
    ],
    objective:
      'Motosikletin kısa durma mesafesi nedeniyle takip mesafesinin artırılmasını kavramak.',
    tags: ['motosiklet', 'takip-mesafesi', 'fren-mesafesi'],
    review: 'draft',
    sourceRef: SRC,
  },

  /* ─────────────────────────  MOTOR BÖLMESİ (KAPUT ALTI)  ───────────────────────── */
  {
    id: 'gen2-bolme-001',
    subject: 'motor',
    topic: 'motor-bolmesi',
    difficulty: 'orta',
    stem: 'Kaput açıldığında motor bölmesinde görülen sarı halkalı çubuk (yağ çubuğu) neyi kontrol etmeye yarar?',
    options: [
      'Soğutma suyunun sıcaklığını ve donma noktasını ölçmeye yarayan bir gösterge çubuğudur',
      'Fren hidroliğinin seviyesini ve içindeki nem oranını okumaya yarayan bir ölçüm aracıdır',
      'Motor karterindeki yağın seviyesini asgari ve azami işaretleri arasında görmeye yarar',
      'Akü sıvısının yoğunluğunu ölçüp şarj durumunu belirlemeye yarayan bir ölçüm çubuğudur',
    ],
    answerIndex: 2,
    explanation:
      'Yağ çubuğu, karterdeki yağ seviyesini gösterir. Motor düz zeminde ve durgunken çubuk çekilir, silinir, tekrar sonuna kadar daldırılıp çıkarılır; iz, alt (min) ve üst (maks) işaretleri arasında olmalıdır.',
    whyWrong: [
      'Soğutma suyu genleşme deposundan, fren hidroliği kendi kabından okunur.',
      'Akü yoğunluğu hidrometreyle ölçülür; yağ çubuğuyla ilgisi yoktur.',
    ],
    objective: 'Motor bölmesindeki yağ çubuğunun görevini tanımak.',
    tags: ['motor-bolmesi', 'yag-cubugu', 'on-kontrol'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen2-bolme-002',
    subject: 'motor',
    topic: 'motor-bolmesi',
    difficulty: 'orta',
    stem: 'Motor bölmesinde bulunan yarı saydam, üzerinde MIN-MAX işaretleri olan ve renkli sıvı içeren kap hangisidir?',
    options: [
      'Soğutma sisteminin genleşme (yedek su) deposu; seviye motor soğukken kontrol edilir',
      'Ön cam yıkama suyu deposu; bu depoda MIN-MAX işaretleri bulunması zorunludur',
      'Motor yağının depolandığı ana hazne; yağ buradan doğrudan gözle görülerek ölçülür',
      'Yakıt filtresinin çökeltme kabı; içindeki sıvı düzenli olarak boşaltılmak zorundadır',
    ],
    answerIndex: 0,
    explanation:
      'Genleşme deposu, soğutma suyunun ısınınca genleşmesine yer açar ve seviyeyi gözle kontrol etmeyi sağlar. Üzerindeki MIN-MAX işaretleri motor SOĞUKKEN geçerlidir; sıcak motorda sistem basınçlı olduğu için kapak açılmaz.',
    whyWrong: [
      'Cam suyu deposu genellikle işaretsizdir ve içinde renkli soğutma sıvısı bulunmaz.',
      'Motor yağı karterde durur, gözle değil çubukla ölçülür; yakıt filtresi kabı bu kapla karıştırılmamalıdır.',
    ],
    objective: 'Genleşme deposunu motor bölmesinde tanımak ve soğukken okumayı bilmek.',
    tags: ['motor-bolmesi', 'genlesme-deposu', 'sogutma-sistemi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen2-bolme-003',
    subject: 'motor',
    topic: 'motor-bolmesi',
    difficulty: 'zor',
    stem: 'Motor bölmesinde çalışırken uyulması gereken güvenlik kuralları hangi seçenekte doğru verilmiştir?',
    options: [
      'Motor sıcakken radyatör kapağı açılabilir; yalnızca elin bezle korunması yeterli olur',
      'Fan durmuşsa tekrar dönmez; bu yüzden kaput altında serbestçe çalışılabilir',
      'Motor durdurulur, soğuması beklenir; fanın kendiliğinden dönebileceği unutulmaz',
      'Akü kutup başları çıplak elle sökülür; eldiven yalnızca kirlenmeyi önlemek içindir',
    ],
    answerIndex: 2,
    explanation:
      'Kaput altı iki tehlike barındırır: yüksek sıcaklık ve hareketli parçalar. Motor durdurulup soğuması beklenir; buna rağmen elektro fan, kontak kapalıyken bile termostat müşiriyle bir süre daha devreye girebilir. Radyatör kapağı ise sistem basınçlıyken kesinlikle açılmaz.',
    whyWrong: [
      'Sıcak sistemde kapak açmak basınçlı kaynar su püskürmesine ve ağır yanığa yol açar.',
      'Fanın durmuş olması bir daha dönmeyeceği anlamına gelmez; akü işlemlerinde de yalıtım gerekir.',
    ],
    objective: 'Motor bölmesinde sıcaklık ve fan kaynaklı riskleri tanımak.',
    tags: ['motor-bolmesi', 'guvenlik', 'elektro-fan'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen2-bolme-004',
    subject: 'motor',
    topic: 'motor-bolmesi',
    difficulty: 'orta',
    stem: 'Motor bölmesinde kayışların (yardımcı/V kayışı) gerginliği ve durumu neden düzenli kontrol edilir?',
    options: [
      'Kayış koparsa alternatör ve su pompası gibi parçalar tahrik alamaz ve araç yolda kalır',
      'Kayış gevşerse motor yağının basıncı düşer ve karterdeki yağ seviyesi hızla azalır',
      'Kayışın gergin olması yakıt pompasının basıncını yükselterek tüketimi belirgin düşürür',
      'Kayış aşınırsa fren hidroliği kirlenir ve fren pedalı zamanla sertleşmeye başlar',
    ],
    answerIndex: 0,
    explanation:
      'Yardımcı kayış, motorun dönüşünü alternatöre, su pompasına ve genellikle direksiyon ile klima kompresörüne aktarır. Koptuğunda şarj kesilir, soğutma suyu dolaşmaz ve motor kısa sürede hararet yapar; bu yüzden çatlak, sertleşme ve gevşeklik düzenli kontrol edilir.',
    whyWrong: [
      'Yağ basıncı yağ pompasına bağlıdır; kayış gerginliğiyle doğrudan ilgisi yoktur.',
      'Kayışın yakıt basıncı ve fren hidroliğiyle bir bağlantısı bulunmaz.',
    ],
    objective: 'Yardımcı kayışın hangi parçaları tahrik ettiğini ve kopmasının sonucunu kavramak.',
    tags: ['motor-bolmesi', 'kayis', 'alternator', 'su-pompasi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen2-bolme-005',
    subject: 'motor',
    topic: 'motor-bolmesi',
    difficulty: 'orta',
    stem: 'Motor bölmesindeki sigorta kutusunun görevi aşağıdakilerden hangisidir?',
    options: [
      'Motorun ürettiği fazla ısıyı emerek kabine geçmesini önleyen bir yalıtım bölmesidir',
      'Elektrik devrelerini aşırı akıma karşı koruyup arıza hâlinde devreyi kesen elemanları taşır',
      'Yakıt hattındaki basıncı düzenleyip enjektörlere giden yakıtı süzen bir filtre ve pompa grubudur',
      'Soğutma suyunun akış yönünü mevsime göre değiştiren vanaların toplandığı bir kutudur',
    ],
    answerIndex: 1,
    explanation:
      'Sigortalar, bir devrede beklenenden yüksek akım geçtiğinde eriyerek devreyi keser ve kabloların ısınıp yangına yol açmasını önler. Atan bir sigortanın yerine daima aynı amperajda olanı takılır; daha yüksek amperajlı sigorta korumayı devre dışı bırakır.',
    whyWrong: ['Isı yalıtımı, yakıt süzme ve soğutma vanaları başka bileşenlerin işidir.'],
    objective: 'Sigorta kutusunun aşırı akım koruması sağladığını kavramak.',
    tags: ['motor-bolmesi', 'sigorta', 'elektrik-sistemi'],
    review: 'draft',
    sourceRef: SRC,
  },

  /* ─────────────────────────  ARAÇ İÇİ KUMANDALAR  ───────────────────────── */
  {
    id: 'gen2-kumanda-001',
    subject: 'motor',
    topic: 'arac-ici-kumandalar',
    difficulty: 'kolay',
    stem: 'Gösterge panelinde içinde ünlem işareti bulunan, yandan kesilmiş lastik biçimindeki sarı ikaz neyi bildirir?',
    options: [
      'Lastiklerden en az birinin hava basıncının önerilen değerin altına düştüğünü bildirir',
      'Lastiklerin diş derinliğinin yasal sınırın altına indiğini ve değişmesi gerektiğini bildirir',
      'Lastiklerin mevsime uygun olmadığını ve kış lastiği takılması gerektiğini bildirir',
      'Lastik balans ayarının bozulduğunu ve dengeleme yapılması gerektiğini bildirir',
    ],
    answerIndex: 0,
    explanation:
      'Bu sembol lastik basıncı izleme sisteminin (TPMS) ikazıdır ve basıncın düştüğünü gösterir. Araç güvenli bir yerde durdurulup dört lastiğin basıncı ölçülmeli, gerekirse üreticinin verdiği değere tamamlanmalıdır.',
    whyWrong: [
      'Diş derinliği, mevsim uygunluğu ve balans durumu elektronik olarak izlenmez; gözle ve serviste kontrol edilir.',
    ],
    objective: 'Lastik basıncı ikaz sembolünü tanımak.',
    tags: ['arac-ici-kumandalar', 'gosterge-paneli', 'lastik-basinc'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen2-kumanda-002',
    subject: 'motor',
    topic: 'arac-ici-kumandalar',
    difficulty: 'orta',
    stem: 'Kabin havalandırmasındaki "iç hava sirkülasyonu" (devridaim) düğmesinin görevi nedir?',
    options: [
      'Dışarıdan hava almayı keserek kabindeki havayı yeniden dolaştırır; tünelde ve kokulu ortamda işe yarar',
      'Klima kompresörünü devreden çıkarıp yalnızca fanla üfleme yapılmasını sağlayan bir düğmedir',
      'Ön cam üfleme kanallarını açıp kapatarak buğunun hızlı giderilmesini sağlayan bir kumandadır',
      'Kabin sıcaklığını otomatik olarak ayarlayıp fan hızını ve üfleme yönünü kendiliğinden değiştiren bir donanımdır',
    ],
    answerIndex: 0,
    explanation:
      'Devridaim, dış hava girişini kapatır ve kabindeki havayı yeniden dolaştırır. Tünelde, yoğun trafikte ya da kötü kokulu bir bölgede geçici olarak açılır. Uzun süre açık bırakılırsa kabinde nem birikip camlar buğulanır.',
    whyWrong: ['Klimayı kapatan, cama üfleyen ve sıcaklığı otomatik ayarlayan kumandalar ayrıdır.'],
    objective: 'İç hava devridaim düğmesinin işlevini ve doğru kullanım anını kavramak.',
    tags: ['arac-ici-kumandalar', 'klima', 'havalandirma'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen2-kumanda-003',
    subject: 'motor',
    topic: 'arac-ici-kumandalar',
    difficulty: 'orta',
    stem: 'Direksiyon üzerindeki sinyal kolunun aşağı ve yukarı hareketleri neyi ifade eder?',
    options: [
      'Aşağı hareket sol sinyali, yukarı hareket sağ sinyali çalıştırır',
      'Aşağı hareket kısa farı, yukarı hareket uzun farı devreye alan bir kumandadır',
      'Aşağı hareket ön silecekleri, yukarı hareket arka sileceği çalıştıran bir koldur',
      'Aşağı hareket dörtlü ikazı, yukarı hareket korna işlevini devreye sokan bir koldur',
    ],
    answerIndex: 0,
    explanation:
      'Sinyal kolu direksiyonun döneceği yönle aynı mantıkta çalışır: kol aşağı indirildiğinde direksiyon sola dönerken geri döneceği yön gibi sol sinyal, yukarı kaldırıldığında sağ sinyal yanar. Manevra bitince kol genellikle kendiliğinden ortaya döner.',
    whyWrong: [
      'Far kademesi genellikle kolun kendisine doğru çekilmesi ya da ucundaki halkayla seçilir.',
      'Silecekler ayrı bir kolda, dörtlü ikaz ise konsoldaki kırmızı üçgen düğmededir.',
    ],
    objective: 'Sinyal kolunun yön mantığını bilmek.',
    tags: ['arac-ici-kumandalar', 'sinyal', 'direksiyon'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen2-kumanda-004',
    subject: 'motor',
    topic: 'arac-ici-kumandalar',
    difficulty: 'orta',
    stem: 'Konsolda bulunan kırmızı üçgen sembollü düğmenin işlevi nedir ve ne zaman kullanılır?',
    options: [
      'Dörtlü ikaz lambalarını yakar; arıza, kaza ve tehlike bildirimi gibi durumlarda kullanılır',
      'Arka cam rezistansını çalıştırır; camda buğu ve buzlanma olduğunda devreye alınır',
      'Aracın hız sabitleyicisini açar; otoyolda sabit hızla seyrederken kullanılan bir kumandadır',
      'Merkezi kilit sistemini devre dışı bırakır; kapıların tek tek kilitlenmesini sağlar',
    ],
    answerIndex: 0,
    explanation:
      'Kırmızı üçgen sembolü dörtlü ikaz (flaşör) düğmesidir. Aracın arızalanması, kaza yapması, zorunlu durması ya da arkadan gelenlerin uyarılması gereken durumlarda kullanılır; normal park veya kısa duraklama için sürekli yakılması yanlış bir alışkanlıktır.',
    whyWrong: [
      'Arka cam rezistansı dikdörtgen ve dalgalı ok sembollüdür.',
      'Hız sabitleyici direksiyon üzerinde, merkezi kilit ise kapı panelinde bulunur.',
    ],
    objective: 'Dörtlü ikaz düğmesini tanımak ve doğru kullanım anını bilmek.',
    tags: ['arac-ici-kumandalar', 'dortlu-ikaz', 'acil-durum'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen2-kumanda-005',
    subject: 'motor',
    topic: 'arac-ici-kumandalar',
    difficulty: 'orta',
    stem: 'Far kumandasında bulunan "otomatik far" (AUTO) konumu ne yapar?',
    options: [
      'Ortam ışığını algılayan sensöre göre kısa farları kendiliğinden yakar ve söndürür',
      'Farların yükseklik ayarını yola göre otomatik değiştirip huzmeyi sürekli aşağı tutar',
      'Uzun farı karşı araç geldiğinde kısaltıp geçtikten sonra yeniden uzun fara döndürür',
      'Sis lambalarını hava durumu verisine göre kendiliğinden devreye alıp çıkarır',
    ],
    answerIndex: 0,
    explanation:
      'AUTO konumu bir ışık sensörüne bağlıdır: hava kararınca ya da tünele girilince kısa farlar kendiliğinden yanar, aydınlıkta söner. Sensörün algılayamadığı sis ve yoğun yağış gibi durumlarda sürücünün farları elle açması gerekir.',
    whyWrong: [
      'Far yükseklik ayarı ayrı bir tekerlekle yapılır.',
      'Uzun farı otomatik kısaltan sistem ile sis lambası kumandası farklı donanımlardır.',
    ],
    objective: 'Otomatik far konumunun ne yaptığını ve sınırını bilmek.',
    tags: ['arac-ici-kumandalar', 'far', 'otomatik-far'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen2-kumanda-006',
    subject: 'pratik',
    topic: 'arac-ici-kumandalar',
    difficulty: 'zor',
    stem: 'Sürüş sırasında bilinmeyen bir kumandayı aramak neden tehlikelidir ve doğrusu nedir?',
    options: [
      'Kumandayı ararken bakış yoldan ayrılır; kumandalar araca binmeden önce tanınmalıdır',
      'Kumandayı ararken el direksiyondan ayrıldığı için aracın hidroliği devre dışı kalır',
      'Kumandayı ararken motor devri düştüğü için araç yavaşlar ve arkadan çarpma riski doğar',
      'Kumandayı ararken kabin sıcaklığı değiştiği için camlar aniden buğulanmaya başlar',
    ],
    answerIndex: 0,
    explanation:
      'Bir düğmeyi ararken göz birkaç saniye yoldan ayrılır; 90 km/saat hızda iki saniye, yolu görmeden 50 metre gitmek demektir. Bu yüzden yabancı bir araca binildiğinde hareket etmeden önce silecek, sinyal, far, dörtlü ikaz ve el freninin yeri kısaca gözden geçirilir.',
    whyWrong: [
      'Elin direksiyondan ayrılması hidroliği devre dışı bırakmaz.',
      'Motor devri ve kabin sıcaklığı kumanda aramanın doğrudan sonucu değildir.',
    ],
    objective: 'Kumandaların sürüş öncesinde tanınması gerektiğini kavramak.',
    tags: ['arac-ici-kumandalar', 'dikkat-dagilmasi', 'on-kontrol'],
    review: 'draft',
    sourceRef: SRC,
  },

  /* ─────────────────────────  ABS DERİNLEŞTİRME  ───────────────────────── */
  {
    id: 'gen2-abs-001',
    subject: 'pratik',
    topic: 'abs-fren',
    difficulty: 'orta',
    stem: 'ABS devrede olan bir araçta acil frenleme sırasında fren pedalında hissedilen titreşim ve tıkırtı ne anlama gelir?',
    options: [
      'Sistem arızalanmıştır; pedal bırakılıp yalnızca el freniyle yavaşlamak gerekiyordur',
      'Sistem çalışıyordur; pedal bırakılmadan basılı tutulur ve direksiyonla yön verilir',
      'Fren balataları bitmiştir; pedala kesik kesik basarak fren gücü toplanmalıdır',
      'Fren hidroliğine hava girmiştir; araç durdurulup sistemin havası alınmalıdır',
    ],
    answerIndex: 1,
    explanation:
      'Titreşim, ABS’nin fren basıncını saniyede birçok kez çözüp yeniden uygulamasından doğar; yani sistem tam olarak görevini yapıyordur. Doğru davranış pedalı kararlılıkla basılı tutmak ve boşalan yön hâkimiyetini kullanarak engelin etrafından dolaşmaktır.',
    whyWrong: [
      'Pedalı bırakmak ya da pompalamak ABS’li araçta fren mesafesini uzatır.',
      'Titreşim balata bitmesinin ya da hidroliğe hava girmesinin belirtisi değildir.',
    ],
    objective: 'ABS titreşiminin arıza değil çalışma belirtisi olduğunu kavramak.',
    tags: ['abs', 'acil-fren', 'fren-teknigi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen2-abs-002',
    subject: 'motor',
    topic: 'abs-fren',
    difficulty: 'zor',
    stem: 'ABS’nin fren mesafesiyle ilgili doğru değerlendirme hangisidir?',
    options: [
      'ABS her zeminde fren mesafesini kısaltır; karda ve çakılda bile en kısa duruşu sağlar',
      'ABS fren mesafesini değiştirmez; tek katkısı fren balatalarının ömrünü uzatmasıdır',
      'ABS asıl olarak yön hâkimiyetini korur; gevşek zeminde mesafeyi bir miktar uzatabilir',
      'ABS yalnızca kuru asfaltta çalışır; ıslak ve karlı zeminde kendiliğinden devre dışı kalır',
    ],
    answerIndex: 2,
    explanation:
      'ABS’nin amacı en kısa mesafe değil, frenlerken direksiyonun işe yaramaya devam etmesidir. Kar ve çakıl gibi gevşek zeminlerde kilitlenen tekerleğin önünde biriken malzeme aracı yavaşlattığı için ABS’li duruş bir miktar uzayabilir; buna karşılık sürücü engelden kaçabilir.',
    whyWrong: [
      'ABS her zeminde mesafeyi kısaltmaz ve balata ömrü için tasarlanmamıştır.',
      'Sistem zemin türüne göre kendiliğinden devre dışı kalmaz.',
    ],
    objective: 'ABS’nin asıl kazanımının yön hâkimiyeti olduğunu kavramak.',
    tags: ['abs', 'fren-mesafesi', 'yon-hakimiyeti'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen2-abs-003',
    subject: 'motor',
    topic: 'abs-fren',
    difficulty: 'orta',
    stem: 'ABS sisteminin tekerleğin kilitlenmek üzere olduğunu anlamasını sağlayan bileşen hangisidir?',
    options: [
      'Her tekerlekte bulunan ve dönüş hızını sürekli ölçen hız sensörleri',
      'Fren pedalının altına yerleştirilmiş, basınç şiddetini ölçen bir yük hücresi',
      'Motor bölmesinde bulunan ve araç hızını ölçen tek merkezi bir sensör',
      'Direksiyon kutusuna bağlı, tekerlek açısını okuyan bir konum sensörü',
    ],
    answerIndex: 0,
    explanation:
      'ABS, her tekerleğin dönüş hızını ayrı ayrı okur. Bir tekerlek diğerlerine göre ani biçimde yavaşlıyorsa kilitlenmek üzeredir; kumanda ünitesi o tekerleğin fren basıncını kısa süre düşürüp yeniden verir. Ölçüm tekerlek başına yapıldığı için müdahale de tekerlek başınadır.',
    whyWrong: [
      'Pedal basıncı ya da tek merkezi bir hız ölçümü, hangi tekerleğin kilitlendiğini söyleyemez.',
      'Direksiyon açısı sensörü ESP’nin girdisidir, ABS’nin kilitlenme ölçütü değildir.',
    ],
    objective: 'ABS’nin tekerlek hız sensörleriyle çalıştığını bilmek.',
    tags: ['abs', 'sensor', 'fren-sistemi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen2-abs-004',
    subject: 'pratik',
    topic: 'abs-fren',
    difficulty: 'orta',
    stem: 'ABS’li bir araçta engelden kaçınmak için "fren + direksiyon" birlikte nasıl kullanılır?',
    options: [
      'Önce tam fren yapılıp araç durdurulur, ancak durduktan sonra direksiyon çevrilir',
      'Fren pedalı kararlılıkla basılı tutulurken direksiyonla boş alana doğru yön verilir',
      'Fren pedalı bırakılıp yalnızca direksiyonla kaçılır; ABS’li araçta fren kullanılmaz',
      'Fren pedalına aralıklı basılıp her boşaltmada direksiyon bir miktar çevrilir',
    ],
    answerIndex: 1,
    explanation:
      'ABS’nin sağladığı şey tam da budur: tekerlekler kilitlenmediği için yön verme yeteneği korunur. Pedal kararlılıkla basılı tutulurken direksiyonla boş alana yönelmek, hem yavaşlamayı hem kaçınmayı aynı anda mümkün kılar.',
    whyWrong: [
      'Durmayı beklemek zaman kaybettirir; freni bırakmak yavaşlamayı ortadan kaldırır.',
      'Pompalama ABS’siz araçların tekniğidir ve ABS’li araçta sistemi engeller.',
    ],
    objective: 'ABS ile fren ve direksiyonun birlikte kullanılabildiğini kavramak.',
    tags: ['abs', 'acil-manevra', 'fren-teknigi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen2-abs-005',
    subject: 'motor',
    topic: 'abs-fren',
    difficulty: 'orta',
    stem: 'Kontak açıldığında yanan ABS ikaz lambasının motor çalıştıktan kısa süre sonra sönmesi neyi gösterir?',
    options: [
      'Sistemin kendi kendini test ettiğini ve testi sorunsuz tamamladığını gösterir',
      'Fren balatalarının yeni değiştirildiğini ve alışma sürecinin bittiğini gösterir',
      'Fren hidroliği seviyesinin maksimum çizgiye kadar dolu olduğunu gösterir',
      'Sistemin kalıcı olarak devre dışı bırakıldığını ve artık çalışmadığını gösterir',
    ],
    answerIndex: 0,
    explanation:
      'Kontak açıldığında birçok ikaz lambası birlikte yanar; bu, sistemlerin ön kontrol (self-test) yaptığı andır. Motor çalıştıktan kısa süre sonra sönmeleri testin sorunsuz geçtiğini gösterir. Sönmeyen bir lamba ise ilgili sistemde uyarı ya da arıza olduğu anlamına gelir.',
    whyWrong: [
      'Lambanın sönmesi balata ya da hidrolik seviyesiyle ilgili bir bilgi vermez.',
      'Sistem devre dışıysa lamba sönmez, sabit yanar.',
    ],
    objective: 'Kontak açılışındaki ikaz lambası ön kontrolünü yorumlamak.',
    tags: ['abs', 'gosterge-paneli', 'on-kontrol'],
    review: 'draft',
    sourceRef: SRC,
  },

  /* ─────────────────────────  YOL ÇİZGİLERİ · GÖREVLİ İŞARETLERİ  ───────────────────────── */
  {
    id: 'gen2-cizgi-001',
    subject: 'trafik',
    topic: 'yol-cizgileri',
    difficulty: 'orta',
    stem: 'Taşıt yolunda yan yana çizilmiş biri devamlı biri kesik iki çizgi bulunduğunda sürücü ne yapmalıdır?',
    options: [
      'İki çizgi bir arada bulunduğunda hiçbir yönden çizgi geçilemez ve sollama yapılamaz',
      'Sürücü kendi tarafındaki çizgiye uyar; kesik çizgi tarafındaki araç kurallara uygunsa geçebilir',
      'Devamlı çizgi tarafındaki sürücü, kesik çizgi tarafındaki sürücüden izin alarak geçiş yapabilir',
      'İki çizgi bir arada yalnızca uyarı amaçlıdır; iki yön de serbestçe sollama yapabilir',
    ],
    answerIndex: 1,
    explanation:
      'Yan yana devamlı ve kesik çizgi bulunduğunda her sürücü kendi şeridine yakın olan çizgiye uyar: kesik çizgi tarafındaki sürücü, karşı yön uygunsa geçiş yapabilir; devamlı çizgi tarafındaki sürücü ise çizgiyi geçemez.',
    whyWrong: [
      'Çizgi çiftinin ikisini birden yasak ya da ikisini birden serbest saymak yanlıştır.',
      'Devamlı çizgi kuralı karşı sürücünün iznine bağlı değildir.',
    ],
    objective: 'Yan yana devamlı-kesik çizgi kuralını uygulamak.',
    tags: ['yol-cizgileri', 'sollama', 'yatay-isaretleme'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen2-cizgi-002',
    subject: 'trafik',
    topic: 'yol-cizgileri',
    difficulty: 'orta',
    stem: 'Taşıt yolunda çizilmiş sarı renkli devamlı kenar çizgisi sürücüye neyi bildirir?',
    options: [
      'O kesimde duraklamanın ve park etmenin yasaklandığını bildiren bir yatay işarettir',
      'O kesimde azami hız sınırının düşürüldüğünü bildiren bir yatay işaret olarak kullanılır',
      'O kesimin yalnızca toplu taşıma araçlarına ayrıldığını bildiren bir şerit işaretidir',
      'O kesimde yolun ileride daralacağını önceden bildiren bir uyarı işaretidir',
    ],
    answerIndex: 0,
    explanation:
      'Taşıt yolu kenarındaki sarı devamlı çizgi, o kesimde duraklama ve park etmenin yasak olduğunu gösterir. Yatay işaretlemeler, düşey levhalarla aynı hukuki bağlayıcılığa sahiptir.',
    whyWrong: ['Hız sınırı, şerit tahsisi ve yol daralması ayrı işaret ve levhalarla bildirilir.'],
    objective: 'Sarı devamlı kenar çizgisinin anlamını bilmek.',
    tags: ['yol-cizgileri', 'duraklama-park', 'yatay-isaretleme'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen2-gorevli-001',
    subject: 'trafik',
    topic: 'gorevli-isaretleri',
    difficulty: 'orta',
    stem: 'Trafiği yöneten görevlinin kolunu dik olarak yukarı kaldırması sürücüler için ne anlama gelir?',
    options: [
      'Bütün yönlerdeki trafiğin durması gerektiğini, kavşağın boşaltılacağını bildirir',
      'Kolun gösterdiği yönden gelenlerin serbestçe geçebileceğini bildiren bir işarettir',
      'Yalnızca yayaların geçebileceğini, araçların yavaşlayarak ilerleyebileceğini bildirir',
      'Kavşakta bekleyen araçların sırayla ve birer birer geçebileceğini bildiren işarettir',
    ],
    answerIndex: 0,
    explanation:
      'Görevlinin kolunu dik yukarı kaldırması, ışıktaki sarı safhaya karşılık gelir: bütün yönler durmaya hazırlanır, kavşak içindekiler kavşağı boşaltır. Görevlinin işareti, ışıklı işaret cihazından ve levhalardan önce gelir.',
    whyWrong: [
      'Yukarı kalkan kol geçiş izni değil, durma ve boşaltma işaretidir.',
      'Yaya geçişi ya da sıralı geçiş bu işaretle bildirilmez.',
    ],
    objective: 'Görevlinin kolu yukarı işaretinin anlamını bilmek.',
    tags: ['gorevli-isaretleri', 'kavsak', 'isaret-onceligi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'gen2-gorevli-002',
    subject: 'trafik',
    topic: 'gorevli-isaretleri',
    difficulty: 'orta',
    stem: 'Bir kavşakta ışıklı işaret cihazı, trafik levhası, yer işaretlemesi ve trafik görevlisi aynı anda farklı şeyler söylüyorsa sürücü hangisine uyar?',
    options: [
      'Sürücü kendi güvenliğine göre hangisinin daha uygun olduğuna kendisi karar verir',
      'Sürücü ışıklı işaret cihazına uyar; görevlinin işareti yalnızca yayaları bağlayan bir uyarıdır',
      'Sürücü önce trafik görevlisinin işaretine, sonra ışığa, sonra levhaya ve yer işaretine uyar',
      'Sürücü yer işaretlemesine öncelik verir; boyalı çizgiler diğer işaretlerin önüne geçer',
    ],
    answerIndex: 2,
    explanation:
      'Çelişki hâlinde sıralama bellidir: önce trafik görevlisinin emri, sonra ışıklı işaret cihazı, sonra trafik levhası, en son yer (yatay) işaretlemesi. Bu sıra, en güncel ve duruma özel bilgiyi en üste koyar; görevli o an oradaki koşulu görerek işaret verir.',
    whyWrong: [
      'Sıralamayı sürücünün takdirine bırakmak ya da tersine çevirmek kavşakta çelişkili davranış üretir.',
      'Görevlinin işareti tüm yol kullanıcılarını bağlar, yalnızca yayaları değil.',
    ],
    objective: 'Çelişki hâlinde işaret önceliği sıralamasını uygulamak.',
    tags: ['gorevli-isaretleri', 'isaret-onceligi', 'kavsak'],
    review: 'draft',
    sourceRef: SRC,
  },
];
