/**
 * ÖZGÜN araç tekniği (motor) soruları — 4. genişletme (Program 2 · Faz 9). ROADMAP C.4/E.6.
 * Kaynak = MEB araç tekniği müfredatı; KENDİ İFADEMİZLE.
 */
import type { QuestionInput } from '@ea/content-schema';

const SRC = 'MEB araç tekniği müfredatı (özgün ifade)';

export const MOTOR_QUESTIONS_4: QuestionInput[] = [
  {
    id: 'motor-401',
    subject: 'motor',
    topic: 'triger',
    difficulty: 'zor',
    stem: 'Seyir hâlindeyken triger (zaman) kayışı koparsa ne olması beklenir?',
    options: [
      'Yalnızca klima devre dışı kalır, sürüşe devam edilir',
      'Motor aniden durur; birçok motorda supaplar pistonlara çarparak ağır hasar oluşabilir',
      'Sadece yakıt tüketimi bir miktar artar',
      'Araç kendiliğinden bir alt vitese geçer',
    ],
    answerIndex: 1,
    explanation:
      'Triger kayışı krank mili ile eksantrik (kam) mili arasındaki zamanlamayı sağlar. Koptuğunda supap-piston uyumu anında bozulur; motor durur ve girişimli tip motorlarda supaplar pistonlara çarparak çok pahalı bir hasara yol açabilir.',
    whyWrong: [
      'Klimayı çeviren kayış genellikle ayrı olan yardımcı (serpantin) kayıştır.',
      'Kopan triger kayışı yakıt tüketimini artıran değil, motoru tamamen durduran bir arızadır.',
      'Vites seçimi ile triger kayışının bir ilgisi yoktur.',
    ],
    objective: 'Triger kayışı kopmasının motor üzerindeki ağır sonuçlarını kavramak.',
    tags: ['triger', 'zaman-kayisi', 'motor-hasari'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-402',
    subject: 'motor',
    topic: 'kayis',
    difficulty: 'orta',
    stem: 'Triger kayışı ile serpantin (yardımcı/V) kayışı arasındaki temel görev farkı nedir?',
    options: [
      'İkisi de aynı parçadır, sadece adları farklıdır',
      'Serpantin kayışı supap zamanlamasını, triger kayışı klimayı çalıştırır',
      'Triger kayışı krank ile eksantrik mili arasındaki senkronu sağlar; serpantin kayışı alternatör, klima kompresörü gibi yardımcı donanımları döndürür',
      'Triger kayışı yalnızca dizel motorlarda bulunur',
    ],
    answerIndex: 2,
    explanation:
      'Triger kayışı motorun içindeki zamanlamayı (krank–eksantrik senkronu) sağlar ve genellikle koruyucu kapak altındadır. Serpantin kayışı ise motorun dışında alternatör, su pompası, klima kompresörü ve direksiyon pompası gibi yardımcı üniteleri döndürür.',
    whyWrong: [
      'İki kayışın görevleri ve konumları tamamen farklıdır.',
      'Görev tanımları bu seçenekte ters yazılmıştır.',
      'Her iki kayış tipi de hem benzinli hem dizel motorlarda kullanılabilir.',
    ],
    objective: 'Triger ve serpantin kayışlarının görev ayrımını öğrenmek.',
    tags: ['kayis', 'triger', 'serpantin'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-403',
    subject: 'motor',
    topic: 'kayis',
    difficulty: 'kolay',
    stem: 'Özellikle soğuk ilk çalıştırmada motor bölmesinden gelen ince cıyaklama (ötme) sesi en çok neyi düşündürür?',
    options: [
      'Yardımcı (V/serpantin) kayışın gevşemiş ya da aşınmış olduğunu',
      'Egzoz borusunun delindiğini',
      'Lastik basıncının düşük olduğunu',
      'Fren balatalarının bittiğini',
    ],
    answerIndex: 0,
    explanation:
      'Gevşeyen veya sertleşip aşınan yardımcı kayış, kasnaklar üzerinde kayarak tiz bir cıyaklama sesi çıkarır; ses genellikle soğuk çalıştırmada ve gaz verildiğinde belirginleşir. Kayış gerginliği kontrol ettirilmelidir.',
    whyWrong: [
      'Egzoz kaçağı boğuk ve gürültülü bir sese yol açar, tiz cıyaklama yapmaz.',
      'Düşük lastik basıncı motor bölmesinden ses üretmez.',
    ],
    objective: 'Kayış kaynaklı sesi tanıyıp bakım ihtiyacını fark etmek.',
    tags: ['kayis', 'ariza-belirtisi', 'ses'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-404',
    subject: 'motor',
    topic: 'kayis',
    difficulty: 'zor',
    stem: 'Sürüş sırasında hem şarj ikaz lambası yanıyor hem de hararet göstergesi hızla yükseliyorsa bu iki belirtinin birlikte görülmesi en çok neyi işaret eder?',
    options: [
      'Yakıt filtresinin tıkandığını',
      'Fren hidroliğinin azaldığını',
      'Klima gazının bittiğini',
      'Alternatörü ve su pompasını birlikte çeviren yardımcı kayışın kopmuş olabileceğini',
    ],
    answerIndex: 3,
    explanation:
      'Birçok araçta serpantin kayışı hem alternatörü hem de su pompasını döndürür. Kayış koptuğunda şarj üretimi durur (şarj lambası yanar) ve soğutma suyu dolaşımı kesildiği için hararet hızla yükselir. Araç en kısa sürede güvenli bir yerde durdurulmalıdır.',
    whyWrong: [
      'Yakıt filtresi tıkanıklığı güç kaybı ve tekleme yapar; şarj ve hararet ikazıyla ilgisi yoktur.',
      'Fren hidroliği eksikliği fren ikazını yakar, hararet yapmaz.',
      'Klima gazının bitmesi yalnızca soğutma performansını düşürür.',
    ],
    objective: 'Birden fazla ikazı birlikte okuyarak kayış kopmasını teşhis edebilmek.',
    tags: ['kayis', 'sarj-lambasi', 'hararet', 'teshis'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-405',
    subject: 'motor',
    topic: 'sarj-sistemi',
    difficulty: 'kolay',
    stem: 'Kontak açıldığında şarj (akü) ikaz lambasının yanıp motor çalıştıktan hemen sonra sönmesi neyi gösterir?',
    options: [
      'Alternatörün arızalı olduğunu',
      'Akünün tamamen boşaldığını',
      'Sistemin normal çalıştığını; lamba kontrolü yapılıp şarj üretiminin başladığını',
      'Sigortalardan birinin attığını',
    ],
    answerIndex: 2,
    explanation:
      'Kontak açıldığında ikaz lambalarının kısa süre yanması bir ampul/devre testidir. Motor çalışınca alternatör şarj üretmeye başladığı için lamba söner; bu, şarj sisteminin sağlıklı olduğunu gösterir.',
    whyWrong: [
      'Alternatör arızasında lamba motor çalışırken de yanmaya devam ederdi.',
      'Akü tamamen boş olsaydı büyük olasılıkla marş bile basmazdı.',
    ],
    objective: 'İkaz lambası test davranışını normal çalışma olarak tanımak.',
    tags: ['sarj-sistemi', 'ikaz-lambasi', 'gosterge'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-406',
    subject: 'motor',
    topic: 'sarj-sistemi',
    difficulty: 'orta',
    stem: 'Gece sürüşünde farlar rölantide belirgin şekilde sararıp motor devri yükselince parlaklaşıyorsa bu durum neyi düşündürmelidir?',
    options: [
      'Far ampullerinin yanlış takıldığını',
      'Şarj sisteminin (alternatör/kayış) verimsiz çalıştığını ve kontrol ettirilmesi gerektiğini',
      'Yakıt seviyesinin azaldığını',
      'Bunun tüm araçlarda tamamen normal olduğunu ve hiçbir kontrol gerektirmediğini',
    ],
    answerIndex: 1,
    explanation:
      'Rölantide belirgin sararma ve devirle parlaklaşma, alternatörün düşük devirde yeterli gerilim üretemediğine ya da kayış/regülatör sorununa işaret edebilir. Şarj sistemi ölçtürülmelidir; aksi hâlde akü zamanla boşalır.',
    whyWrong: [
      'Yanlış takılan ampul sürekli sorun çıkarır, devirle değişen parlaklık yapmaz.',
      'Yakıt seviyesinin far parlaklığıyla ilgisi yoktur.',
      'Belirgin parlaklık değişimi bir uyarıdır; görmezden gelinmemelidir.',
    ],
    objective: 'Şarj sistemi zayıflığının pratik belirtisini fark etmek.',
    tags: ['sarj-sistemi', 'alternator', 'ariza-belirtisi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-407',
    subject: 'motor',
    topic: 'mars-sistemi',
    difficulty: 'orta',
    stem: 'Marşa basıldığında yalnızca hızlı "tık tık" sesi geliyor ve gösterge ışıkları o anda sönükleşiyorsa en olası neden hangisidir?',
    options: [
      'Akünün zayıflamış olması ya da kutup başlarının gevşek/oksitli olması',
      'Yakıt deposunun tamamen boş olması',
      'Triger kayışının kopması',
      'Fren balatalarının aşınması',
    ],
    answerIndex: 0,
    explanation:
      'Tık tık sesi, marş otomatiğinin çekmeye çalışıp yeterli akımı bulamadığını gösterir. Göstergelerin marş anında sönükleşmesi de gerilimin çöktüğünün işaretidir: akü zayıftır ya da kutup başı bağlantısı sağlıksızdır.',
    whyWrong: [
      'Yakıt bitmişse marş normal döner ama motor çalışmaz.',
      'Triger kopması marş sesini engellemez; motorun çalışmasını engeller.',
    ],
    objective: 'Akü kaynaklı marş arızasının tipik belirtisini tanımak.',
    tags: ['mars-sistemi', 'aku', 'teshis'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-408',
    subject: 'motor',
    topic: 'mars-sistemi',
    difficulty: 'zor',
    stem: 'Farlar canlı yanıyor, korna güçlü çalıyor; ancak marşa basıldığında hiçbir ses gelmiyor ve marş dönmüyorsa arıza en olası olarak nerededir?',
    options: [
      'Aküde; akü tamamen boşalmıştır',
      'Lastiklerde; basınç çok düşüktür',
      'Radyatörde; soğutma suyu eksiktir',
      'Marş motorunda veya marş devresinde (kontak/otomatik)',
    ],
    answerIndex: 3,
    explanation:
      'Farların parlak yanması ve kornanın güçlü çalması akünün büyük olasılıkla sağlam olduğunu gösterir. Marşın hiç tepki vermemesi, arızanın marş motoru, marş otomatiği ya da kontak devresi tarafında olduğunu düşündürür.',
    whyWrong: [
      'Boş bir akü farları da besleyemez; belirtiler aküyü aklamaktadır.',
      'Lastik basıncının ve soğutma suyunun marş sistemiyle ilgisi yoktur.',
    ],
    objective: 'Akü kaynaklı ve marş motoru kaynaklı arızayı belirtilerden ayırt etmek.',
    tags: ['mars-sistemi', 'aku', 'ariza-ayrimi'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-409',
    subject: 'motor',
    topic: 'atesleme',
    difficulty: 'orta',
    stem: 'Benzinli bir araçta rölantide sarsıntılı çalışma (tekleme), güç kaybı ve yakıt tüketiminde artış bir arada görülüyorsa öncelikle hangi parçalar kontrol edilmelidir?',
    options: [
      'Silecek lastikleri',
      'Amortisörler',
      'Bujiler ve ateşleme sistemi elemanları',
      'El freni halatı',
    ],
    answerIndex: 2,
    explanation:
      'Aşınmış, kirlenmiş veya tırnak aralığı bozulmuş bujiler karışımı düzenli ateşleyemez. Sonuç; rölantide sarsıntı, hızlanmada tekleme, güç kaybı ve yakıt artışıdır. Buji ve ateşleme bobini/kabloları kontrol edilmelidir.',
    whyWrong: [
      'Silecek ve el freni motorun çalışma düzenini etkilemez.',
      'Amortisör aşınması yol tutuşu bozar; tekleme ve yakıt artışı yapmaz.',
    ],
    objective: 'Buji arızasının tipik belirtilerini tanımak.',
    tags: ['atesleme', 'buji', 'ariza-belirtisi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-410',
    subject: 'motor',
    topic: 'hava-filtresi',
    difficulty: 'kolay',
    stem: 'Hava filtresi aşırı kirlenip tıkanırsa motorda hangi sonuç beklenir?',
    options: [
      'Motora giren hava azalır; güç düşer, yakıt tüketimi ve egzoz dumanı artar',
      'Motor daha güçlü çalışır',
      'Fren mesafesi kısalır',
      'Akü daha hızlı şarj olur',
    ],
    answerIndex: 0,
    explanation:
      'Tıkalı filtre motorun nefes almasını zorlaştırır. Yeterli hava alamayan motorda karışım zenginleşir; güç düşer, tüketim yükselir ve egzozdan isli duman gelebilir. Filtre periyodik olarak değiştirilmelidir.',
    whyWrong: [
      'Hava kısıtlanınca güç artmaz, tam tersine azalır.',
      'Fren sistemi ve akü şarjı hava filtresinden bağımsızdır.',
    ],
    objective: 'Tıkalı hava filtresinin performans ve tüketime etkisini kavramak.',
    tags: ['hava-filtresi', 'bakim', 'yakit-tuketimi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-411',
    subject: 'motor',
    topic: 'polen-filtresi',
    difficulty: 'kolay',
    stem: 'Polen (kabin) filtresinin görevi aşağıdakilerden hangisidir?',
    options: [
      'Motora giren yakıtı süzmek',
      'Yolcu kabinine giren havayı toz ve polenden arındırmak',
      'Egzoz gazındaki zararlı maddeleri azaltmak',
      'Motor yağındaki pislikleri tutmak',
    ],
    answerIndex: 1,
    explanation:
      'Polen filtresi, havalandırma ve klima üzerinden kabine giren havayı toz, polen ve kurumdan temizler. Tıkanırsa hava akışı zayıflar, camlardaki buğu geç açılır ve içeride kötü koku oluşabilir.',
    whyWrong: [
      'Yakıtı yakıt filtresi, motor yağını yağ filtresi süzer.',
      'Egzoz gazını temizleme görevi katalitik konvertöre aittir.',
    ],
    objective: 'Polen filtresinin kabin konforu ve görüşe etkisini öğrenmek.',
    tags: ['polen-filtresi', 'kabin', 'bakim'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-412',
    subject: 'motor',
    topic: 'yakit-sistemi',
    difficulty: 'zor',
    stem: 'Dizel araçlarda yakıt filtresindeki su ayırıcının (su tahliye) önemi nedir?',
    options: [
      'Yakıtı ısıtarak kış performansını artırır',
      'Motor yağının seviyesini dengeler',
      'Egzoz sesini azaltır',
      'Yakıttaki suyu tutar; su hassas enjeksiyon sistemine ulaşırsa pahalı arızalara yol açabilir',
    ],
    answerIndex: 3,
    explanation:
      'Dizel enjeksiyon sistemleri çok yüksek basınçla ve hassas toleranslarla çalışır. Yakıtla gelen su, enjektörlerde ve pompada korozyona ve aşınmaya neden olur. Su ayırıcı bu suyu biriktirir; uyarı geldiğinde tahliye edilmelidir.',
    whyWrong: [
      'Su ayırıcının görevi ısıtma değil, suyu yakıttan ayırmaktır.',
      'Yağ seviyesi ve egzoz sesiyle bir ilgisi yoktur.',
    ],
    objective: 'Dizel yakıt sisteminde suyun zararını ve su ayırıcının işlevini kavramak.',
    tags: ['yakit-filtresi', 'dizel', 'su-ayirici'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-413',
    subject: 'motor',
    topic: 'egzoz-duman',
    difficulty: 'orta',
    stem: 'Egzozdan sürekli mavimsi duman gelmesi ve yağ seviyesinin sık sık düşmesi neyi gösterir?',
    options: [
      'Yakıtın kaliteli olduğunu',
      'Soğutma suyunun eksildiğini',
      'Motorun yağ yaktığını (ör. segman veya supap kılavuzu aşınması)',
      'Lastiklerin balans ayarının bozuk olduğunu',
    ],
    answerIndex: 2,
    explanation:
      'Mavi duman, motor yağının yanma odasına sızıp yakıtla birlikte yandığının işaretidir. Genellikle segman, silindir veya supap kılavuzu aşınmasından kaynaklanır; yağ eksilmesiyle birlikte görülür ve servis kontrolü gerektirir.',
    whyWrong: [
      'Soğutma suyu kaçağı mavi değil, sürekli beyaz yoğun duman yapar.',
      'Balans ayarının egzoz dumanıyla ilgisi yoktur.',
    ],
    objective: 'Mavi egzoz dumanını yağ yakma belirtisi olarak tanımak.',
    tags: ['egzoz', 'mavi-duman', 'yag-yakma'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-414',
    subject: 'motor',
    topic: 'egzoz-duman',
    difficulty: 'zor',
    stem: 'Motor ısındıktan sonra da egzozdan yoğun beyaz duman gelmeye devam ediyor ve soğutma suyu sürekli eksiliyorsa en olası neden nedir?',
    options: [
      'Silindir kapak contası kaçağı nedeniyle soğutma suyunun yanma odasına sızması',
      'Hava filtresinin yeni değiştirilmiş olması',
      'Lastik diş derinliğinin azalması',
      'Far ayarının bozulması',
    ],
    answerIndex: 0,
    explanation:
      'Isınmış motorda süren yoğun beyaz duman, yanma odasında buharlaşan soğutma suyuna işaret eder. En sık neden silindir kapak contası kaçağıdır; su eksilmesi ve bazen yağda süt görünümü de eşlik eder. Gecikmeden servise gidilmelidir.',
    whyWrong: [
      'Yeni hava filtresi duman oluşturmaz.',
      'Lastik ve far konularının egzoz dumanıyla ilgisi yoktur.',
    ],
    objective: 'Sürekli beyaz dumanı conta/soğutma suyu kaçağı ile ilişkilendirmek.',
    tags: ['egzoz', 'beyaz-duman', 'silindir-kapak-contasi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-415',
    subject: 'motor',
    topic: 'egzoz-duman',
    difficulty: 'orta',
    stem: 'Soğuk bir sabah ilk çalıştırmada egzozdan bir süre ince beyaz buhar çıkması ve su damlaması hakkında doğru değerlendirme hangisidir?',
    options: [
      'Motor yağı bitmiştir, araç kullanılmamalıdır',
      'Yanma sonucu oluşan su buharının soğuk egzozda yoğuşmasıdır; motor ısınınca kayboluyorsa normaldir',
      'Yakıt deposuna su karışmıştır, depo boşaltılmalıdır',
      'Katalitik konvertör sökülmelidir',
    ],
    answerIndex: 1,
    explanation:
      'Yanma tepkimesinde doğal olarak su buharı oluşur. Soğuk havada bu buhar egzoz içinde yoğuşarak damlar ve beyaz görünür. Motor ısındıkça kayboluyorsa arıza değildir; kaybolmuyorsa conta kaçağından şüphelenilir.',
    whyWrong: [
      'Yağ eksikliğinin belirtisi yağ basınç lambasıdır, egzozdan su damlaması değildir.',
      'Kısa süreli yoğuşma için depo boşaltmak veya parça sökmek gereksizdir.',
    ],
    objective: 'Normal yoğuşmayı arıza belirtilerinden ayırt etmek.',
    tags: ['egzoz', 'yogusma', 'normal-calisma'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-416',
    subject: 'motor',
    topic: 'egzoz-duman',
    difficulty: 'orta',
    stem: 'Egzoz dumanı rengi ile olası neden eşleştirmelerinden hangisi doğrudur?',
    options: [
      'Siyah = yağ yakma, mavi = su kaçağı, beyaz = zengin karışım',
      'Mavi = zengin karışım, siyah = su kaçağı, beyaz = yağ yakma',
      'Beyaz = normal her durumda, siyah = fren arızası, mavi = lastik aşınması',
      'Siyah = zengin karışım/yetersiz hava, mavi = yağ yakma, sürekli beyaz = soğutma suyu kaçağı',
    ],
    answerIndex: 3,
    explanation:
      'Klasik eşleştirme şöyledir: siyah duman fazla yakıt ya da yetersiz hava (zengin karışım), mavi duman yanma odasında yağ yanması, ısınmış motorda süren beyaz duman ise soğutma suyunun silindire kaçağıdır.',
    whyWrong: [
      'İlk iki seçenekte renk-neden eşleşmeleri birbirinin yerine yazılmıştır.',
      'Duman renklerinin fren veya lastik arızasıyla ilgisi yoktur.',
    ],
    objective: 'Üç duman renginin anlamını bir arada doğru eşleştirmek.',
    tags: ['egzoz', 'duman-rengi', 'teshis'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-417',
    subject: 'motor',
    topic: 'katalitik-konvertor',
    difficulty: 'kolay',
    stem: 'Sıcak katalitik konvertör nedeniyle aracı kuru ot veya saman üzerine park etmek neden tehlikelidir?',
    options: [
      'Katalitik konvertör çok yüksek sıcaklıkta çalıştığı için altındaki kuru bitkileri tutuşturup yangına yol açabilir',
      'Kuru ot lastik basıncını düşürür',
      'Otlar egzoz borusunu tıkayıp motoru güçlendirir',
      'Katalitik konvertör kuru otta daha hızlı soğur',
    ],
    answerIndex: 0,
    explanation:
      'Katalitik konvertör, egzoz gazlarını dönüştürürken yüzlerce dereceye ulaşır ve aracın altında yer alır. Kuru ot, saman veya yaprak yığını üzerine park edildiğinde bu ısı bitkileri tutuşturabilir; araç ve çevre yangını riski doğar.',
    whyWrong: [
      'Kuru otun lastik basıncıyla ilgisi yoktur.',
      'Tıkanan egzoz motoru güçlendirmez, boğar.',
    ],
    objective: 'Sıcak egzoz elemanlarının park yeri seçimindeki yangın riskini bilmek.',
    tags: ['katalitik-konvertor', 'yangin-riski', 'park'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-418',
    subject: 'motor',
    topic: 'amortisor',
    difficulty: 'orta',
    stem: 'Aşağıdaki belirtilerden hangisi amortisörlerin aşındığını düşündürür?',
    options: [
      'Camların içeriden buğulanması',
      'Marş sesinin zayıflaması',
      'Tümsek geçişinden sonra gövde salınımının uzun sürmesi, virajda fazla yatma ve frende burnun aşırı dalması',
      'Egzozdan siyah duman gelmesi',
    ],
    answerIndex: 2,
    explanation:
      'Amortisör, yayların salınımını söndürür. Aşındığında araç tümsek sonrası uzun süre sallanır, virajlarda fazla yatar, sert frende burun aşırı dalar; lastiklerde düzensiz aşınma da görülebilir. Bunlar yol tutuşunu ve fren güvenliğini bozar.',
    whyWrong: [
      'Cam buğusu havalandırma/polen filtresi konusudur.',
      'Marş sesi ve egzoz dumanı süspansiyonla ilgili değildir.',
    ],
    objective: 'Amortisör aşınmasının sürüşte hissedilen belirtilerini tanımak.',
    tags: ['amortisor', 'suspansiyon', 'ariza-belirtisi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-419',
    subject: 'motor',
    topic: 'rot-ayari',
    difficulty: 'orta',
    stem: 'Düz yolda direksiyon hafifçe serbest bırakıldığında araç sürekli bir tarafa kayıyor ve ön lastiklerden biri yalnızca iç veya dış omzundan hızla aşınıyorsa en olası neden nedir?',
    options: [
      'Akünün zayıflaması',
      'Rot (ön düzen) ayarının bozulmuş olması',
      'Fren hidroliğinin eskimesi',
      'Polen filtresinin tıkanması',
    ],
    answerIndex: 1,
    explanation:
      'Rot ayarı tekerleklerin yola doğru açıyla basmasını sağlar. Bozulduğunda araç bir tarafa çeker ve lastik tek omzundan anormal aşınır. Ön düzen ayarı yaptırılmazsa hem lastik ömrü kısalır hem de yol tutuş bozulur.',
    whyWrong: [
      'Akü ve polen filtresi aracın düz gitmesini etkilemez.',
      'Fren hidroliğinin eskimesi çekme değil, fren performans sorunu doğurur.',
    ],
    objective: 'Bozuk rot ayarının çekme ve tek taraflı lastik aşıntısı belirtisini öğrenmek.',
    tags: ['rot-ayari', 'on-duzen', 'lastik-asinmasi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-420',
    subject: 'motor',
    topic: 'rot-ayari',
    difficulty: 'kolay',
    stem: 'Aşağıdaki durumların hangisinden sonra rot (ön düzen) ayarının kontrol ettirilmesi özellikle gerekir?',
    options: [
      'Yakıt deposu doldurulduktan sonra',
      'Silecek lastikleri değiştirildikten sonra',
      'Polen filtresi değiştirildikten sonra',
      'Derin bir çukura sert düşme veya kaldırıma çarpma sonrasında',
    ],
    answerIndex: 3,
    explanation:
      'Çukura sert düşmek ya da kaldırıma çarpmak ön düzen açılarındaki hassas ayarı bozabilir. Böyle bir darbeden sonra araçta çekme veya düzensiz lastik aşıntısı başlamadan rot ayarı kontrol ettirilmelidir.',
    whyWrong: [
      'Yakıt almak ve silecek değişimi ön düzen geometrisini etkilemez.',
      'Polen filtresi kabin havasıyla ilgilidir.',
    ],
    objective: 'Rot ayarını bozan tipik olayları bilmek.',
    tags: ['rot-ayari', 'bakim', 'darbe'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-421',
    subject: 'motor',
    topic: 'aks',
    difficulty: 'zor',
    stem: 'Ön aksdaki kauçuk aks körüğünün yırtılması neden kısa sürede giderilmesi gereken bir sorundur?',
    options: [
      'İçindeki gres kaçar, mafsala toz ve su girer; aks mafsalı aşınarak dönüşlerde tıkırtı sesiyle kendini gösteren pahalı bir arızaya dönüşür',
      'Araç anında çalışmaz hâle gelir',
      'Sadece görüntü kusurudur, teknik bir önemi yoktur',
      'Yakıt deposuna hava girmesine yol açar',
    ],
    answerIndex: 0,
    explanation:
      'Aks körüğü, sabit hız mafsalını gres içinde ve dış etkenlerden korunmuş tutar. Yırtıldığında gres savrulur, içeri toz ve su dolar; mafsal hızla aşınır. İhmal edilirse özellikle tam dönüşlerde tıkırtı başlar ve mafsal komple değişir.',
    whyWrong: [
      'Körük yırtığı aracı hemen yolda bırakmaz; sinsi ilerleyen bir hasardır.',
      'Görüntü sorunu değil, mafsal ömrünü doğrudan etkileyen bir arızadır.',
      'Yakıt sistemiyle hiçbir bağlantısı yoktur.',
    ],
    objective: 'Aks körüğü yırtığının mafsal hasarına giden sürecini kavramak.',
    tags: ['aks', 'aks-korugu', 'mafsal'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-422',
    subject: 'motor',
    topic: 'start-stop',
    difficulty: 'kolay',
    stem: 'Bazı araçlardaki start-stop sisteminin temel amacı nedir?',
    options: [
      'Marş motorunu tamamen devreden çıkarmak',
      'Aracı hızlandırırken ek güç sağlamak',
      'Araç durduğunda (ör. kırmızı ışıkta) motoru otomatik olarak geçici durdurup kalkışta yeniden çalıştırarak yakıt tüketimini ve emisyonu azaltmak',
      'Lastik basıncını otomatik ayarlamak',
    ],
    answerIndex: 2,
    explanation:
      'Start-stop sistemi, trafik ışığı gibi duraklamalarda motoru kendiliğinden durdurur; debriyaja veya frenden ayağın çekilmesine göre anında yeniden çalıştırır. Böylece özellikle şehir içinde boşta yanan yakıt ve egzoz emisyonu azalır.',
    whyWrong: [
      'Sistem tam tersine güçlendirilmiş marş/akü donanımıyla çalışır.',
      'Hızlanma gücü ve lastik basıncıyla ilgisi yoktur.',
    ],
    objective: 'Start-stop sisteminin çalışma mantığını ve amacını öğrenmek.',
    tags: ['start-stop', 'yakit-tasarrufu', 'emisyon'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-423',
    subject: 'motor',
    topic: 'fren-bakim',
    difficulty: 'kolay',
    stem: 'Fren yapıldığında tekerlek tarafından gelen ince metalik cızırtı/gıcırtı sesi çoğunlukla neyin habercisidir?',
    options: [
      'Fren hidroliğinin fazla doldurulduğunun',
      'Fren balatalarının aşınma sınırına geldiğinin',
      'Motor yağının eskidiğinin',
      'Vites kutusunun arızalandığının',
    ],
    answerIndex: 1,
    explanation:
      'Birçok balatada aşınma sınırına gelindiğinde diske sürtünerek ses çıkaran metal ikaz tırnağı bulunur. Frende duyulan ince metalik cızırtı, balataların kontrol edilip gerekiyorsa değiştirilmesi için erken uyarıdır.',
    whyWrong: [
      'Hidrolik seviyesi ses üretmez.',
      'Motor yağı ve vites kutusu fren sesiyle ilişkili değildir.',
    ],
    objective: 'Balata aşınma ikaz sesini tanıyıp erken önlem almak.',
    tags: ['fren', 'balata', 'ses', 'bakim'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-424',
    subject: 'motor',
    topic: 'fren-bakim',
    difficulty: 'orta',
    stem: 'Özellikle yüksek hızdan fren yaparken pedalda ve direksiyonda belirgin titreşim hissediliyorsa en olası neden hangisidir?',
    options: [
      'Yakıt filtresinin tıkanması',
      'Klima kompresörünün devreye girmesi',
      'Akü voltajının düşmesi',
      'Fren disklerinin yüzeyinde bozulma/eğrilik (salgı) oluşması',
    ],
    answerIndex: 3,
    explanation:
      'Aşırı ısınma veya düzensiz aşınma sonucu fren diski yüzeyi dalgalanır (salgı yapar). Balata bu yüzeye bastığında fren kuvveti titreşim olarak pedala ve direksiyona yansır. Diskler ölçtürülmeli; gerekiyorsa taşlanmalı ya da değiştirilmelidir.',
    whyWrong: [
      'Yakıt filtresi ve akü fren titreşimi oluşturmaz.',
      'Klimanın devreye girmesi rölantide hafif devir değişimi yapar, fren titreşimi yapmaz.',
    ],
    objective: 'Frende titreşimi disk yüzey bozulmasıyla ilişkilendirmek.',
    tags: ['fren', 'disk', 'titresim'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-425',
    subject: 'motor',
    topic: 'el-freni',
    difficulty: 'orta',
    stem: 'El freni kolu eskisine göre çok daha yukarı çekildiği hâlde araç eğimde tam durmuyorsa bu ne anlama gelir?',
    options: [
      'El freni halatı uzamış ya da ayarı bozulmuştur; ayar/bakım gereklidir',
      'Bu tamamen normaldir, tüm araçlarda zamanla böyle olur ve bir şey yapılmaz',
      'Motor yağı seviyesi düşmüştür',
      'Lastik basıncı fazladır',
    ],
    answerIndex: 0,
    explanation:
      'Kolun aşırı yukarı gelmesi ve tutma gücünün azalması, halatın uzadığını ya da mekanizmanın/arka balataların ayara ihtiyacı olduğunu gösterir. Eğimli yerde park güvenliği için el freni ayarı geciktirilmeden yaptırılmalıdır.',
    whyWrong: [
      'Belirti bakım gerektirir; kanıksanacak bir durum değildir.',
      'Motor yağının ve lastik basıncının el freni kursuyla ilgisi yoktur.',
    ],
    objective: 'El freni ayar bozukluğunun belirtisini ve önemini bilmek.',
    tags: ['el-freni', 'ayar', 'park-guvenligi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-426',
    subject: 'motor',
    topic: 'fren-hidroligi',
    difficulty: 'zor',
    stem: 'Fren hidroliğinin üreticinin belirttiği aralıklarla değiştirilmesinin temel nedeni nedir?',
    options: [
      'Renginin zamanla açılması',
      'Deposunun her yıl küçülmesi',
      'Hidroliğin zamanla havadan nem çekmesi; kaynama noktası düşen hidroliğin zorlu frenlerde buhar kabarcığı oluşturup pedalın boşa gitmesine yol açabilmesi',
      'Hidroliğin donarak boruları patlatması',
    ],
    answerIndex: 2,
    explanation:
      'Fren hidroliği su çekici (higroskopik) bir sıvıdır. İçindeki su oranı arttıkça kaynama noktası düşer; uzun ve sert frenlemelerde ısınan hidrolik kaynayıp buhar oluşturursa pedal boşa basar. Bu yüzden periyodik değişim güvenlik gereğidir.',
    whyWrong: [
      'Renk değişimi tek başına değişim gerekçesi değildir; asıl sorun nem oranıdır.',
      'Depo boyutu değişmez; hidrolik uygun katkılarla donmaya karşı zaten dayanıklıdır.',
    ],
    objective:
      'Fren hidroliğinin nem kapma özelliği ile periyodik değişim gerekliliğini ilişkilendirmek.',
    tags: ['fren-hidroligi', 'periyodik-bakim', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-427',
    subject: 'motor',
    topic: 'lastik-dis',
    difficulty: 'kolay',
    stem: 'Otomobil lastiklerinde diş derinliğinin inebileceği yasal alt sınır kaç milimetredir?',
    options: ['5 mm', '1,6 mm', '0,5 mm', '3,6 mm'],
    answerIndex: 1,
    explanation:
      'Otomobil lastiklerinde yasal minimum diş derinliği 1,6 milimetredir. Bu sınırın altındaki lastik özellikle ıslak zeminde tutunamaz; hem güvenlik riski oluşturur hem de denetimlerde yaptırıma yol açar.',
    whyWrong: [
      'Diğer değerler yasal sınır değildir; 0,5 mm ölçüsünde bir lastik fiilen kelleşmiştir.',
      'Güvenli sürüş için lastiğin sınıra inmeden yenilenmesi önerilir.',
    ],
    objective: 'Yasal minimum diş derinliği değerini bilmek.',
    tags: ['lastik', 'dis-derinligi', 'yasal-sinir'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-428',
    subject: 'motor',
    topic: 'lastik-dis',
    difficulty: 'orta',
    stem: 'Lastik üzerindeki diş desenlerinin (kanalların) temel görevi aşağıdakilerden hangisidir?',
    options: [
      'Lastiğin daha sessiz görünmesini sağlamak',
      'Jantı korozyondan korumak',
      'Aracın yakıt deposunu havalandırmak',
      'Islak zeminde suyu kanallardan tahliye ederek lastiğin yolla temasını korumak',
    ],
    answerIndex: 3,
    explanation:
      'Diş kanalları, lastik ile yol arasına giren suyu dışarı atarak temas yüzeyini korur. Dişleri aşınmış (kelleşmiş) lastik suyu tahliye edemez; araç ıslak zeminde kolayca kayar ve su üstünde kızaklama riski artar.',
    whyWrong: [
      'Desenler görsel amaçlı değildir; doğrudan güvenlik işlevi görür.',
      'Jant koruması ve yakıt sistemiyle bir ilgisi yoktur.',
    ],
    objective: 'Lastik dişlerinin su tahliyesi ve tutunmadaki rolünü kavramak.',
    tags: ['lastik', 'dis-deseni', 'islak-zemin'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-429',
    subject: 'motor',
    topic: 'lastik-basinc',
    difficulty: 'kolay',
    stem: 'Lastik hava basıncının en doğru ölçüldüğü zaman hangisidir?',
    options: [
      'Lastikler soğukken, yani araç uzun süre durmuşken veya çok az yol yapılmışken',
      'Uzun bir otoyol sürüşünün hemen ardından',
      'Sadece yaz aylarında öğle sıcağında',
      'Motor çalışırken herhangi bir anda; lastik sıcaklığının önemi yoktur',
    ],
    answerIndex: 0,
    explanation:
      'Sürüşte ısınan lastiğin içindeki hava genleşir ve basınç olduğundan yüksek okunur. Bu nedenle basınç, lastikler soğukken ölçülmeli ve üreticinin soğuk lastik için verdiği değere göre ayarlanmalıdır.',
    whyWrong: [
      'Uzun sürüş sonrası ölçüm yanıltıcı biçimde yüksek çıkar.',
      'Basınç kontrolü mevsimden bağımsız, düzenli yapılmalıdır ve lastik sıcaklığı sonucu doğrudan etkiler.',
    ],
    objective: 'Doğru basınç ölçümü için soğuk lastik koşulunu bilmek.',
    tags: ['lastik', 'hava-basinci', 'bakim'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-430',
    subject: 'motor',
    topic: 'lastik-guvenlik',
    difficulty: 'orta',
    stem: 'Lastiğin yanağında (yan yüzeyinde) balon gibi şişlik fark edildiğinde doğru davranış nedir?',
    options: [
      'Basınç biraz düşürülüp kullanılmaya devam edilir',
      'Şişlik iğneyle indirilir',
      'Lastik en kısa sürede değiştirilir; yanak şişliği iç kord bezinin hasarlandığını ve patlama riskini gösterir',
      'Sadece uzun yolda dikkat edilir, şehir içinde sorun olmaz',
    ],
    answerIndex: 2,
    explanation:
      'Yanaktaki şişlik, lastiğin taşıyıcı iç katmanının (kord bezi) darbeyle koptuğunu gösterir. Bu lastik her an, özellikle hız ve yük altında patlayabilir. Yanak hasarı tamir edilmez; lastik değiştirilmelidir.',
    whyWrong: [
      'Basıncı düşürmek yapısal hasarı ortadan kaldırmaz.',
      'Şişliği delmek lastiği kullanılmaz hâle getirir ve tehlikelidir.',
      'Patlama riski şehir içinde de geçerlidir.',
    ],
    objective: 'Yanak şişliğinin yapısal hasar ve patlama riski anlamına geldiğini bilmek.',
    tags: ['lastik', 'yanak-siskinligi', 'patlama-riski'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-431',
    subject: 'motor',
    topic: 'lastik-guvenlik',
    difficulty: 'orta',
    stem: 'İnce tip geçici yedek lastik (incecik stepne) kullanımıyla ilgili doğru ifade hangisidir?',
    options: [
      'Asıl lastikle tamamen aynıdır, süresiz kullanılabilir',
      'Yalnızca arka aksa takılabilir',
      'Takıldıktan sonra araç daha hızlı sürülmelidir',
      'Üzerinde yazan hız sınırına uyularak yalnızca geçici kullanılır; asıl lastik en kısa sürede taktırılır',
    ],
    answerIndex: 3,
    explanation:
      'Geçici stepne dar tabanlı ve düşük dayanımlıdır; üzerinde belirtilen hız sınırı (çoğunlukla 80 km/s) aşılmamalı ve uzun mesafe yapılmamalıdır. Amaç, aracı en yakın lastik servisine güvenle ulaştırmaktır.',
    whyWrong: [
      'Geçici stepne asıl lastiğin yerini tutmaz; yol tutuşu ve fren dengesi farklıdır.',
      'Hangi aksa takılacağı duruma göre değişir; hızlı sürmek ise tam tersine tehlikelidir.',
    ],
    objective: 'Geçici stepnenin hız ve süre kısıtlarını öğrenmek.',
    tags: ['lastik', 'stepne', 'gecici-kullanim'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-432',
    subject: 'motor',
    topic: 'tekerlek-degisimi',
    difficulty: 'orta',
    stem: 'Tekerlek takılırken bijonların çapraz sırayla ve kademeli olarak sıkılmasının nedeni nedir?',
    options: [
      'Bijon anahtarının daha az yıpranmasını sağlamak',
      'Jantın göbeğe her yönden eşit oturmasını sağlayarak salgıyı ve sonradan gevşemeyi önlemek',
      'Lastiğin hava basıncını artırmak',
      'Tekerleğin daha kolay sökülmesini engellemek',
    ],
    answerIndex: 1,
    explanation:
      'Bijonlar sırayla yan yana sıkılırsa jant göbeğe eğik oturabilir. Çapraz ve kademeli sıkma, baskıyı eşit dağıtır; jant düzgün merkezlenir, titreşim (salgı) ve seyir sırasında bijon gevşemesi önlenir.',
    whyWrong: [
      'Amaç anahtarı korumak değil, jantın düzgün oturmasıdır.',
      'Sıkma sırası hava basıncını etkilemez.',
    ],
    objective: 'Çapraz sıkma tekniğinin gerekçesini kavramak.',
    tags: ['bijon', 'tekerlek-degisimi', 'teknik'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-433',
    subject: 'motor',
    topic: 'tekerlek-degisimi',
    difficulty: 'kolay',
    stem: 'Patlak tekerlek değiştirilirken bijonlar ne zaman gevşetilmeye başlanmalıdır?',
    options: [
      'Araç krikoyla kaldırılmadan önce, tekerlek yerdeyken hafifçe gevşetilir',
      'Araç tamamen havadayken',
      'Yeni tekerlek takıldıktan sonra',
      'Bijonlar hiç gevşetilmeden tekerlek çekilerek çıkarılır',
    ],
    answerIndex: 0,
    explanation:
      'Tekerlek yerdeyken zemin sürtünmesi dönmeyi engellediği için bijonlar rahatça çözülür. Araç havadayken kuvvet uygulamak tekerleği boşa döndürür ve krikonun devrilmesine yol açabilir. Bu yüzden önce yerde gevşetilir, kaldırıldıktan sonra tamamen sökülür.',
    whyWrong: [
      'Havadaki tekerlekte bijon çözmek hem zordur hem kriko güvenliğini bozar.',
      'Bijonlar sökülmeden tekerlek çıkarılamaz.',
    ],
    objective: 'Güvenli tekerlek değiştirme sırasını öğrenmek.',
    tags: ['tekerlek-degisimi', 'bijon', 'kriko-guvenligi'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-434',
    subject: 'motor',
    topic: 'antifriz',
    difficulty: 'orta',
    stem: 'Antifrizin yalnızca kış aylarında değil yıl boyunca soğutma sisteminde bulundurulmasının nedeni nedir?',
    options: [
      'Yazın yakıt tüketimini azaltması',
      'Motor yağı yerine de kullanılabilmesi',
      'Donmayı önlemenin yanında kaynama noktasını yükseltmesi ve sistemi korozyona karşı koruması',
      'Lastiklerin yazın ısınmasını engellemesi',
    ],
    answerIndex: 2,
    explanation:
      'Antifriz karışımı kışın donmayı önler; ayrıca suyun kaynama noktasını yükselterek yazın hararet direncini artırır ve içerdiği katkılarla radyatör ile motor su kanallarını paslanma ve kireçlenmeden korur. Bu yüzden dört mevsim kullanılır.',
    whyWrong: [
      'Antifrizin yakıt tüketimiyle ve lastiklerle ilgisi yoktur.',
      'Antifriz bir soğutma sıvısı katkısıdır; asla yağ yerine geçmez.',
    ],
    objective: 'Antifrizin dört mevsim sağladığı üç faydayı öğrenmek.',
    tags: ['antifriz', 'sogutma-sistemi', 'korozyon'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-435',
    subject: 'motor',
    topic: 'rodaj',
    difficulty: 'kolay',
    stem: 'Rodaj dönemi ne anlama gelir ve bu dönemde nasıl davranılır?',
    options: [
      'Aracın yıllık muayene dönemidir; muayene istasyonuna gidilir',
      'Yeni veya motoru yenilenmiş aracın ilk kilometrelerinde parçaların birbirine alışma dönemidir; ani hızlanmadan ve uzun süre sabit yüksek devirden kaçınılır',
      'Kış lastiklerinin takılı kaldığı süredir',
      'Aracın garanti süresinin bittiği tarihtir',
    ],
    answerIndex: 1,
    explanation:
      'Rodaj, yeni imal edilmiş ya da motoru yenilenmiş araçta hareketli parçaların yüzeylerinin birbirine alıştığı ilk kullanım dönemidir. Bu dönemde motor zorlanmamalı; ani gaz, uzun süre sabit yüksek devir ve ağır yükten kaçınılmalıdır.',
    whyWrong: [
      'Rodajın araç muayenesi ve garanti takvimiyle ilgisi yoktur.',
      'Kış lastiği uygulaması ayrı bir mevsimsel kuraldır.',
    ],
    objective: 'Rodaj kavramını ve rodajda sürüş ilkelerini öğrenmek.',
    tags: ['rodaj', 'yeni-arac', 'motor-koruma'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-436',
    subject: 'motor',
    topic: 'sogutma-fani',
    difficulty: 'zor',
    stem: 'Bir araç seyir hâlindeyken hararet göstergesi normal seyrediyor; ancak dur-kalk trafikte veya beklemede sıcaklık hızla yükseliyorsa en olası arıza hangisidir?',
    options: [
      'Yakıt pompası arızası',
      'Debriyaj balatası aşınması',
      'Far ayarının bozulması',
      'Elektro fanın (soğutma fanının) devreye girmemesi',
    ],
    answerIndex: 3,
    explanation:
      'Seyir hâlinde radyatör doğal hava akışıyla soğur; bu yüzden sorun gizlenir. Araç durduğunda soğutmayı fan üstlenir. Fan, müşiri veya sigortası arızalıysa hararet özellikle beklemede ve yavaş trafikte yükselir.',
    whyWrong: [
      'Yakıt pompası arızası güç kaybı ve stop etme yapar, duruşa özgü hararet yapmaz.',
      'Debriyaj ve far konularının soğutmayla ilgisi yoktur.',
    ],
    objective: 'Duruşta ortaya çıkan hararet belirtisini fan arızasıyla ilişkilendirmek.',
    tags: ['sogutma-fani', 'hararet', 'teshis'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-437',
    subject: 'motor',
    topic: 'aku-bakim',
    difficulty: 'kolay',
    stem: 'Uzun süre hiç çalıştırılmadan bekletilen bir araçta akü ile ilgili ne beklenir?',
    options: [
      'Alarm gibi küçük tüketiciler ve kendi kendine boşalma nedeniyle akünün zamanla zayıflaması',
      'Akünün beklerken kendi kendine şarj olması',
      'Akü kapasitesinin artması',
      'Akünün hiçbir şekilde etkilenmemesi',
    ],
    answerIndex: 0,
    explanation:
      'Araç dururken alarm, saat ve kumanda alıcısı gibi tüketiciler az da olsa akım çeker; akünün doğal öz deşarjı da eklenince akü haftalar içinde zayıflayabilir. Uzun bekleyen araç ara ara çalıştırılmalı ya da akü şarj cihazına bağlanmalıdır.',
    whyWrong: [
      'Akü ancak alternatör veya şarj cihazıyla dolar; beklerken şarj olmaz.',
      'Bekleme kapasite kazandırmaz; derin boşalma akü ömrünü kısaltır.',
    ],
    objective: 'Kullanılmayan araçta akünün neden boşaldığını bilmek.',
    tags: ['aku', 'oz-desarj', 'bakim'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-438',
    subject: 'motor',
    topic: 'aku-bakim',
    difficulty: 'zor',
    stem: 'Akü araçtan sökülürken kutup başlarının ayrılma sırası nasıl olmalıdır ve neden?',
    options: [
      'Önce artı kutup sökülür; çünkü artı uç daha kalındır',
      'İki kutup aynı anda sökülmelidir',
      'Önce eksi (şase) kutbu sökülür; böylece anahtar kazayla metal gövdeye değse bile kısa devre ve kıvılcım riski azalır',
      'Sıranın hiçbir önemi yoktur',
    ],
    answerIndex: 2,
    explanation:
      'Aracın gövdesi eksi kutba bağlıdır (şase). Önce eksi kutup ayrılırsa devre kesilir; artı kutupta çalışırken anahtarın gövdeye değmesi artık kısa devre oluşturmaz. Takarken sıra terstir: eksi kutup en son bağlanır.',
    whyWrong: [
      'Kutup kalınlığı söküm sırasının gerekçesi değildir.',
      'Sıra güvenlik açısından önemlidir; yanlış sıra kıvılcıma ve yaralanmaya yol açabilir.',
    ],
    objective: 'Güvenli akü söküm/takım sırasını ve gerekçesini öğrenmek.',
    tags: ['aku', 'kutup-basi', 'kisa-devre'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-439',
    subject: 'motor',
    topic: 'aku-bakim',
    difficulty: 'orta',
    stem: 'Sürekli çok kısa mesafelerde kullanılan bir araçta akünün giderek zayıflamasının nedeni nedir?',
    options: [
      'Kısa yolda lastiklerin az dönmesi',
      'Marşta harcanan enerjinin kısa sürüş boyunca alternatör tarafından geri konamaması',
      'Kısa yolda yakıtın daha hızlı bitmesi',
      'Kısa mesafede fren balatalarının soğuk kalması',
    ],
    answerIndex: 1,
    explanation:
      'Her marş, aküden yüklü bir akım çeker. Sürüş birkaç dakika sürüyorsa alternatör bu enerjiyi yerine koyamadan araç durur. Tekrarlanan kısa yolculuklar akünün şarj düzeyini adım adım düşürür; ara sıra uzun sürüş ya da şarj cihazı gerekir.',
    whyWrong: [
      'Lastik dönüşü ve fren sıcaklığının akü şarjıyla ilgisi yoktur.',
      'Yakıt seviyesi akünün dolumunu belirlemez.',
    ],
    objective: 'Kısa mesafe kullanımının akü şarj dengesine etkisini kavramak.',
    tags: ['aku', 'sarj-dengesi', 'kisa-mesafe'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-440',
    subject: 'motor',
    topic: 'sigorta',
    difficulty: 'orta',
    stem: 'Atan bir sigortanın yerine sigorta yerine geçecek şekilde tel veya alüminyum folyo sarmak neden kesinlikle yapılmamalıdır?',
    options: [
      'Telin sigorta kutusuna sığmaması',
      'Aracın garanti kaydının silinmesi',
      'Radyonun ayarlarının bozulması',
      'Devrenin korumasız kalması; aşırı akımda kabloların ısınıp eriyerek araç yangınına yol açabilmesi',
    ],
    answerIndex: 3,
    explanation:
      'Sigorta, devreden aşırı akım geçtiğinde eriyip devreyi keserek kabloları ve cihazları korur. Tel veya folyo bu korumayı ortadan kaldırır; arıza anında akım kesilmez, kablolar ısınır ve kablo demeti tutuşarak araç yangını çıkabilir.',
    whyWrong: [
      'Sorun fiziki sığma ya da garanti değil, can ve mal güvenliğidir.',
      'Radyo ayarı bu uygulamanın asıl riski yanında önemsiz kalır.',
    ],
    objective: 'Sigortanın koruma işlevini devre dışı bırakmanın yangın riskini bilmek.',
    tags: ['sigorta', 'elektrik', 'yangin-riski'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-441',
    subject: 'motor',
    topic: 'far-ayari',
    difficulty: 'kolay',
    stem: 'Far ayarının bozuk olması gece sürüşünde hangi iki soruna birden yol açar?',
    options: [
      'Yolun yeterince aydınlatılamaması ve karşıdan gelen sürücülerin gözünün kamaştırılması',
      'Yakıt tüketiminin artması ve motorun hararet yapması',
      'Silecek hızının düşmesi ve kornanın zayıflaması',
      'Lastiklerin aşınması ve fren mesafesinin kısalması',
    ],
    answerIndex: 0,
    explanation:
      'Aşağı kaçık veya yanlış yöne bakan far sürücünün kendi görüşünü kısıtlar; yukarı kaçık far ise karşı yönden gelenleri kamaştırarak kaza riskini artırır. Bu yüzden far ayarı periyodik olarak kontrol ettirilmelidir.',
    whyWrong: [
      'Far ayarının yakıt, hararet, silecek veya lastikle ilgisi yoktur.',
      'Kamaşma yalnızca konfor sorunu değil, ciddi bir güvenlik sorunudur.',
    ],
    objective: 'Bozuk far ayarının hem sürücüye hem karşı trafiğe etkisini bilmek.',
    tags: ['far-ayari', 'gece-surusu', 'guvenlik'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-442',
    subject: 'motor',
    topic: 'klima',
    difficulty: 'kolay',
    stem: 'Klima çalıştırıldığında yakıt tüketiminin bir miktar artmasının nedeni nedir?',
    options: [
      'Klimanın lastik basıncını düşürmesi',
      'Klimanın yakıt deposunu soğutması',
      'Klima kompresörünün çalışmak için gücünü motordan alması',
      'Klimanın egzoz borusunu daraltması',
    ],
    answerIndex: 2,
    explanation:
      'Klima kompresörü, kayış aracılığıyla motor tarafından döndürülür. Devreye girdiğinde motora ek yük biner; motor bu yükü karşılamak için biraz daha fazla yakıt harcar. İhtiyaç yokken klimayı kapatmak tüketimi azaltır.',
    whyWrong: [
      'Klimanın lastik basıncı ve egzozla ilgisi yoktur.',
      'Klima kabini soğutur; yakıt deposunu soğutma diye bir işlevi yoktur.',
    ],
    objective: 'Klimanın motordan güç alarak tüketimi artırdığını kavramak.',
    tags: ['klima', 'kompresor', 'yakit-tuketimi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-443',
    subject: 'motor',
    topic: 'klima',
    difficulty: 'orta',
    stem: 'Yağışlı ve soğuk havada camların iç yüzeyinde oluşan buğuyu en hızlı gidermenin yolu nedir?',
    options: [
      'Tüm camları kapatıp beklemek',
      'Hava akımını cama yönlendirip klimayı (AC) da çalıştırmak; klima havanın nemini alarak buğuyu hızla çözer',
      'Silecekleri en yüksek hızda çalıştırmak',
      'Aracı durdurup motoru kapatmak',
    ],
    answerIndex: 1,
    explanation:
      'Buğu, kabindeki nemli havanın soğuk camda yoğuşmasıdır. Klima çalıştığında havayı kurutur; kurutulmuş hava cama üflendiğinde buğu kısa sürede açılır. Sıcak hava ile birlikte kullanmak etkiyi artırır.',
    whyWrong: [
      'Beklemek ve motoru kapatmak nemli havayı kurutmaz.',
      'Silecekler yalnızca camın dış yüzeyini temizler; iç buğuya etki etmez.',
    ],
    objective: 'Klimanın nem alma özelliğini buğu çözmede kullanmayı öğrenmek.',
    tags: ['klima', 'bugu', 'gorus'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-444',
    subject: 'motor',
    topic: 'motor-koruma',
    difficulty: 'kolay',
    stem: 'Motor daha ısınmadan yüksek devirlere çıkmak neden sakıncalıdır?',
    options: [
      'Farların erken yanmasına yol açtığı için',
      'Vites kutusunun kilitlenmesine neden olduğu için',
      'Lastiklerin basıncını artırdığı için',
      'Soğuk yağ henüz tüm parçalara tam ulaşmadığından ve akıcılığı düşük olduğundan motor aşınması arttığı için',
    ],
    answerIndex: 3,
    explanation:
      'Soğuk motorda yağ koyudur ve yağ filmi tüm yüzeylere henüz tam oturmamıştır. Bu durumda yüksek devir, metal yüzeylerin yetersiz yağlamayla çalışmasına ve erken aşınmaya yol açar. Motor ısınana kadar sakin sürülmelidir.',
    whyWrong: [
      'Farlar, vites kilidi ve lastik basıncının motor sıcaklığıyla bu şekilde bir ilişkisi yoktur.',
      'Sorun elektrik değil, yağlama yetersizliğidir.',
    ],
    objective: 'Soğuk motorda düşük devirle sürmenin gerekçesini bilmek.',
    tags: ['motor-koruma', 'soguk-calistirma', 'yaglama'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-445',
    subject: 'motor',
    topic: 'motor-koruma',
    difficulty: 'orta',
    stem: 'Soğuk bir motoru ısıtmanın günümüzde önerilen yolu aşağıdakilerden hangisidir?',
    options: [
      'Kısa bir süre sonra yola çıkıp motoru düşük devirde, yumuşak bir tempoyla sürerek ısıtmak',
      'Park hâlinde uzun süre rölantide bekletmek',
      'Çalıştırır çalıştırmaz yüksek devirle hızlanmak',
      'Motoru ısınana kadar art arda çalıştırıp durdurmak',
    ],
    answerIndex: 0,
    explanation:
      'Uzun rölanti beklemesi motoru çok yavaş ısıtır, yakıt harcar ve çevreyi kirletir. Önerilen yöntem, çalıştırdıktan kısa süre sonra düşük devirde sakin sürüşe başlamaktır; motor yük altında daha hızlı ve dengeli ısınır.',
    whyWrong: [
      'Uzun rölanti hem verimsiz hem gereksiz emisyon kaynağıdır.',
      'Soğukken yüksek devir aşınmayı artırır; sık çalıştırıp durdurmak da aküyü ve motoru yorar.',
    ],
    objective: 'Modern motor ısıtma yaklaşımını öğrenmek.',
    tags: ['motor-koruma', 'rolanti', 'isitma'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-446',
    subject: 'motor',
    topic: 'turbo',
    difficulty: 'orta',
    stem: 'Turboşarjın (turbo) motordaki temel görevi nedir?',
    options: [
      'Fren sistemine ek basınç sağlamak',
      'Motoru marş anında döndürmek',
      'Egzoz gazının enerjisiyle türbini döndürüp silindirlere daha fazla hava basarak aynı motor hacminden daha yüksek güç elde edilmesini sağlamak',
      'Kabin havasını filtrelemek',
    ],
    answerIndex: 2,
    explanation:
      'Turbo, atılan egzoz gazının enerjisini kullanarak bir türbin çevirir; türbinle aynı mile bağlı kompresör motora basınçlı hava gönderir. Silindire daha çok hava girince daha çok yakıt yakılabilir ve küçük hacimden yüksek güç alınır.',
    whyWrong: [
      'Fren basıncı ve marş görevleri farklı sistemlere aittir.',
      'Kabin havasını polen filtresi süzer.',
    ],
    objective: 'Turbonun çalışma ilkesini temel düzeyde kavramak.',
    tags: ['turbo', 'egzoz-gazi', 'guc'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-447',
    subject: 'motor',
    topic: 'turbo',
    difficulty: 'zor',
    stem: 'Uzun ve zorlu bir sürüşün (ör. hızlı otoyol seyri) hemen ardından turbolu bir motoru aniden durdurmak yerine kısa süre rölantide bekletmenin gerekçesi nedir?',
    options: [
      'Akünün bu sürede şarj olmasını sağlamak',
      'Çok ısınan turbonun, motor stop edilmeden önce dolaşan yağ ile bir miktar soğumasına imkân vermek; ani stopta yatakta kalan yağın yanarak turboya zarar verebilmesi',
      'Yakıt deposundaki basıncı düşürmek',
      'Fren balatalarını soğutmak',
    ],
    answerIndex: 1,
    explanation:
      'Zorlu sürüşte turbo gövdesi çok yüksek sıcaklığa çıkar. Motor aniden susturulursa yağ dolaşımı kesilir; turbonun yatağında kalan yağ aşırı ısıyla bozulur ve zamanla yatak aşınır. Kısa rölanti beklemesi bu ısıyı güvenli seviyeye indirir.',
    whyWrong: [
      'Rölantide amaç akü şarjı veya depo basıncı değildir.',
      'Fren balataları motorun rölantide çalışmasından etkilenmez.',
    ],
    objective: 'Turbo soğutma beklemesinin mantığını temel düzeyde öğrenmek.',
    tags: ['turbo', 'rolanti', 'yaglama'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-448',
    subject: 'motor',
    topic: 'yakit-tasarrufu',
    difficulty: 'kolay',
    stem: 'Aşağıdaki sürüş alışkanlıklarından hangisi yakıt tasarrufu sağlar?',
    options: [
      'Her ışıkta ani kalkış yapmak',
      'Sürekli düşük viteste yüksek devirle gitmek',
      'Aracı hep rölantide bekleterek ısıtmak',
      'Ani hızlanma ve ani frenden kaçınıp trafiği önceden okuyarak akıcı ve dengeli bir hızda sürmek',
    ],
    answerIndex: 3,
    explanation:
      'Yakıtın önemli bölümü hızlanma sırasında harcanır. Trafiği önceden okuyup gaz-fren geçişlerini azaltan, uygun viteste dengeli hızda giden sürücü hem yakıttan tasarruf eder hem fren ve lastik ömrünü uzatır.',
    whyWrong: [
      'Ani kalkışlar ve gereksiz yüksek devir tüketimi belirgin artırır.',
      'Uzun rölanti beklemesi hiç yol almadan yakıt harcamaktır.',
    ],
    objective: 'Ekonomik sürüş tekniklerinin temelini öğrenmek.',
    tags: ['yakit-tasarrufu', 'ekonomik-surus', 'cevre'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-449',
    subject: 'motor',
    topic: 'yakit-tasarrufu',
    difficulty: 'orta',
    stem: 'Kullanılmadığı hâlde araçta takılı bırakılan tavan taşıyıcısı (port bagaj) ve yüksek hızda açık bırakılan camlar yakıt tüketimini nasıl etkiler?',
    options: [
      'Rüzgâr direncini artırdıkları için yakıt tüketimini yükseltir; gereksiz taşıyıcı sökülmelidir',
      'Hiçbir etkisi olmaz',
      'Yakıt tüketimini azaltır',
      'Yalnızca lastik basıncını etkiler',
    ],
    answerIndex: 0,
    explanation:
      'Tavan taşıyıcısı aracın aerodinamik yapısını bozar; yüksek hızda açık camlar da hava akışını türbülansa çevirir. Artan rüzgâr direncini yenmek için motor daha fazla yakıt harcar. Kullanılmayan taşıyıcı sökülmeli, yüksek hızda camlar kapatılmalıdır.',
    whyWrong: [
      'Aerodinamik direnç özellikle yüksek hızda tüketimin ana kalemlerindendir; etkisiz sayılamaz.',
      'Bu unsurların lastik basıncıyla ilgisi yoktur.',
    ],
    objective: 'Rüzgâr direncinin yakıt tüketimine etkisini kavramak.',
    tags: ['yakit-tasarrufu', 'aerodinamik', 'tavan-tasiyici'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-450',
    subject: 'motor',
    topic: 'yakit-tasarrufu',
    difficulty: 'orta',
    stem: 'Hemzemin geçit veya uzun süreli bekleme gerektiren durumlarda yakıt ve çevre açısından doğru davranış hangisidir?',
    options: [
      'Gaza aralıklı basarak motoru canlı tutmak',
      'Bekleme uzayacaksa motoru durdurmak; rölantide çalışan motor yol almadan yakıt tüketir ve egzoz gazı üretir',
      'Vitesi boşa alıp devri yükseltmek',
      'Klimayı sonuna kadar açmak',
    ],
    answerIndex: 1,
    explanation:
      'Rölantide çalışan motor hiçbir iş üretmeden yakıt harcar ve çevreye egzoz gazı verir. Beklemenin uzayacağı belliyse motoru durdurmak hem ekonomiktir hem çevrecidir; start-stop donanımlı araçlar bunu zaten kendiliğinden yapar.',
    whyWrong: [
      'Boşta gaza basmak ve devri yükseltmek yalnızca israfı artırır.',
      'Klimayı sonuna kadar açmak beklemede tüketimi daha da yükseltir.',
    ],
    objective: 'Uzun beklemelerde motoru durdurma alışkanlığını kazanmak.',
    tags: ['yakit-tasarrufu', 'rolanti', 'cevre'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-451',
    subject: 'motor',
    topic: 'lpg',
    difficulty: 'orta',
    stem: "LPG'li bir araçta seyir sırasında belirgin gaz kokusu hissedildiğinde doğru davranış nedir?",
    options: [
      'Camları kapatıp yola devam etmek',
      'Aracı açık ve güvenli bir alanda durdurup kontağı kapatmak; kıvılcım oluşturabilecek işlemlerden kaçınmak ve sistemi yetkili servise kontrol ettirmek',
      'Kokunun geçmesi için kaloriferi açmak',
      'Yakıt türünü benzine çevirip hızlanmak',
    ],
    answerIndex: 1,
    explanation:
      'Gaz kokusu sızıntı ihtimali demektir. Araç açık havada durdurulmalı, kontak kapatılmalı, sigara ve kıvılcım kaynaklarından uzak durulmalı ve tesisat yetkili LPG servisinde kontrol ettirilmelidir. Sızıntılı araçla yola devam edilmez.',
    whyWrong: [
      'Camları kapatmak gazın kabinde birikmesine yol açar.',
      'Kalorifer kokuyu gidermez; sızıntı sürer.',
      'Yakıt türü değiştirilse bile sızıntı yapan tesisat tehlike olmaya devam eder.',
    ],
    objective: 'LPG sızıntısı şüphesinde güvenli davranış adımlarını öğrenmek.',
    tags: ['lpg', 'gaz-sizintisi', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-452',
    subject: 'motor',
    topic: 'lpg',
    difficulty: 'kolay',
    stem: "Bir aracın LPG'ye dönüştürülmesiyle ilgili doğru ifade aşağıdakilerden hangisidir?",
    options: [
      'Dönüşüm herkes tarafından evde yapılabilir',
      'LPG tankı ömür boyu hiçbir kontrol gerektirmez',
      'Dönüşüm montajı sonrası araç hemen satılmalıdır',
      'Dönüşüm yetkili firmalarca yapılmalı; tesisat ve tank periyodik sızdırmazlık kontrolünden geçirilmeli, dönüşüm araç belgelerine işlenmelidir',
    ],
    answerIndex: 3,
    explanation:
      'LPG dönüşümü basınçlı gaz tesisatı içerdiğinden yalnızca yetkili ve belgeli firmalarca yapılmalıdır. Sistem, belirli aralıklarla sızdırmazlık kontrolünden geçirilmeli; dönüşüm muayene ve tescil kayıtlarına işlenmelidir.',
    whyWrong: [
      'Yetkisiz montaj sızıntı ve yangın riskini büyütür.',
      'Tank ve tesisat periyodik kontrole tabidir; satış zorunluluğu diye bir kural yoktur.',
    ],
    objective: 'LPG dönüşümünde yetkili servis ve periyodik kontrol zorunluluğunu bilmek.',
    tags: ['lpg', 'donusum', 'periyodik-kontrol'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-453',
    subject: 'motor',
    topic: 'obd',
    difficulty: 'zor',
    stem: 'Motor arıza lambasının (check engine) sabit yanması yerine yanıp sönmesi neden daha acil bir durumdur?',
    options: [
      'Yanıp sönme, aktif bir ateşleme hatası (tekleme) yaşandığını gösterir; yanmadan egzoza kaçan yakıt katalitik konvertöre kalıcı zarar verebilir, hız ve yük azaltılıp en kısa sürede servise gidilmelidir',
      'Yanıp sönme sadece ampulün gevşediğini gösterir',
      'Yanıp sönme, arızanın kendi kendine düzeldiği anlamına gelir',
      'Yanıp sönme, yakıt deposunun dolu olduğunu bildirir',
    ],
    answerIndex: 0,
    explanation:
      'Sabit yanan lamba kayıtlı bir arızayı, yanıp sönen lamba ise o anda süren ateşleme hatasını bildirir. Silindirde yanmayan karışım katalizör içinde tutuşarak onu eritebilir. Bu durumda motor zorlanmadan, gecikmeden servise gidilmelidir.',
    whyWrong: [
      'Lambanın yanıp sönmesi kontrollü bir uyarı desenidir; ampul gevşekliği değildir.',
      'Yanıp sönme düzelmeyi değil, tam tersine ciddileşen bir durumu gösterir.',
      'Yakıt seviyesini ayrı bir gösterge bildirir.',
    ],
    objective: 'Check engine lambasında sabit yanma ile yanıp sönme farkını öğrenmek.',
    tags: ['obd', 'check-engine', 'katalitik-konvertor'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-454',
    subject: 'motor',
    topic: 'hararet',
    difficulty: 'zor',
    stem: 'Hararet yapmış, çok sıcak bir motorun radyatörüne hemen soğuk su doldurmak neden tehlikelidir?',
    options: [
      'Soğuk su radyatörün rengini soldurur',
      'Yakıt tüketimi kalıcı olarak artar',
      'Ani sıcaklık farkı (termik şok) silindir kapağında veya motor bloğunda çatlamaya yol açabilir; su ancak motor soğuduktan sonra ve yavaşça eklenmelidir',
      'Soğuk su akünün boşalmasına neden olur',
    ],
    answerIndex: 2,
    explanation:
      'Kızgın metale aniden soğuk su temas ettiğinde bölgesel hızlı büzülme oluşur; bu termik şok silindir kapağını veya bloğu çatlatabilir. Doğru yöntem motorun soğumasını beklemek, ardından soğutma sıvısını yavaş yavaş tamamlamaktır.',
    whyWrong: [
      'Sorun görüntü ya da yakıt tüketimi değil, metalin çatlamasıdır.',
      'Radyatöre eklenen suyun aküyle bir ilgisi yoktur.',
    ],
    objective: 'Sıcak motora soğuk su eklemenin termik şok riskini kavramak.',
    tags: ['hararet', 'termik-sok', 'sogutma-sistemi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-455',
    subject: 'motor',
    topic: 'motor-bakim',
    difficulty: 'orta',
    stem: 'Motor bölmesini yüksek basınçlı suyla yıkamak neden riskli olabilir?',
    options: [
      'Motorun boyasının parlaklaşması nedeniyle',
      'Basınçlı suyun soket, sigorta kutusu ve alternatör gibi elektrik-elektronik parçalara girerek arızalara ve temassızlıklara yol açabilmesi nedeniyle',
      'Suyun lastikleri kaygan hâle getirmesi nedeniyle',
      'Yakıt kalitesini bozması nedeniyle',
    ],
    answerIndex: 1,
    explanation:
      'Modern motor bölmesi çok sayıda soket, kontrol ünitesi ve sensör barındırır. Basınçlı su bu bağlantıların içine işleyerek kısa devre, temassızlık ve pas oluşturabilir. Temizlik gerekiyorsa hassas bölgeler korunarak, kontrollü yöntemlerle yapılmalıdır.',
    whyWrong: [
      'Amaçlanan sorun görüntü değil, elektrik arızası riskidir.',
      'Lastikler ve yakıt kalitesi motor bölmesi yıkamadan etkilenmez.',
    ],
    objective: 'Basınçlı motor yıkamanın elektronik aksama zararını bilmek.',
    tags: ['motor-bakim', 'elektrik', 'yikama'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
];
