/**
 * ÖZGÜN ilk yardım soruları — 2. genişletme (Program 1). ROADMAP C.4/E.6.
 * Kaynak = resmî temel ilk yardım bilgisi; KENDİ İFADEMİZLE. review:'draft' — İLK YARDIM EĞİTMENİ onayı ZORUNLU.
 */
import type { QuestionInput } from '@ea/content-schema';
const SRC = 'Resmî temel ilk yardım bilgisi (özgün ifade) — uzman onayı bekliyor';
export const ILKYARDIM_QUESTIONS_2: QuestionInput[] = [
  {
    id: 'ilkyardim-201',
    subject: 'ilkyardim',
    topic: 'tyd',
    difficulty: 'orta',
    stem: 'Erişkin bir kişiye dış kalp masajı uygularken göğüs kemiği yaklaşık ne kadar aşağı çökecek şekilde bastırılmalıdır?',
    options: ['Yaklaşık 2 cm', 'Yaklaşık 8 cm', 'Yaklaşık 10 cm', 'Yaklaşık 5 cm'],
    answerIndex: 3,
    explanation:
      'Erişkinde etkili bir dış kalp masajı için göğüs kemiğinin yaklaşık 5 cm çökmesi gerekir; daha sığ bası kanı dolaştırmaya yetmez, aşırı derin bası ise yaralanmaya yol açabilir.',
    whyWrong: [
      '2 cm çok sığdır ve kalbi yeterince sıkıştırmaz.',
      '8-10 cm aşırı derinliktir ve iç organ hasarı riski taşır.',
    ],
    objective: 'Erişkin kalp masajı bası derinliğini bilmek.',
    tags: ['tyd', 'kalp-masaji', 'derinlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-202',
    subject: 'ilkyardim',
    topic: 'tyd',
    difficulty: 'orta',
    stem: 'Tek kişiyle yapılan erişkin temel yaşam desteğinde kalp masajı ve yapay solunum hangi oranda uygulanır?',
    options: [
      '15 bası - 1 soluk',
      '5 bası - 1 soluk',
      '10 bası - 2 soluk',
      '20 bası - 2 soluk',
      '30 bası - 2 soluk',
    ],
    answerIndex: 4,
    explanation:
      'Erişkinde temel yaşam desteği 30 göğüs basısının ardından 2 kurtarıcı soluk verilerek, yani 30:2 oranında sürdürülür ve bu döngü kesintisiz tekrarlanır.',
    whyWrong: [
      '15:1 ve 5:1 gibi oranlar güncel erişkin uygulamasında kullanılmaz.',
      '10:2 ve 20:2 standart bir döngü değildir.',
    ],
    objective: '30:2 bası-soluk oranını kavramak.',
    tags: ['tyd', 'oran', 'canlandirma'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-203',
    subject: 'ilkyardim',
    topic: 'tyd',
    difficulty: 'orta',
    stem: 'Erişkinde kesintisiz uygulanan dış kalp masajının dakikadaki bası sayısı hangi aralıkta olmalıdır?',
    options: ['40-60', '60-80', '100-120', '160-180'],
    answerIndex: 2,
    explanation:
      'Etkili bir dolaşım için erişkinde göğüs basıları dakikada 100 ila 120 arasında bir hızla uygulanır; bu hız kanın beyne ve organlara ulaşmasını sağlar.',
    whyWrong: [
      '40-80 aralığı çok yavaştır ve dolaşımı yeterince desteklemez.',
      '160-180 aşırı hızlıdır ve göğsün geri yükselmesine izin vermez.',
    ],
    objective: 'Kalp masajı bası hızını bilmek.',
    tags: ['tyd', 'hiz', 'kalp-masaji'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-204',
    subject: 'ilkyardim',
    topic: 'bilinc',
    difficulty: 'kolay',
    stem: 'Yerde hareketsiz yatan bir kişinin bilincinin açık olup olmadığını anlamak için ilk olarak ne yapılır?',
    options: [
      'Yüzüne su dökülür',
      'Omzundan hafifçe sarsılıp yüksek sesle seslenilir',
      'Ayağa kaldırılmaya çalışılır',
      'Ağzına ilaç verilir',
    ],
    answerIndex: 1,
    explanation:
      'Bilinç kontrolü için kişinin omzuna hafifçe dokunup sarsılır ve yüksek sesle seslenilir; yanıt yoksa bilincin kapalı olduğu kabul edilerek yardım çağrılır.',
    whyWrong: [
      'Yüze su dökmek bilinç değerlendirmesinin doğru yöntemi değildir.',
      'Kişiyi ayağa kaldırmak ya da ilaç vermek olası yaralanmayı ağırlaştırabilir.',
    ],
    objective: 'Bilinç kontrolü yöntemini uygulamak.',
    tags: ['bilinc', 'degerlendirme', 'ilk-adim'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-205',
    subject: 'ilkyardim',
    topic: 'pozisyon',
    difficulty: 'orta',
    stem: 'Koma (yan yatış / kurtarma) pozisyonu öncelikle hangi yaralıya uygulanır?',
    options: [
      'Solunumu ve nabzı durmuş yaralıya',
      'Kol kırığı olan bilinci açık yaralıya',
      'Bilinci kapalı fakat solunumu olan yaralıya',
      'Yalnızca burnu kanayan yaralıya',
    ],
    answerIndex: 2,
    explanation:
      'Koma pozisyonu, bilinci kapalı olduğu hâlde solunumu devam eden yaralıya uygulanır; yan yatış dilin geriye kaçmasını ve kusmuğun soluk borusunu tıkamasını önler.',
    whyWrong: [
      'Solunumu durmuş yaralıya önce temel yaşam desteği gerekir.',
      'Bilinci açık yaralıya bu pozisyon gerekmez.',
    ],
    objective: 'Koma pozisyonunun endikasyonunu bilmek.',
    tags: ['pozisyon', 'bilinc', 'hava-yolu'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-206',
    subject: 'ilkyardim',
    topic: 'kanama',
    difficulty: 'kolay',
    stem: 'Kol veya bacaktan olan dış kanamayı durdurmak için uygulanacak ilk ve temel yöntem hangisidir?',
    options: [
      'Yaralı bölgeyi ovmak',
      'Yaraya toz şeker dökmek',
      'Yaralıyı ayağa kaldırıp yürütmek',
      'Kanayan yere doğrudan temiz bezle baskı uygulamak',
    ],
    answerIndex: 3,
    explanation:
      'Dış kanamada ilk yöntem, kanayan bölgeye temiz bir bez veya gazlı bezle doğrudan baskı uygulamak ve mümkünse yaralı bölgeyi kalp seviyesinden yukarı kaldırmaktır.',
    whyWrong: [
      'Bölgeyi ovmak kanamayı artırır.',
      'Yaraya şeker gibi maddeler dökmek enfeksiyon riski oluşturur.',
    ],
    objective: 'Dış kanamada doğrudan baskı ilkesini uygulamak.',
    tags: ['kanama', 'baski', 'yaralanma'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-207',
    subject: 'ilkyardim',
    topic: 'kanama',
    difficulty: 'zor',
    stem: 'Baskı ve yükseltme ile durmayan hayati kanamada turnike uygulanırsa hangisi mutlaka yapılmalıdır?',
    options: [
      'Turnikenin uygulandığı saat not edilmeli',
      'Turnike her beş dakikada bir gevşetilmeli',
      'Turnike eklem üzerine bağlanmalı',
      'Turnike ince bir iple sıkılmalı',
    ],
    answerIndex: 0,
    explanation:
      'Turnike ancak başka türlü durdurulamayan hayati kanamalarda son çare olarak uygulanır ve uygulama saati mutlaka bir yere yazılır; bu bilgi hastaneye teslimde çok önemlidir.',
    whyWrong: [
      'Turnike gelişigüzel gevşetilmez; bu tekrar kanamaya yol açar.',
      'Eklem üzerine veya ince iple uygulanması doku hasarını artırır.',
    ],
    objective: 'Turnike uygulamasında saat kaydının önemini kavramak.',
    tags: ['kanama', 'turnike', 'son-care'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-208',
    subject: 'ilkyardim',
    topic: 'sok',
    difficulty: 'orta',
    stem: 'Şok belirtileri gösteren (soluk, soğuk ve terli ciltli) bir yaralıya hangi pozisyon ve önlem uygundur?',
    options: [
      'Oturtulup soğuk su içirilir',
      'Yüzüstü yatırılıp beklenir',
      'Ayağa kaldırılıp yürütülür',
      'Ayaklar yukarı kaldırılıp üzeri örtülerek sıcak tutulur',
    ],
    answerIndex: 3,
    explanation:
      'Şoktaki yaralı sırtüstü yatırılıp bacakları yaklaşık 30 cm yükseltilir ve üzeri örtülerek ısı kaybı önlenir; böylece kanın hayati organlara yönelmesi desteklenir.',
    whyWrong: [
      'Bilinç durumu belirsiz yaralıya sıvı verilmez.',
      'Yüzüstü yatırmak veya yürütmek durumu kötüleştirir.',
    ],
    objective: 'Şok pozisyonu ve ısı korumasını uygulamak.',
    tags: ['sok', 'pozisyon', 'isi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-209',
    subject: 'ilkyardim',
    topic: 'sok',
    difficulty: 'kolay',
    stem: 'Aşağıdakilerden hangisi genel bir şok tablosunun tipik belirtilerinden biridir?',
    options: [
      'Ciltte kızarıklık ve sıcaklık',
      'Yavaş ve derin soluk alıp verme',
      'Belirgin şekilde yükselen tansiyon',
      'Soluk, soğuk ve nemli cilt ile hızlı zayıf nabız',
    ],
    answerIndex: 3,
    explanation:
      'Şokta dolaşım bozulduğu için cilt soluk, soğuk ve terli hâle gelir; nabız hızlanır ve zayıflar, solunum sıklaşır. Bu belirtiler acil müdahale gerektirir.',
    whyWrong: [
      'Kızarık ve sıcak cilt şokun tipik bulgusu değildir.',
      'Şokta solunum yavaş ve derin değil, genellikle hızlı ve yüzeyeldir.',
    ],
    objective: 'Şok belirtilerini tanımak.',
    tags: ['sok', 'belirti', 'dolasim'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-210',
    subject: 'ilkyardim',
    topic: 'yanik',
    difficulty: 'kolay',
    stem: 'Kaynar su ile haşlanan bir kişinin yanık bölgesine ilk yardım olarak ne yapılmalıdır?',
    options: [
      'Yanık üzerine buz konulmalı',
      'Yanık bölgesi bol soğuk (akan) su altında bir süre tutulmalı',
      'Yanığa diş macunu sürülmeli',
      'Yanık bölgesi sıcak suyla yıkanmalı',
    ],
    answerIndex: 1,
    explanation:
      'Yanıkta öncelikle bölge bol ve akan soğuk suyla soğutulur; bu, ısının derine ilerlemesini yavaşlatır ve ağrıyı azaltır. Yara temiz bezle örtülür.',
    whyWrong: [
      'Doğrudan buz koymak dokuyu ayrıca hasarlar.',
      'Diş macunu, yoğurt gibi maddeler enfeksiyona ve iyileşme güçlüğüne yol açar.',
    ],
    objective: 'Yanıkta soğuk su ile soğutma ilkesini uygulamak.',
    tags: ['yanik', 'sogutma', 'ilk-adim'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-211',
    subject: 'ilkyardim',
    topic: 'yanik',
    difficulty: 'orta',
    stem: 'Yanık bölgesine ilk yardımda aşağıdakilerden hangisi kesinlikle yapılmamalıdır?',
    options: [
      'Yanık üzerine macun, yağ veya salça sürmek',
      'Bölgeyi soğuk su ile soğutmak',
      'Yarayı temiz bir bezle örtmek',
      'Yaralıyı sağlık kuruluşuna yönlendirmek',
    ],
    answerIndex: 0,
    explanation:
      'Yanığa diş macunu, yağ, salça gibi maddeler sürülmesi yarayı örterek ısıyı hapseder, enfeksiyon riskini artırır ve doktorun değerlendirmesini zorlaştırır; bu nedenle kesinlikle yapılmaz.',
    whyWrong: [
      'Soğuk su ile soğutmak doğru bir uygulamadır.',
      'Yarayı temiz bezle örtmek ve sağlık kuruluşuna yönlendirmek gereklidir.',
    ],
    objective: 'Yanıkta yapılmaması gerekenleri ayırt etmek.',
    tags: ['yanik', 'yanlis-uygulama', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-212',
    subject: 'ilkyardim',
    topic: 'bogulma',
    difficulty: 'orta',
    stem: 'Yemek yerken boğazına yabancı cisim kaçan, konuşamayan ve öksüremeyen bilinci açık erişkine hangi manevra uygulanır?',
    options: [
      'Sırtına sürekli yumruk atılır',
      'Karın üstü basma (Heimlich) manevrası uygulanır',
      'Bol su içirilir',
      'Sırtüstü yatırılıp beklenir',
    ],
    answerIndex: 1,
    explanation:
      'Tam tıkanmada kişi konuşamaz ve öksüremez; arkasına geçilip göbek ile göğüs kemiği arasına içe-yukarı bası (Heimlich manevrası) uygulanarak cismin çıkması sağlanmaya çalışılır.',
    whyWrong: [
      'Kişiye su içirmek tıkanıklığı artırır.',
      'Hiçbir şey yapmadan beklemek hava yolunun kapalı kalmasına yol açar.',
    ],
    objective: 'Tam tıkanmada Heimlich manevrasını uygulamak.',
    tags: ['bogulma', 'heimlich', 'hava-yolu'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-213',
    subject: 'ilkyardim',
    topic: 'bogulma',
    difficulty: 'kolay',
    stem: 'Hava yolunun yabancı cisimle tam tıkandığını gösteren en belirgin bulgu hangisidir?',
    options: [
      'Kişinin rahatça öksürebilmesi',
      'Kişinin yüksek sesle bağırabilmesi',
      'Kişinin konuşamaması ve öksürememesi',
      'Kişinin normal nefes alabilmesi',
    ],
    answerIndex: 2,
    explanation:
      'Tam tıkanıklıkta hava geçişi durduğu için kişi konuşamaz, öksüremez ve nefes alamaz; genellikle ellerini boğazına götürür. Bu durum acil müdahale gerektirir.',
    whyWrong: [
      'Öksürebilme ve konuşabilme kısmi tıkanmanın işaretidir.',
      'Normal nefes alabiliyorsa tam tıkanma yoktur.',
    ],
    objective: 'Tam ve kısmi tıkanmayı ayırt etmek.',
    tags: ['bogulma', 'belirti', 'hava-yolu'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-214',
    subject: 'ilkyardim',
    topic: 'kirik',
    difficulty: 'orta',
    stem: 'Kolunda kırık şüphesi olan bilinci açık bir yaralıya ilk yardımda ne yapılır?',
    options: [
      'Kemik zorla düzeltilmeye çalışılır',
      'Kol defalarca hareket ettirilir',
      'Kırık bölge bulunduğu şekilde hareketsiz tespit edilir (atellenir)',
      'Yaralıya kırık bölgeyi kullandırılır',
    ],
    answerIndex: 2,
    explanation:
      'Kırık şüphesinde bölge bulunduğu konumda, bir üst ve bir alt eklemi de içine alacak şekilde sabitlenir; amaç hareketi engelleyip ağrıyı ve ek doku hasarını azaltmaktır.',
    whyWrong: [
      'Kemiği zorla düzeltmeye çalışmak damar ve sinir hasarına yol açabilir.',
      'Bölgeyi hareket ettirmek kırığı ağırlaştırır.',
    ],
    objective: 'Kırıkta hareketsiz tespit ilkesini uygulamak.',
    tags: ['kirik', 'atel', 'tespit'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-215',
    subject: 'ilkyardim',
    topic: 'kirik',
    difficulty: 'zor',
    stem: 'Kemiğin cildi delerek dışarı çıktığı açık kırıkta ilk yardımcının öncelikli tutumu ne olmalıdır?',
    options: [
      'Çıkan kemiği içeri itmeye çalışmak',
      'Kanamayı kontrol edip bölgeyi temiz bezle örterek sabitlemek',
      'Kemiği elle yerine oturtmak',
      'Yaralıyı koşarak taşımak',
    ],
    answerIndex: 1,
    explanation:
      'Açık kırıkta önce kanama kontrol edilir, yara temiz bezle örtülür ve bölge olduğu gibi sabitlenir; dışarı çıkan kemik parçası kesinlikle içeri itilmeye çalışılmaz.',
    whyWrong: [
      'Kemiği içeri itmek enfeksiyon ve ek yaralanma riski oluşturur.',
      'Yaralıyı sarsarak taşımak kırığı ve kanamayı ağırlaştırır.',
    ],
    objective: 'Açık kırıkta doğru yaklaşımı belirlemek.',
    tags: ['kirik', 'acik-kirik', 'kanama'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-216',
    subject: 'ilkyardim',
    topic: 'olay-yeri',
    difficulty: 'kolay',
    stem: '112 Acil Sağlık hattını ararken bildirilmesi gereken bilgilerden biri aşağıdakilerden hangisidir?',
    options: [
      'Yaralının en sevdiği yemek',
      'Yakındaki dükkânların isimleri',
      'Olayın kesin yeri, türü ve yaralı sayısı',
      'Hava durumu tahmini',
    ],
    answerIndex: 2,
    explanation:
      '112 aranırken olayın olduğu yer açık biçimde tarif edilir; olayın türü, yaralı sayısı ve yaralıların durumu bildirilir. Görevli izin vermeden telefon kapatılmaz.',
    whyWrong: [
      'Kişisel tercihler acil bildirim için gereksizdir.',
      'Dükkân isimleri ancak adres tarifine yardımcıysa anlam taşır, temel bilgi değildir.',
    ],
    objective: 'Acil çağrıda verilecek bilgileri sıralamak.',
    tags: ['olay-yeri', 'ihbar', '112'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-217',
    subject: 'ilkyardim',
    topic: 'nakil',
    difficulty: 'orta',
    stem: 'Trafik kazasında omurga yaralanması şüphesi olan yaralı için genel kural nedir?',
    options: [
      'Yaralı hemen ayağa kaldırılır',
      'Yaşamı tehdit eden bir tehlike yoksa yaralı yerinden oynatılmaz',
      'Yaralı sürüklenerek taşınır',
      'Yaralının başı geriye doğru bükülür',
    ],
    answerIndex: 1,
    explanation:
      'Omurga yaralanması şüphesinde yaralı, yangın veya patlama gibi zorunlu bir tehlike olmadıkça yerinden oynatılmaz; gereksiz hareket kalıcı felce yol açabilir.',
    whyWrong: [
      'Ayağa kaldırmak veya sürüklemek omurga hasarını ağırlaştırır.',
      'Başı geriye bükmek omurga yaralısında sakıncalıdır.',
    ],
    objective: 'Omurga yaralısında hareketsizlik ilkesini kavramak.',
    tags: ['nakil', 'omurga', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-218',
    subject: 'ilkyardim',
    topic: 'nakil',
    difficulty: 'zor',
    stem: 'Yangın gibi hayati bir tehlike nedeniyle yaralının acilen araçtan çıkarılması gerektiğinde uygun teknik hangisidir?',
    options: [
      'Kolundan asılıp hızla çekmek',
      'Baş-boyun-gövde ekseni korunarak (Rentek benzeri kavrama ile) çıkarmak',
      'Yaralıyı tek koldan sürüklemek',
      'Ayaklarından tutup çekmek',
    ],
    answerIndex: 1,
    explanation:
      'Zorunlu tahliyede yaralı, baş-boyun-gövde aynı hizada tutulacak şekilde kavranıp tek eksende çıkarılır; bu yöntem omurga ve boyun hasarı riskini en aza indirir.',
    whyWrong: [
      'Koldan veya ayaktan çekmek boyun ve omurgayı bükerek zarar verir.',
      'Tek koldan sürüklemek eksen bütünlüğünü bozar.',
    ],
    objective: 'Zorunlu tahliyede eksen koruyan taşımayı bilmek.',
    tags: ['nakil', 'tahliye', 'omurga'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-219',
    subject: 'ilkyardim',
    topic: 'olay-yeri',
    difficulty: 'orta',
    stem: 'Karayolunda meydana gelen bir kazada ikinci bir kazayı önlemek için ilk yapılması gerekenlerden biri hangisidir?',
    options: [
      'Yaralıların üzerini örtmek',
      'Aracın dörtlü flaşörünü yakıp uygun mesafeye reflektör (üçgen) koymak',
      'Kaza yerini terk etmek',
      'Trafiği hızlandırmaya çalışmak',
    ],
    answerIndex: 1,
    explanation:
      'Olay yeri güvenliği için aracın dörtlü flaşörü yakılır, kontak kapatılır ve gelen trafiği uyarmak üzere uygun mesafeye reflektör konularak ikinci bir kazanın önüne geçilir.',
    whyWrong: [
      'Yaralının üzerini örtmek önemlidir ancak ikincil kazayı önlemez.',
      'Olay yerini terk etmek ilk yardım ve güvenlik ilkesine aykırıdır.',
    ],
    objective: 'İkincil kaza önleme tedbirlerini uygulamak.',
    tags: ['olay-yeri', 'guvenlik', 'reflektor'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-220',
    subject: 'ilkyardim',
    topic: 'bilinc',
    difficulty: 'orta',
    stem: 'Bilinci kapalı bir yaralıda ilk yardımcının kontrol etmesi gereken en öncelikli hayati işlev hangisidir?',
    options: [
      'Vücut ısısının kaç derece olduğu',
      'Cilt renginin tonu',
      'Yaralının yaşı',
      'Solunumun (nefes alıp vermenin) olup olmadığı',
    ],
    answerIndex: 3,
    explanation:
      'Bilinci kapalı yaralıda önce hava yolu açılır ve solunumun olup olmadığı değerlendirilir; solunum yoksa temel yaşam desteğine başlanır. Yaşamsal öncelik solunum ve dolaşımdır.',
    whyWrong: [
      'Vücut ısısı ve cilt rengi ikincil bulgulardır.',
      'Yaralının yaşı hayati işlevlerin kontrolünden önce gelmez.',
    ],
    objective: 'Bilinci kapalı yaralıda önceliği solunuma vermek.',
    tags: ['bilinc', 'solunum', 'oncelik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-221',
    subject: 'ilkyardim',
    topic: 'tyd',
    difficulty: 'orta',
    stem: 'Bilinci kapalı bir yaralıda hava yolunu açmak için genellikle uygulanan temel yöntem hangisidir?',
    options: [
      'Baş öne, çeneye doğru bükülür',
      'Ağza sürekli üflenir',
      'Baş hafifçe geriye itilip çene yukarı kaldırılır',
      'Boyun sağa sola çevrilir',
    ],
    answerIndex: 2,
    explanation:
      'Hava yolunu açmanın temel yöntemi başın hafifçe geriye itilip çenenin yukarı kaldırılmasıdır; bu, geriye kaçan dilin hava yolunu tıkamasını önler.',
    whyWrong: [
      'Başı öne bükmek hava yolunu daraltır.',
      'Boynu sağa sola çevirmek omurga yaralısında tehlikelidir ve hava yolunu açmaz.',
    ],
    objective: 'Baş-çene pozisyonu ile hava yolu açmayı bilmek.',
    tags: ['tyd', 'hava-yolu', 'pozisyon'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-222',
    subject: 'ilkyardim',
    topic: 'bayilma',
    difficulty: 'kolay',
    stem: 'Aniden bayılıp yere düşen ancak solunumu düzgün olan bir kişiye ilk yardım olarak ne yapılır?',
    options: [
      'Hemen ayağa kaldırılıp yürütülür',
      'Yüzüne tokat atılır',
      'Ağzına yiyecek verilir',
      'Sırtüstü yatırılıp bacakları hafifçe yukarı kaldırılır',
    ],
    answerIndex: 3,
    explanation:
      'Bayılan kişi sırtüstü yatırılıp bacakları hafifçe yükseltilerek beyne kan akışı desteklenir; sıkan giysiler gevşetilir ve ortam havalandırılır. Genellikle kısa sürede kendine gelir.',
    whyWrong: [
      'Kişiyi ayağa kaldırmak yeniden bayılmaya yol açabilir.',
      'Bilinci tam yerine gelmeden yiyecek vermek boğulmaya neden olabilir.',
    ],
    objective: 'Bayılmada doğru pozisyonu uygulamak.',
    tags: ['bayilma', 'pozisyon', 'dolasim'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-223',
    subject: 'ilkyardim',
    topic: 'kalp-krizi',
    difficulty: 'orta',
    stem: 'Göğsünde baskı ve sıkışma tarzında şiddetli ağrı olan, ağrısı sol kola yayılan bir kişide öncelikle hangisinden şüphelenilir?',
    options: ['Kas tutulması', 'Kalp krizi', 'Basit yorgunluk', 'Göz yorgunluğu'],
    answerIndex: 1,
    explanation:
      'Göğüste sıkışma-baskı tarzı ağrının sol kola, boyna veya çeneye yayılması, terleme ve nefes darlığıyla birlikte kalp krizini düşündürür; vakit kaybetmeden 112 aranır.',
    whyWrong: [
      'Bu belirti örüntüsü basit kas tutulması veya yorgunlukla açıklanamaz.',
      'Göz yorgunluğunun göğüs ağrısıyla ilgisi yoktur.',
    ],
    objective: 'Kalp krizi belirtilerini tanımak.',
    tags: ['kalp-krizi', 'gogus-agrisi', 'belirti'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-224',
    subject: 'ilkyardim',
    topic: 'kalp-krizi',
    difficulty: 'kolay',
    stem: 'Kalp krizi geçirdiğinden şüphelenilen bilinci açık bir kişiye ilk yardımda ne yapılır?',
    options: [
      'Koşturularak hastaneye götürülür',
      'Rahat edeceği (yarı oturur) pozisyonda hareketsiz tutulup 112 aranır',
      'Ağır egzersiz yaptırılır',
      'Sırtüstü düz yatırılıp bekletilerek hiçbir yere haber verilmez',
    ],
    answerIndex: 1,
    explanation:
      'Kalp krizi şüphesinde kişi rahat edeceği yarı oturur pozisyonda hareketsiz tutulur, sıkan giysileri gevşetilir ve hiç vakit kaybetmeden 112 aranır; eforu artıracak hareketlerden kaçınılır.',
    whyWrong: [
      'Koşturmak veya efor yaptırmak kalbin yükünü artırır.',
      'Haber vermeden beklemek hayati zaman kaybına yol açar.',
    ],
    objective: 'Kalp krizinde doğru pozisyon ve çağrıyı uygulamak.',
    tags: ['kalp-krizi', 'pozisyon', '112'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-225',
    subject: 'ilkyardim',
    topic: 'felc',
    difficulty: 'orta',
    stem: 'Yüzünün bir yanı kayan, bir kolunu kaldıramayan ve konuşması bozulan bir kişide öncelikle hangisinden şüphelenilmelidir?',
    options: [
      'Beyin damar tıkanıklığı (inme/felç)',
      'Basit baş ağrısı',
      'Kas krampı',
      'Diş ağrısı',
    ],
    answerIndex: 0,
    explanation:
      'Yüzde asimetri (kayma), bir kolda ani güçsüzlük ve konuşma bozukluğunun birlikte görülmesi inme (felç) belirtisidir; bu üç bulgu tanınır tanınmaz derhal 112 aranmalıdır.',
    whyWrong: [
      'Basit baş ağrısında yüz kayması ve kolda güçsüzlük görülmez.',
      'Kas krampı veya diş ağrısı bu belirti kümesini açıklamaz.',
    ],
    objective: 'İnme belirtilerini (yüz-kol-konuşma) tanımak.',
    tags: ['felc', 'inme', 'belirti'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-226',
    subject: 'ilkyardim',
    topic: 'kanama',
    difficulty: 'kolay',
    stem: 'Darbe olmaksızın başlayan bir burun kanamasında ilk yardım olarak ne yapılır?',
    options: [
      'Baş iyice geriye atılır',
      'Buruna sürekli su verilir',
      'Kişi hızlıca koşturulur',
      'Baş öne eğilip burun kanatları birkaç dakika parmakla sıkılır',
    ],
    answerIndex: 3,
    explanation:
      'Burun kanamasında kişi öne doğru eğilir ve burun kanatları başparmak-işaret parmağıyla birkaç dakika sıkılır; öne eğilmek kanın boğaza kaçıp yutulmasını veya soluk borusuna gitmesini önler.',
    whyWrong: [
      'Başı geriye atmak kanın boğaza akmasına ve mideyi bulandırmasına yol açar.',
      'Koşturmak ve buruna su vermek kanamayı durdurmaz.',
    ],
    objective: 'Burun kanamasında doğru baş pozisyonunu uygulamak.',
    tags: ['kanama', 'burun', 'baski'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-227',
    subject: 'ilkyardim',
    topic: 'donma',
    difficulty: 'orta',
    stem: 'Soğukta uzun süre kalmış, el ve ayakları donma belirtisi gösteren bir kişide hangisi yapılmamalıdır?',
    options: [
      'Kişiyi ılık bir ortama almak',
      'Islak giysilerini çıkarmak',
      'Donmuş bölgeyi kar veya elle sertçe ovmak',
      'Üzerini kuru örtülerle örtmek',
    ],
    answerIndex: 2,
    explanation:
      'Donmuş bölge ovulmaz; ovmak zaten hasarlı dokulara ek zarar verir. Kişi ılık ortama alınır, ıslak giysileri çıkarılıp kuru örtülerle sarılır ve yavaşça ısıtılır.',
    whyWrong: [
      'Kişiyi ılık ortama almak ve ıslak giysileri çıkarmak doğru uygulamalardır.',
      'Kuru örtülerle örtmek ısı kaybını azaltır.',
    ],
    objective: 'Donmada ovmama ilkesini kavramak.',
    tags: ['donma', 'yanlis-uygulama', 'isitma'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-228',
    subject: 'ilkyardim',
    topic: 'donma',
    difficulty: 'orta',
    stem: 'Vücut ısısının tehlikeli biçimde düştüğü hipotermide sık görülen belirtilerden biri hangisidir?',
    options: [
      'Ateşin yükselip ciltte kızarıklık',
      'Yoğun terleme ve susuzluk',
      'İştahın belirgin artması',
      'Titreme, hâlsizlik ve giderek uyuklama hâli',
    ],
    answerIndex: 3,
    explanation:
      'Hipotermide vücut ısınmaya çalışırken titreme, ardından hâlsizlik, uyuşukluk ve uyku hâli görülür; ilerledikçe bilinç bulanır. Kişi sıcak ortama alınıp yavaşça ısıtılmalıdır.',
    whyWrong: [
      'Ateş yükselmesi ve kızarıklık hipoterminin değil aksi durumun bulgusudur.',
      'Yoğun terleme ve iştah artışı hipotermi belirtisi değildir.',
    ],
    objective: 'Hipotermi belirtilerini tanımak.',
    tags: ['donma', 'hipotermi', 'belirti'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-229',
    subject: 'ilkyardim',
    topic: 'zehirlenme',
    difficulty: 'orta',
    stem: 'Kapalı bir garajda egzoz gazından (karbonmonoksit) etkilenmiş bir kişiye ilk yapılması gereken nedir?',
    options: [
      'Kişiye bol su içirilir',
      'Kişi olduğu yerde bekletilir',
      'Kişi hemen temiz havaya / açık alana çıkarılır',
      'Kişiye kusturucu verilir',
    ],
    answerIndex: 2,
    explanation:
      'Solunum yoluyla zehirlenmede öncelik, ortamın güvenliği sağlanarak kişinin derhal temiz havaya çıkarılmasıdır; ardından bilinç ve solunum değerlendirilir ve 112 aranır.',
    whyWrong: [
      'Su içirmek veya kusturmak solunum yoluyla zehirlenmede öncelikli değildir.',
      'Kişiyi gazlı ortamda bekletmek zehirlenmeyi ağırlaştırır.',
    ],
    objective: 'Solunum yoluyla zehirlenmede temiz hava önceliğini kavramak.',
    tags: ['zehirlenme', 'karbonmonoksit', 'temiz-hava'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-230',
    subject: 'ilkyardim',
    topic: 'zehirlenme',
    difficulty: 'kolay',
    stem: 'Bir maddeyle zehirlendiğinden şüphelenilen kişide ilk yardımcının 112 için hazırlaması gereken bilgi hangisidir?',
    options: [
      'Kişinin en sevdiği renk',
      'Evin kaç odalı olduğu',
      'Kişinin ayakkabı numarası',
      'Alınan maddenin ne olduğu, miktarı ve ne zaman alındığı',
    ],
    answerIndex: 3,
    explanation:
      'Zehirlenmede tedaviyi yönlendirmek için maddenin cinsi, alınan miktar ve alınma zamanı önemlidir; mümkünse ambalajı saklanır ve sağlık ekibine bu bilgiler iletilir.',
    whyWrong: [
      'Renk tercihi gibi bilgiler tıbbi açıdan gereksizdir.',
      'Evin oda sayısı ve ayakkabı numarası zehirlenme yönetimiyle ilgisizdir.',
    ],
    objective: 'Zehirlenmede toplanacak bilgileri belirlemek.',
    tags: ['zehirlenme', 'bilgi', '112'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-231',
    subject: 'ilkyardim',
    topic: 'elektrik-carpmasi',
    difficulty: 'orta',
    stem: 'Elektrik akımına kapılmış ve hâlâ akımla temas hâlinde olan bir kişiye müdahaleden önce ne yapılmalıdır?',
    options: [
      'Kişiye çıplak elle dokunulur',
      'Önce elektrik akımı kesilir veya güvenli şekilde temas sonlandırılır',
      'Kişinin üzerine su dökülür',
      'Kişi hemen sarsılır',
    ],
    answerIndex: 1,
    explanation:
      'Elektrik çarpmasında ilk yardımcı, akım kesilmeden ya da kişi iletken olmayan bir cisimle temastan ayrılmadan asla dokunmamalıdır; aksi hâlde kendisi de akıma kapılır.',
    whyWrong: [
      'Çıplak elle dokunmak yardımcının da çarpılmasına yol açar.',
      'Su dökmek elektriği ilettiği için tehlikeyi artırır.',
    ],
    objective: 'Elektrik çarpmasında önce akımı kesme ilkesini kavramak.',
    tags: ['elektrik-carpmasi', 'guvenlik', 'olay-yeri'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-232',
    subject: 'ilkyardim',
    topic: 'elektrik-carpmasi',
    difficulty: 'kolay',
    stem: 'Yere düşmüş yüksek gerilim hattının yakınında yaralı bulunduğunda ilk yardımcının tutumu ne olmalıdır?',
    options: [
      'Hemen hatta ve yaralıya koşarak yaklaşmak',
      'Hattı elle kenara itmek',
      'Yaralıyı ıslak bir bezle çekmek',
      'Güvenli mesafede kalıp yetkililere ve 112ye haber vermek',
    ],
    answerIndex: 3,
    explanation:
      'Yüksek gerilim hattı yere düştüğünde çevrede adım gerilimi tehlikesi vardır; ilk yardımcı güvenli mesafede kalır, kimseyi yaklaştırmaz ve derhal yetkililer ile 112ye haber verir.',
    whyWrong: [
      'Hatta yaklaşmak veya elle itmek ölümcül elektrik çarpmasına yol açar.',
      'Islak bez elektriği ilettiği için güvenli değildir.',
    ],
    objective: 'Yüksek gerilimde güvenli mesafe ilkesini kavramak.',
    tags: ['elektrik-carpmasi', 'yuksek-gerilim', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-233',
    subject: 'ilkyardim',
    topic: 'hayvan-isirigi',
    difficulty: 'kolay',
    stem: 'Bir köpek tarafından ısırılan ve kanayan bir kişide ilk yardım olarak ne yapılır?',
    options: [
      'Yara hiç yıkanmadan kapatılır',
      'Yaraya toprak sürülür',
      'Yara bol su ve sabunla yıkanıp temiz bezle örtülür, sağlık kuruluşuna başvurulur',
      'Yara emilerek temizlenmeye çalışılır',
    ],
    answerIndex: 2,
    explanation:
      'Isırık yarası bol su ve sabunla yıkanarak mikrop yükü azaltılır, temiz bezle örtülür ve kuduz ile tetanoz açısından değerlendirilmek üzere mutlaka sağlık kuruluşuna başvurulur.',
    whyWrong: [
      'Yarayı yıkamadan kapatmak enfeksiyon riskini artırır.',
      'Yaraya toprak sürmek tetanoz gibi ciddi tehlikeler doğurur.',
    ],
    objective: 'Hayvan ısırığında yara temizliği ve başvuru gereğini kavramak.',
    tags: ['hayvan-isirigi', 'yara', 'enfeksiyon'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-234',
    subject: 'ilkyardim',
    topic: 'hayvan-isirigi',
    difficulty: 'orta',
    stem: 'Yılan tarafından koldan ısırılan bir kişide aşağıdakilerden hangisi doğru yaklaşımdır?',
    options: [
      'Isırık bölgesini kesip zehri emmek',
      'Isırılan kolu bol bol hareket ettirmek',
      'Kişiyi sakinleştirip ısırılan bölgeyi hareketsiz tutmak ve 112yi aramak',
      'Bölgeye çok sıkı turnike bağlayıp koşturmak',
    ],
    answerIndex: 2,
    explanation:
      'Yılan ısırığında kişi sakinleştirilir, ısırılan bölge kalp seviyesinin altında ve hareketsiz tutularak zehrin yayılımı yavaşlatılır ve derhal 112 aranır; kesme ve emme gibi yöntemler zarar verir.',
    whyWrong: [
      'Isırığı kesip emmek doku hasarını ve enfeksiyonu artırır.',
      'Bölgeyi hareket ettirmek zehrin daha hızlı yayılmasına yol açar.',
    ],
    objective: 'Yılan ısırığında hareketsizlik ve 112 ilkesini uygulamak.',
    tags: ['hayvan-isirigi', 'yilan', 'hareketsizlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-235',
    subject: 'ilkyardim',
    topic: 'goz-yaralanmasi',
    difficulty: 'orta',
    stem: 'Gözüne temizlik kimyasalı (asit/baz) sıçrayan bir kişiye ilk yardım olarak ne yapılır?',
    options: [
      'Göz kuru bezle ovularak silinir',
      'Göze göz damlası dışında merhem sürülür',
      'Göz bol ve temiz suyla uzun süre yıkanır',
      'Göz kapatılıp beklenir',
    ],
    answerIndex: 2,
    explanation:
      'Göze kimyasal sıçradığında göz, temiz akan suyla en az on beş dakika, göz kapakları açık tutularak bolca yıkanır; bu, kimyasalın seyreltilip uzaklaştırılmasını sağlar. Ardından sağlık kuruluşuna gidilir.',
    whyWrong: [
      'Gözü ovmak kimyasalı dokuya daha çok yayar ve hasarı artırır.',
      'Yıkamadan bekleyip merhem sürmek yanığı derinleştirir.',
    ],
    objective: 'Kimyasal göz yaralanmasında bol su ile yıkamayı uygulamak.',
    tags: ['goz-yaralanmasi', 'kimyasal', 'yikama'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-236',
    subject: 'ilkyardim',
    topic: 'goz-yaralanmasi',
    difficulty: 'zor',
    stem: 'Gözüne metal bir cisim batıp saplanmış bir yaralıya ilk yardımda ne yapılmalıdır?',
    options: [
      'Batan cisim elle çekilip çıkarılır',
      'Göz bastırılarak cisim içeri itilir',
      'Göz sürekli ovulur',
      'Göze soğuk su tutularak cisim akıtılmaya çalışılır',
      'Cisim yerinde bırakılır, göz sabitlenip yaralı sağlık kuruluşuna götürülür',
    ],
    answerIndex: 4,
    explanation:
      'Göze saplanan cisim asla çıkarılmaya çalışılmaz; oynatmak ek hasara ve görme kaybına yol açabilir. Cisim olduğu yerde sabitlenir, göze bası yapılmadan desteklenir ve yaralı hızla sağlık kuruluşuna götürülür.',
    whyWrong: [
      'Batan cismi çekmek veya suyla akıtmaya çalışmak göz yapısına kalıcı zarar verebilir.',
      'Gözü bastırmak veya ovmak yaralanmayı ağırlaştırır.',
    ],
    objective: 'Saplanan cismin çıkarılmaması ilkesini kavramak.',
    tags: ['goz-yaralanmasi', 'sabitleme', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-237',
    subject: 'ilkyardim',
    topic: 'burkulma',
    difficulty: 'kolay',
    stem: 'Ayak bileğini burkan ve şişme başlayan bir kişide ilk yardım olarak hangisi uygundur?',
    options: [
      'Bölge hemen sıcak suya sokulur',
      'Kişi burkulan ayağıyla yürütülür',
      'Bölge kuvvetlice ovulur',
      'Bölge dinlendirilip üzerine soğuk uygulama yapılır ve ayak yükseltilir',
    ],
    answerIndex: 3,
    explanation:
      'Burkulmada bölge dinlendirilir, ilk saatlerde soğuk uygulama ile şişme ve ağrı azaltılır, ayak yükseltilir ve gerekirse elastik bandajla desteklenir. Bu, doku hasarını ve ödemi sınırlar.',
    whyWrong: [
      'Erken dönemde sıcak uygulama şişmeyi ve kanamayı artırır.',
      'Burkulan ayakla yürümek ve bölgeyi ovmak yaralanmayı ağırlaştırır.',
    ],
    objective: 'Burkulmada soğuk uygulama ve yükseltmeyi kavramak.',
    tags: ['burkulma', 'soguk', 'sisme'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-238',
    subject: 'ilkyardim',
    topic: 'tyd',
    difficulty: 'zor',
    stem: 'Bir bebekte (0-1 yaş) dış kalp masajı erişkine göre hangi teknikle uygulanır?',
    options: [
      'Tek elin topuğuyla tüm ağırlıkla bastırarak',
      'İki parmak ucuyla göğüs kemiğine daha hafif ve sığ bastırarak',
      'İki elin topuğuyla derin bastırarak',
      'Yumrukla vurarak',
    ],
    answerIndex: 1,
    explanation:
      'Bebekte kalp masajı, göğüs kemiğinin alt yarısına iki parmak ucuyla, erişkine göre daha az derinlikte ve daha nazik biçimde uygulanır; bebeğin küçük yapısı erişkin tekniğine uygun değildir.',
    whyWrong: [
      'Tek veya iki elin topuğuyla derin bası bebekte iç organ hasarına yol açar.',
      'Yumrukla vurmak hiçbir yaşta uygun bir teknik değildir.',
    ],
    objective: 'Bebekte kalp masajı tekniğini erişkinden ayırt etmek.',
    tags: ['tyd', 'bebek', 'kalp-masaji'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-239',
    subject: 'ilkyardim',
    topic: 'olay-yeri',
    difficulty: 'orta',
    stem: 'İlk yardımın temel amaçlarından biri aşağıdakilerden hangisidir?',
    options: [
      'Yaralıya kesin tıbbi teşhis koymak',
      'Ameliyat gibi tıbbi işlemleri yapmak',
      'Yaralıya ilaç reçetesi yazmak',
      'Yaralıya laboratuvar tetkiki uygulamak',
      'Durumun kötüleşmesini önleyip yaşamsal işlevleri korumak ve iyileşmeyi kolaylaştırmak',
    ],
    answerIndex: 4,
    explanation:
      'İlk yardımın amacı; hayat kurtarmak, durumun daha kötüye gitmesini önlemek ve iyileşme sürecini kolaylaştırmaktır. Teşhis, ameliyat, tetkik ve ilaç yazma gibi işlemler sağlık personelinin görevidir.',
    whyWrong: [
      'Teşhis koymak, reçete yazmak ve tetkik uygulamak ilk yardımın değil hekimin görevidir.',
      'Ameliyat gibi tıbbi işlemler ilk yardım kapsamı dışındadır.',
    ],
    objective: 'İlk yardımın temel amaçlarını kavramak.',
    tags: ['olay-yeri', 'amac', 'tanim'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-240',
    subject: 'ilkyardim',
    topic: 'tyd',
    difficulty: 'orta',
    stem: 'Bir kişinin solunumunun olup olmadığını değerlendirmek için kullanılan yöntem hangisidir?',
    options: [
      'Nabzını uzun süre ölçmek',
      'Göğüs hareketine bakıp, nefesi dinleyip yanakta hissetmeye çalışmak',
      'Kan basıncını ölçmek',
      'Ateşine bakmak',
    ],
    answerIndex: 1,
    explanation:
      'Solunum kontrolünde göğüs kafesinin inip kalkmasına bakılır, nefes sesi dinlenir ve çıkan hava yanakta hissedilmeye çalışılır; bu değerlendirme yaklaşık on saniye içinde yapılır.',
    whyWrong: [
      'Kan basıncı ve ateş ölçümü solunumun varlığını göstermez.',
      'Yalnızca nabzı uzun süre ölçmek solunum değerlendirmesinin yerini tutmaz.',
    ],
    objective: 'Solunum kontrolünde bak-dinle-hisset yöntemini uygulamak.',
    tags: ['tyd', 'solunum', 'degerlendirme'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
];
