/**
 * ÖZGÜN araç tekniği soruları (Sprint 3 genişletme). ROADMAP C.4/E.6.
 * Kaynak = resmî MEB/ODSGM araç tekniği müfredatı; KENDİ İFADEMİZLE. review: 'draft'.
 */
import type { Question } from '@ea/content-schema';

const SRC = 'Resmî MEB/ODSGM araç tekniği müfredatı (özgün ifade)';

export const MOTOR_QUESTIONS: Question[] = [
  {
    id: 'motor-101',
    subject: 'motor',
    topic: 'yaglama',
    difficulty: 'kolay',
    stem: 'Zamanında değiştirilmeyen ve özelliğini yitirmiş motor yağı motorda hangi sonuca yol açar?',
    options: [
      'Yakıt tüketimini kalıcı biçimde azaltarak motorun gücünü belirgin şekilde yükseltir',
      'Motorun daha sessiz çalışmasını ve titreşiminin azalmasını sağlar',
      'Yağlama görevini yapamadığı için sürtünme ve aşınma artar, motor ömrü kısalır',
      'Akünün daha hızlı şarj olmasını ve ömrünün uzamasını sağlar',
    ],
    answerIndex: 2,
    explanation:
      'Eskiyen ve kirlenen motor yağı özelliğini kaybederek parçalar arasında koruyucu film oluşturamaz; sürtünme ve aşınma artar, motorun ömrü kısalır. Bu yüzden yağ, üreticinin öngördüğü aralıklarda değiştirilmelidir.',
    whyWrong: [
      'Eski yağ yakıt tüketimini azaltmaz; artan sürtünme tüketimi yükseltebilir.',
      'Yağlama azaldığında motor daha gürültülü çalışır, sessizleşmez.',
      'Motor yağının akü şarjıyla ilgisi yoktur; aküyü alternatör şarj eder.',
    ],
    objective:
      'Yağ değişiminin geciktirilmesinin sürtünme, aşınma ve motor ömrüne etkisini kavramak.',
    tags: ['motor-yagi', 'yag-degisimi', 'asinma'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-102',
    subject: 'motor',
    topic: 'yaglama',
    difficulty: 'orta',
    stem: 'Sürüş sırasında yağ basıncı ikaz lambası (yağdanlık şekli) kırmızı yanarsa ne yapılmalıdır?',
    options: [
      'Motor devrini yükselterek yağ basıncının artmasını sağlamak',
      'Uyarıyı görmezden gelip yolculuğa aynı şekilde devam etmek',
      'Aracı güvenli yerde durdurup motoru durdurmak',
      'Klimayı kapatıp motor yükünü azaltarak yola devam etmek',
    ],
    answerIndex: 2,
    explanation:
      'Yağ basıncı ikazı yağlamanın yetersiz olduğunu gösterir; yağsız çalışan motor kısa sürede zarar görür. Araç en kısa sürede güvenli bir yerde durdurulmalı, motor durdurulup seviye kontrol edilmelidir.',
    whyWrong: [
      'Motoru yağsız zorlamak sarma/tutukluk gibi kalıcı hasara yol açar.',
      'İkazı görmezden gelmek motorun büyük onarım gerektirmesine neden olabilir.',
    ],
    objective: 'Yağ basıncı ikazına doğru ve güvenli tepki vermeyi öğrenmek.',
    tags: ['yaglama', 'ikaz-lambasi', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-103',
    subject: 'motor',
    topic: 'fren',
    difficulty: 'orta',
    stem: 'ABS (kilitlenmeyi önleyici fren sistemi) ani ve sert frende sürücüye hangi avantajı sağlar?',
    options: [
      'Fren mesafesini her yol koşulunda ve her zeminde yarı yarıya kısaltır',
      'Yakıt tüketimini azaltıp motorun daha verimli çalışmasını sağlar',
      'Motor gücünü artırıp aracın daha çabuk hızlanmasını sağlar',
      'Tekerlek kilitlenmesini önleyip direksiyon hakimiyetini korur',
    ],
    answerIndex: 3,
    explanation:
      'ABS, sert frende tekerleklerin kilitlenip kaymasını önler; böylece sürücü fren yaparken direksiyon hakimiyetini koruyarak engelden kaçınabilir.',
    whyWrong: [
      'ABS her koşulda fren mesafesini yarıya indirmez; asıl amacı yön hakimiyetidir.',
      'Yakıt tüketimi ve motor gücüyle doğrudan bir ilişkisi yoktur.',
    ],
    objective: 'ABS sisteminin kilitlenmeyi önleme ve yön hakimiyeti işlevini kavramak.',
    tags: ['fren', 'abs', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-104',
    subject: 'motor',
    topic: 'fren',
    difficulty: 'kolay',
    stem: 'Fren balatalarının zamanla aşınması durumunda ortaya çıkan sonuç aşağıdakilerden hangisidir?',
    options: [
      'Frenleme performansı düşer ve fren mesafesi uzayabilir',
      'Motor daha sessiz çalışır ve titreşimi azalır',
      'Lastik ömrü uzar ve diş aşınması yavaşlar',
      'Direksiyon kendiliğinden ağırlaşır ve manevralar zorlaşır',
    ],
    answerIndex: 0,
    explanation:
      'Aşınan balatalar diske/kampanaya yeterince baskı uygulayamaz; bu da frenleme gücünü azaltır ve fren mesafesini uzatarak güvenliği tehlikeye atar.',
    whyWrong: [
      'Balata aşınmasının motor sesi ile ilgisi yoktur.',
      'Lastik ömrü fren balatasının aşınmasına bağlı değildir.',
    ],
    objective: 'Fren balatası aşınmasının frenleme güvenliğine etkisini anlamak.',
    tags: ['fren', 'balata', 'bakim'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-105',
    subject: 'motor',
    topic: 'aku',
    difficulty: 'kolay',
    stem: 'Araç aküsünün temel görevi aşağıdakilerden hangisidir?',
    options: [
      'Motoru soğutup çalışma sıcaklığını dengede tutmak',
      'Elektrik enerjisini depolamak ve marş anında sisteme akım vermek',
      'Yakıtı depodan alıp motora basınçla pompalamak',
      'Egzoz gazındaki zararlı maddeleri süzerek temizlemek ve salınımı azaltmak',
    ],
    answerIndex: 1,
    explanation:
      'Akü, kimyasal enerjiyi elektrik enerjisi olarak depolar; özellikle marş anında marş motoruna ve elektrikli donanımlara akım sağlar.',
    whyWrong: [
      'Motoru soğutma görevi soğutma sistemine (radyatör/su) aittir.',
      'Yakıt pompalama görevi yakıt pompasına aittir.',
    ],
    objective: 'Akünün elektrik enerjisi depolama işlevini kavramak.',
    tags: ['aku', 'elektrik', 'mars'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-106',
    subject: 'motor',
    topic: 'elektrik',
    difficulty: 'orta',
    stem: 'Motor çalışırken akünün sürekli şarj edilmesini sağlayan parça hangisidir?',
    options: [
      'Marş motoru (marş dinamosu)',
      'Enjektör (püskürtme memesi)',
      'Alternatör (şarj dinamosu)',
      'Termostat',
    ],
    answerIndex: 2,
    explanation:
      'Alternatör, motor çalışırken kayışla döndürülerek elektrik üretir; bu enerjiyle hem araç sistemini besler hem de aküyü şarj eder.',
    whyWrong: [
      'Marş motoru aküden akım alarak motoru ilk çalıştırır; şarj üretmez.',
      'Enjektör yakıt püskürtür, termostat soğutma sıcaklığını ayarlar.',
    ],
    objective: 'Alternatörün akü şarjındaki rolünü öğrenmek.',
    tags: ['elektrik', 'alternator', 'sarj'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-107',
    subject: 'motor',
    topic: 'sogutma',
    difficulty: 'orta',
    stem: 'Soğutma sistemine antifriz eklenmesinin temel amacı nedir?',
    options: [
      'Yakıt tüketimini azaltıp deponun daha uzun süre dayanmasını sağlamak',
      'Motor yağını temizleyip içindeki kurumu tutmak',
      'Lastiklerin iç basıncını mevsime göre kendiliğinden ayarlamak',
      'Soğutma suyunun kışın donmasını ve yazın aşırı ısınmasını önlemek',
    ],
    answerIndex: 3,
    explanation:
      'Antifriz, soğutma suyunun donma sıcaklığını düşürür ve kaynama sıcaklığını yükseltir; böylece kışın donmayı, sıcakta ise erken kaynamayı önleyerek motoru korur.',
    whyWrong: [
      'Antifrizin yakıt tüketimi üzerinde doğrudan etkisi yoktur.',
      'Motor yağını temizleme görevi yağ ve yağ filtresine aittir.',
    ],
    objective: 'Antifrizin donmayı ve hararet oluşumunu önleme işlevini anlamak.',
    tags: ['sogutma', 'antifriz', 'donma'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-108',
    subject: 'motor',
    topic: 'sogutma',
    difficulty: 'kolay',
    stem: 'Su soğutmalı bir motorda soğutma suyunun görevi aşağıdakilerden hangisidir?',
    options: [
      'Motorun aşırı ısınmasını önleyip sıcaklığı dengede tutmak',
      'Fren devresindeki basıncı artırıp fren gücünü yükseltmek',
      'Farların parlaklığını sabit tutup gece görüşünü artırmak',
      'Yakıt-hava karışımını ateşleyip yanmayı başlatmak ve gücü üretmek',
    ],
    answerIndex: 0,
    explanation:
      'Soğutma suyu, yanma sırasında oluşan ısıyı motordan alıp radyatöre taşır ve dışarı atar; böylece motor uygun çalışma sıcaklığında tutulur.',
    whyWrong: [
      'Frenleme gücü hidrolik fren sistemiyle sağlanır.',
      'Farlar elektrik sistemiyle çalışır, soğutma suyu ile ilgisi yoktur.',
    ],
    objective: 'Soğutma suyunun motoru soğutma işlevini kavramak.',
    tags: ['sogutma', 'radyator', 'sicaklik'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-109',
    subject: 'motor',
    topic: 'hararet',
    difficulty: 'orta',
    stem: 'Gösterge panelinde hararet (motor sıcaklığı) ikazı yanıp motor aşırı ısındığında ilk yapılması gereken nedir?',
    options: [
      'Hızı artırıp hava akımıyla motoru soğutmaya çalışmak',
      'Radyatör kapağını hemen açıp içine soğuk su eklemek',
      'Klimayı açıp motor yükünü azaltarak yola devam etmek',
      'Aracı güvenli bir yere çekip motoru durdurmak',
    ],
    answerIndex: 3,
    explanation:
      'Hararet ikazında motor aşırı ısınmıştır; araç güvenli bir yere çekilip motor durdurulmalı ve soğuması beklenmelidir. Aksi hâlde motorda ciddi hasar oluşabilir.',
    whyWrong: [
      'Hızı artırmak ısınmayı daha da artırarak motoru zorlar.',
      'Sıcak motorda radyatör kapağı açılmaz; basınçlı sıcak su fışkırıp yanığa yol açabilir.',
    ],
    objective: 'Hararet durumunda güvenli ve doğru davranışı öğrenmek.',
    tags: ['hararet', 'sogutma', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-110',
    subject: 'motor',
    topic: 'hararet',
    difficulty: 'zor',
    stem: 'Motor aşırı ısınıp hararet yaptığında radyatör kapağıyla ilgili doğru davranış hangisidir?',
    options: [
      'Motor sıcakken kapağı hemen açıp soğuk su dökmek',
      'Motor soğuyana kadar beklemeden kapağı zorlamak gerekir',
      'Motor yeterince soğumadan kapak kesinlikle açılmaz',
      'Kapak açıksa motor daha hızlı soğur, o yüzden hep açık tutulmalıdır',
    ],
    answerIndex: 2,
    explanation:
      'Soğutma sistemi basınçlı ve çok sıcaktır. Motor soğumadan radyatör kapağı açılırsa fışkıran sıcak su ve buhar ciddi yanıklara neden olabilir; bu nedenle motorun soğuması beklenir. Basınçlı sıcak su yanığa yol açabilir.',
    whyWrong: [
      'Sıcak motora soğuk su dökmek metalde çatlama/deformasyona yol açabilir.',
      'Kapağı zorlamak basınçlı sıcak suyun fışkırmasına ve yanığa sebep olur.',
    ],
    objective: 'Sıcak motorda radyatör kapağının açılmamasının güvenlik gerekçesini kavramak.',
    tags: ['hararet', 'radyator', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-111',
    subject: 'motor',
    topic: 'lastik',
    difficulty: 'kolay',
    stem: 'Lastiklerin güvenli sürüş açısından düzenli kontrol edilmesi gereken özellikleri hangileridir?',
    options: ['Renk ve marka', 'Diş (sırt)', 'Jant çapı ve göbek kapağı', 'Yalnızca üretim yılı'],
    answerIndex: 1,
    explanation:
      'Yeterli diş derinliği yol tutuşunu ve suyu tahliyeyi sağlar; doğru hava basıncı ise dengeli aşınma, güvenli frenleme ve yol tutuşu için gereklidir. İkisi de güvenliği doğrudan etkiler.',
    whyWrong: [
      'Renk ve marka sürüş güvenliğinin belirleyicisi değildir.',
      'Yalnızca üretim yılına bakmak, aşınma ve basınç durumunu göstermez.',
    ],
    objective: 'Lastikte diş derinliği ve hava basıncının güvenlik önemini kavramak.',
    tags: ['lastik', 'dis-derinligi', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-112',
    subject: 'motor',
    topic: 'lastik',
    difficulty: 'orta',
    stem: 'Rot ve balans ayarının bozuk olması aşağıdakilerden hangisine yol açar?',
    options: [
      'Lastiklerin düzensiz/erken aşınmasına ve direksiyonda titremeye',
      'Yakıt deposunun beklenenden hızlı boşalmasına ve tüketimin sabitlenmesine',
      'Akünün daha çabuk şarj olmasına ve marşın güçlenmesine',
      'Egzoz sesinin kısılmasına ve motorun sessizleşmesine',
    ],
    answerIndex: 0,
    explanation:
      'Rot ayarı bozuksa lastikler bir taraftan düzensiz aşınır; balans bozuksa özellikle yüksek hızda direksiyonda titreme oluşur. Her ikisi de lastik ömrünü ve sürüş konforunu olumsuz etkiler.',
    whyWrong: [
      'Rot balans ayarının yakıt deposu doldurma ile ilgisi yoktur.',
      'Akü şarjı alternatöre bağlıdır, rot balans ile değişmez.',
    ],
    objective: 'Rot balans ayarının lastik aşınmasına etkisini anlamak.',
    tags: ['lastik', 'rot-balans', 'asinma'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-113',
    subject: 'motor',
    topic: 'aktarma',
    difficulty: 'orta',
    stem: 'Motorda üretilen hareketi tekerleklere ileten sisteme genel olarak ne ad verilir?',
    options: ['Soğutma sistemi', 'Yakıt sistemi', 'Aktarma organları', 'Aydınlatma sistemi'],
    answerIndex: 2,
    explanation:
      'Debriyaj, şanzıman, şaft ve diferansiyel gibi parçalardan oluşan aktarma organları, motorun ürettiği gücü tekerleklere iletir.',
    whyWrong: [
      'Soğutma sistemi ısıyı uzaklaştırır, güç iletmez.',
      'Yakıt sistemi motora yakıt sağlar; hareketi tekerleğe iletmez.',
    ],
    objective: 'Aktarma organlarının gücü tekerleğe iletme işlevini kavramak.',
    tags: ['aktarma', 'guc-iletimi', 'sanziman'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-114',
    subject: 'motor',
    topic: 'debriyaj',
    difficulty: 'orta',
    stem: 'Debriyajın (kavrama) temel görevi aşağıdakilerden hangisidir?',
    options: [
      'Motorun ürettiği ısıyı dışarı atıp soğutmak',
      'Yakıt basıncını ayarlayıp enjektörlere iletmek',
      'Aküyü şarj edip elektrik sistemini beslemek ve akımı dengelemek',
      'Motor gücünü şanzımana bağlayıp gerektiğinde kesmek',
    ],
    answerIndex: 3,
    explanation:
      'Debriyaj, vites değiştirirken veya duruşta motorun hareketini şanzımandan geçici olarak keser; pedal bırakıldığında gücü tekrar aktararak yumuşak kalkış sağlar.',
    whyWrong: [
      'Motoru soğutma görevi soğutma sistemine aittir.',
      'Yakıt basıncını yakıt sistemi ayarlar; debriyajın bununla ilgisi yoktur.',
    ],
    objective: 'Debriyajın gücü bağlama/kesme işlevini kavramak.',
    tags: ['debriyaj', 'kavrama', 'vites'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-115',
    subject: 'motor',
    topic: 'elektrik',
    difficulty: 'kolay',
    stem: 'Aşağıdakilerden hangisi aracın elektrik sistemiyle çalışan donanımlardandır?',
    options: [
      'Radyatör peteği',
      'Far, sinyal ve korna',
      'Fren balatası',
      'Debriyaj baskı balatası',
    ],
    answerIndex: 1,
    explanation:
      'Far, sinyal lambaları ve korna aküden ve alternatörden beslenen elektrik sistemine bağlı donanımlardır.',
    whyWrong: [
      'Radyatör peteği soğutma sisteminin parçasıdır.',
      'Fren balatası ve debriyaj balatası mekanik parçalardır.',
    ],
    objective: 'Elektrik sistemine bağlı temel donanımları tanımak.',
    tags: ['elektrik', 'far', 'sinyal'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-116',
    subject: 'motor',
    topic: 'gosterge',
    difficulty: 'kolay',
    stem: 'Gösterge panelinde akü/şarj ikaz lambası motor çalışırken yanmaya devam ederse bu neyi gösterir?',
    options: [
      'Lastik basıncının düştüğünü ve yol tutuşun azaldığını',
      'Depodaki yakıtın bittiğini ve rezerve geçildiğini',
      'Şarj sisteminde bir arıza olabileceğini',
      'Motorun henüz soğuk olduğunu ve ısınmayı beklediğini',
    ],
    answerIndex: 2,
    explanation:
      'Motor çalışırken şarj ikazının yanması, alternatörün akü şarjını sağlayamadığını veya kayışın gevşek/kopuk olabileceğini gösterir; sistem kontrol ettirilmelidir.',
    whyWrong: [
      'Lastik basıncı için ayrı bir ikaz göstergesi bulunur.',
      'Yakıt seviyesi ayrı bir gösterge ile takip edilir.',
    ],
    objective: 'Şarj ikaz lambasının anlamını ve olası nedenini kavramak.',
    tags: ['gosterge', 'sarj', 'alternator'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-117',
    subject: 'motor',
    topic: 'yakit',
    difficulty: 'orta',
    stem: 'Benzinli motorlarda hava-yakıt karışımının ateşlenmesini sağlayan parça hangisidir?',
    options: ['Enjektör', 'Termostat', 'Marş motoru', 'Buji'],
    answerIndex: 3,
    explanation:
      'Benzinli motorlarda sıkıştırılan hava-yakıt karışımı, bujinin ürettiği elektrik kıvılcımıyla ateşlenir ve yanma gerçekleşir.',
    whyWrong: [
      'Enjektör yakıtı püskürtür, ateşlemez.',
      'Termostat soğutma sıcaklığını, marş motoru ilk çalışmayı sağlar.',
    ],
    objective: 'Benzinli motorda bujinin ateşleme görevini kavramak.',
    tags: ['yakit', 'buji', 'atesleme'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-118',
    subject: 'motor',
    topic: 'motor-cesit',
    difficulty: 'zor',
    stem: 'Dizel (mazotlu) motorların benzinli motorlardan temel farkı aşağıdakilerden hangisidir?',
    options: [
      'Dizel motorda ateşleme bujiyle yapılır ve kıvılcım gerekir',
      'Dizel motorda yakıt kullanılmaz, yalnızca hava sıkıştırılır',
      'Yakıt, sıkıştırmayla ısınan havada kendiliğinden tutuşur',
      'Dizel motorlar elektrik enerjisiyle çalışır ve yakıt yakmaz',
    ],
    answerIndex: 2,
    explanation:
      'Dizel motorlarda hava yüksek oranda sıkıştırılarak ısıtılır; püskürtülen mazot bu sıcak havada bujiye gerek kalmadan kendiliğinden tutuşur. Benzinli motorlarda ise ateşleme buji ile yapılır.',
    whyWrong: [
      'Buji ile ateşleme benzinli motorların özelliğidir.',
      'Dizel motor da bir içten yanmalı motordur ve yakıt (mazot) kullanır.',
    ],
    objective: 'Dizel ve benzinli motorların ateşleme farkını kavramak.',
    tags: ['motor-cesit', 'dizel', 'atesleme'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-119',
    subject: 'motor',
    topic: 'triger',
    difficulty: 'zor',
    stem: 'Triger (eksantrik/zaman) kayışının görevi ve bakımı ile ilgili doğru ifade hangisidir?',
    options: [
      'Trigerin motorla ilgisi yoktur, sadece klimayı çalıştırır',
      'Krank ile eksantrik milinin uyumlu dönmesini sağlar',
      'Triger kayışı hiçbir zaman değiştirilmez',
      'Triger kayışı lastiklerin balansını ayarlar',
    ],
    answerIndex: 1,
    explanation:
      'Triger kayışı, krank mili ile eksantrik (kam) milinin senkron dönmesini sağlar; belirli aralıklarla değişmesi gerekir. Kopması durumunda supap ve pistonlar çarpışarak motorda ciddi hasar oluşabilir. Kopması motorda ağır hasara yol açabilir.',
    whyWrong: [
      'Trigerin görevi klima değil, motor zamanlamasıdır.',
      'Triger kayışı ömürlüdür; üretici periyoduna göre değiştirilmelidir.',
    ],
    objective: 'Triger kayışının motor zamanlamasındaki kritik rolünü kavramak.',
    tags: ['triger', 'kayis', 'bakim'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-120',
    subject: 'motor',
    topic: 'yaglama',
    difficulty: 'orta',
    stem: 'Motor yağının belirli aralıklarla (ör. kilometre/zamana bağlı) değiştirilmesinin nedeni nedir?',
    options: [
      'Yağ zamanla kirlenip özelliğini yitirir ve yağlama gücü azalır',
      'Yağ değiştikçe motorun gücü sürekli ve kalıcı biçimde artmaya devam eder',
      'Yeni yağ yakıtı ateşleyip yanmayı kolaylaştırır',
      'Yağ değişimi lastik basıncını da düzelttiği için gereklidir',
    ],
    answerIndex: 0,
    explanation:
      'Kullanımla birlikte motor yağı kir, kurum ve metal partikülleriyle kirlenir; kıvamı bozulur ve yağlama etkisi azalır. Bu nedenle belirli aralıklarla değiştirilmesi motorun ömrü için önemlidir.',
    whyWrong: [
      'Yağ değişimi motor gücünü sürekli artırmaz; amacı yağlamayı korumaktır.',
      'Yağın yakıtı ateşleme veya lastik basıncı ile ilgisi yoktur.',
    ],
    objective: 'Periyodik yağ değişiminin gerekçesini kavramak.',
    tags: ['yaglama', 'yag-degisimi', 'bakim'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-121',
    subject: 'motor',
    topic: 'gosterge',
    difficulty: 'orta',
    stem: 'Yüksek viteste ve çok düşük devirde (motor zorlanarak) gitmenin motora etkisi nedir?',
    options: [
      'Motoru dinlendirir, yakıt tüketimini sıfırlar ve ömrünü uzatır',
      'Motoru zorlar, tıkırtı/vuruntu yapabilir ve aşınmayı artırır',
      'Fren sistemini güçlendirip fren mesafesini kısaltır',
      'Aktarma organlarını koruyup vites geçişlerini yumuşatır',
    ],
    answerIndex: 1,
    explanation:
      'Uygun olmayan yüksek viteste düşük devirde gitmek motoru zorlar; yeterli tork bulunmadığından titreme, vuruntu ve aşırı yüklenme oluşur. Hıza uygun vites seçilmelidir.',
    whyWrong: [
      'Zorlanan motor dinlenmez; tersine yıpranır.',
      'Motoru zorlamak yakıt tüketimini sıfırlamaz ve fren sistemiyle ilgisi yoktur.',
    ],
    objective: 'Devir-vites uyumunun motora etkisini kavramak.',
    tags: ['gosterge', 'devir', 'vites'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-122',
    subject: 'motor',
    topic: 'egzoz',
    difficulty: 'orta',
    stem: 'Egzoz sistemindeki katalitik konvertörün (katalizör) temel işlevi nedir?',
    options: [
      'Motor yağını süzüp içindeki metal parçacıkları tutmak',
      'Aküyü şarj edip elektrik sistemine akım sağlamak',
      'Egzoz sesini kısıp gürültü kirliliğini azaltmak ve sesi yumuşatmak',
      'Egzozdaki zararlı gazları daha az zararlı gazlara dönüştürmek',
    ],
    answerIndex: 3,
    explanation:
      'Katalitik konvertör, egzoz gazındaki zararlı bileşenleri kimyasal tepkimelerle daha az zararlı gazlara dönüştürerek çevreye verilen kirliliği azaltır.',
    whyWrong: [
      'Motor yağını yağ filtresi süzer.',
      'Aküyü alternatör şarj eder; katalizörün bununla ilgisi yoktur.',
    ],
    objective: 'Katalitik konvertörün egzoz emisyonunu azaltma işlevini kavramak.',
    tags: ['egzoz', 'katalizor', 'cevre'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-123',
    subject: 'motor',
    topic: 'direksiyon',
    difficulty: 'orta',
    stem: 'Hidrolik/elektrikli direksiyon (power steering) sisteminin sürücüye sağladığı temel fayda nedir?',
    options: [
      'Direksiyonu çevirmeyi kolaylaştırmak',
      'Motorun gücünü artırıp hızlanmayı çabuklaştırmak',
      'Yakıt deposunu büyütüp menzili uzatmak',
      'Fren mesafesini uzatıp yavaşlamayı yumuşatmak',
    ],
    answerIndex: 0,
    explanation:
      'Direksiyon destek sistemi, tekerlekleri yönlendirmek için gereken kuvveti azaltır; böylece özellikle düşük hızda ve park sırasında direksiyon daha kolay çevrilir.',
    whyWrong: [
      'Sistem motor gücünü artırmaz; yönlendirmeyi kolaylaştırır.',
      'Yakıt deposu ve fren mesafesi ile doğrudan ilgisi yoktur.',
    ],
    objective: 'Direksiyon destek sisteminin işlevini kavramak.',
    tags: ['direksiyon', 'hidrolik', 'yonlendirme'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-124',
    subject: 'motor',
    topic: 'fren',
    difficulty: 'zor',
    stem: 'Aracın hızı arttıkça fren (durma) mesafesiyle ilgili doğru ifade hangisidir?',
    options: [
      'Hız arttıkça fren mesafesi değişmez',
      'Hız arttıkça fren mesafesi belirgin biçimde uzar',
      'Hız arttıkça fren mesafesi kısalır',
      'Fren mesafesi yalnızca lastik markasına bağlıdır',
    ],
    answerIndex: 1,
    explanation:
      'Hız arttıkça aracın kinetik enerjisi büyür; bu enerjiyi durdurmak için gereken mesafe de artar. Bu nedenle yüksek hızda takip mesafesi daha uzun tutulmalıdır.',
    whyWrong: [
      'Fren mesafesi hızdan bağımsız değildir; hızla birlikte artar.',
      'Fren mesafesi yalnızca lastik markasına değil; hız, zemin, fren ve lastik durumuna bağlıdır.',
    ],
    objective: 'Hız ile fren mesafesi arasındaki ilişkiyi kavramak.',
    tags: ['fren', 'fren-mesafesi', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-125',
    subject: 'motor',
    topic: 'sogutma',
    difficulty: 'kolay',
    stem: 'Soğutma sisteminde radyatörün görevi aşağıdakilerden hangisidir?',
    options: [
      'Isınan soğutma suyunu hava akımıyla soğutmak',
      'Yakıtı depolayıp motora düzenli olarak göndermek',
      'Elektrik üretip aracın akülerini şarj etmek',
      'Vitesleri değiştirip motor gücünü tekerleğe iletmek',
    ],
    answerIndex: 0,
    explanation:
      'Radyatör, motordan ısı alarak ısınan soğutma suyunu ince kanalları ve hava akımı sayesinde soğutur; soğuyan su tekrar motora gönderilir.',
    whyWrong: [
      'Yakıt depolama görevi yakıt deposuna aittir.',
      'Elektrik üretimi alternatörün, vites değiştirme şanzımanın görevidir.',
    ],
    objective: 'Radyatörün soğutma suyunu soğutma işlevini kavramak.',
    tags: ['sogutma', 'radyator', 'sicaklik'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-126',
    subject: 'motor',
    topic: 'aku',
    difficulty: 'orta',
    stem: 'Farlar açık unutulduğunda aracın çalışmaması (marş basmaması) en olası olarak neyi gösterir?',
    options: [
      'Lastiklerin patladığını',
      'Yağ seviyesinin yükseldiğini',
      'Akünün boşaldığını',
      'Egzozun tıkandığını',
    ],
    answerIndex: 2,
    explanation:
      'Motor kapalıyken farlar açık kalırsa akü elektriği tüketir; şarjı bittiğinde marş motoruna yeterli akım gitmez ve araç çalışmaz. Bu duruma akünün boşalması denir.',
    whyWrong: [
      'Lastik patlaması marşı etkilemez.',
      'Yağ ve egzozun marşın basmamasıyla doğrudan bağlantısı yoktur.',
    ],
    objective: 'Akü boşalmasının belirtisini ve nedenini kavramak.',
    tags: ['aku', 'mars', 'far'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-127',
    subject: 'motor',
    topic: 'lastik',
    difficulty: 'orta',
    stem: 'Lastik hava basıncının olması gerekenden düşük olması hangi sonuçlara yol açar?',
    options: [
      'Yakıt tüketimi ve lastik aşınması artar, yol tutuşu bozulur',
      'Motor daha güçlü çalışır ve hızlanma belirgin biçimde iyileşir',
      'Fren sistemi kendiliğinden güçlenip fren mesafesini kısaltır',
      'Akü daha hızlı şarj olur ve marş gücü artar',
    ],
    answerIndex: 0,
    explanation:
      'Düşük basınçlı lastik yola daha fazla sürtünme ile temas eder; bu da yakıt tüketimini ve kenar aşınmasını artırır, ısınmaya ve yol tutuş kaybına yol açarak güvenliği tehlikeye atar.',
    whyWrong: [
      'Düşük basınç motor gücünü artırmaz.',
      'Fren ve akü ile basınç arasında doğrudan bir güçlenme ilişkisi yoktur.',
    ],
    objective: 'Düşük lastik basıncının güvenlik ve yakıt etkilerini kavramak.',
    tags: ['lastik', 'hava-basinci', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-128',
    subject: 'motor',
    topic: 'aktarma',
    difficulty: 'zor',
    stem: 'Manuel şanzımanlı bir araçta farklı vites kademelerinin bulunmasının temel amacı nedir?',
    options: [
      'Yakıtı soğutup deponun aşırı ısınmasını engellemek',
      'Farların parlaklığını hıza göre kendiliğinden ayarlamak',
      'Motor sesini kısıp kabine gelen gürültüyü azaltmak ve sürüşü sessizleştirmek',
      'Motor gücünü hız ve yol koşuluna göre tekerleğe iletmek',
    ],
    answerIndex: 3,
    explanation:
      'Vites kademeleri, motorun devrini ve torkunu duruma göre ayarlamayı sağlar; kalkışta yüksek tork, yüksek hızda düşük devirle verimli sürüş için farklı dişli oranları kullanılır.',
    whyWrong: [
      'Vitesler süs amaçlı değildir; işlevseldir.',
      'Yakıt soğutma ve far ayarı ile ilgileri yoktur.',
    ],
    objective: 'Şanzıman ve vites kademelerinin işlevini kavramak.',
    tags: ['aktarma', 'sanziman', 'vites'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-129',
    subject: 'motor',
    topic: 'elektrik',
    difficulty: 'kolay',
    stem: 'Aracın sigortalarının (elektrik sigortası) temel görevi nedir?',
    options: [
      'Aşırı akıma karşı elektrik devrelerini korumak',
      'Motoru soğutup çalışma sıcaklığını dengede tutmak',
      'Lastik basıncını ölçüp göstergeye bildirmek',
      'Yakıt seviyesini ölçüp gösterge panelinde göstermek ve uyarı vermek',
    ],
    answerIndex: 0,
    explanation:
      'Sigortalar, bir devrede aşırı akım oluştuğunda eriyip/atarak devreyi keser; böylece kabloların ve elektrikli parçaların zarar görmesini ve yangın riskini önler.',
    whyWrong: [
      'Motor soğutması soğutma sisteminin görevidir.',
      'Lastik basıncı ve yakıt seviyesi ayrı göstergelerle takip edilir.',
    ],
    objective: 'Elektrik sigortasının koruma işlevini kavramak.',
    tags: ['elektrik', 'sigorta', 'koruma'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-130',
    subject: 'motor',
    topic: 'gosterge',
    difficulty: 'orta',
    stem: 'Motor arıza (check engine / motor ikaz) lambası sürüş sırasında yanarsa doğru davranış nedir?',
    options: [
      'Lambanın sönmesini beklemeden hızlanıp yola devam etmek',
      'Lambayı bantla kapatıp göz ardı ederek sürmek',
      'Farları açıp uyarıyı önemsemeden yola devam etmek',
      'En kısa sürede yetkili serviste kontrol ettirmek',
    ],
    answerIndex: 3,
    explanation:
      'Motor ikaz lambası, motor veya emisyon sisteminde bir sorun algılandığını gösterir. Araç dikkatli kullanılmalı ve en kısa sürede yetkili bir serviste arıza tespit ettirilmelidir.',
    whyWrong: [
      'Uyarıyı görmezden gelip hızlanmak arızayı büyütebilir.',
      'Lambayı kapatmak sorunu gizler, çözmez.',
    ],
    objective: 'Motor arıza ikaz lambasına doğru tepkiyi öğrenmek.',
    tags: ['gosterge', 'ariza-lambasi', 'bakim'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
];
