/**
 * ÖZGÜN ilk yardım soruları — 4. genişletme (Program 2 · Faz 9). ROADMAP C.4/E.6.
 * Kaynak = Resmî temel ilk yardım rehberleri; KENDİ İFADEMİZLE. Uzman onayı gereklidir.
 */
import type { QuestionInput } from '@ea/content-schema';

const SRC = 'Resmî temel ilk yardım rehberleri (özgün ifade; uzman onayı gerekli)';

export const ILKYARDIM_QUESTIONS_4: QuestionInput[] = [
  {
    id: 'ilkyardim-401',
    subject: 'ilkyardim',
    topic: 'olay-yeri-guvenligi',
    difficulty: 'kolay',
    stem: 'Kaza yapmış bir araçta yangın riskini azaltmak için ilk yardımcının alması gereken önlemlerden biri hangisidir?',
    options: [
      'Motoru çalışır durumda bırakmak',
      'Aracın kontağını kapatıp el frenini çekmek',
      'Aracın farlarını sürekli yakıp söndürmek',
      'Yakıt deposunun kapağını açıp içine bakmak',
    ],
    answerIndex: 1,
    explanation:
      'Olay yeri güvenliğinde kazaya karışan aracın kontağı kapatılır ve el freni çekilir; böylece hem kıvılcım kaynaklı yangın riski hem de aracın kendiliğinden hareket etme tehlikesi azaltılır.',
    whyWrong: [
      'Motoru çalışır bırakmak yakıt sızıntısı varsa tutuşma riskini artırır.',
      'Yakıt deposunu açmak buhar çıkışını artırarak tehlikeyi büyütür.',
    ],
    objective: 'Olay yerinde kontak kapatma ve el freni çekme önlemini bilmek.',
    tags: ['olay-yeri-guvenligi', 'kontak', 'yangin-riski'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-402',
    subject: 'ilkyardim',
    topic: 'olay-yeri-guvenligi',
    difficulty: 'kolay',
    stem: 'Trafik kazası olay yerinde sigara içilmesine izin verilmemesinin başlıca nedeni nedir?',
    options: [
      'Yaralıların sigara dumanından rahatsız olması',
      'Sigaranın dikkat dağıtması',
      'Sızmış olabilecek yakıtın kıvılcımla tutuşup yangın veya patlamaya yol açabilmesi',
      'Olay yerinde çöp oluşturması',
    ],
    answerIndex: 2,
    explanation:
      'Kaza sonrası araçlardan yakıt sızmış olabilir; sigara ateşi veya kıvılcımı bu yakıtı tutuşturarak yangına ve patlamaya neden olabilir. Bu yüzden olay yerinde kesinlikle sigara içilmez ve içilmesine izin verilmez.',
    whyWrong: [
      'Duman rahatsızlığı ve dikkat dağınıklığı ikincil sakıncalardır; asıl tehlike tutuşmadır.',
      'Çöp oluşturmak güvenlikle ilgili temel gerekçe değildir.',
    ],
    objective: 'Olay yerindeki yangın-patlama riskini kavramak.',
    tags: ['olay-yeri-guvenligi', 'yakit-sizintisi', 'yangin-riski'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-403',
    subject: 'ilkyardim',
    topic: 'olay-yeri-guvenligi',
    difficulty: 'orta',
    stem: 'Olay yerinde toplanan meraklı kalabalığın güvenli bir uzaklığa yönlendirilmesi neden gereklidir?',
    options: [
      'Kalabalık müdahaleyi güçleştirir, yaralının hava almasını engeller ve paniği büyütür',
      'Kalabalık olay yerini daha güvenli hâle getirir',
      'Kalabalığın fotoğraf çekmesi zorunludur',
      'Yaralıların moralinin yükselmesi için kalabalık gerekir',
    ],
    answerIndex: 0,
    explanation:
      'Meraklı kalabalık ilk yardımcının çalışma alanını daraltır, yaralının etrafındaki hava dolaşımını azaltır ve panik ortamı oluşturur; ayrıca yeni kazalara zemin hazırlayabilir. Bu nedenle kalabalık sakin bir dille uzaklaştırılır.',
    whyWrong: [
      'Kalabalık güvenliği artırmaz; aksine ikincil tehlike oluşturur.',
      'Fotoğraf çekmek veya moral vermek olay yeri yönetiminin parçası değildir.',
    ],
    objective: 'Olay yerinde kalabalık yönetiminin gerekçesini açıklamak.',
    tags: ['olay-yeri-guvenligi', 'kalabalik', 'panik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-404',
    subject: 'ilkyardim',
    topic: 'ilkyardim-temelleri',
    difficulty: 'kolay',
    stem: 'Hayat kurtarma zincirinin birinci halkası aşağıdakilerden hangisidir?',
    options: [
      'Hastane acil servislerinde yapılan tedavi',
      'Ambulans ekiplerinin yolda uyguladığı bakım',
      'Yaralının taburcu edilmesi',
      'Sağlık kuruluşuna (112 aranarak) haber verilmesi',
    ],
    answerIndex: 3,
    explanation:
      'Hayat kurtarma zincirinin ilk halkası sağlık kuruluşuna haber vermektir; 112 ne kadar erken aranırsa profesyonel yardım o kadar erken ulaşır. Sonraki halkalar olay yerinde temel yaşam desteği, ambulans müdahalesi ve hastane bakımıdır.',
    whyWrong: [
      'Ambulans ve hastane bakımı zincirin sonraki halkalarıdır.',
      'Taburcu edilme, zincirin bir halkası değildir.',
    ],
    objective: 'Hayat kurtarma zincirinin ilk halkasını bilmek.',
    tags: ['ilkyardim-temelleri', 'hayat-kurtarma-zinciri', '112'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-405',
    subject: 'ilkyardim',
    topic: 'ilkyardim-temelleri',
    difficulty: 'kolay',
    stem: 'İlk yardımın tanımındaki temel özelliklerden biri aşağıdakilerden hangisidir?',
    options: [
      'Yalnızca hekimler tarafından yapılabilmesi',
      'Olay yerinde, eldeki imkânlarla ve ilaç kullanılmadan uygulanması',
      'Mutlaka ambulans içinde yapılması',
      'İleri tıbbi cihazlar gerektirmesi',
    ],
    answerIndex: 1,
    explanation:
      'İlk yardım; sağlık ekibi gelene kadar, olay yerinde bulunan imkânlarla ve ilaçsız olarak yapılan uygulamaları kapsar. Amaç yaşamı korumak ve durumun kötüleşmesini önlemektir; ilaç vermek ilk yardımcının görevi değildir.',
    whyWrong: [
      'İlk yardım, eğitim almış herkes tarafından uygulanabilir; hekim şartı yoktur.',
      'Ambulans içi bakım ve cihazlı müdahale, acil tıbbi yardımın konusudur.',
    ],
    objective: 'İlk yardımın ilaçsız ve olay yeri odaklı tanımını kavramak.',
    tags: ['ilkyardim-temelleri', 'tanim', 'ilacsiz-uygulama'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-406',
    subject: 'ilkyardim',
    topic: 'ilkyardim-temelleri',
    difficulty: 'orta',
    stem: 'Araçta bulundurulan ilk yardım seti (çantası) ile ilgili doğru bilgi hangisidir?',
    options: [
      'Sette bol miktarda ağrı kesici ve antibiyotik bulunmalıdır',
      'Setteki malzemelerin son kullanma tarihine bakılmasına gerek yoktur',
      'Set, aracın dış tamponuna bağlanarak taşınmalıdır',
      'Sette ilaç bulunmaz; sargı bezi, üçgen bandaj, flaster gibi malzemeler bulunur',
    ],
    answerIndex: 3,
    explanation:
      'İlk yardım ilaçsız uygulamalardan oluştuğu için ilk yardım setinde ilaç bulundurulmaz; sette sargı bezi, üçgen bandaj, flaster, makas ve eldiven gibi malzemeler yer alır. Malzemeler düzenli aralıklarla kontrol edilmelidir.',
    whyWrong: [
      'Ağrı kesici ve antibiyotik gibi ilaçlar ilk yardım setine konmaz.',
      'Malzemelerin tarihi ve sağlamlığı düzenli olarak kontrol edilmelidir.',
    ],
    objective: 'İlk yardım setinde ilaç bulunmadığını bilmek.',
    tags: ['ilkyardim-temelleri', 'ilkyardim-cantasi', 'malzeme'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-407',
    subject: 'ilkyardim',
    topic: '112-iletisim',
    difficulty: 'kolay',
    stem: '112 ile yapılan acil çağrı görüşmesi ne zaman sonlandırılmalıdır?',
    options: [
      'Merkezdeki görevli görüşmeyi bitirebileceğinizi söylediğinde',
      'Adres söylenir söylenmez',
      'Telefonun şarjını korumak için olabildiğince erken',
      'Uzaktan siren sesi duyulduğunda',
    ],
    answerIndex: 0,
    explanation:
      '112 görüşmesinde telefon, merkezdeki görevli kapatabileceğinizi söylemeden kapatılmaz; görevli ek sorular sorabilir ve olay yerindeki kişiye telefonda ilk yardım yönlendirmesi yapabilir.',
    whyWrong: [
      'Adres verildikten sonra da görevlinin ek bilgiye ihtiyacı olabilir.',
      'Siren sesi, ekibin doğru adrese ulaştığını garanti etmez.',
    ],
    objective: 'Acil çağrının görevli izniyle sonlandırıldığını bilmek.',
    tags: ['112-iletisim', 'ihbar', 'iletisim'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-408',
    subject: 'ilkyardim',
    topic: '112-iletisim',
    difficulty: 'kolay',
    stem: '112 merkezindeki görevliyle konuşan ilk yardımcının doğru tutumu hangisidir?',
    options: [
      'Bilgi vermeden telefonu hemen kapatmak',
      'Görevlinin sorularını gereksiz bularak yanıtlamamak',
      'Panik içinde bağırarak konuşmak',
      'Sakin kalıp sorulara açık ve net yanıtlar vermek, verilen yönlendirmeleri uygulamak',
    ],
    answerIndex: 3,
    explanation:
      'Acil çağrıda sakin ve anlaşılır konuşmak, sorulara net yanıt vermek ve görevlinin yönlendirmelerini uygulamak, yardımın doğru yere ve doğru şekilde ulaşmasını sağlar.',
    whyWrong: [
      'Panikle bağırmak bilgilerin anlaşılmasını zorlaştırır.',
      'Soruları yanıtsız bırakmak veya telefonu erken kapatmak yardımın gecikmesine yol açar.',
    ],
    objective: 'Acil çağrıda etkili iletişim kurallarını uygulamak.',
    tags: ['112-iletisim', 'iletisim', 'sakinlik'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-409',
    subject: 'ilkyardim',
    topic: 'triyaj',
    difficulty: 'orta',
    stem: 'Birden fazla yaralının bulunduğu bir kazada ilk yardımcı önceliği hangi yaralıya vermelidir?',
    options: [
      'Yüksek sesle ağlayan yaralıya',
      'Solunumu durmuş olan yaralıya',
      'Ayak bileği burkulmuş yaralıya',
      'Elinde küçük bir sıyrık olan yaralıya',
    ],
    answerIndex: 1,
    explanation:
      'Birden çok yaralı olduğunda öncelik yaşamsal tehlikesi en yüksek olana verilir; solunumu durmuş yaralı dakikalar içinde kaybedilebileceği için ilk müdahale ona yapılır.',
    whyWrong: [
      'Ağlayabilen kişinin solunumu ve bilinci var demektir; bekleyebilir.',
      'Burkulma ve sıyrık yaşamı hemen tehdit etmez.',
    ],
    objective: 'Çok yaralılı olayda yaşamsal önceliği belirlemek.',
    tags: ['triyaj', 'oncelik', 'solunum'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-410',
    subject: 'ilkyardim',
    topic: 'triyaj',
    difficulty: 'zor',
    stem: 'Çok yaralılı bir kazada, bağırarak yardım isteyen yaralıdan önce sessiz ve hareketsiz yatan yaralının kontrol edilmesinin nedeni nedir?',
    options: [
      'Sessiz yaralıyla iletişim kurmanın daha kolay olması',
      'Bağıran yaralının kesinlikle yarasız olduğunun bilinmesi',
      'Bağırabilen kişinin bilinci ve solunumu var demektir; sessiz kişinin ise solunumu durmuş olabilir',
      'Sessiz yaralının kimlik bilgilerine daha hızlı ulaşılması',
    ],
    answerIndex: 2,
    explanation:
      'Bağırabilen ve yardım isteyebilen kişinin hava yolu açık, solunumu ve bilinci mevcuttur. Ses çıkarmayan, hareketsiz yaralıda ise bilinç kaybı ve solunum durması olabilir; bu nedenle değerlendirmeye sessiz yaralıdan başlanır.',
    whyWrong: [
      'İletişim kolaylığı veya kimlik tespiti öncelik ölçütü değildir.',
      'Bağıran yaralının da yarası olabilir; ancak yaşamsal işlevleri çalışıyordur.',
    ],
    objective: 'Sessiz yaralının öncelikli değerlendirilme mantığını kavramak.',
    tags: ['triyaj', 'oncelik', 'bilinc'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-411',
    subject: 'ilkyardim',
    topic: 'triyaj',
    difficulty: 'kolay',
    stem: 'Bir kazada, birinde şiddetli kanama diğerinde küçük bir sıyrık bulunan iki yaralıdan hangisine öncelik verilir ve neden?',
    options: [
      'Şiddetli kanaması olana; çünkü hızlı kan kaybı kısa sürede yaşamı tehdit eder',
      'Sıyrığı olana; çünkü tedavisi daha kısa sürer',
      'Hiçbirine; ambulans gelene kadar müdahale edilmez',
      'Sıyrığı olana; çünkü daha az ağrısı vardır',
    ],
    answerIndex: 0,
    explanation:
      'Şiddetli kanama kısa sürede şoka ve ölüme yol açabileceğinden önce kanamalı yaralıya müdahale edilir; küçük sıyrık yaşamsal tehlike oluşturmaz ve bekleyebilir.',
    whyWrong: [
      'Tedavi süresi veya ağrı azlığı öncelik ölçütü değildir.',
      'Yaşamı tehdit eden kanamada ambulansı eli boş beklemek zaman kaybettirir.',
    ],
    objective: 'Kanama şiddetine göre öncelik vermeyi kavramak.',
    tags: ['triyaj', 'kanama', 'oncelik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-412',
    subject: 'ilkyardim',
    topic: 'bilinc-degerlendirme',
    difficulty: 'zor',
    stem: 'Yüksek sesle seslenildiği hâlde yanıt vermeyen bir kişide bilinç düzeyini değerlendirmenin bir sonraki adımı nedir?',
    options: [
      'Kişiyi ayağa kaldırıp yürütmek',
      'Omzuna hafifçe dokunup sıkarak ağrılı uyarana yanıt verip vermediğine bakmak',
      'Yüzüne soğuk su dökmek',
      'Hiç beklemeden kalp masajına başlamak',
    ],
    answerIndex: 1,
    explanation:
      'Bilinç değerlendirmesinde önce sesli uyaran kullanılır; yanıt alınamazsa omuza hafifçe dokunup sıkma gibi ağrılı uyarana verilen tepkiye bakılır. Hiçbir uyarana yanıt yoksa bilinç kapalı kabul edilip solunum değerlendirilir.',
    whyWrong: [
      'Kalp masajı, solunum değerlendirilmeden başlatılmaz.',
      'Su dökmek güvenilir bir değerlendirme yöntemi değildir; kişiyi kaldırmak yaralanmayı ağırlaştırabilir.',
    ],
    objective: 'Sesli ve ağrılı uyaranla bilinç değerlendirme sırasını bilmek.',
    tags: ['bilinc-degerlendirme', 'uyaran', 'degerlendirme'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-413',
    subject: 'ilkyardim',
    topic: 'solunum-degerlendirme',
    difficulty: 'orta',
    stem: 'Bak-dinle-hisset yöntemiyle yapılan solunum kontrolü en fazla kaç saniye sürmelidir?',
    options: ['2 saniye', '30 saniye', '10 saniye', '60 saniye'],
    answerIndex: 2,
    explanation:
      'Solunum kontrolü en fazla 10 saniye içinde tamamlanır; bu sürede solunum görülmez, duyulmaz ve hissedilmezse solunum yok kabul edilerek vakit kaybetmeden temel yaşam desteğine geçilir.',
    whyWrong: [
      '2 saniye, solunumu güvenilir biçimde değerlendirmek için çok kısadır.',
      '30-60 saniye beklemek, müdahalenin gecikmesine yol açar.',
    ],
    objective: 'Solunum kontrolünün 10 saniyeyi aşmaması gerektiğini bilmek.',
    tags: ['solunum-degerlendirme', 'sure', 'bak-dinle-hisset'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-414',
    subject: 'ilkyardim',
    topic: 'ikinci-degerlendirme',
    difficulty: 'orta',
    stem: 'Yaşamsal işlevleri güvence altına alınan yaralıda yapılan ikinci değerlendirme neyi kapsar?',
    options: [
      'Yalnızca nabız sayımını',
      'Yalnızca göz bebeklerinin kontrolünü',
      'Aracın hasar durumunun incelenmesini',
      'Yaralıdan bilgi alınarak baştan ayağa doğru tüm vücudun kontrol edilmesini',
    ],
    answerIndex: 3,
    explanation:
      'İkinci değerlendirmede yaralıdan ya da çevredekilerden olayla ilgili bilgi alınır ve baş bölgesinden başlanarak ayaklara doğru tüm vücut; yara, kanama, şişlik ve şekil bozukluğu yönünden kontrol edilir.',
    whyWrong: [
      'Tek başına nabız veya göz bebeği kontrolü tam bir değerlendirme değildir.',
      'Araç hasarı yaralı değerlendirmesinin konusu değildir.',
    ],
    objective: 'İkinci değerlendirmenin baştan ayağa kontrol olduğunu kavramak.',
    tags: ['ikinci-degerlendirme', 'degerlendirme', 'kontrol'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-415',
    subject: 'ilkyardim',
    topic: 'temel-yasam-destegi',
    difficulty: 'kolay',
    stem: 'Kalp masajı uygulanacak kişi hangi zeminde ve pozisyonda olmalıdır?',
    options: [
      'Sert ve düz bir zeminde, sırtüstü yatar durumda',
      'Yumuşak bir yatakta, yan yatar durumda',
      'Koltukta oturur durumda',
      'Yüzükoyun, başı yana çevrilmiş durumda',
    ],
    answerIndex: 0,
    explanation:
      'Göğüs basılarının etkili olabilmesi için kişi sert ve düz bir zemine sırtüstü yatırılır; yumuşak zeminde bası kuvveti zemine gömülerek kaybolur ve kalp yeterince sıkıştırılamaz.',
    whyWrong: [
      'Yatak gibi yumuşak zeminler bası derinliğini azaltır.',
      'Oturur veya yüzükoyun konumda etkili kalp masajı yapılamaz.',
    ],
    objective: 'Kalp masajında sert-düz zemin gerekliliğini bilmek.',
    tags: ['temel-yasam-destegi', 'zemin', 'kalp-masaji'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-416',
    subject: 'ilkyardim',
    topic: 'temel-yasam-destegi',
    difficulty: 'orta',
    stem: 'Göğüs basısı uygularken ilk yardımcının kollarının duruşu nasıl olmalıdır?',
    options: [
      'Dirsekler bükülü, bilekler gevşek',
      'Tek kol serbest, diğeri göğüste',
      'Dirsekler bükülmeden kollar gergin, omuzlar yaralının göğsünün tam üzerinde',
      'Kollar çapraz, eller göğsün iki yanında',
    ],
    answerIndex: 2,
    explanation:
      'Etkili bası için kollar dirsekler bükülmeden gergin tutulur ve omuzlar yaralının göğsünün tam üzerine getirilir; böylece bası, kol kasları yerine vücut ağırlığıyla dik olarak uygulanır ve ilk yardımcı daha geç yorulur.',
    whyWrong: [
      'Bükülü dirseklerle yapılan bası yüzeysel kalır ve hızla yorgunluk yaratır.',
      'Tek kolla veya çapraz kollarla düzenli ve dik bası uygulanamaz.',
    ],
    objective: 'Kalp masajında doğru kol ve omuz pozisyonunu kavramak.',
    tags: ['temel-yasam-destegi', 'teknik', 'kalp-masaji'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-417',
    subject: 'ilkyardim',
    topic: 'temel-yasam-destegi',
    difficulty: 'orta',
    stem: 'Kurtarıcı soluk verirken üflenen havanın miktarı nasıl ayarlanmalıdır?',
    options: [
      'Olabildiğince güçlü ve uzun üflenir',
      'Göğsü hafifçe yükseltecek kadar, yaklaşık bir saniye süreyle üflenir',
      'Ciğerlerdeki hava tamamen boşalana kadar üflenir',
      'Havanın miktarının hiçbir önemi yoktur',
    ],
    answerIndex: 1,
    explanation:
      'Kurtarıcı soluk, yaralının göğsünü hafifçe yükseltecek kadar ve yaklaşık bir saniye süreyle verilir; aşırı ve hızlı üfleme havanın mideye kaçmasına, mide içeriğinin geri gelip hava yolunu tıkamasına yol açabilir.',
    whyWrong: [
      'Aşırı güçlü üfleme mideye hava kaçırır ve kusmaya neden olabilir.',
      'Miktar ve süre, uygulamanın etkinliği için önemlidir.',
    ],
    objective: 'Kurtarıcı solukta doğru hava miktarını kavramak.',
    tags: ['temel-yasam-destegi', 'suni-solunum', 'teknik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-418',
    subject: 'ilkyardim',
    topic: 'temel-yasam-destegi',
    difficulty: 'orta',
    stem: 'Başlanan temel yaşam desteği hangi durumda sonlandırılabilir?',
    options: [
      'İlk yardımcının kolları yorulmaya başladığında',
      'Uygulamanın üzerinden beş dakika geçtiğinde',
      'Çevredekiler yeterli olduğunu söylediğinde',
      'Sağlık ekibi müdahaleyi devraldığında veya kişi kendine gelip normal solumaya başladığında',
    ],
    answerIndex: 3,
    explanation:
      'Temel yaşam desteği; sağlık ekibi gelip müdahaleyi devralana, kişi hareket edip normal solumaya başlayana ya da ilk yardımcının gücü tamamen tükenene kadar kesintisiz sürdürülür.',
    whyWrong: [
      'Hafif yorgunluk veya belirli bir sürenin dolması sonlandırma nedeni değildir.',
      'Çevredekilerin görüşü tıbbi bir ölçüt oluşturmaz.',
    ],
    objective: 'Temel yaşam desteğinin sonlandırılma koşullarını bilmek.',
    tags: ['temel-yasam-destegi', 'sonlandirma', 'canlandirma'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-419',
    subject: 'ilkyardim',
    topic: 'temel-yasam-destegi',
    difficulty: 'zor',
    stem: 'Çocuk ve bebeklerde temel yaşam desteğine, erişkinden farklı olarak nasıl başlanır?',
    options: [
      'Önce 5 kurtarıcı soluk verilerek',
      'Önce karına bası uygulanarak',
      'Önce şok pozisyonu verilerek',
      'Önce soğuk uygulama yapılarak',
    ],
    answerIndex: 0,
    explanation:
      'Çocuk ve bebeklerde kalp durması çoğunlukla solunum sorunlarından kaynaklandığı için canlandırmaya önce 5 kurtarıcı soluk verilerek başlanır; ardından göğüs basılarına geçilerek döngü sürdürülür.',
    whyWrong: [
      'Karına bası, yabancı cisim tıkanmasında kullanılan ayrı bir uygulamadır.',
      'Şok pozisyonu ve soğuk uygulamanın canlandırmayla ilgisi yoktur.',
    ],
    objective: 'Çocuk ve bebekte canlandırmanın 5 solukla başladığını bilmek.',
    tags: ['temel-yasam-destegi', 'cocuk', 'bebek', 'kurtarici-soluk'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-420',
    subject: 'ilkyardim',
    topic: 'temel-yasam-destegi',
    difficulty: 'zor',
    stem: 'Bebeklerde dolaşımın değerlendirilmesi için nabız genellikle nereden kontrol edilir?',
    options: [
      'Boyundaki şah damarından',
      'Ayak sırtından',
      'Kolun iç yüzündeki atardamardan',
      'Şakak bölgesinden',
    ],
    answerIndex: 2,
    explanation:
      'Bebeklerin boynu kısa ve yumuşak dokulu olduğundan şah damarını yoklamak güçtür; bu nedenle nabız, kolun iç yüzündeki atardamardan (dirsek ile omuz arasında) değerlendirilir.',
    whyWrong: [
      'Şah damarı erişkinlerde tercih edilen noktadır.',
      'Ayak sırtı ve şakak, bebekte güvenilir değerlendirme noktaları değildir.',
    ],
    objective: 'Bebekte nabzın kol iç yüzünden kontrol edildiğini bilmek.',
    tags: ['temel-yasam-destegi', 'bebek', 'nabiz'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-421',
    subject: 'ilkyardim',
    topic: 'temel-yasam-destegi',
    difficulty: 'orta',
    stem: 'Bebeklerde göğüs basısının derinliği yaklaşık ne kadar olmalıdır?',
    options: [
      'Erişkinle aynı, yaklaşık 5 cm',
      'Göğüs yüksekliğinin (ön-arka çapının) yaklaşık üçte biri kadar',
      'Göğüs tamamen çökecek kadar',
      'Belli belirsiz, yarım santimetreden az',
    ],
    answerIndex: 1,
    explanation:
      'Bebekte göğüs basısı, göğsün ön-arka yüksekliğinin yaklaşık üçte biri çökecek derinlikte ve iki parmakla uygulanır; erişkin derinliği bebeğin küçük gövdesi için fazladır.',
    whyWrong: [
      '5 cm derinlik bebekte organ yaralanmasına yol açabilir.',
      'Çok sığ bası ise dolaşımı desteklemez.',
    ],
    objective: 'Bebekte bası derinliğinin göğüs yüksekliğinin üçte biri olduğunu bilmek.',
    tags: ['temel-yasam-destegi', 'bebek', 'derinlik'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-422',
    subject: 'ilkyardim',
    topic: 'bogulma-tikanma',
    difficulty: 'orta',
    stem: 'Hava yolu tam tıkanan gebe bir kadında karına bası uygulanamayacağı için bası nereye yapılır?',
    options: [
      'Sırtın alt bölgesine',
      'Karnın alt bölgesine',
      'Boyun bölgesine',
      'Göğüs kemiğinin üzerine (göğse bası)',
    ],
    answerIndex: 3,
    explanation:
      'Gebelerde ve karına bası uygulanamayan çok kilolu kişilerde, karın yerine göğüs kemiği üzerine bası yapılır; amaç yine göğüs içi basıncı artırarak yabancı cismin dışarı atılmasını sağlamaktır.',
    whyWrong: [
      'Karın bölgesine bası gebede bebeğe ve iç organlara zarar verebilir.',
      'Sırtın alt bölgesi ve boyun, bası uygulanacak yerler değildir.',
    ],
    objective: 'Gebede tıkanmada göğse bası uygulandığını bilmek.',
    tags: ['bogulma-tikanma', 'gebe', 'heimlich'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-423',
    subject: 'ilkyardim',
    topic: 'bogulma-tikanma',
    difficulty: 'orta',
    stem: 'Karına bası (Heimlich) uygulanırken kişinin bilinci kapanırsa ilk yardımcı ne yapmalıdır?',
    options: [
      'Kişiyi dikkatlice yere yatırıp 112 çağrısını kesinleştirmek ve temel yaşam desteğine başlamak',
      'Ayakta karına bası uygulamaya devam etmek',
      'Kişiyi oturtup su içirmeye çalışmak',
      'Kişiyi yüzükoyun çevirip kendine gelmesini beklemek',
    ],
    answerIndex: 0,
    explanation:
      'Tıkanma sırasında bilinç kapanırsa kişi yavaşça yere yatırılır, 112 çağrısı kesinleştirilir ve temel yaşam desteğine başlanır; göğüs basıları aynı zamanda yabancı cismin yerinden oynamasına da yardımcı olabilir.',
    whyWrong: [
      'Bilinci kapalı kişi ayakta tutulamaz; bası ayakta sürdürülemez.',
      'Su içirmek veya beklemek hava yolunun kapalı kalmasına yol açar.',
    ],
    objective: 'Tıkanmada bilinç kapanınca yapılacakları bilmek.',
    tags: ['bogulma-tikanma', 'bilinc-kaybi', 'temel-yasam-destegi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-424',
    subject: 'ilkyardim',
    topic: 'bogulma-tikanma',
    difficulty: 'orta',
    stem: 'Hava yolu tam tıkanan, bilinci açık erişkinde karına basıdan önce hangi uygulama denenir?',
    options: [
      'Bol su içirme',
      'Göğse yumruk vurma',
      'İki kürek kemiğinin arasına el topuğuyla 5 kez sırt darbesi',
      'Kişiyi sırtüstü yatırma',
    ],
    answerIndex: 2,
    explanation:
      'Tam tıkanmada önce kişi hafifçe öne eğilir ve iki kürek kemiğinin arasına el topuğuyla 5 kez sırt darbesi uygulanır; cisim çıkmazsa karına bası (Heimlich) ile dönüşümlü olarak sürdürülür.',
    whyWrong: [
      'Tıkalı hava yoluna su vermek durumu ağırlaştırır.',
      'Göğse yumruk vurmak ya da kişiyi yatırmak tıkanma müdahalesi değildir.',
    ],
    objective: 'Tam tıkanmada sırt darbesi ve karına bası sırasını kavramak.',
    tags: ['bogulma-tikanma', 'sirt-darbesi', 'heimlich'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-425',
    subject: 'ilkyardim',
    topic: 'kanama',
    difficulty: 'kolay',
    stem: 'Kanamalar, kanın aktığı bölgeye göre kaç grupta incelenir ve bunlar nelerdir?',
    options: [
      'İkiye ayrılır: hızlı ve yavaş kanamalar',
      'Üçe ayrılır: dış kanama, iç kanama ve doğal deliklerden olan kanama',
      'Dörde ayrılır: kol, bacak, baş ve gövde kanamaları',
      'Gruplandırılmaz; tüm kanamalar aynı kabul edilir',
    ],
    answerIndex: 1,
    explanation:
      'Kanamalar; kanın vücut dışına aktığı dış kanama, vücut boşluklarına aktığı iç kanama ve kulak, burun gibi doğal deliklerden gelen kanama olmak üzere üç grupta incelenir.',
    whyWrong: [
      'Hız veya vücut bölgesi, temel sınıflandırma ölçütü değildir.',
      'Kanamanın türü, uygulanacak ilk yardımı belirlediği için gruplama önemlidir.',
    ],
    objective: 'Kanama çeşitlerini sınıflandırmak.',
    tags: ['kanama', 'siniflandirma', 'tanim'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-426',
    subject: 'ilkyardim',
    topic: 'kanama',
    difficulty: 'orta',
    stem: 'Doğrudan baskıya rağmen yavaşlamayan şiddetli kol veya bacak kanamasında kullanılan bası noktası uygulaması ne demektir?',
    options: [
      'Yara ile kalp arasındaki ana atardamarın üzerine, altındaki kemiğe doğru bası yapılması',
      'Yaranın içine parmakla bastırılması',
      'Doğrudan kalbin üzerine bastırılması',
      'Yaranın çevresine buz dizilmesi',
    ],
    answerIndex: 0,
    explanation:
      'Bası noktası uygulamasında, kanayan bölgeye giden ana atardamar, yara ile kalp arasında kalan bir noktada altındaki kemiğe doğru bastırılır; böylece bölgeye giden kan akımı azaltılarak kanama yavaşlatılır.',
    whyWrong: [
      'Yaranın içine bastırmak doku hasarını ve enfeksiyon riskini artırır.',
      'Kalbe bastırmak veya buz dizmek kanamayı kontrol etmez.',
    ],
    objective: 'Bası noktası kavramını açıklamak.',
    tags: ['kanama', 'basi-noktasi', 'atardamar'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-427',
    subject: 'ilkyardim',
    topic: 'kanama',
    difficulty: 'zor',
    stem: 'Bacaktaki şiddetli kanamada, doğrudan baskıya ek olarak hangi bölgedeki atardamara bası uygulanabilir?',
    options: [
      'Ayak bileğinin arkasındaki bölgeye',
      'Diz kapağının üstündeki bölgeye',
      'Koltuk altındaki bölgeye',
      'Kasık bölgesindeki atardamara',
    ],
    answerIndex: 3,
    explanation:
      'Bacağı besleyen ana atardamar kasık bölgesinden geçer; bacaktaki durdurulamayan şiddetli kanamada kasıktaki bu atardamara bası uygulanarak bacağa giden kan akımı azaltılabilir.',
    whyWrong: [
      'Ayak bileği ve diz üstü, ana atardamarın bası noktaları değildir.',
      'Koltuk altındaki atardamar kol kanamalarında kullanılır.',
    ],
    objective: 'Bacak kanamasında kasık bası noktasını bilmek.',
    tags: ['kanama', 'basi-noktasi', 'kasik'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-428',
    subject: 'ilkyardim',
    topic: 'kanama',
    difficulty: 'orta',
    stem: 'Kafa travması geçiren yaralının kulağından kan geliyorsa ilk yardımda ne yapılır?',
    options: [
      'Kulak pamukla sıkıca tıkanır',
      'Kulağın içi suyla yıkanır',
      'Kanama engellenmez; omurga şüphesi yoksa yaralı kanayan kulağı alta gelecek şekilde yatırılır ve 112 aranır',
      'Baş geriye itilerek kanamanın içeri akması sağlanır',
    ],
    answerIndex: 2,
    explanation:
      'Kafa travması sonrası kulaktan gelen kan veya sıvı, kafa içi basıncın boşalma yolu olabilir; bu nedenle tıkanmaz. Omurga yaralanması şüphesi yoksa yaralı kanayan kulak alta gelecek şekilde yatırılıp sıvının akmasına izin verilir ve derhal 112 aranır.',
    whyWrong: [
      'Kulağı tıkamak sıvının kafa içinde birikmesine yol açabilir.',
      'Kulağı yıkamak veya kanı içeri yönlendirmek zararlıdır.',
    ],
    objective: 'Kulaktan gelen kanamanın engellenmemesi ilkesini kavramak.',
    tags: ['kanama', 'kafa-travmasi', 'kulak'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-429',
    subject: 'ilkyardim',
    topic: 'kafa-travmasi',
    difficulty: 'orta',
    stem: 'Kazada başını çarpan ve ilk anda iyi görünen bir kişide, ilerleyen saatlerde ortaya çıkan hangi durum acil sağlık başvurusu gerektirir?',
    options: [
      'İştahının hafifçe açılması',
      'Giderek artan uyku hâli, tekrarlayan kusma ve dengesizlik',
      'Kısa süreli hapşırma',
      'Saç derisinde hafif hassasiyet',
    ],
    answerIndex: 1,
    explanation:
      'Kafa travmasında belirtiler saatler sonra ortaya çıkabilir; giderek artan uyuklama, tekrarlayan kusma, dengesizlik veya bilinç bulanıklığı kafa içi kanama işareti olabilir ve derhal sağlık kuruluşuna başvurmayı gerektirir.',
    whyWrong: [
      'İştah değişimi ve hapşırma tek başına tehlike işareti değildir.',
      'Hafif hassasiyet, izlenmesi gereken ama acil olmayan bir bulgudur.',
    ],
    objective: 'Kafa travmasında geç ortaya çıkan tehlike işaretlerini tanımak.',
    tags: ['kafa-travmasi', 'belirti', 'takip'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-430',
    subject: 'ilkyardim',
    topic: 'kafa-travmasi',
    difficulty: 'orta',
    stem: 'Beyin sarsıntısını düşündüren belirtiler hangi seçenekte birlikte verilmiştir?',
    options: [
      'Kısa süreli bilinç kaybı, olayı hatırlayamama, baş ağrısı ve bulantı',
      'Ayak tabanında kaşıntı ve üşüme hissi',
      'Uzun süreli açlık ve susuzluk',
      'Ellerde ciltte kuruma',
    ],
    answerIndex: 0,
    explanation:
      'Beyin sarsıntısında kısa süreli bilinç kaybı, kazayı hatırlayamama, baş ağrısı, bulantı ve sersemlik hissi görülebilir; bu belirtileri olan kişi mutlaka sağlık kuruluşunda değerlendirilmelidir.',
    whyWrong: [
      'Kaşıntı, üşüme ve cilt kuruması kafa travmasının tipik bulguları değildir.',
      'Açlık ve susuzluk beyin sarsıntısını düşündürmez.',
    ],
    objective: 'Beyin sarsıntısı belirtilerini tanımak.',
    tags: ['kafa-travmasi', 'beyin-sarsintisi', 'belirti'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-431',
    subject: 'ilkyardim',
    topic: 'omurga-yaralanmasi',
    difficulty: 'kolay',
    stem: 'Omurga yaralanması şüphesi olan yaralı, taşınması zorunlu olduğunda hangi yüzey üzerinde taşınmalıdır?',
    options: [
      'Yumuşak bir yatak üzerinde',
      'İki kişinin kol kilidi üzerinde oturtularak',
      'Sert ve düz bir zemin ya da sedye üzerinde, baş-boyun-gövde ekseni korunarak',
      'Bir battaniyeye sarılıp omuzda',
    ],
    answerIndex: 2,
    explanation:
      'Omurga yaralısı, taşınması zorunluysa sert ve düz bir yüzey (sedye, kapı benzeri düz zemin) üzerinde, baş-boyun-gövde ekseni bozulmadan ve yeterli sayıda kişiyle taşınır; bükülme kalıcı hasara yol açabilir.',
    whyWrong: [
      'Yumuşak yüzeyler omurganın bükülmesine izin verir.',
      'Oturtarak veya omuzda taşımak omurga eksenini bozar.',
    ],
    objective: 'Omurga yaralısının sert-düz yüzeyde taşındığını bilmek.',
    tags: ['omurga-yaralanmasi', 'tasima', 'sedye'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-432',
    subject: 'ilkyardim',
    topic: 'omurga-yaralanmasi',
    difficulty: 'zor',
    stem: 'Kaza geçiren motosiklet sürücüsünün kaskı ile ilgili doğru ilk yardım davranışı hangisidir?',
    options: [
      'Kask her durumda hemen çıkarılır',
      'Solunumu engelleyen bir durum yoksa kask çıkarılmaz',
      'Kask kırılarak baştan uzaklaştırılır',
      'Kask çıkarılıp yaralının başının altına destek olarak konur',
    ],
    answerIndex: 1,
    explanation:
      'Kaza geçiren motosikletlinin boyun omurları yaralanmış olabilir; kaskı çıkarma girişimi boynu oynatarak hasarı ağırlaştırabilir. Bu nedenle solunumu engelleyen zorunlu bir durum yoksa kask çıkarılmaz ve sağlık ekibi beklenir.',
    whyWrong: [
      'Kaskı her durumda çıkarmak boyun omurlarını tehlikeye atar.',
      'Kaskı kırmak veya baş altına koymak da boynu hareket ettirir.',
    ],
    objective: 'Motosiklet kazasında kaskın çıkarılmama kuralını kavramak.',
    tags: ['omurga-yaralanmasi', 'kask', 'boyun'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-433',
    subject: 'ilkyardim',
    topic: 'arac-icinden-cikarma',
    difficulty: 'orta',
    stem: 'İlk yardımda Rentek manevrası hangi amaçla kullanılır?',
    options: [
      'Kırık kola atel uygulamak için',
      'Burun kanamasını durdurmak için',
      'Bebekte hava yolunu açmak için',
      'Yaşamsal tehlike varsa yaralıyı omurga ekseni korunarak araç içinden çıkarmak için',
    ],
    answerIndex: 3,
    explanation:
      'Rentek manevrası; yangın, patlama riski ya da solunum durması gibi yaşamsal bir zorunluluk olduğunda, oturur hâldeki yaralıyı baş-boyun-gövde ekseni korunarak araçtan çıkarmak için kullanılan tekniktir. Zorunluluk yoksa yaralı araçta bırakılıp sağlık ekibi beklenir.',
    whyWrong: [
      'Atel uygulama ve burun kanaması ayrı ilk yardım konularıdır.',
      'Bebekte hava yolu açma, baş-çene pozisyonuyla ilgilidir.',
    ],
    objective: 'Rentek manevrasının amacını ve koşulunu bilmek.',
    tags: ['arac-icinden-cikarma', 'rentek', 'omurga'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-434',
    subject: 'ilkyardim',
    topic: 'arac-icinden-cikarma',
    difficulty: 'zor',
    stem: 'Rentek manevrasıyla yaralıyı araçtan çıkarmadan önce yapılması gerekenlerden biri hangisidir?',
    options: [
      'Yaralının ayaklarının pedallara sıkışıp sıkışmadığını kontrol etmek ve emniyet kemerini açmak',
      'Yaralının cebindeki eşyaları toplamak',
      'Aracın müzik sistemini kapatmak',
      'Yaralının ayakkabılarını çıkarmak',
    ],
    answerIndex: 0,
    explanation:
      'Çıkarma işleminden önce yaralının emniyet kemeri açılır ve ayaklarının pedallara sıkışıp sıkışmadığı kontrol edilir; sıkışmış bir ayak fark edilmeden çekme yapılırsa yaralanma ağırlaşır ve eksen korunamaz.',
    whyWrong: [
      'Eşya toplamak ve müzik sistemi çıkarma hazırlığıyla ilgisizdir.',
      'Ayakkabı çıkarmak uygulamanın bir adımı değildir.',
    ],
    objective: 'Rentek öncesi kemer ve pedal kontrolünü bilmek.',
    tags: ['arac-icinden-cikarma', 'rentek', 'hazirlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-435',
    subject: 'ilkyardim',
    topic: 'yanik',
    difficulty: 'kolay',
    stem: 'Birinci derece yanıkta ciltte görülen tipik bulgular hangileridir?',
    options: [
      'İçi su dolu kabarcıklar',
      'Kömürleşmiş siyah alanlar',
      'Kızarıklık, hafif şişlik ve ağrı',
      'Cildin tümüyle duyarsızlaşması',
    ],
    answerIndex: 2,
    explanation:
      'Birinci derece yanık cildin en üst tabakasını etkiler; bölgede kızarıklık, hafif şişlik ve dokunmakla artan ağrı görülür. Güneş yanığı bu grubun tipik örneğidir.',
    whyWrong: [
      'Su dolu kabarcıklar ikinci derece yanığın bulgusudur.',
      'Kömürleşme ve duyarsızlaşma üçüncü derece yanığı düşündürür.',
    ],
    objective: 'Birinci derece yanığın bulgularını tanımak.',
    tags: ['yanik', 'birinci-derece', 'belirti'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-436',
    subject: 'ilkyardim',
    topic: 'yanik',
    difficulty: 'orta',
    stem: 'Üçüncü derece yanıkta ağrının beklenenden az olmasının nedeni nedir?',
    options: [
      'Yanığın çok yüzeysel olması',
      'Derinin tüm katlarıyla birlikte sinir uçlarının da zarar görmüş olması',
      'Vücudun ağrıya zamanla alışması',
      'Bu bölgelerde hiç sinir bulunmaması',
    ],
    answerIndex: 1,
    explanation:
      'Üçüncü derece yanıkta deri tüm katlarıyla ve altındaki dokularla birlikte hasar görür; ağrıyı ileten sinir uçları da zarar gördüğünden derin yanık alanında ağrı beklenenden az olabilir. Bu, yanığın hafif değil ağır olduğunun işaretidir.',
    whyWrong: [
      'Yüzeysel yanıklarda ağrı tam tersine belirgindir.',
      'Ağrıya alışma veya sinir bulunmaması söz konusu değildir; sinirler hasarlanmıştır.',
    ],
    objective: 'Üçüncü derece yanıkta ağrı azlığının nedenini kavramak.',
    tags: ['yanik', 'ucuncu-derece', 'belirti'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-437',
    subject: 'ilkyardim',
    topic: 'yanik',
    difficulty: 'kolay',
    stem: 'Giysileri tutuşan bir kişi için doğru ilk yardım davranışı hangisidir?',
    options: [
      'Koşarak alevlerden uzaklaşmasını söylemek',
      'Üzerine kolonya dökmek',
      'Alevleri çıplak elle söndürmeye çalışmak',
      'Koşmasını engelleyip yere yatırmak; battaniye gibi bir örtüyle alevi boğmak ya da yerde yuvarlanmasını sağlamak',
    ],
    answerIndex: 3,
    explanation:
      'Koşmak alevleri rüzgârla büyütür; tutuşan kişi durdurulup yere yatırılır ve alev, battaniye gibi hava geçirmeyen bir örtüyle boğulur ya da kişinin yerde yuvarlanması sağlanır. Ardından yanık bölge soğutulur.',
    whyWrong: [
      'Koşmak alevin büyümesine neden olur.',
      'Kolonya alkollü ve yanıcıdır; çıplak elle müdahale ilk yardımcıyı da yakar.',
    ],
    objective: 'Tutuşan kişide durdur-yatır-boğ ilkesini uygulamak.',
    tags: ['yanik', 'alev', 'mudahale'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-438',
    subject: 'ilkyardim',
    topic: 'elektrik-carpmasi',
    difficulty: 'orta',
    stem: 'Ev tipi (düşük gerilim) elektrik akımına kapılan kişiye ulaşmak için akım kesilemiyorsa ne yapılabilir?',
    options: [
      'Kuru tahta veya plastik gibi yalıtkan bir cisimle kişinin akımla teması kesilir',
      'Kişi ıslak elle hızla çekilir',
      'Kablo metal bir çubukla itilir',
      'Kişinin üzerine su dökülür',
    ],
    answerIndex: 0,
    explanation:
      'Ev elektriğinde akım kesilemiyorsa, kuru zeminde durularak kuru tahta sopa veya plastik gibi yalıtkan bir cisimle kişinin akımla teması kesilebilir. Yüksek gerilim hatlarında ise bu bile yapılmaz; güvenli mesafede beklenip yetkililere haber verilir.',
    whyWrong: [
      'Islak el ve su, elektriği ileterek ilk yardımcıyı da akıma kaptırır.',
      'Metal çubuk iletken olduğu için kullanılmaz.',
    ],
    objective: 'Akım kesilemediğinde yalıtkan cisim kullanmayı bilmek.',
    tags: ['elektrik-carpmasi', 'yalitkan', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-439',
    subject: 'ilkyardim',
    topic: 'elektrik-carpmasi',
    difficulty: 'orta',
    stem: 'Elektrik çarpması geçiren ve kendini iyi hissettiğini söyleyen kişinin yine de sağlık kuruluşunda değerlendirilmesi neden gerekir?',
    options: [
      'Cilt yanığı her zaman çok büyük olduğu için',
      'Elektrik çarpması bulaşıcı olduğu için',
      'Akım, ciltteki küçük yara görüntüsüne rağmen vücut içinde ve kalp ritminde gizli hasar bırakmış olabileceği için',
      'Yalnızca resmî tutanak tutulması gerektiği için',
    ],
    answerIndex: 2,
    explanation:
      'Elektrik akımı vücudun içinden geçerken kalp ritmini bozabilir ve derin dokularda ciltten görünmeyen hasar bırakabilir; kişi kendini iyi hissetse bile sağlık kuruluşunda değerlendirilmesi gerekir.',
    whyWrong: [
      'Cilt yarası küçük olabilir; tehlike asıl olarak içeridedir.',
      'Elektrik çarpması bulaşıcı değildir; başvurunun nedeni tıbbidir.',
    ],
    objective: 'Elektrik çarpmasında gizli iç hasar riskini kavramak.',
    tags: ['elektrik-carpmasi', 'ic-hasar', 'kalp-ritmi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-440',
    subject: 'ilkyardim',
    topic: 'zehirlenme',
    difficulty: 'kolay',
    stem: 'Zehirlenmeler, zehrin vücuda giriş yoluna göre hangi üç grupta incelenir?',
    options: [
      'Göz, kulak ve burun yolu',
      'Sindirim, solunum ve cilt (deri) yolu',
      'Saç, tırnak ve diş yolu',
      'Kas, kemik ve eklem yolu',
    ],
    answerIndex: 1,
    explanation:
      'Zehirlenmeler; ağızdan alınan maddelerle sindirim yolu, gaz ve buharlarla solunum yolu, temas eden kimyasallarla cilt yolu olmak üzere üç grupta incelenir. Giriş yolu, uygulanacak ilk yardımı belirler.',
    whyWrong: [
      'Göz-kulak-burun ya da saç-tırnak-diş şeklinde bir sınıflandırma yoktur.',
      'Kas ve kemik, zehrin giriş yolu olarak tanımlanmaz.',
    ],
    objective: 'Zehirlenme yollarını sınıflandırmak.',
    tags: ['zehirlenme', 'siniflandirma', 'giris-yolu'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-441',
    subject: 'ilkyardim',
    topic: 'zehirlenme',
    difficulty: 'orta',
    stem: 'Cildine tarım ilacı gibi zehirli bir kimyasal bulaşan kişiye ilk yardımda ne yapılır?',
    options: [
      'Kimyasalın kendiliğinden kuruması beklenir',
      'Bölge alkolle ovularak silinir',
      'Bölgeye yağlı krem sürülür',
      'İlk yardımcı kendi elini koruyarak bulaşan giysileri çıkarır ve bölgeyi bol suyla yıkar',
    ],
    answerIndex: 3,
    explanation:
      'Cilt yoluyla zehirlenmede kimyasal bulaşmış giysiler çıkarılır ve bölge bol akan suyla yıkanarak madde ciltten uzaklaştırılır; ilk yardımcı bu sırada eldiven gibi bir korumayla kendisinin kimyasala temasını önler ve 112 aranır.',
    whyWrong: [
      'Beklemek maddenin emilimini artırır.',
      'Alkolle ovmak veya krem sürmek kimyasalı ciltte tutar ve yayar.',
    ],
    objective: 'Cilt yoluyla zehirlenmede yıkama ve öz korunmayı uygulamak.',
    tags: ['zehirlenme', 'cilt-yolu', 'yikama'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-442',
    subject: 'ilkyardim',
    topic: 'zehirlenme',
    difficulty: 'orta',
    stem: 'Egzoz gazındaki karbonmonoksitin özellikle tehlikeli olmasının nedeni nedir?',
    options: [
      'Renksiz ve kokusuz olduğu için fark edilmeden zehirlenmeye yol açması',
      'Çok keskin kokusuyla panik yaratması',
      'Yalnızca gözleri etkilemesi',
      'Havayla hiç karışmaması',
    ],
    answerIndex: 0,
    explanation:
      'Karbonmonoksit renksiz ve kokusuz bir gazdır; kişi farkına varmadan soluyarak zehirlenir ve baş ağrısı, uyku hâli derken bilinç kaybına ilerleyebilir. Bu nedenle kapalı yerde motor çalıştırılmaz.',
    whyWrong: [
      'Keskin kokusu olsaydı erken fark edilirdi; tehlike tam tersinden kaynaklanır.',
      'Karbonmonoksit solunum yoluyla tüm vücudu etkiler; yalnızca gözle sınırlı değildir.',
    ],
    objective: 'Karbonmonoksitin sinsi karakterini kavramak.',
    tags: ['zehirlenme', 'karbonmonoksit', 'egzoz'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-443',
    subject: 'ilkyardim',
    topic: 'bocek-sokmasi-alerji',
    difficulty: 'kolay',
    stem: 'Arı sokmasında deride kalan iğne nasıl uzaklaştırılmalıdır?',
    options: [
      'Parmaklarla sıkılarak',
      'Isıtılmış bir iğneyle deşilerek',
      'Kart gibi sert bir cismin kenarıyla kazınarak',
      'İğneye dokunulmaz, üzeri bantla kapatılır',
    ],
    answerIndex: 2,
    explanation:
      'Deride kalan arı iğnesi, kart benzeri sert bir cismin kenarıyla kazınarak çıkarılır; parmakla sıkmak iğnedeki zehir kesesini boşaltarak daha fazla zehrin geçmesine yol açabilir. Ardından bölge yıkanır ve soğuk uygulanır.',
    whyWrong: [
      'Sıkmak zehir miktarını artırabilir.',
      'Deşmek veya iğnenin üzerini kapatmak doğru uygulamalar değildir.',
    ],
    objective: 'Arı iğnesinin kazınarak çıkarıldığını bilmek.',
    tags: ['bocek-sokmasi-alerji', 'ari', 'igne'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-444',
    subject: 'ilkyardim',
    topic: 'bocek-sokmasi-alerji',
    difficulty: 'kolay',
    stem: 'Arı sokmasından kısa süre sonra yüzünde ve dilinde şişme, ciltte yaygın kızarıklık ve nefes darlığı başlayan kişide ne yapılmalıdır?',
    options: [
      'Belirtiler kendiliğinden geçene kadar beklenir',
      'Ağır alerjik tepki düşünülerek vakit kaybetmeden 112 aranır',
      'Kişiye bol yemek yedirilir',
      'Kişiye sıcak duş aldırılır',
    ],
    answerIndex: 1,
    explanation:
      'Yüz ve dilde şişme, yaygın kızarıklık ve nefes darlığı, tüm vücudu etkileyen ağır alerjik tepkinin işaretidir; hava yolu kısa sürede tıkanabileceği için hiç beklemeden 112 aranır ve kişi yalnız bırakılmaz.',
    whyWrong: [
      'Beklemek hava yolunun kapanmasına yol açabilir.',
      'Yemek yedirmek veya duş aldırmak tabloyu düzeltmez, zaman kaybettirir.',
    ],
    objective: 'Ağır alerjik tepki işaretlerinde 112 gerekliliğini kavramak.',
    tags: ['bocek-sokmasi-alerji', 'alerjik-tepki', '112'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-445',
    subject: 'ilkyardim',
    topic: 'bocek-sokmasi-alerji',
    difficulty: 'kolay',
    stem: 'Basit bir böcek sokmasında ilk yardım olarak hangisi uygundur?',
    options: [
      'Bölgeyi su ve sabunla yıkayıp soğuk uygulama yapmak ve kaşımamak',
      'Bölgeyi rahatlayana kadar kaşımak',
      'Bölgeye sıcak kompres koymak',
      'Bölgeyi çamurla kapatmak',
    ],
    answerIndex: 0,
    explanation:
      'Basit böcek sokmasında bölge su ve sabunla temizlenir, şişme ve kaşıntıyı azaltmak için soğuk uygulanır; kaşımak cildi zedeleyip enfeksiyona zemin hazırladığından kaçınılır.',
    whyWrong: [
      'Kaşımak ve çamur sürmek enfeksiyon riskini artırır.',
      'Sıcak uygulama şişmeyi ve kaşıntıyı artırabilir.',
    ],
    objective: 'Böcek sokmasında temel bakımı uygulamak.',
    tags: ['bocek-sokmasi-alerji', 'soguk-uygulama', 'hijyen'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-446',
    subject: 'ilkyardim',
    topic: 'donma-hipotermi',
    difficulty: 'kolay',
    stem: 'Birinci derece (yüzeysel) donmada görülen belirtiler hangileridir?',
    options: [
      'Ciltte içi sıvı dolu büyük kabarcıklar',
      'Dokunun siyahlaşması',
      'Yüksek ateş ve terleme',
      'Ciltte solukluk, uyuşukluk ve iğnelenme hissi',
    ],
    answerIndex: 3,
    explanation:
      'Birinci derece donmada cilt soluklaşır, bölgede uyuşukluk ile iğnelenme-karıncalanma hissi olur; doku henüz kalıcı hasar görmemiştir. Kişi ılık ortama alınıp bölge yavaşça ısıtılırsa bulgular geriler.',
    whyWrong: [
      'Su dolu kabarcıklar ve siyahlaşma, daha ileri derecelerdeki donmanın bulgularıdır.',
      'Yüksek ateş ve terleme donmayla bağdaşmaz.',
    ],
    objective: 'Yüzeysel donmanın belirtilerini tanımak.',
    tags: ['donma-hipotermi', 'birinci-derece', 'belirti'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-447',
    subject: 'ilkyardim',
    topic: 'donma-hipotermi',
    difficulty: 'orta',
    stem: 'Vücut ısısı ileri derecede düşmüş (hipotermideki) bir kişiye yapılan uygulamalardan hangisi yanlıştır?',
    options: [
      'Kişiyi rüzgârdan korunan ılık bir ortama almak',
      'Isınması için alkollü içecek içirmek',
      'Islak giysilerini kuru giysilerle değiştirmek',
      'Battaniyeye sarıp yavaş yavaş ısıtmak',
    ],
    answerIndex: 1,
    explanation:
      'Alkol geçici sıcaklık hissi verse de damarları genişleterek ısı kaybını hızlandırır ve bilinci baskılar; hipotermideki kişiye kesinlikle alkollü içecek verilmez. Doğru yaklaşım kuru giysi, örtü ve yavaş ısıtmadır.',
    whyWrong: [
      'Ilık ortam, kuru giysi ve battaniye doğru uygulamalardır.',
      'Isıtmanın yavaş ve kademeli olması gerekir; bu bir hata değildir.',
    ],
    objective: 'Hipotermide alkol verilmemesi gerektiğini kavramak.',
    tags: ['donma-hipotermi', 'alkol', 'yanlis-uygulama'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-448',
    subject: 'ilkyardim',
    topic: 'sicak-carpmasi',
    difficulty: 'kolay',
    stem: 'Sıcak bir yaz gününde park hâlindeki kapalı araçta çocuk ya da yolcu bırakmak neden tehlikelidir?',
    options: [
      'Araç camları buğulanabileceği için',
      'Akü hızla boşalacağı için',
      'Araç içi sıcaklık kısa sürede aşırı yükselerek sıcak çarpmasına yol açabileceği için',
      'Koltuk döşemeleri zarar görebileceği için',
    ],
    answerIndex: 2,
    explanation:
      'Güneş altındaki kapalı aracın içi, dış ortamdan çok daha hızlı ısınır ve dakikalar içinde tehlikeli sıcaklıklara ulaşır; içeride kalan kişide, özellikle çocuklarda, yaşamı tehdit eden sıcak çarpması gelişebilir.',
    whyWrong: [
      'Cam buğusu ve akü durumu can güvenliğiyle ilgili temel tehlike değildir.',
      'Döşeme hasarı maddi bir konudur, gerekçe olamaz.',
    ],
    objective: 'Kapalı araçta ısı birikiminin sıcak çarpması riskini kavramak.',
    tags: ['sicak-carpmasi', 'kapali-arac', 'cocuk-guvenligi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-449',
    subject: 'ilkyardim',
    topic: 'goz-kulak-yabanci-cisim',
    difficulty: 'kolay',
    stem: 'Göze toz ya da kirpik gibi serbest bir yabancı cisim kaçtığında ilk yardım olarak ne yapılır?',
    options: [
      'Göz ovulmaz; bol temiz suyla yıkanır, cisim çıkmazsa göz kapatılıp sağlık kuruluşuna gidilir',
      'Göz rahatlayana kadar kuvvetlice ovulur',
      'Cisim sivri bir aletle alınmaya çalışılır',
      'Göze sıcak hava tutulur',
    ],
    answerIndex: 0,
    explanation:
      'Göze kaçan toz veya kirpik için göz kesinlikle ovulmaz; bol temiz suyla yıkanarak cismin akıp gitmesi sağlanır. Çıkmazsa göz temiz bir bezle kapatılıp kişi sağlık kuruluşuna yönlendirilir.',
    whyWrong: [
      'Ovmak cismin göz yüzeyini çizmesine yol açar.',
      'Sivri aletle müdahale ve sıcak hava göz için tehlikelidir.',
    ],
    objective: 'Gözdeki serbest yabancı cisimde yıkama ilkesini uygulamak.',
    tags: ['goz-kulak-yabanci-cisim', 'goz', 'yikama'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-450',
    subject: 'ilkyardim',
    topic: 'goz-kulak-yabanci-cisim',
    difficulty: 'kolay',
    stem: 'Kulağına böcek kaçan ya da yabancı cisim giren kişide doğru ilk yardım davranışı hangisidir?',
    options: [
      'Kulak çubuğuyla cismi çıkarmaya çalışmak',
      'Kulağa vurarak cismi düşürmeye çalışmak',
      'Kulağın içine cımbız sokmak',
      'Kulağı karıştırmadan kişiyi sağlık kuruluşuna yönlendirmek',
    ],
    answerIndex: 3,
    explanation:
      'Kulağa giren cisim veya böcek, çubuk ya da cımbızla çıkarılmaya çalışılırsa daha derine itilebilir ve kulak zarı zarar görebilir; kulak karıştırılmadan kişi sağlık kuruluşuna yönlendirilir.',
    whyWrong: [
      'Çubuk ve cımbız cismi derine iter, kulak zarını yaralayabilir.',
      'Kulağa vurmak da cismin konumunu kötüleştirebilir.',
    ],
    objective: 'Kulağa kaçan cisimde müdahale etmeme ilkesini kavramak.',
    tags: ['goz-kulak-yabanci-cisim', 'kulak', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-451',
    subject: 'ilkyardim',
    topic: 'karin-yaralanmasi',
    difficulty: 'zor',
    stem: 'Karın bölgesindeki derin yaralanmada organlar dışarı çıkmışsa ilk yardımda ne yapılır?',
    options: [
      'Organlar elle yavaşça içeri itilir',
      'Organlar içeri itilmez; üzerleri nemli ve temiz bir bezle örtülüp 112 beklenir',
      'Organların üzerine kuru pamuk bastırılır',
      'Yaralı oturtulup su içirilir',
    ],
    answerIndex: 1,
    explanation:
      'Dışarı çıkan organlar kesinlikle içeri itilmez; bu, enfeksiyona ve ek hasara yol açar. Organların üzeri kurumalarını önlemek için nemli ve temiz bir bezle örtülür, yaralıya ağızdan bir şey verilmez ve 112 beklenir.',
    whyWrong: [
      'İçeri itmek mikropları da içeri taşır ve dokulara zarar verir.',
      'Kuru pamuk dokuya yapışır; su içirmek olası ameliyat öncesinde sakıncalıdır.',
    ],
    objective: 'Karın yaralanmasında dışarı çıkan organa yaklaşımı bilmek.',
    tags: ['karin-yaralanmasi', 'nemli-ortme', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-452',
    subject: 'ilkyardim',
    topic: 'uzuv-kopmasi',
    difficulty: 'orta',
    stem: 'Kaza sonucu kopan bir parmak, sağlık kuruluşuna nasıl ulaştırılmalıdır?',
    options: [
      'Doğrudan buzun içine gömülerek',
      'Sıcak su dolu bir kapta bekletilerek',
      'Temiz nemli beze sarılıp su geçirmez torbaya konarak; bu torba da buzlu su bulunan bir kabın içinde yaralıyla birlikte gönderilerek',
      'Açık hâlde, gölge bir yerde taşınarak',
    ],
    answerIndex: 2,
    explanation:
      'Kopan parça temiz ve nemli bir beze sarılır, su geçirmez bir torbaya konur; torba da içinde buzlu su bulunan ikinci bir kaba yerleştirilir. Parça buzla doğrudan temas ettirilmez ve yaralıyla birlikte aynı araçla gönderilir.',
    whyWrong: [
      'Doğrudan buz teması dokuyu dondurarak dikilme şansını azaltır.',
      'Sıcakta veya açıkta bekletmek dokunun bozulmasını hızlandırır.',
    ],
    objective: 'Kopan uzvun doğru saklama ve taşıma yöntemini bilmek.',
    tags: ['uzuv-kopmasi', 'tasima', 'soguk-zincir'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-453',
    subject: 'ilkyardim',
    topic: 'bayilma',
    difficulty: 'kolay',
    stem: 'Bayılmadan hemen önce sık görülen uyarıcı belirtiler hangileridir?',
    options: [
      'Baş dönmesi, göz kararması, soğuk terleme ve kulak çınlaması',
      'İştah artışı ve neşelenme',
      'Görmede keskinleşme',
      'Kollarda güç artışı',
    ],
    answerIndex: 0,
    explanation:
      'Bayılma öncesinde beyne giden kan azalmaya başladığında baş dönmesi, göz kararması, soğuk terleme, kulak çınlaması ve yüzde solukluk görülür; bu belirtileri fark eden kişi güvenli bir şekilde oturmalı veya uzanmalıdır.',
    whyWrong: [
      'İştah artışı ve neşelenme bayılma habercisi değildir.',
      'Görme keskinleşmez; aksine kararma olur.',
    ],
    objective: 'Bayılma öncesi uyarıcı belirtileri tanımak.',
    tags: ['bayilma', 'belirti', 'on-belirti'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-454',
    subject: 'ilkyardim',
    topic: 'bayilma',
    difficulty: 'kolay',
    stem: 'Bayılacak gibi olduğunu söyleyen bir kişiye ilk yardımda ne yaptırılır?',
    options: [
      'Hızlı adımlarla yürümesi',
      'Ayakta durup derin nefes alması',
      'Araç kullanıyorsa yola devam etmesi',
      'Güvenli bir yerde oturması ya da sırtüstü uzanması; oturuyorsa başını öne eğmesi',
    ],
    answerIndex: 3,
    explanation:
      'Bayılma hissi olan kişi düşüp yaralanmadan önce güvenli bir yerde oturtulur veya sırtüstü uzandırılır; oturuyorsa başını dizlerine doğru öne eğmesi beyne kan akışını destekler. Araç kullanan sürücü derhal güvenli bir yerde durmalıdır.',
    whyWrong: [
      'Yürümek ve ayakta kalmak düşme ile yaralanma riskini artırır.',
      'Bu durumda araç kullanmayı sürdürmek kendisi ve trafik için tehlikelidir.',
    ],
    objective: 'Bayılma hissinde güvenli pozisyon almayı kavramak.',
    tags: ['bayilma', 'pozisyon', 'onlem'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-455',
    subject: 'ilkyardim',
    topic: 'inme',
    difficulty: 'orta',
    stem: 'İnme (felç) belirtileri gösteren bir kişide 112 aranırken hangi bilginin not edilmesi tedavi açısından özellikle önemlidir?',
    options: [
      'Kişinin doğum yeri',
      'Belirtilerin başladığı saat',
      'Kullandığı aracın plakası',
      'O günkü hava sıcaklığı',
    ],
    answerIndex: 1,
    explanation:
      'İnmede bazı tedaviler yalnızca belirtilerin başlangıcından sonraki sınırlı bir zaman diliminde uygulanabilir; bu nedenle yüz kayması, kolda güçsüzlük veya konuşma bozukluğunun ilk fark edildiği saat not edilip sağlık ekibine bildirilmelidir.',
    whyWrong: [
      'Doğum yeri ve plaka bilgisi tedaviyi yönlendirmez.',
      'Hava sıcaklığının inme tedavisiyle doğrudan ilgisi yoktur.',
    ],
    objective: 'İnmede belirti başlangıç saatinin önemini kavramak.',
    tags: ['inme', 'zaman', '112'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
];
