/**
 * ÖZGÜN trafik adabı soruları — 6. genişletme (Program 2 · Faz 9). ROADMAP C.4/E.6.
 * Kaynak = MEB Trafik Adabı müfredatı; KENDİ İFADEMİZLE.
 */
import type { QuestionInput } from '@ea/content-schema';

const SRC = 'MEB Trafik Adabı müfredatı (özgün ifade)';

export const ADAB_QUESTIONS_6: QuestionInput[] = [
  {
    id: 'adab-601',
    subject: 'adab',
    topic: 'arac-anonimligi',
    difficulty: 'kolay',
    stem: 'Yayayken kimseye bağırmayan bir kişi, direksiyona geçince aynı insanlara kolayca öfkelenebiliyor. Bu değişimin en önemli nedeni nedir?',
    options: [
      'Sürücülerin karakteri yayalardan tümüyle farklıdır',
      'Araç içinde insanın sabrı doğal ve kaçınılmaz biçimde azalır',
      'Araç, kişiye bir tür anonimlik ve zırh duygusu verir; yüz yüze olmadığı için insan kendini davranışlarından daha az sorumlu hisseder',
      'Yayaların trafikte hiçbir hakkı olmadığı içindir',
    ],
    answerIndex: 2,
    explanation:
      'Cam ve metalin arkasında insan, karşısındakini bir yüz değil bir "araç" olarak görür; göz göze gelme, tanınma ve utanç kaybolunca öfkenin freni de gevşer. Oysa o aracın içinde de bir insan vardır.',
    whyWrong: [
      'Aynı kişi hem yaya hem sürücü olduğuna göre değişen şey karakter değil, içinde bulunulan durumdur.',
      'Sabrın azalması kaçınılmaz değildir; anonimlik duygusunun farkına varan sürücü öfkesini yönetebilir.',
    ],
    objective: 'Aracın verdiği anonimlik duygusunun saldırganlığı nasıl körüklediğini kavramak.',
    tags: ['arac-anonimligi', 'ofke', 'psikoloji'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-602',
    subject: 'adab',
    topic: 'arac-anonimligi',
    difficulty: 'orta',
    stem: 'Bir sürücü tıkalı trafikte camını açıp yandaki sürücüye ağır sözler söylüyor; aynı kişi markette sıra beklerken böyle davranmayı asla düşünmez. Bu çelişkiyi aşmanın en doğru yolu nedir?',
    options: [
      'Direksiyondaki kişinin de karşısındakinin de birer insan olduğunu hatırlamak; "onu tanısaydım, yüz yüze olsaydım böyle davranır mıydım?" diye kendine sormak',
      'Trafikte farklı kurallar geçerli olduğu için bu davranışı normal saymak',
      'Camları kapalı tutup sesin dışarı çıkmamasını sağlamayı yeterli görmek',
      'Nezaketi yalnızca tanıdık biriyle karşılaşma ihtimali olduğunda göstermek',
    ],
    answerIndex: 0,
    explanation:
      'Markette sıra beklerken devreye giren nezaket, aslında karşımızdakini bir yüz olarak görmemizden doğar. Direksiyondaki insanı bir engel değil de bir birey olarak görmeyi hatırlamak, anonimliğin ürettiği kabalığı çözer.',
    whyWrong: [
      'Trafik ayrı bir ahlak alanı değildir; aynı değerler yolda da geçerlidir.',
      'Sesi içeride tutmak öfkeyi gizler ama gerçek çözüm, öfkenin kaynağındaki "muhatabı yok sayma" tutumunu değiştirmektir.',
      'Nezaketi yalnızca tanınma ihtimaline bağlamak onu bir gösteriye indirger; asıl olgunluk kimse tanımazken de aynı kalmaktır.',
    ],
    objective: 'Anonimlik duygusunu, karşıdakini birey olarak görerek dengelemeyi öğrenmek.',
    tags: ['arac-anonimligi', 'empati', 'ozdenetim'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-603',
    subject: 'adab',
    topic: 'stres-karar-kalitesi',
    difficulty: 'orta',
    stem: 'Yoğun stres altındaki bir sürücünün karar verme kalitesi hakkında en doğru bilgi hangisidir?',
    options: [
      'Stres dikkati artırdığı için kararlar daha isabetli olur',
      'Stresin sürüş kararlarına hiçbir etkisi yoktur',
      'Stres yalnızca acemi sürücülerin kararlarını bozar',
      'Stres, görüş alanını daraltır ve aceleci kararlara yol açar; sürücü riskleri olduğundan küçük, kendi becerisini olduğundan büyük görmeye başlar',
    ],
    answerIndex: 3,
    explanation:
      'Stres altında beyin "hayatta kalma" moduna geçer; çevreyi tarama yeteneği daralır, sabır yerini dürtüye bırakır. Bu yüzden gergin bir sürücü, sakinken asla yapmayacağı riskli hamleleri mantıklı sanabilir.',
    whyWrong: [
      'Ölçülü bir uyarılma faydalı olsa da yoğun stres dikkati daraltır, keskinleştirmez.',
      'Stresin etkisi deneyimden bağımsızdır; usta sürücünün de yargısını bozar.',
    ],
    objective: 'Stresin karar kalitesini nasıl düşürdüğünü kavramak.',
    tags: ['stres-karar-kalitesi', 'risk-algisi', 'psikoloji'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-604',
    subject: 'adab',
    topic: 'stres-karar-kalitesi',
    difficulty: 'zor',
    stem: 'İş yerinden çok gergin çıktınız; trafikte de küçük bir tartışma yaşadınız ve şimdi öfkeyle karışık bir stres içindesiniz. Kritik bir kavşağa yaklaşıyorsunuz. Karar kalitenizi korumak için en doğru yaklaşım hangisidir?',
    options: [
      'Bir an önce eve varmak için tempoyu artırıp kavşakları hızlı geçmek',
      'Gerginliğin yargınızı bozduğunu kabul edip hızı düşürmek, takip mesafesini artırmak ve mümkünse güvenli bir yerde durup birkaç dakika kendinize gelmek',
      'Müziği açıp dikkatinizi olaydan uzaklaştırmaya çalışarak normal sürüşe devam etmek',
      'Öfkeyi bir sonraki yavaş sürücüde boşaltarak rahatlamak',
    ],
    answerIndex: 1,
    explanation:
      'En tehlikeli an, insanın stresli olduğunu fark etmediği andır. Gerginliğin kararları bozduğunu bilerek geçici olarak daha zayıf bir sürücü olduğunuzu kabul etmek, hızı ve beklentileri buna göre ayarlamayı getirir; bu, olgunluğun ta kendisidir.',
    whyWrong: [
      'Tempoyu artırmak, zaten daralmış olan dikkatin üzerine bir de hız riskini ekler.',
      'Müzik dikkati olaydan uzaklaştırmaz, yalnızca böler; stres bedende sürmeye devam eder.',
      'Öfkeyi bir başkasında boşaltmak, kendi gerginliğinizi bir yabancıya ve trafiğe bulaştırmaktır.',
    ],
    objective:
      'Stres altında karar kalitesindeki düşüşü fark edip savunmacı önlem almayı öğrenmek.',
    tags: ['stres-karar-kalitesi', 'ozdenetim', 'defansif-surus'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-605',
    subject: 'adab',
    topic: 'zaman-baskisi-kok-cozum',
    difficulty: 'kolay',
    stem: 'Sürekli "trafiğe yetişemiyorum, hep aceledeyim" diyen bir sürücünün bu sorunu kökten çözmesinin en sağlıklı yolu nedir?',
    options: [
      'Trafikte daha atik ve hızlı sürerek zamanı yolda kazanmak',
      'Kestirme ama riskli ara yolları tercih etmek',
      'Yola birkaç dakika erken çıkmak; zaman baskısını yolda değil, evden çıkış saatinde çözmek',
      'Sarı ışıklarda hızlanıp mümkün olduğunca çok kavşağı geçmek',
    ],
    answerIndex: 2,
    explanation:
      'Acelenin kaynağı çoğu zaman trafik değil, geç çıkıştır. On dakika erken yola çıkmak, yolda yapılacak onlarca riskli manevranın ihtiyacını ortadan kaldırır; en güvenli hız ayarı evden başlar.',
    whyWrong: [
      'Hızlı sürmek kazanılan süreyi belirsiz kılar ama riski kesinleştirir.',
      'Riskli kestirmeler ve sarı ışık yarışı, birkaç dakikayı kazaya çevirebilecek kumarlardır.',
    ],
    objective: 'Zaman baskısını kök nedeninde, erken çıkışla çözmeyi benimsemek.',
    tags: ['zaman-baskisi-kok-cozum', 'planlama', 'sabir'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-606',
    subject: 'adab',
    topic: 'zaman-baskisi-kok-cozum',
    difficulty: 'orta',
    stem: 'Önemli bir randevunuza geç kaldınız ve trafikte her kırmızı ışık sizi daha da geriyor. Hem bugünü kurtaracak hem de bu durumun tekrarını önleyecek en olgun yaklaşım hangisidir?',
    options: [
      'Kaybedilen zamanı telafi etmek için ilk fırsatta hız sınırını aşmak',
      'Bugün için gecikmeyi kabullenip güvenli sürmek, gerekirse haber vermek; bundan sonrası için de çıkış saatini öne almayı alışkanlık hâline getirmek',
      'Randevu sahibini arayıp trafiği bahane ederek sorumluluğu tümüyle trafiğe yüklemek',
      'Şerit şerit dolaşıp en hızlı ilerleyen kuyruğu kollamak',
    ],
    answerIndex: 1,
    explanation:
      'Geç kalmışlık artık değiştirilemez; değiştirilebilecek tek şey, o gecikmeye verilen tepkidir. Bir telefonla haber vermek karşı tarafa saygıdır; asıl çözüm ise yarın aynı stresi yaşamamak için erken çıkmayı huy edinmektir.',
    whyWrong: [
      'Hız sınırını aşmak birkaç dakika kazandırır ama kaybı ölümcül olabilir; geç kalmak bunun yanında küçük kalır.',
      'Sürekli şerit değiştirmek ortalamada zaman kazandırmaz; yalnızca gerginliği ve riski artırır.',
    ],
    objective: 'Zaman baskısı anını güvenle yönetip kök çözümü alışkanlığa dönüştürmek.',
    tags: ['zaman-baskisi-kok-cozum', 'sorumluluk', 'ofke-kontrolu'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-607',
    subject: 'adab',
    topic: 'agresif-surucuden-kacinma',
    difficulty: 'kolay',
    stem: 'Arkanızdaki sürücü sürekli dibinize girip selektör yapıyor, agresif biçimde geçmek istiyor. En güvenli ve olgun davranış hangisidir?',
    options: [
      'Uygun olan ilk yerde sağa geçip yol vermek; agresif sürücüyle inatlaşmak yerine onu güvenle önünüzden göndermek',
      'Hızınızı iyice düşürüp ona ders vermek',
      'Siz de hızlanıp aranızdaki mesafeyi zorlayarak korumaya çalışmak',
      'Fren lambasını birkaç kez yakıp onu tehditkâr biçimde uyarmak',
    ],
    answerIndex: 0,
    explanation:
      'Agresif sürücüyle kazanılacak bir yarış yoktur; kazanç, onu bir an önce hayatınızdan çıkarmaktır. Yol verip geçmesini sağlamak zayıflık değil, tehlikeyi arkanızda bırakmanın en akıllı yoludur.',
    whyWrong: [
      'Hızı düşürerek "ders vermek", öfkeli sürücüyü daha da tehlikeli hamlelere kışkırtır.',
      'Onunla birlikte hızlanmak, agresif sürücünün temposuna ortak olup riski paylaşmaktır.',
    ],
    objective: 'Agresif sürücüden inatlaşmadan, yol vererek uzaklaşmayı öğrenmek.',
    tags: ['agresif-surucuden-kacinma', 'defansif-surus', 'ofke-kontrolu'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-608',
    subject: 'adab',
    topic: 'agresif-surucuden-kacinma',
    difficulty: 'orta',
    stem: 'Yan şeritteki bir sürücü tehlikeli manevralar yapıp adeta sizinle didişmeye çalışıyor; birkaç kez göz teması kurup el hareketi yapıyor. En doğru tutum hangisidir?',
    options: [
      'Göz teması kurup ne istediğini anlamaya ve karşılık vermeye çalışmak',
      'El hareketine el hareketiyle karşılık verip haklı olduğunuzu göstermek',
      'Hiçbir etkileşime girmeden bakışlarınızı yola çevirmek, hızınızı ayarlayıp aranıza mesafe koymak ve gerekiyorsa güzergâhı değiştirerek ondan uzaklaşmak',
      'Aynı hızda yanında kalıp geri adım atmadığınızı hissettirmek',
    ],
    answerIndex: 2,
    explanation:
      'Agresif sürücünün istediği şey tepkidir; ona verilecek her karşılık oyunu sürdürür. Etkileşimi tümüyle kesip mesafe açmak, çatışmayı besleyecek yakıtı ortadan kaldırır. Cevapsız kalan kışkırtma söner.',
    whyWrong: [
      'Göz teması ve el hareketine karşılık, karşı tarafın aradığı muhatap olmayı kabul etmektir; gerilimi tırmandırır.',
      'Yanında sabit kalıp geri adım atmamak bir onur meselesi değildir; iki aracı da tehlikede tutan bir inattır.',
    ],
    objective: 'Kışkırtan agresif sürücüyle etkileşimi kesip uzaklaşmayı benimsemek.',
    tags: ['agresif-surucuden-kacinma', 'yol-ofkesi', 'sakinlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-609',
    subject: 'adab',
    topic: 'rekabet-anlamsizligi',
    difficulty: 'kolay',
    stem: 'Kırmızı ışıkta yanınızdaki sürücü motorunu gaza basarak sizi bir "kalkış yarışına" davet ediyor. Olgun bir sürücü ne yapar?',
    options: [
      'Yeşil yanınca hızlıca kalkıp yarışı kazanmaya çalışmak',
      'Daveti görmezden gelip normal ve sakin biçimde kalkmak; trafikte kazanılacak bir yarış olmadığını bilmek',
      'Ondan biraz önde kalabilmek için ışığa yakın hafifçe ilerlemek',
      'Aynı şekilde motoru gazlayıp kararlılığınızı göstermek',
    ],
    answerIndex: 1,
    explanation:
      'Trafikteki yarışın ödülü yoktur; bir sonraki kırmızı ışıkta yine yan yana gelirsiniz. Daveti reddetmek geri adım değil, anlamsız bir riski en baştan elemektir. Gerçek üstünlük, oyuna hiç girmemektir.',
    whyWrong: [
      'Yarışı kazanmak, birkaç saniyelik bir gurur için kavşağı riskli bir alana çevirir.',
      'Motoru gazlayıp karşılık vermek, çocukça bir meydan okumaya ortak olmaktır.',
    ],
    objective: 'Trafikteki rekabet dürtüsünün anlamsızlığını kavrayıp reddetmeyi öğrenmek.',
    tags: ['rekabet-anlamsizligi', 'ozdenetim', 'kalkis'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-610',
    subject: 'adab',
    topic: 'rekabet-anlamsizligi',
    difficulty: 'orta',
    stem: 'Bir sürücü, kendini sollayan her aracı bir yenilgi gibi görüp yeniden öne geçmeye çalışıyor. Bu "geçilme" duygusuyla ilgili en doğru değerlendirme hangisidir?',
    options: [
      'Öne geçmek haklı bir tepkidir; kimse geçilmeyi kabul etmek zorunda değildir',
      'Bu duygu yalnızca genç sürücülerde görülür ve zararsızdır',
      'Trafikte konum, gerçek bir üstünlük göstergesidir',
      'Trafik bir yarış değil, ortak bir yolculuktur; geçilme duygusu egodan doğar ve gereksiz risk almaya yol açar — kimin önde olduğunun varış açısından bir önemi yoktur',
    ],
    answerIndex: 3,
    explanation:
      'Yol, sıralamanın tutulduğu bir pist değildir; sizi geçen araç birkaç kilometre sonra bir ışıkta yine yanınızdadır. Geçildim duygusu tümüyle egonun ürettiği bir yanılsamadır ve bu yanılsama için can riske atılmaz.',
    whyWrong: [
      'Öne geçme ihtiyacı haklı tepki değil, kontrol edilmesi gereken bir dürtüdür.',
      'Bu duygu her yaştan sürücüde görülebilir ve risk aldırdığı için hiç de zararsız değildir.',
      'Trafikte önde olmak bir statü değildir; herkes aynı yolu paylaşan yolculardır.',
    ],
    objective: 'Geçilme duygusunun egoya dayalı ve anlamsız olduğunu kavramak.',
    tags: ['rekabet-anlamsizligi', 'ego', 'risk-algisi'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-611',
    subject: 'adab',
    topic: 'hatayi-kabullenme',
    difficulty: 'kolay',
    stem: 'Kavşakta yanlış şeride girdiğinizi fark ettiniz ve yandaki sürücü bunu jestlerle belli etti. Olgun bir sürücü nasıl davranır?',
    options: [
      'Hatayı örtmek için haklıymış gibi davranıp inat etmek',
      'Suçu yol çizgilerinin belirsizliğine atıp sinirlenmek',
      'Hatayı kabul edip özür anlamında kısa bir el işareti yapmak ve güvenli biçimde düzeltmeye çalışmak',
      'Hiç oralı olmayıp manevrayı zorla tamamlamak',
    ],
    answerIndex: 2,
    explanation:
      'Hata yapmak kusur değildir; kusur, onu kabullenmemektir. Kısa bir özür işareti hem gerginliği bitirir hem de karşı sürücünün size manevra için alan tanımasını kolaylaştırır. Kabullenmek, olgunluğun en sade hâlidir.',
    whyWrong: [
      'Haklıymış gibi inat etmek, düzeltilebilir bir hatayı tehlikeli bir çıkmaza sokar.',
      'Suçu dışarıya atmak sorunu çözmez; yalnızca gerginliği ve kendi savunmacılığınızı büyütür.',
    ],
    objective: 'Kendi hatasını kabullenip özürle telafi etme olgunluğunu edinmek.',
    tags: ['hatayi-kabullenme', 'ozur', 'olgunluk'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-612',
    subject: 'adab',
    topic: 'hatayi-kabullenme',
    difficulty: 'orta',
    stem: 'Bir tartışmada "ama önce o hata yaptı" demek kolaydır. Trafikte kendi hatasını kabullenmenin, savunmaya geçip başkasını suçlamaya göre en önemli üstünlüğü nedir?',
    options: [
      'Hatasını gören sürücü aynı hatayı tekrarlamamayı öğrenir ve gelişir; suçu dışarı atan ise hatasını hiç fark etmediği için onu sürekli tekrarlar',
      'Kabullenmek, karşı tarafa her koşulda tazminat ödememeyi sağlar',
      'Kabullenen sürücü her zaman haklı çıkar',
      'Hata kabul edildiğinde ceza tümüyle ortadan kalkar',
    ],
    answerIndex: 0,
    explanation:
      'Hatayı kabullenmek yalnızca ahlaki bir erdem değil, öğrenmenin ön koşuludur. "Ben yaptım" diyebilen sürücü nedenini görür ve düzeltir; "o başlattı" diyen ise aynı yanlışı ömür boyu taşır. Gelişimin kapısı, itiraf edebilmektir.',
    whyWrong: [
      'Kabullenmenin değeri tazminat hesabı değildir; kusurun paylaşımı hukuken ayrıca değerlendirilir.',
      'Kabullenmek her zaman haklı çıkarmaz; amacı haklılık değil, doğruyu görebilmektir.',
    ],
    objective: 'Hatayı kabullenmenin öğrenme ve gelişme açısından değerini kavramak.',
    tags: ['hatayi-kabullenme', 'ozelestiri', 'gelisim'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-613',
    subject: 'adab',
    topic: 'kaza-veri-toplama',
    difficulty: 'orta',
    stem: 'Maddi hasarlı bir kaza yaptınız; kimse yaralanmadı ama çok gerginsiniz. Süreci sağlıklı yürütmek için ilk yapmanız gereken nedir?',
    options: [
      'Karşı sürücüyle kimin haklı olduğunu yüksek sesle tartışmaya başlamak',
      'Önce sakinleşmek; ardından güvenliği sağlayıp (dörtlüler, gerekiyorsa araçların fotoğrafı) olay yerinin ve hasarın verilerini soğukkanlılıkla toplamak',
      'Bir an önce oradan ayrılmak için karşı tarafın söylediği her şeyi düşünmeden kabul etmek',
      'Öfkeyle karşı sürücüyü suçlayıp olayı büyütmek',
    ],
    answerIndex: 1,
    explanation:
      'Kaza anındaki en değerli araç sakinliktir. Panik ve öfke, hem yanlış kararlar aldırır hem de tutanağa geçecek verileri gözden kaçırtır. Önce derin bir nefes, sonra güvenlik, sonra sakin veri toplama: bu sıra hem sizi hem hakkınızı korur.',
    whyWrong: [
      'Kimin haklı olduğunu bağırarak tartışmak hiçbir veri üretmez, yalnızca gerginliği tırmandırır.',
      'Sakinleşmeden her şeyi kabul etmek ya da karşı tarafı suçlamak, ikisi de doğru tespiti imkânsız kılar.',
    ],
    objective: 'Kaza sonrası önce sakinleşip soğukkanlı veri toplamayı öğrenmek.',
    tags: ['kaza-veri-toplama', 'sakinlik', 'sorumluluk'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-614',
    subject: 'adab',
    topic: 'kaza-veri-toplama',
    difficulty: 'zor',
    stem: 'Hafif bir kaza sonrası karşı sürücü çok sinirli, sürekli bağırıyor ve sizi suçluyor. Siz ise kusurun paylaşımından emin değilsiniz. En doğru davranış hangisidir?',
    options: [
      'Onun baskısına dayanamayıp bütün kusuru üstlenen bir belge imzalamak',
      'Aynı sesle karşılık verip tartışmayı kazanmaya çalışmak',
      'Onun öfkesine kapılmadan sakin kalmak, tarafların ve olay yerinin fotoğraflarını çekmek, kusuru kendiniz karara bağlamak yerine gerekiyorsa yetkili ve eksper sürecine bırakmak',
      'Tartışmadan kaçmak için olay yerini terk etmek',
    ],
    answerIndex: 2,
    explanation:
      'Karşı tarafın öfkesi, kusurun kimde olduğunu değiştirmez; yüksek ses bir kanıt değildir. Baskı altında imza atmak ya da olay yerini terk etmek sonradan telafisi zor hatalardır. Soğukkanlı biçimde veriyi kaydetmek ve kararı usule bırakmak, hakkınızın tek güvencesidir.',
    whyWrong: [
      'Baskıyla kusuru tümden üstlenmek, gerçekte paylaşımlı olabilecek bir sorumluluğu haksızca yüklenmektir.',
      'Aynı sesle bağırmak veriyi değil yalnızca tansiyonu yükseltir.',
      'Olay yerini terk etmek, haklı olsanız bile sizi hukuken zor duruma düşürür.',
    ],
    objective:
      'Kaza sonrası karşı tarafın öfkesine kapılmadan usule uygun veri toplamayı öğrenmek.',
    tags: ['kaza-veri-toplama', 'ozdenetim', 'tutanak'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-615',
    subject: 'adab',
    topic: 'tutanak-durustlugu',
    difficulty: 'orta',
    stem: 'Kaza tutanağı doldururken, aslında kısmen sizin de dikkatsizliğinizin payı olduğunu biliyorsunuz ama karşı tarafın bunu fark etmediğini görüyorsunuz. Dürüst bir sürücü ne yapar?',
    options: [
      'Fark edilmediğine göre kendi payını hiç dile getirmemek',
      'Bütün kusuru karşı tarafa yıkacak biçimde olayı anlatmak',
      'Tutanağı eksik bırakıp işi tümüyle şansa bırakmak',
      'Olayı olduğu gibi, kendi payını da saklamadan dürüstçe aktarmak; dürüstlük, kimse görmese de vazgeçilmez bir ilkedir',
    ],
    answerIndex: 3,
    explanation:
      'Tutanak, bir kâğıt parçası değil; sonradan hakların, sigortanın ve adaletin dayanacağı bir beyandır. Kendi payını gizlemek anlık bir kazanç gibi görünse de bir yalanın üzerine kurulur. Dürüstlük, tam da kimsenin fark etmediği yerde sınanır.',
    whyWrong: [
      'Fark edilmemek, gerçeği çarpıtmayı haklı kılmaz; dürüstlük tanığa değil vicdana bağlıdır.',
      'Bütün kusuru karşıya yıkmak, hem haksızlık hem de sonradan ortaya çıkabilecek bir yalandır.',
    ],
    objective: 'Kaza tutanağında kendi payını da saklamadan dürüst beyan vermeyi benimsemek.',
    tags: ['tutanak-durustlugu', 'durustluk', 'vicdan'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-616',
    subject: 'adab',
    topic: 'tutanak-durustlugu',
    difficulty: 'kolay',
    stem: 'Kaza sonrası karşı sürücü "tutanağı kendi aramızda halledelim, sen kusuru üstlen, ben sana biraz para vereyim" diyor. Doğru yaklaşım hangisidir?',
    options: [
      'Gerçekte olan neyse onu yansıtan bir tutanak tutmak; kusuru para karşılığında çarpıtmayı kabul etmemek',
      'Teklif cazipse gerçeği değiştirip anlaşmayı kabul etmek',
      'Karşı taraf ne isterse düşünmeden imzalamak',
      'Kim daha çok ısrar ederse onun dediğini yazmak',
    ],
    answerIndex: 0,
    explanation:
      'Kusuru para karşılığı satın almak ya da satmak, tutanağı bir pazarlık aracına çevirir. Oysa tutanak gerçeğin kaydıdır; çarpıtılan her satır, ileride sigortadan mahkemeye kadar herkesi yanıltır. Dürüst kayıt, kısa vadede zor ama uzun vadede en güvenli yoldur.',
    whyWrong: [
      'Parayla gerçeği değiştirmek, hem etik dışıdır hem de sonradan çok daha büyük sorunlar doğurabilir.',
      'Karşı taraf ne derse imzalamak, kendi hakkınızı bilmeden teslim etmektir.',
    ],
    objective: 'Tutanağın gerçeği yansıtması gerektiğini, pazarlık konusu olamayacağını kavramak.',
    tags: ['tutanak-durustlugu', 'durustluk', 'kaza'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-617',
    subject: 'adab',
    topic: 'taniklik-sorumlulugu',
    difficulty: 'orta',
    stem: 'Önünüzde net bir kaza oldu; kusurlu tarafı açıkça gördünüz ancak yaralı yok ve acele bir işiniz var. Trafik adabı açısından en doğru davranış hangisidir?',
    options: [
      'İşiniz olduğu için hiç durmadan geçip gitmek; tanıklık başkalarının işidir',
      'Güvenli bir yerde durup gördüklerinizi taraflara veya yetkililere aktarmayı önermek, en azından iletişim bilginizi bırakmak; dürüst bir tanıklık, haksızlığın önlenmesine katkıdır',
      'Yalnızca tanıdığınız taraf haklıysa tanıklık etmek',
      'Olayı sosyal medyada paylaşıp orada tanıklık ettiğinizi düşünmek',
    ],
    answerIndex: 1,
    explanation:
      'Adil bir sonuç çoğu zaman tarafsız bir tanığa bağlıdır. Gördüğünü dürüstçe aktaran biri, haksız yere suçlanacak birinin hakkını kurtarabilir. Birkaç dakikanızı ayırıp iletişim bilginizi bırakmak, toplumsal vicdanın küçük ama gerçek bir katkısıdır.',
    whyWrong: [
      'Tanıklıktan kaçmak, elinizdeki gerçeğin bir haksızlığı düzeltmesini engeller.',
      'Tanıklığı tanıdıklığa göre seçmek adaleti değil tarafgirliği besler; sosyal medya ise resmi bir tanıklık zemini değildir.',
    ],
    objective: 'Kaza tanıklığını toplumsal bir sorumluluk olarak benimsemek.',
    tags: ['taniklik-sorumlulugu', 'adalet', 'durustluk'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-618',
    subject: 'adab',
    topic: 'taniklik-sorumlulugu',
    difficulty: 'zor',
    stem: 'Tanık olduğunuz bir kazada, kusurlu tarafın sizin uzaktan bir tanıdığınız olduğunu fark ettiniz; oysa gördüğünüz kadarıyla asıl kusur ondaydı. Vicdanlı bir tanık ne yapar?',
    options: [
      'Tanıdığını korumak için olayı onun lehine anlatmak',
      'Zor durumda kalmamak için hiçbir şey görmediğini söylemek',
      'Tanıdıklığın gerçeği değiştirmeyeceğini bilerek gördüğünü olduğu gibi, dürüstçe aktarmak',
      'Tanıklıktan tümüyle çekilip olay yerinden sessizce ayrılmak',
    ],
    answerIndex: 2,
    explanation:
      'Tanıklığın sınandığı yer, tam da tarafsız kalmanın zorlaştığı andır. Tanıdık diye gerçeği eğmek, haksız yere suçlanan öbür tarafa yapılmış bir haksızlıktır. Gerçeği söylemek bazen zordur; ama vicdanın pusulası ilişkiye değil doğruya bakar.',
    whyWrong: [
      'Tanıdığı korumak için gerçeği çarpıtmak, masum olan karşı tarafın hakkını çiğnemektir.',
      'Hiçbir şey görmediğini söylemek ya da sessizce ayrılmak, gerçeği bildiğiniz için pasif bir yalandır.',
    ],
    objective: 'Tanıklıkta kişisel bağlardan bağımsız kalıp gerçeği söylemeyi içselleştirmek.',
    tags: ['taniklik-sorumlulugu', 'tarafsizlik', 'vicdan'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-619',
    subject: 'adab',
    topic: 'yardim-cagirma-hizi',
    difficulty: 'kolay',
    stem: 'Tanık olduğunuz bir trafik kazasında yaralı olduğunu görüyorsunuz. Yapılacak ilk ve en kritik şeylerden biri nedir?',
    options: [
      'Önce olayın nasıl olduğunu anlamak için etrafı uzun uzun incelemek',
      'Yaralıyı hemen kaldırıp aracınıza taşımaya çalışmak',
      'Başka birinin arayacağını düşünüp beklemek',
      'Vakit kaybetmeden acil yardım hattını arayıp yeri ve durumu net biçimde bildirmek; profesyonel yardımı en hızlı şekilde harekete geçirmek',
    ],
    answerIndex: 3,
    explanation:
      'Ağır yaralanmalarda hayatta kalma şansı ilk dakikalara bağlıdır. En değerli katkı, çoğu zaman doğru bir ilk müdahaleden önce gelen hızlı ve net bir yardım çağrısıdır. Geciken her saniye, ekiplerin ulaşımını da geciktirir.',
    whyWrong: [
      'Yaralıyı bilinçsizce kaldırmak, özellikle omurga yaralanmalarında kalıcı hasara yol açabilir.',
      'Başkası arar düşüncesi, herkes aynı şeyi düşündüğünde kimsenin aramamasına yol açar.',
    ],
    objective: 'Kazada yardım çağrısının hızının hayati önemini kavramak.',
    tags: ['yardim-cagirma-hizi', 'acil-cagri', 'sorumluluk'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-620',
    subject: 'adab',
    topic: 'yardim-cagirma-hizi',
    difficulty: 'orta',
    stem: 'Bir kazaya ilk ulaşan sürücüsünüz; kalabalık henüz toplanmadı. Acil yardım hattını ararken en doğru tutum hangisidir?',
    options: [
      'Sakin kalıp yerin adresini, kaza türünü ve yaralı sayısını mümkün olduğunca net aktarmak; hattı kapatmadan operatörün yönlendirmesini dinlemek',
      'Panikle bağırıp yalnızca "kaza var, gelin" deyip telefonu kapatmak',
      'Adres yerine "buralarda bir yerde" gibi belirsiz tarifler vermek',
      'Önce olayı videoya çekip sonra aramak',
    ],
    answerIndex: 0,
    explanation:
      'Yardım çağrısının hızı kadar netliği de önemlidir: doğru adres ve durum bilgisi, ekiplerin doğru donanımla ve doğru yere gelmesini sağlar. Panikle verilen eksik bilgi, kurtarmayı hızlandırmak yerine geciktirir. Operatörle bağlantıyı korumak da bu yüzden değerlidir.',
    whyWrong: [
      'Bağırıp kapatmak, ekiplerin ihtiyaç duyduğu bilgileri alamadan yola çıkmasına yol açar.',
      'Belirsiz adres ekipleri yanlış yönlendirir; video çekmek ise hayat kurtaracak dakikaları harcar.',
    ],
    objective: 'Yardım çağrısını hızlı ve net biçimde yapmayı öğrenmek.',
    tags: ['yardim-cagirma-hizi', 'iletisim', 'acil-cagri'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-621',
    subject: 'adab',
    topic: 'gosteris-akran-baskisi',
    difficulty: 'kolay',
    stem: 'Genç bir sürücü, arkadaşlarını etkilemek için yerleşim yerinde lastik yaktırıp yüksek sesle hızlanıyor. Bu "gösteriş sürüşü" için en doğru değerlendirme hangisidir?',
    options: [
      'Gençliğe özgü, zararsız bir heyecan biçimidir',
      'Ne kendine ne çevresine bir değer katan, yalnızca herkesi tehlikeye atan bir ego gösterisidir; gerçek özgüven kural tanımaktan geçer',
      'Araç güçlüyse ve sürücü yetenekliyse sakıncası yoktur',
      'Yalnızca gece yapılırsa tehlikelidir',
    ],
    answerIndex: 1,
    explanation:
      'Gösteriş sürüşü, alkışlanmak istenen ama aslında yalnızca risk üreten bir davranıştır. Etkilenmesi umulan arkadaşlar bir kaza anında oradan kaçar; geriye yalnızca sürücünün ve mağdurların bedeli kalır. Asıl saygı duyulan sürüş, sessiz ve kurallıdır.',
    whyWrong: [
      'Heyecanı zararsız saymak, o heyecanın bedelini ödeyecek yayaları ve yolcuları görmezden gelmektir.',
      'Aracın gücü ya da saatin geç olması, fizik kurallarını ve başkalarının canını değiştirmez.',
    ],
    objective: 'Gösteriş amaçlı sürüşün anlamsızlığını ve riskini kavramak.',
    tags: ['gosteris-akran-baskisi', 'ego', 'genc-surucu'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-622',
    subject: 'adab',
    topic: 'gosteris-akran-baskisi',
    difficulty: 'orta',
    stem: 'Araçtaki arkadaşlarınız "hadi göster kendini, biraz hızlan, korkma" diye sizi kışkırtıyor. Bu akran baskısına karşı en olgun tutum hangisidir?',
    options: [
      'Arkadaşlarınızı kırmamak için bir süreliğine hızlanıp sonra normale dönmek',
      'Onların cesaretlendirmesini haklı bulup temkini bırakmak',
      'Direksiyondaki tek sorumlunun siz olduğunu net biçimde hatırlatıp güvenli sürüşe devam etmek; "hayır" diyebilmek en büyük olgunluktur',
      'Cesaretinizi kanıtlamak için tek bir riskli manevra yapmak',
    ],
    answerIndex: 2,
    explanation:
      'Araçtaki herkesin canı, o an direksiyonu tutan kişinin kararına emanettir. Arkadaş baskısına hayır demek popülerliği azaltabilir ama bir hayatı kurtarabilir. Gerçek cesaret, riskli manevrada değil; kalabalığa karşı ilkeni koruyabilmektedir.',
    whyWrong: [
      'Bir süreliğine hızlanmak da riski kabul etmektir; kaza için bir anlık dikkatsizlik yeter.',
      'Cesareti tek bir riskli manevrayla kanıtlamaya çalışmak, olgunluğu değil toyluğu gösterir.',
    ],
    objective: 'Akran baskısına direnip direksiyondaki sorumluluğu sahiplenmeyi öğrenmek.',
    tags: ['gosteris-akran-baskisi', 'akran-baskisi', 'sorumluluk'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-623',
    subject: 'adab',
    topic: 'yasli-surucu-saygisi',
    difficulty: 'kolay',
    stem: 'Önünüzdeki araçta yaşlı bir sürücü var; temkinli, yavaş ve zaman zaman tereddütlü ilerliyor. Saygılı ve empatik davranış hangisidir?',
    options: [
      'Takip mesafesini artırıp sabırla, baskı yapmadan ilerlemek; onun da güvenle seyahat etme hakkı olduğunu unutmamak',
      'Korna ve selektörle hızlanması için baskı yapmak',
      'Dibine sokulup tedirgin ederek yol açmasını sağlamak',
      'Yanına gelip pencereden uyarıda bulunmak',
    ],
    answerIndex: 0,
    explanation:
      'Yaşlı sürücü de yolun eşit bir ortağıdır; temkinli sürüşü bir kusur değil, çoğu zaman bir sorumluluk göstergesidir. Baskı, onun tereddüdünü artırıp hata yaptırır. Sabırla mesafe bırakmak, bir gün kendimizin de ihtiyaç duyacağı saygıdır.',
    whyWrong: [
      'Korna ve selektörle baskı, temkinli sürücüyü paniğe sürükleyip riski büyütür.',
      'Dibine sokulmak ya da pencereden uyarmak, hem dikkat dağıtır hem de saygısızlıktır.',
    ],
    objective: 'Yaşlı sürücülere sabır ve saygıyla yaklaşmayı benimsemek.',
    tags: ['yasli-surucu-saygisi', 'empati', 'sabir'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-624',
    subject: 'adab',
    topic: 'yasli-surucu-saygisi',
    difficulty: 'orta',
    stem: '"Yaşlılar trafikte yavaşlatıyor, hiç direksiyona geçmemeliler" diyen bir arkadaşınıza trafik adabı açısından verilecek en doğru cevap nedir?',
    options: [
      '"Haklısın, belli bir yaştan sonra araç kullanmak tümüyle yasaklanmalı"',
      '"Yavaş ve temkinli sürmek çoğu zaman bir güvenlik tercihidir; herkesin yolda bulunma hakkı vardır, bize düşen sabır ve saygı göstermektir"',
      '"Sadece şehir dışında sürmelerine izin verilmeli"',
      '"Yaşlı sürücülerin arkasında hiç kalmamak için farklı güzergâhlar seçmeli"',
    ],
    answerIndex: 1,
    explanation:
      'Trafik, toplumun her kesiminin ortak alanıdır; yalnızca hızlıların değil, temkinlilerin de yeri vardır. Yaşa dayalı dışlama, bir gün herkesin karşılaşacağı bir haksızlığa kapı aralar. Adap, farklı tempolara tahammül edip yolu paylaşmayı gerektirir.',
    whyWrong: [
      'Yaşa göre toptan yasak, bireysel durumları yok sayan bir önyargıdır.',
      'Yaşlı sürücüden kaçmak için güzergâh değiştirmek sorunu çözmez; asıl gereken tutum değişikliğidir.',
    ],
    objective: 'Yaşlı sürücülere yönelik önyargıya karşı hoşgörü geliştirmek.',
    tags: ['yasli-surucu-saygisi', 'onyargi', 'hosgoru'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-625',
    subject: 'adab',
    topic: 'onyargiyla-mucadele',
    difficulty: 'orta',
    stem: 'Bir sürücü, belirli bir araç tipini ya da plakayı görünce "bunlar hep kötü sürer" diyerek temkin yerine peşinen öfkeye geçiyor. Bu önyargılı tutumun trafik açısından zararı nedir?',
    options: [
      'Zararı yoktur; tecrübe zaten insanı böyle genellemelere götürür',
      'Yalnızca o sürücünün ruh hâlini bozar, başka etkisi olmaz',
      'Önyargı, dikkati keskinleştirdiği için aslında faydalıdır',
      'Önyargı, karşıdaki bireyi olduğu gibi görmeyi engeller; sürücüyü gereksiz yere gerginleştirir, haksız saldırganlığa ve yanlış değerlendirmelere yol açar',
    ],
    answerIndex: 3,
    explanation:
      'Trafikte her sürücü bir bireydir; plakası, aracı ya da görünüşü davranışını belirlemez. Önyargı, insana o an gerçekte ne yaptığını değil, kafamızdaki kalıbı gösterir. Bu da hem haksız öfke hem de gerçek riski gözden kaçırma anlamına gelir.',
    whyWrong: [
      'Genellemeleri tecrübe saymak, önyargıyı meşrulaştıran bir yanılgıdır.',
      'Önyargının etkisi kişisel ruh hâliyle sınırlı kalmaz; davranışa ve trafiğe yansır, dikkati keskinleştirmez, çarpıtır.',
    ],
    objective: 'Trafikteki önyargıların bireyi görmeyi engelleyen zararını kavramak.',
    tags: ['onyargiyla-mucadele', 'psikoloji', 'ofke'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-626',
    subject: 'adab',
    topic: 'onyargiyla-mucadele',
    difficulty: 'zor',
    stem: 'Genç bir sürücü sizi düzgün biçimde solladı; siz ise "gençler zaten hep dikkatsiz" diye baştan sinirlisiniz ve manevrayı olduğundan tehlikeli algılıyorsunuz. Bu durum önyargı ile ilgili neyi gösterir?',
    options: [
      'Önyargı, gerçekte kurallı olan bir davranışı bile çarpıtarak algılamamıza yol açabilir; adil olmak için sürücüyü etiketiyle değil, o anki davranışıyla değerlendirmek gerekir',
      'Genç sürücülere karşı temkin her zaman ve koşulsuz haklıdır',
      'Algı hiçbir zaman önyargıdan etkilenmez',
      'Sollama kurallı bile olsa gençler yaptığında yanlıştır',
    ],
    answerIndex: 0,
    explanation:
      'Önyargı yalnızca duygularımızı değil, algımızı da boyar: beklentimize uyan şeyi büyütür, uymayanı görmezden geliriz. Kurallı bir sollamayı tehlikeli sanmak, karşımızdaki gence değil, kafamızdaki etikete tepki verdiğimizi gösterir. Adalet, etiketi değil davranışı görmeyi gerektirir.',
    whyWrong: [
      'Bir yaş grubuna karşı koşulsuz temkin, tanımı gereği önyargıdır.',
      'Algının önyargıdan etkilenmediğini sanmak, bu tuzağa düşmenin ilk adımıdır; kurallı davranış, kimin yaptığından bağımsız olarak kurallıdır.',
    ],
    objective:
      'Önyargının algıyı bile çarpıttığını fark edip davranış temelli değerlendirmeyi öğrenmek.',
    tags: ['onyargiyla-mucadele', 'algi', 'adalet'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-627',
    subject: 'adab',
    topic: 'korna-yerine-sabir',
    difficulty: 'kolay',
    stem: 'Önünüzdeki araç, bir yayanın karşıdan geçmesini beklediği için kısa bir süre durakladı. İçinizden korna çalmak geliyor. En doğru davranış hangisidir?',
    options: [
      'Kısa bir korna ile hatırlatma yapmak',
      'Uzun uzun korna çalıp acele ettirmek',
      'Sabırla beklemek; öndeki sürücü büyük olasılıkla sizin göremediğiniz bir yayaya yol veriyordur',
      'Yandan sıkışıp geçmeye çalışmak',
    ],
    answerIndex: 2,
    explanation:
      'Kornaya uzanmadan önce "acaba onun bir nedeni var mı?" diye sormak, sabrın ilk adımıdır. Çoğu zaman öndeki sürücü sizin açınızdan görünmeyen bir yayaya ya da tehlikeye yol veriyordur. Aceleyle çalınan korna, bir yaya kazasının davetçisi olabilir.',
    whyWrong: [
      'Kısa da olsa korna, haklı bir bekleyişi baskıya çevirir ve öndeki sürücüyü telaşlandırır.',
      'Yandan sıkışıp geçmek, tam da göremediğiniz yayanın önüne çıkmak demektir.',
    ],
    objective: 'Korna dürtüsü yerine sabrı ve nedenini anlama tutumunu koymayı öğrenmek.',
    tags: ['korna-yerine-sabir', 'sabir', 'yaya-saygi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-628',
    subject: 'adab',
    topic: 'korna-yerine-sabir',
    difficulty: 'orta',
    stem: 'Bazı sürücüler en küçük gecikmede refleks olarak kornaya basar. Kornayı bir "sabırsızlık aracı" olmaktan çıkarıp doğru kullanmanın ölçüsü nedir?',
    options: [
      'Korna, öndekini uyarmanın en pratik yolu olduğu için sık kullanılmalıdır',
      'Korna yalnızca bir tehlikeyi önlemek için, kısa ve gerektiğinde çalınmalı; sabırsızlığı, öfkeyi ya da selamlaşmayı ifade etmek için kullanılmamalıdır',
      'Kornanın uzunluğu, gecikmenin süresine göre ayarlanmalıdır',
      'Korna, haklı olduğumuzu karşı tarafa duyurmanın meşru bir yoludur',
    ],
    answerIndex: 1,
    explanation:
      'Korna bir iletişim aracıdır, bir duygu boşaltma valfi değil. Amacı, bir tehlikeyi önlemek için karşı tarafı uyarmaktır. Sabırsızlığın, öfkenin ya da "geçtim işte" demenin sesi olduğunda ise yalnızca gürültü ve gerginlik üretir.',
    whyWrong: [
      'Kornayı pratik diye sık kullanmak, onu bir tehlike uyarısı olmaktan çıkarıp gürültüye çevirir.',
      'Kornanın süresini gecikmeye göre ayarlamak ya da onu haklılık ilanı yapmak, sabırsızlığı meşrulaştırmaktır.',
    ],
    objective:
      'Kornayı sabırsızlık aracı olmaktan çıkarıp yalnızca uyarı amaçlı kullanmayı kavramak.',
    tags: ['korna-yerine-sabir', 'korna-kullanimi', 'nezaket'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-629',
    subject: 'adab',
    topic: 'uykusuz-surus',
    difficulty: 'kolay',
    stem: 'Bir sürücü "alkol almadım, sadece uykusuzum, idare ederim" diyerek yola çıkmak istiyor. Bu düşünce için en doğru değerlendirme hangisidir?',
    options: [
      'Uykusuzluk, alkolden çok daha az risklidir; sürüşe engel değildir',
      'Uykusuzluğun etkisi yalnızca gece sürüşünde önemlidir',
      'Pencereyi açıp müzik dinlemek uykusuzluğu tümüyle giderir',
      'Uykusuzluk da tıpkı alkol gibi tepki süresini uzatır, dikkati ve karar yeteneğini bozar; yorgunken direksiyona geçmemek gerekir',
    ],
    answerIndex: 3,
    explanation:
      'Uzun süre uyanık kalmanın beyin üzerindeki etkisi, belli bir alkol düzeyininkine benzetilir: refleksler yavaşlar, dikkat kesintiye uğrar ve mikro uykular başlar. "İdare ederim" demek, tam da yorgunluğun yargıyı bozduğunun ilk işaretidir.',
    whyWrong: [
      'Uykusuzluğu alkolden daha az riskli saymak, bilimsel olarak yanlış ve tehlikeli bir küçümsemedir.',
      'Pencere ve müzik uyanıklığı yalnızca birkaç dakika taklit eder; uyku ihtiyacını gidermez ve gündüz de risk sürer.',
    ],
    objective: 'Uykusuz sürüşün alkol kadar riskli olduğunu kavramak.',
    tags: ['uykusuz-surus', 'yorgunluk', 'risk-algisi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-630',
    subject: 'adab',
    topic: 'uykusuz-surus',
    difficulty: 'zor',
    stem: 'Gece boyunca çalıştınız ve sabah araçla eve dönüyorsunuz; "birazdan varırım" diye düşünüp gözlerinizin karardığını görmezden geliyorsunuz. Bu durumun en sinsi tehlikesi nedir?',
    options: [
      'Yakıtın erken bitmesi',
      'Aracın motorunun ısınması',
      'Uykulu sürücünün, uyuyakaldığı o birkaç saniyeyi genellikle hiç fark etmemesi; "mikro uyku" sırasında araç kontrolsüz biçimde yol alır ve sürücü tehlikeyi ancak iş işten geçtikten sonra anlar',
      'Sürücünün fazla temkinli davranıp trafiği yavaşlatması',
    ],
    answerIndex: 2,
    explanation:
      'Uykunun en tehlikeli yanı, geldiğini haber vermemesidir. Mikro uyku denen birkaç saniyelik dalmalar sırasında gözler açık olabilir ama beyin kapalıdır; bu saniyelerde araç şeridinden çıkabilir. Sürücü çoğu zaman ne olduğunu ancak kaza anında fark eder.',
    whyWrong: [
      'Yakıt ve motor teknik ayrıntılardır; buradaki tehlike sürücünün bilincinin geçici olarak kaybolmasıdır.',
      'Uykulu sürücü fazla temkinli değil, tam tersine kontrolsüzdür; yavaşlığı değil, dalıp gitmesi öldürücüdür.',
    ],
    objective: 'Mikro uykunun fark edilemez ve ölümcül doğasını kavramak.',
    tags: ['uykusuz-surus', 'mikro-uyku', 'dikkat'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-631',
    subject: 'adab',
    topic: 'ilac-ve-surus',
    difficulty: 'kolay',
    stem: 'Doktorunuzun yazdığı bir ilacın kutusunda "uyku yapabilir, araç kullanmayınız" uyarısı var ama kendinizi iyi hissediyorsunuz. Sorumlu bir sürücü ne yapar?',
    options: [
      'Kendini iyi hissettiği için uyarıyı dikkate almadan araç kullanmak',
      'Uyarıyı ciddiye alıp o ilacı kullandığı sürece direksiyona geçmemek; gerekirse doktoruna veya eczacısına danışmak',
      'İlaç dozunu kendi kararıyla yarıya indirip araç kullanmak',
      'Yalnızca kısa mesafelerde araç kullanmak',
    ],
    answerIndex: 1,
    explanation:
      'Bazı ilaçlar reflekslerinizi ve dikkatinizi, siz fark etmeden yavaşlatabilir; iyi hissetmek bu etkinin olmadığı anlamına gelmez. Kutudaki uyarı bir öneri değil, bir güvenlik bilgisidir. Emin değilseniz, doğru adres doktor ya da eczacıdır.',
    whyWrong: [
      'İyi hissetmek, ilacın tepki süresi üzerindeki etkisini ortadan kaldırmaz.',
      'Dozu kendi başına değiştirmek hem tedaviyi bozar hem de riski gidermez; kısa mesafe de olsa kaza riski sürer.',
    ],
    objective: 'İlaç uyarılarını ciddiye alıp gerektiğinde sürüşten kaçınmayı benimsemek.',
    tags: ['ilac-ve-surus', 'sorumluluk', 'saglik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-632',
    subject: 'adab',
    topic: 'ilac-ve-surus',
    difficulty: 'orta',
    stem: 'Uzun bir yolculuk öncesi alerji ilacı almanız gerekiyor ama bu ilaçların bazılarının uyku yaptığını biliyorsunuz. En doğru yaklaşım hangisidir?',
    options: [
      'Yola çıkmadan önce eczacınıza ya da doktorunuza danışıp uyku yapmayan bir alternatif olup olmadığını sormak; yoksa sürüş planını buna göre ayarlamak',
      'İlacı alıp etkisini yolda görmeyi beklemek',
      'İlacı hiç almayıp sağlığınızı riske atmak',
      'Uyku bastırırsa kahveyle dengelemeyi planlamak',
    ],
    answerIndex: 0,
    explanation:
      'Sağlık ile güvenliği karşı karşıya getirmek yerine, ikisini birlikte gözeten yol aramak en olgun tutumdur. Eczacıya danışmak, çoğu zaman uyku yapmayan bir alternatif ya da doğru zamanlama sunar. Böylece hem tedaviden hem de güvenli sürüşten vazgeçmemiş olursunuz.',
    whyWrong: [
      'Etkiyi yolda görmeyi beklemek, uyku bastırdığında geri dönüşü olmayan bir riske girmektir.',
      'İlacı hiç almamak sağlığı, kahveyle dengelemeye çalışmak ise güvenliği riske atar; ikisi de çözüm değildir.',
    ],
    objective: 'İlaç kullanımıyla sürüş kararını önceden planlayıp uzmana danışmayı öğrenmek.',
    tags: ['ilac-ve-surus', 'planlama', 'saglik'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-633',
    subject: 'adab',
    topic: 'duygusal-durum-surus',
    difficulty: 'kolay',
    stem: 'Çok üzücü bir haber aldınız ve gözleriniz dolu dolu; hemen arabaya binip yola çıkmak üzeresiniz. En doğru davranış hangisidir?',
    options: [
      'Dikkatinizi dağıtmamak için hiç durmadan yola çıkmak',
      'Üzüntüyü bastırmak için hızlı sürüp adrenalinle rahatlamak',
      'Birkaç dakika bekleyip biraz sakinleşmek; yoğun duygular dikkatinizi ve karar yeteneğinizi bozacağı için mümkünse hemen direksiyona geçmemek',
      'Yola çıkıp telefondan yakınlarınızla uzun uzun konuşarak rahatlamaya çalışmak',
    ],
    answerIndex: 2,
    explanation:
      'Yoğun üzüntü, öfke ya da heyecan; tıpkı yorgunluk gibi zihni yoldan çeker. İçi altüst olmuşken direksiyona geçmek, dikkati büyük ölçüde olayın kendisine bırakır. Birkaç dakikalık bir mola, hem sizi hem yoldaki herkesi korur.',
    whyWrong: [
      'Duyguyu dağıtmak için hemen yola çıkmak işe yaramaz; duygu bedende ve zihinde sürmeye devam eder.',
      'Hızlı sürmek ya da telefonla konuşmak, zaten dağınık olan dikkati daha da böler.',
    ],
    objective: 'Yoğun duygusal durumların sürüşe etkisini kabul edip önce sakinleşmeyi öğrenmek.',
    tags: ['duygusal-durum-surus', 'psikoloji', 'dikkat'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-634',
    subject: 'adab',
    topic: 'duygusal-durum-surus',
    difficulty: 'orta',
    stem: 'Ailenizle çok sert bir tartışmanın hemen ardından, hâlâ öfkeliyken araca bindiniz. Bu ruh hâliyle sürmenin en büyük riski nedir ve ne yapmalısınız?',
    options: [
      'Risk yoktur; öfke sürüşü etkilemez, hatta insanı daha uyanık tutar',
      'Öfkeyi gaza yükleyerek boşaltmak en sağlıklı yoldur',
      'Yalnızca uzun yolda risklidir, şehir içinde sorun olmaz',
      'Öfke, saldırgan ve aceleci sürüşe yol açıp riskleri küçük gösterir; birkaç dakika bekleyip sakinleşmek, gerekirse kısa bir yürüyüşle öfkeyi düşürmek en doğrusudur',
    ],
    answerIndex: 3,
    explanation:
      'Öfke, beyni kavga moduna sokar; bu modda sabır azalır, riskler küçük görünür ve direksiyon adeta bir boşaltma alanına dönüşür. Sinirliyken beklenen o birkaç dakika ya da kısa bir yürüyüş, kararların yeniden akla dönmesini sağlar.',
    whyWrong: [
      'Öfkenin uyanık tuttuğu düşüncesi bir yanılgıdır; dikkati keskinleştirmez, daraltır ve dürtüselleştirir.',
      'Öfkeyi gaza yüklemek onu boşaltmaz, trafiğe taşır; risk yalnızca uzun yolda değil, her yerde geçerlidir.',
    ],
    objective: 'Öfkeli sürüşün risklerini kavrayıp sakinleşmeden yola çıkmamayı benimsemek.',
    tags: ['duygusal-durum-surus', 'ofke-kontrolu', 'ozdenetim'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-635',
    subject: 'adab',
    topic: 'cezayi-ders-gorme',
    difficulty: 'kolay',
    stem: 'Hız sınırını aştığınız için ceza aldınız. Trafik adabını içselleştirmiş bir sürücü bu cezaya nasıl bakar?',
    options: [
      'Kural ihlalinin bir sonucu olarak görüp bir daha aynı hatayı yapmamak için bir hatırlatma, bir ders olarak değerlendirir',
      'Yalnızca "yakalandım" diye üzülüp kuralı değil, denetimi suçlar',
      'Bir dahaki sefere radar yerini önceden öğrenmeye karar verir',
      'Cezayı haksızlık sayıp trafik kurallarına daha da az uymaya başlar',
    ],
    answerIndex: 0,
    explanation:
      'Ceza, aslında bu davranış birine zarar verebilirdi diyen bir uyarıdır. Onu bir ders olarak görebilen sürücü, hatasını fark edip düzeltir. "Yakalandım"a takılan ise kuralı değil yalnızca denetimi düşünür ve aynı riski taşımaya devam eder.',
    whyWrong: [
      '"Yakalandım" diye üzülmek, hatanın nedenini değil yalnızca sonucunu görmektir.',
      'Radar yerini öğrenmek ya da cezayı haksızlık sayıp daha çok ihlal etmek, dersi tümüyle kaçırmaktır.',
    ],
    objective: 'Trafik cezasını bir öğrenme fırsatı olarak değerlendirmeyi benimsemek.',
    tags: ['cezayi-ders-gorme', 'ozelestiri', 'kural-icsellestirme'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-636',
    subject: 'adab',
    topic: 'cezayi-ders-gorme',
    difficulty: 'orta',
    stem: 'Bir sürücü aldığı her cezanın ardından "devlet para topluyor" diyerek öfkeleniyor ama davranışını hiç değiştirmiyor. Bu tutumun temel yanlışı nedir?',
    options: [
      'Öfkelenmesi doğaldır; cezaların hiçbir eğitici yönü yoktur',
      'Cezanın amacını, yani davranışı düzelterek can güvenliğini korumayı görmezden gelip yalnızca maddi tarafına takılması; bu yüzden aynı riskli davranışı sürdürür ve hiçbir ders çıkarmaz',
      'Cezaya öfkelenmek, bir daha ihlal yapmamayı garanti eder',
      'Sorun cezanın miktarındadır; ücretsiz olsa davranış kendiliğinden değişirdi',
    ],
    answerIndex: 1,
    explanation:
      'Cezaya yalnızca cebimden çıkan para olarak bakan sürücü, onun asıl mesajını kaçırır: bu davranış bir kazaya yol açabilirdi. Öfkeyle savunmaya geçmek, hatayı görmeyi engeller; böylece ceza tekrarlanır ama davranış hiç değişmez.',
    whyWrong: [
      'Cezaların eğitici yönü vardır; sorun cezada değil, ondan ders çıkarmamaktadır.',
      'Öfke tek başına davranışı değiştirmez; değişim, hatayı kabul etmekle başlar. Mesele miktarda değil, tutumdadır.',
    ],
    objective: 'Cezaya yalnızca maddi açıdan bakmanın öğrenmeyi engellediğini kavramak.',
    tags: ['cezayi-ders-gorme', 'kural-icsellestirme', 'sorumluluk'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-637',
    subject: 'adab',
    topic: 'navigasyon-korukorune',
    difficulty: 'kolay',
    stem: 'Navigasyon uygulaması sizi tek yön levhasının olduğu bir sokağa ters yönden yönlendiriyor. Doğru davranış hangisidir?',
    options: [
      'Navigasyon daha günceldir diye levhaya rağmen sokağa girmek',
      'Emin olmak için sokağın ortasında durup haritayı incelemek',
      'Yol levhalarına ve gerçek trafik işaretlerine uymak; navigasyon bir yardımcıdır, trafik kurallarının yerini almaz',
      'Ters yönde ama çok yavaş girerek riski azaltmaya çalışmak',
    ],
    answerIndex: 2,
    explanation:
      'Navigasyon güncel olmayabilir, hata yapabilir ya da geçici düzenlemeleri bilmeyebilir. Yolda asıl bağlayıcı olan, gözünüzün önündeki levhalar ve işaretlerdir. Ekranı gerçeğin önüne koymak, tek yön ihlali gibi ölümcül hatalara yol açabilir.',
    whyWrong: [
      'Navigasyonun güncel olduğunu varsaymak, levhaya rağmen ters yöne girmeyi haklı çıkarmaz.',
      'Sokak ortasında durmak trafiği tehlikeye atar; yavaş da olsa ters yöne girmek yine ihlaldir ve kaza riski taşır.',
    ],
    objective:
      'Navigasyona körü körüne değil, gerçek trafik işaretlerine öncelik vererek uymayı öğrenmek.',
    tags: ['navigasyon-korukorune', 'trafik-isaretleri', 'dikkat'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-638',
    subject: 'adab',
    topic: 'navigasyon-korukorune',
    difficulty: 'zor',
    stem: 'Navigasyon uygulaması, trafiği azaltmak için sizi dar bir yerleşim içi sokağa yönlendiriyor; sokakta çocuklar oynuyor ve yol çok dar. Bilinçli bir sürücü ne yapar?',
    options: [
      'Uygulama en kısa yolu bildiği için tereddütsüz o sokağa girmek',
      'Sokağın koşullarını kendi gözüyle değerlendirmek; çocukların olduğu dar bir sokakta hızını iyice düşürmek ya da uygunsa daha güvenli bir güzergâhı tercih etmek — son kararı ekran değil sürücü verir',
      'Zaman kazandırdığı için sokaktan normal hızda geçmek',
      'Çocuklara korna çalarak yolu açmalarını sağlamak',
    ],
    answerIndex: 1,
    explanation:
      'Navigasyon yalnızca mesafe ve süreyi hesaplar; sokaktaki çocuğu, dar geçişi ya da o anki riski göremez. Bu değerlendirmeyi yapacak olan sürücüdür. Ekranın en kısa dediği yol, her zaman en güvenli ya da en uygun yol değildir.',
    whyWrong: [
      'Uygulamanın önerisini sorgusuzca izlemek, sürüşün sorumluluğunu bir algoritmaya devretmektir.',
      'Çocukların olduğu dar sokakta normal hızla geçmek ya da korna çalmak, riski görmezden gelen tehlikeli tutumlardır.',
    ],
    objective:
      'Navigasyon önerisini yol koşullarına göre sorgulayıp güvenliği önceliklendirmeyi öğrenmek.',
    tags: ['navigasyon-korukorune', 'sorumluluk', 'yerlesim-ici'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-639',
    subject: 'adab',
    topic: 'egzoz-komsu-hakki',
    difficulty: 'kolay',
    stem: 'Bir sürücü, aracına yüksek ses çıkaran modifiyeli bir egzoz taktırmış ve özellikle gece mahalle içinde motoru gazlıyor. Komşu hakkı açısından en doğru değerlendirme hangisidir?',
    options: [
      'Araç sahibinin kendi aracında istediği değişikliği yapma hakkı vardır, kimseyi ilgilendirmez',
      'Yalnızca gündüz gazlarsa sorun olmaz',
      'Ses güçlü olduğu sürece bu bir başarı ve prestij göstergesidir',
      'Bu gürültü, uyuyan komşuların, hastaların ve çocukların dinlenme hakkını ihlal eder; kişisel zevk, başkalarının huzur hakkının önüne geçemez',
    ],
    answerIndex: 3,
    explanation:
      'Bir aracın çıkardığı ses, sahibinin özel alanında kalmaz; pencerelerden içeri girip uyuyan bir bebeği, dinlenen bir hastayı rahatsız eder. Benim aracım özgürlüğü, komşunun huzur hakkının başladığı yerde biter. Gürültü, görünmez ama gerçek bir zarardır.',
    whyWrong: [
      'Kendi aracım düşüncesi, çıkardığı sesin başkalarının evine girdiği gerçeğini görmezden gelir.',
      'Gündüz de olsa gereksiz gürültü rahatsızlık verir; sesin gücünü prestij saymak, başkalarının hakkını yok saymaktır.',
    ],
    objective: 'Araç gürültüsünün komşuların huzur hakkını ihlal ettiğini kavramak.',
    tags: ['egzoz-komsu-hakki', 'gurultu', 'komsu-hakki'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-640',
    subject: 'adab',
    topic: 'egzoz-komsu-hakki',
    difficulty: 'orta',
    stem: 'Apartmanınızın önünde bazı sürücüler modifiyeli egzozlarıyla gece geç saatlerde gaz veriyor ve komşular şikâyetçi. Bu durumun temel sorunu nedir?',
    options: [
      'Gürültü, park hâlinde ya da geçerken fark etmeksizin komşuların dinlenme ve uyku hakkını ihlal eder; bir kişinin araç zevki, bir mahallenin huzurundan daha önemli olamaz',
      'Sorun yalnızca aracın hızındadır, sesin bir önemi yoktur',
      'Komşular pencerelerini kapatarak çözebilir, sürücülere düşen bir şey yoktur',
      'Egzoz sesi güçlüyse araç daha güvenlidir, bu yüzden hoş görülmelidir',
    ],
    answerIndex: 0,
    explanation:
      'Araç gürültüsü yalnızca yolda değil, park hâlinde gaz verilirken de çevreye yayılır ve evlerin içine girer. Uyku ve huzur, korunması gereken haklardır. Kişisel bir zevk uğruna bütün bir mahallenin gecesini bölmek, komşu hakkının açık bir ihlalidir.',
    whyWrong: [
      'Sorun hız değil, doğrudan gereksiz ve aşırı gürültüdür.',
      'Çözümü komşulardan beklemek sorumluluğu tersine çevirir; güçlü egzoz sesi güvenlikle değil yalnızca gösterişle ilgilidir.',
    ],
    objective: 'Modifiyeli egzoz gürültüsünün komşu hakkına etkisini kavramak.',
    tags: ['egzoz-komsu-hakki', 'komsu-hakki', 'gurultu'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-641',
    subject: 'adab',
    topic: 'site-ici-hiz-gorgusu',
    difficulty: 'kolay',
    stem: 'Oturduğunuz sitenin içinde çocukların bisiklete bindiği, yayaların yürüdüğü dar yollar var. Site içi sürüşte en doğru davranış hangisidir?',
    options: [
      'Site özel alan olduğu için trafik kurallarının geçerli olmadığını düşünmek',
      'Adım hızında, çok yavaş ve her an durabilecek şekilde ilerlemek; çocukların ansızın önünüze çıkabileceğini hesaba katmak',
      'Yol boşsa normal şehir içi hızıyla geçmek',
      'Kimse yoksa hızlanıp bir an önce park yerine ulaşmak',
    ],
    answerIndex: 1,
    explanation:
      'Site içi yollar, çocukların oyun alanı gibidir; bir top ya da bir bisiklet her an köşeden çıkabilir. Burada güvenliğin tek güvencesi, her an durabilecek kadar yavaş gitmektir. Boş görünmek ile boş olmak aynı şey değildir.',
    whyWrong: [
      'Sitenin özel alan olması sorumluluğu azaltmaz; tam tersine yayaların yoğunluğu daha da dikkatli olmayı gerektirir.',
      'Normal şehir hızı ya da kimse yok diye hızlanmak, çocukların öngörülemez hareketleri karşısında ölümcül olabilir.',
    ],
    objective: 'Site içi alanlarda adım hızında, çocuk güvenliğini önceleyen sürüşü benimsemek.',
    tags: ['site-ici-hiz-gorgusu', 'cocuk-guvenligi', 'dusuk-hiz'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-642',
    subject: 'adab',
    topic: 'site-ici-hiz-gorgusu',
    difficulty: 'orta',
    stem: 'Bir komşunuz, sitenin içinde hızlı sürüp "burası benim de yaşadığım yer, istediğim gibi kullanırım" diyor. Site içi hız görgüsü açısından en doğru değerlendirme nedir?',
    options: [
      'Kendi sitesi olduğu için istediği hızda gitme hakkı vardır',
      'Site içinde kural olmadığından herkes kendi kararını verir',
      'Ortak yaşam alanında herkesin, özellikle çocukların güvenliği kişisel konfordan önce gelir; kendi mahallende yavaş sürmek, komşularına ve çocuklarına duyduğun saygının göstergesidir',
      'Yalnızca misafirler yavaş sürmeli, siteyi tanıyanlar hızlı gidebilir',
    ],
    answerIndex: 2,
    explanation:
      'Burada ben de yaşıyorum düşüncesi aslında tam tersini gerektirir: kendi çocuklarının, komşularının yürüdüğü yolda daha da dikkatli olmayı. Ortak alan, herkesin güvenliğinin ortak sorumluluk olduğu yerdir. Tanıdık olmak, hız yapma değil, daha çok özen gösterme nedenidir.',
    whyWrong: [
      'Kendi sitem düşüncesi, o yolu paylaşan diğer sakinlerin güvenlik hakkını yok sayar.',
      'Siteyi tanımak riski azaltmaz; çocuklar her an beklenmedik biçimde hareket edebilir, kural yokluğu sorumsuzluğa izin vermez.',
    ],
    objective: 'Ortak yaşam alanında hız görgüsünü komşuluk sorumluluğu olarak kavramak.',
    tags: ['site-ici-hiz-gorgusu', 'komsu-hakki', 'sorumluluk'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-643',
    subject: 'adab',
    topic: 'yaya-tutarliligi',
    difficulty: 'kolay',
    stem: 'Sürüş sırasında yayaların kurallara uymasını bekleyen bir kişinin, kendisi yaya olduğunda da kırmızı ışıkta beklemesi neden önemlidir?',
    options: [
      'Tutarlılık gerektiği için; kurallara yalnızca direksiyondayken değil, yaya olarak da uymak trafik kültürünün bütünlüğünü sağlar',
      'Yaya olarak kurallara uymak gereksizdir; sorumluluk yalnızca sürücülere aittir',
      'Yaya kuralları yalnızca çocuklar için geçerlidir',
      'Trafik yoğunsa yaya kurallarına uymaya gerek yoktur',
    ],
    answerIndex: 0,
    explanation:
      'Trafik kültürü, rol değiştikçe değişmeyen bir tutarlılık ister. Sürücüyken yayadan kurala uymasını bekleyip yayayken ışığı ihlal etmek çifte standarttır. Üstelik kural tanıyan bir yaya, hem kendi güvenliğini sağlar hem de çocuklara doğru örnek olur.',
    whyWrong: [
      'Sorumluluğu yalnızca sürücülere yüklemek, yayanın da trafiğin bir parçası olduğunu unutmaktır.',
      'Yaya kuralları herkes için geçerlidir; trafiğin yoğunluğu ya da yaş, kırmızı ışığı ihlal etmeyi haklı çıkarmaz.',
    ],
    objective: 'Kurallara sürücü ve yaya olarak tutarlı biçimde uymanın önemini kavramak.',
    tags: ['yaya-tutarliligi', 'tutarlilik', 'trafik-kulturu'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-644',
    subject: 'adab',
    topic: 'yaya-tutarliligi',
    difficulty: 'orta',
    stem: 'Bir kişi araç kullanırken tüm kurallara titizlikle uyuyor, ama yaya olduğunda gelişigüzel yerden, koşarak karşıya geçiyor. Bu tutarsızlığın en doğru değerlendirmesi hangisidir?',
    options: [
      'Yaya olarak kural ihlali kimseye zarar vermez, bu yüzden sorun değildir',
      'Güvenlik ve kural bilinci role göre açılıp kapanmaz; yaya olarak yapılan ihlaller de hem kişinin kendi canını hem de ani fren yapmak zorunda kalan sürücüleri riske atar',
      'Sürücüyken kurallı olması, yayayken serbest olmasını hak ettirir',
      'Yaya ihlalleri yalnızca gece tehlikelidir',
    ],
    answerIndex: 1,
    explanation:
      'Kural bilinci bir kişilik özelliğidir; role göre açılıp kapanan bir düğme değil. Gelişigüzel yerden geçen bir yaya, kendini tehlikeye attığı gibi, onu son anda fark eden sürücüyü de ani frene ve olası bir kazaya zorlar. Tutarlılık, güvenliğin temelidir.',
    whyWrong: [
      'Yaya ihlali kimseye zarar vermez değildir; ani fren zincirleme kazalara yol açabilir.',
      'Sürücüyken kurallı olmak, yayayken ihlali hak ettirmez; tehlike yalnızca geceyle de sınırlı değildir.',
    ],
    objective: 'Kural bilincinin rol değişse de tutarlı kalması gerektiğini kavramak.',
    tags: ['yaya-tutarliligi', 'tutarlilik', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-645',
    subject: 'adab',
    topic: 'cocuga-kotu-ornek',
    difficulty: 'kolay',
    stem: 'Yanınızda çocuğunuz varken bir sürücüye kızıp yüksek sesle ağır sözler söylediniz. Bunun çocuk üzerindeki en önemli etkisi nedir?',
    options: [
      'Çocuk küçük olduğu için hiçbir şey hatırlamaz, etkilenmez',
      'Çocuk yalnızca o an korkar, sonra tümüyle unutur',
      'Çocuk, trafikte öfke ve saldırganlığı normal bir tepki olarak öğrenir; ileride kendi davranışını bugün gördüğü örneğe göre şekillendirir',
      'Çocuk sözlerin anlamını bilmediği için hiç etkilenmez',
    ],
    answerIndex: 2,
    explanation:
      'Çocuklar, ebeveynlerini bir davranış modeli olarak izler. Direksiyonda duyduğu öfkeli sözler, ona trafikte böyle davranılır mesajını verir. Bugün arka koltukta tanık olduğu saldırganlık, yıllar sonra kendi direksiyonunda yeniden hayat bulabilir.',
    whyWrong: [
      'Çocukların gözlem ve taklit gücü, yetişkinlerin sandığından çok daha güçlüdür; unutur varsayımı yanıltıcıdır.',
      'Çocuk sözlerin tam anlamını bilmese de tonu, öfkeyi ve tepkiyi kaydeder; bunları model alır.',
    ],
    objective: 'Trafikteki öfkeli davranışların çocuğa kötü örnek olduğunu kavramak.',
    tags: ['cocuga-kotu-ornek', 'model-davranis', 'ofke'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-646',
    subject: 'adab',
    topic: 'cocuga-kotu-ornek',
    difficulty: 'orta',
    stem: 'Bir ebeveyn, çocuğuna "trafik kurallarına uy" diyor ama kendisi çocuğun gözü önünde emniyet kemerini takmıyor ve telefonla mesajlaşıyor. Bu durumla ilgili en doğru değerlendirme hangisidir?',
    options: [
      'Sözlü öğüt yeterlidir; çocuk ne söylendiğine bakar, ne yapıldığına değil',
      'Çocuk büyüyünce kendisi doğrusunu nasılsa öğrenir, örneğin önemi yoktur',
      'Ebeveyn kurallara uymasa da çocuk okulda öğrendiği için sorun olmaz',
      'Söz ile davranış çeliştiğinde çocuk çoğu zaman davranışı örnek alır; yap dediğimi, yapma yaptığımı yaklaşımı işe yaramaz, tutarlı bir örneklik gerekir',
    ],
    answerIndex: 3,
    explanation:
      'Çocuk için en güçlü ders, söylenen değil yapılandır. Kurala uy deyip kendi kemerini takmayan bir ebeveyn, farkında olmadan asıl davranışı öğretir. Değerler öğütle değil, tutarlı örneklikle aktarılır; çelişki olduğunda kazanan hep görülen davranıştır.',
    whyWrong: [
      'Sözlü öğüt, ona aykırı bir davranışla birlikte verildiğinde etkisini yitirir.',
      'Nasılsa sonra öğrenir ya da okulda öğrenir varsayımları, evdeki günlük örnekliğin belirleyici gücünü küçümser.',
    ],
    objective: 'Çocuğa kural öğretiminde söz-davranış tutarlılığının önemini kavramak.',
    tags: ['cocuga-kotu-ornek', 'tutarlilik', 'aile'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-647',
    subject: 'adab',
    topic: 'hayvanlara-merhamet',
    difficulty: 'kolay',
    stem: 'Yol kenarında yaralı bir sokak hayvanı görüyorsunuz ve trafik uygun. Merhametli ve sorumlu bir sürücü ne yapar?',
    options: [
      'Hayvanları ilgilendirmez diye hiç yavaşlamadan geçmek',
      'Güvenliği sağlayarak durup mümkünse yetkililere (belediye, hayvan barınağı ya da ilgili birim) haber vermek; kendi güvenliğini de riske atmadan yardımcı olmaya çalışmak',
      'Kornaya basıp hayvanı yoldan kaçırmaya çalışmak',
      'Sosyal medyada paylaşmak için fotoğrafını çekip yola devam etmek',
    ],
    answerIndex: 1,
    explanation:
      'Trafik adabı yalnızca insanlara değil, yoldaki tüm canlılara karşı bir duyarlılığı içerir. Yaralı bir hayvan için güvenli biçimde durup yetkiliye haber vermek, hem o canlıya yardım eder hem de arkadan gelen araçların bir kazaya karışmasını önler. Merhamet, küçük bir çabayla gösterilir.',
    whyWrong: [
      'Hiç yavaşlamadan geçmek, hem merhametsizlik hem de yoldaki hayvanın başka kazalara yol açma ihtimalini görmezden gelmektir.',
      'Kornayla ürkütmek yaralı hayvanı trafiğin ortasına sürükleyebilir; yalnızca fotoğraf çekip geçmek ise hiçbir çözüm üretmez.',
    ],
    objective: 'Yoldaki hayvanlara merhamet ve sorumlulukla yaklaşmayı benimsemek.',
    tags: ['hayvanlara-merhamet', 'duyarlilik', 'yardim'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-648',
    subject: 'adab',
    topic: 'hayvanlara-merhamet',
    difficulty: 'zor',
    stem: 'Gece şehirlerarası yolda, ilerideki şeride bir hayvanın çıktığını gördünüz; arkanızda da yakın takipte bir araç var. Hem merhamet hem güvenlik açısından en doğru tepki nedir?',
    options: [
      'Direksiyonu ani kırmadan, kontrolü kaybetmeden hızı azaltmak ve mümkünse fren yaparak yavaşlamak; arkadaki aracı da hesaba katıp savrulmaya yol açacak sert manevralardan kaçınmak',
      'Hayvana çarpmamak için direksiyonu sertçe kırıp karşı şeride geçmek',
      'Hiç yavaşlamadan hızla geçip gitmek',
      'Aniden sert fren yapıp tam olduğunuz yerde durmak',
    ],
    answerIndex: 0,
    explanation:
      'Hayvana zarar vermek istemezsiniz ama ani ve sert bir manevra, hem sizi hem arkadaki aracı çok daha büyük bir tehlikeye atabilir. Doğru tepki, kontrolü koruyarak hızı azaltmaktır; direksiyonu sertçe kırmak ya da apar topar durmak, karşı şeritte ya da arkadan çarpışmalı bir kazayla sonuçlanabilir. Merhamet, kendini ve başkalarını riske atmadan gösterilir.',
    whyWrong: [
      'Direksiyonu sertçe kırıp karşı şeride geçmek, kafa kafaya çarpışma riski doğurur; bu, olası bir hayvan çarpışmasından çok daha ölümcüldür.',
      'Hiç yavaşlamamak merhametsizce, tam olduğunuz yerde ani duruş ise arkadan çarpılmaya davetiye çıkaran bir tepkidir.',
    ],
    objective:
      'Hayvanla karşılaşmada merhamet ile kendi ve başkalarının güvenliğini dengelemeyi öğrenmek.',
    tags: ['hayvanlara-merhamet', 'defansif-surus', 'gece'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-649',
    subject: 'adab',
    topic: 'trafik-gonullulugu',
    difficulty: 'kolay',
    stem: 'Trafik güvenliğine katkı sunmak isteyen bir vatandaş, araç kullanmak dışında gönüllü olarak neler yapabilir?',
    options: [
      'Yalnızca kendi aracını kurallara uygun kullanmak, başka hiçbir şey yapamaz',
      'Sadece sosyal medyada trafik kazası haberlerini paylaşmak',
      'Okullarda ve çevresinde trafik bilinci etkinliklerine katılmak, çocuklara doğru örnek olmak, güvenli davranışları yaymak ve toplumsal farkındalık çalışmalarına destek vermek',
      'Trafik güvenliği yalnızca devletin işidir, bireye düşen bir şey yoktur',
    ],
    answerIndex: 2,
    explanation:
      'Trafik güvenliği yalnızca kural ve denetimle değil, toplumsal bir bilinçle gelişir. Bir vatandaş; çocuklara örnek olarak, çevresini bilinçlendirerek ve farkındalık çalışmalarına gönüllü katılarak bu kültüre katkı sunabilir. Herkes, bulunduğu yerden trafik güvenliğinin bir parçası olabilir.',
    whyWrong: [
      'Bireyin katkısı kendi aracıyla sınırlı değildir; örneklik ve farkındalık yayarak çok daha geniş bir etki yaratabilir.',
      'Trafik güvenliğini yalnızca devlete ya da sosyal medya paylaşımına indirgemek, herkesin üstlenebileceği aktif rolü görmezden gelir.',
    ],
    objective: 'Trafik güvenliğine gönüllü katkının bireysel yollarını kavramak.',
    tags: ['trafik-gonullulugu', 'toplumsal-sorumluluk', 'farkindalik'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-650',
    subject: 'adab',
    topic: 'trafik-gonullulugu',
    difficulty: 'orta',
    stem: '"Ben kurallara uyuyorum, gerisi beni ilgilendirmez" diyen bir sürücüye trafik gönüllülüğü açısından verilecek en doğru cevap nedir?',
    options: [
      '"Haklısın, herkes yalnızca kendinden sorumludur"',
      '"Kurallara uyman yeterli, başkalarının davranışını hiç düşünme"',
      '"Trafik güvenliği yalnızca bireysel bir konudur, ortak bir sorumluluk yoktur"',
      '"Kurallara uyman çok değerli; ama trafik ortak bir alandır — çevrene iyi örnek olmak, gençleri bilinçlendirmek ve güvenli bir kültürü yaymak da hepimizin katkısıyla mümkün olur"',
    ],
    answerIndex: 3,
    explanation:
      'Kişisel kural uyumu değerli bir başlangıçtır ama tek başına yeterli değildir. Trafik, hepimizin paylaştığı bir alan; güvenli bir kültür ancak insanlar birbirine örnek olduğunda ve farkındalığı yaydığında oluşur. Gönüllülük, yalnızca ben demekten hepimiz demeye geçmektir.',
    whyWrong: [
      'Herkes yalnızca kendinden sorumlu bakışı, trafiğin ortak ve etkileşimli doğasını görmezden gelir.',
      'Başkalarının davranışını hiç düşünmemek ya da güvenliği tümüyle bireysel saymak, toplumsal bir sorun olan trafik güvenliğini eksik kavramaktır.',
    ],
    objective: 'Bireysel kural uyumunun ötesinde toplumsal gönüllülüğün değerini kavramak.',
    tags: ['trafik-gonullulugu', 'toplumsal-sorumluluk', 'orneklik'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
];
