/**
 * ÖZGÜN ilk yardım soruları — 5. genişletme (Program 2 · Faz 9). ROADMAP C.4/E.6.
 * Kaynak = Resmî temel ilk yardım rehberleri; KENDİ İFADEMİZLE. Uzman onayı gereklidir.
 */
import type { QuestionInput } from '@ea/content-schema';

const SRC = 'Resmî temel ilk yardım rehberleri (özgün ifade; uzman onayı gerekli)';

export const ILKYARDIM_QUESTIONS_5: QuestionInput[] = [
  {
    id: 'ilkyardim-501',
    subject: 'ilkyardim',
    topic: 'kendini-koruma',
    difficulty: 'kolay',
    stem: 'Kanamalı bir yaralıya müdahale eden ilk yardımcının tek kullanımlık eldiven giymesinin başlıca amacı nedir?',
    options: [
      'Ellerinin kirlenmesini önleyerek daha rahat çalışmak',
      'Yaralıya daha güçlü baskı uygulayabilmek',
      'Kanla bulaşabilecek hastalıklardan hem kendisini hem de yaralıyı korumak',
      'Eldivenin kanamayı kendiliğinden durdurması',
    ],
    answerIndex: 2,
    explanation:
      'Kan ve vücut sıvıları bazı hastalıkları bulaştırabilir. Eldiven, ilk yardımcı ile yaralı arasında koruyucu bir bariyer oluşturur; böylece mikroplar iki yönde de taşınmaz.',
    whyWrong: [
      'Temizlik ve rahatlık ikincil yararlardır; asıl amaç bulaş riskini kesmektir.',
      'Eldivenin kanamayı durdurucu veya baskıyı artırıcı bir etkisi yoktur.',
    ],
    objective: 'Eldivenin enfeksiyondan korunma amacını kavramak.',
    tags: ['kendini-koruma', 'eldiven', 'enfeksiyon'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-502',
    subject: 'ilkyardim',
    topic: 'kendini-koruma',
    difficulty: 'kolay',
    stem: 'Olay yerinde eldiven bulunmuyorsa, kanayan yaraya baskı uygulamak için ilk yardımcı ne yapabilir?',
    options: [
      'Elini temiz bir naylon poşet veya kalın kumaş gibi geçirimsiz bir malzemeyle örterek baskı uygulayabilir',
      'Kanla doğrudan temas etmekten çekinmeden çıplak elle bastırabilir',
      'Eldiven bulunana kadar kanamaya hiç müdahale etmemelidir',
      'Baskıyı yalnızca yaralının kendisinin yapmasını yasaklamalıdır',
    ],
    answerIndex: 0,
    explanation:
      'Eldiven yoksa temiz bir naylon poşet, plastik torba veya birkaç kat temiz kumaş elle yara arasına konarak bariyer oluşturulur. Ayrıca yaralının durumu uygunsa kendi eliyle yarasına baskı yapması da istenebilir.',
    whyWrong: [
      'Çıplak elle kana temas, bulaşıcı hastalık riskini gereksiz yere artırır.',
      'Hayati kanamada müdahaleyi eldiven bulunana kadar geciktirmek kan kaybını büyütür.',
    ],
    objective: 'Eldiven yokken doğaçlama bariyer kullanmayı bilmek.',
    tags: ['kendini-koruma', 'kanama', 'bariyer'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-503',
    subject: 'ilkyardim',
    topic: 'kendini-koruma',
    difficulty: 'kolay',
    stem: 'Müdahale sırasında eline yaralının kanı bulaşan ilk yardımcı, müdahale bittikten sonra ne yapmalıdır?',
    options: [
      'Ellerini yalnızca kuru bir bezle silmelidir',
      'Ellerini kolonyayla ovup bırakmalıdır',
      'Hiçbir şey yapmasına gerek yoktur; kan kuruyunca risk kalmaz',
      'Ellerini bol su ve sabunla iyice yıkamalıdır',
    ],
    answerIndex: 3,
    explanation:
      'Kanla temas eden eller, müdahale biter bitmez bol su ve sabunla iyice yıkanır. Bu basit önlem, kan yoluyla bulaşabilecek mikropların cilt üzerinden taşınma riskini azaltır.',
    whyWrong: [
      'Kuru bezle silmek mikropları uzaklaştırmaz.',
      'Kanın kuruması bulaş riskini ortadan kaldırmaz; temizlik şarttır.',
    ],
    objective: 'Kan temasından sonra el yıkama gerekliliğini bilmek.',
    tags: ['kendini-koruma', 'hijyen', 'el-yikama'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-504',
    subject: 'ilkyardim',
    topic: 'kendini-koruma',
    difficulty: 'orta',
    stem: 'İlk yardımcı olay yerinde önce kimin güvenliğini sağlamalıdır?',
    options: [
      'Önce çevredeki izleyicilerin güvenliğini',
      'Önce kendi güvenliğini; kendisi tehlikeye girerse kimseye yardım edemez',
      'Önce araçların güvenliğini',
      'Güvenlik sırası önemli değildir; hemen yaralıya koşulur',
    ],
    answerIndex: 1,
    explanation:
      'İlk yardımın temel ilkesi, ilk yardımcının önce kendi güvenliğini sağlamasıdır. Tehlikeyi değerlendirmeden yaralıya koşan kişi kendisi de yaralanırsa hem yardım edemez hem de kurtarılması gereken kişi sayısını artırır.',
    whyWrong: [
      'İzleyiciler ve araçlar, ilk yardımcı kendi güvenliğini aldıktan sonra düzenlenir.',
      'Düşünmeden yaralıya koşmak ikinci bir kazaya davetiye çıkarır.',
    ],
    objective: 'Önce kendi güvenliğini sağlama ilkesini kavramak.',
    tags: ['kendini-koruma', 'olay-yeri-guvenligi', 'oncelik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-505',
    subject: 'ilkyardim',
    topic: 'kendini-koruma',
    difficulty: 'orta',
    stem: 'İçerisi zehirli gaz veya yoğun dumanla dolmuş kapalı bir alanda baygın biri görüldüğünde ilk yardımcının doğru davranışı hangisidir?',
    options: [
      'Nefesini tutup hızla içeri dalarak kişiyi sürüklemek',
      'Ortama girip önce pencereleri tek tek kapatmak',
      'Korunmasız içeri girmemek; kapı ve pencereleri dışarıdan açtırmak, 112 ve itfaiyeye haber vermek',
      'Kişi kendiliğinden çıkana kadar hiçbir şey yapmamak',
    ],
    answerIndex: 2,
    explanation:
      'Gazla dolu ortama korunmasız giren kişi birkaç solukta kendisi de etkilenip bayılabilir. Doğru olan, korunmasız içeri girmemek, mümkünse ortamı dışarıdan havalandırmak ve 112 ile itfaiye gibi donanımlı ekipleri çağırmaktır.',
    whyWrong: [
      'Nefes tutmak koruma sağlamaz; gazlar cilt ve gözleri de etkileyebilir, kişi içeride bayılabilir.',
      'Pencereleri kapatmak gaz yoğunluğunu artırır; hiçbir şey yapmamak da yardımı geciktirir.',
    ],
    objective: 'Gazlı ortama korunmasız girilmemesi gerektiğini kavramak.',
    tags: ['kendini-koruma', 'zehirlenme', 'gaz'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-506',
    subject: 'ilkyardim',
    topic: 'olay-yeri-guvenligi',
    difficulty: 'kolay',
    stem: 'Kaza yapan aracın motor bölümünden duman yükselmeye başladığında öncelikle ne yapılmalıdır?',
    options: [
      'Duman kesilene kadar araç içinde beklenmelidir',
      'Motor kaputu açılıp dumanın kaynağına su dökülmelidir',
      'Yalnızca fotoğraf çekilerek durum belgelenmeli',
      'Kontak kapatılmalı ve araçtaki herkes hızla araçtan uzaklaştırılmalıdır',
    ],
    answerIndex: 3,
    explanation:
      'Motordan yükselen duman, yangın başlangıcının habercisi olabilir. Kontak kapatılır ve araçta bulunan herkes güvenli bir uzaklığa alınır; yangın büyürse araç içinde kalanlar için hayati tehlike doğar.',
    whyWrong: [
      'Araç içinde beklemek, olası alevlenmede kaçış süresini yok eder.',
      'Kaputu açmak aleve oksijen sağlayabilir; belgeleme can güvenliğinden önce gelmez.',
    ],
    objective: 'Araç yangını başlangıcında tahliye önceliğini bilmek.',
    tags: ['olay-yeri-guvenligi', 'arac-yangini', 'tahliye'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-507',
    subject: 'ilkyardim',
    topic: 'arac-icinden-cikarma',
    difficulty: 'orta',
    stem: 'Aşağıdakilerden hangisi yaralıyı kaza aracından derhâl çıkarmayı gerektiren geçerli bir neden DEĞİLDİR?',
    options: [
      'Araçta yangın başlaması',
      'Trafiğin daha hızlı akmasını sağlama isteği',
      'Patlama tehlikesinin belirmesi',
      'Yaralının solunumunun durması ve araç içinde canlandırma yapılamaması',
    ],
    answerIndex: 1,
    explanation:
      'Yaralı, kural olarak araçtan çıkarılmaz; yalnızca yangın, patlama tehlikesi veya solunum durması gibi yaşamsal zorunluluklar çıkarmayı haklı kılar. Trafiği rahatlatma isteği yaşamsal bir gerekçe değildir; bunun için trafik önlemleri alınır.',
    whyWrong: [
      'Yangın ve patlama tehlikesi, çıkarmama kuralının bilinen istisnalarıdır.',
      'Solunumu duran yaralıya araç içinde canlandırma yapılamıyorsa çıkarma zorunlu hâle gelir.',
    ],
    objective: 'Araçtan çıkarma istisnalarını yaşamsal gerekçelerle sınırlamak.',
    tags: ['arac-icinden-cikarma', 'istisna', 'yangin'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-508',
    subject: 'ilkyardim',
    topic: 'arac-icinden-cikarma',
    difficulty: 'zor',
    stem: 'Bacakları aracın ezilen bölümü altında sıkışmış, bilinci açık ve solunumu düzenli bir yaralı için doğru yaklaşım hangisidir?',
    options: [
      'Yaralı zorla çekilmez; itfaiye ve 112 çağrılır, ekipler gelene kadar yaralının durumu izlenir ve sakinleştirilir',
      'Yaralı iki kişi tarafından kollarından kuvvetle çekilerek kurtarılır',
      'Sıkışan bölüm yolculardan biri tarafından levyeyle rastgele kaldırılır',
      'Yaralı kendi çabasıyla çıkması için yalnız bırakılır',
    ],
    answerIndex: 0,
    explanation:
      'Sıkışmış yaralıyı zorla çekmek; kırıkları, damar ve doku hasarını ağırlaştırabilir. Yaşamsal bir zorunluluk yoksa kurtarma işi donanımlı ekiplere bırakılır; ilk yardımcı bu sürede yaralının bilincini ve solunumunu izler, onu sakinleştirir.',
    whyWrong: [
      'Kuvvetle çekmek ve kontrolsüz kaldırma girişimleri yaralanmayı derinleştirebilir.',
      'Yaralıyı yalnız bırakmak, durumu kötüleşirse müdahalesiz kalmasına yol açar.',
    ],
    objective: 'Sıkışmış yaralıda kurtarmanın profesyonel ekiplere bırakıldığını bilmek.',
    tags: ['arac-icinden-cikarma', 'sikisma', 'itfaiye'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-509',
    subject: 'ilkyardim',
    topic: 'bogulma-tikanma',
    difficulty: 'kolay',
    stem: 'Yemek sırasında aniden susan bir kişinin iki eliyle boğazını kavraması hangi durumun evrensel işaretidir?',
    options: [
      'Baş dönmesinin',
      'Yemeği beğenmediğinin',
      'Hava yolunun yabancı cisimle tıkandığının',
      'Ses kısıklığının',
    ],
    answerIndex: 2,
    explanation:
      'Ellerin boğaza götürülerek boynun kavranması, dünyaca bilinen boğulma (hava yolu tıkanması) işaretidir. Bu işareti yapan kişi konuşamıyor ve öksüremiyorsa tam tıkanma vardır ve derhâl müdahale gerekir.',
    whyWrong: [
      'Baş dönmesi ve ses kısıklığında kişi genellikle konuşabilir.',
      'Beğenmeme gibi davranışlar aniden gelişen panik tablosunu açıklamaz.',
    ],
    objective: 'Evrensel boğulma işaretini tanımak.',
    tags: ['bogulma-tikanma', 'evrensel-isaret', 'tanima'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-510',
    subject: 'ilkyardim',
    topic: 'bogulma-tikanma',
    difficulty: 'orta',
    stem: 'Hava yolu tıkanan bir bebeğe sırt vuruları uygulanırken bebek nasıl tutulmalıdır?',
    options: [
      'Sırtüstü, başı yukarıda olacak şekilde kucakta',
      'Yüzüstü, ilk yardımcının önkolu üzerinde, başı gövdesinden aşağıda ve çenesi desteklenmiş olarak',
      'Dik konumda, koltuk altlarından tutularak',
      'Ayaklarından baş aşağı sallandırılarak',
    ],
    answerIndex: 1,
    explanation:
      'Bebek, ilk yardımcının önkolu üzerine yüzüstü yatırılır; başı gövdesinden aşağıda tutulur ve çene parmaklarla desteklenir. Bu konumda yer çekimi, sırt vurularının cismi dışarı atmasına yardım eder.',
    whyWrong: [
      'Sırtüstü veya dik konumda sırt vuruları etkisiz kalır.',
      'Ayaklardan sallandırmak bebeğe zarar verebilecek kontrolsüz bir harekettir.',
    ],
    objective: 'Bebekte sırt vuruları sırasındaki doğru tutuşu bilmek.',
    tags: ['bogulma-tikanma', 'bebek', 'sirt-vurusu'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-511',
    subject: 'ilkyardim',
    topic: 'bogulma-tikanma',
    difficulty: 'orta',
    stem: 'Hava yolu tıkanan kişinin ağzındaki yabancı cisimle ilgili doğru uygulama hangisidir?',
    options: [
      'Cisim görünmese bile parmak boğaza sokularak körlemesine taranır',
      'Ağza bol su dökülerek cismin yumuşaması beklenir',
      'Cismi itmek için kişiye ekmek yedirilir',
      'Yalnızca ağızda açıkça görülen ve kolayca ulaşılabilen cisim dikkatle çıkarılır; körlemesine parmak sokulmaz',
    ],
    answerIndex: 3,
    explanation:
      'Ağız içinde açıkça görülen ve kolayca tutulabilen bir cisim dikkatle alınabilir. Görülmeyen cisme körlemesine parmakla ulaşmaya çalışmak, cismi daha derine itebilir ve dokulara zarar verebilir.',
    whyWrong: [
      'Körlemesine tarama cismi hava yolunda daha derine itebilir.',
      'Tıkalı hava yoluna su veya yiyecek vermek tabloyu ağırlaştırır.',
    ],
    objective: 'Körlemesine parmakla ağız taramasının yapılmadığını bilmek.',
    tags: ['bogulma-tikanma', 'yabanci-cisim', 'agiz-kontrolu'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-512',
    subject: 'ilkyardim',
    topic: 'oed',
    difficulty: 'kolay',
    stem: 'Havalimanı ve alışveriş merkezi gibi kalabalık yerlerde bulundurulan OED (otomatik dış defibrilatör) cihazının işlevi nedir?',
    options: [
      'Kalbi duran kişinin kalp ritmini çözümleyip gerekirse elektrik şoku vermek ve kullanıcıyı sesli komutlarla yönlendirmek',
      'Yaralının ateşini ölçmek',
      'Tansiyonu düşen kişiye ilaç vermek',
      'Yaralıyı hastaneye taşımak',
    ],
    answerIndex: 0,
    explanation:
      'OED; kalbi durmuş kişide göğse yapıştırılan pedler aracılığıyla kalp ritmini kendiliğinden çözümleyen, gerekli görürse elektrik şoku veren ve her adımı sesli komutlarla anlatan taşınabilir bir cihazdır. Halka açık noktalara bu yüzden yerleştirilir.',
    whyWrong: [
      'Ateş ölçme ve ilaç verme OED’nin işlevi değildir.',
      'Cihaz taşıma aracı değil, canlandırmaya destek veren bir yaşam kurtarma cihazıdır.',
    ],
    objective: 'OED cihazının temel işlevini tanımak.',
    tags: ['oed', 'defibrilator', 'tanim'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-513',
    subject: 'ilkyardim',
    topic: 'oed',
    difficulty: 'kolay',
    stem: 'OED cihazı şok verilmesini önerdiğinde, şok düğmesine basılmadan hemen önce ne yapılmalıdır?',
    options: [
      'Yaralının eli sıkıca tutulmalıdır',
      'Yaralının göğsüne bir battaniye örtülmelidir',
      'Yaralıya kimsenin dokunmadığından emin olunmalı ve çevredekiler sözle uyarılmalıdır',
      'Yaralı hızla oturur duruma getirilmelidir',
    ],
    answerIndex: 2,
    explanation:
      'Şok anında yaralıya dokunan kişiye de elektrik geçebilir. Bu nedenle düğmeye basmadan önce "Çekilin, kimse dokunmasın!" diye uyarılır ve yaralıya kimsenin temas etmediği gözle kontrol edilir.',
    whyWrong: [
      'El tutmak veya yaralıya dokunmak, şok sırasında ilk yardımcıyı akıma maruz bırakır.',
      'Yaralıyı oturtmak veya örtmek şok uygulamasının adımı değildir.',
    ],
    objective: 'Şok verilirken yaralıya dokunulmaması kuralını bilmek.',
    tags: ['oed', 'sok-dugmesi', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-514',
    subject: 'ilkyardim',
    topic: 'oed',
    difficulty: 'orta',
    stem: 'Canlandırma sırasında olay yerine OED getirildiğinde göğüs basılarıyla ilgili doğru davranış hangisidir?',
    options: [
      'Cihaz görülür görülmez basılar tamamen bırakılır ve yalnız cihaz beklenir',
      'Cihaz hazırlanırken basılara olabildiğince devam edilir; cihaz ritmi çözümlerken yaralıya dokunulmaz',
      'Cihaz çalışırken basılara daha hızlı devam edilir',
      'OED geldiyse göğüs basısına artık hiç gerek kalmaz',
    ],
    answerIndex: 1,
    explanation:
      'Pedler yapıştırılırken göğüs basılarına mümkün olduğunca ara vermeden devam edilir. Cihaz "çözümleme yapılıyor, dokunmayın" uyarısı verdiğinde yaralıdan el çekilir; cihaz yönlendirdiğinde basılar sürdürülür.',
    whyWrong: [
      'Basıları erkenden bırakmak dolaşım desteğini gereksiz yere keser.',
      'Çözümleme sırasında dokunmak cihazın ritmi doğru okumasını engeller; OED tek başına canlandırmanın yerini tutmaz.',
    ],
    objective: 'OED kullanılırken bası-çözümleme uyumunu kavramak.',
    tags: ['oed', 'temel-yasam-destegi', 'cozumleme'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-515',
    subject: 'ilkyardim',
    topic: 'oed',
    difficulty: 'zor',
    stem: 'Halka açık alanlardaki OED cihazlarını kimler kullanabilir?',
    options: [
      'Yalnızca hastane çalışanları',
      'Yalnızca itfaiye personeli',
      'Yalnızca cihazın bulunduğu binanın güvenlik görevlileri',
      'Sesli komutları izleyerek halktan kişiler de kullanabilir; cihaz kullanıcıyı adım adım yönlendirir',
    ],
    answerIndex: 3,
    explanation:
      'OED, sağlık eğitimi olmayan kişilerin de kullanabilmesi için tasarlanmıştır; açıldığında her adımı sesli olarak anlatır ve şoku ancak gerçekten gerekli görürse önerir. Bu sayede halka açık yerlerde erken müdahale mümkün olur.',
    whyWrong: [
      'Cihazın amacı profesyonel ekip gelmeden önce sıradan kişilerin müdahale edebilmesidir.',
      'Kullanımı belirli meslek gruplarıyla sınırlamak, erken şok şansını ortadan kaldırır.',
    ],
    objective: 'OED’nin halk tarafından kullanılabilir tasarlandığını bilmek.',
    tags: ['oed', 'halka-acik', 'kullanim'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-516',
    subject: 'ilkyardim',
    topic: 'temel-yasam-destegi',
    difficulty: 'orta',
    stem: 'Olay yerinde iki ilk yardımcı varsa, göğüs basılarının kalitesini korumak için ne yapılması önerilir?',
    options: [
      'Yorgunluk bası derinliğini düşürmeden, yaklaşık iki dakikada bir bası uygulayan kişinin değişmesi',
      'İkisinin de aynı anda göğse bastırması',
      'Birinin bası yaparken diğerinin yaralının bacaklarını ovması',
      'Yorulan kişinin dinlenirken basıların tamamen durdurulması',
    ],
    answerIndex: 0,
    explanation:
      'Göğüs basısı yorucudur ve yorulan kişinin bası derinliği fark etmeden azalır. İki ilk yardımcı varsa yaklaşık iki dakikada bir, basıya en az ara verecek biçimde hızla yer değiştirilir; böylece bası kalitesi korunur.',
    whyWrong: [
      'Aynı anda iki kişinin bastırması tekniği bozar.',
      'Bacak ovmak canlandırmaya katkı sağlamaz; basıların uzun süre durdurulması dolaşımı keser.',
    ],
    objective: 'İki kurtarıcıyla dönüşümlü bası ilkesini bilmek.',
    tags: ['temel-yasam-destegi', 'yer-degisimi', 'basi-kalitesi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-517',
    subject: 'ilkyardim',
    topic: 'temel-yasam-destegi',
    difficulty: 'orta',
    stem: 'Yüzünde ağır yaralanma olduğu için ağızdan soluk verilemeyen, solunumu durmuş bir yaralıda ilk yardımcı ne yapmalıdır?',
    options: [
      'Canlandırmayı tamamen bırakmalıdır',
      'Yaralıyı oturtup su içirmeyi denemelidir',
      'Sağlık ekibi gelene kadar kesintisiz göğüs basısına devam etmelidir',
      'Yalnızca nabız saymalıdır',
    ],
    answerIndex: 2,
    explanation:
      'Soluk verilemeyen durumlarda yalnızca göğüs basısıyla sürdürülen canlandırma bile dolaşımı destekler ve hiç müdahale etmemekten çok daha iyidir. Basılara sağlık ekibi devralana kadar ara vermeden devam edilir.',
    whyWrong: [
      'Canlandırmayı bırakmak yaşam şansını yok eder.',
      'Solunumu durmuş kişiye su vermek veya yalnız nabız saymak dolaşımı desteklemez.',
    ],
    objective: 'Soluk verilemeyen durumda yalnız bası ile canlandırmayı bilmek.',
    tags: ['temel-yasam-destegi', 'sadece-basi', 'kalp-masaji'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-518',
    subject: 'ilkyardim',
    topic: 'temel-yasam-destegi',
    difficulty: 'kolay',
    stem: 'Erişkine ağızdan ağıza suni solunum yapılırken üflenen havanın burundan geri kaçmaması için ne yapılır?',
    options: [
      'Yaralının başı yana çevrilir',
      'Baş geriye eğik konumdayken yaralının burun kanatları parmaklarla kapatılır',
      'Yaralının ağzı bir bezle örtülür',
      'Üfleme burun yerine kulağa yakın yapılır',
    ],
    answerIndex: 1,
    explanation:
      'Baş geri-çene yukarı pozisyonu korunurken alındaki elin baş ve işaret parmağıyla burun kanatları kapatılır; böylece üflenen hava burundan kaçmadan akciğerlere ulaşır.',
    whyWrong: [
      'Başı yana çevirmek hava yolunun açıklığını bozar.',
      'Ağzı örtmek veya üflemeyi başka yere yapmak havanın akciğere gitmesini engeller.',
    ],
    objective: 'Suni solunumda burun kapatma adımını bilmek.',
    tags: ['temel-yasam-destegi', 'suni-solunum', 'teknik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-519',
    subject: 'ilkyardim',
    topic: 'temel-yasam-destegi',
    difficulty: 'orta',
    stem: 'Bebeğe kurtarıcı soluk verilirken ilk yardımcının ağzı nasıl yerleştirilir?',
    options: [
      'Yalnızca bebeğin burnunu kapsayacak şekilde',
      'Bebeğin yanağına dayanarak',
      'Yalnızca alt dudağına değecek şekilde',
      'Bebeğin ağzını ve burnunu birlikte içine alacak şekilde',
    ],
    answerIndex: 3,
    explanation:
      'Bebeğin yüzü küçük olduğundan ilk yardımcı ağzıyla bebeğin ağız ve burnunu birlikte kavrar; hava, bebeğin göğsünü hafifçe yükseltecek kadar nazikçe verilir.',
    whyWrong: [
      'Yalnızca burun veya dudak üzerinden verilen hava yeterince akciğere ulaşmaz.',
      'Yanağa üflemenin solunum desteğine katkısı olmaz.',
    ],
    objective: 'Bebekte ağız-burun birlikte kavranarak soluk verildiğini bilmek.',
    tags: ['temel-yasam-destegi', 'bebek', 'kurtarici-soluk'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-520',
    subject: 'ilkyardim',
    topic: 'temel-yasam-destegi',
    difficulty: 'zor',
    stem: 'Canlandırma sırasında göğüs basılarına verilen araların olabildiğince kısa tutulması neden önemlidir?',
    options: [
      'Basıya ara verildiği anda beyne ve kalbe giden kan akımı desteği de durur',
      'Uzun aralar ilk yardımcının üşümesine yol açar',
      'Cihazların pili aralarda daha çok tükenir',
      'Aralar yaralının uyanıp kaçmasına neden olur',
    ],
    answerIndex: 0,
    explanation:
      'Kalbi durmuş kişide kanı dolaştıran tek güç göğüs basılarıdır; her ara verildiğinde beyne giden kan desteği kesilir ve yeniden etkili dolaşım kurmak zaman alır. Bu yüzden basılar ancak zorunlu anlarda ve kısa süreliğine kesilir.',
    whyWrong: [
      'Üşüme ve pil tüketimi bası kalitesiyle ilgili gerekçeler değildir.',
      'Bilinçsiz kişinin kalkıp kaçması söz konusu olamaz.',
    ],
    objective: 'Bası kesintilerinin dolaşımı durdurduğunu kavramak.',
    tags: ['temel-yasam-destegi', 'kesinti', 'dolasim'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-521',
    subject: 'ilkyardim',
    topic: 'kanama',
    difficulty: 'orta',
    stem: 'Kanayan bacağın kalp seviyesinden yukarı kaldırılması hangi durumda uygulanmaz?',
    options: [
      'Kanama beş dakikadan uzun sürüyorsa',
      'Yaralı gençse',
      'Bacakta kırık şüphesi de varsa',
      'Kanama toplardamar kaynaklıysa',
    ],
    answerIndex: 2,
    explanation:
      'Kanayan bölgeyi yükseltmek kanamayı yavaşlatmaya yardım eder; ancak aynı uzuvda kırık şüphesi varsa kaldırma hareketi kemik uçlarını oynatıp damar-sinir hasarını ve ağrıyı artırabilir. Bu durumda uzuv oynatılmadan doğrudan baskı sürdürülür.',
    whyWrong: [
      'Kanamanın süresi, türü veya yaralının yaşı yükseltmeyi engellemez.',
      'Toplardamar kanamasında da uzuvda kırık yoksa yükseltme uygulanabilir.',
    ],
    objective: 'Kırık şüphesinin yükseltme uygulamasını engellediğini bilmek.',
    tags: ['kanama', 'yukseltme', 'kirik-suphesi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-522',
    subject: 'ilkyardim',
    topic: 'kanama',
    difficulty: 'orta',
    stem: 'İç kanamadan şüphelenilen bir yaralıda ilk yardımcının doğru tutumu hangisidir?',
    options: [
      'Ağrısını azaltmak için sıcak çay içirmek',
      'Ağızdan hiçbir şey vermemek, yaşam bulgularını izlemek ve 112’yi arayıp durumu bildirmek',
      'Yaralıyı yürüterek dolaşımını hızlandırmak',
      'Karnına sıcak su torbası koyup beklemek',
    ],
    answerIndex: 1,
    explanation:
      'İç kanama dışarıdan durdurulamaz; yaralıya ağızdan yiyecek-içecek verilmez, hareket ettirilmez, bilinç ve solunum düzenli aralıklarla izlenir ve 112 aranarak iç kanama şüphesi açıkça bildirilir.',
    whyWrong: [
      'İçecek vermek olası ameliyatı geciktirebilir ve kusmaya yol açabilir.',
      'Yürütmek ve sıcak uygulama kanamayı artırabilir.',
    ],
    objective: 'İç kanama şüphesinde temel ilk yardım tutumunu bilmek.',
    tags: ['kanama', 'ic-kanama', 'tutum'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-523',
    subject: 'ilkyardim',
    topic: 'kanama',
    difficulty: 'zor',
    stem: 'Direksiyona karnını çarpan bir sürücüde, dışarıdan kanama görülmediği hâlde giderek artan karın ağrısı, karında sertlik ve solukluk-hızlı nabız gelişmesi öncelikle neyi düşündürmelidir?',
    options: [
      'Basit bir kas ağrısını',
      'Yol yorgunluğunu',
      'Araç tutmasını',
      'Karın içi organlardan kaynaklanan iç kanamayı',
    ],
    answerIndex: 3,
    explanation:
      'Karına alınan künt darbe, dış yara bırakmadan iç organları yaralayabilir. Artan karın ağrısı ve sertliğine solukluk, hızlı ve zayıf nabız gibi şok bulgularının eklenmesi iç kanamayı düşündürür; yaralı derhâl 112’ye bildirilmelidir.',
    whyWrong: [
      'Kas ağrısı ve yorgunluk şok bulgularıyla birlikte seyretmez.',
      'Araç tutması bulantıyla seyreder; karın sertliği ve şok tablosu yapmaz.',
    ],
    objective: 'Künt karın travmasında iç kanama bulgularını yorumlamak.',
    tags: ['kanama', 'ic-kanama', 'kunt-travma'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-524',
    subject: 'ilkyardim',
    topic: 'kanama',
    difficulty: 'kolay',
    stem: 'Kanayan yaranın üzerine konan sargı bezi kanla tamamen ıslanırsa ne yapılır?',
    options: [
      'Islanan sargı çıkarılmaz; üzerine yeni bir sargı eklenerek baskıya devam edilir',
      'Islanan sargı çekip atılır ve yara açık bırakılır',
      'Sargı ıslandıysa baskıya son verilir',
      'Yara sabunlu suyla ovularak yıkanır',
    ],
    answerIndex: 0,
    explanation:
      'Islanan sargıyı kaldırmak, yeni oluşmaya başlayan pıhtıyı koparıp kanamayı yeniden şiddetlendirebilir. Bu nedenle ilk sargı yerinde bırakılır ve üzerine ikinci bir sargı konarak baskı sürdürülür.',
    whyWrong: [
      'Sargıyı çıkarmak pıhtılaşmayı bozar.',
      'Baskıyı bırakmak veya yarayı ovmak kan kaybını artırır.',
    ],
    objective: 'Islanan sargının çıkarılmayıp üzerine ekleme yapıldığını bilmek.',
    tags: ['kanama', 'sargi', 'baski'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-525',
    subject: 'ilkyardim',
    topic: 'ezilme-yaralanmasi',
    difficulty: 'orta',
    stem: 'İlk yardımda "ezilme (crush) yaralanması" ne anlama gelir?',
    options: [
      'Cildin yüzeysel olarak sıyrılması',
      'Yalnızca parmak uçlarının morarması',
      'Vücudun bir bölümünün ağır bir yük altında uzun süre sıkışıp kasların ve dokuların ağır hasar görmesi',
      'Kısa süreli hafif bir çarpma',
    ],
    answerIndex: 2,
    explanation:
      'Ezilme yaralanması; enkaz, devrilen araç gibi ağır bir yükün vücut bölümünü uzun süre baskı altında tutmasıyla kaslarda ve dokularda oluşan ağır hasardır. Dış görünüm hafif olsa bile vücudun geneli etkilenebileceğinden ciddi bir acil durumdur.',
    whyWrong: [
      'Sıyrık ve hafif çarpma yüzeysel yaralanmalardır.',
      'Ezilmede sorun morarmayla sınırlı değildir; derin dokular etkilenir.',
    ],
    objective: 'Ezilme yaralanması kavramını tanımlamak.',
    tags: ['ezilme-yaralanmasi', 'tanim', 'crush'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-526',
    subject: 'ilkyardim',
    topic: 'ezilme-yaralanmasi',
    difficulty: 'zor',
    stem: 'Bacağı uzun süredir enkaz altında sıkışmış bir kişiyi ilk yardımcının kendi başına çekip çıkarmaya çalışmaması neden önerilir?',
    options: [
      'Kurtarma işlemi için ücret gerektiği için',
      'Uzun süreli sıkışmada dokular ağır hasar görmüştür; bilinçsiz kurtarma girişimi durumu ağırlaştırabilir ve kurtarma donanımlı ekiplerin işidir',
      'Kişinin enkaz altında daha rahat ettiği için',
      'Sıkışan bölgenin kendiliğinden iyileşeceği için',
    ],
    answerIndex: 1,
    explanation:
      'Uzun süre baskı altında kalan dokularda ciddi iç hasar gelişir ve bu durum dışarıdan görünmez. Eğitimsiz ve donanımsız bir kurtarma girişimi hem yaralıya zarar verebilir hem de enkazın oynamasına yol açabilir; bu nedenle 112 ve itfaiye beklenir, yaralı bu sürede yalnız bırakılmaz.',
    whyWrong: [
      'Ücret veya konfor gibi gerekçelerin ilk yardımla ilgisi yoktur.',
      'Ezilme yaralanması kendiliğinden iyileşen bir durum değildir.',
    ],
    objective: 'Uzun süreli sıkışmada kurtarmanın ekiplere bırakılma nedenini kavramak.',
    tags: ['ezilme-yaralanmasi', 'enkaz', 'profesyonel-kurtarma'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-527',
    subject: 'ilkyardim',
    topic: 'gogus-yaralanmasi',
    difficulty: 'orta',
    stem: 'Göğsüne cisim saplanmış yaralıda cismin yerinden çıkarılmamasının temel nedeni nedir?',
    options: [
      'Cismin daha sonra delil olarak incelenecek olması',
      'Cismi çıkarmanın çok uzun sürmesi',
      'Cismin pas bırakma ihtimali',
      'Saplı cismin yaralanan damarları tıkaç gibi kapatıyor olabilmesi; çıkarılırsa kanamanın şiddetlenebilmesi',
    ],
    answerIndex: 3,
    explanation:
      'Saplanan cisim, kestiği damarların üzerinde doğal bir tıkaç görevi görebilir. Cisim çekildiğinde bu tıkaç ortadan kalkar, kanama birden şiddetlenebilir ve iç organ hasarı büyüyebilir; bu yüzden cisim yerinde bırakılır.',
    whyWrong: [
      'Delil veya pas gibi gerekçeler tıbbi neden değildir.',
      'Sorun sürede değil, çıkarma işleminin kendisinin yarattığı tehlikededir.',
    ],
    objective: 'Saplanan cismin tampon etkisini kavramak.',
    tags: ['gogus-yaralanmasi', 'saplanan-cisim', 'gerekce'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-528',
    subject: 'ilkyardim',
    topic: 'gogus-yaralanmasi',
    difficulty: 'orta',
    stem: 'Göğsünde delici yarası olan, bilinci açık ve nefes almakta zorlanan yaralıya hangi pozisyon verilmesi uygundur?',
    options: [
      'Yarı oturur pozisyon',
      'Yüzükoyun pozisyon',
      'Baş aşağıda, ayaklar yukarıda pozisyon',
      'Dizler karına çekili yan pozisyon',
    ],
    answerIndex: 0,
    explanation:
      'Bilinci açık göğüs yaralısında yarı oturur pozisyon, göğüs kafesinin daha rahat genişlemesine izin vererek solunumu kolaylaştırır. Yaralı bu pozisyonda sakin tutulur ve 112 beklenir.',
    whyWrong: [
      'Yüzükoyun ve baş aşağı pozisyonlar göğse binen basıncı artırıp solunumu güçleştirir.',
      'Dizleri karına çekmek karın yaralanmalarında düşünülen bir pozisyondur.',
    ],
    objective: 'Göğüs yaralısında yarı oturur pozisyonu bilmek.',
    tags: ['gogus-yaralanmasi', 'pozisyon', 'solunum'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-529',
    subject: 'ilkyardim',
    topic: 'gogus-yaralanmasi',
    difficulty: 'zor',
    stem: 'Vücuda saplanmış bir cismin taşıma sırasında oynamaması için ilk yardımcı ne yapabilir?',
    options: [
      'Cismi bantla doğrudan cilde yapıştırır',
      'Cismi hafifçe gevşetip yeniden yerleştirir',
      'Cismin iki yanına rulo yapılmış temiz bezler koyup bunları sargıyla sabitler; cisme yük bindirmez',
      'Cismin görünen bölümünü keserek kısaltır',
    ],
    answerIndex: 2,
    explanation:
      'Saplı cismin çevresi, iki yanına yerleştirilen rulo bez veya bandajlarla desteklenir ve bu destekler sargıyla tespit edilir. Amaç, taşıma sırasında cismin kıpırdayıp dokularda yeni hasar açmasını önlemektir; cismin üzerine baskı uygulanmaz.',
    whyWrong: [
      'Cismi oynatmak, gevşetmek veya kesmeye çalışmak titreşimle iç hasarı artırabilir.',
      'Yalnızca banda güvenmek cismi devrilmeye karşı korumaz.',
    ],
    objective: 'Saplanan cismin destek malzemesiyle sabitlenmesini bilmek.',
    tags: ['gogus-yaralanmasi', 'sabitleme', 'saplanan-cisim'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-530',
    subject: 'ilkyardim',
    topic: 'kafa-travmasi',
    difficulty: 'orta',
    stem: 'Başından ağır darbe alan bir yaralıya neden aynı zamanda boyun (omurga) yaralanması da varmış gibi davranılır?',
    options: [
      'Boyunluk takmak yasal zorunluluk olduğu için',
      'Başa gelen darbenin gücü boyna da iletilebildiği ve omurga hasarı dıştan her zaman belli olmadığı için',
      'Boyun yaralanması yalnızca yaşlılarda görüldüğü için',
      'Baş yaralanması boyundakinden daha önemsiz olduğu için',
    ],
    answerIndex: 1,
    explanation:
      'Başı yaralayan enerji çoğu zaman boyun omurlarına da yansır ve omurga hasarı dışarıdan görünmeyebilir. Bu nedenle ağır kafa travmalı her yaralıda boyun da yaralı kabul edilir; baş-boyun ekseni korunur ve yaralı gereksiz yere oynatılmaz.',
    whyWrong: [
      'Yaklaşımın gerekçesi yasal değil, tıbbidir.',
      'Boyun yaralanması her yaşta görülebilir; kafa travması önemsiz değildir.',
    ],
    objective: 'Kafa travmasında omurganın birlikte değerlendirildiğini kavramak.',
    tags: ['kafa-travmasi', 'omurga', 'birlikte-degerlendirme'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-531',
    subject: 'ilkyardim',
    topic: 'omurga-yaralanmasi',
    difficulty: 'kolay',
    stem: 'Omurga yaralanması şüphesi olan yaralının başı, sağlık ekibi gelene kadar nasıl korunur?',
    options: [
      'Baş bir yastıkla öne doğru itilir',
      'Baş sağa sola çevrilerek rahatlatılır',
      'Yaralı ayağa kaldırılarak başı dik tutulur',
      'İlk yardımcı iki eliyle başı iki yandan kavrayıp baş-boyun-gövde ekseninde hareketsiz tutar',
    ],
    answerIndex: 3,
    explanation:
      'Omurga şüphesinde ilk yardımcı yaralının baş ucuna geçer ve iki eliyle başı iki yandan kavrayarak baş-boyun-gövde ekseninde sabit tutar. Bu basit destek, omurilik hasarını ağırlaştıracak istemsiz hareketleri önler.',
    whyWrong: [
      'Başı itmek, çevirmek veya yaralıyı kaldırmak omuriliğe zarar verebilir.',
      'Yastıkla öne itme boyun eksenini bozar.',
    ],
    objective: 'Elle baş sabitleme uygulamasını bilmek.',
    tags: ['omurga-yaralanmasi', 'bas-sabitleme', 'eksen'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-532',
    subject: 'ilkyardim',
    topic: 'bayilma',
    difficulty: 'kolay',
    stem: 'Bayıldıktan kısa süre sonra kendine gelen kişiyle ilgili doğru davranış hangisidir?',
    options: [
      'Hemen ayağa kaldırılmaz; bir süre dinlendirilir ve kendini iyi hissedene kadar yavaş hareket etmesi sağlanır',
      'Kendine gelir gelmez ayağa kaldırılıp yürütülür',
      'Hemen araç kullanmasına izin verilir',
      'Koşturularak kan dolaşımı hızlandırılır',
    ],
    answerIndex: 0,
    explanation:
      'Bayılma sonrasında dolaşım henüz tam dengelenmemiştir; kişi hemen ayağa kaldırılırsa yeniden bayılabilir. Bir süre yatarak veya oturarak dinlenmesi sağlanır, ayağa yavaş kaldırılır.',
    whyWrong: [
      'Erken ayağa kaldırmak ve yürütmek tekrar bayılmaya yol açabilir.',
      'Yeni bayılmış kişinin araç kullanması kendisi ve trafik için tehlikelidir.',
    ],
    objective: 'Bayılma sonrası erken ayağa kaldırmama kuralını bilmek.',
    tags: ['bayilma', 'toparlanma', 'dinlenme'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-533',
    subject: 'ilkyardim',
    topic: 'bayilma',
    difficulty: 'kolay',
    stem: 'Bayılmış bir kişiye aşağıdakilerden hangisinin yapılması YANLIŞTIR?',
    options: [
      'Sıkan giysilerinin gevşetilmesi',
      'Yüzüne tokat atılması ve kolonya koklatılarak zorla ayıltılmaya çalışılması',
      'Solunumunun kontrol edilmesi',
      'Ortamın havalandırılması',
    ],
    answerIndex: 1,
    explanation:
      'Bayılan kişiye tokat atmak, su çarpmak veya kolonya koklatmak gibi zorla ayıltma girişimleri yarar sağlamaz, zarar verebilir. Doğru olan solunumu kontrol etmek, sıkan giysileri gevşetmek ve temiz hava sağlamaktır.',
    whyWrong: [
      'Giysileri gevşetmek ve havalandırmak solunumu rahatlatan doğru adımlardır.',
      'Solunum kontrolü, bayılmanın daha ciddi bir durum olup olmadığını ayırt ettirir.',
    ],
    objective: 'Bayılmada zorla ayıltma girişimlerinin yanlışlığını bilmek.',
    tags: ['bayilma', 'yanlis-uygulama', 'kolonya'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-534',
    subject: 'ilkyardim',
    topic: 'havale-epilepsi',
    difficulty: 'kolay',
    stem: 'Sara (epilepsi) nöbeti geçiren kişiye aşağıdakilerden hangisi kesinlikle YAPILMAZ?',
    options: [
      'Başının altına yumuşak bir destek konması',
      'Çenesi zorla açılarak ağzına kaşık, bez gibi bir cisim sokulması',
      'Çevresindeki sert cisimlerin uzaklaştırılması',
      'Nöbetin ne kadar sürdüğüne dikkat edilmesi',
    ],
    answerIndex: 1,
    explanation:
      'Nöbet sırasında kişinin çenesini açmaya çalışmak ve ağzına cisim sokmak; dişleri kırabilir, ağız içini yaralayabilir ve cismin hava yoluna kaçmasına yol açabilir. Kasılmalar zorla engellenmez; kişinin kendini yaralaması önlenerek nöbetin geçmesi beklenir.',
    whyWrong: [
      'Baş desteği ve sert cisimlerin uzaklaştırılması yaralanmayı önleyen doğru adımlardır.',
      'Nöbet süresini izlemek, 112’ye verilecek önemli bir bilgidir.',
    ],
    objective: 'Nöbette ağza cisim sokulmayacağını bilmek.',
    tags: ['havale-epilepsi', 'yapilmayacaklar', 'agiz'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-535',
    subject: 'ilkyardim',
    topic: 'havale-epilepsi',
    difficulty: 'orta',
    stem: 'Sara nöbeti sona eren, bilinci henüz tam açılmamış ancak solunumu düzenli olan kişiye ne yapılır?',
    options: [
      'Hemen ayağa kaldırılıp yürütülür',
      'Ağzına şekerli su verilir',
      'Sırtüstü bırakılıp yalnız başına terk edilir',
      'Yan (derlenme) pozisyonuna alınır ve kendine gelene kadar yanında kalınır',
    ],
    answerIndex: 3,
    explanation:
      'Nöbet sonrası dönemde kişi uykulu ve şaşkındır; salgıların ve olası kusmuğun hava yolunu tıkamaması için solunumu düzenliyse yan (derlenme) pozisyonuna alınır, tamamen kendine gelene kadar gözlem altında tutulur.',
    whyWrong: [
      'Bilinci bulanık kişiye ağızdan bir şey vermek boğulma riski yaratır.',
      'Kişiyi yürütmek veya yalnız bırakmak bu savunmasız dönemde tehlikelidir.',
    ],
    objective: 'Nöbet sonrası derlenme pozisyonunu bilmek.',
    tags: ['havale-epilepsi', 'derlenme-pozisyonu', 'nobet-sonrasi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-536',
    subject: 'ilkyardim',
    topic: 'havale-epilepsi',
    difficulty: 'orta',
    stem: 'Nöbet geçiren bir kişi için 112’nin aranması özellikle hangi durumda gerekir?',
    options: [
      'Kişi hayatında ilk kez nöbet geçiriyorsa, nöbet uzun sürüyorsa veya art arda tekrarlıyorsa',
      'Nöbet kısa sürüp kişi tamamen kendine geldiyse ve bilinen hastalığıysa',
      'Kişinin yakınları olay yerindeyse',
      'Nöbet gündüz saatlerinde olduysa',
    ],
    answerIndex: 0,
    explanation:
      'İlk kez geçirilen nöbet, uzun süren nöbet, art arda tekrarlayan nöbetler ve nöbet sırasında oluşan yaralanmalar acil tıbbi değerlendirme gerektirir. Bilinen hastalığı olan ve kısa nöbetin ardından tamamen toparlanan kişide durum yakınlarıyla birlikte değerlendirilebilir.',
    whyWrong: [
      'Yakınların olay yerinde olması veya günün saati aciliyet ölçütü değildir.',
      'Kısa süren ve bilinen nöbet her zaman ambulans gerektirmeyebilir; yine de şüphede 112 aranır.',
    ],
    objective: '112 gerektiren nöbet durumlarını ayırt etmek.',
    tags: ['havale-epilepsi', '112', 'ilk-nobet'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-537',
    subject: 'ilkyardim',
    topic: 'diyabet-acilleri',
    difficulty: 'kolay',
    stem: 'Şeker hastası olduğu bilinen ve bilinci KAPALI olan bir kişiye ilk yardımda ne yapılmaz?',
    options: [
      '112’nin aranması',
      'Solunumunun kontrol edilmesi',
      'Ağzına şekerli su veya yiyecek verilmeye çalışılması',
      'Solunumu varsa yan pozisyona alınması',
    ],
    answerIndex: 2,
    explanation:
      'Bilinci kapalı kişi yutkunamaz; ağzına verilen sıvı veya yiyecek soluk borusuna kaçarak boğulmaya yol açabilir. Şeker hastası bile olsa bilinci kapalı kişiye ağızdan hiçbir şey verilmez; solunum kontrol edilir, gerekirse yan pozisyon verilir ve 112 aranır.',
    whyWrong: [
      '112 çağrısı ve solunum kontrolü her bilinç kaybında temel adımlardır.',
      'Solunumu olan bilinçsiz kişide yan pozisyon hava yolunu korur.',
    ],
    objective: 'Bilinci kapalı kişiye ağızdan bir şey verilmediğini bilmek.',
    tags: ['diyabet-acilleri', 'bilinc-kapali', 'agizdan-verme'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-538',
    subject: 'ilkyardim',
    topic: 'diyabet-acilleri',
    difficulty: 'zor',
    stem: 'Şeker hastasında dakikalar içinde hızla gelişen terleme, titreme, sinirlilik ve ani açlık hissi öncelikle hangi durumu düşündürür?',
    options: [
      'Kan basıncının yükselmesini',
      'Kan şekerinin düşmesini',
      'Vücut ısısının yükselmesini',
      'Görme bozukluğunu',
    ],
    answerIndex: 1,
    explanation:
      'Kan şekeri düşüklüğü belirtileri dakikalar içinde hızla gelişir: soğuk terleme, titreme, sinirlilik, ani açlık ve giderek bilinç bulanıklığı görülür. Kişi bilinçliyse ve güvenle yutabiliyorsa şekerli içecek verilebilir; bilinç bulanıyorsa 112 aranır.',
    whyWrong: [
      'Tansiyon ve ateş yükselmesi bu kadar hızlı ve bu belirti kümesiyle seyretmez.',
      'Görme bozukluğu tek başına bu tabloyu açıklamaz.',
    ],
    objective: 'Hızlı gelişen belirtilerin kan şekeri düşmesine işaret ettiğini bilmek.',
    tags: ['diyabet-acilleri', 'kan-sekeri', 'belirti'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-539',
    subject: 'ilkyardim',
    topic: 'sicak-soguk-uygulama',
    difficulty: 'kolay',
    stem: 'Yeni oluşmuş burkulma ve ezik gibi kapalı yumuşak doku yaralanmalarında şişliği ve ağrıyı azaltmak için hangisi uygulanır?',
    options: [
      'Sıcak su torbası',
      'Bölgenin ovulması',
      'Bölgenin sürekli hareket ettirilmesi',
      'Soğuk uygulama',
    ],
    answerIndex: 3,
    explanation:
      'Yeni (akut) kapalı yaralanmalarda soğuk uygulama damarları büzerek kanamayı ve şişliği sınırlar, ağrıyı hafifletir. Sıcak uygulama bu erken dönemde kan akımını artırarak şişliği büyütür.',
    whyWrong: [
      'Sıcak uygulama ve ovma, taze yaralanmada kanamayı ve ödemi artırır.',
      'Yaralı bölgeyi hareket ettirmek doku hasarını derinleştirir.',
    ],
    objective: 'Akut yumuşak doku yaralanmasında soğuk uygulamayı bilmek.',
    tags: ['sicak-soguk-uygulama', 'soguk', 'burkulma'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-540',
    subject: 'ilkyardim',
    topic: 'sicak-soguk-uygulama',
    difficulty: 'kolay',
    stem: 'Soğuk uygulamada buz neden doğrudan cilde konmaz?',
    options: [
      'Çıplak cilde değen buz, dokuda soğuk yanığına (donmaya benzer hasara) yol açabileceği için',
      'Buzun cilde yapışıp kaybolacağı için',
      'Buzun etkisini tamamen yitireceği için',
      'Cildin buzu eritmesinin uzun sürmesi nedeniyle',
    ],
    answerIndex: 0,
    explanation:
      'Buz doğrudan cilde uygulanırsa aşırı soğuk, dokularda donmaya benzer hasar oluşturabilir. Bu nedenle buz bir beze veya havluya sarılarak uygulanır.',
    whyWrong: [
      'Buzun yapışması veya erime hızı temel gerekçe değildir.',
      'Beze sarılan buz etkisini yitirmez; tam tersine güvenli biçimde soğutur.',
    ],
    objective: 'Buzun beze sarılarak uygulandığını bilmek.',
    tags: ['sicak-soguk-uygulama', 'buz', 'cilt-korumasi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-541',
    subject: 'ilkyardim',
    topic: 'sicak-soguk-uygulama',
    difficulty: 'orta',
    stem: 'Soğuk uygulamanın aynı bölgede uzun süre kesintisiz tutulmamasının nedeni nedir?',
    options: [
      'Bölgenin kaşınmaya başlaması',
      'Buzun pahalı bir malzeme olması',
      'Aşırı ve uzun soğuğun kendisinin dolaşımı bozup dokuya zarar verebilmesi',
      'Yaralının üşüyüp uykuya dalması',
    ],
    answerIndex: 2,
    explanation:
      'Soğuk, kısa ve aralıklı uygulandığında yararlıdır; aynı noktada uzun süre kesintisiz tutulursa bölgedeki kan dolaşımını aşırı azaltarak dokuda hasara yol açabilir. Bu nedenle uygulamaya ara verilerek devam edilir.',
    whyWrong: [
      'Kaşıntı ve maliyet, uygulama süresini belirleyen ölçütler değildir.',
      'Amaç uyku düzeni değil, dokunun korunmasıdır.',
    ],
    objective: 'Soğuk uygulamanın aralıklı yapılmasının gerekçesini kavramak.',
    tags: ['sicak-soguk-uygulama', 'sure', 'doku-korumasi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-542',
    subject: 'ilkyardim',
    topic: 'burkulma',
    difficulty: 'kolay',
    stem: 'Ayak bileği burkulan bir kişide aşağıdakilerden hangisinin yapılması YANLIŞTIR?',
    options: [
      'Bileğin dinlendirilmesi',
      'Eklemin çekiştirilerek yerine oturtulmaya çalışılması',
      'Beze sarılı soğuk uygulama yapılması',
      'Bileğin kalp seviyesinden yukarıda tutulması',
    ],
    answerIndex: 1,
    explanation:
      'Burkulan eklemi çekiştirmek veya "yerine oturtmaya" çalışmak; bağ, damar ve sinir hasarını ağırlaştırabilir. Doğru yaklaşım dinlenme, soğuk uygulama, destekleyici sargı ve bileğin yükseltilmesidir.',
    whyWrong: [
      'Dinlendirme, soğuk uygulama ve yükseltme burkulmanın temel ilk yardım adımlarıdır.',
      'Eklem düzeltme girişimi yalnızca sağlık profesyonellerinin işidir.',
    ],
    objective: 'Burkulmada eklemi çekiştirmenin yanlışlığını bilmek.',
    tags: ['burkulma', 'yapilmayacaklar', 'eklem'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-543',
    subject: 'ilkyardim',
    topic: 'burkulma',
    difficulty: 'kolay',
    stem: 'Burkulan bileğin kalp seviyesinden yukarıda tutulmasının amacı nedir?',
    options: [
      'Kişinin daha rahat televizyon izlemesi',
      'Bileğin daha hızlı terlemesi',
      'Eklemin kendiliğinden yerine oturması',
      'Bölgeye kan göllenmesini azaltarak şişliğin sınırlanması',
    ],
    answerIndex: 3,
    explanation:
      'Yaralanan uzuv kalp seviyesinin üzerine kaldırıldığında bölgede sıvı ve kan birikimi azalır; böylece şişlik ve buna bağlı ağrı sınırlanır.',
    whyWrong: [
      'Konfor ve terleme, yükseltmenin tıbbi amacı değildir.',
      'Yükseltme eklemi yerine oturtmaz; şişliği azaltır.',
    ],
    objective: 'Yükseltmenin şişliği azaltma amacını kavramak.',
    tags: ['burkulma', 'yukseltme', 'sislik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-544',
    subject: 'ilkyardim',
    topic: 'kene-hayvan-isirigi',
    difficulty: 'orta',
    stem: 'Vücuda tutunmuş bir kene nasıl çıkarılmalıdır?',
    options: [
      'İnce uçlu bir cımbızla deriye en yakın noktasından tutulup düz ve yavaş bir hareketle çekilmeli, ardından sağlık kuruluşuna başvurulmalıdır',
      'Parmaklarla ezilerek koparılmalıdır',
      'Kene kendiliğinden düşene kadar haftalarca beklenmelidir',
      'Deriyle birlikte kesilip çıkarılmalıdır',
    ],
    answerIndex: 0,
    explanation:
      'Kene, ince uçlu cımbızla deriye en yakın yerinden tutulur ve döndürmeden, düz ve yavaş bir hareketle çekilir; bölge sonrasında temizlenir ve hastalık riski nedeniyle sağlık kuruluşuna başvurulur.',
    whyWrong: [
      'Keneyi ezmek veya koparmak, ağız parçalarının deride kalmasına ve mikrop bulaşmasına yol açar.',
      'Beklemek veya deriyi kesmek bulaş riskini ve doku hasarını artırır.',
    ],
    objective: 'Kenenin cımbızla düz çekilerek çıkarıldığını bilmek.',
    tags: ['kene-hayvan-isirigi', 'kene', 'cimbiz'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-545',
    subject: 'ilkyardim',
    topic: 'kene-hayvan-isirigi',
    difficulty: 'kolay',
    stem: 'Deriye tutunmuş kenenin üzerine kolonya, gaz yağı dökmek veya sigarayla yakmaya çalışmak neden yanlıştır?',
    options: [
      'Kenenin daha da büyümesine yol açtığı için',
      'Kene bu maddelere karşı tamamen duyarsız olduğu için',
      'Rahatsız edilen kenenin içeriğini deriye boşaltabilmesi ve hastalık bulaştırma riskinin artması nedeniyle',
      'Kolonyanın kene için besleyici olması nedeniyle',
    ],
    answerIndex: 2,
    explanation:
      'Kimyasal madde dökülen veya yakılmaya çalışılan kene strese girer ve mide içeriğini insan derisine boşaltabilir; bu da mikrop bulaştırma olasılığını artırır. Kene yalnızca uygun teknikle, cımbızla çıkarılır.',
    whyWrong: [
      'Sorun kenenin büyümesi veya beslenmesi değil, bulaş riskinin artmasıdır.',
      'Kene bu maddelerden etkilenir; ancak etkilenme biçimi tehlike yaratır.',
    ],
    objective: 'Keneye kimyasal uygulamanın bulaş riskini artırdığını kavramak.',
    tags: ['kene-hayvan-isirigi', 'yanlis-uygulama', 'bulas'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-546',
    subject: 'ilkyardim',
    topic: 'kene-hayvan-isirigi',
    difficulty: 'orta',
    stem: 'Kedi veya köpek ısırığında yara küçük görünse bile sağlık kuruluşuna başvurulmasının başlıca nedeni nedir?',
    options: [
      'Yaranın iz bırakma olasılığı',
      'Kuduz ve yara enfeksiyonu riskinin ancak sağlık kuruluşunda değerlendirilebilmesi',
      'Hayvan sahibinden şikayetçi olma zorunluluğu',
      'Isırık yerinin kaşınacak olması',
    ],
    answerIndex: 1,
    explanation:
      'Hayvan ısırıklarında kuduz bulaşma olasılığı ve yara enfeksiyonu riski vardır; aşı ve tedavi gerekip gerekmediğine sağlık kuruluşu karar verir. Yara sabunlu suyla yıkandıktan sonra kişi küçük ısırıkta bile mutlaka sağlık kuruluşuna yönlendirilir.',
    whyWrong: [
      'İz kalması ve kaşıntı, başvurunun tıbbi gerekçesi değildir.',
      'Şikayet hakkı ayrı bir konudur; sağlık başvurusunun yerini tutmaz.',
    ],
    objective: 'Hayvan ısırığında kuduz riski nedeniyle başvuru gerekliliğini bilmek.',
    tags: ['kene-hayvan-isirigi', 'kuduz', 'isirik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-547',
    subject: 'ilkyardim',
    topic: 'zehirlenme',
    difficulty: 'kolay',
    stem: 'Ev temizliği sırasında iki farklı temizlik kimyasalını karıştırıp açığa çıkan gazdan etkilenen kişi için ortam güvenliyse ilk yapılması gereken nedir?',
    options: [
      'Kişiye ortamda süt içirilmesi',
      'Kişinin aynı ortamda dinlendirilmesi',
      'Gazın kokusunun tanınmaya çalışılması',
      'Kişinin ortamdan çıkarılıp temiz havaya alınması, kapı ve pencerelerin açılması ve 112’nin aranması',
    ],
    answerIndex: 3,
    explanation:
      'Solunan zehirli gazda ilk adım, kişiyi gaz kaynağından uzaklaştırıp temiz havaya çıkarmaktır; ortam havalandırılır ve 112 aranarak hangi maddelerin karıştığı bildirilir.',
    whyWrong: [
      'Kişiyi aynı ortamda tutmak gaz solumaya devam etmesine yol açar.',
      'Süt içirmenin solunum zehirlenmesinde yeri yoktur; koku tanımaya çalışmak ilk yardımcıyı da etkileyebilir.',
    ],
    objective: 'Gaz zehirlenmesinde temiz havaya çıkarma adımını bilmek.',
    tags: ['zehirlenme', 'gaz', 'temiz-hava'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-548',
    subject: 'ilkyardim',
    topic: 'kanama',
    difficulty: 'orta',
    stem: 'Zorunlu hâllerde uygulanan turnike için hangi malzeme UYGUN DEĞİLDİR?',
    options: [
      'Tel, ip ve misina gibi ince, kesici malzemeler',
      'Üçgen bandaj',
      'Katlanmış geniş kumaş şerit',
      'Kravat gibi geniş bir bez',
    ],
    answerIndex: 0,
    explanation:
      'Turnikede tel, ip, misina gibi ince malzemeler dokuya gömülerek damar ve sinirleri keser. Uygulama ancak geniş, yumuşak ve dokuyu kesmeyen malzemelerle (üçgen bandaj, katlanmış kumaş, kravat gibi) yapılır.',
    whyWrong: [
      'Üçgen bandaj ve geniş kumaşlar basıncı geniş yüzeye yayarak dokuyu korur.',
      'Kravat da yeterli genişlikte olduğu için kullanılabilir.',
    ],
    objective: 'Turnike malzemesinin geniş ve kesici olmayan olması gerektiğini bilmek.',
    tags: ['kanama', 'turnike', 'malzeme'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-549',
    subject: 'ilkyardim',
    topic: 'kanama',
    difficulty: 'orta',
    stem: 'Burun kanamasında başın geriye yatırılmamasının nedeni nedir?',
    options: [
      'Boynun ağrımasına yol açması',
      'Kanamanın gözlere sıçraması',
      'Geriye akan kanın yutulmasına veya soluk borusuna kaçmasına neden olabilmesi',
      'Kanamanın tamamen görünmez olması',
    ],
    answerIndex: 2,
    explanation:
      'Baş geriye yatırıldığında kan burun arkasından boğaza akar; yutulan kan mide bulantısı ve kusmaya yol açabilir, soluk borusuna kaçarsa solunumu tehdit eder. Bu yüzden baş hafifçe öne eğilir ve burun kanatlarına baskı uygulanır.',
    whyWrong: [
      'Boyun ağrısı veya kanın göze sıçraması temel gerekçe değildir.',
      'Sorun kanamanın görünmemesi değil, yanlış yöne akmasıdır.',
    ],
    objective: 'Burun kanamasında başın öne eğilmesinin gerekçesini kavramak.',
    tags: ['kanama', 'burun-kanamasi', 'pozisyon'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-550',
    subject: 'ilkyardim',
    topic: 'bilinc-bozuklugu',
    difficulty: 'orta',
    stem: 'Sırtüstü yatan, bilinci kapalı bir yaralı kusmaya başlarsa ilk yardımcı ne yapmalıdır?',
    options: [
      'Yaralının ağzını elle kapatmalıdır',
      'Kusmuğun hava yolunu tıkamaması için yaralıyı, omurga şüphesi varsa baş-boyun-gövde eksenini koruyarak yan çevirmelidir',
      'Yaralıyı oturtup su içirmelidir',
      'Kusma bitene kadar hiçbir şey yapmadan izlemelidir',
    ],
    answerIndex: 1,
    explanation:
      'Sırtüstü yatan bilinçsiz kişide kusmuk soluk borusuna kaçarak boğulmaya yol açabilir. Yaralı derhâl yan çevrilir; omurga yaralanması şüphesi varsa bu dönüş, baş-boyun-gövde ekseni bozulmadan ve mümkünse birden fazla kişiyle yapılır.',
    whyWrong: [
      'Ağzı kapatmak kusmuğun hava yoluna kaçışını hızlandırır.',
      'Bilinçsiz kişi oturtulamaz ve ağızdan bir şey verilemez; izlemekle yetinmek boğulmaya seyirci kalmaktır.',
    ],
    objective: 'Kusan bilinçsiz yaralının yan çevrilmesi gerektiğini bilmek.',
    tags: ['bilinc-bozuklugu', 'kusma', 'hava-yolu'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-551',
    subject: 'ilkyardim',
    topic: 'kalp-acilleri',
    difficulty: 'orta',
    stem: 'Göğsünde kalp krizini düşündüren ağrı başlayan bir sürücünün aracını kullanarak kendi başına hastaneye gitmeye çalışması neden sakıncalıdır?',
    options: [
      'Hastane otoparkında yer bulamayacağı için',
      'Yakıt harcayacağı için',
      'Trafikte ceza yiyebileceği için',
      'Yolda bilinç kaybı gelişirse hem kendisinin hem de trafikteki diğer insanların hayatının tehlikeye gireceği için',
    ],
    answerIndex: 3,
    explanation:
      'Kalp krizinde durum aniden ağırlaşabilir ve bilinç kaybı gelişebilir. Direksiyon başındaki kişi bu durumda ağır bir trafik kazasına yol açabilir. Doğru davranış aracı güvenle durdurmak, hareket etmeden dinlenmek ve 112’den ambulans istemektir.',
    whyWrong: [
      'Otopark, yakıt ve ceza kaygıları hayati riskin yanında önemsizdir.',
      'Ambulans, yol boyunca tıbbi müdahale imkânı da sağladığı için özel araçtan üstündür.',
    ],
    objective: 'Kalp krizi şüphesinde araç kullanılmaması gerektiğini kavramak.',
    tags: ['kalp-acilleri', 'surucu', 'ambulans'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-552',
    subject: 'ilkyardim',
    topic: 'oed',
    difficulty: 'zor',
    stem: 'OED pedleri yapıştırılmadan önce yaralının göğsüyle ilgili nelere dikkat edilir?',
    options: [
      'Göğsün çıplak ve kuru olmasına; ıslaksa hızla kurulanmasına',
      'Göğsün bir battaniyeyle örtülü kalmasına',
      'Pedlerin giysilerin üzerine yapıştırılmasına',
      'Pedlerin ikisinin de aynı noktaya üst üste konmasına',
    ],
    answerIndex: 0,
    explanation:
      'Pedlerin cilde tam temas etmesi gerekir; bu yüzden göğüs açılır, ıslaksa hızla kurulanır ve pedler cihaz üzerindeki şekillere uygun olarak çıplak cilde yapıştırılır. Islak veya giysili yüzey akımın doğru iletilmesini engeller.',
    whyWrong: [
      'Giysi veya örtü üzerine yapıştırılan ped cilde temas edemez.',
      'Pedler cihazın gösterdiği iki ayrı noktaya yapıştırılır; üst üste konmaz.',
    ],
    objective: 'OED pedlerinin kuru ve çıplak cilde yapıştırıldığını bilmek.',
    tags: ['oed', 'ped', 'hazirlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-553',
    subject: 'ilkyardim',
    topic: 'iletisim-destek',
    difficulty: 'kolay',
    stem: 'Bilinci açık bir yaralıya yaklaşan ilk yardımcının doğru tutumu hangisidir?',
    options: [
      'Yaralıyla hiç konuşmadan sessizce müdahale etmek',
      'Yaranın ne kadar kötü göründüğünü ayrıntılarıyla anlatmak',
      'Kendini tanıtmak, sakin bir ses tonuyla ne yapacağını açıklamak ve yaralıyı yalnız bırakmamak',
      'Yaralının sorularını cevapsız bırakmak',
    ],
    answerIndex: 2,
    explanation:
      'Bilinci açık yaralıyla güven ilişkisi kurmak müdahaleyi kolaylaştırır: ilk yardımcı kendini tanıtır, yapacaklarını sakin bir dille anlatır, yaralıyı korkutacak yorumlardan kaçınır ve onu yalnız bırakmaz.',
    whyWrong: [
      'Sessiz kalmak veya soruları yanıtsız bırakmak kaygıyı büyütür.',
      'Yaranın kötülüğünü anlatmak paniği ve şok riskini artırabilir.',
    ],
    objective: 'Yaralıyla güven verici iletişim kurmayı bilmek.',
    tags: ['iletisim-destek', 'sakinlestirme', 'guven'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-554',
    subject: 'ilkyardim',
    topic: 'sok',
    difficulty: 'kolay',
    stem: 'Kaza yerinde yaralının üzerinin battaniye veya montla örtülmesinin ilk yardım açısından amacı nedir?',
    options: [
      'Yaralının kim olduğunun gizlenmesi',
      'Vücut ısısının korunması; ısı kaybının şok tablosunu ağırlaştırabilmesi',
      'Battaniyenin kanamayı kendiliğinden durdurması',
      'Yaralının uyumasının sağlanması',
    ],
    answerIndex: 1,
    explanation:
      'Yaralılar, özellikle kan kaybı olanlar, hızla ısı kaybeder ve üşüme şok tablosunu derinleştirir. Üzerinin örtülmesi vücut ısısını korumaya yardım eder; bu, şok önleminin basit ama önemli bir parçasıdır.',
    whyWrong: [
      'Amaç gizlilik ya da uyku değildir.',
      'Örtünün kanama üzerinde doğrudan durdurucu etkisi yoktur; kanamaya ayrıca müdahale edilir.',
    ],
    objective: 'Isı kaybını önlemenin şok önlemi olduğunu kavramak.',
    tags: ['sok', 'isi-kaybi', 'ortme'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'ilkyardim-555',
    subject: 'ilkyardim',
    topic: 'tasima-teknikleri',
    difficulty: 'orta',
    stem: 'Bilinci açık, omurga yaralanması şüphesi olmayan ancak yürüyemeyen bir yaralı kısa mesafede iki ilk yardımcıyla nasıl taşınabilir?',
    options: [
      'Kollarından ve saçlarından tutularak',
      'Bir kişinin sırtında sürüklenerek',
      'Ayak bileklerinden çekilerek',
      'İki ilk yardımcının el bileklerini kenetleyerek oluşturduğu oturak (altın beşik) üzerinde',
    ],
    answerIndex: 3,
    explanation:
      'Altın beşik yönteminde iki ilk yardımcı el bileklerini birbirine kenetleyerek bir oturak oluşturur; yaralı bu oturağa oturtulur ve kollarını taşıyanların omuzlarına atarak kısa mesafede güvenle taşınır. Yöntem, bilinci açık ve omurga yaralanması şüphesi olmayan yaralılar içindir.',
    whyWrong: [
      'Koldan, saçtan veya bilekten çekmek yaralıya acı verir ve yeni yaralanmalara yol açar.',
      'Sırtta sürüklemek kontrolsüz bir taşıma biçimidir.',
    ],
    objective: 'Altın beşik taşıma yönteminin kullanım koşullarını bilmek.',
    tags: ['tasima-teknikleri', 'altin-besik', 'iki-kisi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
];
