/**
 * ÖZGÜN trafik adabı soruları — 5. genişletme (Program 2 · Faz 9). ROADMAP C.4/E.6.
 * Kaynak = MEB Trafik Adabı müfredatı; KENDİ İFADEMİZLE.
 */
import type { QuestionInput } from '@ea/content-schema';

const SRC = 'MEB Trafik Adabı müfredatı (özgün ifade)';

export const ADAB_QUESTIONS_5: QuestionInput[] = [
  {
    id: 'adab-501',
    subject: 'adab',
    topic: 'trafik-kulturu',
    difficulty: 'orta',
    stem: 'Bir şehrin trafiğine bakarak o toplumun sabır, saygı ve hak anlayışı hakkında fikir edinilebileceği söylenir. Bu görüş trafik adabı açısından ne anlatır?',
    options: [
      'Trafik yalnızca mühendislik ve altyapı sorunudur; kültürle ilgisi yoktur',
      'Trafik, toplum kültürünün aynasıdır; yoldaki davranışlar günlük yaşamdaki değerlerin dışa yansımasıdır',
      'Trafikteki davranışlar yalnızca ceza miktarına göre şekillenir',
      'Kültür yalnızca yayaların davranışını etkiler, sürücüleri etkilemez',
    ],
    answerIndex: 1,
    explanation:
      'Kuyruğa saygı, zayıfı koruma, hakkını ve haddini bilme gibi değerler toplumun genel kültüründe ne kadar güçlüyse trafiğe de o kadar yansır. Yol, bir toplumun karakterinin en görünür sahnelerinden biridir.',
    whyWrong: [
      'Altyapı önemlidir; ancak aynı yolda farklı sürücülerin farklı davranması işin kültür boyutunu gösterir.',
      'Ceza caydırır ama kültür oluşturmaz; kimse görmezken sergilenen davranışı değerler belirler.',
    ],
    objective: 'Trafik kültürü ile toplum kültürü arasındaki ilişkiyi kavramak.',
    tags: ['trafik-kulturu', 'toplum', 'degerler'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-502',
    subject: 'adab',
    topic: 'trafik-kulturu',
    difficulty: 'kolay',
    stem: 'Ülkedeki trafik kültürünün iyileşmesini isteyen bir sürücü işe nereden başlamalıdır?',
    options: [
      'Başkalarını beklemeden kendi davranışlarından; kültür, tek tek bireylerin örnekliğiyle değişir',
      '"Herkes düzelsin, ben de düzelirim" diyerek çoğunluğu beklemekten',
      'Diğer sürücüleri sosyal medyada teşhir etmekten',
      'Yalnızca cezaların artırılmasını talep etmekten',
    ],
    answerIndex: 0,
    explanation:
      'Trafikte nezaket bulaşıcıdır: yol verilen sürücü başkasına yol verir, teşekkür gören teşekkür eder. Değişim, herkesin kontrol edebildiği tek alandan — kendi direksiyonundan — başlar.',
    whyWrong: [
      'Çoğunluğu beklemek, hiç kimsenin başlamadığı bir değişimi beklemektir.',
      'Teşhir ve şikâyet öfke üretir; örnek davranış ise taklit edilir.',
    ],
    objective: 'Trafik kültürünün bireysel örneklikle değiştiğini benimsemek.',
    tags: ['trafik-kulturu', 'orneklik', 'bireysel-sorumluluk'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-503',
    subject: 'adab',
    topic: 'hak-kavrami',
    difficulty: 'orta',
    stem: 'Kavşağa uzanan uzun kuyrukta herkes sırasını beklerken bir sürücü en öne kadar ilerleyip araya sıkışıyor. Bu davranışın "hak" kavramı açısından değerlendirmesi hangisidir?',
    options: [
      'Trafikte hak kavramı aranmaz; boşluğu bulan gider',
      'Kuyrukta beklemek beceriksizliktir; pratik davranan kazanır',
      'Sırada bekleyen herkesin zamanından çalan bir kul hakkı ihlalidir; kazanılan dakikalar başkalarının bekleyişine eklenir',
      'Yalnızca ceza yazılırsa yanlış sayılır',
    ],
    answerIndex: 2,
    explanation:
      'Kuyruk, sınırlı yolun adil paylaşım sözleşmesidir. Öne sıkışan sürücü kimseden para almaz ama herkesten zaman alır; trafikte kul hakkı en çok bu görünmez biçimde yenir.',
    whyWrong: [
      'Boşluk bulmak hak doğurmaz; boşluk, sırasını bekleyenlerin bıraktığı güvenlik payıdır.',
      'Cezasız kalmak davranışı doğru yapmaz; hak ihlali denetimden bağımsızdır.',
    ],
    objective: 'Kuyruk kaçağının kul hakkı boyutunu kavramak.',
    tags: ['hak-kavrami', 'kul-hakki', 'kuyruk'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-504',
    subject: 'adab',
    topic: 'kamu-hakki',
    difficulty: 'kolay',
    stem: 'Bir grup genç, eğlence olsun diye yol kenarındaki trafik levhasını eğip yönünü değiştiriyor. Bu davranış için en doğru değerlendirme hangisidir?',
    options: [
      'Levha nasılsa yenilenir; kalıcı bir zarar yoktur',
      'Yalnızca belediyeye verilen küçük bir maddi zarardır',
      'Yol tenhaysa levhanın önemi de yoktur',
      'Herkesin vergisiyle kurulan güvenlik sistemine, yani kamu hakkına saldırıdır; yanlış yönlendirilen sürücü kazaya sürüklenebilir',
    ],
    answerIndex: 3,
    explanation:
      'Levhalar süs değil, sürücülerin hayati kararlarını dayandırdığı bilgilerdir. Onlara zarar vermek hem toplumun ortak malına hem de o levhaya güvenerek yol alan insanların canına kastetmektir.',
    whyWrong: [
      'Zarar yalnızca maddi değildir; yanlış yön gösteren bir levha ölümcül bir kazanın ilk halkası olabilir.',
      'Tenha yol, levhaya duyulan ihtiyacı azaltmaz; sürücü orayı ilk kez geçiyor olabilir.',
    ],
    objective: 'Trafik donanımına zarar vermenin kamu hakkı ve can güvenliği boyutunu kavramak.',
    tags: ['kamu-hakki', 'levha', 'vandalizm'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-505',
    subject: 'adab',
    topic: 'kural-icsellestirme',
    difficulty: 'orta',
    stem: 'Gece yarısı, çevrede hiçbir araç, yaya ya da denetim kamerası yokken kırmızı ışığa geldiniz. Trafik adabını içselleştirmiş bir sürücü ne yapar?',
    options: [
      'Işık yeşile dönene kadar bekler; kurala uymak, izleyen olup olmamasına bağlı değildir',
      'Etrafı kontrol edip geçer; kural boş kavşak için yazılmamıştır',
      'Ceza riskine göre karar verir; kamera yoksa geçer',
      'Yavaşlayıp durmadan süzülerek geçer',
    ],
    answerIndex: 0,
    explanation:
      'Kuralı içselleştirmek, onu bekçisiz de uygulamaktır. "Boşken geçilir" alışkanlığı, bir gün görülmeyen bir yayanın ya da aracın önünde aynı refleksle tekrarlanır; karakter, kimse bakmıyorken belli olur.',
    whyWrong: [
      'Boş görünen kavşak boş olmayabilir; ışık, sizin göremediklerinizi de hesaba katar.',
      'Cezaya endeksli sürücülük, denetim bitince biten eğreti bir disiplindir.',
    ],
    objective: 'Kurallara denetimden bağımsız, içselleştirerek uymayı benimsemek.',
    tags: ['kural-icsellestirme', 'kirmizi-isik', 'durustluk'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-506',
    subject: 'adab',
    topic: 'kural-icsellestirme',
    difficulty: 'kolay',
    stem: '"Radar yoksa hız sınırı da yok" diyen bir arkadaşınıza trafik adabı açısından verilebilecek en doğru cevap hangisidir?',
    options: [
      '"Haklısın, sınırlar yalnızca ceza yazmak için konur."',
      '"Radar haritası kullanırsan sorun kalmaz."',
      '"Hız sınırı cezayla değil, can güvenliğiyle ilgilidir; kurala denetim için değil, insanların yaşam hakkı için uyulur."',
      '"Gündüz uyman yeterli, gece serbestsin."',
    ],
    answerIndex: 2,
    explanation:
      'Hız sınırları, o yolun geometrisi, çevresi ve insan tepki süresi hesaplanarak belirlenir. Radar sadece hatayı kaydeder; sınırın koruduğu şey ise dosya değil, candır.',
    whyWrong: [
      'Radardan kaçmayı öğrenmek, kuralın amacını hiç anlamamış olmaktır.',
      'Gece görüşün azaldığı saatlerde hız daha da kritik hâle gelir; muafiyet değil dikkat gerektirir.',
    ],
    objective: 'Hız kurallarına ceza korkusuyla değil ilke olarak uymayı kavramak.',
    tags: ['kural-icsellestirme', 'hiz-siniri', 'radar'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-507',
    subject: 'adab',
    topic: 'kural-icsellestirme',
    difficulty: 'orta',
    stem: 'Bir sürücü denetim noktasına yaklaşırken yavaşlıyor, noktayı geçer geçmez yeniden aşırı hıza dönüyor. Bu davranış neyi gösterir?',
    options: [
      'Kuralları çok iyi bildiğini ve akıllıca uyguladığını',
      'Kurala inanmadığını, yalnızca ceza korkusuyla hareket ettiğini; oysa güvenliği sağlayan, kuralın içselleştirilmesidir',
      'Denetim noktalarının gereksiz olduğunu',
      'Deneyimli sürücülüğün doğal bir alışkanlığını',
    ],
    answerIndex: 1,
    explanation:
      'Denetim görünce düzelen davranış, denetim bitince bozulur. Kaza ise radarın olduğu yerde değil, sürücünün kendini serbest hissettiği yerde olur; bu yüzden asıl denetçi vicdandır.',
    whyWrong: [
      'Kuralı bilen ama benimsemeyen sürücü, bilgisini yalnızca cezadan kaçmak için kullanır.',
      'Sorun denetimin varlığı değil, sürücünün kuralla kurduğu pazarlık ilişkisidir.',
    ],
    objective: 'Ceza odaklı uyum ile içselleştirilmiş uyum arasındaki farkı ayırt etmek.',
    tags: ['kural-icsellestirme', 'denetim', 'vicdan'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-508',
    subject: 'adab',
    topic: 'cocuga-ornek-olma',
    difficulty: 'kolay',
    stem: 'Arka koltukta sizi izleyen çocuğunuz varken sarı ışıkta hızlanıp kavşaktan geçiyorsunuz. Bu davranışın uzun vadedeki en önemli sonucu hangisidir?',
    options: [
      'Çocuk kuralları nasılsa okulda öğrenir; etkisi olmaz',
      'Zaman kazandırdığı için çocuğa pratiklik öğretir',
      'Çocuk küçükse fark etmez, unutur',
      'Çocuk kural ihlalini normal görmeye başlar; yarının sürücüsünün trafik anlayışını bugün siz şekillendirirsiniz',
    ],
    answerIndex: 3,
    explanation:
      'Çocuklar trafiği kitaptan değil, ebeveynin direksiyondaki hâlinden öğrenir. Bugün arka koltukta izlenen her ihlal, yıllar sonra başka bir direksiyonda tekrarlanmak üzere kaydedilir.',
    whyWrong: [
      'Okul bilgi verir ama alışkanlığı evdeki örnek kurar; ikisi çelişirse çoğu zaman örnek kazanır.',
      'Çocukların gözlem ve taklit gücü yetişkinlerin sandığından çok daha güçlüdür.',
    ],
    objective: 'Sürücü davranışının çocuklar üzerindeki model etkisini kavramak.',
    tags: ['cocuga-ornek-olma', 'model-davranis', 'aile'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-509',
    subject: 'adab',
    topic: 'cocuga-ornek-olma',
    difficulty: 'orta',
    stem: 'Çocuğunuzla yaya olarak bomboş bir caddede kırmızı yanan yaya ışığına geldiniz. En doğru davranış hangisidir?',
    options: [
      'Yeşili beklemek; çocuğa "kurala araç yokken de uyulur" mesajını sözle değil davranışla vermek',
      'Yol boş olduğu için el ele tutuşup hızla geçmek',
      '"Büyükler bilir, sen tek başınayken bekle" deyip geçmek',
      'Çocuğu kaldırımda bekletip kendiniz geçmek',
    ],
    answerIndex: 0,
    explanation:
      'Çocuk için kural, sizin uyduğunuz şeydir. Boş caddede beklenen bir kırmızı ışık, ileride yalnız başına yol kenarında duran çocuğun hayatını kurtaracak alışkanlığın ilk tuğlasıdır.',
    whyWrong: [
      '"Boşken geçilir" dersini alan çocuk, boşluğu yetişkin gibi değerlendiremez ve yanlış hesap yapar.',
      'Söz ile davranış çeliştiğinde çocuk davranışı öğrenir; "sen yapma ben yapayım" işe yaramaz.',
    ],
    objective: 'Yaya olarak da çocuğa tutarlı kural örnekliği sunmayı benimsemek.',
    tags: ['cocuga-ornek-olma', 'yaya-isigi', 'tutarlilik'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-510',
    subject: 'adab',
    topic: 'acemi-hosgoru',
    difficulty: 'kolay',
    stem: 'Dar bir sokakta önünüzdeki, üzerinde "sürücü adayı" yazan eğitim aracı park manevrasını üçüncü kez deniyor. En uygun davranış hangisidir?',
    options: [
      'Korna çalarak acele etmesini sağlamak',
      'Camı açıp nasıl park edileceğini bağırarak tarif etmek',
      'Sabırla beklemek ya da güvenliyse yavaşça geçmek; her usta sürücünün bir zamanlar aday olduğunu hatırlamak',
      'Aracın burnuna sokularak baskı kurmak',
    ],
    answerIndex: 2,
    explanation:
      'Acemilik bir kusur değil, herkesin geçtiği bir aşamadır. Baskı altındaki aday daha çok hata yapar; birkaç dakikalık sabır, hem manevrayı hem de yeni bir sürücünün öz güvenini korur.',
    whyWrong: [
      'Korna ve baskı, adayın elini ayağına dolaştırır; manevrayı uzatır ve kaza riskini artırır.',
      'Bağırarak tarif etmek yardım değil aşağılamadır; eğitmen zaten araçtadır.',
    ],
    objective: 'Aday ve acemi sürücülere sabır ve hoşgörü göstermeyi benimsemek.',
    tags: ['acemi-hosgoru', 'surucu-adayi', 'sabir'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-511',
    subject: 'adab',
    topic: 'acemi-hosgoru',
    difficulty: 'orta',
    stem: 'Hızlanma şeridinden otoyola katılmaya çalışan "yeni sürücü" yazılı bir araç tereddüt ediyor ve yavaş hızlanıyor. Seyir şeridindeki sürücü olarak ne yaparsınız?',
    options: [
      'Hızınızı koruyup önce siz geçersiniz; katılan araç nasılsa beklemek zorundadır',
      'Mümkünse sol şeride geçerek ya da hızınızı ayarlayarak katılması için güvenli bir boşluk açarsınız',
      'Korna ve selektörle hızlanması için baskı yaparsınız',
      'Yakın takibe girerek onu hızlanmaya zorlarsınız',
    ],
    answerIndex: 1,
    explanation:
      'Katılım, yeni sürücülerin en zorlandığı manevralardandır. Deneyimli sürücünün küçük bir şerit değişikliği veya hafif hız ayarı, acemi için stresli bir anı güvenli bir katılıma çevirir.',
    whyWrong: [
      'Boşluk vermemek, tereddütteki sürücüyü hızlanma şeridinin sonunda durmaya mecbur bırakır; bu, herkes için tehlikelidir.',
      'Baskı acemiyi hızlandırmaz; paniğe itip yanlış karar verdirir.',
    ],
    objective: 'Otoyola katılan acemi sürücüye alan açma nezaketini kavramak.',
    tags: ['acemi-hosgoru', 'otoyol-katilim', 'yardimlasma'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-512',
    subject: 'adab',
    topic: 'yol-verme-dili',
    difficulty: 'orta',
    stem: 'Yan şeritteki sürücü kavşağı yanlış değerlendirdi; son anda sinyal yakıp şeridinize geçmek istiyor ve hatası açık. Trafik adabına uygun "yol verme dili" hangisidir?',
    options: [
      'Hızlanıp boşluğu kapatarak hatasının bedelini ödetmek',
      'Geçmesine izin verip ardından yakın takip ve selektörle rahatsız etmek',
      'Camı açıp hatasını yüksek sesle anlatmak',
      'Hızı hafifçe azaltıp net bir boşluk bırakmak; gerekirse kısa bir el işaretiyle geçebileceğini belli etmek',
    ],
    answerIndex: 3,
    explanation:
      'Hatalı sürücüye yol vermek onun hatasını onaylamak değil, hatanın kazaya dönüşmesini engellemektir. Net bir boşluk ve sakin bir işaret, gerginliği saniyeler içinde çözer.',
    whyWrong: [
      'Boşluğu kapatmak "ders" değil, iki aracı da riske atan bir inatlaşmadır.',
      'Yol verip sonra taciz etmek, yapılan iyiliği misillemeye çevirir; adapta yeri yoktur.',
    ],
    objective: 'Hata yapan sürücüye güvenli ve nazik biçimde yol vermeyi öğrenmek.',
    tags: ['yol-verme-dili', 'hata-toleransi', 'iletisim'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-513',
    subject: 'adab',
    topic: 'ozur-kabulu',
    difficulty: 'kolay',
    stem: 'Sizi ani fren yapmak zorunda bırakan sürücü, elini kaldırarak özür diledi. Olgun bir sürücü bu özrü nasıl karşılar?',
    options: [
      'Kısa bir el işareti ya da baş sallamayla kabul eder; konuyu orada kapatıp sürüşe odaklanır',
      'Özrü yok sayıp aracın yanına yanaşarak tepkisini gösterir',
      'Kabul ettiğini göstermek için uzun uzun korna çalar',
      'Özrü yeterli bulmaz, durup yüz yüze konuşmasını ister',
    ],
    answerIndex: 0,
    explanation:
      'Özür, trafikteki gerginliğin fişini çeker; kabul etmek de en az dilemek kadar olgunluktur. Kısa bir işaretle karşılık vermek, olayı büyümeden kapatır ve iki sürücüyü de yola döndürür.',
    whyWrong: [
      'Özrü görmezden gelip peşine düşmek, bitmiş bir olayı yol öfkesine dönüştürür.',
      'Akan trafikte durup hesap sormak, küçük bir hatayı gerçek bir tehlikeye çevirir.',
    ],
    objective: 'Trafikte özrü kabul edip gerginliği sonlandırma olgunluğunu edinmek.',
    tags: ['ozur-kabulu', 'olgunluk', 'iletisim'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-514',
    subject: 'adab',
    topic: 'korna-sabirsizligi',
    difficulty: 'kolay',
    stem: 'Işık yeşile döndü; bir anlık dalgınlıkla geç kaldınız ve arkanızdaki sürücü uzun uzun korna çalıyor. En doğru davranış hangisidir?',
    options: [
      'İnadına daha da yavaş hareket ederek ders vermek',
      'Camdan el hareketiyle karşılık vermek',
      'Sakin biçimde hareket etmek; gerekirse elinizi kaldırıp dalgınlığınızı kabul etmek ve tartışmaya girmemek',
      'Aracı durdurup inerek sürücüyle yüzleşmek',
    ],
    answerIndex: 2,
    explanation:
      'Karşınızdaki sabırsız davranmış olabilir; ama gecikme de sizden kaynaklandı. Hatanızı küçük bir işaretle üstlenip yola devam etmek, iki kişilik bir gerginliği tek hamlede bitirir.',
    whyWrong: [
      'İnat ve misilleme, kabalığa kabalıkla cevap verip tansiyonu tırmandırır.',
      'Durup inmek, saniyelik bir sürtüşmeyi fiziksel kavga riskine büyütür.',
    ],
    objective: 'Kornalı baskı karşısında misillemesiz, sakin tepki vermeyi öğrenmek.',
    tags: ['korna-sabirsizligi', 'sakinlik', 'yesil-isik'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-515',
    subject: 'adab',
    topic: 'korna-sabirsizligi',
    difficulty: 'orta',
    stem: 'Bazı sürücüler ışık yeşile döner dönmez öndeki araca korna basar. Trafik adabı açısından doğru yaklaşım hangisidir?',
    options: [
      'Korna trafiği hızlandırdığı için bu alışkanlık yararlıdır',
      'Öndeki sürücüye hareket için birkaç saniye tanınmalı; korna ancak gecikme uzarsa kısa ve nazik bir hatırlatma olarak kullanılmalıdır',
      'Yeşilde korna basmak, arkadaki sürücünün görevidir',
      'Korna yerine yakın takiple baskı kurmak daha doğrudur',
    ],
    answerIndex: 1,
    explanation:
      'İnsanın algı ve tepki süresi vardır; yeşil yanar yanmaz çalan korna uyarı değil sabırsızlık ilanıdır. Kornanın adabı, kısalığında ve zamanlamasındadır.',
    whyWrong: [
      'Anında basılan korna öndekini telaşlandırır; telaş, stop etmeye ve daha uzun gecikmeye yol açar.',
      'Yakın takip, sabırsızlığı ses yerine tehlikeyle ifade etmektir; daha da yanlıştır.',
    ],
    objective: 'Işıkta bekleme toleransı ve kornanın ölçülü kullanımını kavramak.',
    tags: ['korna-sabirsizligi', 'tolerans', 'nezaket'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-516',
    subject: 'adab',
    topic: 'yol-calisani-saygisi',
    difficulty: 'orta',
    stem: 'Gece otoyolda, huni ve ışıklarla işaretlenmiş bir yol çalışması bölgesine yaklaşıyorsunuz; işçiler şeride yakın çalışıyor. En doğru davranış hangisidir?',
    options: [
      'Hızınızı korumak; işaretlemeler yalnızca gündüz saatleri içindir',
      'Korna çalarak işçilerin kenara çekilmesini sağlamak',
      'Hunilerin arasından kestirme bir hatla ilerlemek',
      'Hızı belirgin biçimde düşürmek ve mümkünse çalışılan şeritten uzaktaki şeride geçmek; o yol, orada çalışan insanların iş yeridir',
    ],
    answerIndex: 3,
    explanation:
      'Masasında çalışan biri için duvarlar neyse, yol çalışanı için hız ve mesafe bırakan sürücüler odur. Gece görüşün azaldığı saatlerde yavaşlamak ve şerit boşaltmak, o insanların tek korumasıdır.',
    whyWrong: [
      'İşaretlemelerin saati yoktur; çalışma sürdükçe koruma da sürmelidir.',
      'Huniler süs değildir; aralarından geçmek işçilerin güvenlik alanını delmektir.',
    ],
    objective: 'Yol çalışanlarının güvenliği için hız düşürme ve şerit boşaltmayı benimsemek.',
    tags: ['yol-calisani-saygisi', 'gece', 'is-guvenligi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-517',
    subject: 'adab',
    topic: 'yol-calisani-saygisi',
    difficulty: 'kolay',
    stem: 'Trafiği yavaşlatan bir yol çalışmasına denk geldiniz ve "yine mi kazı" diye öfkeleniyorsunuz. Trafik adabına uygun bakış açısı hangisidir?',
    options: [
      'Çalışanların herkesin güvenliği ve konforu için orada olduğunu hatırlamak; düşürülen hız sınırının onların can güvenliği demek olduğunu bilmek',
      'Çalışma bölgesindeki hız sınırını öneri saymak',
      'Öfkeyi işçilere korna çalarak ifade etmek',
      'Zaman kazanmak için şantiye alanının içinden geçmek',
    ],
    answerIndex: 0,
    explanation:
      'Bugün sizi yavaşlatan çalışma, yarın daha güvenli süreceğiniz yolun bedelidir. Baret takan o insanlar sizin için çalışır; onların iş yerinden geçerken gösterilecek özen, en temel saygıdır.',
    whyWrong: [
      'Çalışma bölgesi sınırları öneriye değil, oradaki insanların yaşamına endekslidir.',
      'Kornayla öfke boşaltmak, işini yapan insana haksız bir saldırıdır.',
    ],
    objective: 'Yol çalışmalarına öfke yerine anlayışla yaklaşmayı öğrenmek.',
    tags: ['yol-calisani-saygisi', 'empati', 'hiz-siniri'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-518',
    subject: 'adab',
    topic: 'kaza-yeri-gorgusu',
    difficulty: 'orta',
    stem: 'Bir kaza yerine geldiniz; yeterli sayıda kişi yardım ediyor ve 112 aranmış. Çevrede kalabalık giderek büyüyor. En doğru davranış hangisidir?',
    options: [
      'İnip olayı yakından izlemek; kalabalıkta bir kişi fark etmez',
      'Kalabalığa katılmadan yola devam etmek; yardım yeterliyse en büyük katkı, kaza çevresini ve yolu boş bırakmaktır',
      'Aracı kaza yerinin dibine park edip bilgi almak',
      'Diğer sürücülere olayı anlatmak için yol ortasında durmak',
    ],
    answerIndex: 1,
    explanation:
      'Yardım ile merak arasındaki çizgi nettir: ihtiyaç varsa el uzatılır, yoksa alan açılır. Meraklı kalabalık ambulansın yolunu, görevlinin alanını ve yaralının havasını daraltır.',
    whyWrong: [
      'İzleyici kalabalığı, sağlık ekiplerinin en sık şikâyet ettiği engellerden biridir.',
      'Kaza dibine park eden her araç, müdahale araçlarının duracağı yeri işgal eder.',
    ],
    objective: 'Kaza yerinde yardım ihtiyacı ile meraklı kalabalık ayrımını yapmak.',
    tags: ['kaza-yeri-gorgusu', 'yardim', 'kalabalik'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-519',
    subject: 'adab',
    topic: 'kaza-yeri-gorgusu',
    difficulty: 'zor',
    stem: 'Otoyolda karşı yönde bir kaza olmuş; sizin yönünüz tamamen açık, ancak öndeki araçlar kazayı izlemek için yavaşlıyor. Bu "merak yavaşlaması" için doğru değerlendirme hangisidir?',
    options: [
      'Kazayı görmek doğal bir haktır; yavaşlamanın zararı olmaz',
      'Yalnızca gece saatlerinde sakıncalıdır',
      'Dikkati yoldan koparıp ani frenlere yol açar; açık yönde bile zincirleme kaza ve kilometrelerce gereksiz kuyruk üretir — bakışlar yolda kalmalı, akış korunmalıdır',
      'Trafiği yalnızca kazanın olduğu yönde etkiler',
    ],
    answerIndex: 2,
    explanation:
      'Kaza izlemek için dönen her baş, önündeki aracı saniyelerce görmeyen bir sürücü demektir. İkincil kazaların önemli bir bölümü, kazanın kendisinden değil onu seyredenlerden doğar.',
    whyWrong: [
      'Merak doğaldır ama seyir hâlinde bedeli, öndeki aracın fren lambasını geç görmektir.',
      'Etki tek yönle sınırlı kalmaz; yavaşlama dalgası her iki yönde kilometrelerce yayılır.',
    ],
    objective: 'Kaza seyretme yavaşlamasının ikincil kaza riskini kavramak.',
    tags: ['kaza-yeri-gorgusu', 'ikincil-kaza', 'dikkat'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-520',
    subject: 'adab',
    topic: 'sosyal-medya-gorgusu',
    difficulty: 'kolay',
    stem: 'Bir kaza yerinden geçerken yolcunuz, yaralıların görüntüsünü telefonla çekip paylaşmak istiyor. En doğru tutum hangisidir?',
    options: [
      'Haber değeri taşıdığı için çekmesine yardımcı olmak',
      'Yalnızca araç hasarını çekmesini önermek',
      'İyi kadraj alabilsin diye aracı yavaşlatmak',
      'Engellemek; zor anındaki insanların görüntüsünü yaymak mahremiyet ihlalidir ve kaza çevresinde oyalanmak yardımı geciktirir',
    ],
    answerIndex: 3,
    explanation:
      'Yaralı bir insan, içerik değildir. O görüntü belki bir yakınının telefonuna düşer; kameranın yapamadığını yapan — yol açan, yardım çağıran — sürücü ise gerçek katkıyı verendir.',
    whyWrong: [
      'Haber vermek 112 ile olur; sosyal medyaya görüntü servis etmek habercilik değildir.',
      'Çekim için yavaşlayan araç, arkadaki akışı bozar ve müdahale trafiğini tıkar.',
    ],
    objective: 'Kaza görüntüsü çekip paylaşmanın etik sorunlarını kavramak.',
    tags: ['sosyal-medya-gorgusu', 'mahremiyet', 'kaza'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-521',
    subject: 'adab',
    topic: 'sosyal-medya-gorgusu',
    difficulty: 'orta',
    stem: 'Bir sürücü, seyir hâlindeyken hız göstergesini videoya çekip sosyal medyada paylaşıyor. Bu davranışın en doğru değerlendirmesi hangisidir?',
    options: [
      'Hem sürüş sırasında telefonla uğraşmak hem de yüksek hızı özendirmek, iki ayrı sorumsuzluğun birleşimidir',
      'Takipçilerini bilgilendirdiği için yararlı bir paylaşımdır',
      'Araç güvenli ve yeni olduğu sürece sakıncası yoktur',
      'Yalnızca şehir içinde yapılırsa yanlıştır',
    ],
    answerIndex: 0,
    explanation:
      'Direksiyondayken kamera tutmak dikkat dağınıklığının en tehlikeli biçimlerindendir; paylaşımın kendisi ise hız ihlalini beğeni toplayan bir gösteriye çevirir ve başkalarını da özendirir.',
    whyWrong: [
      'Bilgilendirme değil özendirmedir; izleyen genç sürücüler aynı sahneyi tekrarlamaya heveslenir.',
      'Aracın donanımı, insan tepki süresini ve fizik kurallarını değiştirmez.',
    ],
    objective: 'Sürüş içeriği paylaşma hevesinin risk ve özendirme boyutunu görmek.',
    tags: ['sosyal-medya-gorgusu', 'hiz', 'ozendirme'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-522',
    subject: 'adab',
    topic: 'park-anlasmazligi',
    difficulty: 'orta',
    stem: 'Siz ve başka bir sürücü, aynı boş park yerine aynı anda geldiniz; ikiniz de sinyal veriyorsunuz. Gerginliği büyütmeden çözmenin yolu hangisidir?',
    options: [
      'Hızlı bir manevrayla yeri fiilen kapmak',
      'Araçtan inip yerin size ait olduğunu yüksek sesle savunmak',
      'Camı açıp kısaca anlaşmak ya da yerden feragat edip başka yer aramak; birkaç metrelik asfalt hiçbir kavgaya değmez',
      'Aracınızı yerin ortasına bırakıp bekleyerek karşı tarafı yıldırmak',
    ],
    answerIndex: 2,
    explanation:
      'Park yeri anlaşmazlıklarının haber olmuş sonuçları, konunun ne kadar küçük, tırmanışın ne kadar hızlı olduğunu gösterir. İki saniyelik bir "buyurun" ya da kısa bir uzlaşma, günün geri kalanını kurtarır.',
    whyWrong: [
      'Yeri fiilen kapmak kazanç gibi görünür; ama karşınızda nasıl tepki vereceğini bilmediğiniz bir insan bırakır.',
      'Araçtan inip yüzleşmek, anlaşmazlığı müzakereden meydan okumaya taşır.',
    ],
    objective: 'Park anlaşmazlığını kavgasız, uzlaşmayla çözmeyi öğrenmek.',
    tags: ['park-anlasmazligi', 'uzlasma', 'ofke-kontrolu'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-523',
    subject: 'adab',
    topic: 'park-anlasmazligi',
    difficulty: 'orta',
    stem: 'Aracınıza döndünüz; başka bir araç tam arkanıza park ederek çıkışınızı kapatmış ve sürücüsü ortada yok. En doğru davranış hangisidir?',
    options: [
      'Tamponuyla iterek kendinize çıkış alanı açmak',
      'Çevredeki iş yerlerinden sürücüyü sordurmak, ulaşamazsanız yetkilileri (zabıta veya trafik birimini) aramak; öfkeyle araca zarar vermemek',
      'Aracın camına hakaret içeren bir not bırakıp beklemek',
      'Lastiğinin havasını indirerek sürücüye ders vermek',
    ],
    answerIndex: 1,
    explanation:
      'Karşı taraf açıkça hatalıdır; ama hatalıya verilecek karşılık zarar değil, usuldür. Yetkili çağırmak sorunu sizin adınıza ve hukuk içinde çözer; misilleme ise sizi de hatalılar safına taşır.',
    whyWrong: [
      'Başkasının aracını itmek ya da lastiğini indirmek suçtur; mağdurken fail durumuna düşersiniz.',
      'Hakaret notu sorunu çözmez; döndüğünüzde sizi bekleyen öfkeli bir muhatap yaratır.',
    ],
    objective: 'Park mağduriyetinde misilleme yerine doğru merci yolunu benimsemek.',
    tags: ['park-anlasmazligi', 'yetkili-bildirim', 'sakinlik'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-524',
    subject: 'adab',
    topic: 'deneyim-yanilgisi',
    difficulty: 'orta',
    stem: '"Otuz yıldır kaza yapmadım, emniyet kemerine ihtiyacım yok" diyen deneyimli bir sürücünün bu düşüncesi için en doğru değerlendirme hangisidir?',
    options: [
      'Deneyim, kemerin sağladığı korumanın yerini tutar',
      'Şehir içinde haklıdır, yalnızca şehir dışında yanılır',
      'Kaza yapmayan sürücü zamanla kural muafiyeti kazanır',
      'Yanılgıdır; kaza yalnızca sizin hatanızla olmaz ve fizik kuralları deneyim tanımaz — kemer her yolculukta herkes için gereklidir',
    ],
    answerIndex: 3,
    explanation:
      'Otuz yıllık temiz sicil, karşı yönden gelen bir sürücünün bir saniyelik dalgınlığını engelleyemez. Kemer sizin hatanız için değil, herkesin hatası için takılır; çarpışma anında deneyimin ağırlığı sıfırdır.',
    whyWrong: [
      'Deneyim riski öngörmeyi geliştirir ama çarpışma fiziğini değiştirmez.',
      'Trafikte kıdeme bağlı muafiyet yoktur; kurallar en usta sürücüyü de aynı ölçüde bağlar.',
    ],
    objective: 'Deneyimin koruyucu ekipmanın yerini tutmadığını kavramak.',
    tags: ['deneyim-yanilgisi', 'emniyet-kemeri', 'risk-algisi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-525',
    subject: 'adab',
    topic: 'deneyim-yanilgisi',
    difficulty: 'zor',
    stem: 'Deneyimli bazı sürücüler küçük ihlalleri (sinyalsiz dönüş, hafif hız aşımı) zamanla "artık ustayım" diyerek normalleştirir. Bu sürecin asıl tehlikesi nedir?',
    options: [
      'Her sorunsuz atlatılan ihlal risk algısını biraz daha köreltir; sürücü farkında olmadan güvenlik payını tüketir ve tek bir aksilikte bedel ağır olur',
      'Cezaların birikip belgeye işlenmesi',
      'Yakıt tüketiminin ölçülebilir biçimde artması',
      'Aracın mekanik olarak daha hızlı yıpranması',
    ],
    answerIndex: 0,
    explanation:
      'İhlal ceza görmeyince beyin onu "güvenli" diye kodlar; sınır her seferinde biraz daha itilir. Kaza istatistiklerinde deneyimli sürücülerin de yer almasının nedeni beceri eksikliği değil, aşınmış risk algısıdır.',
    whyWrong: [
      'Ceza puanı görünür bir bedeldir; asıl tehlike görünmeyen algı aşınmasıdır.',
      'Yakıt ve yıpranma teknik ayrıntılardır; söz konusu olan, güvenlik marjının sessizce erimesidir.',
    ],
    objective: 'Kural esnetmenin risk algısını aşındıran birikimli etkisini kavramak.',
    tags: ['deneyim-yanilgisi', 'risk-normallesme', 'kural-esnetme'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-526',
    subject: 'adab',
    topic: 'direksiyon-devri',
    difficulty: 'kolay',
    stem: 'Uzun yolculukta yorulduğunuzu hissediyorsunuz; yanınızdaki arkadaşınız dinlenmiş ve ehliyetli, direksiyonu devralmayı öneriyor. En doğru davranış hangisidir?',
    options: [
      '"Ben başladım, ben bitiririm" diyerek devam etmek',
      'Teklifi kabul edip ilk uygun ve güvenli yerde direksiyonu devretmek; yorgunluğu kabullenmek zayıflık değil olgunluktur',
      'Camı açıp müziği yükselterek yola devam etmek',
      'Hızlanarak yolu erken bitirmeye çalışmak',
    ],
    answerIndex: 1,
    explanation:
      'Yorgunluk, alkol gibi tepki süresini uzatır ve inkârla düzelmez. Direksiyonu devretmek gurur meselesi değil, araçtaki herkesin canına duyulan saygının gereğidir.',
    whyWrong: [
      'İnat, yorgunluğun kararları ne kadar bozduğunun ilk kanıtıdır.',
      'Cam ve müzik uyanıklığı birkaç dakika taklit eder; hızlanmak ise yorgun refleksle daha çok riski birleştirir.',
    ],
    objective: 'Yorgunlukta direksiyonu devretme olgunluğunu benimsemek.',
    tags: ['direksiyon-devri', 'yorgunluk', 'olgunluk'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-527',
    subject: 'adab',
    topic: 'direksiyon-devri',
    difficulty: 'orta',
    stem: 'Yolcusu olduğunuz araçta sürücü sık sık esniyor ve aracı şerit çizgisine doğru sürüklüyor. Ne yapmalısınız?',
    options: [
      'Uyumasın diye radyoyu sonuna kadar açmak',
      'Karışmamak; sürücü kendi durumunu herkesten iyi bilir',
      'Durumu nazikçe dile getirip ilk uygun yerde mola vermeyi, mümkünse direksiyonu devralmayı önermek',
      'Konuyu varış noktasına ulaşınca açmak',
    ],
    answerIndex: 2,
    explanation:
      'Yorgun sürücü kendi durumunun en kötü hakemidir; dışarıdan bakan yolcu belirtileri ondan önce görür. Nazik ama net bir öneri, araçtaki herkesin hayatını koruyan bir müdahaledir.',
    whyWrong: [
      'Gürültü uyanıklık yaratmaz; mikro uykuların gelişini yalnızca geciktirir.',
      'Sonra konuşmak, sorunla varış arasında kaza ihtimalini görmezden gelmektir.',
    ],
    objective: 'Yolcu olarak yorgun sürücüye zamanında ve yapıcı müdahale etmeyi öğrenmek.',
    tags: ['direksiyon-devri', 'yolcu-sorumlulugu', 'uyku'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-528',
    subject: 'adab',
    topic: 'mola-kulturu',
    difficulty: 'kolay',
    stem: 'Uzun yolda yaklaşık iki saatte bir mola vermeyi "zaman kaybı" olarak gören bir sürücüye en doğru cevap hangisidir?',
    options: [
      'Haklıdır; mola yalnızca yakıt almak için verilir',
      'Molayı yalnızca yolcular ister; sürücünün ihtiyacı olmaz',
      'Gece yolculuklarında serin hava sayesinde mola gerekmez',
      'Kısa molalar dikkati tazeler; kaybedilen dakikalar, yorgun kafayla yapılacak tek bir hatanın bedeliyle kıyaslanamaz',
    ],
    answerIndex: 3,
    explanation:
      'Dikkat, kesintisiz sürüşte sessizce tükenen bir kaynaktır. On beş dakikalık mola bir yatırımdır: yolculuğa eklediği süre bellidir, önlediği hatanın bedeli ise ölçülemez.',
    whyWrong: [
      'Mola aracın değil, sürücünün bakımıdır; depo dolu olsa da dikkat boşalır.',
      'Gece yorgunluğu artırır, azaltmaz; mola ihtiyacı gece daha da büyür.',
    ],
    objective: 'Uzun yolda düzenli mola vermeyi bir kültür olarak benimsemek.',
    tags: ['mola-kulturu', 'dikkat', 'uzun-yol'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-529',
    subject: 'adab',
    topic: 'mola-kulturu',
    difficulty: 'kolay',
    stem: 'Tatil yolculuğunda arka koltuktaki çocuklar sıkıldı ve mola istiyor; siz ise "durmadan gidersek erken varırız" diye düşünüyorsunuz. Trafik adabına uygun yaklaşım hangisidir?',
    options: [
      'Yolculuğu yalnız kendi hedefinize göre değil, araçtaki herkesin ihtiyacına göre planlamak ve uygun tesiste mola vermek',
      'Çocukları oyalayıp yola kesintisiz devam etmek',
      'Kaybedilecek süreyi hızlanarak telafi etmek',
      'Molayı yalnızca yakıt bittiğinde vermek',
    ],
    answerIndex: 0,
    explanation:
      'Empati araç içinde başlar: sıkılan, acıkan, tuvaleti gelen yolcu bir yük değil, yolculuğun ortağıdır. Üstelik huzursuz yolcular sürücünün dikkatini de dağıtır; mola herkes için kazançtır.',
    whyWrong: [
      'Oyalamak ihtiyacı ertelemez; araç içi gerginlik dikkat dağınıklığına dönüşür.',
      'Hızlanarak telafi, mola tartışmasını hız riskine çevirir; iki yanlış üst üste biner.',
    ],
    objective: 'Yolculuk planında yolcuların ihtiyaçlarını gözetmeyi öğrenmek.',
    tags: ['mola-kulturu', 'empati', 'aile'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-530',
    subject: 'adab',
    topic: 'cevre-gorgusu',
    difficulty: 'kolay',
    stem: 'Uzun bir yolculuğa çıkmadan önce çevre görgüsü açısından en yararlı küçük hazırlık hangisidir?',
    options: [
      'Camdan atılacak atıkları küçük parçalara ayırmak',
      'Araca küçük bir atık torbası koymak; biriken çöpü molalarda geri dönüşüm veya çöp kutusuna boşaltmak',
      'Atıkları poşetleyip mola yerindeki masada bırakmak',
      'Yol kenarları zaten temizleniyor diye önlem almamak',
    ],
    answerIndex: 1,
    explanation:
      'Çevre duyarlılığı büyük sözlerden değil küçük alışkanlıklardan doğar. Torpido gözüne sığan bir torba, kilometrelerce yolun ve mola yerlerinin temiz kalmasının en basit güvencesidir.',
    whyWrong: [
      'Atığın küçüğü de atıktır; parçalamak kirliliği gizler, ortadan kaldırmaz.',
      'Masada bırakılan poşet, çöpü yalnızca bir sonraki misafirin önüne taşır.',
    ],
    objective: 'Araçta atık torbası bulundurma alışkanlığını kazanmak.',
    tags: ['cevre-gorgusu', 'atik-torbasi', 'aliskanlik'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-531',
    subject: 'adab',
    topic: 'istasyon-gorgusu',
    difficulty: 'kolay',
    stem: 'Akaryakıt istasyonunda pompalar dolu ve araçlar sıraya girmiş. Yan taraftan yaklaşıp boşalan ilk pompaya sıradakilerin önünden girmek isteyen sürücü için doğru değerlendirme hangisidir?',
    options: [
      'İstasyonda sıra kuralı olmaz; çevik davranan alır',
      'Deposu daha boş olan sürücünün önceliği vardır',
      'Bekleyenlerin sırasına saygısızlıktır; trafikteki sıra ve hak anlayışı istasyonun içinde de geçerlidir',
      'Görevliler ses çıkarmıyorsa sakıncası yoktur',
    ],
    answerIndex: 2,
    explanation:
      'Trafik adabı yol bitince bitmez; otopark, gişe ve istasyon da aynı hak anlayışının sahnesidir. Sıraya girmek, bekleyen herkesin zamanına verilen sessiz bir sözdür.',
    whyWrong: [
      'Çeviklik hak doğurmaz; öne geçilen her araçta bir insanın bekleyişi uzar.',
      'Görevlinin sessiz kalması davranışı meşrulaştırmaz; adap denetimle değil vicdanla işler.',
    ],
    objective: 'İstasyon ve benzeri ortak alanlarda sıra hakkına saygıyı benimsemek.',
    tags: ['istasyon-gorgusu', 'sira-hakki', 'nezaket'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-532',
    subject: 'adab',
    topic: 'otopark-iletisimi',
    difficulty: 'kolay',
    stem: 'Otoparktan çıkmak üzeresiniz ve bir sürücünün yeriniz için sinyal verip beklediğini görüyorsunuz. Görgülü davranış hangisidir?',
    options: [
      'Telefon işlerinizi bitirene kadar araçta oyalanmak',
      'Yerin kıymetini bilsin diye bilerek yavaş davranmak',
      'Bekleyeni görmezden gelip dilediğiniz kadar kalmak',
      'Sinyalinizle çıkacağınızı belli etmek ve makul bir sürede, güvenli biçimde yeri boşaltmak',
    ],
    answerIndex: 3,
    explanation:
      'Bekleyen sürücünün en büyük ihtiyacı bilgidir: çıkacak mısınız, kalacak mısınız? Kısa bir sinyal bu belirsizliği bitirir; acele etmeden ama oyalanmadan çıkmak da bekleyişe duyulan saygıdır.',
    whyWrong: [
      'Araçta oyalanmak, bekleyenin dakikalarını sizin rahatınıza harcamaktır.',
      'Kasıtlı yavaşlık, hiçbir kazanç sağlamayan sessiz bir kabalıktır.',
    ],
    objective: 'Otoparkta bekleyen sürücüyle işaretle iletişim kurma görgüsünü edinmek.',
    tags: ['otopark-iletisimi', 'sinyal', 'nezaket'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-533',
    subject: 'adab',
    topic: 'otopark-iletisimi',
    difficulty: 'orta',
    stem: 'Dar bir otoparkta önünüzdeki araç geri geri çıkmaya çalışıyor; siz de o yönden geçmek istiyorsunuz. En doğru davranış hangisidir?',
    options: [
      'Güvenli mesafede durup manevrasını tamamlaması için alan bırakmak; gerekirse kısa bir işaretle beklediğinizi belli etmek',
      'Korna çalarak manevrayı hızlandırmak',
      'Kalan dar boşluktan süratle sıyrılıp geçmek',
      'Aracın hemen arkasına yanaşıp beklemek',
    ],
    answerIndex: 0,
    explanation:
      'Geri manevra, görüşün en kısıtlı olduğu andır; manevradaki sürücünün ihtiyacı baskı değil alandır. Beklediğinizi belli eden kısa bir işaret, iki tarafın da niyetini netleştirir.',
    whyWrong: [
      'Korna manevra yapanı teslim olmaya değil panik yapmaya iter.',
      'Dar boşluktan sıyrılmak, o anda sizi göremeyen bir aracın rotasına girmektir.',
    ],
    objective: 'Manevra yapan araca alan bırakıp niyet bildirme görgüsünü kazanmak.',
    tags: ['otopark-iletisimi', 'geri-manevra', 'sabir'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-534',
    subject: 'adab',
    topic: 'goz-temasi',
    difficulty: 'orta',
    stem: 'Işıksız bir kavşağa, kesişen yoldan gelen başka bir araçla hemen hemen aynı anda yaklaştınız. Göz teması bu durumda ne işe yarar?',
    options: [
      'Karşı sürücüye psikolojik üstünlük kurmaya',
      'Kimin daha kararlı olduğunu test etmeye',
      'Birbirinizi gördüğünüzü ve niyetlerinizi teyit etmeye; göz teması kurulamıyorsa görülmediğinizi varsayıp temkinli davranmanız gerekir',
      'Trafik kurallarını geçersiz kılıp yeni bir öncelik belirlemeye',
    ],
    answerIndex: 2,
    explanation:
      'Kurallar önceliği belirler; göz teması ise karşı tarafın o kuralı sizinle aynı anda, aynı biçimde okuduğunu doğrular. Teyit yoksa varsayım da yok: görülmediğinizi kabul edip hazırlıklı olursunuz.',
    whyWrong: [
      'Bakışma bir güç gösterisi değil, iki sürücü arasındaki en hızlı bilgi alışverişidir.',
      'Göz teması kuralın yerine geçmez; kuralın iki tarafça da anlaşıldığını gösterir.',
    ],
    objective: 'Kavşakta göz temasını görülme teyidi olarak kullanmayı öğrenmek.',
    tags: ['goz-temasi', 'kavsak', 'iletisim'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-535',
    subject: 'adab',
    topic: 'goz-temasi',
    difficulty: 'zor',
    stem: 'Yan yoldan ana yola çıkacaksınız; yaklaşan motosikletlinin sizi fark edip etmediğini anlayamıyorsunuz — göz teması yok, hızı da değişmiyor. En doğru davranış hangisidir?',
    options: [
      'Nasılsa o yavaşlar diyerek yola çıkmak',
      'Görülmediğinizi varsayıp motosikletli geçene kadar beklemek; teyit edilmemiş bir varsayımla asla yola çıkmamak',
      'Korna çalarak varlığınızı duyurup çıkmak',
      'Hızla çıkıp gaza basarak riskli süreyi kısaltmak',
    ],
    answerIndex: 1,
    explanation:
      '"Beni gördü" duygusu, kanıt olmadıkça bir tahminden ibarettir; motosikletli sizi görmemişse fren şansı da yok demektir. Kanıt yoksa öncelik onundur: birkaç saniyelik bekleyiş, tahminle can arasındaki farktır.',
    whyWrong: [
      'Karşı tarafın yavaşlayacağı varsayımı, kazaların tutanaklarındaki en sık cümlelerdendir.',
      'Korna duyulmayabilir, hızla çıkmak ise tepki süresini iki taraf için de sıfırlar.',
    ],
    objective: 'Görülme teyidi olmadan yola çıkmama ilkesini içselleştirmek.',
    tags: ['goz-temasi', 'motosiklet', 'varsayim-riski'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-536',
    subject: 'adab',
    topic: 'selektor-dili',
    difficulty: 'zor',
    stem: 'Dar köprü öncesinde karşıdan gelen araç size selektör yaptı. Bu işaretle ilgili en doğru değerlendirme hangisidir?',
    options: [
      'Selektör her yerde "sen geç" demektir; beklemeden geçilir',
      'Selektör her yerde "yol benim, sen geçme" demektir; kesin olarak durulur',
      'Gündüz yapılan selektörün anlamı yoktur',
      'Selektörün anlamı kişiden kişiye ve bölgeden bölgeye değişebilir; işarete körü körüne güvenmek yerine karşı aracın gerçekten yavaşlayıp beklediğini görerek hareket etmek gerekir',
    ],
    answerIndex: 3,
    explanation:
      'Selektör resmî bir işaret değildir: kimi sürücü "buyurun geçin", kimi "ben geliyorum, çekil" anlamında kullanır. Bu belirsizlik yüzünden güvenilecek olan ışık değil, karşı aracın gözle görülür davranışıdır.',
    whyWrong: [
      'İki zıt anlamı olan bir işarete tek anlam yüklemek, dar geçitte kafa kafaya kalmanın reçetesidir.',
      'Sorun görünürlük değil anlam belirsizliğidir; gündüz de gece de aynı risk geçerlidir.',
    ],
    objective: 'Selektörün resmî olmayan ve bölgesel değişen anlamındaki riski kavramak.',
    tags: ['selektor-dili', 'belirsizlik', 'dar-gecit'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-537',
    subject: 'adab',
    topic: 'selektor-dili',
    difficulty: 'orta',
    stem: 'Yan yoldan çıkmak için bekleyen araca yol vermek istiyor, selektör yapmayı düşünüyorsunuz. Bu iletişimin riski nedir ve en güvenli yöntem hangisidir?',
    options: [
      'Karşı sürücü işareti görünce diğer şeritleri kontrol etmeden aniden çıkabilir; en net dil, hızınızı belirgin biçimde azaltıp güvenli bir boşluk bırakmaktır',
      'Selektör risksizdir; ışıkla verilen davet evrensel bir dildir',
      'Korna çalmak daha güvenli bir davettir',
      'Uzun farı sürekli yakık tutmak niyetinizi en iyi anlatan yöntemdir',
    ],
    answerIndex: 0,
    explanation:
      'Sizin "geç" işaretiniz yalnızca kendi şeridiniz adına verilmiş bir sözdür; yan şeritten gelen aracı susturamaz. Davet eden sürücü, davet ettiği kişinin göremediklerinden de kısmen sorumludur — bu yüzden en dürüst işaret, davranışın kendisidir: yavaşlamak ve yer açmak.',
    whyWrong: [
      'Işıklı davet, karşı tarafın kontrol sorumluluğunu unutturabilir; işaret kazaya aracılık edebilir.',
      'Korna ve sürekli uzun far, davet değil karışıklık ve rahatsızlık üretir.',
    ],
    objective: 'Yol verirken işaret yerine net davranışla iletişim kurmayı öğrenmek.',
    tags: ['selektor-dili', 'yol-verme', 'sorumluluk'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-538',
    subject: 'adab',
    topic: 'engelli-hakki',
    difficulty: 'kolay',
    stem: 'Yoğun trafikte, üzerinde engelli işareti bulunan bir araç yan yoldan akışa katılmaya çalışıyor ve uzun süredir bekliyor. En uygun davranış hangisidir?',
    options: [
      '"Herkes sırayla, işaretin trafikte ayrıcalığı olmaz" diyerek geçip gitmek',
      'Hızınızı azaltıp yol vermek; trafikte güçlük yaşayabilecek sürücülere alan açmak dayanışmanın gereğidir',
      'Korna çalarak beklemeye devam etmesini işaret etmek',
      'Yol verip ardından yakın takiple hızlanmaya zorlamak',
    ],
    answerIndex: 1,
    explanation:
      'Engelli sürücü için yoğun akışa katılmak, ek çaba ve dikkat gerektiren bir manevra olabilir. Birkaç saniyelik bir yol veriş, trafiğin herkes için eşit yaşanabilir olmasına yapılmış küçük ama gerçek bir katkıdır.',
    whyWrong: [
      'Eşitlik herkese aynı davranmak değil, ihtiyacı olana alan açmaktır.',
      'Yol verip sonra baskılamak, gösterilen nezaketi geri almak demektir.',
    ],
    objective: 'Engelli sürücülere yol vererek dayanışma göstermeyi benimsemek.',
    tags: ['engelli-hakki', 'yol-verme', 'dayanisma'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-539',
    subject: 'adab',
    topic: 'engelli-farkindaligi',
    difficulty: 'orta',
    stem: 'Önünüzdeki araçta işitme engelli sürücü işareti var; dar yolda geçiş niyetinizi kornanın duyuramayacağını fark ettiniz. En doğru davranış hangisidir?',
    options: [
      'Kornaya daha uzun ve güçlü basmak',
      'Yakın takibe girerek varlığınızı hissettirmek',
      'Sabırlı olmak, takip mesafesini korumak ve gerekiyorsa görüş alanına girerek ya da uygun anda farla nazikçe işaret ederek görsel iletişim kurmak',
      'Camı açıp bağırarak uyarmak',
    ],
    answerIndex: 2,
    explanation:
      'İletişim, karşı tarafın alabileceği kanaldan kurulur: işitme engelli sürücü için bu kanal görseldir. Aynalarına gireceğiniz konum ve ölçülü bir ışık işareti, kornanın yapamadığını güvenle yapar.',
    whyWrong: [
      'Duyulmayan kornayı büyütmek çözüm değildir; yalnızca çevreyi rahatsız eder.',
      'Yakın takip, işitme engelli sürücünün en geç fark edeceği ve en tehlikeli baskı biçimidir.',
    ],
    objective: 'İşitme engelli sürücüyle görsel kanaldan iletişim kurmayı öğrenmek.',
    tags: ['engelli-farkindaligi', 'gorsel-iletisim', 'sabir'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-540',
    subject: 'adab',
    topic: 'toplu-tasima-seridi',
    difficulty: 'orta',
    stem: 'Yoğun saatte otobüslere ayrılmış şerit boş görünüyor; oradan ilerlerseniz epey zaman kazanacaksınız. Bu ihlalin etik boyutu hangisidir?',
    options: [
      'Boş duran şeridi kullanmak kaynak israfını önler',
      'Otobüs görününce çıkmak koşuluyla kullanılabilir',
      'Kamera yoksa etik bir sorun da yoktur',
      'O şerit, tek araçla yüzlerce yolcu taşıyan toplu taşımanın hızı için ayrılmıştır; işgali, otobüsteki onlarca insanın zamanını tek kişinin konforuna feda eder',
    ],
    answerIndex: 3,
    explanation:
      'Otobüs şeridinin boşluğu, sistemin çalıştığının kanıtıdır: otobüs geldiğinde önü açık olsun diye boştur. Şeride giren her otomobil, arkasındaki dolu otobüsü ve içindeki kalabalığı kendi hızına mahkûm eder.',
    whyWrong: [
      '"Boş duruyor" bakışı, şeridin amacının sürekli doluluk değil anlık geçiş hızı olduğunu gözden kaçırır.',
      'Kamerasız ihlal yine ihlaldir; etik, yakalanma ihtimaliyle ölçülmez.',
    ],
    objective: 'Toplu taşıma şeridinin toplumsal işlevini ve ihlalin etiğini kavramak.',
    tags: ['toplu-tasima-seridi', 'kamu-yarari', 'etik'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-541',
    subject: 'adab',
    topic: 'dugun-konvoyu',
    difficulty: 'kolay',
    stem: 'İçinde bulunduğunuz düğün konvoyunda bazı sürücüler yolu kapatıp yavaş gitmeyi ve pencerelerden sarkmayı teklif ediyor. Ne yaparsınız?',
    options: [
      'Teklifi reddedip kurallara uygun ilerlersiniz; kutlama coşkusu başkalarının yolunu ve güvenliğini rehin alamaz',
      'Konvoyun bir parçası olarak gruba uyarsınız',
      'Yolu yalnızca kısa süreliğine kapatmayı önerirsiniz',
      'Taşkınlığa katılmaz ama konvoyu korumak için arkadan yolu siz kapatırsınız',
    ],
    answerIndex: 0,
    explanation:
      'O yolda düğüne değil hastaneye, işe, uçağa yetişmeye çalışan insanlar da vardır. Gerçek kutlama kimseyi mağdur etmeden yapılandır; grup baskısına verilecek en olgun cevap, kibarca hayır demektir.',
    whyWrong: [
      'Gruba uymak sorumluluğu ortadan kaldırmaz; direksiyondaki herkes kendi aracından sorumludur.',
      '"Kısa süre" kapatma da kapatmadır; arkada bekleyen bir ambulans için sürenin kısası yoktur.',
    ],
    objective: 'Konvoy coşkusunda grup baskısına karşı sorumlu davranmayı öğrenmek.',
    tags: ['dugun-konvoyu', 'grup-baskisi', 'sorumluluk'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-542',
    subject: 'adab',
    topic: 'dugun-konvoyu',
    difficulty: 'kolay',
    stem: 'Şehir içinde yolu yavaşlatan, ani duruşlar yapan taşkın bir düğün konvoyuyla karşılaştınız. En doğru davranış hangisidir?',
    options: [
      'Konvoy araçlarının arasına girip hızlarını düzenlemek',
      'Mesafeyi koruyup etkileşime girmemek; güvenli bir fırsatta uzaklaşmak, tehlikeli taşkınlık sürüyorsa yetkililere bildirmek',
      'Korna çalarak konvoyu protesto etmek',
      'Konvoy araçlarını sıkıştırarak kendinize yol açmak',
    ],
    answerIndex: 1,
    explanation:
      'Öngörülemez hareket eden araç grubuna karşı en güçlü koruma mesafedir. Düzeni sağlamak sizin değil yetkililerin işidir; sizin işiniz, kendinizi ve yolcularınızı o karmaşanın dışında tutmaktır.',
    whyWrong: [
      'Konvoyun arasına girmek, ani duran ve savrulan araçların tam ortasında kalmaktır.',
      'Korna ve sıkıştırma, coşkusu taşmış bir grupla gerginlik başlatmanın en kısa yoludur.',
    ],
    objective: 'Taşkın konvoy karşısında mesafe ve bildirme stratejisini benimsemek.',
    tags: ['dugun-konvoyu', 'mesafe', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-543',
    subject: 'adab',
    topic: 'emniyet-seridi-etigi',
    difficulty: 'orta',
    stem: 'Trafiğin durduğu otoyolda bazı araçlar emniyet şeridinden ilerliyor. Bu ihlalin bir ambulans için gerçek maliyeti nedir?',
    options: [
      'Maliyeti yoktur; ambulanslar nasılsa siren kullanır',
      'Yalnızca ihlal eden araçların ceza riski vardır',
      'Acil durumda ambulansın kullanacağı tek açık yol dolmuş olur; ihlalcilerin geri çekilmeye çalıştığı her saniye, hastaneye yetişmesi gereken bir hayattan eksilir',
      'Yalnızca çekici ve yol bakım araçlarının işini zorlaştırır',
    ],
    answerIndex: 2,
    explanation:
      'Emniyet şeridi, trafik kilitlendiğinde acil araçların son koridorudur. Şeridi dolduran araçlar sirene yol vermek istese bile gidecek yerleri yoktur; kazanılan birkaç yüz metre, bir başkasının altın dakikalarından çalınmıştır.',
    whyWrong: [
      'Siren yol açmaz, yol ister; isteyeceği yer işgal edilmişse siren çaresizdir.',
      'Cezaya indirgenen bakış, işin ucundaki hastayı görmezden gelir.',
    ],
    objective: 'Emniyet şeridi ihlalinin acil yardım süresine maliyetini kavramak.',
    tags: ['emniyet-seridi-etigi', 'ambulans', 'kamu-hakki'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-544',
    subject: 'adab',
    topic: 'kis-lastigi-sorumlulugu',
    difficulty: 'orta',
    stem: 'Bir sürücü "kış lastiği pahalı; kayarsam kendi riskim" diyor. Bu düşüncenin trafik adabı açısından eksiği nedir?',
    options: [
      'Eksiği yoktur; herkes kendi aracından sorumludur',
      'Kış lastiği yalnızca kar yağarken fark yaratır, gerisi abartıdır',
      'Zincir bulundurmak kış lastiğinin yerini her koşulda tutar',
      'Kayan araç yalnız sahibini değil çevresindeki araçları, yayaları ve arkasında kapanan yolu da riske atar; kışa hazırlık, başkalarının canına duyulan saygının parçasıdır',
    ],
    answerIndex: 3,
    explanation:
      'Trafikte "kendi riskim" diye bir şey neredeyse yoktur: kontrolden çıkan araç kiminle karşılaşırsa riski ona da devreder. Donanım eksiği kişisel bir tasarruf değil, topluma yansıyan bir sorumluluk açığıdır.',
    whyWrong: [
      'Kayan aracın çarptığı yaya, sürücünün "kendi riski" hesabında yoktu; sorun tam da budur.',
      'Kış lastiği soğuk asfaltta da fark yaratır; kar beklemek hazırlığı geciktirmektir.',
    ],
    objective: 'Kış hazırlığının başkalarına karşı sorumluluk boyutunu kavramak.',
    tags: ['kis-lastigi-sorumlulugu', 'toplumsal-risk', 'hazirlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-545',
    subject: 'adab',
    topic: 'kis-lastigi-sorumlulugu',
    difficulty: 'zor',
    stem: 'Karlı bir sabah yaz lastikleriyle yola çıkan sürücü "nasılsa yavaş giderim" diye düşünüyor. Bu hesabın zayıf noktası nedir?',
    options: [
      'Yavaş gitmek yakıt tüketimini artırır',
      'Yaz lastiği soğukta sertleşip tutunmasını büyük ölçüde kaybeder; düşük hızda bile araç duramayabilir, rampada kalıp yolu herkese kapatabilir — sorun hız değil, tutunmadır',
      'Yavaş giden araca cezai işlem uygulanır',
      'Kar yağışında lastiğin önemi kalmaz; belirleyici olan sürücü becerisidir',
    ],
    answerIndex: 1,
    explanation:
      'Hız, tutunma sorununu küçültür ama yok etmez: tutunmayan lastik 20 kilometre hızda da kayar, hafif rampada da patinaja düşer. Yolda kalan tek bir araç, arkasındaki yüzlerce aracı ve yolun açılmasını bekleyen ekipleri de cezalandırır.',
    whyWrong: [
      'Mesele ekonomi değil fizik ve sorumluluktur; sertleşen kauçuk yavaşlıkla yumuşamaz.',
      'Beceri, tutunmayan lastiğe yol tutturamaz; kabiliyet fizik kurallarını esnetmez.',
    ],
    objective: '"Yavaş giderim" yanılgısının fiziksel ve toplumsal bedelini kavramak.',
    tags: ['kis-lastigi-sorumlulugu', 'tutunma', 'yanilgi'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-546',
    subject: 'adab',
    topic: 'kural-adap-farki',
    difficulty: 'kolay',
    stem: 'Aşağıdakilerden hangisi yazılı bir trafik kuralı değil, trafik adabı (görgü) örneğidir?',
    options: [
      'Kırmızı ışıkta durmak',
      'Emniyet kemeri takmak',
      'Yol veren sürücüye el işaretiyle teşekkür etmek',
      'Hız sınırına uymak',
    ],
    answerIndex: 2,
    explanation:
      'Kurallar mevzuatta yazar ve yaptırımı vardır; adap ise kimsenin ceza yazmadığı ama trafiği insani kılan davranışlardır. Teşekkür etmemek suç değildir — etmek ise trafiği herkes için güzelleştirir.',
    whyWrong: [
      'Işık, kemer ve hız sınırı mevzuatla düzenlenmiş, denetlenen yükümlülüklerdir.',
      'Adap, kuralın bittiği yerde başlar; ikisini ayırt etmek trafiği iki katmanıyla anlamaktır.',
    ],
    objective: 'Yazılı kural ile trafik adabı arasındaki farkı ayırt etmek.',
    tags: ['kural-adap-farki', 'gorgu', 'tesekkur'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-547',
    subject: 'adab',
    topic: 'gecis-ustunlugu',
    difficulty: 'zor',
    stem: 'Sağa yanaşarak yol verdiğiniz ambulans geçti; hemen şeridinize dönmek üzeresiniz. Bu anda gözden kaçırılmaması gereken en önemli olasılık hangisidir?',
    options: [
      'Ambulansın geri dönüp aynı yoldan tekrar geçmesi',
      'Yol verdiğiniz için arkanızdaki trafiğin size kızması',
      'Yol vermenin cezai işlem gerektirmesi',
      'İlk acil aracın arkasından ikinci bir acil aracın (eskort, itfaiye, polis) geliyor olabileceği; aynalar kontrol edilmeden akışa dönülmemelidir',
    ],
    answerIndex: 3,
    explanation:
      'Acil araçlar çoğu olayda tek başına gitmez: ambulansı bir başka ambulans, itfaiye ya da eskort izleyebilir. İlk siren geçince rahatlayıp aniden şeride dönen sürücü, ikinci sirenin tam rotasına girer.',
    whyWrong: [
      'Sorun geçmiş olan araç değil, henüz görmediğiniz sıradaki araçtır.',
      'Yol vermek zaten yükümlülüktür; buradaki kritik beceri, dönüş anını da aynı dikkatle yönetmektir.',
    ],
    objective: 'Acil araç geçtikten sonra ikinci araç olasılığını kontrol etmeyi öğrenmek.',
    tags: ['gecis-ustunlugu', 'ikinci-arac', 'ayna-kontrolu'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-548',
    subject: 'adab',
    topic: 'emniyet-seridi-etigi',
    difficulty: 'orta',
    stem: 'Uzun yolda telefonunuza bakmak için "iki dakikalığına" emniyet şeridinde durmayı düşünüyorsunuz; acil bir durumunuz yok. Doğru değerlendirme hangisidir?',
    options: [
      'Emniyet şeridi yalnızca zorunlu hâller içindir; keyfî duruş hem arkadan çarpma riski doğurur hem gerçek acil durumdakilerin alanını işgal eder — ilk tesise veya cebe kadar devam edilmelidir',
      'Dörtlü lambalar yakılırsa kısa duruşlar serbesttir',
      'Gündüz görüş açık olduğundan sakıncası yoktur',
      'Araç şeride tam sığıyorsa hiçbir sorun oluşmaz',
    ],
    answerIndex: 0,
    explanation:
      'Emniyet şeridindeki duran araç, seyir hâlindeki trafiğin hemen dibinde hareketsiz bir hedeftir; üstelik oraya gerçekten mecbur kalanın ve acil araçların alanını daraltır. Telefon, birkaç kilometre ilerideki cebi bekleyebilir.',
    whyWrong: [
      'Dörtlü lamba duruşu meşrulaştırmaz; yalnızca ihlali aydınlatır.',
      'Gündüz de olsa yüksek hız farkı, duran araca çarpmayı en ölümcül kaza tiplerinden yapar.',
    ],
    objective: 'Emniyet şeridinde keyfî duruşun risk ve işgal boyutunu kavramak.',
    tags: ['emniyet-seridi-etigi', 'keyfi-durus', 'telefon'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-549',
    subject: 'adab',
    topic: 'hak-kavrami',
    difficulty: 'zor',
    stem: 'Kontrolsüz kavşakta geçiş önceliği sizde; ancak soldan gelen sürücü yavaşlamadan kavşağa giriyor. "Hak" ile "güvenlik" arasındaki doğru denge hangisidir?',
    options: [
      'Öncelik sizde olduğu için hızınızı koruyup hakkınızı kullanmak',
      'Önceliğinizden o an feragat edip yol vermek; haklı olmak çarpışmayı önlemez ve olgun sürücü hakkını canı pahasına savunmaz',
      'Kavşağa hızlanarak girip niyetinizi netleştirmek',
      'Korna ve selektörle hakkınızı ilan ederek geçmek',
    ],
    answerIndex: 1,
    explanation:
      'Trafikte hak, tutanaklarda işe yarar; kavşağın ortasında ise yalnızca fizik geçerlidir. Kuralın size verdiği önceliği, karşı tarafın hatası anında kullanmamak zayıflık değil, en yüksek sürücülük olgunluğudur.',
    whyWrong: [
      'Hakkını koruyarak girilen çarpışmada kazanan taraf yoktur; yalnızca hasar raporu vardır.',
      'Hızlanmak ve ışık-korna gösterisi, hatalı sürücünün hatasına sizin iradenizle ortak olmaktır.',
    ],
    objective: 'Geçiş hakkından güvenlik lehine feragat edebilme olgunluğunu kazanmak.',
    tags: ['hak-kavrami', 'feragat', 'defansif-surus'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-550',
    subject: 'adab',
    topic: 'gurultu-gorgusu',
    difficulty: 'kolay',
    stem: 'Aracınızın alarmı son günlerde geceleri rüzgârdan bile ötüyor ve komşularınız uykularının bölündüğünü söylüyor. Trafik ve çevre görgüsü açısından doğru davranış hangisidir?',
    options: [
      'Alarm güvenlik içindir; kimsenin karışma hakkı olmadığını söylemek',
      'Komşulara pencerelerini kapalı tutmalarını önermek',
      'Alarmın hassasiyetini ayarlatmak veya arızayı gidermek; çevrenin gece sessizliği de korunması gereken bir haktır',
      'Aracı yalnızca gündüzleri kullanmak',
    ],
    answerIndex: 2,
    explanation:
      'Aracınızın çevreye etkisi yalnızca yolda değil, park hâlindeyken de sürer. Sürekli yanlış alarm hem komşuların uyku hakkını ihlal eder hem de gerçek bir hırsızlık anında kimsenin dönüp bakmamasına yol açar.',
    whyWrong: [
      'Güvenlik gerekçesi, arızalı bir cihazın geceyi bölmesine meşruiyet kazandırmaz.',
      'Sorunun kaynağı sizde iken çözümü komşulardan beklemek sorumluluğu tersine çevirmektir.',
    ],
    objective: 'Araç kaynaklı gürültünün çevre hakkına etkisini park hâlinde de gözetmek.',
    tags: ['gurultu-gorgusu', 'alarm', 'komsu-hakki'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
];
