/**
 * ÖZGÜN trafik ve çevre soruları — 5. genişletme (Program 2 · Faz 9). ROADMAP C.4/E.6.
 * Kaynak = resmî müfredat/mevzuat; KENDİ İFADEMİZLE.
 */
import type { QuestionInput } from '@ea/content-schema';

const SRC = 'Karayolları Trafik Yönetmeliği + MEB müfredatı (özgün ifade)';

export const TRAFIK_QUESTIONS_5: QuestionInput[] = [
  {
    id: 'trafik-501',
    subject: 'trafik',
    topic: 'isikli-isaret-cihazlari',
    difficulty: 'kolay',
    stem: 'Kavşaktaki ışıklı işaret cihazında sarı ışık aralıklarla yanıp sönüyorsa sürücü ne yapmalıdır?',
    options: [
      'Durup yeşil ışığın yanmasını beklemelidir',
      'Hızlanarak kavşağı bir an önce terk etmelidir',
      'Yavaşlamalı ve geçiş önceliği kurallarına uyarak dikkatle geçmelidir',
      'Cihaz arızalı sayılacağından tüm işaretleri yok saymalıdır',
    ],
    answerIndex: 2,
    explanation:
      'Yanıp sönen sarı ışık bir uyarıdır: kavşak, ışıkla yönetilmeyen kavşak gibi değerlendirilir. Sürücü hızını azaltır ve geçiş önceliği kurallarına uyarak dikkatle geçer.',
    whyWrong: [
      'Yanıp sönen sarıda yeşil beklenmez; bu ışık sürekli düzendeki sarı değildir.',
      'Hızlanmak uyarı anlamının tam tersidir; kavşakta risk artar.',
      'İşaretleri yok saymak yerine geçiş önceliği kuralları devreye girer.',
    ],
    objective: 'Yanıp sönen sarı ışığın uyarı anlamını bilmek.',
    tags: ['isikli-isaret', 'sari-isik', 'kavsak'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-502',
    subject: 'trafik',
    topic: 'isikli-isaret-cihazlari',
    difficulty: 'orta',
    stem: 'Işıklı işaret cihazında kırmızı ışıkla birlikte sarı ışık da yanıyorsa bu sürücüye ne bildirir?',
    options: [
      'Kavşağın tamamen trafiğe kapatıldığını',
      'Yolun az sonra trafiğe açılacağını; harekete hazırlanılması gerektiğini',
      'Sürücünün beklemeden geçebileceğini',
      'Yalnızca yayaların geçebileceğini',
    ],
    answerIndex: 1,
    explanation:
      'Kırmızı ile birlikte yanan sarı, ışığın az sonra yeşile döneceğini haber verir. Sürücü kalkışa hazırlanır; ancak yeşil yanmadan harekete geçmek yine de ihlaldir.',
    whyWrong: [
      'Bu birleşim kapanışı değil, açılışın yaklaştığını bildirir.',
      'Yeşil yanmadan geçmek kırmızı ışık ihlali sayılır.',
      'Yaya geçişleri ayrı yaya ışıklarıyla düzenlenir; bu birleşimin yayalarla ilgisi yoktur.',
    ],
    objective: 'Kırmızı + sarı birleşiminin "harekete hazırlan" anlamını bilmek.',
    tags: ['isikli-isaret', 'kirmizi-sari', 'kavsak'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-503',
    subject: 'trafik',
    topic: 'isikli-isaret-cihazlari',
    difficulty: 'kolay',
    stem: 'Işıklı işaret cihazında yanan yeşil ok ışığı sürücüye hangi hakkı verir?',
    options: [
      'Yalnızca okun gösterdiği yöne hareket etme',
      'Bütün yönlere serbestçe hareket etme',
      'Kavşak içinde bekleme yapma',
      'Karşı şeride geçerek öndeki aracı sollama',
    ],
    answerIndex: 0,
    explanation:
      'Yeşil ok, sadece okun gösterdiği yöndeki hareketin serbest olduğunu bildirir; diğer yönler için ana ışık düzeni geçerlidir.',
    whyWrong: [
      'Ok tüm yönleri değil, tek bir yönü serbest bırakır.',
      'Kavşak içi bekleme yeri değildir; ok bekleme hakkı tanımaz.',
      'Sollama izniyle hiçbir ilgisi yoktur.',
    ],
    objective: 'Yeşil ok ışığının kapsamını bilmek.',
    tags: ['isikli-isaret', 'yesil-ok', 'donus'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-504',
    subject: 'trafik',
    topic: 'isikli-isaret-cihazlari',
    difficulty: 'kolay',
    stem: 'Dikey olarak yerleştirilmiş standart bir ışıklı işaret cihazında ışıkların yukarıdan aşağıya sıralanışı nasıldır?',
    options: [
      'Yeşil, sarı, kırmızı',
      'Sarı, kırmızı, yeşil',
      'Yeşil, kırmızı, sarı',
      'Kırmızı, sarı, yeşil',
    ],
    answerIndex: 3,
    explanation:
      'Standart dizilişte en üstte kırmızı, ortada sarı, en altta yeşil bulunur. Bu sabit düzen, renkleri ayırt edemeyen sürücülerin bile ışığın konumundan anlamı çıkarabilmesini sağlar.',
    whyWrong: [
      'Yeşilin üstte olduğu diziliş standarda aykırıdır.',
      'Sarı en üstte yer almaz; ortadaki uyarı konumundadır.',
      'Kırmızı ile sarının yer değiştirdiği düzen kullanılmaz.',
    ],
    objective: 'Işıklı işaret cihazındaki standart renk dizilişini bilmek.',
    tags: ['isikli-isaret', 'renk-dizilisi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-505',
    subject: 'trafik',
    topic: 'isikli-isaret-cihazlari',
    difficulty: 'zor',
    stem: 'Işıklı işaret cihazının hiç yanmadığı (arızalı ve sönük olduğu) bir kavşağa yaklaşan sürücü nasıl davranmalıdır?',
    options: [
      'Işıklar yanmadığına göre geçiş hakkı her zaman kendisinindir',
      'Yalnızca korna çalarak geçmelidir',
      'Kavşağı kapalı sayıp geldiği yöne geri dönmelidir',
      'Varsa trafik işaret levhalarına, yoksa kontrolsüz kavşak geçiş kurallarına göre hareket etmelidir',
    ],
    answerIndex: 3,
    explanation:
      'Işıklar devre dışıysa kavşaktaki düzen bir alt kademeye iner: önce oradaki işaret levhaları, onlar da yoksa kontrolsüz kavşaklardaki genel geçiş önceliği kuralları uygulanır.',
    whyWrong: [
      'Işığın sönük olması kimseye otomatik öncelik vermez.',
      'Korna geçiş hakkı doğurmaz; sadece uyarı aracıdır.',
      'Kavşak kapalı değildir; kurallar hiyerarşisine göre dikkatle geçilir.',
    ],
    objective: 'Işıklar arızalıyken uygulanacak kural sırasını kavramak.',
    tags: ['isikli-isaret', 'ariza', 'kontrolsuz-kavsak'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-506',
    subject: 'trafik',
    topic: 'isikli-isaret-cihazlari',
    difficulty: 'orta',
    stem: 'Işıklı kavşakta yeşil ışıkta sağa dönen sürücü, aynı anda kendi yeşil ışığıyla karşıya geçmekte olan yayalarla karşılaşırsa ne yapmalıdır?',
    options: [
      'Korna çalarak yayaları hızlandırmalıdır',
      'Yayaların arasındaki boşluklardan yavaşça ilerlemelidir',
      'Durup yayaların geçişlerini tamamlamasını beklemelidir',
      'Dönüşten vazgeçip kavşaktan düz geçmelidir',
    ],
    answerIndex: 2,
    explanation:
      'Dönüş yapan sürücü, geçiş hakkını kullanan yayalara yol vermek zorundadır. Yeşil ışık dönüşe izin verir; ancak bu izin, geçitteki yayaların önceliğini ortadan kaldırmaz.',
    whyWrong: [
      'Korna, yayaların geçiş hakkını ortadan kaldırmaz ve panik yaratabilir.',
      'Yayaların arasından süzülmek çarpma riski taşır ve ihlaldir.',
      'Rota değiştirmek gerekmez; doğru davranış beklemektir.',
    ],
    objective: 'Dönüşlerde yaya önceliğinin sürdüğünü kavramak.',
    tags: ['yaya-onceligi', 'saga-donus', 'isikli-kavsak'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-507',
    subject: 'trafik',
    topic: 'gorevli-isaretleri',
    difficulty: 'orta',
    stem: 'Kavşakta trafiği yöneten görevlinin cephesinin (ön ve arka tarafının) baktığı yönlerdeki sürücüler için bu duruşun anlamı nedir?',
    options: [
      'Bu yönlerdeki trafik için "dur" anlamına gelir',
      'Bu yönlerdeki trafik serbestçe geçebilir',
      'Yalnızca sağa dönüş serbesttir',
      'Hızlanarak geçilmesi gerektiğini bildirir',
    ],
    answerIndex: 0,
    explanation:
      'Görevlinin ön ve arka cephesi kırmızı ışık gibi okunur: cepheye bakan yönlerdeki araçlar durur. Yol verme, görevlinin yan taraflarına denk gelen yönlere aittir.',
    whyWrong: [
      'Serbest geçiş, cepheye değil yan duruşa denk gelen yönler içindir.',
      'Cephe duruşu dönüş türüne göre ayrım yapmaz; yönün tamamı durur.',
      'Hızlanma talimatı anlamına gelen bir duruş yoktur.',
    ],
    objective: 'Görevlinin cephe duruşunun "dur" anlamını bilmek.',
    tags: ['trafik-polisi', 'kol-isaretleri', 'kavsak'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-508',
    subject: 'trafik',
    topic: 'gorevli-isaretleri',
    difficulty: 'orta',
    stem: 'Trafik görevlisinin bir kolunu dik olarak yukarı kaldırması sürücülere ne anlatır?',
    options: [
      'Yalnızca yayaların durması gerektiğini',
      'Trafiğin hızlanması gerektiğini',
      'Sadece ağır taşıtların durmasını',
      'Bütün yönlerdeki trafiğin durması gerektiğini',
    ],
    answerIndex: 3,
    explanation:
      'Kolun dik olarak yukarı kaldırılması, kavşağa her yönden yaklaşan bütün trafiğe verilen "dur" işaretidir; görevli bu işaretle kavşağı tamamen boşaltıp yeni bir düzen kurar.',
    whyWrong: [
      'İşaret yalnız yayaları değil, tüm trafiği bağlar.',
      'Hızlanma değil, tam tersine durma istenir.',
      'Araç türüne göre ayrım yapılmaz; herkes durur.',
    ],
    objective: 'Yukarı kalkan kolun tüm yönlere "dur" anlamına geldiğini bilmek.',
    tags: ['trafik-polisi', 'kol-isaretleri', 'dur-isareti'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-509',
    subject: 'trafik',
    topic: 'gorevli-isaretleri',
    difficulty: 'kolay',
    stem: 'Trafiği yöneten görevlinin yan duruşu (kollarının açık olduğu taraflar) o yönlerdeki sürücüler için ne anlama gelir?',
    options: [
      'Dur işareti verildiğini',
      'Geçişin serbest olduğunu (yolun açık olduğunu)',
      'Yalnızca sola dönüş yapılabileceğini',
      'Yolun trafiğe tamamen kapalı olduğunu',
    ],
    answerIndex: 1,
    explanation:
      'Görevlinin yan tarafları yeşil ışık gibi okunur: bu yönlere bakan sürücüler için geçiş serbesttir. Duruş yönü değiştikçe açık ve kapalı yönler de değişir.',
    whyWrong: [
      '"Dur", görevlinin cephesine bakan yönler için geçerlidir.',
      'Yan duruş dönüş türünü kısıtlamaz; yönü açar.',
      'Kapalı olan yönler cephenin baktığı yönlerdir.',
    ],
    objective: 'Görevlinin yan duruşunun "geç" anlamını bilmek.',
    tags: ['trafik-polisi', 'kol-isaretleri'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-510',
    subject: 'trafik',
    topic: 'yon-levhalari',
    difficulty: 'kolay',
    stem: 'Otoyollardaki yön ve bilgi levhalarının zemin rengi standart olarak hangisidir?',
    options: ['Mavi', 'Kahverengi', 'Yeşil', 'Sarı'],
    answerIndex: 2,
    explanation:
      'Otoyol yön ve bilgi levhaları yeşil zeminlidir. Sürücü, zemin renginden levhanın hangi yol ağına ait olduğunu tek bakışta anlar.',
    whyWrong: [
      'Mavi zemin, devlet ve il yollarındaki yön levhalarında kullanılır.',
      'Kahverengi zemin turistik ve tarihi yerleri tanıtır.',
      'Sarı zemin genellikle yol çalışması gibi geçici düzenlemelerde görülür.',
    ],
    objective: 'Otoyol levhalarının yeşil zeminli olduğunu bilmek.',
    tags: ['yon-levhasi', 'otoyol', 'levha-renkleri'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-511',
    subject: 'trafik',
    topic: 'yon-levhalari',
    difficulty: 'orta',
    stem: 'Devlet ve il yollarında sürücüleri yerleşim merkezlerine yönlendiren levhaların zemin rengi hangisidir?',
    options: ['Mavi', 'Yeşil', 'Kırmızı', 'Siyah'],
    answerIndex: 0,
    explanation:
      'Devlet ve il yollarının yön levhaları mavi zeminlidir; yeşil zemin otoyola ayrılmıştır. Renk ayrımı, kavşaklarda doğru yol ağını seçmeyi kolaylaştırır.',
    whyWrong: [
      'Yeşil zemin otoyol levhalarına aittir.',
      'Kırmızı, yasak ve tehlike bildirimlerinin rengidir; yön levhası zemini olarak kullanılmaz.',
      'Siyah zeminli yön levhası standart uygulamada yoktur.',
    ],
    objective: 'Devlet/il yolu levhalarının mavi zeminli olduğunu bilmek.',
    tags: ['yon-levhasi', 'levha-renkleri'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-512',
    subject: 'trafik',
    topic: 'yon-levhalari',
    difficulty: 'orta',
    stem: 'Kahverengi zemin üzerine beyaz yazı ve sembol bulunan bilgi levhaları sürücüye neyi tanıtır?',
    options: [
      'Otoyol giriş ve çıkışlarını',
      'Askeri güvenlik bölgelerini',
      'Akaryakıt istasyonlarını',
      'Turistik ve tarihi yerleri',
    ],
    answerIndex: 3,
    explanation:
      'Kahverengi zeminli levhalar ören yeri, müze, milli park gibi turistik ve kültürel değerleri işaret eder; sürücüyü bu noktalara yönlendirir.',
    whyWrong: [
      'Otoyol bilgilendirmesi yeşil zeminli levhalarla yapılır.',
      'Askeri bölge uyarıları bu levha grubuna girmez.',
      'Akaryakıt gibi hizmet tesisleri ayrı hizmet işaretleriyle gösterilir.',
    ],
    objective: 'Kahverengi levhaların turistik-tarihi yerleri gösterdiğini bilmek.',
    tags: ['yon-levhasi', 'turistik-levha', 'levha-renkleri'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-513',
    subject: 'trafik',
    topic: 'yerlesim-levhalari',
    difficulty: 'kolay',
    stem: 'Üzerinde yalnızca yerleşim yerinin adı yazan giriş levhasını geçen otomobil sürücüsü, aksini bildiren başka bir levha yoksa hızını en fazla kaç km/saat olarak ayarlamalıdır?',
    options: ['30', '50', '70', '90'],
    answerIndex: 1,
    explanation:
      'Yerleşim yeri adı yazılı levha, yerleşim biriminin başladığını bildirir; bu noktadan itibaren aksine işaret yoksa otomobiller için yerleşim içi genel sınır olan 50 km/saat geçerlidir.',
    whyWrong: [
      '30 km/saat ancak ek bir hız levhasıyla istenirse geçerli olur.',
      '70 ve 90 km/saat yerleşim yeri dışındaki yol tiplerine ait sınırlardır.',
    ],
    objective: 'Giriş levhasının hız düzenini yerleşim içine çevirdiğini bilmek.',
    tags: ['yerlesim-yeri', 'hiz-siniri', 'levha'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-514',
    subject: 'trafik',
    topic: 'yerlesim-levhalari',
    difficulty: 'orta',
    stem: 'Yerleşim yeri adının üzeri kırmızı bir çizgiyle çizilmiş levha sürücüye neyi bildirir?',
    options: [
      'O yerleşim yerine girişin yasak olduğunu',
      'Yolun trafiğe kapatıldığını',
      'Yerleşim yerinin sona erdiğini; hız düzeninin yerleşim yeri dışı kurallarına döndüğünü',
      'Şehir merkezine yaklaşıldığını',
    ],
    answerIndex: 2,
    explanation:
      'Adı çizilmiş levha yerleşim biriminin çıkışını gösterir. Bu noktadan sonra, aksine işaret yoksa yol tipine göre yerleşim yeri dışı hız sınırları uygulanır.',
    whyWrong: [
      'Levha giriş yasağı koymaz; sınırın bittiğini bildirir.',
      'Yol açıktır; kapatma bildirimi başka işaretlerle yapılır.',
      'Merkeze yaklaşmayı değil, yerleşim biriminden çıkışı anlatır.',
    ],
    objective: 'Çıkış levhasının hız düzenine etkisini kavramak.',
    tags: ['yerlesim-yeri', 'hiz-siniri', 'levha'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-515',
    subject: 'trafik',
    topic: 'yaya-okul-gecidi',
    difficulty: 'kolay',
    stem: 'Okul geçidini sıradan bir yaya geçidinden ayıran temel özellik nedir?',
    options: [
      'Öğrencilerin geçişine ayrılmış olması ve geçişlerin görevli tarafından yönetilebilmesi',
      'Yalnızca gece kullanılması',
      'Sadece taşıtların geçişine izin vermesi',
      'Üzerine park edilebilmesi',
    ],
    answerIndex: 0,
    explanation:
      'Okul geçidi, okul çevresinde öğrencilerin karşıya güvenle geçmesi için ayrılmış geçittir; geçişler çoğu zaman elinde DUR işareti bulunan okul geçidi görevlisince yönetilir.',
    whyWrong: [
      'Kullanım saatle sınırlanmış değildir; okul hareketliliğinin olduğu her an önemlidir.',
      'Geçit taşıtlara değil, yaya konumundaki öğrencilere aittir.',
      'Geçit üzerine park etmek her geçit türünde yasaktır.',
    ],
    objective: 'Okul geçidinin işlevini yaya geçidinden ayırt etmek.',
    tags: ['okul-gecidi', 'yaya-gecidi', 'cocuk-guvenligi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-516',
    subject: 'trafik',
    topic: 'yaya-okul-gecidi',
    difficulty: 'orta',
    stem: 'Yol kenarında okul geçidi levhası gören sürücünün doğru davranışı hangisidir?',
    options: [
      'Hızını artırıp bölgeyi hızla terk etmek',
      'Levhayı yalnızca okul saatleri içinde dikkate almak',
      'Korna çalarak öğrencileri kenara çekilmeye zorlamak',
      'Hızını azaltmak ve her an yola öğrenci çıkabileceğini hesaba katmak',
    ],
    answerIndex: 3,
    explanation:
      'Okul geçidi levhası, ileride öğrenci geçişlerinin yoğun olduğu bir bölge bulunduğunu haber verir. Sürücü hızını düşürür, frene hazır olur ve geçit çevresini sürekli tarar.',
    whyWrong: [
      'Hızlanmak, aniden yola çıkabilecek çocuklara tepki süresini yok eder.',
      'Levhanın uyarısı saatle sınırlı okunamaz; öğrenci hareketliliği değişkendir.',
      'Korna çocukları ürkütüp öngörülemez davranışlara itebilir.',
    ],
    objective: 'Okul geçidi levhasının gerektirdiği sürüş davranışını bilmek.',
    tags: ['okul-gecidi', 'levha', 'cocuk-guvenligi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-517',
    subject: 'trafik',
    topic: 'bisiklet-yolu',
    difficulty: 'kolay',
    stem: 'Yalnızca bisikletlilerin kullanımına ayrılmış bisiklet yolu ile ilgili motorlu araç sürücüleri için kural nedir?',
    options: [
      'Kısa mesafelerde kullanılabilir',
      'Sadece motosikletler girebilir',
      'Motorlu araçlar bu yola giremez, üzerinde duraklayamaz ve park edemez',
      'Gece saatlerinde tüm araçlara açıktır',
    ],
    answerIndex: 2,
    explanation:
      'Bisiklet yolu, bisiklet trafiğine ayrılmış korunaklı bir alandır. Motorlu araçların bu alana girmesi, üzerinde duraklaması veya park etmesi bisikletlileri taşıt trafiğinin içine iterek tehlikeye atar; yasaktır.',
    whyWrong: [
      'Mesafenin kısalığı yasağı kaldırmaz.',
      'Motosiklet de motorlu araçtır; bisiklet yoluna giremez.',
      'Yasak gece-gündüz ayrımı olmaksızın süreklidir.',
    ],
    objective: 'Bisiklet yolunun motorlu araçlara kapalı olduğunu bilmek.',
    tags: ['bisiklet-yolu', 'park-yasagi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-518',
    subject: 'trafik',
    topic: 'bisiklet-yolu',
    difficulty: 'orta',
    stem: 'Trafik mevzuatında "bisiklet şeridi" ne anlama gelir?',
    options: [
      'Bisikletlerin park edildiği alan',
      'Taşıt yolu üzerinde çizgilerle bisikletlere ayrılmış, diğer araçların giremeyeceği şerit',
      'Kaldırımın bisikletlere ayrılan bölümü',
      'Yalnızca yarış bisikletlerinin kullandığı özel pist',
    ],
    answerIndex: 1,
    explanation:
      'Bisiklet şeridi, taşıt yolunun üzerinde yer çizgileri ve işaretlerle bisiklet trafiğine ayrılmış bölümdür; diğer sürücüler bu şeridi işgal edemez.',
    whyWrong: [
      'Park alanı ayrı bir düzenlemedir; şerit seyir içindir.',
      'Kaldırım üzerindeki ayrılmış bölüm bisiklet yolu kapsamına girer, şerit taşıt yolundadır.',
      'Şerit günlük ulaşım içindir; yarışla ilgisi yoktur.',
    ],
    objective: 'Bisiklet şeridi kavramını doğru tanımlamak.',
    tags: ['bisiklet-seridi', 'tanimlar'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-519',
    subject: 'trafik',
    topic: 'bisiklet-yolu',
    difficulty: 'orta',
    stem: 'Bir bisikletlinin yanından geçen otomobil sürücüsü, aracıyla bisiklet arasında yandan en az kaç metre mesafe bırakmalıdır?',
    options: ['1,5 metre', '0,5 metre', '3 metre', '5 metre'],
    answerIndex: 0,
    explanation:
      'Bisikletliyi geçerken en az 1,5 metre yan mesafe bırakılması zorunludur; bisiklet rüzgârdan ve zemin bozukluklarından etkilenip yalpalayabileceği için bu pay hayati önem taşır.',
    whyWrong: [
      'Yarım metre, bisikletlinin küçük bir dengesizliğinde bile çarpışmaya yetecek kadar yakındır.',
      '3 ve 5 metre mevzuattaki asgari değer değildir; kural en az 1,5 metredir.',
    ],
    objective: 'Bisikletli geçişinde 1,5 metre yan mesafe kuralını bilmek.',
    tags: ['bisiklet', 'yan-mesafe', 'sollama'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-520',
    subject: 'trafik',
    topic: 'elektrikli-scooter',
    difficulty: 'kolay',
    stem: 'Paylaşımlı elektrikli skuterlerin (e-skuter) tasarım gereği aşamayacağı azami hız kaç km/saattir?',
    options: ['15', '25', '45', '60'],
    answerIndex: 1,
    explanation:
      'Elektrikli skuterler, hızı 25 km/saati aşmayacak şekilde üretilir ve kullanılır; bu sınır, korumasız sürücünün düşme ve çarpışma riskini kontrol altında tutmak içindir.',
    whyWrong: [
      '15 km/saat mevzuattaki sınır değildir; sınır bunun üzerindedir.',
      '45 ve 60 km/saat motorlu bisiklet ve motosiklet sınıflarını ilgilendiren değerlerdir.',
    ],
    objective: 'E-skuter azami hız sınırını (25 km/saat) bilmek.',
    tags: ['e-skuter', 'hiz-siniri'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-521',
    subject: 'trafik',
    topic: 'elektrikli-scooter',
    difficulty: 'orta',
    stem: 'Elektrikli skuter kullanan bir kişinin kaldırımda (yaya yolunda) sürüş yapması nasıl değerlendirilir?',
    options: [
      'Yavaş sürülmesi şartıyla serbesttir',
      'Yalnızca gece serbesttir',
      'Trafik sıkışıksa serbesttir',
      'Yasaktır; varsa bisiklet yolu veya şeridi, yoksa kurallara uygun biçimde taşıt yolu kullanılır',
    ],
    answerIndex: 3,
    explanation:
      'Kaldırım yayaların alanıdır; e-skuterle yaya yolunda sürmek yasaktır. Sürüş, öncelikle bisiklet yolu veya şeridinde, bunlar yoksa kurallar çerçevesinde taşıt yolunda yapılır.',
    whyWrong: [
      'Düşük hız bile yayalarla çarpışma riskini ortadan kaldırmaz; yasak hıza bağlı değildir.',
      'Gece ayrıcalığı yoktur; görüşün azaldığı saatlerde risk daha da büyür.',
      'Trafik yoğunluğu kaldırımı kullanma hakkı doğurmaz.',
    ],
    objective: 'E-skuterin kaldırımda sürülemeyeceğini bilmek.',
    tags: ['e-skuter', 'yaya-yolu', 'yaya-guvenligi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-522',
    subject: 'trafik',
    topic: 'elektrikli-scooter',
    difficulty: 'orta',
    stem: 'Elektrikli skuterde ikinci bir kişi taşımak ile ilgili kural nedir?',
    options: [
      'Yasaktır; e-skuter tek kişilik bir araçtır',
      'Çocuklar taşınabilir',
      'Kask takan ikinci kişi taşınabilir',
      'Kısa mesafede serbesttir',
    ],
    answerIndex: 0,
    explanation:
      'E-skuter tek kişinin kullanımı için tasarlanmıştır; ikinci kişi taşımak dengeyi ve fren performansını bozduğu için yasaktır. Ayrıca sırt çantası dışında yük de taşınamaz.',
    whyWrong: [
      'Çocuk taşımak da aynı yasağın kapsamındadır ve daha da tehlikelidir.',
      'Kask, taşıma yasağını ortadan kaldırmaz.',
      'Mesafenin kısalığı denge sorununu değiştirmez.',
    ],
    objective: 'E-skuterin tek kişilik olduğunu bilmek.',
    tags: ['e-skuter', 'yolcu-yasagi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-523',
    subject: 'trafik',
    topic: 'ariza-isaretleme',
    difficulty: 'orta',
    stem: 'Yerleşim yeri dışında arızalanarak yolda kalan bir aracın üçgen reflektörleri nasıl yerleştirilmelidir?',
    options: [
      'Aracın hemen yanına, 1 metre mesafeye',
      'Yalnızca aracın tavanına',
      'Araçtan en az 30 metre uzağa ve diğer sürücülerce en az 150 metreden görülebilecek şekilde',
      'Karşı şeridin ortasına',
    ],
    answerIndex: 2,
    explanation:
      'Reflektörler, yaklaşan sürücülere fren ve şerit değiştirme payı bırakacak kadar erken uyarı vermelidir: araçtan en az 30 metre uzağa konur ve en az 150 metreden net görülebilir olmalıdır.',
    whyWrong: [
      'Aracın dibine konan reflektör, ancak araçla aynı anda fark edilir; uyarı işlevi kalmaz.',
      'Tavana konan işaret yerdeki standart uyarı düzeninin yerine geçmez.',
      'Karşı şeride konan gereç oradaki trafiği tehlikeye atar.',
    ],
    objective: 'Reflektör yerleştirmede 30/150 metre kuralını bilmek.',
    tags: ['ariza', 'reflektor', 'mesafe-kurali'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-524',
    subject: 'trafik',
    topic: 'ariza-isaretleme',
    difficulty: 'kolay',
    stem: 'İki yönlü bir yolda arızalanan araç için üçgen reflektörler aracın neresine konulmalıdır?',
    options: [
      'Yalnızca arkasına',
      'Ön ve arkasına birer adet olacak şekilde',
      'Yalnızca önüne',
      'Sağ ve sol yanlarına',
    ],
    answerIndex: 1,
    explanation:
      'İki yönlü yolda tehlike her iki yönden de gelir; bu yüzden reflektörlerden biri aracın önüne, diğeri arkasına yerleştirilerek her iki yöndeki sürücüler uyarılır.',
    whyWrong: [
      'Yalnız arkaya konan reflektör karşı yönden gelenleri uyarmaz.',
      'Yalnız öne konan reflektör de arkadan gelenleri habersiz bırakır.',
      'Yanlara konan işaret iki yöndeki akan trafiğe görünmez.',
    ],
    objective: 'İki yönlü yolda ön-arka işaretleme kuralını bilmek.',
    tags: ['ariza', 'reflektor', 'iki-yonlu-yol'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-525',
    subject: 'trafik',
    topic: 'ariza-isaretleme',
    difficulty: 'zor',
    stem: 'Otoyolda arızalanan aracını emniyet şeridine çeken sürücü ve yolcuları yardım gelene kadar nerede beklemelidir?',
    options: [
      'Araç içinde emniyet kemerleri takılı olarak',
      'Emniyet şeridinde aracın hemen arkasında ayakta',
      'Taşıt yolunun kenarında yürüyerek',
      'Araçtan inerek oto korkuluğun (bariyerin) arkasındaki güvenli alanda',
    ],
    answerIndex: 3,
    explanation:
      'Emniyet şeridindeki araca yüksek hızla çarpılma riski her zaman vardır. Bu nedenle araçta veya aracın dibinde beklenmez; herkes araçtan inip bariyerin arkasındaki güvenli alana geçer.',
    whyWrong: [
      'Araç içinde beklemek, arkadan çarpmada en ağır sonucu doğurur.',
      'Aracın hemen arkası, olası çarpışmanın tam etki alanıdır.',
      'Taşıt yolu kenarında yürümek otoyolda ölümcül risktir.',
    ],
    objective: 'Otoyol arızasında bariyer arkasında bekleme kuralını bilmek.',
    tags: ['otoyol', 'ariza', 'guvenli-bekleme'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-526',
    subject: 'trafik',
    topic: 'kaza-yeri-guvenlik',
    difficulty: 'orta',
    stem: 'Trafik kazası yerinde yangın tehlikesine karşı alınması gereken önlem hangisidir?',
    options: [
      'Kazaya karışan araçların kontağını kapatmak ve çevrede sigara içilmesini engellemek',
      'Motoru rölantide çalışır durumda bırakmak',
      'Sızıntıyı görmek için yakıt deposunu açmak',
      'Araç camlarını kapalı tutmak',
    ],
    answerIndex: 0,
    explanation:
      'Kazada yakıt sızıntısı olabilir; kıvılcım kaynaklarını kesmek esastır. Kontak kapatılır, sigara içilmez ve içilmesine izin verilmez.',
    whyWrong: [
      'Çalışan motor, sızan yakıt için tutuşturucu kaynaktır.',
      'Depoyu açmak buhar çıkışını artırıp riski büyütür.',
      'Camların durumu yangın önlemleriyle ilgili belirleyici değildir.',
    ],
    objective: 'Kaza yerinde yangına karşı temel önlemleri bilmek.',
    tags: ['kaza-yeri', 'yangin', 'guvenlik-onlemi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-527',
    subject: 'trafik',
    topic: 'kaza-yeri-guvenlik',
    difficulty: 'zor',
    stem: 'Kaza yerinin yanından geçen ve yardımına ihtiyaç bulunmayan sürücülerin durup olayı izlemesi nasıl değerlendirilir?',
    options: [
      'Tanıklık için gereklidir',
      'Trafik kültürünün doğal bir parçasıdır',
      'Yanlıştır; trafiği tıkar, yardım araçlarını geciktirir ve yeni kazalara zemin hazırlar',
      'Sürücünün yasal hakkıdır',
    ],
    answerIndex: 2,
    explanation:
      'Kaza yerinde meraklı yığılması, ambulans ve itfaiyenin ulaşmasını geciktirir; ani yavaşlamalar zincirleme kazalara yol açar. Yardım gerekmiyorsa yol boşaltılıp geçilmelidir.',
    whyWrong: [
      'Tanıklık, olayı görenlerin bilgi vermesiyle olur; sonradan durup izlemek tanıklık değildir.',
      'Bu davranış kültür değil, yardım zincirini kıran bir alışkanlıktır.',
      'Trafiği aksatma pahasına durup izleme diye bir hak yoktur.',
    ],
    objective: 'Kaza yerinde seyirci trafiğinin zararını kavramak.',
    tags: ['kaza-yeri', 'trafik-akisi', 'yardim'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-528',
    subject: 'trafik',
    topic: 'hayvan-yaya-gecirme',
    difficulty: 'kolay',
    stem: 'Karayolunda hayvan sürüsüyle karşılaşan sürücünün doğru davranışı nedir?',
    options: [
      'Korna çalarak sürüyü dağıtmak',
      'Hızını azaltmak, gerekirse durarak sürünün güvenle geçmesini beklemek',
      'Uzun farları yakıp hızla ilerlemek',
      'Sürünün içinden yavaşça geçmeye çalışmak',
    ],
    answerIndex: 1,
    explanation:
      'Hayvanların davranışı öngörülemez; ürken hayvan aracın önüne atılabilir. Doğru davranış yavaşlamak, gerekirse durmak ve sürünün yolu boşaltmasını beklemektir.',
    whyWrong: [
      'Korna hayvanları ürkütüp paniğe ve dağılmaya yol açar.',
      'Uzun far ve hız, ürkme riskini artırır.',
      'Sürünün içine girmek hem hayvanlar hem araç için tehlikelidir.',
    ],
    objective: 'Hayvan sürüsü karşısında sakin ve bekleyen sürüşü benimsemek.',
    tags: ['hayvan-surusu', 'guvenli-surus'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-529',
    subject: 'trafik',
    topic: 'hayvan-yaya-gecirme',
    difficulty: 'zor',
    stem: 'Görevli eşliğinde karayolundan karşıya geçirilen bir öğrenci kafilesiyle karşılaşan sürücü ne yapmalıdır?',
    options: [
      'Durmalı ve kafileyi bölmeden geçişin tamamlanmasını beklemelidir',
      'Kafiledeki boşluklardan yavaşça geçmelidir',
      'Yalnızca hızını biraz azaltmalıdır',
      'Selektör yaparak geçiş hakkı istemelidir',
    ],
    answerIndex: 0,
    explanation:
      'Görevli yönetiminde geçen kafile bir bütündür; araçlar durur ve grubun tamamı karşıya geçene kadar bekler. Kafileyi bölmek, arkada kalan çocukları yolun ortasında yalnız bırakır.',
    whyWrong: [
      'Boşluktan geçmek kafileyi böler ve panik yaratır.',
      'Yavaşlamak yetmez; görevlinin işareti ve grup geçişi durmayı gerektirir.',
      'Selektör, yayalara karşı bir öncelik talebi olamaz.',
    ],
    objective: 'Yaya kafilesinin bölünmeden geçirilmesi gerektiğini bilmek.',
    tags: ['yaya-kafilesi', 'okul', 'cocuk-guvenligi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-530',
    subject: 'trafik',
    topic: 'toplu-tasima-kolaylik',
    difficulty: 'kolay',
    stem: 'Yerleşim yeri içinde, duraktan çıkmak için sinyal veren bir belediye otobüsüne arkadan yaklaşan sürücü ne yapmalıdır?',
    options: [
      'Korna çalarak otobüsü durdurmalıdır',
      'Hızlanıp otobüsten önce geçmelidir',
      'Otobüsün çıkışını kapatacak şekilde yanına yaklaşmalıdır',
      'Yavaşlayıp otobüsün ilk hareketine kolaylık sağlamalıdır',
    ],
    answerIndex: 3,
    explanation:
      'Yerleşim yeri içinde sürücüler, duraktan kalkış işareti veren toplu taşıma araçlarına ilk hareketlerinde kolaylık sağlamak zorundadır; bu, toplu ulaşımın aksamadan akmasını sağlar.',
    whyWrong: [
      'Korna, kolaylık gösterme yükümlülüğünü ortadan kaldırmaz.',
      'Hızlanarak önünü kesmek kuralın tam tersidir.',
      'Çıkışı kapatmak hem kural ihlali hem trafik tıkanıklığı nedenidir.',
    ],
    objective: 'Duraktan kalkan toplu taşıma aracına kolaylık kuralını bilmek.',
    tags: ['toplu-tasima', 'durak', 'kolaylik-saglama'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-531',
    subject: 'trafik',
    topic: 'toplu-tasima-kolaylik',
    difficulty: 'orta',
    stem: 'Durakta yolcu indirip bindiren bir otobüsün yanından geçen sürücü neden özellikle dikkatli olmalıdır?',
    options: [
      'Otobüs yakıt alıyor olabileceği için',
      'Durakta trafik görevlisi bulunabileceği için',
      'İnen yolcular otobüsün önünden veya arkasından aniden yola çıkabileceği için',
      'Otobüs sürücüsünün ceza yazma yetkisi olduğu için',
    ],
    answerIndex: 2,
    explanation:
      'Duran otobüs bir görüş perdesidir: inen yolcular, özellikle çocuklar, otobüsün önünden veya arkasından görünmeden yola adım atabilir. Sürücü yavaşlamalı ve frene hazır geçmelidir.',
    whyWrong: [
      'Yakıt ikmali duraklarda yapılmaz; asıl risk yaya hareketidir.',
      'Görevli ihtimali değil, görünmeyen yaya riski dikkat gerektirir.',
      'Otobüs sürücüsünün ceza yetkisi yoktur; tehlike yayalardan gelir.',
    ],
    objective: 'Durak çevresindeki görünmez yaya riskini kavramak.',
    tags: ['durak', 'yaya-guvenligi', 'gorus-perdesi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-532',
    subject: 'trafik',
    topic: 'ters-yon',
    difficulty: 'kolay',
    stem: 'Tek yönlü bir yola ters yönden girmek ile ilgili hangisi doğrudur?',
    options: [
      'Yasaktır; karşıdan gelen trafikle çarpışma riski yaratır ve cezai yaptırımı vardır',
      'Kısa mesafede serbesttir',
      'Yalnızca gece yasaktır',
      'Dörtlü ikaz yakılırsa serbest hâle gelir',
    ],
    answerIndex: 0,
    explanation:
      'Tek yönlü yolda bütün trafik aynı yöne akar; ters giren araç, kendisini beklemeyen sürücülerin tam karşısına çıkar. Bu ihlal hem yasaktır hem de ağır kaza riskinin en kısa yoludur.',
    whyWrong: [
      'Birkaç metre bile ters gitmek karşılaşma riskini doğurur; mesafe istisnası yoktur.',
      'Yasak günün her saatinde geçerlidir.',
      'Dörtlü ikaz, kural dışı hareketi kurallı yapmaz.',
    ],
    objective: 'Tek yönlü yola ters girmenin mutlak yasak olduğunu bilmek.',
    tags: ['ters-yon', 'tek-yonlu-yol'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-533',
    subject: 'trafik',
    topic: 'ters-yon',
    difficulty: 'zor',
    stem: 'Ters yönde araç kullanmanın en önemli tehlikesi aşağıdakilerden hangisidir?',
    options: [
      'Yakıt tüketiminin artması',
      'Diğer sürücülerin o yönden araç beklememesi nedeniyle kafa kafaya çarpışma riskinin çok yüksek olması',
      'Lastiklerin daha hızlı aşınması',
      'Navigasyon cihazının yanlış yönlendirme yapması',
    ],
    answerIndex: 1,
    explanation:
      'Trafik güvenliği öngörülebilirliğe dayanır. Ters yönden gelen araç bu öngörüyü yıkar: karşı sürücünün tepki verecek zamanı ve kaçacak alanı yoktur, çarpışma iki aracın hız toplamıyla gerçekleşir.',
    whyWrong: [
      'Yakıt tüketimi bir güvenlik tehlikesi değildir.',
      'Lastik aşınması ile sürüş yönü arasında böyle bir ilişki kurulamaz.',
      'Navigasyon karışıklığı sonuçtur; asıl tehlike çarpışmadır.',
    ],
    objective: 'Ters yön sürüşünün neden ölümcül olduğunu kavramak.',
    tags: ['ters-yon', 'kafa-kafaya-carpisma', 'risk'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-534',
    subject: 'trafik',
    topic: 'emniyet-kemeri',
    difficulty: 'kolay',
    stem: 'Otomobilin arka koltuğunda oturan yetişkin yolcuların emniyet kemeri takması ile ilgili kural nedir?',
    options: [
      'İsteğe bağlıdır',
      'Yalnızca şehirlerarası yolculukta gerekir',
      'Arka koltukta da emniyet kemeri takmak zorunludur',
      'Sadece çocuklar için zorunludur',
    ],
    answerIndex: 2,
    explanation:
      'Kemer zorunluluğu araçtaki bütün koltuklar için geçerlidir. Kemersiz arka koltuk yolcusu çarpışmada öne savrularak hem kendisi hem öndekiler için ölümcül bir kütleye dönüşür.',
    whyWrong: [
      'Kural tercih değil zorunluluk olarak düzenlenmiştir.',
      'Şehir içi kısa yolculuklarda da kazalar ağır sonuç doğurur; ayrım yoktur.',
      'Zorunluluk yaş ayrımı yapmaz; yetişkinleri de kapsar.',
    ],
    objective: 'Kemer zorunluluğunun arka koltuğu da kapsadığını bilmek.',
    tags: ['emniyet-kemeri', 'arka-koltuk'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-535',
    subject: 'trafik',
    topic: 'emniyet-kemeri',
    difficulty: 'orta',
    stem: 'Aşağıdaki durumların hangisinde sürücü emniyet kemeri takma zorunluluğundan muaftır?',
    options: [
      'Şehir içinde kısa mesafe giderken',
      'Trafik çok yoğunken',
      'Yağmurlu havada',
      'Geri gitme veya park etme manevrası yaparken',
    ],
    answerIndex: 3,
    explanation:
      'Geri gitme ve park manevrası sırasında sürücünün gövdesini döndürerek arkayı görmesi gerekir; bu kısa süreli manevralar kemer muafiyeti tanınan istisnai hâllerdendir.',
    whyWrong: [
      'Mesafenin kısalığı muafiyet nedeni değildir; kazaların önemli bölümü kısa yolculuklarda olur.',
      'Trafik yoğunluğu kemer kuralını değiştirmez.',
      'Hava durumu ile kemer muafiyeti arasında ilişki yoktur.',
    ],
    objective: 'Kemer muafiyetinin manevra hâlleriyle sınırlı olduğunu bilmek.',
    tags: ['emniyet-kemeri', 'muafiyet', 'manevra'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-536',
    subject: 'trafik',
    topic: 'cocuk-guvenligi',
    difficulty: 'orta',
    stem: 'Otomobilde çocuk bağlama sistemi (çocuk koltuğu) hangi çocuklar için zorunludur?',
    options: [
      'Boyu 150 santimetrenin ve ağırlığı 36 kilogramın altındaki çocuklar için',
      'Yalnızca bebekler için',
      'On yaşından büyük tüm çocuklar için',
      'Yalnızca ön koltukta oturan çocuklar için',
    ],
    answerIndex: 0,
    explanation:
      'Standart emniyet kemeri yetişkin gövdesine göre tasarlanmıştır. Boyu 150 santimetreyi, ağırlığı 36 kilogramı aşmayan çocuklar, boylarına uygun çocuk bağlama sistemiyle taşınmak zorundadır.',
    whyWrong: [
      'Zorunluluk bebeklikle sınırlı değildir; ölçüler esas alınır.',
      'Yaş değil boy ve ağırlık ölçütü belirleyicidir.',
      'Kural koltuk konumuna değil, çocuğun ölçülerine bağlıdır.',
    ],
    objective: 'Çocuk koltuğu zorunluluğunun 150 cm/36 kg ölçütünü bilmek.',
    tags: ['cocuk-koltugu', 'cocuk-guvenligi', 'emniyet-kemeri'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-537',
    subject: 'trafik',
    topic: 'cocuk-guvenligi',
    difficulty: 'zor',
    stem: 'Arkaya (sürüş yönünün tersine) bakan bir çocuk koltuğu, otomobilin ön yolcu koltuğuna hangi şartla yerleştirilebilir?',
    options: [
      'Kemer sıkıca bağlanmışsa her zaman yerleştirilebilir',
      'O koltuğa ait hava yastığı devre dışı bırakılmışsa',
      'Çocuk beş yaşından büyükse',
      'Yolculuk kısa sürecekse',
    ],
    answerIndex: 1,
    explanation:
      'Açılan hava yastığı, arkaya bakan koltuktaki bebeğin başına çok yakın mesafeden büyük bir kuvvetle çarpar. Bu yüzden ön koltuğa ancak o koltuğun hava yastığı devre dışı bırakılmışsa arkaya bakan koltuk konulabilir.',
    whyWrong: [
      'Kemerin sıkılığı hava yastığı darbesini önlemez.',
      'Arkaya bakan koltuk zaten küçük bebekler içindir; yaş şartıyla sorun çözülmez.',
      'Sürenin kısalığı hava yastığı riskini ortadan kaldırmaz.',
    ],
    objective: 'Arkaya bakan koltuk ve hava yastığı ilişkisini bilmek.',
    tags: ['cocuk-koltugu', 'hava-yastigi', 'bebek-guvenligi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-538',
    subject: 'trafik',
    topic: 'cep-telefonu',
    difficulty: 'kolay',
    stem: 'Seyir hâlindeki sürücünün cep telefonunu eliyle tutarak kullanması ile ilgili kural nedir?',
    options: [
      'Kısa konuşmalarda serbesttir',
      'Şehir dışında serbesttir',
      'Yalnızca düşük hızda serbesttir',
      'Yasaktır; ancak eller serbest (handsfree) sistemle görüşme yapılabilir',
    ],
    answerIndex: 3,
    explanation:
      'Araç kullanırken telefonu elde tutmak yasaktır; elin direksiyondan, gözün ve dikkatin yoldan ayrılmasına yol açar. Yalnızca eller serbest donanımla görüşme yapılabilir.',
    whyWrong: [
      'Konuşmanın kısalığı dalgınlık riskini ortadan kaldırmaz.',
      'Yasak şehir içi-dışı ayrımı yapmaz.',
      'Hız düşük olsa da tepki gecikmesi kazaya yeter.',
    ],
    objective: 'Elde telefon yasağını ve handsfree istisnasını bilmek.',
    tags: ['cep-telefonu', 'dikkat-daginikligi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-539',
    subject: 'trafik',
    topic: 'cep-telefonu',
    difficulty: 'orta',
    stem: 'Sürücüler için cep telefonu yasağının kapsamı ile ilgili hangisi doğrudur?',
    options: [
      'Yasak yalnızca telefonla konuşmayı kapsar',
      'Telefonu hoparlöre almak da yasaktır',
      'Telefonu elde tutarak yapılan mesajlaşma ve benzeri her kullanım da yasağın kapsamındadır',
      'Navigasyon amaçlı elde kullanım serbesttir',
    ],
    answerIndex: 2,
    explanation:
      'Yasağın özü, telefonun elde tutularak kullanılmasıdır. Mesaj yazmak, sosyal medyaya bakmak gibi kullanımlar gözü yoldan daha uzun süre ayırdığı için konuşmadan bile tehlikelidir.',
    whyWrong: [
      'Yasak konuşmayla sınırlı değildir; elle her kullanımı kapsar.',
      'Eller serbest kullanım (hoparlör/kulaklık sistemi) yasağın istisnasıdır.',
      'Navigasyon da elde tutularak kullanılıyorsa aynı yasağa girer.',
    ],
    objective: 'Telefon yasağının elle her kullanımı kapsadığını bilmek.',
    tags: ['cep-telefonu', 'mesajlasma', 'dikkat-daginikligi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-540',
    subject: 'trafik',
    topic: 'isik-ihlali-yaptirimi',
    difficulty: 'zor',
    stem: 'Son ihlal tarihinden geriye doğru bir yıl içinde üç kez kırmızı ışık ihlali yapan sürücüye uygulanan yaptırım nedir?',
    options: [
      'Sürücü belgesi 30 gün süreyle geri alınır',
      'Yalnızca sözlü uyarı yapılır',
      'Aracı satışa çıkarılır',
      'Belgesi ömür boyu iptal edilir',
    ],
    answerIndex: 0,
    explanation:
      'Kırmızı ışık ihlali her seferinde para cezası gerektirir; bir yıl içinde üçüncü ihlalde ayrıca sürücü belgesi 30 gün süreyle geri alınır. Amaç, tekrarlayan riskli davranışı caydırmaktır.',
    whyWrong: [
      'Sözlü uyarı diye bir yaptırım kademesi yoktur; ihlal her seferinde cezalıdır.',
      'Aracın satılması gibi bir yaptırım mevzuatta yer almaz.',
      'Ömür boyu iptal bu ihlal için öngörülen yaptırım değildir.',
    ],
    objective: 'Tekrarlanan kırmızı ışık ihlalinin belge yaptırımını bilmek.',
    tags: ['kirmizi-isik', 'belge-geri-alma', 'yaptirim'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-541',
    subject: 'trafik',
    topic: 'trafikten-men',
    difficulty: 'orta',
    stem: 'Tescili yapılmadan ve tescil plakası takılmadan trafiğe çıkarılan bir araç için hangi işlem uygulanır?',
    options: [
      'Sadece sözlü uyarı yapılır',
      'Araç trafikten men edilir',
      'Sürücüye ödül puanı verilir',
      'Herhangi bir işlem yapılmaz',
    ],
    answerIndex: 1,
    explanation:
      'Plakasız ve tescilsiz araç trafikte kimliksizdir; sorumluluğu izlenemez. Bu araçlar, eksiklik giderilinceye kadar trafikten men edilir ve sürücüsüne ceza uygulanır.',
    whyWrong: [
      'Tescil eksikliği uyarıyla geçiştirilecek bir kusur değildir.',
      'Ödül puanı, kurallara uyan sürücülere ilişkin bir kavramdır; ihlale uygulanmaz.',
      'İşlemsiz bırakmak, kimliksiz aracın yola devamı demektir; mümkün değildir.',
    ],
    objective: 'Plakasız aracın trafikten men edileceğini bilmek.',
    tags: ['trafikten-men', 'tescil', 'plaka'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-542',
    subject: 'trafik',
    topic: 'trafikten-men',
    difficulty: 'zor',
    stem: '"Aracın trafikten men edilmesi" ifadesi ne anlama gelir?',
    options: [
      'Aracın devlet adına satılması',
      'Sürücünün belgesine el konulması',
      'Eksikliği veya kural dışılığı giderilinceye kadar aracın trafiğe çıkışının engellenmesi',
      'Aracın hurdaya ayrılması',
    ],
    answerIndex: 2,
    explanation:
      'Trafikten men, araca yönelik geçici bir tedbirdir: sigortasızlık, tescilsizlik gibi eksiklik giderilene kadar araç trafiğe çıkarılamaz ve genellikle uygun bir alanda muhafaza altına alınır.',
    whyWrong: [
      'Men tedbiri mülkiyeti etkilemez; satış söz konusu değildir.',
      'Belge geri alma sürücüye, men ise araca uygulanan ayrı yaptırımlardır.',
      'Hurdaya ayırma bambaşka ve kalıcı bir işlemdir.',
    ],
    objective: 'Trafikten men kavramının geçici araç tedbiri olduğunu kavramak.',
    tags: ['trafikten-men', 'tanimlar', 'yaptirim'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-543',
    subject: 'trafik',
    topic: 'zorunlu-gerecler',
    difficulty: 'kolay',
    stem: 'Aşağıdaki gereç gruplarından hangisinin otomobilde bulundurulması zorunludur?',
    options: [
      'Üçgen reflektör, ilk yardım çantası ve yangın söndürme cihazı',
      'Kar zinciri, çekme halatı ve el feneri',
      'Takoz, yedek yakıt bidonu ve pusula',
      'Buz kazıyıcı, şemsiye ve harita',
    ],
    answerIndex: 0,
    explanation:
      'Otomobillerde arıza ve acil durumlar için üçgen reflektörler, ilk yardım çantası ve yangın söndürme cihazı bulundurulmak zorundadır; denetimlerde bu gereçler kontrol edilir.',
    whyWrong: [
      'Kar zinciri ve halat yararlıdır ama otomobil için genel zorunlu donanım listesinde değildir.',
      'Takoz, kamyon ve otobüs gibi büyük araçların zorunlu gerecidir.',
      'Buz kazıyıcı ve benzeri gereçler tamamen isteğe bağlıdır.',
    ],
    objective: 'Otomobilin zorunlu gereç üçlüsünü bilmek.',
    tags: ['zorunlu-gerecler', 'reflektor', 'ilk-yardim-cantasi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-544',
    subject: 'trafik',
    topic: 'zorunlu-gerecler',
    difficulty: 'orta',
    stem: 'Aşağıdaki gereçlerden hangisi otomobiller için zorunlu donanım değildir?',
    options: ['Yangın söndürme cihazı', 'İlk yardım çantası', 'Üçgen reflektör', 'Takoz'],
    answerIndex: 3,
    explanation:
      'Takoz, park hâlinde kaymayı önlemek için kamyon, otobüs, römorklu araçlar gibi büyük ve ağır taşıtlarda bulundurulması zorunlu gereçtir; otomobiller için zorunlu değildir.',
    whyWrong: [
      'Yangın söndürme cihazı otomobilde zorunludur.',
      'İlk yardım çantası da zorunlu gereçler arasındadır.',
      'Üçgen reflektör arıza işaretlemesi için zorunludur.',
    ],
    objective: 'Takozun otomobil için zorunlu olmadığını ayırt etmek.',
    tags: ['zorunlu-gerecler', 'takoz'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-545',
    subject: 'trafik',
    topic: 'cevre-emisyon',
    difficulty: 'kolay',
    stem: 'Araçlarda egzoz gazı emisyon ölçümü yaptırılmasının temel amacı nedir?',
    options: [
      'Motor gücünü artırmak',
      'Egzozdan çıkan kirletici gazların sınır değerlere uygunluğunu denetleyerek hava kirliliğini önlemek',
      'Yakıt deposunun hacmini ölçmek',
      'Aracın ikinci el satış değerini belirlemek',
    ],
    answerIndex: 1,
    explanation:
      'Emisyon ölçümü, aracın egzozundan atılan zararlı gazların yasal sınırlar içinde kalıp kalmadığını denetler; sınırı aşan araçların bakımı sağlanarak hava kalitesi korunur.',
    whyWrong: [
      'Ölçümün amacı performans artışı değil, kirletici denetimi yapmaktır.',
      'Depo hacmiyle emisyonun ilgisi yoktur.',
      'Satış değeri belirleme, ekspertiz işlemlerinin konusudur.',
    ],
    objective: 'Egzoz emisyon ölçümünün çevresel amacını bilmek.',
    tags: ['egzoz-emisyonu', 'cevre', 'hava-kirliligi'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-546',
    subject: 'trafik',
    topic: 'lastik-kurallari',
    difficulty: 'orta',
    stem: 'Otomobil lastiklerinde yasal olarak izin verilen en az diş derinliği kaç milimetredir?',
    options: ['0,6', '3', '1,6', '5'],
    answerIndex: 2,
    explanation:
      'Otomobil lastiklerinde diş derinliği 1,6 milimetrenin altına inemez. Dişleri aşınan lastik ıslak zeminde suyu tahliye edemez; fren mesafesi uzar ve kayma riski artar.',
    whyWrong: [
      '0,6 milimetre, tutunması bitmiş tehlikeli bir lastiği ifade eder.',
      '3 ve 5 milimetre güvenlik açısından iyi değerlerdir ancak yasal alt sınır değildir.',
    ],
    objective: 'Lastikte 1,6 milimetre asgari diş derinliğini bilmek.',
    tags: ['lastik', 'dis-derinligi', 'arac-guvenligi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-547',
    subject: 'trafik',
    topic: 'yaya-yolu-banket',
    difficulty: 'kolay',
    stem: 'Trafikte "banket" ne anlama gelir?',
    options: [
      'Taşıt yolu kenarı ile yol sınırı arasında kalan; yayaların yararlandığı, zorunlu hâllerde araçların da kullanabildiği bölüm',
      'Yolun ortasındaki yükseltilmiş ada',
      'Kavşaklardaki dönüş şeridi',
      'Otoyoldaki ücret toplama alanı',
    ],
    answerIndex: 0,
    explanation:
      'Banket, taşıt yolunun hemen kenarındaki bölümdür; yaya yolu olmayan yerlerde yayalar ve hayvanlar buradan yararlanır, araçlar ancak zorunlu hâllerde kullanır.',
    whyWrong: [
      'Ortadaki yükseltilmiş alan "ada" olarak adlandırılır.',
      'Dönüş şeritleri taşıt yolunun işaretlenmiş bölümleridir.',
      'Ücret toplama alanları gişe bölgeleridir; banketle ilgisi yoktur.',
    ],
    objective: 'Banket kavramını doğru tanımlamak.',
    tags: ['banket', 'tanimlar', 'yaya-yolu'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-548',
    subject: 'trafik',
    topic: 'yaya-yolu-banket',
    difficulty: 'orta',
    stem: 'Yaya yolu ve banket bulunmayan, yerleşim yeri dışındaki bir karayolunda yürümek zorunda kalan yaya hangi tarafı kullanmalıdır?',
    options: [
      'Gidiş yönüne göre sağ tarafı',
      'Gelen araçları görebileceği şekilde gidiş yönüne göre sol tarafı',
      'Yolun ortasını',
      'Dilediği tarafı',
    ],
    answerIndex: 1,
    explanation:
      'Yaya, taşıt yolunda yürümek zorunda kalırsa gidiş yönüne göre sol kenarı kullanır; böylece kendisine en yakın şeritten yaklaşan araçları görür ve gerektiğinde kenara çekilebilir.',
    whyWrong: [
      'Sağ tarafta yürüyen yaya, arkasından yaklaşan araçları göremez.',
      'Yolun ortası her iki yönün de çarpışma hattıdır.',
      'Taraf seçimi keyfe bağlı değildir; görme esasına dayanır.',
    ],
    objective: 'Yayanın taşıt yolunda sol kenarı kullanma kuralını bilmek.',
    tags: ['yaya-kurallari', 'banket', 'gorus'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-549',
    subject: 'trafik',
    topic: 'gabari',
    difficulty: 'orta',
    stem: 'Trafik mevzuatındaki "gabari" kavramı neyi ifade eder?',
    options: [
      'Aracın yakıt tüketim değerini',
      'Yolun asfalt kalınlığını',
      'Motorun silindir hacmini',
      'Araçların yüklü veya yüksüz olarak güvenli seyri için belirlenen uzunluk, genişlik ve yükseklik ölçülerini',
    ],
    answerIndex: 3,
    explanation:
      'Gabari, aracın yüklü ya da yüksüz olarak karayolunda güvenle seyredebilmesi için uyması gereken boyut sınırlarıdır; köprü ve tünel girişlerindeki yükseklik levhaları bu kavrama dayanır.',
    whyWrong: [
      'Yakıt tüketimi ekonomik bir ölçüttür, boyutla ilgisizdir.',
      'Asfalt kalınlığı yol yapım tekniğinin konusudur.',
      'Silindir hacmi motorun büyüklüğünü anlatır, aracın dış ölçülerini değil.',
    ],
    objective: 'Gabari kavramını boyut sınırı olarak tanımlamak.',
    tags: ['gabari', 'tanimlar', 'boyut-siniri'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-550',
    subject: 'trafik',
    topic: 'agir-tasit-serit',
    difficulty: 'orta',
    stem: 'Aynı yönde üç veya daha fazla şeridi bulunan karayollarında kamyon, otobüs gibi ağır taşıtların şerit kullanımı nasıl olmalıdır?',
    options: [
      'En sol şeridi sürekli kullanabilirler',
      'Diledikleri şeridi seçebilirler',
      'En sol şeride giremezler; seyir ve geçişlerini diğer şeritlerden yaparlar',
      'Yalnızca orta şeridi kullanmak zorundadırlar',
    ],
    answerIndex: 2,
    explanation:
      'Ağır taşıtlar yavaş hızlanır ve uzun geçiş mesafesine ihtiyaç duyar. Üç ve daha fazla şeritli yollarda en sol şerit onlara kapalıdır; geçişlerini de diğer şeritleri kullanarak yaparlar.',
    whyWrong: [
      'En sol şeridin sürekli kullanımı hızlı akımı kilitler; yasaktır.',
      'Şerit seçimi araç türüne göre kurala bağlanmıştır, keyfe değil.',
      'Orta şerit zorunluluğu yoktur; en sağ şerit esas, orta şerit geçiş içindir.',
    ],
    objective: 'Ağır taşıtların en sol şerit yasağını bilmek.',
    tags: ['agir-tasit', 'serit-kullanimi', 'sol-serit'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-551',
    subject: 'trafik',
    topic: 'geri-gitme',
    difficulty: 'orta',
    stem: 'Tek yönlü yollarda geri gitmek ile ilgili kural nedir?',
    options: [
      'Duraklama ve park etme manevrası dışında yasaktır',
      'Her zaman serbesttir',
      'Yalnızca gündüz serbesttir',
      'Dörtlü ikaz yakılarak her durumda yapılabilir',
    ],
    answerIndex: 0,
    explanation:
      'Tek yönlü yolda geri giden araç, akışa ters hareket eden araç demektir. Bu nedenle geri gitmek yalnızca duraklama ve park manevralarının gerektirdiği kısa hareketlerle sınırlıdır.',
    whyWrong: [
      'Serbestlik yoktur; geri gitmek akışın mantığına aykırıdır.',
      'Gündüz-gece ayrımı kuralda yer almaz.',
      'Dörtlü ikaz kural dışı hareketi meşrulaştırmaz.',
    ],
    objective: 'Tek yönlü yolda geri gitme yasağını ve istisnasını bilmek.',
    tags: ['geri-gitme', 'tek-yonlu-yol', 'manevra'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-552',
    subject: 'trafik',
    topic: 'dar-yol-gecis',
    difficulty: 'zor',
    stem: 'Eğimli ve dar bir yolda, çıkan araç ile inen araç karşılaştığında geçiş kolaylığını hangisi sağlamalıdır?',
    options: [
      'Çıkan araç geri geri inerek yol vermelidir',
      'İnen araç, çıkan araca yol vermelidir; gerekirse uygun bir yere çekilir veya geri gider',
      'Hangisinin aracı büyükse o yol vermelidir',
      'İki araç aynı anda geçmeyi denemelidir',
    ],
    answerIndex: 1,
    explanation:
      'Yokuşta durup yeniden kalkmak, çıkan araç için kayma ve stop riski taşır. Bu yüzden dar ve eğimli kesimlerde inen araç yol verir; gerekiyorsa uygun bir cebe çekilir ya da güvenle geri gider.',
    whyWrong: [
      'Çıkan aracın geri inmesi, eğimde kontrol kaybına en açık manevradır.',
      'Öncelik araç büyüklüğüne göre değil, eğim yönüne göre belirlenir.',
      'Dar kesimde aynı anda geçiş sıkışma ve çarpışma doğurur.',
    ],
    objective: 'Eğimli dar yolda çıkan araca öncelik kuralını bilmek.',
    tags: ['dar-yol', 'egim', 'gecis-kolayligi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-553',
    subject: 'trafik',
    topic: 'konvoy',
    difficulty: 'zor',
    stem: 'Yerleşim yeri dışında konvoy hâlinde seyreden araçların arasında bırakılması gereken açıklık için kural nedir?',
    options: [
      'Araçlar tampon tampona ilerleyebilir',
      'Açıklık yalnızca gece bırakılır',
      'En fazla bir araç boyu mesafe bırakılır',
      'Kendilerini geçmek isteyen araçların güvenle girebileceği kadar açıklık bırakılmalıdır',
    ],
    answerIndex: 3,
    explanation:
      'Konvoydaki araçlar arasında, geçiş yapan bir aracın araya güvenle girebileceği kadar boşluk bırakılır; aksi hâlde sollamaya başlayan sürücü karşı şeritte sığınacak yer bulamaz.',
    whyWrong: [
      'Tampon tampona seyir hem takip mesafesi ihlali hem geçiş engelidir.',
      'Kural gündüz de aynen geçerlidir.',
      'Sınır "en fazla" değil "en az" mantığıyla, geçen aracın sığacağı kadar olmalıdır.',
    ],
    objective: 'Konvoyda araya girilebilir boşluk bırakma kuralını bilmek.',
    tags: ['konvoy', 'takip-mesafesi', 'sollama'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-554',
    subject: 'trafik',
    topic: 'serit-degistirme-yasagi',
    difficulty: 'zor',
    stem: 'Kavşaklara yaklaşırken şerit değiştirme yasağı hangi mesafeler içinde uygulanır?',
    options: [
      'Yerleşim yeri içinde 30, yerleşim yeri dışında 150 metre',
      'Yerleşim yeri içinde 100, dışında 300 metre',
      'Her yerde 500 metre',
      'Yalnızca kavşağın içinde',
    ],
    answerIndex: 0,
    explanation:
      'Kavşağa yaklaşan sürücü yönünü önceden seçmiş olmalıdır: yerleşim yeri içinde son 30, dışında son 150 metrede şerit değiştirmek yasaktır. Bu, kavşak ağzındaki ani makas manevralarını önler.',
    whyWrong: [
      '100/300 metre mevzuattaki değerler değildir.',
      '500 metrelik tek tip yasak yoktur; mesafe yerleşim durumuna göre değişir.',
      'Yasak kavşağın içiyle sınırlı değildir; yaklaşım mesafesini de kapsar.',
    ],
    objective: 'Kavşak yaklaşımındaki 30/150 metre şerit yasağını bilmek.',
    tags: ['serit-degistirme', 'kavsak', 'mesafe-kurali'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-555',
    subject: 'trafik',
    topic: 'yaya-kurallari',
    difficulty: 'orta',
    stem: 'Yakın çevresinde yaya geçidi veya kavşak bulunmayan bir yerde karşıya geçmek zorunda kalan yaya nasıl davranmalıdır?',
    options: [
      'Taşıt yolu boyunca çapraz (verev) şekilde yürüyerek geçmelidir',
      'Telefonuna bakarak hızla karşıya koşmalıdır',
      'Her iki yönden gelen trafiği kontrol ettikten sonra taşıt yolunu en kısa doğrultuda (dik olarak) geçmelidir',
      'Araç trafiğini elini kaldırarak durdurup ağır adımlarla geçmelidir',
    ],
    answerIndex: 2,
    explanation:
      'Geçit yoksa amaç, taşıt yolunda geçirilen süreyi en aza indirmektir: yaya iki yönü de kontrol eder ve yolu dik doğrultuda, oyalanmadan geçer.',
    whyWrong: [
      'Çapraz geçiş, yolda kalınan süreyi ve riski uzatır.',
      'Telefona bakmak, geçişin en kritik anında görüşü yok eder.',
      'Yayanın trafiği durdurma yetkisi yoktur; güvenli boşluğu beklemesi gerekir.',
    ],
    objective: 'Geçit olmayan yerde dik ve hızlı geçiş kuralını bilmek.',
    tags: ['yaya-kurallari', 'karsiya-gecis'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-556',
    subject: 'trafik',
    topic: 'isaret-koruma',
    difficulty: 'orta',
    stem: 'Trafik işaret levhalarını sökmek, yerini değiştirmek veya üzerini yazı ve afişle kapatmak nasıl değerlendirilir?',
    options: [
      'Belediyeden izin alınırsa serbesttir',
      'Yasaktır; trafik güvenliğini bozan bu davranışlar cezai sorumluluk ve zararın tazminini gerektirir',
      'Yalnızca büyükşehirlerde yasaktır',
      'Reklam amaçlıysa serbesttir',
    ],
    answerIndex: 1,
    explanation:
      'İşaret levhaları trafik düzeninin dilidir; okunamaz hâle getirilen bir levha kazaya davetiye çıkarır. Levhalara müdahale yasaktır, verilen zarar ayrıca tazmin ettirilir.',
    whyWrong: [
      'Levhalar üzerinde tasarruf yetkisi yalnızca yetkili kuruluşlardadır; keyfî izin verilmez.',
      'Yasak ülke genelinde tüm yollarda geçerlidir.',
      'Reklam amacı, güvenlik donanımını kapatma hakkı vermez.',
    ],
    objective: 'Trafik işaretlerinin dokunulmazlığını kavramak.',
    tags: ['isaret-levhasi', 'sorumluluk'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-557',
    subject: 'trafik',
    topic: 'kapi-guvenligi',
    difficulty: 'kolay',
    stem: 'Yol kenarında duraklamış bir araçtaki sürücü veya yolcu, taşıt yolu tarafındaki kapıyı açmadan önce ne yapmalıdır?',
    options: [
      'Kapıyı hızla ve sonuna kadar açmalıdır',
      'Önce kornaya basmalıdır',
      'Dörtlü ikazı yakıp beklemeden inmelidir',
      'Arkadan araç, motosiklet veya bisiklet gelmediğini kontrol etmeli; kapıyı trafiği tehlikeye düşürmeyecek şekilde açmalıdır',
    ],
    answerIndex: 3,
    explanation:
      'Aniden açılan kapı, özellikle bisikletli ve motosikletliler için ciddi bir engeldir. Kapılar ancak ayna ve omuz kontrolünden sonra, trafiği tehlikeye düşürmeyecek şekilde açılabilir.',
    whyWrong: [
      'Kontrolsüz ve ani açılan kapı çarpışmanın kendisidir.',
      'Korna, arkadan gelenin çarpmasını engellemez; kontrol gerekir.',
      'Dörtlü ikaz kontrol yükümlülüğünü kaldırmaz.',
    ],
    objective: 'Kapı açmadan önce arka kontrolü alışkanlığını kazanmak.',
    tags: ['kapi-acma', 'bisiklet', 'duraklama'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-558',
    subject: 'trafik',
    topic: 'yolcu-indirme-bindirme',
    difficulty: 'kolay',
    stem: 'Duraklayan bir araçtan yolcuların iniş ve binişleri kural olarak hangi taraftan yapılmalıdır?',
    options: [
      'Aracın sağ tarafından, kaldırım veya banket yönünden',
      'Aracın sol tarafından, trafik yönünden',
      'Aracın ön tarafından',
      'Hangi kapı yakınsa o taraftan',
    ],
    answerIndex: 0,
    explanation:
      'İniş ve binişler, akan trafiğe uzak olan sağ taraftan yani kaldırım veya banket yönünden yapılır; böylece yolcu taşıt trafiğinin içine adım atmamış olur.',
    whyWrong: [
      'Sol taraftan inen yolcu doğrudan akan trafiğin içine çıkar.',
      'Aracın önü, sürücülerin görmediği kör bölgeye açılır.',
      'Yakınlık değil güvenli taraf esastır.',
    ],
    objective: 'İniş-binişin güvenli (sağ) taraftan yapılacağını bilmek.',
    tags: ['yolcu-indirme', 'duraklama', 'yaya-guvenligi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-559',
    subject: 'trafik',
    topic: 'cevre-temizlik',
    difficulty: 'kolay',
    stem: 'Seyir hâlindeki araçtan dışarıya çöp, izmarit gibi şeyler atmak nasıl değerlendirilir?',
    options: [
      'Küçük atıklar için serbesttir',
      'Yalnızca orman bölgelerinde yasaktır',
      'Yasaktır; çevre kirliliğine ve yangın gibi tehlikelere yol açar, cezai yaptırımı vardır',
      'Doğada çözünen atıklar için serbesttir',
    ],
    answerIndex: 2,
    explanation:
      'Araçtan atılan her atık çevreyi kirletir; yanan izmarit yol kenarındaki kuru otları tutuşturabilir, savrulan cisimler arkadaki sürücüleri şaşırtabilir. Bu davranış yasaktır ve cezalandırılır.',
    whyWrong: [
      'Atığın küçüklüğü kirletme ve tehlike niteliğini değiştirmez.',
      'Yasak yalnız ormanla sınırlı değildir; tüm karayollarında geçerlidir.',
      'Çözünme süresi ne olursa olsun atık yola ve doğaya bırakılamaz.',
    ],
    objective: 'Araçtan atık atmanın yasak olduğunu bilmek.',
    tags: ['cevre', 'cop-atma', 'yangin-riski'],
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-560',
    subject: 'trafik',
    topic: 'gecis-yolu-cikis',
    difficulty: 'zor',
    stem: 'Otopark veya garaj çıkışı gibi bir geçiş yolundan karayoluna çıkacak sürücü, geçiş hakkını nasıl kullanmalıdır?',
    options: [
      'Karayolundaki araçlar ona yol vermek zorundadır',
      'Karayolunda seyreden araçlara ve yayalara yol vermek zorundadır',
      'Önce davranan öncelik kazanır',
      'Korna çalarak çıkışını haber vermesi yeterlidir',
    ],
    answerIndex: 1,
    explanation:
      'Geçiş yolundan çıkan araç, akan trafiğe sonradan katılan taraftır: kaldırımdaki yayalara ve karayolunda seyreden bütün araçlara yol vermeden çıkış yapamaz.',
    whyWrong: [
      'Akan trafiğin, mülkten çıkan araca yol verme yükümlülüğü yoktur.',
      'Öncelik hız veya çeviklikle değil, kuralla belirlenir.',
      'Korna bilgilendirme aracıdır; geçiş hakkı doğurmaz.',
    ],
    objective: 'Geçiş yolundan çıkışta yol verme yükümlülüğünü bilmek.',
    tags: ['gecis-yolu', 'gecis-hakki', 'yaya-onceligi'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
];
