/**
 * ÖZGÜN direksiyon (uygulama) soruları (Sprint 3 — Sürüş Akademisi).
 * Kaynak = MTSK direksiyon eğitimi + MEB direksiyon sınavı uygulaması; KENDİ İFADEMİZLE. review: 'draft'.
 */
import type { Question } from '@ea/content-schema';

const SRC = 'MTSK direksiyon eğitimi ve MEB direksiyon sınavı uygulaması (özgün ifade)';

export const PRATIK_QUESTIONS: Question[] = [
  {
    id: 'pratik-101',
    subject: 'pratik',
    topic: 'arac-kontrol',
    difficulty: 'kolay',
    stem: 'Araca bindikten sonra motoru çalıştırmadan önce yapılması gereken hazırlık sıralaması hangisidir?',
    options: [
      'Önce vitesi tak, sonra kemeri bağla',
      'Koltuk ve aynaları ayarla, kemeri bağla, sonra kontrolleri yap',
      'Kornaya bas, aynalara bakma, motoru çalıştır',
      'Doğrudan gaza bas ve harekete geç',
    ],
    answerIndex: 1,
    explanation:
      'Sürüşe başlamadan önce oturuş mesafesi ve aynalar sürücüye göre ayarlanır, emniyet kemeri bağlanır; böylece pedallara ve göstergelere rahat hâkim olunur. Hazırlık tamamlanmadan hareket güvenli değildir.',
    whyWrong: [
      'Vitesi kemerden önce takmak, hazırlık tamamlanmadan araca kumanda etmek demektir.',
      'Aynalara bakmadan hareket etmek çevredeki tehlikeleri görmemeye yol açar.',
    ],
    objective: 'Sürüş öncesi koltuk-ayna-kemer hazırlık sıralamasını uygulayabilmek.',
    tags: ['arac-kontrol', 'kemer', 'ayna-ayari'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-102',
    subject: 'pratik',
    topic: 'motor-calistirma',
    difficulty: 'kolay',
    stem: 'Manuel vitesli bir aracı çalıştırırken vites kolu ve debriyaj için doğru olan nedir?',
    options: [
      'Vites boşta (nötr) ve debriyaj basılı iken çalıştır',
      'Vites 1. konumdayken debriyaja basmadan çalıştır',
      'Vites geri konumdayken çalıştır',
      'Debriyaja hiç basmadan, vites 2. konumdayken çalıştır',
    ],
    answerIndex: 0,
    explanation:
      'Motor çalıştırılırken vitesin boşta olması ve debriyaja basılması, aracın istem dışı ileri sıçramasını önler. Bu, çalıştırma anındaki en güvenli konumdur.',
    whyWrong: [
      'Vites takılıyken debriyaja basmadan çalıştırmak aracı öne fırlatabilir.',
      'Geri veya 2. vitesle çalıştırma da kontrolsüz hareket riski taşır.',
    ],
    objective: 'Motor çalıştırma anında güvenli vites ve debriyaj konumunu bilmek.',
    tags: ['motor-calistirma', 'debriyaj', 'vites-bosta'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-103',
    subject: 'pratik',
    topic: 'hareket',
    difficulty: 'orta',
    stem: 'Duran bir araçla trafiğe katılmak için harekete geçmeden önce hangi kontrol dizisi doğrudur?',
    options: [
      'Sadece dikiz aynasına bak ve hemen çık',
      'Önce hareket et, sonra sinyal ver',
      'Kornaya basıp doğrudan şeride gir',
      'Aynaları kontrol et, sinyal ver, kör noktayı omuz üstünden gör, sonra hareket et',
    ],
    answerIndex: 3,
    explanation:
      'Trafiğe katılmadan önce aynalardan çevre görülür, niyet sinyalle bildirilir ve aynada görünmeyen kör nokta omuz üstünden kontrol edilir. Bu sıra çarpışma riskini en aza indirir.',
    whyWrong: [
      'Yalnız dikiz aynasına bakmak kör noktadaki aracı gözden kaçırır.',
      'Sinyali hareketten sonra vermek, diğer sürücüleri uyaramaz.',
    ],
    objective: 'Harekete geçerken ayna-sinyal-kör nokta kontrol dizisini uygulamak.',
    tags: ['hareket', 'kor-nokta', 'sinyal'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-104',
    subject: 'pratik',
    topic: 'rampa',
    difficulty: 'zor',
    stem: 'Yokuş yukarı (rampa) bir yolda durduktan sonra geriye kaymadan kalkış yapmanın temel mantığı nedir?',
    options: [
      'El frenini baştan indir, sadece gaza yüklen',
      'El freni çekiliyken debriyajı kavrama noktasına getir, gazı ver ve aracın yüklendiğini hissedince el frenini yavaşça bırak',
      'Debriyajı tamamen bırakıp gaza sonra bas',
      'Fren pedalına basılı tutup gazsız kalkış yap',
    ],
    answerIndex: 1,
    explanation:
      'Rampada kalkışta el freni aracı tutarken debriyaj kavrama noktasına getirilir ve gaz verilir; araç öne yüklenmeye başladığı an el freni bırakılırsa geriye kayma önlenir. Denge, debriyaj ile gazın uyumundadır.',
    whyWrong: [
      'El frenini baştan indirmek araç öne yüklenmeden geriye kaymasına neden olur.',
      'Debriyajı birden bırakmak motoru boğar (stop ettirir).',
    ],
    objective: 'Rampada geriye kaymadan kalkış için el freni-debriyaj-gaz dengesini kurmak.',
    tags: ['rampa', 'debriyaj', 'el-freni'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-105',
    subject: 'pratik',
    topic: 'debriyaj',
    difficulty: 'orta',
    stem: 'Debriyajın "yarım debriyaj" (kavrama noktası) durumu neyi ifade eder?',
    options: [
      'Pedalın tabana kadar basılı olması',
      'Balataların motorun gücünü tekere aktarmaya yeni başladığı, aracın hafifçe ileri gitmeye eğilim gösterdiği geçiş noktası',
      'Debriyajın tamamen serbest bırakılmış hâli',
      'Sadece fren yaparken kullanılan konum',
    ],
    answerIndex: 1,
    explanation:
      'Kavrama noktası, debriyaj yavaşça bırakılırken motor gücünün tekerlere geçmeye başladığı andır; araç hafifçe titrer ve ileri gitmeye eğilir. Yumuşak kalkış ve dar manevralar bu nokta hissedilerek yapılır.',
    whyWrong: [
      'Pedal tabana basılıyken güç aktarılmaz, bu kavrama değil ayırma konumudur.',
      'Tamamen serbest debriyajda kavrama zaten tamamlanmıştır.',
    ],
    objective: 'Debriyaj kavrama (yarım debriyaj) noktasını tanımak ve hissetmek.',
    tags: ['debriyaj', 'kavrama-noktasi', 'kalkis'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-106',
    subject: 'pratik',
    topic: 'geri-park',
    difficulty: 'orta',
    stem: 'Geri geri park ederken (dik/geri park) aynaların kullanımıyla ilgili en doğru davranış hangisidir?',
    options: [
      'Sadece ön cama bakarak geri gitmek',
      'Aynalara hiç bakmadan hızlıca geri gitmek',
      'Yalnız sağ yan aynaya bakmak yeterlidir',
      'Her iki yan aynayı ve dikiz aynasını sık sık kontrol edip gerektiğinde omuz üstünden arkayı görmek',
    ],
    answerIndex: 3,
    explanation:
      'Geri parkta araç arkası, kaldırım ve yaya trafiği ancak yan aynalar, dikiz aynası ve omuz üstü bakış birlikte kullanılarak güvenle görülür. Tek bir aynaya güvenmek kör noktaları gizler.',
    whyWrong: [
      'Yalnız ön cama bakmak aracın gittiği arka tarafı görmez.',
      'Tek yan aynaya bakmak diğer taraftaki engelleri gözden kaçırır.',
    ],
    objective: 'Geri park sırasında çoklu ayna ve omuz üstü kontrolü uygulamak.',
    tags: ['geri-park', 'ayna-kontrol', 'manevra'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-107',
    subject: 'pratik',
    topic: 'paralel-park',
    difficulty: 'zor',
    stem: 'İki araç arasına paralel park yaparken doğru adım sıralaması aşağıdakilerden hangisidir?',
    options: [
      'Öndeki araçla hizalan, geri gelirken direksiyonu boşluğa doğru kır, araç açı alınca direksiyonu ters yöne çevirip düzelt',
      'Doğrudan boşluğa ileri girerek park et',
      'Direksiyonu hiç çevirmeden düz geri git',
      'Boşluğa girmeden önce sinyal vermeye gerek yoktur',
    ],
    answerIndex: 0,
    explanation:
      'Paralel parkta önce park boşluğunun önündeki araçla hizalanılır, geri gelirken direksiyon boşluğa doğru kırılır; araç yeterli açıyı alınca direksiyon ters yöne çevrilerek araç kaldırıma paralel oturtulur. Aynalar her adımda kontrol edilir.',
    whyWrong: [
      'Dar bir boşluğa ileri girerek paralel park tamamlanamaz.',
      'Direksiyon hiç çevrilmezse araç boşluğa yerleşmez.',
      'Manevra öncesi sinyal, arkadan geleni uyarmak için gereklidir.',
    ],
    objective: 'Paralel park manevrasının adım sırasını ve direksiyon yönünü uygulamak.',
    tags: ['paralel-park', 'manevra', 'direksiyon'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-108',
    subject: 'pratik',
    topic: 'donel-kavsak',
    difficulty: 'orta',
    stem: 'Dönel kavşağa (göbekli kavşak) yaklaşan sürücü geçiş hakkı bakımından ne yapmalıdır?',
    options: [
      'Kavşak içindeki araçlara aldırmadan girmek',
      'Kornaya basıp öncelikle kendisi girmek',
      'Kavşak içinde dönmekte olan araçlara yol vermek, uygun boşlukta katılmak',
      'Sinyal vermeden ada etrafında dönmek',
    ],
    answerIndex: 2,
    explanation:
      'Dönel kavşakta kural olarak ada etrafında dönmekte olan araçların geçiş üstünlüğü vardır; yaklaşan sürücü yavaşlar, uygun boşluğu bekler ve öyle katılır. Bu, kavşak içi çarpışmayı önler.',
    whyWrong: [
      'İçerideki araçlara aldırmadan girmek çarpışmaya yol açar.',
      'Korna geçiş hakkı kazandırmaz.',
    ],
    objective: 'Dönel kavşakta içeridekine yol verme kuralını uygulamak.',
    tags: ['donel-kavsak', 'yol-verme', 'kavsak'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-109',
    subject: 'pratik',
    topic: 'kor-nokta',
    difficulty: 'orta',
    stem: 'Şerit değiştirmeden hemen önce, aynada görünmeyen aracı fark etmek için hangi kontrol şarttır?',
    options: [
      'Sadece dikiz aynasına bakmak',
      'Gözleri yalnız yola sabitlemek',
      'Kornaya basmak',
      'Değişilecek yöne doğru kısa bir omuz üstü (kör nokta) bakışı yapmak',
    ],
    answerIndex: 3,
    explanation:
      'Yan aynaların göremediği kör noktada araç bulunabilir; bu yüzden şerit değişiminden önce değişilecek yöne kısa bir omuz üstü bakış yapılır. Bu hareket görüş alanındaki boşluğu kapatır.',
    whyWrong: [
      'Yalnız dikiz aynası yandaki kör noktayı göstermez.',
      'Korna, kör noktadaki aracı görmenizi sağlamaz.',
    ],
    objective: 'Şerit değişiminde kör nokta için omuz üstü kontrolün gerekliliğini kavramak.',
    tags: ['kor-nokta', 'serit-degisimi', 'ayna-kontrol'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-110',
    subject: 'pratik',
    topic: 'vites',
    difficulty: 'orta',
    stem: 'Kavşağa veya hız kesici (kasis) önüne yaklaşırken hızını düşüren sürücü vites için ne yapmalıdır?',
    options: [
      'Yüksek viteste kalıp motoru zorlamak',
      'Düşen hıza uygun daha küçük bir vitese geçmek',
      'Vitesi boşa alıp öyle ilerlemek',
      'Hız ne olursa olsun 4. vitesle geçmek',
    ],
    answerIndex: 1,
    explanation:
      'Hız düştükçe motorun uygun devirde kalması için daha küçük vitese geçilir; böylece araç titremeden, gerektiğinde yeniden hızlanmaya hazır şekilde ilerler. Yüksek viteste yavaş gitmek motoru boğar.',
    whyWrong: [
      'Yüksek viteste düşük hızda motor titrer ve stop edebilir.',
      'Boşta ilerlemek araç kontrolünü ve fren desteğini zayıflatır.',
    ],
    objective: 'Hız düşüşünde doğru (küçük) vitese geçiş mantığını uygulamak.',
    tags: ['vites', 'hiz-kontrol', 'motor-devri'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-111',
    subject: 'pratik',
    topic: 'debriyaj',
    difficulty: 'orta',
    stem: 'Düz yolda seyir hâlindeyken ayağı sürekli debriyaj pedalının üzerinde yarı basılı tutmak neden yanlıştır?',
    options: [
      'Debriyaj balatalarının sürekli sürtünüp aşınmasına (patinaj) ve güç kaybına yol açtığı için yanlıştır',
      'Yakıt tüketimini azalttığı için doğrudur',
      'Motoru soğuttuğu için tercih edilir',
      'Frenleme mesafesini kısalttığı için önerilir',
    ],
    answerIndex: 0,
    explanation:
      'Seyir sırasında ayağın debriyaj üzerinde yarı basılı kalması balataları sürekli kaydırır (patinaj); bu, erken aşınma, güç kaybı ve ısınma demektir. Ayak, kullanılmadığında debriyajdan çekilmelidir.',
    whyWrong: [
      'Patinaj yakıtı azaltmaz; güç kaybı yüzünden tüketimi artırabilir.',
      'Debriyajı yarı basılı tutmanın frenlemeyle ilgisi yoktur.',
    ],
    objective: 'Sürekli yarı debriyajın (patinaj) zararını ve doğru ayak kullanımını bilmek.',
    tags: ['debriyaj', 'patinaj', 'seyir'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-112',
    subject: 'pratik',
    topic: 'durus',
    difficulty: 'kolay',
    stem: 'Normal sürüş sırasında direksiyonun tutulmasıyla ilgili doğru davranış hangisidir?',
    options: [
      'Tek elle, dirseği pencereye dayayarak tutmak',
      'Dizlerle yönlendirmek',
      'İki elle, saat kadranında 9 ve 3 (ya da 10-2) konumlarında dengeli tutmak',
      'Direksiyonu iç kısmından, iki parmakla tutmak',
    ],
    answerIndex: 2,
    explanation:
      'Direksiyon iki elle, dengeli konumlarda tutulduğunda ani bir manevra veya bozuk zeminde araca hâkimiyet korunur. Tek el veya dizle yönlendirme kontrolü kaybettirir.',
    whyWrong: [
      'Tek elle tutmak ani durumlarda tepki süresini uzatır.',
      'Dizle yönlendirmek araç hâkimiyetini tamamen tehlikeye atar.',
    ],
    objective: 'Doğru direksiyon tutuş (iki el) alışkanlığını benimsemek.',
    tags: ['durus', 'direksiyon', 'arac-hakimiyeti'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-113',
    subject: 'pratik',
    topic: 'sinyal',
    difficulty: 'kolay',
    stem: 'Bir kavşaktan sağa veya sola dönecek sürücü sinyali ne zaman vermelidir?',
    options: [
      'Dönüşü tamamladıktan sonra',
      'Tam dönüş anında',
      'Dönüşten yeterince önce, manevrayı arkadakilere zamanında bildirecek şekilde',
      'Sinyal vermek gerekli değildir',
    ],
    answerIndex: 2,
    explanation:
      'Sinyal, niyeti önceden bildirmek içindir; dönüşten yeterince önce verilirse arkadaki ve karşıdan gelen sürücüler tedbir alabilir. Geç verilen sinyal amacına ulaşmaz.',
    whyWrong: [
      'Dönüşten sonra sinyal vermek kimseyi uyarmaz.',
      'Sinyalsiz dönüş diğer sürücüleri hazırlıksız yakalar.',
    ],
    objective: 'Dönüş öncesi erken sinyal verme zamanlamasını uygulamak.',
    tags: ['sinyal', 'donus', 'niyet-bildirme'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-114',
    subject: 'pratik',
    topic: 'sinav-hata',
    difficulty: 'orta',
    stem: 'Direksiyon (uygulama) sınavında, adayın yaptığı hataların değerlendirilmesiyle ilgili genel mantık nedir?',
    options: [
      'Her hata mutlaka sınavı bitirir',
      'Hiçbir hata değerlendirmeyi etkilemez',
      'Yalnızca hız aşımı sınavı bitirir',
      'Bazı hatalar (güvenliği ciddi tehlikeye atanlar) sınavı doğrudan sonlandırırken, daha hafif hatalar puan kaybı olarak işlenir',
    ],
    answerIndex: 3,
    explanation:
      'Uygulama sınavında hataların ağırlığı farklıdır: can güvenliğini ciddi tehlikeye atan veya hakemin müdahalesini gerektiren durumlar sınavı doğrudan sonlandırabilir; daha küçük eksikler ise puan düşümü olarak kaydedilir.',
    whyWrong: [
      'Her hatanın sınavı bitirmesi gerçekçi değildir; hafif hatalar puan kırar.',
      'Hataların hiç değerlendirilmemesi de doğru değildir.',
    ],
    objective: 'Uygulama sınavında ağır ve hafif hata ayrımının mantığını kavramak.',
    tags: ['sinav-hata', 'degerlendirme', 'guvenlik'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-115',
    subject: 'pratik',
    topic: 'sinav-puanlama',
    difficulty: 'orta',
    stem: 'Direksiyon sınavında emniyet kemerini bağlamamak, aynaları kontrol etmemek veya sinyal vermemek nasıl değerlendirilir?',
    options: [
      'Hiç dikkate alınmaz',
      'Değerlendirmede puan kaybına yol açan eksik davranışlardır',
      'Sadece sözlü uyarıyla geçilir, kayda girmez',
      'Sınavı otomatik olarak kazandırır',
    ],
    answerIndex: 1,
    explanation:
      'Kemer bağlamama, ayna kontrolü yapmama ve sinyal vermeme gibi eksikler güvenli sürüş alışkanlıklarının gözlendiği maddelerdir; bunlar değerlendirmede puan kaybı olarak işlenir. Tekrarlanan veya ağırlaşan eksikler sonucu olumsuz etkiler.',
    whyWrong: [
      'Bu davranışlar dikkate alınmadan geçilmez; değerlendirme kapsamındadır.',
      'Eksik davranış sınav kazandırmaz.',
    ],
    objective: 'Kemer/ayna/sinyal eksikliklerinin puan kaybı yarattığını bilmek.',
    tags: ['sinav-puanlama', 'kemer', 'ayna-kontrol'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-116',
    subject: 'pratik',
    topic: 'ayna-kontrol',
    difficulty: 'kolay',
    stem: 'Frenleyip yavaşlamaya başlamadan önce sürücünün alışkanlık hâline getirmesi gereken kontrol nedir?',
    options: [
      'Radyoyu açmak',
      'Camı açmak',
      'Dikiz aynasından arkadan gelen aracın mesafesini kontrol etmek',
      'Vitesi boşa almak',
    ],
    answerIndex: 2,
    explanation:
      'Yavaşlamadan önce dikiz aynasına bakmak, arkadan gelen aracın takip mesafesini görmeyi ve gerekiyorsa frenlemeyi yumuşatmayı sağlar. Bu, arkadan çarpma riskini azaltır.',
    whyWrong: [
      'Radyo veya cam açmak güvenlik kontrolü değildir.',
      'Frenleme öncesi vitesi boşa almak araç desteğini azaltır.',
    ],
    objective: 'Yavaşlama öncesi dikiz aynası kontrol alışkanlığını edinmek.',
    tags: ['ayna-kontrol', 'frenleme', 'takip-mesafesi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-117',
    subject: 'pratik',
    topic: 'yol-verme',
    difficulty: 'orta',
    stem: 'Tali yoldan ana yola çıkacak sürücünün geçiş hakkı bakımından davranışı ne olmalıdır?',
    options: [
      'Ana yoldaki araçlara yol verip uygun boşlukta katılmak',
      'Hızlanıp ana yola dalmak',
      'Ana yoldaki araçları durmaya zorlamak',
      'Sinyal vermeden doğrudan çıkmak',
    ],
    answerIndex: 0,
    explanation:
      'Tali yoldan çıkan araç, ana yoldaki trafiğe göre geçiş hakkı bakımından ikinci sıradadır; yavaşlar, gözlem yapar ve uygun boşlukta katılır. Bu kural kavşak güvenliğinin temelidir.',
    whyWrong: [
      'Ana yola dalmak ya da araçları durmaya zorlamak geçiş hakkını ihlal eder.',
      'Sinyalsiz çıkış niyeti bildirmediği için tehlikelidir.',
    ],
    objective: 'Tali yoldan ana yola çıkışta yol verme kuralını uygulamak.',
    tags: ['yol-verme', 'tali-yol', 'kavsak'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-118',
    subject: 'pratik',
    topic: 'manevra',
    difficulty: 'orta',
    stem: 'Aracı geri geri hareket ettirmeden önce yapılması gereken en temel güvenlik kontrolü nedir?',
    options: [
      'Sadece ileriye bakmak',
      'Kornaya basıp beklemeden geri gitmek',
      'Farları yakıp geri gitmek yeterlidir',
      'Arka ve yanları aynalardan ve gerektiğinde omuz üstünden kontrol edip yaya/engel olmadığından emin olmak',
    ],
    answerIndex: 3,
    explanation:
      'Geri manevrada aracın arkası ve yanları sürücünün doğrudan göremediği alanlardır; bu yüzden aynalar ve omuz üstü bakışla yaya, çocuk veya engel bulunmadığından emin olunmalıdır. Görülmeyen alanlar en büyük risktir.',
    whyWrong: [
      'İleriye bakmak, aracın gittiği arka tarafı görmez.',
      'Korna veya far, arkadaki engeli görmenin yerini tutmaz.',
    ],
    objective: 'Geri manevra öncesi arka/yan gözlem yapma alışkanlığını edinmek.',
    tags: ['manevra', 'geri-gitme', 'gozlem'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-119',
    subject: 'pratik',
    topic: 'rampa',
    difficulty: 'zor',
    stem: 'Rampa (yokuş) kalkışında araç geriye kaymaya başlarsa sürücünün ilk tepkisi ne olmalıdır?',
    options: [
      'Gaza sonuna kadar basmak',
      'Fren veya el freniyle aracı tutup dengeyi yeniden kurarak kalkışı tekrarlamak',
      'Debriyajı tamamen bırakmak',
      'Direksiyonu sağa sola çevirmek',
    ],
    answerIndex: 1,
    explanation:
      'Rampada kayma başladığında öncelik aracı durdurmaktır; fren veya el freniyle araç tutulur, ardından debriyaj-gaz dengesi yeniden kurularak kalkış tekrarlanır. Panikle gaza yüklenmek kontrolü zorlaştırır.',
    whyWrong: [
      'Sonuna kadar gaz vermek aracı ani sıçratabilir, kaymayı çözmez.',
      'Debriyajı birden bırakmak motoru stop ettirir.',
    ],
    objective: 'Rampada geriye kayma anında güvenli düzeltme tepkisini uygulamak.',
    tags: ['rampa', 'el-freni', 'geri-kayma'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-120',
    subject: 'pratik',
    topic: 'sinav-hata',
    difficulty: 'zor',
    stem: 'Direksiyon sınavında hakemin (uygulama sınavı görevlisinin) frene basarak ya da direksiyona müdahale ederek bir çarpışmayı önlemesi ne anlama gelir?',
    options: [
      'Küçük bir puan kırılır ve sınav sürer',
      'Hiçbir etkisi olmaz',
      'Aday güvenliği sağlayamamış sayılır; bu tür müdahale gerektiren durum genellikle sınavın olumsuz sonuçlanmasına yol açar',
      'Adaya avantaj sağlar',
    ],
    answerIndex: 2,
    explanation:
      'Görevlinin fiziksel müdahalesi, adayın kendi başına güvenliği sağlayamadığı ciddi bir durumu gösterir; bu nitelikteki hatalar genellikle sınavı doğrudan olumsuz sonuçlandıran ağır hatalar sınıfındadır.',
    whyWrong: [
      'Böyle bir müdahale küçük puan kaybı değildir; ağır hata sayılır.',
      'Etkisiz olması veya avantaj sağlaması söz konusu değildir.',
    ],
    objective: 'Hakem müdahalesinin ağır hata niteliğini ve sonucunu kavramak.',
    tags: ['sinav-hata', 'hakem-mudahalesi', 'guvenlik'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-121',
    subject: 'pratik',
    topic: 'durus',
    difficulty: 'kolay',
    stem: 'Aracı park edip terk ederken güvenliği sağlamak için hangi işlemler yapılmalıdır?',
    options: [
      'Sadece kontağı kapatmak',
      'Vitesi boşta bırakıp el frenini indirmek',
      'Motoru çalışır bırakıp inmek',
      'Yalnız dörtlü flaşörü yakıp inmek',
      'El frenini çekmek, aracı uygun vitese/park konumuna almak ve kontağı kapatmak',
    ],
    answerIndex: 4,
    explanation:
      'Park sırasında el freni çekilir, manuel araçta uygun vites (genelde 1. veya geri, yokuşta yönüne göre) takılır ve kontak kapatılır; böylece araç kendiliğinden hareket etmez. Boşta ve frensiz bırakmak kayma riski yaratır.',
    whyWrong: [
      'Yalnız kontağı kapatmak aracın kaymasını önlemez.',
      'Boşta ve el freni indirilmiş araç yokuşta kayabilir.',
    ],
    objective: 'Park edip aracı terk ederken güvenli durdurma adımlarını uygulamak.',
    tags: ['durus', 'el-freni', 'park'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-122',
    subject: 'pratik',
    topic: 'vites',
    difficulty: 'kolay',
    stem: 'Duruştan düz zeminde ilk kalkış hangi vitesle yapılır?',
    options: ['3. vites', '2. vites', 'Geri vites', '1. vites'],
    answerIndex: 3,
    explanation:
      'Duruştan kalkış, en yüksek tork sağlayan 1. vitesle yapılır; araç hareketlendikçe kademeli olarak üst vitese geçilir. Düz zeminde kalkış için 1. vites standarttır.',
    whyWrong: [
      '2. veya 3. viteste kalkış motoru zorlar, aracı titretir veya stop ettirir.',
      'Geri vites ileri kalkış için kullanılmaz.',
    ],
    objective: 'Duruştan kalkışta doğru başlangıç vitesini bilmek.',
    tags: ['vites', 'kalkis', 'birinci-vites'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-123',
    subject: 'pratik',
    topic: 'donus',
    difficulty: 'orta',
    stem: 'Dar bir sokağa sola dönerken sürücünün doğru davranış sırası hangisidir?',
    options: [
      'Hızlanıp geniş bir yay çizerek dönmek',
      'Sinyal ver, hızını düşür, aynaları ve karşı yönü kontrol et, uygun açıyla dön',
      'Sinyal vermeden hemen kırmak',
      'Dönüş anında debriyaja basıp motoru boşa almak',
    ],
    answerIndex: 1,
    explanation:
      'Dönüşten önce sinyalle niyet bildirilir, hız güvenli seviyeye düşürülür, aynalar ve karşı yön kontrol edilir; sonra uygun açıyla dönülür. Hazırlıklı ve kontrollü dönüş yaya ve karşı trafik için güvenlidir.',
    whyWrong: [
      'Hızlı ve geniş yaylı dönüş karşı şeride taşma riski taşır.',
      'Dönüşte motoru boşa almak araç hâkimiyetini zayıflatır.',
    ],
    objective: 'Dönüş öncesi sinyal-hız-gözlem sırasını doğru uygulamak.',
    tags: ['donus', 'sinyal', 'hiz-kontrol'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-124',
    subject: 'pratik',
    topic: 'arac-kontrol',
    difficulty: 'orta',
    stem: 'Manuel vitesli araçta tam durmadan hemen önce motorun stop etmesini önlemek için ne yapılır?',
    options: [
      'Araç durmadan önce debriyaja basıp motorun tekerlerden ayrılmasını sağlamak',
      'Sadece frene basmak, debriyaja hiç dokunmamak',
      'Gaza basmaya devam etmek',
      'El frenini ani çekmek',
    ],
    answerIndex: 0,
    explanation:
      'Araç tamamen durmadan hemen önce debriyaja basılırsa motor tekerlerden ayrılır ve devri düşse de stop etmez. Debriyaja basmadan sadece frenle durmak düşük hızda motoru boğar.',
    whyWrong: [
      'Yalnız frenle durmak, debriyaj basılmadığı için motoru stop ettirir.',
      'Gaza basmak durmayı engeller; el freni ani çekmek tehlikelidir.',
    ],
    objective: 'Durma anında debriyaj kullanarak motorun stop etmesini önlemek.',
    tags: ['arac-kontrol', 'debriyaj', 'durma'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'pratik-125',
    subject: 'pratik',
    topic: 'sinav-puanlama',
    difficulty: 'orta',
    stem: 'Direksiyon (uygulama) sınavının başarı mantığı en doğru şekilde nasıl özetlenir?',
    options: [
      'Aracı çalıştırmak tek başına yeterlidir',
      'Sınav süresini doldurmak başarı için yeterlidir',
      'Aday, güvenli sürüş kurallarını uygulayarak yeterli düzeyde araç hâkimiyeti ve trafik davranışı gösterirse başarılı sayılır',
      'Yalnız park manevrasını yapmak sınavı kazandırır',
    ],
    answerIndex: 2,
    explanation:
      'Uygulama sınavında amaç, adayın gerçek trafikte güvenli sürebildiğini göstermesidir; araç hâkimiyeti, doğru gözlem, kurallara uyum ve manevra becerileri bir bütün olarak değerlendirilir. Tek bir işlem başarıyı belirlemez.',
    whyWrong: [
      'Aracı çalıştırmak ya da süreyi doldurmak sürüş yeterliliğini kanıtlamaz.',
      'Tek bir manevra tüm değerlendirmenin yerini tutmaz.',
    ],
    objective: 'Uygulama sınavının bütünsel değerlendirme mantığını kavramak.',
    tags: ['sinav-puanlama', 'arac-hakimiyeti', 'guvenli-surus'],
    badge: 'examiner',
    review: 'draft',
    sourceRef: SRC,
  },
];
