/**
 * ÖZGÜN soru bankası — genişletme kümesi (ROADMAP Faz 12).
 * Hedef: tam e-Sınav dağılımını (trafik 23 · ilkyardım 12 · motor 9 · adab 6) karşılamak.
 * Kaynak = resmî MEB/ODSGM müfredatı + Karayolları Trafik mevzuatı + resmî temel ilk yardım
 * bilgisi; tümü KENDİ İFADEMİZLE (hiçbir uygulama/site sorusu kopyalanmadı — ROADMAP C.4/E.6).
 * `review: 'draft'` → yayından önce alan uzmanı onayı gerekir.
 */
import type { QuestionInput } from '@ea/content-schema';

const SRC = 'Resmî MEB/ODSGM müfredatı ve Karayolları Trafik mevzuatı (özgün ifade)';
const SRC_FA = 'Resmî temel ilk yardım bilgisi (özgün ifade) — uzman onayı bekliyor';

export const EXTRA_QUESTIONS: QuestionInput[] = [
  // ——— TRAFİK VE ÇEVRE (+17 → toplam 23) ———
  {
    id: 'trafik-007',
    subject: 'trafik',
    topic: 'isaretler',
    difficulty: 'kolay',
    stem: 'Ters (başaşağı) üçgen biçimindeki trafik işareti neyi bildirir?',
    options: ['Dur', 'Yol ver', 'Girişi olmayan yol', 'Ana yol'],
    answerIndex: 1,
    explanation:
      'Ters üçgen "Yol Ver" işaretidir: sürücü yavaşlar, gerekiyorsa durur ve geçiş hakkı olan trafiğe öncelik verir.',
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-008',
    subject: 'trafik',
    topic: 'isaretler',
    difficulty: 'orta',
    stem: 'Kırmızı kenarlı daire içindeki işaretler genel olarak neyi anlatır?',
    options: ['Bilgilendirme', 'Yasaklama/kısıtlama', 'Mecburiyet', 'Tehlike uyarısı'],
    answerIndex: 1,
    explanation:
      'Kırmızı kenarlı daireler yasaklama/kısıtlama bildirir (ör. hız sınırı, sollama yasağı). Mavi daireler mecburiyet, üçgenler tehlike uyarısıdır.',
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-009',
    subject: 'trafik',
    topic: 'isik',
    difficulty: 'orta',
    stem: 'Kavşağa yaklaşırken ışık sarıya döndü. Güvenle durabilecek mesafedeyseniz ne yapmalısınız?',
    options: ['Hızlanıp geçmek', 'Durmak', 'Korna çalarak geçmek', 'Şerit değiştirmek'],
    answerIndex: 1,
    explanation:
      'Sarı ışık "hazırlan/duraksa" anlamındadır: güvenle durabilecek mesafedeki sürücü durur; ancak ani fren tehlike yaratacaksa kavşak güvenle terk edilir.',
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-010',
    subject: 'trafik',
    topic: 'isik',
    difficulty: 'kolay',
    stem: 'Kırmızı ışıkta bekleyen sürücü, yeşil yandığında ilk olarak ne yapmalıdır?',
    options: [
      'Hemen gaza basıp hızla kalkmak',
      'Kavşağın boşaldığını ve yayaların geçtiğini kontrol edip hareket etmek',
      'Korna çalıp öndekini uyarmak',
    ],
    answerIndex: 1,
    explanation:
      'Yeşil ışık geçiş hakkı verir ama güvenliği garanti etmez: kavşağı ihlal eden araç/yaya olabilir. Kısa bir kontrolle hareket edilir.',
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-011',
    subject: 'trafik',
    topic: 'oncelik',
    difficulty: 'kolay',
    stem: 'Tali yoldan ana yola çıkacak sürücü ne yapmalıdır?',
    options: [
      'Ana yoldaki araçlara yol vermelidir',
      'Öncelik kendisindedir, doğrudan çıkar',
      'Korna çalarak çıkar',
    ],
    answerIndex: 0,
    explanation:
      'Ana yol – tali yol kesişiminde geçiş önceliği ana yoldaki araçlardadır; tali yoldan çıkan yol vermek zorundadır.',
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-012',
    subject: 'trafik',
    topic: 'oncelik',
    difficulty: 'orta',
    stem: 'Kavşakta sola dönüş yapacak sürücü, karşı yönden düz gelen araca karşı nasıl davranmalıdır?',
    options: [
      'Dönüşe önce başladığı için önceliklidir',
      'Karşıdan düz gelen araca yol vermelidir',
      'Selektör yapıp geçmelidir',
    ],
    answerIndex: 1,
    explanation:
      'Dönüş yapan sürücü, karşı yönden gelen ve düz geçen trafiğe yol vermek zorundadır; uygun boşluk beklenir.',
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-013',
    subject: 'trafik',
    topic: 'hiz',
    difficulty: 'orta',
    stem: 'Yerleşim yeri dışındaki bölünmüş yollarda otomobiller için genel azami hız kaç km/saattir?',
    options: ['90', '110', '120', '130'],
    answerIndex: 1,
    explanation:
      'Otomobilde genel sınırlar: yerleşim içi 50, yerleşim dışı 90, bölünmüş yol 110, otoyol 120 km/s (levha farklı değer gösterebilir).',
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-014',
    subject: 'trafik',
    topic: 'hiz',
    difficulty: 'orta',
    stem: 'Hız arttıkça fren (duruş) mesafesi nasıl değişir?',
    options: ['Değişmez', 'Azalır', 'Artar', 'Önce azalır sonra artar'],
    answerIndex: 2,
    explanation:
      'Hız arttıkça hem tepki mesafesi hem fren mesafesi büyür; duruş mesafesi hızla birlikte katlanarak artar. Bu yüzden hız, koşullara göre ayarlanmalıdır.',
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-015',
    subject: 'trafik',
    topic: 'sollama',
    difficulty: 'kolay',
    stem: 'Öndeki aracı geçmek (sollamak) kural olarak hangi taraftan yapılır?',
    options: ['Sağından', 'Solundan', 'Banketten', 'Fark etmez'],
    answerIndex: 1,
    explanation:
      'Geçme kural olarak soldan yapılır. (İstisna: sola dönüş sinyali veren aracın sağından, kurallara uygun biçimde geçilebilir.)',
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-016',
    subject: 'trafik',
    topic: 'sollama',
    difficulty: 'orta',
    stem: 'Aşağıdaki yerlerin hangisinde öndeki aracı geçmek (sollama) yasaktır?',
    options: [
      'Görüşün açık olduğu düz yolda',
      'Tepe üstü ve dönemeçlerde (görüş yetersizken)',
      'Bölünmüş yolun sol şeridinde',
    ],
    answerIndex: 1,
    explanation:
      'Görüşün yetersiz olduğu tepe üstü ve dönemeçlerde, yaya/okul geçitlerinde, kavşaklarda ve demiryolu geçitlerinde sollama yasaktır — karşıdan gelen görülemez.',
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-017',
    subject: 'trafik',
    topic: 'yaya',
    difficulty: 'kolay',
    stem: 'Işıksız yaya geçidine yaklaşan sürücü, geçitte yaya varsa ne yapmalıdır?',
    options: ['Korna çalıp geçmek', 'Yavaşlamak, gerekiyorsa durup yol vermek', 'Hızlanıp geçmek'],
    answerIndex: 1,
    explanation:
      'Yaya geçidinde öncelik yayanındır; sürücü yavaşlar, gerekiyorsa durur. Yayaya yol vermemek ağır kusurdur.',
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-018',
    subject: 'trafik',
    topic: 'park',
    difficulty: 'orta',
    stem: 'Aşağıdakilerden hangisi duraklamanın (kısa süreli durmanın) yasak olduğu yerlerdendir?',
    options: [
      'Geniş ve açık cadde kenarı',
      'Kavşaklara ve yaya geçitlerine yakın (5 metre içi) alanlar',
      'Otopark girişinin karşı kaldırımı',
    ],
    answerIndex: 1,
    explanation:
      'Kavşak, tünel, köprü, yaya/okul geçidi gibi noktalara 5 metre mesafe içinde duraklamak yasaktır — görüşü ve akışı engeller.',
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-019',
    subject: 'trafik',
    topic: 'emniyet',
    difficulty: 'kolay',
    stem: 'Otomobilde emniyet kemeri kullanma zorunluluğu kimler için geçerlidir?',
    options: ['Yalnız sürücü için', 'Yalnız ön koltuktakiler için', 'Sürücü ve tüm yolcular için'],
    answerIndex: 2,
    explanation:
      'Emniyet kemeri, sürücü dahil aracın tüm koltuklarında oturanlar için zorunludur; kaza anında ölüm/yaralanma riskini büyük ölçüde azaltır.',
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-020',
    subject: 'trafik',
    topic: 'alkol',
    difficulty: 'orta',
    stem: 'Hususi otomobil sürücüleri için yasal kandaki alkol sınırı (promil) nedir?',
    options: ['1.00 promil', '0.50 promil', 'Sınır yoktur', '2.00 promil'],
    answerIndex: 1,
    explanation:
      'Hususi otomobil sürücülerinde yasal sınır 0.50 promildir; ticari/kamu hizmeti sürücülerinde alkollü araç kullanmak tamamen yasaktır. Güvenli olan hiç almamaktır.',
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-021',
    subject: 'trafik',
    topic: 'gece',
    difficulty: 'orta',
    stem: 'Gece, karşı yönden gelen araçla karşılaşan sürücü farlarını nasıl kullanmalıdır?',
    options: [
      'Uzun farla devam eder',
      'Kısa fara geçer',
      'Farları tamamen kapatır',
      'Dörtlü ikaz yakar',
    ],
    answerIndex: 1,
    explanation:
      'Karşılaşmalarda uzun far karşı sürücüyü kamaştırır; kısa fara geçilir. Farları kapatmak da tehlikelidir — görünürlük kaybolur.',
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-022',
    subject: 'trafik',
    topic: 'cevre',
    difficulty: 'kolay',
    stem: 'Yerleşim yerlerinde gereksiz korna çalmak için aşağıdakilerden hangisi doğrudur?',
    options: [
      'Serbesttir',
      'Gürültü kirliliği yaratır ve zorunlu uyarı dışında yasaktır',
      'Yalnız gündüz serbesttir',
    ],
    answerIndex: 1,
    explanation:
      'Korna yalnız uyarı amaçlı ve gerektiğinde kullanılır; gereksiz kullanımı gürültü kirliliğidir ve yasaktır.',
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'trafik-023',
    subject: 'trafik',
    topic: 'hemzemin',
    difficulty: 'orta',
    stem: 'Bariyeri kapalı olan demiryolu (hemzemin) geçidine gelen sürücü ne yapmalıdır?',
    options: [
      'Bariyer aralığından geçmeye çalışır',
      'Durur ve bariyer açılmadan geçmez',
      'Korna çalarak bekler, sonra geçer',
    ],
    answerIndex: 1,
    explanation:
      'Hemzemin geçitte ışık/bariyer talimatına kesin uyulur; bariyer kapalıyken geçmek ölümcül risktir ve ağır kusurdur.',
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },

  // ——— İLK YARDIM (+7 → toplam 12) ———
  {
    id: 'ilkyardim-006',
    subject: 'ilkyardim',
    topic: 'tyd',
    difficulty: 'orta',
    stem: 'Yetişkinde tek kişiyle temel yaşam desteğinde kalp masajı / suni solunum oranı nedir?',
    options: ['15:2', '30:2', '5:1', '10:2'],
    answerIndex: 1,
    explanation: 'Yetişkinde 30 göğüs basısına 2 kurtarıcı soluk uygulanır (30:2 döngüsü).',
    badge: 'official',
    review: 'draft',
    sourceRef: SRC_FA,
  },
  {
    id: 'ilkyardim-007',
    subject: 'ilkyardim',
    topic: 'yanik',
    difficulty: 'kolay',
    stem: 'Sıcak suyla haşlanma gibi bir yanıkta ilk yapılması gereken nedir?',
    options: [
      'Yanık bölgeye diş macunu/yoğurt sürmek',
      'Bölgeyi en az 15-20 dakika soğuk (akan) suyla soğutmak',
      'Su toplamış kabarcıkları patlatmak',
    ],
    answerIndex: 1,
    explanation:
      'Yanıkta ilk adım bölgeyi soğuk suyla soğutmaktır. Macun/yoğurt sürülmez, kabarcıklar patlatılmaz — enfeksiyon riski.',
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC_FA,
  },
  {
    id: 'ilkyardim-008',
    subject: 'ilkyardim',
    topic: 'kirik',
    difficulty: 'orta',
    stem: 'Kol veya bacakta kırık şüphesi olan kazazedeye ilk yardımda ne yapılır?',
    options: [
      'Kırık bölge düzeltilmeye çalışılır',
      'Bölge bulunduğu şekilde tespit edilip (sabitleyip) hareketsiz kılınır',
      'Kazazede hemen ayağa kaldırılır',
    ],
    answerIndex: 1,
    explanation:
      'Kırıkta bölge asla düzeltilmeye çalışılmaz; bulunduğu pozisyonda atel benzeri malzemeyle tespit edilir ve hareket ettirilmez.',
    badge: 'official',
    review: 'draft',
    sourceRef: SRC_FA,
  },
  {
    id: 'ilkyardim-009',
    subject: 'ilkyardim',
    topic: 'sok',
    difficulty: 'orta',
    stem: 'Şok belirtileri gösteren (soluk, soğuk terli, hızlı nabızlı) kazazedeye hangi pozisyon verilir?',
    options: [
      'Oturur pozisyon',
      'Sırtüstü yatırılıp bacaklar ~30 cm yükseltilir (şok pozisyonu)',
      'Yüzüstü pozisyon',
    ],
    answerIndex: 1,
    explanation:
      'Şokta kazazede sırtüstü yatırılır, bacaklar yaklaşık 30 cm yükseltilir; böylece kan yaşamsal organlara yönlendirilir. Üzeri örtülür, sıkan giysiler gevşetilir.',
    badge: 'official',
    review: 'draft',
    sourceRef: SRC_FA,
  },
  {
    id: 'ilkyardim-010',
    subject: 'ilkyardim',
    topic: 'tasima',
    difficulty: 'orta',
    stem: 'Kazazede araç içinden hangi durumda ve nasıl çıkarılır?',
    options: [
      'Her durumda hemen çıkarılır',
      'Yangın/patlama gibi hayati tehlike varsa, omurga korunarak (ör. Rautek yöntemiyle) çıkarılır',
      'Kollarından çekilerek hızla çıkarılır',
    ],
    answerIndex: 1,
    explanation:
      'Zorunlu (hayati) tehlike yoksa kazazede yerinden oynatılmaz. Çıkarmak gerekiyorsa baş-boyun-gövde ekseni korunarak Rautek kavraması gibi teknikler kullanılır.',
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC_FA,
  },
  {
    id: 'ilkyardim-011',
    subject: 'ilkyardim',
    topic: 'bogulma',
    difficulty: 'orta',
    stem: 'Yabancı cisimle tam tıkanan (konuşamayan, öksüremeyen) yetişkine ne uygulanır?',
    options: [
      'Su içirilir',
      'Karına bası (Heimlich manevrası) uygulanır',
      'Sırtüstü yatırılıp beklenir',
    ],
    answerIndex: 1,
    explanation:
      'Tam tıkanmada Heimlich manevrası (karına doğru içe-yukarı bası) uygulanır. Kısmi tıkanmada kişi öksürmeye teşvik edilir.',
    badge: 'official',
    review: 'draft',
    sourceRef: SRC_FA,
  },
  {
    id: 'ilkyardim-012',
    subject: 'ilkyardim',
    topic: 'bilinc',
    difficulty: 'kolay',
    stem: 'Bayılan (kısa süreli bilinç kaybı yaşayan) kişiye ilk yardımda ne yapılır?',
    options: [
      'Ayağa kaldırılıp yürütülür',
      'Sırtüstü yatırılır, ayakları yükseltilir, sıkan giysiler gevşetilir',
      'Yüzüne su dökülür ve sarsılır',
    ],
    answerIndex: 1,
    explanation:
      'Bayılmada kişi sırtüstü yatırılır, ayaklar hafif yükseltilir, temiz hava sağlanır ve sıkan giysiler gevşetilir; kendine gelmezse tıbbi yardım istenir.',
    badge: 'official',
    review: 'draft',
    sourceRef: SRC_FA,
  },

  // ——— ARAÇ TEKNİĞİ (+4 → toplam 9) ———
  {
    id: 'motor-006',
    subject: 'motor',
    topic: 'lastik',
    difficulty: 'orta',
    stem: 'Otomobil lastiklerinde yasal en az diş derinliği kaç milimetredir?',
    options: ['0.6 mm', '1.6 mm', '3.6 mm', '5 mm'],
    answerIndex: 1,
    explanation:
      'Yasal alt sınır 1.6 mm’dir. Diş derinliği azaldıkça özellikle ıslak zeminde tutunma ve fren performansı ciddi düşer.',
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-007',
    subject: 'motor',
    topic: 'elektrik',
    difficulty: 'kolay',
    stem: 'Farlardan biri veya sinyal lambası çalışmıyorsa ilk olarak ne kontrol edilmelidir?',
    options: ['Motor yağı', 'İlgili sigorta ve ampul', 'Fren hidroliği', 'Lastik basıncı'],
    answerIndex: 1,
    explanation:
      'Aydınlatma/sinyal arızalarında ilk bakılacak yer ilgili sigorta ve ampuldür; sigorta atmışsa aynı amper değerinde yenisiyle değiştirilir.',
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-008',
    subject: 'motor',
    topic: 'filtre',
    difficulty: 'orta',
    stem: 'Hava filtresi tıkalı (çok kirli) olan bir motorda ne gözlenir?',
    options: [
      'Yakıt tüketimi azalır',
      'Motor gücü düşer ve yakıt tüketimi artar',
      'Fren mesafesi kısalır',
    ],
    answerIndex: 1,
    explanation:
      'Tıkalı hava filtresi motorun hava almasını zorlaştırır: güç düşer, yakıt tüketimi ve emisyon artar. Periyodik bakımda değiştirilir.',
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'motor-009',
    subject: 'motor',
    topic: 'sogutma',
    difficulty: 'kolay',
    stem: 'Soğutma sistemindeki antifrizin görevi nedir?',
    options: [
      'Yakıtı temizlemek',
      'Soğutma suyunun kışın donmasını, yazın kolay kaynamasını önlemek',
      'Lastik basıncını korumak',
    ],
    answerIndex: 1,
    explanation:
      'Antifriz; soğutma suyunun donma noktasını düşürür, kaynama noktasını yükseltir ve sistemi korozyona karşı korur. Dört mevsim kullanılır.',
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },

  // ——— TRAFİK ADABI (+2 → toplam 6) ———
  {
    id: 'adab-005',
    subject: 'adab',
    topic: 'hosgoru',
    difficulty: 'kolay',
    stem: 'Trafikte başka bir sürücü hatalı davranıp önünüze kırdığında trafik adabına uygun davranış hangisidir?',
    options: [
      'Yaklaşıp selektör ve kornayla karşılık vermek',
      'Sakin kalmak, takip mesafesini açmak ve güvenliği önceliklendirmek',
      'Aynı hatayı ona yaparak ders vermek',
    ],
    answerIndex: 1,
    explanation:
      'Trafik adabı, hata karşısında misilleme değil sakinlik ve hoşgörü gerektirir. Gerekirse hakkından feragat etmek kazayı önler — amaç haklı çıkmak değil, güvenle varmaktır.',
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-006',
    subject: 'adab',
    topic: 'empati',
    difficulty: 'orta',
    stem: 'Trafikte "empati" aşağıdakilerden hangisiyle en iyi açıklanır?',
    options: [
      'Kendi hakkını sonuna kadar savunmak',
      'Diğer yol kullanıcılarının durumunu anlamaya çalışıp ona göre davranmak',
      'Yalnızca yayaları düşünmek',
    ],
    answerIndex: 1,
    explanation:
      'Empati; acemi sürücüden yaşlı yayaya, diğer yol kullanıcılarının bakış açısını anlamak ve davranışı buna göre ayarlamaktır — güvenli ve saygılı trafiğin temeli.',
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
];
