/**
 * ÖZGÜN trafik adabı soruları (Sprint 3 genişletme). ROADMAP C.4/E.6.
 * Kaynak = MEB Trafik Adabı müfredatı; KENDİ İFADEMİZLE. review: 'draft'.
 */
import type { Question } from '@ea/content-schema';

const SRC = 'MEB Trafik Adabı müfredatı (özgün ifade)';

export const ADAB_QUESTIONS: Question[] = [
  {
    id: 'adab-101',
    subject: 'adab',
    topic: 'ofke',
    difficulty: 'kolay',
    stem: 'Önünüzdeki sürücü yeşil ışıkta geç hareket etti. Trafik adabına en uygun davranış hangisidir?',
    options: [
      'Bir an bekleyip sürücünün hazırlanmasına fırsat tanımak',
      'Uzun uzun korna çalıp el kol hareketi yapmak',
      'Sıkışıp yandan tehlikeli şekilde geçmek',
      'Selektör yapıp arkasına iyice yaklaşmak',
    ],
    answerIndex: 0,
    explanation:
      'Kısa bir gecikme sabırla karşılanmalıdır; birkaç saniye beklemek hem güvenliği korur hem de gereksiz gerilimi önler.',
    whyWrong: [
      'Uzun korna ve el kol hareketi saldırganlıktır, öfkeyi büyütür.',
      'Sıkışıp geçmek ve dip mesafeye sokulmak kaza riskini artırır.',
    ],
    objective: 'Küçük gecikmeler karşısında sabırlı ve hoşgörülü davranmayı kavramak.',
    tags: ['ofke-kontrolu', 'sabir', 'kavsak'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-102',
    subject: 'adab',
    topic: 'gecis-ustunlugu',
    difficulty: 'kolay',
    stem: 'Arkanızdan siren çalarak yaklaşan bir ambulans var. Ne yapmalısınız?',
    options: [
      'Hızlanıp ambulansın önünde gitmeye devam etmek',
      'Olduğunuz yerde durup şeridi kapatmak',
      'Güvenli şekilde sağa yanaşıp ambulansa yol vermek',
      'Ambulansın arkasına takılıp aynı hızda ilerlemek',
    ],
    answerIndex: 2,
    explanation:
      'Geçiş üstünlüğü olan araçlara yol vermek yasal bir zorunluluktur; güvenli biçimde sağa yanaşıp yolu açmak bir insanın hayatını kurtarabilir.',
    whyWrong: [
      'Önünde gitmeye çalışmak ambulansı geciktirir ve tehlike yaratır.',
      'Şeridi kapatarak durmak geçişi engeller.',
      'Arkasına takılmak izinsiz geçiş üstünlüğü kullanmaktır.',
    ],
    objective: 'Geçiş üstünlüğü olan araçlara doğru ve güvenli şekilde yol vermeyi öğrenmek.',
    tags: ['gecis-ustunlugu', 'ambulans', 'yol-verme'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-103',
    subject: 'adab',
    topic: 'yaya-saygi',
    difficulty: 'kolay',
    stem: 'Yaya geçidine yaklaşırken karşıdan karşıya geçmek isteyen bir yaya görüyorsunuz. Doğru davranış nedir?',
    options: [
      'Kornaya basıp yayayı hızlıca geçmeye zorlamak',
      'Yavaşlayıp durarak yayaya geçiş önceliği tanımak',
      'Yayayı görmezden gelip hızla geçmek',
      'Yayanın önünden sıyrılıp geçmek',
    ],
    answerIndex: 1,
    explanation:
      'Yaya geçidinde öncelik daima yayanındır; yavaşlayıp durmak yayanın güvenle geçmesini sağlar ve trafik adabının temel gereğidir.',
    whyWrong: [
      'Kornayla zorlamak yayayı paniğe sürükler.',
      'Görmezden gelmek veya sıyrılıp geçmek ciddi kaza riski taşır.',
    ],
    objective: 'Yaya geçitlerinde yayaya öncelik verme ilkesini benimsemek.',
    tags: ['yaya-saygi', 'yaya-gecidi', 'oncelik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-104',
    subject: 'adab',
    topic: 'nezaket',
    difficulty: 'kolay',
    stem: 'Yoğun trafikte bir sürücü sizin şeridinize girmenize izin verdi. En uygun karşılık hangisidir?',
    options: [
      'Hiçbir şey yapmadan devam etmek',
      'Uzun uzun korna çalarak dikkat çekmek',
      'Aynadan bakıp hızlanmak',
      'El kaldırarak ya da kısa selektörle teşekkür etmek',
    ],
    answerIndex: 3,
    explanation:
      'Kısa bir el işareti veya selektörle teşekkür etmek nezaket kültürünü güçlendirir ve trafikte olumlu bir iletişim kurar.',
    whyWrong: [
      'Karşılık vermemek jesti değersiz kılar.',
      'Uzun korna teşekkür değil rahatsızlık ifadesidir.',
    ],
    objective: 'Trafikte nezaket jestlerine uygun teşekkür işaretiyle karşılık vermeyi öğrenmek.',
    tags: ['nezaket', 'iletisim', 'tesekkur'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-105',
    subject: 'adab',
    topic: 'sabir',
    difficulty: 'orta',
    stem: 'Uzun bir trafik sıkışıklığında ilerleme çok yavaş. Trafik adabına uygun tutum hangisidir?',
    options: [
      'Emniyet şeridini kullanarak öne geçmek',
      'Sürekli şerit değiştirip boşluk kollamak',
      'Sıranı koruyup sakin kalarak beklemek',
      'Öndeki araca yaklaşıp korna çalmak',
    ],
    answerIndex: 2,
    explanation:
      'Sıkışıklıkta sırayı korumak ve sakin kalmak hem trafiği daha akıcı tutar hem de kaza ve gerginlik riskini azaltır.',
    whyWrong: [
      'Emniyet şeridi acil durumlar içindir, keyfi kullanımı hem yasak hem tehlikelidir.',
      'Sık şerit değiştirmek akışı bozar ve sürtüşme yaratır.',
    ],
    objective: 'Trafik yoğunluğunda sabırlı ve kural odaklı kalmayı içselleştirmek.',
    tags: ['sabir', 'stres', 'emniyet-seridi'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-106',
    subject: 'adab',
    topic: 'empati',
    difficulty: 'orta',
    stem: 'Önünüzdeki araçta acemi sürücü (yeni sürücü) yazısı var ve temkinli ilerliyor. Empatiye dayalı doğru yaklaşım nedir?',
    options: [
      'Baskı yaparak hızlanmaya zorlamak',
      'Takip mesafesini artırıp anlayışla ilerlemek',
      'Yanına gelip bakışlarla uyarmak',
      'Sürekli selektör yapmak',
    ],
    answerIndex: 1,
    explanation:
      'Acemi sürücünün tedirginliğini anlayıp takip mesafesini artırmak, kendimizin de bir zamanlar yeni olduğunu hatırlayan empatik bir tutumdur.',
    whyWrong: [
      'Baskı ve selektör acemi sürücüyü paniğe sürükleyip hata yaptırabilir.',
      'Yanına sokulup uyarmak dikkat dağıtır ve tehlike doğurur.',
    ],
    objective: 'Deneyimsiz sürücülere karşı empatik ve anlayışlı davranmayı geliştirmek.',
    tags: ['empati', 'acemi-surucu', 'takip-mesafesi'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-107',
    subject: 'adab',
    topic: 'hosgoru',
    difficulty: 'orta',
    stem: 'Bir sürücü dalgınlıkla hatalı sollama yapıp önünüze geçti. Hoşgörüye dayalı davranış hangisidir?',
    options: [
      'Kızmadan yolunuza güvenle devam etmek',
      'Peşine takılıp aynı hatayı ona da yapmak',
      'Hızlanıp önünü keserek ders vermek',
      'Yanına gelip pencereden bağırmak',
    ],
    answerIndex: 0,
    explanation:
      'Başkasının hatasını cezalandırmaya çalışmak yeni bir tehlike doğurur; hoşgörüyle sakin kalmak en güvenli ve olgun tutumdur.',
    whyWrong: [
      'Aynı hatayı tekrarlamak riski katlar.',
      'Önünü kesmek ve bağırmak trafik terörüne dönüşebilir.',
    ],
    objective: 'Başkalarının hatalarını hoşgörüyle karşılayıp misilleme yapmamayı öğrenmek.',
    tags: ['hosgoru', 'ofke-kontrolu', 'misilleme'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-108',
    subject: 'adab',
    topic: 'stres',
    difficulty: 'orta',
    stem: 'İşe geç kaldınız ve trafik çok yoğun; giderek geriliyorsunuz. Stresi yönetmek için en doğru yaklaşım nedir?',
    options: [
      'Riskli manevralarla zaman kazanmaya çalışmak',
      'Diğer sürücülere sinirlenerek gaza yüklenmek',
      'Derin nefes alıp güvenli sürüşe odaklanmak',
      'Telefonla konuşup dikkatini dağıtmak',
    ],
    answerIndex: 2,
    explanation:
      'Geç kalmak bir kazanın telafisi kadar önemli değildir; sakinleşip güvenli sürüşe odaklanmak stresin karar verme yeteneğini bozmasını önler.',
    whyWrong: [
      'Riskli manevralar ve gaza yüklenmek kaza olasılığını yükseltir.',
      'Telefonla uğraşmak stresli anda dikkati iyice azaltır.',
    ],
    objective: 'Zaman baskısı altında stresi yönetip güvenli sürüşü önceliklendirmeyi kavramak.',
    tags: ['stres', 'ofke-kontrolu', 'guvenli-surus'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-109',
    subject: 'adab',
    topic: 'saygi',
    difficulty: 'kolay',
    stem: 'Gece şehir içinde ilerlerken karşıdan araç geliyor. Uzun farlarla (uzun huzme) ilgili doğru davranış nedir?',
    options: [
      'Uzun farları açık tutup karşıya baskı yapmak',
      'Farları birkaç kez yakıp söndürmek',
      'Karşıdaki de yakıyorsa uzun farı açık bırakmak',
      'Karşı sürücüyü göz kamaşmasından korumak için kısa farlara geçmek',
    ],
    answerIndex: 3,
    explanation:
      'Karşıdan araç gelirken kısa farlara geçmek, diğer sürücünün gözünün kamaşmasını önleyen saygılı ve güvenli bir davranıştır.',
    whyWrong: [
      'Uzun farı açık tutmak karşı sürücüyü kör edip kaza riski yaratır.',
      'Farları yakıp söndürmek dikkat dağıtır; karşılık olarak uzun far açmak sorunu büyütür.',
    ],
    objective:
      'Gece sürüşünde karşı sürücüye saygı gösterip far kullanımını doğru ayarlamayı öğrenmek.',
    tags: ['saygi', 'gece-surus', 'far-kullanimi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-110',
    subject: 'adab',
    topic: 'yaya-saygi',
    difficulty: 'orta',
    stem: 'Yaya geçidinde beyaz bastonlu görme engelli bir birey karşıya geçmeyi bekliyor. En uygun davranış hangisidir?',
    options: [
      'Korna çalarak geçmesini istediğinizi belirtmek',
      'Aracı tamamen durdurup güvenle geçişini beklemek',
      'El işaretiyle geçmesini işaret etmek',
      'Yavaşça yanından geçip yola devam etmek',
    ],
    answerIndex: 1,
    explanation:
      'Görme engelli birey el veya ışık işaretini göremez; aracı tamamen durdurup sabırla beklemek en güvenli ve saygılı yaklaşımdır.',
    whyWrong: [
      'Korna görme engelli bireyi yönlendirmez, aksine ürkütür.',
      'El işareti algılanamaz; yanından geçmek ciddi tehlike doğurur.',
    ],
    objective: 'Engelli yayalara özel duyarlılık gösterip güvenli geçiş sağlamayı kavramak.',
    tags: ['yaya-saygi', 'engelli-birey', 'ozveri'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-111',
    subject: 'adab',
    topic: 'sorumluluk',
    difficulty: 'orta',
    stem: 'Park halindeyken bir aracın aynasına hafifçe çarptınız ve etrafta sahibi yok. Sorumluluk sahibi bir sürücü ne yapar?',
    options: [
      'İletişim bilgilerini yazıp araca not bırakmak',
      'Kimse görmediği için hızla oradan uzaklaşmak',
      'Hasar küçük diye görmezden gelmek',
      'Notu bırakmadan durumu unutmak',
    ],
    answerIndex: 0,
    explanation:
      'Verdiği zararın sorumluluğunu üstlenip iletişim bilgisi bırakmak dürüstlüğün ve trafik ahlakının gereğidir; kaçmak ise hukuki ve vicdani hatadır.',
    whyWrong: [
      'Uzaklaşmak veya görmezden gelmek çarpıp kaçma sayılır ve sorumsuzluktur.',
      'Zararı küçümsemek karşı tarafın hakkını yok saymaktır.',
    ],
    objective: 'Verilen zararın sorumluluğunu dürüstçe üstlenmeyi ilke edinmek.',
    tags: ['sorumluluk', 'durustluk', 'park'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-112',
    subject: 'adab',
    topic: 'paylasim',
    difficulty: 'orta',
    stem: 'Dar bir sokakta karşılıklı iki araç geldi ve sadece biri geçebilecek. Trafik adabına uygun çözüm nedir?',
    options: [
      'İlk gelen olduğunuzu düşünüp ısrarla ilerlemek',
      'Korna çalıp karşı sürücünün geri gitmesini beklemek',
      'İki araç da durup uzun süre inatlaşmak',
      'Uygun cep varsa geri çekilip karşı araca yol vermek',
    ],
    answerIndex: 3,
    explanation:
      'Yolu paylaşmak fedakârlık gerektirir; manevraya en uygun konumdaki sürücünün geri çekilip yol vermesi tıkanıklığı en hızlı ve nazik biçimde çözer.',
    whyWrong: [
      'Israrla ilerlemek ve inatlaşmak yolu tümüyle kilitler.',
      'Kornayla karşıyı zorlamak gerginliği artırır.',
    ],
    objective: 'Dar yollarda karşılıklı özveriyle yol paylaşımını yönetmeyi öğrenmek.',
    tags: ['paylasim', 'ozveri', 'dar-yol'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-113',
    subject: 'adab',
    topic: 'iletisim',
    difficulty: 'zor',
    stem: 'Yan şeritteki sürücünün fark etmediği bir tehlike (örneğin gevşemiş bir bagaj kapağı) var. Onu uyarmak için en uygun yol hangisidir?',
    options: [
      'Uzun uzun korna çalıp panik yaratmak',
      'Aracın önünü kesip durmaya zorlamak',
      'Hiç ilgilenmeyip yoluna devam etmek',
      'Sakin bir el işareti veya kısa kornayla nazikçe dikkat çekmek',
    ],
    answerIndex: 3,
    explanation:
      'İyi niyetli bir uyarı, karşı sürücüyü ürkütmeden yapılmalıdır; kısa korna veya sakin el işaretiyle dikkat çekmek hem faydalı hem de güvenlidir.',
    whyWrong: [
      'Uzun korna panik yaratıp yanlış tepkiye yol açabilir.',
      'Önünü kesmek tehlikeyi büyütür; ilgilenmemek ise sorumsuzluktur.',
    ],
    objective: 'Diğer sürücüleri tehlikeye karşı sakin ve doğru işaretlerle uyarmayı kavramak.',
    tags: ['iletisim', 'uyari', 'yardimlasma'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-114',
    subject: 'adab',
    topic: 'ofke',
    difficulty: 'zor',
    stem: 'Bir sürücü size korna çalıp bağırdı; öfkeniz kabardı. Yol öfkesini (road rage) yönetmenin en sağlıklı yolu nedir?',
    options: [
      'Aynı şekilde bağırıp karşılık vermek',
      'Peşine düşüp hesap sormak',
      'Tartışmaya girmeden sakinleşip yolunuza devam etmek',
      'Aracı yaklaştırıp gözdağı vermek',
    ],
    answerIndex: 2,
    explanation:
      'Öfkeye öfkeyle karşılık vermek çatışmayı tırmandırır; geri çekilip sakinleşmek hem sizin hem de çevrenizin güvenliğini korur ve olgunluğun göstergesidir.',
    whyWrong: [
      'Bağırıp karşılık vermek ve gözdağı çatışmayı büyütür.',
      'Peşine düşmek trafik terörüne ve kazaya dönüşebilir.',
    ],
    objective: 'Kışkırtma karşısında öfkeyi kontrol edip çatışmadan uzak durmayı öğrenmek.',
    tags: ['ofke-kontrolu', 'yol-ofkesi', 'sakinlik'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-115',
    subject: 'adab',
    topic: 'ozveri',
    difficulty: 'orta',
    stem: 'Okul servisinden inen çocuklar var ve servis dörtlülerini yakmış. Trafik adabına uygun davranış nedir?',
    options: [
      'Servisi hızla sollayıp geçmek',
      'Yavaşlayıp durarak çocukların güvenle geçmesini beklemek',
      'Korna çalıp servisin çekilmesini istemek',
      'Çocuklara aldırmadan yanından geçmek',
    ],
    answerIndex: 1,
    explanation:
      'Çocuklar trafikte ani ve öngörülemez hareket edebilir; okul servisi çevresinde yavaşlayıp beklemek, biraz gecikmeyi göze alan özverili ve güvenli bir davranıştır.',
    whyWrong: [
      'Hızla sollamak veya aldırmadan geçmek çocuklar için ölümcül risk taşır.',
      'Kornayla acele ettirmek tehlikeli aceleye yol açar.',
    ],
    objective:
      'Okul servisi ve çocukların bulunduğu ortamda ekstra özen ve özveri göstermeyi kavramak.',
    tags: ['ozveri', 'cocuk-guvenligi', 'okul-servisi'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-116',
    subject: 'adab',
    topic: 'saygi',
    difficulty: 'kolay',
    stem: 'Yerleşim yerinde gece geç saatte ilerliyorsunuz. Çevreye saygı açısından hangisi doğrudur?',
    options: [
      'Gürültüyü azaltıp gereksiz korna çalmaktan kaçınmak',
      'Yüksek sesli müzik ve gereksiz korna kullanmak',
      'Motoru gaza basarak yüksek devirde çalıştırmak',
      'Lastik cızırtısıyla hızlı kalkış yapmak',
    ],
    answerIndex: 0,
    explanation:
      'Trafik adabı yalnızca diğer sürücülere değil çevreye ve dinlenen insanlara da saygıyı içerir; gereksiz gürültüden kaçınmak bu duyarlılığın gereğidir.',
    whyWrong: [
      'Yüksek müzik ve gereksiz korna gürültü kirliliği yaratır.',
      'Yüksek devir ve lastik cızırtısı hem rahatsızlık verir hem de tehlikelidir.',
    ],
    objective: 'Çevreye ve topluma saygı çerçevesinde gürültü kirliliğini önlemeyi öğrenmek.',
    tags: ['saygi', 'cevre', 'gurultu'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-117',
    subject: 'adab',
    topic: 'gecis-ustunlugu',
    difficulty: 'zor',
    stem: 'Kırmızı ışıkta beklerken arkanızdan sirenli itfaiye aracı yaklaşıyor; ilerlemek geçişini kolaylaştıracak. Ne yapmalısınız?',
    options: [
      'Kırmızı olduğu için hiç kımıldamadan beklemek',
      'Panikleyip kavşağın ortasına dalmak',
      'Güvenliği sağlayarak yeterince ilerleyip ya da yana çekilip itfaiyeye yol açmak',
      'İtfaiyenin başka yoldan gitmesini beklemek',
    ],
    answerIndex: 2,
    explanation:
      'Geçiş üstünlüğü olan araca yol vermek için gerekli olduğunda, güvenliği sağlamak koşuluyla ölçülü şekilde ilerleyip yolu açmak yasal olarak beklenen doğru davranıştır.',
    whyWrong: [
      'Hiç kımıldamamak itfaiyenin geçişini engelleyip müdahaleyi geciktirir.',
      'Kavşağa kontrolsüz dalmak yan trafikle çarpışmaya yol açar.',
    ],
    objective: 'Kavşakta geçiş üstünlüğü olan araca güvenliği koruyarak yol vermeyi kavramak.',
    tags: ['gecis-ustunlugu', 'itfaiye', 'kavsak'],
    badge: 'official',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-118',
    subject: 'adab',
    topic: 'nezaket',
    difficulty: 'orta',
    stem: 'Bir yan yoldan ana yola çıkmaya çalışan araç uzun süredir bekliyor ve trafik yoğun. Nazik bir sürücü olarak ne yaparsınız?',
    options: [
      'Uygun bir anda yavaşlayıp o araca katılması için yer açmak',
      'Boşluk bırakmadan sıkışık ilerlemeye devam etmek',
      'Korna çalıp beklemesi gerektiğini hatırlatmak',
      'Aracın önünü kapatıp geçmesini engellemek',
    ],
    answerIndex: 0,
    explanation:
      'Yoğun trafikte küçük bir jestle yan yoldaki araca yer açmak, akışı bozmadan yapılan nazik ve dayanışmacı bir davranıştır.',
    whyWrong: [
      'Hiç yer açmamak bekleyeni mağdur eder ve tıkanıklığı uzatır.',
      'Kornayla veya önünü kapatarak dışlamak nezaketsizliktir.',
    ],
    objective: 'Trafikte küçük nezaket jestleriyle diğer sürücülere yer açmayı benimsemek.',
    tags: ['nezaket', 'paylasim', 'yol-verme'],
    badge: 'best',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-119',
    subject: 'adab',
    topic: 'sorumluluk',
    difficulty: 'zor',
    stem: 'Bir arkadaşınız sizi arabayla bırakmayı teklif ediyor ama alkol almış. Sorumlu bir tutum hangisidir?',
    options: [
      'Kısa mesafe diye teklifi kabul etmek',
      'Alkolün etkisini önemsemeyip binmek',
      'Hızlı gitmemesini söyleyip yola çıkmak',
      'Kibarca reddedip onun da direksiyona geçmemesini sağlamak',
    ],
    answerIndex: 3,
    explanation:
      'Alkollü sürücüye engel olmak hem onun hem başkalarının hayatını korur; teklifi reddedip alternatif ulaşım bulmak sorumlu ve vicdanlı bir davranıştır.',
    whyWrong: [
      'Kısa mesafe bile olsa alkollü araçla yolculuk ölümcül risk taşır.',
      'Yavaş gitmesini istemek alkolün refleks ve algı üzerindeki etkisini ortadan kaldırmaz.',
    ],
    objective: 'Alkollü sürüşe karşı sorumlu ve caydırıcı bir tutum geliştirmeyi kavramak.',
    tags: ['sorumluluk', 'alkol', 'guvenlik'],
    badge: 'safety',
    review: 'draft',
    sourceRef: SRC,
  },
  {
    id: 'adab-120',
    subject: 'adab',
    topic: 'empati',
    difficulty: 'orta',
    stem: 'Yağmurlu havada su birikintisinin yanındaki kaldırımda yayalar yürüyor. Empatik sürücü nasıl davranır?',
    options: [
      'Normal hızla geçip yayaların ıslanmasına aldırmamak',
      'Yavaşlayarak birikintiden su sıçratmamaya özen göstermek',
      'Su sıçratmayı eğlenceli bulup hızlanmak',
      'Kornaya basıp yayaların uzaklaşmasını beklemek',
    ],
    answerIndex: 1,
    explanation:
      'Kendini yayanın yerine koyan sürücü, birikinti yanında yavaşlayıp su sıçratmaktan kaçınır; bu küçük dikkat empatinin somut bir yansımasıdır.',
    whyWrong: [
      'Aldırmadan geçmek yayaları ıslatıp mağdur eder.',
      'Bilerek su sıçratmak saygısızlık ve kaba bir davranıştır.',
    ],
    objective: 'Yayaların konforunu gözeterek empatik ve düşünceli sürüş alışkanlığı kazanmak.',
    tags: ['empati', 'yaya-saygi', 'yagmur'],
    badge: 'instructor',
    review: 'draft',
    sourceRef: SRC,
  },
];
