// ÜRETİLMİŞ DOSYA — elle düzenlemeyin.
// Kaynak: apps/mobile/tool/extract_dash_icons.py (Evolution Faz E3).
//
// Gösterge paneli ikaz ışıkları — şeffaf zeminli WebP ikonlar.

/// İkaz ışığı kimliği → varlık yolu.
const Map<String, String> kDashAsset = {
  'abs': 'assets/dash/abs.webp',
  'adaptif-far': 'assets/dash/adaptif-far.webp',
  'adaptif-hiz': 'assets/dash/adaptif-hiz.webp',
  'aku-sarj': 'assets/dash/aku-sarj.webp',
  'aku-sicakligi': 'assets/dash/aku-sicakligi.webp',
  'alternator': 'assets/dash/alternator.webp',
  'arka-capraz': 'assets/dash/arka-capraz.webp',
  'arka-sis-farlari': 'assets/dash/arka-sis-farlari.webp',
  'auto-hold': 'assets/dash/auto-hold.webp',
  'bilgi-mesaji': 'assets/dash/bilgi-mesaji.webp',
  'cam-suyu': 'assets/dash/cam-suyu.webp',
  'carpisma-uyarisi': 'assets/dash/carpisma-uyarisi.webp',
  'cekis-kontrol': 'assets/dash/cekis-kontrol.webp',
  'diferansiyel-kilidi': 'assets/dash/diferansiyel-kilidi.webp',
  'dortlu-flasor': 'assets/dash/dortlu-flasor.webp',
  'dpf': 'assets/dash/dpf.webp',
  'eko-mod': 'assets/dash/eko-mod.webp',
  'el-freni': 'assets/dash/el-freni.webp',
  'emniyet-kemeri': 'assets/dash/emniyet-kemeri.webp',
  'esp': 'assets/dash/esp.webp',
  'far-seviye': 'assets/dash/far-seviye.webp',
  'fren-sistemi': 'assets/dash/fren-sistemi.webp',
  'fren-uyari': 'assets/dash/fren-uyari.webp',
  'gunduz-farlari': 'assets/dash/gunduz-farlari.webp',
  'guvenlik-alarmi': 'assets/dash/guvenlik-alarmi.webp',
  'hararet': 'assets/dash/hararet.webp',
  'hava-filtresi': 'assets/dash/hava-filtresi.webp',
  'hava-yastigi': 'assets/dash/hava-yastigi.webp',
  'hidrolik-direksiyon': 'assets/dash/hidrolik-direksiyon.webp',
  'hiz-sabitleyici': 'assets/dash/hiz-sabitleyici.webp',
  'ileri-mesafe': 'assets/dash/ileri-mesafe.webp',
  'immobilizer': 'assets/dash/immobilizer.webp',
  'kapi-acik': 'assets/dash/kapi-acik.webp',
  'kar-modu': 'assets/dash/kar-modu.webp',
  'katalitik': 'assets/dash/katalitik.webp',
  'kisa-far': 'assets/dash/kisa-far.webp',
  'kizdirma-bujisi': 'assets/dash/kizdirma-bujisi.webp',
  'kor-nokta': 'assets/dash/kor-nokta.webp',
  'lastik-basinci': 'assets/dash/lastik-basinci.webp',
  'motor-arizasi': 'assets/dash/motor-arizasi.webp',
  'on-sis-farlari': 'assets/dash/on-sis-farlari.webp',
  'park-lambasi': 'assets/dash/park-lambasi.webp',
  'park-sensoru': 'assets/dash/park-sensoru.webp',
  'romork-cekme': 'assets/dash/romork-cekme.webp',
  'sag-sinyal': 'assets/dash/sag-sinyal.webp',
  'sanziman-arizasi': 'assets/dash/sanziman-arizasi.webp',
  'sanziman-sicakligi': 'assets/dash/sanziman-sicakligi.webp',
  'serit-koruma': 'assets/dash/serit-koruma.webp',
  'serit-takip': 'assets/dash/serit-takip.webp',
  'servis-zamani': 'assets/dash/servis-zamani.webp',
  'sogutma-suyu': 'assets/dash/sogutma-suyu.webp',
  'sol-sinyal': 'assets/dash/sol-sinyal.webp',
  'spor-mod': 'assets/dash/spor-mod.webp',
  'start-stop': 'assets/dash/start-stop.webp',
  'start-stop-kapali': 'assets/dash/start-stop-kapali.webp',
  'uzun-far': 'assets/dash/uzun-far.webp',
  'yag-basinci': 'assets/dash/yag-basinci.webp',
  'yag-seviyesi': 'assets/dash/yag-seviyesi.webp',
  'yakit-az': 'assets/dash/yakit-az.webp',
  'yokus-inis': 'assets/dash/yokus-inis.webp',
};

/// Bu ikaz ışığının ikonu var mı?
String? dashAsset(String id) => kDashAsset[id];
