// ÜRETİLMİŞ DOSYA — elle düzenlemeyin.
// Kaynak: apps/mobile/tool/extract_mech_assets.py (Evolution Faz E2).
//
// Mekanik görsel kütüphanesi: araç sistemleri, kaput altı, kabin kumandaları, bagaj
// ekipmanları; B / A / D sınıfları. Şeffaf zeminli WebP.

/// Parça kimliği → varlık yolu.
const Map<String, String> kMechAsset = {
  'ac-button': 'assets/mech/ac-button.webp',
  'air-filter-box': 'assets/mech/air-filter-box.webp',
  'battery-12v': 'assets/mech/battery-12v.webp',
  'blank-panel': 'assets/mech/blank-panel.webp',
  'boot-release-button': 'assets/mech/boot-release-button.webp',
  'brake-fluid-reservoir': 'assets/mech/brake-fluid-reservoir.webp',
  'bus-air-gauges': 'assets/mech/bus-air-gauges.webp',
  'bus-air-suspension': 'assets/mech/bus-air-suspension.webp',
  'bus-air-tank': 'assets/mech/bus-air-tank.webp',
  'bus-battery-24v': 'assets/mech/bus-battery-24v.webp',
  'bus-battery-isolator': 'assets/mech/bus-battery-isolator.webp',
  'bus-brake-valves': 'assets/mech/bus-brake-valves.webp',
  'bus-coolant-reservoir': 'assets/mech/bus-coolant-reservoir.webp',
  'bus-dipstick': 'assets/mech/bus-dipstick.webp',
  'bus-door-panel': 'assets/mech/bus-door-panel.webp',
  'bus-emergency-door-release': 'assets/mech/bus-emergency-door-release.webp',
  'bus-emergency-hammer': 'assets/mech/bus-emergency-hammer.webp',
  'bus-exhaust-brake-switch': 'assets/mech/bus-exhaust-brake-switch.webp',
  'bus-fire-extinguisher': 'assets/mech/bus-fire-extinguisher.webp',
  'bus-first-aid-kit': 'assets/mech/bus-first-aid-kit.webp',
  'bus-retarder-stalk': 'assets/mech/bus-retarder-stalk.webp',
  'bus-speed-knob': 'assets/mech/bus-speed-knob.webp',
  'bus-steering-wheel': 'assets/mech/bus-steering-wheel.webp',
  'bus-tachograph': 'assets/mech/bus-tachograph.webp',
  'bus-twin-wheel': 'assets/mech/bus-twin-wheel.webp',
  'bus-wheel-chock': 'assets/mech/bus-wheel-chock.webp',
  'central-lock-button': 'assets/mech/central-lock-button.webp',
  'central-unlock-button': 'assets/mech/central-unlock-button.webp',
  'climate-fan-knob': 'assets/mech/climate-fan-knob.webp',
  'climate-flow-knob': 'assets/mech/climate-flow-knob.webp',
  'climate-maxac-knob': 'assets/mech/climate-maxac-knob.webp',
  'climate-recirc-knob': 'assets/mech/climate-recirc-knob.webp',
  'climate-temp-knob': 'assets/mech/climate-temp-knob.webp',
  'coolant-tank': 'assets/mech/coolant-tank.webp',
  'dipstick-max': 'assets/mech/dipstick-max.webp',
  'dipstick-oil': 'assets/mech/dipstick-oil.webp',
  'engine-block': 'assets/mech/engine-block.webp',
  'engine-start-stop': 'assets/mech/engine-start-stop.webp',
  'engine-v6': 'assets/mech/engine-v6.webp',
  'esp-off-button': 'assets/mech/esp-off-button.webp',
  'fire-extinguisher': 'assets/mech/fire-extinguisher.webp',
  'first-aid-kit': 'assets/mech/first-aid-kit.webp',
  'front-defrost-button': 'assets/mech/front-defrost-button.webp',
  'fuel-flap-button': 'assets/mech/fuel-flap-button.webp',
  'fuse-box': 'assets/mech/fuse-box.webp',
  'hazard-button-rocker': 'assets/mech/hazard-button-rocker.webp',
  'hazard-button-round': 'assets/mech/hazard-button-round.webp',
  'headlight-knob-auto': 'assets/mech/headlight-knob-auto.webp',
  'headlight-knob-fog': 'assets/mech/headlight-knob-fog.webp',
  'headlight-knob-manual': 'assets/mech/headlight-knob-manual.webp',
  'maxac-button': 'assets/mech/maxac-button.webp',
  'mirror-adjust-knob': 'assets/mech/mirror-adjust-knob.webp',
  'mirror-fold-switch': 'assets/mech/mirror-fold-switch.webp',
  'moto-battery': 'assets/mech/moto-battery.webp',
  'moto-brake-lever': 'assets/mech/moto-brake-lever.webp',
  'moto-brake-pedal': 'assets/mech/moto-brake-pedal.webp',
  'moto-brake-reservoir': 'assets/mech/moto-brake-reservoir.webp',
  'moto-chain': 'assets/mech/moto-chain.webp',
  'moto-cluster': 'assets/mech/moto-cluster.webp',
  'moto-clutch-lever': 'assets/mech/moto-clutch-lever.webp',
  'moto-exhaust': 'assets/mech/moto-exhaust.webp',
  'moto-fork': 'assets/mech/moto-fork.webp',
  'moto-front-wheel': 'assets/mech/moto-front-wheel.webp',
  'moto-gear-lever': 'assets/mech/moto-gear-lever.webp',
  'moto-gloves': 'assets/mech/moto-gloves.webp',
  'moto-helmet': 'assets/mech/moto-helmet.webp',
  'moto-hiviz-vest': 'assets/mech/moto-hiviz-vest.webp',
  'moto-horn-switch': 'assets/mech/moto-horn-switch.webp',
  'moto-ignition': 'assets/mech/moto-ignition.webp',
  'moto-kill-switch': 'assets/mech/moto-kill-switch.webp',
  'moto-knee-guard': 'assets/mech/moto-knee-guard.webp',
  'moto-mirror': 'assets/mech/moto-mirror.webp',
  'moto-oil-sight-glass': 'assets/mech/moto-oil-sight-glass.webp',
  'moto-start-switch': 'assets/mech/moto-start-switch.webp',
  'moto-turn-switch': 'assets/mech/moto-turn-switch.webp',
  'oil-filler-cap': 'assets/mech/oil-filler-cap.webp',
  'park-sensor-button': 'assets/mech/park-sensor-button.webp',
  'radiator': 'assets/mech/radiator.webp',
  'rear-defrost-button': 'assets/mech/rear-defrost-button.webp',
  'rear-defrost-knob': 'assets/mech/rear-defrost-knob.webp',
  'rear-fog-slider': 'assets/mech/rear-fog-slider.webp',
  'scissor-jack': 'assets/mech/scissor-jack.webp',
  'seat-adjust-switch': 'assets/mech/seat-adjust-switch.webp',
  'seat-back-heater-button': 'assets/mech/seat-back-heater-button.webp',
  'seat-heater-button': 'assets/mech/seat-heater-button.webp',
  'socket-12v': 'assets/mech/socket-12v.webp',
  'spare-wheel': 'assets/mech/spare-wheel.webp',
  'start-stop-off-button': 'assets/mech/start-stop-off-button.webp',
  'steering-heater-button': 'assets/mech/steering-heater-button.webp',
  'tow-eye': 'assets/mech/tow-eye.webp',
  'usb-a-socket': 'assets/mech/usb-a-socket.webp',
  'usb-c-socket': 'assets/mech/usb-c-socket.webp',
  'usb-charge-socket': 'assets/mech/usb-charge-socket.webp',
  'usb-dual-socket': 'assets/mech/usb-dual-socket.webp',
  'warning-triangle': 'assets/mech/warning-triangle.webp',
  'washer-cap': 'assets/mech/washer-cap.webp',
  'wheel-chock': 'assets/mech/wheel-chock.webp',
  'wheel-wrench': 'assets/mech/wheel-wrench.webp',
  'wiper-stalk-int': 'assets/mech/wiper-stalk-int.webp',
  'wiper-stalk-rear': 'assets/mech/wiper-stalk-rear.webp',
  'wiper-stalk-speed': 'assets/mech/wiper-stalk-speed.webp',
};

/// Bu parçanın görseli var mı?
String? mechAsset(String id) => kMechAsset[id];
