// ÜRETİLMİŞ DOSYA — elle düzenlemeyin.
// Kaynak: apps/mobile/tool/extract_official_signs.py (Evolution Faz E1).
//
// Uygulamadaki trafik işareti → RESMÎ levha vektörü (KGM 2020 / İBB standart posterleri).
// Burada olmayan işaretler parametrik `TrafficSignView` çizicisiyle çizilir:
// sayı-parametrik levhalar (hız/ağırlık/mesafe), resmî karşılığı olmayanlar ve
// kaynak posterde vektör olarak temiz çıkarılamayan birkaç levha.

/// İşaret id → `assets/signs/<kod>.svg`.
const Map<String, String> kOfficialSignAsset = {
  'agirlik-siniri': 'assets/signs/tt-24.svg',
  'akaryakit': 'assets/signs/b-26.svg',
  'aks-yuku-siniri': 'assets/signs/tt-23.svg',
  'alcak-ucus': 'assets/signs/t-17.svg',
  'ana-yol': 'assets/signs/b-38.svg',
  'ana-yol-sonu': 'assets/signs/b-39.svg',
  'anayol-tali-kavsak': 'assets/signs/t-22a.svg',
  'asgari-hiz-sonu': 'assets/signs/tt-41b.svg',
  'at-arabasi-giremez': 'assets/signs/tt-13.svg',
  'bisiklet-gecebilir': 'assets/signs/t-13.svg',
  'bisiklet-giremez': 'assets/signs/tt-8.svg',
  'bisiklet-yolu': 'assets/signs/tt-38a.svg',
  'cesme': 'assets/signs/b-30.svg',
  'cikmaz-yol': 'assets/signs/b-17.svg',
  'dar-gecit-onceligi-sende': 'assets/signs/b-37.svg',
  'dar-gecit-oncelik': 'assets/signs/tt-3.svg',
  'deniz-kiyisi': 'assets/signs/t-6.svg',
  'devamli-viraj': 'assets/signs/t-2a.svg',
  'dikkat': 'assets/signs/t-20.svg',
  'donel-kavsak-yaklasim': 'assets/signs/t-24.svg',
  'donel-mecburi': 'assets/signs/tt-37.svg',
  'donus-yasak-sag': 'assets/signs/tt-26a.svg',
  'donus-yasak-sol': 'assets/signs/tt-26b.svg',
  'dur': 'assets/signs/tt-2.svg',
  'duraklama-yasak': 'assets/signs/p-2.svg',
  'dusen-kaya': 'assets/signs/t-10.svg',
  'egimli-inis': 'assets/signs/t-3a.svg',
  'ehli-hayvan': 'assets/signs/t-14a.svg',
  'el-arabasi-giremez': 'assets/signs/tt-14.svg',
  'gecici-iki-yonlu': 'assets/signs/t-19.svg',
  'genislik-siniri': 'assets/signs/tt-20.svg',
  'gevsek-malzeme': 'assets/signs/t-9.svg',
  'gizli-buzlanma': 'assets/signs/t-37.svg',
  'gumruk-dur': 'assets/signs/tt-31.svg',
  'hastane': 'assets/signs/b-15.svg',
  'hemzemin-gecit': 'assets/signs/t-25.svg',
  'iki-yonlu-trafik': 'assets/signs/t-19.svg',
  'ileri-mecburi': 'assets/signs/tt-35c.svg',
  'ilk-yardim': 'assets/signs/b-23.svg',
  'is-makinesi-cikabilir': 'assets/signs/t-15.svg',
  'isikli-isaret-yaklasim': 'assets/signs/t-16.svg',
  'kamp-yeri': 'assets/signs/b-33.svg',
  'kamyon-giremez': 'assets/signs/tt-10a.svg',
  'kasisli-yol': 'assets/signs/t-7.svg',
  'kontrolsuz-kavsak': 'assets/signs/t-21.svg',
  'motosiklet-giremez': 'assets/signs/tt-7.svg',
  'okul-gecidi': 'assets/signs/t-12.svg',
  'okul-gecidi-bilgi': 'assets/signs/b-14b.svg',
  'otel': 'assets/signs/b-27.svg',
  'otobus-duragi': 'assets/signs/b-22.svg',
  'otobus-giremez': 'assets/signs/tt-10b.svg',
  'otomobil-giremez': 'assets/signs/tt-6.svg',
  'otoyol-baslangic': 'assets/signs/b-18.svg',
  'otoyol-sonu': 'assets/signs/b-19.svg',
  'park-serbest': 'assets/signs/p-3a.svg',
  'park-yeri-bilgi': 'assets/signs/p-3a.svg',
  'polis': 'assets/signs/b-41.svg',
  'saga-mecburi': 'assets/signs/tt-35a.svg',
  'sagdan-daralma': 'assets/signs/t-4b.svg',
  'sagdan-gidin': 'assets/signs/tt-36a.svg',
  'serit-daralmasi-gecici': 'assets/signs/t-4a.svg',
  'sola-mecburi': 'assets/signs/tt-35b.svg',
  'soldan-daralma': 'assets/signs/t-4c.svg',
  'sollama-yasagi-sonu': 'assets/signs/tt-34a.svg',
  'sollama-yasak': 'assets/signs/tt-27.svg',
  'takip-mesafesi': 'assets/signs/tt-25.svg',
  'tamirhane': 'assets/signs/b-24.svg',
  'tasit-giremez': 'assets/signs/tt-5.svg',
  'tehlikeli-viraj-sol': 'assets/signs/t-1b.svg',
  'tek-yon': 'assets/signs/b-16a.svg',
  'telefon': 'assets/signs/b-25.svg',
  'traktor-giremez': 'assets/signs/tt-15.svg',
  'tramvay-duragi': 'assets/signs/b-59.svg',
  'tramvay-hatti': 'assets/signs/t-39.svg',
  'tumsek': 'assets/signs/t-7.svg',
  'u-donusu-yasak': 'assets/signs/tt-26c.svg',
  'uzunluk-siniri': 'assets/signs/tt-22.svg',
  'yandan-ruzgar': 'assets/signs/t-18.svg',
  'yaya-gecidi-bilgi': 'assets/signs/b-14a.svg',
  'yaya-geciti-tehlike': 'assets/signs/t-11.svg',
  'yaya-giremez': 'assets/signs/tt-12.svg',
  'yaya-yolu': 'assets/signs/tt-39a.svg',
  'yol-calismasi': 'assets/signs/t-15.svg',
  'yol-daralmasi': 'assets/signs/t-4a.svg',
  'yol-ver': 'assets/signs/tt-1.svg',
  'zincir-mecburi': 'assets/signs/tt-42a.svg',
};

/// Bu işaretin resmî levha vektörü var mı?
String? officialSignAsset(String signId) => kOfficialSignAsset[signId];
